### ISSUE TITLE
flake: "Podman commit" times out during 'podman rm -fa' cleanup

### ISSUE THREAD

**Issue by wking** [containers/libpod#1042]
In a recent master build, we [have][1]:

```
• Failure in Spec Teardown (AfterEach) [99.227 seconds]
Podman commit
/go/src/github.com/projectatomic/libpod/test/e2e/commit_test.go:10
  podman commit container with change flag [AfterEach]
  /go/src/github.com/projectatomic/libpod/test/e2e/commit_test.go:76
  Timed out after 90.000s.
  Expected process to exit.  It did not.
  /go/src/github.com/projectatomic/libpod/test/e2e/libpod_suite_test.go:220
  Full Stack Trace
  	/go/src/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:48 +0x62
  github.com/onsi/gomega/gexec.(*Session).Wait(0xc42080fd70, 0xc42094cfe8, 0x1, 0x1, 0xc420844428)
  	/go/src/github.com/onsi/gomega/gexec/session.go:142 +0xc6
  github.com/projectatomic/libpod/test/e2e.(*PodmanTest).Cleanup(0xc4200b57c0)
  	/go/src/github.com/projectatomic/libpod/test/e2e/libpod_suite_test.go:220 +0xc8
  github.com/projectatomic/libpod/test/e2e.glob..func2.2()
  	/go/src/github.com/projectatomic/libpod/test/e2e/commit_test.go:27 +0x2a
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4200bf1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/src/github.com/projectatomic/libpod/test/e2e/libpod_suite_test.go:97 +0x13f
  testing.tRunner(0xc4204ca0f0, 0xca4188)
  	/usr/local/go/src/testing/testing.go:777 +0xd0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:824 +0x2e0
```

This is similar to #1040, but this time the operation that is timing out is [the `podman rm -fa`][2] call.  Does anyone have ideas about why that would be taking so long?

[1]: https://travis-ci.org/projectatomic/libpod/jobs/399315452
[2]: https://github.com/projectatomic/libpod/blob/767b3ddc433fd57f461fa9866e3e4d47399a6519/test/e2e/libpod_suite_test.go#L219

**Comment by mheon** [comment]
@wking I suspect this is CGroup cleanup. I've seen cases where trying to open the CGroups for a container so they may be deleted will hang for an indeterminate amount of time. It seems to only happen with the CGroups in question (or at least parts of them) have been removed, but there doesn't seem to be a real consistency to it beyond that.

**Comment by mheon** [comment]
I suspect that the container we are attempting to commit stops, the `cleanupCgroups()` call fires in the post-stop cleanup command, is partially successful at removing some CGroups, and then fails because other CGroups are still in use by conmon & the cleanup command. This then triggers the unknown CGroups bug I'm talking about when we subsequently attempt to remove the container and some CGroups are missing.

**Comment by mheon** [comment]
This may have been fixed by #1051 but let's leave it open for a few days to see if the flakes keep happening

**Comment by rhatdan** [comment]
Flakes do not seem to be happening now, I will close this issue, reopen if the flakes come back.

**Comment by rhatdan** [comment]
Yes

**Comment by mheon** [comment]
Damn, I was really hoping this was just the CGroup issue.

I don't think we've seen this on our CI since then.

**Comment by baude** [comment]
I don't believe we are seeing this flake anymore, closing ... can re-open if appears
