### ISSUE TITLE
flake: "Error determining manifest MIME type" on registry errors

### ISSUE THREAD

**Issue by wking** [containers/libpod#1045]
In a recent FAH28 [run][1]:

```
ginkgo -v -cover -flakeAttempts 3 -progress -trace -noColor test/e2e/.
Running Suite: Libpod Suite
===========================
Random Seed: 1530652357
Will run 316 of 316 specs

Caching alpine...
Caching busybox...
Caching registry.fedoraproject.org/fedora-minimal:latest...
"Error determining manifest MIME type for docker://registry.fedoraproject.org/fedora-minimal:latest: pinging docker registry returned: error pinging registry registry.fedoraproject.org, response code 503"

Ginkgo ran 1 suite in 6.715017037s
Test Suite Failed
make: *** [Makefile:158: localintegration] Error 1
```

That's on a 503.  We've seen this [back in February for auth issues][2] and [for not-found errors][3].

The error message is a bit strange; it seems like the MIME-type detection is just a canary for "we're having HTTP-or-lower-level trouble working with that registry".  There's a similar CRI-O issue in kubernetes-incubator/cri-o#1667.  As far as CI reliability goes, we probably want to retry those fetches (possibly from fallback registries) before giving up in a given CI run.

[1]: https://s3.amazonaws.com/aos-ci/ghprb/projectatomic/libpod/4b2a547e285b123e4bfbf3fd03fa1c3adab4abc3.0.1530651672275164588/output.log
[2]: https://github.com/projectatomic/libpod/pull/289#issuecomment-362900369
[3]: https://github.com/projectatomic/libpod/issues/336

**Comment by baude** [comment]
I don't believe we are seeing this flake anymore, closing ... can re-open if appears
