### ISSUE TITLE
Questions about naming of pulled images

### ISSUE THREAD

**Issue by mtrmac** [containers/libpod#1139]
(From #1112.)

AFAICT the outcome of #1085, apart from pulling the right image, which is clearly correct, is that pulled _name_`@sha256:`_digest_ images are named in the storage as _name_`:none` (where `none` is an actual tag string, not “missing”, and the digest not recorded). (I can now confidently refactor the code to do this inside the `imageParts` abstraction without breaking anything, but that exposes how irregular the code doing this is.) 
  - Is using the explicit `none` tag  Is that intentional? If so, why is it necessary? 
  - Is dropping the digest and not recording it in the storage intentional? If so, why is it necessary? (Looking at `Image.RepoDigests`, it forms a series of _name_`@`_digest_ values, all with the same `Image.image.Digest` value — but a single image (single image ID == config digest) can exist with multiple different manifest digests. Shouldn’t the original values be recorded when pulling, and reproduced in `RepoDigests` in `podman inspect`?)

Everyone has been deferring this to @baude .

**Comment by mtrmac** [comment]
Also maybe @nalind for the questions about recording original pulled digests in c/storage.

**Comment by baude** [comment]
The none tag being used is more or less what docker shows.  Realistically, I think the tag is supposed to be blank.  In docker, iirc, if the tag is blank, then it renders <none> in output.  I can relook at this upon return from PTO if you like ... the none for now however is on purpose.

The second point you raise looks like a bug.  Can you paste an example of whats missing/what should be there and I will look to fix it.

**Comment by mtrmac** [comment]
(Enjoy your PTO; this can absolutely wait.)

> The none tag being used is more or less what docker shows.

Where?

> Realistically, I think the tag is supposed to be blank. In docker, iirc, if the tag is blank, then it renders in output. I can relook at this upon return from PTO if you like ... the none for now however is on purpose.

I suspect that this is strongly related to the second point actually - e.g. Docker, when pulling an image, always records a digest reference (whether pulling by tag, digest, or “all tags”), but records a tagged reference _only if a tag is known_ (pulling by tag, or “all tags”). It’s not that a tag is “blank” when pulling by digest (which would still be different from having a `none` string indistinguishable from an actual `:none` tag), it’s that there is no tagged version of the name recorded at all.

> The second point you raise looks like a bug. Can you paste an example of whats missing/what should be there and I will look to fix it.

- E.g. see the “@digest” cases in  `TestRefNamesFromPossiblyUnqualifiedName`, the digest the user used to pull the image is not recorded by `libpod` at all; and it is not recorded by `storage.Image` either AFAICS, because `storage.Digest` (and `storage.Image.BigDataDigests[storage.ImageDigestBigDataKey]`) can only store one value.  (@nalind am I missing anything?) That is a problem because… 
- … a single image (single _config_ digest) can be pulled many times from many places, with many different _manifest_ digests (e.g. depending on how the compressed version of the layers changes as the compression implementation changes).  Docker records every single name@digest reference which was _actually_ used, and shows them all in `docker inspect`’s `RepoDigests`. As described above, `Image.RepoDigests` tries to compose similar results without actually having the name@digest pairs (and may thus return name@digest references which never existed at the registries).

**Comment by vrothberg** [comment]
@baude @mtrmac @nalind, ping.

**Comment by rhatdan** [comment]
@baude @mtrmac @nalind Lets revit this,  Is this worth having a bluejeans session to discuss?

**Comment by baude** [comment]
sure, anytime

**Comment by rhatdan** [comment]
@mtrmac @baude Whats going on with this issue?

**Comment by rhatdan** [comment]
@baude What is the state of this Issue now?

**Comment by mheon** [comment]
Per @mtrmac we have removed most if not all cases of the literal `:none` tag.
I think we're good to close.

**Comment by mheon** [comment]
(Our matching logic for ImageParts is still a problem, but we can replace that at a later date)
