### ISSUE TITLE
regression: podman run: exit status is 0 after signal

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1221]
Possibly a zombie of #389; I'm filing a new issue because that was closed a long time ago, hence this may actually be a new cause for the same behavior.

In window 1:
```
# podman run --rm --name foo fedora sleep 60;echo $?
```
In a second window: `podman kill foo` or `podman stop foo`. Back to the first window, the exit status is `0` (expected: 137).

podman-0.8.1-1.git6b4ab2a.fc28

**Comment by mheon** [comment]
I feel like we might be having Conmon issues in the new 0.8.1 builds - will take a look after lunch

**Comment by edsantiago** [comment]
Yeah, it's starting to look like conmon. I'm seeing old problems with `podman attach` too (#580)

**Comment by mheon** [comment]
This is a packaging issue - the latest build of Podman for F27 looks to have dropped its built-in `conmon` to use the (far too old) system `conmon`

**Comment by edsantiago** [comment]
^^^ F28, not F27: f27 actually still includes conmon:

```
f27]# rpm -ql podman|grep conm
/usr/libexec/podman/conmon
```

```
f28# rpm -ql podman|grep conm
f28#
```

f27 has its own issues.

**Comment by mheon** [comment]
What I'm getting out of this is that our builds are really broken right now.

**Comment by TomSweeneyRedHat** [comment]
FWIW, I concur about conmon on F27 0.8.1.  In case it helps, it is failing in ./libpod/oci.go, 

```
 // Wait to get container pid from conmon
        type syncStruct struct {
                si  *syncInfo
                err error
        }
        ch := make(chan syncStruct)
        go func() {
                var si *syncInfo
                if err = json.NewDecoder(parentPipe).Decode(&si); err != nil {
                        ch <- syncStruct{err: err}
                        return
                }
                ch <- syncStruct{si: si}
        }()

        select {
        case ss := <-ch:
                if ss.err != nil {
                        return errors.Wrapf(ss.err, "error reading container (probably exited) json message")
                }
```
It's ss.err that is getting an EOF error during the container creation process.  Not sure of the whys, but I'd bet @baude 's hunch on the bad version of conman is what's biting Podman on F27.

**Comment by edsantiago** [comment]
I couldn't find that build in any repo including updates-testing; but I downloaded conmon from [koji](https://koji.fedoraproject.org/koji/buildinfo?buildID=1104940). Looks good. Someone please remember to update the conmon dependency in the podman specfile.

**Comment by mheon** [comment]
This should be fixed on our end - we're back on a good conmon version
@edsantiago Feel free to reopen if it's not
