### ISSUE TITLE
podman ps: status always reports "Less than a second ago" for Exited containers

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1223]
podman ps is always reporting exited containers as having just completed:
```
# podman run fedora date;sleep 10;podman ps -a
Mon Aug  6 16:39:41 UTC 2018
CONTAINER ID   IMAGE                             COMMAND   CREATED          STATUS                              PORTS   NAMES
d78a17bd81ab   docker.io/library/fedora:latest   date      11 seconds ago   Exited (0) Less than a second ago           priceless_payne
```
10 is just an example; even minutes later it still says 'Exited (0) Less than a second ago`.

podman-0.8.1-1.git6b4ab2a.fc28

**Comment by mheon** [comment]
Probably also conmon, since it creates the exit files

**Comment by mheon** [comment]
Nevermind - seemingly unrelated to conmon

**Comment by mheon** [comment]
Actual exited time is shown in `podman inspect` and seems correct. This seems to just be how `podman ps` displays output.

**Comment by mheon** [comment]
This one's not conmon - we're not actually calculating exited time properly for both JSON and normal PS output

**Comment by mheon** [comment]
Opened #1228 to fix

**Comment by vrothberg** [comment]
Closing as the issue has been fixed with https://github.com/containers/libpod/pull/1228.
