### ISSUE TITLE
unprivileged users should be able to retrieve 'podman version' and 'podman info'

### ISSUE THREAD

**Issue by miabbott** [containers/libpod#1263]
/kind feature

I think users should be able to retrieve these pieces of information with out escalating privileges.  Currently, they fail like so:

```
$ whoami
miabbott
$ id -u miabbott
1000
$ podman version
ERRO[0000] No subuid ranges found for user ""           
$ podman info
ERRO[0000] No subuid ranges found for user ""
```

I could buy the argument that maybe `podman info` should require escalated privileges, but I think it is hard to make the same argument for version information.  (Note: `/usr/bin/docker version` will report *some* version information without escalated privileges, but `/usr/bin/docker info` does not work without escalated privileges)

**Comment by mheon** [comment]
Version shouldn't require this. `podman info` does (it needs to create a full runtime to obtain all the information it reports).

@giuseppe Can we disable rootless code if we're only executing `podman version` or `podman --version`?

**Comment by giuseppe** [comment]
yes currently we are doing that in any case.  We will probably need to pre-parse the CLI args for the "version" case, as for the other commands I think we need to get into the user namespace

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/1268
