### ISSUE TITLE
Constructing container environments using OpenShift descriptions using podman?

### ISSUE THREAD

**Issue by Conan-Kudo** [containers/libpod#1291]
/kind feature

**Description**

I'd like to be able to run and test batches of containers defined with the OpenShift YAML/JSON description locally. As it is now, it's not possible to test these without running a full OpenShift system, which makes it difficult to have a consistent description from development to production.

This would be kind of a superset of the `docker-compose.yml` issue (#746), leveraging OpenShift descriptions with content for building the containers, setting them up, and running the service.

The advantage of this is that people can easily develop correct descriptions for setting up OpenShift pods locally that transfer well to a proper OpenShift environment for production, which would only help in increasing adoption of OpenShift as a production environment platform.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Developer workstations running Fedora with podman and buildah installed
* GitLab CI runners with Docker container (of Fedora with buildah + podman)

**Comment by TomSweeneyRedHat** [comment]
FWIW, @mheon discussed this at some length over IRC with the requestor @Conan-Kudo .  I think the gist of the conversation was that this would be a good change for @Conan-Kudo but @mheon thought it would also aid the transition of Podman to CRI-O/OpenShift.  Still digging/thinking to do on it.

**Comment by mheon** [comment]
I think it's potentially beneficial towards CRI-O integration, but also it's a cool direction to go towards if we're already thinking of something similar to compose.

**Comment by rhatdan** [comment]
Some of @baude  podman containre play code is implementding

**Comment by rhatdan** [comment]
Please use podman play kube
