### ISSUE TITLE
Typo in podman-build man page

### ISSUE THREAD

**Issue by alcir** [containers/libpod#1326]
/kind bug

**Description**

Here https://github.com/containers/libpod/blob/master/docs/podman-build.1.md and in the podman-build man page, --ulimit usage is this 
<pre>
--ulimit=type<b>:</b>soft-limit[:hard-limit]
</pre>
while in the subsequent example, and actually using the option in the command line, the right syntax should be 
<pre>
--ulimit=type<b>=</b>soft-limit[:hard-limit]
</pre>

**Comment by mheon** [comment]
Closed via #1327
