### ISSUE TITLE
[Question] regarding integration of cri-o & libpod

### ISSUE THREAD

**Issue by kunalkushwaha** [containers/libpod#1333]
**Description**
In podman roadmap, there is plan to integrate libpod & cri-o.
> Integrate libpod into CRI-O to replace its existing container management backend

How this integration is planned?
- Will cri-o be using libpod as library or as separate binary/service(acess via varlink) 
- Does this mean cri-o will become be more like CRI-shim for podman?
- what all is left to achieve this? 
_(An issue with list of TODOs items, may help other to understand & conbtribute)_ 

**Steps to reproduce the issue:**
**Describe the results you received:**
**Describe the results you expected:**
**Additional information you deem important (e.g. issue happens only occasionally):**
**Output of `podman version`:**
**Output of `podman info`:**
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
The plan is to get CRI-O using libpod as a library.

@baude Opened a PR a month or so ago to start moving CRI-O to libpod for image management.
@vrothberg recently got pkg/apparmor from libpod integrated to CRI-O.  

We put some of this work on hold, to be able to get podman to 1.0 status.  But we plan on getting back to it very soon.

I think creating a TODO list is a good idea.

The biggest concern over this merger is going to be performance and stability.  CRI-O has much larger performance requirements then podman.

@mrunalp mheon WDYT?

**Comment by kunalkushwaha** [comment]
> The biggest concern over this merger is going to be performance and stability. CRI-O has much larger performance requirements then podman.

Is there any performance benchmarking done for podman?  for cri-o there are already with cri-tools.

**Comment by rhatdan** [comment]
We have recently asked the Performance team at Red Hat to look at Podman.  @baude has done some testing but mainly around processing of podman ps commands.

**Comment by mheon** [comment]
The major obstacles to integration code-wise have mostly been removed. The pending SHM locking PR is one of the major remaining ones. We also need to rewrite `podman exec` to use `conmon` instead of directly executing `runc`, and investigate multiple OCI runtimes within the same libpod instace to provide CRI-O's trusted/untrusted runtime model used by kata containers, but we can move forward on integration without having those ready.

**Comment by mrunalp** [comment]
:+1: to creating a todo list. We can start with blocking this behind a tag and then graduating it once the performance matches or exceeds CRI-O performance.

**Comment by vrothberg** [comment]
I think the initial question has been answered, closing.
