### ISSUE TITLE
Feature Request: Support environment variable for authentication file

### ISSUE THREAD

**Issue by frezbo** [containers/libpod#1340]
When running tools  like podman in a CI system like Jenkins, we would love to pass folder specific credentials to push to `dev`, `prod` repositories and not expose the credentials for the user running Jenkins. Docker already supports this with the `DOCKER_CONFIG` environment variable

Proposal being and registry push/pull operations tries to use an environment variable named something like `REGISTRY_AUTH_FILE` (open to better names) and use that for primary operations otherwise fallback to the default `auth.json`

**Comment by mheon** [comment]
This does not sound that difficult.
@umohnani8 @rhatdan WDYT?

**Comment by TomSweeneyRedHat** [comment]
For `podman pull/push/build` and maybe more commands that I'm forgetting, we have an --authfile option that points to the directory that `podman login` has dropped the config.json authentication file into.  Can you use this or are you looking for other credentials?  If so, might be a short term solution, but we should be able to add an environment variable too if that helps.

**Comment by frezbo** [comment]
I could live with the `authfile` option for now, let me explain a use case:
For dev builds it uses a credentials accessible for the dev builds only and the path to file gets exported only for that particular build, same with other environments too.  So having an environmental variable helps prevent config leak and ability to use different credentials per environment. Moreover an environment variable is much easier to use and prevents passing extra options
