### ISSUE TITLE
Question: Websocket for attach?

### ISSUE THREAD

**Issue by semoac** [containers/libpod#1348]
/kind feature

Hi.

We have a small internal project to give to ours team sandboxs with tools using containers.

Today we use xterm.js and Docker to expose the sandboxs but we like to replace Docker with podman and friends.

I'm looking for information about  the websocket needed to expose a terminal via web in podman. Looks like API for AttachToContainer is still in development.

We are not experts in this topic so i ask, Do we need to wait for the AttachToContainer API funcionality or we can do something with the i/o stream socket? There any other way to do this with podman?

We will appreciate any tips or links about this matter.

Thanks

**Comment by mheon** [comment]
Our current API consumers are directly using the I/O stream socket, and that API is stable, so it's not going away and is safe to use. We may also offer AttachToContainer directly over the Varlink API without requiring the socket at some point, but I don't think we definite plans to finish that API any time soon - directly accessing the stream socket has generally been sufficient for our needs.

If you have a use case that would benefit from having the AttachToContainer API implemented, as opposed to direct socket access, we'd like to hear about that as well.

**Comment by semoac** [comment]
Thanks for the answer.

We will check how to expose a shell via web using websockets and the I/O stream socket with podman.

Do you know any project doing this with Podman instead of Docker?

Cheers.

**Comment by rhatdan** [comment]
@semoac Have you looked any further into this?  Is this still something you need.  Seems like something we could provide via podman varlink.

**Comment by rhatdan** [comment]
CLosing because of lack of response for issuer.  Reopen if this is still something you are after.

@TomSweeneyRedHat FYI
