### ISSUE TITLE
podman varlink stales

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#1361]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**Description**

`podman varlink` exits. My assumption it should stay up and serve.

**Describe the results you received:**

```
$ podman --log-level debug varlink unix:/run/podman/io.podman
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: override_kernelcheck=true
DEBU[0000] overlay test mount with multiple lowers succeeded
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true
INFO[0000] Found CNI network crio-bridge (type=bridge) at /etc/cni/net.d/100-crio-bridge.conf
INFO[0000] Found CNI network 200-loopback.conf (type=loopback) at /etc/cni/net.d/200-loopback.conf
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db
DEBU[0000] Set libpod namespace to ""
INFO[0001] varlink service expired (use --timeout to increase session time beyond 1000 ms)
```

And that's it.

Same thing happens when I do `systemctl start io.podman`.

The unix socket gets created and lingers after `podman varlink` exits. Obviously, none of the requests from varlink client get served:

```
ConnectionRefusedError: [Errno 111] Connection refused
```

Is this a known issue or am I doing something wrong?

**Output of `podman version`:**

```
python3-varlink-27.1.1-1.fc29.noarch
libvarlink-util-12-1.fc29.x86_64
podman-0.8.3-4.dev.git3d55721.fc30.x86_64
python3-podman-0.8.3-4.dev.git3d55721.fc30.noarch
```

```
Version:       0.8.3-dev
Go Version:    go1.11rc1
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
It gets started on demand in a socket activated systemd unit file.  We don't want this service running all the time.

**Comment by baude** [comment]
if you want it to stay up use a --timeout value of 0.

**Comment by TomasTomecek** [comment]
Thank you, that worked.

On the other hand, the socket activation is not functioning for me. I'm still getting 'Connection refused' or

```
ConnectionError: [Errno 111] Failed varlink connection "unix:/run/podman/io.podman-io.podman". Is podman service running?: 'unix:/run/podman/io.podman-io.podman'
```

I'm not sure where the problem is, whether if it's systemd, varlink or podman.

**Comment by TomasTomecek** [comment]
I did that, but seems that one of my actions "broke" systemd. After uninstall & reboot & install it started to work just fine. Thank you very much for helping me out.
