### ISSUE TITLE
Create a general overview for users new to podman and/or container technology in general.

### ISSUE THREAD

**Issue by najamelan** [containers/libpod#1376]
I'm quite new to both podman and containers in general and I notice that it is difficult to get an overview of the current state of affairs. The documentation of podman is currently mainly focused on description of command line options, and there is not much overview. It basically comes down to trial and error which isn't a great user experience and is time consuming, especially if one might find out after X days that this or that feature that one needs does not exist (yet).

I think there are some big areas concerning podman:
- image building
- image and container management (exporting, naming, ...)
- running containers
- uid and gid interactions between, dockerfiles, images, containers, the host and filesystems, user namespaces
- network
- storage and filesystem
- security (pitfalls)

It would be amazing if one overview document existed that just goes through the _what you need to know_ about each of these thing:
- basic explanation
- what's currently possible in podman and quickly how to do it, what's not possible
- pitfalls, tips and tricks
- cover basic user scenarios

Examples of things I'm still confused about after using podman for 3 full days and reading plenty of the docs:
- **image building**: should I use buildah or podman build?
- **uid and gid**: I think this is a crucial question, but the current state of affairs seems to be a mess in the entire container community. Lots of people seem to struggle with this, lots of hacks and scripts exist to modify uids, ... things that happen to me: I have a [dockerfile](https://github.com/jessfraz/dockerfiles/blob/master/tor-proxy/Dockerfile) that has `USER tor` at the end without ever calling `adduser`. It turns out I have a tor user on my host. But when I run this, the process runs as root. When I run it with `podman run  --user tor:tor` I get: `error determining run gid: group: unknown group error looking up group "tor"` even though I have a group named `tor` on my host??? It's all pretty unclear how exactly to have control over uid/gid and not shoot oneself in the foot.
- **network**: Currently what I have found in the docs it that one can choose between `bridge`, `host` and `none`, and that the options `ip` and `ip6` aren't implemented. Does this mean I have no way of controlling the ip of a container? And thus I can't use a firewall rule based on ip? Maybe networking warrants a proper tutorial showing different user scenarios?
- **storage**: How do volumes mentioned in a Dockerfile interact with volumes specified on CLI with `podman run`? When I tried to mount /dev/shm/somefolder to /dev/shm in the container that didn't really work. When I used the `--shm-size` it looks like the /dev/shm of the container isn't on /dev/shm of the host and thus is not in memory, but on hdd... Permission issues. Probably this also warrants a proper tutorial going over a number of different user scenarios. How does one manage deleting storage volumes of removed containers?

Tracking issue: #1321

**Comment by vrothberg** [comment]
@rhatdan Some of the points mentioned above suggest (to me) a website (e.g., podman.io).

**Comment by mheon** [comment]
@najamelan Answers to a few of the things you're confused about:

* Image building: `podman build` and `buildah build` should be identical - we use `buildah` code under the hood. Manpages should be altered if this isn't clear.
* Network: We don't presently support `--ip` to set the address of a container, but we're looking to add support in the next week or so.
* Storage: Dockerfile volumes should be overridden by volumes added at runtime by the CLI if there is a conflict. Your SHM issue sounds like a bug - would you mind filing an issue about it?

**Comment by TomSweeneyRedHat** [comment]
podman.io in progress fwiw, along with buildah.io.

**Comment by vrothberg** [comment]
> podman.io in progress fwiw, along with buildah.io.

Nice!

**Comment by najamelan** [comment]
@mheon 
Ok, I will have another look into the /dev/shm issue to be sure

**Comment by najamelan** [comment]
@mheon 
Ok the shm is probably false alarm. It is a tmpfs, so that should be in memory. free only shows the usage in the buffer category, and somehow I was expecting to see the mount somewhere in /dev/shm on the host, not in /var/lib... but that was silly of me... 

When it comes to buildah, the podman build`

**Comment by mheon** [comment]
The manpages should definitely mention `buildah` if they don't. `buildah` is our first-class citizen for building images - `podman build` just uses `buildah bud` to allow us to have a fully Docker-compatible command line. We used to actually execute `buildah` under the hood, but there were objections to making `buildah` a hard requirement of `podman`, so we ended up vendoring their code and using `buildah` as a library.

**Comment by rhatdan** [comment]
Right `podman build` is to mimic the functionality of `docker build`, while buildah's goal is to support Dockerfile but also alternative ways of building containers.

@najamelan Great job putting this together,  We would love to have you help us put together an into website with your ideas.  @TomSweeneyRedHat is working on podman.io as the entrypoint for podman information.

**Comment by najamelan** [comment]
Ok. I will see what I can do but I have little time and my availability will drop more from next week on. Right now I'm trying to get my head round everything involving user id's and mappings. When I understand it, I wouldn't mind trying to write up a clear explanation from the basics on, but first I need to understand it. Further, I'm happy to review stuff and let you know if it's clear for a beginner or not.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat, I really like the proposal in this issue. Maybe we can put our heads together in not so long and collect something like a containers ABC for Podman, Buildah, Skopeo etc. (Cc: @rhatdan)? 

I was skimming parts of the RHEL docu and can imagine re-purposing those for such educational purposes for the projects.

**Comment by rhatdan** [comment]
I agree.

**Comment by rhatdan** [comment]
I think we need to start working on this blog/white paper.

**Comment by rhatdan** [comment]
Is this still something people feel we should write?
@vrothberg @TomSweeneyRedHat ?

**Comment by vrothberg** [comment]
I think there is a sufficient amount of resources now to educate users. We have the websites with dedicated blogs, search engines are kicking it, the demos project is there, etc. There can never be enough documentation but I think we're good now :)

**Comment by TomSweeneyRedHat** [comment]
Didn't beat the close, but I concur.  I think the one spot we're light on in running rootless containers, but I think we're getting there on that too.
