### ISSUE TITLE
Unable to delete files created in rootless mode

### ISSUE THREAD

**Issue by frezbo** [containers/libpod#1386]
`rm -rf ~/.local/share/containers` fails

```
~ (aws:rean-gov-sd)(kc)$ find .local/share/containers/ ! -user frezbo -exec ls -l {} \;
total 0
drwxr-xr-x. 2 100191 100191 6 Aug  9 23:52 leases
drwxr-xr-x. 2 100191 100191 6 Aug  9 23:52 links
total 0
total 0
total 0
drwxr-xr-x. 2 100191 100191 6 Aug  9 23:52 leases
drwxr-xr-x. 2 100191 100191 6 Aug  9 23:52 links
total 0
total 0
~ (aws:rean-gov-sd)(kc)$ 
```

Is this expected? I assumed them to be owned by the current user when using usernamespaces

**Comment by rhatdan** [comment]
If fhey were created inside of the USERNS but not as Root files, then you will have to enter the USERNS to be able to delete them.

buildah unshare allows you to enter the USERNS and you can delete them. We probably need to create a podman unshare.

**Comment by frezbo** [comment]
@rhatdan thanks that  makes sense and it explains why `podman` is able to remove them when deleting the image. I will close this.
