### ISSUE TITLE
RFE: Need to add a podman unshare (Same as buildah unshare)

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#1388]
unshare -u ...

Does not join the userns the same way as podman and buildah use it.

The problem users are seeing, is they can not remove files created in their userns when not in a userns, in their homedir.  Since their is no way to enter the USERNS from podman, they have a difficulty cleaning up  their homedir.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by mheon** [comment]
What would `podman unshare` do as root? Do nothing and throw an error message?

Generally speaking, I don't like this. Our userns UI is complicated enough as it is, and now we want to add a new command with a confusing name (I don't think many people have ever heard of the `unshare` binary) so they can interact with files from rootless Podman, which there is a good chance they don't realize even runs in a userns making them very confused about why the files it creates aren't owned by them, and instead by a UID that probably doesn't even belong to a user.

Going to be a lot of docs work to explain this in a way that anyone will understand

**Comment by rhatdan** [comment]
Well it is the only way to allow them to clean up content in their homedir that was created by one of their UserNS other then their UID.

podman unshare --uidmap --gidmap as root would put you in the mapped usernamespace.

**Comment by giuseppe** [comment]
I am not opposed to the idea but if the goal is just to allow destroying the storage, could it be something like: `podman storage destroy`?  Which I think can be useful for root as well

**Comment by rhatdan** [comment]
Well what happens if I volume mount into a container with podman and then create content as user 60 inside of my container which ends up creating 100060 UIDs in my homedir

podman run -ti -v ~/log:/var/log/ ...

**Comment by rhatdan** [comment]
BTW Storage handling is something we had in atomic, which we might end up adding to podman at some point.

**Comment by rhatdan** [comment]
One thing we could do if we had podman unshare is be ableto do podman mount and manipulate the mount point.

**Comment by rhatdan** [comment]
Just leave this for buildah unshare for now. Have not heard customers asking for this feature.

**Comment by giuseppe** [comment]
could we leave it as a RFE and tag it as "good first issue"?  New contributors might find it useful to start hacking on Podman

**Comment by davidlt** [comment]
I think this might be related: https://github.com/containers/libpod/issues/2739

I was using `podman mount` in Fedora 29 until it sopped working 1-2 months ago and now produces: `Error: cannot mount using driver overlay in rootless mode`. You also cannot do things like `sudo podman mount` as it will not see my user containers. `buildah unshare` + `podman mount` ends up in errors: `Error: could not get runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage: permission denied`.

So probably I need to start using `sudo podman`.
