### ISSUE TITLE
Regression: 'podman invalid-command' exits 0, no longer outputs to stderr

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1395]
podman-0.8.5-1.gitdc5a711.fc28, when invoked with an invalid subcommand, no longer errors:
```
# podman not-a-command
Command "not-a-command" not found.            <<< this goes to stdout, not stderr
See `podman --help`.
# echo $?
0
```
This is a regression from podman-0.8.4-2.git9f9b8cf.fc28:
```
# podman not-a-command
No help topic for 'not-a-command'         <<< on stderr
# echo $?
3
```

**Comment by edsantiago** [comment]
Followup: looks like bbcad6f572207779ead07127e6619961bc0758b9

**Comment by vrothberg** [comment]
@edsantiago, thanks for the report! I will fix that.

**Comment by vrothberg** [comment]
@rhatdan @edsantiago Docker has exit code 1 in such case. Shall we follow that or shall we keep 3 as before?

**Comment by mheon** [comment]
I think 1 is better here

**Comment by edsantiago** [comment]
TBH I was surprised at seeing 3 in the earlier podman: I tend to think of exit codes as 0 and 1, with everything else reserved for special, clearly-documented situations. In short: 1 seems more natural.
