### ISSUE TITLE
Allow to pass options globally to podman via a configuration file

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#1401]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
/kind feature

**Description**
It would be really great to get a way to have a configuration file for podman, allowing to set global options for its call. Having this capacity would allow people to get consistent runs of podman across different ways to actually launch it (being by hand, or scripted).

We might use the currently existing "libpod.conf" file, and maybe add sections for podman subcommands (run, exec, etc) so that we can get a really precise way to pass global, fixed options.

An example of options being "useful" for now is the "--security-opt". An example of configuration would be:
run_options = ["--security-opt label=disabled", "some other option", "and so on"]

That would confine the options to the "run" subcommand only.

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Not a bug
```

**Output of `podman info`:**

```
Not a bug
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@rhatdan I'm fine with this, but I believe you previously expressed opposition to a podman config file?

**Comment by rhatdan** [comment]
my fear of this is the proliferations of config files.  When we merge libpod into CRI-O, Users would be instructed to edit libpod.conf, cri-o.com, storage,conf registries.conf ...

Also handling libpod.conf for users running rootless containers needs to be thought about.  
Should libpod.conf have podman specific config options?

We have been using environment variables for this type of thing at least with podman build and buildah.

So I would not be against adding an environment variable to specify things like security-opt.
Specifying run options this way might get messy.

**Comment by cjeanner** [comment]
@rhatdan hello! well, an environment variable will most probably not serve my purpose :(. Although it seems nice and all, it won't work in some cases, especially:
migrating an existing docker script/stack/whatever making calls to docker CLI from multiple locations, being shell scripts, python scripts and the like, to podman (note: we have some kind of wrapper, but it would be hard to add podman-specifics, especially since docker security-opt takes ":" instead of podman "="). So a configuration file is probably the right way, and is far, far easier to deploy/maintain than some weird/ugly "if-then-else" lost in the wrapper code.

The iso-compatibility might be really important for end-users, and currently, we just don't have that:
As podman doesn't have a daemon, we have to get some global way to pass options to the different subcommands...

**Comment by rhatdan** [comment]
Docker switched over from the ":" to the "=" years ago, and only supports ":" for backwards compatabiltiy.  You should switch your scripts to use the "=",  Other then that our goal is to be fully compatable with the docker CLI.  

Can you make a list of the options you want to pass?

**Comment by cjeanner** [comment]
Didn't know about the docker change - the examples I saw were all using the ":" - I didn't check the date. Good news then on that part :).

So, currently, we don't pass any option to docker, as the daemon is configured globally (selinux separation is not activated).

My goal is to get a 1:1 compatibility between our deploy using docker and using podman, at least as a first step.

It would be really, really helpful to get the capacity to set options in a configuration file, like we can do with the docker daemon.
The "issue" is, in order to get podman to run with the ```--security-opt label=disabled``` we currently need, we'd need to edit at least three projects:
- [kolla](https://github.com/openstack/kolla) in order to inject the option in JSON files
- at least [that file](https://github.com/openstack/tripleo-heat-templates/blob/master/docker/docker-puppet.py) in [tripleo-heat-templates](https://github.com/openstack/tripleo-heat-templates) for the one-shot runs
- and probably [paunch](https://github.com/openstack/paunch) in order to support that option that would be present in generated JSON file

If we could set the needed options (currently, only the ```--security-opt``` is needed, I don't know if we might need anything else) in a global configuration file like libpod.conf, that would really help us going forward with the current work, and avoid having to run a long process for the wrappers modifications right now.

As previously said, if podman wants a 1:1 compatibility with docker (and it looks like it's very close, nice job!), it really should have support for a configuration file, as this would mimic the daemon behaviour, at least regarding the consistent way to run containers.

Also, environment variables will probably not work in our case, as there are multiple ways to run podman/docker, from shell script to python subprocess, all wrapped in sudo calls...

**Comment by vrothberg** [comment]
I have been looking around and found that Podman's `--config` flag is a nop. I somehow interpret that the intention behind this flag is similar to what's being suggested in this issue, @rhatdan @mheon?

**Comment by rhatdan** [comment]
crio.conf currently has an selinux=true value inside of it.  I guess we could add a 
label=true/false flag to libpod. and then wire it in.  We would need to also do

podman run --security-opt label:enabled  or some such to reverse the setting if disabled by default.

**Comment by cjeanner** [comment]
That would be great indeed. I know it's not really cool disabling selinux separation, but sometimes we don't have any choice - and when moving huge docker-based deploy things to podman, getting a real 1:1 compatibility, also with """defaults""" is a plus :).

Thank you for your understanding and time.

**Comment by mheon** [comment]
I'm really iffy on just putting this in libpod.conf - it's a flag for configuring things above libpod, and will affect no code in libpod itself.

@vrothberg `--config` was mainly intended for CI testing originally, but it seemed like it would be useful for cases like this, so I left the flag public. If it's not working, we should look into fixing that.

**Comment by rhatdan** [comment]
I still have no idea on fixing this.

**Comment by rhatdan** [comment]
@cjeanner Have you worked around the problems.  Is there anything we can do short of a podman.conf to solve this problem?

**Comment by cjeanner** [comment]
@rhatdan hello! well, we've added proper selinux configuration/labels/others to the affected containers/data, and it's working. Guess we don't need to push global config disabling selinux now :).

So on our side, no more needs on this field.

**Comment by TomSweeneyRedHat** [comment]
Thanks @cjeanner .  If you feel differently in the future, please reopen this issue or create a new one as works best for you.
