### ISSUE TITLE
Consistent list commands

### ISSUE THREAD

**Issue by fbruetting** [containers/libpod#1404]
/kind feature

Buildah provides `buildah images` and `buildah containers` for listing those contents. Podman however provides `podman images`, `podman container ls` and `podman pod ls` in contrast. This is inconsistent and also confusing, as other programs (at least those I work with) write `list` out (`flatpak list`, `dnf list` etc.). I then often use the wrong form, get an error and have to execute once more.

I’d therefore like to propose
* changing that `ls` to `list` for consistency with other programs, and
* create the commands `podman containers` and `podman pods` additionally (which just link to the before-mentioned list commands) for consistency with Buildah and for having a short form.

As Buildah doesn’t have a v1.0 release yet, I think that API change is ok. 😊

What do you think? Or do I miss something here? (I’m completely new to containerization… 🙈)

This is based on:
```
podman version 0.8.2.1
```

**Comment by baude** [comment]
the ls is consistent with other container runtimes.  i could see us making ls and list aliases to each other?

**Comment by fbruetting** [comment]
Ah ok. But `containers` and `pods` would also really be nice!

**Comment by mheon** [comment]
That might be difficult, since we have `container` and `pod` subcommands - i feel like there'd be a lot of mistyping one or the other

**Comment by fbruetting** [comment]
I don’t see a collision here?

**Comment by vrothberg** [comment]
@fbruetting, thanks for taking the time to open the issue!

> the ls is consistent with other container runtimes. i could see us making ls and list aliases to each other?

:+1:

> Ah ok. However, containers and pods would also be really practical!

Personally, I am against doing that change, but I am sure it depends on the perspective. I am mostly against it as `podman-container` and `podman-containers` are too similar (Levenshtein distance of 1). I would also find it annoying for tab completion in the terminal and it's likely to trick my brain into mixing up the commands - I don't find it intuitively distinguishable.

**Comment by rhatdan** [comment]
I could see adding a ps alias for buildah since Docker sort of made people consider ps as a command for listing containers.

I agree that having podman container versus podman containers is not a good idea.

We wanted to closely model the Docker CLI when building podman so people familiar with it could easily transition.  We had different goals with Buildah.

**Comment by rhatdan** [comment]
There are thousands/millions of scripts that have been written for the Docker CLI.  We need to make it as easy as `alias docker=podman`
Which is why we follow the docker cli standard.

Adding ls, and list for podman seems like a good idea.

We have `podman container ls` now.

**Comment by fbruetting** [comment]
Ok, that’s a good point (although using a more logical syntax by default and enable docker-compatibility by `alias docker="podman --compat"` may be another possible solution for being more flexible).

Would you then like to introduce `buildah container ls|list` and `buildah image ls|list`? Would also solve this inconsistency problem. ;)

And do you maybe like introducing shortcuts like `ip` did by being able to abbreviate `ip address` by `ip addr`, `ip a` etc.?

**Comment by rhatdan** [comment]
Sure I am open to short cuts,   Not sure of the value of adding the `buildah container ls|list` and `buildah image ls|list` but I would consider the PRs.

**Comment by rhatdan** [comment]
Once these ^^ PRs get merged, I think we can close this issue.

**Comment by baude** [comment]
closing per @rhatdan 's comments
