### ISSUE TITLE
Mounting /sys fails with latest podman

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#1447]
/kind bug

**Description**

When running a container in which we mount /sys is now failing with latest podman (deployed from current master).

**Steps to reproduce the issue:**

Run a container which tries to mount /sys or something in /sys/*.

**Describe the results you received:**

```
"stdout: (cellv2) Creating default cell_v2 cell",
    "Error running ['podman', 'run', '--name', 'iscsid', '--label', 'config_id=tripleo_step3', '--label', 'container_name=iscsid', '--label', 'managed_by=paunch', '--label', 'config_data={\"start_order\": 2, \"healthcheck\": {\"test\": \"/openstack/healthcheck\"}, \"image\": \"docker.io/tripleomaster/centos-binary-iscsid:0d5b1d18e88ad27e87368c8844c325cbfe603fdb_e25bec61\", \"environment\": [\"KOLLA_CONFIG_STRATEGY=COPY_ALWAYS\"], \"volumes\": [\"/etc/hosts:/etc/hosts:ro\", \"/etc/localtime:/etc/localtime:ro\", \"/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro\", \"/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro\", \"/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro\", \"/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro\", \"/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro\", \"/dev/log:/dev/log\", \"/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro\", \"/etc/puppet:/etc/puppet:ro\", \"/var/lib/kolla/config_files/iscsid.json:/var/lib/kolla/config_files/config.json:ro\", \"/dev/:/dev/\", \"/run/:/run/\", \"/sys:/sys\", \"/lib/modules:/lib/modules:ro\", \"/etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro\", \"/dev/null:/dev/null\"], \"net\": \"host\", \"privileged\": true, \"restart\": \"always\"}', '--detach=true', '--env=KOLLA_CONFIG_STRATEGY=COPY_ALWAYS', '--net=host', '--privileged=true', '--volume=/etc/hosts:/etc/hosts:ro', '--volume=/etc/localtime:/etc/localtime:ro', '--volume=/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro', '--volume=/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro', '--volume=/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro', '--volume=/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro', '--volume=/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro', '--volume=/dev/log:/dev/log', '--volume=/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro', '--volume=/etc/puppet:/etc/puppet:ro', '--volume=/var/lib/kolla/config_files/iscsid.json:/var/lib/kolla/config_files/config.json:ro', '--volume=/dev/:/dev/', '--volume=/run/:/run/', '--volume=/sys:/sys', '--volume=/lib/modules:/lib/modules:ro', '--volume=/etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro', '--volume=/dev/null:/dev/null', 'docker.io/tripleomaster/centos-binary-iscsid:0d5b1d18e88ad27e87368c8844c325cbfe603fdb_e25bec61']. [127]",
    "stderr: container create failed: container_linux.go:336: starting container process caused \"process_linux.go:399: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/lib/containers/storage/overlay-containers/a38512ad1ebd3de216b5ff0be852084d4c192a0134de5efbc8fda1b1c424ae35/userdata/cgroup\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/639053fb15c709d86cd2aafd357bbe3d68036fde6f9454765e0a9787f5058b8b/merged\\\\\\\" at \\\\\\\"/sys/fs/cgroup\\\\\\\" caused \\\\\\\"stat /sys/fs/cgroup/systemd/machine.slice/libpod-a38512ad1ebd3de216b5ff0be852084d4c192a0134de5efbc8fda1b1c424ae35.scope: no such file or directory\\\\\\\"\\\"\"",
    ": internal libpod error",
```

**Describe the results you expected:**

Container should start without error (like it did before).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.9.2-dev
```

**Output of `podman info`:**

```
host:
  Conmon:
    package: podman-0.8.5-3.gitdc5a711.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.11.2, commit: 2d86a71a1e3f3ccf65f6fb610558e660f5830fe4-dirty'
  MemFree: 497938432
  MemTotal: 8201625600
  OCIRuntime:
    package: runc-1.0.0-37.rc5.dev.gitad0f525.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 1609560064
  SwapTotal: 1610608640
  arch: amd64
  cpus: 4
  hostname: undercloud.localdomain
  kernel: 3.10.0-862.11.6.el7.x86_64
  os: linux
  uptime: 1h 14m 27.08s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.centos.org
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 49
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 29
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running it on centos7 in a VM.

**Comment by mheon** [comment]
I'm seeing a lot of SELinux issues with the `/sys/` mount over here - have to `setenforce 0` to get as far as you did. Definitely issues present other than SELinux, but we may want to look into adjusting the SELinux rules to make this work.

Further interesting news: This doesn't work on Docker 1.13. I'm testing here and getting angry CGroup errors.

**Comment by mheon** [comment]
I've added all volume mounts present, `--privileged`, and `--net=host`, and I cannot make this work on Docker with SELinux as Permissive

**Comment by mheon** [comment]
I wonder if you were launching the Docker daemon with any special configuration - maybe cgroupfs cgroups instead of systemd?

**Comment by mheon** [comment]
Trying cgroupfs got me further - now failing with `process_linux.go:279: applying cgroup configuration for process caused \"open /sys/fs/cgroup/cpuset/cpuset.cpus: no such file or directory\"` out of runc

**Comment by mheon** [comment]
Oh dear. I think whatever I was doing managed to completely wipe out `/sys/fs/cgroup` and that is why Docker was exploding.

**Comment by mheon** [comment]
Confirmed - Docker works with with your config when `/sys/fs/cgroup` is intact

**Comment by mheon** [comment]
Running the exact same command with `docker` replaced with `podman` wipes out /sys/fs/cgroup

**Comment by EmilienM** [comment]
Thanks @mheon for the investigation. Yes I run Docker on the host (with default config). Please let me know if you need more infos on my env. I can also give SSH with root access in this lab. Thanks again.

**Comment by mheon** [comment]
My initial thought was that this was an issue with spec generation, and we were generating the /sys/ bind mount or /sys/fs/cgroup in a sufficiently different way from Docker so as to cause problems. That does not appear to be the case. Moving on to other potential causes today.

**Comment by mheon** [comment]
Nevermind, talked with @rhatdan and we confirmed it was indeed volume mount permissions issues - we need to change all volume mounts from private to rprivate to match Docker and containerd

**Comment by mheon** [comment]
Changing all mount propagation from private to rprivate resolved the issue where the container was wiping out /sys/fs/cgroup, but we're still not able to launch the container. Will open a PR with the private -> rprivate change and continue debugging

**Comment by mheon** [comment]
Getting closer - I think it's the /dev/pts mount we're adding. It's missing from Docker. Maybe an artifact of the /dev/ mount?

**Comment by rhatdan** [comment]
I do recall this being an issue, and perhaps docker does not add /dev/pts if /dev/ is mounted over?

**Comment by rhatdan** [comment]
https://github.com/moby/moby/commit/e076bccb458aeadab9380ce0636456ad6317a85f might be of some interest.

**Comment by mheon** [comment]
I've removed the /dev/pts mount, which moves us closer to the default Docker spec, but did not resolve the problem. Our current problem:
`conmon 3c2f02c7fb3d53954cf9 <ninfo>: console = {.name = '(null)'; .fd = 0}`
`conmon 3c2f02c7fb3d53954cf9 <error>: Failed to get console terminal settings Inappropriate ioctl for device`

**Comment by mheon** [comment]
I think this is resolved by our mount propogation changes
