### ISSUE TITLE
registry auth doesn't work with rootless mode

### ISSUE THREAD

**Issue by mrguitar** [containers/libpod#1457]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**Description**

running podman as rootless fails to log on to a registry using basic auth 

**Steps to reproduce the issue:**

1. setup subuid & subgid for an account via the instructions

2. podman login registry.redhat.io

**Describe the results you received:**
error reading JSON file "/run/containers/0/auth.json": error unmarshaling JSON at "/run/containers/0/auth.json": unexpected end of JSON input 

**Describe the results you expected:**
Login Succeeded!

**Additional information you deem important (e.g. issue happens only occasionally):**
100% of the time

**Output of `podman version`:**

```
$ podman version
Version:       0.8.4
Go Version:    go1.10.3
OS/Arch:       linux/amd64

```

**Output of `podman info`:**

```
$ podman info
host:
  Conmon:
    package: podman-0.8.4-2.git9f9b8cf.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: fd2097f7ef3d0aacd9ed450ddb36fe544a242de4-dirty'
  MemFree: 438554624
  MemTotal: 16697241600
  OCIRuntime:
    package: runc-1.0.0-50.dev.git20aff4f.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 7030026240
  SwapTotal: 8417964032
  arch: amd64
  cpus: 4
  hostname: camacho.local
  kernel: 4.17.19-200.fc28.x86_64
  os: linux
  uptime: 176h 34m 30.33s (Approximately 7.33 days)
insecure registries:
  registries:
  - 172.30.0.0/16
  - brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.redhat.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 36
  GraphDriverName: overlay
  GraphOptions: []
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 25
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
login/logout wasn't really supported by podman 0.8.4 but more recent versions (since 0.8.5) should work: ec07b2d0216c316ac7b2e0869a4e8af02859509d

@mrguitar do you still have the same problem with a more updated version?

**Comment by mrguitar** [comment]
yeah same issue:
$ podman login registry.redhat.io
Username: me
Password: 
error reading JSON file "/run/containers/1001/auth.json": error unmarshaling JSON at "/run/containers/1001/auth.json": unexpected end of JSON input
[mrguitar@camacho ~]$ rpm -qa |grep podman
podman-0.9.1-3.gitaba58d1.fc28.x86_64

**Comment by giuseppe** [comment]
I see.  The error happens because you probably haven't `XDG_RUNTIME_DIR` set and containers/image uses `/run/containers/%UID/auth.json` as a fallback.  We should enforce `XDG_RUNTIME_DIR` to avoid such issues.

**Comment by rhatdan** [comment]
We should add a third option to put the auth file into homedir.
