### ISSUE TITLE
Move away from file locks for containers and pods

### ISSUE THREAD

**Issue by mheon** [containers/libpod#148]
As of now, we use file locks from containers/storage to synchronize operations between libpod in multiple processes. This comes with a number of serious issues

- We can't reap the locks when the container is removed
- Each lock is a file descriptor we have to keep open until the process closes

We need an alternative way of locking important container operations which does not have these limitations before we can seriously think of moving to CRI-O. Potential solution would be to rewrite file locking code to open the file in question immediately before acquiring the lock, and to close it immediately after the lock was released.

**Comment by mheon** [comment]
We should also investigate whether there are other types of locking that can meet our needs. We're definitely leaving a lot of performance on the floor with the need to hit disk for all operations.

**Comment by rhatdan** [comment]
@nalind WDYT

**Comment by rhatdan** [comment]
@mheon Any update on this?

**Comment by mheon** [comment]
Not yet, but it's high on the list once pods come in.

**Comment by mheon** [comment]
Working on this now

**Comment by rhatdan** [comment]
@mheon Is this still the issue for your memory locks?

**Comment by mheon** [comment]
@rhatdan Yeah

**Comment by rhatdan** [comment]
@mheon Do you have a PR for this one?

**Comment by kunalkushwaha** [comment]
Hi, what is the state of this issue? it seems some work is done but not finished.
This is also one of performance issue for podman.

If you need some ideas to be tried, I may work on this.

**Comment by mheon** [comment]
https://github.com/containers/libpod/pull/1235 is the main effort towards solving this. There's a lot of work still to be done (there are still occasional deadlock issues, and it needs a workable path towards integration into existing systems - a way of assigning lock IDs to existing containers). I haven't had time to look at it in a long while, but I'll take another poke this weekend.

**Comment by mheon** [comment]
I also doubt we'll see much performance swapping off file locks in low-container-count scenarios. There are a lot more impactful things we can hit performance-wise - this is mainly a fix for file descriptor issues.

**Comment by mheon** [comment]
(Biggest of those other things is (I think) #1689 - the runc calls are extremely expensive, discarding them in favor of a single stat() is a massive win)

**Comment by rhatdan** [comment]
@mheon You are continuing to work on this correct?

**Comment by mheon** [comment]
@rhatdan It'll be my first priority once we get back from shutdown, want to have it in quickly so I can talk about it at Devconf

**Comment by mheon** [comment]
#1235 is merged, so closing
