### ISSUE TITLE
Can't complete installation on the Mac

### ISSUE THREAD

**Issue by dudash** [containers/libpod#1481]
# **kind bug**

**Description**
```sudo make install``` on the Mac doesn't work because the ```-D``` option isn't available

**Steps to reproduce the issue:**

1. Get a mac

2. Follow the installation instructions

3. Notice that `sudo make install` fails

**Describe the results you received:**
```
jdudash-OSX:libpod jason$ sudo make install
touch .gopathok
install  -D -m 755 bin/podman //usr/local/bin/podman
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install.bin] Error 64
```

**Describe the results you expected:**
The make install command to complete successfully

**Additional information you deem important (e.g. issue happens only occasionally):**
The version of `install` that is default on a Mac (```/usr/bin/install```) doesn't support the -D flag. I know MacOS isn't a high priority, but you might want to avoid using the -D flag. The -d and and -m options are available and work fine.

**Output of `podman version`:**

```
Version:       0.9.2-dev
Go Version:    go1.10.3
OS/Arch:       darwin/amd64
```

**Output of `podman info`:**

```
ERRO[0000] this function is not supported on this os
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacOS High Sierra

**Comment by rhatdan** [comment]
@jwhonce PTAL
