### ISSUE TITLE
container creation timeout: internal libpod error

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1502]
While testing something else, on a long-running job, I came back and found a container in Created state but not running. (I use no `create` commands, only `podman run`). Restarted, and caught it earlier this time, and scrollback shows:
```
` container creation timeout: internal libpod error
```
(initial backtick is part of output). There is nothing else informative anywhere on stdout/stderr.
```
# podman ps -a
CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS    PORTS   NAMES   IS INFRA
8dfeca100fcc   registry.access.redhat.com/rhel7/rhel:latest   bash -c for NUM in ...   9 minutes ago   Created           foo     false
```
`podman inspect foo` attached; it doesn't show me anything useful but maybe it will to you.

I _think_, but am not sure, that the error might be associated with an OSP10 networking hiccup: there was a brief period around that time when my mosh session was unresponsive. I left it to work on other stuff, and came back many minutes later, but have no way of knowing if this happened during that hiccup or after.

Anything I can do to diagnose further? (I'll leave the system untouched for a few hours in case you have suggestions). Anything I can do to try to catch this earlier and report better info?

[podman-inspect.txt](https://github.com/containers/libpod/files/2393701/podman-inspect.txt)

**Comment by mheon** [comment]
State shows configured, which means that the initial call to conmon/runc failed.

**Comment by mheon** [comment]
I don't think either of those requires a network connection, though

**Comment by vrothberg** [comment]
I am closing the issue as it does not seem to be reproducible. Feel free to re-open if the issue occurs again.
