### ISSUE TITLE
RFE: log whether or not podman is running in rootless mode upon invocation

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#1509]
**kind feature**

**Description**

log whether or not podman is running in rootless mode upon invocation..

I think something like this would help debugging a lot when users report issues:

```
$ podman run foo
-> podman is running rootless as user foobar
$ sudo podman foo
-> podman is running as root
```

This is just an idea. Feel free to close if not useful.

**Comment by mheon** [comment]
I think an info-level log about this would be a very good idea

**Comment by baude** [comment]
i agree

**Comment by rhatdan** [comment]
Well we don't want this going to the screen by default.

**Comment by rhatdan** [comment]
podman info and podman version should probably output it though.

**Comment by baude** [comment]
i think the log level would need to be enabled to have it come on screen.

**Comment by rhatdan** [comment]
Works for me.
