### ISSUE TITLE
nameservers in container's /etc/resolv.conf should be reachable

### ISSUE THREAD

**Issue by marcov** [containers/libpod#1533]
When launching `podman run` without `--dns` option, host's `/etc/resolv.conf` is used for the container.

This is a problem when host's `/etc/resolv.conf` only contains nameservers not reachable from the container, e.g. 127.0.0.1.  

Docker ignores  127.0.0.1 in host's `/etc/resolv.conf`. When there’s no other nameserver, it adds 8.8.8.8 and 8.8.4.4.

**Is this a BUG REPORT or FEATURE REQUEST?**:
**kind bug**

**Comment by marcov** [comment]
Looks like docker's [resolvconf package](https://github.com/docker/libnetwork/tree/master/resolvconf) is doing all the job of filtering host's `resolv.conf`. 

Do you think that this could be imported in libpod ?

**Comment by marcov** [comment]
@mheon thanks

**Comment by baude** [comment]
Using the command line switch for --dns is not desirable ?

**Comment by marcov** [comment]
@baude that's a possibility, but probably a user expects a docker-like user experience when using podman. 
Also passing `--dns` is not always an option (e.g. podman used in a script).

**Comment by mheon** [comment]
Going to take a look at this one today

**Comment by mheon** [comment]
Opened #1537 to fix
