### ISSUE TITLE
podman save, twice in a row: Error writing blob: [...] no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1543]
Baffling:
```
# podman pull alpine
[works fine]
# podman save --output /tmp/foo1 alpine
[works fine]
# ^1^2
podman save --output /tmp/foo2 alpine
Getting image source signatures
Copying blob sha256:df64d3292fd6194b7865d7326af5255db6d81e9df29f48adde61a918fbd8c332
 3.00 KB / 4.46 MB [>-------------------------------------------------------] 0s
unable to save ["alpine"]: Error copying image to the remote destination: Error writing blob: open /var/lib/containers/storage/overlay/df64d3292fd6194b7865d7326af5255db6d81e9df29f48adde61a918fbd8c332/merged/bin/busybox: no such file or directory
```
After the initial save, all further saves (of the same image) will fail the same way. Saving a _different_ image will succeed... the first time. 

`podman rmi alpine && podman pull alpine` resets the magic state flag.

podman-0.9.2-2.git81df604.fc28 and podman-0.9.3-4.gita723353.fc29

**Comment by mheon** [comment]
Probably leaving a temporary file somewhere we need to remove

**Comment by rhatdan** [comment]
@nalind Is this the one you think should be fixed now?

**Comment by nalind** [comment]
@rhatdan yes, like https://github.com/containers/buildah/issues/981, this should be fixed by https://github.com/containers/storage/pull/214.

**Comment by mheon** [comment]
@nalind Is the fix for this in #1494

**Comment by nalind** [comment]
Yes, it should be.

**Comment by mheon** [comment]
Ack, thanks!

**Comment by nalind** [comment]
Closed by #1567.

**Comment by dinamic** [comment]
Guys, is this the same issue or a new one:

```
tc@box:~$ podman pull alpine
Trying to pull docker://alpine...Getting image source signatures
Copying blob bdf0201b3a05 done
ERRO[0007] Error pulling image ref //alpine:latest: Error writing blob: error storing blob to file "/var/tmp/storage506373100/1": local error: tls: bad record MAC
Failed
(0x1949200,0xc000a32e60)
Error: error pulling image "alpine": Invalid image name "alpine", expected colon-separated transport:reference
tc@box:~$ podman --version
podman version 1.3.0-dev
```

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment]
@dinamic This is clearly something else (a TLS error reading from a `docker://` source), please file a separate issue (and in there, mention that this looks _a bit_ similar to https://github.com/containers/buildah/issues/1504 ).
