### ISSUE TITLE
Containers sharing --net should take their DNS configuration from dependency

### ISSUE THREAD

**Issue by mheon** [containers/libpod#1546]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug

**Description**

If I start two containers in Docker, one with custom DNS, the second using that container's network namespace, the second container will also share the first container's DNS config. The same is not true of Podman.

Further, Docker also makes DNS configuration conflict with network namespace sharing. I don't think this is a hard requirement in our case, but it might make things easier to understand.

**Steps to reproduce the issue:**

1. Terminal 1: `podman run -t -i --rm --name test --dns 1.1.1.1 fedora bash`

2. Terminal 2: `podman run -t -i --rm --net container:test fedora bash`

3. Terminal 2: `cat /etc/resolv.conf`

**Describe the results you received:**

Same resolv.conf as any other container - same nameservers as the host

**Describe the results you expected:**

Resolv.conf from the first container - only one nameserver, 1.1.1.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Latest master

**Comment by vrothberg** [comment]
@mheon, can you provide a reproducer for Docker? I don't seem able to find one.
