### ISSUE TITLE
error creating libpod runtime: error configuring CNI network plugin: failed to add watch on "/etc/cni/net.d/": no space left on device

### ISSUE THREAD

**Issue by patrickdillon** [containers/libpod#1566]
**kind bug**

**Description**
After playing around with podman a bit yesterday, trying to build a few images and running buildah demos, I can now no longer run commands such as `podman ps`. 

**Steps to reproduce the issue:**
I am shaky as to what caused this but my podman is currently in this state, so it is constantly happening. What led up to this:
1. I ran this buildah example: https://github.com/containers/buildah/blob/master/demos/buildah-scratch-demo.sh  but I believe I stopped the container
2. Played around a bit with building some images, Had no issues until the next day.
3. Now running `podman ps` causes the issue.

**Describe the results you received:**

error creating libpod runtime: error configuring CNI network plugin: failed to add watch on "/etc/cni/net.d/": no space left on device

**Additional information you deem important (e.g. issue happens only occasionally):**
getenforce: enforcing
**Output of `podman version`:**

```
Version:       0.9.1
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
could not get runtime: error configuring CNI network plugin: failed to add watch on "/etc/cni/net.d/": no space left on device
;)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 28

**Comment by mheon** [comment]
I assume you're not out of hard drive space per `df -h`?

If not, it's probably a result of running out of inotify instances. Does `ps aux | grep podman` show many processes?

**Comment by patrickdillon** [comment]
No, not out of disk space: 
```
Filesystem                               Size  Used Avail Use% Mounted on
devtmpfs                                 7.7G     0  7.7G   0% /dev
tmpfs                                    7.7G   86M  7.6G   2% /dev/shm
tmpfs                                    7.7G  2.3M  7.7G   1% /run
tmpfs                                    7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/mapper/fedora_localhost--live-root   49G   19G   28G  40% /
tmpfs                                    7.7G   22M  7.7G   1% /tmp
/dev/nvme0n1p1                           976M  223M  687M  25% /boot
/dev/mapper/fedora_localhost--live-home  176G   27G  141G  16% /home
tmpfs                                    1.6G   20K  1.6G   1% /run/user/42
tmpfs                                    1.6G   12M  1.6G   1% /run/user/1000
```

I forgot to mention that I checked: 
`sysctl user.max_inotify_instances`
result = 128
`fs.inotify.max_user_watches`
result=8192

I see no processes when I grep ps aux | grep podman.

**Comment by baude** [comment]
/dev/mapper/fedora_localhost--live-home -- is this a special flavor of f28?

**Comment by mheon** [comment]
I think we need to build a way of disabling inotify into ocicni, and turn that on for Podman by default. Not as though we need to update the plugins available when we only ever launch a single container per process.

**Comment by patrickdillon** [comment]
> is this a special flavor of f28?
No. It's a standard build. 

My issue resolved after reboot. I wish I could provide more info. If I manage to get podman into the same state again I will let you know.

**Comment by mheon** [comment]
I'm going to leave this open as a tracker for removing inotify by default - we don't need it, and it seems to occasionally cause issues like this.

**Comment by darkmuggle** [comment]
fwiw, I think hit this when running `podman` as a non-privileged user; using `suio podman` work just fine.

**Comment by rhatdan** [comment]
@giuseppe I did not think we used CNI when running in non root mode?

**Comment by mheon** [comment]
We shouldn't. Looks like initialization isn't checking if we're rootless.

I'll add the check and see if that breaks anything.

**Comment by rhatdan** [comment]
@mheon Can we close this issue?

**Comment by mheon** [comment]
Yeah this is fixed
