### ISSUE TITLE
podman logs --tail gives less lines than expect

### ISSUE THREAD

**Issue by ypu** [containers/libpod#1601]
**kind bug**

**Description**
podman logs --tail gives less lines than expect.
**Steps to reproduce the issue:**

1. Start a container with following command:
podman run --name test -dt docker.io/library/alpine:latest sh -c "echo podman; echo podman; echo podman"

2. Check logs with --tail 2
 podman logs --tail 2 test

**Describe the results you received:**
Only get one line output:
```
# podman logs --tail 2 test
podman
```

**Describe the results you expected:**
Get two line as expect

**Additional information you deem important (e.g. issue happens only occasionally):**
The log file output is as following:
```
# podman inspect --format '{{.LogPath}}' test
/var/lib/containers/storage/overlay-containers/0dda63067aa00a826315bf1098952c36e57b694ca0bc4fdaef15138e3f7febfe/userdata/ctr.log
# cat /var/lib/containers/storage/overlay-containers/0dda63067aa00a826315bf1098952c36e57b694ca0bc4fdaef15138e3f7febfe/userdata/ctr.log
2018-10-08T14:01:31.360065875+08:00 stdout P podman
2018-10-08T14:01:31.361610634+08:00 stdout F 
2018-10-08T14:01:31.361726199+08:00 stdout P podman
2018-10-08T14:01:31.362370453+08:00 stdout F 
2018-10-08T14:01:31.362482340+08:00 stdout P podman
2018-10-08T14:01:31.362652660+08:00 stdout F 
```

**Output of `podman version`:**

```
# podman version
Version:       0.9.4-dev
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 28 guest.

**Comment by giuseppe** [comment]
could you please share the environment where you are running the podman process (the output of `env`)?

**Comment by rhatdan** [comment]
Didn't @umohnani8 look into fixing this?

**Comment by umohnani8** [comment]
@rhatdan yeah I guess I messed up --tails while fixing the parsing. Looking into it.

**Comment by rhatdan** [comment]
@umohnani8 I take it this has been fixed?  If not please reopen this issue.
