### ISSUE TITLE
Podman run & create man pages do not mention --net

### ISSUE THREAD

**Issue by mheon** [containers/libpod#1615]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# Uncomment only one, leave it on its own line:

[//]: # **kind bug**

**Description**

The podman run and podman create manpages should mention that --net is an alias for --network, but they do not

**Steps to reproduce the issue:**

1. man podman-run and scroll to --network

**Describe the results you received:**

The --network flag is documented but not --net

**Describe the results you expected:**

The --net flag is documented as an alias of --network

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Current master

**Comment by rhatdan** [comment]
@QiWang19 Could you create a quick PR to fix this?
