### ISSUE TITLE
integration tests: Permission Denied with GOPATH != /go

### ISSUE THREAD

**Issue by cevich** [containers/libpod#1629]
# **kind bug**

**Description**

When running integration tests on ubuntu 18, we see gobs of 'permission denied' errors.  @baude and I looked into this for a few hours and concluded, somehow/why this is related to ``$GOPATH`` not being ``/go``  (in CI's case, ``/root/go``).  Since the test is running as root, the error didn't make much sense.  At the time, getting CI running was our goal, so we left a deeper investigation up to this issue.

**Steps to reproduce the issue:**

1.  Modify ``.cirrus.yml`` environment variable``$CIRRUS_WORKING_DIR`` to ``/root//go/src/github.com/containers/libpod``  (This is used to set ``$GOSRC``).

2. Modify ``contrib/cirrus/setup_environment.sh`` loop item ``"export GOPATH=\"/go\"" \`` -> ``"export GOPATH=\"/root/go\"" \``

3. Temporarily commit those changes and open a PR (so cirrus ci runs) -or- perform the equivalent steps in your dev. environment.

**Describe the results you received:**

Gobs of 'permission denied' errors when integration tests run (``contrib/cirrus/integration_test.sh``).

**Describe the results you expected:**

Integration tests should pass no matter what ``$GOPATH`` (and ``$CIRRUS_WORKING_DIR``) are set to.

**Comment by cevich** [comment]
This is Ubuntu and we tried disabling AppArmor, though it's also entirely possible we did that wrong.  While reading about AppArmor, there were a few side-notes that concerned us.  One being something about paths being incorrect when running inside a chroot (which ***is*** happening), and another I can't remember.  Will paste link if I can find it...

**Comment by cevich** [comment]
[...oh here it is.](https://wiki.ubuntu.com/DebuggingApparmor#AppArmor_and_chroot_environments).  I'll bet this affects buildah too, eh?

**Comment by rhatdan** [comment]
I believe this is fixed.
