### ISSUE TITLE
regression: podman rm --force: Cannot get exit code: error getting exit file for container

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1640]
Shell 1:
```
# podman run --name foo alpine sleep 120
```
Shell 2:
```
# podman rm --force foo
[ 10-second pause, expected ]
867cc2b384e41fe068acb6f7b1c3388c026b2cf2a283bc2fe8c8f1514a6b986d
```
Back to shell 1:
```
ERRO[0012] Cannot get exit code: error getting exit file for container 867cc2b384e41fe068acb6f7b1c3388c026b2cf2a283bc2fe8c8f1514a6b986d: stat /var/run/libpod/exits/867cc2b384e41fe068acb6f7b1c3388c026b2cf2a283bc2fe8c8f1514a6b986d: no such file or directory
# echo $?
0
```
podman-1:0.10.1-1.gite4a1553.fc29 (regression from 0.9.3.1-1.git1cd906d.fc29)

**Comment by mheon** [comment]
Damn, it's conmon file cleanup - it's removing the exit file as it transitions into Exited state.

We shouldn't strictly need it - Cleanup should guarantee a full sync, picking up the exit code. As such, we can probably remove the code in run that looks for it, and just grab it from the database instead.

**Comment by mheon** [comment]
Hm. This fires in the case that the container is removed before we can get status back from the DB, so having the exit file around in that case is convenient... I'll look more into this on Monday.

**Comment by edsantiago** [comment]
ping - this seems to have slipped through the cracks

**Comment by mheon** [comment]
I'll give some more thought here, but unfortunately I don't see an easy way forward here. We're hitting a limitation of our multiprocess design that will require some real effort to work around.

**Comment by rhatdan** [comment]
We should probably exit with a 125 any ways, since this seems like a failure of podman command to correctly access whether or not the container exited correctly.

**Comment by mheon** [comment]
That's definitely a short-term fix until we can get something better rolled out

**Comment by mheon** [comment]
It's a good one, though, better that what we're doing now at least

**Comment by edsantiago** [comment]
Still present in podman-0.12.1.1-1.git66d3499.fc29

**Comment by vrothberg** [comment]
Docker seems to return `137` in such cases which makes cross-compatibility easier for us.

**Comment by mheon** [comment]
I think adding the events system @baude and I were discussing will allow a permanent solution to this, but that's definitely not a 1.1 thing - maybe 1.2 at absolute earliest?

**Comment by rhatdan** [comment]
What is the exit code right now?

**Comment by vrothberg** [comment]
> What is the exit code right now?

0

**Comment by vrothberg** [comment]
> What is the exit code right now?

0
