### ISSUE TITLE
RFE: Add support for podman run --init

### ISSUE THREAD

**Issue by bowlofeggs** [containers/libpod#1670]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: **kind feature**

**Description**

```docker run``` has an ```--init``` flag that replaces process 1 with a minimal process that performs basic signal handling and child management. It would be nice if ```podman run``` had this feature as well.

**Comment by mheon** [comment]
We include some of the functionality of the minimal `tini` init already in Conmon (process reaping, for example). Generally we prefer to use systemd for cases where a more powerful init system is required (we have excellent native support for containerized systemd built in), but I don't see anything wrong with including this as an option (I wouldn't want to force `tini` as a dependency of Podman though)

**Comment by vrothberg** [comment]
I have no strong feelings for nor against the proposal. @baude, @rhatdan WDYT?

**Comment by rhatdan** [comment]
I actually do not believe we need this, since conmon provides this behaviour now,  I believe.

conmon will reap at container process zombies.

@giuseppe WDYT?

**Comment by giuseppe** [comment]
conmon won't be able to reap processes created inside the PID namespace, zombie processes are reparented to PID 1 in the namespace.

The reaper part of conmon is only to cleanup processes left around by the OCI runtime.  This is required as conmon sets itself as a reaper to be able to read the container process exit code

**Comment by rhatdan** [comment]
Does runc have some magic to make this happen?  or does docker just run a container with a static init volume mounted into it and then execs the command?  Or does the init take an option of the first command to fork/exec?

**Comment by rhatdan** [comment]
@mrunalp @runcom WDYT?

**Comment by giuseppe** [comment]
runc doesn't have any magic AFAIK, we will need to go the ugly way of mounting a static binary inside the container (this is what Docker does, it is mounted as `/dev/init`) and use it to boot the real application.

It could be a minimal static C program we ship together with conmon.

**Comment by rhatdan** [comment]
Makes sense.

**Comment by giuseppe** [comment]
that is exactly what I had in mind, it works for me.

Just out of curiosity, what are the differences with tini?

Now the difficult question is how to distribute it.  I think we could add it to the conmon .rpm once we have it?

**Comment by vrothberg** [comment]
> That works for me. @giuseppe WDYT? Do we need this as a separate package?

You can find the package sources for openSUSE [here](https://build.opensuse.org/package/show/Virtualization:containers/catatonit). I think that a separate package makes sense as it can be used for Docker as well (which is what we did for openSUSE/SLES).

**Comment by rhatdan** [comment]
@giuseppe @vrothberg Any movement on this issue?

**Comment by vrothberg** [comment]
I don't think so but I can look into it.

**Comment by vrothberg** [comment]
Thanks for catching up, @rhatdan :)

**Comment by rhatdan** [comment]
Yes lets make it part of the package, we don't want to support it independantly, especially in RHEL.

**Comment by muayyad-alsadi** [comment]
sorry to bump this up,
nothing provides this binary in fedora

```
# podman run --init -ti busybox /bin/sh
Error: container-init binary not found on the host: stat /usr/libexec/podman/catatonit: no such file or directory
# dnf provides '*/catatonit'
Error: No Matches found
```

on the other hand with docker it just work because `/usr/libexec/docker/docker-init-current` is shipped as part of docker package

```
# rpm -qf /usr/libexec/docker/docker-init-current
docker-1.13.1-63.git1185cfd.fc28.x86_64
```

shouldn't we ship `catatonit` and make it a dependency or at least a soft dependency?

**Comment by mheon** [comment]
@lsm5 ^^

**Comment by mheon** [comment]
I know we talked about packaging this up, but I'm not sure what happened with that.

**Comment by vrothberg** [comment]
It's in the pipeline but other tasks had a higher priority. In the meantime, `libpod.conf` and the CLI flags allow using another init binary as a temporary workaround.

**Comment by kurobeats** [comment]
> It's in the pipeline but other tasks had a higher priority. In the meantime, `libpod.conf` and the CLI flags allow using another init binary as a temporary workaround.

Where can we find the workaround?

**Comment by muayyad-alsadi** [comment]
> Where can we find the workaround?

you can pass any init using `podman run --init-path=` like `dumb-init`.

also in `libpod.conf` there is a line for `init_path=""`
