### ISSUE TITLE
podman login should use credential helper if configured

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#1675]
`docker login' uses a credential helper.  If you try to do `docker login` without a credential helper in play you get a warning:

```
# docker login https://quay.io
Username: tomsweeneyredhat
Password:
WARNING! Your password will be stored unencrypted in
/root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

`podman login` should also use a credential helper as Docker does.

**Comment by vrothberg** [comment]
After reading this issue, I realized that podman doesn't offer docker's `--password-stdin` flag. Is there a reason for that? If not, we could this together in the same PR.

**Comment by rhatdan** [comment]
No reason, just an oversight.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Can you add this feature --password-stdin?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack

**Comment by rhatdan** [comment]
@QiWang19 Could you look into the passwork helper now also?

**Comment by rhatdan** [comment]
@QiWang19 Did you ever look into this?

**Comment by QiWang19** [comment]
I saw the code in containers/image, podman already supported configure `"credHelpers"`, but only works for root user.
https://github.com/containers/image/blob/ff926d3c79684793a2135666a2cb738f44ba33dc/pkg/docker/config/config.go#L43

**Comment by rhatdan** [comment]
I thought we got this to work if we did not enter the user namepspace on podman login?

**Comment by QiWang19** [comment]
I mean the pulling error you mentioned. 
login/logout works for non-root if getting out of the user namespace, but pull command can't read the credential.

**Comment by rhatdan** [comment]
Yes we have to work with @giuseppe on that one.  Perhaps we grab credentials before going into user namespace.

**Comment by rhatdan** [comment]
Or can we specify a user name to get the credentials?

**Comment by sdlarsen** [comment]
Was this ever fixed?

**Comment by mheon** [comment]
Was closed by PR https://github.com/containers/libpod/pull/3015 in Podman 1.3.0. Are you still seeing it?

**Comment by TomSweeneyRedHat** [comment]
I'm not convinced that credential-helpers and credstores are handled as they should be by podman/buildah login/logout.  There are certainly no tests or documentation anywhere that I can find.  I'm going to reopen this until we can at least verify, fix if necessary, and create appropriate tests and documentation.

**Comment by sdlarsen** [comment]
Yes @mheon, I see it. Running podman 1.8.0

**Comment by rhatdan** [comment]
@QiWang19 I believe we support credential helpers now, can we close this issue?

**Comment by TomSweeneyRedHat** [comment]
I've not been able to get this to work, might be a personal issue.  I'm also not able to see any documenation.  If you can point me to documenation that shows how this works, we can close this.  Otherwise as a minimum we need to document this before closing this issue.

**Comment by vrothberg** [comment]
@QiWang19 can you help Tom test?

**Comment by QiWang19** [comment]
Open a PR https://github.com/containers/image/pull/950 to add documentation for credential helpers, but this only works for root, rootless login with credential helper doesn't work because of the d-bus issue.  Should add note to the documentation that credential only works for root, and close this issue, or just leave this open?  I already have filed a issue https://github.com/containers/libpod/issues/4123 about the rootless podman using credential helper.
