### ISSUE TITLE
the issue about podman login

### ISSUE THREAD

**Issue by coderwangke** [containers/libpod#1690]
**Steps to reproduce the issue:**

#### steps
docker : docker login docker.io/wangke007/buildah-test:latest 
podman : podman login docker.io/wangke007/buildah-test:latest 

#### result
docker get Login Succeeded, but podman return a issue:
error authenticating creds for "docker.io/wangke007/buildah-test:latest": pinging docker registry returned: error pinging registry docker.io/wangke007/buildah-test:latest, response code 404 (Not Found)

**Comment by rhatdan** [comment]
What version of podman?
@umohnani8 @mtrmac @TomSweeneyRedHat PTAL

**Comment by umohnani8** [comment]
So docker picks up the registry you are trying to log into from a registry/repo/image path as well. Should be an easy fix, but curious to why would you ever want to do that and not just do podman login docker.io?

**Comment by mtrmac** [comment]
Yeah—this looks potentially misleading, suggesting that `podman login docker.io/ns1` and `podman login docker.io/ns2` maintained two independent login records, which does not happen.

**Comment by rhatdan** [comment]
Is this just docker login always attempting to login as docker.io?  If you did 

docker login quay.io/wangke007/buildah-test:latest

Does it do the right thing?

**Comment by umohnani8** [comment]
@rhatdan yeah it asks for credential for quay.io then. Also doing it with the full path, it doesn't care about what user you put in the path, it will still ask for username and password again. Like I can do `docker login docker.io/umohnani8/blah` and then login as `umohnani` instead.

**Comment by umohnani8** [comment]
@mtrmac @rhatdan  so what do we want do about this?

**Comment by rhatdan** [comment]
I think we should match docker's behaviour and grab the registry from the image name.
