### ISSUE TITLE
Set slirp4netns MTU to 65520

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#1732]
Running slirp4netns with `--mtu=65520` significantly improves the throughtput ([1.07 Gbps -> 9.21 Gbps](https://github.com/rootless-containers/slirp4netns/tree/777bdccceffa5bee38dbfd9eefc06628cc160ff6#iperf3-netns---host )) .

I also would like to hear performance & stability feedback about `--mtu=65520` from Podman community.

@giuseppe

**Comment by giuseppe** [comment]
I've played a bit with `--mtu=65520` and I cannot see any problem with podman

**Comment by giuseppe** [comment]
should it be the default for slirp4netns?

**Comment by AkihiroSuda** [comment]
`slirp4netns` itself still uses 1500 as the default.
But RootlessKit (which is used by Usernetes and my PR for Docker) overrides the default to 65520.

So I suggest using 65520 as the Podman default.

**Comment by giuseppe** [comment]
I'll prepare a patch once the slirp4netns available on Fedora is updated and has the `--mtu` option

**Comment by rhatdan** [comment]
@giuseppe has this been fixed?

**Comment by giuseppe** [comment]
no, this is still open

**Comment by rhatdan** [comment]
@AkihiroSuda @giuseppe What is going on with this?

**Comment by giuseppe** [comment]
opened PR: https://github.com/containers/libpod/pull/2626

**Comment by brandon1024** [comment]
A few people have reported significant performance hit with the new default MTU of 65520. This caught me today too, I was seeing terrible slowness that went away when I changed the MTU back to 1500. I'm still scratching my head at this one.

https://github.com/containers/podman/issues/6945
https://www.reddit.com/r/linuxadmin/comments/o6e1x6/performance_issues_when_running_nginx_reverse/

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
@brandon1024 Please do not comment on old issues/PRs. If you have a reproducer create a new issue.
