### ISSUE TITLE
no network access when trying to ping from container

### ISSUE THREAD

**Issue by miabbott** [containers/libpod#1752]
/kind bug

Using CentOS AH Continuous, we found that after upgrading to `podman-0.10.1.3-2.git6e1aeb0.el7`, our tests were unable to ping from a container started via `podman`

```
# rpm -q podman
podman-0.10.1.3-1.gitdb08685.el7.x86_64

# podman run --rm docker.io/busybox ping -c 3 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=47 time=11.373 ms
64 bytes from 1.1.1.1: seq=1 ttl=47 time=11.172 ms
64 bytes from 1.1.1.1: seq=2 ttl=47 time=11.176 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 11.172/11.240/11.373 ms

# rpm-ostree deploy 7.2018.280
Resolving version '7.2018.280'
1 metadata, 0 content objects fetched; 338 B transferred in 0 seconds
22 metadata, 0 content objects fetched; 6 KiB transferred in 0 seconds
39 metadata, 0 content objects fetched; 11 KiB transferred in 0 seconds
1 metadata, 0 content objects fetched; 338 B transferred in 0 seconds
Staging deployment... done
Freed: 6.9 kB (pkgcache branches: 0)
Upgraded:
  podman 0.10.1.3-1.gitdb08685.el7 -> 0.10.1.3-2.git6e1aeb0.el7
Run "systemctl reboot" to start a reboot

...

# rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
                   Version: 7.2018.280 (2018-10-26T16:05:39Z)
                    Commit: 73a6acd439b1b4f6e59191713d611cf8e0891a59c441ed231da3b404a939d4cc

  ostree://centos-atomic-continuous:centos-atomic-host/7/x86_64/devel/continuous
                   Version: 7.2018.279 (2018-10-26T14:03:42Z)
                    Commit: cf664a8b1e4a6c1a20581c2634fc24539b5adba4cc63ff4c87cfd143d0d217a1

# rpm -q podman
podman-0.10.1.3-2.git6e1aeb0.el7.x86_64

# podman run --rm docker.io/busybox ping -c 3 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

No SELinux denials or any other relevant errors found in the journal.

**Comment by mheon** [comment]
@rhatdan @lsm5 What were the differences between 0.10.1.3-1 and 0.10.1.3-2 - this sounds like a packaging issue?

**Comment by rhatdan** [comment]
In ability to ping either means the network is not working?  We dropped CAP_NET_RAW?

**Comment by baude** [comment]
The OS/VM in question here is booting with firewalld disabled.  Enabling firewalld gets this working.  Also, leaving firewalld disabled but disabling docker also allows traffic by default to work.  docker needs to be disabled on boot for this to work.  We are looking into it further with @miabbott

**Comment by miabbott** [comment]
I `git bisect`ed to e2aef6341de2d371cec3e6085cb539dfadede8db

**Comment by rfrush** [comment]
I'm getting the same behavior (container cannot ping).   Docker was enabled at boot on my system, and firewalld is enabled.   What additional information can I dig up for you to help?

**Comment by dagrayvid** [comment]
I'm having the same issue on podman 0.10.1.3-4 installed from latest-rhel76-extras this morning.

**Comment by lsm5** [comment]
On Fri, Nov 02, 2018 at 02:12:04PM -0700, Matthew Heon wrote:
> @rhatdan @lsm5 What were the differences between 0.10.1.3-1 and 0.10.1.3-2 - this sounds like a packaging issue?

* Fri Oct 26 2018 Frantisek Kluknavsky <fkluknav@redhat.com> - 0.10.1.3-2.git6e1aeb0
- rebase to 6e1aeb06f86bfed7045be19c8e8b09c1bf5ba55f
- rebase cri-o to 1.12

@fkluknav

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by baude** [comment]
@rfrush can you reveal OS details?

**Comment by rfrush** [comment]
@baude:

Here you go!

```
$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
$ uname -a
Linux hostname.domain 4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by baude** [comment]
@rfrush any chance you can hop on irc.freenode.net in #podman so I can figure out how to replicate your setup? I'm currently not able to reproduce your results on F28.

**Comment by rfrush** [comment]
@baude   I'll have to work on this on Thursday.  I don't yet have an IRC account, and have limited time today to work on this.

**Comment by baude** [comment]
@rfrush and I did a little debugging and his issue is a little more narrow.  He is not able to get network traffic routing when rootless and firewalld is active.

**Comment by baude** [comment]
@rfrush in your case, we have to be careful to not focus on ping because ping requires certain privileges that are not there by default for a rootless container.  I verified this to be true.  Can you verify that the following works?

podman run -it --rm alpine wget http://github.com/containers/libpod

**Comment by rfrush** [comment]
@baude -

The container does, indeed, have access to get things from the network when run from a mortal account.  See below.   Now all I have to do is figure out how to allow the container to respond to networking requests.  Can you please point me to a good tutorial?   

```
[phred@islnx001 ~]$ podman run -it --rm alpine wget http://github.com/containers/libpod
Connecting to github.com (192.30.253.113:80)

Connecting to github.com (192.30.253.112:443)
libpod               100% |***********************************************************************|   158k  0:00:00 ETA
```
Thanks

**Comment by baude** [comment]
@dagrayvid can you hop into #podman on freenode and we can discussed?

**Comment by NikitaKharkov** [comment]
Hello! Tell me please: did you resolve this issue? I mean reaching to domain names? Because in version 3.4 I still have such a problem. As a developer, I spend a lot of time finding this DevOps issue and find the solution only in the article on Medium.
Maybe I missed some configuration on docker-compose.yml?..

**Comment by mheon** [comment]
Considering he was on podman v0.10 and you are on Podman v3.4, you are almost certainly seeing a different issue. Please file a new bug with details.
