### ISSUE TITLE
improve "open /etc/subuid: no such file or directory" error message

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#1755]
Existing openSUSE deployments will run into the issue that `/etc/sub{g,u}id` are not present as no (base) package added those; useradd and usermod don't create those files. I've fixed this via the `shadow` package now adding those files so that new installs and new users have proper entries but that doesn't solve the issue for existing users.

In other words, existing users don't have this file and will always run into Podman failing with "open /etc/subuid: no such file or directory". I think Podman should catch those errors and guide the user a bit more, maybe even printing the corresponding section from `podman (1)`.

**Comment by giuseppe** [comment]
should we move this issue to `containers/storage`?  The logic for handling `/etc/sub{g,u}id` is there

**Comment by rhatdan** [comment]
SGTM

**Comment by vrothberg** [comment]
I opened https://github.com/containers/storage/issues/231. I suggest keeping the issue here open until https://github.com/containers/storage/issues/231 is merged and vendored.

**Comment by giuseppe** [comment]
@rhatdan SGTM

**Comment by vrothberg** [comment]
I am okay with both solutions :+1:

**Comment by rhatdan** [comment]
I think we need more documentation, for different platforms as the evolve.  RHEL and Centos also do not  fully support podman as non root yet.

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat Any movement on this?  Better documentation in man pages?

**Comment by vrothberg** [comment]
@rhatdan, for me https://github.com/containers/libpod/pull/1795 solved the issue. I am not sure if we could improve the situation besides making that clear in the RHEL docs.

**Comment by rhatdan** [comment]
Ok closing.

**Comment by afbjorklund** [comment]
I didn't bother with fixing `adduser` in busybox, so just hacked `/etc/subuid` and `/etc/subgid`.
Only added `newuidmap` and `newgidmap` binaries (from [shadow](https://github.com/shadow-maint/shadow)), but it seems to be enough...
