### ISSUE TITLE
podman-run manpage: --log-driver and --log-opt options are unclear

### ISSUE THREAD

**Issue by tierpod** [containers/libpod#1763]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**

I can't find documentation about "--log-driver" and "--log-opt" podman run command options. podman-run manpage has no information about supported log drivers list and supported log options.

**Steps to reproduce the issue:**

1. Run "man podman-run" or open https://github.com/containers/libpod/blob/master/docs/podman-run.1.md

**Describe the results you expected:**

Would like to see supported logging drivers list and supported logging options.

**Comment by rhatdan** [comment]
Currently we don't support alternative log-drivers.  Man page needs work though on this.

```
       --log-driver="json-file"

       Logging driver for the container. Default is defined by daemon
       --log-driver flag.

       Warning: the podman logs command works only for the json-file and
       journald logging drivers.

       --log-opt=[]

       Logging driver specific options.

       path=/var/log/container/mycontainer.json: Set the path to the container
       log file.

```

**Comment by vrothberg** [comment]
We might check other docs for the `daemon` term.

**Comment by mheon** [comment]
Closing as we merged a patch to fix
