### ISSUE TITLE
Can't pull an image in rootless mode with 0.11.1 

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#1801]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: # **kind bug**

**Description**

I can't pull an image using podman in rootless mode.

After downgrading to `1:0.10.1.3-4.gitdb08685.fc29` it works just fine.

**Describe the results you received:**
```
$ podman pull registry.fedoraproject.org/fedora:29
could not get runtime: database run root /run/user/1000/run does not match our run root /run/user/1000: database configuration mismatch

$ ll /run/user
total 0
drwx------. 15 tt tt 400 nov 12 13:52 1000

$ ll /run/user/1000
total 0
srw-rw-rw-. 1 tt tt   0 nov 12 13:37 bus
drwx------. 3 tt tt  60 nov 12 13:37 dbus-1
drwx------. 2 tt tt  60 nov 12 13:41 dconf
drwx------. 3 tt tt  60 nov 12 13:38 gnome-shell
drwx------. 2 tt tt  40 nov 12 13:38 gnupg
dr-x------. 2 tt tt   0 nov 12 13:38 gvfs
drwx------. 2 tt tt 120 nov 12 13:40 keyring
drwxr-x--x. 3 tt tt  60 nov 12 13:52 libpod
drwxrwxr-x. 2 tt tt  60 nov 12 13:38 Nextcloud
srw-rw-rw-. 1 tt tt   0 nov 12 13:37 pipewire-0
drwx------. 2 tt tt  80 nov 12 13:37 pulse
drwx------. 4 tt tt  80 nov 12 13:52 run
drwxr-xr-x. 2 tt tt  80 nov 12 13:37 systemd
drwx------. 2 tt tt  40 nov 12 13:52 vfs-containers
drwx------. 2 tt tt  40 nov 12 13:52 vfs-layers
srwxrwxr-x. 1 tt tt   0 nov 12 13:38 wayland-0
-rw-rw----. 1 tt tt   0 nov 12 13:38 wayland-0.lock

$ ll /run/user/1000/run
total 0
drwx------. 2 tt tt 40 nov 12 13:52 vfs-containers
drwx------. 2 tt tt 40 nov 12 13:52 vfs-layers
```

**Describe the results you expected:**
The image would be pulled to a rootless store.

**Output of `podman version`:**

```
Version:       0.11.1
Go Version:    go1.11
Git Commit:    "8967a1d691ed44896b81ad48c863033f23c65eb0-dirty"
Built:         Thu Nov  8 22:35:40 2018
OS/Arch:       linux/amd64
```

This is F29.

**Comment by mheon** [comment]
Alright.

The solution if you want to remove the DB (and all containers with it): `rm -rf $HOME/.local/share/containers`

The slightly more complicated solution to preserve your existing containers:

Make a copy of `/usr/share/containers/libpod.conf `in the `.config` folder in your home directory.
Comment out everything except `tmp_dir`
Change `tmp_dir` to `/run/user/1000/run` (the first path from the error message Podman spits out)
Everything should go back to working

This will probably come up more than once so I'll add it to the troubleshooting doc.

**Comment by mheon** [comment]
Partial fix in #1802 

Need more support on our end to make this transition as graceful as possible.

**Comment by debarshiray** [comment]
Thanks for updating `troubleshooting.md`.

However, it would be nice if we could make this somewhat transparent to the user. I am thinking of someone hacking on Silverblue using a [fedora-toolbox](https://github.com/debarshiray/fedora-toolbox) based development environment. It will be pretty jarring if the toolbox containers suddenly disappear one day after an update. Especially because the purpose of `fedora-toolbox` is to lighten the cognitive burden of the underlying container setup.

**Comment by mheon** [comment]
We think we have a way forward that will not require a user-facing breaking
change, but it involves a large number of changes to core libpod init
functions, so it could be a few days before it lands.

**Comment by watersb** [comment]
The workaround, with a modified copy of `libpod.conf` in `${HOME}/.config`, is not working for me.

**Comment by mheon** [comment]
Sorry - the directory is ~/.config/containers - that was my mistake

**Comment by watersb** [comment]
Ok, trying a `libpod.conf` in `${HOME}/.config/containers`

`$ podman ps
error creating libpod runtime: database tmp dir /run/user/1000/libpod/tmp does not match our tmp dir /run/user/1000/run: database configuration mismatch
`
My `${HOME}/.config/containers/libpod.conf` file has all lines commented out, except for 

`tmp_dir = "/run/user/1000/run"`

I am willing to troubleshoot this a bit; since I have been using Fedora Atomic Silverblue, I have my development environment in there, 19GB, and would prefer to keep those containers.

But I will need some hand-holding on where to look. Most of my Linux skills are Gentoo-ish.

**Comment by mheon** [comment]
Use the full path from the error message - the first one listed (from the
database, not the one labeled as "ours").

The error really needs to be improved - it's trying to say that a
configured path for libpod files no longer matches what the database was
created with (which can cause very bad things - losing track of running
containers, for example). It's just very not clear what field isn't
matching (libpod temporary files directory) and how to fix this

**Comment by watersb** [comment]
I am willing to hack on `fedora-toolbox`, if I can get closer to a work-around.

`$ podman version
Version:       0.11.2-dev
Go Version:    go1.11.2
OS/Arch:       linux/amd64
`
on Fedora Rawhide, using `rpm-ostree`.

**Comment by mheon** [comment]
I'm in the process of patching libpod to respect the paths in the database
if they're not explicitly overridden, which should solve this, but it's
proving to be slow work. I'm hopeful it will be done sometime tomorrow, and
we can get a new, fixed build out. In the meantime, it might be easier to
just revert to an older package

**Comment by watersb** [comment]
Great! I will try again in a day or three. Thanks.

**Comment by TomasTomecek** [comment]
Given Matt's advices, I'm going to close this one as the issue is resolved for me. Please keep those UX fixes coming.
