### ISSUE TITLE
Add reflinks suport to the vfs storage driver

### ISSUE THREAD

**Issue by robmv** [containers/libpod#1815]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind feature**

**Description**

In order to speed up rootless container creation using the vfs storage driver, it could be possible to use reflinks when available, for example over Btrfs or XFS (with reflink enabled format), when creating the container tree. The speed of container creation is one the drawbacks of the vfs driver, since it has to copy the entire tree, with reflinks this could be reduced significantly.

**Comment by rhatdan** [comment]
There is nothing that podman needs to do to support XFS Reflink.  This needs to be configured in the underlying storage at storage creation time.  When you create the mount point for your home dir with XFS you need to specify the mkfs that you want to use reflink.  Then when you run podman it will take advantage.  I sent an email to the xfs storage team a while ago to ask them to turn it on reflink by default but they have not up to this point to the best of my knowledge.

I will ping them again.

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1650453

**Comment by giuseppe** [comment]
Enabling reflinks in the file system is not enough, we will need to add support for it to containers/storage to try a clone first then do a raw copy.  AFAICS, we are using "copy with tar" for vfs.

**Comment by giuseppe** [comment]
is it possible to move this issue to containers/storage (https://blog.github.com/changelog/2018-10-30-issue-transfer/)?  I am not an admin on libpod so I cannot do it
