### ISSUE TITLE
pypodman commit: options "--change", "-f" and "--message" don't take effect

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#1867]
**kind bug**

**Description**
After fix #1743 , `pypodman commit` can run without any error and a commited image can be created. But options `--change`, `-f docker` and `--message` don't take effect.

**Steps to reproduce the issue:**
On Remote:
```
root@rhel8-1 ~]# podman ps -a
CONTAINER ID   IMAGE                             COMMAND     CREATED          STATUS                     PORTS   NAMES         IS INFRA
afacc34a5e9a   docker.io/library/fedora:latest   /bin/bash   13 seconds ago   Exited (0) 4 seconds ago           test-commit   false
```

On Host:
1. `~/.local/bin/pypodman -l root --host 192.168.122.213 commit --change ENTRYPOINT=/bin/sh --change LABEL=blue=image --message "commit test msg" -f docker test-commit image-commited`

2. `~/.local/bin/pypodman -l root --host 192.168.122.213 inspect image-commited`

**Describe the results you received:**
```
[
 { ......
   "Comment": "",
   ......
    "ContainerConfig": {
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "HOSTNAME=",
                "container=podman",
                "FBR=f29",
                "DISTTAG=f29container",
                "FGC=f29"
            ],
            "Cmd": [
                "/bin/bash"
            ],
            "WorkingDir": "/"
        },
   ......
  "Labels": null,
   ......
 }
]
```

**Describe the results you expected:**
I did the same thing with `podman commit --change ENTRYPOINT=/bin/sh --change LABEL=blue=image --message "commit test msg" -f docker test-commit image-commited1` **on Remote**:
```
{
  .......
  "comment": "commit test msg",
  .......
  "containerconfig": {
    "env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "TERM=xterm",
      "HOSTNAME=",
      "container=podman",
      "FBR=f29",
      "DISTTAG=f29container",
      "FGC=f29"
    ],
    "entrypoint": [
      "/bin/sh"
    ],
    "cmd": [
      "/bin/bash"
    ],
    "workingdir": "/",
    "labels": {
      "blue": "image"
    }
  },
  .......
  "labels": {
    "blue": "image"
  },
  .......
}
```
**Additional information you deem important (e.g. issue happens only occasionally):**
Besides, on host if I execute the `pypodman` command without `-f docker`, the image should not be created and a error message should be printed. But the fact is above wrong image can be still created.
If I do this on remote with `podman`:
```
[root@rhel8-1 ~]# podman commit --change ENTRYPOINT=/bin/sh --change LABEL=blue=image --message "commit test msg" test-commit image-commited
messages are only compatible with the docker image format (-f docker)
```
This result probably tells us option `-f` can not work too. 

And, I test option `--author` as well, it can work properly.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@jwhonce PTAL
