### ISSUE TITLE
Feature: Native ZFS Storage Driver

### ISSUE THREAD

**Issue by guygma** [containers/libpod#1870]
[//]: # **kind feature**

**Description**

Is there planned support for a proper `zfs` driver for the container storage (or documentation on one that already exists)? If not, this would be a very nice feature to have. It seems it is something that Docker supports so there is at least a reference implementation in a similar infrastructure.

**Describe the results you received:**

output of `podman --storage-driver fuse-overlay`:

```
time="2018-11-27T00:07:34-05:00" level=error msg="Failed to GetDriver graph fuse-overlayfs /var/lib/containers/storage" 
could not get runtime: failed to GetDriver graph fuse-overlayfs /var/lib/containers/storage: driver not supported
```

**Describe the results you expected:**

The `vfs` driver works, but I would have expected one of the overlay options to work or there to be another way to take advantage of the COW capabilities of zfs.

**Additional information you deem important (e.g. issue happens only occasionally):**

output of `podman --storage-driver zfs info` (didn't find any documentation but just for shits and giggles...):

```
could not get runtime: Unknown option overlay.mountopt
```

**Output of `podman version`:**

```
Version:       0.11.1.1
Go Version:    go1.11.2
Git Commit:    ""
Built:         Mon Nov 26 23:44:37 2018
OS/Arch:       linux/amd64
```

**Output of `podman info`:**
```
time="2018-11-27T00:05:13-05:00" level=error msg="'overlay' is not supported over zfs" 
could not get runtime: 'overlay' is not supported over zfs: backing file system is unsupported for this graph driver
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**

bare-metal arch install, zfs on root with separate /home, /var, and /opt as zfs datasets. The /var dataset has the zfs property `overlay` set to `on`.

**Comment by guygma** [comment]
OK - a bit more digging and tried a plain setup guessing at sane settings and following the error log. I guess you *do* have ZFS support in the graph driver. Nice! I mounted a dataset at `/var/lib/containers/storage` with `overlay=on` and had to comment out a couple lines in the `/etc/storage.conf` (as you may have guessed from the output I included as "additional information I deem important").  I have two related items then. 

First, a question: Is there documentation of this feature anywhere? A grep of the podman man-page yields no results for "zfs|ZFS". The only indication I found that ZFS *may* be supported is a reference to the existence of a driver on [this "practical introduction" from RHEL](https://developers.redhat.com/blog/2018/02/22/container-terminology-practical-introduction/). 

Also, a suggestion/request: I think there should have been a more elegant response to the command `podman --storage-driver=zfs info` given that there is (apparently) such a driver and that the `/var` filesystem was a zfs dataset. Is it possible that the error had to with the mountpoint `/var/lib/containers/storage` was not defined as a dataset itself and instead just part of the filesystem mounted at `/var`? If this is the case, an error message indicating as much would be helpful. If, however, the specific mountpoint of the host dataset containing the relevant filesystem is not a hard requirement, my next best guess at the root cause of the issue I saw is simply a choke in the config file. If the way that I indicated on the command line that I want to use a ZFS backend is not the cannonical way to override the complete set of config options required to successfully change backends, may you please point me to the documentation that describes the proper way to do this for more complex setups (or just let me know it does not yet exist)?

Thanks! Enjoying this tool and its cousins so far.

**Comment by mheon** [comment]
I do believe that c/storage does provide support for ZFS, but you'll likely
need to edit /etc/containers/storage.conf and manually set the storage
driver from overlay to ZFS.

**Comment by mheon** [comment]
For point 1 - I think the proper place is probably the storage.conf manpage (and maybe noting in the manpages for Podman that storage options are sourced from `storage.conf` if not explicitly set, and valid values are the same). I can't see any listing of valid drivers right now, so I think we do need to add that.

For point 2 - you can set storage driver in `/etc/containers/storage.conf` and not need to pass the command line option again.

**Comment by mheon** [comment]
(Details on `storage.conf` can be found via `man storage.conf`, but it's a little sparse in there - could definitely use some improvement)

**Comment by rhatdan** [comment]
storage.conf is part defined here: https://github.com/containers/storage/blob/master/docs/containers-storage.conf.5.md
Open a PR with changes you would like to see.

**Comment by rhatdan** [comment]
@guygma zfs should work, but I don't know of anyone who has tried it out.

**Comment by mheon** [comment]
I think we have an action item here to update the c/storage storage.conf manpage to include valid storage drivers. I've opened https://github.com/containers/storage/pull/250 to handle that.

**Comment by guygma** [comment]
Thank you all for the clarification!  The zfs driver did end up working for me, so I agree it would be nice to have that made a bit more clear in the documentation. I didn't know to look in `man storage.conf` but indeed it does leave some breadcrumbs for the motivated. My case for getting that container up and running was in a VM so I haven't used anything long-term on ZFS yet, but all my bare-metal systems are ZFS on root now so next time I need a container, this will be put to the test again.

**Comment by mheon** [comment]
C/storage manpages have been updated, so I'm going to close. If you encounter any further issues with ZFS, feel free to repoen
