### ISSUE TITLE
pypodman inspect: option "size" should be option "--size"

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#1876]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**
For keeping consistent with `podman`, the option `size` for **`pypodman`** should be `--size`, then `pypodman` will have the same usage as `podman` has:
https://github.com/jwhonce/libpod/blob/842320d2f7922c2ea66f57a07d0a5f67d980de48/contrib/python/pypodman/pypodman/lib/actions/inspect_action.py#L26

**Comment by rhatdan** [comment]
@Edward5hen Please open a PR to fix this.
