### ISSUE TITLE
podman stop should not fail when a container is stopped

### ISSUE THREAD

**Issue by pkubatrh** [containers/libpod#1877]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: **kind bug**

**Description**

Trying to stop an already stopped container results in a failure (error status 125)

**Steps to reproduce the issue:**

$ podman run fedora bash -c "echo Hello World!"
Hello World!
$ podman ps -a
...
5cc9a01f27d9  docker.io/library/fedora:latest  bash -c echo Hell...  5 seconds ago   Exited (0) 5 seconds ago            serene_perlman
...
$ podman stop 5cc9a01f27d9
container is stopped
$ echo $?
125

**Describe the results you received:**
`podman stop` failure

**Describe the results you expected:**
`podman stop` success

**Additional information you deem important (e.g. issue happens only occasionally):**
Similar to #575 which should have been fixed by https://github.com/containers/libpod/commit/b1a8d769b84c52ea5ea74263cff6f582b1bdfcf0 so sounds like a regression.

Using podman version from commit https://github.com/containers/libpod/commit/39560500fcc504bea70d48759f44c64f680c2ef2

**Comment by mheon** [comment]
Probably a regression when we parallelized stop - #1879 should fix

**Comment by baude** [comment]
closing as appears to be fixed
