### ISSUE TITLE
Docker image to be used to play with buildah

### ISSUE THREAD

**Issue by cmoulliard** [containers/libpod#1883]
Is there a Docker image that we could use to play with Buildah on non Linux's machine such as Macos ?

**Comment by rhatdan** [comment]
@cmoulliard  @ipbabble are we all set with this issue?  Can I close it?

**Comment by baude** [comment]
where do we stand with this? OSX folks, please give the remote client a try ...

**Comment by rhatdan** [comment]
Closing the issue.
