### ISSUE TITLE
Merge libpod funcionality into CRI-O

### ISSUE THREAD

**Issue by smarterclayton** [containers/libpod#1884]
It appears that buildah is limited to working on containers it creates itself.  One direction we are considering for the OpenShift build side is to execute builds only within containers created by the existing runtime (crio or docker).  Can buildah perform commands against other containers, and if not, what would it take to support that?

**Comment by rhatdan** [comment]
Sadly this is still in the same state.  Although some sub-packages of libpod are starting to get added to CRI-O

**Comment by rhatdan** [comment]
We have opened talks on this again.

**Comment by vrothberg** [comment]
I am closing this issue in favor of https://github.com/containers/libpod/issues/2791
