### ISSUE TITLE
checkpoint tests fail on F29

### ISSUE THREAD

**Issue by baude** [containers/libpod#1891]
The checkpoint tests appear to fail on F29; I am also able to reproduce manually. I have asked to disable them for F29 on #1890 .

@adrianreber is this something you can look at?

**Comment by adrianreber** [comment]
I opened PR https://github.com/containers/libpod/pull/1895 to be able to see the test failures. On my F29 system I was not able to see these failures.

**Comment by adrianreber** [comment]
I removed the commit to disable checkpoint testing on F29 but I cannot see any F29 checkpoint related errors. Is there any other place I can see the checkpoint related errors on F29?

**Comment by adrianreber** [comment]
It's selinux related. Still trying to better understand it, but right now I think it needs selinux policy changes. I would just open a ticket in bugzilla and see where that discussion leads.

**Comment by adrianreber** [comment]
Depending on the version of `container-selinux` I either see:

```
type=AVC msg=audit(1543862223.631:119): avc:  denied  { connectto } for  pid=870 comm="top" path=002F6372746F6F6C732D70722D393230 scontext=system_u:system_r:container_t:s0:c536,c922 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=unix_stream_socket permissive=0
```
which is with `container-selinux-2.55-1.fc28.noarch`

and with `container-selinux-2.76-1.git87fae85.fc28.noarch` I get:

```
type=AVC msg=audit(1543955552.411:135): avc:  denied  { append } for  pid=868 comm="top" path="/var/lib/containers/storage/overlay-containers/f2054a30f6770db75ae698f911581dfdcc42de712f2c6e8facaed73b718745bb/userdata/dump.log" dev="sda1" ino=4742 scontext=system_u:system_r:container_t:s0:c467,c1020 tcontext=unconfined_u:object_r:container_var_lib_t:s0 tclass=file permissive=0
```

CRIU uses ptrace to stop the process, but the memory from the process is not extracted using ptrace but with the help of what is called parasite code. The parasite code is injected into each dumped process and runs as a daemon which communicates which communicates with main CRIU process and which uses shared memory to transfer the memory of the process fast out of the process.

So the older policy seems to deny access for the CRIU process to talk to the parasite code `connectto`. The newer policy seems to deny something else. Not 100% sure if this happens before the `connectto` or after the `connectto` but SELinux denies accessing the CRIU log file. The parasite code, as well as the main CRIU process are logging to the same file. CRIU, which runs outside of the container can write to the log file, but the process infected by the parasite also tries to access that log file.

So writing to the log file currently seems to be main problem.

**Comment by rhatdan** [comment]
First one looks like the container process is attempting to connect back to a socket created by the podman command?  Is this something varlink does?

The second one looks like a labeling issue.  container_var_lib_t usually means something is mislabled.

In F28 we had issues with container-selinux

dnf -y reinstall container-selinux
restorecon -R -v /var/lib/containers

See if this fixes the issues.

**Comment by adrianreber** [comment]
For me the first one is CRIU talking to its injected parasite code. Not 100% sure but from what CRIU usually does this would make sense.

Running `restorecon` does not help.

**Comment by rhatdan** [comment]
@adrianreber Could you point me where podman is injecting the parasite code.  We might want to label the socket based on the container process label, which would then allow the access.  But this could be somewhat complicated.

**Comment by rhatdan** [comment]
Does criu cause top to connecto a socket?

**Comment by rhatdan** [comment]
Will need this PR merged to make it happen.

https://github.com/opencontainers/selinux/pull/38

Then we should be able to just call label.SetSocketLabel(processlabel) in podman before setting up crio to make this work.

**Comment by adrianreber** [comment]
CRIU is creating the socket here:

https://github.com/checkpoint-restore/criu/blob/criu-dev/compel/src/lib/infect.c#L362

**Comment by adrianreber** [comment]
@rhatdan : What about the other message where the parasite code tries to write to CRIU's logfile:

```
type=AVC msg=audit(1543955552.411:135): avc:  denied  { append } for  pid=868 comm="top" path="/var/lib/containers/storage/overlay-containers/f2054a30f6770db75ae698f911581dfdcc42de712f2c6e8facaed73b718745bb/userdata/dump.log" dev="sda1" ino=4742 scontext=system_u:system_r:container_t:s0:c467,c1020 tcontext=unconfined_u:object_r:container_var_lib_t:s0 tclass=file permissive=0
```

Can this also be solved?

**Comment by rhatdan** [comment]
@adrianreber Where is the dump log created?  Are their actually messages in the log that are missing, or is this just the log file gets created and leaked to the processes inside of the container?

**Comment by adrianreber** [comment]
The `dump.log` file is created in `c.bundlePath()`, but with the changes from above mentioned pull request (1962) these AVC messages are gone and checkpoint/restore works again in F28 and F29.

**Comment by adrianreber** [comment]
This is now fixed with #1962, I will open a PR to re-enable checkpoint/restore tests on F29.

**Comment by adrianreber** [comment]
@rhatdan my testing was not complete. On F29 after a reboot I still get:

```
type=AVC msg=audit(1544711649.744:674): avc:  denied  { append } for  pid=4660 comm="top" path="/var/lib/containers/storage/overlay-containers/15713d242adf58fbfd01792bb7feb47b9e826b0b1f51836cb076c1e7f4f8ee13/userdata/dump.log" dev="sda1" ino=4335 scontext=system_u:system_r:container_t:s0:c153,c616 tcontext=unconfined_u:object_r:container_var_lib_t:s0 tclass=file permissive=0
```

Running `restorecon -R -v /var/lib/containers` does not change anything (as far as I can tell).

Interestingly this only happens when running Podman directly. If running from the test cases through ginkgo, this error does not happen. Could this be related to ginkgo putting the containers on `/tmp`?

**Comment by rhatdan** [comment]
Ok we have to look into who is creating dump.log and whether we want to label it correctly.

One option would be to allow the append, without a create, which means the container would only be able to append to the log file if it was leaked into the container, not able to go and start writing to container_var_lib_t by default.

**Comment by adrianreber** [comment]
CRIU creates dump.log at

https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/log.c#L172

We could create the log file in Podman, label it and CRIU should just overwrite (O_TRUNC) the existing file. Is that possible?

**Comment by baude** [comment]
whats the deal here fellas?

**Comment by adrianreber** [comment]
All checkpoint/restore tests are enabled on the F28, F29 and Ubuntu test runs. RHEL7 not yet, as its CRIU is still too old and so the tests are automatically skipped. Closing this now, as it is no longer a problem.
