### ISSUE TITLE
Question: Allowing users to expose other protocols (sctp) from the pod to the host

### ISSUE THREAD

**Issue by arizvisa** [containers/libpod#1909]
Is there some way to expose other protocols such as "sctp" (rather than "tcp" and "udp") or is it left up to firewall rules? If you're using podman's command line, something similar to `$ podman -p $PORT:$PORT/sctp ...`

Doing a (very) quick search, it seems that this limitation might be referenced at https://github.com/containers/libpod/blob/master/libpod/oci.go#L185. Is this where it's at and is the reason being that golang doesn't natively support sctp or some of the other protocols?

**Comment by mheon** [comment]
It's less a Golang issue and more of a CNI issue, nearest I can tell.

We use https://github.com/containernetworking/cni to configure the system firewall and forward network traffic (and ports on the host) to containers. However, CNI does not at present support SCTP, to the best of my knowledge, so we can't tell it to poke holes in the firewall for SCTP traffic to the container.

@dcbw would know more here (and about potential plans for adding support)

**Comment by arizvisa** [comment]
Ah ok, awesome. Thanks! I'll take a gander over there then.

**Comment by mheon** [comment]
For reference, it looks like the CNI plugins do support this now, so we're adding support for SCTP to Podman now.

**Comment by arizvisa** [comment]
Good deal. Thanks for the heads up.
