### ISSUE TITLE
RFE Image Pruning

### ISSUE THREAD

**Issue by mrguitar** [containers/libpod#1910]
[//]: **kind feature**

**Description**
It would be really nice to have image pruning in podman. Newer versions of dkr have also added some system pruning which is helpful too, but image pruning is especially nice for cleaning up after lots of container builds. 

$ podman images |grep none |wc -l
26
podman rmi $(podman images | grep "^<none>" | awk '{print $3}')

Like w/ older versions of dkr, this will clean up the dangling images w/o removing intermediate layers that are still in use. So we do have an option to clean these up, but a prune command would be really nice and make it easier.

**Output of `podman version`:**

```
Version:       0.10.1.3
Go Version:    go1.10.4
OS/Arch:       linux/amd64

```

**Comment by baude** [comment]
I agree.  I was thinking samsies the other day.  Assigning to myself.

**Comment by mrguitar** [comment]
It looks good to me. The behavior differs a bit from dkr, but the -a option seems silly to me - so that's probably good. I think opting into the dry run makes more sense than prompting "are you sure?", but my view is subjective. @fatherlinux wdyt?

After thinking about it a little more, I'm not sure that the system purge makes a lot of sense for podman, but purging stopped containers does. Can we mimick the same behavior/cli options for that?

**Comment by rhatdan** [comment]
Should it be `podman image rm --prune`, `podman rmi --prune` rather then add a hole other command, and people would be more likely to find it in looking at podman rmi  man pages.

**Comment by baude** [comment]
@rhatdan that works for me ... for the record,  `podman rm --prune` would remove all stopped containers from the system? That should not include created but not run correct?

**Comment by rhatdan** [comment]
I don't know what `podman rm --prune` means.  You prune images not containers.

**Comment by fatherlinux** [comment]
@rhatdan I believe:

1. podman rm --prune would remove all of the COW layers for non-running containers aka created, but not running
2. podman rmi --prune would remove all image layers not in use by either A. running containers or B. created, but not running containers

I always complained that the docker interface was terrible. The "docker images" command shows repositories, the "docker ps -a" command shows COW layers, the "docker history" command shows image layers. IMHO, our confusion on this is due to the upstream API we are mimicking. That said, I really like the --prune options. I think it's another little value add that podman could provide...

**Comment by rhatdan** [comment]
Well podman rm --prune would seem pretty dangerous then. But I am fine with adding it.

I would think podman rmi --prune basically removes all non tagged images, which means no one is using them.

**Comment by rhatdan** [comment]
Maybe those are dangling.

atomic images prune
       prune

       Prune/delete all dangling images, freeing wasted disk space.

**Comment by mheon** [comment]
My only issue with `rm --prune` is the potential for typo or autocomplete danger with `rmi --prune` - someone goes to remove dangling images, slight typo, now a bunch of their stopped containers are gone

**Comment by baude** [comment]
it is already fixed in the PR.  we now have container prune and image prune.  In the case of image prune, it removes all unused images; that can be <none> (by definition) or any images without an associated container.
