### ISSUE TITLE
podman pull download output is verbose

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#1919]
[//]: # **kind feature**

This is current `podman pull` output is too verbose. Even in `--quiet` more.
```
Copying blob sha256:e79a00f901acd49dd7cf3c3bd0f13814eb9a89c99102fa8f781a330aed83376d
 492 B / 492 B [============================================================] 0s
Copying blob sha256:073a9d9f50835d96ba299f325687780433178ed3eaac2c1f55366b54ba94b2fd
 178 B / 178 B [============================================================] 0s
Skipping fetch of repeat blob sha256:073a9d9f50835d96ba299f325687780433178ed3eaac2c1f55366b54ba94b2fd
Copying blob sha256:4aecf21845a128d74821efa61c80b420c9bea3fedb78cdd5e3cc65d96db6f51f
 181 B / 181 B [============================================================] 0s
Copying blob sha256:3426ff39957cfa0e527fd8d66fe627cb268e689c9f263b8c206f102da589384d
 452.96 KB / 452.96 KB [====================================================] 0s
Copying blob sha256:4aec07c74624fd55c8599dcc7b765738fe31553262d5e41018c90d9575e16545
 9.75 MB / 41.54 MB [=============>--------------------------------------------]^C%                                 
```
I'd like to propose more concise version.
```
blob e79a00f901ac [=== 492 B / 492 B ======================================] 3s
blob 073a9d9f5083 [=== 178 B / 178 B ======================================] 1s
Skipping fetch of repeat blob:073a9d9f5083
blob 4aecf21845a1 [=== 181 B / 181 B ======================================] 1s
blob 3426ff39957f [=== 452.96 KB / 452.96 KB ==============================] 5s
blob 4aec07c74624 [=== 9.75 MB / 41.54 MB =====>---------------------------]^C%                                 
```

**Comment by rhatdan** [comment]
LGTM, PRs gladly accepted.

**Comment by abitrolly** [comment]
I can not find the place where the string is constructed. Either GitHub search is broken, or it is in some 3rdparty lib.

**Comment by rhatdan** [comment]
https://github.com/containers/image
```
grep -r "Copying blob" -r .
./copy/copy.go:	ic.c.Printf("Copying blob %s\n", srcInfo.Digest)
```

**Comment by abitrolly** [comment]
Aha, it is a different repository!

https://github.com/containers/image/blob/63a1cbdc5e6537056695cf0d627c0a33b334df53/copy/copy.go#L525

There are two places where the bar is referred.

https://github.com/containers/image/blob/63a1cbdc5e6537056695cf0d627c0a33b334df53/copy/copy.go#L644

https://github.com/containers/image/blob/63a1cbdc5e6537056695cf0d627c0a33b334df53/copy/copy.go#L690

L644 looks like the right thing to patch, and it uses https://github.com/cheggaaa/pb
Gotcha!

**Comment by rhatdan** [comment]
Any progress on this?

**Comment by abitrolly** [comment]
Nope. I am worrying about money balance and can't concentrate on doing experiments with https://github.com/cheggaaa/pb/tree/v2 - `v1` doesn't provide necessary customization options.

**Comment by vrothberg** [comment]
This will conflict with our current work on parallelizing the copying of layers. The output of the progress bars will be less verbose than before:
```
[valentin@nebuchadnezzar libpod]$ podman pull nginx
Trying to pull docker.io/nginx:latest...Getting image source signatures
Copying blob a5a6f2f73cd8: 21.44 MiB / 21.44 MiB [==========================] 9s
Copying blob 1ba02017c4b2: 21.18 MiB / 21.18 MiB [==========================] 9s
Copying blob 33b176c904de: 203 B / 203 B [==================================] 9s
Copying config 568c4670fa80: 5.88 KiB / 5.88 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
568c4670fa800978e08e4a51132b995a54f8d5ae83ca133ef5546d092b864acf
```

**Comment by abitrolly** [comment]
I don't see any reason to duplicate efforts, and I'd let this be handled by parallel branch. For the output above does "Copying config" need a sha and progress bar? Where is it copied from?

**Comment by vrothberg** [comment]
> I don't see any reason to duplicate efforts, and I'd let this be handled by parallel branch. For the output above does "Copying config" need a sha and progress bar? Where is it copied from?

It was shown before, so I thought I keep it. I think it makes sense to display it as it's also being downloaded from the registry (https://registry-1.docker.io/v2/library/nginx/blobs/sha256:568c4670fa800978e08e4a51132b995a54f8d5ae83ca133ef5546d092b864acf).

**Comment by rhatdan** [comment]
I agree we should work this in parallel work.  @abitrolly We would love to have your help and feedback on this.
