### ISSUE TITLE
Support for Image Signing

### ISSUE THREAD

**Issue by johnfosborneiii** [containers/libpod#1927]
Does podman support image signing from the CLI similar to docker-ce/notary? If not, is it on the roadmap?

**Comment by mheon** [comment]
I believe @QiWang19 is starting to work on signing support in https://github.com/containers/libpod/pull/1899 but for the most part we recommend you sign images using `skopeo`

**Comment by mtrmac** [comment]
There already is `podman push --sign-by=`, and `podman pull` does, AFAIK, verify signatures according to the systemwide signature policy.

So, the primary elements of “simple signing” are already available in `podman`; the above-linked `podman trust` work can help with setting up the configuration but is not, strictly speaking, necessary to benefit on push/pull.

**Comment by baude** [comment]
@rhatdan @QiWang19 are we at a point now where we can close this?

**Comment by rhatdan** [comment]
Yes closing
