### ISSUE TITLE
libpod/contrib/python/podman/podman/libs.Image.push disables TLS by default

### ISSUE THREAD

**Issue by mtrmac** [containers/libpod#1929]
AFAICS https://github.com/containers/libpod/blob/5f6ad82524ca7a3281c8464c84b4f9be4ff90aef/contrib/python/podman/podman/libs/images.py#L78-L81 disables TLS by default; that is a rather dangerous default.

Cc: @jwhonce

**Comment by rhatdan** [comment]
Yes I think this should be set to True by default.
