### ISSUE TITLE
libpod crashes when numeric gid is not in group file

### ISSUE THREAD

**Issue by wking** [containers/libpod#1937]
[//]: # **kind bug**

**Description**

When an image config sets [`config.User`][1] to a numeric value (like `1000:1000`), but those values do not exist in the container's `/etc/passwd` and/or `/etc/group`, libpod is currently breaking.  However, the OCI spec [requires converters to copy numeric `uid` and `gid` to the runtime config without attempting to look them up][2].

**Steps to reproduce the issue:**

```console
$ podman version
Version:       0.11.2-dev
Go Version:    go1.10.3
Git Commit:    "5f6ad82524ca7a3281c8464c84b4f9be4ff90aef"
Built:         Tue Dec  4 11:05:15 2018
OS/Arch:       linux/amd64
$ podman run --rm -it registry.svc.ci.openshift.org/ci-op-zvml7cd6/pipeline:installer --help
error creating temporary passwd file for container 228f6e9943d6f18b93c19644e9b619ec4d459a3e0eb31680e064eeedf6473678: unable to get gid 1000 from group file: no matching entries in group file
```

with an image built from [this][3].  I'm skipping `podman info`, because I don't think it matters, and I'm working up a fix for this myself ;).

**Describe the results you expected:**

A successful container run.

[1]: https://github.com/opencontainers/image-spec/blame/v1.0.1/config.md#L118-L123
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.1/conversion.md#L70
[3]: https://github.com/openshift/installer/blob/v0.5.0/images/installer/Dockerfile.ci

**Comment by wking** [comment]
Off topic:

> @mheon mheon added the `bug` label an hour ago

If you want to adjust the issue template, Prow might pick up [`/kind bug`][1] on its own so you don't have to do that manually.  Haven't tested recently though, and I haven't checked to see if the label plugin is enabled for this repo.

[1]: https://deck-ci.svc.ci.openshift.org/command-help

**Comment by mheon** [comment]
I think you're right... I'll poke at it
