### ISSUE TITLE
podman commands documentation on --detach-keys wrong

### ISSUE THREAD

**Issue by jwhonce** [containers/libpod#1959]
[//]: **kind bug**

**Description**
The documentation on detach-keys legal values does not match the source code.
Included in the documentation is:

- CLI argument descriptions in go code
- markdown documents
- man pages
- API.md

**Steps to reproduce the issue:**

1. Review containers/libpod/vendor/github.com/docker/docker/pkg/term/ascii.go vs. documentation listed above.

**Describe the results you received:**

**Describe the results you expected:**
Code and documentation should align regarding legal values.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
from source, master branch
```

**Output of `podman info`:**

```
from source, master branch
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@jwhonce Can you open a PR to fix the documentation. I tried ctr-p, ctr-q to detach from a container and it does not seem to work.

**Comment by rhatdan** [comment]
@mheon is this still an issue?

**Comment by mheon** [comment]
@jwhonce What documentation, where? I don't know of any documentation beyond the Manpages about legal values
