### ISSUE TITLE
regression: 0.12.1.1-1: restart running-container (nonroot): executable file not found

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#1965]
```
$ podman run --detach alpine sleep 60
9e97f53461ea0ba6f60e90991c57a8ea8d4a877017eb60bcbe42f0d19aa17a19
$ podman restart 9e97f53461ea0ba6f60e90991c57a8ea8d4a877017eb60bcbe42f0d19aa17a19
container create failed: container_linux.go:344: starting container process caused "exec: \"sleep\": executable file not found in $PATH"
: internal libpod error
```
Works fine as root. Only seems to happen with running containers; restarting a stopped one works fine.

podman-0.12.1.1-1.git66d3499.fc29

**Comment by mheon** [comment]
@giuseppe PTAL

I'm betting this is the fuse-overlayfs mount issue we were discussing in the other issue - we'll probably need to join the user namespace of the container if it's running when we try to restart it

**Comment by giuseppe** [comment]
good catch, I've opened a PR here: https://github.com/containers/libpod/pull/1975
