### ISSUE TITLE
pypodman port: `-l/--last` is not implemented and "pypodman port $ctn $port" does not work well

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#1974]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind bug**

**Description**
As the title says. 
* Ones work fine:
1. `pypodman port -a/--all`
2. `pypodman port $ctn`
* Which not work:
1. `pypodman port -l/--last`
2. `pypodman port $ctn $port`

**Steps to reproduce the issue:**

1.  `pypodman port -l`

2.  `pypodman port test-port 80`

3.  `pypodman port test-port 80/tcp`

**Describe the results you received:**
1. 
```
[root@localhost ~]# ~/.local/bin/pypodman -l root --host 192.168.122.213 port -l
2018-12-11 16:29:39 CST | ERROR    | pypodman: unrecognized arguments: -l
2018-12-11 16:29:39 CST | ERROR    | Try 'pypodman --help' for more information.
```

2. 
```
[root@localhost ~]# ~/.local/bin/pypodman -l root --host 192.168.122.213 port test-port 80
Container "80" not found
8111ad77c3551c8672a9dd7906787e4bf6eef530f9ae6aab134063ff50d623d7
[{'host_port': '80', 'host_ip': '', 'protocol': 'tcp', 'container_port': '80'}]
```

3. 
```
[root@localhost ~]# ~/.local/bin/pypodman -l root --host 192.168.122.213 port test-port 80/tcp
Container "80/tcp" not found
8111ad77c3551c8672a9dd7906787e4bf6eef530f9ae6aab134063ff50d623d7
[{'host_port': '80', 'host_ip': '', 'protocol': 'tcp', 'container_port': '80'}]
```

**Comment by rhatdan** [comment]
We don't want to support --last for remote API, since it opens up the chance of race conditions to too large.

**Comment by Edward5hen** [comment]
@rhatdan Yes sir, it makes sense.
I think `pypodman port $ctn $port` should be implemented, it seems no other risks included.
