### ISSUE TITLE
Podman start --attach with nonexistent container does not fail

### ISSUE THREAD

**Issue by mheon** [containers/libpod#1981]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**

Podman start --attach doesn't error immediately when a container that does not exist is specified

**Steps to reproduce the issue:**

1. `podman start --attach does_not_exist`

2. Press enter key after command is run

**Describe the results you received:**

The `start --attach` command only errors after any key is pressed once after the command has been run

**Describe the results you expected:**

The `start --attach` command immediately exits with an error stating that the container does not exist

**Additional information you deem important (e.g. issue happens only occasionally):**

Probably an artifact of how we do attach?

**Output of `podman version`:**

0.12.1.1 on F29

**Comment by mheon** [comment]
Alright, now we have two bug labels, so that's nice and confusing.

**Comment by baude** [comment]
cannot reproduce

**Comment by mheon** [comment]
I can't reproduce locally anymore... Not sure what was going on with my terminal. I'm going to close until I can reproduce again.
