### ISSUE TITLE
podman rmi/rm -af and infra containers

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#1991]
Podman is unable to delete all images (`podman rmi -af`) when an infra container of a Pod still exists.

The first attempt of `podman rmi -af` will yield a helpful error message, e.g.:
`
error removing image da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e: container 05bd830d6625975d8013d6004099c4df92daa050f12637c7e85bd0a1664d6273 using image could not be removed: container 05bd830d6625975d8013d6004099c4df92daa050f12637c7e85bd0a1664d6273 is the infra container of pod 159a2a2b6a937e49340cd251e8543bfe273ea13b61cef63a8cb33d25613fcc26 and cannot be removed without removing the pod            
`

Following attempts of `podman rmi -af`, however, will only yield a
`unable to delete all images; re-run the rmi command again.` which isn't very helpful.

If special-casing infra containers is still desired, the descriptive error message should always be printed. If we decide to treat an infra container like any other, we could delete the Pod if it has been paused.

**Comment by mheon** [comment]
The first error is pretty good, aside from the duplication of the infra container ID.

The second error is wierd and makes no sense - did something we do alter the state? We shouldn't be modifying images we don't end up removing, I think?
