### ISSUE TITLE
rootless: cached builds fail with: "error resolving symlinks and comparing modified times"

### ISSUE THREAD

**Issue by cgwalters** [containers/libpod#2012]
```
$ rpm -q podman
podman-0.12.1.1-1.git66d3499.fc29.x86_64
$ make deploy-machine-config-controller
WHAT=machine-config-controller /var/srv/walters/src/github/openshift/machine-config-operator/hack/cluster-push.sh
...
+ podman build -t localhost/machine-config-controller -f Dockerfile.machine-config-controller
STEP 1: FROM registry.svc.ci.openshift.org/openshift/release:golang-1.10 AS builder
STEP 2: WORKDIR /go/src/github.com/openshift/machine-config-operator
--> Using cache bd55df3b0df2f714c4bc0973aae0214c8acad64e4586b11f115e9785b40f0ff2
STEP 3: FROM bd55df3b0df2f714c4bc0973aae0214c8acad64e4586b11f115e9785b40f0ff2 AS builder
STEP 4: COPY . .
error checking if cached image exists from a previous build: error checking if copied files match: error resolving symlinks and comparing modified times: "/home/walters/src/github/openshift/machine-config-operator": panic: runtime error: slice bounds out of range
```

This is running inside an outer podman container on FSB29.

**Comment by cgwalters** [comment]
This looks like a dup of https://github.com/containers/libpod/issues/1973

**Comment by vrothberg** [comment]
@cgwalters, #1973 seems to have issues reproducing it. Is it reproducible in your environment and if so, could you share instructions in  #1973?

**Comment by cgwalters** [comment]
Yep, reproduces 100%.   As far as I can tell this seems likely to be a regression from https://github.com/containers/buildah/commit/0ce1071650c5ab8b7f5e696855e1e05198e2f1f4

I was adding some debug prints but the panic is being thrown from somewhere in the guts of golang's `Cmd.Run()`.

**Comment by cgwalters** [comment]
As far as reproducing, the repository above is https://github.com/openshift/machine-config-operator which has some basic commands that run `podman`.  It's only the 2nd build that breaks.

**Comment by cgwalters** [comment]
Except of course now that I play around with downgrading back to podman 0.10 (which failed with other errors), then back up to `podman-0.12.1.1-1.git66d3499.fc29.x86_64` I can't reproduce anymore...
