### ISSUE TITLE
Portable dir mounting (SELinux problem)

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#2014]
[//]: # **kind feature**

**Description**

Non-transparent volume mappings make `podman` is non portable the same way as Docker. Means that commands that work on Ubuntu won't work on Fedora, because `:Z` suffix needs to be supplied for the later.

Even for the case when I run image as myself in my own directory and I map it explicitly so that container can operate on it.

    ✗ podman run -v $PWD:/src -w /src snapcore/snapcraft:beta ls -la    

    ls: cannot open directory '.': Permission denied

**Describe the results you received:**

Child process is still unable to access the dir.

**Describe the results you expected:**

`snapcraft` can do better and mount dirs to container r/w by default unless explicitly requested to do r/o or this "no access" mount.

**Output of `podman version`:**

```
✗ podman version
Version:       0.12.1.1
Go Version:    go1.10.5
Git Commit:    "8a97c0f33b6bd8eabb04f0b8368b78022b53942f-dirty"
Built:         Fri Dec  7 23:01:00 2018
OS/Arch:       linux/amd64
```

Fedora 28.

**Comment by rhatdan** [comment]
This is SELinux blocking.  If $PWD is your homedir, you would need to disable SELinux

podman run --security-opt label=disabled -v $PWD:/src -w /src snapcore/snapcraft:beta ls -la

**Comment by abitrolly** [comment]
I written that it is SELinux in issue title. The point is to make `podman` select user friendly variant automatically without explicit options to make commands portable for documentation.

**Comment by rhatdan** [comment]
That would be insecure by default.  Which is not going to happen.   A user  needs to know what they are doing when running a container.  There are lots of other potential secuity options that could block running of an application, and we will not disable them either.

**Comment by abitrolly** [comment]
On Wed, 19 Dec 2018 at 12:01, Daniel J Walsh <notifications@github.com>
wrote:

> That would be insecure by default. Which is not going to happen. A user
> needs to know what they are doing when running a container. There are lots
> of other potential secuity options that could block running of an
> application, and we will not disable them either.
>
Can you be more specific about security implications in this case of
mounted directories? Without :Z option it is impossible to mount. With :Z
it is insecure? Are there any other variants?

**Comment by rhatdan** [comment]
We can not generalize policy to allow any content that is volume mounted into  a container to automatically have all of the labels allowed for read/write/execute.  

So the user needs to label the content correctly or turn SELinux separation off.  We do have a side project to allow users to create new types to allow access with more security but for now, we have three choices.

1 User Labels source volume himself with a label containers can read/execute or read/execute/write
2 User uses :z for shared content and :Z for private content and podman relabels the content for the user
3 User Disables SELinux separation.  

Podman will never make the assumption itself what the user expects.
