### ISSUE TITLE
varlink API - GetInfo() misses host/swap_total and host/oci_runtime

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#2016]
**Is this a BUG REPORT or FEATURE REQUEST?**:
**kind bug**

**Description**
Access varlink API `GetInfo()` with python client, find that some information is missing from the result.

**Steps to reproduce the issue:**

1. `podman varlink -t 0 unix:/run/podman/io.podman`

2. open another terminal and python3:
``` 
>>> import varlink
>>> client = varlink.Client.new_with_address('unix:/run/podman/io.podman')
>>> conn = client.open('io.podman', namespaced=True)
>>> info = conn.GetInfo()
>>> info.info.host
namespace(arch='amd64', buildah_version='1.5-dev', cpus=2, distribution=namespace(distribution='"rhel"', version='8.0'), hostname='rhel8-1', kernel='4.18.0-23.el8.x86_64', mem_free=503656448, mem_total=1918967808, os='linux', swap_free=2133229568, swap_total=0, uptime='525h 10m 33.95s (Approximately 21.88 days)')
>>> info.info.host.swap_total
0
```

**Describe the results you received:**
`podman info`:
```
host:
    ......
    ......
    OCIRuntime:
    package: runc-1.0.0-51.rc5.dev.gitfdd8055.el8+1782+b46414a8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
    ......
    ......
    SwapTotal: 2147479552
    ......
    ......
insecure registries:
    ......
    ......
registries:
    ......
    ......
store:
    ......
    ......
```

**Describe the results you expected:**
The information python client gets should be the same as `podman info` does.
`info.info.host.swap_total` should not be 0.
`info.info.host` should include OCIRuntime information.

**Comment by rhatdan** [comment]
@jwhonce @baude is this still an issue?

**Comment by rhatdan** [comment]
@Edward5hen Did this get fixed?

**Comment by baude** [comment]
it is specific to the python library? @jwhonce ?

**Comment by jwhonce** [comment]
@baude I'll look into the varlink code.  This isn't using python3-podman.  It's more than likely in the code populating the structures to return to the client.
