### ISSUE TITLE
empty file when exporting

### ISSUE THREAD

**Issue by nerijus** [containers/libpod#2027]
Version is podman-0.12.1.2-1.git9551f6b.fc29.x86_64 from F29 updates-testing.
I am running podman as user, not root.

$ podman container ls
CONTAINER ID  IMAGE                          COMMAND               CREATED         STATUS             PORTS  NAMES
1ffe1ad85dee  localhost/teamviewer10:latest  /bin/sh -c /opt/t...  11 seconds ago  Up 11 seconds ago         vibrant_stallman

$ podman export 1ffe1ad85dee -o /tmp/tv.tar

File /tmp/tv.tar is 1024 bytes long and contains 0x00 only.

**Comment by mheon** [comment]
@giuseppe Another fuse-overlayfs not leaving the user namespace issue?

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2028

**Comment by nerijus** [comment]
Thank you, exporting works now. But when importing on another PC I get an error:

$ podman import /tmp/tv.tar 
Getting image source signatures
Copying blob sha256:161e4951ad5a9fd9c33b872f10fdd462c2d7db4f9e98e4ed4a0ed0fcac1c279a
 275.23 MB / 275.23 MB [==================================================] 2m7s
Copying config sha256:7954a6d6c52ef2879830fe61dfe4efdab634bb0062a11510b2e270b0a707ee5b
 415 B / 415 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
Error committing the finished image: error adding layer with blob "sha256:161e4951ad5a9fd9c33b872f10fdd462c2d7db4f9e98e4ed4a0ed0fcac1c279a": Error processing tar file(exit status 1): operation not permitted

The user id on the PC where exporting was done is 500, while on importing PC it is 1000. Could it be a problem? Tested it, created the user with the same name and id and tried to import - the same error message.

**Comment by giuseppe** [comment]
@nerijus that bug got fixed recently upstream, could you try with a newer version of Podman?

Basically it is erroring out as it cannot create devices, but they are just ignored in recent versions of Podman

**Comment by nerijus** [comment]
I downloaded source from git head (this repo), applied patches from PR #2028, but still get the same error when importing.

**Comment by giuseppe** [comment]
what image are you using?

**Comment by nerijus** [comment]
Custom made image, I can give a link if needed.

**Comment by nerijus** [comment]
https://sat.lt/tv.tar.gz

**Comment by nerijus** [comment]
I rebuilt podman with the latest commit, made a new export and tried to import - still the same error. The exported image is https://sat.lt/tv.tar.xz

**Comment by nerijus** [comment]
I pushed image to quay.io, and trying to pull on another PC errors out too:
$ podman pull quay.io/nerijus/teamviewer10
Trying to pull quay.io/nerijus/teamviewer10...Getting image source signatures
Copying blob sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17
 71.68 MB / 71.68 MB [=====================================================] 34s
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
 32 B / 32 B [==============================================================] 0s
Skipping fetch of repeat blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:fee6e6fad921b5f7279147076fa43681668860ce9376cf52bceab33917c00c0e
 24.32 MB / 24.32 MB [=====================================================] 11s
Copying blob sha256:d7243d1c911714be6577b92fe8b65e29b21ecae032d9908ffe9bb839c52d8938
 40.76 MB / 40.76 MB [=====================================================] 23s
Copying blob sha256:25eac60f87b92af269ba49fd3ace80dda53cdf9c90d7fe604dc5eda575b5db09
 60.08 MB / 60.08 MB [=====================================================] 26s
Copying blob sha256:4e5ae0769fdbeeeae5725a8de7166292148bbe6e8c5b5803422ec94d632a01f0
 5.84 MB / 5.84 MB [========================================================] 2s
Copying blob sha256:3d24c325b66fd73faff8b3ecef4a621e9de1d4b2748dc2e3b5fe62bfb307f280
 164 B / 164 B [============================================================] 0s
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
 32 B / 32 B [==============================================================] 0s
Writing manifest to image destination
Storing signatures
Failed
error pulling image "quay.io/nerijus/teamviewer10": unable to pull quay.io/nerijus/teamviewer10: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17": Error processing tar file(exit status 1): operation not permitted

**Comment by giuseppe** [comment]
@nerijus it seems I am not authorized to pull the image:

error pulling image "quay.io/nerijus/teamviewer10": unable to pull quay.io/nerijus/teamviewer10: unable to pull image: Error determining manifest MIME type for docker://quay.io/nerijus/teamviewer10:latest: Error reading manifest latest in quay.io/nerijus/teamviewer10: unauthorized: access to the requested resource is not authorized

**Comment by nerijus** [comment]
please try again.

**Comment by nerijus** [comment]
Yes, also from git. $ podman pull quay.io/nerijus/teamviewer10 --log-level debug
flag provided but not defined: -log-level

**Comment by giuseppe** [comment]
please try: `podman --log-level debug pull quay.io/nerijus/teamviewer10`

**Comment by nerijus** [comment]
Sorry.
$ podman --log-level debug pull quay.io/nerijus/teamviewer10
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/user/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/user/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000                
DEBU[0000] Using static dir /home/user/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false 
DEBU[0000] parsed reference into "[overlay@/home/user/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mount_program=/usr/bin/fuse-overlayfs]quay.io/nerijus/teamviewer10:latest" 
Trying to pull quay.io/nerijus/teamviewer10...DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for quay.io/nerijus/teamviewer10:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.io 
DEBU[0000] Error creating parent directories for mkdir /var/lib/containers: permission denied, using a memory-only cache: %!v(MISSING) 
DEBU[0000] GET https://quay.io/v2/
DEBU[0000] Ping https://quay.io/v2/ status 401          
DEBU[0000] GET https://quay.io/v2/auth?scope=repository%3Anerijus%2Fteamviewer10%3Apull&service=quay.io 
DEBU[0001] Increasing token expiration to: 60 seconds   
DEBU[0001] GET https://quay.io/v2/nerijus/teamviewer10/manifests/latest 
DEBU[0001] IsRunningImageAllowed for image docker:quay.io/nerijus/teamviewer10:latest 
DEBU[0001]  Using default policy section                
DEBU[0001]  Requirement 0: allowed                      
DEBU[0001] Overall: allowed                             
Getting image source signatures
DEBU[0001] Manifest has MIME type application/vnd.docker.distribution.manifest.v1+prettyjws, ordered candidate list [application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0001] ... will first try using the original manifest unmodified 
Copying blob sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17
DEBU[0001] Downloading /v2/nerijus/teamviewer10/blobs/sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17 
DEBU[0001] GET https://quay.io/v2/nerijus/teamviewer10/blobs/sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17 
DEBU[0002] Detected compression format gzip             
...
DEBU[0105] GET https://quay.io/v2/nerijus/teamviewer10/blobs/sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1 
DEBU[0106] Detected compression format gzip             
 0 B / 32 B [------------------------------------------------------------------]DEBU[0106] Using original blob without modification     
 32 B / 32 B [==============================================================] 0s
Writing manifest to image destination
Storing signatures
DEBU[0106] Applying tar in /home/user/.local/share/containers/storage/overlay/071d8bd765171080d01682844524be57ac9883e53079b6ac66707e192ea25956/diff 
DEBU[0119] Error pulling image ref //quay.io/nerijus/teamviewer10:latest: Error committing the finished image: error adding layer with blob "sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17": Error processing tar file(exit status 1): operation not permitted 
Failed
ERRO[0119] error pulling image "quay.io/nerijus/teamviewer10": unable to pull quay.io/nerijus/teamviewer10: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17": Error processing tar file(exit status 1): operation not permitted

**Comment by giuseppe** [comment]
what kernel are you using?

**Comment by nerijus** [comment]
4.14.18-300.fc27.x86_64

**Comment by giuseppe** [comment]
we don't really support F27 as it is EOL since 2018-11-30. Could you try on a newer system if it is still broken?  I've tried on two different F29 systems, going to try F28 now

**Comment by nerijus** [comment]
Tried on kernel 4.19.10, and it worked.

**Comment by rhatdan** [comment]
Ok, I guess we can close this then.
