### ISSUE TITLE
podman not honoring volume shm mount

### ISSUE THREAD

**Issue by greg-hydrogen** [containers/libpod#2047]
**kind bug**

**Description**

Podman is not overriding the default SHM when the user specifies the volume mount -v /dev/shm:/dev/shm

**Steps to reproduce the issue:**

1.  Run a container with the volume shm mount ( -v /dev/shm:/dev/shm)

**Describe the results you received:**

The container continue to use the default SHM size as 64M

**Describe the results you expected:**

Container should use the host SHM size

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:       0.12.2-dev
Go Version:    go1.11.2
Git Commit:    "6b059a58828b978f30ed416da066987226e88e73-dirty"
Built:         Thu Dec 20 01:18:07 2018
OS/Arch:       linux/amd64

**Output of `podman info`:**
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.1-1.git66d3499.fc28.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 8a97c0f33b6bd8eabb04f0b8368b78022b53942f-dirty'
  Distribution:
    distribution: fedora
    version: "28"
  MemFree: 60189306880
  MemTotal: 67537940480
  OCIRuntime:
    package: runc-1.0.0-59.dev.gitccb5efd.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  hostname: greg-lnxworkstn
  kernel: 4.19.8-200.fc28.x86_64
  os: linux
  rootless: false
  uptime: 21m 47s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 6
  GraphDriverName: zfs
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Compression: lz4
    Parent Dataset: storage/podman/storage
    Parent Quota: "no"
    Space Available: "310876864512"
    Space Used By Parent: "4758134784"
    Zpool: storage
    Zpool Health: ONLINE
  ImageStore:
    number: 13
  RunRoot: /var/run/containers/storage

**Additional environment details (AWS, VirtualBox, physical, etc.):**
using zfs on linux

**Comment by rhatdan** [comment]
Fixed in master branch.
