### ISSUE TITLE
podman exec doesn't work with custom PATH

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#2063]
The "exec" command does not honor the PATH (if any), of the image, like the "run" command does.

Thus, when using `exec` one _always_ gets the default PATH - using `run` gets the custom PATH.

Overriding the PATH var with `-e` works.

Seems to be a bug setting "env" twice ?

**Comment by mheon** [comment]
I wonder if it's just defaulting to whatever PATH is set in the container when it's first created - if you do a `podman run -e PATH:...`, does it use that path?

If so, it's a pretty simple matter to pull it out of the container config and use it.

**Comment by mheon** [comment]
Sorry, `docker run -e PATH:...` - to see how Docker handles it

**Comment by afbjorklund** [comment]
It worked in Docker (with `run` and `init`)

**Comment by afbjorklund** [comment]
Think I found the issue

**Comment by afbjorklund** [comment]
Here was the duplicated "env" code I meant:

https://github.com/containers/libpod/blob/master/cmd/podman/exec.go#L103
https://github.com/containers/libpod/blob/master/cmd/podman/exec.go#L112

When compared to the run/create version of it:

https://github.com/containers/libpod/blob/master/cmd/podman/create.go#L593
https://github.com/containers/libpod/blob/master/cmd/podman/create.go#L602

**Comment by afbjorklund** [comment]
The current workaround is to add an extra `-e` parameter, when using `exec`:

`-e PATH=/usr/local/go/bin:/home/tc/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

It is not needed for the the inital `run`, but it needed for any re-use with `exec`

`docker://boot2podman-docker-tinycore.bintray.io/tinycore-go:1.10.4`
