### ISSUE TITLE
Add "host-device" networking mode

### ISSUE THREAD

**Issue by skept1c** [containers/libpod#2070]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**kind feature**
##
**Description**

CNI supports [host-device](https://github.com/containernetworking/plugins/tree/master/plugins/main/host-device) networking mode, which might be very useful in our scenario: host with multiples interfaces, each of them is bound to a particular container. However, according to [documentation](https://github.com/containers/libpod/blob/master/docs/podman-create.1.md), libpod does not support _host-device_ mode; Is this mode in roadmap or maybe such a setup can be achieved another way?

**Comment by mheon** [comment]
I think that this is possible if you make a separate CNI network for the host device, and join the container to it with the `--network` flag. There might be an issue if you only wanted to join the host device network, though, as `--network` only allows joining additional CNI networks, not replacing the default one.

**Comment by rhatdan** [comment]
@giuseppe Could you look into this?

**Comment by rhatdan** [comment]
@giuseppe Were you ever able to look at this?

**Comment by giuseppe** [comment]
I've not looked into this yet, I'll try this week

**Comment by rhatdan** [comment]
@giuseppe Did you ever look into this?  @QiWang19 Do you have time to look at this?

**Comment by baude** [comment]
@mheon i think you are exactly correct on the approach in my opinion.  anyways, that is how i would first try to do this? so what would it take to close this out? docs?

**Comment by mheon** [comment]
I'm running low on bugs - I could grab this

**Comment by baude** [comment]
but my question is what needs to be done?

**Comment by mheon** [comment]
We need to ensure containers with --net=none make a network namespace and use CNI to configure the loopback plugin - and only the loopback plugin.

**Comment by rhatdan** [comment]
I agree.

**Comment by vrothberg** [comment]
Assigning to @mheon :)

**Comment by mheon** [comment]
Closing in favor of #3535
