### ISSUE TITLE
podman should login anew if asked to instead of using old credentials

### ISSUE THREAD

**Issue by akostadinov** [containers/libpod#2092]
**Is this a BUG REPORT or FEATURE REQUEST?**:

# **kind bug**

**Description**

```
$  sudo podman login -p k98DR5K-OSHLT8U6KbAqhQG_TReE2C18FJmHYoLzZ0Y -u unused registry.example.com
Authenticating with existing credentials...
Existing credentials are invalid, please enter valid username and password
Login Succeeded!
```

I tell it to login, instead it first tries to use old credentials. This is useless and even harmful? If it found existing credentials working, it wouldn't update with the newly provided ones.

 ```
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to registry.example.com
```

As you see  I login to some registries that only accept temporary access tokens. Existing behaviour causes unnecessary operation delay as well using credentials about to expire instead of new ones.

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
$ podman version
Version:       0.12.2-dev
Go Version:    go1.11.2
Git Commit:    "6868b5aa1444404113bc6a4582203fbbf89490c2"
Built:         Fri Jan  4 17:32:29 2019
OS/Arch:       linux/amd64
```

**Comment by vrothberg** [comment]
@akostadinov, thanks for opening this issue. I agree that Podman shouldn't use existing credentials when others are set via the CLI.
