### ISSUE TITLE
Ubuntu package issues

### ISSUE THREAD

**Issue by cevich** [containers/libpod#2116]
/kind bug

**Description**

`/usr/share/containers/libpod.conf` is not installed [by ubuntu podman package](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa)

**Steps to reproduce the issue:**

1. `apt-get install podman`

2. `ls /usr/share/containers/`

**Describe the results you received:**

not there (also not in `/etc/containers/`)

**Describe the results you expected:**

I **think** it should appear under `/usr/share/containers` (as it does in Fedora)

**Comment by lsm5** [comment]
On Wed, Jan 09, 2019 at 09:10:15PM +0000, Chris Evich wrote:
> Assigned #2116 to @lsm5.

@baude, @mheon please remind me if /usr/share/containers is the right place to
install libpod.conf or if it should be /etc/containers? Also, same path as
Fedora for Ubuntu as well?

> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/libpod/issues/2116#event-2064047439

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
Same path as fedora.

**Comment by cevich** [comment]
Thanks @lsm5

**Comment by rhatdan** [comment]
@cevich @lsm5 Can I close this issue?

**Comment by mheon** [comment]
I'm still hearing about a number of Ubuntu packaging issues, but none of them have to do with libpod.conf

**Comment by lsm5** [comment]
seems missing in ubuntu currently, i'll fix it today and close it.

**Comment by rhatdan** [comment]
Thanks @lsm5

**Comment by lsm5** [comment]
Copying from https://github.com/containers/libpod/issues/2449

>     * No dependency on `uidmap` package (needed for rootless)

I'll add this to podman

> 
>     * Missing `slirp4netns` (no package)

I think this is available in vanilla debian, gotta check ubuntu status though
> 
>     * Missing `registries.conf`

This is via containers-common, IIRC, I wasn't able to get this subpackage working in skopeo, need to revisit.

**Comment by lsm5** [comment]
RE: libpod.conf, the rules file was missing install.config target, have taken care of that now, will push a new build with the above requests handled (maybe slirp4netns will take a while though)

**Comment by lsm5** [comment]
@mheon @rhatdan remind me please, should uidmap be a hard requires or a recommends?

**Comment by rhatdan** [comment]
reccomends (We only need it for rootless.)

**Comment by lsm5** [comment]
RE: slirp4netns, I see that Reinhard got it packaged for debian, but it won't land in ubuntu 18.04 right away unless a backport is requested. I'm looking at https://wiki.ubuntu.com/UbuntuBackports for requesting it, else I gotta put it on the ppa.

**Comment by lsm5** [comment]
alright, so I was able to get slirp4netns on the ppa as well, using the debian packaging source with some modifications https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages

**Comment by lsm5** [comment]
I'd like to have https://github.com/containers/libpod/issues/2596 resolved before I update podman on ubuntu.

**Comment by lsm5** [comment]
removing dependency on cri-o to address https://github.com/containers/libpod/issues/2605 . This also makes it consistent with what's in fedora.

**Comment by afbjorklund** [comment]
Thanks, that should make it less vulnerable to breaking when kubernetes/cri-o changes.

**Comment by SveWoCo** [comment]
Hi I encountered a dependency problem on Ubuntu 16.04 LTS with podman and buildah.
Buildah requires the package skopeo-containers. skopeo-containers provides /etc/containers/storage.conf. 
Podman requires containers-common. This Package also provides /etc/containers/storage.conf, therefore apt complains during the installation and I'm unable to install podman along with buildah.

**Comment by lsm5** [comment]
@SveWoCo ack, skopeo-containers and containers-common are the same package, so I likely screwed something up while changing package names. I'll take care of that.

**Comment by SveWoCo** [comment]
@lsm5 Thank you! I just discovered a another thing which is related to the package cri-o-runc.
It will install runc 1.0.1 rc5 to /usr/lib/cri-o-runc/sbin/runc .
Is this location on purpose? Neither buildah nor podman seem to find it at that location. After altering my PATH settings it works I just want to know if there is a specific reason for this location.

**Comment by lsm5** [comment]
The reason for that location is for the package to not conflict with ubuntu's default runc. If buidah or podman can't access those, that's another issue. I remember this being raised earlier, but I guess I got distracted. Let me take care of that as well before pushing things out

**Comment by lsm5** [comment]
@mheon please remind me, what do I need to do to have podman find `/usr/lib/cri-o-runc/sbin/runc` out of the box?

**Comment by lsm5** [comment]
@SveWoCo btw, I'm fixing 18.04 first, and I'll migrate those changes to 16.04 asap, so please bear with me. Plan to get this sorted today itself though.

**Comment by SveWoCo** [comment]
Ah, ok. Thank you. Don't worry, it is done when it's done...

**Comment by mheon** [comment]
@lsm5 We set runtime path in libpod.conf - set the first path in the `runc` array to be that one

**Comment by afbjorklund** [comment]
In should be in the default array, so _nothing_ should be needed to find `/usr/lib/cri-o-runc/sbin/runc`

``` toml
# Paths to look for a valid OCI runtime (runc, runv, etc)
[runtimes]
runc = [
	    "/usr/bin/runc",
	    "/usr/sbin/runc",
	    "/usr/local/bin/runc",
	    "/usr/local/sbin/runc",
	    "/sbin/runc",
	    "/bin/runc",
	    "/usr/lib/cri-o-runc/sbin/runc"
]
```

Since 9f7643c364dece892a7f89484142e69c8e8185f8

**Comment by SveWoCo** [comment]
Hmm ok but for buildah this is definitely not the case at the moment.

> > dpkg -s cri-o-runc 
Package: cri-o-runc
Status: install ok installed
Priority: extra
Section: devel
Installed-Size: 5624
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Architecture: amd64
Version: 1.0.0-rc5-1~ubuntu16.04.2~ppa69
Depends: libc6 (>= 2.14), libseccomp2 (>= 2.3.0)
Breaks: docker.io (<< 1.12)
Description: Open Container Project - runtime
 "runc" is a command line client for running applications packaged according
 to the Open Container Format (OCF) and is a compliant implementation of
 the Open Container Project specification.
 This package is a fork of the "runc' package, specifically for cri-o.
Built-Using: golang-1.10 (= 1.10.4-2ubuntu1~16.04.1)
Homepage: https://github.com/opencontainers/runc

So runc is installed, but buildah gives me: 

> > buildah run $newcontainer /usr/bin/runecho.sh                                              
error running container: error creating container for [/usr/bin/runecho.sh]: : exec: "runc": executable file not found in $PATH
error while running runtime: exit status 1
ERRO[0000] exit status 1

**Comment by lsm5** [comment]
> Hmm ok but for buildah this is definitely not the case at the moment.
> 
> > > dpkg -s cri-o-runc
> > > Package: cri-o-runc
> > > Status: install ok installed
> > > Priority: extra
> > > Section: devel
> > > Installed-Size: 5624
> > > Maintainer: Lokesh Mandvekar [lsm5@fedoraproject.org](mailto:lsm5@fedoraproject.org)
> > > Architecture: amd64
> > > Version: 1.0.0-rc5-1ubuntu16.04.2ppa69
> > > Depends: libc6 (>= 2.14), libseccomp2 (>= 2.3.0)
> > > Breaks: docker.io (<< 1.12)
> > > Description: Open Container Project - runtime
> > > "runc" is a command line client for running applications packaged according
> > > to the Open Container Format (OCF) and is a compliant implementation of
> > > the Open Container Project specification.
> > > This package is a fork of the "runc' package, specifically for cri-o.
> > > Built-Using: golang-1.10 (= 1.10.4-2ubuntu1~16.04.1)
> > > Homepage: https://github.com/opencontainers/runc
> 
> So runc is installed, but buildah gives me:
> 
> > > buildah run $newcontainer /usr/bin/runecho.sh
> > > error running container: error creating container for [/usr/bin/runecho.sh]: : exec: "runc": executable file not found in $PATH
> > > error while running runtime: exit status 1
> > > ERRO[0000] exit status 1

@nalind @TomSweeneyRedHat PTAL ^ . Can we get `/usr/lib/cri-o-runc/sbin/runc added to default runc paths for buildah?

**Comment by afbjorklund** [comment]
I think you need to set $BUILDAH_RUNTIME

Buildah doesn't have any configuration files

**Comment by dkliban** [comment]
In our Travis environment we are seeing the following:

```
sudo podman info
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/libexec/crio/conmon /usr/local/lib/podman/conmon /usr/local/libexec/crio/conmon /usr/bin/conmon /usr/sbin/conmon /usr/lib/crio/bin/conmon]): invalid argument
```

**Comment by lsm5** [comment]
@dkliban yes, I removed cri-o dependency but forgot to add conmon dependency. It should be fixed with the current build, but hang on for a bit, I'm fixing a skopeo-containers -> containers-common issue.

**Comment by dkliban** [comment]
@lsm5 I saw that a new package was pushed to the Ubuntu repo and tried it out. Looks like our tests that use podman are passing once again. Thanks for fixing the packaging problem!

**Comment by lsm5** [comment]
alrighty, so both bionic and xenial have new builds in the ppa. Please `apt update` and try them out.

RE: buildah, please open a separate issue on buildah (there might be something open already). I'm in the middle of updating buildah, and I'll post back once it's done.

**Comment by adelton** [comment]
I've got
```
The following NEW packages will be installed:
  conmon containernetworking-plugins containers-common containers-golang
  cri-o-runc libgpgme11 podman
```
and
```
Setting up conmon (0-1~dev~ubuntu16.04~ppa2) ...
Setting up containers-golang (0.1-1~dev~ubuntu16.04~ppa1) ...
Setting up containers-common (0.1.36-1~dev~ubuntu16.04.2~ppa7) ...
Setting up libgpgme11:amd64 (1.6.0-1) ...
Setting up containernetworking-plugins (0.7.3-1~ubuntu16.04.2~ppa2) ...
Setting up cri-o-runc (1.0.0-rc5-1~ubuntu16.04.2~ppa69) ...
Setting up podman (1.2.0-1~ubuntu16.04.2~ppa3) ...
```
but `podman build` then fails with
```
STEP 4: RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
error running container: error creating container for [/bin/sh -c groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy]: : exec: "runc": executable file not found in $PATH
Error: error building at step {Env:[DISTTAG=f30container FGC=f30 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy] Flags:[] Attrs:map[] Message:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy Original:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy}: error while running runtime: exit status 1
```

See https://travis-ci.org/adelton/freeipa-container/jobs/508109327#L178.

**Comment by lsm5** [comment]
On Mon, Mar 18, 2019 at 03:49:33PM -0700, Jan Pazdziora wrote:
> I've got
> ```
> The following NEW packages will be installed:
>   conmon containernetworking-plugins containers-common containers-golang
>   cri-o-runc libgpgme11 podman
> ```
> and
> ```
> Setting up conmon (0-1~dev~ubuntu16.04~ppa2) ...
> Setting up containers-golang (0.1-1~dev~ubuntu16.04~ppa1) ...
> Setting up containers-common (0.1.36-1~dev~ubuntu16.04.2~ppa7) ...
> Setting up libgpgme11:amd64 (1.6.0-1) ...
> Setting up containernetworking-plugins (0.7.3-1~ubuntu16.04.2~ppa2) ...
> Setting up cri-o-runc (1.0.0-rc5-1~ubuntu16.04.2~ppa69) ...
> Setting up podman (1.2.0-1~ubuntu16.04.2~ppa3) ...
> ```
> but `podman build` then fails with
> ```
> STEP 4: RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
> error running container: error creating container for [/bin/sh -c groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy]: : exec: "runc": executable file not found in $PATH
> Error: error building at step {Env:[DISTTAG=f30container FGC=f30 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy] Flags:[] Attrs:map[] Message:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy Original:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy}: error while running runtime: exit status 1
> ```
> 
> See https://travis-ci.org/adelton/freeipa-container/jobs/508109327#L178.
> 

Ack, thanks, seems like cri-o-runc isn't installing the binary, I'll fix it
later tonight.



-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
On Mon, Mar 18, 2019 at 07:15:26PM -0400, Lokesh Mandvekar wrote:
> On Mon, Mar 18, 2019 at 03:49:33PM -0700, Jan Pazdziora wrote:
> > I've got
> > ```
> > The following NEW packages will be installed:
> >   conmon containernetworking-plugins containers-common containers-golang
> >   cri-o-runc libgpgme11 podman
> > ```
> > and
> > ```
> > Setting up conmon (0-1~dev~ubuntu16.04~ppa2) ...
> > Setting up containers-golang (0.1-1~dev~ubuntu16.04~ppa1) ...
> > Setting up containers-common (0.1.36-1~dev~ubuntu16.04.2~ppa7) ...
> > Setting up libgpgme11:amd64 (1.6.0-1) ...
> > Setting up containernetworking-plugins (0.7.3-1~ubuntu16.04.2~ppa2) ...
> > Setting up cri-o-runc (1.0.0-rc5-1~ubuntu16.04.2~ppa69) ...
> > Setting up podman (1.2.0-1~ubuntu16.04.2~ppa3) ...
> > ```
> > but `podman build` then fails with
> > ```
> > STEP 4: RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
> > error running container: error creating container for [/bin/sh -c groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy]: : exec: "runc": executable file not found in $PATH
> > Error: error building at step {Env:[DISTTAG=f30container FGC=f30 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy] Flags:[] Attrs:map[] Message:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy Original:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy}: error while running runtime: exit status 1
> > ```
> > 
> > See https://travis-ci.org/adelton/freeipa-container/jobs/508109327#L178.
> > 

Try podman_1.2.0-1~ubuntu16.04.2~ppa4

libpod.conf wasn't installed with the previous build but should be taken care
of now. That file mentions the paths for the runc binary.



-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by adelton** [comment]
I've resubmitted the Travis CI build today and got
```
Setting up conmon (0-1~dev~ubuntu16.04~ppa2) ...
Setting up containers-golang (0.1-1~dev~ubuntu16.04~ppa1) ...
Setting up containers-common (0.1.36-1~dev~ubuntu16.04.2~ppa7) ...
Setting up libgpgme11:amd64 (1.6.0-1) ...
Setting up containernetworking-plugins (0.7.3-1~ubuntu16.04.2~ppa2) ...
Setting up cri-o-runc (1.0.0-rc5-1~ubuntu16.04.2~ppa69) ...
Setting up podman (1.2.0-1~ubuntu16.04.2~ppa5) ...
```
installed (1.2.0-1~ubuntu16.04.2~ppa5 > 1.2.0-1~ubuntu16.04.2~ppa4) but I still get
```
STEP 4: RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
error running container: error creating container for [/bin/sh -c groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy]: : exec: "runc": executable file not found in $PATH
Error: error building at step {Env:[DISTTAG=f30container FGC=f30 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy] Flags:[] Attrs:map[] Message:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy Original:RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy}: error while running runtime: exit status 1
```

See https://travis-ci.org/adelton/freeipa-container/jobs/508109327#L178.

**Comment by lsm5** [comment]
can you please check if `/usr/share/containers/libpod.conf` and `/usr/lib/cri-o-runc/sbin/runc` are present on your system?

**Comment by adelton** [comment]
I don't have an easy way to test that in Travis CI but running steps from https://github.com/containers/libpod/issues/2666#issue-421504843 results in an `ubuntu:xenial`-based container results in
```
# ls -la /usr/share/containers/libpod.conf /usr/lib/cri-o-runc/sbin/runc
-rwxr-xr-x. 1 root root 5743560 Feb 15 11:27 /usr/lib/cri-o-runc/sbin/runc
-rw-r--r--. 1 root root    3818 Mar 19 05:01 /usr/share/containers/libpod.conf
```

**Comment by lsm5** [comment]
@adelton one other thing, can you check if your /usr/share/containers/libpod.conf has:

```[runtimes]
runc = [
	    "/usr/bin/runc",
	    "/usr/sbin/runc",
	    "/usr/local/bin/runc",
	    "/usr/local/sbin/runc",
	    "/sbin/runc",
	    "/bin/runc",
	    "/usr/lib/cri-o-runc/sbin/runc"
]```

Also, might wanna ensure that Ubuntu's default runc isn't being installed on your Travis env.

**Comment by adelton** [comment]
The content of `/usr/share/containers/libpod.conf` matches what you show.
How should I prevent Travis from installing the default `runc` (if it indeed does so)?  I thought that https://github.com/containers/libpod/pull/2059 that we had as a fix for https://github.com/containers/libpod/issues/2046 should have addressed that.
Given that we've had Travis CI with working podman, would it make sense to set up `.travis.yml` in this repository so that the functionality that we've once had is properly checked going forward?

**Comment by lsm5** [comment]
> The content of `/usr/share/containers/libpod.conf` matches what you show.
> How should I prevent Travis from installing the default `runc` (if it indeed does so)? I thought that #2059 that we had as a fix for #2046 should have addressed that.
> Given that we've had Travis CI with working podman, would it make sense to set up `.travis.yml` in this repository so that the functionality that we've once had is properly checked going forward?

@mheon @afbjorklund I'm thinking of having cri-o-runc conflict with Ubuntu's default runc, wdyt? Also, any comment on the above?

**Comment by mheon** [comment]
We could potentially patch libpod.conf in the PPA to only include the CRI-O
runc path? Would that solve it?

**Comment by lsm5** [comment]
> We could potentially patch libpod.conf in the PPA to only include the CRI-O runc path? Would that solve it?

Ya, that's doable. I'll set that up.

**Comment by lsm5** [comment]
@adelton 1.2.0-1~ubuntu16.04.2~ppa6 should be available on ppa now. It only has `/usr/lib/cri-o-runc/sbin/runc` in `libpod.conf`. Let me know how it works.

**Comment by adelton** [comment]
No, it still fails the same way: https://travis-ci.org/adelton/freeipa-container/jobs/508109327

Since the error message is
```
exec: "runc": executable file not found in $PATH
```
I wonder if the configured full path of the `runc` executable is used at all. Why would it say just `"runc"` otherwise?

**Comment by lsm5** [comment]
> No, it still fails the same way: https://travis-ci.org/adelton/freeipa-container/jobs/508109327
> 

So in the travis logs, I see STEP 1 is `registry.fedoraproject.org/fedora:30` and the error is in STEP 4. Just wanna make sure it's the ubuntu cri-o-runc's runc binary that's expected here.

**Comment by lsm5** [comment]
I guess I'll symlink cri-o-runc's binary to /usr/sbin as well in that case and have it conflict with distro's runc.

**Comment by lsm5** [comment]
@mheon @afbjorklund podman binary uses libpod.conf settings by default, yes? Or am I missing anything for that to happen?

**Comment by mheon** [comment]
As long as libpod.conf lives in /etc/containers/ or /usr/share/containers

**Comment by lsm5** [comment]
> As long as libpod.conf lives in /etc/containers/ or /usr/share/containers

Yup, that's already happening. So, the only other thing I can try is a symlink for runc in /usr/sbin and conflict with runc. Doing that now..

**Comment by lsm5** [comment]
@adelton just pushed cri-o-runc 1.0.0-rc6-1\~ubuntu16.04.2\~ppa70 which has a symlink in /usr/sbin . Can you retry please?

**Comment by adelton** [comment]
With `podman 1.2.0-1~ubuntu16.04.2~ppa7` and `cri-o-runc 1.0.0-rc6-1~ubuntu16.04.2~ppa70` things are back to working: https://travis-ci.org/adelton/freeipa-container/jobs/508109332
Thank you!

**Comment by kunalkushwaha** [comment]
Hi @lsm5 one thing I noticed during installation of `podman` on Ubuntu, it removes `docker-ce`. 

I think, none of packages conflicts between `podman` & `docker`, this is not required.  


```
$ sudo apt-get install -y podman cri-o-runc                                                                                                                                                    
Reading package lists... Done                                                                                                                                                                  
Building dependency tree                                                                                                                                                                       
Reading state information... Done                                                                                                                                                              
The following packages were automatically installed and are no longer required:                                                                                                                
  aufs-tools cgroupfs-mount docker-ce-cli pigz                                                                                                                                                 
Use 'sudo apt autoremove' to remove them.                                                                                                                                                      
The following additional packages will be installed:                                                                                                                                           
  conmon containernetworking-plugins containers-common containers-golang slirp4netns uidmap                                                                                                    
The following packages will be REMOVED:                                                                                                                                                        
  containerd.io docker-ce                                                                                                                                                                      
The following NEW packages will be installed:                                                                                                                                                  
  conmon containernetworking-plugins containers-common containers-golang cri-o-runc podman slirp4netns uidmap                                                                                  
0 upgraded, 8 newly installed, 2 to remove and 204 not upgraded       
```

**Comment by rhatdan** [comment]
I know that docker-ce is now conflicting with the installation of runc.

**Comment by lsm5** [comment]
So, the docker-ce conflict with both `runc` and `cri-o-runc` seems to occur because of `/usr/sbin/runc`. I'll have cri-o-runc create a symlink in `/usr/bin` instead of `/usr/sbin` so that we have no conflict with docker-ce and that @adelton is happy too

**Comment by lsm5** [comment]
runc updated on both ubuntu versions in ppa. check it out

**Comment by afbjorklund** [comment]
Glad that the conflict is gone, but it seems confusing to have both /usr/bin/runc and /usr/sbin/runc ?
I hate the fact that containerd.io installs /usr/sbin/runc, instead of handing it off to a separate package.

**Comment by lsm5** [comment]
@afbjorklund cri-o-runc doesn't have `/usr/sbin/runc` anymore. Just `/usr/lib/cri-o-runc/sbin/runc` and a symlink `/usr/bin/runc`

**Comment by mheon** [comment]
@lsm5 Got one more for you - slirp4netns in the PPA looks to be old (0.2.1), we need a 0.3.0 release to support port forwarding for rootless containers

**Comment by adelton** [comment]
Dan suggests that the runc update causes https://github.com/containers/libpod/issues/2798.

**Comment by rhatdan** [comment]
Of course the real issue here is I don't really understand what is going on. and I don't have a Ubuntu to test with right now.

**Comment by SveWoCo** [comment]
would it be possible to provide the previous version of the buildah package via the ppa? Since updating from 1.6 to 1.8 buildah gives me a 
> mkdir /var/run/containers/storage: permission denied

I would like to test if this is caused by the new buildah version or something different.

**Comment by lsm5** [comment]
> would it be possible to provide the previous version of the buildah package via the ppa? Since updating from 1.6 to 1.8 buildah gives me a
> 
> > mkdir /var/run/containers/storage: permission denied
> 
> I would like to test if this is caused by the new buildah version or something different.

Unlikely that I can fetch the exact previous build, cause I force push the deb packaging commits all the time to my fork (cause Travis and rebase and all that stuff), but some version of 1.6 should be doable. Dan/Nalin, do you know what could be the cause of this issue?

**Comment by rhatdan** [comment]
@SveWoCo Are you running rootless. Could you clean out your home dir to see if this fixes the problem?

**Comment by SveWoCo** [comment]
Hi, my problem was solved. With issue [420](https://github.com/containers/buildah/issues/420). It was not a Problem with the package.

**Comment by sdeoras** [comment]
Still seeing podman related pkg issues.
```
sudo apt-get update -qq
sudo apt-get install -qq -y software-properties-common uidmap
sudo add-apt-repository -y ppa:projectatomic/ppa
sudo apt-get update -qq
sudo apt-get -qq -y install podman```
```Preparing to unpack .../containernetworking-plugins_0.7.5-1~ubuntu18.04~ppa1_amd64.deb ...
Unpacking containernetworking-plugins (0.7.5-1~ubuntu18.04~ppa1) ...
dpkg: error processing archive /var/cache/apt/archives/containernetworking-plugins_0.7.5-1~ubuntu18.04~ppa1_amd64.deb (--unpack):
 trying to overwrite '/opt/cni/bin/bridge', which is also in package kubernetes-cni 0.7.5-00
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)```

**Comment by lsm5** [comment]
On Thu, May 30, 2019 at 03:31:25PM -0700, Saurabh Deoras wrote:
> Still seeing podman related pkg issues.
> ```
> sudo apt-get update -qq
> sudo apt-get install -qq -y software-properties-common uidmap
> sudo add-apt-repository -y ppa:projectatomic/ppa
> sudo apt-get update -qq
> sudo apt-get -qq -y install podman```
> ```Preparing to unpack .../containernetworking-plugins_0.7.5-1~ubuntu18.04~ppa1_amd64.deb ...
> Unpacking containernetworking-plugins (0.7.5-1~ubuntu18.04~ppa1) ...
> dpkg: error processing archive /var/cache/apt/archives/containernetworking-plugins_0.7.5-1~ubuntu18.04~ppa1_amd64.deb (--unpack):
>  trying to overwrite '/opt/cni/bin/bridge', which is also in package kubernetes-cni 0.7.5-00
> dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)```

I can move containernetworking-plugins to a soft dependency if that helps users
to use both kube and projectatomic repos together.

@mheon wdyt?


> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/libpod/issues/2116#issuecomment-497508854

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by mheon** [comment]
@lsm5 Yeah, that ought to work fine for us. We have a lot of people just using Podman without root, anyways - you don't really need CNI for that.
