### ISSUE TITLE
podman login should store the credentials in the kernel keyring

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#2167]
It should default to the keyring and then fall back to file storage. 

https://bugzilla.redhat.com/show_bug.cgi?id=1627819

**Comment by vrothberg** [comment]
@rhatdan @mtrmac @umohnani8, I have doubts regarding the kernel keyring, mainly because the keyring is not namespaced. This means that `root-container-A` can read the credentials of `root-container-*` which is a blocker.

Docker uses the `pass(1)` if available on the host which is definitely a security improvement over a json file.

**Comment by rhatdan** [comment]
I don't see the kernel keyring as abig an issue as you. We are blocking access to it via SELinux and seccomp, and we can use usernamespace by default.    Could we use kernel keyring for the root less case. Since this is the one that is causing us issues.

**Comment by rhatdan** [comment]
Does the seccomp filter prevent the use of kernel keyrings altogether inside of the container?  If yes we probably should relax this if using a userns.

**Comment by rhatdan** [comment]
The upstream kernel has a PR to make kernel keyrings unigue per User Namespace, so this would allow us to use kernel keyring for non privileged users, since the container process would not be able to see it.  And the containers themselves could use a kernel keyring.

**Comment by vrothberg** [comment]
Awesome. Once that's in the kernel, we can continue working on it.

**Comment by rhatdan** [comment]
@vrothberg Anything on this, or should I open fhis up for others to look at?

**Comment by vrothberg** [comment]
@rhatdan, feel free to put others on this issue. The copy-detection mechanism received a higher priority but is not yet finished.

**Comment by QiWang19** [comment]
would it be helpful for me if I could see the bugzilla page....?
![bugz](https://user-images.githubusercontent.com/23665824/56136852-98b55d80-5f61-11e9-90a9-7c161f3511cf.png)
