### ISSUE TITLE
1.0: run-kill-start: container stuck in 'Created'

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2168]
There's a race condition causing run, kill, start to fail:
```
# x=$(podman run -d alpine sleep 5);podman kill $x;podman start -a  $x
```
Most of the time this will hang forever (or at least minutes).  Running ps in another shell shows:
```
# podman ps -a
CONTAINER ID  IMAGE                            COMMAND  CREATED         STATUS   PORTS  NAMES
2f04e8b6f399  docker.io/library/alpine:latest  sleep 5  30 seconds ago  Created         goofy_clarke
```
^C yields:
```
^CERRO[0219] Error forwarding signal 2 to container 2f04e8b6f39966f7aab2256155a8d7ab6abbc2ef47929990940f83d2a50f8463: can only kill running containers: container state improper 
```
podman-1.0.0-1.git82e8011.fc29; likewise on f28.

Reproducer is not 100% reliable. It seems to happen more reliably after a pull, but that could be my imagination. Still, if you can't reproduce it, try `podman rmi alpine` first.

**Comment by mheon** [comment]
I'm not seeing the error message after control-C, but I am seeing the rest.

It looks like we're successfully attaching?

We get stuck in a loop doing ```DEBU[0002] Checking container a993cfc61358390cf35934f300b7d59955a26edd186147f82c038c6e3f45c9e8 status... ```

**Comment by mheon** [comment]
That's `WaitWithInterval()` - we're waiting for the container to exit

**Comment by mheon** [comment]
Status is Created - but the container has a PID. This shouldn't be able to happen.

**Comment by edsantiago** [comment]
In the problem-not-reproduced case, ^C gets echoed, then there's a pause, then I get my shell prompt (and exit status is 0). (Which surprises me because I would've expected an immediate exit with signal exit status. But I'm not going to look into that now).

Suggestion: run my reproducer, wait 8 or more seconds to make sure the problem has triggered, then try ^C.

(Can't offer any suggestions re: your note about the impossibility of this condition)

**Comment by baude** [comment]
is this fixed now ??

**Comment by edsantiago** [comment]
infinite-loop test for 15 minutes doesn't reproduce (with podman from master of a few days ago). It used to hang pretty quickly, so I'll call it fixed. Thanks.
