### ISSUE TITLE
runlabel: support for env vars in label

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#2171]
/kind feature

**Description**

Is `podman container runlabel` supposed to support env var substitution? I can't seem to get it to work.

For example: `LABEL RUN="podman run -it -v \${PWD}/logs/:/home/user/.weechat/logs/:z --name weechat weechat"` in my Dockerfile isn't working. The var gets replaced with an empty value. 

This used to work in the past: For example: https://github.com/projectatomic/atomicapp/blob/fba5cbb0a42b79418ac85ab93036a4404b92a431/Dockerfile#L7-L11

**Additional information you deem important (e.g. issue happens only occasionally):**

- i'm running in rootless mode

**Output of `podman version`:**

- `podman-0.12.1.2-1.git9551f6b.fc29.x86_64`

**Comment by rhatdan** [comment]
Yes this is supposed to work.

**Comment by rhatdan** [comment]
@baude has this been fixed.

**Comment by mark-otaris** [comment]
Another variable to substitute is $UID. For example, when I use `
LABEL run="podman run --rm --interactive --tty --network=none --uidmap 0:1:\$UID --uidmap \$UID:0:1 --volume \"\$PWD\":/export/ \$IMAGE"
` in a Dockerfile, and use `podman container runlabel run`, `\$IMAGE` is replaced correctly, but `\$UID` gets replaced by nothing and podman complains that the mapping is invalid.

**Comment by garyedwards** [comment]
Hi, another variable to substitute would be `$DISPLAY`.  I get the same behaviour described above:

    sudo podman inspect localhost/ros:xenial-kinetic-testing | grep RUN
    "RUN": "podman run --rm --interactive --network host --tty --env DISPLAY=$DISPLAY IMAGE"
    sudo podman container runlabel run --display ros:xenial-kinetic-testing
    Command: /proc/self/exe run --rm --interactive --network host --tty --env DISPLAY= localhost/ros:xenial-kinetic-testing

There must be many situations where variable need substituting, is there a more generic way this can be dealt with?  Other example variables can be found in the fedora toolbox project:

https://github.com/debarshiray/toolbox/blob/master/toolbox#L24

**Comment by baude** [comment]
supposed to be fixed, reopen if needed
