### ISSUE TITLE
(podman images) does not handle digested references correctly

### ISSUE THREAD

**Issue by mtrmac** [containers/libpod#2175]
/kind bug

**Description**

`podman images` does not show digested references correctly

**Steps to reproduce the issue:**

```console
$ sudo ./podman pull docker.io/busybox@sha256:bbb143159af9eabdf45511fd5aab4fd2475d4c0e7fd4a5e154b98e838488e510
$ sudo ./podman images
```

**Describe the results you received:**

```
REPOSITORY                         TAG …
docker.io/library/busybox@sha256   bbb143159af9eabdf45511fd5aab4fd2475d4c0e7fd4a5e154b98e838488e510 …
```

**Describe the results you expected:**

```
REPOSITORY                         TAG …
docker.io/library/busybox          @sha256:bbb143159af9eabdf45511fd5aab4fd2475d4c0e7fd4a5e154b98e838488e510   3a093384ac30 …
```
or maybe `<none>` instead of a tag if no tag is known.

**Additional information you deem important (e.g. issue happens only occasionally):**

`ReposToMap` should be using `reference.ParseNormalizeNamed`, like #2106.

**Output of `podman version`:**

```
Version:       1.0.1-dev
Go Version:    go1.10.7
Git Commit:    "0e3264ae4de85d2c974106582f80fd8cadab8bb8"
Built:         Thu Jan 17 15:17:44 2019
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
We should match Docker's output.
