### ISSUE TITLE
Test readme.md needs some love

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2189]
<!--
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind bug

**Description**
The https://github.com/containers/libpod/blob/master/test/README.md test readme page needs some attention.  It tells you how to emulate the Papr tests in your environment, and that's no longer a thing.  Maybe it was late Friday night hiccups I was running into, but I was not able to run the ginkgo test either in my sandbox or by spinning up the container as documented.

**Comment by baude** [comment]
@TomSweeneyRedHat what do i need to do here to close this issue

**Comment by TomSweeneyRedHat** [comment]
Sometimes I love GitHub, I know I wrote more than just a title for this.

In short I was unable to run the Ginkgo tests based on the README.md, I also ran into other issues.

`make localunit` is failing for me with a fresh libpod install.  Not sure if that's expected, but it should be noted if so.

This command also throws up some errors when run:  `GOPATH=~/go ginkgo -v test/e2e/.`.  It completes, but is disconcerting to see the red flash by from time to time and it reports 105 errors.

The individual Ginkgo test runs weren't working, but with your help I touched that up this weekend.

There's a chunk of verbiage about emulating 'PAPR' testing.  I don't think that's in use any more and if not it should be removed.

Finally the System test also fails for me.  'make localsystem'  I don't know if that's due to a bad setup or it's just broken.

So just a general cleaning and additional explanation to warn folks of expected errors would be good.

**Comment by rhatdan** [comment]
@baude @TomSweeneyRedHat Any movement on this?  @TomSweeneyRedHat Could you open a PR to satisfy your needs.

**Comment by TomSweeneyRedHat** [comment]
I'll work with @baude on it.  A lot of what's remaining to be documented I've never gotten to work, so will need @baude to tell me what's cruft on the page and what needs fixing.

**Comment by TomSweeneyRedHat** [comment]
Fixed with 2592
