### ISSUE TITLE
Read-only rootless containers fail to run

### ISSUE THREAD

**Issue by mheon** [containers/libpod#2193]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Rootless containers run read-only will fail to start. If you add a terminal, we get a horribly non-helpful EOF error reading the Conmon JSON response (I thought we fixed that, but evidently not). If you don't add a terminal, you get a more helpful error message (an EPERM trying to bind-mount in /etc/hostname).

**Steps to reproduce the issue:**

1. `podman run --rm --read-only -i busybox sh`

**Describe the results you received:**

```
ERRO[0001] container create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/run/user/1000/overlay-containers/92e6155e155eac348d14f513e82a9e4712e07531ebc320747556a05b0f3deb5e/userdata/hostname\\\" to rootfs \\\"/home/mheon/.local/share/containers/storage/overlay/7b316a76798dd7196477d90cbbdf5195a2e38ede26330b2eea9c1b518f3731ea/merged\\\" at \\\"/home/mheon/.local/share/containers/storage/overlay/7b316a76798dd7196477d90cbbdf5195a2e38ede26330b2eea9c1b518f3731ea/merged/etc/hostname\\\" caused \\\"operation not permitted\\\"\""
```

**Describe the results you expected:**

Container runs successfully, no gigantic error messages

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Fedora packaged v1.0

**Output of `podman info`:**

Nothing unusual - stock install on AMD64

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
it seems to be already fixed in master.  I could see it failing on the Fedora package but master works fine

**Comment by mheon** [comment]
Confirmed here - master's fixed. Closing as such.
