### ISSUE TITLE
Update organization account logo

### ISSUE THREAD

**Issue by fulldecent** [containers/libpod#2207]
The organization logo is not set

https://github.com/containers

So this appears to be a hobby project.

**Comment by rhatdan** [comment]
We were discussing this just before the Hollidays, and I guess we dropped the ball.  @fulldecent Thanks for kicking us in the butt on this.

**Comment by TomSweeneyRedHat** [comment]
FYI @mairin

**Comment by rhatdan** [comment]
We now have a logo.
