### ISSUE TITLE
Specify which platforms are supported

### ISSUE THREAD

**Issue by fulldecent** [containers/libpod#2208]
The following is said in README.md

> available on most Linux platforms

This could be improved to specifically support certain platforms. For example:

> RHEL 7.0 and Ubuntu 18.10 host platforms are officially supported, although the community has also reported success with other Linux distributions. Windows and macOS and other OS hosts are not supported at this time.

**Comment by rhatdan** [comment]
Well "Supported' is a loaded term.  This is a community project.  The only Supported Platform is RHEL7 and RHEL8 Beta. 
If we had a different term, or explained what we meant by support.

**Comment by afbjorklund** [comment]
There are community projects supporting hosts of other platforms (older Linux, Darwin, and Windows), although doing so by running Linux in a virtual machine on them. See https://boot2podman.github.io/

**Comment by fulldecent** [comment]
Saying "RHEL7 and RHEL8 beta is supported" would be an improvement. I am considering this project for a RHEL deployment, and I don't have time to run software/distro combinations that aren't supported, so putting that fact there would be helpful. :-)

**Comment by rhatdan** [comment]
Should this information be in the install.md, or in the README.md?  Could you open a PR for what you would like to see?
