### ISSUE TITLE
Ubuntu package missing dependency "uidmap"

### ISSUE THREAD

**Issue by pipiobjo** [containers/libpod#2211]
Steps to reproduces 

sudo add-apt-repository ppa:projectatomic/ppa
sudo apt-get update
sudo apt-get install podman

```
$ podman version

Version:            1.0.1-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

Execute as non-root user
```
$ podman images

ERRO[0000] cannot find newuidmap: exec: "newuidmap": executable file not found in $PATH
```

Fix it via:
```
$ sudo apt-get install uidmap
```

I think it should be defined as dependency.

**Comment by rhatdan** [comment]
Lokesh can you fix the package requires for Ubuntu?

**Comment by jplandrain** [comment]
Thanks for the fix. It worked for me on Ubuntu 18.04 running into the same issue.

**Comment by rhatdan** [comment]
@jplandrain So you see this as fixed?  @lsm5 Can I close this issue?

**Comment by jplandrain** [comment]
No, not at all. The package uidmap should be a dependency. At the moment, it's not the case and so I had to install it manually as described by @pipiobjo (whom I was thanking for his fix, but that is actually a workaround rather than a fix)

**Comment by mheon** [comment]
I think we're also missing slirp4netns

**Comment by jplandrain** [comment]
> I think we're also missing slirp4netns

I confirm this too

`➜  ~ podman version                                              
Version:            1.0.1-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

➜  ~ podman run --rm -it busybox echo hello world                    
Trying to pull docker.io/library/busybox...Getting image source signatures
Copying blob 697743189b6d: 738.18 KiB / 738.18 KiB [========================] 0s
Copying config d8233ab899d4: 1.46 KiB / 1.46 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
ERRO[0003] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
hello world
`

**Comment by matthewlenz** [comment]
@jplandrain have you located a ppa for slirp4netns?

**Comment by rhatdan** [comment]
@lsm5 is this fixed now?
@pipiobjo is this fixed now?

**Comment by jplandrain** [comment]
Sorry for the delay before I could answer. To me it looks like it works fine now:

'➜  ~ podman version                                              
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

➜  ~ podman run --rm -it busybox echo hello world                
hello world
`

**Comment by nupanick** [comment]
For anyone searching, this also works on armbian, resolving the error "newuidmap": executable file not found in $PATH.
