### ISSUE TITLE
RFE: let logs command accept multiple containers

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#2219]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind feature

**Description**
I'm trying to migrate my projects from docker-compose to a podman-based solution. Probably the main blocker for me is that in docker-compose, you would get a stream of logs from all the containers. In podman, I can only pass a single container to `podman logs`.

Do you think this is a good idea?

I already checked out the code and I think it should be doable.

**Comment by baude** [comment]
can you provide an example of what you'd be thinking? like would the containerid precede the log message?

**Comment by TomasTomecek** [comment]
Yes, that's how docker-compose works. I would expect the same/similar functionality:
```
$ podman logs -f --tail 10 httpd mariadb app
httpd:   log message from httpd
httpd:   another log message from httpd
mariadb: hello
httpd:   httpd is doing something
mariadb: hello again
app:     I'm starting
```

**Comment by rhatdan** [comment]
I don't think this is a bad idea,  we could even do --all.  Please open a PR if you have something working?

**Comment by TomasTomecek** [comment]
I'll try to take a look and figure it out.

**Comment by rhatdan** [comment]
@TomasTomecek Have you done anything on this?

**Comment by TomasTomecek** [comment]
I haven't found free time to work on this. Sadly that will likely not change in coming weeks.

This issue is still on my mind, though.

**Comment by baude** [comment]
@TomasTomecek what are the particulars around this?  are you thinking of being able to add multiple container ids?  what about --all ? one issue for me with all is that it might be too hard to be able to watch for containers that start, stop, rm, etc?

**Comment by TomasTomecek** [comment]
> are you thinking of being able to add multiple container ids?

yes

> what about --all ?

I don't follow, logs command doesn't have such option now.

> one issue for me with all is that it might be too hard to be able to watch for containers that start, stop, rm, etc?

Yes, that's correct. Therefore I'd do the initial implementation by only accepting started containers and if a container dies, just remove it from the watch list.

**Comment by baude** [comment]
i have a working version of this.  let me clean it up and perhaps @TomasTomecek could give it a test?

**Comment by rhatdan** [comment]
This issue is resolved.
