### ISSUE TITLE
apparmor broken in rootless

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#2223]
/kind bug

**Description**

podman fails on systems with AppArmor as it tries loading the default profile: `AppArmor is not supported in rootless mode`

AppArmor requires root privileges. It looks like a wrong condition check.

**Steps to reproduce the issue:**

1. podman run alpine ls

**Output of `podman version`:**

v1.0.0

Sorry for not posting the entire output. I am running it in a minimal VM.

**Comment by vrothberg** [comment]
@cevich, I am a bit concerned that the CI did not catch this bug. Is AppArmor enabled on the Ubuntu machines?

**Comment by cevich** [comment]
@vrothberg Thanks for noticing and asking.  My understanding is that AppArmor **IS** enabled, I will verify this immediately...
