### ISSUE TITLE
Can we rename podman to something less masculine?

### ISSUE THREAD

**Issue by rothgar** [containers/libpod#2226]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Tools should not imply a gender or sex

**Describe the results you received:**

People turned off from the tool because of its name

**Describe the results you expected:**

A neutral name for tools

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The physical world with real people.

**Comment by baude** [comment]
@rothgar thanks for your input.  I am wondering if you can elaborate and share your experiences, etc, on the matter.  Please be more verbose than your original filing here.

**Comment by rhatdan** [comment]
podman stands for pod manager, it is neither masculine or feminine.

**Comment by rothgar** [comment]
It implies a masculine gender which should be avoided. "Man" is not gender neutral no matter what it stands for.

**Comment by rhatdan** [comment]
Well we are not going to change the name.

**Comment by rothgar** [comment]
Thanks for the welcoming and inclusive community.

**Comment by rhatdan** [comment]
We do welcome you and your input.
Just because we don't agree with your suggestion, no reason to be offended.  
Changing the name at this point would cause confusion and loss of market awareness and as I said, I don't agree with you that the name indicates masculinity.

**Comment by rothgar** [comment]
I understand your concerns about name changes. It's confusing for customers and additional work for developers, technical writers, marketing, etc. It's not something to be taken lightly. Naming things is hard and even this repo (libpod) is a good example because it is confusing for `podman` issues.

It's fine that we disagree on the name and the impact it may have to make people feel welcome and included in the community. We are both welcome to our opinions and I'm merely a user so I have very little stake in a name change and understand no name would satisfy everyone.

If a name change was not possible I was hoping to have a discussion about what the name may imply to new people and how documentation and marketing could help clarify that message.

This interaction and votes on the comments gives me some insights about what this community values so I am fine not supporting the project and finding a different solution.

**Comment by rhatdan** [comment]
Well we have several Females working on the project and the artist who drew all of the icons and the coloring book is a Female, as well as my Boss Denise Dumas.  I make it a point to try to higher female engineers if at all possible.
Here is the coloring book and we attempted to be as inclusive as possible with the character representation of the container tools we are designing.  Although podman is a male.  :^)

https://github.com/mairin/coloringbook-container-commandos/blob/master/Web.pdf

**Comment by TomSweeneyRedHat** [comment]
@rothgar Thanks for bringing this discussion up.  If you've suggestions on the changes we could make, I'd think especially to the README.md, I'd be happy to add them into the document if you don't want to do so yourself.

**Comment by vrothberg** [comment]
> This interaction and votes on the comments gives me some insights about what this community values so I am fine not supporting the project and finding a different solution.

The votes are inappropriate in such a context, I agree. However, I cannot spot a contributor among them and certainly no maintainer. Please, do not extrapolate those reactions to the community of this project. Especially the openness of this community made me join it.

**Comment by dereuromark** [comment]
Sometimes I really wonder about the common sense in people.
If you do not understand the (English) language, please do not make wrong assumptions.

If the word is a shortcut for MANAGER do not assume this to be a "man" - ever.
podman === pod manager === totally irrelevant what gender === gender neutral

As such this request is invalid by design for the same reason "black driving" is not racist, but just means the color as in "opposite of white" and "in the dark" which just means without valid ticket.

Eieiei. And even if this was a man, what would be the big deal in that? Totally irrelevant and does not downgrade other genders even. If you take this as insult, you have the problem and should first fix that IMO. If a movie hero is a male, are now all females insulted? I sure hope not. There sure will be another female hero in the next, and also another female tool at some point out there in GitHub.

As for the readme: There is already the explanation of this being a manager, but maybe it can be put in bold or more clearly then.

**Comment by vrothberg** [comment]
@dereuromark, there is no need to turn this discussion into personal attacks. Please, avoid that by all means and remain objective. I do not tolerate such attacks and won't give space for escalating this topic in whatever direction.

There is no arguing against the fact that the name includes "man", no matter what it stands for. However, the naming is done and there are no plans to change that.

This issue has served its purpose to discuss the possibility of renaming the tool and to avoid any escalation based on the last comment I will lock the conversation.

We welcome contributions to make the naming and the intention behind clearer and are thankful for the discussion started by @rothgar!

As an aside, we already planned to apply for Google Summer of Code and the outreachy program and hope that any reactions on this issue from non-community members do not reflect negatively on us.
