### ISSUE TITLE
`podman rmi --force` should be idempotent

### ISSUE THREAD

**Issue by jlebon** [containers/libpod#2234]
/kind feature

**Description**

Just like `/bin/rm -f`, `podman rmi -f` should just return rc=0 if the target image already doesn't exist. This would make it easier to use from scripts.

**Comment by baude** [comment]
@jlebon 

are you saying `rm -f bogus` == 0 but `rmi -f bogus` != 0 ?

**Comment by mheon** [comment]
Per Docker, both `rm -f` and `rmi -f` on bogus containers/images should return 1

**Comment by jlebon** [comment]
I was talking about `/bin/rm`, not `podman rm`, though that'd be nice too. I don't mind gating this behind a switch like `--ignore-nonexisting`.

**Comment by baude** [comment]
we return a 125

**Comment by jlebon** [comment]
Is `125` specific to the ENOENT case?

**Comment by jlebon** [comment]
See also https://github.com/docker/cli/pull/160 and https://github.com/docker/cli/issues/394.

**Comment by mheon** [comment]
I think it's a more generic error for us. 1 seems to be the same for Docker.

I would be fine with a --ignore-removed or --ignore-nonexisting

**Comment by baude** [comment]
We have container|image exists commands too, which give a 0 or 1 strictly based on whether the container or image exists.  Would that help?
```
$ sudo podman container exists bogus
$ echo $?
1
$ sudo podman image exists bogus
$ echo $?
1
```

**Comment by baude** [comment]
@mheon if he is already specifying -f, can we make that the default behaviour for just -f ?

**Comment by mheon** [comment]
It seems like docker-cli did, so I'm fine with it.

**Comment by baude** [comment]
@rhatdan mind commenting as well; you get most twitchy about cli flags.  we are simply proposing that when -f if used for rm/rmi, we would return a zero status if the image didn't exist.

**Comment by rhatdan** [comment]
I am fine with the change.  125, 126 and 127 are more about running the containers and not getting confused between the container exiting with a 1, versus podman exiting with a 1.

**Comment by rhatdan** [comment]
I have added features to make it easy to tell.
