### ISSUE TITLE
podman images <Repository> does not list images if present in locally

### ISSUE THREAD

**Issue by adityashah1212** [containers/libpod#2241]
kind bug

podman images <Repository> when the image is a local image does not list the images in that repository. This is how docker works. I believe podman should have commandline compatibility with docker, if we want it to be a replacement for docker.

**Steps to reproduce the issue:**

1. Create any local image for example busybox

2. Run podman images <Local image repository> without giving the tag

**Describe the results you received:**
```
podman images localhost/busybox/base
unable to find 'localhost/busybox/base' in local storage: no such image
```
**Describe the results you expected:**
```
podman images localhost/busybox/base
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
localhost/busybox/base   1.29.3              ade18c571e6f        4 days ago          2.65 MB
```

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
Version:       1.0.0
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a Physical CentOS 7.5 machine with a custom built podman and updated shadow-utils. All the above commands ran as root. Did not try rootless, though I don't expect the behavior to be different.

**Comment by baude** [comment]
This is a bug ... it works with images tagged as latest ...

**Comment by baude** [comment]
I actually now thing podman is behaving correcting, and certainly is behaving as docker does.  When the tag is omitted, the assumption is the tag is latest.  And therefore, localhost/busybox/base != localhost/busybox/base:1.29.3 and therefore should not be displayed.  @mtrmac do you agree with my assessment?

**Comment by mtrmac** [comment]
**docker-images**(1) explicitly documents that _repository_ without a _tag_ lists all images in the named repository.

**Comment by mtrmac** [comment]
… and this is what I see in my testing as well.

When naming a _single image_, the `:latest` tag tends to be assumed, but it’s up to every subcommand to define the syntax of semantics of its arguments, whether that is an image name, path to a local file, or a repository, or anything else. `docker images` just chose not treat its argument as a single image name.

**Comment by rhatdan** [comment]
@baude @mtrmac is this a bug or working as designed?

**Comment by mtrmac** [comment]
Well, **podman-images**(1) does not say, but if the intent is to be compatible with **docker-images**(1), it’s a bug.

**Comment by rhatdan** [comment]
Ok we should list all images then

```
docker pull fedora
docker pull fedora:26
 docker images fedora
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/fedora    latest              d7372e6c93c6        5 days ago          275 MB
docker.io/fedora    26                  f36d549d2474        5 days ago          232 MB
```

```
podman pull fedora
podman pull fedora:26
podman images fedora
REPOSITORY                 TAG      IMAGE ID       CREATED      SIZE
docker.io/library/fedora   latest   d7372e6c93c6   5 days ago   283 MB
```

Podman should have listed
docker.io/library/fedora   26    f36d549d2474   5 days ago   241 MB

**Comment by rhatdan** [comment]
@QiWang19 Could you fix this.

**Comment by rhatdan** [comment]
Merged in to master.
