### ISSUE TITLE
RFE: add support for "podman system prune"

### ISSUE THREAD

**Issue by ktdreyer** [containers/libpod#2247]
/kind feature

**Description**

Docker has a "[docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/)" command,  but there is no equivalent command in Podman.

**Steps to reproduce the issue:**
1. Search Google for how to clean up container images and resources on a local system.
2. Discover several user guides on the internet advocating the `docker system prune` command.
3. Run `podman system prune`.

**Describe the results you received:**
```
Command "system" not found.
See `podman --help`.
```
I have to keep Googling to figure out how to clean up my system.

**Describe the results you expected:**
This `system prune` feature is available with the podman CLI.

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 13:38:17 2019
OS/Arch:       linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for taking the time to open this issue, @ktdreyer!

The `system prune` can currently be achieved with `podman rmi -a` and `podman volume prune` but I understand the desire to be CLI compatible with Docker. @mheon @baude @rhatdan WDYT?

**Comment by rhatdan** [comment]
We could probably add
podman system info|prune:df
Events will have to wait.

**Comment by rhatdan** [comment]
We now have podman system prune.
