### ISSUE TITLE
Improve ways to install & documentation for it

### ISSUE THREAD

**Issue by h-vetinari** [containers/libpod#2250]
I've been trying to use `podman` - forced by RH policy of not upgrading the `docker` runtime in RHEL anymore, and so far it has been *far* from a drop-in replacement.

Since the last release I have access to within the newest RHEL7.6 is podman 0.11.1, I can't even start filing all the bugs I'm encountering, because - who knows - maybe they're fixed on master already.

So off I go trying to install this somewhere I fully control. This leads me to this issue:
* besides just the default install (`[apt-get|yum|...] install podman`), there should be clear documentation for getting the latest version.
  * currently there are at least two installation/build tutorials which have a non-empty symmetric difference: [one linked from podman.io](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md), and [one in the main repo](https://github.com/containers/libpod/blob/master/install.md)
  * I have a centOS machine at hand, but that is not documented where the [updates are mentioned](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md#basic-setup-and-use-of-podman)
  * podman is not in the [EPEL repo](http://mirror.spreitzer.ch/epel/7/x86_64/Packages/p/)
* ok, so building from source then.
  * [build call](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md#building-and-installing-podman) is quite different from [main install page](https://github.com/containers/libpod/blob/master/install.md#build-and-run-dependencies)
  * even though the build succeeded, I still can't use `podman build` (with a cryptic error), almost certainly because I'll need to install buildah.
  * and so on for skopeo/runc/...?
* make using latest versions easier
  * why not provide an RPM package?
  * same for Ubuntu/Debian - why not provide a `.deb` package?
* podman for windows not available...

So far, the experience has been incredibly frustrating (simple things like tagging don't work, caching is hit-and-miss [+ some weird interactions with keywords], `podman build` and `buildah bud` don't share cache, `--target` is not supported, etc. etc.).

Although I'm hoping that some of these bug fixes will still make it into RHEL8.0 (so that I can *maybe* use it later this year), current status is that I'll have to go back to the lack of features (but much greater stability) of `docker 1.13`.

**Comment by rhatdan** [comment]
@h-vetinari Have you gotten access to a newer version of podman?

**Comment by h-vetinari** [comment]
> @rhatdan: @h-vetinari Have you gotten access to a newer version of podman?

Unfortunately, no. It would be nice to have install-procedures that boil down to a `.deb` or `.rpm` (as well as consistent documentation for it), hence this issue....

**Comment by rhatdan** [comment]
I am not sure why on a RHEL machine you are having a hard time getting access to podman?  It should be in your extras channel.  Which is the same location that you got docker from.  On Centos packages have been made available, but I am not sure where.  @lsm5 Where are the packages from Centos.

**Comment by h-vetinari** [comment]
@rhatdan, I have podman on the RHEL machine, but not the latest version, much less master. If you want me to file bug reports against v.0.11, I can.

See OP:
> Since the last release I have access to within the newest RHEL7.6 is podman 0.11.1, I can't even start filing all the bugs I'm encountering, because - who knows - maybe they're fixed on master already.

Side note: the productive RHEL machine is not under my full control - particularly, I can't just download stuff. On other machines I can test (e.g. CentOS), I have more liberty.

**Comment by rhatdan** [comment]
@lsm5 Do we have a newer version of podman for RHEL7.6 yet?

**Comment by tobwen** [comment]
I have had a look at packaging _podman_ for Debian, but from my point of view, the current Ubuntu packages made it way too complicated.

Since I want to run _podman_ rootless inside the user _podman_ and don't others be abler to run it, building the whole stack is pretty straight forward. Though there are some cmd-parameters missing in _podman_, which pointto _slirp4netns_ binary for example, but this can be hacked by path variables.

I'll release my code in the next days. Need to finish something for University first.

**Comment by h-vetinari** [comment]
@tobwen 
Good to know! Please let me know on this issue once you have something!

@lsm5 @rhatdan 
Would be cool to have a new version in RHEL 7.6 (also including buildah 1.7, because I need `--target` as well, cf. containers/buildah#632). I have a couple issues I'd like to file that I need to replace docker with podman.

**Comment by rhatdan** [comment]
Yes These should be released on the next release of extras.

**Comment by tobwen** [comment]
@h-vetinari some prototypes... I'm using the ugly bash script to keep traffic to the GIT servers low. Sure, you can just wipe the GO-directory and build from scratch. This works for me on rootless. Only fuse3 installations needs root of course.

# HOWTO: backport fuse3 for Debian Stretch
https://gist.github.com/tobwen/c1fc1512458ce272aee2410e36cf1e21

# HOWTO: install podman and dependencies rootless
https://gist.github.com/tobwen/25a010d3b90a6491e5646c0e77163557

I'll add some examples for config files to podman soon. Right now, it won't find the other libraries and tools without making them available in path, change the path variable or add command-line parameters.

**Comment by h-vetinari** [comment]
@tobwen 
Thanks for the prototypes, will have a look into them when I can.

@rhatdan 
Is there any ETA (or standard cadence) on the next round of extras?

**Comment by rhatdan** [comment]
@lsm5 ^^

**Comment by h-vetinari** [comment]
Pleasantly surprised to see that [`install.md`](https://github.com/containers/libpod/blob/master/install.md#ubuntu) now has a ppa for ubuntu. Bit surprised that the installed version is `1.2-dev` (as opposed to last stable), but that's good for filing bugs at least. ;-)

This should however still be updated in [`docs/tutorials/podman_tutorial.md`](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md).

@rhatdan @lsm5 
Any news when a newer podman will hit 7.6 EPEL?

**Comment by lsm5** [comment]
On Thu, Mar 28, 2019 at 05:48:02AM -0700, h-vetinari wrote:
> Pleasantly surprised to see that [`install.md`](https://github.com/containers/libpod/blob/master/install.md#ubuntu) now has a ppa for ubuntu. Bit surprised that the installed version is `1.2-dev` (as opposed to last stable), but that's good for filing bugs at least. ;-)

1.2-dev because master branch is built nightly via Travis.
Snap packages are planned, but that might take a while.

> 
> This should however still be updated in [`docs/tutorials/podman_tutorial.md`](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md).
> 
> @rhatdan @lsm5 
> Any news when a newer podman will hit 7.6 EPEL?

Never on EPEL, unless you mean CentOS Extras or Virt SIG?
Virt SIG I'll update soon, though CentOS Extras might take a while.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/libpod/issues/2250#issuecomment-477580443

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by h-vetinari** [comment]
@lsm5 Thanks for taking the time to answer

> 1.2-dev because master branch is built nightly via Travis.

OK, cool

> > Any news when a newer podman will hit 7.6 EPEL?

> Never on EPEL, unless you mean CentOS Extras or Virt SIG?

Sorry if the naming was wrong, I meant RHEL 7.6 [extras](https://access.redhat.com/solutions/3418891). Point being, when can I install something newer than podman 0.11.1 on a RHEL 7.6 machine?

**Comment by lsm5** [comment]
On Thu, Mar 28, 2019 at 06:06:43AM -0700, h-vetinari wrote:
> @lsm5 Thanks for taking the time to answer
> 
> > 1.2-dev because master branch is built nightly via Travis.
> 
> OK, cool
> 
> > > Any news when a newer podman will hit 7.6 EPEL?
> 
> > Never on EPEL, unless you mean CentOS Extras or Virt SIG?
> 
> Sorry if the naming was wrong, I meant RHEL 7.6 [extras](https://access.redhat.com/solutions/3418891). Point being, when can I install something newer than podman 0.11.1 on a RHEL 7.6 machine?

Looks like 0.12.1.2 was shipped about 2 months ago. Aren't you seeing that one?
Something newer than that will take a few weeks more I guess.
-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by rhatdan** [comment]
@h-vetinari @lsm5 What is the latest on this issue?

**Comment by h-vetinari** [comment]
@rhatdan 
For this issue specifically, I think the only thing left to do is:

> @h-vetinari: [install instructions] should however still be updated in [`docs/tutorials/podman_tutorial.md`](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md).

Regarding other points in the discussion, I'd need to have an update of podman/buildah in the RHEL 7.6 extras channel as soon as possible, but before I'd really need for containers/buildah#1456 and #2887 to be fixed first. Can open a separate issue for this if you want.

**Comment by h-vetinari** [comment]
@rhatdan 
In building podman I stumbled again on the differences between the different build instructions (and some smaller errors).

Would you accept a PR to merge the installation instructions from [`docs/tutorials/podman_tutorial.md`](https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md) into `install.rst`, and just have a pointer to that from the tutorial?

**Comment by TomSweeneyRedHat** [comment]
Why *.rst and not *.md?

**Comment by h-vetinari** [comment]
> @TomSweeneyRedHat Why *.rst and not *.md?

Because I typed the filename from memory and got the extension wrong... Sorry.

**Comment by rhatdan** [comment]
@h-vetinari Yes we would love a PR.

**Comment by TomSweeneyRedHat** [comment]
@h-vetinari no worries on the file name.  Personally, I'd like to see the install instructions be their own page with a link from the tutorial.
