### ISSUE TITLE
podman attach and systemd no interactive shell is available

### ISSUE THREAD

**Issue by vugardzhamalov** [containers/libpod#2261]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I was wondering if there is any chance to get interactive prompt available upon container execution. Otherwise it seems that everything works fine but I have to use 'CTRL+p+q' in order to detach myself as soon as systemd finished with initialization. It will be very nice to be able to interact with shell inside container. Something like "/usr/bin/sh -l"

**Steps to reproduce the issue:**

1. Compose Dockerfile:
FROM fedora:29
RUN dnf -y clean all; dnf -y install httpd; dnf -y clean all; systemctl enable httpd
STOPSIGNAL  SIGRTMIN+3
CMD ["/usr/sbin/init"]
LABEL foo=bar

2. Build the image from Dockerfile:
sudo podman build -f Dockerfile -t httpd_image:1.0

3. Create and run container from the image:
sudo podman run --name fedora29_httpd  --privileged --interactive --tty --publish-all --env container=podman --systemd --entrypoint=/usr/sbin/init --network=host -p 8080:80 --stop-signal=RTMIN+3 httpd_image:1.0

**Describe the results you received:**
When systemd finished initializing it I don't get into shell. Last line of systemd output looks like:

[  OK  ] Started Update UTMP about System Runlevel Changes.

**Describe the results you expected:**
I was hoping to get into shell. Is it expected/possible at all? It seems that I can get shell prompt on non-systemd containers fine, e.g. like "/usr/bin/sh -l"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 21:38:17 2019
OS/Arch:       linux/amd64
```
(paste your output here)
```

**Output of `podman info`:**
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 10113126400
  MemTotal: 16696569856
  OCIRuntime:
    package: containerd.io-1.2.2-3.fc29.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 96ec2177ae841256168fcf76954f7177af9446eb
      spec: 1.0.1-dev
  SwapFree: 4292866048
  SwapTotal: 4292866048
  arch: amd64
  cpus: 4
  hostname: redacted
  kernel: 4.20.5-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 2h 38m 27.02s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 9
  RunRoot: /var/run/containers/storage

```
(paste your output here)
```
systemd 239 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Detected virtualization container-other.
Detected architecture x86-64.

Welcome to Fedora 29 (Container Image)!

Set hostname to <redacted>.
Initializing machine ID from random generator.
File /usr/lib/systemd/system/systemd-journald.service:26 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Slices.
[  OK  ] Listening on Journal Audit Socket.
[  OK  ] Reached target Swap.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Listening on Process Core Dump Socket.
[  OK  ] Reached target Paths.
[  OK  ] Set up automount Arbitrary Executable File Formats File System Automount Point.
[  OK  ] Listening on Journal Socket.
         Mounting Kernel Configuration File System...
         Starting Apply Kernel Variables...
         Mounting Kernel Debug File System...
[  OK  ] Listening on initctl Compatibility Named Pipe.
[  OK  ] Reached target Local File Systems.
         Starting Rebuild Dynamic Linker Cache...
         Starting Rebuild Journal Catalog...
[  OK  ] Listening on Journal Socket (/dev/log).
         Starting Journal Service...
         Starting Create System Users...
[  OK  ] Reached target Remote File Systems.
[  OK  ] Mounted Kernel Configuration File System.
[  OK  ] Mounted Kernel Debug File System.
[  OK  ] Started Apply Kernel Variables.
[  OK  ] Started Rebuild Journal Catalog.
[  OK  ] Started Create System Users.
[  OK  ] Started Rebuild Dynamic Linker Cache.
         Starting Update is Completed...
[  OK  ] Started Update is Completed.
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Flush Journal to Persistent Storage.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Basic System.
[  OK  ] Started daily update of the root trust anchor for DNSSEC.
[  OK  ] Reached target Timers.
         Starting Permit User Sessions...
[  OK  ] Started D-Bus System Message Bus.
         Starting The Apache HTTP Server...
[  OK  ] Started Permit User Sessions.
[  OK  ] Started The Apache HTTP Server.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I think you need to enable a getty in systemd inside the container - unlike on interactive installations, systemd in a container defaults to not enabling the relevant services (not usually needed - if you need a shell inside the container, you'd usually `podman exec -t -i <id> /bin/bash`)

**Comment by rhatdan** [comment]
Would podman exec be an option?  But if @mheon suggestion works for you that would be good.

**Comment by vugardzhamalov** [comment]
Thank you @mheon  and @rhatdan ! Indeed this does exactly what I needed!
