### ISSUE TITLE
add journald logging option

### ISSUE THREAD

**Issue by sidharrell** [containers/libpod#2265]
Feature Request
Current state of the log driver options:

--log-driver="json-file"

Logging driver for the container. Currently not supported. This flag is a NOOP provided soley for scripting compatibility.

I'm not sure if you would rather have an overarching issue, like "add more log-driver options", or the more specific "add a journald log-driver to send container output to the host journal". I went with the latter, but I'm flexible, lmk.

**Comment by rhatdan** [comment]
I think the later  "add a journald log-driver to send container output to the host journal". 
If you feel adventurous to see if you could pull the journal code out of docker and see if you could open a PR for Podman.  That would really help move this forward.

**Comment by mheon** [comment]
@rhatdan I'd think this would need to be a Conmon change, though? That's where the container logs are handled.

So we'd need it in C, not Go.

**Comment by rhatdan** [comment]
Ok, makes sense.

I believe @nalind Did the original work on journal for Docker.  WDYT?

**Comment by haircommander** [comment]
I'd certainly be willing to give a conmon update a shot if everyone else is too busy

**Comment by nalind** [comment]
I think we'll have an easier time writing to and reading from the journal in C than we had in Go.

IIRC the OpenShift teams ran up against the rate limiting that journald is configured to use by default, and they had to disable it.  The journal is doing more work for each bit of data that it gets sent, so there are situations where, without rate limiting, write throughput could be a problem.

**Comment by haircommander** [comment]
I'm working on a solution in C. It isn't too bad because there's already a C api for journald. Just hammering out some branching logic between json-file and journald now. will open PR in conmon when it's ready.

**Comment by cjeanner** [comment]
Hello there,

While you're talking about logging - the "json-file" log-driver doesn't output actual JSON.
It looks like a simple copy of the standard ```/var/lib/containers/storage/overlay-containers/CONTAINER_ID/userdata/ctr.log```...

Care to have a look at it as well?

Cheers,

C.

**Comment by haircommander** [comment]
@cjeanner haha yes I have found that as well. For the time being I have opted to work on changing the language to 'kubernetes-log-file' rather than 'json-file'. If there is a reasonable use-case and demand for a json file output I will look into it, but currently all that is being logged is the container stdout, for which I think kubernetes-log-file is appropriate

**Comment by cjeanner** [comment]
@haircommander uhu - well, I would think a valid use-case would be "send logs to some (k)elk infra", as json is a far more compatible format for such things...
In my current case, I don't have such usage, but still... It's kind of surprising to get a non-JSON when asking a JSON ;).

Anyway - journald support would be really nice as well :).

**Comment by wking** [comment]
Cross-referencing kubernetes-sigs/cri-o#377.

**Comment by rhatdan** [comment]
@haircommander Is working on this for CRI-O, once it is merged there we need to add it to podman.

**Comment by rhatdan** [comment]
@haircommander What is the latest on this?

**Comment by haircommander** [comment]
It hit the backlog but I'll set it up next week

**Comment by rbjorklin** [comment]
Also interested in this since there does not seem to be any rotation on `ctr.log` it has now filled up the disk on some of our machines with long running containers.

**Comment by baude** [comment]
@haircommander how goes this one. any updates?

**Comment by haircommander** [comment]
@baude awaiting some review love: https://github.com/containers/libpod/pull/2709 :)

**Comment by haircommander** [comment]
huzzah! closing via #2709
