### ISSUE TITLE
Allow filtering images by reference

### ISSUE THREAD

**Issue by psafont** [containers/libpod#2266]
/kind feature

**Description**

Docker CLI allows to filter by reference and automatically filters by reference if given an additional parameter:

```
$ sudo docker images --filter reference='docker.io/*'
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/centos    7.4.1708            295a0b2bd8ea        3 months ago        197 MB
$ sudo docker images 'docker.io/*'
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/centos    7.4.1708            295a0b2bd8ea        3 months ago        197 MB
```

Podman currently does not implement [this](https://github.com/containers/libpod/blob/b1d4dbd335f4801487ef86964b6833c3604ceef5/cmd/podman/images.go#L375)

This can surface if users are using the Docker CLI compatibility shim with scripts (as I was doing).

**Comment by mheon** [comment]
Sure, seems like a worthwhile addition

**Comment by rhatdan** [comment]
@QiWang19 Can you look into this?
