### ISSUE TITLE
Varlink SeachIMage API does not have argument to configure if it should require https or not

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#2293]
/kind feature

**Description**
Varlink SeachIMage API does not have argument to configure if it should require https or not.

**Steps to reproduce the issue:**

1. Configure an insecure registry

2.  varlink call unix:/run/podman/io.podman/io.podman.SearchImage '{"name": "busybox"}'
Error: Call failed with error: io.podman.ErrorOccurred
{
  "reason": "couldn't search registry \"localhost:5000\": pinging docker registry returned: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client"
}

I would be glad if you could expose a parameter to allow searching on insecure registries, like podman cli has with the --tls-verify=false:
```
[root@localhost ~]# podman search --tls-verify=false busybox
INDEX            NAME                        DESCRIPTION   STARS   OFFICIAL   AUTOMATED
localhost:5000   localhost:5000/my-busybox
```

JFYI I need it for cockpit-podman tests: we don't have network access in the test VM, and I am setting up an local insecure registry that I want to search and pull images from.

**Comment by rhatdan** [comment]
@KKoukiou could you try https://github.com/containers/libpod/pull/2305 and see if it fixes your issue?

**Comment by KKoukiou** [comment]
@rhatdan No it does not work. Now tls-verify always defaults to true not matter what I pass as argument.

my-ubuntu is an insecure registry, the first command should fail to find the image.

```bash
[kkoukiou@sequoia cockpit-podman]$ sudo varlink call unix:/run/podman/io.podman/io.podman.SearchImage '{"name": "my-ubuntu", "tlsVerify": true}'
{
  "images": [
    {
      "description": "",
      "is_automated": false,
      "is_official": false,
      "name": "my-ubuntu",
      "star_count": 0
    }
  ]
}
[kkoukiou@sequoia cockpit-podman]$ sudo varlink call unix:/run/podman/io.podman/io.podman.SearchImage '{"name": "my-ubuntu", "tlsVerify": false}'
{
  "images": [
    {
      "description": "",
      "is_automated": false,
      "is_official": false,
      "name": "my-ubuntu",
      "star_count": 0
    }
  ]
}
```

**Comment by KKoukiou** [comment]
Also I think the API.md doc file should be updated accordingly, no?
https://github.com/containers/libpod/blob/master/API.md#func-searchimage
And if possible, add in the API docs what is the default value (true, false) for the tls-verify.

**Comment by KKoukiou** [comment]
So, I found that the issue was here that I had the registry listed in insecure registries, so somehow parameter was not taken into effect.

I think we should always respect the passed args however. and have the exact same behavior as the cli.

```
**--tls-verify**

Require HTTPS and verify certificates when contacting registries (default: true). If explicitly set to true,
then TLS verification will be used. If set to false, then TLS verification will not be used. If not specified,
TLS verification will be used unless the target registry is listed as an insecure registry in registries.conf.
```
