### ISSUE TITLE
rootless: readonly volume mount fails with unhelpful diagnostic

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2312]
```
$ podman run --rm -v /tmp:/tmp:ro alpine date
container create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp\\\" to rootfs \\\"/home/esm/.local/share/containers/storage/vfs/dir/a1450cd2ae39b3a8f6e8263064ca2fada1406395912bd4bdc8bfd4c171de6858\\\" at \\\"/home/esm/.local/share/containers/storage/vfs/dir/a1450cd2ae39b3a8f6e8263064ca2fada1406395912bd4bdc8bfd4c171de6858/tmp\\\" caused \\\"operation not permitted\\\"\""
: internal libpod error
```
If run with -it, the error message is even less helpful:
```
$ podman run -it --rm -v /tmp:/tmp:ro alpine date
error reading container (probably exited) json message: EOF
```
There is no AVC in either case. Running with `--log-level=debug` produces no useful output (i.e. nothing different from a successful run). Removing `:ro` yields success.

podman-1.0.0-1.git82e8011.fc29 and runc-1.0.0-67.dev.git12f6a99.fc29 ; kernel 4.19.8-300.fc29.x86_64

Unfortunately I can't reproduce on a fresh virt.

**Comment by mheon** [comment]
I think we may have fixed this already on master

**Comment by edsantiago** [comment]
I just built from 112a5ab2 and am still seeing the same problem.

**Comment by giuseppe** [comment]
I am taking a look

**Comment by giuseppe** [comment]
it looks like a bug in runc.

To verify it, I've tried another runtime:

```
$ podman --runtime /usr/local/bin/crun run -ti --rm -v /tmp:/tmp:ro alpine sh -c 'date; echo hello > /tmp/foo'
Wed Feb 13 16:19:20 UTC 2019
sh: can't create /tmp/foo: Is a directo
```

**Comment by edsantiago** [comment]
I'm really confused now because I have two systems, one that reproduces the failure and one that works cleanly, and both have `runc-1.0.0-67.dev.git12f6a99.fc29.x86_64`

**Comment by giuseppe** [comment]
is there any difference between the two systems?  Same kernel?

**Comment by edsantiago** [comment]
Lots of differences in installed packages; I've been trying to reduce that, but no luck.

Kernels that fail: 4.19.8-300.fc29, 4.20.3-200
Kernels that pass: 4.18.16-300, 4.20.6-200

**Comment by giuseppe** [comment]
it fails on `4.20.6-200.fc29.x86_64` and `runc-1.0.0-67.dev.git12f6a99.fc29.x86_64` as well

**Comment by edsantiago** [comment]
>it fails on 4.20.6-200.fc29.x86_64

Not for me. That seems to eliminate kernel as the source of the problem. (I just tested on 4.20.7-200.fc29; pass)

**Comment by edsantiago** [comment]
@giuseppe what's your `~/.config/containers/storage.conf` ? Mine is:
```
[storage]
  driver = "overlay"
  runroot = "/run/user/14904"
  graphroot = "/home/esm/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```
I've also tried `driver = "vfs"` with `mount_program = ""`. No difference. (I've also tried on LVM $HOME vs non-LVM; no difference)

**Comment by giuseppe** [comment]
@edsantiago it is exactly the same, just different UID and home directory.

**Comment by rhatdan** [comment]
@edsantiago @giuseppe Is this resolved?

**Comment by edsantiago** [comment]
I'm still seeing it on master - 0969d725a3b302d9baa0616a204f7fc824404973

**Comment by giuseppe** [comment]
I think it depends from runc, but I'll need to investigate it further

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2432
