### ISSUE TITLE
varlink: BuildImage() call is not remotable

### ISSUE THREAD

**Issue by larskarlitski** [containers/libpod#2314]
The `BuildImage()` call takes a path to a local Dockerfile. This makes this API essentially non-remotable, because before calling it from a different machine, the file needs to be placed onto the local file system via a different API (such as ssh).

I suggest putting the contents of the Dockerfile into the string instead of a filename.

**Comment by baude** [comment]
@larskarlitski hang tight, i am sitting on a PR for all of this.  I just want the output to be a little better than sit and wait as it is today which is why I was asking questions about wantmore.  I just need an answer and the PR will be submitted.

**Comment by larskarlitski** [comment]
Nice! Thanks for working on this :)

**Comment by baude** [comment]
@larskarlitski if the API isn't what you'd like after that PR goes in, lets collab and make it so.

**Comment by rhatdan** [comment]
This has been merged so closing.
