### ISSUE TITLE
`make localunit` fails with ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by nitkon** [containers/libpod#2324]
`make shell` followed by `make localunit` fails inside the shell:

```
make -C contrib/cirrus/packer test
make[1]: Entering directory '/go/src/github.com/containers/libpod/contrib/cirrus/packer'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'yaml'
Makefile:24: recipe for target 'libpod_base_images.json' failed
make[1]: *** [libpod_base_images.json] Error 1
make[1]: Leaving directory '/go/src/github.com/containers/libpod/contrib/cirrus/packer'
Makefile:175: recipe for target 'localunit' failed
make: *** [localunit] Error 2
```

root@e9a48f3368e8:/go/src/github.com/containers/libpod/contrib/cirrus/packer# pip install pyyaml          
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages
root@e9a48f3368e8:/go/src/github.com/containers/libpod/contrib/cirrus/packer# make test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'yaml'
Makefile:24: recipe for target 'libpod_base_images.json' failed
make: *** [libpod_base_images.json] Error 1

**Comment by cevich** [comment]
IIRC, it's the python 3 PyYAML that is required, which reminds me.  Did you read any docs that should have mentioned this?  (wouldn't surprise me)
