### ISSUE TITLE
[RFE] Show versions of cross-vendored components (libpod/podman/buildah) for foo info

### ISSUE THREAD

**Issue by bogdando** [containers/libpod#2325]
/kind feature

**Description**

In order to improve debugging experience with podman/buildah tooling, please make sure:

* podman info shows the vendored versions of the common libs to buildah, like libpod, and buildah itself
* buildah info shows the vendored versions of the common libs to podman, like libpod and whatnot.

**Steps to reproduce the issue:**

Install podman and buildan from sources to get & test some fixes that have yet make it into packaging. Try to figure out if a fix for libpod has made it into the installed podman & buildah, or a fix for ``buildah build`` has made it into installed ``podman build`` as well.

Or try to have this info from a generic issue reporting form

**Describe the results you received:**

The bug submission form does not provide all those versions used for builds

**Describe the results you expected:**

The bug submission form needs to provide those versions

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Hi @bogdando, thanks a lot for opening this issue. Have you tried out `podman info --debug`? It should display the information you are seeking.

**Comment by bogdando** [comment]
@vrothberg tbh, I didn't. Just posted this issue in order to make sure that a) ``buildah info --debug`` covers cross-vendored things as well, b) the issues submitting form asks for both commands outputs when its needed

**Comment by vrothberg** [comment]
I concur with you @bogdando, the issue form should ask users to run `podman info --debug`. @baude @mheon @TomSweeneyRedHat WDYT?

**Comment by mheon** [comment]
Agree, better too much than too little

**Comment by baude** [comment]
I want to say this was put behind debug by request.  might want to ask @rhatdan

**Comment by rhatdan** [comment]
I don't recall doing that.  MY podman info shows

```
podman info
host:
  BuildahVersion: 1.6-dev
```
I think we should make sure that the next version of podman only uses a non -dev branch of buildah.

**Comment by rhatdan** [comment]
What is the latest on this Issue?

**Comment by vrothberg** [comment]
> What is the latest on this Issue?

I opened https://github.com/containers/libpod/pull/2425 to make the GitHub issue template ask to run `podman info --debug` which will be slightly more verbose. As @rhatdan mentioned, `podman info` already prints the version of buildah.

However, I am not sure if `buildah info` should print the version of libpod as it's not an integral part of Buildah (opposed to Buildah being an integral part of podman-build). In addition to that, `buildah info` could not display a release of libpod due to the circular dependencies.

What I could imagine though is displaying the commit IDs of `containers/{buildah,libpod,image,storage}` which can easily be done via some Makefile tricks and grepping the `vendor.conf`. Builds that do not use `./vendor` (e.g., the ones for Debian) can set env variables for the Makefile.

**Comment by rhatdan** [comment]
Well I think we should remove any dependencies for buildah on libpod.  If there are dependenies, they should be moved to buildah or some other package and then vendored into libpod.

**Comment by mheon** [comment]
I think the biggest one is the secrets code. I'd be fine moving that into buildah wholesale (or a shared repo for common code, either or)

**Comment by rhatdan** [comment]
Makes sense for this to move to buildah.

**Comment by rhatdan** [comment]
I have a PR opened for Secrets patch now, but Flaks is blocking it.https://github.com/containers/libpod/pull/2516

**Comment by rhatdan** [comment]
Buildah no longer vendors libpod, and podman shows the version of buildah it is vendored.  I think I can close this.
