### ISSUE TITLE
Man page missing for podman checkpoint

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2337]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Unless I'm having one of those days, there's not man page for `podman checkpoint` and one is needed.

podman v1.0

**Comment by adrianreber** [comment]
There is one here: https://github.com/containers/libpod/blob/master/docs/podman-container-checkpoint.1.md

Maybe it is confusing because it is only available under the 'podman container' namespace. Should this be done differently?

**Comment by TomSweeneyRedHat** [comment]
@adrianreber probably my bad, I think that's right and I'd forgotten this one was listed that way.  Let me think about it overnight, but I think I'll just leave it as is.

**Comment by rhatdan** [comment]
Yup no podman checkpoint only podman container checkpoint.
