### ISSUE TITLE
Man page missing for podman trust show

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2339]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

We've no man page for `podman trust show` and need one.

**Comment by rhatdan** [comment]
man podman-image-trust
We don't have a podman trust command.

**Comment by TomSweeneyRedHat** [comment]
I'm going to reopen this one, yes we've the man page for this and the other two, but they're not listed on podman(1) and should be.

**Comment by rhatdan** [comment]
We don't currently list the subcommands of subcommands in podman man page.

podman container exists for example is not listed.

**Comment by rhatdan** [comment]
They are listed under podman trust not in podman, but trust is listed under podman man page.
