### ISSUE TITLE
SearchImage() varlink API doesn't return information about the registry

### ISSUE THREAD

**Issue by larskarlitski** [containers/libpod#2344]
/kind feature

`podman search` outputs the name of the registry:
```
INDEX       NAME                                            DESCRIPTION                                       STARS   OFFICIAL   AUTOMATED
docker.io   docker.io/library/busybox                       Busybox base image.                               1506    [OK]       
...
```

The `SearchImage()` call doesn't:
```json
{
  "images": [
    {
      "description": "Busybox base image.",
      "is_automated": false,
      "is_official": true,
      "name": "busybox",
      "star_count": 1506
    }
  ]
}
```

This would be useful for cockpit-podman, which would like to show this information when searching for images.

podman version 1.0.0

**Comment by rhatdan** [comment]
This command against master branch brings back a ton of data.

varlink call unix:/run/podman/io.podman/io.podman.SearchImages '{"query":"busybox"}'
