### ISSUE TITLE
Rework internals of podman pull --all-tags

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2351]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Creating a quick issue so I don't lose track.  @mheon commented on ways to make the `podman pull --all-tags` functionality more efficient in https://github.com/containers/libpod/pull/2188.  This issue is being created to make sure that work gets done.

**Output of `podman info`:**

```
1.0
```

**Comment by rhatdan** [comment]
Since this is merged closing.
