### ISSUE TITLE
Repeated builds produce base images

### ISSUE THREAD

**Issue by jgillich** [containers/libpod#2352]
/kind bug

**Description**

When building a Dockerfile, the first build succeeds, but the every build after that produces an image that appears to be identical to the base image, missing any changes specified in the Dockerfile.

**Steps to reproduce the issue:**

1. Use this Dockerfile:
```
FROM fedora:29

RUN dnf install nodejs -y
```

2. podman build -t node1 -f Dockerfile

3. podman run --rm node1 node -v

4. podman build -t node2 -f Dockerfile

5. podman run --rm node2 node -v

(Edited above example to add '1' to the container name to ease typos)
**Describe the results you received:**
```
$ podman build -t node -f Dockerfile
STEP 1: FROM fedora:29
Getting image source signatures
Copying blob 0be2a68855d7: 85.70 MiB / 85.70 MiB [=======================] 1m27s
Copying config 26ffec5b4a8a: 1.99 KiB / 1.99 KiB [==========================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: RUN dnf install nodejs -y
[omitted]
Installed:
  nodejs-1:10.15.0-1.fc29.x86_64       npm-1:6.4.1-1.10.15.0.1.fc29.x86_64     
  http-parser-2.9.0-1.fc29.x86_64      libicu-62.1-3.fc29.x86_64               
  libuv-1:1.26.0-1.fc29.x86_64        

Complete!
--> bad9aaaf6bf3182c4b876bb0ef6bd04ec214f64c376934c4a06f2a110bac4e16
STEP 3: COMMIT node
--> 36db6e4d58aff7b5d285b4dde8f4351e12b38c2e3d861be25ee31a43405506f2

$ podman run --rm node node -v
v10.15.0

$ podman build -t node2 -f Dockerfile
STEP 1: FROM fedora:29
STEP 2: RUN dnf install nodejs -y
--> Using cache bad9aaaf6bf3182c4b876bb0ef6bd04ec214f64c376934c4a06f2a110bac4e16
STEP 3: COMMIT node2
--> f1f8840c3bb3383dd6dca5d69a77487ba657da00133dabdcac4e942e9b497bfb

$ podman run --rm node2 node -v
container create failed: container_linux.go:344: starting container process caused "exec: \"node\": executable file not found in $PATH"
: internal libpod error
```

The second build appears to be identical to the base image. Compare the image sizes:
```
$ podman images
REPOSITORY                 TAG      IMAGE ID       CREATED         SIZE
localhost/node2            latest   f1f8840c3bb3   6 minutes ago   283 MB
localhost/node             latest   36db6e4d58af   6 minutes ago   579 MB
docker.io/library/fedora   29       26ffec5b4a8a   4 weeks ago     283 MB
```

**Describe the results you expected:**

Both images should have node installed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 21:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1245474816
  MemTotal: 8226537472
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 7924609024
  SwapTotal: 8363438080
  arch: amd64
  cpus: 4
  hostname: thinkpad.localdomain
  kernel: 4.20.7-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 15h 58m 24.75s (Approximately 0.62 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/jgillich/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/jgillich/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running in rootless mode.

Not sure if this should be raised against buildah instead.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
If you turn off caching does it work?

**Comment by jgillich** [comment]
Yes, without caching it works.

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by TomSweeneyRedHat** [comment]
FWIW, my first test with upstream and I wasn't able to replicate, trying further tests.

**Comment by jgillich** [comment]
@TomSweeneyRedHat Are you referring to the development version or 1.0? My system runs Silverblue in case it matters, I'll try to reproduce on an atomic VPS...

**Comment by TomSweeneyRedHat** [comment]
@jgillich I tried it first on my test/build vm which is a bit wonky at times, but it usually has the latest from upstream GitHub on it.  It worked there.

I tried on a fresh Fedora VM with Podman v1.0 on it and I ran into the same error running as root, so I think the issue isn't related to root/non-root user.  I installed Podman from upstream GitHub on that fresh VM and now the error isn't happeing.  I can't conclusively say so, but it looks like the issue has been fixed recently.

Any chance you can try cloning from GitHub and doing a make/make install and see if the problem is cured for you?

**Comment by jgillich** [comment]
Yes, I can confirm, it's working in master. Thanks!
