### ISSUE TITLE
allow file-descriptor passing from podman-exec

### ISSUE THREAD

**Issue by chergert** [containers/libpod#2372]
/kind feature

**Description**

Add support for passing file-descriptors across `podman exec` execution boundary.

I've started integrating some basic podman support into [GNOME Builder](https://wiki.gnome.org/Apps/Builder) using our native container abstractions (like we do for flatpak). One thing that makes this possible with flatpak is that we can pass file descriptors across the execution boundary. That way, I can feed a PTY for the debugger inferior to tooling like gdb while using the controlling PTY to control gdb itself.

I've looked at calling runc directly using --preserve-fds, but that would mean duplicating a lot of what podman already does for us.

**Comment by rhatdan** [comment]
So you want to add a --preserve-fds flag to podman run/create?

**Comment by debarshiray** [comment]
> So you want to add a --preserve-fds flag to podman run/create?

Yes, but to podman run/exec, if I understood @chergert properly.

**Comment by rhatdan** [comment]
@mheon @giuseppe WDYT?

**Comment by giuseppe** [comment]
It is an useful idea.

The only issue is that we are already passing down a bunch of fds, so we would need to properly reassign them.

**Comment by mheon** [comment]
The Flatpak way of doing this is `--forward-fd=FD`, which seems like a sane enough interface... I don't see many people using this, but the exec command isn't very cluttered right now, so I'm not opposed to adding it.

**Comment by rhatdan** [comment]
@giuseppe Do you have time to work on it?

**Comment by rhatdan** [comment]
There are probably going to be SELinux issues with this.  SELinux should block the use of these fd's being passed in.

**Comment by rhatdan** [comment]
Unless they are labeled with something like
system_u:system_r:container_t:s0

**Comment by rhatdan** [comment]
@giuseppe Could you take a look at this?

**Comment by giuseppe** [comment]
PR for runc here: https://github.com/opencontainers/runc/pull/1995

PR for libpod here: https://github.com/containers/libpod/pull/2426
