### ISSUE TITLE
Lookup runc and conmon on PATH?

### ISSUE THREAD

**Issue by llchan** [containers/libpod#2376]
/kind feature

`runc` and `conmon` are currently searched for on a few hardcoded paths, or they can be overridden explicitly by the user.  Is there any reason not to try a `os.LookPath` first and see if we can find one on `PATH`?  Imho it's unintuitive for podman to use a different `runc` from the one the calling shell would invoke.

Of course there are workarounds, but it feels a little silly to do a `podman --runtime=$(which runc) --conmon=$(which conmon) ...` and extra env vars are just more state to keep in sync with PATH.

**Comment by rhatdan** [comment]
The problem we have had in the past was random runc versions might not match podman and runc reports vague errors that are hard to diagnose.

In libpod.conf there is a configuration for podman paths, that could be modified for your default runc/OCI Runtime.

**Comment by llchan** [comment]
I guess I have the opposite problem, the system runc does not match my podman, and the one on PATH is the one that matches.  And I agree, the errors are not totally obvious to diagnose :)  Can those errors be detected by checking `runc --version`?

I also just tried libpod.conf with my paths baked in, and it does the trick and cleans up my command lines. A bit of a heavier-weight approach, but maybe inevitable as we add more features/knobs, so I'm okay with that I guess. Regarding libpod.conf though, it seems that the standard config paths are hardcoded in libpod/runtime.go. Could we configure those at least at compile-time so that they read from a configurable hardcoded prefix?  For example, maybe I want ConfigPath to be /path/to/prefix/share/containers/libpod.conf for a binary that lives in /path/to/prefix/bin/podman, and I know that at build time. Currently it will point to something in /usr/share, which may come from a different system-managed version of podman and not have appropriate changes for our runc/conmon paths.  Or if it's hard to make those build-time-configurable, could they at least be relative to the location of the binary, so the prefix can sort of be inferred?

Yes, each user can override with their own libpod.conf in $HOME, but I'd like to package it in a way that Just Works out of the box.

**Comment by rhatdan** [comment]
Patches welcomed.  :^)

**Comment by llchan** [comment]
Cool, if you're open to that type of change I'll put something together. Should be able to have the makefile pass in some build-time constants that the user can override.

Have to get approval first though, so might be a little bit.

**Comment by mheon** [comment]
If we do this, I think our ideal behavior is to have a bool in libpod.conf to use $PATH for runc/conmon (or separate bools, one for each), and retain the current behavior as default.

**Comment by mheon** [comment]
(Maybe a per-runtime thing with the new multi-runtime handling in libpod.conf?)

**Comment by llchan** [comment]
Agreed, new behavior should be the same as existing behavior if configs dont change. I'll probably do the compile-time-PREFIX-configuration thing first.  Doing an optional lookup on PATH imho would still be nice as a general feature though, so I'll see if I can do that later too.

**Comment by rhatdan** [comment]
@llchan Are you planning on opening a PR for this?

**Comment by llchan** [comment]
Similar to the other ticket, I'm awaiting approvals (from legal team now) to push code changes. If no one is blocked on this can you leave it open for now?

**Comment by giuseppe** [comment]
> Yes, each user can override with their own libpod.conf in $HOME, but I'd like to package it in a way that Just Works out of the box.

the rootless configuration should now copy the default settings from the global configuration, so it should be enough to set it once and every new user will use that paths.

Could you verify if that works?  Otherwise, I think that is a clearer way to address the problem rather than having two different lookup methods

**Comment by rhatdan** [comment]
I think this issue is resolved.
