### ISSUE TITLE
rootless `podman export ... -o` fails

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#2381]
```
[valentin@nebuchadnezzar libpod]$ podman export 254 -o foo.tar
Error: error creating file "foo.tar": open foo.tar: permission denied
```

... while redirecting `... > foo.tar` works. I assume that's namespace related but we might need to document that in the manpage (and the help message).

**Comment by giuseppe** [comment]
do you get any error if you try `buildah unshare touch foo.tar` from the same directory?

**Comment by vrothberg** [comment]
```
$ buildah unshare
$ podman export ... -o foo.tar
```
works.

**Comment by vrothberg** [comment]
If I do a `buildah unshare touch foo.tar` and try to export after, outside the namespace, it doesn't work.

**Comment by rhatdan** [comment]
ls -l foo.tar
