### ISSUE TITLE
podman images: not newline-terminated

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2388]
`podman images`, with a non-json output format, omits the final newline:
```
$ podman images | cat
REPOSITORY                 TAG      IMAGE ID       CREATED       SIZE
docker.io/library/alpine   latest   caf27325b298   2 weeks ago   5.8 MB$ <<<-- this is my prompt
```
This would seem like a minor nit, except it might greatly surprise anyone who does:
```
$ podman images --all --format '{{.Repository}}:{{.Tag}}\t{{.ID}}' | while read name id;do echo "got here <$name> <$id>";done
```
If we have one image, nothing is output. ~~Even more confusingly, if there's more than one, `$id` (the last element of the line) includes a spurious newline:~~ (never mind: that was an artifact of some debugging I was trying)

(Note to reviewer: I thought I had filed an issue about this months ago but can't find it now).

podman-1.0.0-1.git82e8011.fc29.x86_64

**Comment by rhatdan** [comment]
The code specifically does this now.  It checks if output is a tty and if it is executes a printf("\n") otherwise it does not.  And since you are piping to cat, it does not do it.

**Comment by rhatdan** [comment]
//Out method for Go templates
func (t StdoutTemplate) Out() error {
	tmpl, err := template.New("image").Parse(t.Template)
	if err != nil {
		return errors.Wrapf(err, "template parsing error")
	}
	err = tmpl.Execute(os.Stdout, t.Output)
	if err != nil {
		return err
	}
	humanNewLine()
	return nil
}

**Comment by rhatdan** [comment]
@edsantiago Do you think we should not check for Humans on Stdout Templates and always print the newline?
@baude Do you agree?

**Comment by mheon** [comment]
Did we add this in response to another bug? I can't think of another reason it would be there

**Comment by edsantiago** [comment]
@rhatdan I strongly think output should be consistently newline-terminated irrespective of whether stdout is a tty. See my first comment about piping through a `while` loop: the last line of output will be silently ignored.

FWIW I seem to have found in my records a note about reporting this in `ps` back in October; it got fixed, but I can't find a PR for it. (Note that this means that `ps` behaves correctly right now; `images` does not)

**Comment by rhatdan** [comment]
Ps has this line
	fmt.Fprint(w, "\n")

I have no problem adding it.

**Comment by mheon** [comment]
I did a quick search, and I can't find any issues that relate to this, so I have no idea why we added it in the first place.

Given that, I'm fine with removing the TTY check.

@baude @rhatdan We really need to start forcing bugfix commits to add comments with links to the issue number so we don't start reverting bugfixes accidentally

**Comment by edsantiago** [comment]
Further info: [it's a POSIX thing](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline?rq=1):
```
3.206 Line

A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
```
