### ISSUE TITLE
Change the graphroot in storage.conf doesn't effect volume creation

### ISSUE THREAD

**Issue by jpork** [containers/libpod#2395]
I've changed `runroot` and `graphroot` in `/etc/containers/storage.conf`
The new path is reflected in `podman info` and is used for image and container handling.

But new volumes created with `podman volume create new-volume` are placed in the default location:
`/var/lib/containers/storage/new-volume/_data`
I can see it with `podman volume inspect new-volume` and in the filesystem.

I've found no other hint how to change the base dir for volumes.

I run: 
* podman version 1.0.0
* as root
* on 
  Operating System: Fedora 29 (Server Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:29
            Kernel: Linux 4.20.5-200.fc29.x86_64
      Architecture: x86-64

**Comment by mheon** [comment]
There is an (undocumented, and not present in the default configuration) option `volume_path` in libpod.conf that controls the location of the volume path.

Fix here is to:
1. Add that option to the default libpod.conf (commented out, but with a comment explaining its function)
2. Add the option to the libpod.conf manpage
3. Cause volume path to adjust by default when c/storage graph root is moved, as libpod's static dir does

**Comment by mheon** [comment]
#2397 should fix

**Comment by jpork** [comment]
This is exactly what I'm looking for. 

I've added

`volume_path = "/srv/volumes"`

to `/usr/share/containers/libpod.conf`

But it doesn't change the volume location so far. Its still in the default location `/var/lib/containers/storage/...`

**Comment by mheon** [comment]
We have a partial fix in #2397 that will ensure that volumes will always be a subdirectory of c/storage if the default storage directory moves.

Unfortunately, the volume_path option is still broken. I know what's wrong, but it will be a more substantial code change to fix, so we're going to hold it until after v1.1.0 is released

**Comment by mheon** [comment]
Final fix should be in https://github.com/containers/libpod/pull/2454

**Comment by Bill0412** [comment]
After change the location, you may also need to `podman system reset` as mentioned in https://github.com/containers/podman/issues/7039.
