### ISSUE TITLE
Add variable for global flags to runlabel command

### ISSUE THREAD

**Issue by mheon** [containers/libpod#2399]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

We need a variable in `podman runlabel` labels that expands to global Podman options, so we can pass through configuration (for example, storage config) to Podman commands being executed in labels.

**Steps to reproduce the issue:**

0. mkdir /tmp/new

1. podman --root=/tmp/new create --name test1 -t -i --label 'TEST=podman info'

2. podman --root=/tmp/new commit test1 testimg

3. podman --root /tmp/new container runlabel TEST testimg

**Describe the results you received:**

Podman uses the default storage root

**Describe the results you expected:**

Podman uses /tmp/new as a storage root

Ideal fix is something like $GLOBAL_OPTS we can throw in the label between `podman` and `info` to get the right options in there

**Comment by mheon** [comment]
@baude We discussed this via email, but the thread sort of died, so I'm throwing it up here

**Comment by rhatdan** [comment]
@baude Have you looked at this?
@QiWang19 Could you take a look at this?

**Comment by QiWang19** [comment]
@mheon I don't get the picture. Should the output of `podman --root /tmp/new container runlabel TEST testimg` be `GraphRoot: /tmp/new`?
like using `podman --root=/tmp/new create --name test1 -t -i --label 'TEST=podman --root=/tmp/new info'` instead of `podman --root=/tmp/new create --name test1 -t -i --label 'TEST=podman info'` ?

**Comment by mheon** [comment]
@QiWang19 `runlabel` reexecs a new Podman from the label set (`TEST`). We want to add a flag, say $GLOBAL_OPTS, that we can throw in `TEST` (for example, `TEST=podman $GLOBAL_OPTS info`), that expands to any global flags passed to Podman (storage options, log-level, syslog, etc)

**Comment by mheon** [comment]
Sorry, not a flag - a variable, similar to the other variables in runlabel

**Comment by mheon** [comment]
Once the variable is added, we then want the output of the last `podman runlabel` command to reflect the changed global options.
