### ISSUE TITLE
Consider adding Jenkins usage example to K8s plugin repo

### ISSUE THREAD

**Issue by marshallford** [containers/libpod#2414]
Hello all,

I'm trying to wrap my head around how I might use podman within a container in a Jenkins pipeline using the [Jenkins kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin) to build and push an image. Is there a pre-built libpod image for this use case? Does the podman "abstraction" over buildah change this [comparison overview](https://github.com/GoogleContainerTools/kaniko#comparison-with-other-tools) in regards to CICD? Might it be possible to submit a PR of an [example Jenkinsfile](https://github.com/jenkinsci/kubernetes-plugin/tree/master/examples) using podman and related best practices? I don't want to rely on public cloud providers always having a running docker daemon on host machines.

A bit of background: I've played with both [img](https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/) and Kaniko to build images on Jenkins but have run into a number of issues with both tools (caching, volume permissions, root/privilege issues, Jenkins JNLP timeouts, Kaniko doesn't support separate build and push steps, etc) and I am hoping to get podman working instead.

Thank you.

**Comment by mheon** [comment]
Specifically for building, you should find little to no difference between Podman and Buildah. `podman build` is actually executing the same code as `buildah bud` - the only difference are different default arguments for a few CLI flags. If you're only looking at building, `buildah` and `podman` should be identical, so the comparison overview for buildah should also apply here. The main difference in `podman` is adding the ability to run and manage containers based on those images.

As such, if you're only building, you might have better luck at the Buildah repo - a few of the Buildah maintainers do browse here, but you'll probably find better answers at the main repo.

**Comment by rhatdan** [comment]
@marshallford You can use either one in a container depending on your use case. You can also increase/decrease the security you need.  

For building a container in a locked down container you would be better off with buildah. 

You could use `buildah bud --isolation chroot -f Dockerfile .`

**Comment by marshallford** [comment]
@rhatdan Is there a community image for podman or buildah similar to `gcr.io/kaniko-project/executor`, `r.j3ss.co/img`, or `docker.io/dind`?

**Comment by rhatdan** [comment]
Not yet.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Have you had a chance to look at this?

**Comment by TomSweeneyRedHat** [comment]
Not yet

**Comment by marshallford** [comment]
@TomSweeneyRedHat curious if you have any updates regarding a community image.

**Comment by rhatdan** [comment]
@marshallford Any chance you want to take this on?

**Comment by hulkish** [comment]
Im interested in the community image, as well - would like to see this land!

**Comment by marshallford** [comment]
@hulkish I've started to work on an image under my own org (for now). It is a bit heavy and has an old version of runc but feel free to take a look or submit a PR. Thanks.

https://hub.docker.com/r/marshallford/podman
https://github.com/marshallford/podman

**Comment by hulkish** [comment]
@marshallford thanks!

**Comment by baude** [comment]
@TomSweeneyRedHat is this what you were hacking on the other day?

**Comment by baude** [comment]
still need this?

**Comment by rhatdan** [comment]
https://quay.io/user/podman
https://quay.io/user/buildah

Would be the suggested images to use to satisfy this need.  @marshallford if I am incorrect, please reopen this PR,
