### ISSUE TITLE
[feature request] Hide some host details

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2418]
/kind feature

**Description**
A container's interactive guest can get information about kernel and overlay from the host.

**Steps to reproduce the issue:**
1. run rootless container
2. run commands like `dmesg`, `uname -a`, `mount`

**Describe the results you received:**
Detailed information about the kernel, the container is running on and about mounts.

**Describe the results you expected:**
Limited capabilities to do so.

**Additional information you deem important (e.g. issue happens only occasionally):**
- There are work-arounds, f.e. fake binaries, to harm the guest from execution.
- Thinks like `echo 1 > /proc/sys/kernel/dmesg_restrict` can be run by root only and are systemwide.

**Output of `podman version`:**

```
Version:            1.0.1-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.7-dev
  Conmon:
    package: 'cri-o-1.12: /usr/lib/crio/bin/conmon'
    path: /usr/lib/crio/bin/conmon
    version: 'conmon version 1.12.4-dev, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 14659338240
  MemTotal: 18152755200
  OCIRuntime:
    package: 'cri-o-runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 495411200
  SwapTotal: 495411200
  arch: amd64
  cpus: 1
  hostname: ubuntu
  kernel: 4.18.0-15-generic
  os: linux
  rootless: true
  uptime: 15h 38m 3.32s (Approximately 0.62 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /home/tobwen/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/local/bin/fuse-overlayfs
  GraphRoot: /home/tobwen/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 8
  RunRoot: /tmp/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox 6 on latest Windows 10 Pro.

**Comment by rhatdan** [comment]
We don't try to make the kernel secret, so we would not want to block umount -a.

mount will only show the mounts inside of the container.

dmesg is blocked if you run with SELinux in enforcing mode.

**Comment by tobwen** [comment]
Okay, thanks for your reply.
