### ISSUE TITLE
podman image ls not working with podman 1.1.0

### ISSUE THREAD

**Issue by sysrich** [containers/libpod#2468]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm submitting Podman 1.1.0 to openSUSE Kubic, which now has pre-submission (aka staging) testing powered by openQA.

The submission is blocked, because "podman image ls" which is used repeatedly in the test suite is not working with Podman 1.1.0

Screenshot of the failure: https://openqa.opensuse.org/tests/864522#step/podman/18
RPM package (usable on openSUSE Tumbleweed or Kubic) https://download.opensuse.org/repositories/devel:/kubic/openSUSE_Tumbleweed/x86_64/podman-1.0.1-2.1.x86_64.rpm

**Steps to reproduce the issue:**

1. Install podman 1.1.0

2. Run `podman image ls`

**Describe the results you received:**

Help text implying the command syntax is not valid, showing various arguments for `podman image`

**Describe the results you expected:**

`podman image ls` should list images like `podman image images`

**Additional information you deem important (e.g. issue happens only occasionally):**

openSUSE cant ship podman 1.1.0 until we fix this, or adjust the tests to ignore it, which I imagine we probably don't want to do.

**Output of `podman version`:**

```
Version:            1.1.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.1.0
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.0-2.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 1.13.1, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed-kubic"'
    version: "1"
  MemFree: 1553190912
  MemTotal: 1904873472
  OCIRuntime:
    package: runc-1.0.0~rc6-4.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: linux-zent
  kernel: 4.20.10-5-default
  os: linux
  rootless: false
  uptime: 55.29s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Confirmed manually in KVM VMs in addition to openQA

**Comment by mheon** [comment]
@baude Looks like we missed something in cobra changes?

**Comment by mheon** [comment]
I think this one is fixed, but we have a rash of changes coming in to address issues we're finding from the Cobra migration.

@sysrich We'll probably cut a 1.1.1 in a few days once things have settled down and we're confident that we're not regressing - you might want to wait until that appears to release.

**Comment by baude** [comment]
yup! i have a pr for this one

**Comment by sysrich** [comment]
> @sysrich We'll probably cut a 1.1.1 in a few days once things have settled down and we're confident that we're not regressing - you might want to wait until that appears to release.

@mheon thanks, will do. And if there is anything I can do to help with getting 1.1.1 out the door, I'd be happy to help

**Comment by rhatdan** [comment]
@sysrich Please do not Release 1.1.  It needs a lot of work.  Testing it out is probably the best you can do for us now.  
Main issues we are having is around converting to new CLI, missing options, and misnamed commands.

**Comment by rhatdan** [comment]
This is fixed now.
