### ISSUE TITLE
1.1: signal handling: container no longer getting (or handling) SIGTERM

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2472]
In window 1:
```
# podman run --rm --name foo alpine sh -c 'trap "echo got SIGTERM" SIGTERM;echo READY;while :;do sleep 1;done'   
READY
```
In another window:
```
# podman stop foo
```
Expected: "got SIGTERM", a 10-second pause, then the container dies with SIGKILL and the `podman stop` command returns.

Actual: with podman-1.1.0-1.git006206a.fc29, the `stop` command succeeds immediately, the container is killed immediately (exit code 137, expected) and there is no "got SIGTERM".

**Comment by mheon** [comment]
Wild guess, but I think --timeout is being defaulted to 0, forcing us to immediately SIGKILL.

**Comment by mheon** [comment]
```
DEBU[0000] Stopping ctr 06ab1c43aed57577cc24c9cf2a9ede9e33d110c7a77792a0a4fe52bb702aa8da with timeout 0 
```

Yep.

**Comment by mheon** [comment]
Further problems: `--time` and `--timeout` are not mutually exclusive

**Comment by edsantiago** [comment]
Oh, how fascinating! Are `--time` and `--timeout` handled differently? Because I tried `podman stop --time=5 foo` and got the same behavior.

**Comment by edsantiago** [comment]
Oops, comment collision. Yeah, thanks for finding that.

**Comment by mheon** [comment]
Alright, very confusing things are happening here.

For one, I managed to get it to actually use the default timeout of 10 by stopping and restarting a container, which is sort of confusing.

For another, it's not printing the debug logging messages that indicate it actually hit the stop code when I use both `--time` and `--timeout`

**Comment by mheon** [comment]
`ctr.StopTimeout()` is sometimes returning 0. That's rather bizarre.

**Comment by mheon** [comment]
It's a static field from the DB. This makes no sense.

**Comment by mheon** [comment]
Container is not nil. Are we actually setting default to 0?

**Comment by mheon** [comment]
Yep, confirmed - we're somehow defaulting stop timeout to 0.

**Comment by mheon** [comment]
OK, finally worked this one out. #2476
