### ISSUE TITLE
podman container list: broken flag processing

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2489]
#2480 does not include any of the `ps` flags:
```
$ podman container list -a
Error: unknown shorthand flag: 'a' in -a
$ podman container list --help
[ does not actually list any flags other than -h ]
```
Cause: not running `cmd/podman/ps.go:init()`

Even more fun side effect:
```
$ podman container list
ERRO[0000] Could not find flag trace
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```
(because of the `c.Bool("trace")` in line 197, added by #1692).

master @ 4a109a71996e99c9a95b639bbbee1c5e30450c97

**Comment by edsantiago** [comment]
@baude PTAL

**Comment by Lagrang** [comment]
Also flags processing broken for container command parameters.
For instance, following command `podman create $IMAGE_NAME -DsomeParam=value` 
fails with error `Error: unknown shorthand flag: 'D' in -DsomeParam=value`

**Comment by rhatdan** [comment]
@Lagrang Options must come before $IMAGE_NAME

**Comment by mheon** [comment]
@rhatdan I think he's trying to pass the flag into the container
@Lagrang If so, 1.1.1 has a fix included

**Comment by edsantiago** [comment]
Yep, looks fixed in master; thanks.
