### ISSUE TITLE
podman: point to slirp4netns

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2506]
/kind feature

**Description**
It should be possible to point to the binary of _slirp4netns_ in commandline parameter and in config.

Right now, it seems to look in $PATH only: https://github.com/containers/libpod/issues/1234

**Comment by tobwen** [comment]
Can I bump this? It's pretty important, since there's no other way than to hack with PATH variables right now :-(

**Comment by rhatdan** [comment]
Open a PR to make a change.

**Comment by tobwen** [comment]
@rhatdan I'd love to, but I'm not a `go` coder. Maybe I can hack it from existing code. Let me try.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2538
