### ISSUE TITLE
podman cp extracts tarballs, unlike docker cp command

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#2509]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The new `cp` command has some kind of auto-extract feature ?

**Steps to reproduce the issue:**

1. sudo podman cp tinycore-tar-exporter:/tmp/rootfs64.tar.gz ./

**Describe the results you received:**

The results of the tarball was extracted.

**Describe the results you expected:**

The file to be copied, without extraction.

**Output of `podman version`:**

```
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.12
Git Commit:         f3a3d8e28e4b8ec06dd11ec156c10e243165f19d
Built:              Sun Mar  3 20:50:19 2019
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
@QiWang19 Very the behaviour versus Docker, and make sure we match.
