### ISSUE TITLE
podman: tries to create directories in /var while being rootless 

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2510]
/kind bug

**Description**
When trying to run _podman_ rootless with `--log-level=debug` this message occures. 

```
DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers/cache: permission denied
```

**Expected**
_podman_ shouldn't try to write to `/var/lib/containers/cache` when it's in rootless mode.

Might be connected with https://github.com/containers/libpod/issues/2508

**Comment by mheon** [comment]
It seems like some paths might be set incorrectly - we should be using paths exclusively under `/home` with the default configuration.

**Comment by mheon** [comment]
Possibly related to #2508 - both of them seem to be failing to detect that we're rootless and adjust paths to appropriate defaults

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2537

**Comment by tobwen** [comment]
It's alive again on rootless.

```
DEBU[0000] Error creating parent directories for blob-info-cache-v1.boltdb, using a memory-only cache: mkdir /var/lib/containers: permission denied
```

**Comment by rhatdan** [comment]
@giuseppe Anything to do with your rootless merge?

**Comment by mheon** [comment]
I would bet this was the big rootless single userns patch that just merged.

**Comment by giuseppe** [comment]
this is related to a change in containers/image where we use `os.Geteuid()` inside of a user namespace

**Comment by giuseppe** [comment]
PR: https://github.com/containers/image/pull/612

**Comment by TomasTomecek** [comment]
also got bitten by this; will we get a new release soon?
