### ISSUE TITLE
RFE Add --extract option to podman cp commands

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2520]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind feature

**Description**
This is a request for added functionality.  In #2517 we stopped the ability to extract a tar file during a `podman cp` command.  That's the right thing to do for a straight cp.  However I'd like to see a `podman cp --extract my.tar /mydir` option added such that if a tar file was being copied to the container, then it would be extracted there too.  Kind of a one stop shopping thing.

The old code around line 273 in that PR would have to be reinstated under an `if c.extract()` type of statement.

I'd suggest that if a destination argument was not given, the file would be extracted in the container's root directory, otherwise in the Destination directory given as an argument, making that directory first if it was not present. 

I've suggested `--extract` as the option name, but I'm not married to that.  IDK if Docker does something similar, if they do we may want to emulate that instead.

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 FYI

**Comment by QiWang19** [comment]
:ok_hand:
