### ISSUE TITLE
podman  ps --format status=stopped is invalid

### ISSUE THREAD

**Issue by ekultails** [containers/libpod#2526]
/kind bug

**Description**

These appear to be the supported libpod/podman states:
https://github.com/containers/libpod/blob/993b3a17c58826365136f49d7760f8ac88e320b2/pkg/adapter/pods_remote.go#L246-L257

However, the stopped state is marked as invalid when trying to query it. Even the manual page suggests it should be a supported option.

```
$ man podman-ps | grep Status
       │.Status     │ Status of container                      │
       │status   │ [Status] Container's status, e.g running, stopped                   │
```

**Steps to reproduce the issue:**

1. `$ podman ps -f "status=stopped"`

**Describe the results you received:**

```
$ podman ps -f "status=stopped"
invalid filter: stopped is not a valid status
```

**Describe the results you expected:**

```
$ podman ps -f "status=stopped"
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This was originally brought up in this PR: https://github.com/containers/libpod/pull/2524

**Output of `podman version`:**

```
$ podman version
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 15:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: '"49780a1cf10d572edc4e1ea3b8a8429ce391d47d"'
  go version: go1.11.4
  podman version: 1.0.0
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 22500847616
  MemTotal: 33543561216
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 5368705024
  SwapTotal: 5368705024
  arch: amd64
  cpus: 8
  hostname: workstation.localhost
  kernel: 4.19.24-1.lts.fc29.x86_64
  os: linux
  rootless: true
  uptime: 5h 55m 16.81s (Approximately 0.24 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical (laptop).

**Comment by ekultails** [comment]
On a somewhat related note, querying for the `restarting` state appears to work but might be a false-positive since libpod does not fully support this state. Maybe this should be marked invalid?

```
$ podman ps -f status=restarting
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

**Comment by mheon** [comment]
Going to try and take a look at this today, time permitting

**Comment by mheon** [comment]
#2586 to fix

**Comment by mheon** [comment]
(I've actually just mapped the Stopped state to Exited in that PR - they're sufficiently similar as to not really merit filtering separately. Stopped is an intermediate that that quickly transitions to Exited.

**Comment by edsantiago** [comment]
Reopening, because although #2586 does handle some corner cases, it doesn't actually address the issue raised in this PR: `--filter=stopped` is still rejected. (And, as @ekultails noted, `stopped` is the second example in the man page). (And, it's a valid state per `libpod/container.go`)

**Comment by mheon** [comment]
@edsantiago I could make `stopped` map to `exited` as well, which might solve this.

(They are distinct states in libpod, but we transition from `stopped` to `exited` as soon as the cleanup process runs - less than a second, probably)

**Comment by edsantiago** [comment]
@mheon I interpret your suggestion as: "I could silently translate the string `stopped`, when given as a command-line input to the `state` filter, into `exited`". If that's your intention, it sounds like a good solution to me.
