### ISSUE TITLE
[bug in cobra] podman invalid-command: outputs help msg to stderr, exits 0

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2530]
```
$ podman no-such-command
manage pods and images

Usage:
  podman [flags]
  podman [command]
....
$ echo $?
0
```

Expected: 
```
podman: no-such-command: command not found
[Exit 1]
```
This appears to be a [known bug in cobra](https://github.com/spf13/cobra/issues/582). I cannot find a workaround, but of course there may be one I haven't thought of.

There is a [pr against cobra](https://github.com/spf13/cobra/pull/642) but it has sat idle, without comment, for a year.

**Comment by rhatdan** [comment]
This has been fixed.
