### ISSUE TITLE
podman build image vs container

### ISSUE THREAD

**Issue by jitka** [containers/libpod#2554]
/kind bug

**Description**

**Steps to reproduce the issue:**

Fedora 28, podman 1.0.0, buildah not installed

1. `man podman`
```
| podman-build(1)     │ Build a container using a Dockerfile. |
```
2. `man podmain-build`
```
NAME
       podman-build - Build a container image using a Dockerfile.
```

**Describe the results you received:**
 When I run `podman build ..` then `podman container ls` do not show this container only `podman images` show it. 

**Describe the results you expected:**
When I run `docker build ...` and `docker container ls` I see a container and I can run other commands on it.

**Additional information you deem important (e.g. issue happens only occasionally):**
I am new to container. Any beginers guide about podman says 'its just as docker, but without deamon'. I miss tutorial about creating and handling container (not just image)   

`dnf install buildah` do not fix this issue, so I think this is a podman issue not buildah.

**Comment by jitka** [comment]
I found that `podman container ls -a` work just like `docker container ls`. So this is primary documentation issue.

**Comment by TomSweeneyRedHat** [comment]
@jitka Thanks for the issue report.  I do have a question or two if you've the time.  Can you tell me which version of Docker that you're using?  I'm using:
```
# docker -v
Docker version 18.09.0, build 4d60db4
```

and when I do `docker container ls` after the build, I'm not seeing a container there (but didn't expect too).  Did you follow steps like the below or others?

```
# cat ~/Dockerfile.alpine
FROM alpine 

# docker build -t tom -f ~/Dockerfile.alpine .
Sending build context to Docker daemon  3.453GB
Step 1/1 : FROM alpine
latest: Pulling from library/alpine
6c40cc604d8e: Pull complete 
Digest: sha256:b3dbf31b77fd99d9c08f780ce6f5282aba076d70a513a8be859d8d3a4d0c92b8
Status: Downloaded newer image for alpine:latest
 ---> caf27325b298
Successfully built caf27325b298
Successfully tagged tom:latest

# docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
alpine              latest              caf27325b298        4 weeks ago         5.53MB
tom                 latest              caf27325b298        4 weeks ago         5.53MB
```

That being said, `podman container ls` seems to be having issues on my machine unrelated to this, I need to chase that for a bit.

**Comment by TomSweeneyRedHat** [comment]
OK, latest upstream Podman 1.2.0-dev doesn't have the issue that I was seeing and functions in the same way as Docker.

**Comment by rhatdan** [comment]
On podman 1.1.2
```
man podman build
NAME
       podman-build - Build a container image using a Dockerfile.
```

**Comment by jitka** [comment]
Sorry it's hard to reproduce it since I am new. I have lot of testing container and i struggle with all of the `prune` commands. Also I am a bit lose in all `id`s `names` `tags` things - where it was created, how long it is valid. If I run to this issue again I will report it with Docerfile and exact commands i tried. Thanks for the answers.

**Comment by TomSweeneyRedHat** [comment]
No worries @jtka.  Thanks for the update and I hope you enjoy the world of containers.
If you encounter the issue again, please do either reopen this issue or create a new one, which ever works best for you.
