### ISSUE TITLE
How to use a bridge "virbr1" created by libvirt to run a container?

### ISSUE THREAD

**Issue by anilv4** [containers/libpod#2559]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind network usage question

**Description**

1. I would like to use the following bridge "virbr1" created by libvirt to run a container.
~~~
# brctl show
bridge name	bridge id		STP enabled	interfaces
cni0		8000.6a23de05fdd2	no		
virbr0		8000.5254007fa2f3	yes		virbr0-nic
virbr1		8000.525400ee6dae	yes		virbr1-nic
~~~

2. I would also like to set a custom IP when I start this container.

3. Are 1 and 2 doable using podman?

**Comment by mheon** [comment]
This might be possible using CNI. I don't believe either are possible without running as root if that is your usecase.

**Comment by rhatdan** [comment]
Any movement on this one?  Seems to be something people are beginning to request.

**Comment by mheon** [comment]
I think we can do this with CNI as of right now, though figuring out exactly how and documenting it is worthwhile

**Comment by anilv4** [comment]
The workaround I used was to start the libvirt VM using "cni0" to do my testing. However I do not think its the right way to do it.
--

**Comment by anilv4** [comment]
Reopening,  closed by mistake.

> I think we can do this with CNI as of right now, though figuring out exactly how and documenting it is worthwhile

The workaround I used was to start the libvirt VM using "cni0".  However I do not think it was the right way to do it and it was for a simple testing.
--
Once you have the documentation, I can test the steps.

**Comment by anilv4** [comment]
Closing this as I got a reply from @mccv1r0 in https://github.com/containernetworking/cni/issues/638.
