### ISSUE TITLE
podman exec fails on --user

### ISSUE THREAD

**Issue by MarcoFalke** [containers/libpod#2566]
/kind bug

**Description**

Podman always fails with 

```
$ podman exec -u testu -i naughty_hugle echo
Error: unable to find user testu: no matching entries in passwd file
```

**Steps to reproduce the issue:**

```sh
$ podman run -i -t --rm ubuntu:bionic bash
# useradd -ms /bin/bash -U testu

// new terminal
$ podman container ls --all # find it
$ podman exec -u testu -i naughty_hugle true
Error: unable to find user testu: no matching entries in passwd file
```

For comparison in docker:

```sh
$ sudo docker run -i -t --rm ubuntu:bionic bash
# useradd -ms /bin/bash -U testu

// new terminal
$ sudo docker exec -u testu  -i laughing_feistel echo works
works
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.1.2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Works fine as root
@giuseppe Mind taking a look?

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2569
