### ISSUE TITLE
cached podman build fails on `COPY /dir` with symlink

### ISSUE THREAD

**Issue by praiskup** [containers/libpod#2567]
There's
```
$ ls s2i/bin/ -l
total 8
-rwxr-xr-x. 1 praiskup praiskup 210 Mar  7 06:47 assemble
lrwxrwxrwx. 1 praiskup praiskup  23 Mar  7 06:47 run -> /usr/bin/run-postgresql
-rwxr-xr-x. 1 praiskup praiskup  31 Mar  7 06:47 usage
```

Dockerfile contains `COPY ./s2i/bin/ $STI_SCRIPTS_PATH` (where scripts path is `/usr/libexec/s2i` which is set by FROM image).

The error output is:
```
STEP 18: COPY ./s2i/bin/ $STI_SCRIPTS_PATH
Error: error checking if cached image exists from a previous build: error checking if copied files match: error resolving symlinks and comparing modified times: "/home/praiskup/rh/projects/sclorg/postgresql-container/9.6/s2i/bin": error checking if modified time of resolved symbolic link is greater: error walking file tree "/home/praiskup/rh/projects/sclorg/postgresql-container/9.6/s2i/bin": error evaluating symlink "s2i/bin/run": lstat /usr: no such file or directory
: exit status 1
```
So first build is fine, second (from caches) fails.  Do***r used to worked here (sclorg/postgresql-container.git).

**Comment by rhatdan** [comment]
This should be opened for buildah.  Since this code is vendored in from there.

@TomSweeneyRedHat Can you take a look at this.

**Comment by rhatdan** [comment]
Issue is being worked on in Buildah.
@TomSweeneyRedHat Any update?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Could you add a link here also.

**Comment by TomSweeneyRedHat** [comment]
I think this is related to https://github.com/containers/buildah/issues/1219 which I need to get back up higher in the list.

**Comment by praiskup** [comment]
Agreed, it seems to be duplicate.  Thanks.
