### ISSUE TITLE
podman build --help mentions squash is a NOOP

### ISSUE THREAD

**Issue by pkubatrh** [containers/libpod#2568]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
`podman build --help` mentions `--squash` is a NOOP even though it seems to be working. The man page of `podman build` does not mention that it is a NOOP.

**Steps to reproduce the issue:**

1. podman build --help | grep "\-\-squash"

**Describe the results you received:**
--squash Squash newly built layers into a single new layer. The build process does not currently support caching so this is a NOOP.

**Describe the results you expected:**
--squash Squash newly built layers into a single new layer.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:       1.0.0
Go Version:    go1.10.7
Git Commit:    "327964bfa96f91f39042b87b3e52388f448fd66e"
Built:         Mon Jan 14 21:38:13 2019
OS/Arch:       linux/amd64

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Closed via #2625.  Thanks again for the issue and eagle eye @pkubatrh !

**Comment by rhatdan** [comment]
Looks like this is fixed.
