### ISSUE TITLE
rootless: "podman run" gives an imperfect error message if subgid not configured correctly

### ISSUE THREAD

**Issue by sysrich** [containers/libpod#2584]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Scenario - /etc/subuid configured properly, but /etc/subgid not configured at all

User runs `podman run hello-world` and gets 

> ERRO[0000] error creating libpod runtime: Error running podman info while refreshing state: exit status 1 

This is rather confusing and does not help the user debug what actually went wrong.
If the user does something different like `podman image ls` they get a more helpful error message

> ERRO[0000] No subgid ranges found for group "ilmehtar" in /etc/subgid 

I would expect `podman run` to give the same error message given the misconfiguration is the same for `podman run` as it is for `podman image`

**Output of `podman version`:**

```
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-3.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 1.13.1, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20190301"
  MemFree: 11381452800
  MemTotal: 33540861952
  OCIRuntime:
    package: runc-1.0.0~rc6-3.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 34359734272
  SwapTotal: 34359734272
  arch: amd64
  cpus: 8
  hostname: iwreckit.suse.de
  kernel: 4.20.12-1-default
  os: linux
  rootless: true
  uptime: 94h 51m 26.89s (Approximately 3.92 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /home/ilmehtar/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/ilmehtar/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/ilmehtar/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
@giuseppe @mheon Could you guys take a look?

**Comment by giuseppe** [comment]
@rhatdan this is the "podman info" error not being propagated to the caller.  You were working on a patch for that, do you still have it?

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2588
