### ISSUE TITLE
crio-umount.conf and seccomp.json are present in both cri-o and libpod

### ISSUE THREAD

**Issue by lsm5** [containers/libpod#2596]
RE: $SUBJECT, `ETCDIR_LIBPOD` in libpod and `ETCDIR_CRIO` in cri-o are both set to `/etc/crio`, this causes conflicts with the cri-o package unless of course, I change the install rules for the podman deb package.

Do these 2 files need to be present in both repos?

@rhatdan @mheon @baude

**Comment by mheon** [comment]
We can drop the umount config here, it's not used elsewhere.

Seccomp should be moved out of both repositories and sourced from somewhere common - it's not specific to any of our tools. I think there's a containers-seccomp repo we created for this?

**Comment by mheon** [comment]
ETCDIR_LIBPOD is set to /etc/crio in the makefile, apparently, which seems very wrong

**Comment by lsm5** [comment]
@mheon can't seem to find the containers-seccomp repo, do you have a link for that?

**Comment by mheon** [comment]
It lives here: https://github.com/seccomp/containers-golang

Unfortunately, I think my memory was faulty - it doesn't seem to include the defaults

**Comment by lsm5** [comment]
@mheon I notice the doc mentions it generates a `default.json`. It's intended to be the same as our `seccomp.json`, yes? Also, not sure what defaults you mean, but is that something you can get included upstream maybe today? I guess I can create another package for containers-seccomp for ubuntu.
