### ISSUE TITLE
inconsistent behavior with "rm" and "rm -f"

### ISSUE THREAD

**Issue by ikke-t** [containers/libpod#2599]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

```podman rm -f``` returns different value depending than without -f switch for non existing container.  I noticed this while typoing container name by accident.

**Steps to reproduce the issue:**

1. There is no container foobar, see here how return value differs silently: 
```
[vagrant@ikke-fedora ~]$ sudo podman rm  foobar
Error: unable to find container foobar: no container with name or ID foobar found: no such container
[vagrant@ikke-fedora ~]$ echo $?
1
[vagrant@ikke-fedora ~]$ sudo podman rm -f foobar
[vagrant@ikke-fedora ~]$ echo $?
0
```

**Describe the results you received:**

podman rm -f silently returned ok for non existent container name

**Describe the results you expected:**

Error message: "Error: unable to find container foobar: no container with name or ID foobar found: no such container"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

build from last night:
```
https://koji.fedoraproject.org/koji/buildinfo?buildID=1227307
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I believe this is intentional, to mimic the behavior of Coreutils rm. I
don't think we're completely set on retaining the behavior though.

**Comment by giuseppe** [comment]
Docker returns an error if the container is not found.

**Comment by rhatdan** [comment]
@ikke-t Do you need the same behaviour for some reason?

**Comment by ikke-t** [comment]
This is not critical to me. I just would have been happy to spot an error, which silently disappears in current behavior. I found it odd behavior.

**Comment by rhatdan** [comment]
I think we will stick with the current behaviour.
