### ISSUE TITLE
podman ls not working on podman 1.1.2

### ISSUE THREAD

**Issue by sysrich** [containers/libpod#2607]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Like https://github.com/containers/libpod/issues/2468, but this time with `podman ls`

**Steps to reproduce the issue:**

1. Install podman 1.1.2

2. Run `podman ls`

**Describe the results you received:**

Help text implying an invalid argument

**Describe the results you expected:**

Same result as `podman container ls`

**Output of `podman version`:**

```
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 1.13.1, commit: '
  Distribution:
    distribution: '"opensuse-tumbleweed-kubic"'
    version: "20190310"
  MemFree: 3137134592
  MemTotal: 4033679360
  OCIRuntime:
    package: runc-1.0.0~rc6-3.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: static
  kernel: 4.20.13-1-default
  os: linux
  rootless: false
  uptime: 6m 54.23s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
`podman ls` is not a valid command.
The valid commands are:
`podman container ls`
and
`podman images ls`

**Comment by sysrich** [comment]
@rhatdan But it worked in 1.0.x and earlier and I miss it now it’s gone :)

Are we sure we don’t mind it’s absence?

**Comment by rhatdan** [comment]
The fact that it worked was a mistake and it was never documented.

**Comment by sysrich** [comment]
Okay - I will mourn the loss with a smile. Thanks for clearing that’s up
