### ISSUE TITLE
[podman] could not get runtime / could not find a working binary

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2614]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
I'm trying to run _podman_ rootless from the user's home directory (nothing is installed into root). When pointing to the binaries in CLI or via config, _runc_ binary isn't found.

**Steps to reproduce the issue:**

1. `~/podman/usr/local/bin/podman --log-level=debug --conmon /home/podman/podman/usr/local/libexec/crio/conmon --network-cmd-path /home/podman/podman/usr/local/bin/slirp4netns --runtime /home/podman/podman/usr/local/sbin/runc run busybox sh`
2. `~/podman/usr/local/bin/podman --log-level=debug --config /home/podman/rootless.conf run busybox sh`

**Describe the results you received:**
```
INFO[0000] running as rootless
DEBU[0000] Initializing boltdb state at /home/podman/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver vfs
DEBU[0000] Using graph root /home/podman/.local/share/containers/storage
DEBU[0000] Using run root /home/podman/rundir
DEBU[0000] Using static dir /home/podman/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /home/podman/rundir/libpod/tmp
DEBU[0000] Using volume path /home/podman/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Not configuring container store
ERRO[0000] error creating libpod runtime: Error running ./podman info while refreshing state: Error: could not get runtime: could not find a working binary (configured options: map[runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc]]): invalid argument
: exit status 125
```

**Output of `podman version`:**
```
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         1466c8a2f8020c5cc1541348f5f6533239f94136
Built:              Mon Mar 11 20:18:28 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
Error: could not get runtime: could not find a working binary (configured options: map[runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc]]): invalid argument
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian 9 on VirtualBox 6 on Windows 10 on AMD 64

**Comment by giuseppe** [comment]
Are you seeing the issue only for the second command?

the `--runtime /home/podman/podman/usr/local/sbin/runc` is not persisted into the configuration.  In facts we obsoleted the relative configuration in `libpod.conf`.

Now we expect a map of runtime to be present "runtime" -> "list of paths".

If `[runtimes]` is not overriden in the rootless configuration file, then the settings in `/etc/libpod/libpod.conf` are used.

You could either configure it globally, or override for your user in `libpod.conf`.

**Comment by tobwen** [comment]
> Are you seeing the issue only for the second command?

Yes

> Now we expect a map of runtime to be present "runtime" => "list of path"

`--runtime [ /home/podman/podman/usr/local/sbin/runc ] ` ?

> You could either configure it globally, or override for your user in libpod.conf.
Hmm, that's a very uncommon behavior. Normally it's like:

`global config > user config > environment variable > CLI switch`

I think I've read, _podman_ (or _runc_) behave similar?

**Comment by giuseppe** [comment]
> > Now we expect a map of runtime to be present "runtime" => "list of path"
> 
> `--runtime [ /home/podman/podman/usr/local/sbin/runc ] ` ?
> 
> > You could either configure it globally, or override for your user in libpod.conf.
> > Hmm, that's a very uncommon behavior. Normally it's like:
> 
> `global config > user config > environment variable > CLI switch`

the issue is that the first `--runtime` is not stored into the configuration file.

If you want to override it, then you need to specify it again on the CLI for the second command.

**Comment by tobwen** [comment]
> the issue is that the first `--runtime` is not stored into the configuration file.
> 
> If you want to override it, then you need to specify it again on the CLI for the second command

Sorry, seems like I'm too stupid to do this on my own. Could you please give me the correct command line to try it?

**Comment by giuseppe** [comment]
```
~/podman/usr/local/bin/podman --runtime /home/podman/podman/usr/local/sbin/runc --log-level=debug --config /home/podman/rootless.conf run busybox sh
```

**Comment by tobwen** [comment]
I will try it soon. So I cannot run a config-less container?

**Comment by giuseppe** [comment]
you can set it in the `libpod.conf` file:

```
runtime = "runc"

[runtimes]
runc = [
             "/path/to/your//runc",
]
```

**Comment by giuseppe** [comment]
did it work?

**Comment by tobwen** [comment]
I don't want to use a config file, but it also doesn't work with this one:

```
# Paths to look for the Conmon container manager binary
conmon_path = [ "/home/podman/podman/usr/local/libexec/crio/conmon" ]

# Environment variables to pass into conmon
# conmon_env_vars = [ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" ]

# CGroup Manager - valid values are "systemd" and "cgroupfs"
cgroup_manager = "systemd"

# Container init binary
init_path = "/home/podman/podman/usr/libexec/podman/catatonit"

# Directory for persistent libpod files (database, etc)
static_dir = "/home/podman/podman/containers/"

# Directory for temporary files. Must be tmpfs (wiped after reboot)
# tmp_dir = "/var/run/libpod"

# Maximum size of log files (in bytes)
# -1 is unlimited
max_log_size = -1

# Whether to use chroot instead of pivot_root in the runtime
no_pivot_root = false

num_locks = 2048

runtime = "runc"

[runtimes]
runc = [
     "/home/podman/podman/usr/local/sbin/runc",
]
```

results in 

```
$ /home/podman/podman/usr/local/bin/podman --runtime /home/podman/podman/usr/local/sbin/runc --log-level=debug --config /home/podman/podman/libpod.conf run busybox sh
INFO[0000] running as rootless
DEBU[0000] Initializing boltdb state at /home/podman/podman/containers/bolt_state.db
DEBU[0000] Using graph driver vfs
DEBU[0000] Using graph root /home/podman/.local/share/containers/storage
DEBU[0000] Using run root /home/podman/rundir
DEBU[0000] Using static dir /home/podman/podman/containers/
DEBU[0000] Using tmp dir /home/podman/rundir/libpod/tmp
DEBU[0000] Using volume path /home/podman/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] Not configuring container store
ERRO[0000] error creating libpod runtime: Error running /home/podman/podman/usr/local/bin/podman info while refreshing state: Error: could not get runtime: could not find a working binary (configured options: map[runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc]]): invalid argument
: exit status 125
```

**Comment by tobwen** [comment]
But this works now: 
```
/home/podman/podman/usr/local/bin/podman info --debug --runtime /home/podman/podman/usr/local/sbin/runc --log-level=debug --config /home/podman/podman/libpod.conf
```

```
debug:
  compiler: gc
  git commit: 1466c8a2f8020c5cc1541348f5f6533239f94136
  go version: go1.11.5
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: Unknown
    path: /home/podman/podman/usr/local/libexec/crio/conmon
    version: 'conmon version , commit: cc2b49590a485da9bd358440f92f219dfd6b230f'
  Distribution:
    distribution: debian
    version: "9"
  MemFree: 34979520512
  MemTotal: 38205562880
  OCIRuntime:
    package: Unknown
    path: /home/podman/podman/usr/local/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
      spec: 1.0.1-dev
  SwapFree: 8586784768
  SwapTotal: 8586784768
  arch: amd64
  cpus: 8
  hostname: pgsql
  kernel: 4.19.0-0.bpo.2-amd64
  os: linux
  rootless: true
  uptime: 73h 21m 49.82s (Approximately 3.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /home/podman/rundir
  VolumePath: /home/podman/.local/share/containers/storage/volumes

```

**Comment by giuseppe** [comment]
ah right, because runtime data is copied from the main configuration file.  We should probably not do it if it is overriden in the user config file.

If you override from the CLI then it should always work

**Comment by tobwen** [comment]
> because runtime data is copied from the main configuration file

But from which? I don't have a main configuration file in `/etc/`, since I've built and installed rootless. Override mode should work like in any application: `global config > user config > environment variable > CLI switch`

1. `/etc/containers/libpod.conf`
2. `$HOME/.local/containers/libpod.conf` (1 gets ignored)
3. `runtime=runc podman` (1, 2 get ignored)
4. `podman --runtime run` (1, 2, 3 get ignored)

**Comment by giuseppe** [comment]
@tobwen I've added a patch to https://github.com/containers/libpod/pull/2617

could you try it out?

**Comment by tobwen** [comment]
Trying right now.

**Comment by tobwen** [comment]
It works now. Good work!
