### ISSUE TITLE
possible race condition in `podman run --rm` 

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#2619]
/kind bug

**Description**

I have a workflow for development that includes running a container and then immediately running the container again. I updated podman today and it started failing on the second invocation because of a race condition it seems. For example I run 

```
cosa build qemu metal-bios metal-uefi && cosa buildextend-installer
```

where `cosa` [calls out to podman](https://github.com/coreos/coreos-assembler/blame/bc7ce186ccc73a880a9cff9ded0814b8472cd61d/README.md#L89-L99) with a `--name cosa --it --rm`. On execution of the second command I now often see:

```
Error: error creating container storage: the container name "cosa" is already in use by "a09c40e38c99ea6089382647d4808c59098a5d53c791cb392a8be145cb7146de". You have to remove that container to be able to reuse that name.: that name is ae...
```

**Steps to reproduce the issue:**

1. run consecutive containers with the same name back to back

```
[dustymabe@media fedora]$ sudo podman run --rm --name foo -it registry.fedoraproject.org/fedora:29 echo hello &&  sudo podman run --rm --name foo -it registry.fedoraproject.org/fedora:29 echo hello
hello
Error: error creating container storage: the container name "foo" is already in use by "3d36176acb34edbdb1dab8671ba356cc73ab76e7aba37354a1cc93e04a65d17a". You have to remove that container to be able to reuse that name.: that name is ale
```

**Describe the results you received:**

An error message telling me the container existed when it should not because it was executed with `--rm`.

**Describe the results you expected:**

No error.

**Additional information you deem important (e.g. issue happens only occasionally):**

Doesn't happen all the time. But have hit it several times today.

**Output of `podman version`:**

```
[dustymabe@media fedora]$ sudo podman version
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 13:10:31 2019
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
[dustymabe@media fedora]$ sudo podman info --debug
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 247222272
  MemTotal: 20999905280
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 3774595072
  SwapTotal: 4294963200
  arch: amd64
  cpus: 8
  hostname: media
  kernel: 4.20.8-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 575h 30m 15.71s (Approximately 23.96 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 30
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 332
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Desktop machine.

**Comment by mheon** [comment]
Note to self: while looking at the code here, I found the backend for `podman export`, and it's very, very broken. Fix that when I get a chance.

**Comment by mheon** [comment]
Oh, only broken for rootless. Good news, that.

**Comment by mheon** [comment]
Anyways, here's our race.

We launch `--rm` as part of the container cleanup process, which fires once the container is finished. However, it fires async, and there's no guarantee it completes before the main Podman process exits.

We need to add code at the end of `podman run` (and possible `podman start`? Probably not necessary there, but could be good form) to wait until the container is deleted if `--rm` is specified before exiting. Not necessary for non-`rm` (the cleanup process still fires, but all it's doing is unmounting the container, so it's no big deal if something else happens immediately thereafter... If the container restarts, cleanup fires afterwards, finds that it's running, exits instead).

**Comment by mheon** [comment]
Ought to be possible to use events to do this, now that events has landed.

**Comment by giuseppe** [comment]
> Note to self: while looking at the code here, I found the backend for `podman export`, and it's very, very broken. Fix that when I get a chance.

we recently fixed an issue with rootless `podman export`.  What issue are you still seeing?

**Comment by giuseppe** [comment]
We could probably just delete the container before exiting and race with `cleanup` in doing that, one of the two will fail with `ErrNoSuchCtr`, since we don't catch the errors for both of them so we should be fine.  What do you think?  I've tried locally and it seems to work fine.  I can open a PR if you are fine with this solution.

**Comment by rhatdan** [comment]
I am fine with that solution.

**Comment by mheon** [comment]
Yeah, that sounds fine
