### ISSUE TITLE
Support external network namespaces from podman run command.

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#262]
A long time ago I opened a PR to support setting up a network namespace outside of Docker and have the container created by Docker join that network. 

https://github.com/docker/libnetwork/pull/372.

Upstream Docker rejected this... :^(
Let's get it into podman

Basically

podman run --net path:/PATH/TO/NETNS fedora sh

**Comment by rhatdan** [comment]
Any movement on this issue?

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
@baude You want me to give this to someone else?  Like @haircommander?

**Comment by rhatdan** [comment]
@baude Ever get a chance to look at this?

**Comment by haircommander** [comment]
@rhatdan @mheon I am not quite sure, but I'm pretty sure --net ns:<path> works for this purpose. I just added the path option on a branch, but is it necessary with ns?

**Comment by mheon** [comment]
@haircommander I think we didn't have `--net=ns:` when this was written - I think that we can close this since it's been added

**Comment by vrothberg** [comment]
I agree with @mheon. Joining another container's network NS is working since commit 41c7e43b4dbb. Looking at the manpage, I think that some of the help messages could be a bit more informative but we can address that in a more organized fashion.
