### ISSUE TITLE
CI: add manpage-crossref checker

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2630]
`hack/podman-commands.sh` keeps finding instances of new podman commands that aren't being properly added to man pages. Could we add this to our CI?

**Comment by edsantiago** [comment]
@cevich when you have a moment please...

**Comment by cevich** [comment]
Yes we should add this to CI, probably as part of `gating_task` or `contrib/cirrus/unit_test.sh`.  Yep I'll toss up a PR for this, thx for asking.

**Comment by rhatdan** [comment]
Awesome.
