### ISSUE TITLE
Docs for --net in docs/podman-build.1.md shouldn't talk about buildah

### ISSUE THREAD

**Issue by jwakely** [containers/libpod#2639]
The `podman-build.1` man page appears to have been taken straight from `buildah`, and still refers to `buildah`:

> or it can be "host" to indicate that the network namespace in which `buildah` itself is being run should be reused

Since this is the man page for a `podman` command it should refer to `podman` not some other command that isn't actually being run.

**Comment by TomSweeneyRedHat** [comment]
@jwakely TYVM for the eagle eye and more importantly the issue.  FWIW, the man page as a whole grew out of Buildah and as we add options to bud there, we have to add them to the Podman build page too.   We obviously missed these occurrences when we added these particular options, so again thanks for letting us know.  I've just created #2640 to clean it up.

**Comment by jwakely** [comment]
Thanks!
