### ISSUE TITLE
support slirp4netns  --disable-host-loopback

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#2642]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

By default ports listening on `127.0.0.1:*` on the host are accessible from slirp4netns containers as `10.0.2.2:*`.
It would be good to launch `slirp4netns` with `--disable-host-loopback` to prohibit connecting to these ports. https://github.com/rootless-containers/slirp4netns/blob/master/slirp4netns.1.md#filtering-connections

Requires `slirp4netns` v0.3 or later. (Feature detection can be implemented as `slirp4netns --help | grep -- --disable-host-loopback`, although looks ugly)

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/compare/master...giuseppe:slirp-disable-lo?expand=1
