### ISSUE TITLE
podman load: confusing command-line usability

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2667]
There's a confusing and (AFAICT) unused `PATH` option for podman load:
```
$ podman load --help
Usage:
  podman load [flags] [PATH]
```
The man page describes the argument differently, and non-optional:
```
   podman load name[:tag|@digest]
```
However, the option seems to be completely ignored. This is especially misleading when a naïve user types `podman load foo.tar` and it just hangs (waiting for input on stdin).

This one is beyond my ability because I don't know the intention behind this argument.

While you're looking into it, could you also add an `isTerminal()` check?

**Comment by rhatdan** [comment]
Load an image from a tar archive or STDIN

**Comment by kunalkushwaha** [comment]
Ideally the behaviour of `podman load` should report in both cases.

- `podman load <tar-file>` i.e.  argument without any flag should report error.
- `podman load` with input is from terminal, It should report error.

I can work on this.

/assign

**Comment by edsantiago** [comment]
@kunalkushwaha Dan is working on it; #2674. Thank you!

**Comment by kunalkushwaha** [comment]
ohh okay thanks for update :)

**Comment by rhatdan** [comment]
seems like this is fixed
