### ISSUE TITLE
regression: 'podman logs' hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2677]
/kind bug

`podman logs`, on a Created container, hangs:
```
$ podman create --name foo alpine date
ba7a0457e424bde8c99c15921e6484724bff5484256fd689bfe5384c5536ad65
$ podman logs foo
[hangs forever]
```
Seems to be 5e86acd5.

Caught by my BATS tests, which I'm starting to believe might make a good addition to CI.

**Comment by rhatdan** [comment]
We decided that podman logs would work like tail -f /var/log/messages, and will just sit on the log file until user ctrl^c. But regular podman logs ctr should not hang.

**Comment by rhatdan** [comment]
I can not get this to hang unless I use the -f?

**Comment by edsantiago** [comment]
@dwalsh which commit? As above, everything I've tried since 5e86acd hangs for me, root and rootless.

**Comment by rhatdan** [comment]
@edsantiago yes you are correct it hangs if the file does not exists.

**Comment by mheon** [comment]
Closing as #2679 is merged
