### ISSUE TITLE
[rootless] error extracing PID namespace

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2682]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
`podman pod top busybox` gives an error when being rootless

**Steps to reproduce the issue:**
 `/home/podman/podman/usr/local/bin/podman pod top busybox`

**Describe the results you received:**
`Error: error extracing PID namespace: readlink /proc/805/ns/pid: permission denied`

**Comment by giuseppe** [comment]
PR: https://github.com/containers/libpod/pull/2683
