### ISSUE TITLE
make install.catatonic is not arch friendly

### ISSUE THREAD

**Issue by baude** [containers/libpod#2699]
make install.catatonit is not going to work on any arch other than x86_64 because it appears to be pulling a compiled binary for x86_64.  We need an arch friendly way of dealing with this.

**Comment by tobwen** [comment]
```
export GOPATH="$HOME/go"
catatonit_src="openSUSE/catatonit"
          src="$GOPATH/src/github.com/$catatonit_src"
       target="$GOPATH/podman/"

[ -d "$GOPATH" ] || mkdir -p "$GOPATH"
[ -d "$src" ]    || mkdir -p "$src"
[ -d "$target" ] || mkdir -p "$target"

cd "$target"
(  git clone --depth=1 "https://github.com/catatonit_src" "$src" && \
   cd src && autoreconf -i && ./configure && make && make install DESTDIR=$target )
```

**Comment by baude** [comment]
sure, but frankly  i am struggling with this a little.  it is clearly a dependency and I find it a bit unusual having dependencies installed like this.  thoughts?

**Comment by afbjorklund** [comment]
I built it from source. Not sure why it defaults to binary, or why not just add it as a dependency ?

Added these steps, to the above:

```
eval `grep ^CATATONIT_VERSION hack/install_catatonit.sh`
```
in `libpod`

```
git checkout $CATATONIT_VERSION
```
in `catatonit`

Also had to patch the location in (libpod.conf and libpod/runtime.go), since it had been hardcoded.

**Comment by afbjorklund** [comment]
@tobwen : catatonit is a C program. it looks a little odd in a Go directory ?

**Comment by vrothberg** [comment]
I suggest cloning catatonit into a tmp directory, build it there, copy it to the `CATATONIT_PATH`, and remove the directory.

**Comment by tobwen** [comment]
@afbjorklund Sure, this is just my _podman_ rendering stack, where anything _GO_es into: https://gist.github.com/tobwen/25a010d3b90a6491e5646c0e77163557

**Comment by baude** [comment]
Why isn't it just a dep  like runc or conmon

**Comment by rhatdan** [comment]
Someone would need to package it up and get it into Fedora/RHEL/Centos. Currently we are just using this as an internal tool of podman.

**Comment by vrothberg** [comment]
@lsm5 has a card for that but more important things keep popping up.

**Comment by tobwen** [comment]
@rhatdan For what do you use it? I often don't compile it at all. I thought, it's _PID 1_ for the container when activated?

**Comment by afbjorklund** [comment]
Maybe it needs to be in a separate package because of licensing issues ? (GPLv3+, vs. ASL 2.0)

I just added it for completeness (i.e. `run --init`), using `tini` for the actual container examples...

**Comment by tobwen** [comment]
Well that escalated quickly...

https://github.com/yetanothergeek/bbinit
https://github.com/$catatonit_src
https://github.com/Yelp/dumb-init
https://github.com/troglobit/finit
https://github.com/krallin/tini

**Comment by rhatdan** [comment]
@lsm5 Any movement on this?  Has anyone else worked on it?

**Comment by baude** [comment]
@rhatdan @vrothberg what should we do here? i believe this is still an issue

**Comment by baude** [comment]
ping @vrothberg ideas?

**Comment by vrothberg** [comment]
> ping @vrothberg ideas?

I am cool with using `tini` for CI. `catatonit` isn't packaged for Fedora yet and `tini` should be available everywhere.

**Comment by baude** [comment]
we need to get an answer here ... what is required to not do what we are doing?

**Comment by vrothberg** [comment]
@baude, we can either clone the repository and build it or we download the pre-built binaries from https://github.com/krallin/tini/releases.

I prefer cloning and building catatonit. Will look into this tomorrow morning to warmup.
