### ISSUE TITLE
restrict podman to a group

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2701]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Since _podman_ can run rootless, a global installation in `/usr/bin` (etc.) allows every user on the system to run containers. On a multi-user-system, that can quickly ran into problems, since the administrator doesn't have control about resources. Additionally, you can't limit podman using `sudo`, since it doesn't need superior rights to be run.

Would it be possible to limit _podman_ to users, which are in a specific group, f.e. `group=podman` in the config?

**Comment by rhatdan** [comment]
@tobwen podman gives a user no more rights then a user could do without it being installed.

Control to running containers is actually in the /etc/subuid and /etc/subgid files.

If entries are removed from these files, then the users can not really do much with containers.  (Yet)

What exactly are you worried about?

Rootless podman does not do anything with cgroups control.  So basically all of the proceses a user launches inside of his container are governed by the cgroups assigned to the user.

**Comment by tobwen** [comment]
> What exactly are you worried about?

Resources. Since users are root inside the container, they could pull huge applications, which cold have an effect on the host.

Therefor it would be nice to limit only specific, trustable users, to run containers (which are in group _podman_ for example).

**Comment by rhatdan** [comment]
They have no special privs that they don't have as a user.  While they can pull huge executables they are governed by disk space and disk quota if enabled.

The podman container is only running as the user, it id not running as ROOT.  It is just ROOT within its namespace, and it is just writing files as the user or as UIDs mapped to the User Namespace. There is no priv escallation here.

**Comment by tobwen** [comment]
> They have no special privs that they don't have as a user. While they can pull huge executables they are governed by disk space and disk quota if enabled.

What if the user installs a CPU & memory stress testing utility and... sure, he's not user on the main system, bus he's root in the container.
 
> The podman container is only running as the user, it id not running as ROOT. It is just ROOT within its namespace, and it is just writing files as the user or as UIDs mapped to the User Namespace. There is no priv escallation here.

I know, that's why I'm using _podman_ :-)

**Comment by rhatdan** [comment]
Same thing if he runs CPU and Memory stress tests without being in a container.  He will be governed by the cgroups estabilished for his user account.  No difference with being root in the container or running them as his normal user.  They are processes running with the same UID/GID.

**Comment by tobwen** [comment]
But `$HOME` could be mounted as `noexec`. So there's no way for a normal user to run applications, which are not available on the main system.

But okay... maybe I'm the only one having problems here. Need to read into cgroups governance.

Thanks for your time!

**Comment by rhatdan** [comment]
If the homedir is mounted noexec then podman will fail, unless the containers storage is moved to /tmp or /var/tmp.

**Comment by tobwen** [comment]
You're right. I'll play with this in a VM.
