### ISSUE TITLE
[Makefile] make install doesn't include make

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2702]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Most of the time, running `make install` also runs `make`, when it hasn't been run before. Would it be possible to add this to the _Makefile_?

**Comment by rhatdan** [comment]
@tobwen Open a PR to do this.  I think this has been talked about in the past, don't remember what the resolution was.

**Comment by afbjorklund** [comment]
Most likely, `install.bin` should depend on bin/podman (and so on) - not run another make

**Comment by rhatdan** [comment]
@tobwen @afbjorklund Was this work ever done?

**Comment by afbjorklund** [comment]
Don't think so, and I'm more of  a `make all && sudo make install` guy myself - too many permission issues otherwise. Of course, that doesn't mean that the Makefile shouldn't have the proper dependencies.

Can do a PR for it ?

**Comment by afbjorklund** [comment]
Might as well fix the "podman" phony target, while at it. As in: it actually builds bin/podman, not podman...

**Comment by rhatdan** [comment]
SGTM

**Comment by tobwen** [comment]
I haven't digged into it anymore, since I'm using "make && make install", too.

The main problem is that most of the tools just build a subset of features in the default make target. For example, "bash autocomplete" sometimes is a default target, sometimes it is no.

So I've ended up with a small parser, which scans the Makefile for targets and presets me a list.

**Comment by afbjorklund** [comment]
I have that on tab-completion, but to be honest I don't really know who is providing it for me ?

What I am _really_ missing is the ./configure step, but that's another story... (so thanks, `sed`)
The only side-effect is that it ends up being "dirty": mostly for changing some hardcoded paths.

Please take a look at the PR, see if I missed something ?
