### ISSUE TITLE
running with uidmap/gidmap, unable to attach volume.

### ISSUE THREAD

**Issue by s4s0l** [containers/libpod#2713]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I get permission denied when running container with uidmap and gidmap and try to attach volume. both named volume or directory mount cause this error. Running without volume mounts seems to be working fine. I'm running it as root. Disabling selinux does not change the behavior. I know Im not using the latest version, but I haven't found any issue describing similar problem or see anything about it in change log. In the production environment I probably will not be allowed to use any other version anyway (I can use only packages from rh repos). So before I start to wrap my mind around building podman by myself just to verify problem still occurs in latest podman version (what i'm likely to fail anyway due to my limited knowledge about go and rhel) I would politely ask you guys if maybe there is something obvious I'm supposed to do to make it work.

I'm mapping uid/gid to existing user on host, but same happens when this user is absent. so ids 12345 are testuser and testgroup on host.

**Steps to reproduce the issue:**

1.
```
[root ~]# podman run --uidmap 0:12345:1000 --gidmap 0:12345:1000 rhel sh -c "cat /proc/self/uid_map; whoami; id -u; sleep 1000;"
         0      12345       1000
root
0
```
This way container seems to be running as desired user
```
pgrep -U 12345 -a
13288 sh -c cat /proc/self/uid_map; whoami; id -u; sleep 1000;
13357 sleep 1000
```
but top gives me `?` as huser:
```
podman top --latest user huser group hgroup
USER   HUSER   GROUP   HGROUP
root   ?       root    ?
root   ?       root    ?
```
2.
```
podman run --uidmap 0:12345:1000 --gidmap 0:12345:1000 -v my-volume:/tmpxx:Z rhel sh
container create failed: container_linux.go:336: starting container process caused "process_linux.go:399: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/containers/storage/my-volume/_data\\\" to rootfs \\\"/run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/mountpoint\\\" at \\\"/tmpxx\\\" caused \\\"stat /var/lib/containers/storage/my-volume/_data: permission denied\\\"\""
: internal libpod error
```

**Describe the results you received:**

Container failed to start, debug output in attachment
[podman_debug.txt](https://github.com/containers/libpod/files/2987213/podman_debug.txt)

Containers-root permissions look like:
```
ls -Ral /run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/
/run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/:
total 0
drwxr-xr-x.  5 testuser testgroup 100 03-20 08:39 .
drwxr-xr-x. 11 root     root      220 03-20 08:39 ..
drwx------.  2 testuser testgroup  40 03-20 08:39 mountpoint
drwx------.  2 testuser testgroup  40 03-20 08:39 rundir
drwx------.  2 root     root       40 03-20 08:39 shm

/run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/mountpoint:
total 0
drwx------. 2 testuser testgroup  40 03-20 08:39 .
drwxr-xr-x. 5 testuser testgroup 100 03-20 08:39 ..

/run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/rundir:
total 0
drwx------. 2 testuser testgroup  40 03-20 08:39 .
drwxr-xr-x. 5 testuser testgroup 100 03-20 08:39 ..

/run/libpod/containers-root/678d79116d228a987b62ee9614f1ab88af4888399fc98f779a13a095be3be265/shm:
total 0
drwx------. 2 root     root       40 03-20 08:39 .
drwxr-xr-x. 5 testuser testgroup 100 03-20 08:39 ..
```

**Describe the results you expected:**

Running container with mounted volume writable by user root inside container, created files inside container visible on host as created by user 12345.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       0.12.1.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 0.12.1.2
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 5604780cd62b9ea5740b17511630b8723b04f675-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "7.6"
  MemFree: 15426994176
  MemTotal: 16461873152
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: ip-172-31-11-219.eu-central-1.compute.internal
  kernel: 3.10.0-957.10.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 48m 31.57s
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ContainerStore:
    number: 10
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS, RHEL-7.6_HVM_GA-20190128-x86_64-0-Hourly2-GP2 - ami-09de4a4c670389e4b
with all updates installed.

**Comment by neVERberleRfellerER** [comment]
Reproducible with podman 1.1.2 (on Fedora Atomic Host 29).

**Comment by giuseppe** [comment]
how have you created `my-volume`?

**Comment by giuseppe** [comment]
Any chance you could try https://github.com/containers/libpod/pull/2716 ?

**Comment by neVERberleRfellerER** [comment]
> how have you created `my-volume`?

`podman volume create my-volume`
But it does not seem to really matter - podman creates missing volumes automatically.

> Any chance you could try #2716 ?

Yes. I don't know how to build packages on Fedora so I tested it on Arch Linux. It works.

**Comment by giuseppe** [comment]
> > 
> 
> `podman volume create my-volume`

if you run the command manually, then it is owned by root.  With the PR, I've opened, if it is created automatically then it is owned by the correct user

**Comment by giuseppe** [comment]
> > Any chance you could try #2716 ?
> 
> Yes. I don't know how to build packages on Fedora so I tested it on Arch Linux. It works.

thanks for confirming it!  I'd just do a "make" there as well without the .rpm

**Comment by qfunq** [comment]
This never got cleared up for root. Because it's needed in production, I have a port of giuseppes UserNSRoot code to podman 1.6.4-dev (including keep-id) ... it seems to be working perfectly, the volumes are correctly mapped into the username space using the intermediary mount and gid/uid mappings. ginkgo isn't complaining. Is anyone interested in this?
