### ISSUE TITLE
rootless container fails: "Setup user: Invalid argument"

### ISSUE THREAD

**Issue by Spindel** [containers/libpod#2714]
/kind bug

**Description**

rootless podman fails with:
```
Storing signatures
Error: container create failed: container_linux.go:344: starting container process caused "setup user: invalid argument"
: internal libpod error
```

**Steps to reproduce the issue:**

1. Set up pod, try to launch container, as non-root:

```
podman pod create -p 10051:10051 -p 6379:6379 -p 8080:80 --name instance
podman run -dt  --pod instance registry.gitlab.com/modioab/modio-api/redis:master
Error: container create failed: container_linux.go:344: starting container process caused "setup user: invalid argument"
: internal libpod error
```
2. selinux in permissive mode, running other rootless containers seems to work (

3.

**Describe the results you received:**

Error message

**Describe the results you expected:**
Launched redis inside pod

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 19:10:31 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 2982092800
  MemTotal: 33720840192
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 16916934656
  SwapTotal: 16929255424
  arch: amd64
  cpus: 16
  hostname: tide
  kernel: 4.20.16-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 2h 11m 12.87s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/spider/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/spider/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000
  VolumePath: /home/spider/.local/share/containers/storage/volumes


```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine running fedora 29, updated on 2019-03-20

**Comment by rhatdan** [comment]
@haircommander @giuseppe Could you guys look into this?

**Comment by giuseppe** [comment]
please attach the output you get with `--log-level debug`

**Comment by giuseppe** [comment]
I guess the image is setting an user that is not available in the user namespace

**Comment by rhatdan** [comment]
Shouldn't that fail when the image is pulling?

**Comment by giuseppe** [comment]
"setup user: invalid argument" looks like an explicity `USER`, that could be different than UIDs/GIDs used by the image (e.g. files owned by root but readable by anyone)

**Comment by rhatdan** [comment]
@Spindel Could you check the image and see what user it is attempting to be run as?

**Comment by Spindel** [comment]
RUN echo redis:x:100004:100:redis:/:/sbin/nologin >> /etc/passwdUSER
100004EXPOSE 6379CMD ["/usr/bin/redis-server", "/etc/redis.conf"]

**Comment by giuseppe** [comment]
100004 is a way too big value, you either change it or allocate more subuids to your user. Via /etc/subuids and /etc/subgids

**Comment by Spindel** [comment]
Right, thank you.

**Comment by mheon** [comment]
@giuseppe Is the 65000 UID limit documented anywhere? We ought to add it to the manpages.

Also, can we potentially catch this earlier than runc, so we can produce a more sensible error?

**Comment by giuseppe** [comment]
It is just what shadow utils allocates by default. Yes we can catch it earlier, we already do that when extracting an image.  I'll work on a patch

**Comment by mheon** [comment]
@giuseppe Sure, but the run manpage should probably mention the 65k max UID limit will exist for most default installations of rootless Podman, barring nonstandard shadowutils or manual modification

**Comment by rhatdan** [comment]
I would not just document 65k, I would tell them to look at the range of UIDs allocated to /etc/subuid.  I am proposing that eventually we want to use much smaller ranges.  If we were running as root it would be nice to handle this situation by seeing if the UID is outside the range and then just adding it to the range.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/2731
