### ISSUE TITLE
proposal(dockerfile/parse): vendor moby/buildkit instead of docker/docker

### ISSUE THREAD

**Issue by jeffreystoke** [containers/libpod#2734]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I was trying to vendor `github.com/containers/libpod` in my project with `go mod vendor`, but it keeps failing on finding `github.com/docker/docker/builder/dockerfile/parser`, which has been removed from `github.com/docker/docker` since [moby/moby c9ebd2f13b3aab49c2d90cc38dcf2cd0d059697f](https://github.com/moby/moby/commit/c9ebd2f13b3aab49c2d90cc38dcf2cd0d059697f).

Though I can pin `docker/docker` to `v17.03.2-ce` as a work around, but `github.com/Sirupsen/logrus` will cause
```
case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

And I have tried `replace github.com/Sirupsen/logrus v1.4.0 => github.com/sirupsen/logrus v1.4.0` but with no luck :/

So, is it possible to change the current `github.com/docker/docker/builder/dockerfile/parser` dependency to `github.com/moby/buildkit/frontend/dockerfile/parser` which could fix this problem once for all?

**Steps to reproduce the issue:**

1. create a go project using `go mod init`

2. import and use `github.com/containers/libpod/libpod`

3. vendor dependencies using `go mod vendor`

**Describe the results you received:**

fail to vendor `github.com/containers/libpod/libpod` at finding `github.com/docker/docker/builder/dockerfile/parser`

**Describe the results you expected:**

vendor `github.com/containers/libpod/libpod` without any error

**Comment by vrothberg** [comment]
I just skimmed the issue:
`github.com/docker/docker/builder/dockerfile/parser` will be dropped when we vendor the latest buildah (Cc @TomSweeneyRedHat).

Regarding the usage of go mod:
We starting working on making the dependencies `go mod`-friendly but I guess this will take some more time until we have ironed out the rough edges.

**Comment by jeffreystoke** [comment]
Thank you @vrothberg for the quick and informative reply,

Wow, really good news, happy to see `buildah` to be there. Anything I can help?

**Comment by rhatdan** [comment]
Best to help out by testing and reviewing patches.

**Comment by jeffreystoke** [comment]
Well, I have found a workaround to this issue with `replace`

```go
replace github.com/docker/docker/builder/dockerfile/parser v1.13.1 => github.com/moby/buildkit v0.4.0
```

**Comment by jeffreystoke** [comment]
> Best to help out by testing and reviewing patches.

@rhatdan , I will try, but honestly I have never reviewed any code from others.

**Comment by rhatdan** [comment]
@jeffreystoke No problem even reviewing docs or just trying out the code helps.

**Comment by rhatdan** [comment]
@vrothberg Is this still an issue?

**Comment by vrothberg** [comment]
@rhatdan, this should be fixed now. Imagebuildah effectively forked the package of a later version, and everything has been properly propagated through the projects. Thanks for catching up on this!
