### ISSUE TITLE
[rootless] unable to delete files in another namespace (with --rm)

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#2738]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When creating files in a rootless container and chowning these files to another user, it's impossible to remove them from the host without help of the root user.

**Steps to reproduce the issue:**

1. `podman run -ti --rm -v /home/podman/we:/we alpine`
2. `adduser tobwen`
3. `cd /we && touch 1 && chown tobwen 1`
4. [leave container]
5. `rm /home/podman/we/1`

**Describe the results you received:**
File cannot be removed, since it belongs to a non-existing user:
```
$ ls -al
total 8
drwxr-xr-x  2 podman podman 4096 Mar 21 21:41 .
drwxr-xr-x 12 podman podman 4096 Mar 21 21:45 ..
-rw-r--r--  1 166535 166535    0 Mar 21 21:41 1
```
Sure, this is connected to https://github.com/containers/libpod/issues/1386 but since the original container has been removed, there's no way to figure out the namespace it was created in.

**Comment by mheon** [comment]
The UID mappings should always be the same (assuming you did not modify `/etc/subuid` or `/etc/subgid`) so we should still be good to delete these files

**Comment by mheon** [comment]
(The modified subuid/subgid case is sort of concerning, but you need root to do that, so I'm somewhat OK with saying you need root to fix it)

**Comment by neVERberleRfellerER** [comment]
There is also
https://podman.io/blogs/2018/10/03/podman-remove-content-homedir.html
The buildah method works.

**Comment by tobwen** [comment]
@mheon They look like this:
```
$ cat /etc/subuid
tobwen:100000:65536
podman:165536:65536

$ cat  /etc/subgid
tobwen:100000:65536
podman:165536:65536
```

@neVERberleRfellerER Thanks let me try this solution (as mentioned in #1386, but would be great to have this working in podman the native way).

**Comment by mheon** [comment]
@tobwen The `buildah unshare` method ought to still work, since we join namespaces with the same UID/GID maps always, then.

Though it's not good that we can't do this natively with Podman. We shouldn't need an external tool that might not be available in order to clean up after ourselves.

**Comment by tobwen** [comment]
@mheon Can't I do this with normale `unshare` from _util-linux_, too? Or is this a complete different approach?

**Comment by mheon** [comment]
Not 100% sure here - they are conceptually very similar, but the semantics might be different enough to make it impossible (I'd mostly be concerned with how `unshare` gets its user mappings configured).

**Comment by tobwen** [comment]
Hmm... building _buildah_ fails here right now. I'll report & close as soon as I got this working.

**Comment by tobwen** [comment]
A small work-around (where 165635:165617):

```
addgroup --gid 165617 conuser
adduser --gecos "" --disabled-login --uid 165635 --gid 165617 conuser
```

**Comment by rhatdan** [comment]
@tobwen There is a hope that someone will implement podman unshare, but no one has had it prop to the top of the priority list yet.

**Comment by tobwen** [comment]
@rhatdan But it helps to delete the files. But is it normal that _buldah_ greps existing users? `165635` gets `systemd-timesync` here.

**Comment by rhatdan** [comment]
@tobwen buildah/podman are using newuidmap and newgidmap commands provided by the shadow-utils package.  These programs search for the username in the /etc/subuild and /etc/subgid files respectively.  When the find an entry for the user they set the usernamespace in the kernel with the range of UID's specified.

**Comment by tobwen** [comment]
@rh-atomic-bot But my `/etc/subuild` only has 2 entries. Seems like there's an overlap? I've never modified these files.

**Comment by rhatdan** [comment]
No overlay. 
tobwen gets UIDs 100000-165535
powman gets the next 65536 starting at 165536

**Comment by tobwen** [comment]
Yes, but the first user created inside the container gets `165635` and when accessing the namespace with _buildah_, this user gets `systemd-timesync`, which is `100` on the host.

**Comment by rhatdan** [comment]
Please explain exactly what you mean by the first user inside of the container
cat /proc/self/uid_map while in the container,  you should see the mapping.

**Comment by tobwen** [comment]
@rhatdan Please read the initial post, I've explained exactly, what I've done (I've created a new user inside the container, the first new one after root).

Since the container doesn't exist anymore, I cannot rejoin it. So I cannot run `cat /proc/self/uid_map` in there, but the mapping is right in there, of course.

My initial problem was that I cannot remove files, but this works using _unshare_ or _buildah_. I'm just curious, why _buildah_ presets me `systemd-timesync` as a user, while _unshare_ maps it to `nobody`

**Comment by rhatdan** [comment]
Any UID not mapped into the User Namespace will be referred to as nobody.

**Comment by tobwen** [comment]
@rhatdan So Buildah unluckely maps the namespaces UID into an area, where a system UID exists?

**Comment by rhatdan** [comment]
The only UIDs Buildah is going to map are defined in /etc/subuid and the UID running buildah if not root.
