### ISSUE TITLE
redundant image pull shall be avoided (rootless & root)

### ISSUE THREAD

**Issue by kunalkushwaha** [containers/libpod#2741]
kind feature

**Description**

Currently if an image is pulled as root and again same image is pulled in rootless mode (vise-versa too), the whole image is downloaded again. Since, the image is locally available, this shall be avoided.

rootless & root mode should be enforced towards _container execution_ & can be avoided at _image management_

few of reasons:
- Image pull in one of most time consuming process in whole container management.
- CI/CD systems, where same tests expected to be tested for an application in case of both root & rootless mode, redundant image download increase time to test.

**Steps to reproduce the issue:**

1. pull image in root mode.
```
sudo podman pull docker.io/library/busybox
$ sudo podman pull busybox                                                     
Trying to pull docker://busybox...Getting image source signatures
Copying blob 697743189b6d [======================================] 738.2KiB / 738.2KiB
Copying config d8233ab899 [======================================] 1.5KiB / 1.5KiB
Writing manifest to image destination                                  
Storing signatures                                       
d8233ab899d419c58cf3634c0df54ff5d8acc28f8173f09c21df4a07229e1205 
```

2. pull image in rootless mode.
```
$ podman pull busybox                                                                 
Trying to pull docker://busybox...Getting image source signatures                              
Copying blob 697743189b6d [======================================] 738.2KiB / 738.2KiB
Copying config d8233ab899 [======================================] 1.5KiB / 1.5KiB
Writing manifest to image destination                                                                                                                                                          
Storing signatures                                                                                                                                                                             
d8233ab899d419c58cf3634c0df54ff5d8acc28f8173f09c21df4a07229e1205  
```

**Describe the results you received:**
Each time, image is downloaded from remote registry

**Describe the results you expected:**
Once downloaded, it should not be downloaded next time from remote registry

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.11.1
Git Commit:         68e3df37248da85f58662c00e0934d1359f0fdc0-dirty
Built:              Fri Mar 22 14:43:55 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Hi @kunalkushwaha, thanks a lot for opening the issue!

Good news, this issue is already being tracked and worked on. If you're interested, you can follow https://github.com/containers/skopeo/pull/619. We have to iron out some rough edges regarding the lock management, but you can expect it to be merged into Podman soon.

I am closing this issue as there is already https://github.com/containers/libpod/issues/1911.

**Comment by kunalkushwaha** [comment]
Thanks for update. I will followup  #1911 & containers/skopeo#619

**Comment by kunalkushwaha** [comment]
@vrothberg It looks like, the download for parallel process (but in same mode) is only handled with containers/skopeo#619.

Will this fix issue of root and rootless mode too? As I see the image store is different for both root & rootless mode. 

rootless
```
store:
  ConfigFile: /home/kunal/.config/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/kunal/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 12
  RunRoot: /run/user/1000/run
  VolumePath: /home/kunal/.local/share/containers/storage/volumes
```

root
```
store:                                                                                                                                                                                         
  ConfigFile: /etc/containers/storage.conf                                                                                                                                                     
  ContainerStore:                                                                                                                                                                              
    number: 12                                                                                                                                                                                 
  GraphDriverName: overlay                                                                                                                                                                     
  GraphOptions: null                                                                                                                                                                           
  GraphRoot: /var/lib/containers/storage                                                                                                                                                       
  GraphStatus:                                                                                                                                                                                 
    Backing Filesystem: extfs                                                                                                                                                                  
    Native Overlay Diff: "true"                                                                                                                                                                
    Supports d_type: "true"                                                                                                                                                                    
    Using metacopy: "false"                                                                                                                                                                    
  ImageStore:                                                                                                                                                                                  
    number: 121                                                                                                                                                                                
  RunRoot: /var/run/containers/storage                                                                                                                                                         
  VolumePath: /var/lib/containers/storage/volumes 
```

**Comment by vrothberg** [comment]
@kunalkushwaha, yes this will work transparently for both, root and rootless. Skopeo doesn't yet support rootless storage, but we will add support for that soon (Cc @rhatdan @giuseppe).

**Comment by kunalkushwaha** [comment]
I actually meant with this issue is.
- Shared image store for root & rootless mode. (at least an option to allow sharing)
- Though simply using same  image store, may not be good idea, but somehow if its configurable to use the other image-store as cache, so before downloading from remote registry, it can look if its already available in cache store.

e.g  In `containerd` project, there is concept of `namespace` similar to k8s namespace, if an image is already downloaded in one namespace, it will be just copied to other new namespace on image pull.
Though this is  simple there to do as, image store is common and requests are filtered by `namespace`.

**Comment by vrothberg** [comment]
Currently, we don't support that.  Having shared storage across users implies leaking data and can be used for abuse which I find concerning. But I understand the use-case for such a feature and if made optional, I would support the idea.

I _guess_ that containerd can do that as it's running as root.

But @rhatdan and @giuseppe are the experts in this domain. What's your take on that?

**Comment by mheon** [comment]
There has been some talk about this, but only in one direction (allowing
rootless to copy local images from root - you run into problems the other
way because you can't trust that the images). We can make the image store
directories world readable, but I believe we found some files that could
not be accessed even with appropriate permissions due to extra file
attributes.
