### ISSUE TITLE
Cannot access forwarded ports remotely (again?)

### ISSUE THREAD

**Issue by stu-gott** [containers/libpod#2748]
This issue might be related to https://github.com/containers/libpod/issues/1119 -- except that it's affecting podman and friends from March 2019.

Versions I'm using:
podman: 1.2.0-dev
containernetworking-plugins: 0.7.5

I noticed I was unable to reach a container (mapping port 443 externally) from other hosts and did some digging. It appears the forwarding rules on my host might be incomplete.

Some volume mounts and env vars were ommitted, but here's the command I'm using (run as root from systemd, so slirp4netns is not in the picture):
```
/usr/bin/podman run --name container_registry -p 443:443 localhost/registry
```

```
$ sudo iptables-save | grep -i cni
:CNI-DN-d4570469b4829eea2af9d - [0:0]
:CNI-HOSTPORT-DNAT - [0:0]
:CNI-HOSTPORT-MASQ - [0:0]
:CNI-HOSTPORT-SETMARK - [0:0]
:CNI-d4570469b4829eea2af9db8b - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A POSTROUTING -m comment --comment "CNI portfwd requiring masquerade" -j CNI-HOSTPORT-MASQ
-A POSTROUTING -s 10.88.0.0/16 -m comment --comment "name: \"podman\" id: \"520a86c3c7d6664532f70d529f617718e1bf663231226f140762cbeffebbef99\"" -j CNI-d4570469b4829eea2af9db8b
-A CNI-DN-d4570469b4829eea2af9d -s 10.88.0.61/32 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-d4570469b4829eea2af9d -s 127.0.0.1/32 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-d4570469b4829eea2af9d -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.88.0.61:443
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"podman\" id: \"520a86c3c7d6664532f70d529f617718e1bf663231226f140762cbeffebbef99\"" -m multiport --dports 443 -j CNI-DN-d4570469b4829eea2af9d
-A CNI-HOSTPORT-MASQ -m mark --mark 0x2000/0x2000 -j MASQUERADE
-A CNI-HOSTPORT-SETMARK -m comment --comment "CNI portfwd masquerade mark" -j MARK --set-xmark 0x2000/0x2000
-A CNI-d4570469b4829eea2af9db8b -d 10.88.0.0/16 -m comment --comment "name: \"podman\" id: \"520a86c3c7d6664532f70d529f617718e1bf663231226f140762cbeffebbef99\"" -j ACCEPT
-A CNI-d4570469b4829eea2af9db8b ! -d 224.0.0.0/4 -m comment --comment "name: \"podman\" id: \"520a86c3c7d6664532f70d529f617718e1bf663231226f140762cbeffebbef99\"" -j MASQUERADE
:CNI-ADMIN - [0:0]
:CNI-FORWARD - [0:0]
-A FORWARD -m comment --comment "CNI firewall plugin rules" -j CNI-FORWARD
-A CNI-FORWARD -m comment --comment "CNI firewall plugin rules" -j CNI-ADMIN
-A CNI-FORWARD -d 10.88.0.61/32 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A CNI-FORWARD -s 10.88.0.61/32 -j ACCEPT
```

It appears that the inbound FORWARD rule only applies to established connections. Adding something along the lines of this restores external connectivity:

```
iptables -A CNI-FORWARD -p tcp -m tcp --dport 443 -j ACCEPT
```

/kind bug

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/arm
```

**Output of `podman info --debug`:**

```
debug:                                                                                                                                                                                         
  compiler: gc                                                                                                                                                                                 
  git commit: ""                                                                                                                                                                               
  go version: go1.11.5                                                                                                                                                                         
  podman version: 1.2.0-dev                                                                                                                                                                    
host:                                                                                                                                                                                          
  BuildahVersion: 1.8-dev                                                                                                                                                                      
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 07321defa3d5ead30d67443a23b783c6f90fa398'
  Distribution:
    distribution: debian
    version: "9"
  MemFree: 8994816
  MemTotal: 246239232
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1021886464
  SwapTotal: 1023991808
  arch: arm
  cpus: 1
  hostname: <omitted>
  kernel: 4.17.19
  os: linux
  rootless: false
  uptime: 19h 48m 46.74s (Approximately 0.79 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This host is an armv7 box running debian stretch. All packages were compiled from source from the projectatomic ppa.

**Comment by stu-gott** [comment]
bump?

**Comment by mheon** [comment]
@mccv1r0 Anything stick our here?

**Comment by mccv1r0** [comment]
This rule should enable ```-p 433:433``` for anything destined to localhost:443 to be port mapped into the container.  The FORWARD chain shouldn't be involved.

If you are using the IP address of the container itself (i.e. FORWARD chain), currently this [doesn't look like it is supported in current libpod](https://github.com/containers/libpod/blob/master/pkg/firewall/iptables.go#L31)

**Comment by stu-gott** [comment]
So to make sure we're talking about the same thing, look closely at the CNI-FORWARD chain. there's only two rules:
1) accept anything outbound
2) accept anything inbound *FOR ESTABLISHED CONNECTIONS ONLY*

There is no forward rule to allow an inbound conversation to be established. full stop.

------

In this case I'm just attempting the most direct use case. expose port 443 to all hosts. I'm attempting to connect to port 443 using the host's IP from a client machine. This used to work, but upon update to the latest versions of podman and containernetworking-plugins this quit working.

Correct me if I'm wrong: `-p 443:443` is supposed to expose port 443 to all hosts, right? In order to expose only to localhost I'd have to use `-p 127.0.0.1:433:433`, right? Because that's not what's happening.

------

I believe the conversation about connecting to a container's IP address to be moot: there's already a DNAT rule that translates inbound TCP traffic to the container's IP. But it doesn't matter, that's not how I was trying to connect.

**Comment by mccv1r0** [comment]
> So to make sure we're talking about the same thing, look closely at the CNI-FORWARD chain. there's only two rules:
> 
> 1. accept anything outbound
> 2. accept anything inbound _FOR ESTABLISHED CONNECTIONS ONLY_
> 
> There is no forward rule to allow an inbound conversation to be established. full stop.

Correct.  FAD (at least as currently designed) 

> In this case I'm just attempting the most direct use case. expose port 443 to all hosts. I'm attempting to connect to port 443 using the host's IP from a client machine. This used to work, but upon update to the latest versions of podman and containernetworking-plugins this quit working.

I'm surprised it used to work based on my understanding == what I describe below.

> Correct me if I'm wrong: `-p 443:443` is supposed to expose port 443 to all hosts, right? In order to expose only to localhost I'd have to use `-p 127.0.0.1:433:433`, right? Because that's not what's happening.

```-p 443:443```  will only create DNAT rules.  Nothing is done to FORWARD chain.  (Note:  Currently CNI itself doesn't support doing anything to FORWARD chain; podman has added this to libpod until CNI support is ready.)

AFAICT -p ```ip:port-on-that-ip:port-inside-container``` just sets the source IP used -vs- all IP's on the host.  e.g. I supply -p twice below, neither are localhost/127.0.0.1 but each is a local interface on the VM.

```
$ sudo podman run --detach  -p 172.20.0.1:5222:5222 -p 10.132.15.209:5222:5222 socksink
60ce920a4e51b1b3245b43e93bd817c0b18231be85be9ea640672072e3f312d8 
]$ sudo iptables -nvL -t nat | grep 5222 
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.15           172.20.0.1           tcp dpt:5222
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            172.20.0.1           tcp dpt:5222
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            172.20.0.1           tcp dpt:5222 to:10.88.0.15:5222
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.15           10.132.15.209        tcp dpt:5222
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            10.132.15.209        tcp dpt:5222
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.132.15.209        tcp dpt:5222 to:10.88.0.15:5222
    0     0 CNI-DN-d228462a38d78ff9ff242  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "60ce920a4e51b1b3245b43e93bd817c0b18231be85be9ea640672072e3f312d8" */ multiport dports 5222,5222
$ 
```

Now only connections on the host to one of those local interfaces IP's + port will be DNAT into the container.

**Comment by baude** [comment]
do we consider this closed?

**Comment by rhatdan** [comment]
I am going to close, reopen if it still exists.

**Comment by rsaggino** [comment]
We are hitting this issue on Podman 1.4, RHEL 7.6.
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

I am also able to solve the issue with:
iptables -A CNI-FORWARD -p tcp -m tcp --dport $PORT -j ACCEPT

Should we try reopen this?

**Comment by baude** [comment]
you should file a bugzilla
