### ISSUE TITLE
podman build failed on WORKDIR instruction

### ISSUE THREAD

**Issue by Lagrang** [containers/libpod#2753]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman build` failed on Dockerfile with WORKDIR instruction: `ensuring container path "/usr/local/hbase/bin": mkdir /var/lib/containers/storage/btrfs/subvolumes/8325b8065650778d4abbb211b130511525e668b8b45e0df0f1c3563646c4c674/usr/local/hbase: file exists`

**Steps to reproduce the issue:**

1. Dockerfile with WORKDIR instruction

2. Run `podman build`

**Describe the results you received:**
`Command:workdir Args:[/usr/local/hbase/bin] Flags:[] Attrs:map[] Message:WORKDIR $BASE_INSTALL_PATH/hbase/bin Original:WORKDIR $BASE_INSTALL_PATH/hbase/bin}: error ensuring container path "/usr/local/hbase/bin": mkdir /var/lib/containers/storage/btrfs/subvolumes/8325b8065650778d4abbb211b130511525e668b8b45e0df0f1c3563646c4c674/usr/local/hbase: file exists`

**Output of `podman version`:**
```
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.10"
  MemFree: 219127808
  MemTotal: 29423517696
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 9914544128
  SwapTotal: 10000265216
  arch: amd64
  cpus: 8
  hostname: myhost
  kernel: 4.18.0-16-generic
  os: linux
  rootless: true
  uptime: 2h 24m 17.99s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries: []
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/user/.local/share/containers/storage/volumes
```

**Comment by baude** [comment]
please attach a dockerfile that replicates the problem

**Comment by Lagrang** [comment]
Please, see this [repo](https://gitlab.com/hutils/containers/tree/09121d3b7f85e6033b7354c903d209cd815d96d3/hbase/2.x).
I find out, that root cause is symlinks: COPY, VOLUME, WORKDIR instructions cannot handle it.

**Comment by rhatdan** [comment]
Could you check  this out with buildah bud command?

If it fails and it should not, then open an issue on Buildah which will later get vendored into Podman.  If it works on Buildah, then maybe that version has not been vendored into Podman yet.

**Comment by Lagrang** [comment]
https://github.com/containers/buildah/issues/1439

**Comment by Lagrang** [comment]
https://github.com/containers/buildah/issues/1439

**Comment by TomSweeneyRedHat** [comment]
@Lagrang Thanks for the problem report and for moving it over to Buildah.  We'll take a look.
I'm going to close this issue and will continue working with the one in Buildah: containers/buildah#1439
