### ISSUE TITLE
Troubleshooting doc, point 10), should create 65536 subuids and subgids, no?

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2754]
/kind bug

Setting up podman for first time on Fedora 30 Branched, and discovered I had to manually create subuids and subgids for my account, so I arbitrarily created 10,000 of each, only to have podman tell me I needed 65536 of them. I fixed that, and all worked. So the example in the troubleshooting doc at the very end of point 10), which creates only 1,000 of them, would seem to be doomed to failure, unless I am misreading something.

**Comment by rhatdan** [comment]
Well we have fixed podman in the upstream to remove the requirement of 65k UIDs.  So when Podman 1.2 ships you should not have this issue.

**Comment by rpjday** [comment]
Ah, gotcha. Should have checked the history, would probably have noticed that.
