### ISSUE TITLE
--dns* flags should be available in build

### ISSUE THREAD

**Issue by hainesbg** [containers/libpod#2755]
/kind feature

**Description**

`podman build` should have `--dns`, `--dns-opt`, and `--dns-search` options just like `podman run` does.

My use case is trying to hit package repos as part of a Dockerfile build while using the `systemd-resolved` stub resolver (127.0.0.53) in my `/etc/resolv.conf`.

It's probably too much to ask at the moment for the better solution of somehow ultimately querying against the host's resolver library, This would be quite the boon for some situations, but the command line arg would be a workable substitute.

**Comment by mheon** [comment]
Once Buildah adds these we can revendor to pick them up

**Comment by TomSweeneyRedHat** [comment]
Created https://github.com/containers/buildah/issues/1449 to track there.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat We need to vendor in a new buildah to close this issue.

**Comment by TomSweeneyRedHat** [comment]
I've been thinking it's about time for 1.7.3  Any objections @rhatdan or @nalind?  Then a vendor to libpod.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat I would like to straighten out the vendoring issue in libpod first then we can cut a release.

**Comment by baude** [comment]
@TomSweeneyRedHat what is the latest here

**Comment by rhatdan** [comment]
This is in buildah although it is not documented in the man pages.
Ashley can you add information to podman-build man page.
