### ISSUE TITLE
Can not  open test/registries.conf when run podman parallal 

### ISSUE THREAD

**Issue by ypu** [containers/libpod#2757]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Currently we run our integration test with --node 3 options and I find out following messages shows up randomly in the test(this is from https://s3.amazonaws.com/aos-ci/ghprb/containers/libpod/7d04d51d5a8bfb8932ea7b6cd5c0d04a56e49cd8.0.1553501412081858531/output.log):

```
------------------------------
Podman Info 
  podman system info json output
  /go/src/github.com/containers/libpod/test/e2e/info_test.go:42

[BeforeEach] Podman Info
  /go/src/github.com/containers/libpod/test/e2e/info_test.go:20
[It] podman system info json output
  /go/src/github.com/containers/libpod/test/e2e/info_test.go:42
Running: /usr/bin/podman --root /tmp/podman_test598139078/crio --runroot /tmp/podman_test598139078/crio-run --runtime /usr/bin/runc --conmon /usr/libexec/podman/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/podman_test598139078 --storage-driver=vfs system info --format=json
Error: error getting info: error getting registries: unable to parse the registries.conf file: open test/registries.conf: no such file or directory
output: 
```
 

**Steps to reproduce the issue:**

1. Run "make ginkgo" in your libpod source code or with following command:
ginkgo -v -nodes 3  test/e2e

**Describe the results you received:**

Test failed with above error message

**Describe the results you expected:**

podman command runs as expect and tests passed. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Use upstream to test it:
HEAD 54b901fdda9b4ad21d866a12e3e13567d7f8a908
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora

**Comment by baude** [comment]
i think it is a read-only action ... @ypu what do you think being parallel has to do with it?

**Comment by ypu** [comment]
@baude Yes, this should be a read-only action. So I though this should be a bug. Never get this message when I ran the tests one by one. In the same time in my test machine, test with -node 3 will trigger it easily.

**Comment by mheon** [comment]
How do we create registries.conf on the test system - is there a chance we're deleting/recreating it in some tests, causing other tests to try and grab it while it's not there?

**Comment by ypu** [comment]
@mheon Thanks for reminding. Checked the code, the registries.conf path should be "INTEGRATION_ROOT/test/registries.conf" but the error message is tried to read "test/registries.conf". So this should be a bug in the test framework but not podman.

**Comment by rhatdan** [comment]
@ypu Can I close this issue?
