### ISSUE TITLE
unable to start container with macvlan cni plugin

### ISSUE THREAD

**Issue by benjumanji** [containers/libpod#2761]
/kind bug

Using the macvlan cni plugin results in "unknown network mode" and the plugin is not launched.

**Steps to reproduce the issue:**

1. Define a network using the cni macvlan plugin 
```
{
  "cniVersion": "0.3.0",
  "name": "default",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "enp8s0",
      "ipam": {
        "type": "dhcp"
      }
    }
  ]
}
```
2. Run a container

**Describe the results you received:**
```
ben@mullion ~> sudo podman run -it --network=default centos:7 bash
[sudo] password for ben: 
unknown network mode
```

**Describe the results you expected:**
A running container

**Output of `podman version`:**

```
Version:       0.12.1.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 0.12.1.2
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: b909c9e1a3e8f14d5694a118fb9c0c0325a31d4f-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 7434874880
  MemTotal: 16629342208
  OCIRuntime:
    package: containerd.io-1.2.4-3.1.el7.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 6635b4f0c6af3810594d2770f662f34ddc15b40d
      spec: 1.0.1-dev
  SwapFree: 6002044928
  SwapTotal: 6002044928
  arch: amd64
  cpus: 4
  hostname: mullion
  kernel: 3.10.0-957.5.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 216h 43m 44.19s (Approximately 9.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**Comment by mheon** [comment]
The problem here appears to be `--network=default` - it's parsing it as a literal network mode, like `--net=host`. I don't think this is actually specific to the macvlan plugin as such.

We might want to define a separate flag for specifying what CNI networks to join, as opposed to overloading `--net` further than we already have.

**Comment by benjumanji** [comment]
Ahh, is there a way to teach podman that it's a cni network I want to connect to?

**Comment by mheon** [comment]
@benjumanji Yeah, we definitely support that - I think it might be the naming specifically ("default") that's confusing it. You might want to try renaming it and seeing if that works.

Meanwhile, I'd definitely like to get `--cni-default-network` and `--cni-additional-network` flags added, so we don't have parsing problems like this.

**Comment by benjumanji** [comment]
Ah, you are correct. Renaming the network totally solves it. I should have listened to my inner admin "calling your network default is electing the way of pain, call it something else".

**Comment by benjumanji** [comment]
I'll leave it to you folk to decide if you'd like to close / rename whatever.

**Comment by mheon** [comment]
I'm going to close this, given that it's mostly resolved, but I'll open a separate issue for dedicated CNI network flags
