### ISSUE TITLE
"SEE ALSO" podman man page references to other man pages seem inconsistent

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2766]
Doesn't *seem* like this has been addressed in recent commits, so hoping this is not a silly observation. On my Fedora 30 (branched) system, podman version 1.1.2, at the very end of "man podman", one reads:

```
SEE ALSO
       containers-mounts.conf(5), containers-registries.conf(5),
       containers-storage.conf(5), buildah(1), crio(8),
       libpod.conf(5), ... etc etc ...
```

First, the storage man page is available under either of:

```
$ man 5 storage.conf
$ man 5 containers-storage.conf
```
On the other hand, the man page for containers-mounts is available *only* via the listed man page, not the short form (so, technically, it's correct, just inconsistent), while the man page for registries seems available *only* via its short form:

`$ man 5 registries.conf`

and not the longer form listed in the man page. Should there be a consistent presentation of these?

**Comment by rhatdan** [comment]
Could you open a PR to fix this?

**Comment by rpjday** [comment]
I'd be happy to submit a patch to resolve this, I'm just not sure how one wants it resolved.

**Comment by rhatdan** [comment]
Fixing registries.conf versus containers-registries.conf would need to be fixed in skopeo.  I think the long form in general is correct, since there is a chance that storage.conf.5 and mounts.conf.5 could have a conflicting name in the distro.

But for now lets change it to registries.conf so the user would actually find the man page.

**Comment by rpjday** [comment]
OK, I'll send up a patch for that. Interestingly, in a discussion on the Fedora ML, I learned (apparently) that "man storage.conf" still leads one to the "containers-storage" man page simply because "storage.conf" is in the TH line of the gzipped man page. I was unaware it worked like that.

**Comment by rpjday** [comment]
Since this has been clearly subsumed by my subsequent pull request , I'll close this.
