### ISSUE TITLE
Podman fails to start container with fixed IP

### ISSUE THREAD

**Issue by jeka** [containers/libpod#2767]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have created a container with a fixed IP which is started as systemd service on boot.
```
podman create --ip 172.19.0.11 --dns 10.0.2.2 --name container
```
the systemd service file is like following:
```
# /etc/systemd/system/container-podman.service
[Unit]
Description=Container run by podman
After=network-online.target nss-lookup.target
Wants=network-online.target nss-lookup.target

[Service]
Restart=on-failure
RestartSec=10
#ExecStartPre=-/usr/bin/rm -f /var/lib/cni/networks/podman/172.19.0.11
ExecStart=/usr/bin/podman start -a container
ExecStop=/usr/bin/podman stop container
StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
```

Every now and then this service fails to start on boot. Relevant messages in journal are:
```
podman[14255]: time="2019-03-26T11:28:43+01:00" level=error msg="Error while adding pod to CNI network "podman": failed to allocate for range 0: requested IP address 172.19.0.11 is not available in range set 172.19.0.1-172.19.255.254"
podman[14255]: Error: unable to start container 8c3030255375d8b387db439403c5a65c6404a73bdfda319328463a2f1aab2331: error configuring network namespace for container 8c3030255375d8b387db439403c5a65c6404a73bdfda319328463a2f1aab2331: failed to allocate for range 0: requested IP address 172.19.0.11 is not available in range set 172.19.0.1-172.19.255.254
```
When such an failure occurs, there is an existing file /var/lib/cni/networks/podman/172.19.0.11 with contents:
```
cat /var/lib/cni/networks/podman/172.19.0.11
8c3030255375d8b387db439403c5a65c6404a73bdfda319328463a2f1aab2331
```
which was not deleted for some reason during the shutdown of the system.

My current workaround is using the commented line in the above listed .service file 

**Output of podman version:**
```
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 19:10:31 2019
OS/Arch:            linux/amd64

```

**Output of podman info:**
```
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 26632208384
  MemTotal: 33602826240
  OCIRuntime:
    package: containerd.io-1.2.4-3.1.fc29.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 6635b4f0c6af3810594d2770f662f34ddc15b40d
      spec: 1.0.1-dev
  SwapFree: 34357637120
  SwapTotal: 34357637120
  arch: amd64
  cpus: 4
  hostname: zeus
  kernel: 5.0.3-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 2h 4m 2.87s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by rhatdan** [comment]
Looks like a CNI issue?

**Comment by baude** [comment]
@mheon should the IP information be stored in dirs that are recycled during a reboot ?

**Comment by jeka** [comment]
I don't have much experience in the matter, but I think the problem runs a little bit deeper.
I would expect after creating a container with fixed IP (podman create --ip x.x.x.x) this same IP to be not available for any other container. And according to my observation (actually most probably I am wrong), this would include creating a relevant file in  /var/lib/cni/networks/$netname/$fixed-ip. And yet, there is no such file created after "podman create' and the IP is not reserved in any way. Of course, podman must check that the requested IP "belongs" to the container to be started and not bailing out with an error.

**Comment by mheon** [comment]
@baude I don't think we have any say in the matter, given that CNI manages this.

@jeka We're limited here by what the CNI plugins offer us. Those files are an internal implementation detail and we have no guarantee from CNI that they will continue to work, and in the same way. At present, they do not offer IP reservation for static IPs as part of their API; any changes related to that would have to be in the plugins themselves.

**Comment by jeka** [comment]
@mheon OK, I got it.

I guess for fixed IP reservation I must use 'static' type of ipam.

**Comment by mheon** [comment]
There was some talk upstream about formalizing the way that static IPs were handled - right now we're sidestepping the CNI API by passing environment variables requesting the IP in, and they were discussing moving this to the actual API. Might be a good time to request any other changes related to static IPs like this one.

**Comment by jeka** [comment]
@mheon Thanks for the clarification. Can you please, point me at the right location for this talk?

As is turned out 'static' IPAM module is not officially released yet, so as @baude suggested I configured 'host-local' to use tmpfs for dataDir. This at least solves the problem on boot without crude 'rm -f' hack.

**Comment by rhatdan** [comment]
@jeka @mheon Can I close this issue?

**Comment by jeka** [comment]
@rhatdan no objection from me since the problem is not with podman itself

**Comment by praveenkumar** [comment]
@rhatdan @mheon Apology for commenting on a closed issue but https://github.com/containernetworking/plugins/releases/tag/v0.8.0 have now `static` plugin release and I am currently using ` 1.0.2-dev` where I also hit the same issue. I also observed https://github.com/containers/libpod/blob/master/vendor.conf#L17 we are still using `0.7.4` are we plan to update that?

**Comment by mheon** [comment]
We are planning to convert over to the 0.8.0 plugins, though I don't have a timeframe yet - ideally for 1.5.0, but we'll need to make sure it's ready before we bump our minimum plugin version to 0.8.0 (moving to the new model will break the old static IP approach).

**Comment by praveenkumar** [comment]
Thanks 👍, do we have any tracker issue so I can subscribe for this one?

**Comment by mheon** [comment]
No tracker yet, feel free to make one.
