### ISSUE TITLE
commands.md runlabel and play updates

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#2768]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm happy to fix this but need a quick verification.  The 'play' command is not on the 
https://github.com/containers/libpod/blob/master/commands.md page and I think should be.  The runlabel command is on there and I think should NOT be as it's moved to 'containers runlabel'.  @mheon or @baude if you can verify, I'm happy to touch it up.

**Comment by baude** [comment]
You are correct.

**Comment by TomSweeneyRedHat** [comment]
Thanks @baude, I'll go spin up a PR

**Comment by rhatdan** [comment]
Looks like this is fixed.
