### ISSUE TITLE
podman pod top: incomplete output

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2780]
I know this topic has been discussed to exhaustion. I still believe there is a problem that needs addressing: `pod top` is sometimes producing incomplete output on  low-cpu systems.
```bash
#!/bin/bash

wait_for_output() {
    while :;do
        x=$(podman logs $1)
        if expr "$x" : ".*PPID" >/dev/null; then return; fi
        sleep 0.1
    done
}

set -x
podman pod create --infra=false --name p

podman run -d --pod p --name c1 alpine top -d 2
podman run -d --pod p --name c2 alpine top -d 2

wait_for_output c1
wait_for_output c2

# Most of the time, this (correctly) shows 1 header and 2 process lines.
# About one time in five, on a 1-CPU system, this produces only one process
podman pod top p

podman rm -f c1 c2
podman pod rm p
```
Consistently seen and tested up to master @ c600014643fec02b5d48f092b90cc8a511c74eff

Downloadable test script (same as above): [pod-top.sh](https://github.com/containers/libpod/files/3014214/pod-top.sh.txt)

**Comment by mheon** [comment]
@baude We never parallelized top, right?

**Comment by rhatdan** [comment]
@edsantiago do you believe this is still an issue? Worth Fixing? Or can I close?

**Comment by edsantiago** [comment]
@rhatdan I can't reproduce any more - loop script ran for an hour without triggering. So I'm closing. Thanks.
