### ISSUE TITLE
Ambiguity and omissions in podman-related *.conf files

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2783]
System: Fedora 30 branched, fully updated.

Currently pawing through all of the *.conf files listed toward the end of "man podman", and there appears to be some ambiguity, as well as some missing file references.

First, I strongly recommend distinguishing between whether config files are overridden/superseded, versus whether they are added/augmented. Consider this line toward the bottom of "man podman":

`libpod.conf is the configuration file for all tools using libpod to manage containers.  When Podman runs in rootless mode, then the file `$HOME/.config/containers/libpod.conf` is used.`

Don't just say a file is "used" -- say it is used *instead*, or something that makes it clear that file is overriding/superseding the system default file. Do not make the reader have to guess. The same holds for the rest of the files listed under the "FILES" section on that man page.

The second issue is slightly more significant -- there are some missing file references. Consider again this snippet from "man podman":

```
libpod.conf (/etc/containers/libpod.conf)

libpod.conf is the configuration file for all tools using libpod to manage containers.
When Podman runs in rootless mode, then the file
`$HOME/.config/containers/libpod.conf` is used.
```

Except if one then checks "man 5 libpod.conf", one reads:

```
FILES
       /usr/share/containers/libpod.conf, default libpod configuration
       path

       /etc/containers/libpod.conf, override libpod configuration path
```

There is no mention of `/usr/share/containers/libpod.conf` in "man podman", which is potentially misleading; the man pages should be consistent.

I am currently checking the rest of the *.conf files for consistency.

**Comment by rpjday** [comment]
Same issue relates to "mounts.conf" ... "man podman" reads:

```
       mounts.conf (/usr/share/containers/mounts.conf and optionally
       /etc/containers/mounts.conf)

        The mounts.conf file specifies volume mount directories that are
automatically mounted inside containers when executing the `podman run`
or `podman start` commands. When Podman runs in rootless mode, the file
`$HOME/.config/containers/mounts.conf` is also used. Please refer to
containers-mounts.conf(5) for further details.
```
suggesting that *all* of the mounts.conf files contribute to the mount points.

But "man containers-mounts.conf" states:

```
FILES
       Some distributions may provide a
       /usr/share/containers/mounts.conf file to provide default
       mounts, but users can create a /etc/containers/mounts.conf, to
       specify their own special volumes to mount in the container.
```

That does not leave the same impression -- it is not clear from that
wording whether  `/etc/containers/mounts.conf` replaces or augments
what is in `/usr/share/containers/mounts.conf`, and also makes no 
mention of the rootless version `$HOME/.config/containers/mounts.conf`.

That should be clarified.

**Comment by rpjday** [comment]
"man containers-storage.conf" should have a "FILES" section, to be consistent with the other related man pages.

**Comment by rhatdan** [comment]
Looks like this has been fixed.
