### ISSUE TITLE
libpod attach discards stderr

### ISSUE THREAD

**Issue by baude** [containers/libpod#2792]
All of the "outbound" data is being thrown at stdout and is stderr is being ignored.

**Comment by mheon** [comment]
Easy reproducer:
`podman run -t -i --rm fedora ls -l /doesnotexist 2> /dev/null`

That should not output anything - `ls` on a nonexistent file outputs to STDERR.
Instead, we throw it out to STDOUT, and so output is printed.

Could be libpod code, could be Conmon.

**Comment by haircommander** [comment]
The issue is attaching a terminal. runc doesn't allow multiple fd's to be passed with a console_socket [0], so conmon just combines the two sockets to stdout. No fix here, unfortunately.

https://github.com/opencontainers/runc/blob/master/docs/terminals.md#new-terminal

**Comment by rhatdan** [comment]
@giuseppe Is this something crun would allow?

**Comment by giuseppe** [comment]
> @giuseppe Is this something crun would allow?

I'll take a look if there is anything I can do, but I doubt it.  There is just fd we read from, and that doesn't know where the container process is writing to, both stdout and stderr go to the terminal.
