### ISSUE TITLE
Two dangling man page references in "podman" package

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2805]
Apologies for even more pedantry ...

First, "man 1 podman" refers to "crio(8)", of which there is none that I can see -- who is supposed to provide that?

Second, "man 5 oci-hooks" similarly refers to "oci-umount(1)", which I also cannot see.

**Comment by rpjday** [comment]
Ah, I see that "oci-umount(1)" would be provided by the oci-umount package, described as "OCI umount hook for docker". But if I have no Docker-related packages installed, would I need such a package?

**Comment by rpjday** [comment]
Regarding "crio(8)", I see a number of references in libpod source:

```
$ git grep "crio(8)"
docs/podman-export.1.md:podman(1), podman-import(1), crio(8)
docs/podman-history.1.md:podman(1), crio(8)
docs/podman-image-tree.1.md:podman(1), crio(8)
docs/podman-import.1.md:podman(1), podman-export(1), crio(8)
docs/podman-info.1.md:podman(1), containers-registries.conf(5), containers-storage.conf(5), crio(8)
docs/podman-load.1.md:podman(1), podman-save(1), podman-tag(1), crio(8)
docs/podman-login.1.md:podman(1), podman-logout(1), crio(8)
docs/podman-logout.1.md:podman(1), podman-login(1), crio(8)
docs/podman-ps.1.md:podman(1), crio(8)
docs/podman-pull.1.md:podman(1), podman-push(1), podman-login(1), containers-registries.conf(5), crio(8)
docs/podman-push.1.md:podman(1), podman-pull(1), podman-login(1), crio(8)
docs/podman-save.1.md:podman(1), podman-load(1), crio(8)
docs/podman-search.1.md:podman(1), containers-registries.conf(5), crio(8)
docs/podman-tag.1.md:podman(1), crio(8)
docs/podman-version.1.md:podman(1), crio(8)
docs/podman-wait.1.md:podman(1), crio(8)
docs/podman.1.md:`containers-mounts.conf(5)`, `containers-registries.conf(5)`, `containers-storage.conf(5)`, `buildah(1)`, `crio(8)`, `libpod.conf(5)`, `oci-hooks(5)`, `policy.json(5)`, `subuid(5)`, `subgid(5)`, `slirp4netns(1)`
```
but there is no man page. Also, I'm reading a cri-o article here, https://cri-o.io/, that claims one can install the cri-o package on Fedora 28, 29 and Rawhide. I see no such package on my F30 branched system. Am I just looking in the wrong place?

**Comment by mheon** [comment]
All references to oci-umount-hook should probably be purged. It's not strictly Docker specific (it's a generic OCI hook that should work with all OCI-compliant runtimes), but we're not using it with Podman.

**Comment by rpjday** [comment]
OK, I can do that and submit a PR if it's really just a straight text deletion of all references to that.
