### ISSUE TITLE
Wrong option names in sample libpod.conf and manpage

### ISSUE THREAD

**Issue by pcguy85** [containers/libpod#2806]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Setting a value for pause_command or pause_image in libpod.conf as described in docs/libpod.conf (and manpage) has no effect. Looking at the source the names should be infra_command and infra_image respectively.

**Steps to reproduce the issue:**

1. Set custom pause_image = "localhost/pause:3.1" in /etc/containers/libpod.conf

2. Create a pod: podman pod create -n test

**Describe the results you received:**

podman tries to download pause image from the web

**Describe the results you expected:**

podman creates the pod with the image already present

**Additional information you deem important (e.g. issue happens only occasionally):**

Replacing pause_image with infra_image in libpod.conf fixes the issue

**Output of `podman version`:**

```
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
Built:              Wed Mar  6 01:55:51 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: 'podman: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: '
  Distribution:
    distribution: debian
    version: "9"
  MemFree: 1951285248
  MemTotal: 2098655232
  OCIRuntime:
    package: 'podman: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: test
  kernel: 4.9.87-1
  os: linux
  rootless: false
  uptime: 1h 29m 7.69s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@mheon Looks like we need to change the internal name to pause_command and pause_image.
