### ISSUE TITLE
"podman build": If you put tag option after context, no REPO or TAG is assigned

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2811]
Yes, I realize my fingers got ahead of me when I used this Dockerfile:
```
FROM fedora:28
RUN dnf -y install cowsay
```
and built an image using "podman build" but accidentally put the "--tag" option after the context:

`$ podman build . --tag rdayp`

it showed up under "podman images" with no repo or tag values (top line):
```
REPOSITORY                      TAG      IMAGE ID       CREATED          SIZE
<none>                          <none>   51925a656680   18 seconds ago   529 MB
docker.io/library/fedora        28       4c5b21baa7a0   2 months ago     270 MB
docker.io/library/hello-world   latest   fce289e99eb9   2 months ago     6.14 kB
```
There was no diagnostic printed, it just did the build, claimed success and gave me "none" in both the REPOSITORY and TAG fields. Does this merit at least a warning? It took me a few seconds to realize how I had messed up.

**Comment by mheon** [comment]
Is this 1.1.2? I believe we've fixed this on master

**Comment by TomSweeneyRedHat** [comment]
Definitely should be giving you a syntax error, like @mheon noted, thought this was fixed already.

**Comment by rpjday** [comment]
Crap, sorry, yes, it's 1.1.2. Will close if it's been fixed. Will also make more of an effort to check the master branch for stuff like this.
