### ISSUE TITLE
Does podman-container-rm not work (according to man page)?

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2813]
I just noticed this in "man podman-container-rm":
```
       --volumes, -v

       Remove the volumes associated with the container. (Not yet
       implemented)
```
I can see the Go file cmd/podman/volume_rm.go, which superficlally looks like it does that operation. Is the man page out of date? I can fix if so.

**Comment by mheon** [comment]
Yeah, that functionality is working now

**Comment by rpjday** [comment]
OK, I'll push a PR that removes that qualifier. Coming shortly.
