### ISSUE TITLE
Pedantic nitpickery regarding proper man page markdown formatting

### ISSUE THREAD

**Issue by rpjday** [containers/libpod#2815]
Been going through the podman man pages, and a couple questions about proper markdown formatting (not being an expert at markdown).

First, commonly, one sees a pair of options rendered in bold thusly:

`**--help, -h**`

However, would it not make more sense to not bold the intervening comma and render that as:

`**--help**, **-h**`

I've definitely seen that second variant and it makes more logical sense to me.

Also, in podman-container-exists.1.md, I read:

```
# SYNOPSIS
**podman container exists** [*-h*|*--help*] *container*
```
For the same markdown results, would you not use double asterisks instead of single in the last part of that line? Again, I am not a markdown expert so I might just not understand the effect you're going after.

**Comment by rhatdan** [comment]
The only difference between **--help, -h**  and **--help**, **-h** is the "," will be boded in the first and not in the second.  I think using the first throughout is preferable.

**podman container exists** [*-h*|*--help*] *container*
Should be
**podman container exists** [-h|--help] container

The extra "*" make no sense.

**Comment by rpjday** [comment]
OK, so based on my example, your preferred way of writing it would be:
```
# SYNOPSIS
**podman container exists** [*-h*|*--help*] *container*
```
that is, two asterisks around the command, single asterisks around the subsequent things?

**Comment by rpjday** [comment]
Oh, and just to be pedantic, my normal preferred way to render that comma would have it *not* bolded, but that requires a bunch more asterisks and it's not worth it.

**Comment by rhatdan** [comment]
Actually it should be 
**podman container exists** [*options*] *container*
None of the --help ones should exist.

**Comment by rhatdan** [comment]
@rpjday Any update on this?

**Comment by rpjday** [comment]
Sorry, I've been distracted, will get to this at some point.

**Comment by baude** [comment]
@rpjday Any update on this?

**Comment by rhatdan** [comment]
Ashley could you look into this also.

**Comment by ashley-cui** [comment]
It seems like the man pages for podman are split, some using [options] and others listing it all out. I took a look at `man man` and it gave an outline of how manual pages should be written. It looks like all the options were written on top, not just [options]. However, as seen in podman-image-trust, this can look pretty messy.

Here are some of the usages: 

`
       **bold text**          type exactly as shown.
       _italic text_        replace with appropriate argument.
       [**-abc** ]            any or all arguments within [ ] are optional.
       **-a**|**-b**              options delimited by | cannot be used together.
       _argument .._.       argument is repeatable.
       [_expression_] ...   entire expression within [ ] is repeatable.
`

**Comment by rhatdan** [comment]
@ashley-cui Yes we are just looking for you to run through them and make them consistent.

**Comment by ashley-cui** [comment]
So should I just change them all to the [options] format?

**Comment by rhatdan** [comment]
I think so, Could you show me an example of the change?

**Comment by ashley-cui** [comment]
So instead of 
```
# SYNOPSIS
**podman image trust** set|show
[**-h**|**--help**]
[**-j**|**--json**]
[**--raw**]
[**-f**|**--pubkeysfile** KEY1 [**-f**|**--pubkeysfile** KEY2,...]]
[**-t**|**--type** signedBy|accept|reject]
REGISTRY[/REPOSITORY]

# OPTIONS
**-h** **--help**
  Print usage statement.
etc
```
I have

```
## SYNOPSIS
podman image trust set|show [options]

## OPTIONS
**-h,--help**
Print usage statement

**-j,--json **
Output trust as JSON for machine parsing

**--raw**
Output trust policy file as raw JSON
```

**Comment by rhatdan** [comment]
Yup SGTM.

**Comment by rpjday** [comment]
Sorry for the lack of attention, I've been pre-occupied with a current contract. If @ashley-cui has a handle on this, I'm more than happy to hand it off, and go find something else nitpicky to whine about.

**Comment by rhatdan** [comment]
@rpjday No problem.  @ashley-cui is a summer intern and we are bringing her up to speed on the whole libpod/podman process.  Grabbing issues for her to work on.
Thanks for the issue.

**Comment by rpjday** [comment]
The only nitpick I would have with the above is, instead of
**-h,--help**
I would avoid bolding the comma, as in:
**-h**,**--help**
as any punctuation like that is not formally part of the option string.
