### ISSUE TITLE
BUG: loading multiple images corrupts tags of existing ones

### ISSUE THREAD

**Issue by h-vetinari** [containers/libpod#2821]
[Now that I have access to the nightly ppa's (cf. containers/libpod#2250), here's some more things I found]

Sometimes it's necessary to transfer images in bulk (say, to an environment that has restricted internet access). Docker supports saving/loading multiple images, and nominally, podman does too. Loading multiple images saved by docker fails (xref #2822), while loading multiple images saved by podman go through but are either loading incorrectly or even corrupting tags that might have been correct before.

This is a much subtler issue and thus harder to detect.

Steps to reproduce:
```
$ sudo podman pull ubuntu:bionic
$ sudo podman pull ubuntu:cosmic
```
Then, things look as follows.
![multi1](https://user-images.githubusercontent.com/33685575/55333934-81be3800-5498-11e9-99ac-114f8f1031bc.png)

Saving and reloading corrupts the tags.
```
$ sudo podman save docker.io/library/ubuntu:bionic docker.io/library/ubuntu:cosmic > podman_test.tar
$ sudo podman load -i podman_test.tar
```
In particular, `docker.io/library/ubuntu:cosmic` gets wrongly tagged to the commit of `docker.io/library/ubuntu:bionic`, while the actual commit of `docker.io/library/ubuntu:cosmic` gets untagged. 
![multi2](https://user-images.githubusercontent.com/33685575/55333987-9f8b9d00-5498-11e9-80ad-c7910cb224d0.png)

Side note: in contrast to docker, there is no auto-completion for file-names after `sudo podman load -i`

**Comment by h-vetinari** [comment]
@haircommander 
In view of [your comment](https://github.com/containers/libpod/issues/2822#issuecomment-478607766), and before containers/image#610 is fixed, this should IMO at least error loudly, rather than corrupt existing tags.

**Comment by baude** [comment]
@haircommander is this in your domain or do we need to get someone to pick it up?

**Comment by haircommander** [comment]
@baude it is generally out of my domain--it could be in my domain given some time (that I don't currently have) :)
