### ISSUE TITLE
BUG: loading multiple images saved by docker fails

### ISSUE THREAD

**Issue by h-vetinari** [containers/libpod#2822]
[Now that I have access to the nightly ppa's (cf. containers/libpod#2250), here's some more things I found. Companion to #2821]

Sometimes it's necessary to transfer images in bulk (say, to an environment that has restricted internet access). Loading images with podman saved by docker works for single images, but not if there's several (however, loading of several images saved by podman does not work either, see #2821).

Saved by vs #images | single image | multiple images
--------|-----|-----
podman | works | works
docker | works | fails

(Note that docker checks all four boxes here, i.e. importing multiple images saved by podman works)

Steps to reproduce:
```
$ sudo docker pull ubuntu:bionic
$ sudo docker pull ubuntu:cosmic
$ sudo docker save ubuntu:bionic ubuntu:cosmic > podman_test.tar
$ sudo podman load -i podman_test.tar
```
The last command fails with:
```
ERRO[0001] Error pulling image ref podman_test.tar: Error determining manifest MIME type for docker-archive:podman_test.tar: Unexpected tar manifest.json: expected 1 item, got 2
Failed
ERRO[0001] Error pulling image ref podman_test.tar: Error determining manifest MIME type for dir:podman_test.tar: open podman_test.tar/manifest.json: not a directory
Failed
Error: error pulling "": unable to pull dir:podman_test.tar: unable to pull image: Error determining manifest MIME type for dir:podman_test.tar: open podman_test.tar/manifest.json: not a directory
```

**Comment by haircommander** [comment]
this is a duplicate of https://github.com/containers/libpod/issues/2669 :) I will escalate the fix for this, it's going to require some structural changes, so it may take a little to land unfortunately

**Comment by h-vetinari** [comment]
@haircommander 
Sorry for not seeing this before - when I last looked (before I got access to the nightlies), it wasn't there yet. Closing this as duplicate.

Note this also plays into #2821, but I'd suggest to leave that open since the spurious retagging is IMO different from the failure to save several images (actually, the log wrongly suggests that it works - at first glance at least).

**Comment by haircommander** [comment]
They're two issues from the same root problem, and both would be fixed at the same time, but we can leave it open so other people who encounter it can see it's already a known problem. Thanks for the issues @h-vetinari !
