### ISSUE TITLE
Regression: 1.2.0: 'ps --size' crashes

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2824]
```
$ podman run alpine date
[ok]
$ podman ps --size
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x556486a3432a]
[...and many more pages of stacktrace]
```
nonroot only, and only if there's at least one container (not necessarily running). Does not fail after `podman rm -a`.

Baffling and unexpected. Probably a showstopper.

podman-1.2.0-2.git3bd528e.fc29.x86_64

**Comment by baude** [comment]
... looking

**Comment by baude** [comment]
the c.runtime.store is nil
```
(dlv) p c.runtime.store
github.com/containers/libpod/vendor/github.com/containers/storage.Store nil
```

**Comment by mheon** [comment]
I'll take this one

**Comment by giuseppe** [comment]
this one should be fixed with the refactoring.  Please reopen if it is still happeing

**Comment by mheon** [comment]
@giuseppe I actually landed a separate fix that made this an error - need to remove that now that single userns is merged

**Comment by mheon** [comment]
Basically need a revert of https://github.com/containers/libpod/pull/2832
