### ISSUE TITLE
podman cp does not copy folders

### ISSUE THREAD

**Issue by MarcoFalke** [containers/libpod#2836]
/kind bug

**Steps to reproduce the issue:**

Compare podman and docker:

```
$ ls /tmp/new_folder_02/
$
$ podman cp /tmp/new_folder_02 sweet_hellman:/home/
$ podman exec sweet_hellman ls /home/
$
$ sudo docker cp /tmp/new_folder_02 elated_kalam:/home/
$ sudo docker exec elated_kalam ls /home/
new_folder_02
$
```

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
@MarcoFalke just to verify, are there any symlinks involved in this particular copy?

**Comment by MarcoFalke** [comment]
Not that I am aware of. I created the empty folder with `mkdir /tmp/new_folder_02`

**Comment by QiWang19** [comment]
`podman cp` copies the content under the folder into /home/. `ls /home/` shows nothing because the /tmp/new_folder_02 is empty.
Yes, this is kind of a bug because it's different from docker
