### ISSUE TITLE
podman play kube does not accept pod descriptions that have neither command nor args

### ISSUE THREAD

**Issue by larsks** [containers/libpod#2854]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman should accept a pod description like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: metrics
spec:
  containers:
  - name: mosquitto
    image: eclipse-mosquitto
    ports:
      - hostPort: 1883
        containerPort: 1883
        protocol: tcp
```

But this will fail with:

```
Error: container create failed: args must not be empty
```

That means there is no way to declare a container that uses the
default entrypoint and command declared in an image.

**Steps to reproduce the issue:**

1. Use the pod description referenced above.

**Describe the results you received:**

(see description)

**Describe the results you expected:**

I expected the container to start using the `ENTRYPOINT` defined in
the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.2.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.1
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version , commit: 8fba206232c249a8fc4e2fac1469fb2fddbf5cf7'
  Distribution:
    distribution: arch
    version: unknown
  MemFree: 7593590784
  MemTotal: 8283283456
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7
      commit: 69ae5da6afdcaaf38285a10b36f362e41cb298d6
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: data
  kernel: 5.0.5-arch1-1-ARCH
  os: linux
  rootless: false
  uptime: 23h 20m 45.74s (Approximately 0.96 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 14
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by mheon** [comment]
I thought we fixed this one recently (@haircommander did some work on configuring containers from `play kube` from images), but you're running 1.2.0, and I was pretty sure that work landed there, so maybe I'm mistaken.

**Comment by haircommander** [comment]
@mheon I think you're mixing my volume work and the work I did with the pod pause image :) I don't think we have encountered this with play kube yet!

**Comment by haircommander** [comment]
PR here: #2856

**Comment by haircommander** [comment]
PR is merged, closing :)
