### ISSUE TITLE
commit bc320be00bc... (linter) BROKE US

### ISSUE THREAD

**Issue by baude** [containers/libpod#2866]
commit bc320be00bc584bd88525266d23a9d5edb9d44f8 broke our CI; it needs to be reverted so we can process PRs.

When I attempted to create a PR to revert it, it fails because the gometalinter has been removed from the image?

WE CAN NO LONGER PROCESS PRS AND MERGE THEM

**Comment by giuseppe** [comment]
@baude the change was reverted now, can we close this issue?
