### ISSUE TITLE
Podman does not handle image layers correctly, resulting in using x times the diskspace

### ISSUE THREAD

**Issue by amiga23** [containers/libpod#2868]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you pull an image each "EXPOSE, ENTRYPOINT, ..." command used in the image will result in a layer that uses the full image size so far. So in the end x times of the wize will be used on disk. 

**Steps to reproduce the issue:**

1. Create an image with several copy commands, e.g.
```
    FROM busybox:latest
    COPY file1 file1
    COPY file2 file2
    COPY file3 file3
    ENTRYPOINT ./file1
    EXPOSE 8080
    EXPOSE 8081
    EXPOSE 8082
    EXPOSE 8083
    COPY file3 file4
    EXPOSE 8084
```

2. Build the image with podman build

3. Check the artifacts

let's asume file1 is 4MB in size, file2 is 6MB in size and file3 is 10MB in size.
Together with the busybox base image, the image size will be 20.3MB. That is the size, that "podman images" will show.
But in the "storage/vfs/dir/" you will find 11 layers having a total size of 208MB diskspace used.
- 1 layer will be the busybox image with 1.3MB.
- 1 layer will be file1 but with the size of file1 + the 1.3MB of the base image.
- 1 layer will be file2 but with the size of file2 + the 1.3MB of the base image.
- 1 layer will be file3 but with the size of file3 + the 1.3MB of the base image.
- 6 layer with the size of files 1, 2 and 3 + the base image
- 2 layer with the size of the first 3 files + the base image + size of file4

So every EXPOSE or ENTRYPOINT directive adds a layer will the size of everything added before.

This also happens when pulling images from dockerhub. For example: "podman pull pierrecdn/phpipam" will use 8.8GB for an image that has only 469MB.

**Describe the results you received:**

x times diskspace used.

**Describe the results you expected:**

Layers handled correctly, each layer should only contain the files it adds without the the base image, EXPOSE and ENTRYPOINT directives should not add the whole image size to a new layer.

**Additional information you deem important (e.g. issue happens only occasionally):**

Had to edit this issue, as I did misinterpret the results.

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12.1
Built:              Tue Apr  2 20:01:51 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.1
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version , commit: 8fba206232c249a8fc4e2fac1469fb2fddbf5cf7'
  Distribution:
    distribution: arch
    version: unknown
  MemFree: 4825956352
  MemTotal: 8374444032
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7
      commit: 69ae5da6afdcaaf38285a10b36f362e41cb298d6
      spec: 1.0.1-dev
  SwapFree: 9423495168
  SwapTotal: 9448923136
  arch: amd64
  cpus: 4
  hostname: amda10
  kernel: 5.0.5-arch1-1-ARCH
  os: linux
  rootless: true
  uptime: 2h 18m 40.63s (Approximately 0.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1006
  VolumePath: /home/podman/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical on AMD64 and on ARM64 using Archlinux

**Comment by amiga23** [comment]
Issue updated, as I did interpret the results wrong. Every EXPOSE or ENTRYPOINT directive adds the full size of the image and every COPY directive adds the files + the base image.

**Comment by mheon** [comment]
This is a property of the VFS graph driver, and why we don't recommend
using it. Using overlayfs (root) or fuse-overlayfs (rootless) will result
in proper deduplication and storage use.

**Comment by amiga23** [comment]
Thanks for the hint, fuse-overlayfs is available on AUR in Archlinux. After installing and switching storage diver to "overlay" it works like expected.
