### ISSUE TITLE
Equivalent of docker registry-mirrors configuration

### ISSUE THREAD

**Issue by parnigot** [containers/libpod#2871]
Hello,

We are currently evaluating podman at my workplace as a lightweight alternative to docker. Given that all our hosts do not have direct access to the Internet we have to use a private mirror to pull images from the docker hub.

Docker is easy configured by by adding in `/etc/docker/daemon.json` the following:

```
"registry-mirrors": ["https://docker-mirror.internal.network"]
```

With the mirror configured a simple `docker pull alpine` works transparently.

Does podman support something similar? I've searched the documentation with no avail, and right now the only (ugly) workaround that I've found is to specify the mirror address like:

```
podman pull docker://docker-mirror.internal.network/alpine
```

**Comment by vrothberg** [comment]
Hi @parnigot,

thanks a lot for reaching out.

We are currently working on a feature that is similar to Docker's `registry-mirrors` but more powerful as it allows to mirror any registry, not only `docker.io`. You can track the progress over at https://github.com/containers/image/pull/564. This PR will rather sooner than later be merged and the feature will eventually be made available for Podman, Buildah, Skopeo, and CRI-O.

**Comment by rhatdan** [comment]
That PR Seems to be getting closer.

**Comment by baude** [comment]
@vrothberg the pr in question is now merged ... does anything else need to be done to resolve the reported issue?

**Comment by vrothberg** [comment]
My apologies for the very late reply.

The PR at containers/image is merged, and everything has been vendored into Podman. The documentation for mirroring registries can be found here: https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md
