### ISSUE TITLE
Regression in allowed container names breaks Fedora 30 SilverBlue

### ISSUE THREAD

**Issue by hughsie** [containers/libpod#2876]
/kind bug

In the old commit from 2018 de6d5b75ac8baa6871991984dc8dcf9b702b8a9e libpod added a regex to check the container name, which was then changed in https://github.com/containers/libpod/pull/2793 to be a little less restrictive. Something more recent than this started then broke fedora-toolbox (and thus Fedora SilverBlue) as it uses container names like `fedora-toolbox-hughsie:30` i.e. with a colon before the tag. I've not tracked down the exact commit that is responsible. We did think `:` was a valid char as it's used heavily in the OCI spec...

**Steps to reproduce the issue:**

1. Install Fedora 30 SilverBlue
2. toolbox create

**Describe the results you received:**

    toolbox: trying to create container fedora-toolbox-hughsie:30
    Error: error running container create option: name must match regex [a-zA-Z0-9_-]+: invalid argument

**Describe the results you expected:**

A toolbox with the name `fedora-toolbox-hughsie:30`

**Output of `podman version`:**

```
$ podman version
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 12024987648
  MemTotal: 16411090944
  OCIRuntime:
    package: runc-1.0.0-75.dev.git751f18d.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 34cd853bfa9dc792faaae59bbb4d3020225c98c8
      spec: 1.0.1-dev
  SwapFree: 8270114816
  SwapTotal: 8270114816
  arch: amd64
  cpus: 64
  hostname: localhost.localdomain
  kernel: 5.0.5-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 28m 37.99s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/hughsie/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/hughsie/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /var/home/hughsie/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server, Fedora 30 SilverBlue.

**Comment by mheon** [comment]
Wait, we previously allowed `-` and `:`? That sounds like a bug to me. The original intent of the regex was alphanumeric characters and `_`

I have no issues with allowing `-` but `:` is more problematic. It has special connotations in image names, for example - allowing it makes it much more ambiguous whether a name refers to an image or container.

**Comment by debarshiray** [comment]
@mheon yes, since commit 449b8ab7b14fcc0d9e3badbe14b09f387c2c459c or #2793 `podman create` started erroring out if the container was named something like `fedora-toolbox-foo:30`.

I don't know how that commit suddenly started causing problems, but I do know that `podman-1.2.0-28.dev.gitfdf979a` accepted colons and `podman-1.2.0-29.dev.git7b73974` didn't. Bisecting within that range led me to this conclusion.

The toolbox uses `:<tag>` to differentiate between containers created from different Fedora releases, similar to images. If colons are frowned upon, then I guess we should switch to something like a hyphen?

**Comment by mheon** [comment]
@debarshiray The original regex shouldn't have allowed colons, so I would say they are frowned on. Even if we decide to keep support, I would recommend you swap from `:` to a hyphen or underscore, for container/image naming clarity.

@vrothberg You might want to weigh in here as to whether we consider this an API change. IMO this is a bugfix, given that support for non-alphanumeric/underscore characters was never intended and never advertised.

**Comment by vrothberg** [comment]
> @vrothberg You might want to weigh in here as to whether we consider this an API change. IMO this is a bugfix, given that support for non-alphanumeric/underscore characters was never intended and never advertised.

Theoretically, it should entail a major version bump as it broke backward compat. The reason for the change should not impact the versioning scheme though.

I am indoctrinated by the kernel's "never break user space" rule. (IMHO) If we allowed `:` before, we should continue to support it. We could discourage users from using a `:` with a big logrus warning (or even error?).

**Comment by zerotri** [comment]
> @debarshiray The original regex shouldn't have allowed colons, so I would say they are frowned on. Even if we decide to keep support, I would recommend you swap from `:` to a hyphen or underscore, for container/image naming clarity.

While I'm not privy on Go's regex quirks, the original regex doesn't check for the beginning and end of the string, so in order to match it would only need to match somewhere in the name, not the name as a whole. The newer regex tests against the whole name.

So with the old regex `fedora-toolbox-me:30` should return two matches `fedora-toolbox-me` and `30`.
With the new regex, the same string will return no matches because of the existence of the colon.

**Comment by mheon** [comment]
@zerotri Yeah, I think that was an oversight when we wrote the original one... The original intent was to validate the entire name

**Comment by mheon** [comment]
In the interest of not breaking toolbox, I'm thinking that we'll change the regex to allow `:` characters, with a warning that this is a deprecated feature and may be removed in the future.
@vrothberg @debarshiray Does this sound acceptable?

**Comment by debarshiray** [comment]
@mheon That sounds sane to me, but I'd still update toolbox to not use a colon as soon as possible.

I haven't yet been able to fully assess the extent of the breakage here. So far I only know that `podman create` errors out with faulty container names, but I don't know about `podman start` and `podman exec`. If those aren't affected then existing containers would continue to work.

**Comment by vrothberg** [comment]
> @vrothberg @debarshiray Does this sound acceptable?

Sounds good to me.

**Comment by mheon** [comment]
We only validate for creating new containers, so existing ones should be
fine to continue using.

**Comment by debarshiray** [comment]
I have [updated](https://github.com/debarshiray/toolbox/pull/113) the toolbox to not put colons in the names of containers while creating them.

**Comment by mheon** [comment]
Updating the regex to allow colons now

**Comment by mheon** [comment]
I'm going to do this only for containers - pods and volumes will continue to be colon-free

**Comment by mheon** [comment]
#2914 to re-add `:` as an allowed character with warnings.
