### ISSUE TITLE
Rootless podman ps segfault on refresh when containers are present

### ISSUE THREAD

**Issue by mheon** [containers/libpod#2894]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Segfault stack trace: https://paste.fedoraproject.org/paste/ClFhuW2MYXIW2qESPyQ4Mg

When rootless `podman` runs the `refresh` command when containers are present, it will segfault.

Nearest I can tell, the sequence of events goes like this:
Podman's main creates a fresh `libpod.Runtime` to search for user namespaces to join
We haven't joined a user namespace yet, so `GetEUID()` != 0, so the `storage.Store` is not configured
A refresh is requested, so the code attempts to call into the store to create the container's temporary directories. The store has not yet been configured, so we segfault. Podman becomes unusable because refresh is impossible.

We need to do a refresh, though. Otherwise we won't properly reset container states after reboot.

**Steps to reproduce the issue:**

1. Create at least one container e.g. `podman create -t -i fedora bash`

2. Reboot the system

3. Run any `podman` command that is not `podman version`

**Describe the results you received:**

Podman segfaults

**Describe the results you expected:**

Podman does not segfault

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Current master on F29, originally noticed with Rawhide packages

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/containers/libpod/pull/2896
