### ISSUE TITLE
podman native support for systemd .service file

### ISSUE THREAD

**Issue by jamescassell** [containers/libpod#2918]
/kind feature

**Description**

It would be super useful to have podman run a .service file within the container w/o running a full-blown systemd in the container.  Something as simple as specifying `--entrypoint-service=/usr/lib/systemd/system/httpd.service` and auto-selecting the ExecStart line to run with `catatonit` seems like it might work, though a complete replacement might require more work.

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

Not a feature yet.

**Describe the results you expected:**

Can `yum install httpd` then `podman run --entrypoint-service=/usr/lib/systemd/system/httpd.service mycontainer`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
That would involve podman being able to handle all of the flags of the systemd unit file,  NOT going to happen.  I don't see this as a viable option.

**Comment by jamescassell** [comment]
Better might be a systemd feature to start the service then exec catatonit for signal handling, but otherwise get out of the way...

**Comment by rhatdan** [comment]
Why would systemd launch another init system?

**Comment by jamescassell** [comment]
I was just trying to think of a way to re-use the systemd parsing mechanism but not require the entire systemd stack to be running in the container.  I'd brought it up on IRC and someone said I should open this issue to get feedback on the idea of having podman run a .service file with catatonit.  Sounds like it's beyond the realm of possibility, or not desired.

My hope had been to re-use pre-written .service files to avoid having to write custom entrypoint.sh scripts.

**Comment by rhatdan** [comment]
Ping me on IRC and we can discuss  your idea.

**Comment by baude** [comment]
did you guys talk? any movement or action required on this?

**Comment by jamescassell** [comment]
Probably the most appealing reasons to have this are:
1. to avoid setting the `container_manage_cgroup` seboolean.
2. to avoid multiple processes in the container
3. to avoid writing custom entrypoint.sh for each service

It would be cool to have systemd be able to serialize the config for a single `.service` into something akin to an entrypoint.sh that's run by catatonit for signal handling, but such a feature would likely be relevant to systemd not podman.  I'd like to be able to leverage pre-existing systemd service files without running multiple processes in my containers.  I understand it's a pretty big ask.

**Comment by rhatdan** [comment]
@jamescassell Any chance you could open a PR to show your idea?

**Comment by baude** [comment]
updates?

**Comment by rhatdan** [comment]
We really don't see a way to do this easily so I am going to close.
