### ISSUE TITLE
podman-logs output and podman-logs man page very different

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#2920]
Podman logs seems to just show you what happened in the container without timestamps where as podman logs man pages show time stamps and seem to be from when it showed cri-o logs.

Which is correct?

**Comment by mheon** [comment]
We do support timestamps, but only via explicit request. There is a flag
you need to add whose name I forget.

**Comment by rhatdan** [comment]
Well all of the examples in the man pages are wrong, then because they all show timestamps without any special flags that I see.

**Comment by baude** [comment]
To enable timestamps for log messages, you must pass the `--timestamps|-t` flag.  Timestamps are off by default.  We follow docker exactly on this one.

What you are seeing in the examples are a result of logging a redis container.  Redis logs include a timestamp (not related to podman log timestamping).   Mariadb does the same.  Postgresql does not but the log is not very long.

**Comment by baude** [comment]
@rhatdan are we cool?
