### ISSUE TITLE
running rootless `podman image exists` within a `buildah unshare` session results into "could not get runtime... /var... permission denied"

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#2924]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This could be a dupe of #2510.

The issue is coming from
https://github.com/ansible-community/ansible-bender/issues/114 when a command
`podman --log-level debug image exists $id` in rootless mode results into:
```
Error: could not get runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission denied
```

I have purged ~/.config/containers so all the config files are in the default state.

The problem likely is that this command is ran within a `buildah unshare` session.

Feel free to close if this is a dupe.

Real example:
```
$ buildah unshare podman inspect cf427cab2eee
Error: error creating libpod runtime: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission
denied
ERRO[0000] exit status 125
ERRO[0000] exit status 125

$ buildah unshare buildah inspect cf427cab2eee
{
    "Type": "buildah 0.0.1",
    "FromImage": "localhost/image-built-with-role-20190413-194148628160:latest",
    "FromImageID": "cf427cab2eee3bc20d116d36ad620495c90be146e3cca020f3957ef0e47956cb",
    ...
```

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
Looks like rootless detection could be broken in `buildah unshare`

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
we made some changes while refactoring the unshare implementation but that must be already fixed upstream in buildah

**Comment by baude** [comment]
@giuseppe is this fixed?

**Comment by giuseppe** [comment]
yes this is fixed upstream in buildah.

Also we now have `podman unshare` so we don't need to depend on buildah
