### ISSUE TITLE
slirp4netns produces error message, but isn't required

### ISSUE THREAD

**Issue by vsoch** [containers/libpod#2925]
It looks like slirp4netns is needed for setting up the user networking space? Without it (running a container that doesn't need anything special) I get an error that it isn't found:

```bash
$ podman run vanessa/salad
ERRO[0000] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 

 In Go an array is a slice. Utensil discrimination!  

          _________________  .========
         [_________________>< :======
                             '======== 

```
The fix was to install it, of couse:
```bash
$ sudo apt-get install -y slirp4netns
```
```bash
$ podman run vanessa/salad

 Cut it out.  

                   ________  .====
                  [________>< :===
                             '==== 

```
I searched the repo and I didn't see any obvious instruction to install it, other than the Dockerfile for a [fedora](https://github.com/containers/libpod/blob/b625c47ae5170e09d354b6e4e3d40445642102c9/contrib/gate/Dockerfile#L35) base and in the [tutorial here](https://github.com/containers/libpod/blob/7f8e9bd54c7a1c46ea19b58296f6629d55988e0d/docs/tutorials/podman_tutorial.md#familiarizing-yourself-with-podman) (unless it comes via another package?) so the question at hand is if the library should be required, or if the user should discover that it's needed, google search for it, and then install after the fact (btw, the error message telling me to do this was :smile:). At least in [the spec](https://github.com/containers/libpod/blob/278c961f9814b6dde1cb52b017e4afe52f4ad98b/contrib/spec/podman.spec.in#L78) it looks like it's recommended, so it could be that the choice was made to not require it (and then no further action is needed) otherwise it might be logical to add at least to documentation somewhere. Thoughts?

**Comment by giuseppe** [comment]
The reason behind it is that you can use rootless podman without slirp4netns if you specify `--net=host`, so you don't create a new network namespace that must be configured.

Similarly `fuse-overlayfs` is also recommended but not required as you can still use rootless containers with the `vfs` backend.

**Comment by rhatdan** [comment]
Also neither is required for running non rootless.  Therefor fuse-overlay and slirpnetns are Recommended not required.

**Comment by vsoch** [comment]
Makes sense. It wasn't needed for my particular container, so should the message be an error or a warning? The average user is likely to miss this detail, install without it, and then see the error message. Some possible ways to get around this:

 - better documentation (although likely they won't read it beyond install instructions)
 - if slirp3netns is not found, can it not be assumed that --net=host? It might be logical to set this, and then give a warning (not an error).

There should be some solution that removes the default from being triggering this error, and requiring the user to know something substantial about network preferences / setup. Thoughts?

**Comment by rhatdan** [comment]
I think better documentation is always good.  But is this a packaging issue. On Fedora and RHEL8 we have those packages as Recommends, which means they get installed by default.  They are only NOT installed if the person installing the packages tells yum to not install them.

Do we have the same setup for Ununtu?

**Comment by vsoch** [comment]
Based on installing from the package manager and not getting this installed, I'd say the same setup isn't working for Ubuntu. 

Where is the code to release? I just found the [ubuntu_setup.sh](https://github.com/containers/libpod/blob/master/contrib/cirrus/packer/ubuntu_setup.sh) which I think is for testing.

**Comment by baude** [comment]
@lsm5 is this something you fixed?

**Comment by rhatdan** [comment]
@vsoch @lsm5 @jnovy Please tell us if this is fixed and can be closed

**Comment by vsoch** [comment]
I might be testing again on our cluster at some point, but it would be for a centos base (not ubuntu), I probably won't install on my host again just in case there is still an issue. So - probably don't wait up for me to test!

**Comment by baude** [comment]
closing, please re-open if issue persists
