### ISSUE TITLE
Ubuntu ppa: Cannot ioctl TIOCSCTTY: Operation not permitted

### ISSUE THREAD

**Issue by sdcroll** [containers/libpod#2926]
/kind bug

**Description**

I installed podman on Ubuntu 18.04 from the ppa today (2019-04-13), and when running a container, podman commands in other terminals fail.  Example:

    $ podman ps
    cannot ioctl(TIOCSCTTY): Operation not permitted

    $ podman images
    cannot ioctl(TIOCSCTTY): Operation not permitted

If I stop the container, then the commands succeed:

    $ podman ps
    CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

**Steps to reproduce the issue:**

1.  sudo apt -y  install software-properties-common
     sudo add-apt-repository -y ppa:projectatomic/ppa
     sudo apt -y install podman

2.  podman  run -it  --rm docker.io/library/alpine /bin/sh

3.  podman ps   # or whatever, in another terminal

**Describe the results you received:**

    $ podman ps
    cannot ioctl(TIOCSCTTY): Operation not permitted

**Describe the results you expected:**

    $ podman ps
    CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.0-dev
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 5354041344
  MemTotal: 33671516160
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 34028384256
  SwapTotal: 34028384256
  arch: amd64
  cpus: 8
  hostname: squirrel
  kernel: 4.15.0-46-generic
  os: linux
  rootless: true
  uptime: 452h 13m 54.73s (Approximately 18.83 days)
insecure registries:
  registries: []
registries:
  registries: []
store:
  ConfigFile: /home/scroll/.config/containers/storage.conf
  ContainerStore:
    number: 15
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/scroll/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 31
  RunRoot: /tmp/1000
  VolumePath: /home/scroll/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Huh. This one's pretty strange. `podman images` for example should have absolutely no relation to a container running in another terminal - it will never invoke the OCI runtime, or attempt to retrieve container status.

I see two instances of TIOCSCTTY in the libpod code base, both vendored. One is part of `buildah unshare` and I'm fairly certain Podman will never invoke that code. The other is part of our vendored `libcontainer` from `runc` and is in a function that is never called in our codebase. I'm properly confused as to where this is coming from. Potentially being generated by your shell, maybe?

**Comment by mheon** [comment]
What command are you running in the container? Does running another command (e.g. `podman run -t -i --rm fedora bash` have different results?

What shell are you running?

**Comment by mheon** [comment]
Can you try a `podman run` command without `-t` and see if the issue still occurs?

**Comment by mheon** [comment]
Reproduced on Fedora 29, rootless. @baude @giuseppe FYI - this one looks gnarly.

**Comment by mheon** [comment]
`strace -f` does not find a single ioctl call with that ioctl from Podman itself - it has to be the shell. Theory: something we're doing with /dev/console puts things in a bad state.

**Comment by mheon** [comment]
Just about anything else I've tried, Buildah included, is unaffected, so it seems to just be Podman.

**Comment by mheon** [comment]
Not specific to `-t` flag, which I'm pretty sure gates all our our raw terminal stuff - so that's probably off the table as a cause

**Comment by mheon** [comment]
Podman run reacts very poorly to being strace'd now, seemingly.

**Comment by mheon** [comment]
@giuseppe I think this has to be the Rootless userns.

The first container makes the userns, and it seems to be fine. Every subsequent Podman call, though, joins the existing userns, and causes the controlling shell to get an EPERM on trying TIOCSCTTY (I can't tell yet if this happens before or after the command runs), and we get no output out of the command.

**Comment by sdcroll** [comment]
I was able to catch the failing ioctl() call by writing the strace output to a file:

```
$ strace -f -o /tmp/podman.strace podman ps
cannot ioctl(TIOCSCTTY): Operation not permitted

$ grep TIOCSCTTY /tmp/podman.strace
26975 ioctl(1, TIOCSCTTY, 0)            = -1 EPERM (Operation not permitted)
26975 write(2, "cannot ioctl(TIOCSCTTY): Operati"..., 49) = 49
```

If I'm reading the output correctly (I don't have any direct experience with clone), I _think_ a thread of podman is forking a child and that child is calling ioctl():

```
26960 execve("/usr/bin/podman", ["podman", "ps"], 0x7ffc7d0df8a0 /* 58 vars */) = 0
26960 brk(NULL)                         = 0x3bd3000
...
...
...
26960 clone( <unfinished ...>
...
26960 <... clone resumed> child_stack=0x7efc7bffeeb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7efc7bfff9d0, tls=0x7efc7bfff700, child_tidptr=0x7efc7bfff9d0) = 26968
...
...
...
26968 clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7efc7bfff9d0) = 26975
26975 set_robust_list(0x7efc7bfff9e0, 24) = 0
...
26975 prctl(PR_SET_PDEATHSIG, SIGTERM)  = 0
26975 ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
26975 ioctl(1, TIOCSCTTY, 0)            = -1 EPERM (Operation not permitted)
26975 write(2, "cannot ioctl(TIOCSCTTY): Operati"..., 49) = 49
26975 exit_group(1)                     = ?
26975 +++ exited with 1 +++
...
...
...
```

**Comment by giuseppe** [comment]
I've introduced this issue some days ago, I've prepared a PR to revert it: https://github.com/containers/libpod/pull/2927

**Comment by sdcroll** [comment]
Probably not related to the ioctl() issue, but if this is indeed a thread calling fork (per the CLONE_THREAD argument) then be aware that you can only make async-signal-safe calls in the child process or you risk deadlock or other such bad behavior.

From my fork() manpage:

```
       *  After a fork() in a multithreaded program, the child can safely call
          only  async-signal-safe  functions (see signal-safety(7)) until such
          time as it calls execve(2).
```

Calls such as setenv(), fprintf(), strerror(), and free() are definitely not async-signal-safe.  Not sure about some of the other calls in reexec_userns_join().

Also, setenv() and strerror() are not thread safe.
