### ISSUE TITLE
Podman doesn't load registries.conf from $HOME/.config/containers

### ISSUE THREAD

**Issue by Snapstromegon** [containers/libpod#2955]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

According to [this](https://github.com/containers/libpod/blob/master/docs/podman.1.md) -> Files registries.conf it should be possible to overwrite the registries.conf with a file at /home/USERNAME/.config/containers/registries.conf.

I created the default .conf file at that location and recieve a warning, that podman was unable to find it.

**Steps to reproduce the issue:**

1. Move the registries.conf to the .config/containers folder

2. Run podman in rootless mode

**Describe the results you received:**

```
$ podman --log-level debug run --rm -it alpine
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
```

**Describe the results you expected:**

I'd expect to see all paths, where podman looks for the registries and that it finds the custom registries.conf.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm doing this on a shared host, so I'm not able to do anything you'd need root priveleges for.
The /etc/containers/... doesn't exist.

**Output of `podman version`:**

```
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
Version:       0.12.1.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

**Output of `podman info --debug`:**

```
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
cannot clone: Invalid argument
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
ERRO[0000] cannot re-exec process
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Uberspace shared host running CentOS Linux release 7.6.1810 (Core)

**Comment by Snapstromegon** [comment]
My research after cloning the repo shows, that in platform_linux.go the method "CheckForRegistries" actually only looks for the etc registries.conf and outputs the error if it doesn't exist.

In my opinion it should look for overwrites before assuming none is present.

**Comment by mheon** [comment]
I don't know if there is code in c/image for parsing override paths for registries.conf - @giuseppe you would've been the one to add that, probably?

**Comment by baude** [comment]
@giuseppe ptal

**Comment by giuseppe** [comment]
AFAICS, that is only a warning, that should not be printed while running as rootless.  Anything else should be already working fine

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/3227

**Comment by rhatdan** [comment]
@giuseppe Is 
```
Non root users of Podman can create the `$HOME/.config/containers/registries.conf` file to be used instead of the system defaults.
```
true?

**Comment by giuseppe** [comment]
@rhatdan yes, I've tested it by deleting `/etc/containers/registries.conf` and the `$HOME/.config/containers/registries.conf` file was honored.

@Snapstromegon could you confirm that the current git master version of Podman behaves in this way for you as well?

**Comment by Snapstromegon** [comment]
@giuseppe Yes, verified, seems like I was too panic about the warning.
