### ISSUE TITLE
Setting users in pod.yaml

### ISSUE THREAD

**Issue by Fodoj** [containers/libpod#2957]
/kind feature

### Description

I'd love to be able to set a user for container inside pod.yaml, with securityContext. Is that already possible? I tried with `runAsUser` but it didnt change the user.

**Comment by mheon** [comment]
Should be possible, but entirely possible we haven't wired that field in yet.

**Comment by Fodoj** [comment]
@mheon is that the complete code of parsing yaml and converting it to OCI spec and passing it to pod creation? https://github.com/containers/libpod/blob/master/cmd/podman/play_kube.go

**Comment by mheon** [comment]
Yes, all the `play kube` code lives in that file now

**Comment by baude** [comment]
@lsm5 we can talk about this next week

**Comment by vrothberg** [comment]
Ping, any movement on it? We could add a tag to get the community implement it?

**Comment by lsm5** [comment]
@vrothberg nothing so far from my side, and can't say at this point when I can get to it.

**Comment by rhatdan** [comment]
@haircommander Any chance you could look at this?  Or maybe I will grab it.

**Comment by haircommander** [comment]
Yeah I'd like to get #4265 in, then start unifying the namespace workflow for pods

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by rhatdan** [comment]
From my reading of the code, I think this is implemented, reopen if I am mistaken.
