### ISSUE TITLE
podman-remote run --uidmap: makes storage/overlay go+x

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2960]
In window 1:
```
# podman varlink --timeout=0 unix:/run/podman/io.podman
```
In window 2:
```
# ls -ld /var/lib/containers/storage/overlay
drwx------. 13 root root 4096 Apr 17 09:50 /var/lib/containers/storage/overlay

# podman-remote run --uidmap 0:10000:10000 alpine true
# ls -ld /var/lib/containers/storage/overlay
drwx--x--x. 14 root root 4096 Apr 17 09:50 /var/lib/containers/storage/overlay
      ^  ^
      |  |
```
master @ a87cf6fef8f84ded410d547aa772b8f942c5f273

**Comment by edsantiago** [comment]
@giuseppe phew! This seems to be the cause of the problem I've been seeing all week.

@baude PTAL

**Comment by edsantiago** [comment]
To follow up on the IRC discussion: this does not happen with plain (non-remote, non-varlink) podman.

**Comment by baude** [comment]
confirmed as well.

**Comment by edsantiago** [comment]
UPDATE: I am now seeing this with plain podman on master:
```
# ls -ld /var/lib/containers{,/storage}                            
drwx------.  5 root root 4096 Apr 17 09:43 /var/lib/containers                 
drwx------. 11 root root 4096 Apr 17 10:25 /var/lib/containers/storage
# podman run --uidmap 0:10000:10000 alpine true
# !ls
drwx--x--x.  5 root root 4096 Apr 17 09:43 /var/lib/containers                 
drwx--x--x. 11 root root 4096 Apr 17 10:25 /var/lib/containers/storage         
```
I don't know if this is new behavior, or (more likely) screwing up something on my end when I tried this sequence two weeks ago. If anyone else can reproduce, please update title accordingly to remove the podman-remote red herring.

**Comment by rhatdan** [comment]
I think @giuseppe Made some changes to make these directories searchable, so that we would not need to go into two mount namespaces.

**Comment by rhatdan** [comment]
I think the intended permissions of these dirs is 711.

**Comment by edsantiago** [comment]
Then the [400-unprivileged-access.bats test](https://github.com/containers/libpod/blob/master/test/system/400-unprivileged-access.bats) needs to be updated, because "files accessible by other users" is exactly what it is trying to prevent. I suppose we'll have to wait for @giuseppe

**Comment by rhatdan** [comment]
That script is succeeding and you expected it to fail?

**Comment by edsantiago** [comment]
Script is failing, but now I see that my 12:44MDT comment was mistaken. The problem is /var/lib/containers/storage/**overlay** -- that's what podman-remote (and only podman-remote) is clobbering. I will update my comment. Sorry for the confusion.

**Comment by rhatdan** [comment]
podman-remote should not even know about container-storage...

**Comment by edsantiago** [comment]
My fault again: I'm conflating podman-remote with the varlink server.

**Comment by rhatdan** [comment]
So whey you run podman varlink the mode of this file changes?

**Comment by edsantiago** [comment]
See initial post (at top). I would imagine it's `podman varlink` that's doing the chmod, not actually `podman-remote`. Maybe I should refer to it as "the podman-remote ecosystem"?

**Comment by rhatdan** [comment]
Does this only happen when running a podman-remote with a --uidmap? 
And it does not happen if you just do a podman run --uidmap?

**Comment by edsantiago** [comment]
>Does this only happen when running a podman-remote with a --uidmap?
>And it does not happen if you just do a podman run --uidmap?

Correct and correct.

In case it helps, I took podman-remote slightly out of the equation:
```
# ls -ld /var/lib/containers/storage/overlay
drwx------. 9 root root 4096 Apr 30 15:03 /var/lib/containers/storage/overlay
# podman-remote create --uidmap 0:10000:10000 alpine true
ERRO[1153] unable to find flag trace                    
ERRO[1153] unable to find flag syslog                   
2e468cd63dd97e42f473b3df8e2713ee9ea6ac4ccf1a5491a1346ffff37a01b1
# !ls
drwx------. 10 root root 4096 Apr 30 15:04 /var/lib/containers/storage/overlay
```
That is, `podman-remote create` does not harm anything. Then, running varlink directly without podman-remote:
```
# varlink call unix:/run/podman/io.podman/io.podman.StartContainer '{"name":"2e468cd"}'
{
  "container": "2e468cd63dd97e42f473b3df8e2713ee9ea6ac4ccf1a5491a1346ffff37a01b1"
}
# !ls
drwx--x--x. 10 root root 4096 Apr 30 15:05 /var/lib/containers/storage/overlay
```
i.e. the `start`, run by the varlink server, is what did it.
Hope that helps narrow it down.

**Comment by giuseppe** [comment]
having 711 on `/var/lib/containers/storage/overlay` is expected when using uidmap/gidmap, as we rely on the ownership in the subdirectories.
What we have to check for is if an unprivileged user (that it is not mapped to root inside the container) can access any file/directory inside of container.  How does `ls -l /var/lib/containers/storage/overlay` look like?

**Comment by edsantiago** [comment]
EPERM, of course. However, if a nonprivileged user can guess or learn the SHA of a container storage directory:
```
esm$ touch /var/lib/containers/storage/overlay/064500df30a3ead9dca8f03a16bf2beda66eb53564d978e9d565dbedcb1bf1d7/merged/tmp/bar
esm$ ll /var/lib/containers/storage/overlay/064500df30a3ead9dca8f03a16bf2beda66eb53564d978e9d565dbedcb1bf1d7/merged/tmp
total 0
-rw-rw-r--. 1 esm  esm  0 May  1 06:32 bar
-rw-r--r--. 1 root root 0 May  1 06:32 foo
```

**Comment by edsantiago** [comment]
And of course the question that started it all: why does plain podman not change permissions? Why is it only varlink / podman-remote?

**Comment by giuseppe** [comment]
It happens when uidmap/gidmap is used, to allow other users not root to access these directories.  local/remote podman should not matter

**Comment by giuseppe** [comment]
That is strange /var/lib/containers/storage/overlay/064500df30a3ead9dca8f03a16bf2beda66eb53564d978e9d565dbedcb1bf1d7 should have 0700.  I will have to verify it

**Comment by giuseppe** [comment]
interestingly it seems to happen only with varlink?  @baude do we do anything different that can cause the directories in the storage to be created with a different permissions mask?

**Comment by edsantiago** [comment]
Oh, this is interesting: plain podman is chowning, not chmoding:
```
# ls -ld /var/lib/containers/storage/overlay
drwx------. 6 root root 4096 May  1 08:47 /var/lib/containers/storage/overlay
# podman run --uidmap 0:10000:10000 alpine true
# !ls
drwx------. 7 10000 10000 4096 May  1 08:47 /var/lib/containers/storage/overlay
              ^^^^^ ^^^^^
```
Running plain podman fixes it again:
```
# podman run alpine true
# !ls
drwx------. 9 root root 4096 May  1 08:51 /var/lib/containers/storage/overlay
```

**Comment by giuseppe** [comment]
so the problem seems to be in not correctly creating the layer directory with the correct ownership:

https://github.com/containers/storage/pull/334

this seems to solve the issue for me

**Comment by edsantiago** [comment]
Shouldn't this stay open until it gets vendored in?
