### ISSUE TITLE
podman cp - (minus): unimplemented

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#2966]
`podman cp --help` claims that a minus sign reads or writes tar on stdin/out. This would be compatible with docker. It does not work:
```
$ podman create --name foo alpine
ffe8cffa69b18c4d49eed8f52d898ffd1e049ee59ed344a7940dda0fcf264f76
$ podman cp - foo:/
Error: error evaluating symlinks "": lstat -: no such file or directory
$ podman cp foo:/ -
(creates a subdirectory named - (minus))
```
master @ a87cf6fef8f84ded410d547aa772b8f942c5f273 but AFAICT this has never worked.

**Comment by mheon** [comment]
Agree with your assessment - never been in the code, nearest I've seen. Shouldn't be that difficult, though... We have support for untarring, so we can just set input file to `/dev/stdin` and it ought to work, I think

**Comment by edsantiago** [comment]
Good thinking. I just tried that, and it looks like it'll take a little more effort:
```
$ podman cp /dev/stdin foo:/ </tmp/foo.tar
Error: error copying "/tmp/foo.tar" to "/home/esm/.local/share/containers/storage/overlay/f3025680b5ce7cde30ba2ba15d0e95eee9bfcb041b4ad30957598c0ebfdb7e8c/merged": error extracting data to "/home/esm/.local/share/containers/storage/overlay/f3025680b5ce7cde30ba2ba15d0e95eee9bfcb041b4ad30957598c0ebfdb7e8c" while copying: Error processing tar file(exit status 1): remove /merged: device or resource busy
```

**Comment by rhatdan** [comment]
@QiWang19 I thought we tested this.  Once you fix, please make sure there is a test for it.

**Comment by QiWang19** [comment]
@rhatdan No, don't know when was the minus sign description added. I'll work on this.

**Comment by edsantiago** [comment]
Seems to work, but `cp` doesn't seem to be working with volumes. Investigating; may file issue.
