### ISSUE TITLE
Using rootless podman to isolate batch system payloads

### ISSUE THREAD

**Issue by afortiorama** [containers/libpod#2986]
/kind bug

**Description**

I'm trying to use podman to submit batch system jobs. I have CentOS7.6 and I followed this recipe https://www.redhat.com/en/blog/preview-running-containers-without-root-rhel-76 and I found quite few difficulties, included the fact that the container doesn't start and the system seems to be designed to run interactively but I hope to be corrected.

1) Needs either $HOME or $NGD_DATA_HOME. I$HOME is usually defined but since we use generic accounts I was actually hoping to remove it from the batch nodes.
2) runroot path+filename has a limit of 50 characters, some of our batch system paths are much longer than that. True I might try to use ./ but it usually isn't a recommended strategy.
3) I try to have all the files produced under the directory created by the batch system so it can be cleaned up when the job ends. This means use a long command line with --root --runroot --tmpdir.
4) It is not clear why 65535 UIDs are needed for each user and this number cannot be determined by the admin in subuid/subgid. As a matter of fact I would argue that in my case create the container, run the payload, end the container, I only need 1. 

Even setting all this, the container still fails to run in a batch system job. The same command runs interactively though. 

**Steps to reproduce the issue:**

Not sure it is possible to reproduce it without a batch system, but below is the script I run and I put the diffrence between env var below. I've also attached the debug outputof podman command

[podman-debug.txt](https://github.com/containers/libpod/files/3104192/podman-debug.txt)

```
#!/bin/bash -l
echo '##############'
hostname 
echo '##############'
whoami
echo '##############'
env |sort
echo "Executing podman as $USER"
podman --version 
podman info --debug
podman  --root $PWD/podman/root --tmpdir $PWD/podman/tmp --log-level debug run --rm -it docker://centos:7 echo 'Hello World'
sleep 30
```

**Describe the results you received:**
In batch
```
-bash-4.2$ podman  --root $PWD/podman/root --tmpdir $PWD/podman/tmp --runroot $PWD/podman/root --log-level debug run --rm -it docker://centos:7 echo 'Hello World'
[...]
time="2019-04-22T16:56:43+01:00" level=error msg="container create failed: container_linux.go:336: starting container process caused "process_linux.go:279: running exec setns process\
 for init caused \"exit status 10\""
: internal libpod error"
```
**Describe the results you expected:**
Interactively
```
-bash-4.2$ podman  --root $PWD/podman/root --tmpdir $PWD/podman/tmp --runroot $PWD/podman/root --log-level error run --rm -it docker://centos:7 echo 'Hello World'
Hello World
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 0.12.1.2
```

**Output of `podman info --debug`:**

```
podman version 0.12.1.2
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 0.12.1.2
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-0.12.1.2-2.git9551f6b.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: b909c9e1a3e8f14d5694a118fb9c0c0325a31d4f-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 18364760064
  MemTotal: 50465587200
  OCIRuntime:
    package: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 68604321792
  SwapTotal: 68719468544
  arch: amd64
  cpus: 24
  hostname: wn5917240.in.tier2.hep.manchester.ac.uk
  kernel: 3.10.0-957.5.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 843h 0m 16.04s (Approximately 35.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /scratch/condor_pool/condor/dir_29741/IELNDmiOncunnKnSmpc7AjQqtKZXhpABFKDmysqRDmABFKDm82oFQo/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /scratch/condor_pool/condor/dir_29741/user/5016
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is the difference between the env vars interactive and in batch bar some batch system specific ones
```
diff env-var-batch env-var-interactive |grep -v CONDOR|grep -v JOBFEATURE| grep -v HOSTNAME
1d0
< BATCH_SYSTEM=HTCondor
3,14d1
< _CHIRP_DELAYED_UPDATE_PREFIX=Chirp
20,22c7,8
< HOME=/scratch/condor_pool/condor/dir_19365
---
> HOME=/scratch/pools_home/atlas001
27a14
> LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
31d17
< OMP_NUM_THREADS=1
33c19,20
< PWD=/scratch/condor_pool/condor/dir_19365
---
> PWD=/scratch/pools_home/atlas001
> SHELL=/bin/bash
36,38c23,26
< TEMP=/scratch/condor_pool/condor/dir_19365
< TMPDIR=/scratch/condor_pool/condor/dir_19365
< TMP=/scratch/condor_pool/condor/dir_19365
---
> SSH_CLIENT=2001:630:22:d0ff:5054:ff:fe66:fe7f 35914 22
> SSH_CONNECTION=2001:630:22:d0ff:5054:ff:fe66:fe7f 35914 2001:630:22:d0ff:230:48ff:fef5:1e44 22
> SSH_TTY=/dev/pts/1
> TERM=xterm-256color
39a28,29
> XDG_RUNTIME_DIR=/run/user/5000
> XDG_SESSION_ID=6182
```

**Comment by mheon** [comment]
Answering specifically about 65536 UIDs: in upstream Podman (and in the upcoming 1.3.0 release), we allow running with a single UID, but this will cause issues with many common images, which often include files with non-0 UIDs.

For 65536 specifically, though, there is no real requirement for it, and if you modify `/etc/subuid` and `/etc/subgid` I would expect other numbers of UIDs and GIDs to work.

**Comment by mheon** [comment]
For runroot path: that's a kernel limitation - we need a place to put Unix sockets, with (at least most of) a container UUID in them, and the max path length on a Unix socket is 128 characters. We strongly recommend `runroot` be placed somewhere in `/run`, `/tmp`, `/var/run` (or some other tmpfs mount). I can understand why it would be desirable to wrap all contents of a container in the same directory for batch jobs, I don't believe we can help you here.

**Comment by afortiorama** [comment]
Hi @mheon ,

> there is no real requirement for it, and if you modify /etc/subuid and /etc/subgid I would expect other numbers of UIDs and GIDs to work.

the version of podman I'm using says that it needs 65535 UIDs.

```
-bash-4.2$ grep atlas001 /etc/subuid
atlas001:10000:65
-bash-4.2$ podman  --root $PWD/podman/root --tmpdir $PWD/podman/tmp --runroot $PWD/podman/root --log-level error run --rm -it docker://centos:7 echo 'Hello World'
not enough UIDs available for the user, at least 65535 are needed
cannot read argv: Success
```

**Comment by mheon** [comment]
Hm. That sounds like it ought to be fixed.
@giuseppe Now that we allow single mappings, we ought to allow arbitrary-sized mappings as well, I think?

**Comment by afortiorama** [comment]
This might be another clue

I removed the options and if I become atlas001 with su -l atlas001 rather than ssh into the node as atlas001 I get this

```
-bash-4.2$ podman --log-level debug  run --rm -it docker://centos:7 echo 'Hello World' 
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /scratch/pools_home/atlas001/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /scratch/pools_home/atlas001/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/5000                
DEBU[0000] Using static dir /scratch/pools_home/atlas001/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/5000/libpod/tmp      
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
ERRO[0000] error creating libpod runtime: error creating tmpdir /run/user/5000/libpod/tmp: mkdir /run/user/5000: permission denied 
```
while there is something else that is problematic when I try to delete ~/.local I get permission denied even though the files belong to atlas001. To delete I have to change permissions to 755 recursively but even then I cannot delete everything because this directory and two subdirs have the UID of the user inside the container. I believe this shouldn't happen but I might be wrong.

```
ls -l /scratch/pools_home/atlas001/.local/share/containers/storage/vfs/dir/d69483a6face4499acb974449d1303591fcbb5cdce5420f36f8a6607bda11854/run/systemd/
total 4
drwxr-xr-x 4 10191 10191 4096 Mar  5 17:36 netif

```

**Comment by mheon** [comment]
The differing UIDs is expected - you need to use `podman` to remove the containers/images.

Also, you're using the `VFS` storage driver, instead of `fuse-overlayfs`, which can result in significantly increased disk usage.

The `/run/user/` missing is expected when you use `su` - systemd creates that directory on a user logging in, but it doesn't recognize the use of `sudo` or `su` as a login

**Comment by afortiorama** [comment]
So I have to run podman rm --all and podman rmi --all at the end of the job?

I'm using what I have on  CentOS7. Even the fedora repo reccomended to install a more recent version of shadow-utils doesn't contain fuse-overlayfs. 

/run/user permissions are another reason to use another location for runroot then.

**Comment by mheon** [comment]
If you're looking to immediately remove the directories in question, we definitely recommend an `rm --all --force` and `rmi --all --force` before doing so to clear UIDs and GIDs. Once `podman unshare` lands in 1.3.0 you will also be able to use that to spawn a shell that has full permissions to work with these UIDs, which could also be used to remove the directory in question.

**Comment by giuseppe** [comment]
> @giuseppe Now that we allow single mappings, we ought to allow arbitrary-sized mappings as well, I think?

yes, this limitation was dropped and now we allow to run with just one user mapped in the namespace, as you said this can break some images.

**Comment by afortiorama** [comment]
Hi,

I fear that with all the updates the main problem got a bit lost. When running in a batch system the container fails due to the error below which is user name spaces related and due to the fact that the container makes use of login functionalities.

```
-bash-4.2$ podman  --root $PWD/podman/root --tmpdir $PWD/podman/tmp --runroot $PWD/podman/root --log-level debug run --rm -it docker://centos:7 echo 'Hello World'
[...]
time="2019-04-22T16:56:43+01:00" level=error msg="container create failed: container_linux.go:336: starting container process caused "process_linux.go:279: running exec setns process\
 for init caused \"exit status 10\""
: internal libpod error"
```

**Comment by lukasheinrich** [comment]
what is the login functionality that is used? Is it only XDG_*  environment variables? I guess those are used to store image and container state, but perhaps the location of those could be made configurable such that non-login users can be used?

**Comment by afortiorama** [comment]
@lukasheinrich the use of /run/user/<UID> is a login feature. But even setting $HOME and $NGD_DATA_HOME, and overriding the /run/user/<UID> location in the command line (see above) it still fails. I'm not sure why. I assume it is some other more buried login feature since the same command with the same overrides works with a login shell.

**Comment by afortiorama** [comment]
runroot path+filename with a limit of 50 characters is also another problem. We have quite long path names on the WNs.

**Comment by rhatdan** [comment]
@mheon Answered the 50 char limit question above.

**Comment by afortiorama** [comment]
@rhatdan yes, he did. We will have to use relative paths under the job dir to overcome this problem.

**Comment by lukasheinrich** [comment]
@rhatdan -- any guesses what the login-shell dependency could be?

**Comment by rhatdan** [comment]
@lukasheinrich Don't understand the question?

**Comment by lukasheinrich** [comment]
according to @afortiorama podman does not work when the process is not launched from within a login shell.

**Comment by mheon** [comment]
Could be certain environment variables that we expect to be defined? Rootless in particular wants a few environment variables to be present

**Comment by afortiorama** [comment]
Could you let us know which variables? 

there are only two obvious ones are in the top post $HOME or $NGD_DATA_HOME and I set them both again to point to the job area. It'd be really useful to have a batch mode or a batch option that allows to run without switching or overriding all these things manually.

**Comment by giuseppe** [comment]
@afortiorama it should be enough to set `XDG_RUNTIME_DIR`.  Usually its value is `/run/user/$UID`

**Comment by afortiorama** [comment]
@giuseppe I thought that was overridden with --runroot isn't that the case? I'll try also setting the variable.

**Comment by rhatdan** [comment]
Yes I think this is more about environment variables that are setup by a normal login session.Rather then simply doing a service as root and then su/sudo to non root before running podman.  If the scripts setup the runtime/tmp directories used by podman for these scenarios, then it would work.

**Comment by giuseppe** [comment]
can you try with podman from master?  It should work fine without setting any env variable (just be sure it is not set to something we cannot write to).

Once the batch mode terminated, be sure to cleanup everything with:

```
$ rm /dev/shm/libpod_rootless_lock_$(id -u)
$ podman unshare sh -c 'kill -9 `cat $XDG_RUNTIME_DIR/libpod/pause.pid`; rm -rf $PWD/podman $XDG_RUNTIME_DIR/libpod'
```

we might need to add a command that simplies this task

**Comment by rhatdan** [comment]
@afortiorama Did @giuseppe solution work for you?  Would you like futher enhancments?

**Comment by vrothberg** [comment]
Closing due to longer inactivity. Feel free to reopen.

**Comment by japita-se** [comment]
Still unresolved here

```
$ podman images
Error: could not get runtime: error generating default config from memory: cannot mkdir /run/user/0/libpod: mkdir /run/user/0/libpod: permission denied
[developer@algo simu]$ 
```

**Comment by giuseppe** [comment]
> $ podman images
> Error: could not get runtime: error generating default config from memory: cannot mkdir /run/user/0/libpod: mkdir /run/user/0/libpod: permission denied

looks like the wrong value for the `XDG_RUNTIME_DIR` env variable is set.  Could you show the output for `printenv XDG_RUNTIME_DIR`?  You may need to override or unset it
