### ISSUE TITLE
nework=host "is therefore considered insecure" but bridged -p does not work that great

### ISSUE THREAD

**Issue by caffeinejolt** [containers/libpod#2987]
podman-0.12.1.2-2.git9551f6b.el7.centos.x86_64
centos-release-7-6.1810.2.el7.centos.x86_64

running as root with stock RPM config values in /etc/containers, 

--network=host works as expected, but utilizing -p to publish a port does not work (even with iptables starting from a blank state with stock sysctl networking values).... and really, podman is kind of new to me and I am not all the fond of the idea that it is updating iptables rules along with modifying networking sysctl values on the host system.  Its newer software and subject to changes... us early adopters have to choose where to be cautious about future breakage.  I am sure I could hack things into a working state with iptables eventually - it just doesn't feel like a good way to go.

But of course.. "considered insecure" with --network=host isn't great either.  I'd like to better understand how insecure... running basically any program is insecure to some degree.   If everything is locked down in SELinux "container_" land, what additional risks does --network=host impose?  Obviously container processes can bind to the host ports and open connections as the host - those risks are assumed.  The man page states "host mode gives the container full access to local system services such as D-bus and is therefore considered insecure" - I guess I am trying to understand what "full access to local system services" means - that sure sounds like a lot of access!  Does it really mean "full access to network system services" as in the ability to connect to network services on the host (since I would be fine with that)?  Trying to understand the security risks I am potentially exposing myself by avoiding the risks of having podman alter iptables/sysctl-network.

**Comment by mheon** [comment]
Are you trying to use `-p` with `--net=host`? Or does `-p` not work with normal networking, but `--net=host` works?

**Comment by mheon** [comment]
`--net=host` gives the container full access to the host network. It can bind any port on the host, and connect to any port on the host (including localhost). It will use the same IP address(es) as the host throughout (will not have a separate IP, as it would using a network namespace).

On IPTables - our IPTables changes should be entirely self-contained. I think we modify only one sysctl (enable IP forwarding), and then add a set of rules to masquerade traffic to/from the created network bridge (plus additional rules for port ranges).

**Comment by mheon** [comment]
(I wouldn't consider our networking for "early adopters" either - we're using CNI, which has been battle-tested with Kubernetes deployments for years)

**Comment by caffeinejolt** [comment]
> 
> 
> Are you trying to use `-p` with `--net=host`? Or does `-p` not work with normal networking, but `--net=host` works?

The 2 scenarios are 1) just "--net=host" (works) and 2) "-p 80" (does not work)

I do not mix -p with --net=host since I don't think that would make sense.

**Comment by caffeinejolt** [comment]
> 
> 
> (I wouldn't consider our networking for "early adopters" either - we're using CNI, which has been battle-tested with Kubernetes deployments for years)

Understood.  I guess I should not have written that - I think I was just assuming -p would "just work" and when it didn't I started second guessing things.

**Comment by mheon** [comment]
We've seen some bugs around it before, and this sounds like it could be another one.

**Comment by baude** [comment]
You are using an RPM that is over 1 year old based on the podman versioning. 
`podman-0.12.1.2-2.git9551f6b.el7.centos.x86_64` perhaps an upgrade should be considered?

**Comment by mheon** [comment]
That's the latest in CentOS/RHEL7, @baude

**Comment by baude** [comment]
yes, i misread the version ... my apologies ... so lets start with what "does not work" means.  How about a replicator of some sort?

**Comment by caffeinejolt** [comment]
I did not realize the CentOS7 extras yum repo was that far behind - maybe RH upstream is being cautious due to the 1.x bump - I just checked the release history for first time.

By "does not work", that is limited strictly, I think, to network forwarding - I can connect to the published port on the address listed in iptables -L -n 

Chain CNI-FORWARD (1 references)                                                             
target     prot opt source               destination                                         
CNI-ADMIN  all  --  0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
ACCEPT     all  --  0.0.0.0/0            10.88.0.23           ctstate RELATED,ESTABLISHED    
ACCEPT     all  --  10.88.0.23           0.0.0.0/0                                           

In other words - while on the host, I can open a connection to 10.88.0.23:published-port   Its the forwarding that port on the host to that port on the container where things do not seem to be working.  I tried hostIP:hostPort:containerPort, hostPort:containerPort, and containerPort syntax combinations.

One semi-unique thing to my usage may be that I use the "--rootfs  /path/to/container-root --read-only --rm=true" since I curate my own image/root outside of podman-build/buildah.  This is only due to the fact that I am migrating away from systemd-nspawn and am still using old bash scripts to build the image/rootfs.  I also run systemd inside the container for things like zombie reaping etc. - not sure to what extent that is even required anymore in podman/runc etc.  but I also use systemd to set things like CapabilityBoundingSet and NoNewPrivileges for launched processes, so will probably be keeping systemd in there for the time being.  In any case... I don't think this *should* matter, but because it probably deviates from the norm of keeping everything in /var/lib/container and not running systemd in the container, I am pointing it out.

I also run a fairly restrictive set of iptables rules by default, along with restricting some sysctl networking defaults...  but I backed those all out and killed any iptables rules and even rebooted to isolate any impact they could have.  I have ipsets loaded with some values, but cannot imagine that would impact forwarding - suppose I could back those out as well.

Its not a pressing issue or anything - I can work around.  I was mostly just trying to offer feedback and was somewhat curious on the security implications --net=host.

**Comment by caffeinejolt** [comment]
--net=host really seems to be a better fit for me, but I would like to help out on this....  So, literally zero iptables rules got set related to port forwarding.  I can see in pkg/firewall we basically have iptables and firewalld - and firewalld is uninstalled on the host...

Looking at the code, my guess here is that isFirewalldRunning() is the culprit.  It might be useful to allow the user to specify the firewall type either in a config or a cli option.

**Comment by caffeinejolt** [comment]
Maybe something super simple like modding runtime.go - backendType := os.Getenv("FIREWALL_TYPE")

Since at least that allows the user to decide instead of dbus.
