### ISSUE TITLE
podman stop fails

### ISSUE THREAD

**Issue by matthiasclasen** [containers/libpod#2993]
Seeing this in a recent rawhide (podman-1.3.0-17.dev.gitbf5ffda.fc31.x86_64):

```
$ sudo podman stop --all
Error: can only stop created, running, or stopped containers. 4ce604a830f62a37ad71eca9b43c78cb2d50d96598e14711032c6d238dd522fb in state configured: container state improper
```

If this is caused by my containers being created by a previous podman release, may I suggest that your testsuite needs to cover this case: create a container with an older version, and verify that the tested podman can handle it.

These are pets, so I'm not prepared to shoot them everytime you push a new podman into rawhide...

**Comment by mheon** [comment]
Pretty sure this isn't related to the upgrade - we just regressed on how we choose containers for `podman stop` (probably happened when we migrated to remote).

@baude @jwhonce We're using `GetContainersByContext()` to retrieve all containers to act on for `stop`, but we're not filtering the results to only running containers, so we try and stop containers that are only configured.

**Comment by mheon** [comment]
Potential solution: make `stop --all` ignore not only ErrCtrStopped but also ErrCtrStateInvalid

**Comment by mheon** [comment]
#2994 should fix
