### ISSUE TITLE
[RFE] different vfs storage strategy

### ISSUE THREAD

**Issue by flx42** [containers/libpod#2999]
Similar to #2868, but re-instancing for visibility, this is for a use case similar to #2986

I know this approach is also the one taken by docker with `vfs`, but the disk footprint makes it impractical for large images. I have a particular image that takes 218GB for a 5.5GB rootfs. I would gladly trade a longer startup time for the ability to store more than 5 images :)

Outside podman, a straightforward way to do that is:
- `pull`: skopeo saves all compressed layers to a single directory (for caching)
- `run`: umoci unpacks the right layers in order and handles whiteouts to build the final rootfs.

The disk size is now `sum(compress(layers)) + sum(layers)` instead of `sum(layers[:1]) + sum(layers[:2]) + sum(layers[:3]) + ... + sum(layers[:n])`.
It's unfortunate that we don't have a way to achieve that natively in `podman`, we would have to use other tools and then do `podman run --rootfs`.

The startup time does take a hit, which could be mitigated by:
- Not using the Go standard library for decompression (i.e. pipe to `pigz` or just `gzip`)
- Storing uncompressed layer tar files, this does require some additional bookkeeping to keep layer caching functional.

Regarding fuse-overlay: it's not available everywhere, and I don't want the overhead.

Thoughts? Feel free to close if you never plan to support this feature.

**Comment by mheon** [comment]
@nalind PTAL
