### ISSUE TITLE
mount host files and change selinux label of those files inside the container

### ISSUE THREAD

**Issue by caffeinejolt** [containers/libpod#3007]
/kind feature

*Feature request... making everything work with selinux set to enforcing can be a PITA (or at least it is for me a lot of the time).  However, combining selinux and containers can provide a lot of benefit in terms of security/isolation (some of us use them for this combination - portability being a side-benefit).  It would be nice if we could pass a selinux context option to --volume (or something like that) and it would magically pull that mount into the container with the selinux labels set to whatever we specified (i.e. container_file_t etc.).

I cannot seem to get this to work with bind mounts (maybe there is a way though), but an overlay mount can do this in my brief testing:

mount -t overlay overlay -olowerdir=lower,upperdir=upper,workdir=work,ro,context="system_u:object_r:container_file_t:s0" merged

In above example, lower is the source directory on the host system and merged is in the container and now has everything labelled container_file_t (so that the container can access it).

This might only be a good idea for read-only scenarios since otherwise you would end up with stuff in upper that has to be dealt with - but maybe that can be a tmpfs.

Possible scenario where this could be useful: there is a bunch of web content on a dev server with a different label (maybe httpd_sys_content_t) and everything is setup to work with that label - but we want nginx to run in a container and have read-only access to that content - but really nothing else on the system.  In this case it is easy to get that working with this feature compared to messing with /etc/selinux (where a lot of people just say screw it and setenforce 0).

**Comment by mheon** [comment]
Do the existing `:z` and `:Z` options (relabel so content in the volume mount can be accessed in the container) suffice? They don't let you explicitly specify a mount label, but they will match the content in question to the container's mount label.

Though these might not work out well with `--rootfs` because we usually allocate container labels through containers/storage when we configure containers based on an image... @rhatdan maybe a way to explicit set a container's SELinux label at creation time?

**Comment by caffeinejolt** [comment]
Great point!  For some reason, when I read about those earlier - I somehow inferred that they changed the labels in the source content to make that work - but it would make way more sense if they just changed how the labels were seen in the container.  I will try that out and report back it that works with --rootfs

**Comment by rhatdan** [comment]
No you would not want to z or Z in his description, since apache would loose access. I kind of like taking advantage of overlay for this.  Basically setting up an overlay read/only volume with a context label.
The context label would be private to the container, I don't want the user specifying a label.  Mount label would be fine.

--mount overlay:/var/lib/www:/var/lib/www 
Would mount /var/lib/www as readonly via overlay.

**Comment by rhatdan** [comment]
@caffeinejolt they do change the source.

**Comment by rhatdan** [comment]
@rhvgoyal WDYT?

**Comment by caffeinejolt** [comment]
> @caffeinejolt they do change the source.
gotcha - well in that case - this feature could help cut down on the "setenforce 0" movement

**Comment by rhatdan** [comment]
mount -t overlay overlay -o 'nosuid,nodev,noexec,relatime,context="system_u:object_r:container_file_t:s0:c342,c555",lowerdir=/var/www:/tmp/work' /tmp/merged
ls -lZ /tmp/merged/
total 0
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c342,c555  6 Apr 17 03:43 cgi-bin
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c342,c555  6 Apr 17 03:43 html
d---------. 2 root root system_u:object_r:container_file_t:s0:c342,c555 40 Apr 24 16:50 work

This works, overlay requires two directories, but we could just create an empty directory to merge with the source and it would mount with the SELinux label.

**Comment by rhvgoyal** [comment]
For this to work, overlay mounter in container will need atleast read access to labels on lower/. If container already has read access, what's the point of using another overlay mount to change to another set of readable labels.

Using overlay only to transform effective selinux lablels, is definitely not the intended usage of overlayfs.

**Comment by rhatdan** [comment]
Ah yes, so much for that grand plan.

**Comment by rhatdan** [comment]
@caffeinejolt Best we can right now is a tool called udica.

https://github.com/containers/udica

It allows you to create a custom type based on the container you create and then you can run the container with that type and it will give you access.

**Comment by caffeinejolt** [comment]
Good point - admittedly, my plan was to do the overlay mount outside of podman (visible to the host) and then pass the overlay mount to podman as a volume/bind mount.  I realize its not the intended purpose of overlayfs - but, I do it for NFS (i.e. specify selinux context on nfs client mount) and it can be done when mounting devices as well so its not completely odd.

**Comment by caffeinejolt** [comment]
> 
> 
> @caffeinejolt Best we can right now is a tool called udica.
> 
> https://github.com/containers/udica
> 
> It allows you to create a custom type based on the container you create and then you can run the container with that type and it will give you access.

Thanks!  Will check that out.

**Comment by rhvgoyal** [comment]
But if mounter is outside container, then mounter can setup overlay and then bind mount that overlay into container.

**Comment by caffeinejolt** [comment]
> 
> 
> But if mounter is outside container, then mounter can setup overlay and then bind mount that overlay into container.

Right - that is what I was doing - and what resulted in the idea to post a feature request.  Just an issue if people are ok with the mount being visible on the host.... fine by me for my use.

**Comment by rhatdan** [comment]
But as Vivek pointed out this will only work if the content is readable by the container_t process.
If you try to overlay mount some content from your home dir, SELinux should block the read access on the files even if you specify a context mount.

**Comment by caffeinejolt** [comment]
> But as Vivek pointed out this will only work if the content is readable by the container_t process.
> If you try to overlay mount some content from your home dir, SELinux should block the read access on the files even if you specify a context mount.

Confirmed - Permission denied - sigh

**Comment by baude** [comment]
@rhatdan what should we do here?

**Comment by rhatdan** [comment]
I am working on overlay mounts for podman. They currently exists in podman build but not podman run yet.

**Comment by rhatdan** [comment]
Even though we are going to add overlay mounts, this will not fix the issue here. Only solution is to change the label on disk.
