### ISSUE TITLE
Cannot Exec a Command When a Container is in the Exited State

### ISSUE THREAD

**Issue by fatherlinux** [containers/libpod#3020]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Basically, I realized that as I tried to demonstrate the creation of a container...

1. Pull/Expand/Cache Image
2. Create config.json
3. Run container with podman

...there is no way to stop between two and three. This led me to a google search and I found this:

https://forums.docker.com/t/run-command-in-stopped-container/343/2

Which led me to believe that I am not the only human being to find it counter intuitive that you cannot restart a container, then exec in if the initial command given in CMD is not something (aka top, bash connected to a terminal, httpd -X, etc) that makes the container long lived and doesn't detach (because that will cause the container to exit. 

**Steps to reproduce the issue:**

1. podman create -dt quay.io/fatherlinux/on-off-container

2. "podman ps -l" will show exited

3. podman exec -it on-off-container bash

3. Will fail

Also, interactive demo with work around here:

https://www.katacoda.com/fatherlinux/courses/subsystems/container-internals-lab-2-0-part-4

And, code here:

https://github.com/fatherlinux/learn-katacoda/blob/master/subsystems/container-internals-lab-2-0-part-4/02-create-container.md

**Describe the results you received:**

Counterintuitively, the exec command fails. The problem is, I think it's a byproduct of the underlying component architecture, not intuitive for a user who believes the "user space" construction of the "container" is still in the engine. The storage is there. The config.json is there. The namespace may even be constructed with runc init, yet, you can't pass a command into it. 

**Describe the results you expected:**

It would be a nice to have if the command passed to the exec just "got run" in the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

I "think" this is a byproduct of the way the docker daemon and runc were split up. Docker behaves exactly this way as well. I think this has to do with "runc start" and "runc exec"

I think the fix could be to have an if statement that if the container is not running, to run the CMD, and if that exists, "runc run" the exec command instead. This "breaks" the paradigm of the lower level pieces, but is expected from a higher level user which knows nothing of how these things all interact.

This may even involve hacking the Cmd in the config.json.

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: d88bb0e63cb70f9787a8e410716924f380af361f'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 3387252736
  MemTotal: 4133814272
  OCIRuntime:
    package: runc-1.0.0-85.dev.gitdd22a84.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 1d3f73d4086533a858613bc4b6af2b5e882f4730
      spec: 1.0.1-dev
  SwapFree: 4273991680
  SwapTotal: 4273991680
  arch: amd64
  cpus: 2
  hostname: fedora.dc2.crunchtools.com
  kernel: 5.0.8-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 54.49s
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 22
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

on Fedora 29 box, but I don't think the version matters.

**Comment by fatherlinux** [comment]
Also, it would make sense if you could not "exec" after a "podman rm" because that is essentially telling the container engine to "delete the overlay layer and config.json"

**Comment by mheon** [comment]
I think we need the work from @haircommander on conmon exec to get this in. Fortunately, he's working on that now.

Once we have conmon instances for exec sessions, each of them able to fire off an exit command to clean up, that will make things much easier. Right now, it's hard to keep track of what exec sessions are running in a container, which makes shutting down when exec sessions are going hard.

We would need to transition the container from 'exited' to 'created' to run an exec session (runc needs to know about the container to exec into it), but that's not really that big of a deal.

Also, this might warrant a `podman kill --all` or similar, to stop processes in the container even though PID1 in the container isn't running.

**Comment by mheon** [comment]
There is one other joker in the deck here - does runc/crun/Kata support doing this (exec on a container that's not running?)

**Comment by haircommander** [comment]
@mheon @fatherlinux I tried this out with conmon exec, and I'm pretty sure it's not allowed on the runtime side (you can't exec into a container that isn't running)

**Comment by rhatdan** [comment]
I agree you can not exec into a container that is not running.  We used to have this feature in atomic, but I think it should be scripted and not built into podman directly.
