### ISSUE TITLE
Please publish varlink-enabled podman for Ubuntu

### ISSUE THREAD

**Issue by EricHripko** [containers/libpod#3027]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Current builds of `podman` don't seem to have `varlink` build tag. This leads to `podman varlink` command being missing. Could you start publishing varlink-enabled `podman` in projectatomic repos?

**Steps to reproduce the issue:**

1. `apt-get install podman`

2. `podman varlink unix:/run/podman/io.podman`

**Describe the results you received:**
An error message saying:
`Error: unrecognized command 'podman varlink'`

**Describe the results you expected:**
varlink interface to be started up.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A.

**Output of `podman version`:**

```
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.0-dev
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 7116824576
  MemTotal: 8363900928
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: host
  kernel: 4.15.0-47-generic
  os: linux
  rootless: false
  uptime: 387h 25m 49.85s (Approximately 16.12 days)
insecure registries:
  registries: []
registries:
  registries: []
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by mheon** [comment]
This is via the Projectatomic PPA, right?
@lsm5 PTAL

**Comment by EricHripko** [comment]
Yes, that's the one

**Comment by baude** [comment]
@lsm5 are we good here?

**Comment by towe75** [comment]
I'd like to bump this one. 
The ubuntu version 1.4.0 from the Projectatomic PPA is still lacking varlib support.

**Comment by lsm5** [comment]
@towe75 @EricHripko I'll get the libvarlink package on the ppa next week. So please hold on a little longer. I added v1.4.3 to the ppa btw.

**Comment by baude** [comment]
@lsm5 ping/poke

**Comment by towe75** [comment]
@lsm5 , @baude  is there a ubuntu specific show-stopper? I'm not a packaging expert but i work mostly on ubuntu machines. Can i test/support anything?

**Comment by mheon** [comment]
I think our biggest issue is getting libvarlink itself packaged up

**Comment by towe75** [comment]
Question 1: what's the challenge (did not look at libvarlink, yet)? I'm working a lot with C-ish projects, so maybe i can help something.

Question 2: Is it a necessary dependency? Podman, because of go, will surely not depend on it, same for systemd. I understand that it would be nice to have the varlink cli command for testing purposes, but otherwise i can not see the relationship. Possibly i am wrong, though.

**Comment by EricHripko** [comment]
Yeah, https://github.com/varlink/go doesn't seem to use any `cgo`, so it wouldn't use `libvarlink`. That shouldn't be a blocker 🙂

**Comment by baude** [comment]
the challenge of not having libvarlink on ubuntu is two fold:

1. when using a remote-client and the bridge technique, connections will fail because libvarlink is **required**.
2. the varlink util to debug connections is not available.

**Comment by towe75** [comment]
IC. Coming back to libvarlink: why is it a big issue to getting it packed up? I assume it would be published into the very same projectatomic PPA?

**Comment by lsm5** [comment]
> IC. Coming back to libvarlink: why is it a big issue to getting it packed up? I assume it would be published into the very same projectatomic PPA?

1. I'm still setting up autobuild pipelines for ubuntu versions, done with 18.04 and 19.04, in the middle of 16.04 atm.

2. RE: libvarlink deb, I haven't been able to get it built yet, the last few times I tried some days back. I'll revisit that soon as I get the chance, unless you have the deb packaging files ready that I could reuse.

**Comment by lsm5** [comment]
@EricHripko @towe75 varlink enabled packages are just about getting published to ppa for 19.04 and 18.04. PTAL..

**Comment by lsm5** [comment]
should be ready now ..

**Comment by baude** [comment]
closing then ... re-open if a problem arises.
