### ISSUE TITLE
Improve rootless setup experience for arch based systems

### ISSUE THREAD

**Issue by karfau** [containers/libpod#3030]
/kind feature

**Description**
To get podman running on a newly setup manjaro system you need to follow the following instructions:
https://wiki.archlinux.org/index.php/Linux_Containers#Enable_support_to_run_unprivileged_containers_(optional)

Maybe this could all be wrapped into an (AUR?) package (e.g. named something like podman-rootless), so it is easier to find for people new to this level of details regarding containers.

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12.1
Built:              Tue Apr  2 20:01:51 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.1
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version , commit: 8fba206232c249a8fc4e2fac1469fb2fddbf5cf7'
  Distribution:
    distribution: manjaro
    version: unknown
  MemFree: 11468468224
  MemTotal: 16691896320
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7
      commit: 69ae5da6afdcaaf38285a10b36f362e41cb298d6
      spec: 1.0.1-dev
  SwapFree: 23367864320
  SwapTotal: 24207417344
  arch: amd64
  cpus: 8
  hostname: karfau-tux-19
  kernel: 4.19.34-1-MANJARO
  os: linux
  rootless: true
  uptime: 39h 36m 11.8s (Approximately 1.62 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/karfau/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/karfau/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1000
  VolumePath: /home/karfau/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
We would need you or someone else to volunteer to maintain the AUR package, if you want to udpate the install.md for information on arch, please open a PR.

**Comment by karfau** [comment]
> We would need you or someone else to volunteer to maintain the AUR package

Yes, that was also my idea.
I have no experience in this topic and I'm asking myself if this will be something that is still in flux a lot and could easily get out of hands regarding maintenance effort. (Changes could come from arch, kernel, podman, ...?)

If it is likely that such a package it will break on a regular basis I'm quite sure I'll **not** be able to maintain it on my own in addition to getting used to the whole packaging part.

Any opinions?

**Comment by rhatdan** [comment]
Well I have no experience in packaging on Arch, no experience in Arch at all.  Podman releases probably ever 6 weeks or so now, so you would need to do some work when this happens.  (Potentially more if CVE's happen).  But the turn should not be that much.

We would obviously help out on Podman issues that arise.   I would doubt the Kernel or other parts of Arch would cause much problems.  You might be able to ask other Arch packagers to help out and get a second maintainer.

**Comment by karfau** [comment]
OK, I don't know any other arch packagers ...
It sounds doable but I hope creating this issue with the idea in it will attract somebody with more knowledge and some time to pick it up.
Currently it is not a very high prio for me, sorry.
You can decide if it is worth keeping this issue open for the purpose of this or if it is a better idea to close it.

**Comment by baude** [comment]
closing due to interest
