### ISSUE TITLE
Named volume not mounted on container start

### ISSUE THREAD

**Issue by bka2004** [containers/libpod#3046]
/kind bug

I have a problem with named volumes where I'm not sure if it's a bug or me
doing something wrong.

When starting a container with a named volume, the content of that volume is not mounted
and therefore not visible in the container.

I created a named volume which looks like this:

```
[root@frogstar ~]# podman volume inspect FileServerData
[
    {
        "name": "FileServerData",
        "labels": {},
        "mountPoint": "/var/lib/containers/storage/volumes/FileServerData/_data",
        "driver": "local",
        "options": {
            "device": "/dev/md127p1",
            "type": "xfs"
        },
        "scope": "local"
    }
]
```

Then I start a container like this:
`podman run -d -p 139:139 -p 445:445 --volume FileServerData:/shares frogstar_samba`

The container is running, but /var/lib/containers/storage/volumes/FileServerData/_data
is still empty, "mount" shows that /dev/md127p1 is not mounted, as I would expect.

With docker, the same way lead to a filled /shares directory in the container,
so I wonder if more steps are needed with podman, or what else could be wrong.

-----------------------------------------------------------------------------------------------

Related info:
[root@frogstar ~]# podman --version
podman version 1.2.0

[root@frogstar ~]# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: d88bb0e63cb70f9787a8e410716924f380af361f'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 26751668224
  MemTotal: 33493536768
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 16814960640
  SwapTotal: 16814960640
  arch: amd64
  cpus: 6
  hostname: frogstar.fritz.box
  kernel: 5.0.7-200.fc29.x86_64
  os: linux
  rootless: false
  uptime: 96h 58m 34.97s (Approximately 4.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 16
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

**Comment by rhatdan** [comment]
This is a bug and we have a related problem with nfs.  
I have a PR here https://github.com/containers/libpod/pull/2415 that handles this for NFS, but @mheon is working this into the new rewrite of the volume handling.

**Comment by mheon** [comment]
Working on code for this now. Support for XFS volume may take a little longer - I'm targetting tmpfs first, then NFS/XFS/others. Hopefully all will be available in Podman 1.4

**Comment by baude** [comment]
@mheon where do we stand here?

**Comment by mheon** [comment]
Podman inspect fixes took priority. Hopefully next sprint I'll get this in.

**Comment by mheon** [comment]
Relabelling as this is a new feature (support for non-directory local volumes)

**Comment by mheon** [comment]
#3931 to fix

**Comment by bka2004** [comment]
Is this really implemented now? Here's what I get when I try to use it:
[root@frogstar ~]# podman --version
podman version 1.6.2
[root@frogstar ~]# podman volume create --driver local --opt type=xfs --opt device=/dev/md/jbod1 FileServerData         Error: error running volume create option: not yet implemented
[root@frogstar ~]# podman volume create --driver local --opt type=none --opt device=/mnt/data --opt o=bind FileServerData
Error: error running volume create option: not yet implemented

Both ways (using the XFS filesystem or using the already mounted filesystem's directory) don't seem to work.
Am I missing something?

**Comment by mheon** [comment]
The missing bit is 'driver=local' - leave that off for now, as we haven't
implemented volume plugin support yet. The command should work without it.

**Comment by bka2004** [comment]
Thank you, that solved it.
