### ISSUE TITLE
Requesting detailed documentation on containers.conf parameters

### ISSUE THREAD

**Issue by wirobert** [containers/libpod#3050]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
What is containers.conf?  And where did you see it?

**Comment by wirobert** [comment]
My error, I meant /etc/containers/storage.conf. Specifically is there a default userns-remap setting  similar to the Docker /etc/docker/daemon.conf parameter:

{
    "userns-remap" :  "default"
}

**Comment by rhatdan** [comment]
@wirobert I think you are talking about 99-containers.conf
 which was added for devicemapper for RHEL7 use of Docker.  I think this was done by me and @rhvgoyal to fix an issue with the RHEL7 kernel not handling removal of containers when a mount point leaked.

**Comment by rhatdan** [comment]
remap-uids and remap-gids.  The storage.conf

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

**Comment by wirobert** [comment]
To clarify, if I enter one and only one remap-uid/remap-gid pair of values will all containers created by podman use those mappings?

**Comment by rhatdan** [comment]
I believe that will work, unless overridden at the command line with --uidmap.  Not sure how well this works in rootless mode.

**Comment by wirobert** [comment]
I am using root mode Podman v0.7.3 as supported by Red Hat on RHEL 7.5 so I will test to confirm that is the case and update the issue with my results.

**Comment by baude** [comment]
can we close this?

**Comment by wirobert** [comment]
The testing I have done so far indicates that it doesn’t work as expected.

Bill Robertson
Eng-IT Automation Team
engit-auto@cisco.com<mailto:engit-auto@cisco.com>; dc-tools@cisco.com<mailto:dc-tools@cisco.com>;

**Comment by rhatdan** [comment]
@wirobert Please show us your results?

**Comment by rhatdan** [comment]
I am going to close this since we never got any more feedback.  @wirobert Please reopen this if you still have an issue.
