### ISSUE TITLE
/etc/resolv.conf gets reset on container restart

### ISSUE THREAD

**Issue by jlebon** [containers/libpod#3055]
/kind bug

**Description**

I created my pet container with `--dns 192.168.122.1`. Whenever I reboot or have to stop and restart the container, `/etc/resolv.conf` gets overwritten back to `192.168.0.1` (presumably to match my host).

**Steps to reproduce the issue:**

1. start new container with `--dns <ip>`
2. restart container

**Describe the results you received:**

`/etc/resolv.conf` matches host.

**Describe the results you expected:**

`/etc/resolv.conf` matches IP from `--dns <ip>`.

**Output of `podman version`:**

```
$ rpm -q podman
podman-1.2.0-2.git3bd528e.fc30.x86_64
[lux ~]$ podman version
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 5973495808
  MemTotal: 12490448896
  OCIRuntime:
    package: runc-1.0.0-85.dev.gitdd22a84.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: a5dee658ceacfe758cf47ba4ff4319278e58760c
      spec: 1.0.1-dev
  SwapFree: 19323154432
  SwapTotal: 19323154432
  arch: amd64
  cpus: 4
  hostname: lux
  kernel: 5.0.9-301.fc30.x86_64
  os: linux
  rootless: false
  uptime: 9h 47m 46.58s (Approximately 0.38 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 21
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Silverblue 30.20190427.n.0

**Comment by mheon** [comment]
How are you invoking Podman? Can you give a sample command that triggers this?

**Comment by mheon** [comment]
I can't replicate using `podman run --dns 8.8.8.8 -t -i fedora bash` and restarting the container

**Comment by jlebon** [comment]
This is what my pet script currently looks like:

```
    sudo podman run --name $name -e DISPLAY=:0 -e TERM -t --privileged \
       -v $HOME:/home/$USER -v /srv:/srv \
       -v /var/cache/dnf:/var/cache/dnf \
       -v /etc/machine-id:/etc/machine-id:ro \
       -v /var/run/libvirt:/var/run/libvirt \
       -v /var/lib/libvirt:/var/lib/libvirt \
       -v /run/systemd/journal:/run/systemd/journal \
       -v /var/log/journal:/var/log/journal \
       --dns 192.168.122.1 --user=root --entrypoint= \
       --detach-keys='ctrl-q,ctrl-p' --detach --net=host \
       --hostname=$name ${image} /bin/bash
```

Hmm, could be an interaction with `--net=host`?

**Comment by mheon** [comment]
`--net=host` and `--dns` are probably interacting and causing this one

**Comment by mheon** [comment]
Part of me wants to say that we should make the two options conflict, but there are legitimate uses to overriding host DNS while retaining the host network, so I'll see about figuring out what's going on here.

**Comment by mheon** [comment]
Hm. Still doesn't reproduce on master or 1.2 with `--dns 8.8.8.8 --net=host` - though I didn't force a full system reboot, just a container restart.

**Comment by jlebon** [comment]
I agree there are legitimate use cases. In my case, I'm using libvirt's dnsmasq because I don't want to keep editing `/etc/resolv.conf` everytime I hop on/off the VPN. Hmm, I guess I could bind-mount ro `/etc/resolv.conf`? Though not sure how that interacts with NM (i.e. if it `unlink` & `rename` vs updating it in-place).

**Comment by mheon** [comment]
Do you not have an `entrypoint` set (`--entrypoint= \`)? When I try your command Podman is attempting to parse the next argument as the entrypoint and fails to run

**Comment by jlebon** [comment]
> Do you not have an `entrypoint` set (`--entrypoint= \`)?

Hmm, no that works for me:

```
$ sudo podman run --rm -ti --entrypoint= registry.fedoraproject.org/fedora:30 /bin/bash
[root@e28e9826d7ab /]#
```

**Comment by jlebon** [comment]
> Still doesn't reproduce on master or 1.2

Hmm OK, I can try to get a better reproducer when I have some time. Could be related to `--privileged` too somehow?

**Comment by mheon** [comment]
Checking now, potentially

**Comment by debarshiray** [comment]
> In my case, I'm using libvirt's dnsmasq because I don't want to keep
> editing `/etc/resolv.conf` everytime I hop on/off the VPN. Hmm, I guess
> I could bind-mount ro `/etc/resolv.conf`? Though not sure how that
> interacts with NM (i.e. if it `unlink` & `rename` vs updating it in-place).

Just bind mounting `/etc/resolv.conf` won't work. NetworkManager would update it with the *write to temporary file and rename* idiom which would lead to a different inode and the changes won't propagate.

You could use the Flatpak-approach, which is also what Toolbox [does](https://github.com/debarshiray/toolbox/commit/04732139074b60dabe3087c37afbd99bdbf14a8a). In short, use `podman run --dns none --no-hosts ...`, bind mount the host's `/etc` at `/run/host/etc` and create symbolic links inside the container.

**Comment by mheon** [comment]
Update, it doesn't seem like privileged affects this. I'll try a full system restart later today to check if that might cause it.

I would say that I suspect that something in the container is removing resolv.conf and forcing it to be recreated, and there's a logic error somewhere in the recreation so we pick up the wrong DNS, but it's a bind mount inside the container - can't be removed.

Maybe something inside the container is editing it?

**Comment by jlebon** [comment]
> Just bind mounting /etc/resolv.conf won't work. NetworkManager would update it with the write to temporary file and rename idiom which would lead to a different inode and the changes won't propagate.

OK, that's what I suspected. And thinking more on this, I'm pretty sure I've hit this in the past and that's exactly how I ended up with the dnsmasq workaround. Mounting `/run/host/etc` and symlinking sounds like a good solution too.

> Maybe something inside the container is editing it?

Hmm, I can't imagine what would. I don't have e.g. systemd or NM running in there. Basically the only long-running process is tmux.

**Comment by baude** [comment]
@mheon any updates on this?

**Comment by mheon** [comment]
Still can't reproduce locally. Not sure what's going on here

**Comment by rhatdan** [comment]
Ok lets close since you seem to have a workaround.
