### ISSUE TITLE
`podman build -t foo -f foo/bar foo` not creating tag

### ISSUE THREAD

**Issue by NicolasT** [containers/libpod#3057]
(Filing here and not in `buildah` because `podman build` fails and `buildah bud` doesn't...)

/kind bug

Environment:
- `podman-1.2.0-2.git3bd528e.fc30.x86_64`
- `podman-docker-1.2.0-2.git3bd528e.fc30.noarch`
- `buildah-1.7-18.git873f001.fc30.x86_64`

When running `docker build --tag metalk8s-build:latest -f packages/Dockerfile packages` (note, using `podman-docker`), the whole build process runs and succeeds, but no tag is created. When afterwards running `docker images`, it *does* list the newly-created image, but *REPOSITORY* and *TAG* are `<none>`.

However, running `buildah bud --tag metalk8s-build:latest -f packages/Dockerfile packages` *does* create a tagged `localhost/metalk8s-build:latest` image listed in `docker images` (next to the previously created non-tagged image, with different image ID).

So, something gets lost in translation between `podman` and `buildah`, I guess?

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
IDK for sure if this is the problem, but the main difference between `buildah bud` and `podman build` is their default settings of the `--layers` option.  For Buildah that's false, for Podman it's true.  Regardless will dive in.

**Comment by NicolasT** [comment]
So, I took `libpod` from Git, and got it to compile. Turns out that in `master`, the issue doesn't present itself, and the tag *is* created. However, when checking out `v1.2.0` (the system version I got), a build with such binary doesn't create the tag.

So, I performed an 'inverse `git bisect`', so to say, between `v1.2.0` and `master`, where 'good' is 'no tag created' and 'bad' is 'tag created.

After a couple of iterations, it appears commit 024ae24f14a405cd0db40c52ef9d651a8d3ea6a9 fixed the issue (i.e. first commit at which the tag is created as expected):

```
024ae24f14a405cd0db40c52ef9d651a8d3ea6a9 is the first bad commit
commit 024ae24f14a405cd0db40c52ef9d651a8d3ea6a9
Author: TomSweeneyRedHat <tsweeney@redhat.com>
Date:   Sun Apr 14 14:07:42 2019 -0400

    Vendor in latest Buildah

    Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

:040000 040000 4c93a997b84552add8b00f3184fb8542c96d0079 d897f769fc8c5ec01ca503eb27dbf1f25fe65e33 M      test
:100644 100644 2adcb136c6cac3d6ddfb3ac3ce58385682f930ab 886e4794acde185d00af58ab0a9879f58a31d951 M      vendor.conf
:040000 040000 01bcbf7bfc3b57e1d93cae4c27304cc709c36e27 fb806ce7ff9b145ce6615214c9bd8604ea6d3f96 M      vendor
```

Any plans for a 1.2.1/1.3.0 release?

**Comment by TomSweeneyRedHat** [comment]
@NicolasT I just tried running with Buildah, Podman and Docker (as root) and the results look pretty much the same for all three to me.  Fair warning, for Buildah and Podman I used the absolute latest of each and Podman we just a few hours ago vendored the latest Buildah into it.  So perhaps a fix that went into Buildah has addressed this?  Below is what I did:

```
# cat ~/Dockerfile.symtarget 
FROM alpine

ENV HBASE_HOME="/usr/local/hbase"
ENV HBASE_CONF_DIR="/etc/hbase"

RUN mkdir $HBASE_HOME
RUN ln -s $HBASE_HOME $HBASE_CONF_DIR

COPY Dockerfile.symtarget $HBASE_CONF_DIR

# buildah bud --tag tom:latest -f ~/Dockerfile.symtarget .
# podman build  --tag tom2:latest -f ~/Dockerfile.symtarget .
# docker  build  --tag tom3:latest -f ~/Dockerfile.symtarget .
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
tom3                latest              b68727f461cd        5 seconds ago       5.53MB
alpine              latest              cdf98d1859c1        3 weeks ago         5.53MB

# buildah images
REPOSITORY                 TAG      IMAGE ID       CREATED         SIZE
localhost/tom2             latest   db018ebb7b75   3 minutes ago   5.81 MB
localhost/tom              latest   67642cc1dfbb   4 minutes ago   5.8 MB
docker.io/library/alpine   latest   cdf98d1859c1   3 weeks ago     5.8 MB

# podman images
REPOSITORY                 TAG      IMAGE ID       CREATED         SIZE
localhost/tom2             latest   db018ebb7b75   3 minutes ago   5.81 MB
localhost/tom              latest   67642cc1dfbb   4 minutes ago   5.8 MB
docker.io/library/alpine   latest   cdf98d1859c1   3 weeks ago     5.8 MB

# Note, Podman and Buildah share images, that's why you see each others in their listing.
```

**Comment by NicolasT** [comment]
Looks like we came to the same conclusion ;)

**Comment by TomSweeneyRedHat** [comment]
@NicolasT looks like we were commenting at the same time!  A v1.3 release for Podman is very much in the works.  I suspect it will be out to Fedora by end of next week at the absolute latest, but no promises.

**Comment by NicolasT** [comment]
OK then. I'll put a `master` build in my `PATH` temporarily. Thanks!
