### ISSUE TITLE
podman cp: not working with volumes

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3059]
(where "not working" means "files seem to vanish")
```
# podman volume create v
v
# podman run -d --name foo -v v:/mydir alpine sleep 600
b23df78e6fe60da7328cc34a5f1ebf0315075348b11c88010bffcb233c3b787e
# vdir=$(podman volume inspect -f '{{.MountPoint}}' v)
# ls -l $vdir
total 0
```
So far, so good. Now create a file, try to cp it into the volume in the container:
```
# echo hi >myfile
# podman cp myfile foo:/mydir/myfile_in_v
# ls -l $vdir
total 0
# podman exec foo ls -la /mydir
total 12
drwxr-xr-x    2 root     root          4096 May  2 17:19 .
drwxr-xr-x    1 root     root          4096 May  2 17:19 ..
```
That is: the 'cp' seemed to be a NOP. Running `find / -name 'my*'` in the container does not locate the desired myfile.

Or, create a file in the volume, try to cp it out:
```
# echo i am in the volume >$vdir/file_in_vdir
# podman exec foo ls -l /mydir
total 4
-rw-r--r--    1 root     root            19 May  2 17:23 file_in_vdir
# podman exec foo cat /mydir/file_in_vdir
i am in the volume
# podman cp foo:/mydir/file_in_vdir file_from_foo
Error: error evaluating symlinks "": lstat /var/lib/containers/storage/overlay/e98c91535f29a51cf74d99f93ab1012486ffe792a035f0d8c273d6719d8a5f3f/merged/mydir/file_in_vdir: no such file or directory
```
podman @ pr #3041. Haven't actually tested master, will do so on request.

**Comment by mheon** [comment]
Copy doesn't run inside the mount namespace, so we don't get access to things mounted into the container (named volumes, etc) - so I think this is expected.

Does Docker allow copying into volumes? If so they're probably doing some sort of 'cat' inside the container...

**Comment by edsantiago** [comment]
With the exception of having to use `vv` as volume name (docker doesn't allow single-character volume names), all of the above work in docker.

**Comment by edsantiago** [comment]
Minor nit which may or may not deserve its own issue: docker incompatibility: in `volume inspect`, the template element in docker is `Mountpoint` (lower-case p) but in podman it's `MountPoint` (upper-case P). This breaks automation that aliases `docker=podman`

**Comment by mheon** [comment]
I'll take the latter one... I need to rework a lot of volume internals for NFS, anyways

**Comment by baude** [comment]
@QiWang19 is this fixed?

**Comment by QiWang19** [comment]
Yes. PR #3094 is waiting to be merged.
