### ISSUE TITLE
Stuck at created container after error message: WARN[0001] Failed to add conmon to cgroupfs sandbox cgroup: mkdir /sys/fs/cgroup/systemd/libpod_parent: permission denied 

### ISSUE THREAD

**Issue by michielhemme** [containers/libpod#3075]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install Centos 7.6 and then install packages through rpm:
- conmon-1.12.0-12.dev.gitc4f232a.fc29.x86_64
- runc-1.0.0-92.dev.gitc1b8c57.fc31.x86_64
- slirp4netns-0.3.0-1.1.x86_64
- podman-1.2.0-24.dev.git0458daf.fc31.x86_64
- shadow-utils46-newxidmap-4.6-4.el7.x86_64 (Fork for newuid)

2. Enable user namespaces
cat <<EOT > /etc/sysctl.d/51-rootless.conf
user.max_user_namespaces = 15076
EOT
sysctl --system

3. Add users to subuid  subgid
cat <<EOT > /etc/subuid
testaccount:100000:65536
EOT
cp /etc/subuid subgid -y

4. Login to testaccount and start NGINX container:
testaccount: podman --log-level run -d -p 80 nginx

**Describe the results you received:**
[testaccount@centos76 ~]$ podman --log-level=debug run -d -p 80 nginx
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/testaccount/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/testaccount/.local/share/containers/storage 
DEBU[0000] Using run root /tmp/1000                     
DEBU[0000] Using static dir /home/testaccount/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/testaccount/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Using slirp4netns netmode                    
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/testaccount/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/testaccount/.local/share/containers/storage 
DEBU[0000] Using run root /tmp/1000                     
DEBU[0000] Using static dir /home/testaccount/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/testaccount/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] parsed reference into "[vfs@/home/testaccount/.local/share/containers/storage+/tmp/1000]docker.io/library/nginx:latest" 
DEBU[0000] parsed reference into "[vfs@/home/testaccount/.local/share/containers/storage+/tmp/1000]@27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] exporting opaque data as blob "sha256:27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] parsed reference into "[vfs@/home/testaccount/.local/share/containers/storage+/tmp/1000]@27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] exporting opaque data as blob "sha256:27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] parsed reference into "[vfs@/home/testaccount/.local/share/containers/storage+/tmp/1000]@27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] Using random host port 46076 with container port 80 
DEBU[0000] Using slirp4netns netmode                    
DEBU[0000] Allocated lock 3 for container 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 
DEBU[0000] parsed reference into "[vfs@/home/testaccount/.local/share/containers/storage+/tmp/1000]@27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] exporting opaque data as blob "sha256:27a188018e1847b312022b02146bb7ac3da54e96fab838b7db9f102c8c3dd778" 
DEBU[0000] created container "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" 
DEBU[0000] container "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" has work directory "/home/testaccount/.local/share/containers/storage/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata" 
DEBU[0000] container "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" has run directory "/tmp/1000/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata" 
DEBU[0000] New container created "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" 
DEBU[0000] container "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" has CgroupParent "/libpod_parent/libpod-6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" 
DEBU[0000] mounted container "6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85" at "/home/testaccount/.local/share/containers/storage/vfs/dir/5e062ba87328de82c498b2cc3692dbd27874ae5a2053d7a100bdc2d8ce300e35" 
DEBU[0000] Created root filesystem for container 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 at /home/testaccount/.local/share/containers/storage/vfs/dir/5e062ba87328de82c498b2cc3692dbd27874ae5a2053d7a100bdc2d8ce300e35 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
DEBU[0000] Created OCI spec for container 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 at /home/testaccount/.local/share/containers/storage/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata/config.json 
DEBU[0000] /usr/libexec/podman/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/libexec/podman/conmon    args=[-c 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 -u 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 -r /usr/bin/runc -b /home/testaccount/.local/share/containers/storage/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata -p /tmp/1000/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata/pidfile -l /home/testaccount/.local/share/containers/storage/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata/ctr.log --exit-dir /run/user/1000/libpod/tmp/exits --conmon-pidfile /home/testaccount/.local/share/containers/storage/vfs-containers/6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/testaccount/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /tmp/1000 --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 --socket-dir-path /run/user/1000/libpod/tmp/socket --log-level debug --syslog]
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: mkdir /sys/fs/cgroup/systemd/libpod_parent: permission denied 
DEBU[0000] Received container pid: 3984                 
DEBU[0000] Created container 6dbd08b69aa189466ff8f248e20ca7efb55caf751fec6eef1e16c300548cbf85 in OCI runtime 

It hangs till I cancel the command. I've used multiple releases of Podman, Slirp4netns, Conmon, and Runc.

**Describe the results you expected:**
Expected a working container with portmapping.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.2.0-dev
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.1
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: podman-1.2.0-24.dev.git0458daf.fc31.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 96168e342b58efb8f50a050aa22700ac59854f0e'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 2905862144
  MemTotal: 3973672960
  OCIRuntime:
    package: runc-1.0.0-92.dev.gitc1b8c57.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7+dev
      commit: 82c0db510c11ff6ea97d86b5a4f441d8b5376a84
      spec: 1.0.1-dev
  SwapFree: 3435130880
  SwapTotal: 3435130880
  arch: amd64
  cpus: 1
  hostname: centos76.michiel
  kernel: 3.10.0-957.12.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 46m 3.17s
insecure registries:
  registries: []
registries:
  registries:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/testaccount/.config/containers/storage.conf
  ContainerStore:
    number: 51
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/testaccount/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1000
  VolumePath: /home/testaccount/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Running on a Proxmox cluster.
- Centos 7.6 (latest)
- 4GB RAM
- 32GB HDD

**Comment by henrywang** [comment]
Have the same issue on Fedora 30, but not on Fedora 29.
If I disable selinux, everything works well.
Could you please take a look? Thank you so much.
podman version
```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.12
OS/Arch:            linux/amd64
```
podman info --debug
```
ebug:                                
  compiler: gc                  
  git commit: ""
  go version: go1.12
  podman version: 1.2.0                           
host:               
  BuildahVersion: 1.7.2
  Conmon:  
    package: podman-1.2.0-2.git3bd528e.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
  Distribution:
    distribution: fedora      
    version: "30"      
  MemFree: 2911723520
  MemTotal: 16689831936                                     
  OCIRuntime:    
    package: runc-1.0.0-92.dev.gitc1b8c57.fc30.x86_64
    path: /usr/bin/runc   
    version: |-
      runc version 1.0.0-rc7+dev                 
      commit: d38f8a2d00ff444e52d16ab1ea5bbe5c1cb471e8     
      spec: 1.0.1-dev
  SwapFree: 8589668352     
  SwapTotal: 8589930496         
  arch: amd64              
  cpus: 8                  
  hostname: test.redhat.com
  kernel: 5.0.11-300.fc30.x86_64
  os: linux              
  rootless: true                                                    
  uptime: 48h 17m 35.57s (Approximately 2.00 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/test/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/test/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 13
  RunRoot: /run/user/1000
  VolumePath: /home/test/.local/share/containers/storage/volumes
```

**Comment by mheon** [comment]
The `Failed to add conmon to cgroupfs sandbox` line is harmless; we can continue without issue when it happens. I'd actually say it's entirely expected on rootless (we should probably disable actually attempting it in the rootless case).

From the Podman side, it seems like your container has been created and is running. I imagine that, if you hit it with a `podman kill` or `podman stop` from another terminal, it will probably stop the container (I'd be very interested in whether this works). The problem seems to be that the initial Podman process is not exiting.

The fact that this reproduces as both root and rootless is very concerning, though.

**Comment by mheon** [comment]
Hm. From the positioning of the hang, the cause could be starting the container. If `runc` hangs when we request that it starts the container, that would cause the command we see here.

**Comment by mheon** [comment]
@michielhemme can you temporarily disable SELinux and see if you see different results?
@henrywang Please check `journalctl` for any AVCs (they'd be formatted like `audit[23984]: AVC avc:  denied  { write } for  pid=12345` in the logs) and paste them here, so we can tell what SELinux is blocking.

**Comment by michielhemme** [comment]
> @michielhemme can you temporarily disable SELinux and see if you see different results?
> @henrywang Please check `journalctl` for any AVCs (they'd be formatted like `audit[23984]: AVC avc: denied { write } for pid=12345` in the logs) and paste them here, so we can tell what SELinux is blocking.

Tried it with SELinux, disabled, enforced, permissive. All resulting in a hang after started container (so when runc needs to take over). 

Since Rhel8 released yesterday I will continue my research in that distro. Thanks for the help anyway.
I'll keep the installation on disk so If anyone else got a solution, I can try it out and people might find it useful in the future.

**Comment by henrywang** [comment]
> @michielhemme can you temporarily disable SELinux and see if you see different results?
> @henrywang Please check `journalctl` for any AVCs (they'd be formatted like `audit[23984]: AVC avc: denied { write } for pid=12345` in the logs) and paste them here, so we can tell what SELinux is blocking.

Thanks @mheon! Here's my AVC:
`AVC avc:  denied  { map } for  pid=5713 comm="entry_point.sh" path="/usr/bin/env" dev="fuse" ino=1334900 scontext=system_u:system_r:container_t:s0:c112,c627 tcontext=system_u:object_r:fusefs_t:s0 tclass=file permissive=0`

And my podman ps -a result:
```
CONTAINER ID  IMAGE                     COMMAND               CREATED        STATUS                      PORTS  NAMES
9ff5afa03103  docker.io/selenium/hub:3  /opt/bin/entry_po...  3 minutes ago  Exited (139) 3 minutes ago         selenium-hub
```

**Comment by rhatdan** [comment]
That is allowed in the current policy, which you indicate is installed.

Could you try

dnf reinstall container-selinux

And see if anything blows up?

**Comment by michielhemme** [comment]
> Have the same issue on Fedora 30. This issue can be reproduced on both root and rootless user. If I disable selinux, everything works as before. Is there any selinux configure to cause this issue?
> Could you please take a look? Thank you so much.
> podman version
> 
> ```
> Version:            1.2.0
> RemoteAPI Version:  1
> Go Version:         go1.12
> OS/Arch:            linux/amd64
> ```
> 
> podman info --debug
> 
> ```
> ebug:                                
>   compiler: gc                  
>   git commit: ""
>   go version: go1.12
>   podman version: 1.2.0                           
> host:               
>   BuildahVersion: 1.7.2
>   Conmon:  
>     package: podman-1.2.0-2.git3bd528e.fc30.x86_64
>     path: /usr/libexec/podman/conmon
>     version: 'conmon version 1.12.0-dev, commit: a13eadcaf0f07ba590c96d845a03ac3a0da7c56d'
>   Distribution:
>     distribution: fedora      
>     version: "30"      
>   MemFree: 2911723520
>   MemTotal: 16689831936                                     
>   OCIRuntime:    
>     package: runc-1.0.0-92.dev.gitc1b8c57.fc30.x86_64
>     path: /usr/bin/runc   
>     version: |-
>       runc version 1.0.0-rc7+dev                 
>       commit: d38f8a2d00ff444e52d16ab1ea5bbe5c1cb471e8     
>       spec: 1.0.1-dev
>   SwapFree: 8589668352     
>   SwapTotal: 8589930496         
>   arch: amd64              
>   cpus: 8                  
>   hostname: test.redhat.com
>   kernel: 5.0.11-300.fc30.x86_64
>   os: linux              
>   rootless: true                                                    
>   uptime: 48h 17m 35.57s (Approximately 2.00 days)
> insecure registries:
>   registries: []
> registries:
>   registries:
>   - docker.io
>   - registry.fedoraproject.org
>   - quay.io
>   - registry.access.redhat.com
>   - registry.centos.org
> store:
>   ConfigFile: /home/test/.config/containers/storage.conf
>   ContainerStore:
>     number: 1
>   GraphDriverName: overlay
>   GraphOptions:
>   - overlay.mount_program=/usr/bin/fuse-overlayfs
>   GraphRoot: /home/test/.local/share/containers/storage
>   GraphStatus:
>     Backing Filesystem: xfs
>     Native Overlay Diff: "false"
>     Supports d_type: "true"
>     Using metacopy: "false"
>   ImageStore:
>     number: 13
>   RunRoot: /run/user/1000
>   VolumePath: /home/test/.local/share/containers/storage/volumes
> ```

Actually my issue isn't with root user. It works flawlessly on root. The only issue I got is that port binding causes this issue on rootless (I can start a container without port binding, but I can only use Podman if port binding works). 

Since RHEL8 contains Podman V1.02-dev doesn't support rootless port bindings, I needed to install a newer RPM. So far I've tried:
Podman 1.3-dev
Podman 1.2
Podman 1.2-dev
Podman 1.12

I've also tried numerous versions of container-selinux, slirp4netns, and runc.

**Comment by michielhemme** [comment]
@rhatdan I was wondering if you could give any more insight in the release cycle of Podman within Red Hat 8? For example when will 1.12 arrive?

**Comment by rhatdan** [comment]
Currently we have to wait until RHEL8.1 to update container runtimes.  I am trying to change this.

**Comment by rhatdan** [comment]
@michielhemme What AVC's are you seeing on Fedora 30?

ausearch -m avc -ts recent

**Comment by henrywang** [comment]
> That is allowed in the current policy, which you indicate is installed.
> 
> Could you try
> 
> dnf reinstall container-selinux
> 
> And see if anything blows up?

@rhatdan, re-install `container-selinux-2.100-1.git3b78187.fc30.noarch`works for me. Appreciate your help! Does that mean we always need re-install `container-selinux` when updating from Fedora 29 to 30? Thanks.

**Comment by rhatdan** [comment]
No, your the only one that I heard about this from.  Something went wrong when you were updating or installing.  I will be looking for similar issues, and hope that this was just your issue. :^)
