### ISSUE TITLE
Make journald event logging optional

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#3079]
The latest release (v1.3.0) requires [`github.com/coreos/go-systemd/sdjournal`](https://github.com/containers/libpod/blob/master/libpod/events/journal_linux.go#L8) which relies on [development files from systemd](https://github.com/coreos/go-systemd/blob/95778dfbb74eb7e4dbaf43bf7d71809650ef8076/sdjournal/journal.go#L27-L28) which are not available on every target system and could break up builds. I would like to make this feature optional via a buildtag. WDYT?

**Comment by mheon** [comment]
SGTM. @baude Any issues with this?

**Comment by baude** [comment]
I need to think about this before deciding.  the problem is that it is the default setting.

**Comment by baude** [comment]
@saschagrunert put together a PR ... lets see what you have in mind.  I want final say but we can collaborate on it.

**Comment by saschagrunert** [comment]
> @saschagrunert put together a PR ... lets see what you have in mind. I want final say but we can collaborate on it.

I will do, thanks. If you say it should be included in every case we could also just [update the documentation](https://github.com/containers/libpod/blob/master/install.md#build-and-run-dependencies) about building libpod. In CRI-O for example we do not use this new code at all but updating libpod breaks up some builds. Beside that, statically building/linking systemd is a pain point and I usually did not want to put this dependency deeper into the project.
