### ISSUE TITLE
podman-remote create|run; unable to pull : error getting default registries to try

### ISSUE THREAD

**Issue by garethahealy** [containers/libpod#3102]
/kind bug

**Description**
podman-remote create|run both return an error regarding unable to pull image. The image thats trying to be pulled is already local.

https://gist.github.com/garethahealy/edd4d7da405987d15c2b21990721463e

```
$ podman-remote run -it localhost/podmanremote-pause bash
Error: unable to pull : error getting default registries to try: repository name must have at least one component
```

**Steps to reproduce the issue:**
1. podman-remote pull registry.access.redhat.com/ubi8/ubi:8.0
2. podman-remote run -it registry.access.redhat.com/ubi8/ubi:8.0 bash

**Describe the results you received:**
Error: unable to pull : error getting default registries to try: repository name must have at least one component

**Describe the results you expected:**
Container is created/run

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:            1.3.1-dev
RemoteAPI Version:  1
Go Version:         go1.11.10
Git Commit:         627dbd49c5a80146e5806797243b63d0bd157760
Built:              Thu May  9 13:09:27 2019
OS/Arch:            darwin/amd64
```

**Output of `podman info --debug`:**
```
client:
  OS Arch: darwin/amd64
  Podman Version: 1.3.1-dev
  RemoteAPI Version: 1
host:
  arch: amd64
  buildah_version: 1.7.2
  cpus: 1
  distribution:
    distribution: tinycore
    version: "10.0"
  hostname: box
  kernel: 4.19.32-tinycore64
  mem_free: 554090496
  mem_total: 1039273984
  os: linux
  swap_free: 198701056
  swap_total: 198701056
  uptime: 15h 14m 39.63s (Approximately 0.62 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - quay.io
store:
  containers: 1
  graph_driver_name: overlay
  graph_driver_options: ""
  graph_root: /var/lib/containers/storage
  graph_status:
    backing_filesystem: extfs
    native_overlay_diff: "true"
    supports_d_type: "true"
  images: 2
  run_root: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Am using boot2podman as my "server" - https://github.com/boot2podman/boot2podman

**Comment by baude** [comment]
@garethahealy im not able to replicate this with the upstream master version of libpod.  Is there any chance you could hop onto freenode in #podman and we could collab on this?

**Comment by garethahealy** [comment]
Just re-tested with remote and server on latest master and it works. Closing.
