### ISSUE TITLE
Rust ffi bindings crate for libpod

### ISSUE THREAD

**Issue by kallisti5** [containers/libpod#3107]
It appears someone has reserved multiple terms for the containers project @ Rust's crates.io.

A few examples:
* https://crates.io/crates/libpod
* https://crates.io/crates/podman
* https://crates.io/crates/pods
* https://crates.io/crates/podlib
* https://crates.io/crates/conmon
* https://crates.io/crates/buildah

If there are any plans to expose libpod API's in Rust, the containers team may want to take ownership of them.

https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code

**Comment by rhatdan** [comment]
@mheon @baude @vrothberg What should we do with this?

**Comment by mheon** [comment]
The question would be how we want to expose libpod via Rust. Do we want to do CGo and then a Rust FFI wrapper around that, or call in via Varlink?

**Comment by rhatdan** [comment]
How well does rust interact with golang?  Is there a rust library for varlink?

**Comment by rhatdan** [comment]
@giuseppe WDYT? @mtrmac ?

**Comment by mtrmac** [comment]
I mean, is there even any ambition at all to make libpod, or especially conmon, a library to be called by arbitrary third-party projects (with the API commitments it implies)? That’s the first question to be discussed (and API commitments have _significant_ impact on development). Only later we would possibly discuss Rust being possible / desirable / something we want to maintain as opposed to relying on someone else maintaining that.

WRT “taking ownership”, no idea. It may well make sense to let someone interested, not us, to maintain the bindings, and in that case using undecorated names of the upstream projects seems nice.

OTOH having crates for conmon/podman does look suspicious.

**Comment by giuseppe** [comment]
I agree with @mtrmac.  I'd prefer we don't commit on a libpod API yet (an exception could be CRI-O).

AFAIK, it is possible to use varlink from Rust, and I think varlink is the way to interact with Podman we can support and suggest to use.

**Comment by baude** [comment]
for now, i dont think there is interest in doing this.  if the community changes its minds, we can look into it

**Comment by xpepermint** [comment]
I'm also interested in this. Rust is meant for writing system-level apps and I believe we need direct access to lib (e.g. as we have for git).

**Comment by baude** [comment]
@xpepermint interested in writing them?

**Comment by xpepermint** [comment]
@baude That was my first thought but I'm afraid I need to read more stuff before I get my hands dirty. How would you do it? Right now I have so many questions :).

**Comment by baude** [comment]
i think all of us are dying to learn rust and write the bindings but time has not afforded it.  And supporting it probably scares us more ... We have go bindings now in master and that should firm up as well.

**Comment by mheon** [comment]
I think the core question of a new set of Rust bindings would be whether they should wrap Libpod directly and use a direct FFI to interface with Go, or implement the new Libpod HTTP API, which avoids a few potential pitfalls but also involves communicating with an existing Podman service and not directly managing Libpod.

**Comment by rhatdan** [comment]
I think step 1 would definitely be the HTTP API.  Then we can garner the requirements for embedding the library.

**Comment by InfRandomness** [comment]
Hi, is there an ETA on this project ?  is there a repository out there we can contribute to ?

**Comment by rhatdan** [comment]
No one that I am aware of is working on this.  But if you want to take the lead, I can give you a spot on github.com/containers podman-rust or something.

**Comment by InfRandomness** [comment]
I don't think I have enough experience to take the lead of such a big project unfortunately

**Comment by gdesmott** [comment]
> I think step 1 would definitely be the HTTP API. Then we can garner the requirements for embedding the library.

Isn't the HTTP API compatible with the Docker one? If it is then we could just re-use existing crates such as [rust-docker](https://gitlab.com/kblobr/rust-docker) or [bollard](https://github.com/fussybeaver/bollard) to communicate with podman.

**Comment by mheon** [comment]
It offers both a Docker compatible interface and an enhanced Libpod one
that allows you to take advantage of Podman’s added features (e.g. pods).
This means that you can continue to use any library meant to connect to the
Docker API.
