### ISSUE TITLE
Getting fuse-overlayfs into the podman installation instructions

### ISSUE THREAD

**Issue by sVattic** [containers/libpod#3109]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Following the current [installation instructions](https://github.com/containers/libpod/blob/master/install.md#ubuntu), running `podman run -it --rm docker.io/ubuntu` consumes just under 500 MB in `~/.local/share/containers/storage`. It is not immediately obvious to a new user as to why that is the case; personally, I found [this note](https://github.com/containers/libpod/blob/master/docs/podman-run.1.md#rootless-containers) at the bottom of the run man page talking about VFS and fuse-overlay.

It seems like the installation instructions for [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) have packages for fedora; it'd be great to see apt packages as well. Or, since there appear to be static build instructions (I tried it with buildah, but it looks like you need root) so maybe there could be binaries hosted on the releases page.

This has a pretty big impact on people's first impression on podman, which is why this ticket is filed here and not there :)

**Steps to reproduce the issue:**

1. With a clean install, follow installation instructions then run `podman run -it --rm docker.io/ubuntu` and wait to get a shell

2. `cd ~/.local/share/containers/storage && du -h -d 1`

**Describe the results you received:**

Observe a half-gigabyte of storage used :(

**Describe the results you expected:**

It would be great if fuse-overlayfs was ready to go with everyone's default instructions.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.3.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
... 

store:
  ConfigFile: ~/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: ~/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1000
  VolumePath: ~/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by rhatdan** [comment]
@sVattic Thanks for the issue, and we agree this is not a great situation.

@sVattic Any chance you could open a PR with the instruction changes.

**Comment by sVattic** [comment]
@rhatdan Unfortunately I might need some help with the instructions - as you saw in https://github.com/containers/fuse-overlayfs/pull/72 I was able to build some static binaries, but after that was unable to get them to work on my host.

As a test, I copied the `fuse-overlayfs` and `fusermount3` binaries out to my host, and tried this:

```
mkdir lowerdir upperdir workdir lowerdir/a lowerdir/b merged
export PATH=$PATH:$PWD

fuse-overlayfs -o lowerdir=lowerdir/a:lowerdir/b,upperdir=upperdir,workdir=workdir merged
```
```
fusermount3: mount failed: Operation not permitted
fuse-overlayfs: cannot mount: Operation not permitted
```

It might be that my system does not meet the requirements - I was going to try them in a vagrant next, but I ran out of time. If you like, I could open a partial PR getting buildah running and explaining how to export the static binaries?

Personally, I was doing this:

```bash
# Static build
buildah bud -t fuse-overlayfs -f ./Dockerfile.static .

# Make a container from the static image
podman run --name temp localhost/fuse-overlayfs true

# Copy binaries to host
podman cp temp:/usr/bin/fuse-overlayfs .
podman cp temp:/usr/bin/fusermount3 .

# Clean up temp container
podman rm temp

# Presumably, you would copy these to /usr/local/bin once confirming they worked for you
```

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
you need at least Linux 4.18.  What is the version of the kernel you are using?

**Comment by sVattic** [comment]
Oh - I didn't realize that, sorry. I see now that it's mentioned in the man page.

I have 4.15, I will try to get my system on the latest kernel and if that works start writing up a pull request.

**Comment by baude** [comment]
@sVattic how goes this? would love the PR

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Can you finish this up or close it if it is no longer needed?

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this now as I've looked through the docs and ubuntu repos.  fuse-overlayfs is now available on later versions of Ubuntu (https://packages.ubuntu.com/search?keywords=fuse-overlayfs) and the directions to install it are in the rootless install/config page (https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md)

@sVattic  if you think more work is necessary here, please reopen this issue or create a new one as appropriate.
