### ISSUE TITLE
Please provide stable release packages for Ubuntu

### ISSUE THREAD

**Issue by isavcic** [containers/libpod#3129]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As you're already building **dev** deb packages for Ubuntu, can you please provide the **stable** releases as well in the PPA? Just got bitten by #3126.

Thanks.

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by baude** [comment]
i wonder if the folks that use ubuntu should file a bug with ubuntu asking for podman inclusion?  then the ppa could become a development repository?

**Comment by lsm5** [comment]
@isavcic i just built 1.4.3 for 18.04, should be published in a bit. I plan to build stable releases only for the ppa going forward, with the long term goal being snap packages (snaps make it trivial to have dev/stable/release builds)

**Comment by baude** [comment]
please file trackpads for inclusion of podman into ubuntu
