### ISSUE TITLE
Podman image sign & podman push --sign-by cannot find key.

### ISSUE THREAD

**Issue by ezaluzec** [containers/libpod#3150]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

Using a gpg key, trying to sign a container image from a registry or trying to push a signed container to a registry results in error saying, `Error: Error copying image to the remote destination: Error creating signature: key "<key>" not found.`

**Steps to reproduce the issue:**

1. Create gpg key

		gpg --batch --gen-key gpg-batch
		gpg --no-default-keyring --secret-keyring ./key.sec --keyring ./key.pub --edit-key E90B1175 trust
		gpg --no-default-keyring --armor --secret-keyring ./key.sec --keyring ./key.pub --export name@company.com > pubkeys.gpg
		gpg --no-default-keyring --armor --secret-keyring ./key.sec --keyring ./key.pub --output container.tar.bz2.asc --detach-sign container.tar.bz2

2. Import container filesystem tarball

		sudo podman import container.tar.bz2

3. Try podman push 

		sudo podman push --sign-by="/path/to/file/pubkeys.gpg" af7d69bf19c1 quay.url.registry/username/reponame

		sudo podman push --sign-by="./pubkeys.gpg" af7d69bf19c1 quay.url.registry/username/reponame

		sudo podman push --sign-by="./key.sec" af7d69bf19c1 quay.url.registry/username/reponame

		sudo podman push --sign-by="./key.pub" af7d69bf19c1 quay.url.registry/username/reponame

		sudo podman push --sign-by="container.tar.bz2.asc" af7d69bf19c1 quay.url.registry/username/reponame

		sudo podman push --sign-by="name@company.com" af7d69bf19c1 quay.url.registry/username/reponame

4. Try podman image sign

		sudo podman image sign --sign-by name@company.com docker://quay.url.registry/username/reponame

		sudo podman image sign --sign-by name@company.com --directory /path/to/<key> docker://quay.url.registry/username/reponame

**Describe the results you received:**

- podman push

		sudo podman push --sign-by="<key>" af7d69bf19c1e3240507e222b7a4ec318e8399c800ea6124ef0e31eab9b672f7 quay.url.registry/username/reponame
		Getting image source signatures
		Copying blob 7d0b5e2df043 done
		Copying config af7d69bf19 done
		Writing manifest to image destination
		Copying config af7d69bf19 done
		Writing manifest to image destination
		Signing manifest
		Error: Error copying image to the remote destination: Error creating signature: key "<key>" not found

- podman image sign

		sudo podman image sign --sign-by name@company.com  docker://quay.url.registry/username/reponame
		Trying to pull docker://quay.url.registry/username/reponame...Getting image source signatures
		Copying blob cf891f998713 done
		Copying config af7d69bf19 done
		Writing manifest to image destination
		Signing manifest
		ERRO[0015] Error pulling image ref //quay.url.registry/username/reponame:latest: Error creating signature: key "name@company.com " not found
		Failed
		Error: error pulling image docker://quay.url.registry/username/reponame: unable to pull docker://quay.url.registry/username/reponame: unable to pull image: Error creating signature: key "name@company.com " not found

**Describe the results you expected:**

		Getting image source signatures
		Copying blob 33292c266d30 done
		Copying config b4133df433 done
		Writing manifest to image destination
		Copying config b4133df433 done
		Writing manifest to image destination
		Signing manifest
		Storing signatures

**Additional information you deem important (e.g. issue happens only occasionally):**
GPG Key type:

		Key-Type: RSA
		Key-Length: 2048
		Subkey-Type: RSA
		Subkey-Length: 2048

**Output of `podman version`:**

```
sudo podman --version
podman version 1.3.0-dev

```

**Output of `podman info --debug`:**

```
sudo podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.0-dev
host:
  BuildahVersion: 1.8-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "16.04"
  MemFree: 564756480
  MemTotal: 12581769216
  OCIRuntime:
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 12750811136
  SwapTotal: 12872314880
  arch: amd64
  cpus: 16
  hostname: hsv-redsea
  kernel: 4.4.0-142-generic
  os: linux
  rootless: false
  uptime: 1727h 44m 53.35s (Approximately 71.96 days)
insecure registries:
  registries: []
registries:
  registries: []
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 18
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 11
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 - Ubuntu 16.04.6 LTS
 - gpg (GnuPG) 1.4.20

**Comment by vrothberg** [comment]
@QiWang19 PTAL

**Comment by ezaluzec** [comment]
#### [ Update ] 

Closing, worked with gpg2 (GnuPG) 2.1.11 and clearing gpg keyring

#### [ Steps and Output ]

	gpg2 --full-gen-key
	gpg2 --armor --export --output mysignkey.gpg name@company.com 
	sudo podman push --sign-by name@company.com af7d69bf19c1e3240507e222b7a4ec318e8399c800ea6124ef0e31eab9b672f7 

	Getting image source signatures
	Copying blob 7d0b5e2df043 done
	Copying config af7d69bf19 done
	Writing manifest to image destination
	Copying config af7d69bf19 done
	Writing manifest to image destination
	Signing manifest
	Storing signatures
