### ISSUE TITLE
Windows remote client install

### ISSUE THREAD

**Issue by seriousme** [containers/libpod#3151]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Since 1.3.0 it should be possible to use podman-remote on windows thanks to https://github.com/containers/libpod/pull/3031 by @baude. 
However the install page does not specify any other way to install on windows than building from scratch.
It would be nice if their would be a way to download a binary for windows instead of having to build a binary from scratch.  

Kind regards,
Hans

**Comment by rhatdan** [comment]
Our goal later this summer is to have a packaged version for Windows.
@cevich Can you take a look at this, we had talked about leaving a statically built windows and mac version that could be pulled from github.

**Comment by baude** [comment]
if you have a way to run containers, i could make you a dockerfile that would create the windows binary as a temporary solution.  interested?

**Comment by seriousme** [comment]
That would already be a plus as I can use `boot2podman` to run a vm and use `podman-machine ssh` to get into the vm and to use podman there.

**Comment by cevich** [comment]
@rhatdan @baude yes in fact I already [have a PR open to do the publishing part.](https://github.com/containers/libpod/pull/3106).  [Cirrus supports windows containers](https://cirrus-ci.org/guide/windows/), if someone has the powershell skills to make it do useful things.  There are also Windows VM images available in GCE, but again my skills are lacking.  I'll spend time working on my PR this week.

**Comment by baude** [comment]
For the interim, i have built an image that can be used to do this:

```
$ mkdir output
$ podman container runlabel run quay.io/libpod/buildpodman
$ ...
$ ls output/
podman  podman-remote  podman-remote-darwin  podman-remote-windows.exe
```

**Comment by seriousme** [comment]
The build stage works, but something seems to be off:
```dos
podman-remote-windows version
Client:
Version:            1.4.1-dev
RemoteAPI Version:  1
Go Version:         go1.11.7
Git Commit:         fcb7c14c5bb94583db2343faaa1b85f0f2f96092
Built:              Sun Jun  9 11:03:39 2019
OS/Arch:            windows/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: not supported by windows
```
and similarly:
```
podman-remote-windows ps
Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: not supported by windows
```

**Comment by rhatdan** [comment]
@baude do you think we have made any progress on this?
@seriousme Any chance you can try out the latest code?

**Comment by seriousme** [comment]
@rhatdan just tried using boot2podman on windows 10  build 18362 (Update 1903)

```bash
>podman-machine ssh
        .---.        b o o t 2                 mm             https://podman.io
       /o   o\                                 ##
    __(=  "  =)__    ##m###m    m####m    m###m##  ####m##m   m#####m  ##m####m
     //\'-=-'/\\     ##"  "##  ##"  "##  ##"  "##  ## ## ##   " mmm##  ##"   ##
        )   (        ##    ##  ##    ##  ##    ##  ## ## ##  m##"""##  ##    ##
       /     \       ###mm##"  "##mm##"  "##mm###  ## ## ##  ##mmm###  ##    ##
  ____/  / \  \____  ## """      """"      """ ""  "" "" ""   """" ""  ""    ""
 `------'`"`'------' ##                                                art: jgs
tc@box:~$ podman version
Version:            1.4.3-dev
RemoteAPI Version:  1
Go Version:         go1.12
Git Commit:         b611ac1c50184827fa0be04a8de800e09b802705-dirty
Built:              Sun Jun 23 19:07:27 2019
OS/Arch:            linux/amd64
tc@box:~$
```
And then from the windows command line:

```bash
>podman-remote-windows version
Client:
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.11.7
OS/Arch:            windows/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: not supported by windows
```
Same error as before..

**Comment by cevich** [comment]
**Update:** For-testing-use-only Windows (and Darwin) builds are now automatically uploaded here:

Master Branch: https://storage.cloud.google.com/libpod-master-releases/

Pull-requests: https://storage.cloud.google.com/libpod-pr-releases/

(both should be public, let me know if you see any access-denied errors)

**Comment by seriousme** [comment]
Just tried podman-remote-latest-master-windows-amd64/podman-v1.6.0-rc2-36-ga8c2b5de from Google Storage, so it is public.

Results are however the same as for 1.4.5-dev:
```bash
>podman version
Client:
Version:            1.6.0-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            windows/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: A socket operation encountered a dead network.
```

Are we sure this podman.exe in the zip is podman-remote ?
Because trying to dail unix sockets on a windows host seems a bit odd ;-)

**Comment by baude** [comment]
@seriousme that error basically means that podman-remote doesnt know where to send its requests.  its last resort it to look for a socket.  You need to have a linux vm to connect to that has podman on it.  You can then either use a configuration file or the command line options to point podman-remote to the vm in question.

@jwhonce do we have anything that describes this?

**Comment by seriousme** [comment]
Well that explains a lot :-)

I'm using [boot2podman](url) which gives me the ```podman-machine``` command on Windows.

Starting the VM in virtualbox:
```shell
>podman-machine start
Starting "box"...
(box) Check network to re-create if needed...
(box) Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.      
(box) Waiting for an IP...
Machine "box" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `podman-machine env` command.
```
Setting the environment variables
```shell
>podman-machine env
SET PODMAN_USER=root
SET PODMAN_HOST=127.0.0.1
SET PODMAN_PORT=59450
SET PODMAN_IDENTITY_FILE=C:\Users\J\.local\machine\machines\box\id_rsa
SET PODMAN_IGNORE_HOSTS=true
SET PODMAN_MACHINE_NAME=box
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('podman-machine env') DO @%i
```
This is a bit weird, because the VM is not running on 127.0.0.1, but at 192.168.99.100
```shell
>podman-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                    ERRORS
box    -        virtualbox   Running   tcp://192.168.99.100
```

Checking the version of podman inside the VM
```shell
>podman-machine ssh box podman version
Version:            1.4.3-dev
RemoteAPI Version:  1
Go Version:         go1.12
Git Commit:         b611ac1c50184827fa0be04a8de800e09b802705-dirty
Built:              Sun Jun 23 19:07:27 2019
OS/Arch:            linux/amd64
```
However something seems to go wrong with the port assignment as podman.exe tries to connect on port 22 while I specify 59450
```shell
>podman --remote-host 127.0.0.1 --port 59450 version
Client:
Version:            1.6.0-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            windows/amd64

Service:
ssh: connect to host 127.0.0.1 port 22: Connection refused
Error: Unable to obtain server version information: unexpected EOF
```
When I try to connect to the VM using 192.168.99.100. It seems to connect SSHD on port 22 of the VM and tries to authenticate itself:
```shell
>podman --remote-host 192.168.99.100  --port 59450 version
Client:
Version:            1.6.0-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            windows/amd64

Service:
Seriousme@192.168.99.100's password:
Error: Unable to obtain server version information: unexpected EOF
```

Anything else I can try ?

**Comment by jwhonce** [comment]
@seriousme When you install the msi from the link in https://github.com/containers/libpod/issues/3151#issuecomment-536026794 we install a batch script called podman.  That script will query for the necessary configuration information and setup a conf file in your home directory so you only need to provide that information once. 

Supporting non-22 ports within podman is on our roadmap.  As a work around you can either, setup an alias in .ssh/config or use something like:

C:\ set PODMAN_VARLINK_BRIDGE=C:\Windows\System32\OpenSSH\ssh.exe -T -p59450 Seriousme@192.168.99.100 -- /usr/bin/varlink -A "/usr/bin/podman varlink \$VARLINK_ADDRESS" bridge
C:\ podman images

**Comment by seriousme** [comment]
The plot thickens, but I'm not there yet:

```podman-machine``` has an option to create VARLINK_BRIDGE variable

```
>podman-machine env --varlink
SET VARLINK_BRIDGE=C:\WINDOWS\System32\OpenSSH\ssh.exe -F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\Seriousme\.local\machine\machines\box\id_rsa -p 59450 varlink bridge
SET PODMAN_VARLINK_BRIDGE=$VARLINK_BRIDGE
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('podman-machine env --varlink') DO @%i

>podman images
Error: unable to get images: unexpected EOF
```
So at least something happens.
Digging deeper gives:
```
>podman-machine ssh box whoami
tc
>podman-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                    ERRORS
box    *        virtualbox   Running   tcp://192.168.99.100
```
Changing  user to `tc@192.168.99.100` gives the same:
```
>podman images
Error: unable to get images: unexpected EOF
```

has anyone actually got the setup with podman-remote and podman-machine working on Windows or am I chasing ghosts here ?

**Comment by jwhonce** [comment]
@seriousme Please note the changes I made to the end of your PODMAN_VARLINK_BRIDGE

SET VARLINK_BRIDGE=C:\WINDOWS\System32\OpenSSH\ssh.exe -F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@127.0.0.1 -o IdentitiesOnly=yes -i C:\Users\Seriousme\.local\machine\machines\box\id_rsa -p 59450 -- /usr/bin/varlink -A "/usr/bin/podman varlink $VARLINK_ADDRESS"

**Comment by seriousme** [comment]
@jwhonce  thanks for the suggestion, however no luck yet
```
>podman images
Error: Could not get runtime: connection "" has no destination defined
```

**Comment by seriousme** [comment]
Anyways: my OP said:
`It would be nice if their would be a way to download a binary for windows instead of having to build a binary from scratch.`

That has been provided now, thx for that!   So I suggest to close the issue here.

**Comment by jwhonce** [comment]
@seriousme FYI -- That error message means podman on your linux server is cannot configured correctly.
