### ISSUE TITLE
[RFE] Require signed images

### ISSUE THREAD

**Issue by jcpunk** [containers/libpod#3165]
/kind feature

**Description**

For production environments it might be handy to have a setting in libpod.conf where admins can require images are signed (or signed by a set of trusted keys).  In theory this could prevent unexpected content from being deployed or prevent deployment from a compromised registry. 

**Steps to reproduce the issue:**

1. search for way to force podman to only run signed images via libpod.conf

2. nothing obvious in https://github.com/containers/libpod/blob/master/docs/libpod.conf.5.md

**Comment by rhatdan** [comment]
We already have this in /etc/containers/policy.json
man containers-policy.json
