### ISSUE TITLE
RFE: New stability test

### ISSUE THREAD

**Issue by cevich** [containers/libpod#3166]
/kind feature

**Description**

Recent issue found in OpenShift uncovered a gap in testing for large number and speed of container run/rm cycles.  Since in CI our steady-state VM parameters are effectively static, we can detect some classes of resources leaks within a small-ish margin of error.  This is something we should attempt within the ~30min of runtime available.

**Steps to perform:**

1. In parallel with integration tests, spin up one VM per distro/version.

2. On each VM, in a loop execute `podman run --rm ... bash -c 'echo $RANDOM' > /dev/null` with a 10ms delay between each.  Loop for 20-minutes, recording how many containers ran total.

3. Allow VM to idle for 3-5 minutes.

4. Collect memory and other metrics from VM.

5. Pass/Fail test based on expected number of container executions, and comparison of collected metrics values to expected values within some allowable error percentage.

**Comment by baude** [comment]
im not in favor of this for prs ... maybe more for system test or release test?

@mheon argee? if so, close or ?

**Comment by mheon** [comment]
Tend to agree... I don't think our leaks would have been found by conventional testing like this.
