### ISSUE TITLE
Conflict at mount destination with podman 1.3.1

### ISSUE THREAD

**Issue by vsim3** [containers/libpod#3174]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman 1.3 error with docker postgres:10-alpine image
Upgrade to f30 lead to postgresql container error
_ Work fine on v1.2

**Steps to reproduce the issue:**

1. sudo podman run -d --name rss-postgresdb --cap-drop=CAP_NET_BIND_SERVICE --cap-drop=CAP_NET_RAW --conmon-pidfile=${DB_PID} -v ${PGDATA}:/var/lib/postgresql/data:Z -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=${PW} -e POSTGRES_DB=db --uidmap=0:100000:65536 --gidmap=0:100000:65536--oom-score-adj="-1000" -p 127.0.0.1:5432:5432 docker.io/library/postgres:10-alpine

**Describe the results you received:**
<code>Error: conflict at mount destination /var/lib/postgresql/data: duplicate mount destination</code>

**`podman version`:**
podman-1.3.1-1.git7210727.fc30
```

**Comment by cwawak** [comment]
Also seeing the same behavior on the same version - this was a clean Fedora 30 server minimal install. Also on 1.3.1-1-git7210727.fc30.x86_64. Specifying a volume using -v always results in this error.

**Comment by mheon** [comment]
This was my code, I'll take a look.

**Comment by mheon** [comment]
Image volumes - has to be image volumes.

We have a named volume from an image volume at `/var/lib/postgresql/data` and an explicit user-specified mount at `/var/lib/postgresql/data` and we're not properly handling the conflict.

Working up a patch.

**Comment by cwawak** [comment]
@mheon this is exactly what's going on - thank you so much for taking a look, and allowing me to have choice in my container life. 👍

**Comment by mheon** [comment]
#3177 should fix

**Comment by whitel** [comment]
Is there a work around for this while we wait for the patch to land?

**Comment by mheon** [comment]
Try `--image-volume=tmpfs` - it should make the conflict one that Podman is able to automatically resolve.

**Comment by whitel** [comment]
that worked! thanks!

**Comment by vsim3** [comment]
Thanks for that quick fix.

**Comment by rhatdan** [comment]
@mheon Do we need a new release for this?  Is this worth blocking podman 1.3.1?

**Comment by TomSweeneyRedHat** [comment]
+1 on the new release from me, blocking I'm on the fence for.

**Comment by mheon** [comment]
We just merged a few big PRs from Giuseppe on user namespace, so I think
our best bet is to try and cut a 1.4 next week with whatever is ready and
get that it quickly.
