### ISSUE TITLE
Glitches in an interactive shell spawned via 'podman exec', but not 'podman run', due to the presence of OPOST in the outer PTY and missing ONLCR in the inner PTY

### ISSUE THREAD

**Issue by debarshiray** [containers/libpod#3179]
/kind bug

**Description**

People have been observing various kinds of glitches in Toolbox shells. [One such glitch](https://github.com/debarshiray/toolbox/issues/14) is observed in tmux when horizontally splitting with `ctrl+b %`.

Given an interactive shell inside a container:
```
# dnf -y install tmux
# tmux
# seq 10
...
...
# <split horizontally by pressing ctrl+b followed by %>
```

If the glitch reproduces, you'd see the output of `seq 10` disappear in the left pane. If you remove the newly created pane on the right by quitting the shell in it, the output of `seq 10` reappears.

Interestingly, the glitch is influenced by how the container was entered.

A shell obtained this way is unaffected:
```
$ podman run --env TERM=$TERM --rm -it registry.fedoraproject.org/f30/fedora-toolbox:30 /bin/bash
```

However, this is affected:
```
$ podman create --name foo registry.fedoraproject.org/f30/fedora-toolbox:30 sleep +Inf
$ podman start foo
$ podman exec --env TERM=$TERM -it foo /bin/bash
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproducible at will.

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.7
  podman version: 1.2.0
host:
  BuildahVersion: 1.7.2
  Conmon:
    package: podman-1.2.0-2.git3bd528e.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 2b09d2268c06808d88cac9bc499288d539b243de'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 794501120
  MemTotal: 8126943232
  OCIRuntime:
    package: runc-1.0.0-85.dev.gitdd22a84.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 1d3f73d4086533a858613bc4b6af2b5e882f4730
      spec: 1.0.1-dev
  SwapFree: 4127440896
  SwapTotal: 4133482496
  arch: amd64
  cpus: 4
  hostname: kolache
  kernel: 5.0.9-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 11h 28m 7.21s (Approximately 0.46 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/rishi/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/rishi/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/rishi/.local/share/containers/storage/volumes
```

**Comment by baude** [comment]
@haircommander can you comment if the move to use conmon for exec altes this behavior?

**Comment by giuseppe** [comment]
I think it is an issue in runc, as I can see it using directly `runc exec -t`

**Comment by haircommander** [comment]
If it's a runc issue, conmon for exec won't fix it :\

**Comment by kamalmarhubi** [comment]
@giuseppe can you share the repro you used for `runc exec`? I'd like to file this against runc but struggled to get a container started because I'm not familiar with the tool.

**Comment by giuseppe** [comment]
@kamalmarhubi all I've tried is to run `runc run CONTAINER` and from another terminal `runc exec -t CONTAINER sh`

Get a container running with runc is not easy as you need the exploded container rootfs + a config.json file, I'd suggest you just use podman to create the container, and then from another terminal you can use directly runc on that container.

**Comment by debarshiray** [comment]
Turns out that the `ONLCR` flag is disabled in the terminals exhibiting this bug. As per `termios(3)`, `ONLCR` translates to *map NL to CR-NL on output*.

With a PTY created by GNOME Terminal:
```
$ stty
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
$ stty -a
speed 38400 baud; rows 38; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```

With `podman run ...`:
```
# stty
speed 38400 baud; line = 0;
-brkint -imaxbel
# stty -a
speed 38400 baud; rows 38; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```

With `podman exec ...`:
```
# stty
speed 38400 baud; line = 0;
-brkint -imaxbel
-onlcr
# stty -a
speed 38400 baud; rows 38; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
```

**Comment by debarshiray** [comment]
Sadly, enabling `ONLCR` with `stty onlcr` doesn't make the problem go away.

**Comment by kamalmarhubi** [comment]
@debarshiray oh interesting! Do you think this is something that might need to be done by runc? I really don't know anywhere near as much about terminals as I'd like to.

**Comment by kamalmarhubi** [comment]
This is one of these situations where I feel like things would be simpler if runc / podman would just `setns(2)` and `execve(2)` instead of forking and doing all this pseudoterminal nonsense.

**Comment by debarshiray** [comment]
> Do you think this is something that might need to be done by runc?

From a distance, it does seem reasonable to avoid divergences between the different ways in which podman and runc create pseudoterminals. However, in this case, it doesn't look like the `onlcr` flag is the one causing the problem.

Maybe I need to stare harder at the `stty` output to notice any other differences? I don't know, really.

**Comment by ftsell** [comment]
On my setup the only differences are:
- `iutf8` on host, `-iutf8` in container
- `onlcr`on host, `-onlcr` in container

Now I don't know a lot about terminal magic either but to me it doesn't seem like iutf8 is a crucial capability

**Comment by rhatdan** [comment]
@haircommander Does your conmon exec code fix this?
@debarshiray Do we still have an issue with what is in master branch?

**Comment by haircommander** [comment]
this is an issue with runc. @giuseppe do you know if that was fixed

**Comment by giuseppe** [comment]
> this is an issue with runc. @giuseppe do you know if that was fixed

no, I am not aware of any fix that went into runc

**Comment by giuseppe** [comment]
could you try with crun?  Do you have the same problem?

**Comment by egmontkob** [comment]
Logging with `script` either inside `toolbox`, or without `toolbox` involved (in this latter case the behavior is expected) reveals that after printing the vertical separator, the cursor is moved downwards using NL and each line is cleared to its end using `^[[K` or `^[[1K`, meaning that the cursor is expected to stay in the same column (at the middle of the screen).

With `script` logging outside of `toolbox`, these NLs become CRNLs, moving the cursor to the beginning of the line, and thus the next `^[[1K` clears the entire line, resulting in the buggy look.

So I'm almost sure the bug is that `-onlcr` isn't propagated to some tty component and so this unexpected and harmful NL -> CR NL conversion happens.

**Comment by egmontkob** [comment]
Looks like the stty settings aren't autoforwarded from `toolbox`'s (or `podman`'s) inside to its outside.

E.g. from `/dev/pts/2` (as reported by the `tty` command) execute `toolbox`, and then it becomes `/dev/pts/3`. The output of `stty < /dev/pts/2` does not include `-onlcr`, while the output of `stty < /dev/pts/3` does. Manually "fixing" it from another terminal (i.e. `stty -onlcr < /dev/pts/2)` fixes `tmux`'s behavior, although later causes staircase effect in the shell outside of `tmux`.

The termios settings (or at least a reasonable subset thereof; probably the source of `script` is a good starting point) of `/dev/pts/2` should auto-follow the ones of `/dev/pts/3`, it should be the responsibility of whoever forwards the actual data in both directions between these two.

**Comment by egmontkob** [comment]
I was probably wrong saying that the stty settings should be autoforwarded. Many of them are not idempotent (e.g. NL -> CR NL, or ^V as input escaper ("lnext")) and you don't want them to be applied twice. What you need instead is the outer terminal not to do any special processing.

This apparently should be done using `cfmakeraw()` which includes stuff such as `stty -opost` to disable processing the output. `script` [seems to do this](https://github.com/karelzak/util-linux/blob/v2.34/term-utils/script.c#L257) in its `enable_rawmode_tty()` method.

As a quick test, `stty -opost < /dev/pts/2` (as per the previous comment's example), instead of `-onlcr` also repairs `tmux`'s behavior. And also results in staircase effect outside of `tmux`, this I'm yet to understand, but I believe it's the inner terminal `/dev/pts/3` that should take care of avoiding the staircase and not the outer one.

**Comment by egmontkob** [comment]
> And also results in staircase effect outside of tmux, this I'm yet to understand

This links back to the original investigation around `-onlcr`.

So it seems we have two problems, and accordingly, the following two commands fix the situation temporarily (both the tmux split case, as well as the staircase problem outside tmux):

- `stty -opost < /dev/pts/2` on the outer terminal (execute it after attaching to the container)
- `stty onlcr` on the inner terminal

and similarly, for a proper fix, obviously you'd need to make sure that these two are set accordingly automatically.

**Comment by egmontkob** [comment]
Note: `-opost` does a couple of things including `-onlcr`. `cfmakeraw()` does a couple of things including `-opost`. The proper fix should do `cfmakeraw()` on the outer terminal.

**Comment by egmontkob** [comment]
On an absolutely irrelevant note: If the character encoding is UTF-8 then `stty iutf8` should be set inside podman, too.

**Comment by debarshiray** [comment]
To summarize @egmontkob 's diagnosis, we need:
*  `stty --file /path/to/outer/terminal/device -opost` on the outer terminal to remove OPOST
*  `stty --file /path/to/inner/terminal/device onlcr` on the inner terminal to add ONLCR

I see that the `SetRaw` function in `containerd/console` does restore the `OPOST` flag, so I believe that's where one of those two issues comes from. A bit of Git surgery tells me that it has been like that since the first `containerd/console` commit ever. :)

I also see that `ONLCR` gets cleared in a bunch of different places, but I have to stare harder at the terminal code in `runc` to understand which one of those is wrong.

**Comment by debarshiray** [comment]
> If it's a runc issue, conmon for exec won't fix it :\

On bisection, it turns out that commit a1a79c08b72793cf from https://github.com/containers/libpod/pull/3143 fixed this issue.

**Comment by debarshiray** [comment]
Only thing left here is to see if we can add tests for this, which I have now attempted in PR https://github.com/containers/libpod/pull/3986

**Comment by mheon** [comment]
Neat. Closing as this is fixed upstream.

**Comment by vashirov** [comment]
I'm not sure it's totally fixed. I have
```
$ podman version 
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

```
$ podman run -ti fedora:latest 
[root@fec0a25ffd0a /]# stty size 
58 225
```
In another terminal (not even in tmux):
```
$ podman exec -ti fec0a25ffd0a /bin/bash 
[root@fec0a25ffd0a /]# stty size 
0 0
```

**Comment by debarshiray** [comment]
That's a [different issue](https://github.com/containers/libpod/issues/3946).

**Comment by kolyshkin** [comment]
> On bisection, it turns out that commit a1a79c0 from #3143 fixed this issue.

To dig deeper, the change in conmon that fixed this was https://github.com/cri-o/cri-o/pull/568.
