### ISSUE TITLE
podman build -q output prefixes image id with '--> '/'--> Using cache '

### ISSUE THREAD

**Issue by tmds** [containers/libpod#3191]
Actual:
```
$ podman build -q .
--> 5b78988e87bbb00b4c8bb4307db5ff82a71a63ae54e51606032562ce35421997
$ podman build -q .
--> Using cache 5b78988e87bbb00b4c8bb4307db5ff82a71a63ae54e51606032562ce35421997
```
Expected: no prefix so the output is a directly usable image id.

podman v1.3.1.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@tmds can you share the Dockerfile that you used?  I don't have a v1.3.1 handy, but using this Dockerfile:
```
# cat Dockerfile.busybox
FROM busybox
# podman version 
Version:            1.3.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.2
Git Commit:         2bb1487a00d23bb38314b7d7ee861952b7c6517e-dirty
Built:              Thu May 16 12:05:18 2019
OS/Arch:            linux/amd64
```

I'm not seeing the error in upstream.
```
# podman build -q -f ~/Dockerfile.busybox .
--> 64f5d945efcc0f39ab11b3cd4ba403cc9fefe1fa3613123ca016cf3708e8cafb
# podman build -q -f ~/Dockerfile.busybox .
--> 64f5d945efcc0f39ab11b3cd4ba403cc9fefe1fa3613123ca016cf3708e8cafb
```

I think, but can't swear to it that this was a fix not too long ago, but I thought it would have been in v1.3.1.

**Comment by tmds** [comment]
@TomSweeneyRedHat it is not failing. The output format is not matching my expectations:

Instead of:
```
--> 64f5d945efcc0f39ab11b3cd4ba403cc9fefe1fa3613123ca016cf3708e8cafb
```
My expectation (based on `docker` cli) is there to be no prefix:
```
64f5d945efcc0f39ab11b3cd4ba403cc9fefe1fa3613123ca016cf3708e8cafb
```

**Comment by TomSweeneyRedHat** [comment]
@tmds 
Thanks for the explanation.  I though the issue was the first had `-->` and the second had `--> Using cache`.

@rhatdan @nalind WDYT about droppnig the prefix entirely?

**Comment by rhatdan** [comment]
Yes I agree we should not do the -->

**Comment by tmds** [comment]
@TomSweeneyRedHat will this be implemented in one of the next releases?

**Comment by TomSweeneyRedHat** [comment]
@tmds thanks for the reminder.  Let me see if I can crank this out quickly, I'd set it aside for other fires.

**Comment by Romain-Geissler-1A** [comment]
Hi,

Still, the output of "podman build -q" doesn't match the output of "docker build -q":

- docker outputs a single line (the final image id), while podman show all intermediate image ids
- podman prefixes it with "Using cache" when the cache was used, whereas docker only outputs the image id and nothing else.

Is it possible to match the docker output ? It's quite handy to easily fetch an image id with:
DOCKER_IMAGE_ID="$(docker build -q .)"
while with podman currently we need to filter output to have the same result.

Cheers,
Romain

**Comment by tmds** [comment]
@Romain-Geissler-1A can you create a new issue?

**Comment by TomSweeneyRedHat** [comment]
@Romain-Geissler-1A that should be quiet and I thought it was.  Me thinks we've had a change somewhere to not make it quiet any more.  Drat!  Thanks for the heads up.  As this is build issue, I've created a new issue under Buildah and tried to tag you in it so you can follow.  

https://github.com/containers/buildah/issues/1897
