### ISSUE TITLE
Rootless Install Guide

### ISSUE THREAD

**Issue by Snapstromegon** [containers/libpod#3195]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I don't know if this is even possible, but assume I'm on a host that doesn't allow me to run anything as root:

Is it possible to setup podman rootless (this is allowed to include compiling from scratch) and can e.g. the setup guide include some help for this?

Even if it isn't possible to setup podman completely without root, it would be great to have something like a checklist what root has to provide for the setup to work.

My usecase is, that podman is strong by removing the root deamon (compared to the evil d-word) and so it's a good fit for e.g. shared hosting where the user has no root but wants to run containers. My hoster might do some minimal software tweaking, but wouldn't install anything system wide.

Maybe there is also a way easier way to solve my problem of installing podman rootless or a even a guide to it and I was just not able to find it myself...

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Shared Hosting running Centos 7

**Comment by rhatdan** [comment]
Right now it requires the shadow-utils with newuidmap and newgidmap.  I think the rest of the packages could be hacked together to run. But this would be a good exercise.
You would probably need fuse-overlay and slirp4netns either installed on the system or built locally, then you would need to customize the storage.conf file in ~/.config/containers/storage.conf.

**Comment by mheon** [comment]
If you have access to a pre-built Podman binary (and Conmon and slirp4netns), and install them into your home directory, that should work fine (as long as newuidmap and newgidmap are available). If you want to build from source, that's more complicated, because we have a good number of build dependencies that you'd have to produce from scratch.

**Comment by rhatdan** [comment]
I believe that we can make the code work with a single UID without newuidmap and newgidmap.  
You can execute `unshare -r` and enter a User Namespace with a single UID.
You would only be able to run/build containers with a single UID, but this might be a useful use case.
I have a lot of people from the HPC groups looking for this kind of solution.

@giuseppe ^^

**Comment by Snapstromegon** [comment]
okay, I'll see if something like this works for my case - but nevertheless it might be good to mention something like @rhatdan's comment in the install guide.

**Comment by TomSweeneyRedHat** [comment]
+1000  I literally was looking through our docs today and didn't find much if anything.  I was thinking about putting together a tutorial for this, but thought we'd one somewhere.  We should have at least a tutorial in GitHub that goes through the setup process for shadow-utils, /etc/subuid, /etc/subgid, and a bit more.  I'll see if I can hack together a least a rough tutorial that we can expand on.

**Comment by Snapstromegon** [comment]
So just that I understand correctly:
According to @rhatdan it should be possible to have a mode that doesn't need shadow-utils at the cost of having only one uid, but after that according to @mheon it would be possible to just grab the binarys from e.g. a local system and use them completely rootless?

This would just be a dream for many shared hosting clients!

**Comment by mheon** [comment]
I will caution that a lot of standard images require more than 1 UID to work, and thus will need a working shadowutils. You won't be able to use the Fedora, Busybox, Ubuntu, for starters.

**Comment by giuseppe** [comment]
That is already possible. We raise only a warning if podman cannot setup multiple IDs.  You should be fine to run it but as @mheon pointed out, many images will fail

**Comment by cyphar** [comment]
One way to solve the single-UID problem is to look into using the xattr trick that `umoci` uses to store the real uid/gid. You then fake the syscall responses to match. Unfortunately right now this requires `PRoot` (which uses `ptrace`) but post-5.0 kernels have new `SECCOMP_RET_USER_NOTIF` support which means we can fake it using seccomp and thus without the downsides of ptrace.

I have looked at rewriting the important bits of PRoot to use `SECCOMP_RET_USER_NOTIF` but have been busy with other yak shaving over the past few months.

**Comment by Snapstromegon** [comment]
@giuseppe I just tried and found while running CentOS Linux release 7.6.1810 (Core) that if I just use the binarys from a local system, I see the following error:

```
$ podman --log-level=debug info
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
cannot clone: Invalid argument
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
ERRO[0000] cannot re-exec process

````

I assume that a requirement is that at least user namespaces are enabled (would make sense).

```
$ podman --log-level=debug version
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
INFO[0000] running as rootless
Version:       0.12.1.2
Go Version:    go1.10.3
OS/Arch:       linux/amd64

```

@cyphar I see where you're coming from with your last paragraph and I must say, that I was really hyoed after seeing your talks the first time a long while ago.
But in my opinion the first step is to make it work at all - maybe later it will become easier to setup but I love the work you've done and the community did for this project! This project is on a great way and I do believe that it will spread even further and if things like rootless setup work at least partially it might be reason for more hosters to include it in their fundamental setup.

**Comment by giuseppe** [comment]
> One way to solve the single-UID problem is to look into using the xattr trick that `umoci` uses to store the real uid/gid. You then fake the syscall responses to match. Unfortunately right now this requires `PRoot` (which uses `ptrace`) but post-5.0 kernels have new `SECCOMP_RET_USER_NOTIF` support which means we can fake it using seccomp and thus without the downsides of ptrace.

this is something I also wanted to play with in crun (https://github.com/giuseppe/crun/issues/22) but had no time yet to look at.
Are you planning to emulate only file system permissions or also mask syscalls like `seteuid(2)`?  For file system permissions another alternative, at least for rootless Podman that is already using it, is to teach fuse-overlayfs to read and use these xattrs

**Comment by cyphar** [comment]
PRoot does mask syscalls like `seteuid(2)` already (as does my hacky project `remainroot`) so we might as well. The really big issue is `setgroups` and `getgroups` -- because unmapped UIDs show up and you cannot drop them `apt` likes to throw a hissy fit as do a lot of other tools

**Comment by rhatdan** [comment]
@cyphar @giuseppe If we could get this supported in Podman, that would be a nice step forward.  Would love to see some PRs moving this way.

**Comment by giuseppe** [comment]
> @cyphar @giuseppe If we could get this supported in Podman, that would be a nice step forward. Would love to see some PRs moving this way.

we need a monitor for doing the seccomp stuff.  So we should either add these capabilities to conmon, which I think is not really the correct place (unless using directly libcrun?) or the OCI runtime.  In the latter case we need to change conmon to wait for the OCI runtime rather than the container process.

**Comment by cyphar** [comment]
And the problem with doing it in `runc` is that we'd now break the "no daemons for our containers" model...

**Comment by giuseppe** [comment]
> And the problem with doing it in `runc` is that we'd now break the "no daemons for our containers" model...

it will be opt-in, or just work in the `runc run` mode.

**Comment by cyphar** [comment]
We can definitely do it, I was just thinking out loud. I'd prefer it to be more pluggable where we provide a way for `SECCOMP_RET_USER_NOTIF` to be combined with the seccomp configuration.

**Comment by baude** [comment]
updates fellas?

**Comment by TomSweeneyRedHat** [comment]
I'm not sure if it covers the request completely, but we put this up about a month ago
https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md
It's mostly likely a start to a users guide and some of the doc folks had talked about using it as a seed for a more formal users guide.

**Comment by cyphar** [comment]
That is an improvement, though I would like to sit down and try to see what breaks if I try to run an *actually* rootless environment a-la [the original case-study for rootless containers](https://www.youtube.com/watch?v=r6EcUyamu94) (no setuid helpers or configuration of root-only files at all). Hopefully there wouldn't be too many things that break, but given that this is a use-case that modern "rootless" containers don't care too much about I wouldn't be shocked if there are a few things that don't work correctly.

**Comment by rhatdan** [comment]
I just merged into containers/storage a fix that allow ignoring of chown failures. Setting this should allow a single UserNamespace UID to download and work with images.  Pushing them somewhere might be an issue.

Work was asked for by some HPC people.

**Comment by vrothberg** [comment]
Doing some cleanups in the issues; updates for this one?

**Comment by TomSweeneyRedHat** [comment]
I think we've just been nibbling at the tutorial as time has passed.  Currently, @rhatdan @giuseepe @baude and others are working through F31/crun issues and we'll probably need an update for this afterward.

**Comment by rhatdan** [comment]
Yes we need to do some editing on this for cgroupsV2.

**Comment by mheon** [comment]
I think we have another issue already open for this?

**Comment by mheon** [comment]
#3932
