### ISSUE TITLE
Unable to execute "podman ps" as non-privileged user

### ISSUE THREAD

**Issue by akoenig** [containers/libpod#3201]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A `podman ps` as a non-privileged user leads to `Error: cannot read pause process pid file /run/user/0/libpod/pause.pid: open /run/user/0/libpod/pause.pid: permission denied`

**Steps to reproduce the issue:**

1. Install the current PPA version (`podman version 1.3.2-dev`) on `18.04.2 LTS (Bionic Beaver)`
2. Execute `podman ps` as non-privileged user

**Describe the results you received:**

`Error: cannot read pause process pid file /run/user/0/libpod/pause.pid: open /run/user/0/libpod/pause.pid: permission denied`

**Describe the results you expected:**

List of all running containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.3.2-dev
```

**Output of `podman info --debug`:**

As `root`:

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.3.2-dev
host:
  BuildahVersion: 1.9.0-dev
  Conmon:
    package: 'conmon: /usr/libexec/crio/conmon'
    path: /usr/libexec/crio/conmon
    version: 'conmon version , commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 285392896
  MemTotal: 2039857152
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: cjw246f3c000e02s65ya8h4g2
  kernel: 4.15.0-50-generic
  os: linux
  rootless: false
  uptime: 35m 29.87s
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@giuseppe @mheon Is this podman being confused about whether it is in rootless mode?

**Comment by mheon** [comment]
This is definitely rootless code. It doesn't seem to have found the correct
PID for Conmon to join the rootless user namespace.

**Comment by rhatdan** [comment]
Well reading it looks like it is looking for the wrong UID then.
A podman ps as a non-privileged user leads to Error: cannot read pause process pid file /run/user/0/libpod/pause.pid: open /run/user/0/libpod/pause.pid: permission denied

While it should be looking for 
/run/user/USERUID/libpod/pause.pid

**Comment by giuseppe** [comment]
How does the `XDG_RUNTIME_DIR` look like?  Podman would not use that directory if it is not writable, unless the environment variable is explicitly set

**Comment by akoenig** [comment]
@giuseppe Thanks for the hint :slightly_smiling_face: The following works:

As "unprivileged user":

```sh
mkdir $HOME/run
export export XDG_RUNTIME_DIR=$HOME/run

podman ps
```

Would that the way to go? :slightly_smiling_face:

**Comment by rhatdan** [comment]
The question is how do you get this screwed up in the first place.  If you are logged in as non-root and execute podman it will use XDG_RUNTIME_DIR.  To me this looks like you logged in as root and then sudo to a non root user?  Or something like that.

If you login straight as @akoenig XDG_RUNTIME_DIR should be pointing to /run/user/AKOENIGUID.

$ printenv XDG_RUNTIME_DIR
/run/user/3267

$ id -u
3267

**Comment by akoenig** [comment]
Well, your assumption is correct. I have a `userData` script which starts the container via `sudo -u <user> bash -c 'podman run -d -t ...'`.

So in my case, I have to use the "workaround" I've described above (I guess).

**Comment by mheon** [comment]
If you have to make a run directory, please make it on a tmpfs - `/tmp` or /var/run` or similar - Podman needs that directory to clear after a reboot to function properly

**Comment by akoenig** [comment]
@mheon Thanks for the hint. I just got bitten by this scenario :slightly_smiling_face:

**Comment by giuseppe** [comment]
can we close this issue?

**Comment by akoenig** [comment]
Yep, thanks again for the help 🙂
