### ISSUE TITLE
[RFE] Support option to enter a container with the host PID namespace

### ISSUE THREAD

**Issue by mildred** [containers/libpod#3205]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Required by fedora-toolbox project https://github.com/debarshiray/toolbox/issues/176

In order to support having a toolbox with systemd in it, but having shells spawned in the toolbox share the PID namespace of the host, it would be great to have the `podman exec --pid=host` option available to keep the PID namespace of the host while executing in the container.

Similar features like `--net=host` could prove useful as it would avoid requiring using `nsenter` but is out of scope for this issue.

**Output of `podman version`:**

```
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
I thought we supported this already. The good news is that if not, it's a
very simple change on our end

**Comment by mildred** [comment]
I was looking at the implementation, and it does not look that simple as it seems to depend on the OCI runtime (runc ?). And the OCI specs seems to have the notion of sharing or splitting the PID namespace at the container level, and not at the process level, which seems to indicate this would not be possible for `podman exec`.

I tried out using nsenter instead of podman exec to run the commands, and it might not be such a great idea to have `/proc` in the container reflect a split PID namespace and have commands running in the host PID namespace. `/proc/self` and things like that are not working any more.

**Comment by debarshiray** [comment]
@mildred How old is your Toolbox container?

Since version 0.0.6, all Toolbox containers use the host's PID namespace (ie., `podman create --pid host`). So, maybe it's a matter of not being able to change it once the container has already been created (ie., `podman create` versus `podman exec`)?

**Comment by debarshiray** [comment]
Ah, after re-reading https://github.com/debarshiray/toolbox/issues/176, I see what you want.

You want to run systemd within the container with a PID namespace, but the interactive shells spawned by `podman exec` in the host's PID namespace, right?

**Comment by mheon** [comment]
Oh, that's a different matter.

That would require changes to `runc` I think - `exec` enters all of a container's namespaces right now, without exception. I don't think this is impossible, but as we're requiring changes outside the project itself, this could take some time.

**Comment by giuseppe** [comment]
as your original issue report said, the best way to achieve it is probably through `nsenter`.  You could use podman inspect to read the container PID and then tweak what you want to join with `nsenter`

**Comment by mildred** [comment]
Yep, that was the original idea. `podman run` would start a process in a dedicated PID namespace but `podman exec` would be able to keep the host PID namespace (just like nsenter where you can choose which namespace you enter or not).

It just seems that's not possible by using runc, and such cases seems dubious (entering the mount namespace but not the PID namespace gives you a mismatching `/proc` which can be fine for debugging but is not really suited for day to day work).

Because of that I'm closing this as the best option seems to choose at container creation time instead.

**Comment by SGM70** [comment]
Hi All,

Sorry if the question seems a bit silly, but what if I'd like to run Ansible and larn SQL withon a toolbox container? Does it sound a good idea?, and in such a case, would I need to enable in a way or another systemctl withoin a container?

**Comment by rhatdan** [comment]
Probably better off asking this question to toolbox, not podman.
