### ISSUE TITLE
Podman install guide adjustments - DOC

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#3206]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind bug

**Description**
The podman [install notes](https://github.com/containers/libpod/blob/master/install.md) tell the user to [Add configuration](https://github.com/containers/libpod/blob/master/install.md#add-configuration) which I believe needs to be changed to something like "If you do not have the 'containers-common' package available for your distribution, then do this configuration.  Also I don't think the location listed for the registries.conf file (projectatomic) is the correct location at this time.

Secondly, after following the listed steps, there does not appear to be a /usr/share/containers/libpod.conf file installed.  This should happen I believe.

I'm happy to make the adjustments, may need pointers/verification of the same.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
 podman version
Version:            1.3.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.2
Git Commit:         2bb1487a00d23bb38314b7d7ee861952b7c6517e-dirty
Built:              Thu May 16 12:05:18 2019
OS/Arch:            linux/amd64

```

**Comment by TomSweeneyRedHat** [comment]
Per @rhatdan in #3156
```
make install PREFIX=
```

s/b
```
make install PREFIX=/usr
```

**Comment by rhatdan** [comment]
Please open a PR>

**Comment by h-vetinari** [comment]
@TomSweeneyRedHat 
I had linker errors using `sudo podman` when building with selinux and using `PREFIX=/usr` in #3068, but since #3045 is still unsolved (despite being closed), I'll just have a look at the install instructions again and report the status after your PR (and once I find some time)... :)
