### ISSUE TITLE
podman generate systemd for Pods

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3209]
/kind feature

**Description**

Based on user feedback, it would be nice to support generating service files for Pods.

Cc: @baude @mheon

**Comment by apollo13** [comment]
I just wanted to open an issue towards the same goal :) I think in the end it would be really nice if one could get N + 1 service files (n containers & 1 pod) and start the pod service file would start the pod and then the dependant services. Probably using systemd's template units ala pod.service, pod@container1.service etc…?

**Comment by mheon** [comment]
My thoughts are basically the same - one service for the overall pod, and then sub-services for containers within the pod.

**Comment by mbonato** [comment]
+1

**Comment by baude** [comment]
how would you expect the output? right now, for a container, we simply print the output to stdout. that works fine for a single container.  whats being proposed is multiple files.  thoughts?

**Comment by apollo13** [comment]
Well the pod service file would probably have no output and the individual container service files would have the same setup as now output wise.

**Comment by rhatdan** [comment]
@baude Any progress on this?

**Comment by baude** [comment]
we havent had time to do feature work in weeks.

**Comment by mheon** [comment]
@vrothberg landed this one, I believe. Closing as it is included in latest Podman.
