### ISSUE TITLE
Add CI to test podman with Kata-Containers

### ISSUE THREAD

**Issue by amshinde** [containers/libpod#3262]
As discussed in the last crio meeting. It will be useful to have a CI job to test podman with Kata-Containers, similar to what we have in crio today. This will help validate Kata with the latest podman release.

cc @chavafg

**Comment by baude** [comment]
as a pre-req, can you guys produce a how-to kata and podman to make this something that we can try and understand?  

and then, as for the ci, are you talking about your CI or ours? 

if the latter, we'd love to evaluate any PRs you want to submit.

**Comment by baude** [comment]
@amshinde any updates?
