### ISSUE TITLE
Error: failed to prune image: layer not known

### ISSUE THREAD

**Issue by fpytloun** [containers/libpod#3266]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running `podman system prune -a -f --volumes` on some nodes returns `Error: failed to prune image: layer not known` without any further explanation

```
[root@gitlab-runner-cleanup-ll2fl /]# podman system prune -a -f --volumes
Deleted Containers
Deleted Volumes
Error: failed to prune image: layer not known
```

**Steps to reproduce the issue:**

Unfortunately I don't know why this happens only on some nodes. We are using them as gitlab runners using Podman to build images.

**Describe the results you received:**

```
[root@gitlab-runner-cleanup-ll2fl /]# podman system prune -a -f --volumes
Deleted Containers
Deleted Volumes
Error: failed to prune image: layer not known
```

**Describe the results you expected:**

No error, cleaned even images with unknown layers. At least better description of this error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 18:10:31 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: a95a49d3038462d033f84ac314ec8a3064a99cff
  go version: go1.11.5
  podman version: 1.1.2
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: podman-1.1.2-1.git0ad9b6b.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: a95a49d3038462d033f84ac314ec8a3064a99cff'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 12339150848
  MemTotal: 31622615040
  OCIRuntime:
    package: runc-1.0.0-68.dev.git6635b4f.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: ef9132178ccc3d2775d4fb51f1e431f30cac1398-dirty
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: gitlab-runner-cleanup-ll2fl
  kernel: 4.14.91+
  os: linux
  rootless: false
  uptime: 26h 25m 49.33s (Approximately 1.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 554
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Kubernetes pod.

Issue seems to be related to https://github.com/containers/buildah/issues/1447 as I was able to identify broken image and inspecting it gives `layer not known` issue.

**Comment by rhatdan** [comment]
@QiWang19 Can you look into this?

**Comment by baude** [comment]
also does this fail on master?

**Comment by mheon** [comment]
We have a good reproducer for getting these images in #3304

**Comment by thawkins** [comment]
see my note on #3304 about the uid/gid used to create the container files in ~/.local/share/containers

**Comment by baude** [comment]
is this fixed?

**Comment by mheon** [comment]
This one should be fixed

**Comment by Ulrar** [comment]
Hi,

Sorry to dig this up, but what's the solution to fix this ?
Is there some manual cleanup needed ?

Thanks

**Comment by rhatdan** [comment]
Updating your version of Podman most likely.  podman system reset will remove all images and containers.
