### ISSUE TITLE
RHEL EXTRA's updated podman, port mapping isn't working

### ISSUE THREAD

**Issue by michielhemme** [containers/libpod#3270]
/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install RHEL 7.6, register, enable rhel-7-server-beta-rpms, rhel-7-server-extra-rpms, Execute a yum update and after install Podman. Enable user-namespaces, create a test user and add it to /etc/subid(subgid).

2. Fix first error ERRO[0000] container failed: cannot specify gid= mount options for unmapped gid in rootless containers: internal libpod error. Fix this by installing a runc version higher then 1.0.0.83+

3. Solve the next issue ERRO[0000] error checking slirp4netns binary /usr/bin/slirp4netns: exit status 1, solve it by installing a newer version of slirp4netns.

**Describe the results you received:**
Rootless containers with port mapping will hang during start:

[test@rhel76 ~]$ podman --log-level=debug run -d -p 80 nginx
INFO[0000] running as rootless                          
DEBU[0000] Initializing boltdb state at /home/test/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/test/.local/share/containers/storage 
DEBU[0000] Using run root /tmp/1000                     
DEBU[0000] Using static dir /home/test/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/test/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend file              
DEBU[0000] parsed reference into "[vfs@/home/test/.local/share/containers/storage+/tmp/1000]docker.io/library/nginx:latest" 
DEBU[0000] parsed reference into "[vfs@/home/test/.local/share/containers/storage+/tmp/1000]@62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] exporting opaque data as blob "sha256:62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] parsed reference into "[vfs@/home/test/.local/share/containers/storage+/tmp/1000]@62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] exporting opaque data as blob "sha256:62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] parsed reference into "[vfs@/home/test/.local/share/containers/storage+/tmp/1000]@62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] Using random host port 45506 with container port 80 
DEBU[0000] Got mounts: []                               
DEBU[0000] Got volumes: []                              
DEBU[0000] Using slirp4netns netmode                    
DEBU[0000] created OCI spec and options for new container 
DEBU[0000] Allocated lock 1 for container 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 
DEBU[0000] parsed reference into "[vfs@/home/test/.local/share/containers/storage+/tmp/1000]@62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0000] exporting opaque data as blob "sha256:62c261073ecffe22a28f2ba67760a9320bc4bfe8136a83ba9b579983346564be" 
DEBU[0001] created container "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" 
DEBU[0001] container "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" has work directory "/home/test/.local/share/containers/storage/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata" 
DEBU[0001] container "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" has run directory "/tmp/1000/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata" 
DEBU[0001] New container created "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" 
DEBU[0001] container "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" has CgroupParent "/libpod_parent/libpod-81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" 
DEBU[0001] mounted container "81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4" at "/home/test/.local/share/containers/storage/vfs/dir/b76cd35f0dccf4405c302aab854f04f32eff47d1ecbdb753419ffbe90879f635" 
DEBU[0001] Created root filesystem for container 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 at /home/test/.local/share/containers/storage/vfs/dir/b76cd35f0dccf4405c302aab854f04f32eff47d1ecbdb753419ffbe90879f635 
WARN[0001] error mounting secrets, skipping: getting host secret data failed: failed to read secrets from "/usr/share/rhel/secrets": open /usr/share/rhel/secrets: permission denied 
DEBU[0001] /etc/system-fips does not exist on host, not mounting FIPS mode secret 
DEBU[0001] Created OCI spec for container 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 at /home/test/.local/share/containers/storage/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata/config.json 
DEBU[0001] /usr/libexec/podman/conmon messages will be logged to syslog 
DEBU[0001] running conmon: /usr/libexec/podman/conmon    args=[-c 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 -u 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 -r /usr/bin/runc -b /home/test/.local/share/containers/storage/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata -p /tmp/1000/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata/pidfile -l /home/test/.local/share/containers/storage/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata/ctr.log --exit-dir /run/user/1000/libpod/tmp/exits --conmon-pidfile /home/test/.local/share/containers/storage/vfs-containers/81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/test/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /tmp/1000 --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 --socket-dir-path /run/user/1000/libpod/tmp/socket --log-level debug --syslog]
WARN[0001] Failed to add conmon to cgroupfs sandbox cgroup: mkdir /sys/fs/cgroup/systemd/libpod_parent: permission denied 
DEBU[0001] Received container pid: 7524                 
DEBU[0001] Created container 81d786711dfe341aca46980c250a058ef5d8e17379ea8bb9b88380902b16c5d4 in OCI runtime 

**Describe the results you expected:**
A working container with port mapping.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.3.2
RemoteAPI Version:  1
Go Version:         go1.10.8
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
podman info --debug
ERRO[0000] Error refreshing container 5afc1bcc108272debf804f274ddaf06cbaae8878dd633eb49a1979aad8dd6f03: error acquiring lock for container 5afc1bcc108272debf804f274ddaf06cbaae8878dd633eb49a1979aad8dd6f03: file exists 
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.8
  podman version: 1.3.2
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.2-1.git14fdcd0.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 4780496c1f6949e21c807e17b57c183e9424c90a-dirty'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 238211072
  MemTotal: 3973689344
  OCIRuntime:
    package: runc-1.0.0-83.dev.gitf56b4cb.fc28.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 3434860544
  SwapTotal: 3435130880
  arch: amd64
  cpus: 1
  hostname: rhel76
  kernel: 3.10.0-957.el7.x86_64
  os: linux
  rootless: true
  uptime: 4h 7m 30.28s (Approximately 0.17 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/test/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/test/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1000
  VolumePath: /home/test/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ProxMox Cluster
RHEL 7.6
4GB RAM

**Comment by baude** [comment]
please file a bugzilla and close this

**Comment by mheon** [comment]
We make absolutely no promise that rootless Podman is working on RHEL7 right now. It will be working and supported with native packages as of 7.7, so I suggest you wait for that release

**Comment by michielhemme** [comment]
@mheon , Also the beta? Because I get exactly the same error in 7.7.

**Comment by mheon** [comment]
I think it should be - if you see this in the 7.7 Beta, I'd recommend opening a BZ, so we can potentially get a fixed build into the final release

**Comment by junwang123** [comment]
The `podman` gid mapping problem appears to be reproducible with the [7.7 beta packages](https://access.redhat.com/downloads/content/69/ver=/rhel---7/7.7%20Beta/x86_64/packages). Refer to [buildah issue #1657](https://github.com/containers/buildah/issues/1657) for the test case and steps to reproduce.

> [osboxes@osbox76 centos]$ rpm -q podman buildah runc
> podman-1.3.2-1.git14fdcd0.el7.x86_64
> buildah-1.8.2-2.gite23314b.el7.x86_64
> runc-1.0.0-59.dev.git2abd837.el7.x86_64

> [osboxes@osbox76 centos]$ buildah images
> REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
> [osboxes@osbox76 centos]$ buildah containers
> CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
> [osboxes@osbox76 centos]$ buildah bud -f Dockerfile.build -t builder .
> STEP 1: FROM centos
> Getting image source signatures
> Copying blob 8ba884070f61 done
> Copying config 9f38484d22 done
> Writing manifest to image destination
> Storing signatures
> STEP 2: COPY build.sh .
> STEP 3: COPY chroot.sh /target/
> STEP 4: COMMIT builder
> Getting image source signatures
> Copying blob d69483a6face skipped: already exists
> Copying blob 35a05842a678 done
> Copying config cf6405a205 done
> Writing manifest to image destination
> Storing signatures
> --> cf6405a205ed4c7ba13a923b192923cee88c96dc7930da1603bbfed38b1aa7e9
> [osboxes@osbox76 centos]$ podman run --privileged -v $(pwd):/workspace builder /build.sh
> Error: container create failed: cannot specify gid= mount options for unmapped gid in rootless containers
> : internal libpod error
>

**Comment by baude** [comment]
please file a bugzilla if you hope to have this fixed.
