### ISSUE TITLE
containers/storage.conf now needs `runroot` options specified

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#3274]
/kind bug

**Description**

podman now requires me to set `runroot =` in my `~/.config/containers/storage.conf` 

**Steps to reproduce the issue:**

1. configure your system with `~/.config/containers/storage.conf` like:

```
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]
# Default Storage Driver
driver = "overlay"
# Primary Read/Write location of container storage
graphroot = "/var/b/dustymabe-config-containers/storage"
# 
[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
```

note this used to work (i.e. it works today on another system with  `podman-1.2.0-2.git3bd528e.fc29.x86_64`)

2. upgrade to newer podman

3. try to run root podman container: `$ podman run -it --rm registry.fedoraproject.org/fedora:30`

4. See error message:

**Describe the results you received:**

```
$ podman run -it --rm registry.fedoraproject.org/fedora:30 
Error: error creating libpod runtime: no storage runroot specified: missing necessary StoreOptions
```

**Describe the results you expected:**

not requiring the runroot option to be defined and a sane default getting applied. Currently on a fresh install the default in the `~/.config/containers/storage.conf` file is `runroot = "/tmp/1000"` which I don't think is very unique. `/var/run/user/1000/containers/storage` would be better.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ rpm -q podman
podman-1.3.1-1.git7210727.fc30.x86_64
$ podman version
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug 
Error: could not get runtime: no storage runroot specified: missing necessary StoreOptions
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Silverblue:

```
$ rpm-ostree status
State: idle
Warning: failed to query journal: Cannot assign requested address (os error 99)
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/30/x86_64/updates/silverblue
                   Version: 30.20190530.0 (2019-05-30T00:39:27Z)
                BaseCommit: 8980028d1ac8f8180b29233be4704d0ff3c8e01d6833d149dc460919a63c39a7
```

**Comment by cgwalters** [comment]
I don't understand at all why podman is auto-creating the config file; I think that's an anti-pattern.  Don't require users to edit it if they didn't change any options, etc.

**Comment by rhatdan** [comment]
I am wondering this my self.  At least fields like runroot should not be preset.  Once a container is created the the location of the storage is difficult to change.  But the runroot should be flexible.

@mheon @giuseppe WDYT?

**Comment by baude** [comment]
@giuseppe ptal

**Comment by giuseppe** [comment]
The issue started to be visible with b0fcd555db55fc8e739614f44c62f14cd608725d when the function was still under of libpod.

We try to use the default configuration when it is possible.  One difficulty is that the default configuration is not static (e.g. we use `fuse-overlayfs` only when the executable is present), so we need to cherry-pick only a subset of the configuration that is safe to use.  Similarly we cherry-pick some changes from the global configuration under `/etc/containers` when they are not overriden in the `~/.config/containers/` files.

We generate the configuration files for a couple of reasons:

- be as close as possible to "root podman", where the conf files are installed under `/etc` as part of the package installation.  The first run as rootless is the closest thing to that.
- Provide a base for further customizations.

I've opened a PR for containers/storage to address the issue above: https://github.com/containers/storage/pull/372

**Comment by dustymabe** [comment]
> We generate the configuration files for a couple of reasons:
> 
> * be as close as possible to "root podman", where the conf files are installed under `/etc` as part of the package installation.  The first run as rootless is the closest thing to that.


One thing we could do is change "root podman" to default to an empty config

> 
> * Provide a base for further customizations.

In that empty config we place comments and commented out defaults that can easily be un-commented and edited.

**Comment by rhatdan** [comment]
SGTM

**Comment by giuseppe** [comment]
> > *
> 
> One thing we could do is change "root podman" to default to an empty config

we should support the missing setting but I don' think we should change the default.  We do it to be safe in the case the rundir changes and then you won't be able to see the state of the existing containers.

For example, if you run your containers out of a user session, there is no `/run/user/$UID` available, and podman fallbacks to `/tmp` (*).  We use `/tmp` as it has the sticky bit set so it is safe to create a directory there that other users cannot alter.
If you login with the same user, Podman will suddenly start using `/run/user/$UID`, and all of your existing containers are not visible anymore.

To prevent this issue we write the rundir in the config file so that it will be reused by other podman instances.

(*) We are working on enabling user lingering with rootless podman, so that we are always able to use `/run/user/$UID` but we cannot assume it works everywhere (e.g. it doesn't work on RHEL 7).
