### ISSUE TITLE
Unit tests for play kube

### ISSUE THREAD

**Issue by haircommander** [containers/libpod#3286]
/kind feature
??

We have broken play kube numerous times because we don't really test it.

considering it's a feature that is advertised and promoted, we should probably have tests to stop it from breaking

**Comment by haircommander** [comment]
@rhatdan I can't give this love right now, but it also seems like an accessible task for interns.

please close if I missed a discussion about how this isn't viable.

**Comment by mheon** [comment]
Ideal test flow is probably a test that makes a pod, does a `podman generate kube` of that pod, removes said pod, and imports again with `play kube`, verifying that the appropriate number of containers are created, names are preserved, etc.

**Comment by mheon** [comment]
I got this one - https://github.com/containers/libpod/pull/3293

**Comment by vrothberg** [comment]
I am currently having a hard time running YAML files I find on the web, so I was looking for issues.

#3293 was adding unit tests but those are using podman to generate the YAML files. This is a bit problematic as podman is testing itself and we don't have a predefined behaviour we can test against.

I'd love to have a set of YAML files that we test against in addition to the generate-play cycle tests.
