### ISSUE TITLE
RFE - Create Dockerfile.common for podmanimage Dockerfiles

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#3292]
In #3287  @vrothberg suggested making a Dockerfile.common for the Dockerfiles found in ./contrib/podmanimage rather than having repetitive lines in all three.  Before fully implementing, we need to make sure the quay.io/user/podman account is happy building the images using a Dockerfile that includes another.  I think it will be OK, but it does need to be verified.  Valentin's comment:

```
I wonder if we can decompose the common parts of the Dockerfiles into a shared file and control revisions etc. via env variables. The *.in suffix will allow for including another Dockerfile via the #include directive.

The upstream Dockerfile.in could then look like this:

FROM fedora:latest
ENV GOPATH=...
ENV PODMAN_COMMIT=master
ENV CONMON_COMMIT=master

#include ../Dockerfile.common

The Dockerfile.common Dockerfile could then include everything starting from line 14.
```

If this works here, it would be good to do a similar change in [buildah](https://github.com/containers/buildah/tree/master/contrib/buildahimage)

**Comment by rhatdan** [comment]
SGTM

**Comment by baude** [comment]
@TomSweeneyRedHat updates?

**Comment by TomSweeneyRedHat** [comment]
deep back burner, haven't touched  it yet.

**Comment by TomSweeneyRedHat** [comment]
I read through a ton of Dockerfile stuff today and I can't find an easy way to do an INCLUDE directive.  It's something the Dockerfile maintainers are very much against and they added a `COPY --context` directive that kind of does an include, but you need to split things across directories.  Given that each of our Dockerfiles would only save 3 to 5 lines and they've not changed a bit in the several months since they've been created, I'm going to close this now.  We can reopen if things change later or someone has a brighter idea than I.

**Comment by vrothberg** [comment]
> I read through a ton of Dockerfile stuff today and I can't find an easy way to do an INCLUDE directive. It's something the Dockerfile maintainers are very much against and they added a `COPY --context` directive that kind of does an include, but you need to split things across directories. 

We won't find much information in the Docker docs because that's not supported. But Buildah and Podman use a workaround via the C pre-processor. It's mentioned in our docs (https://github.com/containers/libpod/blob/master/docs/podman-build.1.md). The Dockerfile must be suffixed with `.in` to be pre-processesd.

> Given that each of our Dockerfiles would only save 3 to 5 lines and they've not changed a bit in the several months since they've been created, I'm going to close this now. We can reopen if things change later or someone has a brighter idea than I.

Sounds good to me. Thanks a lot for looking into it!

**Comment by rhatdan** [comment]
We should really make some noice about Dockerfile.in and Buildah.  We should blog on it, and perhaps making it used within the Repo might be a good way to demonstrate it and make sure we don't break it. Even if there is not much to share.

**Comment by vrothberg** [comment]
I blogged on Heise.de about it and also will talk about it on Flock. I can
prepare another blog in English after Flock 👍
