### ISSUE TITLE
CentOS 7 podman rpm not installing

### ISSUE THREAD

**Issue by jlmagee** [containers/libpod#3301]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
The podman-1.4.0 in https://cbs.centos.org/repos/virt7-container-common-testing/x86_64/ has unresolved dependencies.

**Steps to reproduce the issue:**

1. yum install podman* 

2.

3.

**Describe the results you received:**
Error: Package: podman-1.4.0-1.el7.x86_64 (virt7-container-common-candidate)
           Requires: slirp4netns >= 0.3-0
Error: Package: podman-1.4.0-1.el7.x86_64 (virt7-container-common-candidate)
           Requires: runc >= 2:1.0.0-57
           Installed: runc-1.0.0-60.dev.git2abd837.el7.x86_64 (@virt7-container-common-candidate)
               runc = 1.0.0-60.dev.git2abd837.el7
           Available: runc-1.0.0-52.dev.git70ca035.el7_5.x86_64 (extras)
               runc = 1.0.0-52.dev.git70ca035.el7_5
           Available: runc-1.0.0-54.dev.git2abd837.el7.x86_64 (extras)
               runc = 1.0.0-54.dev.git2abd837.el7
           Available: runc-1.0.0-57.dev.git2abd837.el7.centos.x86_64 (extras)
               runc = 1.0.0-57.dev.git2abd837.el7.centos
           Available: runc-1.0.0-59.dev.git2abd837.el7.centos.x86_64 (extras)
               runc = 1.0.0-59.dev.git2abd837.el7.centos

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
NA
```

**Output of `podman info --debug`:**

```
NA
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I've been using podman-1.2 from that repo. I've no way to build a new VM to use podman now.  At least help me find whoever may be able to help with this repo.

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by jlmagee** [comment]
@lsm5 How might we have a better CentOS 7 installation source?

**Comment by lsm5** [comment]
@jlmagee thanks, I'll fix this in a bit

**Comment by lsm5** [comment]
@jlmagee should be fixed with https://cbs.centos.org/koji/taskinfo?taskID=843367 ... let me know if any other issues.

**Comment by jlmagee** [comment]
The yum install works now.  Thanks for the quick response.
