### ISSUE TITLE
ginkgo tests: 'port -l' is racy

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3309]
`test/e2e/port_test.go` runs `nginx` but doesn't actually wait for it to start before running `podman port -l`. This is resulting in test panics:
```
[+0334s] Podman port 
[+0334s]   podman port  -l nginx
[+0334s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:51
[+0334s] [BeforeEach] Podman port
[+0334s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:22
[+0334s] [It] podman port  -l nginx
[+0334s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:51
[+0334s] Running: podman [options] run -dt -P quay.io/libpod/alpine_nginx:latest
[+0335s] 7259c47fa5edb88dfd4c253d2d6e9a016f5feed4749434932379dd1cde5acaa7
[+0335s] Running: podman [options] port -l
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   This is not outputting anything
[+0335s] [AfterEach] Podman port
[+0335s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:32
[+0335s] Running: podman [options] stop -a --timeout 0
[+0335s] 7259c47fa5edb88dfd4c253d2d6e9a016f5feed4749434932379dd1cde5acaa7
[+0335s] Running: podman [options] pod stop -a -t 0
[+0335s] Running: podman [options] pod rm -fa
[+0335s] Running: podman [options] rm -fa
[+0335s] 7259c47fa5edb88dfd4c253d2d6e9a016f5feed4749434932379dd1cde5acaa7
[+0335s] 

[+0335s] â€¢! Panic [1.258 seconds]
[+0335s] Podman port
[+0335s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:15
[+0335s]   podman port  -l nginx [It]
[+0335s]   /var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:51
[+0335s] 
[+0335s]   Test Panicked
[+0335s]   runtime error: index out of range
[+0335s]   /usr/lib/golang/src/runtime/panic.go:513
[+0335s] 
[+0335s]   Full Stack Trace
[+0335s]   	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
[+0335s]   github.com/containers/libpod/test/e2e.glob..func47.5()
[+0335s]   	/var/tmp/go/src/github.com/containers/libpod/test/e2e/port_test.go:59 +0x746
[+0335s]   github.com/containers/libpod/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000f67ce0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[+0335s]   	/var/tmp/go/src/github.com/containers/libpod/test/e2e/common_test.go:88 +0xe0
[+0335s]   testing.tRunner(0xc00013c900, 0x13be480)
[+0335s]   	/usr/lib/golang/src/testing/testing.go:827 +0xbf
[+0335s]   created by testing.(*T).Run
[+0335s]   	/usr/lib/golang/src/testing/testing.go:878 +0x35c
[+0335s]   
```
This is obviously **THE** standard problem with `run -d`; the classic solution (run `podman logs` waiting for well-known string) doesn't work here because there's no log output. One possibility might be to repeat-loop the `podman port -l` until there's actual output. I'd love to submit a PR but I don't speak ginkgo.

**Comment by mheon** [comment]
This is basically what healthchecks are for, I think? Set one up and wait until it goes green?

**Comment by cevich** [comment]
Healthchecks?

I think this is a race in this specific test, though haven't looked at the code yet.

**Comment by mheon** [comment]
We can solve the race by setting up a healthcheck and looping until it goes green, which would indicate that it's ready to proceed

**Comment by mheon** [comment]
Though, honestly... Why do we need the container running? `podman port` just reads the configuration of the container.

**Comment by mheon** [comment]
Hell, why does it need to be nginx? We just need a `podman create -t -i -p 80:80 alpine top` or similar.

**Comment by cevich** [comment]
Some of the tests actually try to connect to the container.

**Comment by cevich** [comment]
All the other failures are in 'podman create'  Perhaps something bad broke there, and the 'podman port' panic's are just another symptom?

**Comment by edsantiago** [comment]
>Why do we need the container running? 

I don't think we do; but `-P` gets its ports from the container config, which means the image has to be pulled and read. Maybe the solution is to split it into `podman create` and then `run`?

**Comment by mheon** [comment]
Hm. Alright, this one's properly strange. It's not a `run` vs `create` issue (I'm still going to swap them over to using `create` for speed) - the container is definitely created, and that's all we need.

Instead, the issue seems to be that the container has no ports. This could be an issue with `podman port` or `podman run` with `-P`.

**Comment by mheon** [comment]
@cevich We're only seeing this flake on the system testing PR from @edsantiago right?

**Comment by mheon** [comment]
Alright, nevermind everything I said. It's as @edsantiago originally predicted - a race between `podman run` starting the container and `podman port`.

I assumed it wasn't because there is no technical reason we need the container to be running for `port` to work, but I ignored Docker compatability - Docker will only print the ports of *running* containers, and we duplicated that.

**Comment by edsantiago** [comment]
Thanks for finding the problem.

As for 'only seeing this', I'm going to go out on a limb and say I've only seen it _on this specific CI run_. All my CI runs fail, and all of them seem to be different failures, but I think I would've noticed the **[Panic]** if I'd seen it before.

**Comment by mheon** [comment]
What we really need here is a generic "wait for container to be ready" call in the Ginkgo machinery - something that uses some mechanism (events, maybe?) to ensure a container is running before proceeding.

**Comment by edsantiago** [comment]
`s/in the Ginkgo machinery/in general for pretty much every situation where I've ever needed podman run -d/`

hashtag maybeanideafor1.5?

**Comment by mheon** [comment]
Outside of the context of tests, we'd really recommend healthchecks (more complex, allows you to check that what's in the container is ready) or events (if you see a start event for the ID the container is running).

**Comment by baude** [comment]
This is what I emailed you about last week with the idea of signals, which I agree is maybe more complex than needed.  The idea of a healthcheck could be one way to do it as well.  It would allow us to use podman function to verify readiness without having to use separate tooling.  The downside is that whatever the healthcheck uses (like curl) needs to be installed in the container.

**Comment by baude** [comment]
fwiw, i self assigned this one and had planned to fix it Monday whenI return from PTO.  do you want/need it fixed faster?

**Comment by mheon** [comment]
I'll leave the faster thing up to @edsantiago 

I really wish we had a better way of triggering stuff on events coming in... Might be worth grabbing Giuseppe and Dan and huddling about ways of doing that without killing performance.

**Comment by mheon** [comment]
(Writing the events thing because it's be super neat if we could easily hook into a single container and trigger things on specific events coming in - solves this easily)

**Comment by edsantiago** [comment]
No rush on my account. I'm thinking of spinning the CI roulette wheel again on my PR and seeing what comes up.
