### ISSUE TITLE
Feature request: port over `docker run --mount type=bind,bind-nonrecursive`

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#3314]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`docker run --mount type=bind,bind-nonrecursive` should be supported, because recursive bind-mount cannot be read-only.
https://github.com/docker/cli/pull/1430

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/3315
