### ISSUE TITLE
Varlink pullimage API should not have fast fail behavior in  case some registry is inaccessible

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#3317]
/kind bug

**Description**
When one of the registries configured in /etc/containers/registries.conf is not secure but it's not listed under insecure registries section, PullImage API fails fast without trying to fetch the requested image from other available registries.
This behavior is not consistent with the podman CLI pull command, which correctly tries to fetch the image from other available registries.

**Steps to reproduce the issue:**

1. Add a inaccessible registry in the regstries.search section in the /etc/containers/registries.conf
For ex:
'localhost:5000'

2. Run the PullImage API:
 $ sudo varlink call unix:/run/podman/io.podman/io.podman.PullImage '{"name": "busybox:latest"}'

**Describe the results you received:**
The API call exited almost immediately with

Error: Varlink Error: Connection Closed

**Describe the results you expected:**
Should pull the image normally

**Additional information you deem important (e.g. issue happens only occasionally):**
Always (don't try with images you already downloaded, since catching might help to bypass the problematic registries)

**Output of `podman version`:**

```
1.4
```

**Comment by baude** [comment]
much like the other issue, there appears to be an issue when not using -m with pull.  We may also have an addition proiblem but this should be fixed first.
