### ISSUE TITLE
varlink Commit API fails with Error: Varlink Error: Connection Closed

### ISSUE THREAD

**Issue by KKoukiou** [containers/libpod#3318]
/kind bug

**Description**

Varlink Commit API fails consistentl with:
 Error: Varlink Error: Connection Closed

**Steps to reproduce the issue:**

1. Create some container for example with
podman run busybox

2. Get the ID of the created container by inspecting the podman ps command output

3. Try to commit the container:
```
sudo varlink call unix:/run/podman/io.podman/io.podman.Commit '{"name": "ecbeb66e204c420479bd5f0625857a96ae3ff8e5aaae5a32e76d91bc49e82d0d", "image_name": "test_commited_busybox"}'
```

**Describe the results you received:**
Exited with:
Error: Varlink Error: Connection Closed

No image was created

**Describe the results you expected:**
Same as with podman CLI commit command the commited container should create a new image.

For comparison I ran on the same container the podman commit command and it succeded:
```
sudo podman commit ecbeb66e204c420479bd5f0625857a96ae3ff8e5aaae5a32e76d91bc49e82d0d test_commited_busybox
```

**Output of `podman version`:**

```
1.4
```

**Comment by baude** [comment]
Does it work if you provide all the attributes described by the API?

https://github.com/containers/libpod/blob/master/API.md#Commit

**Comment by KKoukiou** [comment]
> Does it work if you provide all the attributes described by the API?
> 
> https://github.com/containers/libpod/blob/master/API.md#Commit

No. I tried to pass everything and it still does not work, but anyway, the only required are the two I used above, https://github.com/containers/libpod/blob/master/API.md#func-commit

**Comment by baude** [comment]
the backtrace suggests:

```
/home/bbaude/git/src/github.com/containers/libpod/pkg/varlinkapi/images.go:550
```
If you use the varlink call with -m (more), it works.

**Comment by KKoukiou** [comment]
@baude verified that it works with `-m`.
This behaviour must have changed though between 1.3 and 1.4.
So now all method that return a MoreResponse need to be called with a more = true parameter?

**Comment by KKoukiou** [comment]
@baude this is still broken on 2:1.4.4-1.fc30 FYI
