### ISSUE TITLE
podman logs -f: hangs forever as nonroot

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3325]
```
$ podman run --rm -d --name c1 alpine sh -c 'echo a;sleep 10;echo b'
9151e85b082d578aaa8cd771518cb6ed54c8b2ded72471edf166490eefcabd85
$ podman logs -f c1
a
b
```
This now hangs forever (podman @ master). Works as expected (exits when container exits) when run as root.

Caught by BATS tests.

**Comment by mheon** [comment]
Rough timeframe on when this broke? Between the last release that went into 8 and now?

**Comment by edsantiago** [comment]
I'm guessing the last 2 days; I'm pretty sure I ran my bats tests on master on Tuesday. But it might've been Monday.

**Comment by mheon** [comment]
Alright, definitely not the changes I was thinking, then...

**Comment by edsantiago** [comment]
git bisect blames: 629017bb197bcda31ac129fb712ba3c6917b100b , and my manual testing confirms, but that makes no sense....

**Comment by mheon** [comment]
Uh... huh...
Alright that one's strange.

**Comment by giuseppe** [comment]
that commit has broken many other things with rootless containers.  If you try your command twice, you'll see it will fail twice as c1 is not removed despite `--rm` being passed.

https://github.com/containers/libpod/pull/3328 is fixing this issue too

**Comment by baude** [comment]
@giuseppe mind adding some integration tests for some of those things that were broken?  it might help us in the future? if time is a concern, then lets list what they should be and between the interns and I, maybe we can write them?

**Comment by giuseppe** [comment]
this issue could be easily detected with the test I've added here: https://github.com/containers/libpod/pull/3347

**Comment by edsantiago** [comment]
Confirmed as fixed.
