### ISSUE TITLE
podman inspect on stopped container: inconsistent status

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3326]
At some recent point, podman inspect started reporting 'stopped' for nonroot and 'exited' for root:

```
$ podman run -d --name foo alpine sleep 60;podman stop foo;podman inspect --format '{{.State.Status}}' foo
003cdf7dc49ebaff3261c05ed1cc928e26383f5b065b5f835b30a1e909aaffbd
003cdf7dc49ebaff3261c05ed1cc928e26383f5b065b5f835b30a1e909aaffbd
stopped
```

```
# podman run -d --name foo alpine sleep 60;podman stop foo;podman inspect --format '{{.State.Status}}' foo
2a5a082ef5dee2babb0ef4597984f640dd5e35194788c21f025399ca792e9991
2a5a082ef5dee2babb0ef4597984f640dd5e35194788c21f025399ca792e9991
exited
```

Caught by BATS tests (which expect, and have long expected, 'exited')

**Comment by mheon** [comment]
Uh-oh.

It seems like cleanup processes aren't firing for rootless again.

@giuseppe PTAL

**Comment by mheon** [comment]
We might have also broken `--syslog` at some point, which was the only way of debugging these things, so that's fun

**Comment by mheon** [comment]
It's mount options - the PR from @rhatdan that disabled mount options if a new storage driver was specified.

It's wiping the fuse-overlayfs path so it tries to use kernel overlayfs.

**Comment by edsantiago** [comment]
Wow. Thanks for identifying. This has been a surreal gremliny week, it's comforting to know that there's a logical explanation for this one.
