### ISSUE TITLE
podman 1.4.0 requires apparmor module active in kernel

### ISSUE THREAD

**Issue by bvdeenen** [containers/libpod#3331]
Using podman on Void Linux, I found that apparmor needs to be installed, and activated in the kernel in order to `podman run` any image. When not enabled in the kernel, it `podman run` will abort with an `broken pipe` error. 

Enabling apparmor in the kernel (adding `apparmor=1 security=apparmor` to the kernel command line) was enough to make the issue go away.
Full details on the [void linux reddit page: ](https://www.reddit.com/r/voidlinux/comments/c0a2gh/podman_broken_pipe_for_all_containers/)

**Comment by mheon** [comment]
@vrothberg Mind taking a look here?

**Comment by rhatdan** [comment]
@bvdeenen most of us are much more experienced with SELinux then Apparmor.  Any chance you could look at the code and Open a PR?

**Comment by vrothberg** [comment]
I just had a look and believe to have a fix. I'll wrap up a PR, so you can test if that solves the issue.

**Comment by vrothberg** [comment]
https://github.com/containers/libpod/pull/3334 should do the trick. I am currently restricted with bandwidth and cannot set up a new VM for testing.

**Comment by bvdeenen** [comment]
I'll have a look in a few hours. I'm travelling and on a very limited bandwidth, so I'm not sure I can build runc. Depends on how much stuff I have to pull in.
