### ISSUE TITLE
Support, or at least just ignore, Docker Volume :delegated option

### ISSUE THREAD

**Issue by vorburger** [containers/libpod#3340]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

[Docker, apparently, supports](https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated) Volume options `:cached` and `:delegated` and I've run into this Podman failing with `Error: invalid option type "delegated"` on a `docker run ... -v /cache:/cache:delegated` which (presumably) works in "real" Docker; see https://github.com/kubernetes/test-infra/issues/13044.

**Steps to reproduce the issue:**

1. Install Fedora 30 Server
1. sudo dnf install podman-docker
1. git clone https://github.com/kubernetes/test-infra.git
1. git clone https://github.com/kubernetes/kubernetes.git 
1. cd kubernetes
1. ../test-infra/planter/planter.sh bazel build //cmd/kubectl

see https://github.com/kubernetes/test-infra/issues/13044

**Describe the results you received:**
Works like Docker.

**Describe the results you expected:**
Fails with `Error: invalid option type "delegated"` (actually first with `Error: Invalid --security-opt 1: "label:disable"` but https://github.com/kubernetes/test-infra/pull/13045 takes care of that).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.3.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.2
  podman version: 1.3.1
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.1-1.git7210727.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: c9a4c48d1bff85033b7fc9b62d25961dd5048689'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 13008052224
  MemTotal: 33585057792
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 16859000832
  SwapTotal: 16859000832
  arch: amd64
  cpus: 8
  hostname: toby
  kernel: 5.1.6-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 153h 43m 38.99s (Approximately 6.38 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/vorburger/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/vorburger/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /tmp/1000
  VolumePath: /home/vorburger/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by rhatdan** [comment]
Looks like these flags are more for podman remote, we might just want to allow them and ignore them on podman local.
https://docs.docker.com/docker-for-mac/osxfs-caching/

https://docs.docker.com/v17.09/engine/admin/volumes/bind-mounts/#choosing-the--v-or-mount-flag
```
The consistency option, if present, may be one of consistent, delegated, or cached. This setting only applies to Docker for Mac, and is ignored on all other platforms.
```

**Comment by vorburger** [comment]
Right, makes sense now, so the key point here is:

> This setting only applies to Docker for Mac, and is ignored on all other platforms.

FYI I hit this error while running [this kubernetes/test-infra/planter/planter.sh script](https://github.com/kubernetes/test-infra/blob/297f03c3de37a4545ec02e398d03e0d2ef6e943d/planter/planter.sh#L95) on Fedora 30 ... looks like they just always add `:delegated`, because somone found it does something useful for Mac users, and `docker run` apparently ignores it elsewhere - ergo so should `podman run`.

**Comment by mheon** [comment]
Working this one now.
