### ISSUE TITLE
The "args" attribute to "when" is not documented in oci-hooks.5.md

### ISSUE THREAD

**Issue by eriksjolund** [containers/libpod#3342]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

Inconsistent information about the allowed attributes to `when` in the online documentation

https://github.com/containers/libpod/blob/master/pkg/hooks/docs/oci-hooks.5.md#100-hook-schema-1

There is an example where `args` is used as an attribute to `when`

```console
$ cat /etc/containers/oci/hooks.d/oci-systemd-hook.json
{
  "version": "1.0.0",
  "hook": {
    "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
  }
  "when": {
    "args": [".*/init$" , ".*/systemd$"],
  },
  "stages": ["prestart", "poststop"]
}
```
---

But   `args` is not listed as one of the allowed attributes to `when`  here

---

`when` (required object)
  Conditions under which the hook is injected.  The following properties can be specified, and at least one must be specified:

  * `always` (optional boolean)
      If set `true`, this condition matches.
  * `annotations` (optional object)
      If all `annotations` key/value pairs match a key/value pair from the configured annotations, this condition matches.
      Both keys and values must be POSIX extended regular expressions.
  * `commands` (optional array of strings)
      If the configured `process.args[0]` matches an entry, this condition matches.
      Entries must be POSIX extended regular expressions.
  * `hasBindMounts` (optional boolean)
      If `hasBindMounts` is true and the caller requested host-to-container bind mounts, this condition matches.

**Comment by rhatdan** [comment]
Please open a PR to fix this, if you could.

**Comment by eriksjolund** [comment]
Ok, I gave it a try. It seems "args" should not be documented because it was a mistake.
I replaced it with "commands".

https://github.com/containers/libpod/pull/3365

**Comment by eriksjolund** [comment]
#3365 was merged.
