### ISSUE TITLE
What should I import to use API ?

### ISSUE THREAD

**Issue by redcap52** [containers/libpod#3343]
In your docs you said that you have an API for Golang. So, what path should I import to use CreateContainer()  method ?

**Comment by mheon** [comment]
To confirm, we're talking about the Golang API, not the Varlink one, correct?

For the Go API:

Our core API functions live in `github.com/containers/libpod`, with image functions specifically available in the `github.com/containers/libpod/image` subpackage.

Also note that any code calling into Libpod via the Go API must contain the following bit of code somewhere early in main (necessary to make containers/storage work properly):
https://github.com/containers/libpod/blob/master/cmd/podman/main.go#L144-L146

**Comment by mheon** [comment]
@baude I'm fairly certain this one is Varlink, though. There's no CreateContainer endpoint in the Go code, we call it `NewContainer()` there.

**Comment by baude** [comment]
@redcap52 can you please clarify your question here given @mheon's answer?

**Comment by towe75** [comment]
@redcap52  maybe you want to have a look at my related question in https://github.com/containers/libpod/issues/3445

I endet up with this working example program:

```
package main

import (
	"context"

	"github.com/containers/storage/pkg/reexec"
	"github.com/containers/libpod/libpod"
	"github.com/sirupsen/logrus"
)

func main() {

	if reexec.Init() {
		return
	}

	logrus.SetLevel(logrus.TraceLevel)
	logrus.Info("Getting Runtime")

	ctx := context.TODO()
	runtime, err := libpod.NewRuntime(ctx)
	if err != nil {
		logrus.Fatal("Error creating runtime", err)
		return
	}

	containers, err := runtime.GetContainers()
	if err != nil {
		logrus.Fatal("Error listing containers", err)
		return
	}

	for _, c := range(containers) {
		logrus.Info("Found container: ", c.Name())
	}

	runtime.Shutdown(false)

}
```

@baude it would be nice to have some small api example like this in the docs, what do you think?
Obviously it's hard to get started on this topic.

**Comment by baude** [comment]
@redcap52 re-open as needed.
