### ISSUE TITLE
SVG logos shouldn't use text or tspan

### ISSUE THREAD

**Issue by dankohn** [containers/libpod#3350]
Compare https://github.com/containers/libpod/blob/master/logo/podman-logo-source.svg and https://github.com/containers/libpod/blob/master/logo/podman-logo.png on a computer that doesn't have the font Montserrat installed and you can see that the SVG doesn't render correctly.

We converted the font text to be objects so that it renders correctly on all computers. See https://github.com/cncf/landscape#proper-svgs

The updated logo is at https://landscape.cncf.io/logos/podman.svg. I recommend either replacing https://github.com/containers/libpod/blob/master/logo/podman-logo-source.svg or adding it alongside if you want to keep all the Inkscape info in the file.

Also note that Podman is now in the CNCF Landscape: https://landscape.cncf.io/category=application-definition-image-build&format=card-mode&grouping=category&selected=podman

Cc @alexcontini

**Comment by rhatdan** [comment]
Thanks @dankohn I would love to pursue getting Podman donated to CNCF...
Could you open a PR to replace the image?

**Comment by TomSweeneyRedHat** [comment]
FYI @mairin

**Comment by mairin** [comment]
the podman logotype is actually meant to be a bit thicker with the man in grey instead of black, see attached:

![podman-final](https://user-images.githubusercontent.com/799683/59683251-d3c44f00-91a5-11e9-921c-29e65f927176.png)

I can submit the svg as a separate PR

**Comment by dankohn** [comment]
LGTM. SVGs can be tricky.

**Comment by mairin** [comment]
hey the wrong version got merged, can this be reopened?

**Comment by mheon** [comment]
Done

**Comment by mheon** [comment]
With both PRs here merged, I think we're good on updating the logo. Closing as such.
