### ISSUE TITLE
RFE: podman getconfig <container>

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#3351]
/kind feature

Instead of using ``podman inspect`` command to get an image or a container's config (which is expensive due to the database access and the locks), we could have a command which only access to the Config field.

The command would output the same thing as ``podman inspect --format "{{index .Config}}"<container>``.

**Comment by rhatdan** [comment]
Extended commands like should be in the 
```
podman container config 
podman image config
```

**Comment by EmilienM** [comment]
I just realized that for me needs, I can use ``podman ps -a --format "{{.Image}}" --filter label=container_name=memcached`` to get the infos that I need instead of the inspect.

I guess I can close it since podman ps seems to provide that easily?
