### ISSUE TITLE
Do you support Weave network?

### ISSUE THREAD

**Issue by drrford** [containers/libpod#3389]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

Hello. Do you have [Weave network ](https://www.weave.works/docs/net/latest/overview/) support? Weave network has a CNI plugin. This plugin provides Kubernetes support for Weave network. So, I want to know how to use Weave network with Podman.

**Comment by mheon** [comment]
I don't believe anyone has ever tested this, but if Weave provides a CNI plugin, it should work - Podman exclusively uses CNI for networking.

**Comment by mheon** [comment]
Actually, I should rephrase that.

We use CNI, but only for root-owned containers.

When not running as root, we don't have the privileges to invoke CNI, and thus use slirp4netns.

So I believe Weave will work, but only for root-owned containers.

**Comment by rhatdan** [comment]
It should work, and if it does not it is probably a bug.  Reopen this issue if that is the case.
