### ISSUE TITLE
hostname not added to /etc/hosts in rootless mode

### ISSUE THREAD

**Issue by fkaempfer** [containers/libpod#3405]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

I think this is a bug, if it is not intended to work like this.

**Description**

**Steps to reproduce the issue:**

1. $ podman run --hostname=hello alpine:latest cat /etc/hosts

**Describe the results you received:**
An exact copy of the host's /etc/hosts file is displayed, it does not include the container's hostname entry

**Describe the results you expected:**
It should include a line like this:
10.88.0.2       hello

**Additional information you deem important (e.g. issue happens only occasionally):**
If you run the command as root the host entry is correctly added, in root-less mode it is missing.

**Output of `podman version`:**
```
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.11.10
OS/Arch:            linux/amd64

```
I'm using Fedora 29. I tried also with the latest dev snapshot on another machine with the same result.

**Output of `podman info --debug`:**
**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.10
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: podman-1.4.0-2.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 80f19b1591b03dbbc53bf28b154230c7ea372281'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 6912102400
  MemTotal: 16733937664
  OCIRuntime:
    package: runc-1.0.0-92.dev.gitc1b8c57.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc7+dev
      commit: 7f820969cc1cc8ea3357b39f2e2e1514f71c6fec
      spec: 1.0.1-dev
  SwapFree: 8472489984
  SwapTotal: 8472489984
  arch: amd64
  cpus: 8
  hostname: *****
  kernel: 5.0.17-200.fc29.x86_64
  os: linux
  rootless: true
  uptime: 2h 12m 38.44s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/******/.config/containers/storage.conf
  ContainerStore:
    number: 61
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/bin/fuse-overlayfs
  GraphRoot: /home/****/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 64
  RunRoot: /tmp/1000
  VolumePath: /home/*******/.local/share/containers/storage/volumes

```
I can provide this as needed, but I think this should be universally reproducible (at least somebody I asked on IRC yesterday had the exact same result).

Similar issue: https://github.com/containers/libpod/issues/1745

The same problem exists for podman build. But there is an additional/separate issue here: /etc/hostname is not set correctly during podman build, even in root mode. In docker this all works as expected.

To test:

```
FROM alpine:latest
RUN cat /etc/hostname /etc/hosts
```
Compare
```
docker build .
podman build .
```

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
opened a PR here: https://github.com/containers/libpod/pull/3406
