### ISSUE TITLE
complaining about missing "loginctl" systemd binary

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#3410]
/kind bug

running rootless gives warning (no "loginctl" is available in $PATH):

```
WARN[0000] cannot run `loginctl enable-linger` for the current user: exec: "loginctl": executable file not found in $PATH`
```

Maybe you can check for the presence of `/bin/loginctl`, or something ?

https://github.com/containers/libpod/blob/master/pkg/rootless/rootless_linux.go#L201_L211

**Comment by mheon** [comment]
We should probably make the loginctl call dependent on the system being systemd-booted. If it is, we should warn if it fails (we need to ensure that the rootless pause process remains alive, so we need loginctl). If the system isn't using systemd, there's no point to the call anyways.

**Comment by giuseppe** [comment]
I am addressing this issue as part of https://github.com/containers/libpod/pull/3397
