### ISSUE TITLE
can't talk to a V1 docker registry 

### ISSUE THREAD

**Issue by michael-read** [containers/libpod#3416]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
Can't pull images from `hub.docker.com`:
```
podman run -i -t openjdk:8-jre-alpine /bin/sh
Trying to pull hub.docker.com/openjdk:8-jre-alpine...ERRO[0000] Error pulling image ref //hub.docker.com/openjdk:8-jre-alpine: Error initializing source docker://hub.docker.com/openjdk:8-jre-alpine: can't talk to a V1 docker registry 
Failed
Error: unable to pull openjdk:8-jre-alpine: 1 error occurred:
	* Error initializing source docker://hub.docker.com/openjdk:8-jre-alpine: can't talk to a V1 docker registry
```

1. `podman run -i -t openjdk:8-jre-alpine /bin/sh`
```
**Describe the results you received:**
Trying to pull hub.docker.com/openjdk:8-jre-alpine...ERRO[0000] Error pulling image ref //hub.docker.com/openjdk:8-jre-alpine: Error initializing source docker://hub.docker.com/openjdk:8-jre-alpine: can't talk to a V1 docker registry 
Failed
Error: unable to pull openjdk:8-jre-alpine: 1 error occurred:
	* Error initializing source docker://hub.docker.com/openjdk:8-jre-alpine: can't talk to a V1 docker registry
```

**Describe the results you expected:**
I expected it to pull the image and run it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "16.04"
  MemFree: 6353059840
  MemTotal: 16697331712
  OCIRuntime:
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 17060327424
  SwapTotal: 17060327424
  arch: amd64
  cpus: 8
  hostname: hpspectre
  kernel: 4.15.0-52-generic
  os: linux
  rootless: true
  uptime: 2h 42m 23.2s (Approximately 0.08 days)
registries:
  blocked: null
  insecure:
  - default-route-openshift-image-registry.apps.lightbend412.coreostrain.me
  - image-registry.openshift-image-registry.svc:5000
  search:
  - hub.docker.com
store:
  ConfigFile: /home/michael/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/michael/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /tmp/1000
  VolumePath: /home/michael/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox is installed on my machine

**Comment by mheon** [comment]
I believe 1.4.0 has the sysregistriesv2 work...
@mtrmac PTAL - I suspect this is in c/image

**Comment by mtrmac** [comment]
Isn’t this just a simple configuration error?

@michael-read Did you specifically intend to make the search path use `hub.docker.com`, or just the common Docker Hub, which uses the `docker.io` hostname?

Notably `docker://docker.io/openjdk:8-jre-alpine` does exist and can be reached.

---

As for the V1 protocol:

c/image has never supported the v1 protocol (which is so dead that the server repository has been removed, and I can’t even quickly find a specification); Docker has removed it from recent versions of its product as well.

It’s _extremely_ unlikely that we would be working on implementing that protocol at this stage.

At best, I can imagine someone contributing a new transport (`docker-v1`?) that could be maintained without interfering with the v2 client.

But, really, why bother? Per https://engineering.docker.com/2019/03/registry-v1-api-deprecation/ even the Docker hub has supposedly stopped serving content using that protocol already.

**Comment by michael-read** [comment]
Yes, so there was no default set, so I just added the following to the config:
[registries.search]
registries = ['hub.docker.com']

Should it be something else like docker.io? Maybe I'll give that a try.

**Comment by michael-read** [comment]
okay, I changed it to docker.io. Maybe that should be configured as the default during installation.

Now I have another error:
```
Trying to pull docker.io/library/openjdk:8-jre-alpine...Getting image source signatures
Copying blob e7c96db7181b done
Copying blob b6abafe80f63 done
Copying blob f910a506b6cb done
Copying config f7a292bbb7 done
Writing manifest to image destination
Storing signatures
ERRO[0010] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
```
I guess I need to find `slirp4netns`, and get it installed. Would have thought the default install would have set up any required dependencies.

**Comment by rhatdan** [comment]
What are you installing on?  All of this is setup correctly if you install on Fedora, Centos, RHEL, and I believe it should work correctly in Ubuntu, SUSE.

If you are building and installing from hand, then you need to handle the required packages.

**Comment by michael-read** [comment]
Ubuntu 16.04 LTS

**Comment by rhatdan** [comment]
Did you get the packages from the PPC?

**Comment by michael-read** [comment]
I just used:
```
sudo apt install slirp4netns
```
However now, when trying:
```
podman run -i -t openjdk:8-jre-alpine /bin/sh
```
I just get a prompt, without an error:
```
/ # 
```
It appears Podman hasn't been tested on Ubuntu 16.04 LTS.

**Comment by rhatdan** [comment]
Are you in a container when the prompt completes?

**Comment by michael-read** [comment]
okay, my apologies. It does appear that I'm in the container. Closing. Thanks for the help!

**Comment by mcman2017** [comment]
Got this same error running the below on RHEL8 rootless:
podman search registry.access.redhat.com/rhel8

error:
ERRO[0022] error searching registry "registry.access.redhat.com": couldn't search registry "registry.access.redhat.com": can't talk to a V1 docker registry

This was resolved by adding docker.io to the [registries.search].  For rootless, this is in the config file,
$HOME/.config/containers/registries.conf : 
[registries.search]
registries = ['registry.access.redhat.com', 'registry.redhat.io', 'docker.io']

Simple (but not obvious) fix.

**Comment by mheon** [comment]
What distribution are you using that does not have `docker.io` in there by default?

**Comment by mtrmac** [comment]
- As a general practice, please file new issues instead of piling onto closed ones, especially if the details don’t _exactly_ match.
- It’s _extremely_ unlikely that the search path has anything to do with the `registry.redhat.io` failure; `skopeo` _never_ uses the search path for any purpose, to my knowledge. My guess is that the registry in question had a partial outage, where the V2 server was unavailable but the apparently-existing V1 stub continued to be served.
