### ISSUE TITLE
Questions about podman 1.4.3

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#3433]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently podman 1.4.0 released via package on atomic ppa.  However 1.4.3 is already in release. 
One of the features is a much better performance in I/O heavy environments.
1.  What does it mean compared to 1.3.2?  I currently run ceph in podman and it is I/O intensive.
2.  Will 1.4.3 package built any time soon?

**Comment by mheon** [comment]
I'll poke @lsm5 about a fresh release on the PPA.

On a test system with 100% pegged I/O on the partition Podman was using, we saw execution times for simple Podman commands go down from ~90 seconds to ~4 seconds. This is mostly accomplished through streamlining the fastpath - there are still many things which will cause slower performance (for example, launching containers will not be significantly sped up - but commands like `ps` or `inspect` will be).

**Comment by alitvak69** [comment]
@mheon: Any updates on 1.4.3?

**Comment by lsm5** [comment]
building now..

**Comment by alitvak69** [comment]
@lsm5 the build doesn't appear on PPA yes

**Comment by lsm5** [comment]
On Thu, Jun 27, 2019 at 10:14:21AM -0700, alitvak69 wrote:
> @lsm5 the build doesn't appear on PPA yes

It will, once it's done, fighting some other fires too, I'll let you know once
the build is ready


-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by mritd** [comment]
Can we build our own debian package? I also need to upgrade podman to version 1.4.2, but only 1.4.0 in ppa.

**Comment by lsm5** [comment]
I just built 1.4.3 for 18.04 (16.04 to follow), should be published in a bit.

@mritd in case you're interested in building your own or if you want to package it for vanilla debian, untar [this tarball](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+sourcefiles/podman/1.4.3-1~ubuntu18.04~ppa1/podman_1.4.3-1~ubuntu18.04~ppa1.tar.xz) and look in the `debian/` directory.

**Comment by mritd** [comment]
@lsm5 Thank you for your help.

I am not familiar with the debian package build, I just used [fpm](https://github.com/jordansissel/fpm) to create the debian package. Does the official have tools such as scripts for quickly creating installation packages for different Linux distributions? (e.g. `make package`)
