### ISSUE TITLE
podman-1.3.2-1 busts --tmpfs=/var

### ISSUE THREAD

**Issue by caffeinejolt** [containers/libpod#3434]
I just noticed all my podman containers failed to come back up after the podman-1.3.2-1 release to RHEL 7.  I had to remove --tmpfs=/var...options in order to get podman to start without error... but that breaks things for those of us running systemd in a container... or depending on /var being a tmpfs for anything else.

I had previously posted about this in issue #2996

Anyways, this release is DOA for me at least - will try some workarounds before downgrading.

**Comment by mheon** [comment]
Can you get specific error messages?

**Comment by caffeinejolt** [comment]
Error: container create failed: container_linux.go:336: starting container process caused "process_linux.go:399: container init caused \
"rootfs_linux.go:58: mounting \\\"tmpfs\\\" to rootfs \\\"/srv/machines/roots/php54/root\\\" at \\\"/tmp/runctop604820653/runctmpdir9856
91176\\\" caused \\\"tmpcopyup: failed to copy /srv/machines/roots/php54/root/var to /tmp/runctop604820653/runctmpdir985691176: write /t
mp/runctop604820653/runctmpdir985691176/cache/yum/x86_64/7/epel/gen/primary_db.sqlite: no space left on device\\\"\""

**Comment by caffeinejolt** [comment]
May be worth noting I am using --rootfs  --rm=true --read-only

**Comment by mheon** [comment]
Tmpcopyup is running out of space copying up the contents of `/var/` - eek.

**Comment by caffeinejolt** [comment]
There are other problems too...  the above error message is what I get if I use just --tmpfs /var  which I was only using to test out the new podman.  If I use what I want to actually use: --tmpfs=/var:rw,nosuid,nodev,size=524288000  I get this error: Error: nosuid: duplicate mount destination

**Comment by mheon** [comment]
That looks like a parsing error on our end - from the error format, it seems like we're actually trying to mount to `/nosuid` in the container, instead of parsing it as an option. Double eek.

**Comment by caffeinejolt** [comment]
I only get the "parsing error"  with both specified:  --tmpfs=/var:rw,nosuid,nodev,size=524288000   --tmpfs=/tmp:rw,nosuid,nodev,size=524288000

**Comment by caffeinejolt** [comment]
Ok - if I remove /var/lib/cache from my --rootfs image (uses 133MB - yum related it seems), I can get --tmpfs=/var:rw,nosuid,nodev,size=524288000 to work

Which is weird... but I can at least work with that.

Leaving the inability to to specify both --tmpfs=/var:rw,nosuid,nodev,size=524288000 --tmpfs=/tmp:rw,nosuid,nodev,size=524288000 as the remaining problem....

**Comment by mheon** [comment]
I can duplicate the parse error as follows:

`sudo ./bin/podman run -t -i --tmpfs=/var:rw,nosuid,nodev,size=524288000 --rm --tmpfs=/tmp:rw,nosuid,nodev,size=524288000 --read-only fedora bash`

(ignore the bin/podman here, that's my development copy)

Looking into it

**Comment by mheon** [comment]
It's StringArray vs StringSlice again.

@baude We have to do a survey for this, it's broken us a lot.

**Comment by mheon** [comment]
Fix for the parsing issue in #3435

**Comment by caffeinejolt** [comment]
Just using  --tmpfs=/tmp:size=524288000 works and results in the nosuid,nodev,noexec stuff defaults - so I have a workaround for that too now.

I know that podman is considered "experimental" in RHEL7 - so breakage on updates is to be expected, but I need to get this stuff in production soon - so am considering excluding podman from auto yum updates.  Any idea as to when/if it will be out of experimental status?

**Comment by caffeinejolt** [comment]
Actually - using --tmpfs=/tmp:size=524288000  --tmpfs=/var:size=524288000

Works without having to remove /var/cache as specified above - seems to indicate all of the above is parser related
