### ISSUE TITLE
Podman pause hangs the system during shutdown

### ISSUE THREAD

**Issue by QazerLab** [containers/libpod#3440]
Note: first I wanted to post a PR with a fix, but then doubted, because this problem is too easy to reproduce and probably could not be overlooked. Opening an issue to confirm that this really should be treated as a bug.

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
BUG REPORT

/kind bug

**Description**

[This commit](https://github.com/containers/libpod/commit/ce26aa701f5d49b3aaac08b34b1fbc1492067f46) introduced blocking signals for pause process. However, `SIGTERM` is also blocked. The pause process usually runs till the system shutdown, which means that this process hangs the init system for a while during the shutdown (e.g. on my box this grace period is 90 seconds) before the process gets killed by `SIGKILL`:

```
systemd[1]: session-1.scope: Killing process 2195 (podman pause) with signal SIGKILL.
```

**Steps to reproduce the issue:**

1. Work with latest `podman`.
2. Start shutting the system down.

**Describe the results you received:**

Systemd waits for a while before killing the pause process with `SIGKILL`.

**Describe the results you expected:**

Pause process is terminated gracefully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.4.1
RemoteAPI Version:  1
Go Version:         go1.12.5
Built:              Sat Jun 15 22:06:07 2019
OS/Arch:            linux/amd64
```

Also checked with manually built latest sources.

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.5
  podman version: 1.4.1
host:
  BuildahVersion: 1.8.4
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 0.3.0, commit: 8455ce1ef385120deb827d0f0588c04357bad4c4'
  Distribution:
    distribution: arch
    version: unknown
  MemFree: 9574285312
  MemTotal: 16195624960
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 4
  hostname: qazer
  kernel: 5.1.9-arch1-1-ARCH
  os: linux
  rootless: true
  uptime: 3h 17m 43.81s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/qazer/.config/containers/storage.conf
  ContainerStore:
    number: 7
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/qazer/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
  VolumePath: /home/qazer/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
@QazerLab thanks for the report, I think it makes sense to not block SIGTERM.

If you already have a patch, could you please open a PR?

**Comment by QazerLab** [comment]
@giuseppe yep, will PR it few hours later.
