### ISSUE TITLE
rootless: Enable rootless containers by default with user UIDs/GIDs to 65535 in /etc/subxid

### ISSUE THREAD

**Issue by jwflory** [containers/libpod#3441]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It is difficult to enable rootless containers in an environment where there might be hundreds or even a thousand unique users connecting to a host (e.g. HPC clusters). It requires adding all usernames to the `/etc/sub{u,g}id` files. Maintaining this list of users is difficult and needs caution to avoid overlapping namespaces.

For _some_ environments, it could be useful to support a feature where libpod will fill the `/etc/sub{u,g}id` files with actual UIDs (vs. login names) and safely create the mappings up to the default maximum value (`65535`) or maybe a configurable value/range. Using the numerical UIDs seems like one way to enable rootless containers in a very large computing environment without significant configuration work to support it. Using numerical UIDs avoids human error for conflicting namespaces.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is probably more useful as a non-default configuration option. I only anticipate people looking for this if they know they need it.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I expect this use case is highly specific to large-scale HPC environments using software like [Slurm](https://slurm.schedmd.com/) or [Univa GridEngine](https://en.wikipedia.org/wiki/Univa_Grid_Engine) supporting large numbers of users across a distributed number of nodes. But it would be interesting to make containers more accessible to this kind of use case, and I don't see an easy way of doing that without rootless containers.

**Comment by rhatdan** [comment]
I have opened bugs to support managing the /etc/subuid and /etc/subgid files via nsswitch, which should get us closer to what you want.

**Comment by giuseppe** [comment]
I think it could be solved in the immediate future if we enhance newuidmap/newgidmap to allow a static assignment for the additional UIDs/GIDs.

It can be easily done by choosing a range of system users that are allowed to get additional IDs, then split equally the remaining IDs to these system users.

Let's say we pick 0-65536 as the system users range, we have `4294901760` IDs more that we can assign.  In this setup each user in the 0-65536 gets 65535 additional IDs, starting at 65536.

@ebiederm @hallyn what do you think about this idea?  Is it something we could do in shadow-utils?

**Comment by jwflory** [comment]
> I have opened bugs to support managing the /etc/subuid and /etc/subgid files via nsswitch, which should get us closer to what you want.

@rhatdan Do you have links to those bugs I could follow too?

**Comment by rhatdan** [comment]
https://github.com/shadow-maint/shadow/issues/154
Also internal email conversation with glibc developers.

**Comment by ebiederm** [comment]
Giuseppe Scrivano <notifications@github.com> writes:

> I think it could be solved in the immediate future if we enhance
> newuidmap/newgidmap to allow a static assignment for the additional
> UIDs/GIDs.
>
> It can be easily done by choosing a range of system users that are
> allowed to get additional IDs, then split equally the remaining IDs to
> these system users.
>
> Let's say we pick 0-65536 as the system users range, we have
> 4294901760 IDs more that we can assign. In this setup each user in the
> 0-65536 gets 65535 additional IDs, starting at 65536.
>
> @ebiederm @hallyn what do you think about this idea? Is it something
> we could do in shadow-utils?

I think that is already the default policy in Ubuntu.  Unless I am
misunderstanding the suggestion this is already supported and the
configuration knobs just need to be set appropriately on the distro's
you care about.

The user addition takes care of allocationg subordinate uids and adding
them to /etc/subuid, ditto for /etc/subgid.

Or am I not understanding the suggestion?

Eric

**Comment by giuseppe** [comment]
Fedora does that automatically as well, every new user gets 65k additional users.

What I am suggesting is to make the mapping function of the UID, not the user name, perhaps enabling this configuration through a new conf file.  The mapping function `UID -> additional ranges` won't require any lookup in the user DB to find the user name and in `/etc/subuid` to find the ranges allocated to that user.

In this way we will enable something like:

```
$ sudo chroot --userspec 1100:1100 / sh
sh-5.0$ unshare -U sleep 100 &
[1] 2637
sh-5.0$ newuidmap $! ....
newuidmap: Cannot determine your user name.
```

**Comment by SEJeff** [comment]
I just attempted (unsuccessfully) to just put uids into `/etc/subuid` in place of usernames so I could trivially template it for a large range of users. If it supported both, like the `id` command or something, that should be enough to trivially just auto-generate it.

I like your idea from a pragmatic standpoint @giuseppe.

**Comment by hallyn** [comment]
Hm, supporting uids in /etc/subuid should be simple and I don't see any issues with that.  If that helps you, I don't mind accepting or writing a patch to that effect.

**Comment by SEJeff** [comment]
@hallyn my C is a bit rusty but I might take a stab at this. It would be a fun and simple one, thanks!

**Comment by giuseppe** [comment]
> Hm, supporting uids in /etc/subuid should be simple and I don't see any issues with that. If that helps you, I don't mind accepting or writing a patch to that effect.

interestingly, it seems to already work that way.  We will need to adapt Podman to do the lookup in the same way when requesting a range

**Comment by giuseppe** [comment]
@SEJeff could you try if https://github.com/containers/storage/pull/376 is enough to solve the issue?  We need to re-vendor containers/storage in podman

**Comment by hallyn** [comment]
Ok so IIUC this is not an issue here.  I'll close this.  If I'm wrong, please reply :)

**Comment by SEJeff** [comment]
@hallyn can confirm it is working. Please close. Thanks!
