### ISSUE TITLE
nextcloud-apache image hangs unprivileged, fine if run as root

### ISSUE THREAD

**Issue by laolux** [containers/libpod#3444]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I try to run the nextcloud container image from dockerhub using podman as unprivileged user. However, this does not quite work. The container starts and starting to setup nextcloud works, but it never finishes. The container is eventually stuck and cannot be stopped with `podman stop`. If I do exactly the same procedure as root, then everything works smoothly, so I suspect it is not an issue with the image but rather with unprivileged mode of podman.

**Steps to reproduce the issue:**

1. run `podman run -t -i -a STDIN -a STDOUT -a STDERR -p 8080:80/tcp nextcloud:16-apache` to download and start the new container.

2. use a browser to connect to `127.0.0.1:8080`, enter username, password and click `Finish setup`

3. Wait for setup to finish.

**Describe the results you received:**
Browser page turns white, setup never finishes (within 30 minutes at least). Stopping the container using `podman stop` fails with `Error: container 12324 did not die within timeout`. Process needs to be killed with `kill PID`. The container cannot be restarted afterwards: `Error: unable to start container ... stat /entrypoint.sh: no such file or directory`

**Describe the results you expected:**
Setup finishes and and I get greeted by nextcloud. Works perfectly when the container is started as root.

**Additional information you deem important (e.g. issue happens only occasionally):**
I do not get any SELinux issues in sealert, so this should not be the cause.
Also, when I start the container and stop it before finishing the setup, then I can easily restart it. However, once I click `Finish setup` the container is unsable.
Last comment: I can edit the container (before completing the nextcloud setup). When I edit it to start apache in debug mode (with `-X`), then the everything is very slow, but setup actually completes and I can use nextcloud.
**Output of `podman version`:**

```
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.12.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.5
  podman version: 1.4.2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: d7234dc01ae2ef08c42e3591e876723ad1c914c9'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 669716480
  MemTotal: 8213094400
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 8321495040
  SwapTotal: 8350855168
  arch: amd64
  cpus: 8
  hostname: imr-laptop
  kernel: 5.1.12-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 3h 48m 55.99s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/podmanuser/.config/containers/storage.conf
  ContainerStore:
    number: 5
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/podmanuser/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /tmp/1001
  VolumePath: /home/podmanuser/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 30, all updates installed

**Comment by rhatdan** [comment]
Not root users are not allowed to bind to port 80 on the host, or any ports < 1024.  I suspect that is your issue.

https://github.com/containers/libpod/blob/master/rootless.md

@giuseppe What do you think about adding a patch to podman to check for NET_BIND_SERVICE when the user specifies a port < 1024 and throwing an error?

**Comment by mheon** [comment]
The Podman stop error indicates that SIGKILL didn't stop the container - I
think we have further issues here than just a low port

**Comment by giuseppe** [comment]
one observation:

I think the container is not working correctly on a terminal (not sure why it would work as root), if I run your same command and I try to resize the terminal the application is terminated:

```
([Thu Jun 27 13:57:59.942884 2019] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully)
```

I think the issue is in the file system, could you try https://bodhi.fedoraproject.org/updates/FEDORA-2019-1fba8e63f5 ?

Unfortunately that release didn't make into Fedora yet, even though the bug was fixed upstream already since long

**Comment by laolux** [comment]
@rhatdan 
Thanks for pointing that out, but I don't think that I have a port issue here. I use `podman run -t -i -a STDIN -a STDOUT -a STDERR -p 8080:80/tcp nextcloud:16-apache` which contains `-p 8080:80/tcp` which as far as I know will bind port 80 from the container to port 8080 of the host.
Also, if I try to start with `-p 80:80/tcp`, then the container will not start to begin with.

**Comment by laolux** [comment]
@giuseppe 
Thousand thanks, that fixed it :-)

Thank you all for your help and quick responses.
