### ISSUE TITLE
podman play kube error(log driver must be set)

### ISSUE THREAD

**Issue by mritd** [containers/libpod#3449]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running `podman play kube` error

**Steps to reproduce the issue:**

1. `podman run -dt --name nginx -p 1234:80 nginx:1.17.0-alpine`

2. `podman generate kube nginx > nginx.yaml`

3. `podman rm -f nginx`

4. `podman play kube nginx.yaml`

**Describe the results you received:**

``` sh
a container exists with the same name (nginx) as the pod in your YAML file; changing pod name to nginx_pod
Error: error running container create option: log driver must be set: invalid argument
```

**Describe the results you expected:**

Podman successfully runs pod

**Additional information you deem important (e.g. issue happens only occasionally):**

The log prompt does not set `log driver`, but the podman play command does not provide setting parameters.

**Output of `podman version`:**

```
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

``` sh
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 7539142656
  MemTotal: 8358653952
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 2
  hostname: docker1.node
  kernel: 4.15.0-52-generic
  os: linux
  rootless: false
  uptime: 15h 44m 38.29s (Approximately 0.62 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM:  Parallels Desktop
Host OS: Mac 10.14.5
Guest OS: Ubuntu 18.04

**Comment by haircommander** [comment]
This has been fixed in 1.4.1!

**Comment by haircommander** [comment]
First reported here https://github.com/containers/libpod/issues/3157#issuecomment-502889898

**Comment by mritd** [comment]
Thank you for your reply 😁
