### ISSUE TITLE
Rootless access to PCI devices

### ISSUE THREAD

**Issue by xlz-jgoutin** [containers/libpod#3456]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

From my container, I need to access to a PCI device (A FPGA in my case). The user I use to run the container has access to the device using a special group (``fpgauser``, that is the user primary group): 

On the host, the device ownership is set to ``root:fpgauser`` (example ``/sys/devices/pci0000:00/0000:00:1d.0/*``).

Now, If l go to the container, the device ownership become ``nobody:nogroup``. I tried to use some options like ``--group-add=fpgauser``, ``--userns=keep-id``, ``--privileged``, ``--gidmap``, ``--uidmap``, but I didn't success to have correct ownership on the device.

More generally, I get ``nobody:nogroup`` in all the ``/sys/devices`` tree.

**Steps to reproduce the issue:**

Running command like return ``nobody:nogroup``:

``podman run --rm docker.io/ubuntu bash -c "ls -l /sys/devices/pci0000:00"``

The same with ``sudo`` returns the correct ownership.

**Describe the results you received:**

``/sys/devices/pci0000:00`/*` ownership is ``nobody:nogroup``

**Describe the results you expected:**

Correct ownership.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.0
host:
  BuildahVersion: 1.8.3
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 127004753920
  MemTotal: 128856870912
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: ip-172-31-13-137
  kernel: 4.15.0-1043-aws
  os: linux
  rootless: true
  uptime: 19m 20.38s
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/appuser/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/appuser/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/1001
  VolumePath: /home/appuser/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS, f1.2xlarge instance.

**Comment by mheon** [comment]
Are you running rootless?

This seems like a user mapping issue with rootless containers.

**Comment by rhatdan** [comment]
I think you would need to map the group into the container, which I am not sure you can, 

fpgauser

Something like

--gidmap fpgauser:fpgauser:1

Which I am not sure if this is allowed.  fpgauser might have to be translated into the actual GID.

**Comment by giuseppe** [comment]
> --gidmap fpgauser:fpgauser:1

this won't work as the `--gidmap` will be relative to the UIDS/GIDS we have in the first user namespace.

Strange that the user first GID is not mapped inside of the container, that should be present.

Can you show me the output of `id` when you run it from the host and both `cat /proc/self/uid_map`, `cat /proc/self/gid_map` from the container?

Also, could you try to bind mount `-v /sys:/sys` from the host?  Does it make any difference?

**Comment by xlz-jgoutin** [comment]
After reading your comments, I finally managed to make it work. Thanks.

I maybe had something wrong last day with the user group because this time I get ``nobody:root`` as ownership (Maybe because last time I added the user to the group and then make the group as primary, today I directly created the user with this group as primary).

After this, I tried to reproduce the same user and group pair in the container, this worked if I create a user with the same GID, UID as on the host (1001:1001) and then use ``--userns=keep-id``, this gives me the correct ownership ``nobody:fpgauser`` inside the container.

I also tried to map the host user:group (1001:1001) to a container new user with default UID,GID (1000:1000) with `--gidmap 1000:1001:1 --uidmap 1000:1001:1` but this did not work. I am not sure to use these options properly.

**Comment by giuseppe** [comment]
@xlz-jgoutin yes, `--userns=keep-id` is the correct way to keep the same UID inside of the rootless container. `--gidmap 1000:1001:1 --uidmap 1000:1001:1` are not enough, you will still need to map root inside the container, so you'll probably need to do something like:

`--uidmap 0:1001:1 --uidmap 1:1:1001`


If `--uidmap` and `--gidmap` are the same, you can avoid providing `--gidmap`.

I am closing this issue, but please feel free to add more comments or reopen it if you feel it is not solved
