### ISSUE TITLE
Running `sudo -E podman` after rootless `podman` has side effects

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3463]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running `sudo -E podman <anycommand>` after a rootless podman command (that creates the pause process) causes podman to misbehave.

**Steps to reproduce the issue:**
```
$ ./bin/podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

$ /usr/bin/sudo ./bin/podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

$ /usr/bin/sudo -E ./bin/podman ps
Error: error creating libpod runtime: error creating runtime static files directory
/var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage: permission denied

$ rm /run/user/1000/libpod/pause.pid; pkill -9 podman

$ /usr/bin/sudo -E ./bin/podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```
**Output of `podman version`:**

```
Version:            1.4.4-dev
RemoteAPI Version:  1
Go Version:         go1.12.5
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by marcov** [comment]
Adding some debug Printf right before trying to create `/var/lib/containers/storage`, I can see that the user namespace of the `sudo -E podman` is the same of the podman pause process showed in `lsns -t user`

**Comment by giuseppe** [comment]
Isn't XDG_RUNTIME_DIR pointing to the wrong directory with sudo -E?

**Comment by marcov** [comment]
Yea, it is still pointing to `/run/user/1000`. I guess that's not OK then...

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/containers/libpod/pull/3468
