### ISSUE TITLE
Both root and $USER exist in rootless container

### ISSUE THREAD

**Issue by johrstrom** [containers/libpod#3475]
I've been reading a lot of issues about mounting directories and user namespaces and so on, and I believe my use case is different enough from what is currently provided to open this ticket.

What I need in a rootless container are these 2 things.
* the entrypoint is (what it believes to be) root 
* I am $USER (as an example - uid 1000, gid 1000) both inside and outside the container so I can mount my $HOME and correctly use it.

The app that I work on runs as root and serves web pages that ultimately spawn process for non-root users. So those processes are owned by say uid 1000. So that's why I (uid 1000) don't want to **be** root, I want some room (0 mapped to, say, 100099). 

If there's some --uidmap magic that can accomplish this, please let me know, because I've tried just about all I can.

Also, as I'm writing this ticket I'm wondering if it's possible for a uid 100099 (that thinks it's root) that has uid 1000 as it's parent to spawn a process for that parent.  So if it's not possible or just plain too crazy for you to want to implement please let me know.

**Comment by mheon** [comment]
Does `--userns=keep-id` work here? It preserves the UID of the user running the container in the mappings - UID 1000 on the host and in the container would be the same user. The container should still default to running applications as root.

**Comment by johrstrom** [comment]
When I'd tried that my app hung in weird places trying to escelate privileges. If i just `-it /bin/bash` into something like that and try to `sudo ls` it prompts for a password and I think that's causing issues.  A password I don't know btw, my actual host password doesn't seem to work.

**Comment by mheon** [comment]
Hmm. I don't know if we expect sudo to work inside of rootless containers - at least, not natively...

@debarshiray Toolbox allows sudo, right? Do you know if you're doing anything special to allow that?

**Comment by johrstrom** [comment]
Yep, I think I see it [here](https://github.com/debarshiray/toolbox/blob/master/toolbox#L976). Let me try some stuff. Thanks!

**Comment by johrstrom** [comment]
Thanks you so much! That works just like a charm. 

FYI, just in case anyone in the future sees this, I added these lines to my build script and a simple `sudo -u root ....` to my entypoint. 
```shell
buildah run $ctr -- usermod -a -G wheel $USER
buildah run $ctr -- passwd --delete $USER
buildah run $ctr -- passwd --delete root
```
