### ISSUE TITLE
Failed to tear down network namespace after firewall-cmd --reload

### ISSUE THREAD

**Issue by sunilcio** [containers/libpod#348]
version: podman-0-0.3.git367213a.fc27.x86_64
kernel: 4.14.18-300.fc27.x86_64

Steps to reproduce:

Run httpd container:
```
# podman run -ti  docker.io/library/httpd
AH00557: httpd: apr_sockaddr_info_get() failed for b5b06e336b43
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
AH00557: httpd: apr_sockaddr_info_get() failed for b5b06e336b43
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
[Fri Feb 16 19:42:42.406695 2018] [mpm_event:notice] [pid 1:tid 140575279757184] AH00489: Apache/2.4.29 (Unix) configured -- resuming normal operations
[Fri Feb 16 19:42:42.407006 2018] [core:notice] [pid 1:tid 140575279757184] AH00094: Command line: 'httpd -D FOREGROUND'
192.168.122.178 - - [16/Feb/2018:19:42:59 +0000] "GET / HTTP/1.1" 200 45
192.168.122.178 - - [16/Feb/2018:19:43:05 +0000] "GET / HTTP/1.1" 200 45
```

Check connectivity:
```
# curl  192.168.122.178
<html><body><h1>It works!</h1></body></html>
```

Do firewall reload without changing any rules:
```
# firewall-cmd --reload
success
```

Check connectivity again and curl reports connection refused
```
# curl  192.168.122.178
curl: (7) Failed to connect to 192.168.122.178 port 80: Connection refused
```

Stop container:
```
# podman ps -a
CONTAINER ID   IMAGE                     COMMAND            CREATED AT                      STATUS                     PORTS                                    NAMES
b5b06e336b43   docker.io/library/httpd   httpd-foreground   2018-02-16 14:42:37 -0500 EST   Exited (0) 2 minutes ago   0.0.0.0:80->80/udp, 0.0.0.0:80->80/tcp   sad_goodall
```

And try to remove container:
```
# podman rm sad_goodall
ERRO[0000] Error deleting network: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.32/16 -j CNI-e994acb5884bc476c84cb703 -m comment --comment name: "podman" id: "b5b06e336b43b2bb1e746f14b465e0cb4e41e53f63c7b0698a1b276c3318e2b8" --wait]: exit status 2: iptables v1.6.1: Couldn't load target `CNI-e994acb5884bc476c84cb703':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
ERRO[0000] Failed to tear down network namespace for container b5b06e336b43b2bb1e746f14b465e0cb4e41e53f63c7b0698a1b276c3318e2b8: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.88.0.32/16 -j CNI-e994acb5884bc476c84cb703 -m comment --comment name: "podman" id: "b5b06e336b43b2bb1e746f14b465e0cb4e41e53f63c7b0698a1b276c3318e2b8" --wait]: exit status 2: iptables v1.6.1: Couldn't load target `CNI-e994acb5884bc476c84cb703':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
 
b5b06e336b43b2bb1e746f14b465e0cb4e41e53f63c7b0698a1b276c3318e2b8
```

Checking `/var/run/netns` directory, I see large number of left over `cni-fd666752-f089-e3e8-a8e5-85654b1e367c` files while there are no running or stopped containers on system.

```
# ll /var/run/netns/cni-* | wc -l
26
```

If I skip `firewall-cmd --reload` step, then while removing container does not report any error.

Let me know if any other information is required.

**Comment by mheon** [comment]
I suspect CNI is not giving firewalld the hints it needs to know the chains we are creating should persist across a firewall reset. I don't know if this is a known issue upstream - we should check into that.

**Comment by dcbw** [comment]
The CNI plugin does not talk to firewalld at all.  It talks to iptables directly.  So if you reload firewalld, and if firewalld blows away the CNI rules when it reloads, you'll have this problem.

**Comment by rhatdan** [comment]
Does this mean podman/libpod would have to figure out the hints to tell firewalld similar to what CRI-O is doing or is this up in the kube layer where we don't have an idea what is going on?

**Comment by mheon** [comment]
@rhatdan I don't think this is CRI-O code, so we'd have to figure out how Kube is doing it

**Comment by rhatdan** [comment]
Is there a way to tell firewalld that something else is managing these rules?

**Comment by mheon** [comment]
We've greatly improved how this we interact with firewalld with #1431 - sadly, this was not completely fixed, but it's been downgraded to just a warning, and things should proceed fine even if it occurs.
