### ISSUE TITLE
Drop-in replacement of docker network create

### ISSUE THREAD

**Issue by ephracis** [containers/libpod#3481]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be really nice to have a drop-in replacement of `docker network create` to properly cover the following use case:
- Running two or more containers on a single host
- The containers can find each other using name resolution
- Exposed ports are only accessible from other containers (inside the network) and are not accessible from outside the host
- There is no risk of port collision, two containers can both expose the same port on the network

There are alternatives such as creating a pod, the use of CNI networks, or use host networking but all of those carry some loss of functionality. Besides, this is very easy to do with Docker:

1. Create the network using `docker network create`
2. Run the container with the `--network` flag

**Comment by mheon** [comment]
We can expose `network create` to make CNI bridge network configs - it's been on the radar for a while, so I'd like to get it out by end of summer.

Exposed ports only being available within networks could be more problematic... CNI isn't really equipped for that right now. (I'm assuming you mean running containers with `-p` here to expose the ports - if you just mean "container A runs an HTTP server on port 80, container B also runs an HTTP server on port 80, and they can connect to each other on the created network" with no `-p` that will work).

For resolution: we did experiments with name resolution at one point, using a `dnsmasq` server. It's not something CNI offers on its own (we could, of course, get a plugin written for it).

**Comment by mheon** [comment]
The tl;dr here being that I think `network create` will be arriving soon, but possibly without that port behaviour and without name resolution.

**Comment by baude** [comment]
My two cents:

* As @mheon says, we can make a docker network command.
* Name resolution between containers is not related to docker network.  We have no plans in the immediate future for name resolution between containers.
* It might be late in the day but iirc, containers on the same network can access each other's ports without having to expose ports.  Exposing ports allows "other" networks to use the host to "get" to a container's ports.  In other words, to not expose ports outside the host, do not export them.
* the port collision is also not a bi-produce of docker network near as I can tell.  In the case of podman, we would need to identify the exposed ports and make sure no duplicates were being exposed.  In the case where the container allows the host to determine the port, duplicates cannot occur.  If this is a valid use case, we should simply be adding the logic to detect the exposed ports and make sure they do not already exist.  This brings up a number of issues like does the container have to be running to avoid duplication, etc?

**Comment by baude** [comment]
@ephracis thanks for the well written issue.

**Comment by ephracis** [comment]
> Exposed ports only being available within networks could be more problematic... CNI isn't really equipped for that right now. (I'm assuming you mean running containers with -p here to expose the ports - if you just mean "container A runs an HTTP server on port 80, container B also runs an HTTP server on port 80, and they can connect to each other on the created network" with no -p that will work).
Yes, that is how it works in Docker. Published ports (using `-p`) are routed in from the host. If the port is not published, it is only exposed on the network and thus only accessible from other containers on that same network. So I guess CNI networks address this properly already.

> For resolution: we did experiments with name resolution at one point, using a dnsmasq server. It's not something CNI offers on its own (we could, of course, get a plugin written for it).
That would be really helpful. Cause if I don't know the order containers then I have no idea what IP they will get, right? I need a deterministic way for containers to find each other on the CNI network. Not sure how Docker does this but dnsmasq seems like the easiest solution. Or just modifying `/etc/hosts`.

> Name resolution between containers is not related to docker network. We have no plans in the immediate future for name resolution between containers.
Well with Docker I get name resolution automatically. So somehow Docker does this in their networks. So I'm not sure what you mean by "is not related to docker network".

> the port collision is also not a bi-produce of docker network near as I can tell
I brought that up just to illustrate how using a pod is not a drop-in replacement. In a pod we put all ports on localhost which means we run the risk of having port collisions between containers. When using `docker network create` I don't have this risk.

**Comment by rhatdan** [comment]
https://github.com/containers/libpod/pull/3719 is working on a solution for this.

**Comment by baude** [comment]
in 1.6
