### ISSUE TITLE
Ansible modules to replace the docker_xxx modules

### ISSUE THREAD

**Issue by ephracis** [containers/libpod#3482]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

We are a company using Ansible to deploy and manage lots and lots of containerized services. This was quite easy using the `docker_xxx` modules in Ansible. When trying to add support for RHEL 8 we are forced to use podman instead of docker and now we have to resort to using command line instead of proper modules. This makes stuff really hard as most podman commands are not idempotent.

It would be greatly helpful if there were proper Ansible modules to replace the current ones. The modules we use the most are `docker_image`, `docker_container` and `docker_network`.

**Comment by mheon** [comment]
@rhatdan I think you're the most up to date on the state of our Ansible efforts

**Comment by TomSweeneyRedHat** [comment]
FYI @TomasTomecek

**Comment by TomasTomecek** [comment]
@ephracis there was already a ton of work done in this area:
* [podman_image](https://docs.ansible.com/ansible/latest/modules/podman_image_module.html) - new in Ansible 2.8
* [podman_container](https://github.com/ansible/ansible/pull/57956) was merged recently

**Comment by ephracis** [comment]
This is great news! Thanks.

**Comment by baude** [comment]
re-open if needed
