### ISSUE TITLE
Add packages for Ubuntu 19.04

### ISSUE THREAD

**Issue by Davio** [containers/libpod#3485]
/kind feature

**Description**
I'm currently running Ubuntu 19.04, but the packages in the PPA are only for the LTS versions 16.04.2 and 18.04, see https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Steps to reproduce the issue:**

1. Go to https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Describe the results you received:**
See that there are no packages for 19.04

**Describe the results you expected:**
Packages for Ubuntu 19.04

**Comment by rhatdan** [comment]
We really could use help from the Ubuntu community for packaging up Podman for Ubuntu either as a Snap or as a PPA.

**Comment by lsabi** [comment]
**NON-OPTIMAL SOLUTION (MAY LEAD TO PROBLEMS)**
I found a dirty work around:

Go to the launchpad page

[https://launchpad.net/~projectatomic/+archive/ubuntu/ppa](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa)

Click on "Technical details about this PPA" and select your ubuntu version. You will have two lines of code: deb \<url> and deb-src \<url>

Run in the terminal
`sudo add-apt-repository "deb <url>"`
`sudo apt update`
`sudo apt install podman`

In my case I have Ubuntu 19.04 and I have the following deb line

`deb http://ppa.launchpad.net/projectatomic/ppa/ubuntu bionic main`

I know it is a work around and that it is not the best, but it should be written on the documentation that for now only LTS versions are supported. Maybe I'll do that after checking the code of conduct for contributions.

@rhatdan 

If it really is a bad work around, please let me know so that I can delete the comment.

Best

**Comment by sluongng** [comment]
I think being able to support latest releases (not just LTS) version is quite important to make podman widely adopted in favor of the traditional docker CLI.

Ubuntu has a twice per year release cycle and it should not take this long / this difficult to get support for new version as the library are almost of not all identically supported moving from 18.04 -> 18.10 -> 19.04. And as report above, there are work around which mean that the build is definitely compatible.

Perhaps if we can add a list of OS tags (at least for Ubuntu) and automate the releases via Continuous Integration? There seems to be a cry out for automation here.

**Comment by madhub** [comment]
Agree , please add support for ubuntu 19.04

**Comment by alitvak69** [comment]
@rhatdan While I am not a good candidate for packager for various reasons, I would like to suggest something.  It looks like people behind the atomic ppa are very busy and cannot spend time to build packages regularly for LTS Ubuntu releases not to mention others.  I wonder if developers of podman could write a document on how to build debs for podman + dependencies and put it in this github repo or?  I can imagine that the number of ubuntu people who experiment with the latest podman can pull and build releases and eventually someone will make it a part of some custom ppa.  I at some point was able to build a podman deb but I already had all dependencies running on my machine, so I am sure I wouldn't be as successful on the clean box without some guidance.

**Comment by lsm5** [comment]
sorry about the delay everyone, I plan on getting automated builds setup for ubuntu versions by this weekend.

**Comment by lsabi** [comment]
@lsm5 let me know if you need help in writing the automated builds (so I can learn it too)

**Comment by lsm5** [comment]
@lsabi Consider cri-o-1.14. I have a [gitlab CI job](https://gitlab.com/lsm5/cri-o/blob/bionic-1.14/.gitlab-ci.yml) which will run this [autobuilder script](https://gist.github.com/lsm5/8465d3fdcbc101a12f40caf57581ad77) in a [registry.gitlab.com/lsm5/rpm-builder:bionic]( https://gitlab.com/lsm5/rpm-builder/container_registry) container. Currently, I see some issue with submitting build from CI to PPA, maybe it's cause my dput.cf is using sftp, but locally it works fine via ftp. Once I have the dput issue solved, I'll replicate this for the other packages and add new ubuntu images. HTH. It's still not there yet, so I can get back to you once everything's working.

**Comment by mkeedlinger** [comment]
I am also very interested in having podman available on Ubuntu 19.04.

This may not be the best place to ask, but what is the process like to get podman into the official Ubuntu repos? Is that in the works somewhere?

<sub><sub>Note: love the idea of podman! solves all the things that stop me from using containers right now. Thanks to all those who have put work into it!</sub></sub>

**Comment by lsm5** [comment]
> I am also very interested in having podman available on Ubuntu 19.04.

Autobuilds are coming. Some minor issues to get around. You'll notice some disco packages on https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages . Hope to be done before Monday.

> 
> This may not be the best place to ask, but what is the process like to get podman into the official Ubuntu repos? Is that in the works somewhere?

For that, packages would need to go into debian first. I guess there's some work in the community happening on this, but neither anyone in podman upstream (AFAIK) nor I (the packager for most distros) are working on that. If Debian no longer requires building from distro golang deps, then I can revisit that, but otherwise, I'd rather let someone else do it.

I'm looking at using openSUSE's Open Build Service for Debian (and raspbian), so maybe that'll be good enough for debian users.

> 
> Note: love the idea of podman! solves all the things that stop me from using containers right now. Thanks to all those who have put work into it!

Thanks! :) Hopefully I'll have more updates by Monday morning, would appreciate testing and feedback!

**Comment by lsm5** [comment]
podman 1.4.4 is installable (and hopefully usable :D ) on 19.04. FWIW, `podman version` works on my 19.04 container, haven't tested anything beyond that. Let me know how it goes.

I've set up autobuilds for 18.04 and 19.04 so hopefully new builds should land on the PPA within an hour or less of upstream tag release.

I plan to work on enabling debian builds via openSUSE OBS before refreshing 16.04 packages. Hope there's not too much demand for 16.04 anymore though :)

Enjoy!

**Comment by lsm5** [comment]
In case anybody cares, the autobuilder job is at https://github.com/lsm5/rpm-builder/tree/disco . The actual debian packaging source can be found at https://github.com/lsm5/libpod/tree/disco/debian . HTH.

**Comment by alitvak69** [comment]
@lsm5 Thank you for your work.  A slightly off topic question.  Can one build rpms for centos7 using some framework that already exists?

**Comment by lsm5** [comment]
> @lsm5 Thank you for your work. A slightly off topic question. Can one build rpms for centos7 using some framework that already exists?

The f30 and cri-o branches on https://github.com/lsm5/rpm-builder/ should build rpms for centos7 virt and paas sigs. There's still some pending work to be done on the CentOS infra side, which I hope to get to this week. But builds should be landing on [CBS](https://cbs.centos.org). Let me know if you need the actual yum repos from CBS.

podman 1.4.4 can be found [here](https://cbs.centos.org/koji/buildinfo?buildID=26305). Let me know if any issues with install, koji tags or anything else.

**Comment by alitvak69** [comment]
@lsm5 Thanks again I will test it and let you know if I  run into issues.  If pull podman 1.44 from  CBS the dependencies should be found there as well, correct?

**Comment by lsm5** [comment]
> @lsm5 Thanks again I will test it and let you know if I run into issues. If pull podman 1.44 from CBS the dependencies should be found there as well, correct?

afaict, yes, but if not, then please open a separate issue for centos

**Comment by mkeedlinger** [comment]
@lsm5 I tried to follow the instructions [here](https://github.com/containers/libpod/blob/master/install.md#ubuntu) to get podman on 19.04, but it says the package is not found still.

Am I missing something?

**Comment by lsm5** [comment]
@mkeedlinger it's available in https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages . Could you please post the error message?

**Comment by madhub** [comment]
It works now, I tested on ubuntu 19.04. 

![image](https://user-images.githubusercontent.com/8907962/62230866-692b4380-b3e0-11e9-8958-7e67ac01a55c.png)

**Comment by mkeedlinger** [comment]
@lsm5 Just tried again and it works. I was trying to do some fancy ansible, doing it manually worked great.

**Comment by alitvak69** [comment]
@lsm5 Needed to use podman 1.5.0-2 from CBS repo but the build apparently failed.   Using it to verify fix in another ticket. Could you please take a look?

**Comment by c16a** [comment]
I can finally move on from the Docker daemon now. Awesome work @lsm5
