### ISSUE TITLE
missing docs for podman-container-init

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3489]
`podman-container-init` misses documentation such as man pages.

I'd also love the command to place a copy of the config in $PWD to make it more accessible.

**Comment by mheon** [comment]
We have a manpage for podman-init but did not alias it for podman-container-init... Oops.

**Comment by ashley-cui** [comment]
@vrothberg What do you mean by 'config'?

**Comment by vrothberg** [comment]
```
$ podman create alpine ls 0b45f419e02bdf2a024d937b1887982af2680370e28ad1338c3d5e4bde59846e
$ ls /home/valentin/.local/share/containers/storage/overlay-containers/0b45f419e02bdf2a024d937b1887982af2680370e28ad1338c3d5e4bde59846e/userdata
artifacts  shm
$ ls /home/valentin/.local/share/containers/storage/overlay-containers/0b45f419e02bdf2a024d937b1887982af2680370e28ad1338c3d5e4bde59846e/userdata
artifacts  attach  config.json  ctl  ctr.log  shm
```

@ashley-cui, I was referring to the runtime config (i..e, the config.json above). Maybe it's better to just print the path to the container's userdata instead of the config. In the current form, users will have a hard to figure out where the generated files by init are placed.

@mheon @rhatdan WDYT?

**Comment by mheon** [comment]
@vrothberg My original intent was to let you grab the path from `podman inspect` after using `podman init`; `podman init $ctr; podman inspect $ctr | grep OCI` for example.

**Comment by baude** [comment]
status please?

**Comment by rhatdan** [comment]
podman-container-init man page exists now.

**Comment by vrothberg** [comment]
> podman-container-init man page exists now.

@rhatdan, I don't see it

**Comment by ashley-cui** [comment]
@vrothberg https://github.com/containers/libpod/blob/master/docs/links/podman-container-init.1

**Comment by vrothberg** [comment]
I must be blind, thanks @ashley-cui!

We can close the issue :)
