### ISSUE TITLE
podman-remote:  messages refer to `podman` instead of `podman-remote`

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3503]
Examples:
```
[~]$ podman-remote
Error: missing command 'podman COMMAND'
Try 'podman --help' for more information.

[~]$ podman-remote awoeuerwr
Error: unrecognized command `podman awoeuerwr`
Try 'podman --help' for more information.

[~]$ podman-remote --help | tail -n1
Use "podman [command] --help" for more information about a command.
```

One way to approach this, could be to make the root-cobra-command build conditional. This would allow for changing the description as well.

Cc: @baude @jwhonce

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
The problem with this is that when we use podman on the mac (which is just a version of podman-remote), we do want it to pop up as only podman, but on using podman-remote it should pop up as podman-remote. Not really sure how to branch off these three, since the usage is in the shared main file.

**Comment by vrothberg** [comment]
@ashley-cui, that's a good point!

I think we can inject it as a string from the `Makefile`. We're doing that already for a bunch of variables (see https://github.com/containers/libpod/blob/master/Makefile#L66). Depending on the make target, we could set the name of command with "podman" being the default. What do you think?

**Comment by ashley-cui** [comment]
@vrothberg Sounds good, I'll look into it!
