### ISSUE TITLE
Add option to not create own cgroups

### ISSUE THREAD

**Issue by Gigadoc2** [containers/libpod#3542]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When using podman with a single-host setup to run "traditional" (not "cloud-native") services, I would like for podman to not create a new slice for the container.
The current behaviour means that even while using the systemd cgroup-manager backend, a command like `systemctl status container.service` (where `container.service` is a service unit executing a podman container) will not show me the processes running within that container, or the resources used by it. Instead, I have to find the slice created by podman and review that.
Furthermore, I have encountered some scenarios where systemd considers `container.service` to be inactive, as the podman command exited already, but the actual container lives on, thus breaking commands like `systemctl restart container.service`.

Thus I would be very happy if there was an option to turn this off entirely (as opposed to choosing between the systemd or the cgroupfs backend), so that I can have systemd handle the cgroup allocation and resource control with native unit file semantics.

This is not a bug report as the above mentioned edge-cases are not bugs *per se*, it is just that when podman is managing the cgroups (even if it is through systemd), systemd cannot control the container as good as it can control "native" processes.

**Output of `podman version`:**

```
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.6
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 41010e63c287618b1dc34ee11d10d268e2feeefe'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 3167023104
  MemTotal: 4133478400
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 4
  hostname: vivec
  kernel: 5.1.16-300.fc30.x86_64
  os: linux
  rootless: false
  uptime: 21m 23.08s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
QEMU-KVM virtual machines (libvirt)

**Comment by mheon** [comment]
This isn't the first time I've heard this one mentioned.

We'd need a way to tell the OCI runtime not to create CGroups - there's no way of doing that in the spec currently. I believe `runc` has such functionality, but it's internal only, for integration testing - not something we can instruct it to do. If it were to expose that functionality for us, it shouldn't be particularly difficult for us to add support for it (could probably be affixed to the flag @giuseppe is adding for CGroup namespaces).

There are, of course, downsides to disabling CGroups - all resource limit related flags would suddenly stop working, since we're using an existing CGroup which we can't guarantee we can modify. That's probably an acceptable tradeoff if we're being called from unit files (you can add them there instead).

I'll tag @mrunalp who mentioned the possibility of exposing runc's no-cgroups functionality.

**Comment by giuseppe** [comment]
as @mheon said we are limited though as we cannot configure it, but it should not be an issue at all with containers created through systemd as some of the limits can be configured in the unit file itself.

We will need to teach Podman to do the same thing with conmon and not create any cgroup.

I've exposed a new option for crun (`--cgroup-manager=disabled`) so we can start playing with it without waiting on runc: https://github.com/giuseppe/crun/pull/53

**Comment by Gigadoc2** [comment]
I am now wondering what happens when running rootless podman.

When doing so, the container processes do not seem to be put into different cgroups. Are runc or crun not used in this case (and then, what is used)?

**Comment by mheon** [comment]
They are both options for rootless, `runc` being default. They detect the rootless condition, and have special handling (don't create cgroups) that is is not exposed otherwise (well, it is now in `crun` via flag - thanks @giuseppe)

**Comment by rhatdan** [comment]
mheon could we convince runc of the "rootless" condition to not configure its own cgroups?  
I would think we would be able to get runc to support the --cgroup-manager=none or disabled lets,open a PR to them and see if we can get a couple of maintainers to merge it.

**Comment by mheon** [comment]
Agree. I think this also helps the scenario that Openstack has been seeing - if their containers are using systemd cgroups and not making their own, no dependency issues.

**Comment by mheon** [comment]
Working this in #3581

**Comment by giuseppe** [comment]
I've cut a new release of crun that has support for `--cgroup-manager=none`: https://bodhi.fedoraproject.org/updates/FEDORA-2019-f84b229286

**Comment by mheon** [comment]
Fixed in 3581 but only with crun - runc support not yet added
