### ISSUE TITLE
Internal default CNI plugin

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#3544]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The idea is to have an in-memory CNI implementation which defaults to a bridged-interface to avoid the necessary runtime dependency to CNI plugins. This would make podman per-default work from a networking perspective, without pushing around network configuration files. It should still be possible to use different CNI configurations. 

What do you think?

**Comment by mheon** [comment]
Would the goal here be to reimplement the CNI plugins? Or to vendor some of the code into Podman?

My initial reaction is to be a bit wary of potential binary bloat - we're already touching 60mb for Podman, and the CNI plugins are a pretty hefty 30-ish MB if I recall correctly.

**Comment by saschagrunert** [comment]
> Would the goal here be to reimplement the CNI plugins? Or to vendor some of the code into Podman?

The latter, we could get inspired by the current bridge implementation of containernetworking/plugins: https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go

> My initial reaction is to be a bit wary of potential binary bloat - we're already touching 60mb for Podman, and the CNI plugins are a pretty hefty 30-ish MB if I recall correctly.

Hm, this could be a point, but the bridge plugin is around 4MB and I think it would be a valuable addition to people who want to use podman as simple drop-in replacement to docker. If we don't have a clear packaging around podman (like on NixOS), then the current CNI configuration could confuse end-users.

**Comment by rhatdan** [comment]
@saschagrunert If you can figure a way to put Podman on a diet, and save several MB, I would consider it.  BTW We have an issue with --net=none, not configuring localhost, as well, so I would want this to work out of the box as well.

**Comment by mheon** [comment]
I think the big issue is that we can't just vendor bridge.

We need loopback and firewall too, at a mimum (firewall is required for any soft of function, localhost for loopback configuration).

I wouldn't be opposed to including them, but we definitely want compile-time fencing here, and building without integrated CNI should be the default. I think you can definitely save a good bit of space versus bundling the entirety of CNI, at the cost of a very fat Podman binary.

**Comment by mheon** [comment]
(To clarify, I mean podman binary with CNI build it is probably lighter than Podman and CNI as separate binaries)

**Comment by saschagrunert** [comment]
I understand, thanks for the feedback. I will continue my investigations in how to solve this in a proper way.

**Comment by rhatdan** [comment]
@saschagrunert @mheon Any update on this issue?

**Comment by mheon** [comment]
Not on our end. I'm fine with accepting patches (assuming it's built conditionally), but don't view it as a priority on our end right now.

**Comment by saschagrunert** [comment]
I evaluated the topic further and don's see any clean interface where a library like libpod could work with and I see the efforts as too high to continue here if its not a high priority.
