### ISSUE TITLE
podman CI should test udica functionality

### ISSUE THREAD

**Issue by wrabcak** [containers/libpod#3555]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Udica is a tool for generating SELinux security profiles for containers, based on inspecting container. 
It looks like in podman version 1.4+ json structure after inspecting container has changed, which made udica useless.  
I fixed udica today:
https://github.com/containers/udica/commit/47c4c08c94dbcf82e4e96f303429133727b6ae02

It would be great to have udica tests in CI of podman to make sure to inform udica developers (me) that you changed JSON structure for inspecting container. 

The initial test could be really easy. e.g:
```
$ git clone https://github.com/containers/udica
# cd udica && sudo python3 ./setup.py install`
# podman run -v /home:/home:ro -v /var/spool:/var/spool:rw -p 21:21 -it fedora bash
# podman inspect -l > container.json
# udica -j container.json  my_container
```

I can help with udica test, if somebody help me with podman CI. 

Thanks,
Lukas.

**Comment by rhatdan** [comment]
@cevich PTAL

**Comment by cevich** [comment]
@wrabcak sure happy to help. This appears on the surface to be really easy.  Am I correct in believing it doesn't matter much what platform/environment your example (above) runs on?  e.g. a Fedora VM is okay?

**Comment by wrabcak** [comment]
Hi @cevich, 
The best solution for me is to use Fedora VM and run following beakerlib test:
https://src.fedoraproject.org/rpms/udica/blob/master/f/tests/sanity/runtest.sh

If in podman CI there is no possibility to run beakerlib test, steps in issue description should be enough for CI. 

Thanks for your help!
Lukas.

**Comment by cevich** [comment]
Oh even better, can I just have a fedora VM pull down that `runtest.sh` script and execute it after build/install podman?

What do I need to install to satisfy:

```bash
# Include Beaker environment
. /usr/bin/rhts-environment.sh || exit 1
. /usr/share/beakerlib/beakerlib.sh || exit 1
```

?

**Comment by wrabcak** [comment]
Yeah, that should be enough.

**Comment by rhatdan** [comment]
What is the latest on this issue @wrabcak @cevich ?

**Comment by wrabcak** [comment]
@cevich  is preparing CI on Udica side:
https://github.com/containers/udica/pull/37

**Comment by cevich** [comment]
Oh woops, ya, we should close this issue, the ultimate solution will come in via new CI in udica.
