### ISSUE TITLE
rm of a container in a pod using a volume breaks podman

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3556]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Creating a container in a pod, assigning a volume to it and then trying to remove it results in:
```
Error: error freeing lock for container 4edf[ CUT ]de358a6: no such file or directory
```

**Steps to reproduce the issue:**

1. `podman pod create --name foopod`

2. `podman volume create foovolume`

3. `podman create --volume foovolume:/foovolume --pod foopod alpine sleep 1234 && podman start -l`

4. `podman stop -t 1 -l`

5. `podman rm <partial ID of ctr>`

6. `podman ps -a`: container is stil listed as in DB

7. `podman rm <partial ID of ctr>`:

**Describe the results you received:**
```
Error: error freeing lock for container 4edf[ CUT ]de358a6: no such file or directory
```

After this, it's not possible to remove the container from DB, unless something like [container eviction](https://github.com/containers/libpod/pull/3549) is used.

**Output of `podman version`:**
`144567b42dba2c8c426538a4b5fe7d718b43284a`

**Comment by mheon** [comment]
Eeek. Looking.

**Comment by mheon** [comment]
Found it.

**Comment by mheon** [comment]
#3558 to fix. I think this one was my fault - oops.
