### ISSUE TITLE
unable to run podman

### ISSUE THREAD

**Issue by har2103** [containers/libpod#3560]
hi,

am running podman in my virtual machine and installed using the git hub link steps. 

i am able to see podman version.
[root@localhost ]# podman version
Version:            1.4.2
RemoteAPI Version:  1
Go Version:         go1.11.10
OS/Arch:            linux/amd64
[root@localhost ]# 

[root@localhost ]# podman load -i app-ace-mq-0711.tar
Error: could not get runtime: failed to mount overlay for metacopy check: invalid argument

unable to use it.

appreciate your help on same.

**Comment by baude** [comment]
kernel bug, can you upgrade your kernel

**Comment by rhatdan** [comment]
Or edit /etc/containers/storage.conf and remove metacopy.

**Comment by mheon** [comment]
Closing, as this is a known issue (too old kernel)
