### ISSUE TITLE
Speed up latest container/pod lookup

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3567]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
How do you see speeding up the "latest" container/pod (can be extended to image too) lookup by adding a specific reference to it  in the state?

At the moment we iterate over all containers or pods to find the one with latest creation date, so I think having a direct reference to it may be worth doing.

It could be a new "latest" bucket for boltDB and a new map for in memory state.

**Comment by baude** [comment]
why do we need this? ar e you seeing a performance issue?

**Comment by vrothberg** [comment]
I think this is possible but we cannot get rid of the `O(n)` lookup/list walk entirely. The problem is container removal: if the latest container gets removed, we had to lookup the "next" latest one at some point. I _think_ the benefit of such an improvement highly depends on the usage, so I don't think it's worth the effort.

@mheon @giuseppe @haircommander WDYT?

**Comment by mheon** [comment]
If I see any potential advantage in this, it would be to change the semantics of "latest" from "last container created" to "last container I worked with"... But at this point, that would be a major, and quite confusing, change.

**Comment by haircommander** [comment]
Given the removal problem, I'm not that inclined to add the extra complexity and data. I also ask @baude's question, have you noticed performance issues? Otherwise, it feels like a needlessly complicated optimization to me.

**Comment by marcov** [comment]
> I think this is possible but we cannot get rid of the `O(n)` lookup/list walk entirely. The problem is container removal: if the latest container gets removed, we had to lookup the "next" latest one at some point.

That's correct, that would be the main limitation. But, after this O(n) search, you could store this next-latest ID for later use.

> If I see any potential advantage in this, it would be to change the semantics of "latest" from "last container created" to "last container I worked with"... But at this point, that would be a major, and quite confusing, change.

@mheon my proposal is not to change the semantic, but to skip the O(n) search when not needed.

But, to really see if that's worth, we should measure the current performances in a setup with a high containers number.

**Comment by baude** [comment]
@mheon correct me if I am mistaken here but I think a container or pod lookup is done within the context of the DB and should be very fast even with thousands of containers?

**Comment by mheon** [comment]
Nope, latest-container lookup requires a full JSON decode on the config struct for each container in the DB, which can be quite expensive.

**Comment by marcov** [comment]
Just did some test with some 100s of containers, and `ps -l` response time is still below 1s. So, given the reduced benefit, let's close this.
