### ISSUE TITLE
CentOS 7: Rebuilt podman 1.4.4 metacopy=on error

### ISSUE THREAD

**Issue by space88man** [containers/libpod#3571]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Running a franken-system: CentOS 7, rebuilt 1.4.4 (Fedora 30 src RPM, rebuilt due to older glibc).

```
# F30 binaries
containernetworking-plugins-0.8.1-1.fc30.x86_64
containers-common-0.1.37-0.gite079f9d.fc30.x86_64
buildah-1.9.0-1.git00eb895.fc30.x86_64
container-selinux-2.109-1.gitdb771da.fc30.noarch
runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64


# podman  run --rm centos:7 echo 'Hello, World!'
Error: could not get runtime: failed to mount overlay for metacopy check: invalid argument

```

Not sure if this is supposed to work: current versions of podman require kernels with metacopy= capabilities? I.e., RHEL 7 - generation is not (intended to be) supported?

Another franken-system with CentOS 7+ZFS as graph driver  and that seemed to work.

**Steps to reproduce the issue:**

1. Install podman 1.4.4 on CentOS 7 userspace (This is an RPM rebuild of Fedora 30 1.4.4.)
2. Use overlay as graph driver
2. Run `podman info`
3. 

**Describe the results you received:**
```
# podman info
Error: could not get runtime: failed to mount overlay for metacopy check: invalid argument

```

**Describe the results you expected:**
podman displays runtime information

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.4.5-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:** 

[Here need to reboot into a kernel with metacopy support, otherwise I won't be able to run the command; grabbed a kernel from elrepo.]

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.4.5-dev
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-1.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 779dc13a6d298d6b55d4aa1d72c15cd213905f2e'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 115511296
  MemTotal: 2086727680
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: centos7.localhost
  kernel: 5.2.0-1.el7.elrepo.x86_64
  os: linux
  rootless: false
  uptime: 28m 57.45s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mountopt=nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 11
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Grabbed a 5.2.0 kernel from elrepo, and that worked.

**Comment by baude** [comment]
you need to a newer kernel or to take out the metacopy from the the configuration file.

**Comment by rhatdan** [comment]
Right containers-common on Fedora supports metacopy=on, which is not supported on older kernels.
