### ISSUE TITLE
Auto update containers with podman

### ISSUE THREAD

**Issue by viggy96** [containers/libpod#3575]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Is there a method of automatically updating containers when a new version is available in the repository? I use watchtower to achieve this currently with docker, and that container requires mounting the docker unix socket to work, which of course, won't work for podman. Is there another method of achieving this, or is this feature on the roadmap?

**Comment by rhatdan** [comment]
Would a cron job/systemd timer work for this?  Not sure what watchtower is, but it seems line it must be just checking periodically and pulling new images.

**Comment by rhatdan** [comment]
After reading https://hub.docker.com/r/v2tec/watchtower/ it looks like this would be fairly easy to implement via a systemd timer.  

The issue would be if you wanted to make this general purpose. Launch a watcher on an existing container. Being able to get the command line executed, and gernate the CLI command based on it.

**Comment by viggy96** [comment]
Yeah, I want this to be general purpose for all my containers. Which is why I like that watchtower container so much, its a very simple solution to auto update all my containerised applications.

**Comment by abitrolly** [comment]
Docker added `--pull=...` option to `run` recently. Will that help https://github.com/docker/cli/pull/1498 ?

**Comment by rhatdan** [comment]
I don't think this will help, although it is something we should add to Podman.  @QiWang19 Could you add --pull for podman run and create.

**Comment by rhatdan** [comment]
Or @abitrolly If you wanted to add the support that would be great also.

**Comment by mheon** [comment]
This is being worked on.

**Comment by rhatdan** [comment]
@QiWang19 What is the state of this issue?

**Comment by QiWang19** [comment]
> @QiWang19 What is the state of this issue?

I haven't started working on this issue.

**Comment by mheon** [comment]
Should be made substantially easier with the patch from @vrothberg to display the original creation command in `podman inspect`

**Comment by delight** [comment]
> Yeah, I want this to be general purpose for all my containers. Which is why I like that watchtower container so much, its a very simple solution to auto update all my containerised applications.

In watchtower the behavior configureable over labels:

https://containrrr.github.io/watchtower/container-selection/

**Comment by viggy96** [comment]
@delight That's not what I want though. I want to have podman update all my containers just like watchtower does by default.

**Comment by delight** [comment]
@viggy96 anyways I think you are addressing your request to the wrong project though. IMO it's rather an implementation detail of watchtower. Right now watchtower is accessing the docker api via go. It's rather up to watchtower to support podman additionally.

**Comment by viggy96** [comment]
@delight I was just using watchtower as an example. I'm not expecting podman guys to support watchtower. I was asking for a similar solution that would work for podman. @vrothberg has already taken up this issue, so I'd say its very relevant to this project.

**Comment by mrguitar** [comment]
+1 to having a mechanism to generate timers for this. That would be great.

**Comment by rhatdan** [comment]
@vrothberg any progress on this?

**Comment by vrothberg** [comment]
No. The v2 API has a higher priority. I will tackle it after my PTO along with the open systemd issues.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/libpod/pull/5480 to support auto-updating containers. Feel free to play with it and provide feedback.
