### ISSUE TITLE
Improve cmd/podman/shared/container.go documentation

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3577]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

Documentation inside `cmd/podman/shared/container.go` can be improved:
- All periods should end with `.`.
- Some syntax error can be fixed, e.g.: `// PBatch is performs batch operations on a container in parallel`
- Documentation should follow [Go reccomendations](https://blog.golang.org/godoc-documenting-go-code), .e.g. when documenting an element, the comment should being begins with the name of the element it describes.

**Comment by rhatdan** [comment]
@marcov Have you seen any improvements on this?  @TomSweeneyRedHat What do you think?

**Comment by TomSweeneyRedHat** [comment]
I think I just assigned it to myself so I won't forget it.  @marcov I'd be happy to hear what you think none the less.

**Comment by marcov** [comment]
@TomSweeneyRedHat thank you for taking care. I intentionally left the assignee open :wink:

**Comment by baude** [comment]
I think the PR from @EmilienM cleaned this up.  I see two additional issues; one spelling error and one missing period at the end of a comment.  When i  look at this file all exported functions are documented which is the golang standard.  Unless we want to hold this issue open for the two nits, I consider this complete and ready for close.

**Comment by marcov** [comment]
Given the current state, I'm ok to close this
