### ISSUE TITLE
`podman-remote ps` has `--size` set by default

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3578]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

By default `podman-remote ps` computes all containers' rootfs and rw size, and this results in significant higher response time compared to running `podman ps`.

Effect on a system with 5 containers:
```
$ time sudo ./bin/podman-remote ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```
/usr/bin/sudo -E ./bin/podman-remote ps  0.03s user 0.01s system 0% cpu **24.108 total**
```
$ time sudo ./bin/podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```
/usr/bin/sudo -E ./bin/podman ps  0.04s user 0.03s system 100% cpu **0.075 total**

**Comment by rhatdan** [comment]
@QiWang19 PTAL
