### ISSUE TITLE
podman won't work if any single subuid/gid map exists, even if it's behind a range-map

### ISSUE THREAD

**Issue by runapp** [containers/libpod#3636]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

As title says. Please check the reproduce steps.

**Steps to reproduce the issue:**

1.
 
```sh
echo "$USER:100000:65536" >> /etc/subuid
echo "$USER:$(id -u):1" >> /etc/subuid
echo "$USER:100000:65536" >> /etc/subgid
echo "$USER:$(id -g):1" >> /etc/subgid
```

2. `killall podman`

3. `podman pull opensuse/tumbleweed` #(or any image with at least one file of uid/gid > 0)

**Describe the results you received:**

`ERRO[0011] .... there might not be enough IDs available in the namespace (requested 0:15 for /etc/shadow): lchown /etc/shadow: invalid argument`

**Describe the results you expected:**

No errors and image pulled. If I remove the two `:1` lines in `sub?id`, no error occurs.

**Additional information you deem important (e.g. issue happens only occasionally):**

In fact I don't know if it's a problem with `newuidmap` or `podman`.

And BTW I get the warning of `WARN[0000] using rootless single mapping into the namespace...` the first time I run `podman pull`. Then it creates the `pause.pid` file and stays after pull operation fails. I then modified the `/etc/sub?id` and reran `podman pull`, which didn't show the warn again, and mislead me to that if the problem was solved. Would it be better to try caching all warnings and re-show them if started from previously "paused" workers?

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-lp151.5.1.x86_64
    path: /usr/lib/podman/bin/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"opensuse-leap"'
    version: "15.1"
  MemFree: 1977597952
  MemTotal: 8154513408
  OCIRuntime:
    package: runc-1.0.0~rc6-lp151.1.2.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6
      spec: 1.0.1-dev
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  hostname: 
  kernel: 4.12.14-lp151.28.4-default
  os: linux
  rootless: true
  uptime: 123h 15m 17s (Approximately 5.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/runapp/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/runapp/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/runapp/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Are the `newuidmap` and `newgidmap` executables available? What are their permissions?

@giuseppe PTAL

**Comment by runapp** [comment]
@mheon Thank you for your quick reply.

```
:~> l `which newuidmap` `which newgidmap`
-rwsr-xr-x 1 root shadow 37944 4月  28 03:43 /usr/bin/newgidmap*
-rwsr-xr-x 1 root shadow 37912 4月  28 03:43 /usr/bin/newuidmap*
```

I believe there's no problem with them cause if I delete `$USER:$UID:1` line (and subgid one), pull operates well.

**Comment by PoisonBCat** [comment]
Maybe u can try follow commands:
echo "CURRENT USERNAME:110000:65536" > /etc/subuid
echo "CURRENT USERNAME:110000:65536" > /etc/subgid

Hope these can help you

**Comment by giuseppe** [comment]
adding the user UID/GID seems to confuse newuidmap/newgidmap.  They are not needed though as they can be already used without being present in the subuid/subgid file.

Have you found documented anywhere that they should be added to the `subuid` and `subgid` files?

**Comment by runapp** [comment]
@giuseppe I’ll check manual of newuidmap later. It’s originally for `lxc-usernxexec` to map the real uid to an container uid, which makes `chown` between real fs and chrooted fs possible.

**Comment by giuseppe** [comment]
@runapp I was wondering if you found documented anywhere that you need to add your own UID/GID to the configuration files.  Possibly newer versions behave the same way, I I think it is just a wrong configuration.

Since it seems to work with a regular configuration and that is related to newuidmap/newgidmap that are not under Podman control, I am going to close this issue.

Please feel free to add more comments or reopen it if you still think it is Podman doing something wrong.

**Comment by runapp** [comment]
@giuseppe Please check Example section of `lxc-usernsexec`, which writes:

       If your user id is 1000, root in a container is mapped to 190000, and
       you wish to chown a file you own to root in the container, you can
       use:

              lxc-usernsexec -m b:0:1000:1 -m b:1:190000:1 -- /bin/chown 1:1 $file

       This maps your userid to root in the user namespace, and 190000 to
       uid 1.  Since root in the user namespace is privileged over all
       userids mapped into the namespace, you are allowed to change the file
       ownership, which you could not do on the host using a simple chown.

That's why an extra single map to the real uid is needed.

**Comment by runapp** [comment]
BTW I found `podman pull` didn't call `/usr/bin/new?idmap` at all. I renamed `/usr/bin/newgidmap` temporarily but `podman pull` just behaves the same.
