### ISSUE TITLE
podman does not create console if -t is present in noninteractive shell

### ISSUE THREAD

**Issue by kubco2** [containers/libpod#3640]
/kind bug

**Description**
If we run podman exec -t  in non-interactive shell, it does not create console.

**Steps to reproduce the issue:**

1. 
podman run --rm -d --name test ubi8 sleep 1000

2. 
run this command in non-interactive shell:
podman exec -t test date

**Describe the results you received:**
exec failed: provided file is not a console
Error: exit status 1

**Describe the results you expected:**
It should work as with docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.4.4
```

**Comment by vrothberg** [comment]
Hi @kubco2, thanks for opening the issue. Can you share the output of `podman info --debug` and `podman --log-level=debug exec -t test date`? I am unable to reproduce it on my Fedora 30 machine.

**Comment by kubco2** [comment]
Hi, looks like it is fixed in master branch. Probably with this commit https://github.com/containers/libpod/commit/a1a79c08b72793cf2f75490d8ffc844c3d16bd4a

**Comment by mheon** [comment]
I don't think the issue is actually solved - conmon exec just introduced a new one over it.

**Comment by mheon** [comment]
Oh, nevermind. Working as advertised, per comparison with Docker. Neat.
