### ISSUE TITLE
build: `STEP n:`  messages print to StdErr

### ISSUE THREAD

**Issue by adambkaplan** [containers/libpod#3642]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman's `STEP: X` messages print to `StdErr` rather than `StdOut`

**Steps to reproduce the issue:**

1. podman build -t mytag . > /path/to/stdout.log 2>/path/to/stderr.log

**Describe the results you received:**

stdout.log contains various messages, such as if cache was used.
`STEP n:` messages are logged to stderr.log.

**Describe the results you expected:**

Expected `STEP: n` messages to print to stdout, rather than stderr.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.6
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.2.0, commit: 945b4c484b3c1b0b8c70a22ac69f9bc71d5a7f7d'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2180550656
  MemTotal: 16687108096
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 6998261760
  SwapTotal: 8413769728
  arch: amd64
  cpus: 8
  hostname: dhcp137-158.rdu.redhat.com
  kernel: 5.1.17-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 198h 27m 56.12s (Approximately 8.25 days)
registries:
  blocked: null
  insecure:
  - 172.30.0.0/16
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/adkaplan/.config/containers/storage.conf
  ContainerStore:
    number: 79
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/adkaplan/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 299
  RunRoot: /run/user/1000
  VolumePath: /home/adkaplan/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 30, local machine.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by adambkaplan** [comment]
@mheon @TomSweeneyRedHat was also able to reproduce with buildah:

```
$ buildah version
Version:         1.9.0
Go Version:      go1.12.5
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Comment by TomSweeneyRedHat** [comment]
@nalind I know that the output was sent to stderr for a reason that I'm not recalling atm, do you recall?

**Comment by TomSweeneyRedHat** [comment]
and @mheon, forgot to note, this is indeed Buildah functionality, not Podman

**Comment by nalind** [comment]
@TomSweeneyRedHat it may well have been arbitrary.  At the API level, the messages go through the `BuildOptions.Log` callback if it's set, so I guess we could add a CLI flag to have it use a callback to write them to a specified file descriptor.

**Comment by TomSweeneyRedHat** [comment]
Moved to Buildah https://github.com/containers/buildah/issues/1772, closing here.

**Comment by TomSweeneyRedHat** [comment]
FYI proposed fix:  https://github.com/containers/buildah/pull/1869
