### ISSUE TITLE
Running sshd inside container produce wired error due to pam_loginuid.

### ISSUE THREAD

**Issue by Gh0u1L5** [containers/libpod#3651]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a container running as a SSH jump host on a remote server. Recently I'm trying to switch from docker to podman. And then, argh, podman breaks my jump host in a very weird way: the SSH authentication step finished successfully, but my SSH client failed with an error code 254.

I took some time investigating the details. Later it turns out that the SSH client failed because it cannot complete the pam session on the remote server. More specifically, it failed to run a pam module called pam_loginuid. I searched on the Internet, and noticed that it seems to be a bug that has been already fixed by docker. 

Reference: https://stackoverflow.com/questions/21391142/why-is-it-needed-to-set-pam-loginuid-to-its-optional-value-with-docker

Any ideas?

**Steps to reproduce the issue:**

1. Run an OpenSSH server (v7.4 in my case) instead a container. Make sure the following line is in its PAM config:
```
session    required     pam_loginuid.so
```

2. Run an OpenSSH client (v7.9 in my case) to connect the server.

**Describe the results you received:**

The client exited with error code 254.

**Describe the results you expected:**

The client connect to the server successfully.

**Output of `podman version`:**

```
Version:            1.4.3
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.3
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-rc2, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 1875042304
  MemTotal: 8361558016
  OCIRuntime:
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2145382400
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  hostname: emerson-VirtualBox
  kernel: 5.0.0-16-generic
  os: linux
  rootless: true
  uptime: 3h 41m 20.5s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/emerson/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/emerson/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/emerson/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The test output pasted here is from a VirtualBox instance, but a bare-metal machine can produce the same error.

**Comment by mheon** [comment]
I do not think that we want to add `CAP_AUDIT_WRITE` to the default container capabilities. Maintaining a minimal set of capabilities improves the security of containers, and most containers will not require AUDIT_WRITE for normal operation. If you want to use it, you can add `--cap-add audit_write` to your Podman command line.

You can also look into making the loginuid module optional - the linked StackOverflow article notes that this ought to be possible.

**Comment by Gh0u1L5** [comment]
Ummm, cool, if that's about security concerns, then I'm totally okay with it. I'll close the ticket and consider using optional pam module instead. Thanks for your reply.

**Comment by vrothberg** [comment]
@mheon, Podman is currently setting AUDIT_WRITE
```
[libpod (master)]$ podman top -l capeff
EFFECTIVE CAPS
AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,SETUID,SYS_CHROOT
```

**Comment by mheon** [comment]
Huh. Guess it must have made its way into the default caps in the OCI generator. I had a feeling we wouldn't want it because it can be used to break our `loginuid` chain.

**Comment by rhatdan** [comment]
Personally I think we should drop it.  Running sshd inside of a container should not be supported by default, users should have to do a --cap-add AUDIT_WRITE if they want this to work.

**Comment by rhatdan** [comment]
Is your failure SELinux or trying to do this as rootless?  I would figure rootless would not work.

**Comment by Gh0u1L5** [comment]
@mheon After reading @vrothberg 's reply, I got curious and tested SSHD in container with the `--cap-add CAP_AUDIT_WRITE` flag. Surprisingly, that didn't fix the problem. There's something else breaks pam_loginuid.so in podman.

**Comment by mheon** [comment]
Interesting. Can you provide a few more details to help reproduce? Podman command used to run the container, whether you're running as root?

**Comment by Gh0u1L5** [comment]
@mheon @rhatdan I'm running podman as root, with SELinux disabled. The podman command I ran unfortunately requires a private container image that I cannot provide. But I'll try find a valid public image to help reproduce the problem.

**Comment by Gh0u1L5** [comment]
@mheon __Reproduce Steps:__
1. Add 'docker.io' to podman's registries.
2. Start a Fedora 20 container using
``` bash
sudo podman run -it fedora:20 /bin/bash
```
3. Install OpenSSH server using
``` bash
yum -y install openssh-server
ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
```
4. Create a temporary user and set its password.
5. Start SSHD on port 2222 with debug output
``` bash
/usr/sbin/sshd -d -p 2222
```
6. SSH to the container from the outside
``` bash
ssh -p 2222 <container IP>
```

**Comment by baude** [comment]
fedora 20?

**Comment by baude** [comment]
using your instructions and the latest master build, i was able to make this work perfectly.  the key is to use the latest **fedora** package that is actually from **fedora**.

```
sudo podman run -it --rm registry.fedoraproject.org/fedora:latest /bin/bash
[root@24899cac9bdd /]# dnf -y install passwd openssh-server
...
[root@24899cac9bdd /]# ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
...
[root@24899cac9bdd /]# ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ""
...
[root@24899cac9bdd /]# ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
...
[root@24899cac9bdd /]# useradd foobar
[root@24899cac9bdd /]# passwd foobar
...
[root@24899cac9bdd /]# /usr/sbin/sshd -d -p 2222
...
debug1: Bind to port 2222 on ::.
Server listening on :: port 2222.
```

In another terminal, ssh into the container.

**Comment by Gh0u1L5** [comment]
Cool, thanks @baude , that's a really helpful observation for me.

Another interesting fact is, I just tested both Fedora 20 and latest Fedora on docker 19.03.1, sshd is working properly on both of them. So the old Fedora must have something inside its pam_loginuid that's working for docker, but won't work in podman. Is this fact helpful for you guys?

**Comment by Gh0u1L5** [comment]
By the way, I feel I may have to briefly explain why I choose Fedora 20 to reproduce this bug.

I choose Fedora 20 because this bug was found on a RHEL 7.5 container (which is the majority of the RHEL systems I guess). I'm not familiar with the version mapping between Fedora and RHEL, but I roughly remember that some old RHEL 7 releases was based on Fedora 19~20. That's why I pick Fedora 20. Moreover, that means this bug may also exists in some newer Fedora versions.

**Comment by baude** [comment]
@rhatdan @mheon ring any bells?

@Gh0u1L5 lemme try this on a centos container, much closer imho

**Comment by baude** [comment]
The following works as expected.  Please try building this Dockerfile.
```
FROM registry.centos.org/centos:latest
RUN yum -y update && yum -y install openssh-server passwd && yum clean all
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N "" && ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N "" && ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
RUN useradd foobar && echo "foobar:foobar" | chpasswd
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
```

**Comment by baude** [comment]
@Gh0u1L5 I hope my feedback works ... given that Fedora 20 is way past end-of-life, it is a tough scenario to work with.

**Comment by rhatdan** [comment]
One key difference between podman and docker is that when you run podman the  /proc/self/loginuid would be set, not sure if this would cause issues.   Since pam_loginuid will fail when it tries to set it.  In Docker it will not be set.
```
# podman run fedora cat /proc/self/loginuid 
3267
 ```
That is my UID.

```
# docker run fedora cat /proc/self/loginuid 
4294967295
```
That is the UID=-1 basically meaning the docker daemon was never started by a logged in user.

I would also try to run the sshd container fully privileged to see if something else is causing an issue.

**Comment by baude** [comment]
may we close?

**Comment by mheon** [comment]
No, we're still working this one

**Comment by rhatdan** [comment]
I think this is fixed.  I don't see this as a bug.  It is just a configuration issue in the container image as @baude pointed out.  Reopen if you disagree.

**Comment by reenberg** [comment]
@rhatdan, I kind of disagree with this being a configuration issue of the container.  That change of `pam_loginuid.so` from required to optional is a workaround.  

However I wonder if that workaround could impose a security issue in some way?  Anyways, the root cause should really be fixed instead.

Unless I have totally misunderstood something, then this bug has been reported in Debian ([726661](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=726661), OCT 2013), LXC ([#661](https://github.com/lxc/lxc/issues/661), SEP 2015).  

One of the Ubuntu/LXC developpers made a patch for this issue in linux-pam (https://github.com/linux-pam/linux-pam/commit/2e62d5aea3f5ac267cfa54f0ea1f8c07ac85a95a) JAN 2014.

[BZ#1728777](https://bugzilla.redhat.com/show_bug.cgi?id=1728777) was opened JUN 2019, regarding this patch nog being present in RH, and it seems to have been acceptet (Status: ON_QA → VERIFIED).

So i agree, this is not a bug in podman, it rather seems like a bug in RH and thus also CentOs, and potentially other distros as well, if they aren't using a "newer" version of pam or have backported that patch.

Sorry to bring up a closed ticket like this, but I felt like it was missing some background info, for future people coming by with this issue (like myself).
