### ISSUE TITLE
Feature: do not copy in libpod.conf to user directory

### ISSUE THREAD

**Issue by hholst80** [containers/libpod#3658]
Please do not copy in a copy of `libpod.conf` into the user directory `.config/container/libpod.conf` it is a surprising behavior for almost any application I have used on Linux. The expected and, may I say, correct behavior should be

1) if `.config/container/libpod.conf` exists use that, or continue
2) if `/etc/container/libpod.conf` exist, use that or continue
3) if `/usr/share/...` exist, ...
4) use compile time defaults, or break.

This probably requires some re-engineering on the config format itself. An example, an undefined `volume_path` depends on the user id (and if running in rootless or not). I suggest putting the config logic, now used to write out a config in the home directory, in the config loader instead. Make a `podman config` that emits the active config if the user should want to have it's own config to maintain and customize.

An additional side effect of doing it like I suggest instead of like it is done now, where a standard conf is populated in the user directories, is that it moves the expected version migration duties from  podman to the package manager. Requiring podman understand a long chain of legacy formats for its configs seems to me just seems like a lot of unnecessary work created for podman.

**Comment by mheon** [comment]
Rootless configs are very different from the root configurations that live in `/etc/containers` in terms of default settings - numerous things (CGroup manager, logging configuration, paths for container storage, etc) differ, and some (most notably the paths in use) differ from user to user. We could theoretically run rootless without a config file, but we'd be recomputing defaults every time, which could result in unexpected behaviour (there are scenarios where we might use a different temporary directory, which could cause us to lose track of running containers).

We could probably move everything except those basic paths into a common rootless config somewhere in `/etc/` though.

**Comment by giuseppe** [comment]
also another reason why we do that is that the defaults settings can change (e.g. different runtime directory whether you run through `sudo` or the user logins), so it is safer to just create it once and re-use it.

**Comment by baude** [comment]
should this be closed?
