### ISSUE TITLE
[Feature Request] Multiple Networking

### ISSUE THREAD

**Issue by draplater** [containers/libpod#3669]
Containers can join multiple networks which allows you to provide fine grained network policy for connectivity and isolation. Docker has a command ```docker network connect``` to let containers join multiple network, but it's inconvenient for podman to do this.

https://success.docker.com/article/multiple-docker-networks

**Comment by mheon** [comment]
Podman allows you to do this, but you must specify the networks at creation time with `--net=<network_name>`

**Comment by baude** [comment]
@draplater acceptable ?

**Comment by thapliyalgunjan** [comment]
I am also looking for the same. Doesn't look like it is supported
The --net option at the time of container creation allows container to connect to a single network.
The "docker network connect" with the docker daemon used to allow connecting container to multiple isolated networks

**Comment by mheon** [comment]
List all networks you want to connect to, separate by commas.

E.G. `podman run --net=network1,network2,network3`
