### ISSUE TITLE
“podman ps” and “podman info” crashes without CAP_DAC_OVERRIDE capability.

### ISSUE THREAD

**Issue by Gh0u1L5** [containers/libpod#3684]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have an environment that contains some sensitive information, and thus drops some capabilities after sudo. E.g. CAP_DAC_OVERRIDE.

The docker containers have been deployed by a headless root user with full capabilities, so for this part I have no problem. But when I start a script to monitor the containers status, `podman ps` crashes unexpectedly, with the following errors:

> Error: error creating libpod runtime: error changing permissions on file for metacopy check: chmod /var/lib/containers/storage/overlay/metacopy-check259741764/merged/f: permission denied

I checked the source codes, and eventually located to [this line](https://github.com/containers/storage/blob/v1.12.16/drivers/overlay/check.go#L157) in containers/storage. It seems that the driver requires CAP_DAC_OVERRIDE to chmod in "metacopy check". This leaves me a few questions:

1. What's the purpose of this "metacopy check"?

2. Can we assume "usingMetacopy" is false if an error is thrown during the check?

3. If not, can we omit "metacopy check" if current root user doesn't have CAP_DAC_OVERRIDE?

4. Shouldn't the "/var/lib/containers/storage/overlay/metacopy-check259741764/merged/f" file be owned by root? Why root cannot chmod on it after dropping CAP_DAC_OVERRIDE?

By the way, because currently podman cache the metacopy check result in its $RUNHOME, I now have an ugly workaround: manually add a metacopy()-false file to the $RUNHOME, then `podman ps` will work as expected. This is apparently something that can be easily broken in the future, so I'm here to ask for some help.

**Steps to reproduce the issue:**

1. Clean the cached results of previous metacopy check.
``` bash
rm -rf /var/run/containers/storage/overlay/
```

2. Drop the CAP_DAC_OVERRIDE capability.
``` bash
sudo capsh --drop=cap_dac_override --
```

3. Run some podman commands like
```
podman ps
podman info
```

**Describe the results you received:**

> Error: error creating libpod runtime: error changing permissions on file for metacopy check: chmod /var/lib/containers/storage/overlay/metacopy-check259741764/merged/f: permission denied

**Describe the results you expected:**

> CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.3
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.3
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-rc2, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 759484416
  MemTotal: 8361558016
  OCIRuntime:
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 2139820032
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  hostname: emerson-VirtualBox
  kernel: 5.0.0-16-generic
  os: linux
  rootless: false
  uptime: 19h 7m 9.33s (Approximately 0.79 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by mheon** [comment]
@nalind Looks like this is out of c/storage

**Comment by baude** [comment]
@Gh0u1L5 does dropping the metacopy from the options in storage.conf make it work?

**Comment by Gh0u1L5** [comment]
@baude Currently I don't have metacopy option in storage.conf, what should I write to drop it?

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

By the way, I happen to have a question about podman's configure: Is there an option to turn off iptables for root podman? Like the `"iptables": false` option in /etc/docker/daemon.json?

**Comment by rhatdan** [comment]
@Gh0u1L5 containers/storage does some setup checks on overlay file system the first time it is run, we would need a patch to it to handle the permission denied, and then this should work.  Could you look there to open a PR to fix this.
Don't know about the iptables: false.

**Comment by rhatdan** [comment]
@nalind @rhgoyal WDYT?

**Comment by rhatdan** [comment]
This looks like it is a bug in metacopyup on override.

If you remove metacopyup from storage.conf, this should start working.

**Comment by Gh0u1L5** [comment]
Hi @rhatdan , if I don't have metacopyup in my storage.conf, what should I do?

**Comment by Gh0u1L5** [comment]
By the way, how should we patch the permission denied case? Just return usingMetacopy=false?

**Comment by mheon** [comment]
I believe Dan is working on a patch to fix this on the c/storage side

**Comment by rhatdan** [comment]
@mheon no that is a different metacopyup issue.  This one is being investigated in the kernel, by @rhvgoyal

**Comment by rhvgoyal** [comment]
Debugged this a little bit. Found that work/work dir does not have any read/write/execute permission. 

d---------. 2 root root 6 Aug  8 11:42 work

So any attempt to create file during copy up fails without CAP_DAC_OVERRIDE.

I am wondering if permission on work can be relaxed to 600. This is supposed to be overlay internal
directory which nobody is supposed to be looking into. I am hoping that allowing read/write access to root (even without CAP_DAC_OVERRIDE) is probably ok.

Will give it a try and see what upstream thinks about it.

**Comment by rhvgoyal** [comment]
BTW, this problem is not associated with metacopy feature. It happens even without metacopy enabled. Basically CAP_DAC_OVERRIDE for mounter is needed, given the current code.

**Comment by rhvgoyal** [comment]
Even if I get rid of CAP_DAC_OVERRIDE requirement for work dir, I think in some cases it can fail to copy up. If target directory is owned by user and root does not have permissions to write in that directory, then copy up of file will fail?

So to me it looks like CAP_DAC_OVERRIDE will still be needed to make these cases work.

@rhatdan WDYT

**Comment by rhvgoyal** [comment]
I wrote a fix for work dir and then tried running unionmount-testsuite with CAP_DAC_OVERRIDE dropped and it failed very soon. 

I think it was trying to open a file owned by "bin" write only and got permission denied. Given current security model in overlay, we check permission on lower/upper inode against the credentials of mounter. And if file is owned by bin without any write permission for root, it fails.

-rw-r--r--. 1 bin bin 12 Aug  8 14:03 /mnt/a/foo101
./run --open-file /mnt/a/foo101 -w -W q
/mnt/a/foo101: Unexpected error: Permission denied

So my understanding is that mounter needs to have CAP_DAC_OVERRIDE.

**Comment by rhatdan** [comment]
So that means if I as a user wanted to write to a file and I owned the file, it would fail because the mounter would be running as root and not dwalsh, correct?

**Comment by rhatdan** [comment]
@Gh0u1L5 How pratical is this with these constraints?  Vivek could make a fixed kernel available, but not much will work with it.

**Comment by rhatdan** [comment]
One potential alternative would be fuse-overlayfs, although It might have the same issues.  @giuseppe WDYT?

**Comment by giuseppe** [comment]
fuse-overlayfs will still have to deal with the different UIDs/GIDs available in the user namespace, so I am afraid it will fail in the same way.

**Comment by baude** [comment]
is there anything that can be done here or should we close?

**Comment by mheon** [comment]
I think we're stuck - Podman, running as root, does require DAC_OVERRIDE.
