### ISSUE TITLE
rawhide: run with --uidmap: container init caused ... operation not permitted

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3685]
Just a heads-up about rawhide:
```
# podman run --rm alpine true
[ ok ]

# podman run --rm --uidmap 0:100:10000 alpine true
Error: time="2019-07-31T21:47:03-04:00" level=warning msg="signal: killed"
time="2019-07-31T21:47:03-04:00" level=error msg="container_linux.go:346: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"sysfs\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/abc9cfd9515c80731af19b9e50beb60697a8f51a74a64e71a79b10c652457127/merged\\\\\\\" at \\\\\\\"/sys\\\\\\\" caused \\\\\\\"operation not permitted\\\\\\\"\\\"\"\n"
container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"sysfs\\\" to rootfs \\\"/var/lib/containers/storage/overlay/abc9cfd9515c80731af19b9e50beb60697a8f51a74a64e71a79b10c652457127/merged\\\" at \\\"/sys\\\" caused \\\"operation not permitted\\\"\""
: OCI runtime error
```
Seems to be kernel: 5.3.0-0.rc1.git3.1.fc31 demonstrates this, 5.1.0-0.rc1 does not. (But other things may have changed in the reboot, so I can't be sure. I can't narrow it down further; simply upgrading kernel on my virt, without a full dnf upgrade, yields an unbootable system).

It is not podman-related: both podman-1.4.5-0.29.dev.gitd6b41eb.fc31 and 1.4.5-0.59.dev.git680a383.fc31 exhibit the same behavior.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by edsantiago** [comment]
Filed: [rhbz#1736758](https://bugzilla.redhat.com/show_bug.cgi?id=1736758)

**Comment by giuseppe** [comment]
fixed upstream by: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5c6207539aea8b22490f9569db5aa72ddfd0d486

**Comment by vrothberg** [comment]
Closing since it seems to be fixed in Rawhide now.
