### ISSUE TITLE
Embedded DNS in containers

### ISSUE THREAD

**Issue by Rydekull** [containers/libpod#3694]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

There is a feature that I am missing in podman to sort of prevents me from transitioning completely.

Its fairly easily demonstrated:
[root@jotun ~]# docker network create mynet
7cc8cd4a5a5712bc797fed1da7dc6f16a8fae8b0f4cfb4470e8b98c7fc88c0cd
[root@jotun ~]# docker run -d --rm --network mynet --name nginx1 nginx:latest
a3e2cc7dc8009e416ab01bdc23e4a11b84efa2a09689412cca142d85bffef21e
[root@jotun ~]# docker run -d --rm --network mynet --name nginx2 nginx:latest
874e9a4dc5b1c12c6881d4e96808850beb7a055167b53b7a534724d5f110875b
[root@jotun ~]# docker ps | grep nginx
874e9a4dc5b1        nginx:latest                "nginx -g 'daemon ..."   6 seconds ago       Up 5 seconds          80/tcp nginx2
a3e2cc7dc800        nginx:latest                "nginx -g 'daemon ..."   15 seconds ago      Up 14 seconds         80/tcp nginx1
[root@jotun ~]# docker exec -it nginx2 bash
root@874e9a4dc5b1:/# curl -v nginx1
...
*   Trying 172.21.0.2...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55e95bce9dd0)
* Connected to nginx1 (172.21.0.2) port 80 (#0)
...
root@874e9a4dc5b1:/# exit
[root@jotun ~]# docker exec -it nginx1 bash
root@a3e2cc7dc800:/# curl -v nginx2
...
*   Trying 172.21.0.3...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55fb9695ddd0)
* Connected to nginx2 (172.21.0.3) port 80 (#0)
...
root@a3e2cc7dc800:/# exit

As you can see above, I create a docker network, two containers, and then I could automatically address the name of each container from within.

This is really helpful when setting up containers on a host and having for example an application find the database.

You can find more information from dockers documentation here:
https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/

I mean, its nothing special as such, but every network seems to get its own dns subdomain, which is named like the docker network created.

As such, the hosts above are actually named nginx1.mynet and nginx2.mynet as described.  It sets up both A and PTR records.

This is very convenient for anyone using containers daily.

This is probably somewhere in the realm between podman / CNI or in conjunction. But I personally think that maybe getting some inspiration from libvirt can be useful and spawn of a dnsmasq for a network once created via podman would be useful. Since it would allow for a greater flexibility.

At any rate, as long as A/PTR records are created/removed when containers are created/deleted on a CNI network, i'll be happy :-)

**Comment by baude** [comment]
https://github.com/containers/dnsname/  should give you what you want.
