### ISSUE TITLE
Cannot access container from container via host

### ISSUE THREAD

**Issue by ephracis** [containers/libpod#3697]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a use case where I need one container to access a bunch of other containers. I am trying to port this from Docker to Podman but ran into an issue when two containers reside on the same host.

When using Docker I just had container A access server 1 and server 2 on their DNS names, and it worked, no matter which server container A was running on. But with Podman it seems that container A cannot reach pods on the same host.

Since there are different mechanisms creating these two types of containers, and it may not always be the case that the containers will be colocated on the same server, using a pod is out of the question.

**Steps to reproduce the issue:**

1. On server 1, create container A

2. On server 1, create container B listening on port X

3. On server 2, create container B listening on port X

4. From container A, try to access server 2 on port Y

5. From container A, try to access server 1 on port Y

**Describe the results you received:**

The last step fails. A simple curl command "hangs" and times out.

**Describe the results you expected:**

The last step should succeed with a response from container B.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.3.2
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.3.2
host:
  BuildahVersion: 1.8.2
  Conmon:
    package: podman-1.3.2-1.git14fdcd0.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: e0b5a754190a3c24175944ff64fa7add6c8b0431-dirty'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 992817152
  MemTotal: 1927389184
  OCIRuntime:
    package: runc-1.0.0-59.dev.git2abd837.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: haproxy-chbr-node1.vms.dev.basalt.se
  kernel: 3.10.0-957.12.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 33m 35.14s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- OpenStack Rocky.
- All access is using DNS which resolves to a 192.168.0.0/24 address
- If I start a listening netcat on server 1 then container A can access that port. It's when it's trying to access a port of a container on the same port it stops working.

**Comment by ephracis** [comment]
I can ping both servers from the container. So the routing seems to work properly. The issue is somewhere else.

If I figure out the dynamically assigned IP of the other container (10.88.0.5) I can access it (although not using the published port but the "inside" port). It's when I try to access on the host IP 192.168.0.11 that I get a timeout. But 192.168.0.12 works fine (server 2).

**Comment by mheon** [comment]
I think the inside vs outside port behavior is mostly expected. The outside port is only mapped on the host system - so I think you could access it, but you'd need to do it via the host's IP (and possibly even the host's external IP - I don't know if the forwarding logic includes the internal CNI port).

**Comment by baude** [comment]
first thing i would like to see you do is use a more recent version of podman.  1.3.2 is quite old.

also,  do you have a typo on step 5? should it be from container B?

as @mheon said, by default, we do not expose containers to networks outside of their own. i believe to do that you would need to create a firewall/iptables rule that forwards traffic from the routable network port to the container network port.

**Comment by Gh0u1L5** [comment]
I suspect you are hitting this issue https://github.com/containers/libpod/issues/2886, and this PR https://github.com/containers/libpod/pull/2940 should fix the problem.

**Comment by ephracis** [comment]
> also, do you have a typo on step 5? should it be from container B?

No. Container A is a front end, running on one server, and container B is a backend running on both the same server as A, and on other services. A distributes load across the B backends.

> I think the inside vs outside port behavior is mostly expected.

That's what I figure as well. Just wanted to mention it for completeness.

> first thing i would like to see you do is use a more recent version of podman. 1.3.2 is quite old.

It is what I get when doing `yum install podman` on my lab CentOS machines in CI. I would hope a more updated version finds its way to CentOS and RHEL very soon.

> I suspect you are hitting this issue #2886, and this PR #2940 should fix the problem.

Most definitely. Will close as a duplicate.
