### ISSUE TITLE
editing '/usr/share/containers/libpod.conf' not honored

### ISSUE THREAD

**Issue by baude** [containers/libpod#3702]
I know we moved to this approach where our downstream packages ship a '/usr/share/containers/libpod.conf' ... and i believe we want users to copy that to /etc/containers/libpod.conf and make local edits.  But it appears that changes '/usr/share/containers/libpod.conf' is not being honored.

is that by intent or a bug?

**Comment by baude** [comment]
@rhatdan wdyt?

**Comment by mheon** [comment]
If we are not honoring changes, that means we're not loading the file. That's a pretty fundamental problem - means we're probably running on compiled in defaults, as opposed to using the config file at all.

**Comment by baude** [comment]
i agree, but I want @rhatdan do agree samewise.

**Comment by rhatdan** [comment]
/etc/containers/libpod.conf should override /usr/share/containers/libpod.conf.  If it does not, we should fix this before we ship podman 1.5.

**Comment by baude** [comment]
@rhatdan I think you misunderstand ... I'm asking if I edit /usr/share/containers/libpod.conf in place, should podman honor those changes?

**Comment by mheon** [comment]
If we are not "honoring the changes" and there is no `/etc/containers/libpod.conf` in place - that's 100% a bug.

**Comment by rhatdan** [comment]
@baude Correct `rootful` should honor anything in /usr/share/containers/libpod.conf as long as their is no /etc/containers/libpod.conf.

**Comment by baude** [comment]
ok, it is a bug as @mheon  says
