### ISSUE TITLE
can't go get libpod (not enough arguments in call to watch.NewStreamWatcher)

### ISSUE THREAD

**Issue by fiws** [containers/libpod#3706]
/kind bug

**Description**

`go get -u github.com/containers/libpod/libpod` results in an error in a fresh project.

**Steps to reproduce the issue:**

1. `go mod init github.com/fiws/test-repo-123`

2. `go get -u github.com/containers/libpod/libpod`

**Describe the results you received:**

```
# k8s.io/client-go/rest
/home/fiws/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
❯ go version                                    
go version go1.12.7 linux/amd64
```

**Comment by baude** [comment]
im not sure we are committed to being able to do this are we @mheon @vrothberg

**Comment by mheon** [comment]
It seems like something we'd like to be able to support - and this makes me a little leery we might have dependency issues that might surface their heads elsewhere.

**Comment by vrothberg** [comment]
We don't have this issue in CRI-O which is using go modules. We definitely need to track this down but I assume it's a hiccup in the k8s deps. I don't know how go mod concludes to use `v11.0.0+` while were vendoring a commit from 2019...

**Comment by fiws** [comment]
> im not sure we are committed to being able to do this are we @mheon @vrothberg

Wait what? I thought this was a primary goal (with the repo being named "**lib**pod") 

Don't you expect people to depend on libpod via go? would you recommend using varlink instead?

**Comment by vrothberg** [comment]
I am certain that the **-u** is the problem as it forces to update the dependencies and some other dependency has a lower minor version of K8s in its `go.mod` which ultimately forces go mod to use an older version of k8s.

However, vendoring libpod via go mod works. If you do a `go get`, `go mod vendor` it'll work just fine. We just need to stick with the dependencies of libpod and not change them as it happens with `go get -u`.

**Comment by fiws** [comment]
Alright now (without `-u`) I'm getting the classic `go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"`

**Comment by vrothberg** [comment]
Awesome, thanks for the update, @fiws!
