### ISSUE TITLE
support --pull-always for create/run

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3734]
(extracted from a discussion on IRC)

Extend `podman-run` and `podman-create` to always pull the image. This can come in handy in systemd unit files where users might want to always run the latest images. Currently, podman will use a local image and if absent contact the registry.

`podman-build` already supports the flag and we could easily pass it down via `CreateContainer(...)`.

**Comment by mheon** [comment]
Isn't Qi working on this now? Believe it's tagged for 1.5.1.

**Comment by vrothberg** [comment]
True, the PR is here: https://github.com/containers/libpod/pull/3617
