### ISSUE TITLE
No default route when overriding mac with the tuning plugin

### ISSUE THREAD

**Issue by stigger** [containers/libpod#3743]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to use a macvlan-based network with a mac overridden using the tuning plugin. It kind of works, but there is no default route in the container. Simply removing the mac setting from the conflist (while leaving the tuning plugin reference) fixes the default route.

I don't think this is a problem in CNI, because cnitool shows identical output for both conflists (the only difference is the mac address).

**Steps to reproduce the issue:**

Run container with the following conflist:

```
{
    "cniVersion": "0.3.0",
    "name": "mynet",
    "plugins": [
      {
        "type": "macvlan",
        "master": "eth0",
        "ipam": {
          "type": "static",
          "addresses": [
            {
              "address": "192.168.132.48/24",
              "gateway": "192.168.132.1"
            }
          ],
          "routes": [
            { "dst": "0.0.0.0/0" }
          ]
        }
      },
      {
        "type": "tuning",
        "mac": "ba:c8:2b:a5:5c:50"
      }
    ]
}
```

**Describe the results you received:**

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.132.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**Describe the results you expected:**

```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.132.1   0.0.0.0         UG    0      0        0 eth0
192.168.132.0   0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-2.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 189935616
  MemTotal: 16590094336
  OCIRuntime:
    package: runc-1.0.0-64.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 12
  hostname: hostname
  kernel: 3.10.0-957.10.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 967h 51m 55.78s (Approximately 40.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 8
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /podman
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 61
  RunRoot: /var/run/containers/storage
  VolumePath: /volumes
```

**Comment by mheon** [comment]
@mccv1r0 Any clues here? We're not doing anything that would affect this part of CNI on the Podman end.

**Comment by mccv1r0** [comment]
Using that conflist, every container using ```mynet``` will get the same mac address (assuming it even works; I've never tried it... I point it out in case someone in the future happens to find this issue.)  The runtime (i.e. podman) is meant to supply a unique mac address (which it gets from e.g. bash command line or some per-container config.)

I've reproduced the overall problem with macvlan and other (e.g. bridge) CNI plugins.  When the mac is specified, the default (and possibly other) routes don't seem to be set in the container.

**Comment by rhatdan** [comment]
FYI: 
https://stackoverflow.com/questions/21018729/generate-mac-address-in-go

**Comment by mccv1r0** [comment]
https://github.com/containernetworking/plugins/pull/364

**Comment by mheon** [comment]
Fixed upstream in plugins, so I think we're good to close
