### ISSUE TITLE
Current ubuntu install instructions are broken due to conmon

### ISSUE THREAD

**Issue by h-vetinari** [containers/libpod#3763]
I wanted to upgrade to the newest podman in my ubuntu container builder, which broke podman.
```
$ sudo podman pull docker.io/library/ubuntu:bionic
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon]): invalid argument
```

Same after retrying the [install instructions](https://github.com/containers/libpod/blob/master/install.md), but after running `sudo apt-get install conmon`, things work again. I'm guessing `conmon` needs to be added as a dependency in the metadata of the PPA-package. @lsm5

**Comment by lsm5** [comment]
@h-vetinari what version of ubuntu btw?

**Comment by h-vetinari** [comment]
@lsm5 
Ubuntu 18.04

**Comment by lsm5** [comment]
@h-vetinari can you retry now with the latest podman?

**Comment by rhatdan** [comment]
I am closing this because we believe it is fixed.  Reopen if I am mistaken.

**Comment by h-vetinari** [comment]
> @lsm5: @h-vetinari can you retry now with the latest podman?

Works, thanks!
