### ISSUE TITLE
podman commit fails with btrfs driver

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3773]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running `podman commit` with storage driver btrfs fails.
                                                                                                                               

**Steps to reproduce the issue:**

1. sudo podman run -it alpine uname -a

2. sudo podman commit $(sudo podman ps -q -l) myimage

**Describe the results you received:**
```
Error: error copying layers and metadata for container "bb1897bad6c1fc8e60345d851f09326123a35f6cc63726512a840b73508824c9": Error initializing source containers-storage:eager_davinci: error extracting layer "26901245dcfe136daffb841cac3e03fa1ed4a25100dc91446754a5a16ac4028d": btrfs driver does not support mount options
```

**Output of `podman version`:**
```
$ git rev-parse HEAD
dce17390381a7c16d2f64848c2470e10d4e782ab
```

**Comment by vrothberg** [comment]
@marcov looks like the `/etc/containers/storage.conf` has the `mountopt` set. Can you check that?

**Comment by marcov** [comment]
@vrothberg mountopt is not specified. Is it something I should add then?

**Comment by vrothberg** [comment]
> @vrothberg mountopt is not specified. Is it something I should add then?

I wouldn't change that. Are you interested in chasing this bug?

**Comment by rhatdan** [comment]
This is the "ro" option, that I added to fsdiff.go.

**Comment by rhatdan** [comment]
Opened https://github.com/containers/storage/pull/416 to fix this, I believe, please try it out.

**Comment by vrothberg** [comment]
That was quick, thanks Dan!

**Comment by rhatdan** [comment]
Usually when I introduce a bug, i like to squash it as fast as possible.

**Comment by marcov** [comment]
Thank you @rhatdan, @vrothberg , confirmed to work here too.
