### ISSUE TITLE
--tmpfs defaults are not compatible with docker

### ISSUE THREAD

**Issue by computator** [containers/libpod#3780]
/kind bug

The `--tmpfs` option (and probably `--mount` too) defaults to 64MB of space, vs docker's default size is unlimited according to [this documentation](https://docs.docker.com/storage/tmpfs/#tmpfs-options) of `tmpfs-size`.

In addition, Docker's `--tmpfs` doesn't allow any options, but podman's has several. I'm not too concerned about this one though since the tmpfs syntax for podman is a superset of Docker's.

**Output of `podman version`:**

```
podman version 1.4.4
```

**Comment by rhatdan** [comment]
@ashley-cui PTAL, just change the --tmpfs to not be confined to 64k.

**Comment by rhatdan** [comment]
Or @computator if you want to take a stab at fixing it.  PRs welcome...

**Comment by ashley-cui** [comment]
> @ashley-cui PTAL, just change the --tmpfs to not be confined to 64k.

@rhatdan should I just remove the default value for --tmpfs? How would I test this?

**Comment by ashley-cui** [comment]
@rhatdan When the --tmpfs flag is used in docker, no defaults are set. However, in podman, it automatically sets various defaults:
```
$docker create --name test --tmpfs /a alpine
docker inspect test 
...
"Tmpfs": {
    "/a": ""
}
```

```
$podman create --name test --tmpfs /a alpine
podman inspect test 
...
"Tmpfs": {
                "/a": "noexec,nosuid,nodev,rw,size=65536k,rprivate,tmpcopyup"
            }
```

Should this also be fixed? I'm not really sure where the size and other defaults are used later, so I'm wary of how to manipulate it.

**Comment by mheon** [comment]
Related: #3803 

We set these defaults largely for security. I think that 65MB is a safe default that can be increased if required.

**Comment by rhatdan** [comment]
I would remove the 65mb, since this is still controlled by the cgroup.  The tmpfs space is < 50% of all available Memory for all tmpfs in the contianer (Memory cgroup).
The other flags should stay.  I don't see a problem with nodev, nosuid.  Perhaps we should eliminate noexec.
