### ISSUE TITLE
cgroupsv2: rootless: libpod.conf inherit runtimes from root configuration

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#3781]
I just enabled cgroupsv2 on my machine and set crun as the runtime in `/usr/share/containers/libpod.conf`. After removing the rootless one in `~/.config/containers/`, I expected it to inherit the runtimes setting from the root config. This would be needed for clean installation of Fedora 31 where cgroupsv2 will be enabled by default.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/3787
