### ISSUE TITLE
io.podman.Ps varlink call slow

### ISSUE THREAD

**Issue by st1971** [containers/libpod#3784]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Calling the io.podman.Ps API over varlink is excessively slow, taking approximately 30 seconds, the same behavior is exhibited with both rooted and rootless setup. Also with the all flag set to true would expect to see containers in a stopped state these are missing.
**Steps to reproduce the issue:**

1. podman varlink --timeout 0 unix:$XDG_RUNTIME_DIR/io.podman

2. varlink call unix:$XDG_RUNTIME_DIR/io.podman/io.podman.Ps '{"all": true}'

3.

**Describe the results you received:**

JSon document returned with only running containers listed, takes approximately 30 seconds for the result to be returned.

**Describe the results you expected:**

JSon document with all container listed, returned with a similar processing time to that of running 'podman ps -a'

**Additional information you deem important (e.g. issue happens only occasionally):**

If running the podman varlink interface is started with --log-level=debug set it looks from the debug output that call is descending into each overlay to get information however running 'podman --log-level=debug ps -a' does not show these filesystem interactions.

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 164df8af4e62dc759c312eab4b97ea9fb6b5f1fc'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 22082277376
  MemTotal: 33672069120
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 34359734272
  SwapTotal: 34359734272
  arch: amd64
  cpus: 8
  hostname: steve-linux
  kernel: 5.2.6-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 42h 18m 1.25s (Approximately 1.75 days)
registries:
  blocked: null
  insecure:
  - steve-linux.lan:5000
  search:
  - steve-linux.lan:5000
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/steve/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/steve/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000
  VolumePath: /var/home/steve/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical box running Fedora SilverBlue 30 
Output of uname -a
```
Linux steve-linux 5.2.6-200.fc30.x86_64 #1 SMP Mon Aug 5 13:20:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
varlink --version
18
rpm -qf `which varlink`
libvarlink-util-18-1.fc30.x86_64
```

**Comment by baude** [comment]
how many containers are in the store?

**Comment by mheon** [comment]
@baude Didn't we resolve an issue earlier where `--size` was unconditionally true for `ps` over Varlink? That sounds like a likely culprit

**Comment by st1971** [comment]
@baude Currently there are only 2 container in the store

@mheon If I add ```--size``` to ```ps``` then it takes the same amount of time to execute as it does via the varlink interface, also ```--log-level=debug``` output matches.  unfortunately there is no size option in PsOpts in v1.4.4, will look out for a new release.

**Comment by baude** [comment]
still, 30 seconds even with size is suggesting something else.  and the reporter is saying rooted and rootless. could be a lot of things at this point.

**Comment by st1971** [comment]
My apologies, i have re-timed rooted this morning and there is no problem with rooted. Don't know how i managed to screw up the timing of that quite so much.  So this is only effecting a rootless setup.

Timings for the rootless calls
```
time varlink call unix:$XDG_RUNTIME_DIR/podman/io.podman/io.podman.Ps '{"all": true}'
{
  "containers": [
    ...
    ...
  ]
}
varlink call unix:$XDG_RUNTIME_DIR/podman/io.podman/io.podman.Ps   0.00s user 0.00s system 0% cpu 37.071 total

time podman ps -a --size                                                             
CONTAINER ID  IMAGE                                 COMMAND               CREATED       STATUS           PORTS                   NAMES            SIZE
...
...
podman ps -a --size  8.89s user 13.79s system 61% cpu 36.976 total

time podman ps -a       
CONTAINER ID  IMAGE                                 COMMAND               CREATED       STATUS           PORTS                   NAMES
...
...
podman ps -a  0.05s user 0.03s system 112% cpu 0.073 total
```

**Comment by baude** [comment]
With 11 running containers, I did a brief test and the results we subsecond.

```$ time varlink call unix:/run/user/1000/io.podman/io.podman.Ps '{"all": true}'
...
real	0m0.019s
user	0m0.001s
sys	0m0.004s
```

**Comment by st1971** [comment]
@baude what version are you running 1.4.4 or 1.5.0?

**Comment by baude** [comment]
1.5 (upstream master)

**Comment by st1971** [comment]
have finally managed to get 1.5 to install on silverblue, working as expected now.  Thank you both for your help.
