### ISSUE TITLE
rawhide: rootless: podman run broken: slirp4netns failed

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3790]
On latest & greatest rawhide:
```
$ podman run --rm  alpine date
Error: slirp4netns failed
```
Debug log attached, but there is no useful trace of the actual slirp4netns invocation. There are cgroup warnings at the end.

Side note: I also saw, on the very first rootless run:
```
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
```
No idea if this is related.
```
podman-1.5.1-0.3.dev.git3bc861c.fc31
slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31
kernel-5.3.0-0.rc3.git1.1.fc31
runc-1.0.0-98.dev.git2e94378.fc31
```
[podman-slirp4netns-failed.log](https://github.com/containers/libpod/files/3492353/podman-slirp4netns-failed.log)

**Comment by mheon** [comment]
The warn line is fine - we're shipping a config that includes `crun` but it's not a hard dependency of the package, so if it's not available, we throw a warning in the logs and don't allow using it.

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by edsantiago** [comment]
Still failing with latest [1.5.1-0.8.dev.gitec93c9d.fc31 build](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/5670/pipeline/) (click `/tmp/package-test.sh 12m11s` and scroll to line 470) (yes, I know the line is green and should be red. That seems to have started happening last week. I'm hoping it'll get fixed). ec93c9d8 is from just a little while ago today.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
slirp4netns cannot open `/dev/net/tun`.  The file has the wrong permissions:

```
$ ls -l /dev/net/tun
crw-------. 1 root root 10, 200 Aug 13 11:56 /dev/net/tun
```

If I change it to 666 then it works fine.

It looks like a regression in udev.  Could you file a bug?

**Comment by rhatdan** [comment]
Yes this looks like  a bug.

**Comment by rhatdan** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1740664

**Comment by edsantiago** [comment]
~I'm~ I was trying to narrow down the conditions causing breakage, by dnf-upgrading and identifying the components that cause it. It is not going well (partial dnf upgrades on rawhide, followed by reboot, cause reboot hangs). I'll try one last time and will update the bz with any info I can find.

**Comment by oblitum** [comment]
I get that warn too the first time I run podman on my machine, afterwards it doesn't show up anymore, until I reboot.

**Comment by ViceIce** [comment]
A workaround for the permission issue on `docker-desktop`:

https://github.com/docker/for-win/issues/4627
https://github.com/docker/for-mac/issues/3838

**Comment by cho2** [comment]
![Cuplikan layar dari 2019-11-01 15-16-02](https://user-images.githubusercontent.com/6271071/68011743-b5757080-fcba-11e9-857a-5e661649fc3f.png)
OS: openSUSE Leap 15.1

**Comment by rhatdan** [comment]
https://github.com/containers/libpod/pull/4350 will at least get us the output of what the error is.  and this has been merged upstream.  If someone could try this out and tell us why slirp4netns is failing.

**Comment by stderr-enst** [comment]
1.6.3 should contain #4350, right?
Any idea when the projectatomic ppa will ship 1.6.3 for ubuntu 18.04?
I would provide the output to this bug, but I don't have the time right now to build podman myself on this machine.

**Comment by TomSweeneyRedHat** [comment]
@stderr-enst yes, 1.6.3 includes the changs from #4350.  IDK about the shipping time to ubuntu, if anyone would it would be @lsm5

**Comment by rufoa** [comment]
> 1.6.3 should contain #4350, right?
> Any idea when the projectatomic ppa will ship 1.6.3 for ubuntu 18.04?
> I would provide the output to this bug, but I don't have the time right now to build podman myself on this machine.

Just built the deb for 1.6.3 manually
Can confirm this issue is resolved on both Ubuntu and Debian
