### ISSUE TITLE
regression: podman run: exit status 0 after 'rm --force`

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3795]
```
# (podman run --name foo alpine sleep 30;echo $?)&
[1] 13212
# podman rm --force foo
[pause 10 seconds]
57c5063848af9f40b436d224ea2ef5808c5db591b6cd1aa0addb3be7e3eddf34
# 0   <--- this is the exit status. It should be 137
```
podman-1.5.0-2.fc30.x86_64

**Comment by rhatdan** [comment]
Why should it be 137?  Didn't `podman rm --force foo` work?

**Comment by mheon** [comment]
When trying to debug this, I found that events is acting properly strange.
`podman events --since 1h --until 1s` on 1.4.4 exits instantly, shows me the events in question. In 1.5.0, it seems to hang.

**Comment by edsantiago** [comment]
`podman rm` worked. The exit status pointed to by the arrow is that of the container itself, which was killed, therefore its exit status should be 137. Another way to say this:

In window 1:
```
# podman run --name foo alpine sleep 30
```
In window 2:
```
# podman rm -f foo
```
Then, after the 10-second wait, go back to window 1:
```
# echo $?
0
```
Sorry for not being clear.

**Comment by edsantiago** [comment]
Side note: `podman kill foo` and `podman stop foo` both result in a container exit status of 137, as expected. It's only `rm -f` that is weird.

**Comment by edsantiago** [comment]
@mheon I cannot reproduce that behavior. I tried with a running container, without; also with running container and running `podman rm -f foo` during the 10-second wait. The `podman events` command in question always dumps a bunch of lines, then exits 0.

**Comment by mheon** [comment]
It's journald. We're scanning every single journal entry on the system. It's taking 30 seconds to complete on my desktop.

**Comment by mheon** [comment]
@baude We're probably going to need a revert of https://github.com/containers/libpod/pull/3745 - it nuked performance of events on systems with long journals.

**Comment by rhatdan** [comment]
This seems like something we should fix before releasing to Fedora.

**Comment by mheon** [comment]
I think I got the core issue here - problem was that we were testing with file backend and not journald. Might want to look into that later.

The events performance thing is separate, and probably does require a revert.

**Comment by edsantiago** [comment]
Oh, *yuk*:
```
# podman run --rm alpine sh -c /bin/false;echo $?
0    <--- should be 1
```
Without `--rm`, works as expected (1). Without `sh -c`, also works as expected. 

This may merit a separate issue but I've got a gut sense that they're related. LMK.

**Comment by mheon** [comment]
Same issue. Fix in progress.

**Comment by mheon** [comment]
#3797 to fix both issues
