### ISSUE TITLE
[ultra-low prio] behavior change: MergedDir no longer exists by default

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3798]
This is very probably not a problem report; but it is a behavior change from 1.4, and since there's a user-visible `podman inspect` field involved, I think it's worth filing for posterity:

In short: the `/var/lib/containers/.../merged` directory is no longer created by default; it only exists during the scope of `podman mount`.
```
# podman run --name foo alpine true
# podman inspect --format '{{.GraphDriver.Data.MergedDir}}' foo
/var/lib/containers/storage/overlay/5b224370d5fc105cfbbc7cf164fbf5a05279a96a3b98b074aadc23b2b93d5902/merged
# ls -l $(!!)
ls: cannot access '/var/lib/containers/storage/.../merged': No such file or directory
```
It is created, with proper content, upon running `podman mount foo`. It is deleted again upon `podman umount foo`. In 1.4 and all earlier versions, the `merged` directory exists but is empty.

If this was a deliberate change, I wonder if perhaps `podman inspect` could be amended to omit `MergedDir` if it's not mounted? Again, this seems low priority.

podman-1.5.0-2.fc30.x86_64

**Comment by rhatdan** [comment]
We did this in an attempt to cleanup leaked mount points.  I think removing it from inspect if not mounted is a good idea.
