### ISSUE TITLE
Segfault on a failed image pull

### ISSUE THREAD

**Issue by haircommander** [containers/libpod#3802]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
CI found a segfault during a (presumed) network flake
 
**Steps to reproduce the issue:**

1. Run the CI

2. Have the universe choose to fail at a perfect moment?

**Describe the results you received:**
+0227s] === RUN   TestImage_NewFromLocal
[+0228s] Trying to pull docker.io/library/busybox:latest...
[+0229s] Getting image source signatures
[+0229s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0230s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0230s] Writing manifest to image destination
[+0230s] Storing signatures
[+0230s] Trying to pull docker.io/library/busybox:glibc...
[+0231s] Getting image source signatures
[+0232s] Copying blob sha256:3a8992130e72cd4d47c4c2b255b75912a9cd9272f53f12306c745665fffc33fb
[+0233s] Copying config sha256:32b9e6a4f1f19713280028bf2886d23edbc05c26a933685afd4e40dfd1d2d6b5
[+0233s] Writing manifest to image destination
[+0233s] Storing signatures
[+0233s] --- PASS: TestImage_NewFromLocal (6.71s)
[+0233s] === RUN   TestImage_New
[+0234s] Trying to pull docker.io/library/busybox:latest...
[+0235s] Getting image source signatures
[+0235s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0236s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0236s] Writing manifest to image destination
[+0236s] Storing signatures
[+0236s] Trying to pull docker.io/library/busybox...
[+0237s] Getting image source signatures
[+0238s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0238s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0238s] Writing manifest to image destination
[+0238s] Storing signatures
[+0239s] Trying to pull docker.io/busybox:latest...
[+0240s] Getting image source signatures
[+0240s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0241s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0241s] Writing manifest to image destination
[+0241s] Storing signatures
[+0241s] Trying to pull docker.io/busybox...
[+0243s] Getting image source signatures
[+0243s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0243s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0244s] Writing manifest to image destination
[+0244s] Storing signatures
[+0244s] Trying to pull docker.io/library/busybox:latest...
[+0245s] Getting image source signatures
[+0245s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0246s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0246s] Writing manifest to image destination
[+0246s] Storing signatures
[+0246s] Trying to pull docker.io/library/busybox...
[+0247s] Getting image source signatures
[+0248s] Copying blob sha256:ee153a04d6837058642958836062f20badf39f558be3e6c7c7773ef7d8301d90
[+0248s] Copying config sha256:db8ee88ad75f6bdc74663f4992a185e2722fa29573abcc1a19186cc5ec09dceb
[+0248s] Writing manifest to image destination
[+0248s] Storing signatures
[+0249s] Trying to pull registry.fedoraproject.org/fedora-minimal:latest...
[+0250s] Getting image source signatures
[+0250s] Copying blob sha256:8fad33c002fa130aceec4fd0cadc8bad0d7561667ab24aee75dea825be933de0
[+0256s] Copying config sha256:847a6054047619b8908f61e0211e3480ab20ce4b6cf17b03db081322ade301d3
[+0256s] Writing manifest to image destination
[+0256s] Storing signatures
[+0261s]   Error processing tar file(io: read/write on closed pipe): 
[+0261s] --- FAIL: TestImage_New (27.60s)
[+0261s]     image_test.go:143: 
[+0261s]         	Error Trace:	image_test.go:143
[+0261s]         	Error:      	Received unexpected error:
[+0261s]         	            	Error processing tar file(io: read/write on closed pipe): 
[+0261s]         	            	error adding layer with blob "sha256:8fad33c002fa130aceec4fd0cadc8bad0d7561667ab24aee75dea825be933de0"
[+0261s]         	            	github.com/containers/libpod/vendor/github.com/containers/image/storage.(*storageImageDestination).Commit
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/vendor/github.com/containers/image/storage/storage_image.go:691
[+0261s]         	            	github.com/containers/libpod/vendor/github.com/containers/image/copy.Image
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/vendor/github.com/containers/image/copy/copy.go:209
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).doPullImage
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:287
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).pullImageFromHeuristicSource
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:227
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image.go:160
[+0261s]         	            	github.com/containers/libpod/libpod/image.TestImage_New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image_test.go:142
[+0261s]         	            	testing.tRunner
[+0261s]         	            		/usr/lib/golang/src/testing/testing.go:865
[+0261s]         	            	runtime.goexit
[+0261s]         	            		/usr/lib/golang/src/runtime/asm_amd64.s:1337
[+0261s]         	            	Error committing the finished image
[+0261s]         	            	github.com/containers/libpod/vendor/github.com/containers/image/copy.Image
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/vendor/github.com/containers/image/copy/copy.go:210
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).doPullImage
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:287
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).pullImageFromHeuristicSource
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:227
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image.go:160
[+0261s]         	            	github.com/containers/libpod/libpod/image.TestImage_New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image_test.go:142
[+0261s]         	            	testing.tRunner
[+0261s]         	            		/usr/lib/golang/src/testing/testing.go:865
[+0261s]         	            	runtime.goexit
[+0261s]         	            		/usr/lib/golang/src/runtime/asm_amd64.s:1337
[+0261s]         	            	unable to pull image
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).doPullImage
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:310
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).pullImageFromHeuristicSource
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/pull.go:227
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image.go:160
[+0261s]         	            	github.com/containers/libpod/libpod/image.TestImage_New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image_test.go:142
[+0261s]         	            	testing.tRunner
[+0261s]         	            		/usr/lib/golang/src/testing/testing.go:865
[+0261s]         	            	runtime.goexit
[+0261s]         	            		/usr/lib/golang/src/runtime/asm_amd64.s:1337
[+0261s]         	            	unable to pull registry.fedoraproject.org/fedora-minimal:latest
[+0261s]         	            	github.com/containers/libpod/libpod/image.(*Runtime).New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image.go:162
[+0261s]         	            	github.com/containers/libpod/libpod/image.TestImage_New
[+0261s]         	            		/var/tmp/go/src/github.com/containers/libpod/libpod/image/image_test.go:142
[+0261s]         	            	testing.tRunner
[+0261s]         	            		/usr/lib/golang/src/testing/testing.go:865
[+0261s]         	            	runtime.goexit
[+0261s]         	            		/usr/lib/golang/src/runtime/asm_amd64.s:1337
[+0261s]         	Test:       	TestImage_New
[+0261s] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[+0261s] 	panic: runtime error: invalid memory address or nil pointer dereference
[+0261s] [signal SIGSEGV: segmentation violation code=0x1 addr=0x210 pc=0xcea078]
[+0261s] 
[+0261s] goroutine 253 [running]:
[+0261s] testing.tRunner.func1(0xc00030ce00)
[+0261s] 	/usr/lib/golang/src/testing/testing.go:830 +0x392
[+0261s] panic(0xdf8d80, 0x17ac110)
[+0261s] 	/usr/lib/golang/src/runtime/panic.go:522 +0x1b5
[+0261s] github.com/containers/libpod/libpod/image.(*Image).ID(...)
[+0261s] 	/var/tmp/go/src/github.com/containers/libpod/libpod/image/image.go:286
[+0261s] github.com/containers/libpod/libpod/image.TestImage_New(0xc00030ce00)
[+0261s] 	/var/tmp/go/src/github.com/containers/libpod/libpod/image/image_test.go:144 +0x3f8
[+0261s] testing.tRunner(0xc00030ce00, 0xf583a8)
[+0261s] 	/usr/lib/golang/src/testing/testing.go:865 +0xc0
[+0261s] created by testing.(*T).Run
[+0261s] 	/usr/lib/golang/src/testing/testing.go:916 +0x35a
[+0261s] 

**Describe the results you expected:**
probably just the image pull fails gracefully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
latest master
```

**Output of `podman info --debug`:**

```
remote: false
fedora 30
root
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
this should be the link to the CI run: https://cirrus-ci.com/task/5183568630775808

**Comment by rhatdan** [comment]
Since we have not seen this again, I am going to close, @haircommander reopen if this is something you feel we should pursue.
