### ISSUE TITLE
[doc] `podman run` doesn't elaborate about named volumes

### ISSUE THREAD

**Issue by xcffl** [containers/libpod#3811]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Neither `--volume` nor `--mount` in [here](https://github.com/containers/libpod/blob/master/docs/podman-run.1.md) talk about named volumes. They only elaborate mounting a external data source with absolute path (which might be a cause of podman-compose attampts to create named volumes and bind mount them, and [might lead to data loss](https://github.com/muayyad-alsadi/podman-compose/issues/13#issuecomment-521123163)).

In Docker, both `-v` and `-m` can mount named volumes. Just give it's name. Podman handles this the same way as well.

**Describe the results you received:**
No documentation [here](https://github.com/containers/libpod/blob/master/docs/podman-run.1.md) talks about how to mount named volumes

**Describe the results you expected:**
Elaborate how to use `-v` and `-m` in `podman run` to mount named volumes in a managed state.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Huh. Did we never modify the manpages when we added volumes? Hm.

This should be a simple fix, thanks for pointing this out.

**Comment by rhatdan** [comment]
@xcffl Interested in opening a PR with updated docs?  PRs welcome...
