### ISSUE TITLE
tmpfs mounts do not accept exec option

### ISSUE THREAD

**Issue by psafont** [containers/libpod#3819]
The manual is quite clear on which flags are supported:
```
--tmpfs
This command mounts a tmpfs at /tmp within the container.  The supported mount options are the same as the Linux default mount flags. If you do not specify any options, the systems uses the following options: 
```

However the `exec` options is rejected as invalid in the current master: https://github.com/containers/libpod/blob/4d470c73ca9f441ced162431270977b967b547a1/pkg/util/mountOpts.go#L50
```
$ podman run --rm --tmpfs /tmp:exec -it docker.io/library/alpine /bin/sh
Error: unknown tmpfs option "exec": invalid mount option
```

Additional info:
This came up while using the docker wrapper for podman, docker supports this mount option for tmpfs.

A revision on the code or the documentation about this would be good to have.

**Comment by mheon** [comment]
Related: #3803 - we need the option to resolve that as well

**Comment by mheon** [comment]
We need to do this for all mounts - not just tmpfs

**Comment by mheon** [comment]
We need to update and revendor Buildah to land fixes to the shared option parse code first. Then we can add this to Podman.

**Comment by bruceg** [comment]
FWIW I am also having this issue after switching from docker to podman for a build infrastructure tool that ends up running `ldd` on built programs on tmpfs. Without the `exec` flag, this breaks.
