### ISSUE TITLE
podman cp can't only copy content within a directory as docker does

### ISSUE THREAD

**Issue by xcffl** [containers/libpod#3826]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Both `docker cp /path/to/source/ /path/to/destination` and `cp /path/to/source/ /path/to/destination` copy the **content** within the source directory to the destination. But podman copies the source **directory** instead.

**Steps to reproduce the issue:**
1. `podman cp ./data/ test_container:/tmp`

2. `podman exec test_container ls /tmp | grep data`

**Describe the results you received:**
data

**Describe the results you expected:**
Nothing, since there should be the content within data directory rather than **the data directory itself.**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.5.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.5.0
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 75436032
  MemTotal: 2087612416
  OCIRuntime:
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 474738688
  SwapTotal: 536866816
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: ip-172-26-31-172
  kernel: 5.0.0-1012-aws
  os: linux
  rootless: true
  uptime: 2h 13m 12.9s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/ubuntu/.config/containers/storage.conf
  ContainerStore:
    number: 14
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/ubuntu/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 14
  RunRoot: /tmp/1000
  VolumePath: /home/ubuntu/.local/share/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
Use source path ending with /. (that is: slash followed by dot) will copy the content.
```
// current result is same with docker
$ sudo docker cp  ./data/ 387f:/tmp
$ sudo docker exec -it 387f ls /tmp | grep data
data
```
https://docs.docker.com/engine/reference/commandline/cp/
> DEST_PATH exists and is a directory
SRC_PATH does end with /. (that is: slash followed by dot)
the content of the source directory is copied into this directory

**Comment by QiWang19** [comment]
I'll close this issue. Reopen if @xcffl still have this issue.
