### ISSUE TITLE
Podman 1.5.x rpms are failing to build on CBS 

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#3835]
/kind packaging
I am trying to test the latest release 1.5 on centos and RPM builds on CBS are failing.
Can someone take a look at the builds and fix them?  I would also appreciate a document on how you build it using rpm-build repo so I could build them manually if I need to test master or other releases. 

Thank you for all help and attention.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@alitvak69 built at https://cbs.centos.org/koji/taskinfo?taskID=918733 

RE: how it's built, all the centos specific changes are included on fedora's latest release's spec file (so right now on f30). See: https://src.fedoraproject.org/rpms/podman/blob/f30/f/podman.spec . 

RE: autobuilds, there's an hourly job at https://gitlab.com/lsm5/rpm-builder/tree/fedora-release which checks for latest released tags and builds for fedora and then for centos. It'll also check for pushing builds in testing to release for fedora and centos.

Closing..

**Comment by alitvak69** [comment]
Thank you @lsm5

**Comment by alitvak69** [comment]
I think it was closed too soon.  Where did you get libseccomp >= 2.4.1?

Resolving Dependencies
--> Running transaction check
---> Package podman.x86_64 0:1.4.4-2.el7.centos will be updated
---> Package podman.x86_64 0:1.5.1-3.el7 will be an update
--> Processing Dependency: podman-manpages = 1.5.1-3.el7 for package: podman-1.5.1-3.el7.x86_64
--> Processing Dependency: libseccomp >= 2.4.1 for package: podman-1.5.1-3.el7.x86_64
--> Running transaction check
---> Package podman.x86_64 0:1.5.1-3.el7 will be an update
--> Processing Dependency: libseccomp >= 2.4.1 for package: podman-1.5.1-3.el7.x86_64
---> Package podman-manpages.noarch 0:1.4.4-1.el7 will be updated
---> Package podman-manpages.noarch 0:1.5.1-3.el7 will be an update
--> Finished Dependency Resolution
Error: Package: podman-1.5.1-3.el7.x86_64 (virt7-container-common-el7-build)
           Requires: libseccomp >= 2.4.1
           Installed: libseccomp-2.3.2-3.el7.x86_64 (@virt7-container-common-el7-build)
               libseccomp = 2.3.2-3.el7
           Available: libseccomp-2.3.1-3.el7.i686 (base)
               libseccomp = 2.3.1-3.el7
 You could try using --skip-broken to work around the problem

**Comment by lsm5** [comment]
@alitvak69 I'm building the newest libseccomp for CBS at https://cbs.centos.org/koji/taskinfo?taskID=919837 . But I kinda wanna suggest you hold off on the upgrade cause of https://github.com/containers/libpod/issues/3838

**Comment by alitvak69** [comment]
Has issue #3838 been addressed?  If so is it 1.5.1 or it becomes 1.5.2?  Reading the issue, it seems to have no effect in ubuntu, correct?

**Comment by alitvak69** [comment]
@lsm5 Any update on this?

**Comment by matihost** [comment]
It would be nice if cbs.centos.org builds build also for CentOS8 (aka el8 arch)
CentOS 8 is shipped with pretty alpha 1.0.0-5 podman release.

Trying to install podman-1.6.1-2.el7.x86_64 on CentOS 8 (risky thou) ends with:
```
 Problem: conflicting requests
  - nothing provides conmon needed by podman-1.6.1-2.el7.x86_64
  - nothing provides containernetworking-plugins >= 0.7.5-1 needed by podman-1.6.1-2.el7.x86_64
  - nothing provides podman-manpages = 1.6.1-2.el7 needed by podman-1.6.1-2.el7.x86_64
  - nothing provides runc >= 1.0.0-57 needed by podman-1.6.1-2.el7.x86_64
  - nothing provides slirp4netns >= 0.3.0-2 needed by podman-1.6.1-2.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
There is no conmon package on cbs.centos.org at all.

**Comment by lsm5** [comment]
I'll build conmon for centos.

On Mon, Oct 14, 2019 at 04:58:25AM -0700, matihost wrote:
> It would be nice if cbs.centos.org builds build also for CentOS8 (aka el8 arch)
> CentOS 8 is shipped with pretty alpha 1.0.0-5 podman release.
> 
> Trying to install podman-1.6.1-2.el7.x86_64 on CentOS 8 (risky thou) ends with:
> ```
>  Problem: conflicting requests
>   - nothing provides conmon needed by podman-1.6.1-2.el7.x86_64
>   - nothing provides containernetworking-plugins >= 0.7.5-1 needed by podman-1.6.1-2.el7.x86_64
>   - nothing provides podman-manpages = 1.6.1-2.el7 needed by podman-1.6.1-2.el7.x86_64
>   - nothing provides runc >= 1.0.0-57 needed by podman-1.6.1-2.el7.x86_64
>   - nothing provides slirp4netns >= 0.3.0-2 needed by podman-1.6.1-2.el7.x86_64
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```
> There is no conmon package on cbs.centos.org at all.
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/libpod/issues/3835#issuecomment-541634424

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
ummmm .. btw, el7 package install on el8 isn't supported, so even after conmon is built and available, it may not work, and there's not much I'll be able to do about it. Just FYI.

**Comment by matihost** [comment]
Thanks.

I'm just wondering about the general strategy related to podman to RHEL/CentOS 8 family.

* The CentOS/RHEL 7 extras repo contains podman 1.4.4

* RHEL7 still contains docker (old, but native docker) - so there is small pressure to switch to podman.

* RHEL/CentOS 8 have old podman (1.0.0 - no networking is my biggest struggle) - w/o real docker replacement this system version is unusable now.

So just recommending to at least continous release package  not only for Mac, but also for RHEL / CentOS distros.

Please expose some CI repo with latest packages for all RHEL family distibutions.

**Comment by lsm5** [comment]
> Thanks.
> 
> I'm just wondering about the general strategy related to podman to RHEL/CentOS 8 family.

CentOS Stream is coming. That should take care of this AFAICT.

**Comment by rhatdan** [comment]
Starting at 8.1 (November) we will move podman to a new release every three months.  Hopefully a lot closer to the released version.  Or -1 of it.

**Comment by denji** [comment]
CentOS 8 Stream - podman 1.0.5...
```
# podman version
Version:       1.0.5
Go Version:    go1.11.6
OS/Arch:       linux/amd64
```

**Comment by yrobla** [comment]
Centos 8 is still on 1.0.5 version, while RHEL 8 has a much newer version. How can we get the matching version for CentOS 8?

**Comment by matihost** [comment]
CentOS has a delay with RHEL release (several months).
However - the  "cr" yum repository contains CentOS 8.1 packages - so you can 
```
sudo yum-config-manager --enable cr
```
and try install podman 
Or only for podman:
```
sudo yum install --enable-repo=cr -y podman
```


But it is still old podman 1.4.x

If you need fresh podman, either switch to Fedora or Ubuntu - as packages are fresh there (1.6.2)
Or build podman from scratch (haven't tried thou)
Or hunt for some el7 rpm build on cbs repo.
