### ISSUE TITLE
Support pod host network

### ISSUE THREAD

**Issue by chenzhiwei** [containers/libpod#3837]
This is a follow up issue of PR: https://github.com/containers/libpod/pull/3836

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Support pod host network:
* In pod yaml file
* In pod create --network host

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@baude This seems to be going along with what you demo'd yesterday?

**Comment by daledude** [comment]
Being able to set --network on pod create would be useful to us since we use macvlan. Currently Z
I have to create a container in the pod with my shared network and use that as options to other containers in the pod.

**Comment by rhatdan** [comment]
@mheon is this something that is being worked on?

**Comment by mheon** [comment]
https://github.com/containers/libpod/pull/5241
