### ISSUE TITLE
update github issue report template to include rpm/deb version

### ISSUE THREAD

**Issue by lsm5** [containers/libpod#3839]
@baude @mheon PTAL..

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When filing a new issue, it would be useful to collect the rpm or deb package info in the details than to manually ask the reporter to fill in those details later on. See https://github.com/containers/libpod/issues/3838 for example.

The template addition could look like so:

**Output of `rpm -q podman` (fedora/rhel/centos) or `apt list podman` (ubuntu/debian):**

```
(paste your output here)
```

**Comment by lsm5** [comment]
I notice `podman info --debug` does list rpm version with conmon info, but that won't be the case once conmon is independent.

**Comment by baude** [comment]
make a pr lokesh!

**Comment by lsm5** [comment]
ha, I'll do that, I thought this was some github magic I didn't have access to :D
