### ISSUE TITLE
Document using rootless container with systemd

### ISSUE THREAD

**Issue by MatMaul** [containers/libpod#3866]
Rootless podman works great with systemd to manage services ran as a user.
However it would be nice to add some docs for that somewhere, or tweak `generate systemd` for the rootless use case.

The 2 difficult points I ran into was:
- the service must depends on `user@uid.service` so the user dbus session is initialized and the /run user folder exists
- KillMode=none as explained in #3657

Here is a working unit:
```
[Unit]
Description=nginx
Requires=user@1003.service
After=user@1003.service

[Service]
Type=simple
KillMode=none
ExecStartPre=-/usr/bin/podman rm -f nginx
ExecStartPre=/usr/bin/podman pull nginx
ExecStart=/usr/bin/podman run --name=nginx -p 8080:80 nginx
ExecStop=/usr/bin/podman stop nginx
Restart=always
User=nginx
Group=nginx

[Install]
WantedBy=multi-user.target
```

**Comment by rhatdan** [comment]
PRs and Blogs welcomed.  :^)

**Comment by MatMaul** [comment]
Where do you think I could contribute such a doc ?

**Comment by MatMaul** [comment]
rootless_tutorial.md ?

**Comment by TomSweeneyRedHat** [comment]
I'd drop it in rootless_tutorial at least to start.  I'd make a new section for it in that md file.

**Comment by mheon** [comment]
I think both of these could be pretty easily dropped into `generate systemd` as defaults based on a rootless.IsRootless() check
