### ISSUE TITLE
Flag "--pull" of "podman run" not recognized

### ISSUE THREAD

**Issue by matpen** [containers/libpod#3867]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The flag `--pull` of `podman run` documented [here](https://github.com/containers/libpod/blob/master/docs/podman-run.1.md) does not work.

**Steps to reproduce the issue:**

1. Run a simple test: `podman run --rm --pull=never docker.io/library/ubuntu:18.04 true`

2. Observe the error: `Error: unknown flag: --pull`

**Describe the results you received:**

The command fails.

**Describe the results you expected:**

The command should not fail (according to the docs).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.5.0
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 1578082304
  MemTotal: 16673423360
  OCIRuntime:
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 17018646528
  SwapTotal: 17036734464
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: matteo-laptop
  kernel: 5.0.0-25-generic
  os: linux
  rootless: false
  uptime: 6h 19m 27.38s (Approximately 0.25 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 32
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /home/matteo/MyData/data/podman/root
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 126
  RunRoot: /var/run/containers/storage
  VolumePath: /home/matteo/MyData/data/podman/root/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/bionic,now 1.5.0-2~ubuntu18.04~ppa5 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical host (laptop).

**Comment by mheon** [comment]
Probably a remote vs local thing - are you using podman-remote?

**Comment by matpen** [comment]
Nope, just flat local `podman`.

**Comment by TomSweeneyRedHat** [comment]
I was near that code yesterday, I'll hop in and take a look.

**Comment by TomSweeneyRedHat** [comment]
Seems to be working on Fedora 30 Podman v1.5.2-dev

```
# podman run --rm --pull=never docker.io/library/ubuntu:18.04 true

# podman run --rm --pull=always docker.io/library/ubuntu:18.04 true
Trying to pull docker.io/library/ubuntu:18.04...
Getting image source signatures
Copying blob 6001e1789921 skipped: already exists
Copying blob 35c102085707 skipped: already exists
Copying blob 251f5509d51d skipped: already exists
Copying blob 8e829fe70a46 skipped: already exists
Copying config a2a15febcd done
Writing manifest to image destination
Storing signatures

# podman version
Version:            1.5.2-dev
RemoteAPI Version:  1
Go Version:         go1.12.6
OS/Arch:            linux/amd64
```

Trying to find a 1.5.0 kit to see if it's a problem that's been fixed since then.

**Comment by TomSweeneyRedHat** [comment]
@matpen My confusion with this one is I remember reviewing the code a few weeks back, but the PR (https://github.com/containers/libpod/pull/3617) was just merged a few days ago.  This functionality is only currently available in upstream Podman and will be part of the next release.  You can verify this by doing `man podman run` and I'm sure you won't see the `--pull` option there.  The online man page is valid for the upstream version of Podman only.

If you can build Podman from GitHub, then the --pull will be available.

Hope that helps!  I'm going to close this issue.

**Comment by matpen** [comment]
@TomSweeneyRedHat Indeed the option is not in the manpage! Thank you for clarifying that, and sorry for the noise...
