### ISSUE TITLE
Unable to run imported image rootless

### ISSUE THREAD

**Issue by oblitum** [containers/libpod#3871]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've just saved an image that's working just fine to a tarball and then imported it and tried to run it but I keep getting errors.

**Steps to reproduce the issue:**

1. `podman save archlinux -o archlinux.tar`

2. `podman import archlinux.tar archlinux2`

**Describe the results you received:**

```
[I] ➜ podman images
REPOSITORY                     TAG      IMAGE ID       CREATED          SIZE
docker.io/library/archlinux2   latest   011937530344   15 minutes ago   10.8 GB
localhost/archlinux            latest   41e04dead9e9   7 hours ago      10.8 GB
localhost/archlinux/oblitum    latest   36d9c387c422   21 hours ago     9.4 GB
localhost/archlinux/base       latest   3ae3713c1bd0   23 hours ago     478 MB

[I] ➜ podman tag 011937530344 archlinux2

[I] ➜ podman rmi docker.io/library/archlinux2
Untagged: docker.io/library/archlinux2:latest

[I] ➜ podman images
REPOSITORY                    TAG      IMAGE ID       CREATED          SIZE
localhost/archlinux2          latest   011937530344   17 minutes ago   10.8 GB
localhost/archlinux           latest   41e04dead9e9   7 hours ago      10.8 GB
localhost/archlinux/oblitum   latest   36d9c387c422   21 hours ago     9.4 GB
localhost/archlinux/base      latest   3ae3713c1bd0   23 hours ago     478 MB

[I] ➜ podman run --rm -it archlinux2
Error: No command specified on command line or as CMD or ENTRYPOINT in this image

[I] ➜ podman run --rm -it archlinux2 /bin/sh
Error: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": OCI runtime error

[I] ➜ podman run --rm -it -u=francisco archlinux2 bash
Error: unable to find user francisco: no matching entries in passwd file
```

**Describe the results you expected:**

First, when importing while tagging it as archlinux2, I didn't expect the full tag to become `docker.io/library/archlinux2`, it doesn't make sense. Second, I ignore how to run the imported image as rootless.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[I] ➜ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
[I] ➜ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.0, commit: e217fdff82e0b1a6184a28c43043a4065083407f'
  Distribution:
    distribution: arch
    version: unknown
  MemFree: 13708578816
  MemTotal: 16747802624
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: leibniz
  kernel: 5.2.9-arch1-1-ARCH
  os: linux
  rootless: true
  uptime: 75h 12m 14.54s (Approximately 3.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/francisco/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/francisco/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000
  VolumePath: /home/francisco/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[I] ➜ pacman -Qi podman
Name            : podman
Version         : 1.5.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  device-mapper  iptables  libseccomp  ostree  runc  skopeo  btrfs-progs  slirp4netns  libsystemd
Optional Deps   : podman-docker: for Docker-compatible CLI
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 102.71 MiB
Packager        : Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Sat 17 Aug 2019 05:16:49 PM -03
Install Date    : Sun 18 Aug 2019 04:17:14 AM -03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by oblitum** [comment]
My main interest in doing this is to carry the tarball to other machines, but the second is that I wish to delete the original image and leave the imported one because I want to check if by doing that I can erase the internal history and overlayfs diffs from filesystem and have squashed image. I wish there was a squash command for doing this.

**Comment by oblitum** [comment]
Oh sorry... it seems like I used the wrong command for images, it's `podman load`. And after loading, it just creates a new tag, so not useful for squashing.

**Comment by mheon** [comment]
@rhatdan @TomSweeneyRedHat Can `buildah` easily squash? I think I recall that it can?

**Comment by rhatdan** [comment]
It might not be a bad idea to add a `buildah squash` command.  @nalind @TomSweeneyRedHat WDYT? I think there is a PR open on squashing a number of layers.

**Comment by oblitum** [comment]
@rhatdan I think it's great having it, because diffs may include files that don't exist anymore in the result image, because they have been removed. A squash command would be nice to clear up any of such historical artifacts.

**Comment by rhatdan** [comment]
Could you open an issue with buildah to add support.

**Comment by TomSweeneyRedHat** [comment]
We've `--squash` already for `commit` and `bud`.  We also have a `--max-layers` PR in flight waiting for a review from @nalind (hint, hint) https://github.com/containers/buildah/pull/1790.  Just recovered my laptop after it crashed (yet again), I'll go play.

**Comment by oblitum** [comment]
@rhatdan sure: https://github.com/containers/buildah/issues/1810

**Comment by oblitum** [comment]
@TomSweeneyRedHat I tried `--squash` when building initial image with `bud` but I've hit this issue, I couldn't use the flag at all: https://github.com/containers/buildah/issues/1806.

**Comment by TomSweeneyRedHat** [comment]
Assuming `buildah commit --squash` is working, it's not solving this issue from what I can see quickly.
I was hoping the below would work.  @nalind any thoughts?
```
# podman pull alpine
# podman save alpine -o alpine.tar
# podman import alpine.tar alpine2

# podman images
REPOSITORY                  TAG      IMAGE ID       CREATED          SIZE
docker.io/library/alpine2   latest   7e367ff8040b   52 seconds ago   5.85 MB
docker.io/library/alpine    latest   961769676411   25 hours ago     5.85 MB

# podman tag 7e367ff8040b alpine2

# podman rmi docker.io/library/alpine2
Untagged: docker.io/library/alpine2:latest

# podman images
REPOSITORY                 TAG      IMAGE ID       CREATED              SIZE
localhost/alpine2          latest   7e367ff8040b   About a minute ago   5.85 MB
docker.io/library/alpine   latest   961769676411   25 hours ago         5.85 MB

# buildah from alpine2
alpine2-working-container

# buildah commit --squash alpine2-working-container alpine3

# podman images
REPOSITORY                 TAG      IMAGE ID       CREATED         SIZE
localhost/alpine3          latest   b0e5f1aca6b0   5 seconds ago   5.85 MB
localhost/alpine2          latest   7e367ff8040b   6 minutes ago   5.85 MB
docker.io/library/alpine   latest   961769676411   25 hours ago    5.85 MB

# podman run --rm -it alpine3 /bin/sh
Error: time="2019-08-21T17:18:49-04:00" level=error msg="container_linux.go:346: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\"\n"
container_linux.go:346: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
: OCI runtime error
```





```

**Comment by oblitum** [comment]
@TomSweeneyRedHat [as I commented before](https://github.com/containers/libpod/issues/3871#issuecomment-523597449), I get the same error when I use `import` from an image I've used `save`, the image works when I `load` the .tar, not `import`. If it's the same machine you used `save` and you didn't delete the original image, then it simply creates a new tag, otherwise it'll recreate the image.

I'm new to podman and buildah so I don't know exactly what you're attempting but I got the same error without buildah in the process.

**Comment by oblitum** [comment]
@TomSweeneyRedHat I'm trying buildah like you did about, except for the `import` part, but currently I'm failing for completely different reasons, `buildah commit --squash` fails because there's no space left on disk, this seems to be happening because it's using `/tmp` as temporary storage, and my image is big. Any way for to change the temporary storage of the operation?

**Comment by rhatdan** [comment]
@oblitum open an issue on this.  Probably should be using /var/tmp the default.
Might be buildah --runroot /var/tmp/containers ...
Not sure if buldah is using this directory for temporary storage.

**Comment by oblitum** [comment]
@rhatdan done https://github.com/containers/buildah/issues/1815.

**Comment by oblitum** [comment]
Folks, I've resized my `/tmp` to try this, gladly I had enough RAM for this attempt, and `buildah commit --squash` worked! After applying it and removing the original image, all overlayfs diff history was pruned from disk, and I earned a few megabytes in the process due to that.

So @TomSweeneyRedHat, as I [commented](https://github.com/containers/libpod/issues/3871#issuecomment-523952933), I guess the error message you got is indeed for using `import` instead of `load`.

**Comment by TomSweeneyRedHat** [comment]
@oblitum glad it worked out for you!  I'll poke further at that error message when I get a chance.

**Comment by oblitum** [comment]
May I ask something here, thought I think it's off-topic but I ignore where to chat about podman. I've read that podman and docker containers/images are compatible, but I'm concerned whether an image created rootless will run fine in Docker for Windows, will it? My doubt comes due to the uid/gid mapping and what will happen on Windows.

**Comment by TomSweeneyRedHat** [comment]
@oblitum best asked on the Podman mailing list:  https://podman.io/mailinglist/

I've not tried what you're suggesting, but I think it would neat experiment, I'm going to guess you're spot on about the uid/gid mapping being "fun" in Windows, but it would be fun to try.  Others on the list might  have experience with that though.

**Comment by oblitum** [comment]
@TomSweeneyRedHat OK, thanks.

**Comment by oblitum** [comment]
OK, I've loaded the tarball on docker for windows and the image simply works :)
