### ISSUE TITLE
RFE: podman-remote: support becoming root from other user (i.e. sudo)

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#3875]
/kind feature

**Description**

I couldn't find this anywhere so forgive me if it is already implemented. I'd like to be able to access the root owned containers on a machine by leveraging an existing user that has sudo privileges. The usefulness of this is that a good number of machines don't allow the root user to log in, but an admin can access root containers via a user with sudo access. 

Is there a way to use `podman-remote` to become the root user via another user with appropriate permissions?

**Comment by rhatdan** [comment]
Good point, we should think about allowing it to go through sudo.
@baude WDYT?

**Comment by baude** [comment]
it might be possible but not trivial. ill take the assignment

**Comment by afbjorklund** [comment]
The workaround in boot2podman (as compared with boot2docker) was to allow the sudo user (i.e. the default user for ssh that has sudo rights) to login as root as well (using the same authorized_keys).

**Comment by afbjorklund** [comment]
For minikube we will probably just _skip_ using varlink, there are only like two commands that are needed anyway (`podman load` and `podman build`) and those can use the regular `ssh sudo podman` instead.

Everything else can use `kubectl` or `crictl` from Kubernetes, there is no immediate need to clone the `minikube docker-env` command IMHO. The only downside is that "build context" needs to be handled.

Would like to keep **that** environment CRI-agnostic, rather just replace "docker" with "podman" ?

The commands above are just to cover some gaping functionality holes in the CRI specification.

**Comment by rhatdan** [comment]
I think this is still an interesting problem.

**Comment by baude** [comment]
agree

**Comment by afbjorklund** [comment]
Now `sudo` has been implemented for both `podman-machine` and `minikube podman-env`...

This means that the VM no longer has to allow SSH access for the root user, in order to work.

**Comment by rhatdan** [comment]
@dustymabe Can we close this?

**Comment by dustymabe** [comment]
It's been a while since I've played around with this. Any particular docs I should follow now to test?

**Comment by rhatdan** [comment]
@baude @jwhonce Is this possible now?  With API V2?

**Comment by vrothberg** [comment]
@baude @jwhonce , ping. I think we can support that as long as the ordinary user has permissions on the remote machine.

**Comment by baude** [comment]
yup!
