### ISSUE TITLE
login doesn't display server-side error message

### ISSUE THREAD

**Issue by saschpe** [containers/libpod#3884]
/kind bug

**Description**

*podman login* doesn't display server-side error message when it fails.

**Steps to reproduce the issue:**

1. `podman login registry.gitlab.com`
2. enter random credentials

**Describe the results you received:**
The following response seems hardcoded:
> error logging into "registry.gitlab.com": invalid username/password

**Describe the results you expected:**
While it should have returned the error message as provided by the authentication endpoint (*Docker* daemon ouput):

> Error response from daemon: Get https://registry.gitlab.com/v2/: unauthorized: HTTP Basic: Access denied
> You must use a personal access token with 'api' scope for Git over HTTP.
> You can generate one at https://gitlab.com/profile/personal_access_tokens

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 4078399488
  MemTotal: 33664155648
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: festor
  kernel: 5.2.9-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 73h 41m 21.39s (Approximately 3.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/saschpe/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/saschpe/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 8
  RunRoot: /run/user/1000
  VolumePath: /home/saschpe/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Comment by vrothberg** [comment]
Hi @saschpe, thanks for opening the issue! @QiWang19, would you have a look at it? I guess we might need some changes in c/image as well.

**Comment by vrothberg** [comment]
I have a weak preference to put this error into the debugging logs  to avoid cluttering the output but maybe others feel differently about it.

**Comment by saschpe** [comment]
Depends on how output for other registries looks like but this is important information for end users. It took me quite a while to figure out the issue. In fact I had to install *docker* again to double-check the matter ;-)

**Comment by QiWang19** [comment]
server-side error message is in the http response

https://github.com/containers/image/blob/634605d06e738aec8332bcfd69162e7509ac7aaf/docker/docker_client.go#L529

we return hard code error invalid username/password if `http.StatusUnauthorized`...should we return the message from http response...?

**Comment by mheon** [comment]
Providing it in `--log-level=debug` at a minimum would be a good idea
