### ISSUE TITLE
pkg cgroups fails to detect cgroupv2

### ISSUE THREAD

**Issue by marcov** [containers/libpod#3912]
/kind bug

**Description**

I think `pkg/cgroups` `IsCgroup2UnifiedMode()` may not correctly detect if the cgroup v2 is used.

It is  checking the superblock magic number of `/sys/fs/cgroup`, that's a tmpfs mount. Instead, it should check `/sys/fs/cgroup/unified`.

**Steps to reproduce the issue:**

1. (set `cgroup_manager= "cgroupfs"` in libpod.conf)

2. Run a container

This is printed in the logs:
```
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: write /sys/fs/cgroup/unified/libpod_parent/conmon/tasks: open /sys/fs/cgroup/unified/libpod_parent/conmon/tasks: permission denied
```

This is failing because `tasks` file was removed in cgroup v2.

I am on openSUSE Tumbleweed:
```
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
```

/cc @saschagrunert

**Comment by saschagrunert** [comment]
We encounter the same issue in CRI-O on the latest master and v1.15.0:

```
> sudo crictl runp test/testdata/sandbox_config.json
```
```
WARN[2019-08-30 12:46:18.787383018+02:00] Failed to add conmon to cgroupfs sandbox cgroup: write /sys/fs/cgroup/unified/Burstable/pod_123-456/crio-conmon-441aef63f8ae5071cad593e093cd2b903bbbefb60993f00c8182636ae4761559/tasks: open /sys/fs/cgroup/unified/Burstable/pod_123-456/crio-conmon-441aef63f8ae5071cad593e093cd2b903bbbefb60993f00c8182636ae4761559/tasks: permission denied  file="oci/oci_linux.go:57"
```

**Comment by vrothberg** [comment]
Hi @marcov, thanks for opening the issue!

@giuseppe PTAL

**Comment by giuseppe** [comment]
There should not be any /sys/fs/cgroup/unified when cgroup-v2 only is used.  The mounts table shows you are running in hybrid mode, and that is not supported. A controller can either be assigned to cgroup v1 or to cgroup v2, making things really confusing.

More info here: https://systemd.io/CGROUP_DELEGATION.html#three-different-tree-setups-

**Comment by saschagrunert** [comment]
> There should not be any /sys/fs/cgroup/unified when cgroup-v2 only is used. The mounts table shows you are running in hybrid mode, and that is not supported. A controller can either be assigned to cgroup v1 or to cgroup v2, making things really confusing.
> 
> More info here: https://systemd.io/CGROUP_DELEGATION.html#three-different-tree-setups-

Thanks for the hint @giuseppe, but how do we put systemd in cgroup-v2 only mode? Would it work to set something like `systemd.unified_cgroup_hierarchy=1`?

**Comment by giuseppe** [comment]
Yes, you will need to modify the kernel cmdline and include `systemd.unified_cgroup_hierarchy=1`

**Comment by marcov** [comment]
I tried to boot using that cmdline and I get this:
```
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: write /sys/fs/cgroup/cgroup.subtree_control: invalid argument
```

Also, running integration tests in cri-o now gives:
```
Error: container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"mountpoint for cgroup not found\"": OCI runtime error
make: *** [Makefile:197: integration] Error 127
```

**Comment by vrothberg** [comment]
@marcov, are you using crun or runc? runc doesn't support v2 yet, so we need to use crun for the time being. Not sure if that causes the issue though.

**Comment by marcov** [comment]
It's runc, yes, thanks for pointing that out. But, the `WARN` is coming from libpod, not runc.

**Comment by giuseppe** [comment]
@marcov can this be closed?

**Comment by marcov** [comment]
yes @giuseppe, closed
