### ISSUE TITLE
Rootless `podman run --privileged` fails if there is an inaccessible `/dev` subdirectory

### ISSUE THREAD

**Issue by QazerLab** [containers/libpod#3919]
/kind bug

**Description**

Current implementation of privileged containers [uses](https://github.com/containers/libpod/blob/8ba21acd459069cd53b492d46736b85c3436296b/pkg/spec/config_linux.go#L117-L120) `libcontainer`'s `HostDevices()` function to obtain the list of host devices. This function [returns any error arising](https://github.com/opencontainers/runc/blob/51f2a861da7fb1d4f6f8370a60258c6f315956ef/libcontainer/devices/devices.go#L72-L75) when accessing the subdirectories in `/dev`. This means, that having some inaccessible (by current user) subdirectory in `/dev` makes rootless `podman run --privileged` crash, e.g.:

```
$ podman run --privileged alpine
Error: open /dev/vboxusb: permission denied
```

Dir permissions are:

```
$ stat /dev/vboxusb/
...
Access: (0750/drwxr-x---)  Uid: (    0/    root)   Gid: (  108/vboxusers)
```

**Steps to reproduce the issue:**

1. Create a subdirectory in `/dev` which is not accessible to ordinary users: `sudo mkdir -m 0700 /dev/kaboom`
2. Run privileged rootless container: `podman run --privileged alpine`

**Describe the results you received:**

`podman` crashes with the `permission denied` error.

**Describe the results you expected:**

Inaccessible directory is ignored.

**Comment by mheon** [comment]
@giuseppe Probably related to the code added to add devices to privileged rootless containers?

**Comment by giuseppe** [comment]
since I already have a PR that changes the code to handle devices when rootless, I've added a patch to take care of this issue as well: https://github.com/containers/libpod/pull/3909

**Comment by carbolymer** [comment]
I think I'm experiencing this exact issue on 4.1.0:
```
% podman run --rm --privileged bash
Error: crun: error stat'ing file `/dev/vboxusb/001/002`: Permission denied: OCI permission denied
% podman --version                 
podman version 4.1.0
% /usr/bin/ls -al /dev/vboxusb/001
total 0
drwxr-x--- 2 root vboxusers     80 May 18 08:14 .
drwxr-x--- 4 root vboxusers     80 May 18 08:14 ..
crw-rw---- 1 root vboxusers 189, 1 May 18 08:14 002
crw-rw---- 1 root vboxusers 189, 2 May 18 08:14 003
```

**Comment by rhatdan** [comment]
This looks likely to be a different issue, please open a new one. This could be something that crun is causing.  Are you running in rootless mode?

**Comment by carbolymer** [comment]
Rootless. Opened #14284.
