### ISSUE TITLE
`podman build` does not reuse cache when current directory changed

### ISSUE THREAD

**Issue by shaicoleman** [containers/libpod#3921]
/kind bug

**Description**

When changing the directory context, the cache isn't used, even if it points to the same directory.

**Steps to reproduce the issue:**
```
sudo podman build --rm --file rails/Dockerfile -t myimage ..
cd ..
sudo podman build --rm --file docker/rails/Dockerfile -t myimage .
```

**Output of `podman version`:**
```
Version:            1.5.0
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.5.0
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: unknown'
  Distribution:
    distribution: linuxmint
    version: "19.2"
  MemFree: 5022597120
  MemTotal: 16622612480
  OCIRuntime:
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 16986927104
  SwapTotal: 16986927104
  arch: amd64
  cpus: 12
  eventlogger: journald
  hostname: shai-5591
  kernel: 5.0.0-25-generic
  os: linux
  rootless: false
  uptime: 21m 22.48s
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 35
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info:**
```
`podman/bionic,now 1.5.0-2~ubuntu18.04~ppa5 amd64 [installed]`
```

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
@shaicoleman Best to open issues against https://github.com/containers/buildah for build issues, since podman is just using buildah code to do `podman build`

**Comment by TomSweeneyRedHat** [comment]
I've not been able to duplicate this using Buildah v1.11.0 which should be in the next release of Podman. I'm not sure if that will be Podman 1.5.1 or Podman 1.6.0, but it will be contained that next version. I'm going to close this now as containers/buildah#1792 appears to have fixed the issue. If you find otherwise, please feel free to reopen this or create a new issue as appropriate.
