### ISSUE TITLE
Ubuntu PPA out of date

### ISSUE THREAD

**Issue by shaicoleman** [containers/libpod#3923]
/kind bug

**Description**

The Ubuntu PPA is out of date. The latest version is 1.5.1, while the latest version on the PPA is 1.5.0

Would be great if the PPA would automatically be update whenever there's a new release.

It would save everybody time not having to deal with bugs that have already been fixed in newer versions.

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@mheon @shaicoleman yup, I had disabled autorebuild on podman cause of #3838 (sorry I felt it was troublesome). Let me re-enable it given the issue is fixed.

**Comment by lsm5** [comment]
packages built at https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages ... taking a while to publish though, no idea why, should be done in sometime I hope. @shaicoleman please close this once you see the new builds on your env, thanks.

**Comment by shaicoleman** [comment]
They are updated now, thanks!

**Comment by shaicoleman** [comment]
@lsm5 , can you into why the v1.6.0-rc1 package wasn't generated?

**Comment by lsm5** [comment]
> @lsm5 , can you into why the v1.6.0-rc1 package wasn't generated?

it wasn't cause I disabled the autobuilder job for a bit. @mheon are we good to have rc tags built and pushed to ppa?

**Comment by mheon** [comment]
Uhm. I'm a little iffy on this - I kind of feel they should be opt-in.

I wish there was a way to mark them as pre-release, similar to Fedora's updates-testing channel.

**Comment by lsm5** [comment]
> Uhm. I'm a little iffy on this - I kind of feel they should be opt-in.
> 
> I wish there was a way to mark them as pre-release, similar to Fedora's updates-testing channel.

afaik, ppa doesn't/can't provide separate channels. If you suspect things would break, maybe it's best to not build RCs at all.

**Comment by lsm5** [comment]
What I could do is maybe create a separate ppa itself and build latest commit hourly. Similar to what's done for rawhide. People can use it at their own risk then?

**Comment by shaicoleman** [comment]
@lsm5 , Yes, you could have several PPAs (e.g. beta/dev/stable), 
See for example: https://launchpad.net/~chromium-team

**Comment by lsm5** [comment]
> @lsm5 , Yes, you could have several PPAs (e.g. beta/dev/stable),
> See for example: https://launchpad.net/~chromium-team

So, if I'm reading that right, that's just separate PPAs and no in-built separation like updates-testing and updates on Fedora, yes?

**Comment by shaicoleman** [comment]
@lsm5 , yes, exactly.
Just make sure that when you release a stable version, to release it to the beta channel as well, so it isn't behind stable.

**Comment by baude** [comment]
imho, i would keep things as is ... rc's are not needed in the ppa.  ideally we want podman in ubuntu proper ... and if that were to happen, then rcs in the ppas would make perfect sense.  i really dont want bug reports on two different repos.

thoughts?

**Comment by lsm5** [comment]
> imho, i would keep things as is ... rc's are not needed in the ppa. ideally we want podman in ubuntu proper ... and if that were to happen, then rcs in the ppas would make perfect sense. i really dont want bug reports on two different repos.
> 
> thoughts?

I'd love that :D .. that'd mean less work for me :) . But, shouldn't be too expensive to have a rawhide-esque ppa (I'm thinking upstream master branch) if it helps the adventurous users.

**Comment by lsm5** [comment]
@baude so, remind me, are the RCs gonna be a regular thing now?

**Comment by shaicoleman** [comment]
@lsm5, ideally there should 3 PPAs:
* Nightly (hourly/nightly)
* Beta (which would include any tagged release, e.g. beta and RC)
* Stable

**Comment by baude** [comment]
rcs will be regular.  and imho, stable should be part of ubuntu ideally fwiw.  anyways, dealers choice here.

**Comment by rhatdan** [comment]
I would say have three.  RCs should only be available for a week or so.  We just want to make sure we don't have a regression before we release.

**Comment by shaicoleman** [comment]
I've opened a new issue #4099 , as this issue is closed

**Comment by shaicoleman** [comment]
1.6.2 is out, while 1.6.1 is the latest in PPA. Reopening

**Comment by shaicoleman** [comment]
PPA updated, closing
