### ISSUE TITLE
podman (also buildah) push to docker often gets stuck or errors out

### ISSUE THREAD

**Issue by sdeoras** [containers/libpod#3935]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
In a workflow that starts with building container images using `buildah` followed by pushing to `docker.io/<account>/<public-repo>:tag`, I am observing that:

- Building images always succeeds
- Pushing to docker hub often gets stuck and sometimes fails with http timeouts
- In a few instances the push succeeded, but docker hub did not display the updated tag on UI. In that same instance, I also saw error that the json manifest was incorrect (although I have not been able to repro that error since)

In some cases when I aborted the push using Ctrl-C, I was not able to push again. More info below.

**Steps to reproduce the issue:**

1. Use buildah to build a new container image (say from fedora 30 base image).

2. Create a public repo on docker hub

3. Use either `podman` or `buildah` to push

I am not sure if this has anything to do with final image size, but I am pushing total image size of about 1.2G with first layer being the upstream fedora 30 base image and second layer consisting of my updates. I also not very clear on how to split my final image into multiple smaller layers, which I am guessing may potentially solve my issue.

**Describe the results you received:**
```
podman push <imageName>:tag
Getting image source signatures
Copying blob c2fd56fec0a7 done
Copying blob 606d67d8e1b8 skipped: already exists
Error: Error copying image to the remote destination: Error writing blob: Patch https://registry-1.docker.io/v2/<accountName>/<repoName>/blobs/uploads/94278296-3332-4ddf-b7e9-5ddd0ac7a981?_state=14V6SECMk2wsBQr22R1QsmuW0UchLWSeeQm8291W8Zt7Ik5hbWUiOiJkaWFtYW50aS9tYWluLXByb2QiLCJVVUlEIjoiOTQyNzgyOTYtMzMzMi00ZGRmLWI3ZTktNWRkZDBhYzdhOTgxIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE5LTA5LTA0VDE1OjA3OjI3LjYxNzUwMjc0OVoifQ%3D%3D: net/http: HTTP/1.x transport connection broken: write tcp 172.16.36.102:58404->34.228.211.243:443: write: connection reset by peer
```

**Describe the results you expected:**
I expected push to go through without errors since I could push the same image using `docker`. I tar it up, load in `docker` and then push. Expecting to be able to do full docker-less workflow.

**Additional information you deem important (e.g. issue happens only occasionally):**
Trying to push the same image again also results in following error often:

```
buildah push <imageName>:tag
Getting image source signatures
Copying blob c2fd56fec0a7 done
Copying blob 606d67d8e1b8 skipped: already exists
Patch https://registry-1.docker.io/v2/<accountName>/<repoName>/blobs/uploads/f585c202-eeca-4ac3-819f-79b3e206a031?_state=gbm89rW7YDke56EPBXGlGiOmJbws4ua8vPrEYzJTzfh7Ik5hbWUiOiJkaWFtYW50aS9tYWluLXByb2QiLCJVVUlEIjoiZjU4NWMyMDItZWVjYS00YWMzLTgxOWYtNzliM2UyMDZhMDMxIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE5LTA5LTA0VDE1OjE5OjMxLjk2NDU1NTU5NloifQ%3D%3D: open /home/sdeoras/.local/share/containers/storage/overlay/2907538fd383e9ff8f77339bd572dc09b6a869fb2a66c0e8f3f10b96566ec6c8/merged/etc/bash_completion.d/git: no such file or directory
ERRO[0002] exit status 1
```

**Output of `podman version`:**
```
(paste your output here)
podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```
```
buildah version
Version:         1.10.1
Go Version:      go1.12.7
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2140905472
  MemTotal: 16532365312
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: dusy
  kernel: 5.2.9-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 68h 42m 52.39s (Approximately 2.83 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - quay.io
  - docker.io
store:
  ConfigFile: /home/sdeoras/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/sdeoras/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 12
  RunRoot: /tmp/1000
  VolumePath: /home/sdeoras/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 30 installation on laptop

**Comment by rhatdan** [comment]
Docker hub is having issues with OCI Images.  Could you see if the problem goes a way if you specify --format docker,

You can make this the default if you set:
```
export BUILDAH_FORMAT=docker
```

**Comment by sdeoras** [comment]
@rhatdan, I'll make that default, however, for the previous push that failed I seem to be stuck in some kind of a state that causes `buildah` to throw following error. Is there a better way to clean up (I have tried deleting `${HOME}/.local/share/containers/storage` in the past and I think that had helped)

```
BUILDAH_FORMAT=docker buildah push <image>:tag
Getting image source signatures
Copying blob c2fd56fec0a7 done
Copying blob 606d67d8e1b8 skipped: already exists
Patch https://registry-1.docker.io/v2/<acountName>/<repoName>/blobs/uploads/59530b5e-11ab-4951-a616-945fc5b0eb43?_state=70-Q9rka8Q1x-pOWosZ9qdjfsh2kNZm3nqlo4wQANhl7Ik5hbWUiOiJkaWFtYW50aS9tYWluLXByb2QiLCJVVUlEIjoiNTk1MzBiNWUtMTFhYi00OTUxLWE2MTYtOTQ1ZmM1YjBlYjQzIiwiT2Zmc2V0IjowLCJTdGFydGVkQXQiOiIyMDE5LTA5LTA0VDE1OjQ0OjMxLjQyMjU3OTAzN1oifQ%3D%3D: open /home/sdeoras/.local/share/containers/storage/overlay/2907538fd383e9ff8f77339bd572dc09b6a869fb2a66c0e8f3f10b96566ec6c8/merged/etc/bash_completion.d/git: no such file or directory
ERRO[0002] exit status 1 
```

**Comment by rhatdan** [comment]
Can you just `buildah rmi <image>:tag`

**Comment by baude** [comment]
what needs to be done here? it isnt clear to me there is a problem?

**Comment by sdeoras** [comment]
as @rhatdan commented earlier, if this is because dockerhub has problems with OCI images, we can close this issue.

**Comment by TomSweeneyRedHat** [comment]
@sdeoras thanks for the follow up, closing.
