### ISSUE TITLE
rawhide: rootless(?): unable to create pod cgroup

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3939]
On current rawhide:
```
$ podman pod create --infra=false
Error: unable to create pod: unable to create pod cgroup for pod f6e5b1f4226f5145fbe5da90a5fa43da4b2ab9255180da764a1f3c555df6c70e: error creating cgroup user.slice/user-libpod_pod_f6e5b1f4226f5145fbe5da90a5fa43da4b2ab9255180da764a1f3c555df6c70e.slice: dial unix /run/user/0/bus: connect: permission denied
     >>>> ----- be sure to note the /run/user/0 above   ---^^^^^
$ echo $?
125
$ id
uid=1000(fedora) gid=1000(fedora) groups=1000(fedora) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
With --log-level=debug:
```
...
DEBU[0000] using runtime "/usr/bin/crun"
DEBU[0000] Created cgroup path user.slice/user-libpod_pod_0b61d20bd8cfa2af93e649ed85ddd24a5417ae764080073d95ab3722da19a1ad.slice for parent user.slice and name libpod_pod_0b61d20bd8cfa2af93e649ed85ddd24a5417ae764080073d95ab3722da19a1ad
```
podman-1.5.2-0.46.dev.git1d8a940.fc32.x86_64
crun-0.7-2.fc31.x86_64
package runc is not installed
kernel  5.3.0-0.rc5.git2.1.fc32.x86_64

**Comment by giuseppe** [comment]
looks like `XDG_RUNTIME_DIR` is not configured correctly.

Have you created the user session through `sudo`?

Could you print your environment variables?

**Comment by edsantiago** [comment]
Session opened via `su -` from root. There is no `XDG_*` in env; only relevant variables are `HOME=/home/fedora`, `LOGNAME=fedora`, `USER=fedora`.

I realize that there's this new fancy systemd dbus XDG universe but some of us are very old UNIX users and don't use that stuff; and we can't just say "use dbus for everything" to people who have functional workflows.

**Comment by mheon** [comment]
@edsantiago Is this fixed? I think we got this one with the XDG_RUNTIME_DIR fixes

**Comment by edsantiago** [comment]
Seems to be fixed - closing
