### ISSUE TITLE
Expose port on running container

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#3949]
/kind feature

Is it possible to expose a port from a running container with `podman`? I am not sure `docker` allows this.

The story - I started `db` in interactive mode, loaded dumps, configured it and forgot to expose port. Now I need to access it from outside, and I see no way to do this.

```
podman version 1.5.1
```

**Comment by abitrolly** [comment]
Used `podman exec` with https://serveo.net for now.

**Comment by baude** [comment]
one thing you could do is commit the container to an image and then rerun that image?

**Comment by abitrolly** [comment]
@baude even if I commit the state, only saved data will be preserved - all the processes inside will be restarted and memory contents will be lost, right?

**Comment by rhatdan** [comment]
@abitrolly The answer to your question was yes.
