### ISSUE TITLE
cleanup mount test bug

### ISSUE THREAD

**Issue by gabibeyer** [containers/libpod#3953]
Not entirely sure whether this is an issue with the test not working as originally intended, or if the code base may need some modifications and the test is correct.

The "podman run -d mount cleanup test" in the `run_cleanup_test.go` [file](https://github.com/containers/libpod/blob/cef5bec06b200ffa5caed46db296e55fb7d72376/test/e2e/run_cleanup_test.go#L38) was incorrectly using the `Expect` function (not providing a [matcher](https://github.com/containers/libpod/blob/cef5bec06b200ffa5caed46db296e55fb7d72376/vendor/github.com/onsi/gomega/gomega_dsl.go#L133)), so it was passing regardless of the input. However, once `Expect` was used correctly, some tests are failing.

It looks like the mount is not actually getting cleaned up, or maybe not giving enough time for conmon to do the cleanup before checking results. Anyways, this can be seen in 
 this PR: #3941 . I'm not entirely sure how to move forward on this, and could use some help. I believe it is blocking #3756 (although maybe not entirely related to the PR).

Thank you, 
Gabi

**Comment by rhatdan** [comment]
See if adding
```
		wait := podmanTest.Podman([]string{"wait", cid})
		wait.WaitWithDefaultTimeout()
		Expect(stop.ExitCode()).To(Equal(0))
```
After the stop fixes the issue.

**Comment by rhatdan** [comment]
I think this is definitely a race.

**Comment by mheon** [comment]
#3941 is merged, so this is fixed, closing
