### ISSUE TITLE
Some systemd features might not work properly in rootless containers

### ISSUE THREAD

**Issue by msekletar** [containers/libpod#3957]
In rootless.md we already have a quite a list of known issues. I think it would be a good idea to a have a bullet-point there which mentions that some systemd APIs and options don't work in rootless containers.

For example, all cgroup resource control options won't be applied (with cgroupv1), however, service will start. Then there are unit file options which will cause service failure if used for a service in the rootless container (e.g. `PrivateNetwork=`).

**Comment by rhatdan** [comment]
Any chance you could open a PR?
