### ISSUE TITLE
Cannot commit user container with `--pause`

### ISSUE THREAD

**Issue by marusak** [containers/libpod#3970]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I cannot commit container that is owned by user (not root) and is running and I use option `--pause`.

**Steps to reproduce the issue:**
1. `podman run -di --name first fedora sh`
2. `podman commit --pause first commited`

**Describe the results you received:**
Output from the second step:
```
no such directory for freezer.state
Error: error pausing container "99b27d6f7404ae1d3ae18ad9474c8f331cf1b291c8bf1f553d8e7618cef2034a": `/usr/sbin/runc pause 99b27d6f7404ae1d3ae18ad9474c8f331cf1b291c8bf1f553d8e7618cef2034a` failed: exit status 1
```

**Describe the results you expected:**
Successfully commits. This works when I run everything as root:
1. `sudo podman run -di --name first fedora sh`
2. `sudo podman commit --pause first commited`

or when I firstly stop the container and then do commit without `--pause`.

**Additional information you deem important (e.g. issue happens only occasionally):**
I run this on Fedora 30 without CGroupsV2. Can this be related? (wild guess, but since this happens only for user containers...)

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 1382494208
  MemTotal: 16451891200
  OCIRuntime:
    package: containerd.io-1.2.1-2.0.rc.0.1.fc29.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      commit: 10d38b660a77168360df3522881e2dc2be5056bd
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: mm.localdomain
  kernel: 5.2.11-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 74h 22m 30.14s (Approximately 3.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/mmarusak/.config/containers/storage.conf
  ContainerStore:
    number: 9
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/mmarusak/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /run/user/1000
  VolumePath: /home/mmarusak/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Comment by mheon** [comment]
Outside of CGroups V2 + `crun`, we do not have the proper permissions to pause containers without root. So the error here is expected, but it should give an error message that the option isn't supported, not the one it's giving.

**Comment by marusak** [comment]
Makes sense, when someone adds some checks please use error message that was introduced in https://github.com/containers/libpod/pull/3753 , then it is easier for us (cockpit team), thanks :)
