### ISSUE TITLE
Question: Does podman respect UFW firewall rules on ubuntu?

### ISSUE THREAD

**Issue by menathor** [containers/libpod#3981]
Hi all,

Just wondering if any ubuntu users could tell me whether podman respects / works with UFW firewall rules? Docker bypasses them completely which is a major security issue that's been written about for years but still hasn't been addressed.

Cheers! :)

**Comment by mheon** [comment]
Podman uses CNI for networking, so this question would be better directed there - but I'm fairly certain the answer is no. CNI seems to mostly call directly into IPTables, though I think it may have support for interfacing with firewalld as well.

**Comment by AkihiroSuda** [comment]
Rootless podman obeys the system firewall configuration as well as rootless docker

**Comment by baude** [comment]
closing unless there is an action for us ... re-open if needed
