### ISSUE TITLE
podman-remote.conf port and identity file support

### ISSUE THREAD

**Issue by lukczarnota** [containers/libpod#3987]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. install podman and podman-machine on MacOS
2. create test machine 
```
podman-machine create test
```
3. get envs
```
podman-machine env test
```
4. export envs
```
eval $(podman-machine env test)
```
5. test podman
```
➜  ~ podman ps
Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```
6. try with podman-remote.conf
```
[connections]
    [connections.test]
    destination = "localhost"
    username = "root"
    port = "51584"
    identity_file = "/Users/XXXX/.local/machine/machines/test/id_rsa"
    default = true
```
7. test podman
```
➜  ~ podman ps
Password:
[its trying to connect on port 22 instead of 51584]
```

**Describe the results you received:**
 check 6 and 7 

**Describe the results you expected:**
podman should connect to localhost on port 51584 to root user using /Users/XXXX/.local/machine/machines/test/id_rsa key file

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            darwin/amd64
```

**Output of `podman info --debug`:**

```

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman: 1.5.1
https://github.com/containers/libpod/
/usr/local/Caskroom/podman/1.5.1 (70 files, 45.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/podman.rb
==> Name
podman
==> Artifacts
brew/podman (Binary)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, macOS High Sierra 10.13.2

**Comment by baude** [comment]
this is not a bug, it is a feature ... we do not currently support port and identity file

**Comment by baude** [comment]
can you use your ~/.ssh/config to do this?
