### ISSUE TITLE
(minor) podman push error: exit status inconsistent with docker

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#3991]
Super minor: the exit status of a failing `podman push` is 125; docker is 1:
```
# podman pull alpine
...
# podman tag alpine foo.bar/fu/bar
# podman push !$
Getting image source signatures
Error: Error copying image to the remote destination: Error trying to reuse blob sha256:03901b4a2ea88eeaad62dbe59b072b28b6efa00491962b8741081c5df50c65e0 at destination: pinging docker registry returned: Get https://foo.bar/v2/: dial tcp: lookup foo.bar on 10.11.142.1:53: no such host
# echo $?
125      <----- docker-1.13 exits 1
```
Similarly for access-denied type errors: `podman tag alpine docker.io/nosuchname/nosuchimage`

**Comment by mheon** [comment]
@rhatdan Was this deliberate on our part, to differentiate between different pull errors?

**Comment by rhatdan** [comment]
We have defaulted podman to exit with 125 on errors unless other tools override.  

man podman 

Documents this now.  I have no problem changing the default.   But other tools might be relying on this, now.

podman run and docker run both fail with 125 by default.
Just other parts of Docker fail with 1 on failures while podman does 125 for all commands.

**Comment by vrothberg** [comment]
I'll take a shot and close this issue since we're in between a rock and a hard place. It would be good to align with Docker while users might already depend on the current behavior. Feel free to reopen.

**Comment by rhatdan** [comment]
I think docker is the one being incosistant.
`docker run` and `docker exec` will exit with 125 on failures as I recall.  Since you want to record the container exit code as the exit code.
