### ISSUE TITLE
errors with varlink via systemd

### ISSUE THREAD

**Issue by cevich** [containers/libpod#4005]
/kind bug

**Description**

When executing in a tight loop, or multiple simultaneous podman-remote throws `EOF` errors.

**Steps to reproduce the issue:**

1. `make podman podman-remote`
1. `make install PREFIX=/usr`
2. `systemctl daemon-reload`
3. `systemctl enable io.podman.socket`
3. `systemctl enable io.podman.service`
3. `systemctl start io.podman.socket`
3. `while podman-remote run -it --rm alpine echo "hi"; do :; done`

**Describe the results you received:**

Either:

```
hi
...cut several repeats...
hi
Error: unexpected EOF
...
```

or

```
hi
...cut several repeats...
hi
Error: Virtual Read failed, 0: EOF
...
```

**Describe the results you expected:**

A continuous stream of `hi` and no errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

Found while discovering/debugging issue #3998

Also sometimes reproducible with:
`podman-remote run --rm alpine echo "hello" & podman-remote run --rm alpine echo "hello"`

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
# podman-remote version
Client:
Version:            1.5.2-dev
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64

Service:
Version:            1.5.2-dev
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

af8fedcc78674d71d43ca3000438c42b7b6b6994

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Reproduced on a VM with 2 vCPUs (no threads) and 4 GiB memory.

**Comment by vrothberg** [comment]
I can reproduce immediately. Interestingly, I cannot reproduce when avoiding the socket activation and running `sudo podman varlink -t 0 unix:/run/podman/io.podman` directly.

**Comment by vrothberg** [comment]
I get a 100 percent error rate when doing a `podman-remote run alpine echo "hi" > /dev/null`.

**Comment by vrothberg** [comment]
It looks like the logic to disable sdnotify was wrong. Opened #4089 to address the issue. It fixes the issues locally but lets wait what the CI has to say.

**Comment by cevich** [comment]
Oh this is fantastic! Thanks @vrothberg :smiley_cat:
