### ISSUE TITLE
podman info --debug fails under windows when running inside ubuntu:18.04 container

### ISSUE THREAD

**Issue by hholst80** [containers/libpod#4014]
````
holst@0c46f2b623a6:~/tugboat$ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
holst@0c46f2b623a6:~/tugboat$ podman info --debug
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
cannot clone: Operation not permitted
Error: could not get runtime: cannot re-exec process
WARN[0000] unable to find /home/holst/.config/containers/registries.conf. some podman (image shortnames) commands may be limited
````

````
PS C:\Users\henri> docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
PS C:\Users\henri>
````

**Comment by baude** [comment]
it appears you are not running the podman remote client binary.  this is the only supported binary on windows and like docker, connects to a linux vm to run.  when running the podman remote client binary on windows, it will report an API version which is absent in your output.  moreover, this explains the oci runtime problems.

im not sure which instructions you used for your setup, but in the case you are building this from master or a source tree, you can build the remote client binary with `make podman-remote-windows`

**Comment by mheon** [comment]
@baude I think he may be running Podman in a Docker container running Ubuntu on Windows. Without knowing more about the setup, though, I don't think we can reasonably comment on debugging.

**Comment by vrothberg** [comment]
@hholst80, could you reply to the following questions? The environment is not yet clear to resolve your issue.

> Under windows meaning? Are you attempting to run Podman inside a container being run by Docker?

> What is the OS of the container fedora 31?

**Comment by hholst80** [comment]
Explicit repro steps:

1. Obtain a machine with Windows 10.
2. Install Docker Desktop for Windows https://www.docker.com/products/docker-desktop
3. Start a container from the command prompt: `docker run -it --rm ubuntu:18.04`
4. Install podman inside the container. Follow this guide: https://computingforgeeks.com/how-to-install-podman-on-ubuntu/
5. Still inside the container, run: `podman info --debug`

**Comment by vrothberg** [comment]
@hholst80, thanks for sharing. This environment is quite exotic but I don't want to give up yet. Can you share the output when running `podman info --debug`?

**Comment by rhatdan** [comment]
Podman will not work in a locked down container yet.  We can get a lot further by turning off some security features.

RUn a --privileged container with Docker and  podman should be able to function,

**Comment by vrothberg** [comment]
@giuseppe, can you have a look at it? It looks like `crun` is cloning which would be surprising for the `info` use case where we only need the version and commit.

**Comment by hholst80** [comment]
> ```
> holst@0c46f2b623a6:~/tugboat$ podman info --debug
> WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
> cannot clone: Operation not permitted
> Error: could not get runtime: cannot re-exec process
> WARN[0000] unable to find /home/holst/.config/containers/registries.conf. some podman (image shortnames) commands may be limited
> ```

**Comment by vrothberg** [comment]
Just had a look at the code, it has nothing to do with `crun`. The cloning error comes from Podman trying to create a new user namespace for running rootless.

@hholst80 are you running the container as `--privileged`?

**Comment by giuseppe** [comment]
Clone failures usually are related to seccomp blocking them.  Can you try disabling it?

**Comment by hholst80** [comment]
> Just had a look at the code, it has nothing to do with `crun`. The cloning error comes from Podman trying to create a new user namespace for running rootless.
> 
> @hholst80 are you running the container as `--privileged`?

No, not running as privileged.

**Comment by vrothberg** [comment]
@hholst80 can you try running the container (in which you're running Podman) as privileged?

**Comment by vrothberg** [comment]
Closing. Please reopen in case it's not working in a privileged container.

The support for unprivileged containers will improve with https://github.com/containers/libpod/pull/4698.
