### ISSUE TITLE
podman generate systemd contains wrong PIDFile path on CentOS 7

### ISSUE THREAD

**Issue by ansemjo** [containers/libpod#4055]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On a CentOS 7 machine the `podman generate systemd <id>` command generates a service file with a wrong `PIDFile=` path.

**Steps to reproduce the issue:**

1. Run a `CentOS Linux release 7.7.1908 (Core)` (this was true for 7.6 too) release and use the packaged `podman` version from `extras`.

2. Create a container with podman.

3. Run `podman generate systemd <id> > /etc/systemd/system/speedtest.service` and reload the daemon to pick up the new service.

4. Attempt to start / enable the container through systemd with `systemctl start speedtest`.

**Describe the results you received:**

Somewhat confusing error `Job for speedtest.service failed because a configured resource limit was exceeded.`. The culprit appears to be the `PIDFile`, which can't be opened.

<details>
<summary>Full logs</summary>

```
# systemctl start speedtest.service 
Job for speedtest.service failed because a configured resource limit was exceeded. See "systemctl status speedtest.service" and "journalctl -xe" for details.
# systemctl status speedtest.service 
● speedtest.service - aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7 Podman Container
   Loaded: loaded (/etc/systemd/system/speedtest.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/speedtest.service.d
           └─override.conf
   Active: failed (Result: start-limit) since Tue 2019-09-17 21:39:03 CEST; 1s ago
  Process: 13242 ExecStart=/usr/bin/podman start aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7 (code=exited, status=0/SUCCESS)

Sep 17 21:39:03 hostname systemd[1]: Can't open PID file /var/lib/containers/storage/overlay-containers/aed038fe1d44110eb633c891e1e1105a...irectory
Sep 17 21:39:03 hostname systemd[1]: Failed to start aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7 Podman Container.
Sep 17 21:39:03 hostname systemd[1]: Unit speedtest.service entered failed state.
Sep 17 21:39:03 hostname systemd[1]: speedtest.service failed.
Sep 17 21:39:03 hostname systemd[1]: speedtest.service holdoff time over, scheduling restart.
Sep 17 21:39:03 hostname systemd[1]: Stopped aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7 Podman Container.
Sep 17 21:39:03 hostname systemd[1]: start request repeated too quickly for speedtest.service
Sep 17 21:39:03 hostname systemd[1]: Failed to start aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7 Podman Container.
Sep 17 21:39:03 hostname systemd[1]: Unit speedtest.service entered failed state.
Sep 17 21:39:03 hostname systemd[1]: speedtest.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

</details>

**Describe the results you expected:**

I expected the container to start normally, just as it does with `podman start speedtest`.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is running on a CentOS 7.7 machine with the packaged podman from the `extras` repository as stated above. **I am aware** that this is not the most recent version available of podman. But it's the most recent version available if you stick to the package repositories.

**Output of `podman version`:**

```
# podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

<details>
<summary><b>Output of <code>podman info --debug</code>:</b></summary>

```
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 6942957568
  MemTotal: 8199704576
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 3436179456
  SwapTotal: 3436179456
  arch: amd64
  cpus: 14
  hostname: <hostname>
  kernel: 3.10.0-1062.1.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 46m 14.08s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 6
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-1.4.4-4.el7.centos.x86_64
```

---

The fix is actually quite simple: just insert the correct `PIDFile` path which is under `/var/run/containers/storage/overlay-containers/<id>/userdata/pidfile` for me. I just thought you might want to fix this for the podman package in CentOS if you have control over that.

```diff
9c9
< PIDFile=/var/lib/containers/storage/overlay-containers/aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7/userdata/aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7.pid
---
> PIDFile=/var/run/containers/storage/overlay-containers/aed038fe1d44110eb633c891e1e1105ac323b83b838b2bc67567bb073139ddf7/userdata/pidfile
```

**Comment by mheon** [comment]
This is fixed in Podman 1.5.x and higher. I don't know exactly when we can expect those in CentOS though - probably 7.8?

**Comment by baude** [comment]
given this is fixed upstream and this is being reported upstream, im going to close this

**Comment by ansemjo** [comment]
Fair enough. Would there have been a more appropriate place to report this or should we just wait?

**Comment by mheon** [comment]
I think @lsm5 maintains faster-moving Podman packages for CentOS
