### ISSUE TITLE
events_logfile_path toml key in libpod.conf

### ISSUE THREAD

**Issue by llchan** [containers/libpod#4062]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

https://github.com/containers/libpod/blob/7ac6ed3b4b27621e7aa15da335e65ffa601fb83e/libpod/runtime.go#L250

Not sure if this is a typo or not, but the toml key has a leading dash.  If this is intentional, feel free to close, just thought I'd mention it since it looks unconventional in the config file.

**Comment by mheon** [comment]
Definitely a typo. Oops.
