### ISSUE TITLE
Rootless `podman Info` should show the current UID_MAP

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#4067]
Lots of times when people have problems with rootless podman, we find that they have not setup User Namespace correctly.

Having podman info display this data would allow us to eliminate one common request we give to users.

**Comment by giuseppe** [comment]
since `podman info` runs in the same user namespace, it could be the output of `/proc/self/?id_map`

**Comment by mheon** [comment]
I also think we need to better display what happened with `newuidmap`/`newgidmap` - it's very hard to get any debugging information about what they're doing. If I force the rootless userns to be recreated with `podman system migrate` I'd really like to get at least a debug log saying `newuidmap exited with 0` on the next run, or something similar
