### ISSUE TITLE
Launching the same container twice creates a new firefox tab, rather than a window

### ISSUE THREAD

**Issue by ITmaze** [containers/libpod#4078]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I run a simple container with firefox-esr a second time, instead of opening a new window, the new process opens a tab in the existing firefox-esr window.

I understood that the processes were completely isolated, this seems to indicate that they are not.

**Steps to reproduce the issue:**

1. `alias docker=podman`

2. `xhost +"local:docker@"`

3. `docker run -e DISPLAY=${DISPLAY} --net=host itmaze/firefox-esr &`

4. `docker run -e DISPLAY=${DISPLAY} --net=host itmaze/firefox-esr &`

**Describe the results you received:**

After launching, a window opens with Firefox and two tabs, the default URL (as specified in the Dockerfile) and the Mozilla Privacy URL.

After launching a second time, an additional tab with the Dockerfile specified URL is added to the same window.

If I set the default search engine in the last tab as per the Ecosia instructions (allow, add, yes), then the default search is changed for *all* tabs.

**Describe the results you expected:**

I was expecting a new window to open that was completely isolated from the first window, different preferences, different settings, different plug-ins.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a vanilla minimal ubuntu installation with only open-vm-tools-desktop and podman installed (from the projectatomic ppa)

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  MemFree: 1738747904
  MemTotal: 16792702976
  OCIRuntime:
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1026801664
  SwapTotal: 1027600384
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: water
  kernel: 5.0.0-29-generic
  os: linux
  rootless: true
  uptime: 2h 10m 13.76s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /home/administrator/.config/containers/storage.conf
  ContainerStore:
    number: 20
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/administrator/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 19
  RunRoot: /run/user/1000
  VolumePath: /home/administrator/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/disco,now 1.5.1-2~ubuntu19.04~ppa1 amd64 [installed]
podman/disco 1.5.1-2~ubuntu19.04~ppa1 i386
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is a VMware Fusion Guest running an up to date minimal install of Ubuntu (disco) 19.04.

The Dockerfile is trivial:

```
FROM debian:stable-slim

RUN \
	apt-get update && \
	apt-get -y upgrade && \
	apt-get -y install xterm

RUN \
	apt-get -y install firefox-esr

RUN \
	useradd -ms /bin/bash docker

USER docker

ENTRYPOINT ["/usr/bin/firefox-esr"]
CMD ["https://www.ecosia.org/"]
```

The build command:
```
docker build -t itmaze/firefox-esr:latest .
```

**Comment by rhatdan** [comment]
You are using X Windows to do this.  The itmaze/firefox-esr is opening a connection to $DISPLAY or to a port on the host network and asking the firefox that is running to open a TAB.  You are not running a separate instance of Firefox.

**Comment by ITmaze** [comment]
Confirmed, I just tried this in native docker and the same behaviour happens, very unexpected.

Thank you @rhatdan
