### ISSUE TITLE
podman info display cgroups version

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#4080]
I think it would be helpful to include the cgroups version in the host section of `podman info`. With more users and distributions using v2, there might be some common configuration hiccups we could detect easier with that at hand for new issues.

@giuseppe WDYT?

**Comment by baude** [comment]
yes please

**Comment by rhatdan** [comment]
We would need this for buildah info as well.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/4141

**Comment by giuseppe** [comment]
and for Buildah: https://github.com/containers/buildah/pull/1876
