### ISSUE TITLE
libpod.conf option to set default shm-size

### ISSUE THREAD

**Issue by jcpunk** [containers/libpod#4084]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Along with the other default options within `libpod.conf` it would be helpful for me to set an alternate default for `shm-size`.

**Steps to reproduce the issue:**

1. look for way to set the default of `--shm-size` within podman to a value other than 64m

2.

3.

**Describe the results you received:**

No way to override the set for `--shm-size` within a config file.  Must manually set each time.

**Describe the results you expected:**

Way to set this within `libpod.conf`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.13rc1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13rc1
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: conmon-2.0.0-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.0, commit: ae68c1c29156934457e2649990c241a5e0b0251b'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 695001088
  MemTotal: 33547685888
  OCIRuntime:
    package: crun-0.9.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun 0.9.1
      spec: 1.0.0
      +SYSTEMD +SELINUX +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 34342432768
  SwapTotal: 34359734272
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: testify.fnal.gov
  kernel: 5.3.0-1.fc31.x86_64
  os: linux
  rootless: true
  uptime: 74h 17m 34.07s (Approximately 3.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/riehecky/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/riehecky/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
  VolumePath: /home/riehecky/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.git0005792.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
tested on a physical host

**Comment by mheon** [comment]
@rhatdan This sounds like a good use-case for `containers.conf`

**Comment by rhatdan** [comment]
I agree this is a containers.conf issue.  We need to start moving that PR https://github.com/containers/buildah/pull/1858 forward.
@QiWang19 FYI

**Comment by mheon** [comment]
Upcoming feature with containers.conf, so we shouldn't close this

**Comment by vrothberg** [comment]
Assigning @rhatdan as he's the driving force behind containers.conf.

**Comment by rhatdan** [comment]
Fixed in containers.conf #4698
