### ISSUE TITLE
Integration tests: run pod doesn't wait for port-bind before check

### ISSUE THREAD

**Issue by cevich** [containers/libpod#4085]
/kind bug

**Description**

When starting a pod (or a container) in detached-mode, the command exits as soon as the entry-point starts.  Several tests start nginx listening in a container on a specific port.  However, these tests do not wait for nginx startup-completion (port-binding), before checking accessibility of the test-port.

**Steps to reproduce the issue:**

(speculative)
1. `podman run --pod $(podman pod create --name test -p 8080:80) -dt nginx && nc -z localhost 8080`

**Describe the results you received:**

Sometimes the `nc` command returns exit code `1`

**Describe the results you expected:**

The `nc` command should always exit `0` assuming the nginx process is running and bound to port 8080.

**Additional information you deem important (e.g. issue happens only occasionally):**

* Example failure: https://cirrus-ci.com/task/4927408802627584?command=integration_test
* Located in test: `podman create pod with network portbindings`:
https://github.com/containers/libpod/blob/master/test/e2e/pod_create_test.go#L106-L108
* There's a false-positive race possible on line 95, where port is expected to be inaccessable. 
 This may not be the case due to some other future/secondary/unknown breakage causing it to "leak".

**Comment by cevich** [comment]
Suggestion - Given how many integration tests use the nginx image, what if we customize it so it emits some output, like 'READY' after nginx has been started.  Then the test can use `podman logs...` to wait for "READY" before running the `nc ...` check.

**Comment by cevich** [comment]
Easier (maybe) suggestion:  A custom nginx image for testing.

```Dockerfile
FROM nginx:latest
RUN sed -i -r -e 's#error_log\s+\/var\/log\/nginx\/error.log\s+warn\;#error_log  /var/log/nginx/error.log debug;#' /etc/nginx/nginx.conf
CMD ["nginx-debug", "-g", "daemon off;"]
```

When run, this will splat a bunch of useful status bits on stdout (and therefor to it's log):

```
root@20d0039f82d2:/# nginx-debug -g "daemon off;"
2019/09/23 18:55:51 [debug] 13#13: bind() 0.0.0.0:80 #6 
2019/09/23 18:55:51 [notice] 13#13: using the "epoll" event method
2019/09/23 18:55:51 [debug] 13#13: counter: 00007F631D3D4080, 1
2019/09/23 18:55:51 [notice] 13#13: nginx/1.17.3
2019/09/23 18:55:51 [notice] 13#13: built by gcc 8.3.0 (Debian 8.3.0-6) 
2019/09/23 18:55:51 [notice] 13#13: OS: Linux 5.1.11-200.fc29.x86_64
2019/09/23 18:55:51 [notice] 13#13: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/09/23 18:55:51 [debug] 13#13: write: 7, 00007FFC00F18C80, 3, 0
2019/09/23 18:55:51 [debug] 13#13: setproctitle: "nginx: master process nginx-debug -g daemon off;"
2019/09/23 18:55:51 [notice] 13#13: start worker processes
2019/09/23 18:55:51 [debug] 13#13: channel 3:7
2019/09/23 18:55:51 [notice] 13#13: start worker process 14
2019/09/23 18:55:51 [debug] 13#13: sigsuspend
2019/09/23 18:55:51 [debug] 14#14: add cleanup: 000055FAF603D6F0
2019/09/23 18:55:51 [debug] 14#14: malloc: 000055FAF601F910:8
2019/09/23 18:55:51 [debug] 14#14: notify eventfd: 9
2019/09/23 18:55:51 [debug] 14#14: eventfd: 10
2019/09/23 18:55:51 [debug] 14#14: testing the EPOLLRDHUP flag: success
2019/09/23 18:55:51 [debug] 14#14: malloc: 000055FAF60243D0:6144
2019/09/23 18:55:51 [debug] 14#14: malloc: 00007F631CB4A010:253952
2019/09/23 18:55:51 [debug] 14#14: malloc: 000055FAF60418A0:98304
2019/09/23 18:55:51 [debug] 14#14: malloc: 000055FAF60598B0:98304
2019/09/23 18:55:51 [debug] 14#14: epoll add event: fd:6 op:1 ev:00002001
2019/09/23 18:55:51 [debug] 14#14: epoll add event: fd:7 op:1 ev:00002001
2019/09/23 18:55:51 [debug] 14#14: setproctitle: "nginx: worker process"
2019/09/23 18:55:51 [debug] 14#14: worker cycle
2019/09/23 18:55:51 [debug] 14#14: epoll timer: -1
```

That lets us modify the affected tests to use `podman logs` and watch for `start worker process` using `utils.WaitContainerReady()` to signal startup completion.

**Comment by rhatdan** [comment]
Do we know if nginx supports sd-notify?  If it does, we could test for that and kill two birds with one stone.

**Comment by cevich** [comment]
I did a search through `./test/e2e` and a *lot* of tests rely on the nginx container w/o any checking if it's actually up and listening (only if it's up).  We always run it in a container, so we'd need to rig that up through systemd which...may be a bit much for the integration tests?  Maybe I'm not fully understanding your idea though.

**Comment by cevich** [comment]
Something like ^^^ is what I had in mind (but complete)

**Comment by cevich** [comment]
This is still an issue, but doesn't flake very frequently.  Can re-open if otherwise.
