### ISSUE TITLE
podman-remote: missing error messages

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4096]
```
# podman-remote run alpine /no/such/command
```
(i.e. no output). Error message goes only to the varlink window:
```
# podman varlink --timeout=0
ERRO[1399] container_linux.go:346: starting container process caused "exec: \"/no/such/command\": stat /no/such/command: no such file or directory": OCI runtime command not found error
```
podman-1.6.0-2.fc30.x86_64 as well as current master @ 83b2348313c52cc3e20d72285a9d81d3d72c2d5d; but this is a longstanding bug

**Comment by edsantiago** [comment]
Problem still present in master @ 381fa4df875af3d2acee34d4fc1a608b2218b551

**Comment by mheon** [comment]
You need to not only reopen, but clear the stale-issue label, to prevent it from autoclosing again. Sort of annoying.
