### ISSUE TITLE
Add Ubuntu PPAs for dev/beta channels

### ISSUE THREAD

**Issue by shaicoleman** [containers/libpod#4099]
/kind feature

**Description**

At the moment only stable releases are available to download from the Ubuntu PPA.

Allowing people to download nightly and prerelease (rc/betas) would allow more users to test releases to ensure they are stable, and to allow users to use fixes and enhancements that aren't yet in stable

Ideally there will be 3 PPAs:
Dev (hourly/nightly)
Beta (which would include any tagged release, e.g. beta and RC)
Stable

Discussed in: #3923

**Comment by rhatdan** [comment]
Nice work @shaicoleman and @lsm5 We are getting closer.

**Comment by vrothberg** [comment]
@shaicoleman @lsm5, what's the latest state on this work?

**Comment by lsm5** [comment]
On Wed, Oct 30, 2019 at 01:48:23AM -0700, Valentin Rothberg wrote:
> @shaicoleman @lsm5, what's the latest state on this work?

WIP, but nothing landed yet, but hopefully soon..

**Comment by rhatdan** [comment]
@lsm5 any update?

**Comment by vrothberg** [comment]
Yes, the cross-distro packaging is now happening in the public OBS instance:
https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers

There are three streams: stable, testing, unstable.

**Comment by rhatdan** [comment]
@vrothberg Can we close this PR then?

**Comment by vrothberg** [comment]
> @vrothberg Can we close this PR then?

Sounds good. Feel free to re-open if needed.
