### ISSUE TITLE
Centos8 podman is 1.1.0?

### ISSUE THREAD

**Issue by willzhang** [containers/libpod#4105]
Why the podman version is 1.1.0 in centos8, how can I install the latest version of podman use yum ?

**Comment by TomSweeneyRedHat** [comment]
@lsm5 can you assist please?

**Comment by lsm5** [comment]
Probably not until centos enables sig repos for centos8. For now you gotta wait for stuff to land in base CentOS.

**Comment by willzhang** [comment]
Centos7 is v1.4.4, but I really want to use the latest version of podman!

**Comment by willzhang** [comment]
Ok
