### ISSUE TITLE
Varlink interface: allow container log formatting

### ISSUE THREAD

**Issue by johanbrandhorst** [containers/libpod#4107]
/kind feature

**Description**

The podman varlink interface currently allows the user to get the logs from a container, but they always include a very verbose log format:

```
2019-09-25T17:46:06.557798440+01:00 stderr F [2019-09-25 16:46:06 +0000] [1] [INFO] Starting gunicorn 19.9.0
2019-09-25T17:46:06.558227606+01:00 stderr F [2019-09-25 16:46:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
2019-09-25T17:46:06.558276963+01:00 stderr F [2019-09-25 16:46:06 +0000] [1] [INFO] Using worker: gevent
2019-09-25T17:46:06.559931444+01:00 stderr F [2019-09-25 16:46:06 +0000] [9] [INFO] Booting worker with pid: 9
2019-09-25T17:46:07.442431290+01:00 stderr F [2019-09-25 16:46:07 +0000] [1] [INFO] Handling signal: term
2019-09-25T17:46:09.747009937+01:00 stderr F [2019-09-25 16:46:09 +0000] [9] [INFO] Worker exiting (pid: 9)
2019-09-25T17:46:09.851370437+01:00 stderr F [2019-09-25 16:46:09 +0000] [1] [INFO] Shutting down: Master
```
vs `podman logs <id>`:
```
$ podman logs 0afa6ac3f940
[2019-09-25 16:46:06 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-09-25 16:46:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2019-09-25 16:46:06 +0000] [1] [INFO] Using worker: gevent
[2019-09-25 16:46:06 +0000] [9] [INFO] Booting worker with pid: 9
[2019-09-25 16:46:07 +0000] [1] [INFO] Handling signal: term
[2019-09-25 16:46:09 +0000] [9] [INFO] Worker exiting (pid: 9)
[2019-09-25 16:46:09 +0000] [1] [INFO] Shutting down: Master
```

The header: `2019-09-25T17:46:06.557798440+01:00 stderr F` is only prepended to the varlink logs, it appears.

This format gets in the way more often than not, but there does not appear to be a way to configure it. I propose it is removed altogether or made configurable.

**Steps to reproduce the issue:**

1. Start a container
1. Get the containers logs via the varlink interface
1. Observe verbose logging metadata

**Describe the results you received:**

I received excessively verbose logs.

**Describe the results you expected:**

I expected to be able to configure the logging format, or that there was none.

**Output of `podman version`:**

```bash
$ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.0, commit: e217fdff82e0b1a6184a28c43043a4065083407f'
  Distribution:
    distribution: manjaro
    version: unknown
  MemFree: 198766592
  MemTotal: 16569856000
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 18179530752
  SwapTotal: 18223570944
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: REDACTED-x1
  kernel: 4.19.69-1-MANJARO
  os: linux
  rootless: true
  uptime: 22h 29m 13.05s (Approximately 0.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/REDACTED/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/REDACTED/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/REDACTED/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on bare metal (laptop)

**Comment by johanbrandhorst** [comment]
This logging appears to be applied here:
https://github.com/containers/libpod/blob/8ab3c86aa19d4851ee31a764becb7cbc8c1e9c07/libpod/container_log_linux.go#L100. I would be happy to submit a PR to remove the headers myself, if that is deemed an appropriate action.

**Comment by haircommander** [comment]
@johanbrandhorst are you using `systemd` log driver or `k8s-file`? The above code is only for `systemd`, and I think you're seeing output of `k8s-file` that is being read directly from the log file

**Comment by johanbrandhorst** [comment]
@haircommander I'm not sure, whatever the default is I guess? I haven't specified the log driver explicitly. This is using a varlink interface where the host is `podman varlink unix:/home/$(whoami)/podman.socket -t 0 &`.

**Comment by johanbrandhorst** [comment]
Setting `k8s-file` explicitly also results in the same verbose output.

**Comment by haircommander** [comment]
@johanbrandhorst can you describe your exact process? I am not able to reproduce your problem
```
 $ ./bin/podman varlink unix:/run/podman/io.podman -t 0 &
[1] 15218
 $ podman-remote run  --log-driver k8s-file alpine echo hi
hi
 $ podman-remote logs -l
hi
```
this is on latest master, and podman 1.5.1

**Comment by johanbrandhorst** [comment]
Sorry, I was not using `podman-remote`, but rather the generated `iopodman` package to interact with the varlink interface from inside a go application. You can see exactly what I'm doing here: https://github.com/uw-labs/podrick/blob/03d090fffb46e7e702035e37f73add6d0682c39d/podrick.go#L136. Feel free to clone and run the tests on this branch, I expect you should be able to reproduce the results easily. Sorry if the code is a little messy, I'm still prototyping.

**Comment by johanbrandhorst** [comment]
This is is still a problem

**Comment by vrothberg** [comment]
> This logging appears to be applied here:
> 
> https://github.com/containers/libpod/blob/8ab3c86aa19d4851ee31a764becb7cbc8c1e9c07/libpod/container_log_linux.go#L100
> . I would be happy to submit a PR to remove the headers myself, if that is deemed an appropriate action.

@jwhonce @baude @haircommander WDYT? @johanbrandhorst thanks for offering help!

**Comment by rhatdan** [comment]
I would go with the formatting string.

**Comment by johanbrandhorst** [comment]
I'll see if I can put together a PR with a formatting string.

**Comment by johanbrandhorst** [comment]
I had a brief look into implementing this and it appears the formatting is happening before writing it to the journal. Adding a formatting string to `GetContainerLogs` won't do anything, unless we want to parse the already formatted strings.

I could _remove_ the existing formatting from the logging code and then add it back as a configurable format in GetContainerLogs. What do you think?

**Comment by rhatdan** [comment]
@baude @jwhonce ^^

**Comment by johanbrandhorst** [comment]
This is still a problem. Could we reopen this please?

**Comment by rhatdan** [comment]
Lets make this apply to APIV2, Varlink is in depracated mode.

**Comment by rhatdan** [comment]
@jwhonce Says we have this now in APIV2.

**Comment by johanbrandhorst** [comment]
Sorry, I missed the varlink deprecation, what is the future plan for the podman API and what is the deprecation schedule? I have written libraries that consume the varlink API so it'll let me plan ahead.

**Comment by baude** [comment]
We are in the process of completing, documenting, and writing tests for the new api now.  We are still working on some of the major bits like attach.  But we are getting close.  As for a timeline, I honestly cannot be certain.  One indicator to nearly done will be when you see us wiring the remote client from varlink to the restful interface.

**Comment by johanbrandhorst** [comment]
Is there a definition of the new API? Something to generate clients against (OpenAPI/Protobuf)?

**Comment by vrothberg** [comment]
> Is there a definition of the new API? Something to generate clients against (OpenAPI/Protobuf)?

Here's a recent blog post on the new API: https://podman.io/blogs/2020/01/17/podman-new-api.html

We're always happy about contributions :)

**Comment by johanbrandhorst** [comment]
> > Is there a definition of the new API? Something to generate clients against (OpenAPI/Protobuf)?
> 
> Here's a recent blog post on the new API: https://podman.io/blogs/2020/01/17/podman-new-api.html
> 
> We're always happy about contributions :)

Thank you! I will take a look.
