### ISSUE TITLE
How to report security issues

### ISSUE THREAD

**Issue by inthenets** [containers/libpod#4108]
Hey folks,

I tried emailing a few contacts associated with the repo and project recently, but haven't heard back as of now. Recently took a look at the code and security model of Podman, specifically with it's Varlink integration and wrote up some security related details and have some findings that are likely of interest to you folks.

I couldn't find the typical security@ email address to discussing issues (yet!), so I'm wondering who I can get in contact with over email to have a look at the security research and see what needs fixed/changed/documented which can be used to improve security for the project. Opening a public issue on the repo is probably not the best way to talk about the issues prior to them being fixed/documented as applicable, so please advise.

Thanks!

**Comment by baude** [comment]
@inthenets you can email me bbaude@ i work for Red Hat

**Comment by inthenets** [comment]
Thanks baude!

**Comment by MarcoFalke** [comment]
As a note to maintainers, you can also set one up on GitHub: https://github.com/containers/libpod/security/policy

**Comment by mheon** [comment]
We now have instructions for this in the README.
