### ISSUE TITLE
1.6 rc2, fc30, rootless: warnings about missing crun

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4115]
(Similar to, but not the same as, #4012)

podman-1.6.0-0.2.rc2.fc30 rootless outputs copious warnings by default:
```
$ podman images
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
REPOSITORY                   TAG       IMAGE ID       CREATED        SIZE
....
```
This is fc30, not fc31. I made the warnings go away by hand-editing `~/.config/containers/libpod.conf` but am concerned that this is going to come back and haunt us; in particular, regular users will end up doing the same (removing runc from config) and then ending up with nonworking podman when they upgrade to fc31.

**Comment by mheon** [comment]
This repros as rootless, but not as root. I'm really confused as to why default log level is not the same between the two.

**Comment by mheon** [comment]
We explicitly set `ERROR` level logging by default for Podman, unconditionally, unless overridden by CLI.

**Comment by mheon** [comment]
```
$ podman info --log-level=error
WARN[0000] cannot find mappings for user mcs: No subuid ranges found for user "mcs" in /etc/subuid 
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
```

Well there's our problem. `logrus` as rootless is ignoring `log-level=error`. Maybe something about how we exec a new process?

**Comment by mheon** [comment]
I think it's definitely the re-exec part of rootless.

**Comment by edsantiago** [comment]
Nice. Fixing this bug may then fix #4012 and get gating tests to pass on rawhide.

**Comment by mheon** [comment]
@giuseppe Poke - where does rootless re-exec happen? I'm trying to trace the code, but getting lost in the make pause process vs join pause process bit.

**Comment by mheon** [comment]
Alright, we seem to be passing literal `argv` into the reexec'd process... So I don't see how we're losing the log level.

**Comment by mheon** [comment]
Does not seem directly related to reexec... I can get it to happen both inside and outside the rootless user namespace.
