### ISSUE TITLE
Cannot access Podman via varlink bridge

### ISSUE THREAD

**Issue by bryonbaker** [containers/libpod#4129]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
kind bug

**Description**
Cannot access podman in a Centos 8 VM via Podman on Mac.
 
**Steps to reproduce the issue:**

1. Installed Centos 8 Streams in MacOS Fusion

2. Configured the environments as per these instructions: [https://podman.io/blogs/2019/01/16/podman-varlink.html](https://podman.io/blogs/2019/01/16/podman-varlink.html)

3. Tested the connection using

`varlink --bridge "ssh _centos-ip-address_" info`

**Describe the results you received:**

```
varlink -debug -bridge "ssh podmanuser@10.10.0.6" info
Error: Cannot get info for 'bridge:ssh podmanuser@10.10.0.6': unexpected EOF
```

**Describe the results you expected:**

```
Vendor: Atomic
Product: podman
Version: 0.10.1
URL: https://github.com/containers/libpod
Interfaces:
  org.varlink.service
  io.podman
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**~/.ssh/config**
```
Host 10.10.0.6
    RequestTTY no
    IdentityFile ~/.ssh/podmanuser
    User podmanuser
    VisualHostKey no
    RemoteCommand /usr/bin/varlink bridge --connect unix:/run/podman/io.podman
    GSSAPIAuthentication no
    ForwardX11 no
```

**Output of `podman version`:**

```
podman version 1.0.2-dev
```

**Output of `/usr/bin/varlink --version`:**

```
16
```

**Output of `podman info --debug`:**

```
ERRO[0000] 'overlay' is not supported over xfs at "/home/bryon/.local/share/containers/storage/overlay" 
ERRO[0000] Failed to built-in GetDriver graph btrfs /home/bryon/.local/share/containers/storage 
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.0.2-dev
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 1f3eb753f2440487206781bcc9b7aeb2eb3c4685-dirty'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 2121342976
  MemTotal: 3940093952
  OCIRuntime:
    package: runc-1.0.0-55.rc5.dev.git2abd837.module_el8.0.0+58+91b614e7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.0'
  SwapFree: 4242534400
  SwapTotal: 4242534400
  arch: amd64
  cpus: 2
  hostname: localhost.localdomain
  kernel: 4.18.0-144.el8.x86_64
  os: linux
  rootless: true
  uptime: 22m 6.89s
insecure registries:
  registries: []
registries:
  registries:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  ConfigFile: /home/bryon/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/bryon/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS: 10.14.6 (18G95)
Fusion: Professional Version 11.5.0 (14634996)
/usr/bin/varlink: 16

**Comment by rhatdan** [comment]
I am not sure if a podman version that old will work on Centos. Might need updated versions of podman and varlink.

**Comment by bryonbaker** [comment]
Yeah I I noticed that. The latest Centos seems to have some very old packages in it. I'll see if I can work out how to pull an upstream podman into Centos now they have moved to AppStreams (still getting my head around that).
The varlink is the latest though as I pulled that directly from git and built it.

**Comment by baude** [comment]
podman-1.0.0-2.git921f98f.module_el8.0.0+58+91b614e7.x86_64 is way too old to work ... you will need updated packages for sure.

**Comment by bryonbaker** [comment]
I've rolled back to Centos 7 as it has a much later version of podman (1.4.4) and will try it. The trouble is that varlink is not available in the Centos 7 RPMs and I can't find which RPM to pull it from. The varlink github site has almost no documentation - including how to build it from scratch. Where is varlink available from?

**Comment by baude** [comment]
fedora has all the packages needed.  remote podman is still working itself into EL distributions.

**Comment by bryonbaker** [comment]
Thanks. I normally use fedora. But for this I have a constraint that i must use Centos - it seems to be the only OS that will work with xhyve. (I am building an alternative to Docker for Mac)
Still working on it. For now I this this issue should be closed

**Comment by baude** [comment]
per user, closing
