### ISSUE TITLE
generate systemd: add network dependency

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#4130]
To support enabling services at system startup, the generated services need to add networking dependencies, namely:

```
Wants=network.target
After=network-online.target
```

Can be tested with enabling a generated service and testing the network connection of the container after reboot. Should also make sure that exposed ports are reachable.

**Comment by mheon** [comment]
@vrothberg @baude We may want to exclude anything with a `kind/feature` label from this reaping. I don't think closing feature requests because nobody has had a chance to work on them is productive.

**Comment by vrothberg** [comment]
@mheon, I think the bot only supports one exempt label. I think it doesn't hurt to be reminded of inactivity - adding the "do-not-close" label will prevent it from being closed in the future.

**Comment by rhatdan** [comment]
@vrothberg Did you ever get around to this?  Shouldn't this be a simple fix?

**Comment by vrothberg** [comment]
Didn't do it yet. I planned to tackle it when working on a bigger item for systemd generation.
