### ISSUE TITLE
Feature - Podman pull status even when under Kubernetes

### ISSUE THREAD

**Issue by fatherlinux** [containers/libpod#414]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>
/kind feature

**Description**
Image pull status. Right now, unless you run the image pull interactively, you can't watch the status. This is sub-optimal when you are running under Kubernetes. For example, there is no way to see how far along the image is. When you are pulling a huge image in Kube/OCP, you just sit there and wait. It gives that sense of no control that users hate. It would be awesome to be able to asynchronously find the status of a pull out. 

This is the same problem docker has.

Basically, have an option in podman to see the status of containers/storage so that you can see what's going on with CRI-O. That would be super cool.

**Steps to reproduce the issue:**

1. Submit a job to kubernetes

2. Wait :-)

3. No status on image pull other than, there is an image pull happening.

**Describe the results you received:**

**Describe the results you expected:**
Would be cool to have an images --status or some such to watch the status interactively while the images are being pulled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
The image library, `github.com/containers/image`, does support writing status back to us, but I suspect that won't make it across processes. We probably need to land support of support upstream to store pull state somewhere (on disk?) where we can get at it and display it

**Comment by rhatdan** [comment]
@mtrmac WDYT?

**Comment by mtrmac** [comment]
Yeah, `containers/image/copy.Options.Progress` exists; it might need significant extensions to be really nice, it’s just a stream of (blob ID, offset) updates with no “total number of blobs“, “blob done” or “total expected size” information), but that’s mostly local and trivial work. So, having podman show this (if it does not show the default reporting, which is text-only but more informative) is simple enough.

The higher level, either making the status of CRI-O visible through completely unrelated local podman processes, or through the CRI-O API itself and Kubernetes pod/node(?) status [which one is this issue really about?], would be most of the work.

**Comment by rhatdan** [comment]
@haircommander @umohnani8 PTAL

Could you potentially work on this together.

**Comment by vrothberg** [comment]
Have there been attempts to extend the CRI with user-friendly pull progress? Doing the dance with Podman seems a bit too complex to me.

**Comment by vrothberg** [comment]
(going through issues at the moment)
@fatherlinux @rhatdan, I think this issue needs some more discussion and input from the CRI-O folks (Cc: @mrunalp @runcom). There are many possibilities to implement this (e.g., CRI-O could log, write to a dedicated file, expose a dedicated grpc API, CRI extension) but CRI-O needs to provide something before we can start for Podman. Maybe that's something for porting CRI-O's image handling over to libpod (Cc: @baude).

**Comment by vrothberg** [comment]
Ping @runcom, @mrunalp. WDYT?

**Comment by rhatdan** [comment]
This issue seems to have gone dead.  Should this issue be moved to CRI-O?

**Comment by baude** [comment]
closing as nothing appears to impact podman, re-open on a different component if needed
