### ISSUE TITLE
PODMAN_HOST should match DOCKER_HOST uri format

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4156]
`DOCKER_HOST` can also be used with URIs to define exactly how to connect to a host, like `DOCKER_HOST=ssh://root@address`.

This feature is key for providing a good user experience because it allows users to use the tool without having to modify CLI arguments or API calls (docker-py loads it implicitely) in scripts/tools.

This was initially described in https://github.com/containers/libpod/issues/2276 which was closed, even if it was not really implemented.

**Comment by rhatdan** [comment]
Seems like a reasonable request.
@baude @jwhonce WDYT?
@ssbarnea a PR would help this along.

**Comment by baude** [comment]
we have similar environment variables just not called DOCKER_HOST or PODMAN_HOST.  Is the actual name required here?

**Comment by rhatdan** [comment]
The question I would have is, would the use of a URI be easier for users to descover then a bunch of different Environment variables.

**Comment by ssbarnea** [comment]
I think that a single URI variable provides more flexibility and is also more future proof. When using multiple variables there is always the need to introduce new ones,... like add protocol, add SSL escpace options, .... --- this is why I think an URI is more appropriate (not to mention that it does not clutter the user env). Switching credentials is would be just one set instead on N-sets-unsets.

I think that docker did the same thing initially where DOCKER_HOST was only the hostname but later they realized that they need more and upgraded it.

There is no special requirement for using proposed name, you are free to use PODMAN_URI or whatever think is more appropriate.

I would like to have the time to make the PR myself but I am afraid I am overloaded till December, at least. Maybe someone else can step in.

**Comment by afbjorklund** [comment]
Setting DOCKER_HOST assumes that it will talk the docker protocol, while it will be varlink...

And we have already used PODMAN_HOST for the hostname (sans scheme and username)

**Comment by afbjorklund** [comment]
What do you think about #4161 ?

**Comment by afbjorklund** [comment]
Here is the comparison of environment variables, between `docker-machine` and `podman-machine`:

```bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/home/anders/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval $(docker-machine env)
```

```bash
export PODMAN_USER="root"
export PODMAN_HOST="127.0.0.1"
export PODMAN_PORT="38053"
export PODMAN_IDENTITY_FILE="/home/anders/.local/machine/machines/box/id_rsa"
export PODMAN_IGNORE_HOSTS="true"
export PODMAN_MACHINE_NAME="box"
# Run this command to configure your shell: 
# eval $(podman-machine env)
```

It would be possible to add a PODMAN_URI, but I don't think varlink (nor ssh) supports `ssh://` ?

**Comment by afbjorklund** [comment]
@ssbarnea : are you OK with using **two** variables instead of one ? PODMAN_USER/PODMAN_HOST

**Comment by sshnaidm** [comment]
Actually it's two variables: `PODMAN_VARLINK_ADDRESS` and combination of `PODMAN_USER/PODMAN_HOST`.
If we use tcp connection to varlink we need to use `PODMAN_VARLINK_ADDRESS`, if unix socket via SSH then `PODMAN_USER/PODMAN_HOST`. Is it right? Please correct me if I'm wrong.
Also there are `--username user --remote-host host` CLI options that can be used with `podman-remote` to connect to varlink unix socket via SSH, but I don't find how to connect with command options to TCP varlink. Is it available only with `PODMAN_VARLINK_ADDRESS=tcp:host:port` environment variable?

**Comment by afbjorklund** [comment]
That sounds about right.

I'm not sure if you are supposed to **use** `tcp:` directly, due to the lack of authentication and encryption ? In the examples it is _only_ used to access a local tcp tunnel, which is then using ssh for the transport:

https://github.com/containers/libpod/blob/master/docs/tutorials/remote_client.md#remote-node-setup

``` console
$ ssh -L 127.0.0.1:1234:/run/podman/io.podman root@remotehost
$ PODMAN_VARLINK_ADDRESS="tcp:127.0.0.1:1234" bin/podman-remote images
```

**Comment by sshnaidm** [comment]
I think `tcp:` is great for local testing, also docker supports it too.
I think maybe `PODMAN_VARLINK_ADDRESS` can be expanded to options like `ssh://user@host` so that we don't need to calculate it depending on protocol.
Just:
```
PODMAN_VARLINK_ADDRESS="tcp:127.0.0.1:1234" bin/podman-remote images
PODMAN_VARLINK_ADDRESS="ssh://user@remote_host:remote_port" bin/podman-remote images
```
Or maybe to introduce a new variable like `PODMAN_REMOTE_HOST`
Then you need to care about one variable only, it makes life easier :)

**Comment by sshnaidm** [comment]
So, is it possible to have one variable for remote connection configuration like it's in docker?

**Comment by afbjorklund** [comment]
Should be trivial to add yet another variable, and parse it as a fallback.

**Comment by rhatdan** [comment]
@afbjorklund or @ssbarnea could you open a PR for this feature?

**Comment by ssbarnea** [comment]
@rhatdan Sorry but until https://github.com/containers/libpod/issues/4511 is fixed I have few incentives to implement such feature. Once that one is sorted I will probably try to raise a PR as I want to make it easier to everyone to use podman.

**Comment by afbjorklund** [comment]
I need all 4 variables (for podman-machine) so adding another one does not help me (need port and key)

**Comment by rhatdan** [comment]
@ssbarnea Are you still interested in this one?
