### ISSUE TITLE
CI flake in `Podman start [It] podman failed to start with --rm should delete the container `

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#4167]
/kind bug

I've seen the test below flake/fail several times in the past week (or so). This issue is meant to help us tracking it down.

```
[+1941s] [Fail] Podman start [It] podman failed to start with --rm should delete the container 
[+1941s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/start_test.go:113
```

**Comment by vrothberg** [comment]
@baude is already working on tracking it down in https://github.com/containers/libpod/pulls

**Comment by vrothberg** [comment]
I haven't seen the flakes recently but am not sure they have been tackled. @baude do you know?

**Comment by NevilleC** [comment]
Still happening, see https://github.com/containers/libpod/pull/4748#discussion_r361343232

**Comment by baude** [comment]
.. i think we shot this one ... closing for now.
