### ISSUE TITLE
[rawhide,rootless] podman run: sd-bus call: Permission denied:

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4182]
Possible flake: it triggered on fc31 gating tests, but not on two separate fc31 VMs I created. I'm now seeing it on rawhide:
```
$ podman run alpine date
Error: sd-bus call: Permission denied: OCI runtime permission denied error
```
debug log: [podman-sd-bus-eperm.txt](https://github.com/containers/libpod/files/3687038/podman-sd-bus-eperm.txt)

I noticed the `/run/user/0/bus` error, and tried setting `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus`, but that made no difference. Neither did `setenforce 0`.
```
$ ls -lRa /run/user/1000
/run/user/1000:
total 0
drwxr-xr-x. 2 fedora fedora 40 Oct  3 11:19 .
drwxr-xr-x. 4 root   root   80 Oct  3 11:19 ..

```
```
Important package versions:
  5.4.0-0.rc0.git3.1.fc32.x86_64
  conmon-2.0.2-0.1.dev.git422ce21.fc32.x86_64
  crun-0.10-1.fc32.x86_64
  iptables-1.8.3-5.fc31.x86_64
  iptables-libs-1.8.3-5.fc31.x86_64
  podman-1.6.2-0.1.dev.gite67e9e1.fc32.x86_64
  podman-manpages-1.5.2-0.88.dev.git2366fd7.fc32.noarch
  podman-tests-1.6.2-0.1.dev.gite67e9e1.fc32.x86_64
  slirp4netns-0.4.0-22.1.dev.git4e51172.fc32.x86_64
  systemd-243-2.gitfab6f01.fc32.x86_64
  systemd-libs-243-2.gitfab6f01.fc32.x86_64
  systemd-pam-243-2.gitfab6f01.fc32.x86_64
  systemd-rpm-macros-243-2.gitfab6f01.fc32.noarch
  systemd-udev-243-2.gitfab6f01.fc32.x86_64
```

[podman-sd-bus-eperm.txt](https://github.com/containers/libpod/files/3687038/podman-sd-bus-eperm.txt)

**Comment by edsantiago** [comment]
This fixes it:
```
$ export XDG_RUNTIME_DIR=/run/user/$(id -u)
```
@giuseppe I suspect this falls under your area of expertise

**Comment by giuseppe** [comment]
when XDG_RUNTIME_DIR is not specified, Podman tries to set it to a location that is usable by the current user, and it seems weird that `/run/user/0` was used, unless it was explicitly set.  Could you verify if `XDG_RUNTIME_DIR` is leaking from the root session?

**Comment by edsantiago** [comment]
`XDG_RUNTIME_DIR` is not leaking. It is unset. I suspect that something-something-recent is making magical dbus calls before podman initializes XDG_RUNTIME_DIR.

**Comment by edsantiago** [comment]
Might not be a change in podman; on this system, I can reproduce even with podman-1.6.0-0.27.dev.git19075ca

**Comment by edsantiago** [comment]
Tried downgrading to 5.4.0-0.rc0.git2.1.fc32 (from git3.1) and systemd-243-1.fc32 (from 243-2.gitfab6f01) because a similar test vm, in which gating tests passed, shows those versions. No luck: I still see the sd-bus error.

**Comment by mheon** [comment]
I think this one is was fixed by our XDG_RUNTIME_DIR fixes?

**Comment by adelton** [comment]
I now see this issue on Fedora 31 and the XDG_RUNTIME_DIR does not seem to help: https://bugzilla.redhat.com/show_bug.cgi?id=1776187.
