### ISSUE TITLE
podman network create: should validate input

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4184]
```
# podman network create 'foo '   <--- foo with a space
/etc/cni/net.d/foo .conflist

# podman network create '../bar'
/etc/cni/bar.conflist
```
Present as of e67e9e12

**Comment by mheon** [comment]
`../` seems like a bug, but IMO `'foo '` is legitimate - if I explicitly want a space in my CNI network name... well, why not?

**Comment by edsantiago** [comment]
I filed this because I noticed, in today's demo, output that looked like:
```
# podman network ls
podman ...
podman2 ...
podman2 ...
```
That is, two "podman2" results. I don't know if one of those is a trailing-space difference, or if there's another reason why there are two, but I humbly suggest that trailing spaces should be absolutely forbidden in any name, be it network or container or pod or anything. The confusion value overrides any possible reason in favor. (Space *within* the string, maybe; but honestly I think the sanest option is to use the existing `nameRegex` validation for consistency).

**Comment by mheon** [comment]
Fair enough.

Simplest way would be to reuse the existing name regex, I agree.

**Comment by rhatdan** [comment]
Yes, kill off spaces.
