### ISSUE TITLE
Have --userns=keep-id in rootless podman also map over secondary groups

### ISSUE THREAD

**Issue by paulraines68** [containers/libpod#4185]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Also have the --userns=keep-id option map over a user's secondary groups.  This is so when a secondary group writable directory is mapped such as with -v /data:/data the container process can still write to it.

Say user 'linuxuser' with default group 'linuxuser' is also in group 'data'.  And directory /data is read/write/setgid group 'data'. If this directory is mapped with -v /data:/data currently using rootless podman, they user has no way to write to it in the container.

If this is not technically possible, then maybe an option that gives the rootless user the ability to choose a group other than their login default group to be used by the container.

I have tried running 'newgrp data' before running podman but this did not change things.

**Comment by rhatdan** [comment]
Does `podman run --group-add data --userns keep-id` do what you want?

**Comment by rhatdan** [comment]
Does not look like it works.  Looks like a bug @giuseppe Any ideas?

```
$ podman run -ti fedora groups
root
$ podman run --group-add wheel -ti fedora groups
root wheel
$ podman run --group-add wheel --userns=keep-id -ti fedora groups
groups: cannot find name for group ID 3267
3267 nobody
```

**Comment by paulraines68** [comment]
No, seems to be just ignored for me.  On the mounted host directory files in group 'data' still show up as 65534.  Same with and without --userns=keep-id for me.  I don't see how it worked for you without the --userns=keep-id though.

```
$ id
uid=7829(raines) gid=7829(raines) groups=7829(raines),1605(data)

$ podman run -it -v /:/host --group-add data rhel7 groups
root

$ podman run -it -v /:/host --group-add data --userns=keep-id rhel7 groups
groups: cannot find name for group ID 7829
7829
```

I am running podman-1.4.4-4.el7.centos.x86_64 on CentOS 7.7

**Comment by paulraines68** [comment]
I should add it does work for me on the 'wheel' group

```
$ podman run -it -v /:/host --group-add wheel rhel7 groups
root wheel
$ podman run -it -v /:/host --group-add wheel --userns=keep-id rhel7 groups
groups: cannot find name for group ID 5829
5829 wheel
```
so maybe only works for groups defined both on the host and in the container?  Not sure why the last did not work for you.  Bug in your development version?

But the GID is remapped so it will not work with host directory mounted directories anyway

```
$ dmesg > /var/tmp/rainesdir/dmesg.out
$ podman run -it -v /:/host --group-add wheel rhel7 bash
[root@4640fa7786e6 /]# cd /host/var/tmp/rainesdir
[root@4640fa7786e6 rainesdir]# ls -l
-rw-rw-r-- 1 root  root  101103 Oct  3 16:17 dmesg.out
[root@4640fa7786e6 rainesdir]# chgrp wheel dmesg.out
[root@4640fa7786e6 rainesdir]# ls -l
-rw-rw-r-- 1 root  wheel 101103 Oct  3 16:17 dmesg.out
[root@4640fa7786e6 rainesdir]# exit
exit
$ ls -l /var/tmp/rainesdir/
-rw-rw-r-- 1 raines 10000009 101103 Oct  3 12:17 dmesg.out

```

We would need the group specified with --group-add  not to be namespace remapped

**Comment by rhatdan** [comment]
Does it work if you specify it via GID, rather then name?

**Comment by paulraines68** [comment]
Yes, it does 

```
$ podman run -it -v /:/host --group-add 1605 --userns=keep-id rhel7 groups
groups: cannot find name for group ID 7829
7829 groups: cannot find name for group ID 1605
1605
```

But unfortunately on the mapped host filesystem, while 7829 works, the 1605 does not as it is remapped to 10001605

```
$ grep raines /etc/subgid
raines:10000000:100000
carlsbad[0]:rainesdir$ ls -l
-rw-rw-r-- 1 raines raines 101088 Oct  3 15:49 dmesg1.out
-rw-rw-r-- 1 raines data 101088 Oct  3 15:49 dmesg2.out
carlsbad[0]:rainesdir$ podman run -it -v /:/host --group-add 1605 --userns=keep-id rhel7 bash
bash-4.2$ ls -l /host/var/tmp/rainesdir
-rw-rw-r-- 1 7829  7829 101088 Oct  3 19:49 dmesg1.out
-rw-rw-r-- 1 7829 65534 101088 Oct  3 19:49 dmesg2.out
bash-4.2$ chgrp 1605 /host/var/tmp/rainesdir/dmesg2.out
bash-4.2$ exit
exit
carlsbad[0]:rainesdir$ ls -l /var/tmp/rainesdir
-rw-rw-r-- 1 raines raines   101088 Oct  3 15:49 dmesg1.out
-rw-rw-r-- 1 raines 10001605 101088 Oct  3 15:49 dmesg2.out
```

I cannot use --gidmap in rootless podman.  So I was hoping whatever magic --userns=keep-id is doing could be used for these secondary groups too.

Ideally it would not require having to change anything in the containers image (e.g. /etc/group) so users would not have to modify images for analysis tools they get from 3rd parties before using them to analyze data in group directories.

**Comment by rhatdan** [comment]
@mheon @giuseppe WDYT?  Should we maintain the additional groups of a user into the container when the user specified --userns=keep-id, or should we add a new option to keep gids from the host.
--userns=keep-id,keep-groups?

**Comment by mheon** [comment]
`--userns=keep-all`?

**Comment by mheon** [comment]
I think separate option makes the most sense

**Comment by mheon** [comment]
Groups could also be useful for people mounting volumes into containers, and then expecting to use other users in the container to access them. Ensure the directory on the host is owned by the `data` group, then add all the users in the container who need access to that `data` group? Would be a nice addition, I think

**Comment by giuseppe** [comment]
`--userns=keep-id` already maps the secondary groups from the host:

```
$ podman run  --rm -ti --userns=keep-id  fedora grep Groups /proc/self/status
Groups:	65534 65534 65534 65534 1000 65534 

$ grep Groups /proc/self/status
Groups:	10 954 973 982 1000 1003 
```

They appear as the unknown id inside of the user namespace since the original id is not mapped (and it cannot be mapped as they are not owned by the unprivileged user).

They are honored by the kernel, I made a quick test like:

```
$ mkdir /tmp/test
$ sudo chown root:wheel /tmp/test
$ sudo chmod 750 /tmp/test
$ echo hello > /tmp/test/hello
$ podman run  --rm -ti --userns=keep-id -v /tmp:/host-tmp  fedora cat /host-tmp/test/hello
hello
```

Can you show me the output of the above grep commands on your system (both on the host and in the container)?

**Comment by rhatdan** [comment]
We currently populate the /etc/passwd with the UID, perhaps we should add the group ids as well if they do not exists.

**Comment by giuseppe** [comment]
from the user namespace PoV these GIDs are not present, they all appear as 65534.

**Comment by rhatdan** [comment]
@giuseppe I thought you said that we mapped the GIDs into the container.
I think the user wants

```
$ groups
dwalsh wheel
$ grep wheel /etc/group
wheel:x:10:dwalsh,test1
$ podman run --userns=keep-id fedora groups
groups: cannot find name for group ID 3267
3267 nobody
```
To be
```
$ podman run --userns=keep-id fedora groups
dwalsh wheel
```
Where we add the UID from /etc/passwd to /etc/passwd in the container. 
$ podman run --userns=keep-id alpine cat /proc/self/gid_map
would list out that 
10 10 1
```

**Comment by paulraines68** [comment]
I don't see --userns=keep-id mapping the secondary groups like you show:

```
$ podman run --rm -it --userns=keep-id rhel7 grep Groups /proc/self/status
Groups:
$ grep Groups /proc/self/status                            
Groups: 25 160 162 998 1039 1072 1101 1109 1489 1501 1605 1608 7829 9250
```
And as a duplicated of your quick test

```
$ getent group data
data:*:1605:raines,...
$ sudo mkdir /tmp/grpdata
$ sudo chown root:webdev /tmp/grpdata
$ sudo chmod g+rws,o-rwx /tmp/grpdata
$ dmesg > /tmp/grpdata/dmesg.out
$ podman run --rm -it --userns=keep-id -v/:/host rhel7 head /host/tmp/grpdata/dmesg.out
head: cannot open '/host/tmp/grpdata/dmesg.out' for reading: Permission denied

```

Again I am running podman-1.4.4-4.el7.centos.x86_64 on CentOS 7.7

**Comment by paulraines68** [comment]
I should add that I am looking to using rootless podman as an alternative to singularity which was the only working way of doing "rootless" secure docker-like containers I know of now.  This is what we use on our compute cluster now but users find it difficult to translate since they are used to docker and instructions they find on the internet for the containers they download are all docker-centric

singularity definitely handles secondary groups just fine:

```
$ singularity shell -B /:/host fedora-latest.simg
Singularity: Invoking an interactive shell within container...
Singularity fedora-latest.simg:/var/tmp> id -G
5829 25 160 162 998 1039 1072 1101 1109 1489 1501 1605 1608 9250
Singularity fedora-latest.simg:/var/tmp> ls -ald /host/tmp/grpdata
drwxrws--- 2 root data 4096 Oct  4 10:23 /host/tmp/grpdata
Singularity fedora-latest.simg:/var/tmp> cd /host/tmp/grpdata
Singularity fedora-latest.simg:/host/tmp/grpdata> ls -l
-rw-rw-r-- 1 raines data 101088 Oct  4 10:23 dmesg.out
Singularity fedora-latest.simg:/host/tmp/grpdata> head -1 dmesg.out
[    0.000000] microcode: microcode updated early to revision 0x200005e, date = 2019-04-02
Singularity fedora-latest.simg:/host/tmp/grpdata> echo HERE >> dmesg.out
Singularity fedora-latest.simg:/host/tmp/grpdata>
```

**Comment by giuseppe** [comment]
> @giuseppe I thought you said that we mapped the GIDs into the container.

we cannot map these GIDs in the user namespace, newgidmap would not allow to use group IDs not specified in `/etc/subgid`.  Still, we should not lose access to them, even if they appear as 65534.

I'll need to debug it further, as on Fedora 31 the groups are maintained, while we don't do that on Centos 7.7

**Comment by giuseppe** [comment]
> I'll need to debug it further, as on Fedora 31 the groups are maintained, while we don't do that on Centos 7.7

it looks like a difference in the OCI runtime.  With runc I get the empty Groups set, with crun instead I get the original groups maintained in the container.

**Comment by vrothberg** [comment]
@giuseppe @rhatdan @mheon how can we proceed?

**Comment by giuseppe** [comment]
I've added an annotation to crun to keep secondary groups inside of the container:

https://github.com/containers/crun/pull/149

crun 0.10.4 has this feature.

To use it from Podman  you can use `--annotation io.crun.keep_original_groups=1`.

There is an open issue for making this feature part of the OCI specs, until then it is a crun-only feature.

**Comment by paulraines68** [comment]
I am trying this on CentOS 8.3 where it seems I finally have all the parts I need but it does not work

```
sisu[0]:~$ rpm -q crun
crun-0.14.1-2.module_el8.3.0+475+c50ce30b.x86_64
sisu[0]:~$ rpm -q podman
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
sisu[0]:~$
sisu[0]:~$ grep Groups /proc/self/status
Groups: 25 160 162 998 1039 1072 1101 1109 1489 1501 1606 1608 5829 9250
sisu[0]:~$ podman --runtime /usr/bin/crun run --annotation io.crun.keep_original_groups=1 -it -v /:/host --userns=keep-id redhat-website:v1
id: cannot find name for group ID 5829
[raines@c8d8a501f727 /]$ grep Groups /proc/self/status
Groups:
[raines@c8d8a501f727 /]$ id
uid=5829(raines) gid=5829 groups=5829
```

What am I missing?

**Comment by giuseppe** [comment]
Can you please try with `run.oci.keep_original_groups=1`?

podman --runtime /usr/bin/crun run --annotation run.oci.keep_original_groups=1 -it -v /:/host --userns=keep-id redhat-website:v1

We didn't own `crun.io` so we changed the name to `run.oci.keep_original_groups`

**Comment by paulraines68** [comment]
Curiously if I run the alpine image instead of fedora I get

```
~ $ groups
raines nobody nobody nobody nobody nobody nobody nobody nobody nobody nobody nobody nobody nobody
~ $ grep Groups /proc/self/status
Groups: 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 5829 65534
```

**Comment by giuseppe** [comment]
can you run `grep Groups /proc/self/status` in the fedora image?

The `groups` tool in Fedora might remove duplicates

**Comment by paulraines68** [comment]
```
[raines@nymeria ~]$ podman --runtime /usr/bin/crun run --annotation run.oci.keep_original_groups=1  --name podmantest2 -it --rm --userns=keep-id fedora bash
bash-5.1$ grep Groups /proc/self/status
Groups: 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 5829 65534
bash-5.1$ groups
raines nobody
bash-5.1$
```

**Comment by giuseppe** [comment]
so it looks like the groups are maintained but the `groups` tool on Fedora remove duplicates

**Comment by paulraines68** [comment]
> so it looks like the groups are maintained but the `groups` tool on Fedora remove duplicates

Not sure what you mean by "maintained".  My groups outside the container are

Groups: 25 160 162 998 1039 1072 1101 1109 1489 1501 1606 1608 5829 9250

that is definitely not what I see inside even after using --annotation run.oci.keep_original_groups=1

**Comment by rhatdan** [comment]
The  groups command sees:
grep Groups /proc/self/status
Groups: 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 65534 5829 65534

And then reports them as
5829 65534

If you look at that process from outside of the container you would see that the process still has the groups you expect.

grep Groups /proc/$PID/status
Groups: 25 160 162 998 1039 1072 1101 1109 1489 1501 1606 1608 5829 9250

@vrothberg we probably should add a podman top -o hgroups

**Comment by paulraines68** [comment]
Okay, but what use is that to me?  I need all the secondary groups to work inside the container.

In practice we have just abandoned Docker and Podman at our site primarily because of this issue and are using Singularity which just does the right thing and works with no special options needed. The hassle is having to convert docker images to SIF images and covert options like -v to -B and sometimes the translations just don't work without having to actually modify the image.  So it is a pain and I am keeping an I on podman to see if it will ever work too.

**Comment by rhatdan** [comment]
That is my point the secondary groups are available to you. Have you tried to use them?

**Comment by paulraines68** [comment]
> That is my point the secondary groups are available to you. Have you tried to use them?

Ok, I see.  All these groups show up as nobody inside the container but still work "magically" outside.  Yes that does appear to be the case.  

I have a directory in group 'sysadm' I am in

```
$ ls -ld /cluster/itgroup/tmp/test
drwxrws--- 3 root sysadm 4096 Sep 23 10:05 /cluster/itgroup/tmp/test
```

If I run

```
podman --runtime /usr/bin/crun run --annotation run.oci.keep_original_groups=1 -v /cluster/itgroup:/data -it --rm --userns=keep-id fedora bash
```

I get inside the container:

```
$ cd /data/tmp/test
$ touch foobar.txt
$ ls -l
-rw-rw----. 1 raines nobody 0 Sep 23 14:05 foobar.txt
$ mkdir foobar.dir
$ ls -ald foobar.dir
drwxrws---. 2 raines nobody 4096 Sep 23 14:05 foobar.dir
```

and outside I now see:

```
$ ls -l /cluster/itgroup/tmp/test
drwxrws--- 2 raines sysadm 4096 Sep 23 10:05 foobar.dir
-rw-rw---- 1 raines sysadm    0 Sep 23 10:05 foobar.txt
```

so it seems to work though what one "sees" inside is confusing

Thanks.

**Comment by rhatdan** [comment]
A patch was just merged into podman top that will show you the groups associated with the processes in the container, from the hosts user namespace perspective and from the containers perspective.
