### ISSUE TITLE
Cannot run MongoDB in systemd-container

### ISSUE THREAD

**Issue by ephracis** [containers/libpod#4191]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a systemd container based on centos/systemd

2. Install rh-mongodb34-mongod inside container

3. Start container with `podman ... --systemd=true ...`

**Describe the results you received:**

The service cannot start inside the container, it fails with the following error:

> New main PID 817 does not belong to service, and PID file is not owned by root. Refusing.

**Describe the results you expected:**

Prior to CentOS 7.7 and https://access.redhat.com/solutions/4420581 everything worked great.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.4.4
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 9602150400
  MemTotal: 16656789504
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: foreman-chbr-node1.vms.dev.basalt.se
  kernel: 3.10.0-957.12.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 1h 5m 18.04s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual machine running on OpenStack, having run `yum -y update` on the host prior to starting the container.

Same version of systemd on host and container.

I have also filed an issue with Foreman in case their installation and configuration of MongoDB is the issue: https://projects.theforeman.org/issues/27887

But I am starting to suspect that the issue is with running a systemd container with `systemd-219-67` and I suspected podman to fix all the mounts when using the `--systemd` flag.

**Comment by ephracis** [comment]
I have an easy way to reproduce the issue:

```
$ cat Dockerfile
FROM centos/systemd
RUN yum -y update && \
    yum -y install centos-release-scl && \
    yum -y install rh-mongodb34-mongodb-server && \
    systemctl enable rh-mongodb34-mongod.service

$ sudo podman build -t test .

... snip ...

$ sudo podman run --systemd=true --name test -d --privileged test
19ae5a643b6b71223068c329b167f9135f3603e32e0e8d5fb920df562c389034

$ sudo podman exec -it test systemctl status rh-mongodb34-mongod
● rh-mongodb34-mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/usr/lib/systemd/system/rh-mongodb34-mongod.service; enabled; vendor preset: disabled)
   Active: activating (start) since Fri 2019-10-04 11:03:03 UTC; 1min 28s ago
  Process: 75 ExecStart=/opt/rh/rh-mongodb34/root/usr/libexec/mongodb-scl-helper enable $RH_MONGODB34_SCLS_ENABLED -- /opt/rh/rh-mongodb34/root/usr/bin/mongod $OPTIONS run (code=exited, status=0/SUCCESS)
   CGroup: /machine.slice/libpod-19ae5a643b6b71223068c329b167f9135f3603e32e0e8d5fb920df562c389034.scope/system.slice/rh-mongodb34-mongod.service
           └─193 /opt/rh/rh-mongodb34/root/usr/bin/mongod -f /etc/opt/rh/rh-mongodb34/mongod.conf run

Oct 04 11:03:03 19ae5a643b6b systemd[1]: Starting High-performance, schema-free document-oriented database...
Oct 04 11:03:03 19ae5a643b6b mongodb-scl-helper[75]: about to fork child process, waiting until server is ready for connections.
Oct 04 11:03:03 19ae5a643b6b mongodb-scl-helper[75]: forked process: 193
Oct 04 11:03:04 19ae5a643b6b mongodb-scl-helper[75]: child process started successfully, parent exiting
Oct 04 11:03:04 19ae5a643b6b systemd[1]: New main PID 193 does not belong to service, and PID file is not owned by root. Refusing.
Oct 04 11:03:04 19ae5a643b6b systemd[1]: New main PID 193 does not belong to service, and PID file is not owned by root. Refusing.
```

**Comment by rhatdan** [comment]
Seems like a systemd issue.  Could you open a bugzilla on this.  I don't believe this is an upstream issue.

**Comment by ephracis** [comment]
Which bugzilla? Should I open a support ticket in the Customer Portal?

**Comment by ephracis** [comment]
I found a Red Hat Bugzilla and created an account to file this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1758509

I also opened a support ticket in Customer Portal since it happens on our RHEL servers too.

**Comment by ephracis** [comment]
The interesting part is that it works fine when run directly on the host. It's only inside a container that the issue appears. That's why I suspected that there is something wrong with how the container is run, either a fault by me or by podman.

**Comment by rhatdan** [comment]
Thanks this very well could be a bug in podman or in mongodb. But bugzilla is the place to put older versions of the tools, rather then upstream.

**Comment by ephracis** [comment]
Ok, I put the component as systemd but maybe that should be changed to something else then. Didn't see podman or "container tools" there, though.

If it would help I could try the upstream libpod, either now (just to check if it's present in master) or when you have branch with a suggested fix.

**Comment by sshnaidm** [comment]
With `podman-1.5.1-3.fc30.x86_64` it runs fine:
```
● rh-mongodb34-mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/usr/lib/systemd/system/rh-mongodb34-mongod.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-10-06 14:17:31 UTC; 49s ago
  Process: 55 ExecStart=/opt/rh/rh-mongodb34/root/usr/libexec/mongodb-scl-helper enable $RH_MONGODB34_SCLS_ENABLED -- /opt/rh/rh-mongodb34/root/usr/bin/mongod $OPTIONS run (code=exited, status=0/SUCCESS)
 Main PID: 69 (mongod)
   CGroup: /machine.slice/libpod-049c34384b9dce05a186656fea08b67e827fdefd504b2e29a7b7404e13727c8f.scope/system.slice/rh-mongodb34-mongod.service
           └─69 /opt/rh/rh-mongodb34/root/usr/bin/mongod -f /etc/opt/rh/rh-mo...

Oct 06 14:17:30 049c34384b9d systemd[1]: Starting High-performance, schema-f....
Oct 06 14:17:30 049c34384b9d mongodb-scl-helper[55]: about to fork child proc...
Oct 06 14:17:30 049c34384b9d mongodb-scl-helper[55]: forked process: 69
Oct 06 14:17:31 049c34384b9d systemd[1]: Started High-performance, schema-fr....
Hint: Some lines were ellipsized, use -l to show in full.

```

**Comment by ephracis** [comment]
Cool! Will the fix be backported to the 1.4 branch anytime soon, since that's what's available on RHEL/CentOS right now?

Also, are there any binaries for CentOS for 1.5 or even 1.6? Or do I need to compile it manually in order to verify that it solves my issue?

**Comment by rhatdan** [comment]
@lsm5 Could you point at the Centos 1.5 or 1.6 packages?

**Comment by ephracis** [comment]
Any update on when we can expect to see 1.5 or 1.6 in CentOS (or a 1.4.5 with the fix backported)?

**Comment by rhatdan** [comment]
@lsm5 Pointers?

**Comment by rhatdan** [comment]
I know the packages for podman 1.6 will show up in RHEL 8.1.1 which is scheduled to come out in January.
