### ISSUE TITLE
Inspect fails for .Image field

### ISSUE THREAD

**Issue by laped83** [containers/libpod#4193]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman run -t -d fedora:30 cat

2. podman inspect -f="{{.Image}}" 1e7c4920ed4b

3.

**Describe the results you received:**

Error: Template parsing error: template: image:1:2: executing "image" at <.Image>: can't evaluate field Image in type *libpod.InspectContainerData

**Describe the results you expected:**

The value of "Image": "9eff96f4c827f839118cd36a028c8ae00187fbda5707a470bb60f0ece860c0cf",

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 494751744
  MemTotal: 16617947136
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 8031039488
  SwapTotal: 8380215296
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: laped.localdomain
  kernel: 5.2.17-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 100h 38m 32.26s (Approximately 4.17 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/laa/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /home/laa/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /tmp/1000
  VolumePath: /home/laa/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical fedora workstation

**Comment by vrothberg** [comment]
Hi @laped83, thanks for the report. I can reproduce and found the issue.

@baude @mheon, the problem is that the go field is called `ImageID` while the json identifier is called `Image` (see https://github.com/containers/libpod/blob/master/libpod/container_inspect.go#L99). Strictly speaking, changing `ImageID` to `Image` is breaking the API. _However_, a simple `podman inspect $CTR` will print the json structure, so all users should have been tricked into trying to filter for `Image` which makes me consider it a bug fix. WDYT?

**Comment by mheon** [comment]
@vrothberg We actually do normalization for a few of these in the `inspect` code - when we've changed identifiers previously, we did a crude string-replace to ensure the old ones still worked - https://github.com/containers/libpod/blob/master/cmd/podman/inspect.go#L99-L106

I think we should replace ImageID with Image, and add another one of these string-replaces as a band-aid to keep from breaking folks. We can deprecate and remove them at a later date.

**Comment by vrothberg** [comment]
Fix is here: https://github.com/containers/libpod/pull/4195
