### ISSUE TITLE
Removing kubernetes breaks podman

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#4202]
Or, more specifically, running `kubeadm reset` removes **all** of CNI:

https://github.com/kubernetes/kubernetes/blob/v1.16.0/cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go#L84

* **`/etc/cni/net.d`**
* `/var/lib/dockershim`
* `/var/run/kubernetes`
* **`/var/lib/cni`**

This is a "known issue" for CRI-O, where I assume it doesn't matter:
https://github.com/cri-o/cri-o/blob/master/tutorials/kubeadm.md

> First, CRI-O and kubeadm reset don't play well together, as kubeadm reset empties /etc/cni/net.d/. Therefore, it is good to change the crio.network.network_dir in crio.conf to somewhere kubeadm won't touch.

i.e. if you remove Kubernetes, you probably don't need CRI-O either...
But it is unfortunate that networking in podman doesn't work afterwards.

> error configuring network namespace for container 8cf402b2d46c31e7fc80fa3a215342b510e18ebc3510e8baf92df941cad4bbd0: Missing CNI default network

----

This isn't really podman's fault, and I'm not sure that any reasonable workaround can be made...

Will open a ticket with kubeadm, see if it can do some more surgical cleanup of created files ?

Found this out when trying to test minikube on CentOS 8: https://github.com/kubernetes/minikube/issues/5532#issuecomment-538051803

It _worked_ in the end, but the out-of-the-box experience was awful. WIll try OKD alpha next time.

**Comment by vrothberg** [comment]
Thanks for the report, @afbjorklund!

> Will open a ticket with kubeadm, see if it can do some more surgical cleanup of created files ?

I agree. From a packaging perspective, it seems concerning that the kubeadm deletes files from _other_ packages.

**Comment by afbjorklund** [comment]
The directory contains two files, so it _should_ only have removed one of them:

* `/etc/cni/net.d/87-podman-bridge.conflist`
* **`/etc/cni/net.d/k8s.conf`**

Anyway, functionality can be restored again with: `sudo yum reinstall podman`

And it worked OK, even if an older version (1.0.1) `podman-1.0.0-2.git921f98f`

**Comment by afbjorklund** [comment]
Opened https://github.com/kubernetes/kubeadm/issues/1822

**Comment by vrothberg** [comment]
I'm closing the issue as it must be fixed in `kubeadm`. Thanks a lot, @afbjorklund, for pushing to fix it!
