### ISSUE TITLE
Podman is not taking proxy env variables when pulling or login

### ISSUE THREAD

**Issue by GolanTrevize10** [containers/libpod#4211]
/kind bug

**Description**

When I try to do a podman build, podman login or podman pull behind a proxy I get a connection refused error when trying to connect with docker hub or redhat registry. Curl works so https_proxy variable is correctly set up and the URLs are whitelisted in the proxy. I am running podman inside an Openshift pod. 

**Steps to reproduce the issue:**

1. Create a docker image with podman installed inside it. 

2. Run the docker image in Openshift behind a proxy setting env variables https_proxy

3. Inside the pod run sudo /usr/bin/podman login registry.access.redhat.com --storage-driver vfs or sudo /usr/bin/podman login registry-1.docker.io --storage-driver vfs

**Describe the results you received:**

sh-4.2$ sudo /usr/bin/podman login registry-1.docker.io --storage-driver vfs --log-level debug
Username: dsf
Password:
DEBU[0003] Looking for TLS certificates and private keys in /etc/docker/certs.d/registry-1.docker.io
DEBU[0003] GET https://registry-1.docker.io/v2/
DEBU[0003] Ping https://registry-1.docker.io/v2/ err Get https://registry-1.docker.io/v2/: dial tcp 52.55.198.220:443: connect: connection refused (&url.Error{Op:"Get", URL:"https://registry-1.docker.io/v2/", Err:(*net.OpError)(0xc420536c80)})
DEBU[0003] GET https://registry-1.docker.io/v1/_ping
DEBU[0003] Ping https://registry-1.docker.io/v1/_ping err Get https://registry-1.docker.io/v1/_ping: dial tcp 52.2.186.244:443: connect: connection refused (&url.Error{Op:"Get", URL:"https://registry-1.docker.io/v1/_ping", Err:(*net.OpError)(0xc420537040)})
ERRO[0003] error authenticating creds for "registry-1.docker.io": pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp 52.55.198.220:443: connect: connection refused

**Describe the results you expected:**
I expect login succesful or credentials error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

**Output of `podman info --debug`:**

debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.6"
  MemFree: 25185411072
  MemTotal: 67368648704
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  hostname: jenkins-slave-prg-test-slmwg
  kernel: 3.10.0-957.5.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 632h 27m 26.24s (Approximately 26.33 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: []
  GraphRoot: /var/lib/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-1.4.4-4.el7.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on a pod on Openshift 3.11

**Comment by rhatdan** [comment]
Are you sure the environment variables are set within the container running podman?  Can podman see the proxy from its network?

**Comment by GolanTrevize10** [comment]
@rhatdan yes, as I mentioned if I do a curl to the red hat registry or docker hub from within the container it works

**Comment by rhatdan** [comment]
Could you try a newer version of podman, or verify if podman on the host outside of the container follows the rules?  The HTTP_PROXY redirect is supposed to be handled in the GOLANG libraries, podman does not do anything with these specifically.  So it could be that podman as compiled with an older version of golang that did not properly support this feature.

**Comment by GolanTrevize10** [comment]
Where can I get a newer version of podman from? I installed the latest RHEL podman package.

**Comment by mheon** [comment]
You're on 1.4.4, which makes me think RHEL 7?

@lsm5 maintains a repo with a more up-to-date build of Podman for RHEL/Cent 7.

**Comment by lsm5** [comment]
seems the latest build of 1.6.1 for centos7 failed. Let me fix that and get back..

**Comment by lsm5** [comment]
https://cbs.centos.org/koji/taskinfo?taskID=982862 podman 1.6.1

**Comment by GolanTrevize10** [comment]
Thanks I tried with that podman package but it does not work. I got this error

time="2019-10-14T22:17:34+02:00" level=error msg="could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument"

I have installed conmon.

**Comment by GolanTrevize10** [comment]
I added the path to conmon to the libpod.config and now I get a different error: 

time="2019-10-15T16:57:31+02:00" level=warning msg="conmon at /usr/libexec/crio/conmon invalid: outdated conmon version"
time="2019-10-15T16:57:31+02:00" level=error msg="could not get runtime: please update to v1.0.0 or later: outdated conmon 

I have conmon 1.10

**Comment by GolanTrevize10** [comment]
I tried with podman 1.5.1 but I got same error. @lsm5 can you make a package of podman 1.6.1 including conmon?

**Comment by dustymabe** [comment]
@GolanTrevize10 - did your issue every get fully resolved ?
