### ISSUE TITLE
document that rootless mode enables lingering mode

### ISSUE THREAD

**Issue by giuseppe** [containers/libpod#4224]
add a note to the documentation explaining why rootless containers need lingering mode

**Comment by cgwalters** [comment]
Just noting here I don't think rootless podman should *automatically* try to change the host system to enable this.  Let's just print a clear error message.

The rationale for this is that while it's convenient for "user owns machine" cases, we also want to support "organization owns machine" cases where the user can't/shouldn't gain root on their systems.  For those types of scenarios, enabling linger is something that the "system administrator" should do via e.g. a config management system.

**Comment by debarshiray** [comment]
Yes, I agree with @cgwalters 

People might get surprised if using Toolbox toggles the lingering mode of the system because they think of `toolbox enter` as a shell, which it basically is.

**Comment by rhatdan** [comment]
I agree we should not do this by default.  But documenting it does not hut.  We want to tell the admin how to enable it.

**Comment by giuseppe** [comment]
since it seems there is agreement on disabling lingering mode by default, I've opened a PR here:

https://github.com/containers/libpod/pull/4269

**Comment by andrew-aladev** [comment]
[This issue](https://github.com/moby/moby/issues/40708) is the reason. Just one docker developer made wrong decision and broke rootless mode.

**Comment by AkihiroSuda** [comment]
@andrew-aladev Even if we avoided using XDG dirs, anyway you need to use linger mode to keep user processes running on systemd hosts.

**Comment by andrew-aladev** [comment]
@AkihiroSuda, `$HOME/.local/share` is a good standard path that is stable across sessions. `XDG_*` path is designed for software that don't want to store some data across sessions. These directories has been implemented as re-mounted tmpfs endpoiints.
