### ISSUE TITLE
Centos 7 systemd container on Fedora 31

### ISSUE THREAD

**Issue by greg-hydrogen** [containers/libpod#4226]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running a centos 7 container with systemd fails to run on Fedora 31 

**Steps to reproduce the issue:**

1.  podman run -ti centos7-with-systemd /sbin/init

2.  output shows the following:

Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.

3.  This occurs when running as root and rootless

**Describe the results you received:**

Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.

**Describe the results you expected:**

Expect systemd to run 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.13
OS/Arch:            linux/amd64

**Output of `podman info --debug`:**

 podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.1-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 5e0eadedda9508810235ab878174dca1183f4013'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 18496446464
  MemTotal: 67443789824
  OCIRuntime:
    package: crun-0.10.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.1
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  eventlogger: journald
  hostname: kubhost
  kernel: 5.3.0-1.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 186h 43m 44.97s (Approximately 7.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/greg/.config/containers/storage.conf
  ContainerStore:
    number: 13
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/greg/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 21
  RunRoot: /run/user/1000
  VolumePath: /home/greg/.local/share/containers/storage/volumes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
running ZFS

**Comment by mheon** [comment]
My suspicion is that the systemd used in Cent 7 images is too early to support CGroups v2, as used in Fedora 31 by default

**Comment by greg-hydrogen** [comment]
@mheon - agreed, will there be a work around or for users using Centos 7 systemd or should everything be rebuild with Centos 8

**Comment by baude** [comment]
i dont think this is a podman problem?

**Comment by mheon** [comment]
@baude We should contact the systemd folks to be sure. If there's a trivial workaround on the Podman side it could be worthwhile

**Comment by rhatdan** [comment]
@greg-hydrogen could you open a bugzilla on this?  Open it on Podman and we will pull in the systemd team.

**Comment by perlun** [comment]
For reference: https://bugzilla.redhat.com/show_bug.cgi?id=1760645

**Comment by space88man** [comment]
@giuseppe  I am seeing the same problem with  a fedora:31 container (where presumable systemd is cgroup2 aware). Hangs at

```
INFO[0000] Running conmon under slice machine.slice and unitName
libpod-conmon-ddb15b914e83b432a44b9fa9726fb30d144e667f16b4c157d2c8aa54139ec61a.scope
```

**Comment by giuseppe** [comment]
@space88man that looks a different issue.

Could you please verify if the `NOTIFY_SOCKET` environment variable is defined in your session?

**Comment by space88man** [comment]
@giuseppe Fedora 31 terminal (as root and non-root) both do not have NOTIFY_SOCKET in the environment.

**Comment by space88man** [comment]
Sorry for the noise: my issue is was due to the existence of an upgraded package oci-systemd-hook from F30 to F31. This package prevents F31 podman from launching systemd based containers.

After removing it,  the cgroupv2-aware containers(F30,F31,CentOS 8) run and I get the same error as OP for older containers.

**Comment by giuseppe** [comment]
@lsm5 @rhatdan oci-systemd-hook is causing different issues on cgroups v2.  Should we change the  podman spec file to conflict with oci-systemd-hook?

**Comment by rhatdan** [comment]
We should obsolete it.  There are no users of oci-systemd-hook any longer.

**Comment by rhatdan** [comment]
@lsm5 @jnovy Could you guys obsolete oci-systemd-hook?

**Comment by rhatdan** [comment]
oci-systemd-hook no longer exists in Fedora 31/32

**Comment by rhatdan** [comment]
Added obsolet oci-systemd-hook
