### ISSUE TITLE
Off by one error in the docs for uidmap

### ISSUE THREAD

**Issue by leorochael** [containers/libpod#4239]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The documentation for `--uidmap` says:

> **--uidmap**=*container_uid:host_uid:amount*
> 
> Run the container in a new user namespace using the supplied mapping. This option conflicts with the --userns and --subuidname flags.
This option can be passed several times to map different ranges. If calling Podman run as an unprivileged user, the user needs to have the right to use the mapping. See `subuid(5)`.
The example maps uids 0-2000 in the container to the uids 30000-31999 on the host. `--uidmap=0:30000:2000`

But if the third parameter is `amount`, then the text should say:

> The example maps uids 0-1999 in the container to the uids 30000-31999 on the host: `--uidmap=0:30000:2000`

Right?

**Steps to reproduce the issue:**

1. Find the documentation for `podman run`

2. Look up the definition of `--uidmap`

3. Do some math :wink:

**Describe the results you received:**

In the documentation, it's confusing whether the end uid is included in the range or not.

**Describe the results you expected:**

Clarity regarding which UIDs are actually remapped.

**Output of `podman version`:**

Not relevant. Link to latest commit on master as of now:

https://github.com/containers/libpod/blob/5963077e93937046b6b13d6f1da8c1f932c0e6ff/docs/podman-run.1.md

**Comment by rhatdan** [comment]
Please open a PR to fix the documentation.

**Comment by leorochael** [comment]
Hi @rhatdan, thank you for the quick response.

I'd just like confirmation if my interpretation is correct and `--uidmap=0:30000:2000` should map uids 0 to 1999 in the container.

**Comment by rhatdan** [comment]
Yes you are correct.
