### ISSUE TITLE
A command to factory reset a Podman installation

### ISSUE THREAD

**Issue by debarshiray** [containers/libpod#4240]
/kind feature

**Description**

It would be helpful to have a way to factory reset a Podman installation to recover from situations when Podman is badly broken due to some bug. Perhaps, something like `podman system reset`.

Every now and then early adopters and testers of Podman have to do this. A command that encapsulates all the steps is easier to document, helps with user support, etc..

Some potential complications that can arise:
* ~/.local/share/containers can't be removed by a simple `rm -rf`. It needs `podman unshare` or `sudo`, and the former might not work if the breakage is bad enough.
* Detecting running `exec` sessions.

See https://github.com/containers/toolbox/pull/295 for an attempt to implement it in Toolbox.

**Comment by rhatdan** [comment]
We want this.  @QiWang19 PTAL

**Comment by tinmanjuggernaut** [comment]
New to dockers and podman. I've been setting up and blowing away dockers as I try setting them up. I manually erased my ~/.local/share/containers to reset everything because of all the wasted space from orphan images being created and duplicated space. Now that I'm setting up more dockers, my container list is always empty, even though when I try removing some images it says they're part of a container, though no container command will give any hint that there are any. A factory reset option would be helpful.

**Comment by rhatdan** [comment]
rm -rf ~/.config/containers ~/.local/share/containers
rm -rf /run/user/3267/overlay*

Would be the way to reset storage.

**Comment by tinmanjuggernaut** [comment]
Thanks.

**Comment by rhatdan** [comment]
I have begun work on this one

**Comment by debarshiray** [comment]
> rm -rf ~/.config/containers ~/.local/share/containers

Removing `~/.local/share/containers` either needs `sudo` on the host, or you need to enter the user namespace, because it has files owned by UIDs that aren't your UID on the host.

Not requiring the `sudo` access, or having to do the namespace dance manually, is one of the advantages of having a `reset` command. Remember, when things are really broken, you can't even rely on `podman unshare` to work.

**Comment by debarshiray** [comment]
> I have begun work on this one

Yay, thanks @rhatdan

**Comment by rhatdan** [comment]
This has been merged upstream

podman system reset

**Comment by gwd-at** [comment]
`podman system reset` gives `mkdir /run/user/1000: permission denied` in cases where I managed to mistreat podman and its configs (back and forth) in enough ways. 
up to the point of `podman info` output:  
```
mkdir /run/user/1000: permission denied
```
