### ISSUE TITLE
Podman `build --pull` vs docker behavior

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#4252]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind feature

**Description**

Podman `build --pull` right now behaves different compared to docker, which makes it hard to use as a drop-in replacement.

On docker, the `--pull` flags forces a re-pull of the image during build, whereas on podman it only specifies that the image has to be pulled if not present. I know that there is the `--pull-always` flag, but what is the intention of setting `--pull=false` on build? From my understanding this will fail always if the image is not available locally, right?

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert  this is a partial WIP  https://github.com/containers/buildah/pull/1873 on the Buildah side.   In short `podman --pull=false` fails currently if the image is not present locally.  It will not pull from the repo.  `docker --pull=false` tries to use the local image and then pulls from the repo if it's not present.  I've fixed that part of the equation in 1873 and added a `--pull-never` functionality to do the current  '--pull=false` functionality.  That is use local, and fail if not present (don't pull).

While going through that I also noticed that `podman --pull=true' and 'docker - -pull=true' were not in sync.   I'm trying to figure that one out now.

**Comment by saschagrunert** [comment]
> While going through that I also noticed that `podman --pull=true' and 'docker - -pull=true' were not in sync. I'm trying to figure that one out now.

Cool, thanks! I think it would be fine to have a more fine-granular option set for buildah, while podman sticks to the docker behavior, right? I don't see a big reason for having both, `--pull` and `--pull-always` flags in podman.

**Comment by TomSweeneyRedHat** [comment]
I think the `podman --pull=true/false` should match `docker --pull=true/false` functionality.  However, I think it's good the have the --pull-always and --pull-never functionality in both Podman and Buildah.  If folks want it they can use it, if not, it's easy to ignore.

**Comment by TomSweeneyRedHat** [comment]
@saschagrunert beat me to the punch as usual, but I want to leave a few breadcrumbs here.  https://github.com/containers/libpod/pull/4506 merged in Buildah 1.11.5 which contains https://github.com/containers/buildah/pull/1873 that fixes this, we now match Docker's pull functionality and have a litle bit extra in --pull-always and --pull-never

**Comment by saschagrunert** [comment]
Thanks @TomSweeneyRedHat ! :)
