### ISSUE TITLE
`podman start --attach` does not connect stdin by default

### ISSUE THREAD

**Issue by rohanlean** [containers/libpod#4259]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `podman create -ti --name nostdin busybox`

2. `podman start -a nostdin`

**Describe the results you received:**
Podman does not attach stdin.

**Describe the results you expected:**
Podman does attach stdin.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running `podman start -ai` instead works around this.

For version information see #4258.

**Comment by mheon** [comment]
I need to double-check against Docker, but I think the expected behavior is to set `-i` by default if the container was created with `-i`
