### ISSUE TITLE
in MacOS, podman 1.5.1 cli does not have a 'login' command

### ISSUE THREAD

**Issue by edmacabebe** [containers/libpod#4266]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**I intend to login to an image-registry in a codeready ocp4 in my laptop**

**Steps to reproduce the issue:**

1. podman login -u someuser my-registry:50000

**Describe the results you received:**
unrecognized command ...

**Describe the results you expected:**
Should login my terminal instance environment into an image-repository

**Output of `podman version`:**

```
Client:
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.2
OS/Arch:            darwin/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Comment by vrothberg** [comment]
Hi @edmacabebe, thanks for opening the issue. We're tracking this topic already in https://github.com/containers/libpod/issues/4039, so I'll close this PR. Feel free to join the conversation in https://github.com/containers/libpod/issues/4039.
