### ISSUE TITLE
`podman stats` is incompatible with Docker

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#4274]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman stats` requires containers to be specified while `docker stats` shows all running containers by default.

Also, the man page describes the behavior of Docker, not the current behavior of Podman.
https://github.com/containers/libpod/blob/7e238b9e0c650b20f1a325dad14ef94a3e7d1aab/docs/podman-stats.1.md

**Steps to reproduce the issue:**

`podman stats`

**Describe the results you received:**
`Error: you must provide at least one name or id` 

https://github.com/containers/libpod/blob/5f72e6ef2ef7b6941cefc3c655903aeacb53e115/cmd/podman/stats.go#L48
https://github.com/containers/libpod/blob/fd389d28ce2223550c82d809cbafa12a54e733e6/cmd/podman/common.go#L43-L63

**Describe the results you expected:**
Should show all running containers as in `docker stats`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version: 1.6.1
...
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @AkihiroSuda. I opened https://github.com/containers/libpod/pull/4275 to fix it.
