### ISSUE TITLE
Anonymous volume is incompatible with Docker

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#4276]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman run -v /var/lib` bind-mounts `/var/lib` while it should create an anonymous volume

**Steps to reproduce the issue:**
`podman run -v /var/lib` 

**Describe the results you received:**
It behaves as if `-v /var/lib:/var/lib` was specified

**Describe the results you expected:**
It should create a temporary anonymous volume, copy the content from `/var/lib` in the orignal image into the volume, mount the volume, and retain the volume until the container is removed.

**Output of `podman version`:**
1.6.1

**Comment by mheon** [comment]
I'll take this one
