### ISSUE TITLE
podman-remote for windows: "bash: varlink: command not found, Error: unable to get images: unexpected EOF"

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#4277]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I'm testing the podman-remote for windows msi. After the installation, run `podman images` on windows10 CMD, it looks like the connection can be successfully made, but failed with error message `bash: varlink: command not found`. It seems that only `podman --help` and `podman --version` can work on windows locally.

**Steps to reproduce the issue:**
On podman node - Fedora30:
1. build from scratch

2. pull an image

3. `systemctl start io.podman.socket`

On podman-remote windows10 node:
1. install the latest windows MSI from: https://storage.googleapis.com/libpod-master-releases/podman-remote-latest-master-windows-amd64.msi

2. run `podman images` on windows CMD 

**Describe the results you received:**
On podman-remote windows 10 node:
```
C:\Users\shenw>podman images
Please enter the remote hosts name or IP address: 10.73.2.3
Please enter the remote user name: root
root@10.73.2.3's password:
bash: varlink: command not found
Error: unable to get images: unexpected EOF
```

**Describe the results you expected:**
`podman images` on the remote node can successfully list the pulled image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
On podman linux(fedora30) node:
```
[root@dell-per630-03 conmon]# hostnamectl
   Static hostname: dell-per630-03.rhts.eng.pek2.redhat.com
         Icon name: computer-server
           Chassis: server
        Machine ID: ef208d04b76f4fd8ada64cfcdcbe1714
           Boot ID: 79f12d166d654bcf8cc1a0931402f4d9
  Operating System: Fedora 30 (Thirty)
       CPE OS Name: cpe:/o:fedoraproject:fedora:30
            Kernel: Linux 5.2.18-200.fc30.x86_64
      Architecture: x86-64
[root@dell-per630-03 conmon]# podman version
Version:            1.6.2-dev
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

On podman-remote windows 10 node:
```
C:\Users\shenw>podman --version
podman-remote-windows.exe version 1.6.2-dev
```

**Output of `podman info --debug`:**
On podman linux(fedora30) node:
```
[root@dell-per630-03 conmon]# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2-dev
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.3-dev, commit: bc758d8bd98a29ac3aa4f62a886575bfec0e39a1'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 29861572608
  MemTotal: 33622429696
  OCIRuntime:
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 16882069504
  SwapTotal: 16882069504
  arch: amd64
  cpus: 24
  eventlogger: journald
  hostname: dell-per630-03.rhts.eng.pek2.redhat.com
  kernel: 5.2.18-200.fc30.x86_64
  os: linux
  rootless: false
  uptime: 7h 43m 32.86s (Approximately 0.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
windows machine version: Windows 10 Home; verison1809

**Comment by jwhonce** [comment]
@Edward5hen Just to be clear, that package is installed on the linux server not the windows box.

**Comment by afbjorklund** [comment]
Are the other varlink packages available yet ? I'm still using the ones for fc29, couldn't find fc30...

https://copr-be.cloud.fedoraproject.org/results/@varlink/varlink/fedora-29-x86_64/

The one I was using was `fedora-varlink`, that had the config for the com.redhat.resolver etc.

It still doesn't work out of the box though, so had to patch in the podman configuration...

``` console
[root@db2343837355 ~]# varlink resolve org.varlink.resolver
unix:/run/org.varlink.resolver
[root@db2343837355 ~]# varlink resolve io.podman
Error resolving interface io.podman
```


```diff
# Enable podman in resolver
patch /usr/lib/fedora.json << EOF
--- fedora.json.orig	2018-11-11 14:24:43.022068639 +0100
+++ fedora.json	2018-12-07 22:34:24.658048674 +0100
@@ -50,6 +50,12 @@
       }
     },
     {
+      "address": "unix:/run/podman/io.podman;mode=0600",
+      "interfaces": [
+        "io.podman"
+      ]
+    },
+    {
       "address": "unix:/run/org.varlink.resolver;mode=0666",
       "interfaces": [
         "com.redhat.resolver",

EOF
```

```console
[root@db2343837355 ~]# varlink resolve io.podman
unix:/run/podman/io.podman;mode=0600
```

**Comment by Edward5hen** [comment]
After I install `libvarlink-util-0:18-1.fc30.x86_64` by `yum install -y libvarlink-util`, the windows remote node works as expected.

Do we have any doc for this point that indicates we have to install `libvarlink-util` before we use windows msi? I didn't find it. If not, it might be better adding it in the podman-remote documentation.

**Comment by vrothberg** [comment]
@jwhonce @baude PTAL

**Comment by baude** [comment]
the rpm spec for podman has the dep now.  so this should no longer happen.  closing as such.
