### ISSUE TITLE
Podman images are not compatible with docker hub

### ISSUE THREAD

**Issue by johanbrandhorst** [containers/libpod#4285]
/kind bug

**Description**

Building an image and pushing it to `docker.io` succeeds, but the tags do not show up in the docker hub web interface. Pulling from `podman` and some `docker` clients work, but is notably broken for docker 19.03: https://github.com/moby/moby/issues/39727.

This could well be a bug with docker hub, but nonetheless it's a problem for podman users, so we should track the progress on this.

**Steps to reproduce the issue:**

1. Build a container image with `podman`
1. Tag and push the image to docker hub.
1. Try to find the image tag on docker hub.

**Describe the results you received:**

I'm not seeing the tag on docker hub.

**Describe the results you expected:**

I expected to see my image tag.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4dc8bcfec41e10ca760c8e2089474c2843dfd066'
  Distribution:
    distribution: manjaro
    version: unknown
  MemFree: 675332096
  MemTotal: 16569847808
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9
      commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
      spec: 1.0.1-dev
  SwapFree: 18191396864
  SwapTotal: 18223570944
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: REDACTED
  kernel: 4.19.79-1-MANJARO
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.1
      commit: 4d38845e2e311b684fc8d1c775c725bfcd5ddc27
  uptime: 55h 15m 4.65s (Approximately 2.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/REDACTED/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/REDACTED/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 6
  RunRoot: /run/user/1000
  VolumePath: /home/REDACTED/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on bare metal (laptop).

**Comment by TomSweeneyRedHat** [comment]
@johanbrandhorst This looks to be an issue with dockerhub UI not supporting OCI images somehow.

I created a new image like this:
```
# podman pull docker://docker.io/tomsweeneyredhat/testing:first
# podman run testing:first ls -alF
# podman commit 0f0fdddb1183 docker.io/tomsweeneyredhat/testing:newtry
# podman push docker://quay.io/tomsweeneyredhat/testing:newtry
{No new 'newtry' tag on dockerhub ui for the image}
# podman rmi -a   # remove all local the images
# podman pull  docker://docker.io/tomsweeneyredhat/testing:newtry
Trying to pull docker://docker.io/tomsweeneyredhat/testing:newtry...
Getting image source signatures
Copying blob 14c1a220a43b done
Copying blob 910d8f35ad8e done
Copying blob 3eebc3ebaf68 done
Copying config 0ddf431f98 done
Writing manifest to image destination
Storing signatures
0ddf431f98354d6069430a8dcd7b2137bf749b98e138906103eed7d633c6c258
```
so although the tag isn't listed on the dockerhub ui, it appears to be there.  If I use skopeo to inspect the repo I can see newtry:
```
# skopeo inspect docker://docker.io/tomsweeneyredhat/testing:newtry
{
    "Name": "docker.io/tomsweeneyredhat/testing",
    "Digest": "sha256:8d3c1937b2cfb0714653068a9d6ba3196b9174c522cf76fa135bcfad08102205",
    "RepoTags": [
        "first",
        "fourth",
        "newtry",
        "second",
        "third",
        "try11.3"
    ],
    "Created": "2019-10-18T17:23:38.904949839Z",
    "DockerVersion": "",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:910d8f35ad8e06f02edaf13bfe509c4979fa01d16ff369aea7ff842a37573e6c",
        "sha256:14c1a220a43bb113ac877e430d9654adca7e25134d6775bb9cc1ae032e733e3d",
        "sha256:3eebc3ebaf685783de37067d871365271a5f75725b7faf28f5a737d2a6a86ff5"
    ]
}
```
Or I can change the format of the container from OCI to Docker like this:
```
# podman commit --format=docker d5af7f8ff795 docker.io/tomsweeneyredhat/testing:newtry2
```
and after pushing, the tag is displayed on the dockerhub ui.   If I do this to quay.io instead of docker.io, it all works fine.

@vrothberg, I seem to recall you had looked into this recently for another PR.  This is using Buildah v1.11.3 and Podman v1.6.2.  Did you find differently or tweak something to help dockerhub?

@rhatdan, other thoughts?

@johanbrandhorst after pushing the new tag, are you able to pull it even though it's not listed in the dockerhub ui?

**Comment by johanbrandhorst** [comment]
Pulling does indeed work. Thanks for the `podman commit --format` tip. I suspected this would be a docker hub issue.

**Comment by rhatdan** [comment]
Please open an issue with them for better support of OCI images.

**Comment by TomSweeneyRedHat** [comment]
@johanbrandhorst thanks for the confirmation of the pull of the image and for the issue and discussion afterwards.

**Comment by johanbrandhorst** [comment]
Hub issue: https://github.com/docker/hub-feedback/issues/1871. Do we want to keep this open to track that issue?

**Comment by vrothberg** [comment]
> @vrothberg, I seem to recall you had looked into this recently for another PR. This is using Buildah v1.11.3 and Podman v1.6.2. Did you find differently or tweak something to help dockerhub?

I didn't perform any change for Docker Hub precisely. There were a couple of reports from a few weeks ago with very similar symptoms. Though, I thought they have already been fixed on Docker Hub.

**Comment by TomSweeneyRedHat** [comment]
@johanbrandhorst I'm fine with leaving this issue open until the smoke settles with the issue you've put up at docker/hub

**Comment by mheon** [comment]
I continue to see reports of issues with OCI images and Dockerhub

**Comment by fedelibre** [comment]
I have the same problem.

I'm working on a CI set up for an open source project.
Do you know any alternative free as in beer registry? quay.io has only a 30 day trial...

**Comment by TomSweeneyRedHat** [comment]
@fedelibre thanks for the note.
You should be able to create a free account on quay.io.  Granted it only gives you one private repository and (I think) unlimited public ones, so it's not production ready, but great for testing/playing.

Go to [quay.io](https://quay.io) and click on the "SIGN IN" link on the top right.  If by chance you're still logged in with a trial account that's going to expire, first logout before doing the sign in.

At the bottom of this page, click on the "Create Account" link.  Fill in the info, you'll need a unique e-mail from your other account, then click on "Create Free Account"

HTH

**Comment by johanbrandhorst** [comment]
Still an issue

**Comment by andrewhill93** [comment]
Still an issue. Just pushed an image using podman on CentOS 8 and it doesn't show anything in the DockerHub UI, but I can pull the image fine (and it shows that there have been image pulls)

**Comment by vrothberg** [comment]
I just tested and Docker Hub is now displaying OCI images correctly, so I am closing the issue.
