### ISSUE TITLE
config: wrong entry for runtime[s]

### ISSUE THREAD

**Issue by tobwen** [containers/libpod#4302]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
When specifying `--runtime` on a blank system (with no existing config files), there wrong value gets written to the config file.

**Steps to reproduce the issue:**
1. Install _podman_ and all other tools and libs as user under `/home/tobwen/podman/usr/local/` on a brand new VM.

2. Execute
```
/home/tobwen/podman/usr/local/bin/podman --log-level=debug --tmpdir /tmp/user/1000/libpod/tmp --conmon /home/tobwen/podman/usr/local/bin/conmon --network-cmd-path /home/tobwen/podman/usr/local/bin/slirp4netns --runtime /home/tobwen/podman/usr/local/bin/runc --storage-driver overlay --storage-opt "overlay.mount_program=/home/tobwen/podman/usr/local/bin/fuse-overlayfs" run hello-world 
```

3. Check `/home/tobwen/.config/containers/libpod.conf`

**Describe the results you received:**
(warning: this has been trimmed down for reasons)
```
runtime = "/home/tobwen/podman/usr/local/bin/runc"

[runtimes]
  runc = ["/usr/bin/runc", "/usr/sbin/runc", "/usr/local/bin/runc", "/usr/local/sbin/runc", "/sbin/runc", "/bin/runc", "/usr/lib/cri-o-runc/sbin/runc", "/run/current-system/sw/bin/runc"]
```

**Describe the results you expected:**
```
runtime = "runc"

[runtimes]
runc = [ "/home/tobwen/podman/usr/local/bin/runc" ]
```

**Output of `podman version`:**
```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
tobwen@pgsql:~/podman/usr/local/bin$ ./podman --tmpdir /tmp/user/1000/libpod/tmp info debug
Error: `podman system info` takes no arguments
tobwen@pgsql:~/podman/usr/local/bin$ ./podman --tmpdir /tmp/user/1000/libpod/tmp info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.5
  podman version: 1.6.3-dev
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/conmon
    version: 'conmon version 2.0.3-dev, commit: bc758d8bd98a29ac3aa4f62a886575bfec0e39a1'
  Distribution:
    distribution: debian
    version: "9"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    - container_id: 65537
      host_id: 1258512
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    - container_id: 65537
      host_id: 1258512
      size: 65536
  MemFree: 35587067904
  MemTotal: 38205444096
  OCIRuntime:
    name: runc
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 4e3701702e966b4258fbab5b92efa6418c5ae6c6
      spec: 1.0.1-dev
  SwapFree: 8586784768
  SwapTotal: 8586784768
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: pgsql
  kernel: 4.19.0-0.bpo.6-amd64
  os: linux
  rootless: true
  uptime: 29h 19m 13.88s (Approximately 1.21 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/tobwen/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/tobwen/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /tmp/user/1000
  VolumePath: /home/tobwen/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
n/a (built manually)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian 9 (64-bit) on VirtualBox 6 on Windows 10 on AMD 64

**Comment by giuseppe** [comment]
it looks like the expected behaviour.

You have specified `--runtime /home/tobwen/podman/usr/local/bin/runc` so that setting is written to the configuration file.

That is different than specifying `runc`, as when you specify an absolute path then exactly that executable will be tried.  If you specify the runtime by name, then Podman will try to find it at  the specified locations.

**Comment by tobwen** [comment]
Then `--help` might be wrong. It tells me to specify a path, not a name.
```
--runtime string            Path to the OCI-compatible binary used to run containers, default is /usr/bin/runc
```

So when a path gets specified at `--runtime`, `[runtimes]` shouldn't be written at all, since you cannot find _runc_ or _crun_ in there.

**Comment by rhatdan** [comment]
I thought the name could be a full path, if so shouldn't we record the full path that the user specified.

**Comment by tobwen** [comment]
Seems like it *can* ne a full path. I just thought, runtimes path should go under _[runtimes]_ to be able to switch between _runc_ and _crun_ by specifying a name.

**Comment by rhatdan** [comment]
Yes the runtimes are more for the distribution to sort of guess where the OCI runtimes are installed (In my opinion) But if the user tells you exactly where the OCI runtime is, I don't see the reason to have to search through for it.

**Comment by mheon** [comment]
`--runtime` also short-circuits the logic for the `[runtimes]` section of the config. If a path is given, it is assumed that you're overwriting the entire `[runtimes]` section with a path not present in it.

On these config merging issues: I would rather we give priority to https://github.com/containers/libpod/issues/4214 and focus on not requiring initial Podman setup to use an arcane set of flags to get the rootless config file in a good state.
