### ISSUE TITLE
Add packages for Ubuntu 19.10 distributions

### ISSUE THREAD

**Issue by Davio** [containers/libpod#4307]
/kind feature

**Description**
I'm currently running Pop! Os 19.10, which is based on Ubuntu 19.10 Eoan Ermine, but there is currently no repository for this version, see https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Steps to reproduce the issue:**

    Go to https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Describe the results you received:**
See that there are no packages for 19.10

**Describe the results you expected:**
Packages for Ubuntu 19.10

Side note: As 19.10 officially deprecates 19.04 support (or at least that's what I thought), 19.04 packages can be dropped eventually.

**Comment by lsm5** [comment]
I'm enabling ubuntu 19.10 on OBS along with debian, see: https://github.com/containers/libpod/issues/1742#issuecomment-555061785

**Comment by lsm5** [comment]
19.10 has been enabled now, see: https://github.com/containers/libpod/blob/master/install.md . Please re-open if any issues..
