### ISSUE TITLE
podman does not forward ipv6 ports

### ISSUE THREAD

**Issue by laolux** [containers/libpod#4311]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman does not forward ipv6 requests to the container, only ipv4.
Trying to make nginx available via ipv6 fails. Connecting from the host using [::1]:PORT fails, wheras connecting to the nginx server via [::1]:PORT from inside the container works. Also, connecting from the host using 127.0.0.1:PORT works. Connecting to the container vial ipv6 should work or it should be clearly documented that `--publish` only works for connections via ipv4.

**Steps to reproduce the issue:**

1. make a fresh fedora container with nginx installed

2. run container via `podman run --name nginx-static -t -a STDOUT -a STDERR -a STDIN --rm -p 8080:80/tcp  localhost/fednginximage bash`

3. inside the container run `/usr/sbin/nginx`

4. from the host, try to connect to the nginx server via both, `[::1]:8080` and `127.0.0.1:8080`

**Describe the results you received:**
Connecting from the host only works for `127.0.0.1:8080`, but fails for `[::1]:8080`

**Describe the results you expected:**
Connecting from the host should work for both cases.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  MemFree: 6668619776
  MemTotal: 16682893312
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 8407478272
  SwapTotal: 8407478272
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: notebook
  kernel: 5.3.6-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 3h 38m 52.24s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/podmanuser/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.4-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.4
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/podmanuser/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /tmp/1003
  VolumePath: /home/podmanuser/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal fedora 30

**Comment by AkihiroSuda** [comment]
A workaround for this issue is to run `socat` on the host

**Comment by rhatdan** [comment]
@AkihiroSuda @giuseppe Should we be running with slirp4netns -6 by default?

**Comment by AkihiroSuda** [comment]
It seems libslirp doesn't support forwarding IPv6 ports
https://gitlab.freedesktop.org/slirp/libslirp/blob/ad36c04a3ef961a2dbb6dc78dd5322318a7f10b6/src/slirp.c#L1001

Somebody should submit patches to libslirp upstream for supporting IPv6.

Or maybe podman can use RootlessKit's nsenter-based port forwarder which is simpler and faster.
(Used by Rootless Docker)

RootlessKit's port forwarder is untested with IPv6 either, but it should not be too difficult to support IPv6 if it doesn't work with IPv6.
https://github.com/rootless-containers/rootlesskit/tree/master/pkg/port/builtin

**Comment by laolux** [comment]
> Could you try running slirp4netns with `-6` option?
> 
> ```
> $ mv slirp4netns slirp4netns.orig
> $ cat > slirp4netns << EOF
> #!/bin/sh
> exec slirp4netns.orig -6 $@
> EOF
> $ chmod +x slirp4netns
> ```
> 
> (or simply recompile podman with modified source)

Thanks, I tried, but it did not help. Same result as before.

I tried the same with creating and running the container as root. That does not help either. So maybe remove the `rootless` label?

**Comment by AkihiroSuda** [comment]
> I tried the same with creating and running the container as root. That does not help either. So maybe remove the rootless label?

The result is same but the cause seems different. Could you open a separate issue for discussing rootful IPv6?

**Comment by rhatdan** [comment]
This is something we want, although no one is working on it at this time.

**Comment by rhatdan** [comment]
Have we determined if Docker forwards IPV6 ports?  I think we have determined that it did not, so nothing to fix here.   Am I correct @mccv1r0?

**Comment by mccv1r0** [comment]
That's my understanding as well.
