### ISSUE TITLE
podman does not forward ipv6 ports - podman as root

### ISSUE THREAD

**Issue by laolux** [containers/libpod#4323]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Note: This issue is about running podman as **root**.  It is very similar to #4311, but the cause seems to be different https://github.com/containers/libpod/issues/4311#issuecomment-545243940 

podman does not forward ipv6 requests to the container, only ipv4.
Trying to make nginx available via ipv6 fails. Connecting from the host using [::1]:PORT fails, wheras connecting to the nginx server via [::1]:PORT from inside the container works. Also, connecting from the host using 127.0.0.1:PORT works. Connecting to the container vial ipv6 should work or it should be clearly documented that `--publish` only works for connections via ipv4.

**Steps to reproduce the issue:**

1. make a fresh fedora container with nginx installed

2. run container via `podman run --name nginx-static -t -a STDOUT -a STDERR -a STDIN --rm -p 8080:80/tcp  localhost/fednginximage bash`

3. inside the container run `/usr/sbin/nginx`

4. from the host, try to connect to the nginx server via both, `[::1]:8080` and `127.0.0.1:8080`

**Describe the results you received:**
Connecting from the host only works for `127.0.0.1:8080`, but fails for `[::1]:8080`

**Describe the results you expected:**
Connecting from the host should work for both cases.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  MemFree: 6668619776
  MemTotal: 16682893312
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 8407478272
  SwapTotal: 8407478272
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: notebook
  kernel: 5.3.6-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 3h 38m 52.24s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/podmanuser/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.4-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.4
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/podmanuser/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /tmp/1003
  VolumePath: /home/podmanuser/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal fedora 30

**Comment by mheon** [comment]
@baude is looking into this one

**Comment by rhatdan** [comment]
I believe that the CNI guys say this is the right behaviour?  Should we close?

**Comment by mheon** [comment]
I think we need to positively verify if recent Docker does forward v6 ports before we close definitively

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by rhatdan** [comment]
Closing, reopen if we find that Docker does this.

**Comment by NMi-ru** [comment]
> Closing, reopen if we find that Docker does this.

docker-1.13.1-108 on CentOS7 works with IPv6 by default.

docker-compose.yml excerpt:
  ports:
    - "10051:10051"

ss -anp | grep 10051:
tcp    LISTEN     0      128    [::]:10051              [::]:*                   users:(("docker-proxy-cu",pid=4697,fd=4))

**Comment by mheon** [comment]
That's just a proxy service holding the port open so it can't be used by any applications on the host - is it actually adding rules to forward them? `ip6tables -nvL` and `ip6tables -t nat -nvL` would help.

**Comment by NMi-ru** [comment]
> is it actually adding rules to forward them? `ip6tables -nvL` and `ip6tables -t nat -nvL` would help.
Nope. 4tables contains only default "CNI firewall plugin rules" for 10.88/16, ip6tables is empty.

I've managed to implement a fix using xinetd binding to specific ipv6 address + "redirect = 127.0.0.1 443".

**Comment by aquasync** [comment]
I believe docker does do IPv6 by default. My test case:

```
$ sudo podman run -d --rm -p 10030:1080 --name=socks5 serjs/go-socks5-proxy
$ curl -s --socks5-hostname [::1]:10030 https://www.google.com | wc 
curl: (7) Failed to connect to ::1 port 10030: Connection refused
      0       0       0
```

Versus:

```
$ sudo docker run -d --rm -p 10030:1080 --name=socks5 serjs/go-socks5-proxy
$ curl -s --socks5-hostname [::1]:10030 https://www.google.com | wc 
     14     352   13894
```

In my case this was the underlying problem with an issue I've been debugging. I have two Ubuntu 20.04 server installs, and switching from docker to podman was failing on one - turned out one had `::1` included for localhost in /etc/hosts, causing downstream failures due to the above.

**Comment by aquasync** [comment]
Comparing the `ss -anp` output between the two, the difference is docker's is bound to `*:10030`, vs podman's `0.0.0.0:10030`.

**Comment by rhatdan** [comment]
Please open a new issue.
