### ISSUE TITLE
allow amending/changing --subuidname (and --subgidname) with --uidmap (resp --gidmap)

### ISSUE THREAD

**Issue by ibotty** [containers/libpod#4324]
/kind feature

## Description

It would be great to be able to allow a container to run with the privileges of a given user (using --subuidname and --subgidname) but allow mapping some uids and gids differently.

I envision that for `myuser` with uid `1002` and subuid `myuser:231072:65536` the following would work.

```
# sudo podman run --subuidname myuser --uidmap 0:1002:1 ubi8 cat /proc/self/uid_map
         0       1002          1
         1     231072      65536
```

(Of course it would be great to allow name resolution in second position of --uidmap as well, so that --uidmap 0:myuser:1 works.)

**Comment by rhatdan** [comment]
Why would this be better then
```
sudo -u dwalsh /usr/bin/podman run fedora cat /proc/self/uid_map 
         0       3267          1
         1     100000      65536
```

**Comment by ibotty** [comment]
It shares the host's container storage and allows using different CNIs.  There are other differences you will certainly be aware of more than I am.

**Comment by rhatdan** [comment]
Ok so you just want to run the system containers with a users user-namespace 

I think we would want to be easier then this.

podman run  --uidmap myuser ubi8 cat /proc/self/uid_map
         0       3267          1
         1     100000      65536

Where it would see that uidmap is a user and would look up the users UID and the users map and use them.

@giuseppe @mheon @baude WDYT?

Would be fairly easy to implement.

**Comment by ibotty** [comment]
That's great and enough for one use case.  But consider typical s2i images that run as user 1000 (or any other non-root). It would be great to be able to map this id instead.  Maybe it ought to map the configured user?

**Comment by rhatdan** [comment]
So podman has an alternative method --userns keep-id  Which basically remaps the UIDs inside of your user namespace so that UID 0 == 100000 and UID 3267==3267


```
$ podman run --userns keep-id ubi8 cat /proc/self/uid_map
         0          1       3267
      3267          0          1
      3268       3268      62269

$ podman run --userns keep-id ubi8 id 
uid=3267(3267) gid=3267 groups=3267,65534(nobody)
```

**Comment by ibotty** [comment]
I know about that option.  I hope to be proven wrong, but using --userns keep-id does not allow running a "system container" (i.e. root podman's CNI).

I would propose that the hypothetical  `--uidmap myuser` maps container's USER (as in Dockerfile) to the host's myuser and lays the subuid-mapping around.  (So with USER=0 it corresponds to your proposal).

I like what that sounds like.

**Comment by rhatdan** [comment]
Yes it is only for non root use case for now.  But If this is something you see as useful, then I believe we would consider a PR that implements it.

I am just trying to get get your exact requirements.

**Comment by ibotty** [comment]
I see.  Thank you for being so responsive (as usual!).  Right now I am using a script that sets --uidmap options to get what you proposed in [your answer above](https://github.com/containers/libpod/issues/4324#issuecomment-545632936).

**Comment by giuseppe** [comment]
we could extend `--subuidname` to also accept an OFFSET where these IDs are mapped: `--subuidname myuser[:OFFSET]`, something like:

```
diff --git a/pkg/util/utils.go b/pkg/util/utils.go
index d9a84e4e..a49da2f1 100644
--- a/pkg/util/utils.go
+++ b/pkg/util/utils.go
@@ -6,6 +6,7 @@ import (
        "path/filepath"
        "regexp"
        "strings"
+       "strconv"
        "sync"
        "time"
 
@@ -251,12 +252,38 @@ func ParseIDMapping(mode namespaces.UsernsMode, UIDMapSlice, GIDMapSlice []strin
        }
 
        if subUIDMap != "" && subGIDMap != "" {
-               mappings, err := idtools.NewIDMappings(subUIDMap, subGIDMap)
+               subUIDMapParts := strings.Split(subUIDMap, ":")
+               if len(subUIDMapParts) > 2 {
+                       return nil, errors.New("invalid value for subuidmap")
+               }
+               subGIDMapParts := strings.Split(subGIDMap, ":")
+               if len(subGIDMapParts) > 2 {
+                       return nil, errors.New("invalid value for subgidmap")
+               }
+               mappings, err := idtools.NewIDMappings(subUIDMapParts[0], subGIDMapParts[0])
                if err != nil {
                        return nil, err
                }
                options.UIDMap = mappings.UIDs()
                options.GIDMap = mappings.GIDs()
+               if len(subUIDMapParts) > 1 {
+                       off, err := strconv.Atoi(subUIDMapParts[1])
+                       if err != nil {
+                               return nil, err
+                       }
+                       for i := range(options.UIDMap) {
+                               options.UIDMap[i].ContainerID = options.UIDMap[i].ContainerID + off
+                       }
+               }
+               if len(subGIDMapParts) > 1 {
+                       off, err := strconv.Atoi(subGIDMapParts[1])
+                       if err != nil {
+                               return nil, err
+                       }
+                       for i := range(options.GIDMap) {
+                               options.GIDMap[i].ContainerID = options.GIDMap[i].ContainerID + off
+                       }
+               }
        }
        parsedUIDMap, err := idtools.ParseIDMap(UIDMapSlice, "UID")
        if err != nil {
```

that will allow you do to as root:

```
$ grep gscrivano /etc/subuid
gscrivano:110000:65536

$ sudo podman run --rm --uidmap 0:1000:1  --subuidname gscrivano:1  alpine cat /proc/self/uid_map
         1     110000      65536
         0       1000          1
```

That will leave room for your custom `--uidmap`.

For more complex cases, it is always possible to use directly `--uidmap` and avoid completely `--subuidname`.

**Comment by rhatdan** [comment]
@ibotty @giuseppe is this something we should go forward with?

**Comment by giuseppe** [comment]
> @ibotty @giuseppe is this something we should go forward with?

I'd just expect the users to provide the correct mappings.  There are so many ways to tweak these intervals, that I don't think we should try to fit into `--subuidname`

**Comment by rhatdan** [comment]
Ok so maybe this is a documentation issue, explaining how to do this?  Perhaps a blog?
