### ISSUE TITLE
cgroup V2 with podman running older systemd containers is broken.

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#4327]
This is reported in a bugzilla here.

https://bugzilla.redhat.com/show_bug.cgi?id=1760645

The systemd guys pointed out how they have worked around the issue.

```
cgroupv2 support was added in systemd-230. centos7 has systemd-219, so no
support.

What we do in systemd-nspawn is check the guest to guess if it supports
cgroupsv2.
If it has systemd >= 230, it does. See
https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L445-L480.
If the guest has no support for v2, we try to mount v1. This is not very
elegant,
but we couldn't come up with an approach that would allow us to use cgroupv2,
but not break old images.
```

**Comment by rhatdan** [comment]
@giuseppe could you look into fixing this?

**Comment by giuseppe** [comment]
I've looked into this, it requires changes in the OCI runtime as well as in Podman.  So we need to add an extension to the OCI specs.

It seems that on a cgroups v2 host it is possible to mount only controllers that are not already used by cgroups 2, so we will be able to mount only the named systemd hierarchy.

**Comment by rhatdan** [comment]
This is not something we can fix, so closing.
