### ISSUE TITLE
Error in setting path on windows

### ISSUE THREAD

**Issue by CaselIT** [containers/libpod#4335]
I've installed the "Latest remote client for Windows"  tried it and uninstalled.

After uninstalling it the user path on my machine is left to `%PATH%;C:\Program Files (x86)\RedHat\Podman"` (in the registry under `HKEY_CURRENT_USER\Environment`) which causes problems both because I no longer have the paths set on my user path and because the `"` left in the path causes problems with other scripts

I'm not sure if the error happened during install or uninstall, if it is podman that causes it or the installer used on windows (it is the only new application I installed before having this problem), but it may be worth looking into it.

Thanks

Edited to add the reference to the registry

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by Zhappa** [comment]
@rhatdan @jwhonce I got this issue in https://github.com/containers/podman/releases/tag/v3.3.1 release.
Now i even can't remove this stuff from PATH, i don't know where it is defined (there is nothing in PATH configuration about it).
I tried remove PODMAN - nothing changed, this line still in PATH. Kinda ruined my work morning :(

**Comment by CaselIT** [comment]
I think I had to remove it from the registry entry? I honestly don't remember, sorry
