### ISSUE TITLE
Podman doesn't use auth in ~/.docker/config.json correctly

### ISSUE THREAD

**Issue by yihuaf** [containers/libpod#4357]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling from azure container registry, `docker pull` is successful whereas `podman pull` fails. Auth information is located under `~/.docker/config.json`. Podman documentation on `pull` specifies that if no `auth.json` file is found, then  `~/.docker/config.json` is used.

**Steps to reproduce the issue:**

1. az acr login

2. podman pull <images>

**Describe the results you received:**

 unable to retrieve auth token: invalid username/password

**Describe the results you expected:**

Pull successful

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
[yihuaf@localhost km]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.9
  podman version: 1.6.1
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.1-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 4346fbe0b2634b05857973bdf663598081240374'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 2509381632
  MemTotal: 16482402304
  OCIRuntime:
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 7904391168
  SwapTotal: 8308912128
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.2.16-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 741h 40m 51.26s (Approximately 30.88 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: $HOME/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.4-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.4
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: $HOME/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 9
  RunRoot: /run/user/1000
  VolumePath: $HOME/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local fedora 30 box.

**Comment by rhatdan** [comment]
Could you try --authfile=""
If you do a `podman login`, does everything work?

**Comment by rhatdan** [comment]
@QiWang19 I think removing the default from the options will fix this issue.

**Comment by yihuaf** [comment]
`--authfile=""` doesn't seem to work. Should I try converting .docker/config.json into a authfile? Is there a doc on the format of the authfile? I can't seem to find it.

Will try podman login a bit. Azure is a bit pain to use docker/podman login directly. Their CLI is hardcoded wrapper to docker login.

**Comment by TomSweeneyRedHat** [comment]
The authfile and the .docker/config.json file should have the same format.  I've created #4359 to find or fix that part of the doc up.  I would have expected to find that info on the podman-login/logout pages or at least a pointer to it from there.

**Comment by yihuaf** [comment]
If it's the same format, then `--authfile` is not being used at all, it seems. When pointing the authfile to `.docker/config.json`, from the log:

`DEBU[0000] Credentials not found`

**Comment by QiWang19** [comment]
@yihuaf Can you check your credentials exists in ~/.docker/config.json? I dailed to replica this issue with my plain text JSON format credential in ~/.docker/config.json.
Azure doc mentioned the token used by az acr login is valid for 1 hour, maybe it has been wiped out?

**Comment by yihuaf** [comment]
Then that doesn't explain why `docker pull` is successful. I also just tried with a fresh `az acr login` to make sure.

Here is the debug log if that helps.
```
[yihuaf@localhost ~]$ sudo podman --log-level=debug pull kontainkubecr.azurecr.io/test-node-fedora:for_novdemo
DEBU[0000] using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is being used 
DEBU[0000] cached value indicated that native-diff is not being used 
WARN[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.mountopt=nodev,metacopy=on]kontainkubecr.azurecr.io/test-node-fedora:for_novdemo" 
Trying to pull kontainkubecr.azurecr.io/test-node-fedora:for_novdemo...
DEBU[0000] reference rewritten from 'kontainkubecr.azurecr.io/test-node-fedora:for_novdemo' to 'kontainkubecr.azurecr.io/test-node-fedora:for_novdemo' 
DEBU[0000] Trying to pull "kontainkubecr.azurecr.io/test-node-fedora:for_novdemo" 
DEBU[0000] Credentials not found                        
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for kontainkubecr.azurecr.io/test-node-fedora:for_novdemo 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/kontainkubecr.azurecr.io 
DEBU[0000] GET https://kontainkubecr.azurecr.io/v2/     
DEBU[0000] Ping https://kontainkubecr.azurecr.io/v2/ status 401 
DEBU[0000] GET https://kontainkubecr.azurecr.io/oauth2/token?scope=repository%3Atest-node-fedora%3Apull&service=kontainkubecr.azurecr.io 
DEBU[0000] Error pulling image ref //kontainkubecr.azurecr.io/test-node-fedora:for_novdemo: Error initializing source docker://kontainkubecr.azurecr.io/test-node-fedora:for_novdemo: unable to retrieve auth token: invalid username/password 
  unable to retrieve auth token: invalid username/password
ERRO[0000] error pulling image "kontainkubecr.azurecr.io/test-node-fedora:for_novdemo": unable to pull kontainkubecr.azurecr.io/test-node-fedora:for_novdemo: unable to pull image: Error initializing source docker://kontainkubecr.azurecr.io/test-node-fedora:for_novdemo: unable to retrieve auth token: invalid username/password 
```
Same log with adding `--authfile=""`.

**Comment by rhatdan** [comment]
Could you try --authfile=~/.docker/config.json
To see if it reads it then?

**Comment by yihuaf** [comment]
It doesn't seem to read the file it all. It also doesn't complain if the file does not exist or is in bad format.

**Comment by yihuaf** [comment]
Like: `docker.io.qiwanredhat.azurecr.io/hello-world:v1`? That doesn't seem to work.

Is identitytoken something specific to azurecr?

**Comment by TomSweeneyRedHat** [comment]
I don't think the azure registry has made the auth file different, I think Docker upstream may have.  I'm running Docker
```
# docker version
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.13beta1
 Git commit:        0dd43dd
 Built:             Fri Jul 26 03:04:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```
and my Podman auth file which used to look like Docker's earlier versions looks like:
```
# cat /run/user/0/containers/auth.json
{
	"auths": {
		"docker.io": {
			"auth": "dG....="
		}
	}
```
But as @QiWang19 pointed out, the Docker authfile now looks like:
```
# cat ~/.docker/config.json
{
	"auths": {
		"": {
			"auth": "dG....="
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.8 (linux)"
	}
}
```

So rather than the repo host, `docker.io`, it appears docker has blanked that out.  If I `docker login quay.io`, it adds that in ala:

```
# cat ~/.docker/config.json
{
	"auths": {
		"": {
			"auth": "dG....="
		},
		"quay.io": {
			"auth": "dG....="
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.8 (linux)"
	}
}
```

If that field is missing in the auth, we might be able to fill it in with 'docker.io', but that's kind of hacky.  @mtrmac any thoughts?

**Comment by TomSweeneyRedHat** [comment]
@yihuaf as an experiment, can you modify your `~/.docker/config.json` and put `docker.io` between the two `""` by the auth stanza and see if that works for you?

**Comment by QiWang19** [comment]
> Like: `docker.io.qiwanredhat.azurecr.io/hello-world:v1`? That doesn't seem to work.
> 
> Is identitytoken something specific to azurecr?

No.
I mean from the error mesage fof podman . Podman is trying `docker://qiwanredhat.azurecr.io` which doesn't work.
I haven't found a way to pull from azurecr.io successfully.
```
Error initializing source docker://qiwanredhat.azurecr.io/hello-world:v1: unable to retrieve auth token: invalid username/password
```

**Comment by mtrmac** [comment]
The `""` thing seems entirely unrelated to what @yihuaf has reported (the contents in https://github.com/containers/libpod/issues/4357#issuecomment-547628643 don’t contain that, at least).

The `identitytoken` field might be the actual cause, also mentioned in https://github.com/containers/skopeo/issues/533 . Apparently that requires adding a (variant of?) OAuth2 support.

**Comment by yihuaf** [comment]
The issue https://github.com/containers/skopeo/issues/533 describes the same issue in fact. However, I don't see any issue in containers/image repo to track this. Should we file an issue in containers/image to get this resolved, perhaps referencing this issue and https://github.com/containers/skopeo/issues/533?

**Comment by rhatdan** [comment]
SGTM

**Comment by yihuaf** [comment]
@rhatdan https://github.com/containers/image/issues/748 filed. Thanks.

**Comment by MartinPotier** [comment]
Bumped into this problem today as well

**Comment by Asgoret** [comment]
Doesn't resolved.
```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 03:00:00 1970
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
Please try again with Podman 3.0.

**Comment by Asgoret** [comment]
@mheon well...
```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
Error: Cannot connect to the Podman socket, make sure there is a Podman REST API service running.: vfs driver does not support overlay.mount_program options
```

**Comment by Asgoret** [comment]
@mheon Upgrade podman to 3.0.0 version and still `podman login` doesn't store any data in `~./docker/config.json`

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
Why would podman write to a file owned by Docker?  ~/docker/config.json. 
The podman man page says that podman will store data in:${XDG_RUNTIME_DIR}/containers/auth.json.
for rootless containers.  Podman tools will use this file, and will fall back to use ~/docker/config.json if a user had done
`docker login` in the past.

```
man podman login
       podman  login logs into a specified registry server with the correct username and password. If the registry is not specified, the first registry under [registries.search] from registries.conf will be used. podman login reads in the username and password from
       STDIN.  The username and password can also be set using the username and password flags.  The path of the authentication file can be specified by the user by setting the authfile flag. The default path  for  reading  and  writing  credentials  is  ${XDG_RUN‐
       TIME_DIR}/containers/auth.json.  Podman will use existing credentials if the user does not pass in a username.  Podman will first search for the username and password in the ${XDG_RUNTIME_DIR}/containers/auth.json, if they are not valid, Podman will then use
       any existing credentials found in $HOME/.docker/config.json.  If those credentials are not present, Podman will create ${XDG_RUNTIME_DIR}/containers/auth.json (if the file does not exist) and will then store the username and password from STDIN as  a  base64
       encoded string in it.  For more details about format and configurations of the auth.json file, please refer to containers-auth.json(5)
```

**Comment by fuomag9** [comment]
My `${XDG_RUNTIME_DIR}/containers/auth.json` randomly disappears, is that normal?

**Comment by matejvasek** [comment]
> My `${XDG_RUNTIME_DIR}/containers/auth.json` randomly disappears and I need to keep logging in, is that normal?

The XDG_RUNTIME_DIR directory may be put on tmpfs meaning it will disappears on reboot.

**Comment by matejvasek** [comment]
@fuomag9 https://github.com/containers/podman/issues/12706

**Comment by fuomag9** [comment]
My `$XDG_RUNTIME_DIR` points to `/run/user/1000` which does indeed appear to be a tmpfs, shouldn't podman chose a different folder for saving credentials? e.g. `~/.config`

**Comment by matejvasek** [comment]
@fuomag9 see the referenced issue #12706
