### ISSUE TITLE
Document the authfile contents, most likely in podman login.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#4359]
We don't seem to have documented the contents of an authfile, at least I can't find it quickly.  I'll look further, but I thought I'd create this issue as a place holder.

We probably should have some documentation in the podman-login/logout man pages, or links to it from those man pages.

**Comment by TomSweeneyRedHat** [comment]
Problem first noted in #4357, @umohnani8 do you recall documenting the contents of the authfile somewhere in the past?

**Comment by TomSweeneyRedHat** [comment]
@yihuaf FYI

**Comment by vrothberg** [comment]
Since the logic is implemented over there, containers/image could be a good host for such docs (e..g, `containers-authfile(5)`) which can then be cross-referenced here and in buildah.

**Comment by rhatdan** [comment]
Yes lets put the docs into containers/image

**Comment by umohnani8** [comment]
@TomSweeneyRedHat by contents you mean what exactly is in the authfile? From what I remember, podman login will add the credentials to either the default location of authfile or whatever the user sets the location to be with the `--authfile` flag.
When checking for credentials, e.g when doing a podman pull, it will first check the authfile location, if the creds are not found there it checks the docker one. We never store the creds in docker file when doing a podman login. 
The man page is all the documentation I remember doing.
The authfile format should match the docker one.

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 thanks for the info.  Yep, the reporter was asking for what the contents of the file looked like.  I thought we had added a dummy sample in some man page, but I guess we'd not.  It would be nice to have that specified somewhere.  I'm fine if this moves to c/image and then we just add a note in the podman login/logut pages to look there for more details.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Could you work on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Any movement on this?

**Comment by TomSweeneyRedHat** [comment]
Not yet, but lets keep it around.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Reminder that you have this one outstanding.

**Comment by TomSweeneyRedHat** [comment]
Closed via: https://github.com/containers/image/pull/821
