### ISSUE TITLE
cgroupns=private should be enabled by default for unified mode?

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#4363]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature (?)

**Description**

In Moby (cgroup v1), cgroupns is not used by default because it was not available in the kernel until kernel 4.6 (May 2016), and the default behavior will not change on cgroup v1 environments, because changing the default will break compatibility and surprise users.

Podman seems to have followed this behavior for both cgroup v1 mode and v2 mode.

But for cgroup v2, I'm wondering both Moby and Podman should switch to enable cgroupns by default.
As the migration to cgroup v2 is already breaking compatibility, there is no reason to hesitate enable cgroupns by default?

**Comment by mheon** [comment]
I'm generally in favor, though ideally I'd like a config option to allow it
to be switched to off by default by users and distros.

**Comment by rhatdan** [comment]
I agree we need to add a flag to disable it.
 Lets turn this on ASAP.
@AkihiroSuda Interested in open a PR?

**Comment by giuseppe** [comment]
> I agree we need to add a flag to disable it.

from the CLI, it can be disabled with `--cgroupns=host`, but we miss a way to configure namespaces from the config file.

Not sure that should be a blocker though.  Changing the default should not matter for most users, I've already verified that containers  with systemd as payload work fine.

**Comment by mheon** [comment]
I'm fine with changing the default now as long as we add the config option
once we can

**Comment by rhatdan** [comment]
Yes lets add the option and I will have @QiWang19 Add the config to containers-conf PR, when we start doing Podman.

**Comment by giuseppe** [comment]
opened a PR here to change the default value: https://github.com/containers/libpod/pull/4374

**Comment by lio24** [comment]
deploiement container  avec linux ou ubuntu colonial
