### ISSUE TITLE
[macOS] Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory

### ISSUE THREAD

**Issue by amitkrout** [containers/libpod#4364]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. $ brew cask install podman

2. $ podman pull ubuntu

3. 

**Describe the results you received:**
```
$ podman pull ubuntu
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Describe the results you expected:**
should not throw runtime error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64

Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
$ podman info --debug
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by amitkrout** [comment]
@rhatdan It would be really helpful if share some kind of doc reference of what you suggest

**Comment by ssbarnea** [comment]
Did you managed to get a signed podman, my testing of podman got stuck at https://github.com/containers/libpod/issues/4511

**Comment by ag1989** [comment]
> Did you managed to get a signed podman, my testing of podman got stuck at #4511

Nope, still not properly signed...

**Comment by amitkrout** [comment]
> > Did you managed to get a signed podman, my testing of podman got stuck at #4511
> 
> Nope, still not properly signed...

FYI... In case you are using ```macOS Catalina```
https://developer.apple.com/news/?id=09032019a

**Comment by zekaguilar** [comment]
Hi, I've got stuck here too, any draft to share @jwhonce  ?
Thanks !

**Comment by MrBuddyCasino** [comment]
Would be interested in how to get podman running on macOS, too. Any hints?

**Comment by guiguir68** [comment]
Same problem here. Waiting for you @jwhonce :)

podman version 1.6.1-dev (installed with brew cask)
macOS Catalina 10.15.1

**Comment by sachingorade** [comment]
> @jwhonce is preparing such a document now.

Please post the link if its partially done too (to at least get podman working :) )

Thanks.

**Comment by misanche** [comment]
waiting the document too :)

**Comment by jwhonce** [comment]
I don't have access to Catalina, so these are my best guesses until I do:

# xattr -d com.apple.quarantine /usr/local/bin/podman
- or -
# xattr -d com.apple.quarantine `readlink /usr/local/bin/podman`

should get you over the signing issue.  Then setting PODMAN_VARLINK_BRIDGE to point to your linux server.

export PODMAN_VARLINK_BRIDGE=$'ssh -T -p22 root@localhost -- "varlink -A \'podman varlink \$VARLINK_ADDRESS\' bridge"'

Note that in the above example the macos user has provided the linux server with their ssh public key for access without a password. And yes, varlink is called twice. Once, for the ssh-tunnel the other is doing the actual work. I hope this helps.

**Comment by sayboras** [comment]
can we have some steps before the official docs ?

**Comment by zhuguoliang** [comment]
Got stuck here too

> Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64
Service:
Error: could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory

**Comment by lokinell** [comment]
I have the same problem.

**Comment by ssbarnea** [comment]
I can give ssh access to a MacOS Catalina with latest xcode and homebrew if any libpod developer  for debugging libpod building. 

I suspect that building podman for macos will be a real struggle if we build inside a linux vm code that later runs on macos. I bet is not possible to sign that binaries from within the linux vm.

**Comment by davinkevin** [comment]
The same problem for me on a fresh macOS Catalina install with only Podman installed (with `brew cask`). 

Very sad to not be able to replace the docker-cli with it now...

**Comment by andreufontb** [comment]
The macOS catalina filesystem is mounted in a readonly partition. It looks like podman is triyng to set run time in this partition. 

> $ sudo mkdir -p /run/podman
mkdir: /run/podman: Read-only file system

Installing version 1.6.3 i get a more 
> Client:
Version:            1.6.3-dev
RemoteAPI Version:  1
Go Version:         go1.12.10
Git Commit:         6c6e78374f5be949d11a8608080c96e2d22ca872
Built:              Tue Oct 29 20:08:11 2019
OS/Arch:            darwin/amd64
>
> Service:
> Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: no such file or directory

**Comment by rhatdan** [comment]
Podman expects /run to be mounted as a tmpfs and be writeable.

**Comment by afbjorklund** [comment]
It also expects it to contain a unix socket, which it probably wont.

Exposing the socket file from the VM to the Mac host is a big hassle...
Docker does this [*](https://docs.docker.com/docker-for-mac/docker-toolbox/), but I'm not sure that Podman has the same need.

Probably easier to just use the varlink protocol (over ssh) instead ?

Seems like the original root cause is the missing environment variables.
Without the remote config, it will assume it is running on a Linux host.

It needs the `PODMAN_VARLINK_BRIDGE` set up

For instance: podman-machine env --varlink

**Comment by afbjorklund** [comment]
@jwhonce : did you complete any docs, on how to set up the Linux virtual machine ?

Here is one link that I found: https://medium.com/@bszeti/podman-and-skopeo-on-macos-1b3b9cf21e60

It uses VirtualBox, to create a Fedora VM and then install ssh and podman packages.

Similar to this setup: https://podman.io/blogs/2019/01/14/podman-machine-and-boot2podman.html

**Comment by ipbabble** [comment]
@amitkrout  I followed the instructions here and got it to work:
https://github.com/containers/libpod/blob/master/docs/tutorials/remote_client.md

But FYI export that env var for the link. I'm not sure why the doc shows it the way it does.

**Comment by jwhonce** [comment]
@ipbabble https://github.com/containers/libpod/pull/4997 updates the documentation for setting up the varlink bridge.

**Comment by vrothberg** [comment]
@jwhonce, is this issue resolved with the latest updates to the docs?

**Comment by ahmetb** [comment]
I hate to say I came here with exact same problem after reading website and poking through the CLI for 15 minutes.

Can someone please update `podman.io` homepage to say:

> Podman only works on Linux, however a remote Linux machine can be configured from macOS and Windows to use Podman on other platforms.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat WDYT?

**Comment by TomSweeneyRedHat** [comment]
Sure, always happy to take a PR.

**Comment by Aisuko** [comment]
I hit the same issue, Is there any update for this issue?

**Comment by ahmetb** [comment]
I won't be able to provide a PR, I am hoping maintainers can jump in.

**Comment by TomSweeneyRedHat** [comment]
Clarified (hopefully) in https://github.com/containers/podman.io/pull/210

**Comment by TomSweeneyRedHat** [comment]
containers/podman.io#210 has merged fwiw

**Comment by abdennour** [comment]
still have same issue with this Mac: 

![image](https://user-images.githubusercontent.com/1788384/103245407-1eb14c00-4971-11eb-93cf-babe070a4940.png)

should i upgrade ? or is it podman issue ?

```sh
➜  ~ podman version
Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/4s/ch8k_58x04l59gv_p4jfq6lr0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory

```

**Comment by balupton** [comment]
Seems the issue has come back: https://stackoverflow.com/q/65590560/130638

I'm running Big Sur 11.1 (20C69)

Here's my uname:

```
Darwin redacted 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

**Comment by balupton** [comment]
never mind, user error, hadn't yet configured the remote client connection:

https://github.com/containers/podman/blob/master/docs/tutorials/mac_win_client.md

**Comment by ssbarnea** [comment]
Considering the number of users encountering this cryptic error, I would reopen this issue and assure that when we fail with it, we also print a descriptive message, maybe one with a link to documentation page.

**Comment by balupton** [comment]
> Considering the number of users encountering this cryptic error, I would reopen this issue and assure that when we fail with it, we also print a descriptive message, maybe one with a link to documentation page.

I'd also update https://podman.io/getting-started/ to have a section within `Familiarizing yourself with Podman` about the operating system support and the remote client.

As I think most people see installation part there, and be like, okay, nevermind, I've already got podman successfully installed via brew, so I don't need to look at that.

**Comment by afbjorklund** [comment]
Or just make the error message look like Docker, then everyone would recognize it ? https://github.com/containers/podman/issues/7301#issuecomment-734694469

For what it is worth, it is the same story on Linux (when you run the same program, `podman-remote`)

```
$ podman-remote version
Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///run/user/1000/podman/podman.sock: connect: no such file or directory
```

**Comment by rhatdan** [comment]
How about
./bin/podman-remote images
Error: Cannot connect to the Podman socket. Is the podman service running?: Get "http://d/v2.0.0/libpod/_ping": dial unix ///run/user/3267/podman/podman.sock: connect: connection refused

**Comment by rhatdan** [comment]
Actually I like this better.
Error: Cannot connect to the Podman socket, make sure their is a podman service running.: Get "http://d/v2.0.0/libpod/_ping": dial unix ///run/user/3267/podman/podman.sock: connect: connection refused

**Comment by rhatdan** [comment]
https://github.com/containers/podman/pull/8915

**Comment by JudeNiroshan** [comment]
For some people like me who couldn't really understand why `brew install podman` didn't work, the answer is, there should be linux virtual machine in order to run the podman. So, what the official documentation suggesting is for all MacOS and Windows users to spin up a linux virtual machine and connect your podman with that VM. That VM is acting as a backend server for your podman program. 

For MacOS users can simple run these commands which install podman and virtual machine program to spin up a linux VM.

```
  brew install podman 
  brew install qemu 
  podman machine init 
  podman machine start
```

**Comment by rhatdan** [comment]
Where should we document this to make it easier to understand?

**Comment by rhatdan** [comment]
@ashley-cui @baude WDYT of adding a --now flag to podman machine init?

systemctl enable --now foo.service 

Is what I base the idea on.

Then the instructions could be simplified to 
  brew install podman 
  brew install qemu 
  podman machine init --now

**Comment by kspendli** [comment]
i used below steps to resolve.

Removed podman brew uninstall podman
Removed containers files from the following directories:
rm -rf ~/.config/containers/
rm -rf ~/.local/share/containers

rm ~/.ssh/podman* related files 
Reinstalled podman using brew brew install podman
Init the podman machine and start it.
