### ISSUE TITLE
Fedora 31: podman failed with "Error: could not get runtime: unknown event logger type:"

### ISSUE THREAD

**Issue by henrywang** [containers/libpod#4392]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot run podman `root-less` on Fedora 31with the following error:
```
Error: could not get runtime: unknown event logger type:
```
But podman can be run on `root`.

**Steps to reproduce the issue:**

1. Run `podnam` on root-less user on Fedora 31

2. Failed with above error

**Describe the results you received:**
```
Error: could not get runtime: unknown event logger type:
```

**Describe the results you expected:**

Run without error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Cannot run this command due to this issue. But `podman -v` can be run with result:
```
podman version 1.6.2
```

**Output of `podman info --debug`:**

Cannot run this command due to this issue.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
podman-manpages-1.6.2-2.fc31.noarch
```

**Comment by mheon** [comment]
If you do not have any custom configuration in `~/.config/containers/libpod.conf` I recommend deleting the file; Podman should recreate one with sane defaults which will not have this issue.

**Comment by henrywang** [comment]
Thanks @mheon! Your comment works for me.
`podman` works on my Fedora 30, but it failed after update to Fedora 31. But I did not find any related break changes for `podman` from Fedora 31 release doc. Only found one common bug, which is about docker, on [Common F31 bugs](https://fedoraproject.org/wiki/Common_F31_bugs#Docker_package_no_longer_available_and_will_not_run_by_default_.28due_to_switch_to_cgroups_v2.29)

**Comment by goldmann** [comment]
Same here, removing `~/.config/containers/libpod.conf` helped.

**Comment by mheon** [comment]
We'll see about getting this added to the Fedora upgrade issues list.

**Comment by rhatdan** [comment]
@mheon What do you want to do with this?

**Comment by mheon** [comment]
I think we may be able to resolve it. We want to do a 1.6.4 for Fedora anyways, so this would be a good opportunity. I'll look into it.
