### ISSUE TITLE
support logs -f without printing any line

### ISSUE THREAD

**Issue by giuseppe** [containers/libpod#4396]
/kind feature

**Description**

I'd like to be able to use "podman logs -f` and not print any existing log line.  I want to follow only the new output.

It is not currently possible as `podman logs -fl --tail 0` defaults to print all lines.

Should we change the type to Int64 and use `-1` as default, or rather change the default to `math.MaxUint64`?

**Comment by mheon** [comment]
I'd support going to signed and special-casing negative numbers

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/4399
