### ISSUE TITLE
Docs are missing from GitHub site?

### ISSUE THREAD

**Issue by srp33** [containers/libpod#4406]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Docs are missing.

**Steps to reproduce the issue:**

1. Browse to https://github.com/containers/libpod/blob/master/commands.md

2. Click on links.

**Describe the results you received:**

404 errors. They were there until a couple of days ago.

**Describe the results you expected:**
Docs to appear.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Not relevant

**Output of `podman info --debug`:**

Not relevant

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Not relevant

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by TomSweeneyRedHat** [comment]
@srp33 thanks for the heads up.  I just clicked on your link above and got right to that page.  Could this have been a network hiccup or perhaps some kind of GitHub service outage when you tried earlier?

**Comment by srp33** [comment]
That page comes up but none of the links on that page work.

**Comment by TomSweeneyRedHat** [comment]
@srp33 thanks, speed reading bit me in the backside again, missed that part.  @baude could this be do to your documenation restructuring?

**Comment by baude** [comment]
go here -> https://podman.readthedocs.io/en/latest/index.html

what you are browsing are the source for the docs.

**Comment by srp33** [comment]
Thanks. I'll submit a pull request to modify the link that was pointing to that page.

**Comment by TomSweeneyRedHat** [comment]
I'm going to reopen this, all of the links on https://github.com/containers/libpod/blob/master/commands.md are broken and need to be changed.  @srp33 I think you're taking that on and that would be very much appreciated.  If not, we need to chase those down.

**Comment by rhatdan** [comment]
This is fixed in libpod now.
