### ISSUE TITLE
Support `-f`/`--force` flag in `podman image prune`

### ISSUE THREAD

**Issue by XVilka** [containers/libpod#4410]
/kind feature

**Description**

Docker CLI has a `-f` flag for the `docker image prune` command. So for podman to be compatible with docker, especially in scripts, at least it would be better not to show an error:

**Steps to reproduce the issue:**

1. `podman image prune -f`

**Describe the results you received:**

`Error: unknown shorthand flag: 'f' in -f`

**Describe the results you expected:**

Should not throw an error on both `-f` and `--force` flags used.

**Comment by rhatdan** [comment]
@XVilka Interested in adding these flags.  Looks like we are also missing
      --filter filter   Provide filter values (e.g. 'until=<timestamp>')

**Comment by rhatdan** [comment]
BTW What kind of confirmation is Docker doing?  I don't think Podman does any prompting at this point.

**Comment by XVilka** [comment]
```sh
$ docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N]
```
Even if podman doesn't ask, at least it should not report an error if `-f` flag is used.

**Comment by rhatdan** [comment]
I agree.
