### ISSUE TITLE
Support `--filter` flag in `podman image prune`

### ISSUE THREAD

**Issue by XVilka** [containers/libpod#4411]
/kind feature

**Description**

Docker CLI has a `--filter` flag for the `docker image prune` command. So for podman to be compatible with docker, especially in scripts, at least it would be better not to show an error:

**Steps to reproduce the issue:**

1. `podman image prune --filter "until=12h"`

**Describe the results you received:**

`Error: unknown flag: --filter`

**Describe the results you expected:**

Should not throw an error on `--filter`, moreover, it should support specifying the flag multiple times, and it should support filtering itself.

**Comment by rhatdan** [comment]
@XVilka Interested in opening a PR?

**Comment by XVilka** [comment]
Sorry, I don't have much experience with Go.

**Comment by kunalkushwaha** [comment]
I am also facing this issue.. will pick it up.

/assign
