### ISSUE TITLE
Move commands.md to commands-demo.md and update links

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#4414]
Per  #4407, the links in the commands.md page to the various man pages have changed.  The README.md was updated to the new readthedocs page for the docs.  Rename the commands.md page to a commands-demo.md page or something aggreable, leave a breadcrumb page behind at commands.md, and then update the links on the page for the man pages to their location at readthedocs.

**Comment by Zyqsempai** [comment]
I will take it!

**Comment by haircommander** [comment]
Thanks @Zyqsempai !

**Comment by TomSweeneyRedHat** [comment]
@Zyqsempai I'm super jealous of your profile icon....

**Comment by Zyqsempai** [comment]
@TomSweeneyRedHat I know;) Everybody are!))

**Comment by rhatdan** [comment]
@TomSweeneyRedHat is this still something you are interested in?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan yeah, we ought to touch this up at some point.  Added the do-not-close label.

**Comment by cpanato** [comment]
This is still open for contributions? If yes what's is missing?

**Comment by rhatdan** [comment]
Sure, just no one has stepped up to the plate to make an PR, if you have the time @cpanato We would love to see it.

**Comment by rhatdan** [comment]
@Zyqsempai @cpanato Any movement on this?

**Comment by cpanato** [comment]
sorry for the delay, PR today :) @rhatdan
