### ISSUE TITLE
BUG: Podman cannot chdir: Permission denied in rootless mode

### ISSUE THREAD

**Issue by marekvesely-direct** [containers/libpod#4416]
/kind bug

**Description**

Podman is not able to execute in rootless mode. It is writing: cannot chdir: Permission denied.

**Steps to reproduce the issue:**

1. Install Podman, create special user and group and add lines:
teamcityagent:200000:65536
to /etc/subuid and /etc/subgid

2. execute command:  podman unshare cat /proc/self/uid_map
under teamcityagent user.

**Describe the results you received:**
$ podman unshare cat /proc/self/uid_map
cannot chdir: Permission denied
         0          0 4294967295

**Describe the results you expected:**
$ podman unshare cat /proc/self/uid_map
         0       1001     1
         1       100000   65536
     65537       165536   65536
or similar

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 1769316352
  MemTotal: 8200630272
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: teamcity-iot-01.triglav.local
  kernel: 3.10.0-1062.1.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 576h 17m 55s (Approximately 24.00 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is VM in Vcenter running on CentOS 7.7.1908

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by rhatdan** [comment]
RHEL7 Rootless is not supported yet.  It will not be supported until RHEL7.8 release.
I don't think we have fuse-overlay yet.  And you need to set a sysctl to support User Namespace in the first place.

Something like:

sysctl user.max_user_namespaces=15000

**Comment by mheon** [comment]
I believe it's considered tech preview.

**Comment by rhatdan** [comment]
Any ways, this should be reported as a bugzilla and not to the upstream repo, since this is distro specific.
@marekvesely-direct if the sysctl does not fix the issue, could you open a bugzilla on it, and we can look at it there.
