### ISSUE TITLE
Re-add FFJSON for container and pod structs

### ISSUE THREAD

**Issue by mheon** [containers/libpod#442]
#440 just removed our FFJSON code because we were seeing segfaults after adding some things to the DB. We should track this down and figure out where the bug is (likely to be upstream FFJSON issue) and get it fixed to we can add FFJSON again to speed up our encode/decode

**Comment by baude** [comment]
Matt reports we are held up by an old ffjson bug

**Comment by rhatdan** [comment]
@mheon This still broken?

**Comment by mheon** [comment]
@rhatdan The bug we're hitting is 6 years old, I don't think this is getting fixed

**Comment by mheon** [comment]
I want to take another look at this before we move into CRI-O. Maybe a custom encoder/decoder for the one struct in question?

**Comment by wking** [comment]
Are there particular operations where JSON (de)serializing is a bottleneck?  I'd expect Go's stdlib parser/serializer to be fast enough for most cases.  And when it isn't fast enough, I'd expect we'd want to move to a database (SQLite?) instead of using a speedier JSON (de)serialization library.

**Comment by mheon** [comment]
@wking We use a lightweight key-value database (https://github.com/boltdb/bolt)  for storing our state, and currently encode container and pod state in JSON before storing it. As such, we have two or three intensive decode operations to retrieve a container, and the speed advantage from swapping to faster serialization/deserialization method could be considerable. We could also investigate swapping encodings entirely to something more space-conscious and suited to fast encoding/decoding (Google's Protobuf springs to mind), but that would be a potentially breaking change in database format (we could probably write a migration script but it would be a real pain), and the fast-and-loose nature of JSON lets us get away with a lot of database changes that wouldn't be allowable in a more structured datastore.

We previously had a SQLite backend, but abandoned it due to development issues (too frequent schema migrations, we were early in development and the database was changing left and right). I'd like to add a SQL backend again at some point as an alternative to Bolt.

**Comment by vrothberg** [comment]
@mheon, has this issue been resolved in the meantime? I think yes, but am not 100 percent sure.

**Comment by mheon** [comment]
@vrothberg Yeah, we should be able to close this. FFJSON is back in. Potentially not for long, though, given #1283
