### ISSUE TITLE
Cannot be removed a67ac443f7f6-infra pod

### ISSUE THREAD

**Issue by peterwillcn** [containers/libpod#4426]
Cannot be removed a67ac443f7f6-infra pod

**Comment by baude** [comment]
could you provide more information? version of podman, distro, the command you ran?

**Comment by peterwillcn** [comment]
Centos8 default version 
docker rm a67ac443f7f6-infra

**Comment by mheon** [comment]
Infra containers cannot be removed on their own. The pod they belong to
must be removed, which will remove them.
