### ISSUE TITLE
podman still fails after adding subuid/subgid ranges

### ISSUE THREAD

**Issue by pkratoch** [containers/libpod#4436]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hello, I want to ask how to recover from the following state:

I have large UID, so useradd didn't create subuid and subgid ranges. I ran podman a few times and it failed. So, I discovered the subuid/subgid ranges missing and added them manually, but podman still doesn't work.

I managed to recover in VM by deleting all config and some other stuff and reinstalling podman, but I don't remember how and I possibly broke the system by deleting some other things, so I don't want to do it on my own system.

Is there a good, deterministic way of recovering from this? Thank you!

Btw, ideal solution would be to make podman to recognize newly added subuid/subgid ranges are recover automatically, or at least advise user what to do. For this reason, I am marking this issue as a bug.

Additional note: if I do the steps below without steps 4. and 5., it all works ok.

**Steps to reproduce the issue:**

1. In "/etc/login.defs", UID_MAX is set to 60000
2. ``# useradd -u 100000 user1``
3. ``# su - user1``
4. ``# su -c "podman run --rm -it registry.fedoraproject.org/fedora-minimal" - user1``
5. ``# su -c "podman run --rm -it registry.fedoraproject.org/fedora-minimal" - user1  # (need to run two times for some reason)``
6. ``# usermod -v 100000-165536 -w 100000-165536 user1``
7. ``# su -c "podman run --log-level=warning --rm -it registry.fedoraproject.org/fedora-minimal" - user1``

**Describe the results you received:**
```
WARN[0000] the current user namespace doesn't match the configuration in /etc/subuid or /etc/subgid 
WARN[0000] you can use `podman system migrate` to recreate the user namespace and restart the containers 
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] running as rootless                          
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
Trying to pull registry.fedoraproject.org/fedora-minimal...
Getting image source signatures
Copying blob eab6ae2ae0c1 done
Copying config 7bb5a60e8a done
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:5 for /usr/bin/write): lchown /usr/bin/write: invalid argument
Error: unable to pull registry.fedoraproject.org/fedora-minimal: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:eab6ae2ae0c1b29c62c08b8ebefd7d690e794d426c6db86ce887fab367c395ed": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:5 for /usr/bin/write): lchown /usr/bin/write: invalid argument
```

**Describe the results you expected:**
No error, it should run the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.2-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 114172
      size: 1
    uidmap:
    - container_id: 0
      host_id: 114172
      size: 1
  MemFree: 5595512832
  MemTotal: 16664981504
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 8413769728
  SwapTotal: 8413769728
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: pkratoch.usersys.redhat.com
  kernel: 5.3.7-200.fc30.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 2h 18m 2.46s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/pkratoch/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.5-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.6.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/pkratoch/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/114172
  VolumePath: /home/pkratoch/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Happens on my system, but it's reproducible in virtual machine, too.

**Comment by giuseppe** [comment]
as the warning is suggesting you, you may need to recreate the user namespace:
```
WARN[0000] you can use `podman system migrate` to recreate the user namespace and restart the containers
```

Could you try using `podman system migrate` and then try creating the container again?

**Comment by pkratoch** [comment]
``podman system migrate`` did not resolve my issue, I still get the same warnings and errors as before. Is there any other way to "recreate the user namespace"?

**Comment by giuseppe** [comment]
so if I read above correctly, you UID for `user1` is `100000` and you are adding an additional subuid range `100000-165536`?

That won't work as the ID `100000` is present twice, once as your ID, another time as part of the additional ids.

**Comment by pkratoch** [comment]
You are absolutely right! If I make the ranges e.g. ``200000-265536`` instead, the migrate command works. I am closing this as the problem was on my side. Thank you for investigating this and explaining me what's wrong.

**Comment by rhatdan** [comment]
@giuseppe seems like something we should report an error to the user.  Something like Your UID can not be in the range of subuids or subgids.
