### ISSUE TITLE
Podman won't install on Fedora 31 after changing cgroup to v1

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#4445]
On a Fedora 31 machine, I installed Docker with `dnf -y install moby-engine` and then followed this procedure to set cgroup from the default v2 to v1:

```
As Root: 
# vi /etc/default/grub 
Add 'systemd.unified_cgroup_hierarchy=0' to the GRUB_CMDLINE_LINUX line 
# grub2-mkconfig 
# shutdown –r now 
```

Then after creating a few containers using Docker after the reboot, I installed podman and received this:

```
# dnf -y install podman
Fedora Modular 31 - x86_64                                                                        11 kB/s | 3.4 kB     00:00    
Failed to download metadata for repo 'fedora-modular'
Error: Failed to download metadata for repo 'fedora-modular'
```

It was installing latest Podman, I believe v1.6.2.

**Comment by giuseppe** [comment]
I don't think the error is related to the version of cgroup you are using.

Could you try running `dnf` with `--verbose`?
