### ISSUE TITLE
podman pull not working with oci-archive:path

### ISSUE THREAD

**Issue by lfarkas** [containers/libpod#4450]
podman pull (version 1.6.2) on fedora-31 not working with oci-archive:...
I've created the tar with [jib](https://github.com/GoogleContainerTools/jib) the created tar contains config.json and manifest.json but when I try to pull it with:
`podman pull oci-archive:/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar`
I've got this error:
`Error: error pulling image "oci-archive:/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar": unable to pull oci-archive:/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar: error determining pull goal for image "oci-archive:/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar": error loading manifest for {"/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar" "/home/lfarkas/work/vidux/vidux/java/face/app/build/jib-image.tar" ""}: error loading index: open /var/tmp/oci138821439/index.json: no such file or directory`

If I change the image format to docker in jib and pull as docker-archive:... than it's working.

**Comment by baude** [comment]
@TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Per the OCI image spec, there must be an `index.json` file present in OCI format images: https://github.com/opencontainers/image-spec/blob/master/image-layout.md

It does not sound like Jib is producing valid OCIv1 format images if this file is missing.

**Comment by vrothberg** [comment]
I concur with Matt.

**Comment by lfarkas** [comment]
sorry than i report it to jib
