### ISSUE TITLE
Pinging container from host

### ISSUE THREAD

**Issue by DaanDeMeyer** [containers/libpod#4455]
Hi,

I'm sorry if this has already been asked but I didn't manage to find any related Google search results.

What I'm looking to do is to use podman to start a development environment that I can ssh into using VSCode's Remote SSH support (until they natively support podman). With a default rootless container, `slirp4netns` is used which allows me to ping the host ip from the container but doesn't allow me to ping the container from the host.

What would be to optimal way to achieve this? Basically, I would like `ping 10.0.2.100` (with 10.0.2.100 being the `tap0` IP) to work when executed from the host. I'm assuming I need to use a different `--network` option but I'm unsure which one I would have to use.

With `systemd-nspawn` I was able to use the `--network-veth` option to achieve the desired result.

**Comment by mheon** [comment]
We presently do not support joining rootless containers to networks. It requires privileges that Podman does not possess when run without root. As such, rootless containers do not have IP addresses, and cannot be pinged directly.

**Comment by DaanDeMeyer** [comment]
Is the recommended alternative to use `--network=bridge`?

**Comment by mheon** [comment]
That is not available for rootless containers - again, no privileges to properly join the bridge. If you are running as root, the default bridge network will give each container a distinct IP, which will do what you're looking for.

**Comment by DaanDeMeyer** [comment]
I managed to get ssh access (on a rootless container) by using port mapping. Thanks for the quick responses!
