### ISSUE TITLE
reminder: rootless, rawhide: spurious warnings

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4456]
Just a reminder that gating tests are broken for rootless on rawhide due to spurious warning messages:
```
$ podman images
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
```
It seems possible that this is an unintended side effect of #4352. This is something for @vrothberg to look at once he's back. I'm filing issue so it doesn't get forgotten.

First build showing this problem: ca4c24c

**Comment by mheon** [comment]
Why are we printing warning messages again? I remember fixing that.

**Comment by edsantiago** [comment]
@mheon I believe it is a side effect of the config-parsing changes in #4352

**Comment by mheon** [comment]
I think it's the code in the `init()` block in `main_local.go`. It's running before we properly set log level.

We should investigate moving it into `Before()` which contains most of our init logic.

**Comment by vrothberg** [comment]
I suggest removing the config generation entirely, see https://github.com/containers/libpod/pull/4457.

**Comment by edsantiago** [comment]
Followup: #4457 seems to have fixed the spurious warning messages, thank you. But gating tests are now [failing rootless](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/7152/pipeline/#step-248-log-958) with:
```
$ podman run --rm quay.io/libpod/alpine_labels:latest /bin/true
time="2019-11-06T12:51:29Z" level=error msg="oci runtime \"runc\" does not support CGroups V2: use system migrate to mitigate"
Error: this version of runc doesn't work on cgroups v2: OCI runtime error
```
It'll take me a little while to look into it; am commenting simply in case it elicits an "aha" in anyone.

**Comment by vrothberg** [comment]
Great, happy we could tackle it so quickly!

> It'll take me a little while to look into it; am commenting simply in case it elicits an "aha" in anyone.

@edsantiago did this work before? I think we have two options: 1) force the gating tests to use `crun` or 2) force `crun` in the `config.Config` logic. Cc @mheon

**Comment by edsantiago** [comment]
Before what? :-/ Gating tests were passing in 1e750f7, October 31, and I'm pretty sure that was with crun.

**Comment by vrothberg** [comment]
@edsantiago, the error message indicates that we're running `runc`. I don't know how these tests are run, so I wonder what has changed. Let's make it a PS?
