### ISSUE TITLE
latest version of podman on flathub?

### ISSUE THREAD

**Issue by jonasbartho** [containers/libpod#4458]
Hi,

Can you guys do an effort to also offer the latest version of podman through flathub(flatpak), not only as a snap package? :)

Kinds regards,
Jonas

**Comment by TomSweeneyRedHat** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
I'd love to see this included, but I can't invest any time myself atm :( . @abitrolly any chance you'd be interested? :crossed_fingers: :) ?

If not, @TomSweeneyRedHat @baude @mheon @rhatdan we should reach out to the community.

**Comment by abitrolly** [comment]
While the idea to research Flatpak format seems interesting, I am not sure I possess the necessary resources to take a responsibility.

**Comment by MycroftHolmes1989** [comment]
While you guys are at it, would you kindly consider adding it to OpenSUSE Build Services? It would be an easy way to target multiple distros and support latest releases,. For example, the official PPA does not have support for Ubunt 19.10 yet. Those problems would probably be easier to handle if you just add the project to OBS.

**Comment by lsm5** [comment]
On Tue, Nov 12, 2019 at 09:40:05AM -0800, M Holmes wrote:
> While you guys are at it, would you kindly consider adding it to OpenSUSE Build Services? It would be an easy way to target multiple distros and support latest releases,. For example, the official PPA does not have support for Ubunt 19.10 yet. Those problems would probably be easier to handle if you just add the project to OBS.
> 

Ubuntu 19.10 on PPA is currently wip. I did ping the obs people for help but no
response yet. /cc @vrothberg.

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by vrothberg** [comment]
There's no response yet.

**Comment by lsm5** [comment]
@MycroftHolmes1989 in case you have experience with OBS, would you be willing to help out?

**Comment by MycroftHolmes1989** [comment]
Unfortunately, I'm not qualified enough to undertake such a task. Sorry.

**Comment by lsm5** [comment]
On Tue, Nov 12, 2019 at 11:26:14AM -0800, M Holmes wrote:
> Unfortunately, I'm not qualified enough to undertake such a task. Sorry.

No worries. OBS is on our agenda yes, as that'll make it easier to ship for
vanilla Debian too, but we're fighting some other fires so it's gonna take
longer unless maybe we get additional community support.

Meanwhile, I hope to have 19.10 enabled on the PPA by early next week.

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by lsm5** [comment]
@MycroftHolmes1989 https://github.com/containers/libpod/issues/1742#issuecomment-555061785 :)

**Comment by rhatdan** [comment]
Since this is handled in the other issue, I am going to close this.

**Comment by Yajo** [comment]
I've been reading the other issue but found nothing about bundling podman inside flatpak. Is that done? Is that possible?

**Comment by rhatdan** [comment]
Podman could be installed in a flatpak, and it might work. But realize that a flatpak is a container, and you would be attempting to run containers within containers, which very likely is going to be blocked by some kind of security mechanism. or other issues with namespaces.

Why do you need it in a flatpack?

**Comment by Yajo** [comment]
I was thinking on the possibility to create an alternative to yunohost inside a desktop app. Flatpak seemed like the best option to package it, while podman seemed like the best option to run services in it.

**Comment by rhatdan** [comment]
@alexlarsson WDYT?
