### ISSUE TITLE
slirp4netns socket path can get too long in tmp_path

### ISSUE THREAD

**Issue by duritong** [containers/libpod#4467]
/kind bug
**Description**

While playing around I had a podman tmp_path in:
`/run/podman-tmp/verylongnamethatwillnotwork`

When running a rootless pod with a portmaping the pod did not start and podman just hang.

When debugging I figured out aht slirp4netns got started e.g. with the following api path:

`/run/podman-tmp/verylongnamethatwillnotwork/libpod/tmp/a59f251cbed09ec9f9080c58f70a445a639d3c8e613e30f6e20a5420aa94837b.net`

But actually this path did not exist and slirp4netns just tried in a loop to open it and likely waited to be created.

On the other hand podman had a socket open, but the path for the socket was just:

`/run/podman-tmp/verylongnamethatwillnotwork/libpod/tmp/a59f251cbed09ec9f9080c58f70a445a639d3c8e613e30f6e20a`

=> see the missing characters at the end.

So what happened imho is that podman created a socket path that respects the (ancient?) limitation of the maximum socket path length. But told nobody!

Either the socket path propagation should correctly happen or it should error out or we must ensure shorter socketpaths.

**Comment by AkihiroSuda** [comment]
Maybe we should support abstract sockets and/or FD

**Comment by giuseppe** [comment]
I think it is now fixed with: https://github.com/rootless-containers/slirp4netns/pull/158

Podman won't hang and an error message is printed
