### ISSUE TITLE
Upgrade woe: 1.4->1.6: Error: could not get runtime: eventer creation: No support for journald logging

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4469]
Upgrading from `podman-1.4.2-6.module+el8.2.0+4448+2029f340` to `1.6.2-5.module+el8.2.0+4584+0d586e68` on rhel8, rootless, results in unrunnable podman:
```
$ podman run --rm alpine true
Error: could not get runtime: eventer creation: No support for journald logging
```
Removing `~/.config/containers` and `~/.local/share/containers` makes it work again.

I imagine this is a CANTFIX/WONTFIX. Am filing in case it helps someone in the future.

**Comment by rhatdan** [comment]
Would `podman system migrate` have fixed your issue?

**Comment by edsantiago** [comment]
Good question. I didn't think of it, and no longer have that virt, and am scrambling to figure out the current batch of rhel8 problems right now. Will test if I get a chance today.

**Comment by edsantiago** [comment]
Nope:
```
$ podman system migrate
Error: could not get runtime: eventer creation: No support for journald logging
$ podman info
Error: could not get runtime: eventer creation: No support for journald logging
```
Will leave the VM up for a while (fiddling with buildah) in case there's anything else you'd like me to try.

**Comment by rhatdan** [comment]
podman --events-backend file info

**Comment by edsantiago** [comment]
[podman-events-backend-file-into.txt](https://github.com/containers/libpod/files/3821966/podman-events-backend-file-into.txt)

**Comment by edsantiago** [comment]
...and, because I belatedly realized that that isn't very helpful:
```
$ grep journ ~/.config/containers/*
/home/testuser/.config/containers/libpod.conf:events_logger = "journald"

$ sed -ie '/events_logger/d' ~/.config/containers/libpod.conf
$ podman info
[ works ]
$ podman run alpine_labels date
Thu Nov  7 22:29:45 UTC 2019
```

**Comment by mheon** [comment]
Is this a build flags issue, maybe? This error seems suspiciously similar to a "we didn't build with systemd support" one...

**Comment by mheon** [comment]
Yep, that error comes out when Podman is not built with systemd support.

**Comment by edsantiago** [comment]
Oh, interesting. Looking now at the specfile. @jnovy, heads-up, this may end up landing on your plate...

**Comment by edsantiago** [comment]
I can't find a smoking gun, but there _is_ a specfile change similar to the buildah one. @jnovy, I think I'm going to drop this one on you for a closer look since you were able to figure out the buildah issue. @mheon, thanks for the insight!

**Comment by rhatdan** [comment]
This is not an upstream issue, so I am going to close.  Please reopen if I am mistaken.
