### ISSUE TITLE
Automatic redeploy container when image base updated

### ISSUE THREAD

**Issue by colundrum** [containers/libpod#4472]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I purpose the possibility to have a solution like watchtower (https://github.com/containrrr/watchtower) which permit to reploy containers (automatically) when image is updated.

I think that it can help to stay up-to-date due to the lack to doc about doing it automatically using CI/CD with podman

**Steps to reproduce the issue:**

1. Deploy Toto/1:latest

2. Update Toto/1:latest

3. Nothing append automatically, I need to pull and reploy manually

**Describe the results you expected:**
When image is updated in registry, pull it and reploy container(s) using it.
All automatically

**Comment by rhatdan** [comment]
We had an intern working on a project like this, this past summer.
https://github.com/containers/podhawk
PTAL.  See if this is somewhat matching your needs and something we should pursue.

**Comment by colundrum** [comment]
@rhatdan Thanks, I'll look if I can adapt it.
I'll tell you if I push my development to my dev/stage.

**Comment by colundrum** [comment]
Working on Podhawk, this issue can be close because Podhawk'll resolve it
