### ISSUE TITLE
Wrong network namespace when exec in container created with --net=host

### ISSUE THREAD

**Issue by faulesocke** [containers/libpod#4473]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When a container is created with `podman run --net=host` all instances of `podman exec` to that container do not attach to the containers network namespace but use whatever network namespace they are executed in.

**Steps to reproduce the issue:**
```
ip netns add foo
ip netns exec foo podman run --net=host -d <image>
podman exec <cid> ip link
```

**Describe the results you received:**
I receive a list of the network devices in my current network namespace.

**Describe the results you expected:**
I expect to see the network devices currently present in the containers network namespace.

**Additional information you deem important (e.g. issue happens only occasionally):**
I actually use `--net=host` to manually create a network namespace as root and then I use `ip netns exec su --login -c "podman run --net=host ..." <user>` to drop privileges and run a rootless container inside that namespace.

This allows me to put whatever I like into that namespace prior to running any container app. This is especially useful to put a macvlan or veth interface into a rootless container.

**Output of `podman version`:**

```
% podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
probably not necessary
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
% xbps-query podman
architecture: x86_64
build-date: 2019-10-28 09:08 UTC
filename-sha256: 9f02213136c2e47678d2a7df463ff39b38ef0bde9e2f423e06f8d8a25ad31f0b
filename-size: 17MB
homepage: https://podman.io/
install-date: 2019-11-02 14:30 UTC
installed_size: 52MB
license: Apache-2.0
maintainer: Cameron Nemo <camerontnorman@gmail.com>
metafile-sha256: 217e71f163e554521506eee062869443aa3467d1b3a4d1a3ded0f738b0ddbc4b
pkgver: podman-1.6.2_1
repository: https://alpha.de.repo.voidlinux.org/current
shlib-requires:
	libpthread.so.0
	libgpgme.so.11
	libassuan.so.0
	libgpg-error.so.0
	libseccomp.so.2
	librt.so.1
	libdevmapper.so.1.02
	libc.so.6
short_desc: Simple management tool for containers and images
source-revisions: podman:1c4242350be
state: installed
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Void Linux, physical machine.

**Comment by mheon** [comment]
I strongly suspect this is a bug with the OCI runtime - runc or crun. Podman does not influence this beyond calling the OCI runtime.

**Comment by faulesocke** [comment]
So do I have to report the bug somewhere else?

**Comment by mheon** [comment]
I would inspect the container and look for the OCIRuntime key - that will tell you what runtime we're using to launch containers. I suspect it will be `runc` which lives at github.com/opencontainers/runc - you'll probably want to report against them

**Comment by rhatdan** [comment]
@faulesocke also could you try with crun, to see if it works differently?
@giuseppe WDYT?

**Comment by giuseppe** [comment]
not sure what would be the best way to handle it.  When you specify `--net=host` you basically tell the OCI runtime to not create any network namespace and use whatever it runs in.

If you create a network namespace, and run Podman from there, that will be the namespace used, despite `--net=host` seems like using the host network namespace.

Similarly for `exec`, if no network namespace must be created then it uses whatever is used at `podman exec` time.

An obvious solution would be to join the network namespace for the container process.  But that would cause other issues, e.g. the container process might have created another network namespace so it is still different than the original `--net host` one.

Given the choice between the two behaviours I think we should prefer the former, where we use the network namespace we are running in, as it is controllable by the user instead the latter behaviour depends from the application running inside of the container.

**Comment by faulesocke** [comment]
Why would `exec` ever create a network namespace? I thought it's there to join the existing namespaces.

**Comment by faulesocke** [comment]
@rhatdan I will try with `crun`.

**Comment by giuseppe** [comment]
> Why would `exec` ever create a network namespace? I thought it's there to join the existing namespaces.

it should not.  It should either use the existing one, or join the first process in the container network namespace .

**Comment by faulesocke** [comment]
> not sure what would be the best way to handle it. When you specify `--net=host` you basically tell the OCI runtime to not create any network namespace and use whatever it runs in.

Exactly that was my thought.

> If you create a network namespace, and run Podman from there, that will be the namespace used, despite `--net=host` seems like using the host network namespace.
> 
> Similarly for `exec`, if no network namespace must be created then it uses whatever is used at `podman exec` time.

To me that is counter-intuitive. Why would exec behave differently for a container with it's "own" network namespace than for a container that got created with a previously existing one? If it would be possible, I would use the `--net=ns:/path/to/netns` syntax but this seems to be impossible for rootless containers. However, in that case I would expect `exec` to also join the namespace specified at creation time and not the one that the `podman` command is run from.

**Comment by faulesocke** [comment]
crun behaves exactly the same way. I am still searching for a way to attach a rootless container to a network namespace I previously created as root.

**Comment by mheon** [comment]
`--netns=path:$PATH` doesn't work?

**Comment by giuseppe** [comment]
> crun behaves exactly the same way. I am still searching for a way to attach a rootless container to a network namespace I previously created as root.

if the network namespace was created by root in the initial user namespace, then a rootless container cannot join it.

**Comment by rhatdan** [comment]
@giuseppe Does the network namespace have to be created within the user namespace or just be owned by the root of the user namespace?

**Comment by faulesocke** [comment]
@giuseppe and would it be possible to create the user and network namespaces as root and then tell podman to use these?

**Comment by giuseppe** [comment]
> @giuseppe Does the network namespace have to be created within the user namespace or just be owned by the root of the user namespace?

it must be owned by the root of the user namespace, as long as you are in an user namespace which is parent or the same as the owner of the network namespace.

So if you have something like:

```
+-- initial namespace A (user must be root here)
|-----+ user namespace B
        |----- network namespace D
|----- user namespace C
```

where both user namespaces are created by the same rootless user.

You cannot join network namespace D if you are in the user namespace C.

You can join it either if you are in A or in B.



> @giuseppe and would it be possible to create the user and network namespaces as root and then tell podman to use these?

if root owns these namespaces, then rootless cannot join them.

**Comment by mheon** [comment]
And I imagine a simple `chown` won't work - it actually needs to be created by the user namespace?

**Comment by giuseppe** [comment]
> And I imagine a simple `chown` won't work - it actually needs to be created by the user namespace?

I don't think the user namespace ownership can be changed, I've tried to chown it and I get an `Operation not permitted` error

**Comment by rhatdan** [comment]
@giuseppe @faulesocke Is there any fix for this other then to document the behaviour?

**Comment by giuseppe** [comment]
@rhatdan there is no fix for rootless containers, as they cannot join a namespace owned by root.

**Comment by rhatdan** [comment]
Ok can you document this in the rootless.md file?
