### ISSUE TITLE
please update podman in RHEL extra's more often

### ISSUE THREAD

**Issue by jonasbartho** [containers/libpod#4476]
Hi, 

Ref. https://github.com/containers/libpod/issues/3044

The same issue applies now in RHEL 7.7... 
The current available version of podman is 1.4.4-4 and we preferably want to have the latest(v1.6.3) since the newer ones have important bug fixes for running rootless podman.  If i want to convince my developers to switch completely to podman from docker, then we need a more frequent update release on podman and necessary dependencies... 

Thank you in advance for the help!
TAGS: @fatherlinux

**Comment by rhatdan** [comment]
RHEL7.8 version of Podman will match the RHEL8.2 version.  Sadly this will probably be the final release other then CVE fixes, since RHEL7 will be entering its next level of support, which is just security fixes.

**Comment by jonasbartho** [comment]
Hmm, that is unfortunate!
Does podman/buildah have an online rpm-repository where I could download from? I have googled for this without any success. That would partially solve our problem.

**Comment by rhatdan** [comment]
You can run newer podman inside of a container quay.io/podman/stable which would get you a newer version.  
You would need to run this in a --privileged container with the hosts podman or docker.

**Comment by jonasbartho** [comment]
Hmm, that is sadly not a good solution for us.
Shame that there is no own repository... It would make it a lot easier for our developers to change.

**Comment by rhatdan** [comment]
@jonasbartho Moving to RHEL8 you will get latest podman every three months.  RHEL7 is probably not a great place for developers at this point, since it is almost 7 years old.

**Comment by jonasbartho** [comment]
Ok thx!
