### ISSUE TITLE
COPY relative path misparsed

### ISSUE THREAD

**Issue by carroarmato0** [containers/libpod#4479]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While building a container, the process is interrupted at the following step:

```
# Copy basic configuration files
COPY ./resources/ /
```

When enabling --log-level debug, the last entry in the log is:

> Error: error building at STEP "COPY ./resources/ /": no files found matching "/opt/jenkins/workspace/product-container-builds/container-apache/apache22-centos6/ --label \"org.opencontainers.image.source=https:/git.somecompany.eu/scm/division/container-apache.git\" --label \"org.opencontainers.image.revision=4b37ccb0834a860be8fd82bc460a06ee557c537b\" --label \"org.opencontainers.build_tool.source=https:/git.somecompany.eu/scm/division/product-container-builder.git\" --label \"org.opencontainers.build_tool.revision=215901d4e69917954e64c0dd3828c618d33d71ea\" --label \"org.opencontainers.image.created=2019-11-08 11:43:19+01:00\"/resources": no such file or directory

At first glace, for some reason --label and other irrelevant things seem to have slipped in the path.

**Steps to reproduce the issue:**

1. The following Dockerfile is used:

```
FROM centos6:latest

LABEL \
    org.opencontainers.image.description="Apache Intermediate Image"

# Allow specifying a repository base url and config
ARG REPOURL
ARG LOCAL_REPO_CONFIG

# Copy Repository template
RUN echo "${LOCAL_REPO_CONFIG}" | base64 -d > /etc/yum.repos.d/local-repo.repo

# Make REPOURL value available to the Yum Repo template
RUN echo "${REPOURL}" > /etc/yum/vars/repourl

# Install software packages
RUN yum makecache; \
    time yum install -y \
        httpd \
        httpd-devel \
        httpd-tools \
        mod_ssl \
        mod_authnz_crowd \
        jakarta-commons-httpclient; \
    yum clean all; \
    rm -rf /var/cache/yum;

# Remove default configuration
RUN rm -fr /etc/httpd/conf.d/*

# Copy basic configuration files
COPY ./resources/ /

# Symlink access and error logs to stout and sterr
RUN ln -sf /dev/stdout /var/log/httpd/access_log; ln -sf /dev/stderr /var/log/httpd/error_log

# Request Runtime engine to expose the listening port of the application
EXPOSE 80
EXPOSE 443

CMD ["/usr/sbin/httpd","-D", "FOREGROUND"]
```

2. The command used to build (some variables are not expanded because they can't be used for reproducability):

  podman build \
    --build-arg REPOURL="${REPOURL}" \
    --build-arg LOCAL_REPO_CONFIG="${REPO_CONFIG}" \
    --log-level debug \
    --label "org.opencontainers.image.ref.name=${CONTAINER_NAME}:${CONTAINER_TAG}" \
    --label "org.opencontainers.image.title=${CONTAINER_NAME}" \
    "${CUSTOM_LABELS}" \
    --iidfile ${CONTAINER_NAME}.id \
    --logfile ${CONTAINER_NAME}.log \
    --force-rm \
    --no-cache \
    --tag "${CONTAINER_NAME}:${CONTAINER_TAG}" \
    -f Dockerfile \
    .

**Describe the results you received:**

The container is unable to be built successfully

**Describe the results you expected:**

Podman copies the files in ./resources and recreates the folder structure inside the container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 2782011392
  MemTotal: 8201572352
  OCIRuntime:
    package: containerd.io-1.2.10-3.2.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 3999264768
  SwapTotal: 3999264768
  arch: amd64
  cpus: 2
  hostname: platojenkslave4
  kernel: 3.10.0-1062.4.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 191h 31m 8.7s (Approximately 7.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - artifactory.somecompany.eu
  - docker.io
store:
  ConfigFile: /opt/jenkins/.config/containers/storage.conf
  ContainerStore:
    number: 5
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /opt/jenkins/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 35
  RunRoot: /run/user/1000
  VolumePath: /opt/jenkins/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 7.7 running on a vSphere VM.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@carroarmato0 I've tried using your Dockerfile with upstream Buildah and I'm seeing a different error:

```
STEP 9: COPY ./resources/ /
DEBU COPY []string(nil), imagebuilder.Copy{FromFS:false, From:"", Src:[]string{"./resources/"}, Dest:"/", Download:false, Chown:""} 
DEBU error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[./resources/ /] Flags:[] Attrs:map[] Message:COPY ./resources/ / Original:COPY ./resources/ /}: no files found matching "/root/resources": no such file or directory 
error building at STEP "COPY ./resources/ /": no files found matching "/root/resources": no such file or directory
[root@localhost ~]# 
```

Which in my case anyway is valid as I don't have a /root/resources directory.  I don't see a command in your Dockerfle that I suspect would create that directory, am I missing something?

**Comment by carroarmato0** [comment]
> @carroarmato0 I've tried using your Dockerfile with upstream Buildah and I'm seeing a different error:
> 
> ```
> STEP 9: COPY ./resources/ /
> DEBU COPY []string(nil), imagebuilder.Copy{FromFS:false, From:"", Src:[]string{"./resources/"}, Dest:"/", Download:false, Chown:""} 
> DEBU error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[./resources/ /] Flags:[] Attrs:map[] Message:COPY ./resources/ / Original:COPY ./resources/ /}: no files found matching "/root/resources": no such file or directory 
> error building at STEP "COPY ./resources/ /": no files found matching "/root/resources": no such file or directory
> [root@localhost ~]# 
> ```
> 
> Which in my case anyway is valid as I don't have a /root/resources directory. I don't see a command in your Dockerfle that I suspect would create that directory, am I missing something?

So the way I envisioned it to work is having Jenkins pull down a Git repository in a Job.
The structure looks like this:

```
.
├── Dockerfile
├── Jenkinsfile
└── resources
    └── etc
        └── httpd
            └── conf
                ├── common
                │   ├── status.conf
                │   └── stealth.conf
                └── httpd.conf
```

The behavior I have with Docker, is that the contents or the resources folder, being applied to "/", results in the configuration files (status.conf, stealth.conf and httpd.conf) being copied inside the container in /etc/httpd/conf/... etc.

I'm not sure if this is a different behavior in buildah.

But the output of the error message makes it look like something went wrong with parsing the full path to the resources folder.

**Comment by TomSweeneyRedHat** [comment]
@carroarmato0 Maybe I've late Friday afternoon brain, but the message, although messed up, seems to be saying it can't find the resource directory in that last bit.  I noticed you have an older version of Podman/Buildah.  Any chance you could upgrade and try again?

**Comment by carroarmato0** [comment]
> @carroarmato0 Maybe I've late Friday afternoon brain, but the message, although messed up, seems to be saying it can't find the resource directory in that last bit. I noticed you have an older version of Podman/Buildah. Any chance you could upgrade and try again?

Already 10pm over here, brain definitely set in weekend mode :)

Using Podman for a client, I suspect they want to keep things as vanilla as possible (in this case, whatever CentOS makes available in the repo's on 7.7).
I do believe I can find rpm's for podman 1.6.2 and buildah 1.11.4 from here: https://buildlogs.centos.org/centos/7/virt/x86_64/container/ which I could try out and see what happens.

I wonder though on the other hand if perhaps there's something off about the current directory/context in which Buildah is finding itself in.

I'll only be able to give this some further testing on Tuesday with a newer version.

**Comment by TomSweeneyRedHat** [comment]
Thanks @carroarmato0 !  FWIW, unless you want to play with or use Buildah directly, you should only need the Podman rpm from there, that should be enough.   The context directory might be it too, you'd need to be in the same directory as the Dockerfile per your tree above.

Enjoy the weekend and thanks for the help chasing this.

**Comment by carroarmato0** [comment]
The packages from that link are unusable due to the absence of the libvarlink-util dependency.
Ended up using most packages coming from https://cbs.centos.org.

When trying to use podman I realized the switch to crun instead of runc.

```
#podman --version && podman info
podman version 1.6.2
Error: could not get runtime: default OCI runtime "crun" not found: invalid argument
```

I fear this is going to become a slippery slope in Centos 7.7 . Will try reverting and taking a closer look to see if it's really not something weird with the context/path which podman is excuted in.

**Comment by carroarmato0** [comment]
After some more testing I figured there was something wrong with  "${CUSTOM_LABELS}".

This variable is injected as a parameter to podman. After inspecting it, I don't seem to see anything weird with it.

```
  podman build \
    --build-arg REPOURL="${REPOURL}" \
    --build-arg LOCAL_REPO_CONFIG="${REPO_CONFIG}" \
    ${DEBUG_STRING} \
    --label "org.opencontainers.image.ref.name=${CONTAINER_NAME}:${CONTAINER_TAG}" \
    --label "org.opencontainers.image.title=${CONTAINER_NAME}" \
    "${CUSTOM_LABELS}" \
    --iidfile ${CONTAINER_NAME}.id \
    --logfile ${CONTAINER_NAME}.log \
    --force-rm \
    --no-cache \
    --tag "${CONTAINER_NAME}:${CONTAINER_TAG}" \
    -f Dockerfile \
    .
```
CUSTOM_LABELS resolves to:

`
 --label 'org.opencontainers.image.source=https://git.somecompany.eu/scm/somedivision/container-apache.git' --label 'org.opencontainers.image.revision=4b37ccb0834a860be8fd82bc460a06ee557c537b' --label 'org.opencontainers.build_tool.source=https://git.somecompany.eu/scm/somedivision/product-container-builder.git' --label 'org.opencontainers.build_tool.revision=215901d4e69917954e64c0dd3828c618d33d71ea' --label 'org.opencontainers.image.created=2019-11-08 11:43:19+01:00'
`

So apparently this is not a context/path issue. Not really sure if there's a subtle issue I'm looking over, max parameter length reached? Or podman getting confuse by too many parameters

**Comment by carroarmato0** [comment]
I'm going to close this issue as it's clear that there's something wrong with how the values are being passed to podman's commandline arguments, rather than something going wrong with podman itself. Thanks for taking the time to have a look.
