### ISSUE TITLE
changelog entries for v1.6.3 are missing and no 1.6 RA on podman.io

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#4485]
Just pulled up the changelog.txt file and it has no entries for 1.6.3.

Also there's not a release announcement for 1.6* on podman.io, poke, poke.

**Comment by baude** [comment]
@mheon is this something you fix quickly?

**Comment by rhatdan** [comment]
I would just close this.  I don't see a big issue in going back and fixing this. Not a high priority. We are onto 1.7.0 at this point.
