### ISSUE TITLE
Unable to upload file to container over varlink

### ISSUE THREAD

**Issue by johanbrandhorst** [containers/libpod#4495]
/kind bug

**Description**

I would like to be able to programmatically upload arbitrary data to a container and put it in a file of my choice. This is possible today in [the Docker API](https://docs.docker.com/engine/api/v1.40/#operation/PutContainerArchive).

In my quest to find a solution to this I scoured the issue tracker and the source and I found two possible solutions:

1. Like `podman cp`, mount, write, unmount.

   This was initially successfull, but only because I was running `podman` on the same machine, as this relies on access to the same filesystem as the podman host. Even when co-located, it would sometimes suffer from permission issues when writing files into the containers filesystem.
2. I found the following snippet in the libpod source:

   https://github.com/containers/libpod/blob/master/pkg/adapter/runtime_remote.go#L550
   While I was able to upload the file (I took the opportunity of adding some helpers to varlink/go: https://github.com/varlink/go/pull/19), but it just gives me the name of a tempfile on the host filesystem, and infuriatingly doesn't seem to allow me to move the file after the transfer has finished.

   This is still my main line of inquiry, and I believe it would be successful if there was just some way to move the file once it has been transmitted. Any pointers?

**Steps to reproduce the issue:**

1. Attempt to upload a file or archive to a container over varlink.

**Describe the results you received:**

This was impossible, as best I can tell.

**Describe the results you expected:**

I expected it to be possible, as an analogue to the [Docker archive upload API](https://docs.docker.com/engine/api/v1.40/#operation/PutContainerArchive)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.3
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 65fe0226d85b69fc9e527e376795c9791199153d'
  Distribution:
    distribution: manjaro
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
  MemFree: 1179627520
  MemTotal: 16569847808
  OCIRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9
      commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
      spec: 1.0.1-dev
  SwapFree: 18195599360
  SwapTotal: 18223570944
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: johan-x1
  kernel: 4.19.81-1-MANJARO
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.2
      commit: 69153b0d1cb82216d6782179ff7c3c5e91c731a1
  uptime: 35h 46m 32.67s (Approximately 1.46 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/REDACTED/.config/containers/storage.conf
  ContainerStore:
    number: 20
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/REDACTED/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 131
  RunRoot: /run/user/1000
  VolumePath: /home/REDACTED/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

On bare metal (laptop).

**Comment by sshnaidm** [comment]
Is this about https://github.com/containers/libpod/issues/4207 ?

**Comment by johanbrandhorst** [comment]
No, but I guess that covers the same thing. This is about a library I'm writing for dynamically starting and removing containers for Go tests.

**Comment by johanbrandhorst** [comment]
This is still an issue.

**Comment by rhatdan** [comment]
Ok I removed it from auto close.

**Comment by vrothberg** [comment]
I am going to close this issue. To the best of my knowledge, there are no plans to support copy over varlink. This will likely change with the upcoming v2 API (rest based).
