### ISSUE TITLE
configuration option for dns server to use

### ISSUE THREAD

**Issue by whitel** [containers/libpod#4508]
/kind feature
also kind of a bug

**Description**
If you are using 127.0.0.1 in resolv.conf, podman appears to switch to using 8.8.8.8 in the containers it runs. In some networks that dns server may be blocked. You can work around this issue by passing `--dns=<my-dns-server>` but it would be nice to be able to set this system/user -wide. 

I propose an entry in to the libpod.conf file(s).  However, a similar issue is fixed via resolv.conf (if I am reading it correctly) here: https://github.com/containers/libpod/issues/3277

Docker/Moby had a similar problem: https://github.com/moby/moby/issues/23910

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Comment by mheon** [comment]
@rhatdan @QiWang19 Looks like a good candidate for containers.conf

**Comment by larsks** [comment]
Note that this is already possible in Docker, which lets you set the default resolver via `/etc/docker/daemon.json` (or as a command line argument to `dockerd`). I've hit the same problem as langdon and I agree that always having to add `--dns a.b.c.d` to my `podman run` invocations is annoying (particularly when I forget!).

**Comment by baude** [comment]
@rhatdan containers.conf ?

**Comment by rhatdan** [comment]
Yes @QiWang19 could easily add this option.

**Comment by rhatdan** [comment]
Begin adding support https://github.com/containers/common/pull/29

**Comment by ensc** [comment]
Is this available in 1.7.0?  `containers.conf` seems to be ignored with podman-1.7.0-0.5.rc2.fc31.x86_64

**Comment by mheon** [comment]
I don't believe it is - we're expecting initial support to land in 1.8.0. We'll begin gradually deprecating libpod.conf at that time as well.

**Comment by gbryant200** [comment]
I'm running docker
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
on Ubuntu 18.04
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```
I'm behind a company proxy; I have /etc/systemd/system/docker.service.d/proxy.conf file:
```
[Service]
Environment="http_proxy=http://domain\\user:pw@proxy.com:3128/"
Environment="HTTP_PROXY=http://domain\\user:pw@proxy.com:3128/"
Environment="HTTPS_PROXY=http://domain\\user:pw@proxy.com:3128/"
Environment="https_proxy=http://domain\\user:pw@proxy.com:3128/"
Environment="NO_PROXY=localhost,127.0.0.1/"
Environment="no_proxy=localhost,127.0.0.1/"
```

`systemctl show --property=Environment docker` list the environment variables as expected (if I URL encode the '\', then this command doesn't list anything).

### is there a way to specify the type of proxy authentication in the above file?  I've had to specify 'basic' authentication before.  I'm not sure how to configure the above file for different authentication types.

`/etc/resolv.conf` lists
```
nameserver 127.0.0.53
options edns0
search dns_domain.com
```

`/etc/docker/daemon-json`
```
{
        "dns": ["10.100.219.1", "10.100.19.1"]
}
```

I can ping anything from the host.  Absolutely no DNS resolution problems.

If I try to run `docker run hello-world` I get the following error:
```
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup http: Temporary failure in name resolution.
```

if I run `docker run hello-world --dns 10.100.219.1`  I get the same error.

Any ideas?  From my searching, it seems like this issue has been going on for sometime on Ubuntu.

**Comment by larsks** [comment]
@gbryant200 you seem to be in the wrong place: this is for bug reports about [podman](https://podman.io/), which is an alternative to Docker. It's not for questions about Docker.

**Comment by rhatdan** [comment]
@whitel The latest containers.conf in github.com/containers/common, has support for the dns server issue.  The PR to get containers.conf support into Podman is very close. One more issue to get it merged.

**Comment by rhatdan** [comment]
containers.conf support is now in.

**Comment by whitel** [comment]
\o/
