### ISSUE TITLE
Better error message when relabelling fail

### ISSUE THREAD

**Issue by DamienCassou** [containers/libpod#4515]
I've spent quite some time trying to understand why `podman run --volume /foo:/bar:Z` would fail:

```
Error: relabel failed "...": operation not permitted
```

After finding https://github.com/containers/libpod/issues/2379, I realized I had root-owned files in the directory being used as the volume on the host.

I would be great to have an error message a bit more explicit if that is possible.

Thank you so much for podman, it makes my life quite simpler.

**Comment by baude** [comment]
@DamienCassou would you like to propose a PR? We'd be happy to work with you.

**Comment by DamienCassou** [comment]
Brent Baude <notifications@github.com> writes:
> @DamienCassou would you like to propose a PR? We'd be happy to work
> with you.

I'm sorry but I won't do that. I have a lot on my plate for FLOSS
projects already :-).

Feel free to close the issue if no one wants to work on it.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by mheon** [comment]
I think we do the relabel ourselves so we could catch EPERM and wrap it
with a better error.

**Comment by rhatdan** [comment]
I just opened a PR on go-selinux to indicate the file that selinux failed to relabel, which would have made this a lot easie to diagnose.
https://github.com/opencontainers/selinux/pull/60

**Comment by rhatdan** [comment]
This is fixed in master.

**Comment by DamienCassou** [comment]
Daniel J Walsh <notifications@github.com> writes:
> This is fixed in master.

thank you!

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
