### ISSUE TITLE
projectatomic PPA repository has no Release file!

### ISSUE THREAD

**Issue by mido3ds** [containers/libpod#4520]
/kind bug

**Description**

Cant add the repo projectatomic to install podman on ubuntu18.10

**Steps to reproduce the issue:**
```
$ sudo add-apt-repository -y ppa:projectatomic/ppa
```
**Describe the results you received:**

```
E: The repository 'http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Distro info**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by lsm5** [comment]
cosmic is EOL'd already, so I didn't build for it. Might wanna uprade to disco and retry, or wait a while and give OBS repos a try ( not ready yet but will be soon).

See: https://github.com/containers/libpod/issues/1742#issuecomment-555061785

**Comment by rhatdan** [comment]
@mido3ds @lsm5 Can we close this issue?

**Comment by mido3ds** [comment]
Yes, sure. Sorry didn't have time to reply and close.
