### ISSUE TITLE
Containers in a pod without an infra container have different IP addresses

### ISSUE THREAD

**Issue by amshinde** [containers/libpod#4531]
I observed that containers in a pod without an infra container have different IP addresses and hostname. Shouldnt containers in a single pod have the same IP and share namespaces among them, regardless of infra container not being present?

**Comment by haircommander** [comment]
containers without infra can't currently share namespaces. It was originally planned to implement it, but it fell to the wayside

**Comment by haircommander** [comment]
a lot of the pod infrastructure relies on the infra container, for better or worse.

**Comment by mheon** [comment]
I believe they can share namespaces, but it is not at all enforced, and
works like any other container doing --net=container - you have to manually
share individual namespaces. Pods in libpod are a very loose collection of
containers, and without an infra container to keep them together they don't
share much at all.

**Comment by amshinde** [comment]
Ok, so sounds like this is mainly due to lack of cycles and not an inherent limitation. 
Containers in a pod are supposed to share network, ipc and uts namespaces all of which could be persisted without relying on any container being present.

**Comment by mheon** [comment]
"Supposed to" is a little strong... the original intent of a Pod in libpod was a loose group of containers that might or might not share containers. We've slowly drifted away from this, but I like keeping the convention that we don't force people to use an infra container and shared namespaces.

**Comment by rhatdan** [comment]
@mheon @haircommander Reading this, I am not sure if there are any action items?

**Comment by haircommander** [comment]
Yeah it seems this limitation is a consequence of design
