### ISSUE TITLE
`--tty` merges stdin and stderr

### ISSUE THREAD

**Issue by AloisMahdal** [containers/libpod#4532]
/kind bug

**Description**

Using `--tty` merges stdout and stderr of the command or `ENTRYPOINT`.

**Steps to reproduce the issue:**

 1. Build this `Dockerfile`:

        FROM fedora:30
        RUN { \
                echo "#!/bin/bash"; \
                echo "echo i am output; echo i am error >&2"; \
            }> /bin/test_oe
        RUN chmod +x /bin/test_oe
        ENTRYPOINT ["/bin/test_oe"]

 2. `podman run --rm -t $IMAGE_ID` 1>1 2>2

 3. `head 1 2`

**Describe the results you received:**

    ==> 1 <==
    i am output
    i am error

    ==> 2 <==

**Describe the results you expected:**

    ==> 1 <==
    i am output

    ==> 2 <==
    i am error

(It's what I get without `-t`).

**Additional information you deem important (e.g. issue happens only occasionally):**

I think `ENTRYPOINT` is not important in the reproducer; one would have
same problem without it and with running `test_oe` directly.

The use case is that my app generates data that needs to be parsed, so merging with
stderr (where it can post errors/info/debug) corrupts it.

Without `-t` it works mostly fine (save for aesthetics) but from what I've seen in
most of the docs, running with `-t` seems to be extremely common so I have to assume
that my users will use `-t`.

**Output of `podman version`:**

    Version:            1.6.2
    RemoteAPI Version:  1
    Go Version:         go1.12.10
    OS/Arch:            linux/amd64

**Output of `podman info --debug`:**

    debug:
      compiler: gc
      git commit: ""
      go version: go1.12.10
      podman version: 1.6.2
    host:
      BuildahVersion: 1.11.3
      CgroupVersion: v1
      Conmon:
        package: conmon-2.0.2-1.fc30.x86_64
        path: /usr/bin/conmon
        version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
      Distribution:
        distribution: fedora
        version: "30"
      IDMappings:
        gidmap:
        - container_id: 0
          host_id: (REDACTED)
          size: 1
        - container_id: 1
          host_id: 1738400
          size: 65536
        uidmap:
        - container_id: 0
          host_id: (REDACTED)
          size: 1
        - container_id: 1
          host_id: 1738400
          size: 65536
      MemFree: 2604322816
      MemTotal: 16189874176
      OCIRuntime:
        name: runc
        package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
        path: /usr/bin/runc
        version: |-
          runc version 1.0.0-rc9+dev
          commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
          spec: 1.0.1-dev
      SwapFree: 7786983424
      SwapTotal: 8589930496
      arch: amd64
      cpus: 8
      eventlogger: journald
      hostname: (REDACTED)
      kernel: 5.3.11-200.fc30.x86_64
      os: linux
      rootless: true
      slirp4netns:
        Executable: /usr/bin/slirp4netns
        Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
        Version: |-
          slirp4netns version 0.4.0-beta.2
          commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
      uptime: 10h 40m 25.19s (Approximately 0.42 days)
    registries:
      blocked: null
      insecure: null
      search:
      - docker.io
      - registry.fedoraproject.org
      - (REDACTED)
    store:
      ConfigFile: /home/(REDACTED)/.config/containers/storage.conf
      ContainerStore:
        number: 50
      GraphDriverName: overlay
      GraphOptions:
        overlay.mount_program:
          Executable: /usr/bin/fuse-overlayfs
          Package: fuse-overlayfs-0.6.5-2.fc30.x86_64
          Version: |-
            fusermount3 version: 3.6.2
            fuse-overlayfs: version 0.6.5
            FUSE library version 3.6.2
            using FUSE kernel interface version 7.29
      GraphRoot: /home/(REDACTED)/.local/share/containers/storage
      GraphStatus:
        Backing Filesystem: extfs
        Native Overlay Diff: "false"
        Supports d_type: "true"
        Using metacopy: "false"
      ImageStore:
        number: 12
      RunRoot: /run/user/(REDACTED)
      VolumePath: /home/(REDACTED)/.local/share/containers/storage/volumes

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

    podman-1.6.2-2.fc30.x86_64

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Regular Fedora 30.

**Comment by giuseppe** [comment]
unfortunately there is no way to understand whether the output on the tty is generated through stdout or stderr on the other end.

As you said, if you need to filter stdout/stderr then you need to drop `--tty`.
