### ISSUE TITLE
podman should check for newer versions of images when starting a new container 

### ISSUE THREAD

**Issue by QiWang19** [containers/libpod#4535]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1. podman pull $image

2. podman run $opts $image

3.

**Describe the results you received:**
podman will always use the locally available image without checking if there is a newer version

**Describe the results you expected:**

podman should (optionally) check for a newer version and (optionally) pull it if one is found

[Bug 1684263](https://bugzilla.redhat.com/show_bug.cgi?id=1684263)

**Comment by rhatdan** [comment]
@QiWang19 Still working on this?

**Comment by rhatdan** [comment]
@QiWang19 Please update.

**Comment by rhatdan** [comment]
@QiWang19 needs an update.

**Comment by QiWang19** [comment]
podman run --pull=always can always pull the new image and solve this issue.

**Comment by rhatdan** [comment]
We should add the --pull default into contianers.conf
