### ISSUE TITLE
possibility to set a proxy directly in podman instead of set the system wide environment variable

### ISSUE THREAD

**Issue by pirminjanka** [containers/libpod#4543]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

possibility to set a proxy directly in podman (e.g. podman config) instead of set the system wide environment variable (e.g. in /etc/profile)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64

RHEL8
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.4.2-stable2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 2863865856
  MemTotal: 4083748864
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 2
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: false
  uptime: 11m 56.22s
registries:
  blocked: null
  insecure: null
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-manpages-1.4.2-5.module+el8.1.0+4240+893c1ab8.noarch
podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtual

**Comment by alexcasutt** [comment]
+1

**Comment by rhatdan** [comment]
This is part of the containers/common containers.conf effort.

**Comment by rhatdan** [comment]
https://github.com/containers/common/pull/20

**Comment by rhatdan** [comment]
Still waiting for containers.conf to be merged.

**Comment by rhatdan** [comment]
Containers.conf is there.

**Comment by abpatwa** [comment]
> Podman will obey system proxy configuration from environment variables when pulling images. There is no way to disable this aside from clearing the environment variables when running Podman.

Thanks for the reply. offcourse any services follow/obey system proxy variable but there must be some way to exclude while podman runs (pull/run). For eg: curl command, we can test internet with and without proxy from his flags. It will really helpful if we try to found something like that. Because proxy is mandate on system for service runnig.

**Comment by rhatdan** [comment]
Does
http_proxy="" podman pull ...

Work for you?

**Comment by abpatwa** [comment]
> Does
> http_proxy="" podman pull ...
> 
> Work for you?

Dont Require this? It will work only without proxy as registry is inhouse-server. I need to exclude the proxy variable while run podman. With proxy variables its going over internet and then recvd error..

**Comment by rhatdan** [comment]
I don't understand, You can unset the environment or what ever to remove this.  These environment variables effect golang, not even something Podman understands.  We are not going to add an ignore the environment flag to Podman.

**Comment by abpatwa** [comment]
> I don't understand, You can unset the environment or what ever to remove this. These environment variables effect golang, not even something Podman understands. We are not going to add an ignore the environment flag to Podman.

As i said, we require internet service on that server i can disable the proxy on system as its will stop internet.  So require parameter to exclude the system proxy while running podman command for pull

**Comment by rhatdan** [comment]
NoProxy=true podman ...

Should satisfy this.

**Comment by abpatwa** [comment]
> NoProxy=true

It looks like not a valid Flag

Error: unknown flag: --Noproxy
Error: unknown flag: --noproxy

**Comment by rhatdan** [comment]
If you set the environment variable `no_proxy=*` will tell golang/podman to not use a proxy when connecting to https.

https://godoc.org/golang.org/x/net/http/httpproxy

```
    // NoProxy represents the NO_PROXY or no_proxy environment
    // variable. It specifies a string that contains comma-separated values
    // specifying hosts that should be excluded from proxying. Each value is
    // represented by an IP address prefix (1.2.3.4), an IP address prefix in
    // CIDR notation (1.2.3.4/8), a domain name, or a special DNS label (*).
    // An IP address prefix and domain name can also include a literal port
    // number (1.2.3.4:80).
    // A domain name matches that name and all subdomains. A domain name with
    // a leading "." matches subdomains only. For example "foo.com" matches
    // "foo.com" and "bar.foo.com"; ".y.com" matches "x.y.com" but not "y.com".
    // A single asterisk (*) indicates that no proxying should be done.
    // A best effort is made to parse the string and errors are
    // ignored.
    NoProxy string
```
