### ISSUE TITLE
"--device" should not resolve symbolic links

### ISSUE THREAD

**Issue by stefanb2** [containers/libpod#4550]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug  (well, could also be considered feature request, see below)

**Description**

Device numbering, e.g. for USB devices, is non-deterministic. Take f.ex. the use case of having two USB-to-serial devices connected via a hub to the host: it is not determined which of them will be `/dev/ttyUSB0` after disconnecting and reconnecting the hub from the host. In order for non-root users not to have to resort to root "magic incantations" the OS generates symbolic links with fixed names based on unique device properties as `/dev/serial/by-id/XXX`.

Unfortunately the `--device` option resolves the symbolic link, hence a container will be hard-coded to the real `/dev/ttyUSBx` that the symbolic link was pointing to at the time of the creation of the container. But on container restart that may be the wrong device or the device may no longer exist.

**Steps to reproduce the issue:**

```sh
# no devices connected
$ ls -lht /dev/serial/by-id

# connect device A (the one we want to use inside the container) -> ttyUSB0
$ ls -lht /dev/serial/by-id
lrwxrwxrwx. 1 root root 13 Nov 22 08:43 usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0 -> ../../ttyUSB0

# connect device B -> ttyUSB1
$ ls -lht /dev/serial/by-id
lrwxrwxrwx. 1 root root 13 Nov 22 08:43 usb-FTDI_FT230X_Basic_UART_DN03LNJE-if00-port0 -> ../../ttyUSB1
lrwxrwxrwx. 1 root root 13 Nov 22 08:43 usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0 -> ../../ttyUSB0

# create the container, passing in device A with the fixed name
# NOTE: SELinux / crun annotation required for rootless container
$ podman run -it --name alpine-serial --security-opt label=disable --annotation io.crun.keep_original_groups=1 --device /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0:/dev/ttyUSB0 alpine
/ # ls -lht /dev/ttyUSB*
crw-rw----    1 nobody   nobody    188,   0 Nov 22 06:43 /dev/ttyUSB0
/ # exit
$

# start the container again
$ podman start -ia alpine-serial
/ # ls -lht /dev/ttyUSB*
crw-rw----    1 nobody   nobody    188,   0 Nov 22 06:50 /dev/ttyUSB0
/ # exit
$

# remove device A & B
$ ls -lht /dev/serial/by-id

# connect device B -> ttyUSB0
$ ls -lht /dev/serial/by-id
lrwxrwxrwx. 1 root root 13 Nov 22 08:51 usb-FTDI_FT230X_Basic_UART_DN03LNJE-if00-port0 -> ../../ttyUSB0

# connect device A -> ttyUSB1
$ ls -lht /dev/serial/by-id
lrwxrwxrwx. 1 root root 13 Nov 22 08:51 usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0 -> ../../ttyUSB1
lrwxrwxrwx. 1 root root 13 Nov 22 08:51 usb-FTDI_FT230X_Basic_UART_DN03LNJE-if00-port0 -> ../../ttyUSB0

# remove device B(!!!) -> device A stays as ttyUSB1
$ ls -lht /dev/serial/by-id
lrwxrwxrwx. 1 root root 13 Nov 22 08:51 usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0 -> ../../ttyUSB1

# now start the container again
$ podman start -ia alpine-serial
Error: unable to start container 7fe07dafa43e6752be593710d1303a1180271f4b358433db6e5557b024ec5d0c: error stat'ing file '/dev/ttyUSB0': No such file or directory: OCI runtime command not found error
```

**Describe the results you received:**

Can't start the container again or get the wrong device unless I make sure that device A is assigned to `/dev/ttyUSB0`

**Describe the results you expected:**

Container should access device A using the symbolic link hence ensuring it is always talking to the correct device.

**Additional information you deem important (e.g. issue happens only occasionally):**

I see two ways this could be addressed:

* don't resolve the symbolic link (i.e. this is a bug)
* add a "don't follow symbolic link" flag to permissions (maybe follow `find -P` convention?), e.g. `--device /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DN03TPFH-if00-port0:/dev/ttyUSB0:rwP` (i.e. this is a feature request)

Or is this an OCI runtime issue? I couldn't find the device information when I used `podman inspect alpine-serial`.

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 7781224448
  MemTotal: 16461656064
  OCIRuntime:
    name: crun
    package: crun-0.10.5-2.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 15024144384
  SwapTotal: 20002631680
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: stefanb-lnx.localdomain
  kernel: 5.3.11-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 167h 41m 8.59s (Approximately 6.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/stefanb/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/stefanb/workarea/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 10
  RunRoot: /run/user/1000
  VolumePath: /home/stefanb/workarea/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

none

**Comment by giuseppe** [comment]
for the OCI runtime it should not matter as anyway the symlink is resolved at mount time.

I think we should store the original path provided to `--device` instead of resolving it, so that when we restart the container we'll resolve it again.

Would you like to open a PR for doing it?

**Comment by stefanb2** [comment]
I can probably look into the source code over the weekend.

**Comment by mheon** [comment]
The core issue is that we're not storing devices in the DB, but in the OCI spec, which only contains the major and minor numbers for each (plus the destination path). We don't know where the original source of the device was. To fix, we'd need to add devices to the database and add them to the container as part of final spec generation, but I'm not sure if I like that approach - shifts a lot of burden that normally only happens once to happen every time the container starts.

**Comment by rhatdan** [comment]
BTW, their might be a lot of changes coming the --device option way.
After discussions with nvidia and intel on their specialized GPUS for containers, they are looking to add a command like

podman device create foobar

and then 

podman run --device foobar

Where foobar gets translated into an actual device, after some code is run to configure the devices.

**Comment by mheon** [comment]
If we do that, can we please not overload the existing syntax? Adding a new flag is easy and doesn't make parsing overly complicated.

**Comment by rhatdan** [comment]
Except you have a different CLI then how you handle volumes, networks.  The hope is that nvidia and/or Intel work on this, since they are the experts.

**Comment by rhatdan** [comment]
@mheon @stefanb2 Do we still have this issue?

**Comment by stefanb2** [comment]
Unless the mentioned updates by Nvidia/Intel have been integrated the issue still exists.

If the consensus is that it can't/won't be fixed then I would suggest that the limitation is added to the documentation of the `--device` option.

**Comment by rhatdan** [comment]
@stefanb2 could you open a PR to fix the troublshooting guide on --device, and perhaps also fix the man pages.
