### ISSUE TITLE
Provide way to set up Podman for rootless with NFS home directories

### ISSUE THREAD

**Issue by adrianreber** [containers/libpod#4551]
In my article https://podman.io/blogs/2019/10/28/podman-with-nfs.html I described what is necessary to setup rootless Podman for users on NFS:

```
$ podman info
$ sed -e "s,graphroot.*$,graphroot = \"/tmp/centos/containers\",g" -i .config/containers/storage.conf
$ rm -f ./.local/share/containers/storage/libpod/bolt_state.db ./.local/share/containers/cache/blob-info-cache-v1.boltdb
```

With newer versions of Podman this is even more work as I have to set driver to "vfs" and actually remove the line `mountopt` (or `mount_program`) from storage.conf or else Podman will not work at all. I also have to change `runroot` in certain HPC like setups when running under slurm. Getting a system assigned via slurm means that the login usually does not go through the normal processes and `/run/user/ID` does not exist. Doing all the changes to storage.conf is doable for a test system but does not really scale when there are hundreds of users on the system. Therefore it would help if it would be possible to set this globally and whenever a user starts Podman it uses those global values to create storage.conf and friends.

This is probably related to https://github.com/containers/libpod/issues/3587

**Comment by giuseppe** [comment]
using NFS for the storage can't really work at the moment, since NFS is not user namespace aware.  It could in theory used as an additional ro store, but still there is need to provide correct files ownership before it can be used with rootless

**Comment by adrianreber** [comment]
> using NFS for the storage can't really work at the moment, since NFS is not user namespace aware. It could in theory used as an additional ro store, but still there is need to provide correct files ownership before it can be used with rootless

I know and that is not what this is about. Sorry if I gave that impression. What I wanted to ask for here is a way to globally configure Podman for all users to not use the home directory, because it is NFS based. There should be a global configuration option which tells Podman, for all rootless users, to user a certain non NFS directory. Like `/tmp/containers` for example.

Currently to do this I have to run the above commands for each user which does not really scale.

**Comment by giuseppe** [comment]
ah sorry for the misunderstanding.  It is not yet possible, but after the vork @vrothberg did to unify the config files, we could probably think of a way to set a template where the storage is created and set it once somewhere in `/etc/containers/`.

**Comment by rhatdan** [comment]
Yes this is the containers.conf stuff that is being worked on.

One thing we would need there is a mechanism to specify the homedir for rootless users

graphroot=$HOME/.local/share/containers/storage
And change it to 
graphroot=/var/tmp/$USER/containers/storage

And have to tools smart enough to substiture $HOME or $USER when setting up the storage.

**Comment by rhatdan** [comment]
I have a PR for this, but it is not tested in container/storage.

https://github.com/containers/storage/pull/518

This PR is totally untested, and needs work, when I get time, or if someone else grabs it and finishes it.

**Comment by rhatdan** [comment]
@QiWang19 is working on this.

**Comment by rhatdan** [comment]
We now have support for this on NFS Servers with rootless.  But we need a blog explaining how to do it.

Anyone want to take a stab at writing a blog.

**Comment by NikolausDemmel** [comment]
> We now have support for this on NFS Servers with rootless. But we need a blog explaining how to do it.

Does "this" mean "a config option to configure the storage to some place outside HOME", or "storage on NFS"?

**Comment by QiWang19** [comment]
@NikolausDemmel the storage path can be configured by setting `rootless_storage_path` in storage.conf, it's not required under `HOME` https://github.com/containers/storage/blob/master/docs/containers-storage.conf.5.md

**Comment by NikolausDemmel** [comment]
Ok, thanks for the quick response. So no storage on NFS yet (no problem).

**Comment by rhatdan** [comment]
@NikolausDemmel I don't expect there to be any NFS support for User Namespace for many years, most likely never.

**Comment by rhatdan** [comment]
@QiWang19 Let's write a blog on this together.

**Comment by NikolausDemmel** [comment]
OK got it. Thanks!

**Comment by rhatdan** [comment]
We wrote on this subject before, but it is time to update it.

https://www.redhat.com/sysadmin/rootless-podman-nfs

**Comment by QiWang19** [comment]
> We wrote on this subject before, but it is time to update it.
> 
> https://www.redhat.com/sysadmin/rootless-podman-nfs

ok, Let's do it. I can look at this first.
