### ISSUE TITLE
flakes in libpod/test/e2e/prune_test.go:54

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#4552]
In the recent past, I have seen the prune tests flaking often enough to justify tracking down the cause:

```
[+1666s] [Fail] Podman prune [It] podman container prune containers 
[+1666s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/prune_test.go:54
```

**Comment by mheon** [comment]
@vrothberg Do you think these were solved by the patch you landed? I can't recall seeing them recently

**Comment by vrothberg** [comment]
Yes, they are fixed now. Thanks for the ping!
