### ISSUE TITLE
podman play kube seccomp annotations don't function like k8s

### ISSUE THREAD

**Issue by haircommander** [containers/libpod#4555]
follow up issue to track

k8s yaml format parses a profile path like
localhost/<path> with a global value <seccomp_root> filled, whereas now this PR does localhost:<seccomp_root>/<path>

We can either hardcode the configuration path, add a flag to play kube to customize the path, or add a config value. I don't think it matters very much which we do, but I can imagine future users needing some sort of consistency with k8s here.

**Comment by rhatdan** [comment]
@baude @mheon WDYT?

**Comment by vrothberg** [comment]
I think we should be as close to K8s behavior as possible.

**Comment by rhatdan** [comment]
@haircommander can you open a PR to fix this?

**Comment by rhatdan** [comment]
@haircommander Any chance to work on this?
