### ISSUE TITLE
[Discussion] Names history support for images

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#4566]
Since https://github.com/containers/storage/pull/422 is merged I'd like to discuss how we would like to add this feature to libpod. Basically, we now have the information at hand which names an image had in the past (due to retag or untag), which allows two new use cases:

- [ ] Provide more information than the name `<none>` if a image got untagged
- [ ] Undo an image tag operation

Do we want to add an additional column to `podman images`, like `PREVOUS NAMES`?
Do we want to fallback to the names history if the image name would be `<none>`?

**Comment by vrothberg** [comment]
> Do we want to add an additional column to `podman images`, like `PREVOUS NAMES`?

Sounds good to me, but I would make it conditional via a CLI flag (--previous-names or --history etc.). Currently, the podman-images output is small enough to fit into a standard terminal size. Printing previous names by default, however, can lead to situations where a single image can render the output unreadable.

> Do we want to fallback to the names history if the image name would be `<none>`?

I would not change existing semantics/behavior.

**Comment by mheon** [comment]
Agree with Valentin here

**Comment by rhatdan** [comment]
--no-trunc could be modified to handle this.

**Comment by vrothberg** [comment]
> --no-trunc could be modified to handle this.

That would imply that we display a `PREVOUS NAMES` column by default which I wouldn't like to do for the aforementioned reasons - it would still clutter the current output.

**Comment by rhatdan** [comment]
I was thinking of using REPOs or TAGS for this.
Something like 
```
podman images --no-trunc
REPOSITORY                             TAG      IMAGE ID                                                                    CREATED       SIZE
<none>,docker.io/library/feodra <none> sha256:a2e245db8bd33174f8fe8cdeed17136905f76b789039ae42e455aabf6dc6d135
 5 weeks ago   5.82 MB
```

**Comment by saschagrunert** [comment]
I saw that there is some name preservation on image tagging: https://github.com/containers/libpod/blob/c2dfef544476dba671db3ef65b095da9ec18bbf1/libpod/image/image.go#L537-L544

that's also why the `Names` field is a slice :thinking:

...I'll spin up a PR in the next minutes, let's discuss the implementation details there. :+1:

**Comment by vrothberg** [comment]
Please wait before investing time. I like Dan's proposal but it would display wrong names as those are not valid references anymore.

**Comment by vrothberg** [comment]
> Please wait before investing time. I like Dan's proposal but it would display wrong names as those are not valid references anymore.

It might also break existing users parsing the output.

**Comment by saschagrunert** [comment]
> > Please wait before investing time. I like Dan's proposal but it would display wrong names as those are not valid references anymore.

Too late, I already spent time on this. :green_heart: 

> It might also break existing users parsing the output.

That was my concern too.

**Comment by rhatdan** [comment]
I am fine with the --history flag and the way you are doing it now. After playing with the Buildah version, I like this.
