### ISSUE TITLE
[podman] concurrent podman run --rm removes same container under fedora 31

### ISSUE THREAD

**Issue by NeroBurner** [containers/libpod#4567]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
when running `podman run --rm` concurrently sometimes there is an error message about a missing container. I suspect two container runs get the same id and are double deleted

**Steps to reproduce the issue:**

1. create a script to start concurrent podman runs
```bash
$ cat start_x_container.sh 
#!/bin/bash
IMAGE=ubuntu:bionic
podman pull ${IMAGE}
date -R
echo "start"
for i in $(seq 0 $1); do
        podman run --rm -t ${IMAGE} date -R &
done
wait
echo "finish"
```

2. start podman concurrently (9 concurrent threads in this example)
```
./start_x_container.sh 8
Trying to pull ubuntu:bionic...
Getting image source signatures
Copying blob 45d437916d57 skipped: already exists
Copying blob 7ddbc47eeb70 skipped: already exists
Copying blob c1bbdc448b72 skipped: already exists
Copying blob 8c3b70e39044 skipped: already exists
Copying config 7753497586 done
Writing manifest to image destination
Storing signatures
775349758637aff77bf85e2ff0597e86e3e859183ef0baba8b3e8fc8d3cba51c
Tue, 26 Nov 2019 14:29:07 +0000
start
Tue, 26 Nov 2019 14:29:08 +0000
Tue, 26 Nov 2019 14:29:09 +0000
Tue, 26 Nov 2019 14:29:09 +0000
Tue, 26 Nov 2019 14:29:10 +0000
Tue, 26 Nov 2019 14:29:10 +0000
Tue, 26 Nov 2019 14:29:10 +0000
Tue, 26 Nov 2019 14:29:11 +0000
Tue, 26 Nov 2019 14:29:10 +0000
Tue, 26 Nov 2019 14:29:11 +0000
ERRO[0003] Error removing container 10e3c73c817789626f5d3756e060bf7157715e219bda113c24b27570d03ba3ad: container 10e3c73c817789626f5d3756e060bf7157715e219bda113c24b27570d03ba3ad does not exist in database: no such container 
finish
```

**Describe the results you received:**
2 out of 5 times I get one or two error messages like the following
```
ERRO[0003] Error removing container 10e3c73c817789626f5d3756e060bf7157715e219bda113c24b27570d03ba3ad: container 10e3c73c817789626f5d3756e060bf7157715e219bda113c24b27570d03ba3ad does not exist in database: no such container 
```

**Describe the results you expected:**
podman should run and destroy containers concurrently without a hiccup

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 6690500608
  MemTotal: 8148983808
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8283746304
  SwapTotal: 8283746304
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: builder-f31
  kernel: 5.3.11-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 49m 53.07s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/builder/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7-1.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/builder/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/builder/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
kvm+qemu virtual machine set-up with virtmanager

**Comment by rhatdan** [comment]
When you run a container we cleanup in a script being executed by conmon, `podman cleanup`.  Which could definitely cause this issue.
I thought that we had special cased the --rm to kill the container when not using the `-d` flag.
@mheon thoughts?

**Comment by mheon** [comment]
They're definitely not getting the same ID. This is almost certainly the cleanup process race.

For `podman run --rm`, we will attempt to remove the container in two ways when it exits: from the main Podman process (`podman run` that is attached to the container), and from the "cleanup process" (a separate Podman spawned when the container exits to handle cleanup). We need the extra cleanup process incase you decide to detach from the container at some point, causing the main `podman run` to exit while the container is still running (the process could also be killed, or suffer an error, etc) - it guarantees that the container will be removed.

Normally, if the two are both active, `podman run` always wins, removing the container first (it's a keyboard-interactive process, so it gets first priority on CPU time from the kernel). Adding `&` to the end removes that special interactive priority, so suddenly it's an even race between the two, and sometimes (maybe even most of the time) `podman run` loses, and we get this error message, which isn't really an error; the container is definitely gone, and I believe that `podman run` will still exit without an error. We ought to consider dropping that to a warning.

**Comment by rhatdan** [comment]
```
		if err := r.Runtime.RemoveContainer(ctx, ctr, false, true); err != nil {
			if errors.Cause(err) == define.ErrNoSuchCtr {
				logrus.Warnf("Container %s does not exist: %v", ctr.ID(), err)
			} else {
				logrus.Errorf("Error removing container %s: %v", ctr.ID(), err)
			}
		}
```
Looks like we shouldbe handling this.

**Comment by mheon** [comment]
It's trying to catch `ErrNoSuchCtr` but it's printing an error including `no such container` which seems very suspicious...

**Comment by mheon** [comment]
Might need to also catch `ErrCtrRemoved`?

**Comment by mheon** [comment]
Looks like @rhatdan fixed this one, closing
