### ISSUE TITLE
"make uninstall" only removes manpages?

### ISSUE THREAD

**Issue by yegle** [containers/libpod#4572]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It looks like the "make uninstall" only removes manpages, but not configs, binaries.

**Steps to reproduce the issue:**

1. make install
2. make uninstall

**Describe the results you received:**
`podman` binary is still in `/usr/local/bin/podman`

**Describe the results you expected:**
Binaries (and also configs) should all be removed by running `make uninstall`.

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/containers/libpod/blob/master/Makefile#L444 not sure if this is WAI though.

**Output of `podman version`:**
n/a

**Output of `podman info --debug`:**
n/a

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm at git HEAD (f5ef3d59bcc7e7beae8716ab10153e1eafd634c1).

**Comment by rhatdan** [comment]
Please open a PR to fix it...
