### ISSUE TITLE
rawhide/rootless: "cannot configure rootless cgroup"

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4574]
Looks like the container-selinux bug is fixed; rootless gating tests are now [failing](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/7586/pipeline/#step-250-log-923) with:
```
$ podman do-something
cannot configure rootless cgroup using the cgroupfs manager
...followed by expected output...
```
podman-1.6.4-0.40.dev.git27a09f8.fc32.x86_64

**Comment by rhatdan** [comment]
Rootless containers are supposed to be using systemd cgroup manager.

**Comment by giuseppe** [comment]
that error is coming from crun, and it should not happen with recent versions of crun.

What version are you using?

**Comment by giuseppe** [comment]
I was able to reproduce locally, looking at it..

**Comment by giuseppe** [comment]
it is a warning printed by crun, but not the error message.

The best would be to take the last line of the output, or check that the expected line is included in of the ouput, instead of a direct comparison

**Comment by rhatdan** [comment]
Is it being printed to stderr?

**Comment by giuseppe** [comment]
yes it is printed to stderr.

PR here: https://github.com/containers/libpod/pull/4576

**Comment by giuseppe** [comment]
I am not sure that covers all the cases.  But at least now the ouput is less confusing if we want to detect when the executable is not found.

I don't think we should put too much effort into using the cgroupfs manager on Rawhide.  We want rootless to use systemd so that cgroups can be properly delegated.  Can we change the tests to do it?

**Comment by edsantiago** [comment]
> Can we change the tests to [use `cgroup_manager = "systemd"`]

Can you suggest an exact recipe to do this? i.e.: should this be hardcoded into the command-line podman invocation for all commands? Should the pre-test setup create `$user/.config/containers/libpod.conf`? How exactly would you recommend that this take place?

**Comment by giuseppe** [comment]
> Can you suggest an exact recipe to do this? i.e.: should this be hardcoded into the command-line podman invocation for all commands? Should the pre-test setup create `$user/.config/containers/libpod.conf`? How exactly would you recommend that this take place?

if you'd like we can work on this together.  I am not really familiar with your environment, but I am afraid the most difficult part is how we can create the user session.  Maybe setting lingering more first?

**Comment by edsantiago** [comment]
Linger is already enabled. This is the rawhide/rootless stanza that runs the tests:
```
       run: loginctl enable-linger fedora; su -c ${PWD}/test_podman.sh - fedora
```
I'm on build cop duty today, and completely overwhelmed, so I won't be able to work on this any more until Monday.
