### ISSUE TITLE
rootless podman should have to use a non-root cert directory too

### ISSUE THREAD

**Issue by lfarkas** [containers/libpod#4577]
/kind feature

podman pull/push/sign use the /etc/containers/certs.d (and also /etc/docker/certs.d) for looking up client cert for connecting to a given registry. but in rootless podman case it's not really good way that a user should have to copy certs into system directory (or always use --cert-dir command line option) . 
it'd be very useful to treat cert as other settings and in rootless mode also scan the ~/.config/containers/certs.d and every user can put his own certs into his own directory. what's more in this case the .key file shouldn't have to be system wide readable.

**Comment by rhatdan** [comment]
SGTM, Would you be interested in opening a PR to implement this?

**Comment by mheon** [comment]
I kind of suspect the fix needs to live in containers/image. But I don't know if the rootless detection code is able to be imported there (I know it lives in containers/common now, but I'm not sure if we can use that in c/image, the start of our import chain).

**Comment by lfarkas** [comment]
> SGTM



> SGTM, Would you be interested in opening a PR to implement this?

imho those who knows the code can do it much faster them me:-)

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
@vrothberg Actually this has to be wired through containers/image correct?

**Comment by vrothberg** [comment]
> @vrothberg Actually this has to be wired through containers/image correct?

I believe so, yes. Especially when it comes to default behavior, we should let c/image decide.

**Comment by rhatdan** [comment]
PR https://github.com/containers/image/pull/817

**Comment by rhatdan** [comment]
Since this is merged, it is in master branch.
