### ISSUE TITLE
rhel-8 and centos-8 rpms are missing gpgme

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4580]
Apparently there are at several missing dependencies for building libpod rpms on RHEL8/CentOS8:

```
btrfs-progs-devel
glibc-static
go-md2man
gpgme-devel  # gpgme is but it does not install gpgme.h
libassuan-devel
libgpg-error-devel
libgpg-error-devel
```

**Comment by mheon** [comment]
I think you just need to use the `btrfs_noversion` and `exclude_graphdriver_btrfs` tags to remove btrfs, which is entirely removed.

The rest are (AFAIK) distributed in other streams on RHEL, but are present somewhere.

**Comment by mheon** [comment]
(Except maybe go-md2man)

**Comment by ssbarnea** [comment]
@mheon Thanks for the hint, clearly helped a lot.. Now I am stuck at
```
# github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:4:11: fatal error: gpgme.h: No such file or directory
 // #include <gpgme.h>
``` 
What trick do I need to pass that one?

**Comment by rhatdan** [comment]
@mtrmac Ideas?

**Comment by rhatdan** [comment]
Could you open a bugzilla on that gpgme to see what they suggest?

**Comment by mtrmac** [comment]
> gpgme-devel  # gpgme is but it does not install gpgme.h

That would explain the failure.

WRT asking for the files to be included, that needs to go through the same process as any other build requirement packages (which may or may not result in them being added, to set expectations).

The dependency can be avoided with the `containers_image_openpgp` Go tag; then the code will not support signing (only verification).

**Comment by ssbarnea** [comment]
We bypassed the rpm building by disabling gpgme support but this bug should stay open until we will include gpgme support in the rpm.

**Comment by thomasmckay** [comment]
I've just encountered not being able to install `gpgme-devel` on `centos:8` base image, is there a link somewhere that I can watch how this will be resolved? (I understand not related to libpod project but am a bit desperate to find solution.)

**Comment by mtrmac** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1726861 (note, that is primarily about a _different_ package) says:
> gpgme-devel is available on CentOS 8 in the PowerTools repository.
> The CentOS PowerTools has all the packages found in the RHEL8 codeready-builder-for-rhel-8-x86_64-rpms (aka: codeready-builder) repository.
>
> dnf --enablerepo=PowerTools list gpgme-devel

Do note that using the CodeReady-Builder repository on RHEL probably has significant impact on the amount of support you can get from Red Hat for the related activities.

**Comment by baude** [comment]
@ssbarnea can we close this or ?

**Comment by ssbarnea** [comment]
AFAIK, no because at this moment we build it without gpgme feature. This would be ok to close when we address this aspect. PRs are welcomed here.

**Comment by mtrmac** [comment]
PRs to what? This Podman repository? Packaging somewhere?

The link above says that the gpgme-devel package is available, although in a repo that may have to be explicitly enabled. Is that incorrect?

**Comment by rhatdan** [comment]
I don't see this as an upstream issue.

**Comment by greenbergphssedu** [comment]
@rhatdan , the `gpgme-devel` is not in RHEL8 repositories.

```
Last metadata expiration check: 0:03:26 ago on Tue 10 Mar 2020 02:08:41 PM EDT.
=================================================================== Name Exactly Matched: gpgme ====================================================================
gpgme.x86_64 : GnuPG Made Easy - high level crypto API
gpgme.x86_64 : GnuPG Made Easy - high level crypto API
gpgme.i686 : GnuPG Made Easy - high level crypto API
================================================================== Name & Summary Matched: gpgme ===================================================================
gpgmepp.i686 : C++ bindings/wrapper for GPGME
gpgmepp.x86_64 : C++ bindings/wrapper for GPGME
qgpgme.x86_64 : Qt API bindings/wrapper for GPGME
qgpgme.i686 : Qt API bindings/wrapper for GPGME
gpgme-debugsource.x86_64 : Debug sources for package gpgme
gpgme-debugsource.i686 : Debug sources for package gpgme
gpgme-debuginfo.i686 : Debug information for package gpgme
gpgme-debuginfo.x86_64 : Debug information for package gpgme
qgpgme-debuginfo.i686 : Debug information for package qgpgme
qgpgme-debuginfo.x86_64 : Debug information for package qgpgme
gpgmepp-debuginfo.x86_64 : Debug information for package gpgmepp
gpgmepp-debuginfo.i686 : Debug information for package gpgmepp
gpgme-devel-debuginfo.x86_64 : Debug information for package gpgme-devel
gpgme-devel-debuginfo.i686 : Debug information for package gpgme-devel
====================================================================== Summary Matched: gpgme ======================================================================
python3-gpg.x86_64 : gpgme bindings for Python 3
python3-gpg.x86_64 : gpgme bindings for Python 3
```

**Comment by greenbergphssedu** [comment]
> AFAIK, no because at this moment we build it without gpgme feature. 

@ssbarnea , how do you disable building `gpgme`? I tried using tag `exclude_gpgme` to no avail.

```
GO111MODULE=on go build -mod=vendor \
-gcflags 'all=-trimpath=/root/dev/go/src/github.com/containers/libpod' \
-asmflags 'all=-trimpath=/root/dev/go/src/github.com/containers/libpod' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=173f430852e52a1acf69b4d9d18da20893031a79 -X github.com/containers/libpod/libpod/define.buildInfo=1583864245 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc -extldflags ""' -tags " exclude_graphdriver_btrfs btrfs_noversion selinux  exclude_graphdriver_devicemapper seccomp varlink exclude_pgpgme" -o bin/podman github.com/containers/libpod/cmd/podman
```

**Comment by greenpau** [comment]
> AFAIK, no because at this moment we build it without gpgme feature. 

@ssbarnea , how do you disable building `gpgme`? I tried using tag `exclude_gpgme` to no avail.

```
GO111MODULE=on go build -mod=vendor \
-gcflags 'all=-trimpath=/root/dev/go/src/github.com/containers/libpod' \
-asmflags 'all=-trimpath=/root/dev/go/src/github.com/containers/libpod' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=173f430852e52a1acf69b4d9d18da20893031a79 -X github.com/containers/libpod/libpod/define.buildInfo=1583864245 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc -extldflags ""' -tags " exclude_graphdriver_btrfs btrfs_noversion selinux  exclude_graphdriver_devicemapper seccomp varlink exclude_pgpgme" -o bin/podman github.com/containers/libpod/cmd/podman
```

**Comment by rhatdan** [comment]
@mtrmac ^^

**Comment by mtrmac** [comment]
See https://github.com/containers/libpod/issues/4580#issuecomment-575918453 , but I haven’t personally verified that. If the package is missing and you need it, please use your RHEL support options.

The tag to use would be, as mentioned in https://github.com/containers/libpod/issues/4580#issuecomment-561084164  , `containers_image_openpgp`.

**Comment by greenpau** [comment]
@mtrmac , @mtrmac , thank you!

For anyone interested, here are my steps building `podman`:

```
cd ${GOPATH}/src/github.com && mkdir -p containers
cd containers && git clone https://github.com/containers/libpod.git
cd libpod
make BUILDTAGS="containers_image_openpgp exclude_graphdriver_btrfs btrfs_noversion selinux  exclude_graphdriver_devicemapper exclude_seccomp varlink "
./bin/podman -v
```

**Comment by mrbrandao** [comment]
> @mtrmac , @mtrmac , thank you!
> 
> For anyone interested, here are my steps building `podman`:
> 
> ```
> subscription-manager repos --enable=rhel-8-for-x86_64-appstream-rpms
> yum -y install libseccomp libseccomp-devel
> cd ${GOPATH}/src/github.com && mkdir -p containers
> cd containers && git clone https://github.com/containers/libpod.git
> cd libpod
> make BUILDTAGS="containers_image_openpgp exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper selinux seccomp varlink "
> ./bin/podman -v
> ```

on RHEL8 after installing the libseccomp I also had to force the pkg-config path to find the `libseccomp.pc' file.    
Like:

```bash
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig"
make BUILDTAGS="containers_image_openpgp exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper selinux seccomp varlink "
```
