### ISSUE TITLE
make validate and make lint are too verbose

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4581]
Currently, `make validate` and `make lint` do output >900 lines of boilerplate output and often a failure is hidden among them, making quite hard to use, especially for a commands that should be run on any commit.

Ideally each of this command should not output more than ~10 lines of code and any error or warning should be easy to read by the user (colors maybe). 

One make source of spam is git-validation tasks which prints "successes" and that runs even on changes that were already merged to master branch.

Another issue that makes the output harder to read is make itself which, for historical reasons, does not follow the practice of printing errors on stderr instead of stdout. Sadly I doubt there is anything we can do in this area.

**Comment by rhatdan** [comment]
Would you be interested in opening a PR to quiet the output down.  Perhaps filtering out the "success" messages...

**Comment by baude** [comment]
closing
