### ISSUE TITLE
unable to close conn

### ISSUE THREAD

**Issue by nitrocode** [containers/libpod#4585]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot close connection to container once run interactively

**Steps to reproduce the issue:**

1. Run alpine container

        podman  run -it --rm docker.io/library/alpine /bin/sh

2. Then exit

        / # exit

This doesn't work and I have to hit Ctrl + C to exit.

**Describe the results you received:**

> ERRO[0002] unable to close conn: "close unixpacket @->/run/user/1000/libpod/tmp/socket/b96520808e7f77e03d4869f225c9841b9418863d9ea5b68f60a0fd008b41c40d/attach: use of closed network connection"

**Describe the results you expected:**

Exit container without having to run Ctrl + C

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
✗ podman version                                        
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
✗ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: linuxmint
    version: "18.3"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 4203626496
  MemTotal: 16760188928
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 17119047680
  SwapTotal: 17119047680
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: user-All-Series
  kernel: 4.15.0-70-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.1
      commit: unknown
  uptime: 22h 38m 39.18s (Approximately 0.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/user/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
✗ apt list podman 
Listing... Done
podman/xenial,now 1.6.2-1~ubuntu16.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This works fine on Fedora 31, I would figure this is a problem with the conmon package and podman package interaction.

@giuseppe @haircommander @mheon Thoughts?

**Comment by giuseppe** [comment]
it seems like the latest conmon is installed but the version output seems incorrect (missing commit).  How was conmon installed?  It might just be an issue in the way we build the package

**Comment by rhatdan** [comment]
I think this is a build issue, so I am going to close, Reopen if I am mistaken.

**Comment by buckley310** [comment]
For posterity; I can reliably recreate this issue on 1.6.3, but not on 1.7.0. Seems like that fixed it. It's also not ubuntu/mint specific.
