### ISSUE TITLE
podman run --entrypoint handled differently compare to docker

### ISSUE THREAD

**Issue by yegle** [containers/libpod#4595]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I was able to have `--entrypoint="sh -c '...'"` with docker just fine, but it looks like podman assumes the `--entrypoint` is specifying a binary path in contrast to a full command.

**Steps to reproduce the issue:**

1. Run the following:

```
podman run -it \
        --entrypoint="/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" \
        docker://certbot/dns-cloudflare:latest
```

**Describe the results you received:**
```
Error: container_linux.go:346: starting container process caused "exec: \"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 17813{!}; done;'\": stat /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 17813{!}; done;': no such file or directory": OCI runtime command not found error
```

**Describe the results you expected:**
It should allow me to use that command as entrypoint.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 293355520
  MemTotal: 1031737344
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: ip-172-31-4-114
  kernel: 4.15.0-1051-aws
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 2h 39m 53.72s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/ubuntu/.config/containers/storage.conf
  ContainerStore:
    number: 5
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/ubuntu/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 3
  RunRoot: /run/user/1000
  VolumePath: /home/ubuntu/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/bionic,now 1.6.2-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

In case it's useful, the machine is an AWS EC2 VM with official Ubuntu 18.04 LTS image.

**Comment by mheon** [comment]
I believe we expect entrypoint, when passed on the command line, to be either a single path or a JSON-formatted array or arguments, so `["bin/sh", "-c", "..."]` should work.

**Comment by yegle** [comment]
An easy workaround would be:

```
podman run -it \
        --entrypoint=sh \
        docker://certbot/dns-cloudflare:latest \
         -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;'
```

**Comment by rhatdan** [comment]
@yegle @mheon so is this a bug or not?

**Comment by ecks** [comment]
I ran into this issue as well. Looks like there is a cmd format and an exec format for entrypoint, which are two different things. By default it will use cmd format, meaning it will execute the entrypoint using "sh -c", however you can opt out of that and have the entrypoint command executed directly by enclosing it in brackets.

Maybe the docs need to be annotated to account for that?

**Comment by mheon** [comment]
I think we probably should rewrite `--entrypoint` to match the way we parse `ENTRYPOINT` - try a JSON decode, and if that fails use it as an argument to `sh -c`.

**Comment by mheon** [comment]
Need to verify that matches Docker, though

**Comment by mheon** [comment]
The given entrypoint doesn't work on my Docker; what version are you using?

**Comment by rhatdan** [comment]
Since we have had no response from @yegle I am going to close this issue. Please reopen if this is still needed.

**Comment by yegle** [comment]
Sorry for not responding earlier.

The original issue was raised when using a `docker-compose.yaml` with the following content on `podman-compose`:

```
services:
  certbot:
    image: docker.io/certbot/dns-cloudflare
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```

This works with `docker-compose` but not `podman-compose`. Let me file a bug to `podman-compose` repo.

**Comment by SN4K3D** [comment]
Thanks a lot @mheon for your first response its working for me
