### ISSUE TITLE
podman run --detach to hang when triggered form a django app

### ISSUE THREAD

**Issue by parmentelat** [containers/libpod#4600]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am new to podman; I was running a docker-backed web service under fedora29, and like others I realize that the upgrade path with docker is unclear, so I am giving this a shot

When serving a http client request, that goes from nginx to django, that spawns a bash script which in turn invokes:  
`podman run --rm --detach --user root` *`a very long argument list`*

My issue is simple; if i run that long command (see typical usage below) directly in a terminal, `podman run` behaves as I expect, it prints out a container hash and returns immediately

However as soon as this same command gets triggered from within the django app, it hangs; 

**Steps to reproduce the issue:**

1. not sure really, short of setting up a complete django app, so I am at a loss to give detailed instructions here

**Describe the results you received:**

the typical state of my system once `podman run` has been issued looks like this (the uwsgi process hosts the django app)

```
# pstree -p
<snip>
                └─uwsgi(67890)───nbh(68504)───podman(68640)─┬─3(68753)
                                                            ├─{podman}(68641)
                                                            ├─{podman}(68642)
                                                            ├─<snip>another 25 similar lines or so

# ps -w 68640
    PID TTY      STAT   TIME COMMAND
  68640 ?        Sl     0:00 podman run --name python3-s2-x-student-0004 -p 52043:8888 --user root --rm --detach --env NBAUTOEVAL_LOG=/home/jovyan/work/.nbautoeval <snip>

# ps 68753
    PID TTY      STAT   TIME COMMAND
  68753 ?        S      0:03 /usr/bin/crun start 52898f113dd66bf6711d94287e0f3c22adaced1211ef623062028585038e80aa

# strace -p 68753
strace: Process 68753 attached
select(4, [3], NULL, NULL, {tv_sec=0, tv_usec=2001}) = 0 (Timeout)
kill(68751, 0)                          = 0
select(4, [3], NULL, NULL, {tv_sec=0, tv_usec=10000}) = 0 (Timeout)
kill(68751, 0)                          = 0
<snip>
```

and at that point I can no longer run `podman ps` that hangs too.

it looks like that `crun start` process is trying to read from some file descriptor; 
this is unexpected because of the `--detach` option;
I have made various attempts on the django side to make double sure that all possible inputs were closed, explicitly redirecting `stdin` to `/dev/null` and setting `close_fds=True` in Python's `subprocess.run()`, to no avail.

**Describe the results you expected:**

because I specify the `--detach` option, I do not expect `podman run` to hang

**Additional information you deem important (e.g. issue happens only occasionally):**

typical full command
```
podman run --name python3-s2-x-student-0004 -p 52043:8888 --user root --rm --detach --env NBAUTOEVAL_LOG=/home/jovyan/work/.nbautoeval -v /nbhosting/dev/students/student-0004/python3-s2:/home/jovyan/work -v /nbhosting/dev/jupyter/python3-s2/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py:ro -v /nbhosting/dev/jupyter/python3-s2:/home/jovyan/.jupyter/custom:ro -v /nbhosting/dev/modules/python3-s2:/home/jovyan/modules:ro -v /nbhosting/dev/static/python3-s2:/home/jovyan/static:ro -v /nbhosting/dev/courses-git/python3-s2:/nbhosting/dev/courses-git/python3-s2:ro -e PYTHONPATH=/home/jovyan/modules python3-s2 start-in-dir-as-uid.sh /home/jovyan 100333 jupyter notebook --ip=0.0.0.0 --no-browser --NotebookApp.notebook_dir=/home/jovyan/work --NotebookApp.token=python3-s2-x-student-0004 --NotebookApp.base_url=/52043/ --log-level=DEBUG
```
**Output of `podman version`:**

```
podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 247907241984
  MemTotal: 270380605440
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 32
  eventlogger: journald
  hostname: thermals
  kernel: 5.3.12-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 2h 12m 55.85s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /nbhosting/containers
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 28
  RunRoot: /var/run/containers/storage
  VolumePath: /nbhosting/containers/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

this is physical box

**Comment by giuseppe** [comment]
can you please show the output for `strings /proc/68753/env` (where 68753 is the PID for `crun start`).

I am afraid there is a `NOTIFY_SOCKET` environment variable being leaked that is enabling the systemd notify socket support

**Comment by parmentelat** [comment]
> On 29 Nov 2019, at 15:49, Giuseppe Scrivano <notifications@github.com> wrote:
> 
> can you please show the output for strings /proc/68753/env (where 68753 is the PID for crun start).
> 
> I am afraid there is a NOTIFY_SOCKET environment variable being leaked that is enabling the systemd notify socket support

good catch:

root@thermals ~ (master *) # ps 94700
    PID TTY      STAT   TIME COMMAND
  94700 ?        S      0:18 /usr/bin/crun start 6d5acc12e08ef2dbc76e77e8d2c51ca6324854d803d2334d63d800714b47c344

root@thermals ~ (master *) # strings /proc/94700/environ
XDG_RUNTIME_DIR=/run/user/0
NOTIFY_SOCKET=/run/systemd/notify
_LIBCONTAINER_CLONED_BINARY=1

—
is it enough for me to add `—env NOTIFY_SOCKET=` to the arguments to `podman run`  ?

**Comment by parmentelat** [comment]
answering my own question:

is it enough for me to add `—env NOTIFY_SOCKET=` to the arguments to `podman run` ?

the answer is no, which of course makes sense  
I might not need any assistance from podman to erase that env variable, I'll tweak my code and report if/how i manage to take care of that

**Comment by parmentelat** [comment]
I just had to add
```
unset NOTIFY_SOCKET
```
in my bash script prior to triggering `podman run` and poof, that solved my issue !

thanks a million because at the time when I resorted to filing that bug I was about to bang my head against the screen ;)

**Comment by parmentelat** [comment]
just a final word on this; I had actually seen that `NOTIFY_SOCKET` thingy mentioned some place else; I can't remember where exactly but I do remember there was also a mention of gnome, and for that reason, I thought that would not apply to me b/c this box has no graphical desktop nor anything of that sort; it's just been used as a chromium headless test box at some point, so all I have in this area is 

```
# rpm -aq | egrep -i 'gnome|x11'
gnome-keyring-3.34.0-1.fc31.x86_64
xorg-x11-fonts-misc-7.5-23.fc31.noarch
xorg-x11-font-utils-7.5-42.fc31.x86_64
libX11-1.6.8-3.fc31.x86_64
libgnome-keyring-3.12.0-18.fc31.x86_64
libX11-common-1.6.8-3.fc31.noarch
```

all this to say that it could help others to document how this variable ends up in my environment...

**Comment by giuseppe** [comment]
you could invoke Podman without that env variable being set.  So something like `NOTIFY_SOCKET= podman run .....`.  Although it would be nice to know why that is happening.  Some process is leaking that variable to Podman and it should not happen

**Comment by parmentelat** [comment]
> Although it would be nice to know why that is happening. Some process is leaking that variable to Podman and it should not happen

well, this here:
https://www.freedesktop.org/software/systemd/man/sd_notify.html#Notes

suggests otherwise, i.e. it suggests on the contrary that it is to be expected that my code, being itself triggered by systemd, has this variable set; 

it more feels the other way around, I mean to say, the fact that podman depends on that variable being set or not, feels terribly wrong

or what am I missing ?

**Comment by rhatdan** [comment]
If this variable is set, Podman expects the process inside of the container to write to the socket, if it never writes to the socket Podman will just hang.
Systemd will only set the socket in a notify unit file, I believe, which indicates to Podman that you expect this behaviour.

**Comment by parmentelat** [comment]
> If this variable is set, Podman expects the process inside of the container to write to the socket, if it never writes to the socket Podman will just hang.
> Systemd will only set the socket in a notify unit file, I believe, which indicates to Podman that you expect this behaviour.

until I read your answer I was not even aware of the existence of ‘notify’ unit files

indeed, in my setup I found that uwsgi, which hosts my django app, is configured that way

# grep notify /usr/lib/systemd/system/uwsgi.service
Type=notify

and it turns out, the django app is the one that spawns the ‘podman run’ process, so I guess that’s how I end up with the the env. variable being set..

so, as far as I am concerned unset’ting the variable seems like the way to go 

thanks for the clarification !
