### ISSUE TITLE
rpm/deb repository for podman?

### ISSUE THREAD

**Issue by jonasbartho** [containers/libpod#4612]
Hi,

Is there any way possible for podman to have rpm and deb packages of the latest podman version on a remote repository URL(incl. all necessary dependencies...)? 

Example with docker community-edition: https://download.docker.com/linux/centos/7/x86_64/stable

**Comment by ssbarnea** [comment]
I think that we will have this soon. It happens that I am currently working on multi-platform building or rpm, and jobs will produce repositories. I guess it will be very easy to make an official repo once we get these sorted.

**Comment by jonasbartho** [comment]
awesome @ssbarnea !!!, that would help me and many others a great deal promoting podman(instead of docker) in their companies! Please send me a ping when this is available!

Kind regards,
Jonas
