### ISSUE TITLE
run --rmi? [feature] to clean extracted container image

### ISSUE THREAD

**Issue by onlyjob** [containers/libpod#4628]
I'm running the following command for the first time:

    podman run -it --rm oci-archive:debian10.oci /bin/echo "Hi"

And after execution an extracted image is left behind:

~~~~
$ podman images
REPOSITORY                 TAG      IMAGE ID       CREATED       SIZE
<none>                     <none>   834dd85c5b99   3 hours ago   162 MB
~~~~

It would be great to have an option like `--rmi` to clean-up such unpacked/pulled image.

Thanks.

**Comment by vrothberg** [comment]
This sounds like a great enhancement to me. In case the image is being used by another container, I suggest to ignore the error that it couldn't be removed.

**Comment by mheon** [comment]
Agree. Do we also want to restrict it so we only remove the image if it was not already present?

**Comment by rhatdan** [comment]
Since @onlyjob brought up the Idea, I will let him answer it.  I personally could go either way.

**Comment by onlyjob** [comment]
Thanks. I think implementation should carefully check if image is being used but always remove unused images even if they existed before.

Extracted image is just a "cache" and when user explicitly requestd to drop cache with `--rmi` I think it would be best to do just that.

**Comment by rhatdan** [comment]
Sounds reasonable.  @onlyjob Would you be interested in adding a PR?

**Comment by onlyjob** [comment]
Of course you've asked for PR, as always. :)

I'm not qualified and have no time to implement even if I could...

**Comment by rhatdan** [comment]
If you don't ask, you never know if someone will say yes.  Thanks for the suggestion.

**Comment by bipuladh** [comment]
@rhatdan I want to take up this issue.

**Comment by vrothberg** [comment]
> @rhatdan I want to take up this issue.

Thanks! I assigned the issue to you. Feel free to reach out here or on the #podman channel on Freenode if you have any questions.

**Comment by rhatdan** [comment]
Excellent @bipuladh Looking forward to the PR.

**Comment by mheon** [comment]
Being worked on, I believe

**Comment by vrothberg** [comment]
@bipuladh, did you find time to look into this issue?

**Comment by bipuladh** [comment]
@vrothberg I stopped because there is a PR https://github.com/containers/libpod/pull/4772 that works on this issue.

**Comment by vrothberg** [comment]
> @vrothberg I stopped because there is a PR #4772 that works on this issue.

Sorry for not noticing earlier! I dropped a comment that already assigned issues should not be picked up without communicating it.

**Comment by boaz0** [comment]
@bipuladh I am really sorry that I missed your comment asking to work on this. If you want you can continue working from where I stopped (I don't mind mentoring you - contact me via email: bshuster -at- redhat).

@vrothberg this wasn't intentionally and I'm really sorry. I know it's my fault that I didn't read the thread carefully but may I suggest adding the "assigned" tag to issues so I could filter unassigned issues?

Again, I feel bad and am sorry. If there is anything I can do to fix this, let me know.
Thanks.

**Comment by vrothberg** [comment]
That's an honest mistake, which can happen. Don't worry, @boaz0! I think you should continue working on it, given there's already the open PR.

> [...]  may I suggest adding the "assigned" tag to issues so I could filter unassigned issues?

Did you have a look at GitHub search syntax (see below)? I believe it's possible to look for unassigned issues. Anyhow, even a label still requires to read the issue and the comments.

https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests

**Comment by boaz0** [comment]
@vrothberg - that's actually cool, I didn't know Github has its own search syntax. 
Thank you.

**Comment by rhatdan** [comment]
@boaz0 Are you still working on this, or did it get merged?

**Comment by boaz0** [comment]
@rhatdan still working on this - close to completion

**Comment by mheon** [comment]
I'll try and do a final review in prep for merge after lunch
