### ISSUE TITLE
builds are broken: go-md2man unavailable

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4632]
#4616 broke [rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=39424289) -- and, presumably, all koji/brew -- builds:
```
if [ ! -x "/builddir/build/BUILD/libpod-5c3af009c6027429d60f6e73bf3ade346ec3d410/_output/bin/go-md2man" ]; then \
	   	env GO111MODULE=off go get -u github.com/cpuguy83/go-md2man; \
fi
# cd .; git clone -- https://github.com/cpuguy83/go-md2man /builddir/build/BUILD/libpod-5c3af009c6027429d60f6e73bf3ade346ec3d410/_output/src/github.com/cpuguy83/go-md2man
Cloning into '/builddir/build/BUILD/libpod-5c3af009c6027429d60f6e73bf3ade346ec3d410/_output/src/github.com/cpuguy83/go-md2man'...
fatal: unable to access 'https://github.com/cpuguy83/go-md2man/': Could not resolve host: github.com
package github.com/cpuguy83/go-md2man: exit status 128
make: *** [Makefile:490: .install.md2man] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.953d7H (%install)
```
Sorry, but it will have to be reverted. The koji/brew build environment is network-isolated and cannot run `go fetch`.

**Comment by TomSweeneyRedHat** [comment]
UGH, my main concern here is how the PR to make this change passed.  We must not use changes in Makefile that are in a PR when testing the PR?

**Comment by edsantiago** [comment]
The PR passed because the build happens in CI-land, not koji-land. Koji-land is different. This really couldn't have been caught in CI.

**Comment by ssbarnea** [comment]
More than happy to help address this. Still, the reality is that we are talking about a regression happening on a specific case that is not covered in CI. That is the real bug: if we want to avoid this from happening we need to be sure we have a CI job running that runs in an isolated environment. That would be a good start.

Apparently my PR uncovered a but at https://github.com/containers/libpod/blob/master/Makefile#L490 where the desired behavior should be install command if not found *anywhere* -- as it could be installed at system level via a rpm.

I will make a PR to address this, is likely a one-liner.
