### ISSUE TITLE
RFE: predictable port generation

### ISSUE THREAD

**Issue by whitel** [containers/libpod#4633]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

One thing that is nice about Docker's port generation is that you can guess what it will be (sometimes). Basically, when you are launching container after container trying to get something to work, in docker, your generated port number will keep counting up. As a result, you can easily test by just changing the port number in the browser or on your command line from the last run. 

Podman, as far as I can tell, chooses pretty random port numbers. 

**Steps to reproduce the issue:**

1. launch apache container with "-P" and see port assigned (e.g. podman run -d -P httpd)
1. do it again
1. note that the ports generated are wildly different

**Output of `podman version`:**

```
podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Comment by baude** [comment]
please explain how this helps users? the current algo is faster than counting imho so it would be a weighing of performance against user benefit.

**Comment by whitel** [comment]
I thought I had: being able to predict the port number makes the frustration of making a container work the first time lower because you don't have to look up the port every time you launch a container. 

Definitely a minor improvement but I recently went through this while trying to get something to work, ran through 20-30 containers and had to look up the port to change in the browser every time. With docker, I didn't have to look up the port which made one less step in the "code, build, test" cycle.

**Comment by rhatdan** [comment]
I would bet this is difficult from the nature of CNI.  Since each exec is different.
I would figure this would be fairly easy to script using the 

```
podman run -d -p 80 fedora sleep 300
6c2895e9b7e41845e62d1d5293afecda1ed86e3911f35d8d2ed9e5a0f5316ad8
$ podman inspect -l -f '{{ .NetworkSettings.Ports }}'
[{35751 80 tcp }]
```
A little additional awking and you get your port.
