### ISSUE TITLE
podman denies opening a file for writing as root owned by a different user on /tmp

### ISSUE THREAD

**Issue by cfelder** [containers/libpod#4649]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman denies opening a file for writing as root owned by a different user on /tmp

(2500661 4 drwxrwxrwt 1 root root 4096 Dec  5 16:56 /tmp)

**Steps to reproduce the issue:**

1. start container as root: ``podman run --rm -it centos:centos8 /bin/bash``

2. create a file on /tmp, change ownership, open file for writing

``touch /tmp/a && chown mail:mail /tmp/a && vi /tmp/a`` _(actually write something to it in vi and exit :x)_ - **fails**

or

``touch /tmp/a && chown mail:mail /tmp/a && python3 -c "open('/tmp/a', 'w')"`` - **fails**
(but requires installing python3 beforehand: ``dnf install -y python3``

whereas shell redirection works

``touch /tmp/a && chown mail:mail /tmp/a && echo "foo" > /tmp/a`` - **succeeds**

3. do the same steps on docker - **succeeds**

**Describe the results you received:**

``PermissionError: [Errno 13] Permission denied: '/tmp/a'``

**Describe the results you expected:**

_changed file contents_

**Additional information you deem important (e.g. issue happens only occasionally):**

* selinux on fedora-30 Podman host is disabled

```
[root@fedora-30 ~]# getenforce
Disabled
```

* disabling seccomp doesn't resolve this issue

```
podman run --security-opt aaseccomp=unconfined --rm -it centos:centos8 /bin/bash
```

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.2-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 243286016
  MemTotal: 4120739840
  OCIRuntime:
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9+dev
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev
  SwapFree: 4261670912
  SwapTotal: 4265603072
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: fedora-30
  kernel: 5.3.11-200.fc30.x86_64
  os: linux
  rootless: false
  uptime: 242h 25m 39.11s (Approximately 10.08 days)
registries:
  blocked: null
  insecure:
  - jenkinsng.admin.frm2
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
  - registry.redhat.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 10
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

fedora-30 VM is running on macOS Parallels host system

**Comment by mheon** [comment]
@rhatdan @baude @vrothberg @giuseppe PTAL - looked at this one for a while in IRC, came away stumped

**Comment by cfelder** [comment]
> 3. do the same steps on docker - **succeeds**

I just installed docker on my f30 VM and tried again and it **fails** as well whereas it doesn't fail in my docker environment on my macOS host. Must be an issue with the configuration of the host system though.

**Comment by vrothberg** [comment]
Just to double check: it only fails in vi when trying to write? Opening works?

**Comment by cfelder** [comment]
Yes and shell redirection does:

```
openat(AT_FDCWD, "a", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "a", O_WRONLY|O_TRUNC) = 3
```

**Comment by cfelder** [comment]
apparently this fails on the fedora-30 host in general

``touch /tmp/a && chown mail:mail /tmp/a && vi /tmp/a``

or

``touch /tmp/a && chown mail:mail /tmp/a && python3 -c "open('/tmp/a', 'w')"``

**Comment by giuseppe** [comment]
that is controlled by the `fs.protected_regular` sysctl.

Can you try `sysctl fs.protected_regular=0` and see if it changes the result you get?

**Comment by cfelder** [comment]
@giuseppe This resolves the issue on the host as well as on the container. Thanks.

**Comment by rhatdan** [comment]
This is not a podman issue.
