### ISSUE TITLE
pause.pid not cleaned up when podman killed by jenkins

### ISSUE THREAD

**Issue by kedmison** [containers/libpod#4655]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am using podman commands, in a rootless mode, in a Jenkins pipeline.  the second and subsequent execution of the pipeline fails with an error.  
```
$ podman images
ERRO[0000] cannot join pause process.  You may need to remove /run/user/10007/libpod/pause.pid and stop all containers
ERRO[0000] you can use `system migrate` to recreate the pause process
ERRO[0000] open /proc/31749/ns/user: no such file or directory
```

I monitored the pause.pid file and the process it represented.  I could see both the file being created and the process being created, when podman commands were first executed.  The podman daemon stayed around until the very end of the Jenkins job, at which time the process disappeared (potentially deliberately cleaned up by Jenkins?).  The pause.pid file remained in place.

**Steps to reproduce the issue:**

1. enable rootless podman use for Jenkins user. 

2. create a Jenkins pipeline that executes podman commands.  I used a remote build worker, and 'sh' steps to execute podman in a shell script context.

**Describe the results you received:**

- The podman daemon died, and the timing of the process death was around the same time that the complete Jenkins pipeline ended (note: not the stage in which the podman commands were run.)  
- Second and subsequent jenkins builds failed due to the presence of the pause.pid file without the actual matching process.
- Manual deletion of the pause.pid file was enough to make the next build succeed (but only the next build, as the problem conditions were re-created).

**Describe the results you expected:**
Repeatable podman operations using a Jenkins pipeline.  
Whether this is by not killing podman, or by podman death cleaning up the pause.pid file in a 'nice' shutdown, is open.

**Output of `podman version`:**

```
podman version 1.4.4
```

**Output of `podman info --debug`:**

```
$ podman info --debug
ERRO[0000] cannot join pause process.  You may need to remove /run/user/10007/libpod/pause.pid and stop all containers
ERRO[0000] you can use `system migrate` to recreate the pause process
ERRO[0000] open /proc/31749/ns/user: no such file or directory
```
it happened ;) after cleaning up the pause file, I got this.
```
$ rm -v /run/user/$UID/libpod/pause.pid; podman info --debug
removed ‘/run/user/10007/libpod/pause.pid’
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 16598474752
  MemTotal: 33469374464
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 16035250176
  SwapTotal: 16756240384
  arch: amd64
  cpus: 8
  hostname: turing.ca.alcatel-lucent.com
  kernel: 3.10.0-1062.4.3.el7.x86_64
  os: linux
  rootless: true
  uptime: 119h 37m 57.31s (Approximately 4.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/jenkins/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/jenkins/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 21
  RunRoot: /run/user/10007
  VolumePath: /home/jenkins/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-1.4.4-4.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical workstation, E5-1620 v3, 32GB RAM, CentOS Linux release 7.7.1908

**Comment by mheon** [comment]
@giuseppe Don't we have code for recreating the pause process if it's dead as of 1.6.x? I believe I remember that being added

**Comment by mheon** [comment]
In a brief test, it appears Podman master will recreate the pause process if it has died in the interim. Closing as this is fixed upstream.

**Comment by kedmison** [comment]
Is there any harm in testing for the presence of the pause.pid process, and directly deleting the file if the process is gone?  I need something to make my pipelines work, rather than wait until I get a podman 1.6.x distribution...

**Comment by mheon** [comment]
I believe that should be fine.
