### ISSUE TITLE
using the podman Python API freezes it all

### ISSUE THREAD

**Issue by parmentelat** [containers/libpod#4656]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I need to use the Python API to monitor the running containers; what I observe at this point is:

#### before
* from terminal 1, running `podman ps` works instantaneously; `pgrep podman` returns no entry

#### trigger the issue
* in terminal 2, I start a Python interpreter and simply run 

```
with podman.Client() as client:
   ...:     list(client.containers.list())
```

**Describe the results you received:**

#### after
* the Python command does not return and hangs forever
* similarly a `podman ps` command at that point in terminal 1 hangs as well
* `pgrep podman` exhibits one process
```
ps $(pgrep podman)
    PID TTY      STAT   TIME COMMAND
 328282 ?        Ssl   32:03 /usr/bin/podman varlink unix:/run/podman/io.podman --timeout=60000
```

**Describe the results you expected:**

I expect the Python statement to return very quickly with a list of my running containers, and `podman ps` to be able to list running containers at all times

**Additional information you deem important (e.g. issue happens only occasionally):**

As far as I can tell this happens every time.

I am experiencing this on the same vanilla f31 box as the one that exhibited #4600, and at first I thought this could even be related; however a pretty version of `/proc/328282/environ` shows this

```
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
LISTEN_PID=328282
LISTEN_FDS=1
LISTEN_FDNAMES=io.podman.socket
INVOCATION_ID=230f954c0ac44788ba4e3917d55dae01
JOURNAL_STREAM=9:2071639
```

Maybe relevant also, the way I have configured podman wrt systemd is to have both units `io.podman.service` and `io.podman.socket` enabled

Finally, an `strace` session on that 328282 varlink thingy reports an endless stream of 

```
<snip> 
futex(0xc0004ca4c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x562dbb0259e8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x562dbb0259e8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
<snip>
```

**Output of `podman version`:**

```
podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 178932133888
  MemTotal: 270380605440
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 32
  eventlogger: journald
  hostname: thermals
  kernel: 5.3.12-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 190h 51m 35.83s (Approximately 7.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 104
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /nbhosting/containers
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 28
  RunRoot: /var/run/containers/storage
  VolumePath: /nbhosting/containers/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -aq | grep podman
podman-docker-1.6.2-2.fc31.noarch
podman-manpages-1.6.2-2.fc31.noarch
podman-1.6.2-2.fc31.x86_64
# pip freeze | grep podman
podman==1.6.0
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical box running vanilla fedora31; upgraded from at least fedora27, used to run docker instead of podman

it feels like I have something grossly misconfigured..

**Comment by parmentelat** [comment]
I have just tried to replace the pip-installed podman module with the one I just noticed in dnf

```
 1027  pip uninstall podman
 1028  dnf install python3-podman-api
```

but observe the very same behaviour

**Comment by parmentelat** [comment]
@jwhonce if you'd like any additional information, please feel free to ask - thanks !

**Comment by parmentelat** [comment]
I would appreciate any kind of feedback on this issue, that is a hard stopper for me

I would happily need to know at least 
* whether this is a bug indeed, 
* or whether I am misinterpreting something and am having wrong expectations about how the system behaves

thanks !

**Comment by rhatdan** [comment]
Are you running the python as root?  The service is listening as root, and should only be communicated with via root.

**Comment by parmentelat** [comment]
Yes everything is run locally from within the f31 box, and everything runs as root at this point

**Comment by rhatdan** [comment]
@jwhonce Ideas?

**Comment by parmentelat** [comment]
if that's of any interest I am presently on irc and available for any fumbling about that could help shedding any light on this

**Comment by parmentelat** [comment]
I've been trying to understand this issue a little better on my side

((for the record I have taken the time to completely wipe out the podman install, i.e. rpm uninstalled, cleaned the containers area completely, in short scrubbed as much as I could before reinstalling))

I need to amend the issue topic; turns out the Python API call **does return eventually** after a **very long while**; here's the code that I run on the Python side

```
In [6]: def bench():
   ...:     now = time.time()
   ...:     with podman.Client() as client:
   ...:         containers = list(client.containers.list())
   ...:     print(containers)
   ...:     duration = time.time()-now
   ...:     print(f"took {duration:2g}s")
```

and, the `containers` variable comes up with **valid information** (at that time I have a single container running) :

```
In [7]: bench()
[{'id': 'dda5ec297950654b2088e7ef884a5305f5f656bbecdeba909ca4cdb02c67594b', 'image': 'localhost/python3-s2:latest', 'imageid': '9479daf896a7bc30e390bf4dde68f5e763bda0fa7d263a183617029255a3a436', 'command': ['tini', '-g', '--', 'start-in-dir-as-uid.sh', '/home/jovyan', '100277', 'jupyter', 'notebook', '--ip=0.0.0.0', '--no-browser', '--NotebookApp.notebook_dir=/home/jovyan/work', '--NotebookApp.token=python3-s2-x-57f9dd0f5709a11d694073f0c3d11fdf', '--NotebookApp.base_url=/43493/', '--log-level=DEBUG'], 'createdat': '2020-01-07T19:19:09Z', 'runningfor': '14h35m13.968377532s', 'status': 'running', 'ports': [{'host_port': '43493', 'host_ip': '', 'protocol': 'tcp', 'container_port': '8888'}], 'rootfssize': 4206911091, 'rwsize': 308451205, 'names': 'python3-s2-x-57f9dd0f5709a11d694073f0c3d11fdf', 'labels': {'maintainer': 'Jupyter Project <jupyter@googlegroups.com>'}, 'mounts': [{'destination': '/home/jovyan/.jupyter/jupyter_notebook_config.py', 'type': 'bind', 'source': '/nbhosting/dev/jupyter/python3-s2/jupyter_notebook_config.py', 'options': ['ro', 'rprivate', 'rbind']}, {'destination': '/home/jovyan/.jupyter/custom', 'type': 'bind', 'source': '/nbhosting/dev/jupyter/python3-s2', 'options': ['ro', 'rprivate', 'rbind']}, {'destination': '/home/jovyan/modules', 'type': 'bind', 'source': '/nbhosting/dev/modules/python3-s2', 'options': ['ro', 'rprivate', 'rbind']}, {'destination': '/home/jovyan/static', 'type': 'bind', 'source': '/nbhosting/dev/static/python3-s2', 'options': ['ro', 'rprivate', 'rbind']}, {'destination': '/nbhosting/dev/courses-git/python3-s2', 'type': 'bind', 'source': '/nbhosting/dev/courses-git/python3-s2', 'options': ['ro', 'rprivate', 'rbind']}, {'destination': '/home/jovyan/work', 'type': 'bind', 'source': '/nbhosting/dev/students/57f9dd0f5709a11d694073f0c3d11fdf/python3-s2', 'options': ['rw', 'rprivate', 'rbind']}, {'destination': '/proc', 'type': 'proc', 'source': 'proc', 'options': ['nosuid', 'noexec', 'nodev']}, {'destination': '/dev', 'type': 'tmpfs', 'source': 'tmpfs', 'options': ['nosuid', 'strictatime', 'mode=755', 'size=65536k']}, {'destination': '/dev/pts', 'type': 'devpts', 'source': 'devpts', 'options': ['nosuid', 'noexec', 'newinstance', 'ptmxmode=0666', 'mode=0620', 'gid=5']}, {'destination': '/dev/mqueue', 'type': 'mqueue', 'source': 'mqueue', 'options': ['nosuid', 'noexec', 'nodev']}, {'destination': '/sys', 'type': 'sysfs', 'source': 'sysfs', 'options': ['nosuid', 'noexec', 'nodev', 'ro']}, {'destination': '/sys/fs/cgroup', 'type': 'cgroup', 'source': 'cgroup', 'options': ['rprivate', 'nosuid', 'noexec', 'nodev', 'relatime', 'ro']}], 'containerrunning': True, 'namespaces': {'user': '4026531837', 'uts': '4026533015', 'pidns': '4026533017', 'pid': '87567', 'cgroup': '4026531835', 'net': '4026532759', 'mnt': '4026533014', 'ipc': '4026533016'}, 'running': True}]
took 113.915s
```

several measurements exhibit a duration for the API call that all are in the 110-120s range:
```
took 118.627s
took 113.915s
took 113.431s
took 115.71s
```

I'm having a hard time figuring what can possibly cause the API to hold the data for so long, especially considering that it eventually serves it allright ...

***

I was also, probably unrelated but still, a bit curious about this `timeout` setting below
In which circumstances exactly is that timeout likely to trigger ?
should I try messing with that ?


```
systemctl cat io.podman.service
# /usr/lib/systemd/system/io.podman.service
[Unit]
<snip>

[Service]
Type=simple
ExecStart=/usr/bin/podman varlink unix:%t/podman/io.podman --timeout=60000
TimeoutStopSec=30
KillMode=process

[Install]
<snip>
```

**Comment by parmentelat** [comment]
now, if instead of running one of my containers, I spawn one in a simpler way

```
podman run -ti --rm ubuntu
```

then in this case the API behaves more or less as expected

```
In [6]: bench()
[{'id': '91530acb3301b6d8ed03f57c8952d6500200fd76638b4236fa380ee095439405', 'image': 'docker.io/library/ubuntu:latest', 'imageid': '549b9b86cb8d75a2b668c21c50ee092716d070f129fd1493f95ab7e43767eab8', 'command': ['/bin/bash'], 'createdat': '2020-01-08T14:21:38+01:00', 'runningfor': '7.801287879s', 'status': 'running', 'ports': [], 'rootfssize': 64194718, 'rwsize': 0, 'names': 'practical_montalcini', 'labels': {}, 'mounts': [{'destination': '/proc', 'type': 'proc', 'source': 'proc', 'options': ['nosuid', 'noexec', 'nodev']}, {'destination': '/dev', 'type': 'tmpfs', 'source': 'tmpfs', 'options': ['nosuid', 'strictatime', 'mode=755', 'size=65536k']}, {'destination': '/dev/pts', 'type': 'devpts', 'source': 'devpts', 'options': ['nosuid', 'noexec', 'newinstance', 'ptmxmode=0666', 'mode=0620', 'gid=5']}, {'destination': '/dev/mqueue', 'type': 'mqueue', 'source': 'mqueue', 'options': ['nosuid', 'noexec', 'nodev']}, {'destination': '/sys', 'type': 'sysfs', 'source': 'sysfs', 'options': ['nosuid', 'noexec', 'nodev', 'ro']}, {'destination': '/sys/fs/cgroup', 'type': 'cgroup', 'source': 'cgroup', 'options': ['rprivate', 'nosuid', 'noexec', 'nodev', 'relatime', 'ro']}], 'containerrunning': True, 'namespaces': {'user': '4026531837', 'uts': '4026533015', 'pidns': '4026533017', 'pid': '353875', 'cgroup': '4026531835', 'net': '4026532759', 'mnt': '4026533014', 'ipc': '4026533016'}, 'running': True}]
took 0.943457s
```

although a duration of nearly 1s to probe for one single container does sound odd, it's clearly more workable than almost minutes :)

so this points at the way the container is started

I could try and isolate what differences, in the ways both containers are started, that triggers the problem; any recommendation as to what could be the most likely culprit here ?

**Comment by parmentelat** [comment]
as per @jwhonce instructions on irc, I have tried to run `podman inspect -s` on both containers

the outcome is that on the regular ubuntu container `inspect -s` returns relatively fast, while on my custom containers it hangs for the approximate same duration as the API call

when *strace*'ing that `podman inspect` process, I can see a great many deal of calls to `futex()`like typically 

```
<snip>
sched_yield()                           = 0
futex(0x5634b261bc30, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x5634b261bc30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5634b261bd48, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=100000}) = -1 EAGAIN (Resource temporarily unavailable)
epoll_pwait(4, [], 128, 0, NULL, 140736723234360) = 0
futex(0xc000ab4148, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5634b2646520, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5634b261bc30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5634b26289e8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x5634b26289e8, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0xc0004fa148, FUTEX_WAKE_PRIVATE, 1) = 1epoll_pwait(4, [], 128, 0, NULL, 140736723234360) = 0
<snip>
```

**Comment by parmentelat** [comment]
@mheon 
`podman mount` on the custom container returns quickly within 1/10 s

**Comment by parmentelat** [comment]
as a conclusion on this issue, it seems that the time taken by the API call is mostly spent in figuring the hard-disk space used by the container

an evidence of that is the presence of `'rootfssize': 64194718` in the data structure returned by the API

Transfering to podman-python to see if there is / suggest a way for the API call to specify that this information is not needed

https://github.com/containers/python-podman/issues/72
