### ISSUE TITLE
Rootless podman doesn't recognize cgroupv2 mount at /sys/fs/cgroups/unified

### ISSUE THREAD

**Issue by trusch** [containers/libpod#4659]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
If I run for example `podman stats` it reports that this doesn't work because I'm rootless and not using cgroupv2.

When looking up how it checks if I'm using cgroupsv2 I see that it looks for the mount type of /sys/fs/cgroups, but is not inspecting /sys/fs/cgroups/unified.

The cgroups man-page even states that `... on many modern systems, systemd(1) automatically mounts the cgroup2 filesystem at /sys/fs/cgroup/unified during the boot process. `

**Steps to reproduce the issue:**

1. Be on an arch system. My cgroup related mounts look like this:
```
 tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
```

2. Run `podman stats` as normal user

**Describe the results you received:**

`Error: stats is not supported in rootless mode without cgroups v2`

**Describe the results you expected:**

podman should start streaming stats

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.3
RemoteAPI Version:  1
Go Version:         go1.13.4
Git Commit:         9d087f6a766259ba53b224944f1b7b778035c370-dirty
Built:              Sat Nov 23 12:56:15 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 9d087f6a766259ba53b224944f1b7b778035c370-dirty
  go version: go1.13.4
  podman version: 1.6.3
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: eb5fa88c26fde5ce1e3f8a1d2a8a9498b2d7dbe6'
  Distribution:
    distribution: arch
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  MemFree: 24207544320
  MemTotal: 33396453376
  OCIRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9
      commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: archlinux
  kernel: 5.4.2-arch1-1
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.2
      commit: 69153b0d1cb82216d6782179ff7c3c5e91c731a1
  uptime: 2h 12m 29.76s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/tino/.config/containers/storage.conf
  ContainerStore:
    number: 12
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.8.0
        fuse-overlayfs: version 0.7
        FUSE library version 3.8.0
        using FUSE kernel interface version 7.31
  GraphRoot: /home/tino/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 11
  RunRoot: /run/user/1000
  VolumePath: /home/tino/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
> pacman -Q podman
podman 1.6.3-1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Kernel: Linux archlinux 5.4.2-arch1-1

**Comment by mheon** [comment]
@giuseppe PTAL - looks like our cgroups package isn't detecting the mount?

**Comment by giuseppe** [comment]
if cgroup v2 is mounted on `/sys/fs/cgroup/unified` then it is not the unified hierarchy where cgroup v2 is mounted at `/sys/fs/cgroup`.  That is the `hybrid` hierarchy where cgroup v1 and cgroup v2 coexist.

We don't support that.

More details can be found here: https://systemd.io/CGROUP_DELEGATION.html#three-different-tree-setups-
