### ISSUE TITLE
podman cp as root fails on centos 7 version (1.4.4) of podman to cp from host to container

### ISSUE THREAD

**Issue by Amjadhpc** [containers/libpod#4662]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

 I am running the podman version that comes with centos 7 on home directory that are mounted on gpfs filesystem . Hence running as root.

**Steps to reproduce the issue:**

1.podman pull docker://nvcr.io/hpc/namd:2.13-singlenode
.

2.podman images | grep namd
nvcr.io/hpc/namd        2.13-singlenode   17ca6780eca0   9 months ago   372 MB
 ls /mnt
apoa1_nve_cuda.namd

podman  cp   /mnt/apoa1_nve_cuda.namd  namd:2.13-singlenode:/mnt/

**Describe the results you received:**

Error: invalid arguments /mnt/apoa1_nve_cuda.namd, namd:2.13-singlenode:/mnt/ you must use just one container

**Describe the results you expected:**

just cp file from host to container
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

(paste your output here)
```
podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

**Output of `podman info --debug`:**

```
(paste your output here)
```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 390952685568
  MemTotal: 404709134336
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 33764143104
  SwapTotal: 33764143104
  arch: amd64
  cpus: 24
  hostname: g02.hpc.private
  kernel: 3.10.0-1062.1.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 428h 13m 40.73s (Approximately 17.83 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-1.4.4-4.el7.centos.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
HOME DIR on GPFS FS . Hence running as root on GPU  node

**Comment by vrothberg** [comment]
@mheon, do you know when a more recent Podman hits CentOS 7? I believe the CP bug has been fixed in more recent versions.

**Comment by mheon** [comment]
I think 1.6.3 is landing in 7.8? Not sure of the timeframe there

**Comment by vrothberg** [comment]
@jnovy @lsm5, do you know ~ETA?

**Comment by rhatdan** [comment]
I would figure this lines up with Summit.  IE March/April time frame.

**Comment by rhatdan** [comment]
Since this is not an upstream issue, closing.
