### ISSUE TITLE
rpm packaging should run on any incoming PR

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#4669]
In order to avoid breaking the packaging (rpm for now) I would like to get approval to enable running rdo-check 3rd party CI jobs on any incoming PR instead of manually triggering them using the magic `check-rdo` comment.

Me and the others from tripleo-ci team will continue to keep an eye on these jobs and be considered the maintainers of them. They run in ~5 minutes, and we could easily add extra tests if we want (now is only `make package-install`).

In fact running these jobs on each PR does mean that a failure of these jobs **would not block libpod workflow.** This only happened once accidentally while we were configuring the github integrations.

This morning we already enabled periodic runs of these jobs and you can see the full build history:

* https://review.rdoproject.org/zuul/builds?job_name=podman-package-centos-8
* https://review.rdoproject.org/zuul/builds?job_name=podman-package-fedora-30
* https://review.rdoproject.org/zuul/builds?job_name=podman-package-rhel-8

**Comment by TomSweeneyRedHat** [comment]
I like the idea!

**Comment by baude** [comment]
lgtm

**Comment by chkumar246** [comment]
+1

**Comment by raukadah** [comment]
+1

**Comment by jnovy** [comment]
Sounds good!

**Comment by EmilienM** [comment]
LGTM, very good idea. We'll see how that works out but for sure it'll bring good feedback.

**Comment by rhatdan** [comment]
Sure what do we need to do?

**Comment by ssbarnea** [comment]
You do not need to do anything, mainly we will activate this by merging https://review.rdoproject.org/r/#/c/24032/ -- posting it here so others may find the place that controls it.

**Comment by ssbarnea** [comment]
I am closing this as it was activated few minutes ago. Feel free to reopen or comment if you spot any issues.
