### ISSUE TITLE
rawhide: --security-opt label=disable incorrect context

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4673]
On rawhide:
```console
# podman run --security-opt label=disable alpine cat /proc/self/attr/current; echo
unconfined_u:unconfined_r:unconfined_t:s0 (expected: unconfined_u:system_r:spc_t:s0)

# ls -lZ /usr/bin/podman
-rwxr-xr-x. 1 root root system_u:object_r:bin_t:s0 57442952 Dec  7 18:13 /usr/bin/podman
```
Also affects `buildah run`.

podman-1.6.4-0.69.dev.git7287f69.fc32
crun-0.10.6-1.fc32
container-selinux-2.123.0-0.3.dev.git0b25a4a.fc32
libselinux-3.0-1.fc32
selinux-policy-3.14.5-18.fc32

**Comment by mheon** [comment]
@rhatdan PTAL

I thought we expected to be unconfined when label=disable was passed?

**Comment by edsantiago** [comment]
Ugh; bad copypasta. I have edited the initial post to `unconfined_u:system_r:spc_t`. @mheon, thanks for catching that.

**Comment by rhatdan** [comment]
The issue is podman is mislabelled.
restorecon -v /usr/bin
If this does not change the label, then something failed when container-selinux was installed
yum reinstall -y container-selinux

**Comment by edsantiago** [comment]
Weird - it's not failing on today's VM:
```console
# ls -lZ /usr/bin/podman
-rwxr-xr-x. 1 root root system_u:object_r:container_runtime_exec_t:s0 57452032 Dec  9 11:14 /usr/bin/podman
```
container-selinux today is `2.123.0-0.4.dev.git0b25a4a.fc32`, up from `-0.3` yesterday. I'll assume something got fixed.
