### ISSUE TITLE
podman run --security-opt label=type:svirt_qemu_net_t : AVC

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4685]
```console
# podman run --rm --security-opt label=type:svirt_qemu_net_t alpine date
standard_init_linux.go:211: exec user process caused "permission denied"
# echo $?
1
```
AVC is:
```
type=AVC msg=audit(1576158540.639:47074): avc:  denied  { transition } for  pid=16008 comm="runc:[2:INIT]" path="/bin/busybox" dev="overlay" ino=1626763 scontext=unconfined_u:system_r:container_runtime_t:s0 tcontext=system_u:system_r:svirt_qemu_net_t:s0:c259,c674 tclass=process permissive=0
```
Found when testing 1.7.0 but also seems to be present in 1.6.2 and possibly older.

**Comment by rhatdan** [comment]
This is what is supposed to happen.  svirt_qemu_net_t is a VM selinux type not a container type.  We want to block this transition.

**Comment by edsantiago** [comment]
Thanks. It works with docker (I don't know why). I'll remove that from the podman-docker-autotest suite.

**Comment by rhatdan** [comment]
I would be surprised that this works from Docker, unless docker daemon is not running as container_runtime_t.

ps -eZ | grep dockerd

**Comment by edsantiago** [comment]
I don't have a RHEL7 system to test with right now... but fwiw this is a test that you wrote for inclusion in docker-autotest in early 2016... and it has been working 100% with docker since then.

**Comment by edsantiago** [comment]
docker-1.13.1-104.git4ef4b30.el7 and container-selinux-2.107-3.el7:
```console
# docker run --rm --security-opt label=type:svirt_qemu_net_t alpine cat /proc/self/attr/current;echo
system_u:system_r:svirt_qemu_net_t:s0:c575,c667
# ps -eZ|grep dockerd
system_u:system_r:container_runtime_t:s0 16617 ? 00:00:00 dockerd-current
```
@rhatdan I'll leave the virt running and check in again tomorrow morning in case there's anything else you'd like me to look at.

**Comment by rhatdan** [comment]
But the rhel7 system does not have the same container-selinux as we have in RHEL8.  Basically I updated the selinux-policy to NOT allow the transition from a container_runtime_t do svirt_* (Virtual machine) domains.  So this is expected.

2016 Dan Walsh was mistaken.  And hopefully 2019 Dan Walsh is a little better informed.  :^)

**Comment by edsantiago** [comment]
Makes sense. I happened to have an old RHEL8 VM handy and found that the transition was allowed with `container-selinux-2:2.107-2.module+el8.1.0+4016+4220c060` but forbidden after dnf-upgrade to `2:2.124.0-1.module+el8.2.0+5182+3136e5d4`. Thank you, 2019 @rhatdan!
