### ISSUE TITLE
1.7.0: Regression: source can't be a URL for COPY

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4686]
```console
# cat Dockerfile
FROM alpine
ADD https://raw.githubusercontent.com/autotest/autotest-docker/master/LICENSE /LICENSE
# podman build .
STEP 1: FROM alpine
STEP 2: ADD https://raw.githubusercontent.com/autotest/autotest-docker/master/LICENSE /LICENSE
Error: error building at STEP "ADD https://raw.githubusercontent.com/autotest/autotest-docker/master/LICENSE /LICENSE": source can't be a URL for COPY
```
podman-1.7.0-0.2.rc1.fc30 and .fc31

Works as expected on 1.6.2

**Comment by rhatdan** [comment]
I think this is a bug fix.  @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Yep, we weren't matching Docker, now we are.  https://github.com/containers/buildah/pull/1977

**Comment by edsantiago** [comment]
Is that new docker behavior? Because docker 1.13 on RHEL7 allows it - that's why docker-autotest has an explicit test for it

**Comment by TomSweeneyRedHat** [comment]
I believe it's current Docker upstream behavior.  @QiWang19  worked on it.

**Comment by edsantiago** [comment]
docker 19.03.5 allows it
```console
# docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
latest: Pulling from library/alpine
89d9c30c1d48: Pull complete
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
 ---> 965ea09ff2eb
Step 2/2 : ADD https://raw.githubusercontent.com/autotest/autotest-docker/master/LICENSE /LICENSE
Downloading  18.34kB
 ---> 9275b9a479aa
Successfully built 9275b9a479aa
```

**Comment by edsantiago** [comment]
I think this is due to [confusion between COPY and ADD](https://stackoverflow.com/questions/24958140/what-is-the-difference-between-the-copy-and-add-commands-in-a-dockerfile). COPY does not allow URLs; ADD does. I still believe this is an undesired regression.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago just to be clear in my noggin, COPY  with URL allowed in Docker RHEL-1.13.1 but not Docker upstream.  ADD with URL is allowed in both Dockr RHEL-1.13.1 and Docker upstream?

**Comment by edsantiago** [comment]
I don't know about Docker on RHEL: OpenStack is acting up and I can't get a virt. All I can say is that docker 19.03.5 allows `ADD URL`, and presumably so does every docker 1.13 in history since there's a docker-autotest for it. docker 19.03.5 chokes on `COPY URL`:
```
Step 2/2 : COPY https://raw.githubusercontent.com/autotest/autotest-docker/maste
r/LICENSE /LICENSE
COPY failed: source can't be a URL for COPY
```
I have no way right now of knowing what docker-1.13 does with `COPY URL`.

**Comment by TomSweeneyRedHat** [comment]
Thanks @edsantiago, I'll see if I can revert that ADD side of things.

**Comment by mheon** [comment]
@edsantiago @TomSweeneyRedHat Should we hold 1.7.0 final release for a fix to this?

**Comment by edsantiago** [comment]
This is the sort of thing that is impossible to answer because it depends on use cases that (a) are entirely out of our control and, worse, (b) we have not the slightest clue about. There could be one person out there using this form, or one thousand. There is no way to know.

Given that this is a change since 1.6.2, and it breaks something that has "worked" for a long time, I would unfortunately say that this is a release blocker.

**Comment by edsantiago** [comment]
Finally got a RHEL7 VM. docker-1.13.1-104.git4ef4b30.el7:
```
ADD URL -> ok
COPY URL -> fails: Source can't be a URL for COPY
```

**Comment by TomSweeneyRedHat** [comment]
@mheon PR WIP, if that goes well tonight/tomorrow, would like to squeeze into 1.7.0.  I think this might bite us otherwise.

**Comment by TomSweeneyRedHat** [comment]
With PR #2019 in play:
```
# buildah bud -t tom -f ~/Dockerfile.addurl .
STEP 1: FROM alpine
STEP 2: ADD https://raw.githubusercontent.com/autotest/autotest-docker/master/LICENSE /LICENSE
STEP 3: COMMIT tom

```

**Comment by TomSweeneyRedHat** [comment]
btb, forgot to add, really, really great catch @edsantiago, TYVM!

**Comment by edsantiago** [comment]
This is fixed.
