### ISSUE TITLE
1.6.4 - release tarball has misplaced *.5.md files

### ISSUE THREAD

**Issue by sysrich** [containers/libpod#4688]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The 1.6.4 release has the *.5.md files in the incorrect place to correctly build the appropriate manpages

https://github.com/containers/libpod/tree/v1.6.4/docs/source/markdown should contain containers-mounts.conf.5.md and libpod.conf.5.md but instead they are located in https://github.com/containers/libpod/tree/v1.6.4/docs/

Therefore make docs doesn't build them

And openSUSE packaging of 1.6.4 broke (but this is easy to workaround now I've figured out what's going on :))

**Steps to reproduce the issue:**

1. Unpack 1.6.4

2. Run make docs

3. Examine contents of docs/build/man

**Describe the results you received:**

*.5 man pages are missing

**Describe the results you expected:**

*.5 man pages should be present

**Comment by rhafer** [comment]
This sees to be fixed in 1.7.0 (See #4428). So I guess it can be closed.

**Comment by vrothberg** [comment]
Thanks, @rhafer and @sysrich! I am closing the issue.
