### ISSUE TITLE
Podman does not respect the --file argument

### ISSUE THREAD

**Issue by semtexzv** [containers/libpod#4695]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman build does not properly respect the `--file, -f` option. When running podman in following structure:
``` 
./
./sub/
./sub/Dockerfile.test
./Dockerfile.test
````

`podman build -f sub/Dockerfile.test`, podman is using the `./Dockerfile.test`. If we remove the `./Dockerfile test`, Podman correctly uses the `sub/Dockerfile.test` but it does not build it in current directory, rather it `cd`s into the `sub` directory and builds it there.

**Steps to reproduce the issue:**

1. `git clone https://github.com/semtexzv/podtest && cd podtest`

2. `podman build -f sub/Dockerfile.test` 

3. `podman build -f sub/Dockerfile.wrongdir`

**Describe the results you received:**
On step 2 podman uses `./Dockerfile.test`, and executes
` ADD / i-am-in-current-dir` build command (specified in `./Dockerfile.test`)

On step 3 podman fails to  correctly build container from `sub/Dockerfile.wrongdir`, outputting that it can't find the `sub/testfile` in using the  `./sub/sub/testfile` path.

**Describe the results you expected:**
On step 2 podman should build the the container from `sub/Dockerfile.test`, running 
`ADD / i-am-in-sub-dir` command specified in it.

On step 3 podman should correctly build image containing the `./sub/tesfile`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1676271616
  MemTotal: 16424656896
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: dhcp131-23.brq.redhat.com
  kernel: 5.3.15-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 49h 32m 30.03s (Approximately 2.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/mhornicky/.config/containers/storage.conf
  ContainerStore:
    number: 36
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/mhornicky/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 62
  RunRoot: /run/user/1000
  VolumePath: /home/mhornicky/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Could you try your example with `buildah bud`?
Since podman just vendors buildah, this could likely just be an issue in buildah.

**Comment by semtexzv** [comment]
Buildah bud works correctly.

**Comment by rhatdan** [comment]
Do `buildah version` and `podman info | grep buildah` match?

**Comment by semtexzv** [comment]
Yes:
`buildah version` :
```
Version:         1.11.4
Go Version:      go1.13.1
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.0.0
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
```
`podman info --debug | grep buildah` :

```
"buildah version": "1.11.4",
```

**Comment by rhatdan** [comment]
Ok that is strange.

**Comment by rhatdan** [comment]
Adding the context directory fixes this, But basically this is the context directory is not being selected correctly.
