### ISSUE TITLE
Crashes when listing port mapping for latest(but removed) container

### ISSUE THREAD

**Issue by poulad** [containers/libpod#4705]
/kind bug

**Description**

CLI crashes when listing port mappings if no container process is running.

**Steps to reproduce the issue:**

1. `podman rm --all`

2. `podman port --latest`

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/14295804/70870251-e1913c00-1f5e-11ea-8f87-ad73e244fc1d.png)

**Describe the results you expected:**

A user friendly error message similar to `inspect` sub-command:

```
no such container
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

**Output of `podman info --debug`:**

```
(paste your output here)
```
![image](https://user-images.githubusercontent.com/14295804/70870272-3634b700-1f5f-11ea-8bc1-2db049b31470.png)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual Machine

**Comment by mheon** [comment]
Your version of Podman (0.10.1.3) is extremely old. I strongly recommend you upgrade - RHEL 7.7 has Podman 1.4.4 available, for example.
