### ISSUE TITLE
Unable to access application publically/outside after exposing port with podman 

### ISSUE THREAD

**Issue by Koushikgudipati** [containers/libpod#4715]
<--
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**NOTE** A large number of issues reported against Podman are often found to already be fixed
in more current versions of the project.  Before reporting an issue, please verify the
version you are running with `podman version` and compare it to the latest release
documented on the top of Podman's [README.md](../README.md).  If they differ, please
update your version of Podman to the latest possible and retry your command before creating
an issue.

If you are filing a bug against `podman build`, please instead file a bug
against Buildah (https://github.com/containers/buildah/issues). Podman build
executes Buildah to perform container builds, and as such the Buildah
maintainers are best equipped to handle these bugs.
-->

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

*Unable to access application running in podman container after exposing port outside*

<--
I installed podman 1.4 on RHEL 7.7 server
when i create container and expose port outside to access publicly I am not able to access the application. Inside the container i am able to access the application but using server IP i am not able to access the application after exposing the port.
Does podman have any other config to expose the app publically
Please help me on this

-->

**Steps to reproduce the issue:**

1. create a container using podman and expose externally using one port

**Describe the results you received:**
-->>podman run -dt -p 8085:8080/tcp localhost/gk3
661b7c6df520973e838aa2348934489d516c5e80873ead0e6bafc08bcbcaf53c

-> podman ps
CONTAINER ID  IMAGE                 COMMAND               CREATED        STATUS            PORTS                   NAMES
661b7c6df520  localhost/gk3:latest  /bin/sh -c /opt/i...  6 seconds ago  Up 5 seconds ago  0.0.0.0:8085->8080/tcp  charming_haslett
getting this connection refused error
curl -v localhost:8085
* About to connect() to localhost port 8085 (#0)
*   Trying 127.0.0.1...
* Connection refused
* Failed connect to localhost:8085; Connection refused

**Describe the results you expected:**
If it works fine i should get the application page when i curl the IP:port

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64


**Output of `podman info --debug`:**

```
(paste your output here)
```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 164327424
  MemTotal: 8191909888
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: inmbzp5133
  kernel: 3.10.0-1062.4.3.el7.x86_64
  os: linux
  rootless: true
  uptime: 555h 18m 38.22s (Approximately 23.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /home/koushik/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/koushik/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1073
  VolumePath: /home/koushik/.local/share/containers/storage/volumes


**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```rpm -q podman
podman-1.4.4-4.el7.x86_64


**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am not getting podman network command in cli. how to get it?
Please check and let me know how to fix this issue

**Comment by mheon** [comment]
The `podman network` command is only available in 1.6.x and higher, which will likely arrive in 7.8.

Can you access the port remotely, from other systems?

**Comment by Koushikgudipati** [comment]
which port ? container port or server port?
I can see on server port is listening but when i am doing telnet from different host its not connecting 
getting "connection refused....."
is there any way to fix this issue or any workaround?
is it only in RHEL7.7 or any other Linux OS also?

**Comment by mheon** [comment]
We don't know the cause yet, so I can't say. Can you provide IPTables rules from the server via `iptables -nvL` and `sudo iptables -nvL`?

Also, can you confirm if you are running Podman with or without root?

**Comment by Koushikgudipati** [comment]
iptables -nvL
Chain INPUT (policy ACCEPT 1195 packets, 115K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 156K  185M CNI-FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
 157K  173M DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 107K  169M DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
 106K  169M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
49928 3931K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DOCKER     all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      docker_gwbridge  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  docker_gwbridge !docker_gwbridge  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker_gwbridge docker_gwbridge  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 528 packets, 48276 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination
 156K  185M CNI-ADMIN  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI firewall plugin rules */
11608   23M ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.12           ctstate RELATED,ESTABLISHED
 5314  285K ACCEPT     all  --  *      *       10.88.0.12           0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.13           ctstate RELATED,ESTABLISHED
   20   800 ACCEPT     all  --  *      *       10.88.0.13           0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.14           ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      *       10.88.0.14           0.0.0.0/0
   16  2328 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.17           ctstate RELATED,ESTABLISHED
   16  1048 ACCEPT     all  --  *      *       10.88.0.17           0.0.0.0/0
   14  1225 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.18           ctstate RELATED,ESTABLISHED
   14   990 ACCEPT     all  --  *      *       10.88.0.18           0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.19           ctstate RELATED,ESTABLISHED
   20   800 ACCEPT     all  --  *      *       10.88.0.19           0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.20           ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      *       10.88.0.20           0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.22           ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      *       10.88.0.22           0.0.0.0/0

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
   92  8016 ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:9443
 1118  104K ACCEPT     tcp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           tcp dpt:9080

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  docker_gwbridge docker0  0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  docker0 docker_gwbridge  0.0.0.0/0            0.0.0.0/0
 157K  173M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

I am running podman with root

**Comment by mheon** [comment]
@Koushikgudipati Sorry, can you also provide `sudo iptables -nvL --t nat`

@mccv1r0 Mind taking a look here?

**Comment by mheon** [comment]
Also, the contents of `/etc/cni/net.d` would be helpful

**Comment by mccv1r0** [comment]
In addition to providing ``` sudo iptables -nvL --t nat ```  can you confirm that something in the container is actually listening on port ``` 8080 ``` ?

**Comment by Koushikgudipati** [comment]
iptables -nvL --t nat
Chain PREROUTING (policy ACCEPT 5152 packets, 809K bytes)
 pkts bytes target     prot opt in     out     source               destination
95274 4640K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
18712  904K CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 4895 packets, 782K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 5828 packets, 423K bytes)
 pkts bytes target     prot opt in     out     source               destination
   10   600 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
  115  5620 CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 5849 packets, 424K bytes)
 pkts bytes target     prot opt in     out     source               destination
49123 3487K CNI-HOSTPORT-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd requiring masquerade */
   66  4103 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  all  --  *      !docker_gwbridge  172.21.0.0/16        0.0.0.0/0
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:9443
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:9080
    6   373 CNI-e3e350612fbe6b9d70016958  all  --  *      *       10.88.0.12           0.0.0.0/0            /* name: "podman" id: "936469986f038df5a3f7ff7f3e193ac6e8570a7e57e8dcbd9f930e7d100e707a" */
    0     0 CNI-3a53d18bcc722f2be012479e  all  --  *      *       10.88.0.13           0.0.0.0/0            /* name: "podman" id: "19e6d5e336b95ff708a86d63b1106b7307a6100d366129527aefc01a973b985b" */
    0     0 CNI-6c2c314d162f7197587f06f2  all  --  *      *       10.88.0.14           0.0.0.0/0            /* name: "podman" id: "b50865d5b110b9737b8f38b5a32810024586965fd0c230241fc7f71da06c90b0" */
    8   524 CNI-3852aaa5231c0483f1758c45  all  --  *      *       10.88.0.17           0.0.0.0/0            /* name: "podman" id: "618e3cf6ebec13e303c88e916223e6b3d1df13383e59f101a41f4ed794ed0755" */
    0     0 CNI-2815bcd25e898c48a4951f23  all  --  *      *       10.88.0.18           0.0.0.0/0            /* name: "podman" id: "9fd7a6ccdcfb7c43875b3c1de56d5ec4475f15e1cfd8cb0904842df5cce2fae8" */
    0     0 CNI-09cd9393ee267e3e87498705  all  --  *      *       10.88.0.19           0.0.0.0/0            /* name: "podman" id: "fef6e6332a8a72e7ba044e6cd7d3cfc50445b98c9d77260bffc239abd5cf9861" */
    0     0 CNI-ce27b0f58c9abc9bab6409bf  all  --  *      *       10.88.0.20           0.0.0.0/0            /* name: "podman" id: "934b1f92f9879440f617a66f6d782463d0cd77f4537fd24e5742762f9f039007" */
    0     0 CNI-92e02f2963e26acf18d0725b  all  --  *      *       10.88.0.22           0.0.0.0/0            /* name: "podman" id: "a7a34801d0e3643d39736ac2de7c5aa48e4719c99699a048365c5e3c38b5f6de" */
    8   524 CNI-2e7fc965034638c0970ac471  all  --  *      *       10.88.0.24           0.0.0.0/0            /* name: "podman" id: "91bf0aa183ec71ef04b265723dcd424d7c5aaa470d3b1a612833a909349c3ba8" */

Chain CNI-09cd9393ee267e3e87498705 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "fef6e6332a8a72e7ba044e6cd7d3cfc50445b98c9d77260bffc239abd5cf9861" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "fef6e6332a8a72e7ba044e6cd7d3cfc50445b98c9d77260bffc239abd5cf9861" */

Chain CNI-2815bcd25e898c48a4951f23 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "9fd7a6ccdcfb7c43875b3c1de56d5ec4475f15e1cfd8cb0904842df5cce2fae8" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "9fd7a6ccdcfb7c43875b3c1de56d5ec4475f15e1cfd8cb0904842df5cce2fae8" */

Chain CNI-2e7fc965034638c0970ac471 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "91bf0aa183ec71ef04b265723dcd424d7c5aaa470d3b1a612833a909349c3ba8" */
    8   524 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "91bf0aa183ec71ef04b265723dcd424d7c5aaa470d3b1a612833a909349c3ba8" */

Chain CNI-3852aaa5231c0483f1758c45 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "618e3cf6ebec13e303c88e916223e6b3d1df13383e59f101a41f4ed794ed0755" */
    8   524 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "618e3cf6ebec13e303c88e916223e6b3d1df13383e59f101a41f4ed794ed0755" */

Chain CNI-3a53d18bcc722f2be012479e (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "19e6d5e336b95ff708a86d63b1106b7307a6100d366129527aefc01a973b985b" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "19e6d5e336b95ff708a86d63b1106b7307a6100d366129527aefc01a973b985b" */

Chain CNI-6c2c314d162f7197587f06f2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "b50865d5b110b9737b8f38b5a32810024586965fd0c230241fc7f71da06c90b0" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "b50865d5b110b9737b8f38b5a32810024586965fd0c230241fc7f71da06c90b0" */

Chain CNI-92e02f2963e26acf18d0725b (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "a7a34801d0e3643d39736ac2de7c5aa48e4719c99699a048365c5e3c38b5f6de" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "a7a34801d0e3643d39736ac2de7c5aa48e4719c99699a048365c5e3c38b5f6de" */

Chain CNI-DN-09cd9393ee267e3e87498 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.19           9.109.123.133        tcp dpt:3259
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            9.109.123.133        tcp dpt:3259
   21  1100 DNAT       tcp  --  *      *       0.0.0.0/0            9.109.123.133        tcp dpt:3259 to:10.88.0.19:9080

Chain CNI-DN-2815bcd25e898c48a4951 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.18           9.109.123.133        tcp dpt:32597
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            9.109.123.133        tcp dpt:32597
    2   112 DNAT       tcp  --  *      *       0.0.0.0/0            9.109.123.133        tcp dpt:32597 to:10.88.0.18:80

Chain CNI-DN-2e7fc965034638c0970ac (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.24           9.109.123.133        tcp dpt:32598
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            9.109.123.133        tcp dpt:32598
   21  1100 DNAT       tcp  --  *      *       0.0.0.0/0            9.109.123.133        tcp dpt:32598 to:10.88.0.24:9080

Chain CNI-DN-3a53d18bcc722f2be0124 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.13           0.0.0.0/0            tcp dpt:39869
    1    60 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:39869
   21  1100 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:39869 to:10.88.0.13:9080

Chain CNI-DN-92e02f2963e26acf18d07 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.22           9.109.123.133        tcp dpt:9081
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            9.109.123.133        tcp dpt:9081
    1    60 DNAT       tcp  --  *      *       0.0.0.0/0            9.109.123.133        tcp dpt:9081 to:10.88.0.22:9080

Chain CNI-DN-ce27b0f58c9abc9bab640 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.20           9.109.123.133        tcp dpt:9080
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            9.109.123.133        tcp dpt:9080
    1    60 DNAT       tcp  --  *      *       0.0.0.0/0            9.109.123.133        tcp dpt:9080 to:10.88.0.20:9080

Chain CNI-DN-e3e350612fbe6b9d70016 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       10.88.0.12           0.0.0.0/0            tcp dpt:8085
    0     0 CNI-HOSTPORT-SETMARK  tcp  --  *      *       127.0.0.1            0.0.0.0/0            tcp dpt:8085
   26  1360 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8085 to:10.88.0.12:9080

Chain CNI-HOSTPORT-DNAT (2 references)
 pkts bytes target     prot opt in     out     source               destination
   26  1360 CNI-DN-e3e350612fbe6b9d70016  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "936469986f038df5a3f7ff7f3e193ac6e8570a7e57e8dcbd9f930e7d100e707a" */ multiport dports 8085
   21  1100 CNI-DN-3a53d18bcc722f2be0124  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "19e6d5e336b95ff708a86d63b1106b7307a6100d366129527aefc01a973b985b" */ multiport dports 39869
    3   172 CNI-DN-2815bcd25e898c48a4951  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "9fd7a6ccdcfb7c43875b3c1de56d5ec4475f15e1cfd8cb0904842df5cce2fae8" */ multiport dports 32597
   21  1100 CNI-DN-09cd9393ee267e3e87498  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "fef6e6332a8a72e7ba044e6cd7d3cfc50445b98c9d77260bffc239abd5cf9861" */ multiport dports 3259
    1    60 CNI-DN-ce27b0f58c9abc9bab640  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "934b1f92f9879440f617a66f6d782463d0cd77f4537fd24e5742762f9f039007" */ multiport dports 9080
    1    60 CNI-DN-92e02f2963e26acf18d07  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "a7a34801d0e3643d39736ac2de7c5aa48e4719c99699a048365c5e3c38b5f6de" */ multiport dports 9081
   21  1100 CNI-DN-2e7fc965034638c0970ac  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "91bf0aa183ec71ef04b265723dcd424d7c5aaa470d3b1a612833a909349c3ba8" */ multiport dports 32598

Chain CNI-HOSTPORT-MASQ (1 references)
 pkts bytes target     prot opt in     out     source               destination
   23  1380 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0x2000/0x2000

Chain CNI-HOSTPORT-SETMARK (14 references)
 pkts bytes target     prot opt in     out     source               destination
   23  1380 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* CNI portfwd masquerade mark */ MARK or 0x2000

Chain CNI-ce27b0f58c9abc9bab6409bf (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "934b1f92f9879440f617a66f6d782463d0cd77f4537fd24e5742762f9f039007" */
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "934b1f92f9879440f617a66f6d782463d0cd77f4537fd24e5742762f9f039007" */

Chain CNI-e3e350612fbe6b9d70016958 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.88.0.0/16         /* name: "podman" id: "936469986f038df5a3f7ff7f3e193ac6e8570a7e57e8dcbd9f930e7d100e707a" */
    6   373 MASQUERADE  all  --  *      *       0.0.0.0/0           !224.0.0.0/4          /* name: "podman" id: "936469986f038df5a3f7ff7f3e193ac6e8570a7e57e8dcbd9f930e7d100e707a" */

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  docker_gwbridge *       0.0.0.0/0            0.0.0.0/0
   16   912 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:32768 to:172.17.0.2:9443
   68  4008 DNAT       tcp  --  !docker0 *       0.0.0.0/0  

container is listening on port specified. inside the container if i do curl -v localhost:<port> it is working.
but from outside the container it is not working.

**Comment by mccv1r0** [comment]
At first glance, this doesn't look right:

```
Chain CNI-DN-e3e350612fbe6b9d70016 (1 references)
pkts bytes target prot opt in out source destination
0 0 CNI-HOSTPORT-SETMARK tcp -- * * 10.88.0.12 0.0.0.0/0 tcp dpt:8085
0 0 CNI-HOSTPORT-SETMARK tcp -- * * 127.0.0.1 0.0.0.0/0 tcp dpt:8085
26 1360 DNAT tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:8085 to:10.88.0.12:9080
```

The podman command mapped port 8085 to 8080 ```-p 8085:8080```   yet I see 9080 in the DNAT rule.

**Comment by rhatdan** [comment]
@Koushikgudipati @mccv1r0 What should I do with this issue?

**Comment by mccv1r0** [comment]
IMHO close it.  It can be reopened if it's still a issue.

**Comment by barseghyanartur** [comment]
Same issue here. Problems after upgrade. Current version of podman 1.8.0.

**Comment by mheon** [comment]
Separate issue would be helpful, so we can get the full information from the issue template provided

**Comment by barseghyanartur** [comment]
@mheon:

Done.
