### ISSUE TITLE
Limit content of `~/.config/containers/libpod.conf`

### ISSUE THREAD

**Issue by ensc** [containers/libpod#4724]
/kind bug
/kind feature

**Description**

A `~/.config/containers/libpod.conf` file  is created at the first start of `podman` with the actual settings. 

This file is not touched/migrated after then which causes problems when there is a `libpod.conf` from ancient versions. E.g. one with

```
cgroup_manager = "cgroupfs"
```

settings whose code path is not tested anymore and which causes problems in recent versions (e.g. #4704).

I suggest to either:

- keep this file empty
- comment out its content so that it documents the actual settings and gives user a template
- like before but include `.../libpod.conf.d/*.conf` files where user configuration happens (like [systemd-system.conf](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html))

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
Already handled on master (actually made it into 1.6.3 as well I think)
