### ISSUE TITLE
slirp4netns cpu usage with torrents

### ISSUE THREAD

**Issue by G-Ray** [containers/libpod#4737]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running an image for deluge with some torrent downloading (~20MB/s), slirp4netns takes around 30-50% cpu according to `top`. Is it an expecting behavior with all the tcp connections involved by torrents ? Could it be related to https://github.com/rootless-containers/slirp4netns/issues/157 ?

**Steps to reproduce the issue:**

1. `podman pod create --name mypod -p 8112:8112`

2. `podman create --name=deluge --pod mypod linuxserver/deluge`

3. `podman start deluge`

4. go to `http://localhost:8112`, password is `deluge`. Set download path to `/downloads` and load a torrent, like https://torrent.fedoraproject.org/torrents/Fedora-Workstation-Live-x86_64-31.torrent for instance.

**Describe the results you received:**

Cpu usage of slirp4netns is around 35% while deluged consumes 65% for instance. (34 connections to peers and downloading at ~25MB/s)

**Describe the results you expected:**

Only deluged usage would be noticeable in the `top` output.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.6.2
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.1
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 141193216
  MemTotal: 8212029440
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8202743808
  SwapTotal: 8346660864
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: nuc
  kernel: 5.3.16-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 28m 56.36s
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: [HOME]/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: [HOME]/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /run/user/1000
  VolumePath: [HOME]/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora Server 31 on a baremetal

**Comment by mheon** [comment]
Slirp is expected to use some CPU (it has to manually move data into and
out of the container) but that amount sounds high. How fast are you
downloading at?

**Comment by G-Ray** [comment]
I was downloading at around `25MB/s`, not so fast I guess. Is it expected ?

**Comment by rhatdan** [comment]
@AkihiroSuda PTAL

**Comment by AkihiroSuda** [comment]
Changing mtu may have some effect?

https://github.com/containers/libpod/blob/b29928f01598810328fa6b0cf91abb84670d8d01/libpod/networking_linux.go#L212

**Comment by G-Ray** [comment]
I Just compiled the project with mtu set to 1500, result is similar. Any other guess ? The issue is easily repductible, I updated the original post if you want to give it a try.

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I think that CPU usage is expected when using slirp4netns as it is emulating the entire network stack.

**Comment by vrothberg** [comment]
Closing the issue as it's expected behavior.
