### ISSUE TITLE
(minor) podman kill: should do input validation

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#4746]
Looks like podman is accepting any int, casting to ulong, and passing it along:
```console
# podman run -d --name foo alpine sleep 60
5eafd476443109ab52af53cc68a08e81f3eb7a2249c81993193b01590cd1d5b2
# podman kill -s -1 foo
ERRO[0000] unknown signal "18446744073709551615"
unknown signal "18446744073709551615"
Error: error sending signal to container 5eafd476443109ab52af53cc68a08e81f3eb7a2249c81993193b01590cd1d5b2: `/usr/bin/runc kill 5eafd476443109ab52af53cc68a08e81f3eb7a2249c81993193b01590cd1d5b2 18446744073709551615` failed: exit status 1
# podman kill -s 999 foo
ERRO[0000] container_linux.go:389: signaling init process caused "invalid argument"
container_linux.go:389: signaling init process caused "invalid argument"
Error: error sending signal to container 5eafd476443109ab52af53cc68a08e81f3eb7a2249c81993193b01590cd1d5b2: `/usr/bin/runc kill 5eafd476443109ab52af53cc68a08e81f3eb7a2249c81993193b01590cd1d5b2 999` failed: exit status 1

------
# [ expected something more like ]:
Error: Invalid signal: -1 (or 999)
```
Would it make sense to validate against `SIGRTMAX` before accepting it? 

And, for the sake of discussion, I feel it might be a nice courtesy to accept a signed int and run `abs()` on it. Those of us with fingers trained to type `kill -N` would appreciate it. 

Oh, also, `kill -s 0` throws an error (invalid signal). This is what docker does, so we might need to keep it for compatibility, but it could also be nice to replicate standard `kill -0` behavior (exit 0 if container exists).

**Comment by rhatdan** [comment]
I like to get a fix on all of these.

Anyone out there looking for a quick git project should grab this.
