### ISSUE TITLE
Secure Configuration for Podman

### ISSUE THREAD

**Issue by Michael-Angel-Sec** [containers/libpod#4750]
We have done basics such as Securing the Operating System per Openscap, Central Logging, Auditing, SELinux Enforcing, FIPS mode.  We also configured rootless containers per RedHat Documentation [1].  We have setup signed images as a requirement to pull containers although I understand this does not block manual local container file import. [2]  I've had trouble finding security recommendations for podman itself (not the creation of secure containers).

How can podman's configuration be secured?

We are running RedHat RHEL7 Latest packaged version of Podman:
podman.x86_64                         1.4.4-4.el7            @rhel-7-server-extras-rpms

What podman configuration files should we setup auditing against?
`-w /etc/containers/policy.json -p wa -k podman-config-monitor`
`-w /usr/lib/tmpfiles.d/podman.conf -p wa -k podman-config-monitor`
`-w /usr/share/containers/libpod.conf -p wa -k podman-config-monitor`
`Is it helpful to audit all root-less user's podman config files and if yes how could this be done?`

podman command auditing
`-a always,exit -F arch=b64 podman -k podman-command`

[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/managing_containers/index#set_up_for_rootless_containers 

[2] https://access.redhat.com/articles/3116561 Verifying image signing for Red Hat Container Registry

Cliff notes: 
atomic trust add \
    --pubkeys /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release \
    --sigstore https://access.redhat.com/webassets/docker/content/sigstore \
    registry.access.redhat.com

Adds a section to the /etc/containers/policy.json file. 
...
Adds signature server files in directory /etc/containers/registries.d/.

        docker:
          registry.access.redhat.com:
            sigstore: https://access.redhat.com/webassets/docker/content/sigstore
And the registry.redhat.io.yaml file:

        docker:
          registry.redhat.io:
            sigstore: https://access.redhat.com/webassets/docker/content/sigstore

**Comment by rhatdan** [comment]
@mtrmac @vrothberg @mheon PTAL
I think you should watch /etc/containers/registries.conf
Perhaps storage.conf

**Comment by Michael-Angel-Sec** [comment]
Thank you, good idea I added those files and the entire directory with better labels.

> -w /etc/containers/registries.json -p wa -k apodman-registries
> -w /etc/containers/storage.json -p wa -k apodman-storage
> -w /etc/containers/policy.json -p wa -k apodman-policy
> -w /etc/containers/ -p wa -k apodman-containers
> 
> -w /usr/lib/tmpfiles.d/podman.conf -p wa -k apodman-config
> -w /usr/share/containers/libpod.conf -p wa -k apodman-config
> 
> -w /usr/bin/podman -p xar -k apodman-command

**Comment by mtrmac** [comment]
I kind of want to push against the whole idea of “how can we make it secure”, that should be the default expectation; non-default hardening should only be necessary for users with unusual requirements. If we are not living up to that, that’s, by default, a bug (or, maybe, rarely, a known painful compromise).

WRT auditing global configuration files, search for `RootForImplicitAbsolutePaths` in `vendor/containers/image`; the list of such files can expand over time.  Also consider the case of configuration (and credentials) that are expected to exist in per-user files (in home directories and `/run`).

**Comment by vrothberg** [comment]
@Michael-Angel-Sec, do you have further questions?

**Comment by Michael-Angel-Sec** [comment]
Thank you, I appreciate your secure by default position.   I appreciate these areas to focus on.
