### ISSUE TITLE
podman login to alias registry configured in registries.conf doesn't work.

### ISSUE THREAD

**Issue by smekkley** [containers/libpod#4765]
I have a following registries.conf.
```
[[registry]]
prefix = "alias.com"
location = "origin.com"
```

`podman pull alias.com/image` works as expected. Even though alias.com doesn't exist in dns record, it successfully pulls from origin.com.
However, when I do `podman login alias.com`, it tries to resolve the name, and times out, instead of trying to logging into origin.com. 

Is this an designed behaviour?

This is vaguely related to this issue that I'm trying to figure out, where I want podman pull to verify the signature across registries with the same signature that's generated from one gpg key.
I'm pretty convinced that podman signature verification also doesn't work, even though it's suggested to work in the thread.
https://github.com/containers/skopeo/issues/792

I'm using podman version 1.4.4 on CentOS 7 on production.
I've tried with the latest podman but the result was the same.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by vrothberg** [comment]
> Is this an designed behaviour?

Redirection and mirroring only happens when _pulling_, not when pushing or logging in.

**Comment by mtrmac** [comment]
Yes, this works as intended; credentials are specific to registry servers, not to image names / pull locations.

Consider the following configuration:
```
[[registry]]
prefix = "alias.com/product1"
location = "origin.com/product1"
```
It must be possible to run `podman login origin.com` (to pull `alias.com/product1`, which is redirected by the configuration), _and also_ `podman login alias.com` (to pull e.g. `alias.com/product2`, which is _not_ redirected by the configuration), and the two servers are going to have, in general, different credentials. Similar, possibly even starker, concerns exist for authenticating to mirrors (where the clients may have legitimate credentials for the mirrors, but not for the original upstream registries).
