### ISSUE TITLE
Checkpoint failed due to not able to add socket to tar

### ISSUE THREAD

**Issue by zhuguoliang** [containers/libpod#4775]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot checkpoint and export

**Steps to reproduce the issue:**

1. run sql in container

2. podman container checkpoint --tcp-established -l --export=/tmp/1.tar.gz

**Describe the results you received:**

ERRO[0017] Can't add file /var/lib/containers/storage/overlay/f783017883a46a071165d988f6e54c31ff094a8cb018d6bd2c0fd1519b56a7a6/diff/run/mysqld/mysqld.sock to tar: archive/tar: sockets not supported

**Describe the results you expected:**
Successful checkpoint and export

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0-rc1
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.7.0-rc1
host:
  BuildahVersion: 1.11.6
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.8, commit: d35534bc4b9bc722bf1ab6f4e828fcaa6bee236a-dirty'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 1970593792
  MemTotal: 16273141760
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 993243136
  SwapTotal: 993243136
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: hostu18
  kernel: 4.15.0-66-generic
  os: linux
  rootless: false
  uptime: 7h 59m 6.34s (Approximately 0.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
on Aliyun ecs

**Comment by adrianreber** [comment]
@zhuguoliang Not sure this can be fixed. But you can trying starting the container and telling Podman to mount a tmpfs at /run? Something like `podman run --tmpfs /run`.

**Comment by zhuguoliang** [comment]
It worked!    But why it works?

**Comment by adrianreber** [comment]
> It worked!

Perfect!

> But why it works?

During checkpointing `tmpfs` are handled by CRIU and are then part of the checkpoint. Directories with volatile data are, for the migration use-case, best mounted as `tmpfs` during container start.

In the end I am not sure why it fails. CRIU also uses `tar` to transfer the `tmpfs` content. CRIU, however, uses the `tar` binary. I guess the GO tar implementation which is part of Podman is just missing the feature to correctly add sockets to an archive.

**Comment by rst0git** [comment]
The error occurs because [`archive/tar`](https://github.com/golang/go/blob/50bd1c4d4eb4fac8ddeb5f063c099daccfb71b26/src/archive/tar/common.go#L658) fails when a file has ModeSocket. This change was introduced with Go 1.9 (commit: https://github.com/golang/go/commit/66b5a2f3f0b1d94f69763114a85a977f5bc0277a).
