### ISSUE TITLE
Depends on obsolete/archived "github.com/fatih/camelcase"

### ISSUE THREAD

**Issue by onlyjob** [containers/libpod#4783]
[github.com/fatih/camelcase](https://github.com/fatih/camelcase) is an unmaintained/archived project.

Let's reduce dependency on dead code please.

**Comment by mheon** [comment]
Seems to be used primarily to generate headers for CLI output in commands like `ps`, `stats`, `history`. One direct invocation, six or seven calls to the function it's used in.

**Comment by rhatdan** [comment]
@onlyjob do you know of an alternative?

**Comment by onlyjob** [comment]
I wish I knew...

**Comment by onlyjob** [comment]
The closest I can think of is [github.com/mattn/go-shellwords](https://github.com/mattn/go-shellwords)

**Comment by vrothberg** [comment]
The package is _really_ small, so I forked it into libpod: https://github.com/containers/libpod/pull/4968

**Comment by onlyjob** [comment]
Wouldn't it be better to switch to `mattn/go-shellwords`? It appears to be already used by Buildah and `containers/storage`.

**Comment by vrothberg** [comment]
@onlyjob, `go-shellwords` seems to behave differently. It's used to split a single-string shell command into an array, while `camelcase` is splitting a camelcase borders.
