### ISSUE TITLE
Build gets the wrong version, when built from tarball

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#4787]
Seems like the build script picks up the version of the **build system** instead...

When using something like (a branch of) [buildroot](https://buildroot.org/), that builds from dist tarballs.

It also uses "git fetch", which can be quite costly (we are using a shallow clone)

So it would be better if "make podman" didn't do all those magic git commands ?

----

The workaround is to provide the required version in the "CIRRUS_TAG" variable

```bash
    VERSION*)
        OUTPUT="${CIRRUS_TAG:-$(git fetch --tags && git describe HEAD 2> /dev/null)}"
        ;;
    NUMBER*)
        OUTPUT="$($0 VERSION | sed 's/-.*//')"
        ;;
```

Or to give up a provide both RELEASE_VERSION and RELEASE_NUMBER

```make
RELEASE_VERSION ?= $(shell hack/get_release_info.sh VERSION)
RELEASE_NUMBER ?= $(shell hack/get_release_info.sh NUMBER|sed -e 's/^v\(.*\)/\1/')
```

Like currently done for the GIT_COMMIT variable, similar issue (wrong git repo)

```make
GIT_COMMIT ?= $(if $(shell git status --porcelain --untracked-files=no),${COMMIT_NO}-dirty,${COMMIT_NO})
```

https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package/podman

**Comment by afbjorklund** [comment]
The main problem is:

```console
$ git remote -v
origin	https://github.com/buildroot/buildroot (fetch)
origin	https://github.com/buildroot/buildroot (push)
```
Which then outputs:

```console
$ git describe HEAD
2019.02.8
$ git rev-parse HEAD
aaa1437b110f886ee24757595542f715a77d702a
```

**Comment by vrothberg** [comment]
@afbjorklund mind opening a PR with what you have in mind?

**Comment by afbjorklund** [comment]
I wanted to have some feedback, in what would be the best version to allow building from tarball ?

When looking at for instance the `runc` and `conmon` builds, they have a simpler version handling:

```make
VERSION := ${shell cat ./VERSION}
```

That would of course require that this file is updated as part of the release process, not only tagged.

----

But the current workaround is fine too (=it works).

`CIRRUS_TAG=$(PODMAN_VERSION) $(MAKE) GIT_COMMIT=$(PODMAN_COMMIT) podman`

Just thought the name "CIRRUS_TAG" was weird ?

But I didn't want to mess around with sed'ing the v.

**Comment by afbjorklund** [comment]
I guess fedora would have had the same problem too, if it had used `make` instead of `%gobuild` ?

https://src.fedoraproject.org/rpms/podman/blob/master/f/podman.spec

Even when building from git, it seems a bit unnecessary to have to download all the _other_ git tags.

So used the same workaround, also for the brew package that I posted.

**Comment by afbjorklund** [comment]
Hacking the build system seems to have had other side effects:

**podman version -f json**
```
    "Client": {
        "RemoteAPIVersion": 1,
        "Version": "1.7.0-rc2",
        "GoVersion": "go1.13.5",
        "GitCommit": "",
        "Built": 0,
        "OsArch": "linux/amd64"
    },
```

I guess there was nothing populating gitCommit / buildInfo ?

https://koji.fedoraproject.org/koji/buildinfo?buildID=1426822

**Comment by afbjorklund** [comment]
@vrothberg : added PR, as requested

Before:

``` shell
CIRRUS_TAG=$(PODMAN_VERSION) $(MAKE) GIT_COMMIT=$(PODMAN_COMMIT) podman
```

After:

``` shell
$(MAKE) VERSION=$(PODMAN_VERSION) GIT_COMMIT=$(PODMAN_COMMIT) podman
```

**Comment by afbjorklund** [comment]
Two problems with above PR, it broke builds **not** using $(VERSION) and it _still_ used git...

**Comment by afbjorklund** [comment]
I will go with the (undocumented) `$CIRRUS_TAG` for now, feel free to improve the build.

**Comment by afbjorklund** [comment]
Reopen as per comments in the initial attempt. Apparently everyone is doing their own workarounds.

**Comment by baude** [comment]
@vrothberg can you look at this again?

**Comment by vrothberg** [comment]
> @vrothberg can you look at this again?

I prefer @afbjorklund and @cevich to continue working on the issue. They seem to have an idea how to move forward on this.

**Comment by cevich** [comment]
> I will go with the (undocumented) $CIRRUS_TAG for now, feel free to improve the build.

I originally wanted to do this except found some even less documented complications:

* It's desirable to do throwaway builds on PRs, to validate the build+release process actually works.
* I found `$CIRRUS_TAG` is only set when executing against a commit that is tagged. Meaning it will almost never be set for a PR.
* Worse, a tagged commit may show up in the middle of a PR's set of commits.
* More worser, the maintainer may push the tags before or well after the PR is merged.  We cannot predict the sequence.
* We don't want versions like ''v1.7.0-288-ge27ce8160' (ever).  It should be simplified to the tag name or 'v.1.7.0-testing' (or similar, for PRs).

:confounded: complicated :confounded: 

So this is what `is_release()` in `contrib/cirrus/lib.sh` is suppose to help with.  In any case, take a peek at that function and I think it will help you understand the Makefile and `hack/get_release_info.sh` better.  I very much do not like the way this is currently, so please, if you have a mind for simplifying it, I'm in favor :+1:

**Comment by afbjorklund** [comment]
I would rather **not** have a situation like fedora, where release ends up being broken for half a year due to overly complex versioning scheme... (looking at you, `cri-o-1.15.2-1.module_f30+6830+9be88745`)

Everything works fine when building from the git repository directly, so the main breakage was when trying to use "traditional" packaging systems - normally based on numberic versions and dist tarballs.

----

Adding the git commit to the metadata and build variables is a tolerable workaround, for now.

```Makefile
PODMAN_VERSION = v1.6.4
PODMAN_COMMIT = 5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26
```

The main annoyance is that there is no accepted standard on _what_ those variables should be.

Most common options seem to be `$(VERSION)` (from a VERSION file) and `$(GIT_COMMIT)`.

And of course we still haven't even decided whether the `v` is just silent or omitted entirely...

**Comment by afbjorklund** [comment]
And I don't think that build time even _can_ be fixed, as per https://reproducible-builds.org/

But if anything, one would probably have to add [SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/) to metadata ?

**Comment by cevich** [comment]
> overly complex versioning scheme

That's why in the Makefile, I went to 'git describe' and for making tgz/zip files, that detail is encoded into release.txt  The problems related to `$CIRRUS_TAG` is related but more about automation knowing when to push artifacts (as opposed to always pushing them on every merge).

**Comment by cevich** [comment]
FWIW: If you want to extend/add to metadata in `release.txt` the only user of it (AFAIK) is `contrib/cirrus/upload_release_archive.sh`.

**Comment by rhatdan** [comment]
@cevich @afbjorklund What is the scoop on this one? Can I close it?

**Comment by afbjorklund** [comment]
I'm using the `CIRRUS_TAG` and `GIT_COMMIT` workaround, which seems to be doing the trick...

```console
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ sudo podman version
Version:            1.6.5
RemoteAPI Version:  1
Go Version:         go1.11.13
Git Commit:         45e7be192ef99e870c59a1cd2c1fa7940b0af2d6
Built:              Fri Feb 14 16:11:48 2020
OS/Arch:            linux/amd64
```

Maybe not the prettiest, but "works for me". Now, if only I could find some `podman-remote` ;-)

Should I open a PR about adding binaries to the GitHub releases, or will you fix the Cirrus CI ?

**Comment by rhatdan** [comment]
I am going to close this issue.  @cevich Is in charge of Cirrus CI...
