### ISSUE TITLE
podman build on cbs

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#4789]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I needed to test 1.7 on centos 7 and noticed that the build has been failing.  

Failure points to task here:

https://cbs.centos.org/koji/taskinfo?taskID=1092090

```
Result 
GenericError: Unable to complete build: epoch mismatch (build: 2, rpm: None)
```

However, when I look at the last build tasks all files were successfully produced here:

https://cbs.centos.org/kojifiles/work/tasks/2091/1092091/

I downloaded srpm was able to build it successfully after installing all dependencies.  

Could you take a look at the reason 1.7rc is not making to the repo?

**Comment by alitvak69** [comment]
Podman 1.7 RPM is still failing to build on cbs

**Comment by vrothberg** [comment]
@jnovy, could you have a look?

**Comment by alitvak69** [comment]
@jnovy It seems to be an issue with epoch 2 being used.  Successfully built 1.6.2 has no epoch.

**Comment by alitvak69** [comment]
@lsm5 Can you please take a look?  This has been going on forever, the builds are failing to publish due to some tag issue on CBS while rpms seems to be building fine.

**Comment by rhatdan** [comment]
@lsm5 Any update?

**Comment by lsm5** [comment]
not using cbs anymore for new builds. Updates available on OBS.

@alitvak69 please re-open if you notice any issues with the latest packages.
