### ISSUE TITLE
NetworkSettings not exposed on varlinkAPI

### ISSUE THREAD

**Issue by marusak** [containers/libpod#4792]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
I don't see `NetworkSettings` (like `IPAddress`, `Gateway`...) in varlink API. (I checked `GetContainer` method and documentation if it is not somewhere else)

**Steps to reproduce the issue:**
1. `sudo varlink call unix:/run/podman/io.podman/io.podman.GetContainer '{"id": "<some_id>"}'`

**Describe the results you received:**
Information about container (like `command`, `image`, `mounts`...)

**Describe the results you expected:**
The same information plus NetworkSettings (like I would get in `podman inspect`)

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

**Comment by rhatdan** [comment]
podman-remote inspect seems to be getting it?

**Comment by rhatdan** [comment]
Does this call get you what  you want?
varlink call unix:/run/podman/io.podman/io.podman.ContainerInspectData '{"name": "test1"}'

**Comment by marusak** [comment]
> Does this call get you what you want?
varlink call unix:/run/podman/io.podman/io.podman.ContainerInspectData '{"name": "test1"}'

Yes, it is there. I missed this command since it returns string (and therefore it is not described what it contains). Also from doc "This call is for development of Podman only and generally should not be used.". I hope it can be exposed in some better form than string.

**Comment by rhatdan** [comment]
There is a major rework/rewrite going on in podman for remote connections, to support functionality like the docker.sock calls.  Not sure if they will be able to get back to this one any time soon.

**Comment by baude** [comment]
@marusak There is a `InspectContainer` endpoint that does the exact same thing as ContainerInspectData.  The string being return is just json-string and should be able to marshalled.  i think this solves your problem. Please comment otherwise and we can re-open.
