### ISSUE TITLE
Container Creation Entrypoint is a single string instead of a list

### ISSUE THREAD

**Issue by astronouth7303** [containers/libpod#4809]
/kind bug

**Description**

The parameters to create a container (the `Create` type in the varlink schema) takes a single string. However, the OCI image configuration and the config key out of `InspectImage` can be an array.

**Steps to reproduce the issue:**

1. Try to create a container with an array entrypoint (either from an image with one or via varlink API)

**Describe the results you received:**
```
{'error': 'org.varlink.service.InvalidParameter', 'parameters': {'parameter': 'client.call.create.entrypoint'}}
```

**Describe the results you expected:**
Successful creation of a container

**Additional information you deem important (e.g. issue happens only occasionally):**
Based on https://github.com/containers/libpod/blob/bd3d8f4e282dc7a552d955bf5958b53d23937604/cmd/podman/varlink/io.podman.varlink#L318 I'm sure this is still in master.

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26
Built:              Sat Dec 21 13:13:24 2019
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 5cc92849f7fc9dd734ca2fd8f3ae8830b9a7eb26
  go version: go1.13.5
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.2, commit: unknown'
  Distribution:
    distribution: debian
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 188473344
  MemTotal: 8229838848
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc9+dfsg1
      commit: 1.0.0~rc9+dfsg1-1
      spec: 1.0.1-dev
  SwapFree: 6091321344
  SwapTotal: 8467247104
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: cayde7
  kernel: 5.3.0-3-amd64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.1
      commit: 4d38845e2e311b684fc8d1c775c725bfcd5ddc27
  uptime: 79h 6m 34.73s (Approximately 3.29 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/astraluma/.config/containers/storage.conf
  ContainerStore:
    number: 79
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.7.0
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.7.0
        using FUSE kernel interface version 7.31
  GraphRoot: /home/astraluma/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 139
  RunRoot: /run/user/1000
  VolumePath: /home/astraluma/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Complicated

**Comment by astronouth7303** [comment]
I did check with https://github.com/opencontainers/image-spec/blob/master/config.md to see what the OCI had to say on the subject.

**Comment by baude** [comment]
@astronouth7303 given that a type has to be declared ... can you give me an actual example?  are you converting the array to a string before passing it?

**Comment by astronouth7303** [comment]
No? It's pretty straight-forward?

OCI says entyrpoint is an array (an argv). Docker says that entrypoint either an array or a string.

OCI says that the program actually run is entrypoint and command, concatenated.

So my usage, I want the entrypoint `["/mc-server-entrypoint", "-shell", "/bin/sh"]`. Since `command` is an array, would expect that `entrypoint` is also an array. But it's not, it's a string, which implies it only accepts the argv[0], that is `"/mc-server-entrypoint"`, without additional arguments.

**Comment by mheon** [comment]
I'll take this one, I think it's identical to the change parsing I did
earlier

**Comment by mheon** [comment]
Given the deprecation of Varlink, I'm going to go ahead and close this as WONTFIX. The feedback has been addressed in the new HTTP API, though.
