### ISSUE TITLE
Podman release for armhf architecture

### ISSUE THREAD

**Issue by yolanv** [containers/libpod#4811]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently, there is no armhf build for Podman, which eliminates the use of Podman for operating systems such as Raspbian. Although you can probably compile it with the source code, it would be nice to have a pre-compiled binary to use. This prevents the user from installing all the needed dependencies in order to compile Podman by himself.

Installing with Snap gives the following error:

> pi@raspberrypi:~ $ sudo snap install podman
> error: snap "podman" is not available on this architecture (armhf) but exists on other
>        architectures (amd64).

**Steps to reproduce the issue:**

1. on armhf architecture: sudo snap install podman

**Describe the results you received:**
> pi@raspberrypi:~ $ sudo snap install podman
> error: snap "podman" is not available on this architecture (armhf) but exists on other
>        architectures (amd64).

**Describe the results you expected:**
Having a compiled binary for armhf available.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested on a Raspberry Pi 3 Model B with Raspbian Buster. Latest image (as of the time of writing) with snapd installed.

**Comment by rhatdan** [comment]
Any chance you would be willing to open a PR to make this happen?

**Comment by yolanv** [comment]
> Any chance you would be willing to open a PR to make this happen?

Thanks for your reply. If I could, I would. However, I'm unexperienced in this field. If someone could guide me through the process or has some handy resources on the internet I could use, I would be more than happy to give it a try.

**Comment by baude** [comment]
my understanding is raspberrian was based on debian?

**Comment by giuseppe** [comment]
> my understanding is raspberrian was based on debian?

yes correct, raspbian is based on debian.

@yolanv could you try if https://launchpad.net/~projectatomic/+archive/ubuntu/ppa has the packages you are looking for?

**Comment by vrothberg** [comment]
The cross-distribution packaging is now happening on the Open Build Service. https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable provides packages from ARM. Maybe they'll do the job?

**Comment by agners** [comment]
If you prefer building your own distribution, the OpenEmbedded layer meta-virtualization has recipe for podman (https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/).

**Comment by rhatdan** [comment]
@agners Could you open a PR to add that link to the install.md file?

**Comment by baude** [comment]
@vrothberg care to knock this out for bug week?

**Comment by yolanv** [comment]
@vrothberg Indeed, the openSUSE page has builds for armHF (more specifically Raspbian). This basically solves the issue. Thanks alot!
