### ISSUE TITLE
Container not accessible outside host due to lack of forwarding 

### ISSUE THREAD

**Issue by MK27** [containers/libpod#4834]
This is on a Fedora 31 system.  I'm brand new to podman, using it because of the cgroups2 issue with docker -- which is fine by me, since I am pretty new to docker to start with.

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After dealing with issue 4114: https://github.com/containers/libpod/issues/4114
By running `ip link add cni-podman0 type bridge`, a rootfull container started thus:

    podman run -p 80:80/tcp ....

Has port 80 accessible from the host but not beyond that (icmp type 3 "unreachable"); the server is bound to 0.0.0.0 in the container:
```
host> netstat -lnp
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -                   

host> iptables -L -v
Chain INPUT (policy ACCEPT 329 packets, 47703 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   49  6489 CNI-FORWARD  all  --  any    any     anywhere             anywhere             /* CNI firewall plugin rules */
    4   240 REJECT     all  --  any    any     anywhere             anywhere             reject-with icmp-port-unreachable

Chain OUTPUT (policy ACCEPT 335 packets, 36724 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   49  6489 CNI-ADMIN  all  --  any    any     anywhere             anywhere             /* CNI firewall plugin rules */
```

I'm not all that proficient with these things, but the empty CNI-ADMIN chain referenced by the CNI-FORWARD chain looks responsible, so I tried:

    iptables -A CNI-ADMIN -j ACCEPT

And this works, I dunno how robust or appropriate a solution it really is -- right now I only need the one container, I think it should do for that.

**Steps to reproduce the issue:**

Happens every time the system is rebooted; starting a container fails immediately because of issue 4114, once that is corrected the container will start but be unaccessible beyond the host until that accept rule is added to the CNI-ADMIN chain.

**Describe the results you expected:**

I'm hoping to have this stuff automated properly for me :)

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:                                
  compiler: gc                                   
  git commit: ""
  go version: go1.13.1      
  podman version: 1.6.2                       
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 5053612032
  MemTotal: 11988262912
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 16683962368
  SwapTotal: 17365110784
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.4.0-i5Asus
  os: linux
  rootless: false
  uptime: 49h 52m 14.95s (Approximately 2.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 9
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.2-2.fc31.x86_64
```

Additional environment details (AWS, VirtualBox, physical, etc.):

I'm working via `ssh root@localhost` because of the issue with `XDG_RUNTIME_DIR`: https://bugzilla.redhat.com/show_bug.cgi?id=1776187 
(Can't use `su root` because "podman on cgroup V2 needs to have a full systemd login session to work".)

**Comment by baude** [comment]
@dcbw any idea what might be going on here/

**Comment by imcsk8** [comment]
Can you paste how are you testing the connection to the port 80 of the host?

**Comment by baude** [comment]
@MK27 nudge

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by MK27** [comment]
Sorry for the delay gang.

How would you like me to test it?

**Comment by rhatdan** [comment]
@mheon Could you answer @MK27 question?

**Comment by mheon** [comment]
We're stepping outside my area of expertise here, but `telnet` and `netstat` to see if the port is open on the host and remote, plus the output of `iptables -nvL` and `iptables -t nat -nvL` would help us diagnose.

I suspect from this we're going to have some missing IPTables forwarding rules, given that CNI was unable to even create a bridge for you; there's definitely something going wrong on their end, and it doesn't seem to be generating errors.

(A `podman run --log-level=debug` trace of your Podman command would help here, maybe CNI is generating warnings that aren't being printed)

**Comment by rhatdan** [comment]
@MK27 Are you still interested in this?  You never gave @mheon the output of the podman run --log-level=debug?

**Comment by rhatdan** [comment]
Closing for lack of response.  Reopen if this is still an issue for you.
