### ISSUE TITLE
Check if uid is not higher than maxuid and gid is not higher than maxgid, otherwise exit with message.

### ISSUE THREAD

**Issue by mangonel** [containers/libpod#4838]
Error is non descriptive
 
``` bash
id
uid=70000(test) gid=1001(test) groups=1001(test)
toolbox enter
Error: unable to start container "fedora-toolbox-30": container_linux.go:346: starting container process caused "process_linux.go:319: getting the final child's pid from pipe caused \"EOF\"": OCI runtime error
```

My guess this is caused by:
--userns=keep-id 
Which requires uid not to be greater than maxUID and gid not to be greater than maxGID.
With maxUID being the third field in subuid and maxGID being the third field in subgid.

**Comment by debarshiray** [comment]
Let's fix this in Podman itself.
