### ISSUE TITLE
wish: improve docs for `podman exec --privileged`

### ISSUE THREAD

**Issue by markstos** [containers/libpod#4840]
The `--privileged` flag for `podman exec` is currently documented like this:

> Give the process extended Linux capabilities when running the command in container.

More detailed documentation is required for users to know if they need "extended" capabilities are not. This is especially true in the case or rootless/unprivileged containers. What does it mean for an unprivileged user to create a "--privileged" container vs an unprivileged one?

@mheon Has already weighed in here to clarify some: https://github.com/containers/libpod/commit/e8a32e3722e0b814c654cdb8809565a21fc120d3#r36737969

Also @rhatdan clarified some on a related Gitlab issue as well:
https://gitlab.com/uppercat/tlbx/issues/5#note_269716530

**Comment by rhatdan** [comment]
@markstos interested in opening a PR to fix the issue?

**Comment by markstos** [comment]
Yes.

**Comment by vrothberg** [comment]
Thanks for contributing, @markstos! Closing as #4841 fixed it.
