### ISSUE TITLE
Cannot change CMD in commit to a command with arguments (from 1.7)

### ISSUE THREAD

**Issue by marusak** [containers/libpod#4847]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Setting up `CMD` in `commit` command cannot be a command with arguments, but only single executable since 1.7. It worked as expected before.

**Steps to reproduce the issue:**
(happens both with system and user container)
1.  `(sudo) podman run --name to_be_commited -dit fedora bash`
2.  `(sudo) podman commit -c CMD="sleep 6000" to_be_commited commited_image`

**Describe the results you received:**
The second command fails with `Error: invalid change "CMD=sleep 6000" - invalid instruction CMD=SLEEP`
However, if I use just command without any arguments, it works. E.g. (not valid cmd, but to show the point)
```
(sudo)  podman commit -c CMD="sleep" to_be_commited commited_image
```

**Describe the results you expected:**
Successfully created image. If I run these two commands with `podman-1.6.2-2`, the image is created and in `sudo podman inspect commited_image` I see:
```
"Config": {
            "Cmd": [
                "/bin/sh",
                "-c",
                "sleep 6000"
            ],
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Worked in `podman-1.6.2-2`, broken in `podman-1.7.0-2`.

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Comment by mheon** [comment]
I'll grab this one

**Comment by mheon** [comment]
This is a result of our parsing changes for `--change` in 1.7.0 to more closely match `docker commit` syntax.

Multi-part `commit` changes are not allowed in Docker with just quotation marks, and instead require an array. Also, use of an `=` between instruction and value is really discouraged - a space is greatly preferred. `sudo podman commit -c 'CMD ["sleep", "6000"]' to_be_commited commited_image` should work here.

I recognize that breaking changes between versions are bad for users, but Podman aims to provide Docker compatibility, and the existing parsing of the `--change` flag was completely incompatible (and also very broken, which is what originally prompted the move). The flag is meant to consume lines formatted as they would be in a Dockerfile, and reuse the existing Dockerfile parser. I can at least say that this should be the last breaking change the flag sees - now that it's been fixed to match Docker syntax, it shouldn't need to change again.

**Comment by marusak** [comment]
I see.
How is API affected? (from docs)
```
method Commit(name: string, image_name: string, changes: []string, author: string, message: string, pause: bool, manifestType: string) -> (reply: MoreResponse)
```
What is supposed to be passed into `changes` in the same usecase?

**Comment by mheon** [comment]
The format for each individual change (string in the array) should again match standard Dockerfile format - instruction, then value, separated by a single space - basically identical to what we pass into the command line for `--change`.

**Comment by marusak** [comment]
```
sudo varlink call unix:/run/podman/io.podman/io.podman.Commit '{"name": "to_be_commited", "image_name": "new_name_foo", "changes": ["CMD [\"sleep\", \"6000\"]"]}'
```
works. It seems not to break API? I'll try to implement this and see how it behaves with older versions. But really, having array as string in API is so unfriendly...

**Comment by marusak** [comment]
of course it breaks api :disappointed:  Running command https://github.com/containers/libpod/issues/4847#issuecomment-573731214 on 1.6 and 1.7):
```
$ sudo podman inspect commited_image_from_1.6
            "Cmd": [
                "sleep",
                " \"6000\""
            ],
```

```
 $ sudo podman inspect commited_image_from_1.7
            "Cmd": [
                "sleep",
                "6000"
            ],

```
The one from 1.6 is of course invalid command and it fails. So I guess we AGAIN need to put conditions on API version in cockpit-podman.

**Comment by martinpitt** [comment]
varlink was designed to be a self-descripting, extensible, and stable API. This really isn't that. Also, encoding a list into a string and passing that through the API as a string? Why not actually passing a list? On top of being sensible, this would have kept the API backwards compatible, this now broke it for no reason at all..

Sorry for the rant, but that has happened several times now...
