### ISSUE TITLE
[DEV] cannot build with forked libpod using 'replace' in go.mod

### ISSUE THREAD

**Issue by zhuguoliang** [containers/libpod#4848]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

Neither

**Description**

I forked libpod to add a requested feature, but it seems that libpod use "-mod=vendor" in Makefile which will generate "no such file" error in vendor dir.

**Steps to reproduce the issue:**

1. fork libpod to my own github repo
2. modify Makefile line10 PROJECT := github.com/Genetalks/libpod
3. change go.mod by add line : replace github.com/containers/libpod => github.com/Genetalks/libpod v1.7.1-0.20200113075557-0b3767272c75
4. invoke make command

**Describe the results you received:**

> zgl@zgl-host:~/go/src/github.com/Genetalks/libpod$ make
GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/home/zgl/go/src/github.com/Genetalks/libpod' -asmflags 'all=-trimpath=/home/zgl/go/src/github.com/Genetalks/libpod' -ldflags '-X github.com/Genetalks/libpod/libpod/define.gitCommit=0b3767272c7556bd1e9f1ed9f6998a26546f1167-dirty -X github.com/Genetalks/libpod/libpod/define.buildInfo=1578904939 -X github.com/Genetalks/libpod/libpod/config._installPrefix=/usr/local -X github.com/Genetalks/libpod/libpod/config._etcDir=/etc -extldflags ""' -tags "apparmor   selinux systemd exclude_graphdriver_devicemapper seccomp varlink" -o bin/podman github.com/Genetalks/libpod/cmd/podman
build github.com/Genetalks/libpod/cmd/podman: cannot load github.com/containers/libpod/cmd/podman/cliconfig: open /home/zgl/go/src/github.com/Genetalks/libpod/vendor/github.com/containers/libpod/cmd/podman/cliconfig: no such file or directory
Makefile:169: recipe for target 'bin/podman' failed
make: *** [bin/podman] Error 1

**Describe the results you expected:**
Success libpod compile.

**Comment by vrothberg** [comment]
@zhuguoliang, you don't need to modify the Makefile or do a go-module replacement for local development.

**Comment by zhuguoliang** [comment]
@vrothberg Hi, but on a forked repo, invoking make will produce errors.

**Comment by vrothberg** [comment]
Can you do `make podman` in a clean fork and copy the error messages? There is no need to change the module, so something else must be going on.

**Comment by zhuguoliang** [comment]
Thanks, "make" generates the error but make podman works.

**Comment by vrothberg** [comment]
@zhuguoliang can you paste the error?

**Comment by zhuguoliang** [comment]
@vrothberg 
Here is the output when invoke "make".

> zgl@zgl-host:~/go/src/github.com/Genetalks/libpod$ make
touch .gopathok
GO111MODULE=off go generate ./cmd/podman/varlink/...
GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/home/zgl/go/src/github.com/Genetalks/libpod' -asmflags 'all=-trimpath=/home/zgl/go/src/github.com/Genetalks/libpod' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=9e2e4d7615311b38b1e553af32a5666888ef3c96-dirty -X github.com/containers/libpod/libpod/define.buildInfo=1578961409 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc -extldflags ""' -tags "apparmor   selinux systemd exclude_graphdriver_devicemapper seccomp varlink" -o bin/podman github.com/containers/libpod/cmd/podman
go: errors parsing go.mod:
/home/zgl/go/src/github.com/Genetalks/libpod/go.mod:83: module lookup disabled by -mod=vendor
Makefile:169: recipe for target 'bin/podman' failed
make: *** [bin/podman] Error 1
