### ISSUE TITLE
First two characters are swapped in 'podman exec' streams, but not 'podman run'

### ISSUE THREAD

**Issue by jdloft** [containers/libpod#4863]
After entering a toolbox the first character isn't displayed and instead is inserted after the second character is input. This happens on BASH and ZSH and with a test user with a vanilla homedir.

Fedora Silverblue 31, toolbox 0.0.17

Example: after typing "exit" immediately following "toolbox enter"
![Screenshot from 2020-01-11 21-44-10](https://user-images.githubusercontent.com/8332322/72214273-e7296580-34bb-11ea-887b-7cc0936a58fa.png)

**Comment by giuseppe** [comment]
@haircommander PTAL

**Comment by haircommander** [comment]
oh, hooray I already fixed this in https://github.com/containers/libpod/pull/4818 :smile: can you try latest master @debarshiray ?

**Comment by mheon** [comment]
I think a better question now might be what did #4818 not fix - great work @haircommander

**Comment by mheon** [comment]
We should cut a 1.7.1 after Devconf.cz to get this out into the wild

**Comment by debarshiray** [comment]
> oh, hooray I already fixed this in #4818 smile can you try latest master @debarshiray ?

Confirmed fixed in master. I tested the snapshot at commit d52132b6ecc1c1c9fb955ecee629f8d169ef1119
