### ISSUE TITLE
Build script stopped working after upgrading podman

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#4865]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I upgraded podman from version 1.4.4 to 1.6.4, and then it stopped working.

Also tried with later versions, both v1.7.0 and master but with same results...

**Steps to reproduce the issue:**

1.  This is a simplified version of the process:

2. sudo podman run -d --name build busybox sleep 3600

3. sudo podman exec build sh -x < hello

**Describe the results you received:**

```console
$ sudo podman exec build sh -x < hello
$
```

**Describe the results you expected:**

```console
$ sudo podman exec build sh -x < hello
+ echo Hello
Hello
$
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Custom build from git.

Ubuntu 16.04 (laptop)

The real build scripts:

https://github.com/boot2podman/boot2podman/blob/v0.24/kernel/build.sh

https://github.com/boot2podman/boot2podman/blob/v0.24/packages/build.sh

**Comment by afbjorklund** [comment]
Possibly related to #4818 and friends

**Comment by mheon** [comment]
As discussed in IRC, this could be the lack of `-i`. I believe we started respecting it for `podman exec` in 1.6.x with the exec rework (previously it was unconditionally assumed).

**Comment by afbjorklund** [comment]
Seems that the `-i` flag is now needed, when wanting to pass stdin to `exec`.

Upgrading to `master` seems to have worked, so I suppose 1.7.1 would too.

**Comment by afbjorklund** [comment]
Builds are working again, with `1.7.1-dev`.
