### ISSUE TITLE
feature request: support pods in `systemd generate --new`

### ISSUE THREAD

**Issue by apollo13** [containers/libpod#4875]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman generate systemd --new pod` currently fails with:
```
Error: error generating systemd unit files: cannot generate generic files for a pod
```

**Steps to reproduce the issue:**

1. Run `podman generate systemd --new pod` on a pod

After talking to @mheon on IRC he suggested to open a feature request since it should be technically possible to create such a systemd file.

**Comment by vrothberg** [comment]
I'll pick this one. It's already on my todo list but I deferred tackling it as I wanted to think a bit about an elegant way to find a mapping to the pod.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @apollo13 !

**Comment by rhatdan** [comment]
@vrothberg hasn't some of this been implemented?

**Comment by vrothberg** [comment]
It has been for containers but not for pods. I will tackle this after my PTO. The v2 API (and the bugs) had a higher priority in past weeks.

**Comment by rhatdan** [comment]
No problem,

**Comment by runiq** [comment]
Any news on this? I'd love not having to keep around the container config files when creating systemd units for pods :)

**Comment by vrothberg** [comment]
Not yet. I expect to be working on this in May. Note that you can create systemd units for pods but not (yet) with the `--new` flag.

**Comment by vrothberg** [comment]
I going through issues at the moment and noticed that this one is covered mutliple times. Given https://github.com/containers/libpod/issues/5605 has a more recent conversation, I am going to close this one here and ask to move comments over to https://github.com/containers/libpod/issues/5605.
