### ISSUE TITLE
Update Ubuntu installation documentation

### ISSUE THREAD

**Issue by shaicoleman** [containers/libpod#4885]
**Description**
The installation instructions for Ubuntu are out of date, now that builds are available through OBS.
https://podman.io/getting-started/installation

In the Atomic PPA, the description needs to be updated to say it's deprecated
https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Comment by kisst** [comment]
Builds are also failing on the PPA, the dependency list on the install page contains packages which are not available on the default repo( like btrfs-tools ), currently I would say it's not possible to install `podman` on Ubuntu, a distro which cover quite a large user-base. 

An install instruction update is needed for sure.

**Comment by rhatdan** [comment]
This PR was merged 5 hours ago.  Does this fix your needs?

**Comment by kisst** [comment]
Once that repo version of the install instruction is published to the main website ( podman.io ) then this issue can be closed, but yes I managed to use the opensuse builds to install on Ubuntu based on the repo's version of the install instruction.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
Fixed by @lsm5 in https://github.com/containers/podman.io/pull/182
