### ISSUE TITLE
How to mount new volume(s) into my home folder with podman run(rootless)?

### ISSUE THREAD

**Issue by jonasbartho** [containers/libpod#4891]
/kind bug ?

I really really want my firm to go away from docker and completely switch to rootless podman....  The only problem I have with rootless podman is that I can't mount new volumes in my own home folder? I asked Daniel Walsh 2 months-ish ago and he said that it should have been fixed in the master branch(I was using v1.6.2 on fedora 30 back then)

Now I am trying the same thing with podman v1.7.0 on Fedora 31 , but still without any success? Am I still doing something wrong? 

Example that works with docker:
$ sudo docker run -v $HOME/neo4j/data:/data neo4j

What I try as rootless podman:
§ podman run --privileged -v $HOME/neo4j/data:/data neo4j
##error message:
_Error: error checking path  "/home/jonas/neo4j/data": stat  /home/jonas/neo4j/data: no such file or directory_

If i create the folders manually with my local user it works... but my users at my firm want to use the "--volume/-v" parameter to mount up new folders in their home folders...

PS: SELinux is temporarily disabled for troubleshoot purposes...

**Comment by rhatdan** [comment]
@jonasbartho You want it to create a new directory on your host when you mount it, and we decided to reject this fix.  My problem with it, is it can lead to errors where a typo accidentally succeeds.  If Docker creates new directories on the host, when you volume mount them in, I believe this is a bug. 

To me this is like saying
mount -o bind /home/jonas/neo4j/data /mnt
and expecting the mount program to create  `/home/jonas/neo4j/data` directory

**Comment by jonasbartho** [comment]
Aha, thank you for this clarification @rhatdan! I see your point!  👍 
Such small differences in comparison to docker like this one should be proper documented to avoid misunderstandings.
