### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by NickJLange** [containers/libpod#4903]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I've not been happy with the process to get podman working on a raspberry pi. As such, I've written an ansible role that solves this problem - if a binary distribution is ever created, then this ansible role would be deprecated. 

*Question* Is there general guidance on how to increase the quality ( I don't really need name attribution) to point raspberry pi users at this role? 

**Additional information you deem important (e.g. issue happens only occasionally):**

[Galaxy Link](https://galaxy.ansible.com/nickjlange/podmansetupraspberrypi)

**Output of `podman version`:**

```
njl@marsAlpha:~ $ podman --version
podman version 1.5.1

```

**Output of `podman info --debug`:**

```
njl@marsAlpha:~ $ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: Unknown
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.11-dev, commit: 77f4a5131bfc344ab4485cd3f1e4644bfa2122e2'
  Distribution:
    distribution: raspbian
    version: "10"
  MemFree: 525623296
  MemTotal: 971063296
  OCIRuntime:
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  SwapFree: 480768000
  SwapTotal: 536866816
  arch: arm
  cpus: 4
  eventlogger: journald
  hostname: marsAlpha
  kernel: 4.19.75-v7+
  os: linux
  rootless: true
  uptime: 385h 2m 50.01s (Approximately 16.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /home/njl/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/njl/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1001
  VolumePath: /home/njl/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
njl@marsAlpha:~ $ apt list podman
Listing... Done

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Raspberry Pi - 2/3/4.

**Comment by afbjorklund** [comment]
It would probably be easier to cross-compile this from the laptop ?

`GOARCH=arm GOARM=6 make podman`

https://github.com/golang/go/wiki/GoArm

Note that you might to have to run `make varlink_generate` first...

Some of the generated binaries might crash with `qemu-arm`.
And the detection scripts don't really work when cross-compiling.

```
GO111MODULE=off go generate ./cmd/podman/varlink/...
qemu: unhandled CPU exception 0x10004 - aborting
R00=00000000 R01=0000001e R02=002125f8 R03=00000000
R04=00000001 R05=00000000 R06=00000000 R07=0013d994
R08=00000007 R09=000000e0 R10=00400540 R11=0022103c
R12=00000034 R13=00445f8c R14=00018f50 R15=000639ec
PSR=20000010 --C- A usr32
signal: aborted (core dumped)
cmd/podman/varlink/generate.go:3: running "go": exit status 1
```

```
GO111MODULE=on go build -mod=vendor ... -tags "   selinux systemd exclude_graphdriver_devicemapper seccomp varlink" ...

build github.com/seccomp/libseccomp-golang: cannot load github.com/seccomp/libseccomp-golang: no Go source files
```

**Comment by afbjorklund** [comment]
This would of course also be fixed by #4811 - or, even better, by #1742

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930440

Note that the default kernel might not be optimal for running containers.

See https://blog.hypriot.com/post/verify-kernel-container-compatibility/

**Comment by NickJLange** [comment]
Thanks for the links. Based on the links, it seems normal users will not have to go through the pain of building this manually. So the first question is answered - this playbook will shortly be  redundant except for folks playing on the bleeding edge. 

> re: It would probably be easier to cross-compile this from the laptop ?

I agree. That was plan A. Alas, across the eco-system (podman, buildah, skopeo, slirp4netns etc) it gets painfully complex unless I'm on a linux-based box. 

Anyway - thanks for the pointers. Glad raspbian support is inching forward.

**Comment by afbjorklund** [comment]
Another approach is changing Linux distribution, and use something like Ubuntu or Fedora instead...

Then you get support for the `aarch64` (arm64) architecture, as well as package support for `podman`.

Raspbian is a 32-bit architecture for backwards-compatiblity, so it runs arm even on 64-bit processors.

But there is no reason why both can't be supported... Especially for the older 32-bit generations of Pis.

----

I'm doing a rather special distribution called **boot2podman**, which _will_ be available also for ARM.

See https://boot2podman.github.io/2019/10/13/containers-on-arm.html (it uses [Tiny Core](http://www.tinycorelinux.net/): PiCore)

**Comment by vrothberg** [comment]
@NickJLange, can you state which problems you encountered? As @afbjorklund has mentioned, Podman is packaged for many distributions, which support the Raspberry Pi.

In case you want to build everything from scratch, refer to the following guide: https://github.com/containers/libpod/blob/master/install.md#building-from-scratch

**Comment by lsm5** [comment]
@NickJLange have you seen the raspbian section in the [install doc](https://github.com/containers/libpod/blob/master/install.md). Let me know if any issues..

**Comment by afbjorklund** [comment]
@lsm5 : there are some issues with the Raspbian instructions.

Some minor:
`-bash: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list: Permission denied`

Some major:
`E: Unable to locate package podman`

Also, you probably want to have `varlink`, `libvarlink` and `libvarlink-dev` in different packages ?

**Comment by afbjorklund** [comment]
Apparently the 32-bit builds for arm are failing in OBS:
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

**Comment by Ciantic** [comment]
Besides the first line missing sudo, I'm encountering also the fact that podman is not available. 

```
sudo /bin/bash -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/Raspbian_10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:testing/Raspbian_10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update -qq

pi@raspberrypi:~ $ sudo apt-get install podman
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package podman
```

**Comment by NickJLange** [comment]
> @NickJLange have you seen the raspbian section in the [install doc](https://github.com/containers/libpod/blob/master/install.md)? Let me know if any issues..

Indeed I have! All I'm doing (for the ecosystem) is wrapping that up in a glorified for-if-then-do compile and build script

> @NickJLange, can you state which problems you encountered? As @afbjorklund has mentioned, Podman is packaged for many distributions, which support the Raspberry Pi.

My problem is building the ecosystem (podman, buildah, skopeo etc) and distribution across my fleet of rpis. This playbook automates this chore away until the raspbian repos are updated to allow "apt install libpod." All the work separately referenced is progress towards making the playbook redundant.


> I'm doing a rather special distribution called **boot2podman**, which _will_ be available also for ARM.
> 
> See https://boot2podman.github.io/2019/10/13/containers-on-arm.html (it uses [Tiny Core](http://www.tinycorelinux.net/): PiCore)

Thank you - I look forward to trying this out next holiday.

**Comment by lsm5** [comment]
ack, I'll sort this out and get back to you..

**Comment by lsm5** [comment]
`podman_1.7.0~2` succeeded for raspbian 10 on OBS. So please give this another try.

@afbjorklund i'll work on splitting varlink packages next ..

**Comment by baude** [comment]
@lsm5 i personally would disable varlink supported in any build for rasberry pi.

**Comment by rhatdan** [comment]
A very impressive demo at devconf.cz was using the virtual kublet talking varlink to podman on a raspberry pi
https://github.com/virtual-kubelet/podman

**Comment by lsm5** [comment]
> @lsm5 i personally would disable varlink supported in any build for rasberry pi.

@baude why so? arch issues or other hardware limitations?

**Comment by baude** [comment]
because long-term varlink support for us will be deprecated and I just don't know that it is worth it.

https://podman.io/blogs/2020/01/17/podman-new-api.html

**Comment by afbjorklund** [comment]
Then again the varlink support is already there, and the new HTTP API is not really out yet ?

Varlink (the binary) is also really really small, it is the build system that is big (hello, meson)

**Comment by rhatdan** [comment]
We are going to be supporting varlink for quite a while longer, so I think we should put it in.

**Comment by vrothberg** [comment]
I am closing the issue. Podman 1.7 is now available, see https://github.com/containers/libpod/issues/4903#issuecomment-577233696
