### ISSUE TITLE
Fedora 31: Can't run selenium/hub container image

### ISSUE THREAD

**Issue by henrywang** [containers/libpod#4904]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Can't run selenium/hub:3 image and get the following error:
```
➜ podman logs hub
2020-01-19 07:34:37,788 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2020-01-19 07:34:37,790 INFO supervisord started with pid 3
2020-01-19 07:34:38,792 INFO spawnerr: unknown error making dispatchers for 'selenium-hub': EACCES
2020-01-19 07:34:39,793 INFO gave up: selenium-hub entered FATAL state, too many start retries too quickly
```
And after I delete `/var/home/xiaofwan/.config/containers/libpod.conf`, `libpod.conf` can't be generated automatically

**Steps to reproduce the issue:**

1. run `podman run -d --network host --name hub --privileged selenium/hub:3`

**Describe the results you received:**
Can't get container started

**Describe the results you expected:**
Have container started without any error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 5421518848
  MemTotal: 8215134208
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8359243776
  SwapTotal: 8359243776
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.4.8-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 2h 37m 9.04s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/home/xiaofwan/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/xiaofwan/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/xiaofwan/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
I take it, you are running rootless?  Can you try running this container as root.
My usual suspects on this type of issue, is something in User Namespace is blocking the access.  Of course another potential problem would be SELinux.  So if SELinux is enabled, could you try with `setenforce 0`

**Comment by henrywang** [comment]
Thanks @rhatdan! You always have such a quick response! :+1: 
1. Yes, I'm running rootless.
2. Tried run with root, same error log.
3. Still have same issue after setting SELinux to Permissive mode.
4. Podman is able to create libpod.conf automatically if it does not exist. But it does not work in Silverblue. I tried on my Fedora 31 machine, it works. Is it related with home directory different? (`/var/home/xiaofwan` for Silverblue, not `/home/xiaofwan`)

**Comment by rhatdan** [comment]
Well if this fails as root, then it is not a rootless issue.  Does the container work with docker?  Does the container work if you run it with `--privileged` flag?

**Comment by henrywang** [comment]
This image is download from `docker.io/selenium/hub`, and same image works on my Fedora 31 machine running with `podman`.
No, it does not work with `--privileged` flag.

**Comment by henrywang** [comment]
@rhatdan, I can use the `--user root` option to get the hub and nodes running. Do you have any ideas about the reason? Thanks!

**Comment by rhatdan** [comment]
You are saying you needed to run this command
```
$ podman run --user root -d --network host --name hub --privileged selenium/hub:3
```
And it worked?  This should be the default, unless selenium/hub:3 defaults to running as a non root user?

**Comment by henrywang** [comment]
Yes. It worked. The `selenium/hub:3` runs as `seluser`, not `root`.

**Comment by rhatdan** [comment]
Then that means the selenium/hub image is incorrect and should be fixed.  It seems like there is a permission issue, and the seluser is not able to do what it needs.

**Comment by henrywang** [comment]
Got it! Thanks @rhatdan.

**Comment by henrywang** [comment]
@rhatdan, I tried same container image `selenium/hub:3` on Fedora 30, everything works well.
The difference is `cgrouip v1` vs `cgroup v2` and `runc` vs `crun`. Is that possible that the cgroup or crun caused this issue? Thanks!

**Info on Fedora 30:**
`podman version`
```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.12.14
OS/Arch:            linux/amd64
```
`podman info --debug`
```
debug:       
  compiler: gc
  git commit: ""       
  go version: go1.12.14   
  podman version: 1.7.0        
host:      
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:  
    package: conmon-2.0.2-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: a89d21975ee86e84e0b0e1c0f887687582f4b0e3'
  Distribution:
    distribution: fedora      
    version: "30"      
  MemFree: 169222144
  MemTotal: 1024778240                    
  OCIRuntime:    
    name: runc
    package: runc-1.0.0-95.rc9.gitc1485a1.fc30.x86_64
    path: /usr/bin/runc
    version: |-                        
      runc version 1.0.0-rc9+dev        
      commit: 0840802d505e28d3adcbc7a275cbeadbdf64ddec
      spec: 1.0.1-dev      
  SwapFree: 1291567104          
  SwapTotal: 1291841536    
  arch: amd64             
  cpus: 1    
  eventlogger: journald
  hostname: m1.cockpit.lan            
  kernel: 5.4.7-100.fc30.x86_64                                                                
  os: linux
  rootless: false                              
  uptime: 7m 43.26s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by henrywang** [comment]
Hey @rhatdan,
I downgrade `podman` to `1.6.2` from `1.7.0` on Fedora 31. Running `podman run -d --network host --name hub --privileged selenium/hub:latest` (non-root) works.
Any changes between 1.6.2 and 1.7.0 caused this issue? Thanks!

**Comment by mheon** [comment]
If you only downgraded Podman, it's not `crun` or CGroups v2

**Comment by rhatdan** [comment]
Can you confirm that going back to podman 1.7.0, it is broken again?

**Comment by vrothberg** [comment]
I cannot reproduce on F31 in the very same setup (crun, cgroupsv2, podman 1.7).

@henrywang, are you still seeing the issue?

**Comment by henrywang** [comment]
Sorry for late response. Just came back from my vacation.
@rhatdan, I update to podman 1.7.0. Still have same issue.
@vrothberg, Updating to podman 1.8.0 doesn't fix this issue.
And I have the same issue on both my laptop and my workstation. Both of them are running on F31, my laptop is running F31 Silverblue.

**Comment by rhatdan** [comment]
@henrywang Earlier you said it was working on NON Silverblue F31, now it is broken?  Have you tried to identify exactly what is failing within the container?

You also said that if you launch this with --user root it works, is this still the case?

**Comment by henrywang** [comment]
Thanks @rhatdan.
1. Yes, it was working on F31(non-silverblue) before (with podman `1.6.2`), and it's broken now because my F31(non-silverblue) got system update (podman updated to `1.7.0` and then `1.8.0`).
2. Looks `supervisord` cannot start selenium service
3. `--user root` works on podman `1.8.0` and `1.7.0`

Summary: (Same selenium/hub:3 image)
1. Podman `1.6.2` works even no `--user root` added.
2. Podman `1.7.0` and `1.8.0` work only with `--user root` added.

**Comment by rhatdan** [comment]
Have you been able to strace what is blowing up?

Most likely would be some file/directory path has changed that used to be accessible by non-root is now changed.  And the processes inside the container are getting permission denied. 

I would figure it is something in /dev or one of the mounted file system objects.

**Comment by rhatdan** [comment]
Since this has been over a month with no response, I will close.  Reopen if this is still happening and you have more output.
