### ISSUE TITLE
podman build fails to emulate systemd (daemon-reload) while setting up postgresql

### ISSUE THREAD

**Issue by groovyman** [containers/libpod#4909]
/kind bug
Podman run has a useful support for systemd (--systemd) during build and runtime. On Fedora you have to allow `container_manage_cgroup` and then you can build and later run this Dockerfile:

```
FROM fedora
RUN dnf -y install httpd; dnf clean all; systemctl enable httpd
EXPOSE 80
CMD [ "/sbin/init" ]`
```

This is great! But when you try to do the same with postgres, you will receive an error:

It is clear to me, that configuring the httpd is easier because you need no running server to get your configuration done. But with postgres, you need a functional systemd or a surrogate, when you are enforced to run:

```
RUN /usr/sbin/postgresql-new-systemd-unit --unit postgresql@kivi --datadir ${POSTGR_KIVI_DATADIR}
```

Unfortunately this calll will give you a:
```
STEP 38: RUN /usr/sbin/postgresql-new-systemd-unit --unit postgresql@kivi --datadir  ${POSTGR_KIVI_DATADIR}
2020-01-20T12:34:06.000813580Z: cannot configure rootless cgroup using the cgroupfs manager
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
FATAL: Can not perform 'systemctl daemon-reload'
 * cleaning up created dropin directory
Error: error building at STEP "RUN /usr/sbin/postgresql-new-systemd-unit --unit postgresql@kivi --datadir  ${POSTGR_KIVI_DATADIR}": error while running runtime: exit status 1
```

**Steps to reproduce the issue:**

1. Try to setup up postgresql in the most recent fedora version
2. while building the image, Initialize the database calling postgresql-new-systemd-unit 

**Describe the results you received:**

The initialization of httpd is possible inside a podman build, i would expect to do the same with a database.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
-- a standard F31 
[cgroove@buster docker_kivitendo]$ podman version
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
[cgroove@buster docker_kivitendo]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.9-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 7d46f3e7711aa3578488284ae2f98b447658f086'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 4288081920
  MemTotal: 12284686336
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 10449399808
  SwapTotal: 10737414144
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: buster
  kernel: 5.4.10-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 86h 17m 43.36s (Approximately 3.58 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/cgroove/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.3-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.3
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/cgroove/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 46
  RunRoot: /run/user/1000
  VolumePath: /home/cgroove/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
do you get the same error if the executable you run in the container is named `init` or `systemd`?

**Comment by groovyman** [comment]
Salut Guiseppe,
i took the Dokerfile of the httpd-System example into mine, so these are the recent lines:

```
FROM fedora

#
# mount volumes
#
VOLUME [ "/var/lib/pgsql/data" ]


#
# Software setup
#

# Packages
# perform updates 
RUN dnf -y update
# perform install (later add mod_fcgid )
RUN dnf -y install  httpd mod_fcgid postgresql-server postgresql-contrib\
  perl-Algorithm-CheckDigits perl-Archive-Zip perl-CPAN perl-Class-XSAccessor \
  perl-Clone perl-Config-Std perl-DBD-Pg perl-DBI perl-Daemon-Generic \
  perl-DateTime perl-DateTime-Set perl-Email-Address perl-Email-MIME perl-FCGI \
  perl-File-Copy-Recursive perl-File-Flock perl-File-MimeInfo perl-File-Slurp \
  perl-GD perl-HTML-Restrict perl-JSON perl-List-MoreUtils perl-List-UtilsBy \
  perl-Net-SMTP-SSL perl-Net-SSLGlue perl-PBKDF2-Tiny perl-PDF-API2 \
  perl-Params-Validate perl-Regexp-IPv6 perl-Rose-DB perl-Rose-DB-Object \
  perl-Rose-Object perl-Sort-Naturally perl-String-ShellQuote \
  perl-Template-Toolkit perl-Text-CSV_XS perl-Text-Iconv perl-URI perl-XML-Writer \
  perl-YAML perl-libwww-perl cpanminus \
  php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd php-fpm php-xml \ 
  texlive-scheme-medium langpacks-de git

# kick out unused packacges
RUN dnf clean all

# Need access to cpan to get DateTime-Event-Cron (sad)
RUN cpanm  DateTime::Event::Cron

#
# ## setup database 
#
# enable the database in systemd
RUN systemctl enable httpd
RUN systemctl enable postgresql

# initialize the database
RUN /usr/sbin/postgresql-new-systemd-unit --unit postgresql@kivi --datadir  ${POSTGR_KIVI_DATADIR}


# run the system/init daeman  (the bottom)
CMD [ "/sbin/init" ]

```

**Comment by groovyman** [comment]
The steps around the occurence of `daemon-reload`  has been described here:
https://pgstef.github.io/2018/02/28/custom_pgdata_with_systemd.html

**Comment by mheon** [comment]
Does Buildah have the same systemd integration Podman does? That would be the first thing I'd suspect

**Comment by groovyman** [comment]
As far as i understood, podman uses buildah and libpod. Anyway the build process should allow the setup of all services, so we need a better build support for systemd.

**Comment by rhatdan** [comment]
No buildah does not have support for running systemd inside of containers only inside of podman.

**Comment by groovyman** [comment]
Salut Daniel (@rhatdan),

### foreword
yes and thanks. That must be the reason, why the dog is called buildah and not runnah!

Ok, anyway my suggestion should be correct, that the podman-build should be able to use systemd and its services. Building may also include a setup of a database.

### my workaround
I found a workaround for this problem. My application needs the httpd and postgres services, in order to get the application running. On this ground i created a new bash driven systemd services, that will execute as a postinstaller the configuration, that can not be done inside podman-build.
This service is created and enabled in the podman-builld phase and is executed when the application is executed the first time. 

The systemd-postinstaller initializes the database and will enable and start postgresql and then httpd. As a very latest step it will disable himself in systemd.

### why i am using systemd and fedora ?
I am trying to run a erp-system inside a container. My aim was to create an instance out of the box for production and testing. Your (Dan's) presentations and articles convinced me to give a rootless podman a try and learn podman and its relation with selinux. (great work!) 
I decided to use F31 because this distribution delivers most of the packages out of the box to run my little erp-system.

**Comment by mheon** [comment]
@nalind PTAL

**Comment by rhatdan** [comment]
Since this is not something Docker supports, and is beyond what we are working on now, I think this has to be contributed someone else.

**Comment by groovyman** [comment]
I solved this issue by my own. I found out, that podman has some minor limitations to perform a `systemctl reload` that was not a big surprise to me. Yes Daniel, your are right, this is not something that even docker is supporting.

But when you try to migrate an application into podman, sometimes you expect to have a full featured linux inside. I found out, that some docker devops are thinking in the same way, when they prefer a `supervirod` init replacement over a docker-compose with a couple of mini-nodes.

My solution was to do as much as possible in a podman-build phase and  then to do the rest while podman-start was starting. I was able to create a postinstall-service in systemd, that was called immediately after start and that executed the things, that wasn't possible while i was in the podman-build phase.
So the postinstall-service was able to configure the postgres database, the httpd service with is application inside and at the end to enable and start both services, that has been loaded while i was running podman-buid.

If you do not want to run a zoo of little node using docker-compose (or podman-compose), this is a old fashioned way to run a fat container. It is ok, but some of the _composer_ might laugh at you and  me ;-)

**Comment by rhatdan** [comment]
@groovyman I am going to close, but this is something we could think about in the future.

**Comment by groovyman** [comment]
> @groovyman I am going to close, but this is something we could think about in the future.

That's ok, i can reply on my workaround.

**Comment by srix55** [comment]
I was building postgresql-13 and was trying with plain buildah's scripting approach. Ideally, I should have been able to get through the systemd requirements to start postgresql in systemd's init in one buildah sitting. I don't want to go to podman to just run systemctl enable postgresql-13. Currently it looks like this is the only way it can be done. Would be great if buildah could do it.

**Comment by rhatdan** [comment]
Not sure what you want @srix55, us to somehow fire up systemd to be able to handle systemctl commands in a build phase?

**Comment by groovyman** [comment]
The origin problem has bean solved for more than a year and it is running perfectly.
The systemd was used to perform some postinstall tasks that needs to be executed once. The trick is to have a script, that performs all the postinstall things as a systemd service, that is automatically been performed by systemd, when `podman run` is beeing called for the very first time. After all things has beeing done (and said) ... the service disables itself and enable the dedicated services.

If you take care and follow the design principles of an immutable container as far as possible, then you got it.

I know, that this strategy was not intended by docker oder podman, now the outdated swarm oder docker/podman-compose or kubernetes think differernt.  Anyway in some cases a fat but immutable container is a useful design, i you want to wrap  an ole fashioned forking unix application into a container that makes use of IPC.

Thanks again and again to Redhat-Dan and his magnificent men in their flying pods.

**Comment by srix55** [comment]
@groovyman @rhatdan Thanks for the clarification. It makes sense to have podman in the final steps of buildah. One question though - how come systemctl enable works in buildah -bud and not in buildah run?

**Comment by groovyman** [comment]
Salut @srix55 i
you are talking abount somewhat different, but i am not sure what you want. Building a container is a process, that is issued by a devop and its talks is to create an image, that can be instantietet as a running container by `podman run`. With podman-create you can autocreate a simple system.d  file, that can be loaded into systemd, in order to get your services in their pods savely shutdown oder restarted when the server performs a reboot.

I do not know anybody, who yould perform the `buildah` or `podman build` by systemd. Or are you talking about a CI/DI pipeline?

**Comment by srix55** [comment]
@groovyman 
Yes... learning how podman works with buildah. Well, I was primarily using buildah to put postgresql onto a RedHat UBI-init image. Since UBI-init is a systemd, I wanted to do a 'systemctl enable postgresql-13' while using buildah run in my bash script. That didn't work as systemctl wasn't available. However, the httpd example given in RedHat UBI-init doc showed systemctl enable working with buildah bud. Tried that and systemctl works fine with bud (Dockerfile), even though a full systemd isn't running in the build phase (I think..). So, was wondering why buildah run doesn't have systemctl while buildah -bud does.

**Comment by rhatdan** [comment]
That sounds like a bug.  If systemctl works in buildah bud, bud not in buildah run.  Could you give me a script that caused the issue.

This script works fine for me.
```
ctr=$(buildah from fedora)
buildah run $ctr dnf -y install systemd postgresql-server
buildah run $ctr systemctl enable postgresql
```

**Comment by srix55** [comment]
@rhatdan Yes... that's working.. Not sure what I was doing wrong to get errors on systemctl enable. I'll switch back to buildah scripting from dockerfile and check. Thanks.
