### ISSUE TITLE
podman (v1.7) load doesn't support other architectures

### ISSUE THREAD

**Issue by vrothberg** [containers/libpod#4917]
Starting with Podman v1.7, we have some more rigorous checks for matching the architecture and os of an image to the local machine. We can override the local machine by using --override-{arch,os} in other Podman commands but it's currently missing for Podman load.

Based on user feedback: https://github.com/containers/libpod/issues/4849#issuecomment-576385798

**Comment by mheon** [comment]
@vrothberg Given we're removing the checks in c/image, can this be closed?

**Comment by vrothberg** [comment]
Let's wait until we merged c/image. Keeping it open might prevent users from a doing a redundant report.

**Comment by vrothberg** [comment]
This has been fixed.
