### ISSUE TITLE
Streaming a tar archive with podman cp - fails

### ISSUE THREAD

**Issue by loibpet** [containers/libpod#4918]
/kind bug

From https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-cp.1.md: 

> If - is specified for either the SRC_PATH or DEST_PATH, you can also stream a tar archive from STDIN or to STDOUT.

However, this is not working, whereas this is working without any issues for docker.

**Steps to reproduce the issue:**

Testing on 2 RedHat 7.7 boxes, one with a podman and the other one with a docker installation.

The following shell script can be used as a test case:
```shell
#!/bin/bash

cd

echo "Hello!" > hello.txt

CONTAINER=`docker run  -v $HOME/.check/tmp802502308:/my-files  -dit --name QyQK5xqR ubi7/ubi:latest /bin/bash`
tar -c hello.txt |  docker cp - $CONTAINER:/tmp

exit 0
```

Gives for podman:
`Error: error evaluating symlinks "": lstat /proc/9633/fd/pipe:[70982]: no such file or directory`

Replacing `docker` with `podman` has no effect. However, if running on an installation with uses `docker` instead of   `podman` then the above script works without any errors.

**Output of `podman version` (Box 1):**
```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `docker version` (Box 2):**
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-84.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Tue Nov  6 18:41:32 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-84.git07f3374.el7.x86_64
 Go version:      go1.10.2
 Git commit:      07f3374/1.13.1
 Built:           Tue Nov  6 18:41:32 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `podman info --debug`:**
```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 2188943360
  MemTotal: 3971801088
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: ip-10-115-125-4.eu-central-1.compute.internal
  kernel: 3.10.0-1062.9.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 3h 28m 12.61s (Approximately 0.12 days)
registries:
  blocked:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
  insecure: null
  search:
  - cl-base-docker-dev-local.artifactory.dbgcloud.io
  - cl-base-docker-dev.artifactory.dbgcloud.io
  - registry.access.redhat.com
store:
  ConfigFile: /home/ea516/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/ea516/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 1
  RunRoot: /run/user/1001
  VolumePath: /home/ea516/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.x86_64 (Box 1)
docker-1.13.1-84.git07f3374.el7.x86_64 (Box 2)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested on RedHat 7.7, running in AWS

**Comment by mheon** [comment]
I feel like we may have fixed this already, but I'm on mobile so I can't
verify. Testing against master would confirm.

**Comment by mheon** [comment]
Confirmed this is fixed on master, closing
