### ISSUE TITLE
[Mac] Man pages are not complete for the remote client on Mac.

### ISSUE THREAD

**Issue by ipbabble** [containers/libpod#4922]
/kind bug

**Description**

On the Mac client (remote client) the complete set of manual pages is not available. Only the highest level man page is available. So for every podman man page you request you get the main podman man page.

**Steps to reproduce the issue:**

1.
Example:
$ podman images
Error: Could not get runtime: dial unix /run/podman/io.podman: connect: no such file or directory
podman(1)()                                                        podman(1)()

NAME
       podman - A Simple management tool for pods, containers and images.

SYNOPSIS
       podman [options] command

2.

3.

**Describe the results you received:**
 See above

**Describe the results you expected:**
I expect to see individual podman sub command man pages when requested.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:
Version:            1.6.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            darwin/amd64

Service:
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

$ brew info cask podman
cask: stable 0.8.4, HEAD
Emacs dependency management
https://cask.readthedocs.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cask.rb
==> Dependencies
Required: emacs ✘
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 4,853 (30 days), 15,526 (90 days), 67,876 (365 days)
install-on-request: 4,776 (30 days), 15,244 (90 days), 66,479 (365 days)
build-error: 0 (30 days)

Error: No available formula with the name "podman"
Found a cask named "podman" instead.

podman: 1.6.0,28-gdac7889d
https://github.com/containers/libpod/
/usr/local/Caskroom/podman/1.6.0,28-gdac7889d (2 files, 47.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/podman.rb
==> Name
podman
==> Artifacts
podman-v1.6.0-28-gdac7889d/podman (Binary)

**Comment by ipbabble** [comment]
FYI the version of Podman on my Fedora 31 server is:
'''
# podman version
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
'''

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@ipbabble Could you open a PR to fix this?  Not likely @jwhonce Will get to it soon, since he is concentrating on APIV2.

**Comment by vrothberg** [comment]
Ping. I guess we had to bump the version of the Mac client as well, right?

**Comment by rhatdan** [comment]
@cevich I think this is because the new versions are not being built?

**Comment by cevich** [comment]
Hrmmm, I'm not sure about this one, @baude do you know where/how that homebrew package comes from?

**Comment by rhatdan** [comment]
@ashley-cui Could you verify the man pages are available?

**Comment by ashley-cui** [comment]
Looks like the manpages are not included in the tarball attached to the release. The remote manpages are compiled differently since I last took a look at them, but once I understand that the fix should be as simple as adding the manpages into the tarball and updating the homebrew ruby install code

**Comment by ashley-cui** [comment]
@mheon Do you know how the `podman-remote-darwin.tar.gz` asset on the latest release was created? It looks like manpages are missing there but `make podman-remote-darwin-release` makes a .zip that has the correct manpages inside. If it's okay, I can just change that asset to the .zip that the make command creates and then update the homebrew formula; this should fix everything

**Comment by mheon** [comment]
The release tars are manually produced by me by means of `make podman-remote-darwin` and tarring the result. A specific make target that produces a tar or zip with appropriate contents would solve this.

**Comment by ashley-cui** [comment]
Closed via https://github.com/Homebrew/homebrew-cask/pull/84399#event-3446294998
