### ISSUE TITLE
[prior to v1.8] Port binding not working in rootless mode

### ISSUE THREAD

**Issue by RobertYost** [containers/libpod#4935]
# **EDIT** (by @AkihiroSuda): If you are hitting an issue similar to this with Podman >= v.1.8.0, you are likely to be hitting https://github.com/containers/libpod/issues/5249, not this issue. 
- - -

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Podman isn't properly binding to a port I specify when running rootless

**Steps to reproduce the issue:**

1. `podman run -d -p 6000:8080 --name <name> <image tag>`

2. `curl http://localhost:6000`
-> Returns `Failed to connect to localhost port 6000: Connection refused`
3. `lsof -i :6000`
-> Returns nothing (i.e. no output, nothing running on port 6000)
4. `podman ps`
-> Lists container as running

**Describe the results you received:**
Container is not published to port, but is running

**Describe the results you expected:**
Expected it to work similarly to `docker run` given the same arguments. When I run `sudo docker run -d -p 6000:8080 --name <name> <image tag>`, the port binding works correctly. However it seems something else is going on with podman, even when using non-privileged ports.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried looking through various other similar issues but unfortunately nothing in those seemed be applicable to me. Specifically issue #661

**Output of `podman version`:**
```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "19.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 257163264
  MemTotal: 1030762496
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: transity
  kernel: 5.0.0-38-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 12h 12m 9.73s (Approximately 0.50 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/default/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/default/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 13
  RunRoot: /run/user/1001
  VolumePath: /home/default/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/disco,now 1.6.2-1~ubuntu19.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on an Ubuntu 19.04 digital ocean droplet

**Comment by mheon** [comment]
There have been major changes in rootless port forwarding in master that
will be landing soon in release 1.7.1 - I think these may resolve your
issue.

**Comment by mheon** [comment]
Also - do you have `slirp4netns` installed at all? Can you confirm it is running when the container is running?

**Comment by RobertYost** [comment]
> Also - do you have `slirp4netns` installed at all? Can you confirm it is running when the container is running?

Looks like it is installed, with version 0.4.2. I'm not quite familiar with how slirp4netns works, how would I go about checking to see if it's running while the container is running?

Also - will make sure to look out for that release, thanks for the heads up.

**Comment by AkihiroSuda** [comment]
Maybe slirp4netns process crashed ?

**Comment by redstorm1** [comment]
I am also suffering from this.

**Comment by rhatdan** [comment]
Any more diagnoses on this?  Is slirp4netns still running when this happens?

**Comment by mheon** [comment]
There was a separate issue where we noticed that RootlessKit was sometimes racing and opening the host port inside the container's network namespace; I'm not sure if this has been fixed.

**Comment by AkihiroSuda** [comment]
@mheon We need that to be fixed as well, but not related to this issue (v1.6.2)

**Comment by AkihiroSuda** [comment]
opened issue https://github.com/containers/libpod/issues/5249 as the reminder

**Comment by xcffl** [comment]
````
Version:            1.8.2-dev
RemoteAPI Version:  1
Go Version:         go1.14rc1
Git Commit:         494b39aced39992c804045232055290cbb7eeafb-dirty
Built:              Sat Aug  4 08:00:00 2018
OS/Arch:            linux/amd64
````
1.8.2 the issue still exists.
After the container being created, if I `curl` the opened port, it firstly says
````
curl: (56) Recv failure: Connection reset by peer
````
The following `curl` will then return
````
curl: (7) Failed to connect to 0.0.0.0 port 8001: Connection refused
````

There is nothing listening to that port (by checking `ss -lp 'sport = :port_number'`.
However, the corresponding slirp4netns process is alive (which has a `"SandboxKey": "/run/user/1000/netns/cni-xxxxxxxxxxx"`

**Comment by aleks-mariusz** [comment]
I too seem to have developed this issue (which straingely at one point previously, it _was_ working but now i have fallen afoul of this same problem) and interesting bit here is that i'm using Podman 1.8.1 (contrary to the title saying _prior-to-v1.8_.. 

<details><summary>full `--log-level=debug` output of my podman run..</summary>
```
pi@raspberrypi:~ $ podman run -p 8080:80 --log-level=debug -d --name octoprint14 --device /dev/ttyUSB0:/dev/ttyUSB0 -v ./octoprint-data:/data docker.io/aleksmariusz/octoprint:1.4.0-20200315
DEBU[0000] Using conmon: "/usr/libexec/podman/conmon"
DEBU[0000] Initializing boltdb state at /home/pi/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver vfs
DEBU[0000] Using graph root /home/pi/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/pi/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/pi/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] No store required. Not opening container store.
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/lib/cri-o-runc/sbin/runc"
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
DEBU[0000] Failed to add podman to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH
INFO[0000] running as rootless
DEBU[0000] Using conmon: "/usr/libexec/podman/conmon"
DEBU[0000] Initializing boltdb state at /home/pi/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver vfs
DEBU[0000] Using graph root /home/pi/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000/containers
DEBU[0000] Using static dir /home/pi/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Using volume path /home/pi/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "vfs"
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/lib/cri-o-runc/sbin/runc"
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
DEBU[0000] parsed reference into "[vfs@/home/pi/.local/share/containers/storage+/run/user/1000/containers]docker.io/aleksmariusz/octoprint:1.4.0-20200315"
DEBU[0000] parsed reference into "[vfs@/home/pi/.local/share/containers/storage+/run/user/1000/containers]@ed54200e51ae0bada984869bf989ce15b9da688b483b2aaad76d389f68afe6e3"
DEBU[0001] exporting opaque data as blob "sha256:ed54200e51ae0bada984869bf989ce15b9da688b483b2aaad76d389f68afe6e3"
INFO[0001] Using "amd64" (architecture) on "arm" host
DEBU[0001] Adding image volume at /data
DEBU[0001] User mount ./octoprint-data:/data options []
DEBU[0001] Using slirp4netns netmode
DEBU[0001] No hostname set; container's hostname will default to runtime default
DEBU[0001] Loading seccomp profile from "/usr/share/containers/seccomp.json"
DEBU[0001] Adding mount /proc
DEBU[0001] Adding mount /dev
DEBU[0001] Adding mount /dev/pts
DEBU[0001] Adding mount /dev/mqueue
DEBU[0001] Adding mount /sys
DEBU[0001] Adding mount /sys/fs/cgroup
DEBU[0001] Adding mount /dev/ttyUSB0
DEBU[0001] setting container name octoprint14
DEBU[0001] created OCI spec and options for new container
DEBU[0001] parsed reference into "[vfs@/home/pi/.local/share/containers/storage+/run/user/1000/containers]@ed54200e51ae0bada984869bf989ce15b9da688b483b2aaad76d389f68afe6e3"
DEBU[0001] exporting opaque data as blob "sha256:ed54200e51ae0bada984869bf989ce15b9da688b483b2aaad76d389f68afe6e3"
DEBU[0269] created container "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134"
DEBU[0269] container "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134" has work directory "/home/pi/.local/share/containers/storage/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata"
DEBU[0269] container "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134" has run directory "/run/user/1000/containers/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata"
DEBU[0270] New container created "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134"
DEBU[0270] container "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134" has CgroupParent "/libpod_parent/libpod-8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134"
DEBU[0270] mounted container "8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134" at "/home/pi/.local/share/containers/storage/vfs/dir/7c1761570617b7af18233bf1c32bc973ffc82a9ead56dd7e699e89b9183e3a1d"
DEBU[0270] Created root filesystem for container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 at /home/pi/.local/share/containers/storage/vfs/dir/7c1761570617b7af18233bf1c32bc973ffc82a9ead56dd7e699e89b9183e3a1d
DEBU[0270] Made network namespace at /run/user/1000/netns/cni-f90a8d46-63ff-c746-30d9-b986047843d7 for container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134
DEBU[0270] slirp4netns command: /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-f90a8d46-63ff-c746-30d9-b986047843d7 tap0
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="starting parent driver"
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="opaque=map[builtin.socketpath:/run/user/1000/libpod/tmp/rootlessport281369407/.bp.sock builtin.readypipepath:/run/user/1000/libpod/tmp/rootlessport281369407/.bp-ready.pipe]"
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="starting child driver in child netns (\"/proc/self/exe\" [containers-rootlessport-child])"
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="waiting for initComplete"
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="initComplete is closed; parent and child established the communication channel"
DEBU[0272] rootlessport: time="2020-03-17T13:07:24Z" level=info msg="exposing ports [{8080 80 tcp }]"
DEBU[0273] rootlessport is ready
DEBU[0273] rootlessport: time="2020-03-17T13:07:25Z" level=info msg=ready
time="2020-03-17T13:07:25Z" level=info msg="waiting for exitfd to be closed"
DEBU[0273] skipping loading default AppArmor profile (rootless mode)
DEBU[0273] /etc/system-fips does not exist on host, not mounting FIPS mode secret
DEBU[0273] set root propagation to "rslave"
DEBU[0273] Created OCI spec for container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 at /home/pi/.local/share/containers/storage/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata/config.json
DEBU[0273] /usr/libexec/podman/conmon messages will be logged to syslog
DEBU[0273] running conmon: /usr/libexec/podman/conmon    args="[--api-version 1 -c 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 -u 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 -r /usr/lib/cri-o-runc/sbin/runc -b /home/pi/.local/share/containers/storage/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata -p /run/user/1000/containers/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata/pidfile -l k8s-file:/home/pi/.local/share/containers/storage/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata/ctr.log --exit-dir /run/user/1000/libpod/tmp/exits --socket-dir-path /run/user/1000/libpod/tmp/socket --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/vfs-containers/8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/pi/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg vfs --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134]"
WARN[0273] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup for cpuset: mkdir /sys/fs/cgroup/cpuset: read-only file system
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0275] Received: 4104
INFO[0275] Got Conmon PID as 4093
DEBU[0275] Created container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 in OCI runtime
DEBU[0275] Starting container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 with command [/usr/bin/entry.sh /usr/local/bin/python /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf]
DEBU[0275] Started container 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134
8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134
```
</details>

I am trying to work out what might have changed that caused it to get into this state, but am running out of ideas (i've tried reverting every change since it worked).  Could really use some help what might have changed, what to check for next?

```
pi@raspberrypi:~ $ podman ps -a
CONTAINER ID  IMAGE                                            COMMAND               CREATED         STATUS             PORTS                 NAMES
8abe143bceb5  docker.io/aleksmariusz/octoprint:1.4.0-20200315  /usr/local/bin/py...  22 minutes ago  Up 18 minutes ago  0.0.0.0:8080->80/tcp  octoprint14

I also checked to make sure the port isn't being bound _inside_ the container..

```
pi@raspberrypi:~ $ podman exec octoprint14 netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      13/python
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
```

and that the port inside the container is listening properly.. 

```
pi@raspberrypi:~ $ podman exec octoprint14 nc -vz localhost 80
localhost (127.0.0.1:80) open
```

but outside the container, on the host, the port is not open :-( 

```
pi@raspberrypi:~ $ nc -vz localhost 8080
nc: connect to localhost port 8080 (tcp) failed: Connection refused
```

Also i made sure slirp4netns is running (i'm not sure if there's a difference using that, and rootlesskit for port forwarding.. or how to change which implementation i use):

```
  PID USER      CPU% MEM% S  NI TTY       VIRT   RES   SHR   OOM NLWP   DISK READ  DISK WRITE  UTIME+   STIME+  START Command                                                                                                                                    
    1 root       0.0  1.7 S   0 ?        14952  4008  2644     0    1     no perm     no perm  0:02.95  0:05.31 Jan01 /sbin/init                                                                                                                                 
 4093 pi         0.0  0.7 S   0 ?        14928  1652  1408     7    2    0.00 B/s    0.00 B/s  0:00.00  0:00.06 13:07 `- /usr/libexec/podman/conmon --api-version 1 -c 8abe143bceb537673e5d6ccb2fa0548c2b7c7770efd7715cd5ca885b4972e134 -u 8abe143bceb537673e5d6c
 4104 pi         0.0  5.6 S   0 ?        15804 12964  4500    55    1    0.00 B/s    0.00 B/s  0:12.54  0:01.39 13:07 |  `- /usr/local/bin/python /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
 4129 pi         6.2 23.3 S   0 ?        70700 54136  5660   233   20    0.00 B/s    0.00 B/s  4:45.24  0:39.58 13:26 |     `- /usr/local/bin/python /usr/local/bin/octoprint --iknowwhatimdoing --basedir /data
 4128 100100     0.0  1.6 S   0 ?         6140  3788  2772    16    1    0.00 B/s    0.00 B/s  0:00.36  0:00.15 13:26 |     `- /usr/sbin/haproxy -db -f /etc/haproxy/haproxy.cfg
 4071 pi         0.0  1.1 S   0 pts/1     5780  2524  1596    10    1    0.00 B/s    0.00 B/s  0:00.21  0:00.89 13:26 `- /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-f90a8d
  747 pi         0.0  0.5 S   0 ?        41232  1064   888     4    1    0.00 B/s    0.00 B/s  0:00.01  0:00.01 11:35 `- podman
  354 pi         0.0  1.3 S   0 ?        14512  3108  2204    13    1    0.00 B/s    0.00 B/s  0:00.53  0:00.19 11:34 `- /lib/systemd/systemd --user
  369 pi         0.0  1.1 S   0 ?        16420  2492  1032    10    1     no perm     no perm  0:00.00  0:00.00 11:34 |  `- (sd-pam)
```

<details><summary>I'm using podman 1.8.1</summary>
```
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/arm
```
</details>

**Comment by AkihiroSuda** [comment]
@xcffl @aleks-mariusz It is likely that you are hitting https://github.com/containers/libpod/issues/5249 , not this issue. The code has significantly changed in v1.8.

**Comment by aleks-mariusz** [comment]
> @xcffl @aleks-mariusz It is likely that you are hitting #5249 , not this issue. The code has significantly changed in v1.8.

Thanks for the pointer, i've copied these details to that issue as well..

**Comment by rhatdan** [comment]
Can we close this issue, if this is fixed in the master branches.  RHEL8.2.1 will have podman 1.9.3.
Reopen if I am mistaken.
