### ISSUE TITLE
generate kube does not include security-opt

### ISSUE THREAD

**Issue by FlorianLudwig** [containers/libpod#4950]
/kind bug

**Description**

The `security-opt` is not included when generated kubernetes pod descriptions.

**Steps to reproduce the issue:**

```
podman run --name test -v `pwd`:/host --security-opt "label=disable" docker.io/library/bash:latest ls /host
podman generate kube > test.yaml
```

**Describe the results you received:**
The `security-opt` has no influence on the generated yaml

**Describe the results you expected:**
the `test.yaml` should contain `securityContext: seLinuxOptions`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Comment by rhatdan** [comment]
label=disable in SELinux terms would translate to 
```
security-object:
    type: spc_t
```
I guess.

@FlorianLudwig interested in opening a PR?

@mheon @haircommander Do we have enough info in the container to know SELinux was disabled.

**Comment by mheon** [comment]
The `io.podman.annotations.label` annotation in newer Podman-created containers should do the jobr

**Comment by rhatdan** [comment]
@QiWang19 PTAL
