### ISSUE TITLE
Empty NetworkSettings when using slirp4netns

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#4955]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The network settings are not written/exposed when running rootless podman on top of slirp4netns.

**Steps to reproduce the issue:**

```
> podman run --name test -d alpine sleep infinity
> podman inspect test | jq .[0].NetworkSettings
```

**Describe the results you received:**

```json
{
  "Bridge": "",
  "SandboxID": "",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": [],
  "SandboxKey": "",
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "",
  "IPPrefixLen": 0,
  "IPv6Gateway": "",
  "MacAddress": ""
}
```

**Describe the results you expected:**

```json
{
  "Bridge": "",
  "SandboxID": "",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": [],
  "SandboxKey": "/var/run/user/1000/netns/cni-912cca20-62b2-074b-0315-fe227fbc8416",
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "10.88.0.1",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "10.88.0.67",
  "IPPrefixLen": 16,
  "IPv6Gateway": "",
  "MacAddress": "12:2e:92:35:75:6d"
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm opening this issue because I want to discuss what the best way would be to implement this. This kind of bug seems to need an additional step in:
https://github.com/containers/libpod/blob/6518421f89e2e953f918d35e44d3d8d7299e06a8/libpod/networking_linux.go#L166-L167

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.12.15
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
I would argue that they don't really have IP addresses, gateways, MAC addresses, etc - they bind against the host, so the addresses don't belong to them.

**Comment by saschagrunert** [comment]
> I would argue that they don't really have IP addresses, gateways, MAC addresses, etc - they bind against the host, so the addresses don't belong to them.

Makes sense, but I would need the information which IP the `tap0` interface got assigned via podman. So we may want to set this field somehow.

**Comment by rhatdan** [comment]
@saschagrunert @mheon @AkihiroSuda Any work being done on this?

**Comment by mheon** [comment]
Not on my end. I think the first conversation has to be what is sane to set (I'm not certain whether we want to provide an IP if it's not reachable from the host, for example)

**Comment by saschagrunert** [comment]
> Not on my end. I think the first conversation has to be what is sane to set (I'm not certain whether we want to provide an IP if it's not reachable from the host, for example)

Hm yeah I agree. So we probably want to close this as wont-fix?

**Comment by rhatdan** [comment]
Won't Fix.
