### ISSUE TITLE
Podman in fedora 31 testing repo

### ISSUE THREAD

**Issue by stbischof** [containers/libpod#4956]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind feature

**Description**

At the moment are the "testing versions" only for Fedora 32 available.

 IT would be great to have them also in Fedora 31

https://github.com/containers/libpod/blob/8beeb067aac857deb29e91562cf4b6f068fe0328/install.md#L167-L178

**Steps to reproduce the issue:**

https://bodhi.fedoraproject.org/updates/?packages=podman

**Comment by TomSweeneyRedHat** [comment]
@lsm5 PTAL

**Comment by baude** [comment]
For stable Fedora version, our process is that we only put packages that are bound for actual stable releases.  To me, this is what upstream is for.   We really want to avoid bug reporting on unreleased versions, though as a user, I can completely understand the desire.

We also have a COPR repo building from upstream -> https://copr.fedorainfracloud.org/coprs/baude/Upstream_CRIO_Family/  Each commit upstream gets built

@rhatdan @mheon what do you think?

**Comment by mheon** [comment]
The COPR might solve the ask here

**Comment by stbischof** [comment]
works for me!
 
you may should add  this to way to the docs

`sudo dnf config-manager --add-repo https://copr.fedorainfracloud.org/coprs/baude/Upstream_CRIO_Family/repo/fedora-31/baude-Upstream_CRIO_Family-fedora-31.repo`

**Comment by rhatdan** [comment]
Could you open a PR to add this to the docs?
