### ISSUE TITLE
Fails to set 'security.selinux' extended file attribute when moving file inside container

### ISSUE THREAD

**Issue by rasup** [containers/libpod#4963]
/kind bug

**Description**

Fails to set 'security.selinux' extended file attribute when moving a file to a mapped volume inside a container.

This causes Python's `shutil.move()` to raise an exception and commandline `mv` to output an error message.
I'm not sure if this is actually a Podman bug but version 1.7.0 exhibits this while 1.6.2 doesn't.

**Steps to reproduce the issue:**

1. On Fedora 31: `mkdir ~/d`

2a. `podman run -i -t -w /root -v ~/d:/root:rw,z fedora:31 bash -c 'touch /tmp/f && python3 -c "import shutil;shutil.move(\"/tmp/f\", \"f\")"'`
or
2b. `podman run -i -t -w /root -v ~/d:/root:rw fedora:31 bash -c 'touch /tmp/f && mv /tmp/f .'`

**Describe the results you received:**
In both 2a and 2b the file is actually copied, but:

2a:

> Traceback (most recent call last):
>   File "/usr/lib64/python3.7/shutil.py", line 566, in move
>     os.rename(src, real_dst)
> OSError: [Errno 18] Invalid cross-device link: '/tmp/f' -> 'f'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib64/python3.7/shutil.py", line 580, in move
>     copy_function(src, real_dst)
>   File "/usr/lib64/python3.7/shutil.py", line 267, in copy2
>     copystat(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/lib64/python3.7/shutil.py", line 209, in copystat
>     _copyxattr(src, dst, follow_symlinks=follow)
>   File "/usr/lib64/python3.7/shutil.py", line 165, in _copyxattr
>     os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
> PermissionError: [Errno 13] Permission denied: 'f'

2b:

> mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied

**Describe the results you expected:**
I expected the file to be moved without any errors.

**Additional information:**
Moving files from `/tmp` to `/tmp`, from `/root` to `/root` or from `/root` to `/tmp` doesn't cause any problems.

**Output of `podman version`:**

```
podman version 1.7.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.9-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 7d46f3e7711aa3578488284ae2f98b447658f086'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 164462592
  MemTotal: 2077921280
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 2146693120
  SwapTotal: 2217734144
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: fedora31.localdomain
  kernel: 5.4.12-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 10h 47m 50.76s (Approximately 0.42 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/vagrant/.config/containers/storage.conf
  ContainerStore:
    number: 13
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/vagrant/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000/containers
  VolumePath: /home/vagrant/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The above info is from a VirtualBox Fedora 31 VM but it can be reproduced on a physical Fedora 31 machine too. I haven't tried reproducing it on other platforms.

**Comment by mheon** [comment]
I assume you're running rootless?

**Comment by mheon** [comment]
@rhatdan Does this sound like a permissions issue because rootless can't set SELinux contexts, or is this more likely to be fuse-overlay?

**Comment by rhatdan** [comment]
The problem is shutil.move python bindings is attempting to copy the Security attributes from the source file to the target file.  I believe the latest shutil.copy code ignores this error, since it will not be allowed within a container.  Since SELinux indicates that it is disabled to processes within the container, shutil should not be attempting to keep these labels.

**Comment by rasup** [comment]
> I assume you're running rootless?

Yes, I am.

> The problem is shutil.move python bindings is attempting to copy the Security attributes from the source file to the target file. I believe the latest shutil.copy code ignores this error, since it will not be allowed within a container. Since SELinux indicates that it is disabled to processes within the container, shutil should not be attempting to keep these labels.

So what you are saying is that it is a bug in `shutil.move`?

**Comment by rhatdan** [comment]
I am saying, I believe in Python3 latest release in Fedora 31, shutil.move has been changed to ignore these errors.
The problem is, there are SELinux Extended attributes on these files and shutil.move is attempting to create them on a fuse-overlay file system.  SELinux is blocking them from being created.  There is nothing Podman or SELinux or fuse-overlay can do to fix this.

**Comment by rasup** [comment]
> I am saying, I believe in Python3 latest release in Fedora 31, shutil.move has been changed to ignore these errors.

I don't think it has. I'm on Fedora 31 using `python3-3.7.6-1.fc31.x86_64` which I believe is the latest version.

I found [this old issue](https://bugs.python.org/issue1438480) which is still open but seems like it would have fixed my issue too.

Thanks!

**Comment by rhatdan** [comment]
I see this in /usr/lib64/python3.7/shutil.py
```
def copymode(src, dst, *, follow_symlinks=True):
...
if hasattr(os, 'listxattr'):
    def _copyxattr(src, dst, *, follow_symlinks=True):
        """Copy extended filesystem attributes from `src` to `dst`.

        Overwrite existing attributes.

        If `follow_symlinks` is false, symlinks won't be followed.

        """

        try:
            names = os.listxattr(src, follow_symlinks=follow_symlinks)
        except OSError as e:
            if e.errno not in (errno.ENOTSUP, errno.ENODATA, errno.EINVAL):
                raise
            return
        for name in names:
            try:
                value = os.getxattr(src, name, follow_symlinks=follow_symlinks)
                os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
            except OSError as e:
                if e.errno not in (errno.EPERM, errno.ENOTSUP, errno.ENODATA,
                                   errno.EINVAL):
                    raise
```

**Comment by rhatdan** [comment]
Looks like the move calls move calls copystat which calls copyxattrs.

**Comment by rasup** [comment]
Yes. `errno.EACCES` is missing from the tuple of allowed errors raised by `os.setxattr()`.

**Comment by rhatdan** [comment]
Yes not sure why they would handle EPERM and EACCESS differently.

**Comment by rhatdan** [comment]
This is a bug in python3, we can not fix it from podman.

**Comment by jnsnow** [comment]
@rhatdan do you know if a python bug got filed? I'm running into this now and this closed issue is at the top of the search results pile.

**Comment by rhatdan** [comment]
No I am not sure if I did open one.

**Comment by rhatdan** [comment]
@giuseppe Didn't you have  a way to handle this in fuse-overlayfs as well?

**Comment by giuseppe** [comment]
we have a way to skip using xattrs, if `noxattrs=1` is specified in the mountopts then it should work

**Comment by jnsnow** [comment]
I am seeing this issue on a f31 host using the f32 container (Which I believe to be using Python 3.8). I have a python script that uses shutil.move() to move files created via tempfile (likely usually in tmpfs, /tmp) to a destination file.

In this case I am using rootless podman and declaring my storage as -v ~/foobar:/foobar:z -- but shutil calls are still causing selinux failures; the troubleshooter indicates it is denying the relabelto/relabelfrom permissions.

(I believe in this case, the container environment would be moving a file from a fuse-overlayfs /tmp to a mapped volume owned by a non-root user.)

I think what's going wrong in my case is that I am using `sample_permissions` to copy the permissions of a file I intend to overwrite onto the tempfile, and *then* I try to move it over a destination file. This causes relabelto/relabelfrom errors everywhere.

It makes sense to me that if I am replacing a file with certain xattrs that I will want the same xattrs to be present on it once replaced; I don't think Python has a bug here exactly. (Maybe the bug is that python throws instead of continuing gracefully, if anything.)

I'll have to look into the specifics of my case more -- maybe this is just a docfix, somewhere, or a blog article. Hope this comment helps future searchers.

--js

**Comment by rhatdan** [comment]
shutils ignores the errors in one place and then fails on them in another.  They should be ignored everywhere.

**Comment by abitrolly** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/shutil.py", line 803, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/var/tmp/mdapi-ggqz7n9j/epel-7_primary.sqlite' -> 'repositories/epel-7_primary.sqlite'
```
And what is the solution for F33?

**Comment by rhatdan** [comment]
Ask the python developers.

**Comment by frafra** [comment]
That's not just Python related. The same problem occurs while running a Fedora 34 container using Podman on a Fedora 34 system and calling the `mv` program from coreutils.

**Comment by PavelSosin-320** [comment]
@giuseppe This bug still exists in podman 4 on Fedora 36 WS beta when rootless user tries to create container. There is no python here, only podman and crun. Container layer can't be created by btrfs storage driver. podman has stopped to work in Fedora 35 and never come back. I already opened issue #https://github.com/containers/storage/issues/1082 on container-storage but never got solution. If the solution was found 2 years ago could it be encapsulated and replicated to all containers packages runnable as rootless?

**Comment by giuseppe** [comment]
> @giuseppe This bug still exists in podman 4 on Fedora 36 WS beta when rootless user tries to create container. There is no python here, only podman and crun.

so that is a different issue.  Let's continue the discussion in https://github.com/containers/storage/issues/1082
