### ISSUE TITLE
Project Kubric bugs?

### ISSUE THREAD

**Issue by astronouth7303** [containers/libpod#4967]
Went to use the Project Kubric builds, found two issues:

* The docker manpages are being shipped in the `podman` binary package
* There is a typo'd directory `/usr/share/bash-completion/comletions/`

What's the best place to file these bugs?

**Comment by vrothberg** [comment]
Thanks for reaching out! This seems related to the opensuse packages, so I suggest to file them at https://bugzilla.opensuse.org.

**Comment by astronouth7303** [comment]
Opened as https://bugzilla.opensuse.org/show_bug.cgi?id=1161824

**Comment by astronouth7303** [comment]
So openSuse says the Deb artifacts of project kubic are managed by upstream.

**Comment by mheon** [comment]
@lsm5 PTAL
