### ISSUE TITLE
[Feature Request] Podman run to accept kube yaml

### ISSUE THREAD

**Issue by mjudeikis** [containers/libpod#4969]
Podman currently can generate kube yaml. It would be amazing if podman could accept kube-yaml and run it locally for local development/debugging outside the cluster. Basically do a roundtrip for kube generate :)

There is some caveats on what can and can't be run. But let's assume YAML was generated by podman, so we could support backward compatibility.

**Comment by mheon** [comment]
We support this via the 'podman play kube' command

**Comment by mjudeikis** [comment]
+1 :) thanks for fast response :)
