### ISSUE TITLE
Add annotations into containers.conf file

### ISSUE THREAD

**Issue by ArangoGutierrez** [containers/libpod#4978]
With the upcoming feature of containers.conf file, having the ability to hard code "--annotation" oci hooks into the conf file will be a good idea and a very handy tool to have.

This will open the door for sysadmins or even users to hard code ocihooks to prepare the environment, bindmount GPU drivers based on nvidia-smi bin or other related use cases, as to also hard code a clean up process for Podman/Buildah.

**Comment by baude** [comment]
@rhatdan wdyt?

**Comment by rhatdan** [comment]
I am fine with this.  We talked about it at devconf.cz

**Comment by rhatdan** [comment]
@ArangoGutierrez Could you open an issue with github.com:containers/common and better yet open a PR on github.com:containers/common/pkg/config/ to add annotations.

**Comment by ArangoGutierrez** [comment]
Happy to do it.

**Comment by ArangoGutierrez** [comment]
https://github.com/containers/common/issues/62
