### ISSUE TITLE
docker and libpod endpoint of Rest API V2

### ISSUE THREAD

**Issue by stbischof** [containers/libpod#4990]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The Post that announces the new rest api v2 https://podman.io/blogs/2020/01/17/podman-new-api.html describes that there are 2 main entpoints.

one For docker and one for libpos

```
<endpoint_base_url>/libpod/images/json
And if you wanted a list of images but in docker-compatibility, you would use:
<endpoint_base_url>/images/json
```

wouldn't it be better to have libpod and docker in  separate

```
<endpoint_base_url>/libpod/images/json
<endpoint_base_url>/docker/images/json
```

**Comment by mheon** [comment]
I don't think we have support for TCP listening in the service command yet,
only unix socket. It is desperately in need of documentation, though

**Comment by stbischof** [comment]
the docy showed me the way to tcp:/

´For example, *unix://tmp/foobar.sock* or *tcp:localhost:8080*.´

https://github.com/containers/libpod/blob/aa13779e9e8d5bb6090d514e3aad9387cb0a2d35/docs/source/markdown/podman-service.1.md#L8-L15

**Comment by rhatdan** [comment]
Doing this is totally unsupported.  You are opening up a root connection on your host with no security protections.  It would work on localhost, but would be very dangerous if you actually listed on a public port.
We would recommend using ssh tunnel. connections to embed the socket connections from a remote host.
@jwhonce is working on a nice solution to make this easy for users to do.

**Comment by baude** [comment]
the service command supports a uri format of tcp or unix more or less.  the format of the URI will change slightly when I get a chance to correct it (tcp:/ vs tcp:// vc tcp:).  I believe the issue you hit is that you don't have the version in the path "v1.24"

**Comment by stbischof** [comment]
All I did with tcp / http / rest is just to test the new features:

This ticket is because i think that the /libpod endpoint should be beside not inside the docker one

<endpoint_base_url>/libpod/images/json
<endpoint_base_url>/docker/images/json

**Comment by rhatdan** [comment]
The installed base of "docker" api callers are going to call
<endpoint_base_url>/images/json, this is not something we can chage.
<endpoint_base_url>/libpod/images/json
is not under
<endpoint_base_url>/images/json

**Comment by stbischof** [comment]
thx!
