### ISSUE TITLE
Is it possible to get `ip link set up` not to fail inside unprivileged container?

### ISSUE THREAD

**Issue by grzegorzk** [containers/libpod#4998]
/kind feature

**Description**

I have a simple container with openvpn process in it. I'm trying to start openvpn in this container as unprivileged user by passing capabilities when executing `podman run`

**Steps to reproduce the issue:**

1. `Dockerfile`:
```
FROM archlinux
RUN pacman -Sy --noconfirm openvpn
```

2. Build image (as unprivileged user)

```
podman build -t openvpn .
```

3. Start container with systemd

`systemd` service:
```
[Unit]
Description=OpenVPN in Podman container
After=syslog.target network-online.target
Wants=network-online.target

[Service]
User=my_unprivileged_user
Group=my_unprivileged_group
ExecStart=/usr/bin/podman run --rm -v /home/my_unprivileged_user/ovpn_config_files/:/ovpn_config_files --device /dev/net/tun --network "host" --cap-add CAP_IPC_LOCK,CAP_NET_ADMIN,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETGID,CAP_SETUID,CAP_SYS_CHROOT,CAP_DAC_OVERRIDE,CAP_AUDIT_WRITE localhost/openvpn:latest tail -f /etc/passwd
ExecStop=/usr/bin/podman stop -t 1 localhost/openvpn:latest
Capabilities=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE
DeviceAllow=/dev/null rw
DeviceAllow=/dev/net/tun rw
RestartSec=5s
Restart=on-failure

[Install]
WantedBy=multi-user.target

```

4. Start the service (as root) results in podman container being started as unprivileged user (expected)

5. As unprivileged user I exec into the container and run:
```
/usr/bin/ip link set dev tun0 up mtu 1500
```

**Describe the results you received:**

`ip link` fails

**Describe the results you expected:**

Since all capabilities are passed I'd expect `ip link` to succeed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
Built:              Sat Jan 11 12:49:39 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
compiler: gc
git commit: b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
go version: go1.13.5
podman version: 1.7.0
host:
BuildahVersion: 1.12.0
CgroupVersion: v1
Conmon:
package: Unknown
path: /usr/bin/conmon
version: 'conmon version 2.0.9, commit: 60b42f20f222df9da07a01ee444327348b9f54ee'
Distribution:
distribution: arch
version: unknown
IDMappings:
gidmap:
- container_id: 0
host_id: 1000
size: 1
- container_id: 1
host_id: 100000
size: 65536
uidmap:
- container_id: 0
host_id: 1000
size: 1
- container_id: 1
host_id: 100000
size: 65536
MemFree: 739700736
MemTotal: 1030991872
OCIRuntime:
name: runc
package: Unknown
path: /usr/bin/runc
version: |-
runc version 1.0.0-rc9
commit: d736ef14f0288d6993a1845745d6756cfc9ddd5a
spec: 1.0.1-dev
SwapFree: 4293914624
SwapTotal: 4293914624
arch: amd64
cpus: 1
eventlogger: journald
hostname: unknown
kernel: 5.4.13-arch1-1
os: linux
rootless: true
slirp4netns:
Executable: /usr/bin/slirp4netns
Package: Unknown
Version: |-
slirp4netns version 0.4.3
commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
uptime: 5m 19.45s
registries:
search:
- docker.io
- registry.fedoraproject.org
- quay.io
- registry.access.redhat.com
- registry.centos.org
store:
ConfigFile: /home/grzegorz/.config/containers/storage.conf
ContainerStore:
number: 1
GraphDriverName: overlay
GraphOptions:
overlay.mount_program:
Executable: /usr/bin/fuse-overlayfs
Package: Unknown
Version: |-
fusermount3 version: 3.9.0
fuse-overlayfs: version 0.7.5
FUSE library version 3.9.0
using FUSE kernel interface version 7.31
GraphRoot: /home/grzegorz/.local/share/containers/storage
GraphStatus:
Backing Filesystem: extfs
Native Overlay Diff: "false"
Supports d_type: "true"
Using metacopy: "false"
ImageStore:
number: 2
RunRoot: /run/user/1000/containers
VolumePath: /home/grzegorz/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
pacman -Q podman
podman 1.7.0-1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Linode (1CPU, 1Gb RAM)

**Comment by rhatdan** [comment]
podman uses user namespaces, if you pass a CAP into podman running rootless, you give it the Capability over the user namespace,  This only effects the container and has no effect on the host OS.  If you attempt to do an activity that requires a real Capability, then this will NOT work.  Rootless users still have no way to get Real Capabilities.

**Comment by grzegorzk** [comment]
Thanks for explanation, I thought capabilities passed through `Capabilities` within service file would be "available" from inside of the container. Is this a feature podman would support in the future?

**Comment by rhatdan** [comment]
I don't know if this is possible.  @giuseppe Any ideas?

**Comment by giuseppe** [comment]
it will work if you create a new network namespace, but you are passing `--network "host"` and an unprivileged user cannot modify the host network namespace

**Comment by rhatdan** [comment]
But he is attempting to leak capabilties into the container.  He granted the process in the unit file CAP_NET_ADMIN which should allow processes in the service to modify the network stack.  
My guess is once you create  User Namespace then all Linux capabilities no longer exists.

**Comment by giuseppe** [comment]
> But he is attempting to leak capabilties into the container. He granted the process in the unit file CAP_NET_ADMIN which should allow processes in the service to modify the network stack.
> My guess is once you create User Namespace then all Linux capabilities no longer exists.

that is not enough.  The user namespace where the user has all the capabilities doesn't own the host host network namespace.

If a network namespace is created, then it is owned by the user namespace where the user has all the capabilities (unless dropped).

The owner of the host network namespace is the initial user namespace, so that is root without running in a new user namespace.  So it would work only from a root container that doesn't create a new user namespace.

**Comment by grzegorzk** [comment]
Indeed when I remove `--network "host"` I'm getting through `tun0` creation and assigning IP address as well as bringing the interface up. I cannot see the external interface from within the container though. I'll search through documentation, I guess I need to set NAT rule to route traffic to that interface.

**Comment by giuseppe** [comment]
> I cannot see the external interface from within the container though. I'll search through documentation, I guess I need to set NAT rule to route traffic to that interface.

that won't be possible though.  A rootless user cannot modify the host network devices.

You'd need to set it up separately as root user

**Comment by grzegorzk** [comment]
That was my understanding. Many thanks for direction.

Ps. I love what you guys are doing and thought for a moment there would be something I could help with.

**Comment by grzegorzk** [comment]
I was digging a bit more and finally landed at the correct documentation here: https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities

Indeed `Capabilities` is not supported anymore and also what's left over will not work for non-system services.
