### ISSUE TITLE
Re-integration to CRIO blockers

### ISSUE THREAD

**Issue by baude** [containers/libpod#500]
We need to reintegrate libpod into cri-o at some near point; however, the following things must be addressed prior to doing so:

- container restart (done!)
- image library implemented fully
- pods implemented
- locking
- conmon cleanup

Please add additional items as needed.

**Comment by mheon** [comment]
I think we have everything we'll need for CRI-O pods merged already. At least initially, I doubt they will be used by CRI-O as much more than a way of organizing containers - CRI-O has its own pod stop/start/remove commands, which are more specialized to Kubernetes pods (one infra container for namespaces, no further dependencies) and will suit their needs better than our pod API. CRI-O also doesn't require container restart (Kube will never restart a container, it will only create a new one).

The biggest issue preventing us from moving forward is locking right now. We need a way of cleaning up file locks on removing containers.

Furthermore, we're going to need work around the APIs for `exec` and `attach` to make them do what Kubernetes expects. `exec` could be a real pain, given we're going to have to plug in `conmon` support for it. This is less critical than locking, though, as we can implement the rest of the CRI without these pretty easily.

We're also probably going to be finding some serious performance issues, but I'm less worried about those than getting us back to 100% E2E and critest passing

**Comment by rhatdan** [comment]
Where do we stand on these issues at this point?

**Comment by wking** [comment]
Low-hanging fruit for this is kubernetes-incubator/cri-o#1517 and anywhere else we can spit out a small package to replace some of CRI-O's current library code.  I don't know how far we can go with that approach, but making the integration a series of smaller pivots will probably make it easier to review.

**Comment by rhatdan** [comment]
I agree I would like to see some small PRs opened to start moving this way.  Perhaps have a large PR that is a WIP, to run the tests and then slowly merge it in.

**Comment by vrothberg** [comment]
This issue looks a bit dusty. Given that some work items have been finished already and others are being worked on: Shall we close this issue?

**Comment by rhatdan** [comment]
Yes I would prefer to break this up, and open individual issues.
