### ISSUE TITLE
Inconsistency between json output of podman ps and podman images

### ISSUE THREAD

**Issue by HarryMichal** [containers/libpod#5001]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Hi, when I run commands `podman ps --format json` and `podman images --format json` I see some inconsistency between those two outputs.
1. Names of entries of containers start with upper case letters (eg. Image, Command,..) and special words are all in capitals (eg, ID, PID,..). In the case of images, the names of entries are always lower cases.
2. The output of `podman ps` has four entries with time: `Create`, `CreatedAt`, `ExitedAt` and `StartedAt`. The entry `Create` is formatted in a human-readable format. The output of `podman images` only holds one time entry: `created` that is machine-readable.
3. *I'm not really sure about this one*. The output of `podman ps` has an entry called `Names` that holds a string. The output of `podman images` has an entry called `names` that holds an array of strings.

Here is my proposed solution (just ideas, I'm open to discussion):
1. Use one of the conventions and stick to it. Which one it will be is your decision.
2. In the output of `podman images` rename the entry `created` to `createdat` (using the current naming scheme) and add a new entry called `created` that will hold the human-readable format.
3. In the output of `podman ps` rename `Names` to `Name` because it doesn't make sense to be in plural form when it only holds a single value. Is this also necessary for the images (even though there **is** an array) considering the frequency of renaming images?

Thank you for taking a lot at this.

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
We cannot rename `Names` to `Name` for compatibility with Docker. Their version of the field is called that, and we need to maintain the name so Go templates in `--format` continue to work. I'll look at the rest, but I'm a bit hesitant to make changes here; the current situation isn't perfect, certainly, but we risk breaking users by renaming or removing fields.

**Comment by rhatdan** [comment]
@mheon did you ever work on this?

**Comment by mheon** [comment]
Nope, haven't found time

**Comment by rhatdan** [comment]
Ok marking this as a good first time issue, and maybe @sujil02 or someone else will have a chance to dive into it.  @kunalkushwaha WDYT?

**Comment by kunalkushwaha** [comment]
I can pick it up if no one is working on this.

**Comment by rhatdan** [comment]
Go for it.

**Comment by kunalkushwaha** [comment]
I looked into this issue and found  `JSON` output has no compatibility issue with `docker` commands, as it's additional in `podman`. Docker only supports `--format` in Go templates.
- So making changes in `JSON` format is easy, if we agree to make changes.

> 1. Names of entries of containers start with upper case letters (eg. Image, Command,..) and special words are all in capitals (eg, ID, PID,..). In the case of images, the names of entries are always lower cases.
 
This can be easily fixed and changes are required in [cli code](https://github.com/containers/libpod/blob/master/cmd/podman/images.go#L36) only.

> 2. The output of podman ps has four entries with time: Create, CreatedAt, ExitedAt and StartedAt. The entry Create is formatted in a human-readable format. The output of podman images only holds one time entry: created that is machine-readable.

This is possible since the output is local in the JSON output.

> 3. I'm not really sure about this one. The output of podman ps has an entry called Names that holds a string. The output of podman images has an entry called names that holds an array of strings.

This is not preferable, as @mheon mentioned above, this will create compatibility issue with docker  https://github.com/containers/libpod/issues/5001#issuecomment-587176892
