### ISSUE TITLE
errors when using podman pull with [storage] driver = "overlay"

### ISSUE THREAD

**Issue by delight** [containers/libpod#5010]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
`podman pull` runs into errors when using overlay as storage driver.

**Steps to reproduce the issue:**

1.
Adjust $HOME/.config/containers/storage.conf from driver = "vfs" to

[storage]
  driver = "overlay"

2.
podman pull docker.io/gogs/gogs

3.

**Describe the results you received:**
Trying to pull docker.io/gogs/gogs...
Getting image source signatures
Copying blob 4167d3e14976 done  
Copying blob 5587acc07e36 done  
Copying blob e49ccb7bd542 done  
Copying blob 601ee68e0a52 done  
Copying blob bf08e966ad0d done  
Copying blob 704e829dff56 done  
Copying blob 64ac88304b1b done  
Copying blob 49e36b9adb56 done  
Copying blob 4d7b09493930 done  
Copying blob 404754f221e6 done  
Copying config 58387219ce done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): operation not permitted
Error: error pulling image "docker.io/gogs/gogs": unable to pull docker.io/gogs/gogs: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:404754f221e640bc62a9463f2902eafbac07fc7f67b472be9aab32d0c4162810": Error processing tar file(exit status 1): operation not permitted

**Describe the results you expected:**
Trying to pull docker.io/gogs/gogs...
Getting image source signatures
Copying blob 601ee68e0a52 done  
Copying blob 704e829dff56 done  
Copying blob 5587acc07e36 done  
Copying blob e49ccb7bd542 done  
Copying blob 4167d3e14976 done  
Copying blob bf08e966ad0d done  
Copying blob 64ac88304b1b done  
Copying blob 49e36b9adb56 done  
Copying blob 4d7b09493930 done  
Copying blob 404754f221e6 done  
Copying config 58387219ce done  
Writing manifest to image destination
Storing signatures
58387219ce8f26d0bedb365f378d781769f99c8d025b235086ba4c92532164e0

**Additional information you deem important (e.g. issue happens only occasionally):**

With 

[storage]
  driver = "vfs"

podman pull works, but uses **557 MB** for the 107 MB image.

That was the reason in the first place that I tried changing the storage driver. Docker is using overlay2, which uses just marginal more space then the image is in size.

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: neon
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 13213732864
  MemTotal: 16670547968
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 376664064
  SwapTotal: 376664064
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: skopelos
  kernel: 5.3.0-28-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 1h 1m 59.54s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/koko/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /home/koko/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/koko/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman 
Listing... Done
podman/unknown,now 1.7.0~5 amd64 [installed]

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical xbuntu (KDE neon)
Release:        18.04
Codename:       bionic

**Comment by delight** [comment]
Ok I found this entry about fuse-overlayfs in https://github.com/containers/libpod/blob/master/troubleshooting.md

So it seems that it is a permission (root-less) problem. Unfortunately there is no fuse-overlayfs for Xbuntu < 19.04 :-/

**Comment by rhatdan** [comment]
Not really an upstream problem, and not sure if someone is going to package fuse-overlayfs for older versions.

**Comment by delight** [comment]
@rhatdan Everything I found googling was related to rootless **build** on top of overlayfs but not on related to run or pull

The informations seem a little ambiguous to me right now ... should podman pull and podman run work on overlayfs without fuse ?

**Comment by rhatdan** [comment]
No, the issue is the a rootless user is NOT allowed to mount an overlayfs (Yet).  When you are pulling an image or doing a podman run, the storage layer needs to be mounted.  Since you are running rootless all `mount -t overlay` is blocked.  This is why we use fuse-overlay, since `mount -t fuse` is allowed in a usernamespace for non privileged users.

**Comment by delight** [comment]
Got it. So we should probably close this issue! Sorry for opening it in the first place.

@rhatdan Would the storage drivers for btrfs have similar "problems" in rootless?

**Comment by rhatdan** [comment]
I believe btrfs works in rootless mode, but I never tried it.

**Comment by delight** [comment]
@rhatdan btrfs driver seems not to be supported at all in podman 1.7.0~5 - neither for root nor for rootless

I gave it a spin on a system with btrfs

`podman --storage-driver btrfs info`

```
ERRO[0000] Failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage 
Error: could not get runtime: failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage: driver not supported
```

Same thing happens if 

```
[storage]
  driver = "vfs"
```

is changed to

```
[storage]
  driver = "btrfs"
```

Should I create a issue/ticket for this?

Btw. Docker detects btrfs automagically, uses that btrfs storage driver and works as expected.

**Comment by delight** [comment]
permission problems and missing fuse-libraries ain't the problem of libpod IMO

issue can be closed
