### ISSUE TITLE
Can't stop toolbox containers

### ISSUE THREAD

**Issue by HarryMichal** [containers/libpod#5014]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've been using Fedora Rawhide before version 1.7.0 was released and I've been able to stop my toolbox containers with `podman stop [container]`. But a few days ago (27/01) I rebased (Fedora Silverblue) back to release 31. Since then I've not been able to stop my toolbox containers with `podman stop`. This is probably related to #3821 because the error message is the same.

**Steps to reproduce the issue:**

1. `toolbox create -c mycontainer`

2. `toolbox enter -c mycontainer`

3. exit the container with `exit` or `Ctrl+D`

4. `podman stop mycontainer`

**Describe the results you received:**

`Error: given PIDs did not die within timeout`

**Describe the results you expected:**

Name of the removed container + 0 return value

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.9-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 7d46f3e7711aa3578488284ae2f98b447658f086'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 501272576
  MemTotal: 16658223104
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8231841792
  SwapTotal: 8413769728
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: harry-work
  kernel: 5.4.13-201.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 24h 9m 40.76s (Approximately 1.00 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/omichal/.config/containers/storage.conf
  ContainerStore:
    number: 37
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/omichal/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 18
  RunRoot: /run/user/1000
  VolumePath: /var/home/omichal/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using Fedora Silverblue 31

**Comment by vrothberg** [comment]
@HarryMichal, thanks for opening the issue. I can't reproduce the issue on a fresh Siverblue 31. Do you hit it every time?

**Comment by HarryMichal** [comment]
On my personal laptop: 'yes'. In a VM with fresh Fedora Workstation 31: 'no'. I may try to reset podman with `podman system reset` and see if it solves anything.

**Comment by vrothberg** [comment]
@HarryMichal, did a reset solve the issue for you?

**Comment by HarryMichal** [comment]
Yes, it did. But I hade to run it and reboot several times. Here's the output after running the command for the first time: 
![Screenshot from 2020-02-03 11-16-52](https://user-images.githubusercontent.com/17991284/73646185-2bea8b80-4679-11ea-9eb5-eff68db5fbf2.png)

But nevertheless, it works now, so I'm closing this.
