### ISSUE TITLE
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/bin/conmon]): invalid argument

### ISSUE THREAD

**Issue by Dmitriy-Chilikin** [containers/libpod#5023]
I installed Podman and started running integration tests. Got this error :
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/bin/conmon]): invalid argument
Failure [0.042 seconds]
[BeforeSuite] BeforeSuite 
/go/src/github.com/containers/libpod/test/e2e/common_test.go:98

  Expected
      <int>: 125
  to equal
      <int>: 0
What do I need to do to fix it?

**Comment by vrothberg** [comment]
Please provide the requested information in the issue template. The most important data is the output of `podman info --debug`.

**Comment by Dmitriy-Chilikin** [comment]
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument

**Comment by vrothberg** [comment]
Which distribution and which version of Podman?

**Comment by Dmitriy-Chilikin** [comment]
podman version 1.7.1-dev
I deleted and reinstalled Podman. The problem is gone.
