### ISSUE TITLE
podman commit gives bad error when container is not running

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#5029]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.  podman pull alpine

2.  podman run alpine /bin/sh

3. podman commit {ctrId}

**Describe the results you received:**
```
# podman commit affectionate_haibt tommer
Error: container not known
```
If I use the same command on a container that's running, it works.

**Describe the results you expected:**
Preferably the commit to happen.  Or if we're not allowing containers that are not running  to be commited, then a better error message and an update in the man page to note that.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.7.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.7
Git Commit:         eb283657036f5dc69c926432252768d158989100-dirty
Built:              Thu Jan 30 10:58:51 2020
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

# podman info --debug
debug:
  compiler: gc
  git commit: eb283657036f5dc69c926432252768d158989100-dirty
  go version: go1.12.7
  podman version: 1.7.1-dev
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.3-dev, commit: 002da2522941fde456f5213c8a5a96c9836c2592'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 3546157056
  MemTotal: 6247559168
  OCIRuntime:
    name: runc
    package: containerd.io-1.2.6-3.3.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 2683289600
  SwapTotal: 2684350464
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.2.9-200.fc30.x86_64
  os: linux
  rootless: false
  uptime: 121h 5m 48.48s (Approximately 5.04 days)
registries:
  bad.docker.io:
    Blocked: false
    Insecure: true
    Location: bad.docker.io
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: bad.docker.io
  block.docker.io:
    Blocked: true
    Insecure: false
    Location: block.docker.io
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: block.docker.io
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.6.1-2.gitc548530.fc30.x86_64
      Version: |-
        fuse-overlayfs: version 0.6.1
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM running Fedora 31.

**Comment by baude** [comment]
@TomSweeneyRedHat i cannot reproduce this.

**Comment by TomSweeneyRedHat** [comment]
Sorry about the firedrill baude, I must have had something messed up in my sandbox that created the issue.  I just refreshed it to master, rebuilt and I too can't duplicate.  Closing and apologizing.
