### ISSUE TITLE
storage-driver btrfs not supported

### ISSUE THREAD

**Issue by delight** [containers/libpod#5043]
**BUG REPORT**

/kind bug

Podman is refusing to work with btrfs as storage-driver

**Steps to reproduce the issue:**

Easy way:
Specify desired storage driver as parameter
`podman --storage-driver btrfs info`

"Right" way:
1. adjust storage.conf

Change
```
[storage]
  driver = "vfs"
```
to
```
[storage]
  driver = "btrfs"
```

2. Empty $HOME/.local/share/containers/storage/

Make sure $HOME/.local/share/containers/storage/
is emtpy or emtpy it

3. run podman info or any other podman comand
`podman info`

**Describe the results you received:**
ERRO[0000] Failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage 
Error: could not get runtime: failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage: driver not supported

**Describe the results you expected:**
Podman info page, something similiar to the **vfs** version:

host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: neon
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 3027853312
  MemTotal: 16670543872
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 2046816256
  SwapTotal: 2046816256
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: skopelos
  kernel: 5.3.0-28-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 9h 4m 0.5s (Approximately 0.38 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/koko/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/koko/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/koko/.local/share/containers/storage/volumes

**Additional information you deem important (e.g. issue happens only occasionally):**
just in comparison: Docker detects btrfs automagically, uses that btrfs storage driver and works as expected.

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
If (btrfs is set in storage.conf):
ERRO[0004] Failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage 
Error: could not get runtime: failed to GetDriver graph btrfs /home/koko/.local/share/containers/storage: driver not supported

Podman info --debug (with vfs):
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: neon
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 3036528640
  MemTotal: 16670543872
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 2046816256
  SwapTotal: 2046816256
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: skopelos
  kernel: 5.3.0-28-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 9h 10m 40.41s (Approximately 0.38 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/koko/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/koko/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/koko/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 1.7.0~5 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical xbuntu (KDE neon)
Release: 18.04
Codename: bionic

**Comment by rhatdan** [comment]
This is an issue with the way the package was built, the BUILD TAGS are disabling btrfs support.

**Comment by rhatdan** [comment]
@lsm5 @jnovy PTAL

**Comment by rhatdan** [comment]
Please open a bugzilla with the distro that you got the package from.

**Comment by delight** [comment]
@rhatdan the package is from the open side build server as described in the installation docs. The problem remains with podman 1.8.0-2 .. distro is Ubuntu lts 18.04 as described in the initial text

**Comment by mheon** [comment]
Reopening, we do handle OBS issues here for lack of a better venue

**Comment by lsm5** [comment]
@delight should be fixed by `1.8.0~5`, will be available in an hour or less. Please re-open if it doesn't.

**Comment by delight** [comment]
@lsm5 just tryed 1.8.0~5 and 1.8.0~6 

Both are able to start the btrfs storage drive.
Downloading the image and starting a container works. Podman creates subvolumes in btrfs as expected. 
Removing thou won't work correctly.

Simplest way of reproducing the error is something like 
`podman pull ubuntu
`
and then trying to delete it again
`podman rmi ubuntu`

result in
Error: remove /home/koko/.local/share/containers/storage/btrfs/subvolumes/27b97a061bd85ff57a9e5a6d40205f5c600d09319d23baaf69a4f0bd468c0ae7: operation not permitted

This behavior results ultimately in a bunch of unexpected errors e.g.:
1) When a container is created and deleted again
ERRO[0024] Error removing container a8819fc16eef827bca67f8642dda849f78000c07d1b4fe893c8f1926afd53c3f: error removing container a8819fc16eef827bca67f8642dda849f78000c07d1b4fe893c8f1926afd53c3f root filesystem: remove /home/koko/.local/share/containers/storage/btrfs/subvolumes/53f23057d3f31b4992ff75faa784cbb3f8d3ef275b61eab04ecccc216bb0df94: operation not permitted 

and even though `podman ps -a` is an empty list `podman rmi ubuntu` will result in an error like:
A container associated with containers/storage, i.e. via Buildah, CRI-O, etc., may be associated with this image: ccc6e87d482b
Error: image is in use by a container

2) When trying to remove a just downloaded image the initially described permission error occurs ... now the image is not in the list anymore `podman image ls` but when trying to download the image again it acts like the image layers are already there ... resulting in wrong image.

Only workaround I found is to remove the btrfs subvolumes after removing something with podman ... though this is not really a workaround because you won't be able to tell easily which subvolume hash is associated with a certain image or container.

tltr;
In general the btrfs storage driver is loading but it is unusable because of the problem with *not* removing the created subvolumes

**Comment by delight** [comment]
I guess the problem is already known see #3963 

something around https://github.com/containers/storage/blob/1c8d809f3db40ab852112332457e2ea7a09ba859/drivers/btrfs/btrfs.go#L635 ?

**Comment by delight** [comment]
OK, using the mount option "user_subvol_rm_alowed" is a pragmatic workaround IMO .. a little documentation on the topic would be desirable. I'll check for the right place but would appreciate if you could pin-point me to a good place.

Closing this ticket.

**Comment by rhatdan** [comment]
I would guess in storage.conf man page? in github.com:containers/storage.
