### ISSUE TITLE
I can't understand why to use a lot of pointer in iopodman.Create.

### ISSUE THREAD

**Issue by shaneing** [containers/libpod#5047]
The `iopodman.Create` as follow:

```go
type Create struct {
    // ...
    Entrypoint             *string   `json:"entrypoint,omitempty"`
    Env                    *[]string `json:"env,omitempty"`
    // ...
}
```
IMHO, the struct is hard to use.

**Comment by mheon** [comment]
It makes a distinction between the empty string, "", and completely unset.
A nil means the setting should be left as default, a "" overrides it with
the empty string. The two have very different meanings in some places.

**Comment by shaneing** [comment]
> It makes a distinction between the empty string, "", and completely unset. A nil means the setting should be left as default, a "" overrides it with the empty string. The two have very different meanings in some places.

It seems less needed. For example:

```go
func stringArrayFromVarlink(v []string, flagName string, defaultValue []string) CRStringArray {
	cr := CRStringArray{}
	if v == nil {
		cr.Val = []string{}
		if defaultValue != nil {
			cr.Val = defaultValue
		}
		cr.Changed = false
	} else {
		cr.Val = v
		cr.Changed = true
	}
	cr.Flag = flagName
	return cr
}

func stringFromVarlink(v string, flagName string, defaultValue string) CRString {
	cr := CRString{}
	if v == "" {
		if defaultValue != "" {
			cr.Val = defaultValue
		}
		cr.Changed = false
	} else {
		cr.Val = v
		cr.Changed = true
	}
	cr.Flag = flagName
	return cr
}
```

If really needed, the following struct is looked good to me:

```go
 type NullString struct { 
 	String  string 
 	Valid bool 
 } 
```
🤔

**Comment by shaneing** [comment]
I have another problem. Why not use `iopodman.ContainerMount` instead of `iopodman.Create.Mount`.

**Comment by mheon** [comment]
The Varlink API is in the process of being deprecated, so not much we can
do about this right now. Part of the interface for the new HTTP API is
fixed for compatibility, but design of the libpod endpoints is still early
enough that comments would be welcome

**Comment by shaneing** [comment]
@mheon ok, thanks. I will follow the HTTP API.
