### ISSUE TITLE
Reboot of your system might kill your container image files

### ISSUE THREAD

**Issue by groovyman** [containers/libpod#5057]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I am using a clean F31 distribution. On my server i created a technical user (id > 1000, not the first) , that is dedicated to run a podman-container, rootless of course. I got my server into run state and before a shutdown i make sure, that the container is stopped by podman stop <container id>.

After reboot i want to restart the podman-container, but the container-file is not there. The when i try to remove that image, podman tells me, that there is no file.

```
[tlxoffice@chasmash docker_kivitendo]$ podman ps -a
CONTAINER ID  IMAGE                       COMMAND               CREATED         STATUS                     PORTS                        NAMES
a6edeae3c880  localhost/kivi_prod:latest  /lib/systemd/syst...  42 minutes ago  Exited (0) 30 minutes ago  192.168.178.39:9190->80/tcp  jovial_stonebraker
[tlxoffice@chasmash docker_kivitendo]$ podman start a6edeae3c880
Error: unable to start container "a6edeae3c880": cannot chown run directory /run/user/1001/overlay-containers/a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39/userdata: chown /run/user/1001/overlay-containers/a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39/userdata: no such file or directory
[tlxoffice@chasmash docker_kivitendo]$ podman rm a6edeae3c880
Error: error freeing lock for container a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39: no such file or directory
[tlxoffice@chasmash docker_kivitendo]$ podman rm a6edeae3c880
Error: no container with name or ID a6edeae3c880 found: no such container
```
gaaahhh!

**Steps to reproduce the issue:**

1. get a user with a uid > 1000. It looks like, that the very first user does not have this problem

2. stop your container

3. reboot und try to restart the container again

**Describe the results you received:**
```
[tlxoffice@chasmash docker_kivitendo]$ podman start a6edeae3c880
Error: unable to start container "a6edeae3c880": cannot chown run directory /run/user/1001/overlay-containers/a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39/userdata: chown /run/user/1001/overlay-containers/a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39/userdata: no such file or directory
```

**Describe the results you expected:**
a proper start!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[tlxoffice@chasmash docker_kivitendo]$ podman version
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
[tlxoffice@chasmash docker_kivitendo]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 15688372224
  MemTotal: 16427331584
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8300523520
  SwapTotal: 8300523520
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: chasmash
  kernel: 5.4.15-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 44m 9.47s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/tlxoffice/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 77
  RunRoot: /run/user/1001
  VolumePath: /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[tlxoffice@chasmash docker_kivitendo]$ rpm -q -f /usr/bin/podman
podman-1.7.0-2.fc31.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
a proper Fedora F31

**Comment by mheon** [comment]
No such file or directory on rootless storage directory? We should be recreating that on detecting a reboot. RunRoot is set appropriately to a tmpfs, so it looks as though we ought to be wiping the alive file after reboot, which is confusing. 

`Error: error freeing lock for container a6edeae3c8807b9d39b54733566c2533dd53f8efbcd92365b98913896261bb39: no such file or directory`
That is not particularly concerning - looks like another consequence of the refresh code not running after a reboot. The question becomes whether the code is running, but erroring out, or if it is not running at all. A debug trace (add `--log-level=debug` to a Podman command) of the first Podman process run after a reboot would be appreciated.

**Comment by groovyman** [comment]
Sorry, 
i am a bit confused, because i would never put a container image on a tempoary filesystem.
The curious thing is, that this does not happend on a workstation F31 Installation with a user having a uid 1000. 
I want to point our,that is stopped the container before i initiate a reboot. So there should not be any volatile data on a tmpfs directory at all, am i right.-

- How can i support to solve it ?
- How can i make sure, that the stopped state of the container will not get lost ?

**Comment by mheon** [comment]
What is happening is that Podman is not detecting and appropriately handling the reboot; as such locks are not reallocated, temporary directories are not recreated, etc. We detect reboots via a file created on a tmpfs directory, somewhere in `RunRoot` (as seen in `podman info`), which appears to be a tmpfs filesystem and should be recreated after reboot. If you can provide a `--log-level=debug` trace of the first Podman command run after a reboot, it would help debug what is going on (whether we are not detecting the reboot at all, or encountering an error when we try to handle it).

**Comment by groovyman** [comment]
Salut Matthew,
first of all, thank you for taking some time to help me!
ok, here is what you have asked me for:
`[tlxoffice@chasmash docker_kivitendo]$ podman start 2f803416eaf0 --log-level=debug
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding run root "/run/user/1001/containers" with "/run/user/1001" from database 
DEBU[0000] Overriding tmp dir "/run/user/1001/libpod/tmp" with "/var/tmp/run-1001/libpod/tmp" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001                
DEBU[0000] Using static dir /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/tmp/run-1001/libpod/tmp   
DEBU[0000] Using volume path /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] Initialized SHM lock manager at path /libpod_rootless_lock_1001 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding run root "/run/user/1001/containers" with "/run/user/1001" from database 
DEBU[0000] Overriding tmp dir "/run/user/1001/libpod/tmp" with "/var/tmp/run-1001/libpod/tmp" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001                
DEBU[0000] Using static dir /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/tmp/run-1001/libpod/tmp   
DEBU[0000] Using volume path /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] No store required. Not opening container store. 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
INFO[0000] running as rootless                          
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding run root "/run/user/1001/containers" with "/run/user/1001" from database 
DEBU[0000] Overriding tmp dir "/run/user/1001/libpod/tmp" with "/var/tmp/run-1001/libpod/tmp" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001                
DEBU[0000] Using static dir /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/tmp/run-1001/libpod/tmp   
DEBU[0000] Using volume path /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] Made network namespace at /run/user/1001/netns/cni-db6a4b73-596b-6ec1-26db-fcead227882a for container 2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680 
DEBU[0000] slirp4netns command: /usr/bin/slirp4netns --api-socket /var/tmp/run-1001/libpod/tmp/2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680.net --disable-host-loopback --mtu 65520 -c -e 3 -r 4 --netns-type=path /run/user/1001/netns/cni-db6a4b73-596b-6ec1-26db-fcead227882a tap0 
DEBU[0000] overlay: mount_data=lowerdir=/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/4ZY7RHOX2TAAYZ6IO35HRQMUX4:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/EMX4EADEPNYIPC44S7BRU3ONO3:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/ZRL57DDOZYQAANFACBKABCS47S:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/XLAZHGJUWAJVWIF7CLZQ7H6ZQO:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/7S7KYZ3PUWAX5MTRRTPX2F5C3W:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/Y2F3XBWRTPYKUZBZD7O2LVRFMB:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/DT7APDD2TJCFPPKKDNF4WHE2M4:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/6DIBLEDQXK5MB6MQBQQ2INTHM3:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/N7VHH4AZ6GAMA2CSJZ7FKCYZUL:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/2UJC4S3Z6RO65JSU3K6LDXBZRW:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/EJYHYP6J72FVY3HKTTAYNSNAGQ:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/4VG766MZVJRNTTGVM5RUMPRUN5:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/LKARK4CLIV2VDBNFZT54L3FRJD:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/5ZFVM2R6MELOF7LYFAU64XUCBT:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/THOYQ5NTIZL2QCOI2524VCJ3WJ:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/VFF2UYOY225UMW3APVC35ZH6NN:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/H53OUC4CG45ZVMTL3T5A3CRYBF:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/ER4ZK6KNUCH275WMQGBZLMSAL2:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/F37KEJYE3AJLZE3QFK3CSD6LXI:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/2HWJ5PG6YDLO2SEVQEJOXSDS65:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/SXIUXRZRMN6RTBQ2YMZVWMSAJ2:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/BRMGEU4F65MSFTMOMW2AMSH7P6:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/O4ZCAP5RWZ4RZTBZAEOJEPUJHL:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/ZENWBLPY6MG7EM2XUWCTJWZWU4:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/YBZ7V5F6HSU6MT55PHUSBWLRPX:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/K6RRCAOLMYT3BFGDWGBWLNMHZP:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/AWBUAAVMVZUBVEQUHR3QMB4ZJM:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/JBVCEG5WZPRJPCN36FPBA7S5UX:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/POPIFKHISJMADXP726HNTDXYVM:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/6RS6ZMJY7FABMILQSONMCROEMK:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/3MDNMFCOBZM6PJ2QZEWL6C4QA4:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/NVPUFQI37N6NMT3IAQW3AL6O6K:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/SJIAYEZTDFEDLSDWZMQSXOJKV2:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/WUOGADXPXGQI5QV2VIK2KCEALI:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/OVUKVVJBWY5MGVEYAERXHSRSWN:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/JLX2HQUJVCD6HAPDXFAWA64AGF:/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/l/HBRR5H3IXUNKDZ27L3H532MPGP,upperdir=/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/6c24af328b9a145e647a6867097b39d485ac81a81184449d1c6bd3ea664376f6/diff,workdir=/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/6c24af328b9a145e647a6867097b39d485ac81a81184449d1c6bd3ea664376f6/work,context="system_u:object_r:container_file_t:s0:c581,c641" 
DEBU[0000] mounted container "2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680" at "/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/6c24af328b9a145e647a6867097b39d485ac81a81184449d1c6bd3ea664376f6/merged" 
DEBU[0000] Created root filesystem for container 2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680 at /mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/overlay/6c24af328b9a145e647a6867097b39d485ac81a81184449d1c6bd3ea664376f6/merged 
DEBU[0001] Cleaning up container 2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680 
DEBU[0001] Tearing down network namespace at /run/user/1001/netns/cni-db6a4b73-596b-6ec1-26db-fcead227882a for container 2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680 
DEBU[0001] unmounted container "2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680" 
ERRO[0001] unable to start container "2f803416eaf0": cannot chown run directory /run/user/1001/overlay-containers/2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680/userdata: chown /run/user/1001/overlay-containers/2f803416eaf0631157c571c41ae57aaf0a4b7bebf9b005f8feeacf9b10a96680/userdata: no such file or directory 

`

**Comment by mheon** [comment]
`DEBU[0000] Using tmp dir /var/tmp/run-1001/libpod/tmp   `

Is this directory on a tmpfs?

If not, that is why we're not detecting reboot. You could try deleting the libpod database at `/mnt/raidSpace/Homes/tlxoffice/.local/share/containers/storage/libpod/bolt_state.db` and your containers.conf (usually lives in `~/.config/containers/libpod.conf`) and see if tmp dir is moved into `/run/user/1001` where it should be.

**Comment by groovyman** [comment]
Salut Matthew,

the directory `/var/tmp/run-1001/libpod/tmp` was not a tmpfs. So i removed the user and created a new technical user. After a reboot, the very first podman call gave me this:

```
 - - - -
INFO[0000] running as rootless                          
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /mnt/raidSpace/Homes/techlxoffice/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /mnt/raidSpace/Homes/techlxoffice/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1001/containers     
DEBU[0000] Using static dir /mnt/raidSpace/Homes/techlxoffice/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1001/libpod/tmp      
DEBU[0000] Using volume path /mnt/raidSpace/Homes/techlxoffice/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] No store required. Not opening container store. 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
- - - -
```
So i figured out, where he goes:
```
[techlxoffice@chasmash docker_kivitendo]$ df -k /run/user/1001/libpod/tmp
Dateisystem    1K-Blöcke Benutzt Verfügbar Verw% Eingehängt auf
tmpfs            1604232       4   1604228    1% /run/user/1001
```
looks better. So let's start the stopped container:

```
[techlxoffice@chasmash docker_kivitendo]$ podman ps -a
CONTAINER ID  IMAGE                       COMMAND               CREATED         STATUS                     PORTS                        NAMES
29dc6c4e0d90  localhost/kivi_prod:latest  /lib/systemd/syst...  39 minutes ago  Exited (0) 12 minutes ago  192.168.178.39:9190->80/tcp  boring_zhukovsky
[techlxoffice@chasmash docker_kivitendo]$ podman start 29dc6c4e0d90
29dc6c4e0d9038ae7298b8faef2002d76476032c5aeb1002fd838adb3f702140
```
Isn't this fantastic!

Thanks Matthew!
