### ISSUE TITLE
bind mounts not working without --privileged flag

### ISSUE THREAD

**Issue by mnahkies** [containers/libpod#5059]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using podman on Fedora 31 as a replacement for docker, I've had issues getting bind mounts to continue working correctly.

Unless I pass the `--privileged` flag, I seem to also get a permission denied error when trying to access any of the files mounted inside the container.

All files are owned by the user that is running the container, and I've tried matching the user/group ids of the user inside the container to the outer host as well.

**Steps to reproduce the issue:**

1. Clone https://github.com/mnahkies/podman-bind-mount-bug

2. Run `./outter-script.sh`

3. Observe that the `inner-script.sh` that was run within the container was not able to access the file that was mounted into the container.

**Describe the results you received:**
`cat: can't open '/opt/bug/data/my-data.txt': Permission denied`

**Describe the results you expected:**
`if you see this, then it worked!`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
podman version 1.7.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1521664000
  MemTotal: 16627400704
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8401186816
  SwapTotal: 8401186816
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: XXXX
  kernel: 5.4.13-201.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 2h 53m 5.59s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/mike/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/mike/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 8
  RunRoot: /run/user/1000/containers
  VolumePath: /home/mike/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine, running a fully updated Fedora 31 installation (which was a fresh install rather than upgraded from previous release)

**Comment by mheon** [comment]
Are y ou running as root, or rootless

**Comment by mnahkies** [comment]
Running as my own user, which has the default uid/gid of 1000:1000

I've tried passing `-u 1000:1000` to the run command as well to no avail.

**Comment by mheon** [comment]
SELinux pops up as the most obvious cause to me. Does appending `:z` to the volume mount to relabel it (or running the container with `--security-opt label=disable`) resolve the issue?

**Comment by rhatdan** [comment]
Please show the command that does not work, and what errors you are seeing.
Most likely SELinux or User Namespace related.

**Comment by mnahkies** [comment]
The linked repository contains a minimal reproduction of the issue I was experiencing.

Appending `:z` does indeed work, thanks. Unfortunately my knowledge of SELinux is pretty limited. Why do the files need to be re-labelled? 

I see that on the docker documentation there is a warning that this could have unintended consequences due to the relabelling, and I notice that the relabelling removes the `unconfined_u` / `user_home_t` label and adds `system_u` / `container_file_t`
(ref: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label)

Why did this work without relabelling using docker? Was it due to docker using root permissions?

**Comment by mnahkies** [comment]
Also tested using the `--security-opt label=disable` parameter, and can confirm that also worked (and did not modify the existing labels)

I'll close this, but if you don't mind explaining the reason why this becomes necessary when migrating to podman from docker I'd appreciate it - this has been my only real pain point so far and I'd like to better understand it

**Comment by mheon** [comment]
This should be identical between Docker and Podman - you may have been running Docker without SELinux support?

**Comment by mnahkies** [comment]
Definitely possible, I've been using fedora with docker since fedora 28 or so and don't believe I made any customisations to disable selinux, but I can spin up a VM and test that theory

**Comment by rhatdan** [comment]
Depending on the version of docker, native or upstream, it might not have had the --selinux-enabled flag passed into the daemon.  Without this flag SELinux separation for containers would be disabled.
