### ISSUE TITLE
f31 rootless: podman pod rm: error updating pod: .../pids.max: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5072]
```console
$ podman pod create --name=foo
fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e
$ podman pod rm foo
Error: error updating pod fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e conmon group: open /sys/fs/cgroup/libpod_parent/fae80ab038ebb1cd8a3e32d8e6e098b6795f260e36652ba7b5aa34cbd1d6d12e/conmon/pids.max: no such file or directory
$ echo $?
125
```
podman-1.8.0-0.1.fc31.x86_64
crun-0.11-1.fc31.x86_64
conmon-2.0.10-2.fc31.x86_64

**Comment by mheon** [comment]
Related: https://github.com/containers/libpod/issues/5042

**Comment by edsantiago** [comment]
Issue still present in `crun-0.12-1.fc31.x86_64`

**Comment by baude** [comment]
@mheon is this a libpod problem or a runtime problem?

**Comment by mheon** [comment]
No clue - probably us, since we make pod cgroups, but I'm not 100%. Have not managed to reproduce, but I haven't tried the exact environment either here or #5042

**Comment by giuseppe** [comment]
we try to lower the pids limit to 1 when we remove a pod, but it is just an error we print to stdout, and it doesn't block the `podman rm` execution.

It happens only when there is no access to the cgroup (such as rootless with cgroupfs), so I think it is fine to leave it.

A simple reproducer is: `podman --cgroup-manager cgroupfs pod create --name=foo && podman --cgroup-manager cgroupfs pod  rm foo`

**Comment by rhatdan** [comment]
@edsantiago are you fine with this?

**Comment by edsantiago** [comment]
Not really. It is an error message, clearly labeled `Error`, and exits nonzero. I don't think end users will appreciate this.

**Comment by mheon** [comment]
We probably should not be trying to make cgroups in the first place on rootless with cgroupfs in v2 - I'm amazed we aren't getting errors trying to create the cgroups in the first place

**Comment by rhatdan** [comment]
I think the bug here is that this is attempting to write to cgroups on a non running container.  We should not be doing this.

**Comment by edsantiago** [comment]
Update: problem does not occur with `loginctl enable-linger testuser`

**Comment by giuseppe** [comment]
I think we should not make setting pids.max=1 an error.  It is a best effort protection and a warning should be enough.

**Comment by rhatdan** [comment]
I agree.

**Comment by edsantiago** [comment]
Issue still present in podman-1.8.0-0.2.fc31.x86_64

**Comment by edsantiago** [comment]
I'm OK with it though. This isn't a showstopper.

**Comment by mheon** [comment]
The patch is definitely in the tag, so I'm really confused as to how this is still happening.

**Comment by edsantiago** [comment]
Never mind! Just after I tested, I got a new build notification. The new build works. To make the difference clear:
```diff
               vvv
- podman-1.8.0-0.2.fc31
+ podman-1.8.0-2.fc31
               ^
```
dash-zero-dot-two was the one I initially tested and found not fixed; dash-two works fine. Sorry about the confusion.
