### ISSUE TITLE
Error: could not get runtime: could not find a working conmon binary 

### ISSUE THREAD

**Issue by Dmitriy-Chilikin** [containers/libpod#5076]
I installed podman on Centos 7. I started integration tests and get an error.
[root@localhost libpod]# GOPATH=~/go ginkgo -v test/e2e/.
Failed to compile e2e:

go: github.com/containers/image/v5@v5.1.0 requires
	github.com/docker/go-connections@v0.0.0-20180212134524-7beb39f0b969: invalid version: git fetch --unshallow -f https://github.com/docker/go-connections in /root/go/pkg/mod/cache/vcs/d4d85c75c05a73a49903227d5abc01a97e2af98bb40d3e0568d93c9e52de9e77: exit status 128:
	fatal: git fetch-pack: expected shallow list

Ginkgo ran 1 suite in 46.801339442s
Test Suite Failed
[root@localhost libpod]# podman info --debug
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument
[root@localhost libpod]# podman --version
podman version 1.8.0-dev
How to fix it ?

**Comment by giuseppe** [comment]
how have you installed podman?

You also need to make sure conmon (https://github.com/containers/conmon/) is installed

**Comment by rhatdan** [comment]
I don't see this as an upstream issue.  Hopefully @Dmitriy-Chilikin has it working.  Might want to have conversation on email list at podman.io.  Or join us on IRC on #podman on freenode.
