### ISSUE TITLE
fix pre-commit to be installed with make install.tools

### ISSUE THREAD

**Issue by baude** [containers/libpod#5081]
We need to make using pre-commit easier to use by making it available in make install.tools.  Unfortunately it is made difficult because it isn't a simple binary of package that can be installed.  Please think of a way this could be made smoother for first time setup.

Thanks @ssbarnea 
cc @vrothberg

**Comment by rhatdan** [comment]
Opened a PR for this.

**Comment by Akasurde** [comment]
Can we close this since PR #5248 is merged ? Thanks.
