### ISSUE TITLE
run --workdir=/nonesuch: chdir: No such file or directory: OCI runtime command not found error

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5084]
```console
# podman run --workdir=/nonesuch alpine pwd
Error: chdir: No such file or directory: OCI runtime command not found error
# echo $?
127
(expected: "/nonesuch" and exit 0)
```
This is a change in longstanding behavior. I don't know what the correct behavior should be for this case, but it _is_ a difference from docker and from all versions of podman up to now.

podman-1.8.0-0.1.fc31.x86_64
conmon-2.0.10-2.fc31.x86_64

Curiously, I cannot reproduce with podman @ master on f30.

**Comment by mheon** [comment]
Could this be runc vs crun?

**Comment by mheon** [comment]
Also, expected behavior is that the workdir will be created?

**Comment by edsantiago** [comment]
Oh, good call: it could very well be `crun`. Yes, expected behavior is to create the directory:
```bash
f30# podman run -it --workdir=/none/such alpine sh
/none/such # touch abc
/none/such # ls -l /none/such/abc
-rw-r--r--    1 root     root             0 Feb  4 17:56 /none/such/abc
/none/such #
```

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by rhatdan** [comment]
Yuck, I don't like the default.  Basically this ends up with typos creating directories in the container...

**Comment by giuseppe** [comment]
yes this is a crun vs runc difference.

I can easily change it in crun if we agree on what behaviour makes more sense.

I agree with Dan and I think that `chdir`'ing to a not existing one should raise an error rather than creating it automatically

**Comment by rhatdan** [comment]
I am closing this since, I see this as a Bug in runc/docker, not something we should fix.
