### ISSUE TITLE
how could I build or download latest version for mac?

### ISSUE THREAD

**Issue by medyagh** [containers/libpod#5100]
Hi I am trying to add podman as a driver to minikube, and I because I am running systemd in container I need to try to see if "--cgroup-manager cgroupfs" will fix my problem however the podman available on brew is only 1.6 and it does not have --cgroup-manager

how could I build or download latest version for mac ? is it possible to add mac binary to release page ?

I also tried to build it myself using:
```
make local-cross
```
inside an ubuntu container but I got this error (after following the docs to build from scractch on the site https://podman.io/getting-started/installation.html#Build%20and%20Run%20Dependencies)

```
root@6fd678b13405:~# cd libpod/
root@6fd678b13405:~/libpod# make local-cross
mkdir -p "/go/src/github.com/containers"
ln -sfn "/root/libpod" "/go/src/github.com/containers/libpod"
ln -sfn "/root/libpod/vendor/github.com/varlink" "/go/src/github.com/varlink"
touch .gopathok
TARGET="darwin.amd64"; \
GOOS="${TARGET%%.*}" \
GOARCH="${TARGET##*.}" \
GO111MODULE=on go build -mod=vendor -gcflags 'all=-trimpath=/root/libpod' -asmflags 'all=-trimpath=/root/libpod' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=fa5e95837e793b05987a7e9c40a00c9e67c7a6cb -X github.com/containers/libpod/libpod/define.buildInfo=1580950302 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc -extldflags ""' -tags 'containers_image_openpgp exclude_graphdriver_btrfs exclude_graphdriver_devicemapper exclude_graphdriver_overlay' -o "bin/podman.cross.darwin.amd64" github.com/containers/libpod/cmd/podman


# github.com/containers/libpod/pkg/adapter
pkg/adapter/containers.go:453:12: undefined: StartAttachCtr
pkg/adapter/containers.go:543:12: undefined: StartAttachCtr
pkg/adapter/containers.go:684:10: undefined: StartAttachCtr
pkg/adapter/containers.go:915:2: not enough arguments to return
pkg/adapter/containers.go:915:18: container.Top undefined (type *libpod.Container has no field or method Top)
pkg/adapter/containers.go:983:12: undefined: ExecAttachCtr
make: *** [Makefile:210: bin/podman.cross.darwin.amd64] Error 2
root@6fd678b13405:~/libpod# 
root@6fd678b13405:~/libpod# 
root@6fd678b13405:~/libpod# sysctl kernel.unprivileged_userns_clone=1
```

**Comment by afbjorklund** [comment]
There is a homebrew formula here:
https://github.com/containers/libpod/issues/4511#issuecomment-570891830

You can also find binaries on the homepage:
https://github.com/containers/libpod#readme

**Comment by afbjorklund** [comment]
It seems the latest binary is `v1.6.2-26-gd358840e`

https://storage.googleapis.com/libpod-master-releases/podman-remote-latest-master-darwin-amd64.zip

So you might want to build it yourself, after all.

I think you also avoid GateKeeper, that way ?

**Comment by rhatdan** [comment]
@afbjorklund @medyagh interested in opening a PR to update the MAC version and helping us get through the gatekeeper?

**Comment by afbjorklund** [comment]
I think that you need to add an Apple ID to the CI release process (somehow), unfortunately not an Apple developer anymore myself - but I think there was some links in the original Mac issue ?

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Apparently it "only" quarantines software downloaded using a web browser, email, or similar
So if users download the above with curl or similar command-line tool, they are OK (I've read).

----

Was hoping that an actual Mac user could front as a maintainer for the brew formula, so that we can catch build issues like the `uname` thing - I can only verify it using Linuxbrew (slightly different)

Not sure why the CI builds are not updating ? The Windows build looks even older (1.6.2)
And the Linux binary (for `podman-remote) is not there at all, only this Ubuntu Snap thing.

**Comment by rhatdan** [comment]
@cevich @lsm5 Any idea what is going wrong?

**Comment by lsm5** [comment]
no idea about macos

**Comment by afbjorklund** [comment]
Seems like the build failed: https://cirrus-ci.com/build/6518463703285760

Or at least the darwin part: https://cirrus-ci.com/task/5164168995143680

```
[+0035s] Uploading archive as podman-remote-latest-v1.8.0-darwin-amd64.zip
[+0036s] BucketNotFoundException: 404 gs://libpod-v1.8.0-releases bucket does not exist.
[+0037s] BucketNotFoundException: 404 gs://libpod-v1.8.0-releases bucket does not exist.
[+0037s] .
[+0037s] Release now available for download at:
[+0037s]     https://storage.googleapis.com/libpod-v1.8.0-releases/podman-remote-latest-v1.8.0-darwin-amd64.zip
[+0037s]     https://storage.googleapis.com/libpod-v1.8.0-releases/podman-remote-v1.8.0-v1.8.0-darwin-amd64.zip
```

**Comment by afbjorklund** [comment]
The more recent builds seems to be skipping over the upload phase altogether:

`Skipping release processing: Commit range|CIRRUS_TAG is development tagged.`

@lsm5: snapcraft seems to have "other issues": Snapped podman_0.11.1.1_amd64.snap

There's some other random binaries, not sure if they are used later (fedora-30/ubuntu-18)

**Comment by rhatdan** [comment]
@cevich PTAL

**Comment by cevich** [comment]
Ya, builds on branches are broken due to not having an existing named storage bucket to upload them.  This can be fixed manually (by creating the bucket).  I'm more concerned about builds from the master branch not being uploaded, I'll need to investigate that...

**Comment by cevich** [comment]
Consolidating this into #4511
