### ISSUE TITLE
veth lost carrier during conmon

### ISSUE THREAD

**Issue by zhuguoliang** [containers/libpod#5105]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.  podman run -d --rm --sysctl net.ipv6.conf.all.disable_ipv6=1 --security-opt=seccomp=unconfined -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" 68f439d43b4d  
Note that 68f439d43b4d is a container built locally with Containerfile's content:

> FROM docker.io/elasticsearch:7.5.1
> RUN chmod 755 /usr/share/elasticsearch

2. podman container checkpoint -l --export=/tmp/cp.tar.gz

3. scp /tmp/cp.tar.gz hostb:/tmp

4. podman container restore --log-level debug  -i /tmp/cp.tar.gz

**Describe the results you received:**

> ERRO[0250] failed to restore container 876ad1102f7c744d87d031345a695fc696c8cbbc0115cc266dc3c0c1d0ba1731: container creation timeout: internal libpod error

By checking /var/log/syslog I see following:

> Feb  6 21:09:38 host systemd[1]: Started Session 9 of user root.
Feb  6 21:11:52 host systemd-networkd[267]: veth87647d28: Lost carrier
Feb  6 21:11:52 host kernel: [  317.198494] cni-podman0: port 1(veth87647d28) entered disabled state
Feb  6 21:11:52 host kernel: [  317.204624] device veth87647d28 left promiscuous mode
Feb  6 21:11:52 host kernel: [  317.204627] cni-podman0: port 1(veth87647d28) entered disabled state
Feb  6 21:11:53 host systemd[1]: Starting resolvconf-pull-resolved.service...
Feb  6 21:11:53 host systemd-networkd[267]: cni-podman0: Lost carrier
Feb  6 21:11:53 host networkd-dispatcher[385]: Failed to request link: No such device
Feb  6 21:11:53 host networkd-dispatcher[385]: ERROR:Failed to get interface "veth87647d28" status: Command '['/bin/networkctl', 'status', '--no-pager', '--no-legend', '--', 'veth87647d28']' returned non-zero exit status 1.
Feb  6 21:11:53 host systemd[1]: Started resolvconf-pull-resolved.service.
Feb  6 21:11:53 host podman[1164]: 2020-02-06 21:11:53.092915093 +0800 CST m=+250.094394436 container restore 876ad1102f7c744d87d031345a695fc696c8cbbc0115cc266dc3c0c1d0ba1731 (image=68f439d43b4d54b8369b157df1d67fc63b906a67a55bb446c408bfdacfb67495, name=vigorous_bose)

**Describe the results you expected:**

Successfully restored container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.1-dev
RemoteAPI Version:  1
Go Version:         go1.13
Git Commit:         bf34f7042b3fa42a6b8c0967b5999ceb02018a29-dirty
Built:              Thu Feb  6 19:39:00 2020
OS/Arch:            linux/amd64
```
Note that this is a slightly modified version of podman, aiming at preserving modtime for overlayfs files.

**Output of `podman info --debug`:**

```
(paste your output here)debug:
  compiler: gc
  git commit: bf34f7042b3fa42a6b8c0967b5999ceb02018a29-dirty
  go version: go1.13
  podman version: 1.7.1-dev
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.8, commit: d35534bc4b9bc722bf1ab6f4e828fcaa6bee236a-dirty'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 6447038464
  MemTotal: 8364310528
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 993243136
  SwapTotal: 993243136
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: host
  kernel: 4.15.0-66-generic
  os: linux
  rootless: false
  uptime: 17m 26.5s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Comment by mheon** [comment]
@adrianreber PTAL

**Comment by adrianreber** [comment]
A couple of weeks ago exactly this was working for you, right? #4779 

What has changed since #4779 used to work?

**Comment by zhuguoliang** [comment]
Yes, but somehow it stopped working now, I disabled IPV6 by adding --sysctl net.ipv6.conf.all.disable_ipv6=1 to the run command. I wonder if the printed log in syslog leads directly to the problem of ipv6 support.

**Comment by zhuguoliang** [comment]
There are 2 things stalling the restore.

1. During container restore, podman always prints "IPv6" enabled, which turned out to be in line:
https://github.com/containers/libpod/blob/ee811431d29962c3a801903ca3ca342a2000f65e/libpod/container_internal_linux.go#L1265
IPv6  is turned on by default. 

2. Apparmor is complaining with no profile:

> Feb 10 16:57:43 podman kernel: [  417.580789] audit: type=1400 audit(1581325063.038:11): apparmor="DENIED" operation="change_profile" info="label not found" error=-2 profile="unconfined" name="libpod-default-1.7.1-dev" pid=1386 comm="elasticsearch[7"

I work around the first problem by hand-code to false. I wonder what shall I do with the second problem.

**Comment by zhuguoliang** [comment]
@adrianreber PTAL

**Comment by adrianreber** [comment]
@zhuguoliang Sorry but I do not know enough about AppArmor do be able to help you. Can you switch to Fedora 30 or CentOS 8? SELinux support is available and working for CRIU and Podman there.

**Comment by zhuguoliang** [comment]
OK, I will try it

**Comment by zhuguoliang** [comment]
@adrianreber The problem is gone with centos 8.0, we move on to centos for future development.
 I reopen if any ubuntu user came into this.
