### ISSUE TITLE
podman-play-kube link in readme is broken

### ISSUE THREAD

**Issue by warpfork** [containers/libpod#5106]
/kind bug

**Description**

The README in the ["out of scope" section](https://github.com/containers/libpod#out-of-scope) has a reference to

> (see podman-play-kube)

wherein the link points to `https://github.com/containers/libpod/blob/master/docs/podman-play-kube.1.md`, but no such document exists.

**Comment by rhatdan** [comment]
Link should be changed to:
https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-play-kube.1.md
Interested in opening a PR to change this?

**Comment by vrothberg** [comment]
Opened #5195
