### ISSUE TITLE
suggestion: rename `podman service` to avoid conflict with `docker service`

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#5108]
`podman service`  looks as if it was Podman's implementation of `docker service`.

I suggest renaming `podman service` to `podman daemon`, because it seems actually reimplementation of `docker daemon` that had existed in Docker 1.10 and prior versions.

**Comment by mheon** [comment]
We're trying to avoid running this as a daemon (using systemd socket-activation, and having a timeout on the command so it's not always on), so `podman daemon` is probably a bad idea, but I'm not opposed to renaming to ensure we don't conflict.

**Comment by mheon** [comment]
If so, we should do this quick, before we cut a 1.8.0 final and formalize the name in an official release

**Comment by mheon** [comment]
@baude @rhatdan @vrothberg PTAL

**Comment by AkihiroSuda** [comment]
Or maybe `podman system service`

**Comment by vrothberg** [comment]
`podman listen`?

Thanks for pointing that out, @AkihiroSuda !

**Comment by rhatdan** [comment]
Why would podman service conflict with docker.service?

**Comment by rhatdan** [comment]
Podman is not listening by default at docker.sock, If you install podman-docker, it will create a linkfile between /run/docker.sock and /run/podman.sock.  But podman-docker conflicts with docker-* packages.

**Comment by vrothberg** [comment]
There's a `docker service` command -> https://docs.docker.com/engine/reference/commandline/service/

**Comment by rhatdan** [comment]
So this is their replacement for dockerd?  If it is, then podman service makes sense.  Except for not listening on docker.sock?

**Comment by mheon** [comment]
No, it's a swarm command, AFAIK - it launches a service via swarm

**Comment by rhatdan** [comment]
Well we have said we will not support Docker swarm, does it matter we have the same name?

**Comment by mheon** [comment]
Potential confusion? I'd prefer not to knowingly conflict with Docker commands if we can afford not to

**Comment by rhatdan** [comment]
Fine, except that if we come up with a strange name for this service.
podman restapi
podman server

**Comment by mheon** [comment]
`podman server` sounds good to me

**Comment by mheon** [comment]
`podman system service` also works for me

**Comment by rhatdan** [comment]
Yes I like keeping it under system.
