### ISSUE TITLE
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve

### ISSUE THREAD

**Issue by adrianreber** [containers/libpod#5114]
CRIU is running Podman based checkpoint/restore tests in Travis. Because the Travis kernel is broken for checkpoint/restore on overlayfs we switched to VFS:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1857257

To tell Podman to use VFS I am running `podman --storage-driver vfs info` first before running any other Podman command. This used to be good enough to initialize Podman to use VFS. This still kind of works, but now, every time Podman is started I see following error message:

```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve
```

Everything works as expected but now we get a lot of those error messages in CI.

This is using 6-podman_1.7.0~6_amd64.deb from the kubic stable repository for 18.04. The complete log can be found here:

https://travis-ci.org/checkpoint-restore/criu/jobs/646854308

Right now this seems to be purely cosmetic, but it is new and used to be not visible.

Probably I am using the wrong approach to switch Podman to VFS, but that is how it used to work before.

**Comment by mheon** [comment]
This is the result of storage.conf still having `overlay` set, while the database contains `vfs` from your initial `podman info` command. The database wins, but this could be very confusing for users (your configuration file is being overridden), so we write errors.

**Comment by adrianreber** [comment]
Is the only way around this modifying storage.conf?

**Comment by mheon** [comment]
I think removing it would also work, but that might prevent us from locating the correct base directory for Podman files.

**Comment by vrothberg** [comment]
> ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve

The error message seems to be swapping the database and user-selection as well.

Why are we logging an error for this case? Wouldn't an Info log be sufficient?

**Comment by vrothberg** [comment]
Cc: @giuseppe @rhatdan

**Comment by rhatdan** [comment]
@adrianreber Any update on this issue?

**Comment by adrianreber** [comment]
I do not see the error message any more in the current CRIU CI runs based on Podman 1.8.1~1.

Closing it.

**Comment by JJ** [comment]
Same error in podman 2.2.1:

```
User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve
```

**Comment by rhatdan** [comment]
@JJ Please open new issue or follow the instructions above to cleanup the problem.

Bottom line is you ran podman with vfs mode, and now this is recorded in the database. Only way to switch is to reset your storage or delete the libpod database.

**Comment by PhilipSchmid** [comment]
For all wondering what @rhatdan probably meant with "reset your storage":
```bash
sudo rm -rf ~/.local/share/containers/
```
At least it worked for me on Pop_OS 20.04 with Podman (`3.0.0`) :smile: ...

**Comment by Kiritow** [comment]
If you are using nested podman, this might help: `rm /var/lib/containers/storage/libpod/bolt_state.db`

**Comment by anarcat** [comment]
> For all wondering what @rhatdan probably meant with "reset your storage":
>
>     sudo rm -rf ~/.local/share/containers/


you know, this would be a *great* addition to that error message :p

**Comment by anarcat** [comment]
well i can't figure out how to fork this repo. somehow github tells me it's already forked, but https://github.com/anarcat/podman is a 404. go figure.

maybe this patch would do it, anyways:

```diff
modified   libpod/runtime.go
@@ -1019,7 +1019,7 @@ func (r *Runtime) mergeDBConfig(dbConfig *DBConfig) {
 	if !r.storageSet.GraphDriverNameSet && dbConfig.GraphDriver != "" {
 		if r.storageConfig.GraphDriverName != dbConfig.GraphDriver &&
 			r.storageConfig.GraphDriverName != "" {
-			logrus.Errorf("User-selected graph driver %q overwritten by graph driver %q from database - delete libpod local files to resolve.  May prevent use of images created by other tools",
+			logrus.Errorf("User-selected graph driver %q overwritten by graph driver %q from database - delete libpod local files (.local/share/containers) to resolve.  May prevent use of images created by other tools",
 				r.storageConfig.GraphDriverName, dbConfig.GraphDriver)
 		}
 		r.storageConfig.GraphDriverName = dbConfig.GraphDriver
```

**Comment by yubiuser** [comment]
Fixed with https://github.com/containers/podman/pull/16311

**Comment by pzygielo** [comment]
@anarcat
> well i can't figure out how to fork this repo. somehow github tells me it's already forked, but https://github.com/anarcat/podman is a 404. go figure.

https://github.com/anarcat/libpod

**Comment by anarcat** [comment]
> https://github.com/anarcat/libpod

good catch, thanks! i've deleted the fork to avoid making a fool of myself next time. :)
