### ISSUE TITLE
Please add some examples for libpod

### ISSUE THREAD

**Issue by gh67uyyghj** [containers/libpod#5124]
Thanks for making libpod and podman possible. I spent hours trying to understand how to just make something that is equivalent to ` ContainerCreate()` and `ContainerStart()` in docker go-client without making it (mostly via reading cmd/podman). Please add some documentation about how to pull images and run a container. Maybe I am just stupid but honestly the lack of well documented API will limit the success of the project.

**Comment by TomSweeneyRedHat** [comment]
@gh67uyyghj Glad you were able to work through it all and get stuff working.

We have a number of tutorials on https://podman.io, I don't know if you happened across those or not.  We also have an introductory tutorial in the project at https://github.com/containers/libpod/tree/master/docs/tutorials along with a few others.

If you've suggestions for other documentation that you think would be helpful, especially any of the commands that you finally used, please send them along or better yet, start up a PR and we help us work out the kinks!

Thanks!

**Comment by mheon** [comment]
In API terms:

The Go API for Libpod is still not what I'd call stable. We have ambitions of making it stable, hopefully within the next year, but that's still a ways away.

We are presently in the process of building an HTTP API with both Docker-compatible endpoints (to allow applications that formerly used the Docker socket to continue functioning) and new Libpod-specific endpoints to expose our added functionality like pods. This API is still in its early stages, but it's under heavy development, and we're making great progress; this should soon be our recommended API for interacting with Podman, until we can find the time to properly stabilize Libpod.

**Comment by gh67uyyghj** [comment]
Thank you @TomasTomecek @mheon for the really quick response. I was trying to explore libpod and replace docker go-client with it since I wanted to use the pod feature and interact directly with network namespace with netlink since I guess this is not possible with network namespaces used by Docker.

Anyway it seems I just came too early but the project seems really promising especially for applications that need to run and maintain containers in a more cleaner way than calling Docker daemon.
