### ISSUE TITLE
How to debug process that malfunctions within podman

### ISSUE THREAD

**Issue by grzegorzk** [containers/libpod#5133]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I wanted to run openvpn in podman container and initially I thought it's running without any problem (on host `netstat` was listing port as mapped by podman). However when I looked at `netstat` output from within the container then noticed that nothing is listening to network traffic.

**Steps to reproduce the issue:**

Do below as root (ideally should also work when executed as rootless)

1. `podman run -it --rm archlinux /bin/bash`

2. `pacman -Sy openvpn`

3. Run `openvpn` with valid config and certs

**Describe the results you received:**

Openvpn starts and does not report any error however running `netstat -ntlp` from within the container yields no result.

**Describe the results you expected:**

I'd expect openvpn port listed within `netstat` output

**Additional information you deem important (e.g. issue happens only occasionally):**

I'd like to debug this further but I reached my limits. Process I run executes without errors though it does not "listen" to the network traffic. Are there any tricks I can use to see where is the process actually failing? I can drop here zip package with example certs if requested.

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
Built:              Sat Jan 11 13:49:39 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
compiler: gc
git commit: b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
go version: go1.13.5
podman version: 1.7.0
host:
BuildahVersion: 1.12.0
CgroupVersion: v1
Conmon:
package: Unknown
path: /usr/bin/conmon
version: 'conmon version 2.0.9, commit: 60b42f20f222df9da07a01ee444327348b9f54ee'
Distribution:
distribution: arch
version: unknown
IDMappings:
gidmap:
- container_id: 0
host_id: 1000
size: 1
- container_id: 1
host_id: 165536
size: 65536
uidmap:
- container_id: 0
host_id: 1000
size: 1
- container_id: 1
host_id: 165536
size: 65536
MemFree: 129361162240
MemTotal: 134693437440
OCIRuntime:
name: runc
package: Unknown
path: /usr/bin/runc
version: |-
runc version 1.0.0-rc10
commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
spec: 1.0.1-dev
SwapFree: 0
SwapTotal: 0
arch: amd64
cpus: 12
eventlogger: journald
hostname: archlinux
kernel: 5.5.2-arch1-1
os: linux
rootless: true
slirp4netns:
Executable: /usr/bin/slirp4netns
Package: Unknown
Version: |-
slirp4netns version 0.4.3
commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
uptime: 3h 27m 31.79s (Approximately 0.12 days)
registries:
search:
- docker.io
- registry.fedoraproject.org
- quay.io
- registry.access.redhat.com
- registry.centos.org
store:
ConfigFile: /home/grzegorz/.config/containers/storage.conf
ContainerStore:
number: 0
GraphDriverName: overlay
GraphOptions:
overlay.mount_program:
Executable: /usr/bin/fuse-overlayfs
Package: Unknown
Version: |-
fusermount3 version: 3.9.0
fuse-overlayfs: version 0.7.5
FUSE library version 3.9.0
using FUSE kernel interface version 7.31
GraphRoot: /home/grzegorz/.local/share/containers/storage
GraphStatus:
Backing Filesystem: extfs
Native Overlay Diff: "false"
Supports d_type: "true"
Using metacopy: "false"
ImageStore:
number: 1
RunRoot: /run/user/1000/containers
VolumePath: /home/grzegorz/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
pacman -Q podman
podman 1.7.0-1
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on my laptop but also seen the same behavior on my throwaway test system on Linode.

**Comment by grzegorzk** [comment]
I have tried to test the container with `privileged` option and run it as root. If I install `openssh` within the container and run it I can see the `sshd` process is listening for traffic on port 22, `openvpn` starts and definitely binds to `tun` device, however it does not listen on expected port (I cannot see `openvpn` entry in `netstat` output).

**Comment by rhatdan** [comment]
Are you running rootless or rootfull?

**Comment by grzegorzk** [comment]
Running as root:

```
podman run --rm -d --name openvpn --network="host" --privileged -p 37898:37898 -v ./entrypoint.sh:/entrypoint.sh archlinux /bin/bash /entrypoint.sh
```

(`entrypoint.sh` attached as `entrypoint.sh.txt`, all certs and keys had been created for this test)

[entrypoint.sh.txt](https://github.com/containers/libpod/files/4184384/entrypoint.sh.txt)

**Comment by grzegorzk** [comment]
I see the same behavior when running within alpine container:

```
podman run --rm -d --name openvpn --network="host" --privileged -p 37898:37898 -v ./entrypoint.sh:/entrypoint.sh alpine:3.10 /bin/sh /entrypoint.sh
```

[entrypoint.sh.txt](https://github.com/containers/libpod/files/4184411/entrypoint.sh.txt)

**Comment by vrothberg** [comment]
@grzegorzk, can you try with Podman v1.8.0?

**Comment by grzegorzk** [comment]
Tried on v1.8.0 however I'm seeing the same behavior (openvpn starts, binds to tun0 however `netstat` does not list openvpn; I tried to start `sshd` from within the container and can see service listening  listed by netstat)

**Comment by grzegorzk** [comment]
It works, though I changed so many things on the way that I'm not sure if it was podman version bump. I will do little writeup on openvpn wiki pages for others to use. Thanks for your great help!
