### ISSUE TITLE
rootless podman cant bind mount a volume file.

### ISSUE THREAD

**Issue by nimbius** [containers/libpod#5134]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

bind mounting a single file with -v throws a go error.

**Steps to reproduce the issue:**

1. mount a single file during podman run (-v configuration.py:/etc/config/configuration.py )

2.

3.

**Describe the results you received:**
error in container_linux.go

Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/cicero/.local/share/containers/storage/volumes/configuration.py/_data\\\" to rootfs \\\"/home/cicero/.local/share/containers/storage/vfs/dir/aa48a7a30b304bdba9fbf100c4667454685306e6d2f52ec6f90b08b1a8e8c567\\\" at \\\"/home/cicero/.local/share/containers/storage/vfs/dir/aa48a7a30b304bdba9fbf100c4667454685306e6d2f52ec6f90b08b1a8e8c567/etc/netbox/config/configuration.py\\\" caused \\\"not a directory\\\"\"": OCI runtime error

**Describe the results you expected:**
file bind mounted properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
Built:              Sat Jan 11 04:49:39 2020
OS/Arch:            linux/amd64
```
(paste your output here)
```

**Output of `podman info --debug`:**
debug:
  compiler: gc
  git commit: b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 60b42f20f222df9da07a01ee444327348b9f54ee'
  Distribution:
    distribution: arch
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
  MemFree: 10153840640
  MemTotal: 16781713408
  OCIRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  eventlogger: journald
  hostname: malt
  kernel: 5.4.15-arch1-1
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 41m 22.84s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/cicero/.config/containers/storage.conf
  ContainerStore:
    number: 22
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/cicero/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 8
  RunRoot: /run/user/1000
  VolumePath: /home/cicero/.local/share/containers/storage/volumes

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Comment by mheon** [comment]
You need to make the file a relative path by saying ./ in front of it;
otherwise, we assume it's the name of a named volume. I would expect that
to work, and not will, though. Given that, I think we have a definite bug
in the handling of the named volume, and a case we should document better
(everything passed to -v that is not an absolute or relative path will be
assumed to be the name of a named volume).

**Comment by nimbius** [comment]
hm.  relative pathing still appears to produce a fault.


 podman run --pod netbox-pod -v ./configuration.py:/etc/netbox/config/ netboxcommunity/netbox:v2.7.4
Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/cicero/netbox-dev/netbox/netbox/netbox/netconfig_01/configuration.py\\\" to rootfs \\\"/home/cicero/.local/share/containers/storage/vfs/dir/420de5979ea542e15a9285dea7024f0fb1179c75db4fbe445060bb63ff0de82a\\\" at \\\"/home/cicero/.local/share/containers/storage/vfs/dir/420de5979ea542e15a9285dea7024f0fb1179c75db4fbe445060bb63ff0de82a/etc/netbox/config\\\" caused \\\"not a directory\\\"\"": OCI runtime error

**Comment by mheon** [comment]
Alright, that's probably the same error we saw with the named volume. I'll
take a look on Monday.

**Comment by rhatdan** [comment]
Can you try to fully path it?

-v $PWD/...

**Comment by mheon** [comment]
I can't replicate this on Fedora 30 or 31, runc or crun, with latest Podman (1.8.0). Any chance you can retest with 1.8.0 and see if the problem is resolved?

**Comment by nimbius** [comment]
upgraded to latest 1.8 on Arch and the issue is no longer seen in debug or my CI.
