### ISSUE TITLE
buildah volume names ignored in podman

### ISSUE THREAD

**Issue by nimbius** [containers/libpod#5139]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

volumes created in 'buildah config -v' are created in podman during 'podman run' but the names assigned in buildah to the image are ignored.

**Steps to reproduce the issue:**

1. buildah from $image --name $yourimage

2. buildah config -v test:/path/to/bind/mount $yourimage

3.buildah commit 

**Describe the results you received:**
podman volume ls shows volumes are created and tracked properly, however 
the names are 65 character anonymous bind...not the name set in buildah. 

**Describe the results you expected:**
names set for mount points in buildah are honored by podman

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
Built:              Sat Jan 11 04:49:39 2020
OS/Arch:            linux/amd64

**Output of `podman info --debug`:**

debug:
  compiler: gc
  git commit: b7ce1157b00af09f4a09e39b377aa3abff46ee05-dirty
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 60b42f20f222df9da07a01ee444327348b9f54ee'
  Distribution:
    distribution: arch
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 110000
      size: 65536
  MemFree: 3906342912
  MemTotal: 16781713408
  OCIRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 16
  eventlogger: journald
  hostname: malt
  kernel: 5.4.15-arch1-1
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 17h 24m 9.05s (Approximately 0.71 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/cicero/.config/containers/storage.conf
  ContainerStore:
    number: 10
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/cicero/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 12
  RunRoot: /run/user/1000
  VolumePath: /home/cicero/.local/share/containers/storage/volumes

**Comment by mheon** [comment]
I don't believe that names for volumes are part of the OCI or Docker image specifications, just the paths they will be made at - @baude @vrothberg correct me if I'm wrong here

**Comment by nimbius** [comment]
ah, silly me.  this isnt part of the spec at all and for good reason.
https://github.com/moby/moby/issues/30647

spec 1.1 and 1.2 also do not reference named volumes anywhere...so i wonder why buildah even offers the option to name a volume if its pointless in the image
