### ISSUE TITLE
rootless podman: port forwarding does not work if firewalld is installed

### ISSUE THREAD

**Issue by disaster123** [containers/libpod#5141]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

curently no idea if this is expected or not

**Description**

If firewalld is running on the host the port forwardig for rootless containers does not work as all traffic is blocked in firewalld.

**Steps to reproduce the issue:**

1. install and enable firewalld

2.install podman 1.8.0

3. run a container using port forwarding f.e.: podman run --rm --name some-nginx -d -p 8080:80 nginx

**Describe the results you received:**

Port 8080 is not accessible for outside world and no rule was added to iptables to allow this kind of traffic.

**Describe the results you expected:**

I would expect that podman somehow inserts a rule into iptables or somewhat interacts with firewall or or there is a special chain for containers in firewalld or there is a documentation describing on how to solve this.

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: debian
    version: "10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 2002
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 14995468288
  MemTotal: 16617996288
  OCIRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.12.1.2-552e
      commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: cloud1-vm137
  kernel: 4.19.102+48-ph
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 60h 46m 37.35s (Approximately 2.50 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 0.3
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000/containers
  VolumePath: /home/podman/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.0~2 amd64 [installed]
podman/unknown 1.8.0~2 arm64
podman/unknown 1.8.0~2 armhf
podman/unknown 1.8.0~2 ppc64el
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@AkihiroSuda PTAL, Is this a slirp4netns issue?

**Comment by giuseppe** [comment]
I think it is expected, as rootless we don't touch the firewall, that is a privileged operation

**Comment by disaster123** [comment]
mhm than this is most probably a feature request. I hoped that there is a possibilty to arrange this by using dbus or something like this.

**Comment by rhatdan** [comment]
Is there a way to talk to dbus about opening firewall ports for rootless users?

**Comment by disaster123** [comment]
Good question - no idea ;-)

**Comment by mheon** [comment]
Fedora Workstation already defaults 1025-65536 to open. I don't believe server does the same for security reasons.

**Comment by rhatdan** [comment]
I don't believe there is a way for a non privileged user to request dbus to open fire wall rules.  Reopeon if I am mistaken.  A PR to the troubleshooting guide might be helpful for this as well,

**Comment by ahmadalli** [comment]
Sorry if I'm late to the party. I think this is the right behavior. Even for a rootful container, I think it's better to have an option if we want to open the port to the world or not (and control access to ports using firewalls).

This is why I'm considering the use `slirp4netns` even for my rootful containers
