### ISSUE TITLE
docker commit: wrong help text

### ISSUE THREAD

**Issue by loibpet** [containers/libpod#5145]
/kind bug

**Description**

Thanks for the quick fix for issue #5027 which is working now as expected.

However, the help text still needs a little update regarding the now removed second mandatory parameter:

```shell
podman --version && podman commit --help

podman version 1.8.0

Create new image based on the changed container

Description:
Create an image from a container's changes. Optionally tag the image created, set the author with the --author flag, set the commit message with the --message flag, and make changes to the instructions with the --change flag.

Usage:
  podman commit [flags] CONTAINER IMAGE
```

**Comment by rhatdan** [comment]
@loibpet Would you be interested in opening a PR to fix this?

**Comment by Jumanjii** [comment]
@loibpet  I don't want to rush this one on you as my first contribution to this project.
Could you just share if you want to do it or if I can create the merge request?

https://github.com/containers/libpod/blob/master/cmd/podman/commit.go#L18

**Comment by loibpet** [comment]
Pls. go on an create a PR
