### ISSUE TITLE
podman login with different mandatory parameter than docker login

### ISSUE THREAD

**Issue by loibpet** [containers/libpod#5146]
/kind bug

**Description**

Ran into this problem, when I was checking if scripts developed for docker were running with podman.

podman supposed to be compatible to docker in terms of parameters. However, there are still breaking differences:

```shell
docker --version && docker login --help

Docker version 1.13.1, build 07f3374/1.13.1

Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry

Options:
      --help              Print usage
  -p, --password string   Password
  -u, --username string   Username
```

whereas:
```shell
podman --version && podman login --help

podman version 1.8.0

Login to a container registry

Description:
  Login to a container registry on a specified server.

Usage:
  podman login [flags] REGISTRY

Examples:
  podman login -u testuser -p testpassword localhost:5000
  podman login -u testuser -p testpassword localhost:5000
  podman login --authfile authdir/myauths.json quay.io

Flags:
      --authfile string   Path of the authentication file. Use REGISTRY_AUTH_FILE environment variable to override
      --cert-dir string   Pathname of a directory containing TLS certificates and keys used to connect to the registry
      --get-login         Return the current login user for the registry (default true)
  -p, --password string   Password for registry
      --password-stdin    Take the password from stdin
      --tls-verify        Require HTTPS and verify certificates when contacting registries (default true)
  -u, --username string   Username for registry
```
The issue the mandatory parameter (REGISTRY) for the podman command. This breaks any compatibility.

**Describe the results you expected:**

No additional mandatory parameter for parameter inherited from docker.

**Comment by rhatdan** [comment]
Well Docker is only supporting one registry Docker.io.  We could do similar and only support the first registry in registries.conf.  I am not crazy about hard coding docker.io into podman login.

**Comment by loibpet** [comment]
This is exactly what we do. We change the registries.conf to point to an internal registry. This is where we push then our images with the scripts.

**Comment by rhatdan** [comment]
Ok, we can default to the first registry in registries.conf if it does not exist.
Would you be interested in opening a PR for this?

**Comment by rhatdan** [comment]
As soon as #5233 gets merged this issue will close.
