### ISSUE TITLE
Cannot run `podman system service` as normal user

### ISSUE THREAD

**Issue by marusak** [containers/libpod#5147]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Running `podman system service` as normal user fails:
```
$ podman system service
Error: could not get runtime: eventer creation: No support for journald logging
```

**Describe the results you expected:**

Succeed the same way as root one does:
```
$ sudo podman system service
This function is EXPERIMENTAL.
```

**Output of `podman version`:**

I build the current master with `$ ./contrib/build_rpm.sh` and then installed the produced rpm.

**Comment by giuseppe** [comment]
how have you created the user session?

Do you have any file under `~/.containers/config`?

**Comment by marusak** [comment]
> how have you created the user session?

I am not sure if I understand the question correctly, but I just logged in into my Fedora 31 account.

> Do you have any file under ~/.containers/config?

```
ls ~/.containers/config
ls: cannot access '/home/mmarusak/.containers/config': No such file or director
```

**Comment by giuseppe** [comment]
> Error: could not get runtime: eventer creation: No support for journald logging

looks like Podman got built without systemd support, is `systemd-devel` installed correctly?

What is the output for `hack/systemd_tag.sh` ?

**Comment by marusak** [comment]
> looks like Podman got built without systemd support, is systemd-devel installed correctly?

```
$ rpm -q systemd-devel
systemd-devel-243.5-1.fc31.x86_64
```

> What is the output for hack/systemd_tag.sh ?
```
systemd
```

But anyway, It was my local build which was broken. I removed it, installed whatever is released in Fedora and it works.
However, would be great if also local builds would work.

But closing, thanks for your help!
