### ISSUE TITLE
podman ps -a --format=json does not include image hash 

### ISSUE THREAD

**Issue by liewegas** [containers/libpod#5160]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The ``podman inspect`` output includes the both the ``Image`` property (the hash) and ``ImageName`` property (container name).  ``podman ps --format=json`` output does not include the hash.  For our application (ceph), that means we need to run inspect on every running container to get this information and build a host inventory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
1.7.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.9-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 7d46f3e7711aa3578488284ae2f98b447658f086'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 37882519552
  MemTotal: 202800291840
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 23485739008
  SwapTotal: 24008192000
  arch: amd64
  cpus: 32
  eventlogger: journald
  hostname: gnit
  kernel: 5.3.16-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 318h 53m 57.5s (Approximately 13.25 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 13
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 15
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

**Comment by baude** [comment]
@liewegas thanks for the report ... im not sure i understand what you are asking for.  you want another field that has the hash or ? are you comparing us to docker?

**Comment by vrothberg** [comment]
Note that `podman inspect` does _not_ contain the hash (i.e., the sha256 digest) of an image but the image ID which is also included in `podman ps`:
```
$ podman ps --format=json            
[                                                    
     {                                               
          "ID": "694456a0f847",                      
          "Image": "docker.io/library/alpine:latest",
....
```

The difference is that `ps` prints the short digest, while `inspect` shows the full digest:
```

**Comment by mheon** [comment]
Isn't `ID` in ps the container ID?

**Comment by vrothberg** [comment]
> Isn't `ID` in ps the container ID?

Must have been a lack of coffee :^) Yes, that's the container ID.

Inspect uses "Image" as the ID, and "ImageName" as the reference. Ps is using "Image" as the reference.

Curiously:
```
root@nebuchadnezzar valentin # docker ps --format "{{.ID}} {{.Image}}"
a24b256a66ac alpine
```
While Docker docs claim Image as the ID...

It would still be helpful to fully understand @liewegas's use case.

**Comment by liewegas** [comment]
I'm trying to build an inventory of running ceph containers on the host that includes

- container id
- image name
- image id (hash)

and do it quickly.  Right now that requires running podman inspect on every container, which makes this inventory take many seconds overall.  If the podman ps included the image hash, then it would have everything I need and (I'm hoping) still take the <200ms it does now.

**Comment by vrothberg** [comment]
I think we can add that to the output. But note that the ID is not a hash (as the image digest) but just a unique ID.

**Comment by rhatdan** [comment]
Is there a way to customize the podman ps output, similar to podman top?

**Comment by vrothberg** [comment]
> Is there a way to customize the podman ps output, similar to podman top?

Yes, with `--format`.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/libpod/pull/5223
