### ISSUE TITLE
Failure running podman with systemd as non root user

### ISSUE THREAD

**Issue by lburgazzoli** [containers/libpod#5173]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to run a a systemd service with podman as non privileged user but the service fails with  error. The same service work when executed as root

**Steps to reproduce the issue:**

1. create a new user 
```
useradd -s /sbin/nologin --create-home nexus-system
```

2. install a systemd service file as follow:
```
[Unit]
Description=Nexus Podman container
Wants=syslog.service

[Service]
User=nexus-system
Group=nexus-system
Restart=always
ExecStart=/usr/bin/podman run \
	--log-level=debug \
	--rm \
	-ti \
	--publish 8081:8081 \
	--name nexus \
	sonatype/nexus3:3.20.1

ExecStop=/usr/bin/podman stop -t 10 nexus

[Install]
WantedBy=multi-user.target
```
3. run the service
```
systemctl daemon-reload
systemctl start nexus
```

**Describe the results you received:**

Service fails to start with the following message:
```
could not get runtime: error generating default config from memory: cannot mkdir /home/nexus-system/rundir/libpod: mkdir /home/nexus-system/rundir/libpod: no such file or directory
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 32241123328
  MemTotal: 33633120256
  OCIRuntime:
    name: crun
    package: crun-0.12.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.1
      commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 34359734272
  SwapTotal: 34359734272
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: uranus
  kernel: 5.4.17-200.fc31.x86_64
  os: linux
  rootless: false
  uptime: 38m 18.26s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64
```

**Comment by rhatdan** [comment]
could not get runtime: error generating default config from memory: cannot mkdir /home/nexus-system/rundir/libpod: mkdir /home/nexus-system/rundir/libpod: no such file or directory
This looks like you have hacked up the ~/.config/containers directory?

**Comment by mheon** [comment]
I think we select that directory if all else fails and we cannot find a usable /run/user or /tmp

In any case, having /run in your $HOME and not on a tmpfs is DANGEROUS and strongly not recommended. You may wish to run `podman system reset` (will delete all containers + pods + images) and let Podman regenerate its configuration - that may get a more usable tmpdir

**Comment by lburgazzoli** [comment]
> could not get runtime: error generating default config from memory: cannot mkdir /home/nexus-system/rundir/libpod: mkdir /home/nexus-system/rundir/libpod: no such file or directory
> This looks like you have hacked up the ~/.config/containers directory?

Not at all

**Comment by lburgazzoli** [comment]
> I think we select that directory if all else fails and we cannot find a usable /run/user or /tmp
> 
> In any case, having /run in your $HOME and not on a tmpfs is DANGEROUS and strongly not recommended. You may wish to run `podman system reset` (will delete all containers + pods + images) and let Podman regenerate its configuration - that may get a more usable tmpdir

`podman system reset` done, but I see the same error

**Comment by rhatdan** [comment]
The issue here is the user has never logged, in.  Podman is being run as a user, but podman makes assumptions about XDG_RUNTIME_DIR being setup when it executes.  I think this is what is going wrong.

**Comment by lburgazzoli** [comment]
so `loginctl enable-linger nexus-system` seems to help here
