### ISSUE TITLE
No network in nested containers

### ISSUE THREAD

**Issue by matpen** [containers/libpod#5188]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Like [others](https://github.com/containers/libpod/issues/4131), me too I am looking forward to the ability of running unprivileged containers inside other unprivileged containers, which IIUC is being [worked on](https://github.com/containers/libpod/pull/4698). Meanwhile I am temporarily resorting to running inside **privileged** containers, which does work (can start a container and run a command), however the inner container gets no network.

**Steps to reproduce the issue:**

I tried different variation of the command below, and the result is always that the inner command `apt-get update` hangs for a while, then reports `Temporary failure resolving 'archive.ubuntu.com'`. By adding the `--network=host` to the inner run, the network becomes accessible, but this is not viable for my use case.

```bash
podman run \
    -it \
    --rm \
    --volume /tmp/podman:/var/lib/containers/storage \
    --privileged \
    --cap-add CAP_SYS_ADMIN \
    --security-opt seccomp=unconfined \
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --device /dev/fuse:rw \
    docker.io/library/ubuntu:18.04 \
    bash -c "
        # Install podman
        apt-get -yqq update
        apt-get -yqq install software-properties-common uidmap
        add-apt-repository -y ppa:projectatomic/ppa
        apt-get -yqq install podman slirp4netns iptables

        # Attempt to run container-in-container
        podman run \
            -it \
            --rm \
            --privileged \
            --cap-add CAP_SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --cgroup-manager cgroupfs \
            --events-backend=none \
            --device /dev/fuse:rw \
            docker.io/library/ubuntu:18.04 \
            apt-get -y update
"
```

**Describe the results you received:**

Inner container has no access to network, unless run with `--network=host`

**Describe the results you expected:**

The inner container should have access to the network.

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 938029056
  MemTotal: 16647700480
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 16565137408
  SwapTotal: 17036734464
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: matteo-laptop
  kernel: 5.3.0-28-generic
  os: linux
  rootless: false
  uptime: 13h 43m 35.79s (Approximately 0.54 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 25
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /home/matteo/podman/root
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 61
  RunRoot: /var/run/containers/storage
  VolumePath: /home/matteo/podman/root/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/bionic,now 1.6.2-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical laptop.

**Comment by rhatdan** [comment]
First have you tried to use buidah to build containers within locked down containers?  We have this working and images available on quay.io:buildah/stable.

https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/

Does this satisfy you needs?

As far as running a container within a container, we usually advise to turn off most of the namespaces on the internal container.  IE --net=host.  Since you are already in a container, no reason to add more isolation,  Especially if you are running in a locked down container.

**Comment by matpen** [comment]
> First have you tried to use buidah to build containers within locked down containers?

Yes, but I am stuck at [some point](https://github.com/containers/buildah/issues/1818). However, this issue is about a different use case (see below) since I am not trying to build containers.

> https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container/
> Does this satisfy you needs?

Studied carefully some time ago, and already implemented that way. However... see the issue I linked above.

> As far as running a container within a container, we usually advise to turn off most of the namespaces on the internal container. IE --net=host. Since you are already in a container, no reason to add more isolation, Especially if you are running in a locked down container.

In my case, the "outer" container provides a web service that allows users to run containers via a web interface. For this reason, the "inner" container network needs to be isolated, or it will conflict with the "outer" container, or with other "inner" containers.

**Comment by giuseppe** [comment]
in theory, from a nested unprivileged container it should be possible to use the full set of CNI plugins as the rootless user has full control on the network namespace in the outer container.

**Comment by matpen** [comment]
I am willing to provide more data and perform more tests, if it can help. Switching podman versions should be possible for me, too.

**Comment by giuseppe** [comment]
have you already tried using CNI from a rootless container (`--network bridge`)?

**Comment by matpen** [comment]
Just tried, no luck. But thanks to your suggestion, I also found `--network=slirp4netns`, and that one seems to work!

Not sure about the differences between the various types, and whether this one is suitable in our environment (any hint?) but I will go ahead and try to integrate this solution. Will report back as soon as possible.

**Comment by giuseppe** [comment]
slirp4netns on top of slirp4netns will be really slow.

Ideally we should use `--network host` inside of the container, or get CNI to work.

**Comment by matpen** [comment]
> slirp4netns on top of slirp4netns will be really slow.

I believe that this does not affect the current use case because the outer container is privileged (so it uses the bridge network?). Anyway, during my tests performance seems acceptable.

However, I am facing a different problem with `slirp4netns`: it appears that, as soon as the inner container is started, the outer container becomes unreachable (forwarded ports do not respond).

Here is a minimal reproducer (note that `podman_test` is simply a default Ubuntu image where I pre-installed podman + netcat, see the OP):
```bash
# Start the outer container in background
podman run \
    -it \
    --rm \
    --publish 127.0.0.1:8001:8000 \
    --volume /tmp/podman:/var/lib/containers/storage \
    --cap-add CAP_SYS_ADMIN \
    --cap-add CAP_NET_ADMIN \
    --volume /dev/net/tun \
    --security-opt seccomp=unconfined \
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
    podman_test \
    bash -c "
        # Start listening on the exposed port
        nc -lk 8000 &

        # Start the inner container (after some time)
        sleep 5
        podman run \
            -it \
            --rm \
            --cgroup-manager cgroupfs \
            --events-backend=none \
            --network=slirp4netns \
            docker.io/library/ubuntu:18.04 \
            bash -c 'sleep 10' &
" &

# Test before launching the inner container (succeeds)
sleep 2
nc -zv -w1 localhost 8001 >&2

# Test after launching the inner container (fails)
sleep 10
nc -zv -w1 localhost 8001 >&2

# Wait for background processes to exit
wait
```

**Comment by giuseppe** [comment]
> I believe that this does not affect the current use case because the outer container is privileged (so it uses the bridge network?). Anyway, during my tests performance seems acceptable.

if the outer process is rootless, it will still use slirp4netns.  `--privileged` for rootless doesn't give any additional privilege in the host for setting up a bridge

**Comment by matpen** [comment]
The outer container is rootful. Sorry for not being clear, I thought that privileged containers must be rootful (or they wont start).

**Comment by rhatdan** [comment]
No, I actually started to write a blog on this a while back. I should finish writing it.
--privileged means turn off all of the container security isolation. (SELinux, Dropped Capabilities, Read/Only kernel file systems, Seccomp.

It has nothing to do with Rootless or rootful, and nothing to do with namespaces.

**Comment by matpen** [comment]
Thank you for the clarifications. In any case, I will make sure to add `sudo` when posting examples, so that they become more clear. 

I also performed some checks and:
* running `podman inspect` on the running containers seems to confirm the use of the bridged network;
* I also see no difference in the output of `podman inspect` if I force the use of the bridge by adding `--network=bridge` on command line;
* adding `--network=bridge` to the outer container in my [last example](https://github.com/containers/libpod/issues/5188#issuecomment-586184501) makes no difference (network connectivity is lost when the inner container is started);
* adding `--network=bridge` to the inner container, too, makes no difference either: also, no error related to permissions is raised.

Also, you might have noticed that, in an effort of reducing permissions as much as possible, I removed `--privileged` in my last example and am using `--cap-add CAP_NET_ADMIN --volume /dev/net/tun` instead (I get permission errors without those).
It seems to me that those capabilities somehow allow podman to interfere with the host network setup... might this be a plausible theory?

**Comment by rhatdan** [comment]
@matpen Can I close this issue?

**Comment by matpen** [comment]
@rhatdan Actually, the issue does not seem to be solved. According to the [latest investigation](https://github.com/containers/libpod/issues/5188#issuecomment-586707796), there seem to be no viable workaround. My understanding is that the only hope to [get CNI to work](https://github.com/containers/libpod/issues/5188#issuecomment-585855545), as mentioned by @giuseppe. So, unless that task is being tracked by another issue, I would rather keep this one open.

**Comment by rhatdan** [comment]
@matpen @giuseppe No work on this in the last couple of months.

**Comment by giuseppe** [comment]
the inner container will end up trying to setup the same CNI network as the outer container.

You should either change the mask for the outer container, or the inner one.

Can you try the following command?

```
podman run \
    -it \
    --rm \
    --volume /tmp/podman:/var/lib/containers/storage \
    --privileged \
    --cap-add CAP_SYS_ADMIN \
    --security-opt seccomp=unconfined \
    --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
    --device /dev/fuse:rw \
        localhost/podman_test \
    bash -c "
        sed -i -e 's/10.88.0/10.89.0/g' /etc/cni/net.d/87-podman-bridge.conflist
        # Attempt to run container-in-container
        podman run \
            -it \
            --rm \
            --privileged \
            --cap-add CAP_SYS_ADMIN \
            --security-opt seccomp=unconfined \
            --cgroup-manager cgroupfs \
            --events-backend=none \
            --device /dev/fuse:rw \
            docker.io/library/ubuntu:18.04 \
            apt-get -y update
"
```

Please notice the additional sed command

**Comment by matpen** [comment]
@giuseppe Thank you very much for your input. This one looks like a viable solution.

I run exactly your code, and it seems to work: the last `apt-get -y update` properly connects to the internet. However, If we remove the `sed` command, we have the same behaviour described in the OP.

I will now try to implement this solution in my application, and report back if further roadblocks arise. Meanwhile, may I ask how we should regard this issue? Is it due to "user incompetence" or is it something that podman should handle automatically (and we can hope to see a PR in the future)?

**Comment by giuseppe** [comment]
the `sed` command is the proposed fix for the problem, I'd not expect it to work without it :-)

and I don't think podman should try to deal this case.  It is a misconfiguration from the user side.
