### ISSUE TITLE
ERRO[0000] error loading cached network config network not found in CNI cache

### ISSUE THREAD

**Issue by pik10** [containers/libpod#5193]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I get this error message. ERRO[0000] error loading cached network config: network "appnet" not found in CNI cache 

appnet is the name of my custom network.  

**Steps to reproduce the issue:**

1. run the command sudo podman container ls

2. if I run the same command again the error message doesn't appear.

**Describe the results you received:**
I received the list of containers after the error message

**Describe the results you expected:**
I expected the result without the error message.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.8.0
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 2905063424
  MemTotal: 8078143488
  OCIRuntime:
    name: crun
    package: crun-0.12.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.1
      commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8220831744
  SwapTotal: 8220831744
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: x1c01-local
  kernel: 5.4.17-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 9h 58m 33.32s (Approximately 0.38 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/peter/.config/containers/storage.conf
  ContainerStore:
    number: 5
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/peter/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /run/user/1000/containers
  VolumePath: /home/peter/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical computer.

![Screenshot from 2020-02-12 23-38-24](https://user-images.githubusercontent.com/24878616/74402031-14d23900-4df1-11ea-87eb-18690d19fdba.png)

**Comment by vrothberg** [comment]
Hi @pik10, thanks for opening this issue!

That's an error in ocicni (https://github.com/cri-o/ocicni/blob/master/pkg/ocicni/ocicni.go#L504-L508) and I would be prefer this to be a debug log; error logging a fall back isn't necessary IMHO.

**Comment by vrothberg** [comment]
I opened a PR -> https://github.com/cri-o/ocicni/pull/68

**Comment by vrothberg** [comment]
@rhatdan, can we cut a new release of ocicni to pull in the changes?

**Comment by rhatdan** [comment]
Sure, but I am not sure I have the power.
@haircommander @mrunalp PTAL

**Comment by haircommander** [comment]
I honestly can't find evidence of there being rigorous versions of ocicni. the latest tag is 0.1.0, somehow the currently vendored version here is `github.com/cri-o/ocicni v0.1.1-0.20190920040751-deac903fd99b` I can't find where in the package the version is defined. Would you be opposed to pulling in the most recent commit instead @vrothberg

**Comment by vrothberg** [comment]
> Would you be opposed to pulling in the most recent commit instead @vrothberg

I don't feel strongly about it (given it would fix a bug) but it's a project under the CRI-O umbrella, so I have the expectation that it's doing a proper release management. It would make the lives of downstream packagers (e.g., Debian) much easier.

**Comment by haircommander** [comment]
TBH I think it should live as a libpod package, but that conversation has dwindled

**Comment by rhatdan** [comment]
I just published v0.2.0...

**Comment by haircommander** [comment]
nice, thanks

**Comment by vrothberg** [comment]
Awesome!

**Comment by rhatdan** [comment]
Might get yelled at, but probably ignored.
