### ISSUE TITLE
podman pause container from registry.redhat.io?

### ISSUE THREAD

**Issue by nimbius** [containers/libpod#5201]
/kind feature

**Description**

why isnt pause pulled from registry.redhat.io if im logged in?  
if "The Red Hat Ecosystem Catalog is the official source for discovering and learning more about the Red Hat Ecosystem of both Red Hat and certified third-party products and services." then why am I pulling from Googles registry too?

**Steps to reproduce the issue:**

1.podman pod create --name foo 

2. watch things fail

**Describe the results you received:**

ERRO[0001] Error freeing pod lock after failed creation: no such file or directory 
Error: unable to create pod: error adding Infra Container: unable to pull k8s.gcr.io/pause:3.1: unable to pull image: Error initializing source docker://k8s.gcr.io/pause:3.1: error pinging docker registry k8s.gcr.io

**Describe the results you expected:**
pull that pod from registry.redhat.io, the official source for discovering and learning more about the Red Hat Ecosystem of both Red Hat and certified third-party products and services.

**Additional information you deem important (e.g. issue happens only occasionally):**

pulling from a single registry that bills itself as "Enterprise-Grade Containers"
and "Your trusted source for secure, certified, and up-to-date container images" 
is an excellent way to improve auditability of dockerless rootless containers in an 
enterprise setting.

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
[peapod@smbob ~]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 6ffbb2ec70dbe5ba56e4bfde946fb04f19dd8bbf'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 10000
      size: 55537
    - container_id: 55538
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 10000
      size: 55537
    - container_id: 55538
      host_id: 100000
      size: 65536
  MemFree: 1004707840
  MemTotal: 8095240192
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8401186816
  SwapTotal: 8401186816
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: smbob.rand.org
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-2.git21fdece.module+el8.1.1+5460+3ac089c3.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 2h 43m 27.76s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /home/peapod/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-1.module+el8.1.1+5259+bcdd613a.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/peapod/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1001
  VolumePath: /home/peapod/.local/share/containers/storage/volumes


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -qi podman
Name        : podman
Version     : 1.6.4
Release     : 2.module+el8.1.1+5363+bf8ff1af
Architecture: x86_64
Install Date: Tue 11 Feb 2020 09:00:48 AM PST
Group       : Unspecified
Size        : 59988453
License     : ASL 2.0
Signature   : RSA/SHA256, Mon 06 Jan 2020 06:57:25 AM PST, Key ID 199e2f91fd431d51
Source RPM  : podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.src.rpm
Build Date  : Fri 03 Jan 2020 04:20:53 AM PST
Build Host  : x86-vm-09.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://podman.io/
Summary     : Manage Pods, Containers and Container Images

```
enterprise environment with boring enterprise requirements.

**Comment by mheon** [comment]
There has been talk around this - let me see if I can dig up details

**Comment by vrothberg** [comment]
This seems like a Red Hat specific request, which should go through Red Hat customer channels rather than through the vendor-neutral upstream here :)

**Comment by nimbius** [comment]
@vrothberg 
there sure are a lot of Red Hat specific members in "the containers organzation," so you'll have to forgive me if I get my issues misplaced ;)

Opened case 02585119 for the full enterprise experience.

**Comment by cruscio** [comment]
Ran into an issue with this today. Podman 1.6.4

My organization blocks storage.googleapis.com. OpenDNS was hijacking the HTTP request to show a content filtering error page. 

```
[root ~]# podman pod create --name my_pod
ERRO[0001] Error freeing pod lock after failed creation: no such file or directory 
Error: unable to create pod: error adding Infra Container: unable to pull k8s.gcr.io/pause:3.1: unable to pull image: Error parsing image configuration: Get https://storage.googleapis.com/us.artifacts.google-containers.appspot.com/containers/images/sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e: remote error: tls: handshake failure
```

If you google [storage.googleapis.com](https://www.google.com/search?client=ubuntu&channel=fs&q=storage.googleapis.com) the top results are mostly about it being a malicious site. It's heavy handed security policy, but it's probably a not-uncommon filter on corporate networks.

**Comment by nimbius** [comment]
Is it safe for podman to check registries.conf for pause container location as well?

**Comment by giuseppe** [comment]
will be enough on RHEL to change the default setting for `infra_image` in `libpod.conf`?

**Comment by vrothberg** [comment]
> @vrothberg
> there sure are a lot of Red Hat specific members in "the containers organzation," so you'll have to forgive me if I get my issues misplaced ;)

Fully understand why you opened the issue :)

> Opened case 02585119 for the full enterprise experience.

Thanks!

Since it's a Red Hat specific request, I am closing the issue. As @giuseppe mentioned above, the infra image can be changed in the `libpod.conf` if desired.

**Comment by rhatdan** [comment]
Which means this is a packaging issue and should be handled by a Red Hat bugzilla.
