### ISSUE TITLE
Passing arg to bypass X11 cause permission denied error

### ISSUE THREAD

**Issue by groovyman** [containers/libpod#5226]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am not quite sure, if this is a bug. Let me explain what i have done. Id decided to migrate a dizzy java swing application into a podman. I also got some ideas from [X11 and podman](http://sham1.sinervo.fi/blog/x11_and_podman.html) So i reused a fedora system and added some software to run remote X11 sessions:

```
FROM fedora
ENV HOME=/home/yourhome
RUN mkdir -p ${HOME}

#
# mount the data file to an external ressource
#
VOLUME [ "/home/yourhome/export"  ]

#
# Packages
# perform updates 
RUN dnf -y update

# perform install (disabled php-fpm)
RUN dnf -y install xorg-x11-server-utils xorg-x11-xauth java-11-openjdk curl unzip wget


#
# get your java app as a zip
RUN cd ${HOME} && wget -N http://  .... 

# unzip arvice and delete archive
RUN unzip ,,,
ADD startjl.sh  /home/yourhome/startjl.sh
RUN chmod +x /home/yourhome/startjl.sh

# for testing
CMD tail -f /dev/null
# this should be exexuted CMD /home/yourhome/startjl.sh
```

The problem does not seem to be the dockerfile but its execution:

- This one runs without any X11 bypass arguments
`
  podman run -ti   myImage
`
- This one fails with this error message:

```
podman run -ti -e DISPLAY --net=host --rm  \
  --interactive --tty \
  -v  ${DATA_STORE}/data:/home/yourhome/export:z \
  -v ~/.Xauthority:/root/.Xauthority:z \
  jlohn01

-- i get this:
{"msg":"exec container process `/bin/sh`: Permission denied","level":"error","time":"2020-02-17T09:54:39.000393894Z"}
```

I already allowed the access on both directories:

```
chcon -t container_file_t -R  ${DATA_STORE}/data
chcon -t container_file_t -R  ~/.Xauthority
```

**Steps to reproduce the issue:**

1. simply try both runner 

2.

3.

**Describe the results you received:**

sometime this:
`{"msg":"exec container process `/bin/sh`: Permission denied","level":"error","time":"2020-02-17T09:54:39.000393894Z"}

in another constellation i saw this weired message, that a executable was not found in the path.

`
**Describe the results you expected:**
An application that is beeing display on my remote screen.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 2571313152
  MemTotal: 12284690432
  OCIRuntime:
    name: crun
    package: crun-0.12.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.1
      commit: df5f2b2369b3d9f36d175e1183b26e5cee55dd0a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 10710151168
  SwapTotal: 10737414144
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: buster
  kernel: 5.4.18-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 1h 48m 19.17s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/cgroove/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/cgroove/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 89
  RunRoot: /run/user/1000
  VolumePath: /home/cgroove/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-docker-1.8.0-2.fc31.noarch
cockpit-podman-13-1.fc31.noarch
podman-compose-0.1.5-2.git20191107.fc31.noarch
podman-1.8.0-2.fc31.x86_64
podman-plugins-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by groovyman** [comment]
update: I changed the cmd to the shell, that calls the java app and added also the volume arg `/tmp/.X11-unix/` but still receiving the eror:
```
[cgroove@buster lohnbuchhaltung]$ podman run -ti -e DISPLAY --net=host --rm    --interactive --tty  -v /tmp/.X11-unix/:/tmp/.X11-unix/  -v  ${DATA_STORE}/lohnbuch:/home/lohnf/jlohn:z   -v ~/.Xauthority:/root/.Xauthority:z  jlohn05
+ export HOME=/home/lohnf
+ HOME=/home/lohnf
+ export LD_LIBRARY_PATH=/home/lohnf/jlohn28
+ LD_LIBRARY_PATH=/home/lohnf/jlohn28
+ export DISPLAY
+ cd /home/lohnf/jlohn28
+ exec java -Xmx512m -jar jlohn.jar
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)

```
So the DISPLAY env-var does not work. I think that i am getting closer, but still missing something.

**Comment by rhatdan** [comment]
SELinux is going to block container_t from communicating with the XServer process.  Just chcon on /tmp is not going to help.  Disable selinux and see if you get further.

--security-opt label=disable

**Comment by groovyman** [comment]
Salut Dan,
1. i disabled selinux on the hosting system 
2. and called the container with:

```
podman run -ti -e DISPLAY=$DISPLAY --net=host --rm   --security-opt label=disable  -v  ${DATA_STORE}/data:/home/lohnbucher/jlohn:z   -v ~/.Xauthority:/home/lohnbucher/.Xauthority:z   -v /tmp/.X11-unix/:/tmp/.X11-unix/   jlohn06
```
But i still get the same error. Did you meant, that i should disable selinux on the host ? (i did)

**Comment by mheon** [comment]
I think the Toolbox folks forward X into the container - @debarshiray Did you need to do anything special to do that?

**Comment by groovyman** [comment]
Salut Matthew,
i think they work with CoreOS oder Silverblue, i gave 'fedora:latest' a try. Anyway any help is appreciated to get the java application to work inside a podman.

Thank you in advance!

**Comment by rhatdan** [comment]
No you do not need to disable SELinux on the host.
I take this it works with --privileged?
If yes, then we have an issue with Capabiltiies, SECCOMP or SELinux.  You seem to have eliminated SELinux, but just to make sure.
Can you try in permissive mode
setenforce 0
If this does not fix it and --privilege does, could you try without --privileged and just
--cap-add all
If this does not fix it, try with
--security-opt seccomp=unconfined

Then we might have a better idea of what security feature is blocking your access.

**Comment by adrianreber** [comment]
@groovyman 

Not exactly what you are looking for but I am using the following commands in an HPC like setup to run a container (rootless) with X forwarding:
```
export `scontrol show job $SLURM_JOBID | grep BatchHost`
srun -N 2 -n 2 podman pull quay.io/adrianreber/mpi-life:latest
srun -N 2 -n 2 touch /tmp/.Xauthority
srun hostname > hosts
ssh $BatchHost -X -C "cp .Xauthority /tmp/; mpirun --hostfile hosts podman run --rm --env-host --userns=keep-id --pid=host --ipc=host --net=host -v /tmp/podman-mpirun/:/tmp/podman-mpirun/:z  -v /tmp/.Xauthority:/home/mpi/.Xauthority:z quay.io/adrianreber/mpi-life:latest -b -p -m
```

This is on a host I connect to via `ssh -X` so it is even one level more complicated X forwarding. But this works rootless, so maybe there is something in this example which helps you.

If remember it correctly it was important that the user ID in the container is the same as outside, because X relies on that.

**Comment by groovyman** [comment]
Thank your very much for your help.
I got another idea to run a sshd inside the podman. That would change its behaviour to a running service. By ssh -Y i could tunnel X11.

**Comment by groovyman** [comment]
@rhatdan 

Just give you a reply on your suggestions:
1. test (setenforce=1 / --privileged)  not working, same X11 problem
2. test (setenforce=0 / --privileged)  not working, same X11 problem
3. test  setenforce=0 does not help. The podman process seems to be unable to connect to the UNIX-domain socket under :0  `Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.` 
4. test `security-opt seccomp=unconfined` also not working.

I think, one of both volume mounts cause the problem.

-  ~/.Xauthority:/home/lohnbucher/.Xauthority:z   
-   /tmp/.X11-unix/:/tmp/.X11-unix/

**Comment by rhatdan** [comment]
Well if this all does not fix it, then the only thing left would be user namespace. I guess login to the container and see if you can see these directories and what the permissions look like on them.

**Comment by groovyman** [comment]
Salut @rhatdan ,
i fixed it using systemd and a running sshd.  I do not need any .X11 or socket bypassing by a mounted volume. 
```
FROM fedora

#
# mount the data file to an external ressource
#

#
# Packages
# perform updates 
RUN dnf -y update

# perform install (disabled php-fpm)
RUN dnf -y install firewalld openssh-server passwd xorg-x11-server-utils xorg-x11-xauth java-11-openjdk curl unzip wget firefox
RUN dnf clean all

#
# ## regitser an enable the postinstaller
ADD postInstaller.sh /usr/local/bin/postInstaller.sh

# install postinstall script as a service
RUN chown root:root  /usr/local/bin/postInstaller.sh
RUN chmod 740 /usr/local/bin/postInstaller.sh

ADD postinst.service /etc/systemd/system
RUN chmod 640 /etc/systemd/system/postinst.service
RUN chown root:root /etc/systemd/system/postinst.service
RUN systemctl enable postinst



# 
# enable sshd and allow remote access, firewall needs to be configured later
RUN systemctl enable sshd.service


#
# create user lohnbucher
ENV LBHOME=/home/lohnbucher
RUN useradd -m lohnbucher
RUN chown -R lohnbucher:lohnbucher  ${LBHOME}
RUN echo "secret\nsecret\n" | passwd --stdin --force lohnbucher 

#
# get a ole sh....  desktop application
RUN cd ${LBHOME} && wget -N http://   somewhere from the net 

# unzip arvice and delete archive
RUN cd ${LBHOME} && unzip -o javaZip.zip 
RUN cd ${LBHOME} && rm -f  javaZip.zip
# do some chown and chmod and publish a data directory as a volume

# export standard sshd port number
EXPOSE 22


# run systemd
CMD [ "/lib/systemd/systemd" ]

```
The postinstaller is the only service that takes over the nasty things, that podman-build is unable to carry out (i.e. start services, reconfigure systemd etc etc)
```
#!/bin/sh
# 
# magic postinstaller


# config the firewalld and restat sshd
firewall-cmd --permanent --zone=public --add-service=ssh 
systemctl restart sshd.service

# remove and restore lohnbucher Xauth file
mv ~lohnbucher/.Xauthority  ~lohnbucher/.XauthorityOLE
touch ~lohnbucher/.Xauthority
# perform some admin operations here


# add or start some addtional services here if you like

# run this installer only one
systemctl disable postinst
```
That was also the solution to run with multiple services in one container (see also #4909). I hope no _composer_ will kill me due to my heretic misuse of modern container art. ;-)

**Comment by rhatdan** [comment]
Good, you got a result.  I am gong to close this issue, since this is not something that is a bug in podman, other people have found other ways to satisfy this requirement.  Reopen if you disagree.
