### ISSUE TITLE
order of single + double dash options to `podman run` can cause errors

### ISSUE THREAD

**Issue by miabbott** [containers/libpod#5232]
/kind bug

Using RHCOS 44.81.202002131031-0 with `podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64`

Tried to run an existing container image with a mix of single dash and double dash options (notably `--systemd`) and the `run` command tries to pull the wrong image:

```
$ sudo podman run -d --systemd -p 80:80 docker-registry.upshift.redhat.com/miabbott/httpd:ubi-init
Trying to pull registry.access.redhat.com/80:80...
  name unknown: Repo not found
Trying to pull registry.fedoraproject.org/80:80...
  manifest unknown: manifest unknown
Trying to pull registry.centos.org/80:80...
  manifest unknown: manifest unknown
Trying to pull docker.io/library/80:80...
  denied: requested access to the resource is denied
Error: unable to pull 80:80: 4 errors occurred:
        * Error initializing source docker://registry.access.redhat.com/80:80: Error reading manifest 80 in registry.access.redhat.com/80: name unknown: Repo not found
        * Error initializing source docker://registry.fedoraproject.org/80:80: Error reading manifest 80 in registry.fedoraproject.org/80: manifest unknown: manifest unknown
        * Error initializing source docker://registry.centos.org/80:80: Error reading manifest 80 in registry.centos.org/80: manifest unknown: manifest unknown
        * Error initializing source docker://80:80: Error reading manifest 80 in docker.io/library/80: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

Or it has some sort of parsing error when options are shuffled around:

```
$ sudo podman run --systemd -d -p 80:80 docker-registry.upshift.redhat.com/miabbott/httpd:ubi-init
Error: cannot parse bool -d: strconv.ParseBool: parsing "-d": invalid syntax
```

Or it can't find the image at all?

```
$ sudo podman run -d -p 80:80 --systemd docker-registry.upshift.redhat.com/miabbott/httpd:ubi-init
Error: image name or ID is required
```

OK, looking at the actual help it shows that `--systemd` expects a string value...so maybe we can improve the usage here so that invalid values to `--systemd` are reported as such?

```
$ sudo podman run -d -p 80:80 --systemd true docker-registry.upshift.redhat.com/miabbott/httpd:ubi-init
e829cf747f99c13054519cf82456ebe9351eb37bf0a1d5daa0e5b11a8d906107
```

**Comment by mheon** [comment]
I think I might know this one... `--systemd` changed from a boolean to requiring an argument sometime recently, and it could well be consuming `-p` as its argument.

Try `--systemd=true`

**Comment by miabbott** [comment]
@mheon Yeah, I blindly went using `--systemd` without RTFM first.

In my original comment, you can see that passing a value to `--systemd` got me going.  But I still think some input validation would be appropriate here.

**Comment by mheon** [comment]
We do basically no parsing before pulling the image, which is arguably a mistake, but very difficult to change in the current code. Fortunately, we're already doing some reworks on create, so we might be able to fix this eventually.

**Comment by rhatdan** [comment]
@mheon Any update on this issue?

**Comment by rhatdan** [comment]
@ParkerVR --systemd option should fail unless the value of "true", "false", "always" is passed in.

**Comment by mheon** [comment]
Won't actually solve the original issue. The core of this was our change of `--systemd` from not taking an argument, to taking an argument.

**Comment by dougsland** [comment]
Looks like it was fixed by:

commit c8f57b71a4255938efa23fec37c59181c1c657e4
Author: Daniel J Walsh <dwalsh@redhat.com>
Date:   Fri Jun 5 10:44:16 2020 -0400

    Fix handling of systemd.
    
    Systemd enablement has to happen on the server side, since we need
    check if the image is running systemd.
    
    Also need to make sure user setting the StopSignal is not overriden on the
    server side. But if not set and using systemd, we set it correctly.
    
    Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>


$ ./bin/podman run --systemd -d -p 80:80 myhelloworld-http
Error: invalid config provided: --systemd values must be one of "true, false, always": invalid configuration

@rhatdan any additional work here or should we close?

**Comment by mheon** [comment]
This should be safe to close
