### ISSUE TITLE
Problem mounting cifs-share as volume into container

### ISSUE THREAD

**Issue by kommulu** [containers/libpod#5239]
Hi,
I hope this is the right place to ask a question regarding Podman.
So, I want to migrate my containers from Docker to Podman, to be able to run them rootless easily.
My biggest roadblock is the following:
On my container-host (CentOS 8, Podman 1.6.4) I have a cifs-share mounted. The share is mounted with uid and gid 8000 and the context set to "system_u:object_r:container_file_t:s0".

In one of my containers I have an application running that gets started with uid and gid 8000, so it can write to the share, which is mapped into the container as a volume.
If I run this container as root with Podman everything is fine. The application starts as uid 8000 and the share also is owned by uid/gid 8000.

But if I run that container as some other unprivileged user, the share suddenly is owned by root:root inside the container, which of course prevents the application from writing to that share.

I feel like I am missing something extremely obvious to solve that problem.
Can somebody maybe point me in the right direction or give me a hint?
Thanks in advance.

**Comment by mheon** [comment]
Firstly, you will *only* be able to write to that share from users that have access to UID and/or GID 8000. Rootless Podman runs with the same privileged that the user running it has; if that user does not have permission to access that UID and GID, we won't either. Furthermore, rootless Podman uses a user namespace to grant the user who ran it access to more than 1 UID and GID. This means that the view of the system that rootless Podman has is different; the user that ran the container will be UID/GID 0, and other users/groups specified in subuid and subgid will be added as 1-65536. These will not match the users and groups on the host for those numbers.

If you were to run a rootless container as UID/GID 8000 with `--userns=keep-id` then the UID and GID would be preserved in the container; UID/GID 8000 in the container and host would be the same users, so you could write to the share as you'd expect. Alternatively, if you ran the rootless container as UID/GID 8000 without `--userns=keep-id` and ran your app in the container as root, it would be able to access the share, as root in the container is mapped to the user and group that ran the container.

This is somewhat confusing, but it's one of the sacrifices we make for security in rootless. Root has the ability to ignore permissions checks, but without root we can't do that without massive security implications.

**Comment by rhatdan** [comment]
@kommulu Could you show the command you are using to run the container.  Bottom line, you need UID 8000 mapped into the user namespace if this is the only UID allowed to write to the container.
In the non root users entry in /etc/subuild, you need to add a mapping something like 8000:8000:1

**Comment by kommulu** [comment]
Hi @mheon ,

thank you for your idea, but sadly it does not work.
If I start the container like this:
`podman run -d --name iot_test -p 8081:8080 -v iot-data:/datadir -v /path/to/cifsshare:/files -e UID=8000 -e GID=8000 --userns=keep-id iot:latest`

The container fails to start with:
`Updating UID / GID... 
usermod: cannot lock /etc/passwd; try again later.`

@rhatdan the normal command to start my container would be:
`podman run -d --name iot_test -p 8081:8080 -v iot-data:/datadir -v /path/to/cifsshare:/files -e UID=8000 -e GID=8000 iot:latest`
How would I add that mapping? Am still kinda new to rootless containers.

**Comment by rhatdan** [comment]
Sadly that is not what I meant.
I was talking about adding 
8000:8000:1 to /etc/subuid for the user. Although I don't think that would work correctly either.

@giuseppe Would podman handle multiple entries in /etc/subuid and /etc/subgid?

**Comment by rhatdan** [comment]
No this will not work.
I was attemting to do.
dwalsh:100000:8000
dwalsh:8000:1
dwalsh:108001:5753

But this ends up mapping, UID 8000 on the host to UID 1 inside of the container.  I think we would need to do some special code in podman to be able to handle this.  Like --keep-uid

$ podman unshare cat /proc/self/uid_map
         0       3267          1
         1       8000          1
         2     100000       8000
      8002     108001      57536

**Comment by giuseppe** [comment]
The additional IDs are mapped sequentially.  So your user becomes root, then the first additional block starts at 1, the second one starts at len(first_block)...

If you want a specific user mapped you need to create an inner user namespace.  If you want user 8000 to be mapped to 0, then you'll need something like `--uidmap 0:1:1 --uidmap 1:0:1 --uidmap 2:2: 8000`

**Comment by rhatdan** [comment]
I wonder if we should add some way for a normal user to be able to do this.

**Comment by mheon** [comment]
`sudo podman system configure-uidmap $username` that allows us to map host UID/GIDs into that user?

The problem is that this is for all rootless containers, not just one (though I suppose we can alter the mappings in more containers to omit the added UIDs/GIDs... but that's also pretty awkward).

**Comment by kommulu** [comment]
So,
I tried it like @giuseppe suggested:
`podman run -d --name iot_test -p 8081:8080 -v iot-data:/datadir -v /path/to/cifsshare:/files -e UID=8000 -e GID=8000 --uidmap 0:1:1 --uidmap 1:0:1 --uidmap 2:2: 8000 iot:latest`

That alsmost did it, but the cifs-share was then owned by uid/gid 1 inside the container.
I tinkered around with the last --uidmap, but had no luck, but I also do not yet understand the uid-mapping.

**Comment by kommulu** [comment]
After thinking about the whole thing some more, is there any possibility at the moment to get this to work in a rootless environment?
The alternative for me would be: start the container as root, application starts with uid/gid 8000, cifs-share gets mapped correctly.
Only benefit here would be to ditch Docker.
SELinux is active on the container-host and works like a charm with podman, so I still have that as a security measurement.

But, could I start the container as root and still give it a new user-ns, so that a potential attacker is confined in a user-ns without root-access if they manage to break out of the container?
Does that make sense? If so, how would I do it?

**Comment by rhatdan** [comment]
If you want that you could do it with 
```
# podman --uidmap 0:500000:8000 --uidmap 8000:8000:1 --user 8000 ...
```

**Comment by kommulu** [comment]
Hi @rhatdan ,
I think I wrote this the wrong way.
With rootless podman, as far as I know, when I create a container as a normal user, the application inside gets started as user root. But, this is done inside a new usernamespace. So in the container it runs as uid 0, but on the host it is e.g. 13456.

Now, the problem seems to be, if I start my container as a non-privileged user, the mapping of my cifs-share does not work as expected. My application is not started as root anyways, I can set that via environment variables and it works fine.
So, it seems like I have to run the container as root on my host, to be able to use that cifs-share.
But I still would like to run the container as some random uid on my host., so that the following command does not look like it does:
`podman top --latest user huser`
`USER      HUSER`
`root      root`

Is that possible? To run as root inside the container, but have a different uid on the host?

**Comment by rhatdan** [comment]
The issue is whether or not the UID that owns the cifs-share is available within the User namespace that the user has access too.  

If the CIFS share is owned by UID 98765, and is only writeable by user 98765 then all the rootless users has to have 98765 mapped into their User Namespaces.  We do not handle this well at this time.

But another option would be to user default user groups.  If the Group 98765 is required to write to the CIFS share, then you could add non root users to the CIFS group.  Then user could execute a rootless podman container and leak the user groups into the container.  Note this requires the crun runtime, not runc.

```
man podman-run
...
       Note: if the user only has access rights via a group then accessing the
       device from inside a rootless container will  fail.  The  crun  runtime
       offers  a  workaround  for  this  by  adding  the  option  --annotation
       io.crun.keep_original_groups=1.
```

This should work on all non RHEL systems that have crun available, using an recent version of podman.

**Comment by kommulu** [comment]
Thanks for the additional idea, but all the servers are RHEL-based.
Anyways, I will try and get this to work in some way.
Thanks everybody for your help.
