### ISSUE TITLE
APIv2: possible decoder issue

### ISSUE THREAD

**Issue by schubter** [containers/libpod#5242]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

when trying the images/create?fromImage=golang&tag=1.12 endpoint I got stuck with: unable to pull :: error getting default registries to try: invalid reference format

after digging thru the code I found that the decoder does not seem to decode properly

I've added `        fmt.Println("create from image", query, r.URL.Query(), r.URL)`
below https://github.com/containers/libpod/blob/master/pkg/api/handlers/generic/images.go#L247

and this is the output

`create from image { } map[fromImage:[podman] tag:[master]] /v1.25/images/create?fromImage=podman&tag=master`

somehow the fromImage variable then passed into the ImageRuntime is just ":", which fails on every step of the way after.

**Describe the results you received:**

unable to pull :: error getting default registries to try: invalid reference format

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.13
Git Commit:         ff0f8388138f7b66c4312db0e984f0bedcac2558-dirty
Built:              Tue Feb 18 09:59:19 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ff0f8388138f7b66c4312db0e984f0bedcac2558-dirty
  go version: go1.12.13
  podman version: 1.8.1-dev
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: debian
    version: "10"
  MemFree: 1088954368
  MemTotal: 4138446848
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  SwapFree: 2274074624
  SwapTotal: 4138442752
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: hst-m04.dc.burg-1.de
  kernel: 4.19.0-6-amd64
  os: linux
  rootless: false
  uptime: 1955h 46m 24.54s (Approximately 81.46 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 37
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Comment by schubter** [comment]
I think I've tracked it down to here: https://github.com/gorilla/schema/blob/master/decoder.go#L194

seems like if the fields in the struct are lowercase, thus unexported - CanSet returns false

```
query := struct {
	FromImage string `schema:"fromImage"`
	Tag       string `schema:"tag"`
}{}
```

seems like this should fixe it

**Comment by rhatdan** [comment]
@schubter could you open a PR to fix?
