### ISSUE TITLE
rootless: error joining network namespace [...] unknown FS magic on "something cni"

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5246]
```console
$ podman run -d alpine sleep 10
21f3b66daff69619c8ba70870b51f26e3711207c8e5e252ccae311fb5d26bb56
$ podman ps
ERRO[0000] error joining network namespace for container 21f3b66daff69619c8ba70870b51f26e3711207c8e5e252ccae311fb5d26bb56: error retrieving network namespace at /var/tmp/run-1000/netns/cni-4ba3685e-05d7-1f91-2ed0-5f77eb68f2d1: unknown FS magic on "/var/tmp/run-1000/netns/cni-4ba3685e-05d7-1f91-2ed0-5f77eb68f2d1": ef53
CONTAINER ID  IMAGE                            COMMAND   CREATED       STATUS           PORTS  NAMES
21f3b66daff6  docker.io/library/alpine:latest  sleep 10  1 second ago  Up 1 second ago         silly_tereshkova
$ podman rm -a -f
ERRO[0000] error joining network namespace for container 21f3b66daff69619c8ba70870b51f26e3711207c8e5e252ccae311fb5d26bb56: error retrieving network namespace at /var/tmp/run-1000/netns/cni-4ba3685e-05d7-1f91-2ed0-5f77eb68f2d1: unknown FS magic on "/var/tmp/run-1000/netns/cni-4ba3685e-05d7-1f91-2ed0-5f77eb68f2d1": ef53
21f3b66daff69619c8ba70870b51f26e3711207c8e5e252ccae311fb5d26bb56
```
podman-1.8.1-0.1.dev.git0bd29f8.fc33 (yes, fc33) on rawhide fc32. Does not happen with podman-2:1.8.0-0.2.dev.gitc4f6d56.fc32. Again: this seems to be a podman problem, because the only difference between all-ok and all-fails is the podman rpm.

5.6.0-0.rc1.git0.1.fc32.x86_64
crun-0.12.1-1.fc32.x86_64
containernetworking-plugins-0.8.5-1.1.gitf5c3d1b.fc32.x86_64

Happens on pretty much podman-everything: `top`, `exec`, `kill`, too much for me to track down.

**Comment by rhatdan** [comment]
Could be the kernel as well.

**Comment by edsantiago** [comment]
If so it's a combination of elements. The only difference between (mostly) passing tests, and this failure, is `dnf upgrade podman`

**Comment by rhatdan** [comment]
@mheon @baude Any ideas.
I am on F32 right now, but I am running an older f31 podman.

**Comment by mheon** [comment]
When I have seen this before, it was from a user namespace mismatch - the rootless processes were in different user/mount namespaces so only one could see the netns mounts.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/libpod/pull/5324

**Comment by djnotes** [comment]
I was experiencing this error on WSL 2 with Fedora 35. I deleted the /tmp/myname-runtime and /tmp/podman-run-1000 directories and then exited WSL 2, executed `wsl --shutdown` and then booted up WSL again. Problem solved.
