### ISSUE TITLE
copr podman rpm "could not get runtime: eventer creation: No support for journald logging"

### ISSUE THREAD

**Issue by larsks** [containers/libpod#5250]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running the latest build from copr (podman-1.8.1-1582048950.gita5d55966.fc31.x86_64) fails with:

```
Error: could not get runtime: eventer creation: No support for journald logging
```

**Comment by rhatdan** [comment]
@larsks @baude Is this still an issue?

**Comment by larsks** [comment]
This appears to have been resolved.
