### ISSUE TITLE
podman play kube from deleted working directory errors out

### ISSUE THREAD

**Issue by Komic** [containers/libpod#5254]
/kind bug

Trying to run `podman play kube` from a non existing working directory results in the following error:
````
ERRO[0002] error starting some container dependencies
ERRO[0002] "unable to determine if \"\" is mounted: unable to get absolute path for : getwd: no such file or directory"
Error: error starting some containers: internal libpod error
````

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
@Komic Would you expect it to throw an  error or create the working dir?  What does kubernetes do?

**Comment by Komic** [comment]
That I don't know. Why is the working dir even relevant here, is it used internally? If not, as a user I guess I just expected it to run.

**Comment by rhatdan** [comment]
Workingdir, is the location where the executable is launched from.  Apps tend to do getpwd() call and I guess if this fails, then the app could fail.

**Comment by rhatdan** [comment]
@Komic Can I close this issue now?

**Comment by Komic** [comment]
If you don't think a fix is needed sure!
