### ISSUE TITLE
The fedora package of podman-remote contains regular podman

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#5298]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The `podman-remote` 1.8.0 package in Fedora 31 contains a regular `podman` binary.

This means that all commands run locally, despite $PODMAN_VARLINK_ADDRESS

**Reason**

It is missing a space character in the rpm specfile, when adding the extra build tags...

See https://github.com/kubernetes/minikube/issues/6708#issuecomment-589951963

**Output of `podman version`:**

```
[root@c37593dbac0d /]# podman-remote version -f json
{
    "Client": {
        "RemoteAPIVersion": 1,
        "Version": "1.8.0",
        "GoVersion": "go1.13.6",
        "GitCommit": "",
        "Built": 0,
        "OsArch": "linux/amd64"
    },
    "Server": {
        "RemoteAPIVersion": 1,
        "Version": "1.8.0",
        "GoVersion": "go1.13.6",
        "GitCommit": "",
        "Built": 0,
        "OsArch": "linux/amd64"
    }
}
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[root@c37593dbac0d /]# rpm -q podman-remote
podman-remote-1.8.0-2.fc31.x86_64
```

**Comment by afbjorklund** [comment]
ping @lsm5

**Comment by olivierlemasle** [comment]
Fedora bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1806147
Pagure PR: https://src.fedoraproject.org/rpms/podman/pull-request/24

**Comment by afbjorklund** [comment]
Probably better handled in Fedora, thanks for reporting!
