### ISSUE TITLE
podman logs --tail reverses output

### ISSUE THREAD

**Issue by Obbi89** [containers/libpod#5310]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using `podman logs --tail 10` on a container the output is newest line first instead of oldest first.

**Steps to reproduce the issue:**

1. `podman run --name tail_reversion -it debian:stable bash -c 'for f in {0..20}; do echo $f; done'`

2. `podman logs --tail 10 tail_reversion`

**Describe the results you received:**
Output lines are received in newest first order

**Describe the results you expected:**
Output lines should be oldest first.

Specifying `--tail -1` outputs lines in correct order.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I run in user mode (rootless) with the fuse-overlay driver.

**Comment by mheon** [comment]
@baude Would your tailreader have fixed this?

@Obbi89 We actually rewrote the way that `podman logs --tail` works in 1.8.1-rc1 to fix an unrelated issue, any chance you can try the RC?

**Comment by Obbi89** [comment]
@mheon aye I was able to quickly build podman and run it with the same commands as described above and the bug seems fixed.
Should've tried that earlier.
