### ISSUE TITLE
rootless: "The cgroups manager is set to systemd blah blah"

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5314]
#4574 is back in podman-1.8.1-0.3.rc1.fc31 (and, I believe, in rawhide)
```console
$ podman ps
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```
Yes, linger is enabled. Error goes away if I manually set magic envariables:
```
$ export XDG_RUNTIME_DIR=/run/user/1000
$ export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
$ podman ps
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

**Comment by mheon** [comment]
Are those environment variables not set otherwise?

**Comment by edsantiago** [comment]
No, but podman has (had?) some sort of magic internal logic that set them to defaults if unset.

**Comment by edsantiago** [comment]
bisect shows #5253 as culprit?!?

**Comment by mheon** [comment]
Did this part of the rootless code move into containers/common? Potentially we desynced between common and Podman implementations?

**Comment by edsantiago** [comment]
No, and that's what's stumping me! I don't see anywhere that could be affecting this:
```console
$ git cdif 84640525 c8436cd8
...long output, but only one place touches XDG_etc, and I can't see how that would break anything
```
The DBUS-setting code is in `libpod/runtime.go:SetXdgDirs()` and I could see how things might get twisty if `XDG_RUNTIME_DIR` is unset but the warning happens even if it _is_ set. And `/bus` exists under it. I've even tried stepping back to clear my mind; I don't see what can be causing this.

**Comment by edsantiago** [comment]
`ltrace` seems to imply that `SetXdgDirs()` is getting invoked and is performing correctly:
```
881629 setenv("XDG_RUNTIME_DIR", "/run/user/1000", 1)                            = 0
881629 setenv("DBUS_SESSION_BUS_ADDRESS", "unix:path=/run/user/1000/bus", 1)     = 0
```
(but it could also be the `Setenv` in `vendor/github.com/godbus/dbus/conn.go`. I don't know how to tell).

**Comment by edsantiago** [comment]
Update. I'm starting to feel sure that it's something to do with this new file:
```
vendor/github.com/containers/common/pkg/config/config.go
...
There's a `NewConfig()` that calls `config.checkCgroupsAndAdjustConfig()` which looks suspiciously like the warning we're seeing. If this somehow gets invoked before `SetXdgDirs()` in `cmd/podman/main.go`, it would explain the problem. Can someone go-literate please acknowledge and confirm?
