### ISSUE TITLE
how to enable traffic from pod to another pod's port?

### ISSUE THREAD

**Issue by ikke-t** [containers/libpod#5316]
/kind feature

**Description**

I need a bit guidance. I don't get traffic from one pod to another on the same host. How to enable pod to pod traffic within podman?

**Steps to reproduce the issue:**

1. I start pod for mqtt, it listens to 1883/tcp:

```
sudo podman run --name mosquitto \
  --rm -p "9001:9001" -p "1883:1883" \
  -v "/var/lib/containers/exported_volumes/mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z" \
 -v "/var/lib/containers/exported_volumes/mosquitto-data:/mosquitto/data:Z" \
 -v "/var/lib/containers/exported_volumes/mosquitto-log:/mosquitto/log:Z" \
  --conmon-pidfile  /%t/%n-pid --cidfile /%t/%n-cid \
  eclipse-mosquitto:latest
```

2. I start another pod as mqtt client for sending traffic to mqtt broker:

```
podman run \
   -it \
   -v /home/redhatter/data:/app/data:Z \
   --device=/dev/ttyACM0 \
   -e TZ=Europe/Helsinki \
   -v /run/udev:/run/udev:ro \
   --privileged=true \
   --name z2m
   koenkk/zigbee2mqtt
```

**Describe the results you received:**

I've tried both setting the bridge ip for mqtt client and also the host public ip. In either case I don't get connection:

```
zigbee2mqtt:info  2020-02-24 20:50:42: Connecting to MQTT server at mqtt://192.168.1.5                                                 
zigbee2mqtt:error 2020-02-24 20:51:22: Not connected to MQTT server!
```

I also tried allowing internal traffic for public ip:

```
firewall-cmd --permanent --zone=public --add-rich-rule=' rule family="ipv4" source address="10.88.0.0/16" port protocol="tcp" accept' 
```

here are the relevant network device settings:

```
    link/ether 00:0d:b9:4b:31:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.5/24 brd 192.168.1.255 scope global dynamic noprefixroute enp1s0
       valid_lft 84409sec preferred_lft 84409sec
    inet6 fe80::e7bd:5bae:a01e:bfa4/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
5: cni-podman0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether d2:20:02:52:ca:ac brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.1/16 brd 10.88.255.255 scope global cni-podman0
       valid_lft forever preferred_lft forever
    inet6 fe80::d020:2ff:fe52:caac/64 scope link 
       valid_lft forever preferred_lft forever
9: vethfb218ddb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cni-podman0 state UP group default 
    link/ether 2e:e3:bc:ce:91:0c brd ff:ff:ff:ff:ff:ff link-netns cni-041d8968-3756-8188-e622-96223e850187
    inet6 fe80::2ce3:bcff:fece:910c/64 scope link 
       valid_lft forever preferred_lft forever
```

I also got instructed at #podman@freenode to drop the firewall section, and add default gw to bridge config:

```
{
    "cniVersion": "0.4.0",
    "name": "podman",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "cni-podman0",
            "isGateway": true,
            "isDefaultGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "routes": [
                    {
                        "dst": "0.0.0.0/0"
                    }
                ],
                "ranges": [
                    [
                        {
                            "subnet": "10.88.0.0/16",
                            "gateway": "10.88.0.1"
                        }
                    ]
                ]
            }
        },
        {
            "type": "portmap",
            "capabilities": {
                "portMappings": true
            }
        }
    ]
}

```

**Describe the results you expected:**

MQTT client to connect to MQTT broker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:                                                                                                                           [7/335]
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 6ffbb2ec70dbe5ba56e4bfde946fb04f19dd8bbf'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 2986414080
  MemTotal: 3945947136
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1073737728
  SwapTotal: 1073737728
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: apu.konttikoulu.fi
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 37m 27.94s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical rhel8.1

**Comment by mheon** [comment]
The request here seems to be to access another pod via ports forwarded to the host with PortMap (that is, hit another pod via the host's IP and a forwarded port).

@mccv1r0 PTAL

**Comment by mccv1r0** [comment]
On Fedora 30 (my laptop) a quick test for me works fine.  I can connect to the port specified via -p using either the IP address assigned to the LOM device which gets dhcp address from corp network as well as the podman0 Linux bridge.

What is your iptables FORWARD policy?  Actually, to save a few round trips, what are your iptables rules for filter and nat tables?

The value of these sysctl variables will be helpful too:

 net.bridge.bridge-nf-call-arptables
 net.bridge.bridge-nf-call-ip6tables
 net.bridge.bridge-nf-call-iptables

**Comment by mccv1r0** [comment]
Make sure ```br_netfilter``` module is loaded as well

**Comment by mccv1r0** [comment]
@ikke-t : if possible can you try to insert a rule into firewalld FORWARD chain at the beginning:

 ```sudo iptables -I FORWARD -s 10.88.0.0/16 -j ACCEPT ``` 

If the last rule is a REJECT that matches everything, setting the default policy to ACCEPT isn't going to help.

**Comment by ikke-t** [comment]
Thanks a lot guys, now it works!

The magic there was that by default, RHEL doesn't load the br_netfilter. Also, one needs to put the bridge ip or host public ip instead of localhost.

I believe localhost is the 127.0.0.1 in the pod net namespace, instead the host one. I also removed the above mentioned trial of adding firewalld rich rule for bridge ip range, it is not needed once br_netfilter is loaded.

So all in all, perhaps podman should load br_netfilter to make sure the firewall rules work?

While debugging, I went throught the firewall rules, and otherwise they looked fine. I didn't have the default reject there.

**Comment by ikke-t** [comment]
I propose you add br_netfilter loading to podman rpm. As otherwise people will fail a lot with this. I fixed it like this on my system:

```
echo br_netfilter > /etc/modules-load.d/podman.conf
```

**Comment by rhatdan** [comment]
Seems like a packaging issue as opposed to an upstream issue.
@lsm5 WDYT?

**Comment by rhatdan** [comment]
@lsm5 Reping

**Comment by lsm5** [comment]
> @lsm5 Reping

I'll add this..

**Comment by lsm5** [comment]
added to rawhide https://koji.fedoraproject.org/koji/taskinfo?taskID=42876942

**Comment by rhatdan** [comment]
Can you add it to F32 as well?

**Comment by lsm5** [comment]
> Can you add it to F32 as well?

yup, will do

**Comment by lsm5** [comment]
> Can you add it to F32 as well?

https://koji.fedoraproject.org/koji/taskinfo?taskID=42891689

**Comment by rhatdan** [comment]
I believe this is fixed in the package now.
