### ISSUE TITLE
'shared' bind-propagation not working with unionfs-fuse

### ISSUE THREAD

**Issue by jobcespedes** [containers/libpod#5322]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to use bind-propagation shared with unionfs-fuse inside podman container does not work. The mount point is correctly shown inside container but not in host. Docker works. I'm not sure it is related to #1834

**Steps to reproduce the issue:**

1.  create dir layout for unionfs-mount
```bash
mkdir -p /tmp/multienv/dir1 && echo "dir1_var1" > /tmp/multienv/dir1/var
mkdir -p /tmp/multienv/dir2 && echo "dir2_var1" > /tmp/multienv/dir2/var
mkdir -p /tmp/multienv/unionfs
cd /tmp/multienv/
```

2. Test with podman
```bash
## mount 'dir2' over 'dir1' in '/tmp/multienv/unionfs' using a container
podman run --name multienv_unionfs --privileged=true --rm=true --env TZ=America/Costa_Rica --env PGID=1000 --env PUID=1000 --env UNION_DIRS=/dir2=RW:/dir1=RO --env MOUNT_PATH=/unionfs/ --env COW=true --volume /tmp/multienv/dir2:/dir2 --volume /tmp/multienv/dir1:/dir1 --volume /tmp/multienv/unionfs:/unionfs:shared --detach=true jobcespedes/multienv

## container's unionfs mount dir content
podman exec -it multienv_unionfs ls -al unionfs

## host's unionfs mount dir content
ls -al unionfs

## stop and remove container
podman stop multienv_unionfs
```
3. Test with docker
```bash
## mount 'dir2' over 'dir1' in '/tmp/multienv/unionfs' using a container
docker run --name multienv_unionfs --privileged=true --rm=true --env TZ=America/Costa_Rica --env PGID=1000 --env PUID=1000 --env UNION_DIRS=/dir2=RW:/dir1=RO --env MOUNT_PATH=/unionfs/ --env COW=true --volume /tmp/multienv/dir2:/dir2 --volume /tmp/multienv/dir1:/dir1 --volume /tmp/multienv/unionfs:/unionfs:shared --detach=true jobcespedes/multienv

## container's unionfs mount dir content
docker exec -it multienv_unionfs ls -al unionfs

## host's unionfs mount dir content
ls -al unionfs

## stop and remove container
docker stop multienv_unionfs
```

**Describe the results you received:**
1. With podman, host `unionfs` dir:
```bash
# ls -al unionfs
total 0
drwxrwxr-x. 2 job  40 feb 25 10:29 .
drwxrwxr-x. 5 job 100 feb 25 10:29 ..
```

1. With docker, host `unionfs` dir:
```bash
# ls -al unionfs/
total 4
drwxrwxr-x. 1 job  60 feb 25 10:28 .
drwxrwxr-x. 5 job 100 feb 25 10:29 ..
-rw-rw-r--. 1 job  10 feb 25 10:28 var
```

**Describe the results you expected:**
Same as Docker: files available in host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 352104448
  MemTotal: 16785330176
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 96f6022b37cbe12b26c9ad33a24677bec72a9cc3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: vm-01
  kernel: 5.4.19-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 141h 29m 58.75s (Approximately 5.88 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/home/job/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/job/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 9
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/job/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora Silverblue 31 VM

**Comment by mheon** [comment]
@rhatdan I think you're the most familiar with mount propagation - mind taking a look?

**Comment by giuseppe** [comment]
this is not a bug.  Rootless containers cannot create mounts in the host.

The `shared mount` is created inside of the rootless mount namespace, you can reach it with `podman unshare`

**Comment by mheon** [comment]
@jobcespedes It sounds like we expect this to work as root, but not without.

**Comment by jobcespedes** [comment]
Thanks for the clarification @giuseppe and @mheon . I was not aware of it. 

Two things:
1. I recently tried running it as root and `mount point`, files don't show up in host.
2. `podman unshare ls -al /tmp/multienv/unionfs` and `podman unshare mount`  show nothing for '/tmp/multienv/unionfs'

Am I getting it wrong?

**Comment by mheon** [comment]
If the procedure here fails as root, I'd consider that a bug. Reopening.

**Comment by jobcespedes** [comment]
@mheon I just find out it works with root outside /tmp. I don't know why it doesn't work in /tmp. For example mounting somewhere inside $HOME instead:
```bash
# As root
parent=$HOME
mkdir -p $parent/multienv/dir1 && echo "dir1_var1" > $parent/multienv/dir1/var
mkdir -p $parent/multienv/dir2 && echo "dir2_var1" > $parent/multienv/dir2/var
mkdir -p $parent/multienv/unionfs
cd $parent/multienv/

## mount 'dir2' over 'dir1' in '/tmp/multienv/unionfs' using a container
podman run --name multienv_unionfs --privileged=true --rm=true --env TZ=America/Costa_Rica --env PGID=1000 --env PUID=1000 --env UNION_DIRS=/dir2=RW:/dir1=RO --env MOUNT_PATH=/unionfs/ --env COW=true --volume $parent/multienv/dir2:/dir2 --volume $parent/multienv/dir1:/dir1 --volume $parent/multienv/unionfs:/unionfs:shared --detach=true jobcespedes/multienv
```

**Comment by jobcespedes** [comment]
One more thing: when rootless, even outside /tmp/, I didn't find anything with `podman unshare`

**Comment by giuseppe** [comment]
you need to make sure `$parent/multienv/unionfs` is already a mount on the host.

You can do something like:

```
# mount --bind --make-shared $parent/multienv/unionfs $parent/multienv/unionfs
```

for rootless you need to run that command from the `podman unshare` environment

**Comment by jobcespedes** [comment]
I see it now with `podman unshare`. Thank you.

I might need to change my approach. I wanted to symplify having a union directory.  But my current approach of having the unionfs binary and mounting the directory in a  rootless container seems kind of cumbersome related to that initial goal. I though it was just a matter of exposing the union directory to the host.

This is not podman related anymore. But if anyone thinks there is a better approach for simplifying things and don't mind sharing, it’ll be much appreciate it.

**Comment by mheon** [comment]
I wonder if adding `rshared` to the options for the volume mount would help

**Comment by giuseppe** [comment]
> I wonder if adding `rshared` to the options for the volume mount would help

for rootless no.  Mounts created in a rootless mount namespace will never be propagated to the host.

As unprivileged user you could use directly FUSE on the host to mount the unionfs but you'll have some limitations (no containers, no multiple IDs available...)

**Comment by jobcespedes** [comment]
>  Mounts created in a rootless mount namespace will never be propagated to the host

this is great for me actually, since the original intention is not to create one but to expose files from the union directory. 

If just files from a directory could be shown in the host without a mount being propagated...

I was thinking live syncing files between the union directory and another second directory, inside the container. Being that second directory, the volume shared with the host. However, it gets me far from my original goal of simplicity.

So, it's probably going to be FUSE in the host as suggested (no containers).

Thank you guys

**Comment by rhatdan** [comment]
@jobcespedes It would be good if you could write up a blog talking about what you found out.  Then we could link it from podman.io.

**Comment by jobcespedes** [comment]
Here is a [Draft](https://jobcespedes.github.io/2020/03/alias-docker-podman/) for the Blog idea. Planning on posting on Dev.to

Let me know what you think.

**Comment by rhatdan** [comment]
Looks great, thanks.

**Comment by jobcespedes** [comment]
[Here](https://jobcespedes.dev/2020/03/alias-docker-podman/) it is. The final version.
