### ISSUE TITLE
cgroup2: privileged and cgroupns

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/libpod#5341]
The [cgroup v2 KEP](https://github.com/kubernetes/enhancements/pull/1370) which was merged yesterday says "Privileged pods will still use the host cgroup namespace".

Should this apply to:
* `podman play kube`?  (I suggest yes, for Kubernetes compatibility)
* `podman run --privileged`? (I suggest no, for backward compatibility)

**Comment by mheon** [comment]
Tend to agree on both. We should also investigate enabling CGroup namespace sharing for our pods - I believe they're still not sharing.

**Comment by AkihiroSuda** [comment]
@giuseppe WDYT?

**Comment by giuseppe** [comment]
I would prefer that we are uniform here and both `--privileged` modes use the host cgroup namespace.  I think we are still in time for such a breaking change for `--privileged` on cgroup v2 :-)

**Comment by AkihiroSuda** [comment]
Either is fine to me

**Comment by rhatdan** [comment]
We have set a precedent that --privileged does not effect namespaces only security controls.  I don't think we should change that.

**Comment by giuseppe** [comment]
> We have set a precedent that --privileged does not effect namespaces only security controls. I don't think we should change that.

I think the goal is to be uniform with what Kubernetes does.  It was agreed to not unshare the cgroup namespace as there is currently no way to set it in Kubernetes and was also considered a breaking change.

Not sure how much we should care though.

**Comment by AkihiroSuda** [comment]
Any ETA of the final decision?

**Comment by AkihiroSuda** [comment]
ping

**Comment by giuseppe** [comment]
I am 50/50 whether it is better to do what K8s does (and what we did on cgroup v1) or handle cgroupns as the other namespaces.

**Comment by rhatdan** [comment]
As I said before --privileged does not effect namespaces, it should not eliminate --cgrouns or --userns.
`

**Comment by giuseppe** [comment]
ok so let's just fix `kube play` for Kubernetes compatibility
