### ISSUE TITLE
Podman hanging with couchdb

### ISSUE THREAD

**Issue by astronouth7303** [containers/libpod#5351]
/kind bug

**Description**

Podman+Couchdb consistently hangs.

I don't think this is quite the same as #5350 because I can get this to happen even immediately after I clean out all of podman.

**Steps to reproduce the issue:**

1. `podman run --env COUCHDB_USER=spam --env COUCHDB_PASSWORD=eggs --publish 127.0.0.1:5984:5984 --detach couchdb`

Other podman commands like `podman ps` hang while the above is running.

**Describe the results you received:**

I expect it to print the container ID and exit.

**Describe the results you expected:**

Never does either.

**Additional information you deem important (e.g. issue happens only occasionally):**

After Ctrl-C-ing the `podman run` command, I get the same `podman rm` error:

```
🐚 podman rm -f --all                                                                                                                             
Error: error removing container 76a75f2734acc74733024c2c6390d173d2fda046fc91d7fb5f51acc25847ce7d root filesystem: unlinkat /home/astraluma/.local/share/containers/storage/overlay-containers/76a75f2734acc74733024c2c6390d173d2fda046fc91d7fb5f51acc25847ce7d/userdata/shm: device or resource busy
```

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.8
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.8
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.9, commit: unknown'
  Distribution:
    distribution: debian
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 232390656
  MemTotal: 8229736448
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc10+dfsg1
      commit: 1.0.0~rc10+dfsg1-1
      spec: 1.0.1-dev
  SwapFree: 8373923840
  SwapTotal: 8467247104
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: cayde7
  kernel: 5.4.0-4-amd64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 1h 23m 50.25s (Approximately 0.04 days)
registries:
  search:
  - docker.io
store:
  ConfigFile: /home/astraluma/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  GraphRoot: /home/astraluma/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/astraluma/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.0~7 amd64 [installed]
podman/unknown 1.8.0~7 arm64
podman/unknown 1.8.0~7 armhf
podman/unknown 1.8.0~7 ppc64el
```

(Project kubric)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running debian on a real laptop, same one as all my other bugs.

**Comment by baude** [comment]
can you provide the whole command you are using including the image name?

**Comment by mheon** [comment]
I'm thinking this could also be a slirp issue

**Comment by astronouth7303** [comment]
@baude oops sorry, it's just the dockerhub `couchdb` library image.

**Comment by rhatdan** [comment]
@astronouth7303 Please provide the entire command you are seeing this with?  And are you using the latest podman comand?

**Comment by astronouth7303** [comment]
The entire command is at the top.

I was using the latest at the time I filed this bug. I know you've had a release since then. I haven't retested.

**Comment by mheon** [comment]
Can't reproduce locally - seems to be working fine over here. If you can still reproduce, adding a `--log-level=debug` to the command and pasting the output would probably help.

**Comment by astronouth7303** [comment]
This seems to have been cleaned up with Podman 1.8.2/slirp4netns 0.4.3.
