### ISSUE TITLE
f30: could not get runtime: default OCI runtime "crun" not found: invalid argument

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5358]
1.8.0-3.fc30 is failing [gating tests](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-f30-build-pipeline/detail/fedora-f30-build-pipeline/1357/pipeline/) with:
```
Error: could not get runtime: default OCI runtime "crun" not found: invalid argument
```

**Comment by lsm5** [comment]
i think this will be handled by https://bodhi.fedoraproject.org/updates/FEDORA-2020-89326b1795 . /cc @cevich

**Comment by edsantiago** [comment]
That is literally the build that broke gating tests...

**Comment by lsm5** [comment]
err sorry, i should've noticed the version-release sooner, can we modify gating test to explicitly install crun for f30? @cevich asked me to make crun a weak dep for f30.

**Comment by edsantiago** [comment]
f30 shouldn't be requiring or using crun, it should be runc only

I think there's some config file broken maybe? Maybe this is packaging a too-new version from master, and picking up a config file that specifies crun? I haven't dived into it, obviously.

**Comment by lsm5** [comment]
ack, yes. So I got `sed -s 's/^runtime[ =].*"runc/runtime = "crun/' libpod.conf  -i` in the rpm spec file. I guess I should leave it unchanged for f30.  /cc @mheon @cevich

**Comment by mheon** [comment]
Yeah, that should be 31 and higher only.

**Comment by cevich** [comment]
On master, the gate CI task uses a F31 container.  Other branches use lower versions but I'm not going to go looking for problems there :smile:

**Comment by cevich** [comment]
oh oops, those aren't the gating tests I was thinking of.  nevermind.

**Comment by lsm5** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2020-ccc3e64ea5

**Comment by rhatdan** [comment]
I believe this was fixed a while ago, reopen if I am mistaken.
