### ISSUE TITLE
Unprivileged podman should allow to not use slirp4nets ans still have port forwarding

### ISSUE THREAD

**Issue by ya-isakov** [containers/libpod#5362]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It looks like, now Podman is using Rootlesskit to implement port forwarding. This is confirmed by the fact, that incoming packets are seen on loopback interface, not on tap0. So, if I understand correctly, for some containers slirp4netns is not needed at all, e.g. for services which doesn't need to have network connectivity, and which could be set to listen on loopback.

**Comment by mheon** [comment]
Isn't this what `--net=none` does?

**Comment by ya-isakov** [comment]
Unfortunately, no. I also hoped that it will work, but it doesn't. Two things are not quite right - loopback interface is not up, and it looks like no process is listening for port in host.

**Comment by rhatdan** [comment]
@ya-isakov Are you still seeing this issue?  I believe --net=none should solve the issue in that the processes in the container will be on the network namespace of the host.

**Comment by ya-isakov** [comment]
@rhatdan as I said in https://github.com/containers/libpod/issues/5362#issuecomment-593166903, I've tried with --net=none, and it was not what I mean, as there was no interfaces at all, even loopback, which prevents my daemon from starting, as it was not found interfaces to listen on.

**Comment by rhatdan** [comment]
I should have said --net=host

**Comment by rhatdan** [comment]
Since I have not heard back, I think this solved your issue.
