### ISSUE TITLE
APIv2: Container create requires network

### ISSUE THREAD

**Issue by marusak** [containers/libpod#5366]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Using APIv2 to create a new container fails with `invalid network`. I just want to create a new container with using only the image name as I would do on command line.

**Steps to reproduce the issue:**

1. `sudo curl --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/containers/create -H "Content-Type: application/json" --request POST --data "{\"image\":\"docker.io/library/fedora:latest\"}"`

**Describe the results you received:**
`{"cause":"invalid network \"\"","message":"invalid config provided: invalid network \"\"","response":500}`

**Describe the results you expected:**
A container would be created. This command should be equivalent to `sudo podman create docker.io/library/fedora:latest` which succeeds. 

Using local build of the current master.

**Comment by baude** [comment]
i have a fix for this in my local git as I was fixing a number of issues.  I'll prune it out this morning and make a pr.

**Comment by marusak** [comment]
This is still not fixed.
The same reproducer works exactly the same with `podman-1.8.2-1.fc31.x86_64` which was released yesterday. (Also tried current master to build it for myself and the same result).
Can someone please reopen this issue?

**Comment by rhatdan** [comment]
@baude PTAL
