### ISSUE TITLE
Pushing signed images does not work as expected

### ISSUE THREAD

**Issue by saschagrunert** [containers/libpod#5378]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If I push an image into `quay.io` via `podman push --sign-by` and the repository has content trust enabled, then the pushed tag does still not show-up as signed.

**Steps to reproduce the issue:**

1. Create a quay.io repo with enabled content trust:
    ![create_repo](https://user-images.githubusercontent.com/695473/75773232-c4922b00-5d4d-11ea-9904-9626768458e9.gif)

2. Push a signed image:
```bash
> sudo podman pull docker.io/alpine
Trying to pull docker.io/alpine...
Getting image source signatures
Copying blob c9b1b535fdd9 [--------------------------------------] 0.0b / 0.0b
Copying config e7d92cdc71 done
Writing manifest to image destination
Storing signatures
e7d92cdc71feacf90708cb59182d0df1b911f8ae022d29e8e95d75ca6a99776a

> sudo podman tag docker.io/alpine quay.io/saschagrunert/alpine
> sudo podman push --sign-by sgrunert@suse.com quay.io/saschagrunert/alpine
Getting image source signatures
Copying blob 5216338b40a7 done
Copying config e7d92cdc71 done
Writing manifest to image destination
Signing manifest
Storing signatures
```

3. Verify that the image is not signed:
    ![signed](https://user-images.githubusercontent.com/695473/75773481-471aea80-5d4e-11ea-9763-592ea4080e26.gif)

**Describe the results you received:**

The image is not signed, which can also be verified on a `podman pull`:

```bash
> cat policy.json
{
  "default": [{ "type": "insecureAcceptAnything" }],
  "transports": {
    "docker": {
      "quay.io/saschagrunert": [
        {
          "type": "signedBy",
          "keyType": "GPGKeys",
          "keyPath": "/home/sascha/.gnupg/trustdb.gpg"
        }
      ]
    }
  }
}
> sudo podman pull --signature-policy=policy.json quay.io/saschagrunert/alpine
Trying to pull quay.io/saschagrunert/alpine...
  A signature was required, but no signature exists
Error: error pulling image "quay.io/saschagrunert/alpine": unable to pull quay.io/saschagrunert/alpine: unable to pull image: Source image rejected: A signature was required, but no signature exists
```

**Describe the results you expected:**

A signed image should be pushed to the remote, right?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
> podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.12.17
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
> sudo podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.17
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-25.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20200229"
  MemFree: 22493511680
  MemTotal: 33331335168
  OCIRuntime:
    name: runc
    package: runc-1.0.0~rc10-2.1.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc10
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: ws-sascha
  kernel: 5.5.6-1-default
  os: linux
  rootless: false
  uptime: 2h 32m 14.72s (Approximately 0.08 days)
registries:
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
> rpm -q podman
podman-1.8.0-2.2.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm on the latest openSUSE Tumbleweed.

**Comment by rhatdan** [comment]
@vrothberg @mtrmac I think this is quay.io, does not understand simple signing.  And expects things to be signed by notary?

**Comment by saschagrunert** [comment]
> @vrothberg @mtrmac I think this is quay.io, does not understand simple signing. And expects things to be signed by notary?

My follow-up question on this would be: Which registry understands GPG-based signing?

**Comment by mtrmac** [comment]
Quay uses a Notary (-like ?) signing system.

“Simple signing” (the c/image thing) does not quite _require_ registry support; the signatures are stand-alone blobs.

Anyway, the two are not interoperable at all.

AFAIK, there is only one implementation with direct support and no configuration required (just pull/push and the signatures are automatically included), the OpenShift integrated registry; for any other registry the signatures can be distributed separately using a static web server (and every client has to be configured with the location of that web server).

See https://github.com/containers/image/blob/master/docs/signature-protocols.md for the technical details, and maybe https://access.redhat.com/solutions/4039981 (subscription required) or https://medium.com/cri-o/secure-your-kubernetes-production-cluster-7ec607749583 for a tutorial (though I haven’t re-read any of the three documents right now to ensure accuracy, and at least the CRI-O blog has an indentation error in the sigstore-staging configuration).

**Comment by saschagrunert** [comment]
Thanks for the clarification @mtrmac :pray: I wrote up a little tutorial [in a GitHub gist](https://gist.github.com/saschagrunert/1d0b3cc40ce0418558d7c2a5a8fe8a1c). I'm wondering if it would be worth the effort to add it to this repo. WDYT?

**Comment by mtrmac** [comment]
The tutorial looks great. (Two nits: The default does not point at localhost:8000, and for general use mentioning the X-R-S-S extension = OpenShift integrated registry, at least in passing, might be useful.)

Adding it to https://github.com/containers/libpod/tree/master/docs/tutorials makes sense to me, but that’s up to the maintainers of the Podman repo. Or maybe a blog post? Or both 😎

**Comment by TomSweeneyRedHat** [comment]
I'd love to have the tutorial in either or both spots.   Dropping it in the tutorial section in Podman and I'd be happy to write a little blog post that links to it if you didn't want to on podman.io.

**Comment by saschagrunert** [comment]
> The tutorial looks great. (Two nits: The default does not point at localhost:8000, and for general use mentioning the X-R-S-S extension = OpenShift integrated registry, at least in passing, might be useful.)
> 
> Adding it to https://github.com/containers/libpod/tree/master/docs/tutorials makes sense to me, but that’s up to the maintainers of the Podman repo. Or maybe a blog post? Or both

Alright cool, I'll prepare the PR so we can close this for now. :pray:
