### ISSUE TITLE
Error when trying podman inspect --format

### ISSUE THREAD

**Issue by PauloLaScience** [containers/libpod#5380]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I get an error when I try to inspect Network Ports. I can get a list but not individual elements
**Steps to reproduce the issue:**

1. Start with podman run a stopped container pw2

2.  podman inspect --format='{{range $p, $conf := .NetworkSettings.Ports}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' pw2
3.

**Describe the results you received:**
Error: Template parsing error: template: image:1:59: executing "image" at <index $conf 0>: error calling index: can't index item of type ocicni.PortMapping

**Describe the results you expected:**
I should get 3000 and 8080
podman inspect --format='{{.NetworkSettings.Ports}}' pw2
[{3000 3000 tcp } {8080 8080 tcp }]

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 7718391808
  MemTotal: 16704053248
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 96f6022b37cbe12b26c9ad33a24677bec72a9cc3
      spec: 1.0.1-dev
  SwapFree: 8405381120
  SwapTotal: 8405381120
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: paulem-Latitude-5590
  kernel: 5.5.7-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 6h 10m 53.92s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - gcr.io
store:
  ConfigFile: /home/devadpa/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/devadpa/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 48
  RunRoot: /run/user/1000
  VolumePath: /home/devadpa/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical laptop Dell 5590 running Fedora 31

**Comment by mheon** [comment]
This is part of why I really dislike templating. It requires that our internal data representations match Docker, which is not a promise that I want to make.

In this case, the format for our port structures in `podman inspect` looks to differ from the format Docker uses. We can probably reformat our output to match Docker more closely. I'll try and find some time to look into it, but this is fairly low on my priorities list. Other contributors are welcome to take this one given that.

**Comment by rhatdan** [comment]
@kunalkushwaha @sujil02 Interested?

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by QiWang19** [comment]
Podman has `HostConfig.PortBindings` can match docker for the port configs, but doesn't support field `.NetworkSettings.Ports` like docker does. Do we plan to change the Ports filed under InspectNetworkSettings to a map type?
```
$ docker  inspect --format='{{range $p, $conf := .HostConfig.PortBindings}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' ctr
 8080/tcp -> 8000 
$ podman  inspect --format='{{range $p, $conf := .HostConfig.PortBindings}} {{$p}} -> {{(index $conf 0).HostPort}} {{end}}' ctr
   8080/tcp   ->   8080
```

**Comment by mheon** [comment]
We have no intention of changing database storage format for ports, but we
could do the conversion to Docker format as part of inspect (could be slow,
though, pretty ranges can easily make thousands of port structures)
