### ISSUE TITLE
podman search in private registry fails : error unauthorized: authentication required 

### ISSUE THREAD

**Issue by boogie777** [containers/libpod#5405]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.
podman search debian                                                                                                                                              
ERRO[0000] error getting search results from v2 endpoint "registry.bob.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
INDEX       NAME                                                         DESCRIPTION                                       STARS   OFFICIAL   AUTOMATED
docker.io   docker.io/library/debian                                     Debian is a Linux distribution that's compos...   3392    [OK]       
docker.io   docker.io/smartentry/debian                                  debian with smartentry                            4                  [OK]

2.

3.

**Describe the results you received:**
ERRO[0000] error getting search results from v2 endpoint "registry.bob.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
INDEX       NAME                                                         DESCRIPTION                                       STARS   OFFICIAL   AUTOMATED

**Describe the results you expected:**
retrieve  images hosted in the repository : same images that have been pull and push using 
podman pull / podman push

**Additional information you deem important (e.g. issue happens only occasionally):**
A auth file as been set which helped to push with podman 

 ~/.config/containers  cat auth.json                                                                                                                                  
{
	"auths": {
		registry.bob.io": {
			"auth": "xxxxxx="
		}
	}
}

**Output of `podman version`:**

```
podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
 boogie@boogieland  ~/.config/containers  podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 10278772736
  MemTotal: 16659619840
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1023406080
  SwapTotal: 1023406080
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: boogieland
  kernel: 5.3.0-40-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 33m 3.29s
registries:
  search:
  - paasregistry.ilius.io
  - docker.io
  - quay.io
store:
  ConfigFile: /home/boogie/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/boogie/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 4
  RunRoot: /run/user/1000/containers
  VolumePath: /home/boogie/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
sudo apt list podman
[sudo] password for boogie: 
Listing... Done
podman/unknown,now 1.8.0~7 amd64 [installed]

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for opening the issue. Does it work when doing `podman search --authfile $file ...`?

**Comment by vrothberg** [comment]
>A auth file as been set which helped to push with podman
> ~/.config/containers  cat auth.json

That's the wrong path actually. By default, Podman is using `${XDG_RUNTIME_DIR}/containers/auth.json` which usually is `run/user/$UID/containers/auth.json`.

Can you copy the file there instead and retry?

**Comment by boogie777** [comment]
Hello @vrothberg , thx for you answer.
i tried ( and removed the file from previous path)  but got the same result 

 echo ${XDG_RUNTIME_DIR}                                                                                                                 
/run/user/1000
 boogie@boogieland  /run/user/1000/containers  cat auth.json                                                                                                                           
{
	"auths": {
		"registry.bob.io": {
			"auth": "xxxx"
		}
	}
}
 boogie@boogieland  /run/user/1000/containers  podman search debian                                                                                                                    
ERRO[0000] error getting search results from v2 endpoint "paasregistry.ilius.io": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 

thx for your help.

**Comment by vrothberg** [comment]
@boogie777 the auth file only points to `registry.bob.io` which won't match `paasregistry.ilius.io`.

**Comment by boogie777** [comment]
Hello, thanks for your answer :this is a fake registry as i wanted to quickly hide the real name ..i wrote this name just for exemple ..
there's only one registry tested and the result is the one provided ... impossible to search even if the authent file has been set in the ${XDG_RUNTIME_DIR}/containers/auth.json. 
Feel free to ask me to try something else. Thx for your help.

**Comment by vrothberg** [comment]
@boogie777, can you try a `podman login` and then search? I cannot reproduce your issue and it's the first time I have seen a report it's not working; I want to figure out if the provided authfile may be incomplete.

**Comment by boogie777** [comment]
Hello @vrothberg 
as requested here's the output of login and search command.you 'll see that even if we're loggued , it 's not possible to search  for images in our private registry ..even if the image ..as been pushed previously using podman push .

Thx for your help.

 podman login -u xxx -p xxx https://xxx.xxx.xx                                                                                                     
Login Succeeded!
 boogie@boogieland  ~  podman search debian-helm                                                                                                                                                
ERRO[0000] error getting search results from v2 endpoint "xxx.xxx.xx": unable to retrieve auth token: invalid username/password: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
INDEX       NAME                                                      DESCRIPTION                                       STARS   OFFICIAL   AUTOMATED
docker.io   docker.io/crosscloudci/debian-helm-kubectl                                                                  0                  
docker.io   docker.io/iessp/debian-helm-gcloud-awscli                                                                   0                  
docker.io   docker.io/iidlx/debian-helm-kubectl                                                                         0                  
quay.io     quay.io/hellofresh/concourse-helm-resource                                                                  0                  
..
....

**Comment by miquecg** [comment]
Something is definitely going on with `podman login`:
```
➜ podman login docker.io
Username: user
Password:
Login Succeeded!

➜ l .config/containers
total 12K
drwxr-xr-x 2 devel devel 4.0K Apr  7 11:47 .
drwxr-xr-x 7 devel devel 4.0K Mar 26 16:57 ..
-rw-r--r-- 1 devel devel 1.3K Mar 16 11:22 storage.conf

➜ l /run/user/1000/containers
total 4.0K
drwx------ 6 devel devel 140 Apr  7 11:48 .
drwx------ 7 devel devel 180 Apr  7 11:23 ..
-rwxr-xr-x 1 devel devel  65 Apr  7 11:48 auth.json
drwx------ 2 devel devel  40 Apr  7 11:22 overlay
drwx------ 2 devel devel  40 Apr  7 11:22 overlay-containers
drwx------ 2 devel devel  60 Apr  7 11:22 overlay-layers
drwx------ 2 devel devel  40 Apr  7 11:22 overlay-locks

➜ cat /run/user/1000/containers/auth.json
{
        "auths": {
                "docker.io": {
                        "auth": "xxxxxxxxxxxxxxx"
                }
        }
}%

➜ podman login --get-login docker.io
Error: not logged into docker.io
```

**`podman version`**
```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/amd64
```

**`podman info --debug`**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.14, commit: '
  Distribution:
    distribution: debian
    version: "10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 236326912
  MemTotal: 1021259776
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  SwapFree: 1060106240
  SwapTotal: 1060106240
  arch: amd64
  cpus: 3
  eventlogger: journald
  hostname: debian
  kernel: 4.19.0-8-amd64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 46m 35.27s
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/devel/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  GraphRoot: /home/devel/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/devel/.local/share/containers/storage/volumes
```

**`apt list podman`**
```
➜ apt list podman
Listing... Done
podman/unknown,now 1.8.2~143 amd64 [installed]
podman/unknown 1.8.2~143 arm64
podman/unknown 1.8.2~143 armhf
podman/unknown 1.8.2~143 ppc64el
```

Was ever before the username inside the `auth.json`?

Hope this helps!

**Comment by vrothberg** [comment]
Thanks for providing the details!

For the sake of completeness, can you try `$ podman login --authfile /run/user/1000/containers/auth.json --get-login docker.io`? I cannot reproduce on my machine.

@mtrmac, ideas what it might be?

**Comment by mtrmac** [comment]
I really wouldn’t expect `--get-login` to be unable to find just-updated credentials.

`podman --log-level=debug …` might reveal which files the code is reading in the various commands (but, sadly, probably not which files it is writing to).

**Comment by miquecg** [comment]
This is super weird... Now it works! I don't know what could happen.

The only thing I've seen different is that `auth` value is now considerably longer compared to the previous one which failed (despite showing up login succeeded message).

**Comment by vrothberg** [comment]
I am going to close the issue as we don't have a reproducer. Feel free to reopen at any time.

**Comment by cybernet** [comment]
i'm having similar issues with login for docker.io

```
[root@webd ~]# podman login docker.io
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to docker.io
[root@webd ~]# podman run -dt -p 8080:8080/tcp docker.io/pi-hole/pi-hole
Trying to pull docker.io/pi-hole/pi-hole...
  denied: requested access to the resource is denied
Error: unable to pull docker.io/pi-hole/pi-hole: unable to pull image: Error initializing source docker://pi-hole/pi-hole:latest: Error reading manifest latest in docker.io/pi-hole/pi-hole: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
@cybernet  Could you try --log-level to check which authfile the credential is returning from? Which Podman verison you are using?
```
# podman --log-level debug login docker.io
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Returning credentials from /run/containers/0/auth.json 
Authenticating with existing credentials...
```

**Comment by cybernet** [comment]
> @cybernet Could you try --log-level to check which authfile the credential is returning from? Which Podman verison you are using?
> 
> ```
> # podman --log-level debug login docker.io
> INFO[0000] Setting parallel job count to 13             
> DEBU[0000] Returning credentials from /run/containers/0/auth.json 
> Authenticating with existing credentials...
> ```

[root@cent0 ~]# podman --log-level debug login docker.io
DEBU[0000] Returning credentials from /run/user/0/containers/auth.json 
Authenticating with existing credentials...
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io 
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://auth.docker.io/token?account=cybernet2u&service=registry.docker.io 
DEBU[0000] GET https://registry-1.docker.io/v2/         
Existing credentials are valid. Already logged in to docker.io

**Comment by QiWang19** [comment]
@cybernet Which podman version you are using? This seems the same issues as https://bugzilla.redhat.com/show_bug.cgi?id=1867495

**Comment by cybernet** [comment]
> @cybernet Which podman version you are using? This seems the same issues as https://bugzilla.redhat.com/show_bug.cgi?id=1867495

1.6.4 LTS
CentOS 8

**Comment by cybernet** [comment]
apparently it was fixed ...

Since the problem described in this bug report should be
resolved in a recent advisory, it has been closed with a
resolution of ERRATA.

For information on the advisory (OpenShift Container Platform 4.3.38 bug fix update), and where to find the updated
files, follow the link below.

If the solution does not work for you, open a new bug report.

https://access.redhat.com/errata/RHBA-2020:3609
