### ISSUE TITLE
libpod and varlink version (ctx context)

### ISSUE THREAD

**Issue by bruno-anjos** [containers/libpod#5406]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I generate the Go Bindings for the Podman Varlink API, it uses methods from the `varlink.Connection` yet it does not provide the first argument that is required, which should be `ctx  context`.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 4492791808
  MemTotal: 7233531904
  OCIRuntime:
    name: crun
    package: crun-0.12.2.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.2.1
      commit: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 7377776640
  SwapTotal: 7377776640
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.7-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 42h 35m 3.33s (Approximately 1.75 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/b.anjos/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/b.anjos/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000/containers
  VolumePath: /home/b.anjos/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Installed Packages
Name         : podman
Epoch        : 2
Version      : 1.8.0
Release      : 2.fc31
Architecture : x86_64
Size         : 58 M
Source       : podman-1.8.0-2.fc31.src.rpm
Repository   : @System
From repo    : updates
Summary      : Manage Pods, Containers and Container Images
URL          : https://podman.io/
License      : ASL 2.0
Description  : podman (Pod Manager) is a fully featured container engine that is a simple
             : daemonless tool.  podman provides a Docker-CLI comparable command line that
             : eases the transition from other container engines and allows the management of
             : pods, containers and images.  Simply put: alias docker=podman.
             : Most podman commands can be run as a regular user, without requiring
             : additional privileges.
             : 
             : podman uses Buildah(1) internally to create container images.
             : Both tools share image (not container) storage, hence each can use or
             : manipulate images (but not containers) created by the other.
             : 
             : Manage Pods, Containers and Container Images
             : libpod Simple management tool for pods, containers and images
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Fedora Server 31

**Comment by rhatdan** [comment]
Is there a reason you want to do this with Varlink, versus APIV2?

**Comment by baude** [comment]
@rhatdan dont assign this to me! you already stated you didn't want this fixed when Jhon asked you about it.  Are you changing your mind?  Harald changed the the varlink api which broke us

**Comment by rhatdan** [comment]
Don't recall.  Anyways just looking for your comment.
@bruno-anjos We are deprecating varlink support.  We would love to work with you on APIV2 support.

**Comment by bruno-anjos** [comment]
There is no reason for me to use the old API versus the new one. I just read the New API announcement in the blog, and I thought the varlink API was still the one fully implemented and working, therefore the one I should be using.

Is the new APIV2 already in a usable state? I would also be using Go, so the bindings mentioned in the post would also be really useful. Is there anything you can point me to to follow the development state of the new APIV2 (besides the blog and GitHub)?

Side note I also thought that the whole varlink API was a bit confusing, so I believe that the change to the new API will be well received by the community.

I would gladly help you guys testing APIV2. Just to give some context I would be using the Podman API mainly to do container migration for my master thesis.

**Comment by rhatdan** [comment]
Well it is under heavy development, but for most use cases it is probably ready.  @baude could give you the most up2date information, and the documentation on it is pretty good.

Any help you can give us on testing would be greatly appreciated.
