### ISSUE TITLE
cannot access /dev/fd/1 from UID!=0

### ISSUE THREAD

**Issue by thoraxe** [containers/libpod#5416]
/kind bug

**Description**
When trying to run supervisord inside a container with podman and UID!=0 you get:
IOError: [Errno 13] Permission denied: '/dev/fd/1'

**Steps to reproduce the issue:**
1. podman run image

**Describe the results you received:**
https://gist.github.com/thoraxe/0139d451ba627b488683a83204ddf6e7

**Describe the results you expected:**
Image runs

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/Dockerfile

This used to work in previous versions of Podman.

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 934690816
  MemTotal: 32847253504
  OCIRuntime:
    name: crun
    package: crun-0.12.2.1-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.12.2.1
      commit: cd7cea7114db5f6aa35fbb69fa307c19c2728a31
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 14319087616
  SwapTotal: 16471027712
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: t490s-festive-local
  kernel: 5.3.18-300.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 41h 33m 25.56s (Approximately 1.71 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/thoraxe/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/thoraxe/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 17
  RunRoot: /run/user/1000/containers
  VolumePath: /home/thoraxe/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.0-2.fc31.x86_64```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
T460 
Linux t490s-festive-local 5.3.18-300.fc31.x86_64 #1 SMP Wed Dec 18 20:13:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mheon** [comment]
@rhatdan @giuseppe @vrothberg I feel like this happened before, but I can't seem to find details. Any ideas?

**Comment by thoraxe** [comment]
I was previously using F28 and it worked there, so whatever podman version was present in F28 as of a few months ago it worked. You can use quay.io/openshiftroadshow/lab-ocp-ocs:ocp4-prod to test with

**Comment by st1971** [comment]
this may have something to do with no tty being allocated...
`podman run --rm quay.io/openshiftroadshow/lab-ocp-ocs:ocp4-prod`
fails
`podman run --rm -t quay.io/openshiftroadshow/lab-ocp-ocs:ocp4-prod`
works (well for me)

**Comment by st1971** [comment]
had a bit more of a poke about on this, possibly a crun problem, think it's creating fifos with incorrect ownership.
with crun:
`podman run --rm --user 1000:1000 fedora:31 /bin/bash -c 'ls -lah /dev/fd/1; while true; do echo "test" > /dev/fd/1; sleep 2; done;'`
fails with permission denied, if i use lsof on the host to find the underlying fifo that's being used that fifo is owned uid 1000, the symlink to it is owned by 100999
with runc:
`podman run --rm --user 1000:1000 fedora:31 /bin/bash -c 'ls -lah /dev/fd/1; while true; do echo "test" > /dev/fd/1; sleep 2; done;'`
works without issue, if i use lsof on the host to find the underlying fifo that's being used that fifo is owned uid 100999 as is the symlink to it.

so guessing that somewhere in the crun code ownership is not being set correctly after the fifo is created

**Comment by giuseppe** [comment]
that should be fixed with conmon 2.0.11: https://github.com/containers/conmon/pull/112

**Comment by rhatdan** [comment]
@giuseppe @jnovy @lsm5 Looks like conmon-.2.0.11 is built for F31, but not in updates testing?

**Comment by giuseppe** [comment]
we have an updated conmon for Fedora 31 now.  Closing the issue
