### ISSUE TITLE
Missing podman 1.8.0 conmon binaries on ubuntu 18 system

### ISSUE THREAD

**Issue by mritd** [containers/libpod#5422]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

missing podman 1.8.0 conmon binaries on ubuntu 18 system

**Steps to reproduce the issue:**

1. Install podman according to [official documentation](https://podman.io/getting-started/installation)

2. Execute `podman ps` command

3. An error message appears: `Error: error creating libpod runtime: could not find a working conmon binary`

**Describe the results you received:**

podman ps command fails to run

**Describe the results you expected:**

podman ps command works

**Additional information you deem important (e.g. issue happens only occasionally):**

After searching with dpkg command, it seems that the conmon package does not contain any binary files

![image](https://user-images.githubusercontent.com/13043245/76159967-d6663a80-6160-11ea-8ec1-422d78e56526.png)

**Output of `podman version`:**

```
ubuntu ➜  ~ podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

Cannot run command

```
Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
ubuntu ➜  ~ apt list podman
Listing... Done
podman/unknown,now 1.8.0~7 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 18

**Comment by DsDeesu** [comment]
Same here, Ubuntu 18.04. Installed with instructions from https://podman.io/getting-started/installation.

Error: could not get runtime: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument

podman version 1.8.0                                                                                                                               
WARN[0000] unable to find /home/user/.config/containers/registries.conf. some podman (image shortnames) commands may be limited

**Comment by ReveredMachine** [comment]
A previous provided build of 1.8.0 for ubuntu 18.04 was working properly. Is there anyhow a way to get a previous build of the version 1.8.0 via apt-get ?

**Comment by mritd** [comment]
@ReveredMachine You can make it work by manually compiling conmon:

```sh
# install build deps
apt install build-essential libc6-dev libglib2.0-dev pkg-config -y
# clone source
git clone http://github.com/containers/conmon
# install
cd conmon && make install PREFIX=/usr
```

But this is not the best solution ... I still can't believe the lack of binary files in deb (theoretically, it should pass the test before releasing the release version).

**Comment by mritd** [comment]
I even look forward to officially adding a `make deb` option to the Makefile so that we can build deb packages on our own; however, most open source projects are built by a dedicated repository, and the repository contains a more professional package build configuration (I prefer fpm to package, because I don't want to learn build specifications for specific packages... 😂)

**Comment by mritd** [comment]
> A previous provided build of 1.8.0 for ubuntu 18.04 was working properly. Is there anyhow a way to get a previous build of the version 1.8.0 via apt-get ?

Similar to the kubeadm official documentation, it is best practice to use the `apt-mark hold` command to maintain the version after the specific version is installed, so that we don't have to worry about problems caused by accidental upgrades 😂

**Comment by johscheuer** [comment]
Related: https://github.com/containers/conmon/issues/126 (or probably the issue)

**Comment by Diaoul** [comment]
So, I wanted to try podman for the first time and encountered this bug. This is rather embarrassing :laughing:

**Comment by hunleyd** [comment]
Ran into this after upgrading to conmon-2.0.11-2 from conmon-2.0.10~2

**Comment by ReveredMachine** [comment]
@mritd Thank you for the hint regarding _apt-mark hold_ with this I can prevent an upgrade from podman which I have already installed on a machine. But unfortunately this will not help if I have to install it on another machine too.
It seems to be that it also will not work if I install conmon manually (see comment from @hunleyd) or am I wrong ?

**Comment by TomSweeneyRedHat** [comment]
@lsm5?

**Comment by mritd** [comment]
@ReveredMachine 

> @ReveredMachine You can make it work by manually compiling conmon:
> 
> ```shell
> # install build deps
> apt install build-essential libc6-dev libglib2.0-dev pkg-config -y
> # clone source
> git clone http://github.com/containers/conmon
> # install
> cd conmon && make install PREFIX=/usr
> ```
> 
> But this is not the best solution ... I still can't believe the lack of binary files in deb (theoretically, it should pass the test before releasing the release version).

@ReveredMachine I tested by manually compiling conmon that works.

**Comment by ReveredMachine** [comment]
@mritd I also tested it, and it worked. Thus for a development system it can be done as a feasible workaround.
But for none development systems the development packages (build-essential libc6-dev libglib2.0-dev) will usually not be instzalled, so there this kind of workaround is not a good solution.

**Comment by lsm5** [comment]
sorry about that everyone. Fixes building on testing and stable repos: https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/conmon and https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/conmon . Should be installable in a bit.

**Comment by mritd** [comment]
@lsm5 Thanks for fixing this, it has worked after testing. Should I close the issue or wait for feedback from others?

**Comment by rhatdan** [comment]
I closed issue, reopen if this was a mistake.
