### ISSUE TITLE
Dangling file in /var/lib/cni/networks/podman after hard restart

### ISSUE THREAD

**Issue by Schrottfresse** [containers/libpod#5433]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

My server restarts hard occasionally (as in I have a brownout because my fuse triggers). When this happens I have the same dangling files reported [here](https://github.com/containers/libpod/issues/4526) and [here](https://github.com/containers/libpod/issues/3759). Podman has no possibility to clean up.

**Steps to reproduce the issue:**

1. Hard restart server.

**Describe the results you received:**

Dangling files still in `/var/lib/cni/networks/podman`.

**Describe the results you expected:**

Cleaned up filesystem, no dangling files in `/var/lib/cni/networks/podman`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 32140668928
  MemTotal: 33369112576
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 16835932160
  SwapTotal: 16835932160
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: carter
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 1h 35m 6.12s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-1.6.4-2.module_el8.1.0+272+3e64ee36.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical server

**Comment by mheon** [comment]
I'll take this one.

**Comment by mheon** [comment]
@Schrottfresse Any chance you can test #5434 and see if this resolves it?

**Comment by Schrottfresse** [comment]
@mheon I will try to do it the next days.

**Comment by wingzero0** [comment]
I have the same issue on the centos 8, podman version 1.9.1.

Do I need to apply any setting to activate the #5434  ?

Thank you

**Output of `podman version` :**
```
# podman version
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
# podman info --debug
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.12.12
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.6-1.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 2721f230f94894671f141762bd0d1af2fb263239'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: dmzAppServer
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-147.8.1.el8_1.x86_64
  memFree: 1215787008
  memTotal: 3963326464
  ociRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4265603072
  swapTotal: 4265603072
  uptime: 39m 44.73s
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
  - localhost:5000
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 10
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
```

**Comment by wingzero0** [comment]
For more detail, there are 4 running containers with dedicated IP settings (10.88.0.2, 10.88.0.3, 10.88.0.4, 10.88.0.5) in my centos 8.

After reboots (I use `reboot` command), there are usually 1 or 2 IP exists at `/var/lib/cni/networks/podman` 

> I have the same issue on the centos 8, podman version 1.9.1.
> 
> Do I need to apply any setting to activate the #5434 ?
> 
> Thank you
> 
> **Output of `podman version` :**
> 
> ```
> # podman version
> Version:            1.9.1
> RemoteAPI Version:  1
> Go Version:         go1.12.12
> OS/Arch:            linux/amd64
> ```
> 
> **Output of `podman info --debug`:**
> 
> ```
> # podman info --debug
> debug:
>   compiler: gc
>   gitCommit: ""
>   goVersion: go1.12.12
>   podmanVersion: 1.9.1
> host:
>   arch: amd64
>   buildahVersion: 1.14.8
>   cgroupVersion: v1
>   conmon:
>     package: conmon-2.0.6-1.module_el8.1.0+298+41f9343a.x86_64
>     path: /usr/bin/conmon
>     version: 'conmon version 2.0.6, commit: 2721f230f94894671f141762bd0d1af2fb263239'
>   cpus: 8
>   distribution:
>     distribution: '"centos"'
>     version: "8"
>   eventLogger: file
>   hostname: dmzAppServer
>   idMappings:
>     gidmap: null
>     uidmap: null
>   kernel: 4.18.0-147.8.1.el8_1.x86_64
>   memFree: 1215787008
>   memTotal: 3963326464
>   ociRuntime:
>     name: runc
>     package: runc-1.0.0-64.rc9.module_el8.1.0+298+41f9343a.x86_64
>     path: /usr/bin/runc
>     version: 'runc version spec: 1.0.1-dev'
>   os: linux
>   rootless: false
>   slirp4netns:
>     executable: ""
>     package: ""
>     version: ""
>   swapFree: 4265603072
>   swapTotal: 4265603072
>   uptime: 39m 44.73s
> registries:
>   localhost:5000:
>     Blocked: false
>     Insecure: true
>     Location: localhost:5000
>     MirrorByDigestOnly: false
>     Mirrors: []
>     Prefix: localhost:5000
>   search:
>   - registry.access.redhat.com
>   - registry.fedoraproject.org
>   - registry.centos.org
>   - docker.io
>   - localhost:5000
> store:
>   configFile: /etc/containers/storage.conf
>   containerStore:
>     number: 5
>     paused: 0
>     running: 5
>     stopped: 0
>   graphDriverName: overlay
>   graphOptions: {}
>   graphRoot: /var/lib/containers/storage
>   graphStatus:
>     Backing Filesystem: xfs
>     Native Overlay Diff: "true"
>     Supports d_type: "true"
>     Using metacopy: "false"
>   imageStore:
>     number: 10
>   runRoot: /var/run/containers/storage
>   volumePath: /var/lib/containers/storage/volumes
> ```
> 
> **Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
> 
> ```
> # rpm -q podman
> podman-1.9.1-1.1.el8.x86_64
> ```
> 
> **Additional environment details (AWS, VirtualBox, physical, etc.):**
> Vsphere VM

**Comment by mheon** [comment]
Can you provide the names of the files? Do they prevent you from starting the containers which use those IPs?
