### ISSUE TITLE
podman container runlabel documentation references nonexistent --set flag

### ISSUE THREAD

**Issue by coandco** [containers/libpod#5438]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The podman documentation at `docs/source/markdown/podman-container-runlabel.1.md` describes a `--set NAME=VALUE` option which (as far as I can tell from looking through the git history) has never existed in the `podman container runlabel` command.  As such, it seems like the feature should either be added or the documentation updated to remove references to the missing option.

**Steps to reproduce the issue:**

1. Execute `man podman-container-runlabel` and note the following section:

```
       --set=NAME=VALUE

       Set name  value
```
2. Attempt to use the `--set` option and note that it doesn't work

```
$ podman container runlabel --display --set FOO=BAR run exampleimage
Error: unknown flag: --set
```

**Describe the results you received:**
No `--set` option available, despite documentation suggesting as much in `docs/source/markdown/podman-container-runlabel.1.md`.

**Describe the results you expected:**
Either for the `--set` option to work or the documentation to reflect its absence.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: debian
    version: "10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  MemFree: 2856894464
  MemTotal: 33413627904
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 34025750528
  SwapTotal: 34040967168
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: search2
  kernel: 4.19.0-8-amd64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'   
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 90h 20m 23.08s (Approximately 3.75 days) 
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/elastalert/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27   
  GraphRoot: /home/elastalert/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 122
  RunRoot: /var/tmp/run-1003/containers
  VolumePath: /home/elastalert/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 1.8.0~7 amd64 [installed]
podman/unknown 1.8.0~7 arm64
podman/unknown 1.8.0~7 armhf
podman/unknown 1.8.0~7 ppc64el
```
(I have the Kubic project .debs for Debian 10 installed, as per https://podman.io/getting-started/installation.html)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running on a physical box.

**Comment by coandco** [comment]
I've created a pull request to remove `--set` from the documentation at #5437.

**Comment by Akasurde** [comment]
@mheon @rhatdan Can we close this since the #5437 is merged? Thanks.
