### ISSUE TITLE
Starting a systemd container with USER set to non-root fails to start systemd ungracefully

### ISSUE THREAD

**Issue by Markolie** [containers/libpod#5442]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Starting a systemd container by setting the CMD to "/sbin/init" when the USER is set to non-root causes systemd to fail to start. The container still works, however.

This is sort of expected behavior, but I don't think it can hurt to handle this a bit more gracefully so the user is more clearly informed of the issue.

**Steps to reproduce the issue:**

1. Create a Dockerfile:

```
FROM registry.access.redhat.com/ubi8/ubi:8.1-397

RUN adduser example

USER example

CMD ["/sbin/init"]
```

2. Run `sudo podman build -t example . && sudo podman run --name example -it example:latest`

3. Check if the following error occurs:

```
Set hostname to <7f620aebdfcc>.
Initializing machine ID from random generator.
Cannot write /run/machine-id: Permission denied
Failed to write /run/systemd/container, ignoring: No such file or directory
Assertion 'getuid() == 0' failed at ../src/core/main.c:1176, function bump_rlimit_memlock(). Aborting.
Caught <ABRT>, dumped core as pid 6.
Freezing execution.
```

4. Check if you can still exec into the container: `sudo podman exec -it example /bin/bash`

**Describe the results you received:**

An error occurred and systemd did not start. The container still started.

**Describe the results you expected:**

I can think of four options:
1) In a systemd container, if the USER is non-root, Podman should make sure systemd is still started as root.
2) A warning message should be shown to the user that systemd will not work without starting the container as ROOT.
3) Show an error message to the user and prevent the container from starting at all.
4) Do not attempt to start systemd if the CMD is /sbin/init but the USER is not root.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 6ffbb2ec70dbe5ba56e4bfde946fb04f19dd8bbf'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 172929024
  MemTotal: 3961724928
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2138738688
  SwapTotal: 2147479552
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: vb-ct-t01
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: false
  uptime: 1h 22m 5.43s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 25
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 117
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by rhatdan** [comment]
I don't see a role for the container engine here.  We could catch that you are running /sbin/init and say we refuse to run this as non root, but then someone might find an init program that can be run as non root.

**Comment by Markolie** [comment]
Ah, my bad @rhatdan. I figured I'd report it, but if it's not something the engine should handle feel free to close this.

**Comment by rhatdan** [comment]
Thanks, but I don't think we can do anything about it.
