### ISSUE TITLE
podman warnings while rootless, falling back to --cgroup-manager=cgroupfs

### ISSUE THREAD

**Issue by aleks-mariusz** [containers/libpod#5443]
/kind bug

**Description**

possibly related to (maybe even re-opening) #5314 .. when doing any podman command as a non-root user, i am also get repeated warnings:

this is _despite_ having not only `loginctl enable-linger`'d already, as well as manually set the environment variables (as per [the workaround mentioned in the related issue](https://github.com/containers/libpod/issues/5314#issue-570007594), which has been closed but i am still experiencing it, compiled from master as of last night.. 

**Steps to reproduce the issue:**

1. enable linger

2. set those XDG/DBUS env vars

3. run a podman rootless command

**Describe the results you received:**

<details><summary>warnings repeatedly for each command</summary>

```
pi@raspberrypi:~$ podman images
WARN[0001] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0001] For using systemd, you may need to login using an user session 
WARN[0001] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0001] Falling back to --cgroup-manager=cgroupfs    
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
REPOSITORY                         TAG                   IMAGE ID       CREATED       SIZE
docker.io/library/alpine           latest                8093515ca679   7 weeks ago   5.08 MB
```

</details>

<details><summary>another example, launching a container</summary>

```
pi@raspberrypi:~$ podman run -p 8080:80 -d --name octoprint14 --device /dev/ttyUSB0:/dev/ttyUSB0 -v /iscsi/octoprint-data-1.4:/data docker.io/aleksmariusz/octoprint:1.4.0-202003062053
WARN[0001] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0001] For using systemd, you may need to login using an user session 
WARN[0001] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0001] Falling back to --cgroup-manager=cgroupfs    
4cf0fa4d586627cd44913fce7534a9a5321af7a3f3aa486a1603bb5714cea389
```

</details>

**Describe the results you expected:**

no warnings would be nice :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

<details><summary>Output of `podman version`:</summary>

```
pi@raspberrypi:~$ podman version
WARN[0001] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0001] For using systemd, you may need to login using an user session 
WARN[0001] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0001] Falling back to --cgroup-manager=cgroupfs    
Version:            1.8.1-dev
RemoteAPI Version:  1
Go Version:         go1.13.8
Git Commit:         3d48940927b1133e2bfd1c3accba84345cc56ee6
Built:              Tue Mar 10 00:23:11 2020
OS/Arch:            linux/arm
```

</details>

<details><summary>Output of `podman info --debug`:</summary>

```
pi@raspberrypi:~$ podman info --debug
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
debug:
  compiler: gc
  git commit: 3d48940927b1133e2bfd1c3accba84345cc56ee6
  go version: go1.13.8
  podman version: 1.8.1-dev
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.11-dev, commit: 86aa80b908d7532ab9b6edd6f4f27ba4bf6ba17b'
  Distribution:
    distribution: raspbian
    version: "9"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 362144
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 362144
      size: 65536
  MemFree: 36495360
  MemTotal: 237723648
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: arm
  cpus: 1
  eventlogger: file
  hostname: raspberrypi
  kernel: 4.19.66+
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.3+dev
      commit: unknown
  uptime: 34m 36.85s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /home/pi/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/pi/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 3
  RunRoot: /run/user/1000/containers
  VolumePath: /home/pi/.local/share/containers/storage/volumes
```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`)**

not applicable, compiled from master commit 3d48940927b1133e2bfd1c3accba84345cc56ee6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

this is running a (cross)-compiled podman, rootless, on a Raspberry Pi Model B (the linux flavor is Raspbian, based on Debian 9).

**Comment by mheon** [comment]
From the fact that you have enabled linger already, I assume that your system is systemd-based?

@giuseppe PTAL

**Comment by aleks-mariusz** [comment]
> From the fact that you have enabled linger already, I assume that your system is systemd-based?

yes, version info (in case it helps):

```
pi@raspberrypi:~$ systemctl --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by aleks-mariusz** [comment]
another strange behaviour is even after the program runs/exits, i still see it in my proceseses.. 

```
pi@raspberrypi:~$ ps auxwww|grep podman
pi        4374  0.0  0.8   4360  1972 pts/0    S+   23:51   0:00 grep --color=auto podman
pi@raspberrypi:~$ podman ps -a
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
CONTAINER ID  IMAGE                                                COMMAND               CREATED       STATUS                    PORTS                 NAMES
4cf0fa4d5866  docker.io/aleksmariusz/octoprint:1.4.0-202003062053  /usr/local/bin/py...  11 hours ago  Exited (0) 4 minutes ago  0.0.0.0:8080->80/tcp  octoprint14
pi@raspberrypi:~$ ps auxwww|grep podman
pi        4387  0.2  0.6  39452  1520 ?        S    23:51   0:00 podman
pi        4401  0.0  0.8   4360  2032 pts/0    S+   23:51   0:00 grep --color=auto podman
```

**Comment by mheon** [comment]
We expect one process to stay alive (the pause process - it keeps our user namespace active). If there's any more than one with no containers running, I'd be concerned.

**Comment by aleks-mariusz** [comment]
so to me, this looks like exactly that, a 'no containers running' situation, where i end up having a podman running after i simply performed a query command:

```
pi@raspberrypi:~$ ps auxwww|grep -i '[p]odman'
pi@raspberrypi:~$ podman ps -a
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
pi@raspberrypi:~$ ps auxwww|grep -i '[p]odman'
pi        9897  0.5  0.7  39452  1640 ?        S    19:05   0:00 podman
pi@raspberrypi:~$ 
```

**Comment by mheon** [comment]
There's still just one process (the pause process) - seems normal

**Comment by aleks-mariusz** [comment]
ahh i misread previously and missed the part about 'more than one'.. apologies..

any ideas about all the warnings (original reason for this issue) ?

**Comment by rhatdan** [comment]
The error usually means that you are running a container on a system without systemd or rootless without a dbus session? 

Did you use `su` from root to become a user?

**Comment by aleks-mariusz** [comment]
system definitely has systemd, how do i check if there's a dbus session ? negative on the if i su'd from root

**Comment by rhatdan** [comment]
The code is checking for environment variable DBUS_SESSION_BUS_ADDRESS

```
	session := os.Getenv("DBUS_SESSION_BUS_ADDRESS")
	hasSession := session != ""
	if hasSession && strings.HasPrefix(session, "unix:path=") {
		_, err := os.Stat(strings.TrimPrefix(session, "unix:path="))
		hasSession = err == nil
	}
```

**Comment by the-antz** [comment]
I have `cgroup_manager = "cgroupfs"`in `/etc/containers/libpod.conf (I'm not on a systemd distro) but still get this warning. Shouldn't this suppress the warning?

**Comment by mheon** [comment]
This could be overridden in `~/.config/containers/libpod.conf` if that file exists

**Comment by the-antz** [comment]
> This could be overridden in `~/.config/containers/libpod.conf` if that file exists

Thanks for the hint but I don't have that file.

Setting the option as command line argument doesn't suppress it neither.

**Comment by aleks-mariusz** [comment]
I guess i'm just going to have to  work-around the issue for the time being i guess until it can be sorted.. 

mine is: `alias podman='podman 2>/dev/null'`

**Comment by mheon** [comment]
@aleks-mariusz Can you see if the DBUS_SESSION_BUS_ADDRESS environment variable is set?

@the-antz Can you provide your `/etc/containers/libpod.conf`? I'll take a look on Monday and see where we're calling this code, this code being called if cgroup manager is not set seems like a bug

**Comment by djerius** [comment]
I also see this on rootless podman 1.8.1.  In addition to ignoring the `--cgroup-manager` command line option, it also ignores the entry in `libpod.conf`:

```
$ podman --cgroup-manager=cgroupfs info
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
```
```
$ cat ~/.config/containers/libpod.conf
cgroup_manager = "cgroupfs"

$ podman --config ~/.config/containers/libpod.conf
WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
```

**Comment by the-antz** [comment]
@mheon thx!

[libpod.conf.txt](https://github.com/containers/libpod/files/4333063/libpod.conf.txt)
(had to rename the file to make github happy)

**Comment by mrowa** [comment]
I have the same issue on KVM guest based on fresh ubuntu 18.04 cloud image. It's headless VM. I installed podman through the method shown on podman.io for ubuntu - using Kubic repository.

OS: ubuntu based on cloud image "bionic-server-cloudimg-amd64.img" from 9th of March.
Podman version installed: 1.8.1.

**Comment by giuseppe** [comment]
I think there are two different issues here:

If you are running on a systemd service, then the `DBUS_SESSION_BUS_ADDRESS` is expected to point to the user session dbus socket (e.g. `unix:path=/run/user/1000/bus`).

The second one, is that we are checking the cgroup manager in containers/common when the default configuration is created.  We shouldn't do that because the setting can be overriden with `--cgroup-manager`.  Also it seems to be done before we set the verbosity for the logger.  @rhatdan are you fine with dropping the check in containers/common and do it only in libpod?  Otherwise, what is the correct way to honor overrides from the CLI?

**Comment by aleks-mariusz** [comment]
> If you are running on a systemd service, then the `DBUS_SESSION_BUS_ADDRESS` is expected to point to the user session dbus socket (e.g. `unix:path=/run/user/1000/bus`).

Well firstly, DBUS_SESSION_BUS_ADDRESS is not set automatically when i log in (is it supposed to be?), Secondly, i end up manually setting it to that value, but related to that, i don't actually see any file or dir named `dbus` under my /run/user/1000.. not sure what's supposed to create that.. i _have_ enabled linger, and from the output of `loginctl list-sessions` i see:

```
SESSION  UID USER SEAT TTY  
     c2 1000 pi        pts/0

1 sessions listed.```

**Comment by giuseppe** [comment]
yes it should be set automatically (unless you login through `su`).

What do you see with `systemctl --user status dbus.socket`?

**Comment by aleks-mariusz** [comment]
```
pi@raspberrypi:~$ systemctl --user status dbus.socket
* dbus.socket - D-Bus Message Bus Socket
   Loaded: loaded (/etc/systemd/user/dbus.socket; disabled; vendor preset: enabled)
   Active: inactive (dead)
   Listen: /run/user/1000/dbus/user_bus_socket (Stream)
```

**Comment by giuseppe** [comment]
> pi@raspberrypi:~$ systemctl --user status dbus.socket
> Unit dbus.socket could not be found.

This seems to be the issue as rootless podman, if systemd is used, needs a session dbus and a valid `DBUS_SESSION_BUS_ADDRESS`

**Comment by aleks-mariusz** [comment]
Ok, after quite a bit of researching and trying different things, i've found what the missing ingredient was:

The `dbus-user-session` package was missing (this is Raspbian, a Debian flavor, i'm on version 10 aka _buster_).

After installing this, the command will work properly (after doing `systemctl --user enable --now dbus.socket`), resulting in:

```
pi@raspberrypi:~$ systemctl --user status dbus.socket
● dbus.socket - D-Bus User Message Bus Socket
   Loaded: loaded (/usr/lib/systemd/user/dbus.socket; static; vendor preset: enabled)
   Active: active (running) since Mon 2020-03-16 17:16:25 GMT; 5min ago
   Listen: /run/user/1000/bus (Stream)
  Process: 457 ExecStartPost=/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus (code=exited, status=0/SUCCESS)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus.socket

Mar 16 17:16:25 raspberrypi systemd[326]: Starting D-Bus User Message Bus Socket.
Mar 16 17:16:25 raspberrypi systemd[326]: Listening on D-Bus User Message Bus Socket.
```

Also now when logging in the DBUS_SESSION_BUS_ADDRESS env var _is_ set properly automatically, and podman also works without warnings.

What action-items should we take away from this? maybe mention this package is a requirement for rootless podman (at least on Debian, possibly Ubuntu, but not sure what the equivalent is on CentOS).

**Comment by giuseppe** [comment]
> $ podman --cgroup-manager=cgroupfs info
> WARN[0000] The cgroups manager is set to systemd but there is no systemd user session available 
> WARN[0000] For using systemd, you may need to login using an user session 
> WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
> WARN[0000] Falling back to --cgroup-manager=cgroupfs

could you try to also add `events_logger =	"file"` to the configuration file?

**Comment by araven** [comment]
This command works for me 
````bash:
systemctl --user start dbus.socket
````

**Comment by acacio** [comment]
Just to confirm, installing `dbus-user-session` in my blank Debian Bullseye system, fixed all issues.

We should add this to the Installation info for Debian.

**Comment by giuseppe** [comment]
it should be added as a dependency, can you please file an issue for the Debian package?

**Comment by eighthave** [comment]
Here's a related bug in the Debian BTS https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013344

**Comment by shanewa** [comment]
This works to me: [Fedora-33 HOST / Fedora-33 LXC GUEST :: WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available](https://discuss.linuxcontainers.org/t/fedora-33-host-fedora-33-lxc-guest-warn-0000-the-cgroupv2-manager-is-set-to-systemd-but-there-is-no-systemd-user-session-available/10759)

Just as the following to this file, creating it if necessary:
${HOME}/.config/containers/containers.conf:

```
[engine]
events_logger = "file"
cgroup_manager = "cgroupfs"
```

**Comment by wojnarw** [comment]
> This works to me: [Fedora-33 HOST / Fedora-33 LXC GUEST :: WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available](https://discuss.linuxcontainers.org/t/fedora-33-host-fedora-33-lxc-guest-warn-0000-the-cgroupv2-manager-is-set-to-systemd-but-there-is-no-systemd-user-session-available/10759)
> 
> Just as the following to this file, creating it if necessary: ${HOME}/.config/containers/containers.conf:
> 
> ```
> [engine]
> events_logger = "file"
> cgroup_manager = "cgroupfs"
> ```

thank you! this seems to have worked, since I got a different error now!

**Comment by mirekphd** [comment]
> after doing `systemctl --user enable --now dbus.socket`),

A more permanent solution is enabling lingering, which helped me when the above failed:
```
$ loginctl enable-linger $USER
```

_________
Now I can see my user's `$XDG_RUNTIME_DIR` being created and used:
```
$ ls -lant $XDG_RUNTIME_DIR
total 0
drwxr-xr-x 6 1177 1177 160 Aug  5 11:36 systemd
drwx------ 8 1177 1177 220 Aug  5 11:36 .
drwx------ 3 1177 1177  60 Aug  5 11:36 dbus-1
drwx------ 3 1177 1177  60 Aug  5 11:33 containers
drwx-----T 2 1177 1177  40 Aug  5 11:33 libpod
drwx------ 2 1177 1177 140 Aug  5 11:33 gnupg
srw-rw-rw- 1 1177 1177   0 Aug  5 11:33 pk-debconf-socket
drwxr-xr-x 2 1177 1177  60 Aug  5 11:33 podman
srw-rw-rw- 1 1177 1177   0 Aug  5 11:33 snapd-session-agent.socket
srw-rw-rw- 1 1177 1177   0 Aug  5 11:33 bus
drwxr-xr-x 3    0    0  60 Aug  5 11:33 ..
```

Credit goes to the suggestion from line 3 from `podman`'s sumptuous warning message (thanks RedHat!):
```
# Before:
$ podman run -u 1177 ubuntu bash -c "whoami"
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1177` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1177` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
1177
#
# After:
$ podman run -u 1177 ubuntu bash -c "whoami"
1177
```
