### ISSUE TITLE
Failed to install podman with download.opensuse.org repo on Travis Ubuntu bionic non x86_64

### ISSUE THREAD

**Issue by junaruga** [containers/libpod#5447]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Related to https://github.com/containers/libpod/issues/4570#issuecomment-573536966 , I tried the new way to install podman to Ubuntu bionic, following the document: https://podman.io/getting-started/installation - Ubuntu
This works on Travis x86_64 (amd64) host environment.
But it does not work on Travis aarch64 (arm64), ppc64le and s390x host environment.

```
. /etc/os-release
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | sudo apt-key add -
sudo apt-get update -qq
sudo apt-get -qq -y install podman
```

You can see the aarch64 log here, https://travis-ci.org/junaruga/ci-multi-arch-native-container-test/jobs/660695823#L85

```
$ sudo apt-get -qq -y install podman
E: Unable to locate package podman
```
Do you know what's the reason?

**Steps to reproduce the issue:**

1. Fork this repository: https://github.com/junaruga/ci-multi-arch-native-container-test

2. Do `git clone` and `git checkout`.

    ```
    $ git clone <the GIT URL>
    $ cd ci-multi-arch-native-container-test
    $ git checkout feature/test-with-the-latest-podman-deb
    ```

3. Enable your forked repository's Travis from your Travis setting page, then push the branch to your repository. And see the Travis result.

**Describe the results you received:**

The case: in the cases: aarch64-bionic-fedora, ppc64le-bionic-fedora and s390x-bionic-fedora, the podman is not installed like this log: https://travis-ci.org/junaruga/ci-multi-arch-native-container-test/jobs/660695823#L85 .

**Describe the results you expected:**

The podman should be installed in the Ubuntu non-x86_64, bionic cases.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

This is the output on x86_64 environment where podman could be installed.

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.11, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 2000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 2000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 6433202176
  MemTotal: 8361897984
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  eventlogger: file
  hostname: travis-job-138d9cda-c478-479d-8861-13d7ad9b9f46
  kernel: 5.0.0-1031-gcp
  os: linux
  rootless: true
  uptime: 1m 19.04s
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/travis/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/travis/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/2000/containers
  VolumePath: /home/travis/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
podman/unknown,now 1.8.0~7 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Travis https://travis-ci.org/junaruga/ci-multi-arch-native-container-test/builds/660695817

**Comment by junaruga** [comment]
Do I need to set below kind of arch info to the repository like docker's installation document?

https://docs.docker.com/install/linux/docker-ce/ubuntu/

arm64 case to set the repository for docker on Ubuntu.

```
$ sudo add-apt-repository \
   "deb [arch=arm64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
```

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@junaruga so, non-x86_64 envs for 18.04 aren't setup correctly which causes many unresolvable dependency errors and fixing that ain't too high on OBS' priority list. So, quite unlikely this will get fixed. But I'm hoping they'll enable 20.04 soon as it's released, so you'll have some LTS to work with.

I'll update the doc to specify what arches are currently supported for what distro.

**Comment by junaruga** [comment]
@lsm5 In case of Travis, the Ubuntu newest distro version is bionic (= 18.04). After 20.04 will be released, I am not sure when Travis will start supporting 20.04.

I have been waiting that this issue https://github.com/containers/libpod/issues/4570#issuecomment-573475045 that prevents podman to be installed on non-x86_64, would be fixed. This issue was fixed on podman 1.7.0.

But podman project changed the repo from ppa:projectatomic/ppa to OBS.
And another issue for non-x86_64 happened.

Is it possible for you to update podman to the latest version in `ppa:projectatomic/ppa` if it's hard to fix the OBS 18.03 repo issue?

```
sudo add-apt-repository -y ppa:projectatomic/ppa
```

Or do we have to wait someone's podman deb packaging work in Debian?
https://wiki.debian.org/Podman

**Comment by junaruga** [comment]
I just share that some people in Travis community are expecting podman will be installed on Travis.
https://travis-ci.community/t/podman-libpod-support/6823

**Comment by lsm5** [comment]
On Tue, Mar 10, 2020 at 10:37:11AM -0700, Jun Aruga wrote:
> @lsm5 In case of Travis, the Ubuntu newest distro version is bionic (= 18.04). After 20.04 will be released, I am not sure when Travis will start supporting 20.04.
> 
> I have been waiting that this issue https://github.com/containers/libpod/issues/4570#issuecomment-573475045 that prevents podman to be installed on non-x86_64, would be fixed. This issue was fixed on podman 1.7.0.
> 
> But podman project changed the repo from ppa:projectatomic/ppa to OBS.
> And another issue for non-x86_64 happened.
> 
> Is it possible for you to update podman to the latest version in `ppa:projectatomic/ppa` if it's hard to fix the OBS 18.03 repo issue?

sorry, I can't have that on my plate now. I've modified my autobuilder scripts
to use OBS, and PPA will require separate maintenance.

If it helps, I can add you to
projectatomic/ppa and/or help you create your own ppa, would that be good for you?

And you should be able to just re-use this source: https://gitlab.com/rhcontainerbot/podman/-/tree/debian-stable/debian
Also, there's there `debian-testing` branch for the OBS testing repo. Only
difference being testing branch gets RC content in addition to stable releases.

Maybe some modification might be needed in the debian/changelog file to
accurately mention the distro name for PPA.

Let me know..

> 
> ```
> sudo add-apt-repository -y ppa:projectatomic/ppa
> ```
> 
> Or do we have to wait someone's podman deb packaging work in Debian?
> https://wiki.debian.org/Podman

No idea about that one. Feel free to check with the deb maintainer about the
status of that.

> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/libpod/issues/5447#issuecomment-597218388

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by junaruga** [comment]
> If it helps, I can add you to
projectatomic/ppa and/or help you create your own ppa, would that be good for you?

@lsm5 thank you for showing the possibility to create the own ppa.
As I am not familiar with deb packaging, I am not a right person to be added to the ppa.

> No idea about that one. Feel free to check with the deb maintainer about the
status of that.

podman is actually in review status for the Debian new package, seeing the page.
https://ftp-master.debian.org/new/libpod_1.6.4+dfsg1-2.html

Perhaps, this maintainer could be the right person to be added.
I will send email to him for the help.

**Comment by krisklau** [comment]
What's the next step for resolving this?

**Comment by junaruga** [comment]
> I will send email to him for the help.

As he declined it, we have to fix if we want to fix it.
I am fine to close this ticket. I can use `docker` for this use case.
We can wait podman will be shipped for the non x86_64 architectures in the official Debian repository. Then I think Ubuntu will pick up it soon.
