### ISSUE TITLE
Podman stops accepting terminal input

### ISSUE THREAD

**Issue by computator** [containers/libpod#5454]
/kind bug

**Description**

Podman seems to intermittently corrupt the terminal somehow while running containers. Once this happens, any new containers will not accept any input or the detach keys. The only way to regain control is by stopping the container from another terminal. When the container exits, all the keys typed into it are dumped to the shell which then causes "command not found" or other errors depending on which keys had been pressed. This issue continues to happen for any new containers started in the same terminal window. Resetting the terminal doesn't fix it, but it can be fixed either by starting a new subshell or by closing the terminal window and opening a new one.

**Steps to reproduce the issue:**

1. Start a container attached to the terminal.

2. Use the container some and then exit it

3. Repeat steps 1-2 an indeterminate number of times. At some point a newly started container will not accept any input.

4. Stop the container from another terminal (`podman stop -l`)

5. Run any container in the original terminal window (Ex: `podman run --rm -ti ubuntu`) and see it still will not accept any input.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have run across this multiple times while developing and testing various containerized apps. I believe it's happened in both root and rootless mode, but I mostly use rootless. Once the issue is triggered neither mode works in that terminal window as tested with:
`podman run --rm -ti ubuntu` and `sudo podman run --rm -ti ubuntu`.

**Output of `podman version`:**

```
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.11, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 23185395712
  MemTotal: 33688653824
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: computator
  kernel: 5.3.0-40-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 4h 2m 22.21s (Approximately 0.17 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/computator/.config/containers/storage.conf
  ContainerStore:
    number: 40
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/local/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  GraphRoot: /home/computator/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 14
  RunRoot: /run/user/1000/containers
  VolumePath: /home/computator/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.0~7 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04

**Comment by computator** [comment]
I just ran across something that might help. After I had a container get stuck and stop accepting input, I stopped it in another terminal per usual as above. However, this time I tried running another podman command (that wasn't podman run), and this was the result:
```
$ podman container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] Error: error reading input: read /dev/stdin: resource temporarily unavailable
$
```
It wrote the prompt out, but never gave me a chance to pick yes or no, it immediately failed when it tried to read stdin. So that gives some more idea of how stdin is getting corrupted!

**Comment by computator** [comment]
I just ran `sh` to clear the error so my terminal was usable again and I got this potentially relevant message:
```
user@host$ sh
$ sh: turning off NDELAY mode

```

**Comment by mheon** [comment]
Can you try clearing terminal configuration with `reset` to see if that resolves it? I'm wondering if some of the changes we make for terminal attach (setting raw mode, among a few other things) might be being set, but not cleared.

**Comment by computator** [comment]
Resetting the terminal was the first thing I tried, sadly it doesn't help.

**Comment by rhatdan** [comment]
@computator @mheon Does this still happen with the latest versions of podman and conmon?

**Comment by computator** [comment]
I haven't had it happen yet, but I haven't been using containers much in the last week or two and may just not have triggered it yet. I will update this if I run into it again.

**Comment by rhatdan** [comment]
Ok reopen if it happens again.
