### ISSUE TITLE
Podman fails to run with --log-driver=journald on Centos 7

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#5467]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When running podman it fails to start the container if log driver set to journald.  Looks like the same issue described in https://github.com/containers/conmon/issues/67#issuecomment-594775765

**Steps to reproduce the issue:**

1.  podman run --name test --log-driver=journald httpd

**Describe the results you received:**
[conmon:e] Include journald in compilation path to log to systemd journal
Error: write child: broken pipe

**Describe the results you expected:**
Container started without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.1
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.11-1.1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.11, commit: cf3619d7130285b31fb70d0573414e1fae5ebe4e'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 6653034496
  MemTotal: 8368828416
  OCIRuntime:
    name: runc
    package: runc-1.0.0-15.1.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 67b92f062188d9cb6472b428855432c9f35efcf5
      spec: 1.0.1-dev
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: host.example.com
  kernel: 4.13.10-1.el7.elrepo.x86_64
  os: linux
  rootless: false
  uptime: 6535h 56m 26.77s (Approximately 272.29 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 33
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
conmon-2.0.11-1.1.el7.x86_64
podman-1.8.1-2.1.el7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by alitvak69** [comment]
Rebuilding conmon source RPM with packages below installed fixed the issue. 

`systemd-libs`
`systemd-devel`

I believe it was the same issue with packaging as the one I have seen for ubuntu while ago.

**Comment by mheon** [comment]
@alitvak69 Where are these packages sourced from? I'm pretty sure the official repos aren't shipping those versions yet

**Comment by alitvak69** [comment]
https://podman.io/getting-started/installation

**Comment by alitvak69** [comment]
The repo for centos listed there and managed by @lsm5

**Comment by lsm5** [comment]
> Rebuilding conmon source RPM with packages below installed fixed the issue.
> 
> `systemd-libs`
> `systemd-devel`
> 
> I believe it was the same issue with packaging as the one I have seen for ubuntu while ago.

@alitvak69 so you only added these two as build-deps and no other change in the build process, yes? I can fix that for centos.

@mheon @haircommander fedora would need this too, yes?

**Comment by mheon** [comment]
Yep, if not already done, we should depend on those in Fedora as well

**Comment by alitvak69** [comment]
@lsm5 I didn't changed specs I just made sure those packages were there :-).  But yes it totally makes sense to add those as dependencies.

**Comment by alitvak69** [comment]
Any news about this.  I have not seen any updates on kubik.

**Comment by TomSweeneyRedHat** [comment]
@mheon @haircommander PTAL

**Comment by lsm5** [comment]
i did make the changes on fedora, I think i need to change the centos branch too, let me check..

**Comment by lsm5** [comment]
@alitvak69 sorry the webhook integration for autobuilds was a little messed up, it's building now using this spec file: https://build.opensuse.org/package/view_file/devel:kubic:libcontainers:stable/conmon/_service:obs_scm:conmon.spec?expand=1

**Comment by lsm5** [comment]
@alitvak69 built, should land soon https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable/conmon/CentOS_7/x86_64

**Comment by rhatdan** [comment]
I take it the build has dropped so closing.
