### ISSUE TITLE
Problems with podman generate systemd

### ISSUE THREAD

**Issue by larsks** [containers/libpod#5485]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The unit files produced by `podman generate systemd --new ...` are problematic because they will fail to start the service if the system crashes.  This happens because the container is only removed as part of `ExecStopPost`, and during a crash (/power failure/etc) that never runs.  The result is that a subsequent attempt to start the service will fail with `Error: error creating container storage: the container name "your_container_name" is already in use by ...`.

You can't simply drop the `--new`, because then the resulting unit file won't actually create the container if it doesn't exist.

What you really need to make this robust is one of two things:

- Tie the lifetime of the container to the lifetime of the `podman` command. When the `podman` exits, the container is gone. This would make a containerized service behave like a normal un-containerized service, which would work well with a process manager like `systemd`.

- Allow replacing an existing container with a new container.  E.g., introduce a `--replace` flag to `podman run` so that `podman run --replace --name foo ...` would permit create a new container named `foo` *even if one already exists*.

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @larskarlitski!

I like the idea of a `--replace` flag as it allows to generalize this problem beyond systemd.

@mheon @giuseppe @rhatdan WDYT?

**Comment by giuseppe** [comment]
could we add a `ExecStartPre` that does a `rm -f`?

**Comment by vrothberg** [comment]
> could we add a `ExecStartPre` that does a `rm -f`?

That will only work for containers that have been named but won't work for unnamed containers.

**Comment by mheon** [comment]
No issues here, sounds reasonable to do

**Comment by rhatdan** [comment]
@larsks @vrothberg Does this issue still exist?

**Comment by vrothberg** [comment]
Yes. The idea is to add `--replace` to run/create which will remove an existing container in case of a name conflict. There are a couple of issues I want to tackle once the v2 work is closer to the finish line.

**Comment by rhatdan** [comment]
@vrothberg Any progress on this?

**Comment by vrothberg** [comment]
#6553 will fix it :+1:
