### ISSUE TITLE
rh-container-bot stopped building 17 weeks ago

### ISSUE THREAD

**Issue by bbros-dev** [containers/libpod#5502]
/kind bug

**Description**
Not sure if this is the best place to report this? But it looks like the @rh-container-bot stopped building about 17 weeks ago:

https://launchpad.net/~projectatomic/+archive/ubuntu/ppa?field.series_filter=bionic

Please point me to the more appropriate place to report if it is not here.

I arrived at that PPA via the install doc instructions:

```bash
sudo apt update
sudo apt install software-properties-common uidmap
sudo add-apt-repository ppa:projectatomic/ppa
sudo apt update
sudo apt install podman
```

**Comment by TomSweeneyRedHat** [comment]
@lsm5 is this something on your watch?

**Comment by lsm5** [comment]
@bbros-dev hi, the ppa is deprecated. I thought I added that in the description somewhere, but guess not. The podman install docs mention the steps to setup OBS repos.
