### ISSUE TITLE
RFE: generalize/simplify podman's handling of configuration options and files

### ISSUE THREAD

**Issue by djerius** [containers/libpod#5509]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

First off, I should note I'm not familiar with the wealth of environments that podman is being run in, so I don't have a lot of domain specific knowledge, but I'll go out on a limb anyway.

I'm working on a network where user home directories are NFS mounted and shared across multiple heterogeneous hosts. Each host requires it's own set of configuration files to match local conditions, such as different storage drivers (e.g. `vfs` vs. `overlay`), different names for local storage directories, mount configurations, etc.

I've run into some difficulties mapping the existing set of configuration options (which I'm sure have a sound historical basis) onto this model.

There isn't currently a consistent and comprehensive interface to manage the configuration files, configuration options, or sets of configuration files. The existing approach seems geared towards a very particular environment.

For instance, `--config` is available to specify the location of `libpod.conf`, but there are no similar options for `storage.conf`, or `mount.conf`.  A subset of the configuration variables in `storage.conf` may be modified via the `--root`, `--storage--driver`, `--storage-opt`, and accompanying `XDG_DATA_HOME`, `STORAGE_DRIVER` and `STORAGE_OPT` environment variables.

The only means of choosing between different sets of configuration files is via the `XDG_CONFIG_HOME` environment variable, which is an awkward fit, as conceptually it indicates that *all* of the user's configuration is located there, when in fact it's being used to specify just the `podman` configuration. For example, in my environment, it's not possible for a user to simply set `XDG_CONFIG_HOME` on a per host basis without possibly breaking any number of other systems or programs.  Instead, to be safe, one must run

```
XDG_CONFIG_HOME=$PODMAN_CONFIG_HOME podman
```

There's a further complication that changing configuration values often leads to a conflict with what's in `bolt_state.db`, so I find myself constantly performing the following ritual

 ```
pkill podman
rm bolt_state.db
podman info
```
While there are undoubtedly good reasons why one would change some of the configuration options at run time, there's a fragility in there which means that effectively it doesn't work out that way. 

I recognize that `podman` uses other commands under the hood, and it may be impossible to provide a uniform and comprehensive interface.  In that case, I think it'd better to recognize that upfront and deem that `podman` shouldn't single out particular options as it does now, but leave configuration to the configuration files. That may reduce flexibility, but I think it would make things more resilient.

I think the simplest approach is to have `podman` choose between sets of configuration files, using a search path that looks like

```
$PODMAN_CONFIG_HOME:$XDG_CONFIG_HOME/.config/containers:$HOME/.cconfig/containers
```
and leave it at that. (**Edit**: add a command line option to set `PODMAN_CONFIG_HOME`)

`If runtime modification is required, provide a uniform interface, e.g.
```
-D storage.driver="overlay" -D mounts./tmp/wprkdir=/tmp/workder
```

etc, and then update a copy of the current configuration files with the updated values and pass those along to the subsystems.  And somehow keep `bolt_state.db` updated.

**Comment by mheon** [comment]
Sorry that this got ignored. We're in the middle of a big rework of Podman as a whole, and this got caught in the cracks.

One piece of interesting news is that we've introduced a new configuration file, `containers.conf`, which unifies a lot of options and will eventually replace `libpod.conf`; unfortunately, it does not include storage or image configuration, as those are separate libraries. That's also why we have no flag to set configuration files for those two, though it should be doable to allow.

We are moving away from storing most configuration in the user's homedir (I think we still create a `storage.conf` though) which may alleviate some of your configuration swapping pain. It may be worth adding an alternative config location for rootless Podman, but it's hard to tell exactly where that should live, given that there aren't many places that survive reboot we can safely use outside of the user's home. I don't know that I want to involve environment variables in this more than the standard XDG_CONFIG_HOME and similar.

**Comment by rhatdan** [comment]
We have done this with the introduction of containers.conf
