### ISSUE TITLE
System logs flooded with mesage

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#5537]
Moved from https://github.com/containers/podman.io/issues/208 as reported there by @NTMan.  Please continue the discussion here.
Why my system logs flooded with message `container kill 8f3ff324c6a5188c9ff63ac3f870cc6c4ffc1a3046f4db025dc2d62f4de39f76 (image=dev-registry.sbis.ru/local_stand/inside:20.2100, name=inside)` when I start container?

[system-log.zip](https://github.com/containers/podman.io/files/4346986/system-log.zip)

```
$ podman --version
podman version 1.8.1-dev
```

[podman inspect inside](https://github.com/containers/podman.io/files/4346988/podman-inspect-inside.txt)

**Comment by mheon** [comment]
This is deliberate. These are the container events messages - Podman is leaving a log of what's going on. If you do not want this logged to journald, you can change to file logging by changing `libpod.conf` so that `events_logger` is set to `file`

**Comment by NTMan** [comment]
I suppose that the message itself said that happening something bad with the container.
And I am curious how to fix it.
That more strange today after computer reboot I didn't see these messages, but if they will return in the future I want to know what this means these messages and what should I do to fix it.

**Comment by mheon** [comment]
Probably the Signal 23 issue we're seeing elsewhere. Podman 1.8.2 will be released shortly to address it.

**Comment by NTMan** [comment]
Oh, I see today podman was upgraded maybe this fixed my problem.
```
 cat /var/log/dnf.log.1 | grep podman
2020-03-18T12:20:34Z DEBUG ---> Package podman.x86_64 2:1.8.1-0.1.dev.git0bd29f8.fc33 will be upgraded
2020-03-18T12:20:34Z DEBUG ---> Package podman.x86_64 2:1.8.2-0.1.dev.git412a114.fc33 will be an upgrade
2020-03-18T12:20:34Z DEBUG ---> Package podman-plugins.x86_64 2:1.8.1-0.1.dev.git0bd29f8.fc33 will be upgraded
2020-03-18T12:20:34Z DEBUG ---> Package podman-plugins.x86_64 2:1.8.2-0.1.dev.git412a114.fc33 will be an upgrade
 podman                                                           x86_64                                  2:1.8.2-0.1.dev.git412a114.fc33                                        rawhide                                                 13 M
 podman-plugins                                                   x86_64                                  2:1.8.2-0.1.dev.git412a114.fc33                                        rawhide                                                1.4 M
  perl-vars-1.05-452.fc33.noarch                                                  podman-2:1.8.2-0.1.dev.git412a114.fc33.x86_64                                 podman-plugins-2:1.8.2-0.1.dev.git412a114.fc33.x86_64                        
2020-03-18T12:30:47Z DDEBUG /var/cache/dnf/rawhide-2d95c80a1fa0a67d/packages/podman-1.8.2-0.1.dev.git412a114.fc33.x86_64.rpm removed
```

**Comment by mheon** [comment]
Yep, that sounds like it
