### ISSUE TITLE
RFE: podman generate systemd should write files to their proper path

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5538]
Currently, `podman generate systemd --file` writes to the current directory. This is problematic:
* It requires the user to `mv` the file into the proper location, which is rife with possibilities for user error
* After the mv, `systemctl start` may fail with the unhelpful message:
```
Failed to start container-xyz.service: Unit container-xyz.service not found.
```
This is because a unit file generated in `$HOME` will have the wrong SELinux type; it has to be fixed with `restorecon`.

All of this increases user suffering. I believe that `podman generate systemd --file` should Do The Right Thing:
* root: create in `/etc/systemd/system/`
* rootless: create in `$HOME/.config/systemd/user/`

Whether or not podman should create missing intermediate directories is a good question.

Make special note of the root case: it looks like there is some confusion about the destination path. There shouldn't be: `/lib/systemd` should never be touched by `podman generate systemd`, only by the actual podman rpm. Local configuration should be in `/etc/systemd/system`.

Since `podman generate systemd --file` currently spits out the path of the generated file, I believe this change can easily be made without fear of ambiguity or incompatibility.

**Comment by vrothberg** [comment]
Thanks for the detailed RFE, @edsantiago!

> Since podman generate systemd --file currently spits out the path of the generated file, I believe this change can easily be made without fear of ambiguity or incompatibility.

It would still be a breaking change; some users might rely on the current behavior that all files are generated in `pwd`.

@rhatdan asked for an`--install` flag which I didn't like yesterday but the selinux issue really convinces me.

**Comment by rhatdan** [comment]
Yes I think having --install, and then we could add it to containers.conf to allow users to always do this.

**Comment by zypA13510** [comment]
> This is because a unit file generated in `$HOME` will have the wrong SELinux type; it has to be fixed with `restorecon`.

Took me half an hour to realize what's wrong. I wish I had seen this. It should at least be listed in the man page as an FAQ.

**Comment by rhatdan** [comment]
Please open a PR to add the comment to the man page.

**Comment by rhatdan** [comment]
Looks like this as fixed in upstream
