### ISSUE TITLE
podman push fails to push to own repostory

### ISSUE THREAD

**Issue by loibpet** [containers/libpod#5565]
/kind bug

**Description**

Ran into this problem, when I was checking if scripts developed for docker were running with podman.

**Setup:** Secured infrastructure with own container registry. Production container are allowed only from this own registry. Therefore, `/etc/containers/registries.conf` is modified as follows:
```
[registries.search]
...
registries = ['myregistry.mycompany.com']
...
[registries.insecure]
registries = []
...
[registries.block]
registries = ['docker.io', 'registry.fedoraproject.org', 'quay.io', 'registry.centos.org']
```

The following steps are performed:
1. `docker -v`
1. `docker pull ubi7/ubi:latest`
1. `docker tag  ubi7/ubi:latest bakery/baseimages/ubi7/ubi:test`
1. `docker login`
1. `docker push bakery/baseimages/ubi7/ubi:test`

This is working fine for `docker`, but fails with `podman`, i.e. `docker` pulls the container, tags it and pushes it to the own registry. `podman` fails pushing it to the registry.

For podman:
```
podman version 1.8.1

Now pulling ...
Trying to pull myregistry.mycompany.com/ubi7/ubi:latest...
...
Now tagging ...
Username: 
Password:
Login Succeeded!
Now pushing ...
Error: Error copying image to the remote destination: Error initializing destination docker://bakery/baseimages/ubi7/ubi:test: registry docker.io is blocked in /etc/containers/registries.conf
```

whereas for docker:
```
Docker version 1.13.1, build 07f3374/1.13.1

Now pulling ...
Trying to pull repository myregistry.mycompany.com/ubi7/ubi ...
latest: Pulling from myregistry.mycompany.com/ubi7/ubi
...
Status: Downloaded newer image for myregistry.mycompany.com/ubi7/ubi:latest
Now tagging ...
Username (myself): 
Password:
Login Succeeded
Now pushing ...
The push refers to a repository [myregistry.mycompany.com/bakery/baseimages/ubi7/ubi]
...
```
The container is pushed then successfully to `myregistry.mycompany.com`.

**Describe the results you expected:**

`podman` behaves as `docker`and is able to push to registry as defined in `registries.conf`.

**Comment by vrothberg** [comment]
@loibpet, am I reading the issue correctly that you want `podman push bakery/baseimages/ubi7/ubi:test` to resolve to `myregistry.mycompany.com/bakery/baseimages/ubi7/ubi:test`?

**Comment by loibpet** [comment]
Yes. This is exactly the behavior from docker

**Comment by vrothberg** [comment]
Thanks!

Currently, Podman and Buildah only consult use the search registries in `registries.conf` for pulling while pushing will normalize unqualified image names to `docker.io/{library}`.

I don't think we can change that behavior without breaking existing users who already rely on the current behavior.

@rhatdan, can you weigh in?

**Comment by loibpet** [comment]
So, you:

- Break the compatibility to `docker`
- Avoid the usage of own repositories as needed in secured and regulated entities; our regulations make it next to impossible to use source-to-image:
   - we are required to pre-fill our container with the complete software stack
   - run through a formal acceptance with these pre-filled container
   - run in production only these formally accpted container without further modifications

My organization is running into a legal issue here. Hence, podman and `OpenShift` are not usable for us.

Did I get you correct on this?

**Comment by vrothberg** [comment]
>     * Break the compatibility to `docker`

The Docker we are talking about is a fork and not a vanilla Docker-ce.

>     * Avoid the usage of own repositories as needed in secured and regulated entities; our regulations make it next to impossible to use source-to-image:

Why not specify the full reference (i.e., `myregistry.mycompany.com/bakery/baseimages/ubi7/ubi:test`)? Podman is not blocking anybody from doing anything.

To be clear, only `podman pull` will iterate over the search registries and attempt to pull in the specified order. Note that only happens for short image names (or unqualified images names) such as `fedora` (in contrast to a fully qualified image name specifying domain & repository such as `docker.io/library/fedora:latest`).

When pushing, Podman does not look at the search registries for short image names. `fedora` will be normalized to `docker.io/library/fedora:31` (just as Docker-ce does). If users want to push to another registry, they need to specify the domain and registry.

I believe that [skopeo sync](https://github.com/containers/skopeo/blob/master/docs/skopeo-sync.1.md) may be a good tool for migrating images from registry to registry.

**Comment by rhatdan** [comment]
Correct registries.conf is only supposed to be used for shorname expansion. If the image is stored in container storage, it will be fully specified, if you push the image without a destination, then it will attempt to push to the fully specified image registry name specified n containre/storage.  If you want to push it somewhere else, then you need to specify a destination.

**Comment by loibpet** [comment]
So, I would have to tag my image accordingly, i.e. adding the registry to the tag. Correct?

Then, I have the issue that any regular user being able to access my pipeline or run the `podman` command on the command line can define the registry as they want to. However, modifying the `registries.conf` has the advantage that it requires a system administrator to perform this task, i.e. the regular user cannot change the push destination. This is in our environment of advantage. Or did I just miss anything?

**Comment by rhatdan** [comment]
Currently we don't enforce where images are being pushed, although maybe blocked will stop you from pushing to certain registries.
Is your goal to prevent malicious users or accidental users.  Malicious users are very difficult to control if you give them access to the low level tools like podman and skopeo.

**Comment by vrothberg** [comment]
> So, I would have to tag my image accordingly, i.e. adding the registry to the tag. Correct?

Yes. Tagging would work. In case you want to push multiple images from A to B, I highly recommend having a look at `skopeo-sync`; it's meant for exactly this use case.

> Then, I have the issue that any regular user being able to access my pipeline or run the `podman` command on the command line can define the registry as they want to. However, modifying the `registries.conf` has the advantage that it requires a system administrator to perform this task, i.e. the regular user cannot change the push destination. This is in our environment of advantage. Or did I just miss anything?

If you want to prevent users from accessing registries, you can specify them in the `registries.conf` as blocked. They will not be able to push/pull to these registries.

**Comment by rhatdan** [comment]
I think we have answered the questions, reopen if I am mistaken.
