### ISSUE TITLE
Firewalld issue

### ISSUE THREAD

**Issue by JuSt19** [containers/libpod#5568]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Once we deploy the microservices within podman with selinux and firewalld (both activated)...services start not responding requests properly. If you connect to the container and try to ping, dig any internal or external domain, any action to verify the connection, the pod is not able no do nothing, if we restart the pod but first with firewalld and selinux disabled...everything is ok and all back to normality.

**Steps to reproduce the issue:**

1. Activate Firewalld

2. Deploy two containers:
podman run --name nginx01 -d -p 8080:80 nginx
podman run --name nginx02 -d -p 8081:80 nginx

3. Stop firewalld

4. Try to make internal DNS query or external such as google or something...

**Describe the results you received:**

root@4d01a46cd8c7:/# ping 10.88.0.3
PING 10.88.0.3 (10.88.0.3) 56(84) bytes of data.
From 10.88.0.2 icmp_seq=10 Destination Host Unreachable
From 10.88.0.2 icmp_seq=11 Destination Host Unreachable
From 10.88.0.2 icmp_seq=12 Destination Host Unreachable
From 10.88.0.2 icmp_seq=13 Destination Host Unreachable

root@8d9d9097cc6e:/app# ping subdomain.domain.com
ping: subdomain.domain.com: Temporary failure in name resolution

When the microservice try to connec to SQL Server:
SqlExceptionHelper","message":"The connection attempt failed."

**Describe the results you expected:**
- The possibility to make dns querys and connect to other services such as sql

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.4.4
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 553943040
  MemTotal: 8201318400
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.centos.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 5519458304
  SwapTotal: 6509555712
  arch: amd64
  cpus: 4
  hostname: test-podman-01
  kernel: 3.10.0-1062.1.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 594h 16m 31.05s (Approximately 24.75 days)
registries:
  blocked: null
  insecure:
  - 172.16.x.x:8087
  - 172.16.x.x:8089
  search:
  - registry.internaldomain.com
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 16
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 16
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
@mheon PTAL

**Comment by rhatdan** [comment]
I don't think this is an SELinux issue, but I am willing to be proven wrong?  If you put the machine in permissive mode, does it still fail with the file wall rules up?

Are there any AVC messages in the audit.log.

This issue looks a lot like a firewall rules.

From the podman info this looks like it is happening with root.

BTW There should be a newer version of podman available for centos.

**Comment by ikke-t** [comment]
check out it's not the same I had a while back, confusion between iptables and firewalld: https://github.com/containers/libpod/issues/5335

**Comment by JuSt19** [comment]
I have updated the main issue with more information and also the title, this issues is focused in firewalld.

I've talked yesterday with @mheon and he asked me to do some tests and here's the output:

[root@test-podman-01 ~]# podman exec -it nginx02 bash
Error: cannot exec into container that is not running: container state improper

`[root@test-podman-01 ~]# iptables -nvL
Chain INPUT (policy ACCEPT 256 packets, 18390 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 16 packets, 920 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 153 packets, 17604 bytes)
 pkts bytes target     prot opt in     out     source               destination`

`[root@test-podman-01 ~]# iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 20 packets, 1262 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 12 packets, 802 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 9 packets, 2232 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 17 packets, 2692 bytes)
 pkts bytes target     prot opt in     out     source               destination
`

**Comment by JuSt19** [comment]
I have found this links about the same issue in the same env:

https://github.com/containers/libpod/issues/348
https://github.com/containers/libpod/pull/1431#issuecomment-579939112

**Comment by mheon** [comment]
I feel like we may have fixed this on master, but I'm not precisely sure as to when...

@JuSt19 There's a Centos virt-sig repo that distributes more up-to-date Podman packages; would you be willing to give those a shot and see if a more recent version is fixed? @lsm5 where did that repo live, again?

**Comment by JuSt19** [comment]
@mheon that's perfect for me, could you please share to me this repo and then i'll test if it's already fixed.

Awaiting!

**Comment by lsm5** [comment]
> I feel like we may have fixed this on master, but I'm not precisely sure as to when...
> 
> @JuSt19 There's a Centos virt-sig repo that distributes more up-to-date Podman packages; would you be willing to give those a shot and see if a more recent version is fixed? @lsm5 where did that repo live, again?

I don't maintain the virt-sig repo anymore. All non-fedora and non-rhel is on OBS now. 1.8.2 should be available for centos 7 via the OBS stable repo. See the Kubic project section under CentOS at https://podman.io/getting-started/installation for installation instructions

**Comment by JuSt19** [comment]
> > I feel like we may have fixed this on master, but I'm not precisely sure as to when...
> > @JuSt19 There's a Centos virt-sig repo that distributes more up-to-date Podman packages; would you be willing to give those a shot and see if a more recent version is fixed? @lsm5 where did that repo live, again?
> 
> I don't maintain the virt-sig repo anymore. All non-fedora and non-rhel is on OBS now. 1.8.2 should be available for centos 7 via the OBS stable repo. See the Kubic project section under CentOS at https://podman.io/getting-started/installation for installation instructions

Still failing after update to 1.8.2 and doing the same thing to reproduce the same with the old version.

**Comment by cfelder** [comment]
Hello, is there any progress on this? I am experiencing the same issue on CentOS 8. When firewall is enabled. Basically name resolution does not work whereas routing works fine when using Its directly.

**Comment by mheon** [comment]
@mccv1r0 Any thoughts on this one?

**Comment by cfelder** [comment]
This may be related to #5335. I am currently not using the kubic repos but with the version provided in AppStream repos for CentOS 8

``podman-1.6.4-2.module_el8.1.0+272+3e64ee36.src.rpm``

a wrong CNI configuration is created containing iptables as backend for the firewall plugin.

This is easy to reproduce using:
```
$ podman network create newnetwork
$ podman network inspect newnetwork | grep backend
				"backend": "iptables",
```

**Comment by baude** [comment]
this is a known issue and is fixed upstream ... both the network create code and default cni config

**Comment by cfelder** [comment]
any chance getting this into the releases shipped with the base/appstream repos on rhel?

**Comment by rhatdan** [comment]
Is it fixed in podman-1.16.4?  Which should be released in rhel8.2 release.

**Comment by rhatdan** [comment]
We will release podman-1.9.* in RHEL8.2.1 in the summer time.

**Comment by cfelder** [comment]
Looking forward to see this and hopefully dnsmasq plugin in the next release. Meanwhile I can workaround this by myself.

Thanks a lot.

**Comment by mheon** [comment]
Can you confirm whether there is a firewall block in the base network we ship (`87-podman-bridge.conflist`)?

**Comment by cfelder** [comment]
For ``podman-1.6.4-2.module_el8.1.0+272+3e64ee36.src.rpm`` there is the following block:

```
        {
            "type": "firewall",
            "backend": "iptables"
        }
```

**Comment by mheon** [comment]
Alright. So we are at least shipping a vaguely working config, here.

**Comment by rhatdan** [comment]
@mheon Is this still an issue with the upstream?

**Comment by mheon** [comment]
This should be fixed on upstream CNI configs.
