### ISSUE TITLE
Since version 1.8.3-0.1.dev.gitaa6c8c2.fc33 all console utilities in container working only in 80x25 chars .

### ISSUE THREAD

**Issue by NTMan** [containers/libpod#5584]
Since version 1.8.3-0.1.dev.gitaa6c8c2.fc33 all console utilities in container working only in 80x25 chars .

![Screenshot from 2020-03-23 10-07-27](https://user-images.githubusercontent.com/200750/77284816-6673ba80-6cf1-11ea-98f7-2ec35f10f1c6.png)

Last good version is 1.8.2-0.9.dev.gitcccd05c.fc33

**Comment by rhatdan** [comment]
@mheon @haircommander @giuseppe Terminal resize broke?

**Comment by mheon** [comment]
More details would be greatly appreciated - is this with `podman exec`, or `podman run`, or both?

**Comment by NTMan** [comment]
> More details would be greatly appreciated - is this with `podman exec`, or `podman run`, or both?

It's the result of both commands.

1. `$ podman run my-super-container`
2. `$ podman exec -it inside mc`

**Comment by mheon** [comment]
#5613 to fix
