### ISSUE TITLE
APIv2: `commit` badly attached and documented

### ISSUE THREAD

**Issue by marusak** [containers/libpod#5586]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I am trying to use `commit` from APIv2 and having hard time due to miserable documentation. (1) First issue is that it is attached to `/commit` instead of `/libpod/commit` which would be much better for consistent experience. (2) But the main issue is that it does not mention that the request needs some body, without the body it fails:

```
sudo curl -X POST --unix-socket /run/podman/podman.sock "http://d/v1.24/commit?container=44c004db4b17&comment=message&repo=myrepo"
{"cause":"EOF","message":"Decode(): EOF","response":500}
```

Passing just empty object, solves this issue:
```
sudo curl -X POST --unix-socket /run/podman/podman.sock -H "Content-Type: application/json" --data "{}" "http://d/v1.24/commit?container=44c004db4b17&comment=message&repo=myrepo&tag=1" 
{"cause":"no such container","message":"no container with name or ID 44c004db4b17 found: no such container","response":404}
```

(3) Also I think some parameters must be required (like `container`), but the doc does not mention it.
(4) Finally, is it possible to set up 'format' the same way I could do `podman commit --format <format>`?

Using current master and reading current documentation.

**Comment by marusak** [comment]
Also, could I get example how to set up two changes? For example lets say I want to set up CMD to `bash -c "echo 'hello world'"` and USER to `admin`?
Thank you

**Comment by mheon** [comment]
@baude @jwhonce PTAL

**Comment by baude** [comment]
1. Added libpod endpoint in #5588 
2. Was a bug, fixed
3. fixed in swagger docs
4. yup, i added that.
5. sudo curl -X POST --unix-socket /run/podman/podman.sock 'http://d/v1.24/libpod/commit?author=baude&changes=CMD%3D%2Fbin%2Ffoobar&container=foo&repo=quay.io%2Fbaude%2Fdunbar&tag=latest

**Comment by marusak** [comment]
Thank you @baude for the quick fixes!
ad 5. I was mostly asking how is it possible to pass more than one `change` (comma separated, space separated, some kind of array...)? And also how it should be encoded when the value is more than one string (sometimes these things are passed as arrays, sometimes as encoded strings...)
