### ISSUE TITLE
Man docker-pull mentions SOURCE without contextualizing it

### ISSUE THREAD

**Issue by rhn** [containers/libpod#5603]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In `man docker-pull`, the command syntax is "podman pull [options] name[:tag|@digest]", without any mention of SOURCE. The man page doesn't mention SOURCE outside of the SOURCE section, and so there's  some link missing there.

It says ""SOURCE" uses a "transport":"details" format.", and the only thing resembling that syntax is name:tag, potentially leading to some confusion.

**Steps to reproduce the issue:**

1. `man docker-pull`

2. Look at the SOURCE section

**Describe the results you received:**

A SOURCE section that seems out of place.

**Describe the results you expected:**

Either no mention of SOURCE, or a syntax that includes a clear way to use SOURCE.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.1-2.fc31.x86_64
```

**Comment by vrothberg** [comment]
Thanks for opening the issue, @rhn! The `podman-pull` man page really needs some updates. In the meantime, there's a `containers-transports(5)` man page providing all the details for the various transports. We should like to that man page.

**Comment by rhatdan** [comment]
@rhn Interested in opening a PR to improve the man page?

**Comment by rhn** [comment]
I don't really know what went wrong there unfortunately :(

**Comment by rhatdan** [comment]
I opened a PR to fix this PTAL
