### ISSUE TITLE
Honour network settings in podman play/generate kube

### ISSUE THREAD

**Issue by cfelder** [containers/libpod#5609]
/kind feature

**Description**

I am uncertain whether the kube yaml standard supports network settings.

Either ``podman play kube`` should honour network settings, e.g. ``--network`` or the generated yaml file using ``podman generate kube`` should take into account network settings for pods and/or containers.

As far as I can see in #5241 network opts have been added to ``podman pod create`` but there seems to be nothing for either ``podman play kube`` nor ``podman generate kube``.

For single containers and systemd generation this is already supported using
``podman generate systemd {ctrID} --new``

Thanks a lot for this.

I checked versions 1.6.4 (CentOS 8), 1.8.0 (Fedora 30) and 1.8.2 (Kubic Repos for CentOS 8)

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?
