### ISSUE TITLE
How do podman containers make connections and port issues?

### ISSUE THREAD

**Issue by ZeronoFreya** [containers/libpod#5621]
> I can't access http://irc.freenode.net/, so I'd like to ask some questions

Question 1: not root user cannot create a nginx application with a port number of 80?
>Podman can not create containers that bind to ports < 1024.
>Non priv users are not allowed to bind to ports < 1024, so this requires root.

So I can only create nginx under root? And I also need PHP and mariadb to support my site, I've tried to reference PHP in nginx's configuration file:
```
location ~ \.php(.*)$ {
    fastcgi_pass   php:9000;
    ...
}
```
Check with `nginx -t` and report an error: `nginx: [emerg] host not found in upstream "php" in ...`
But docker works that way

Question 2: How do I create two 80-port containers in the same pod? 
like this：

```
podman pod create --name zf_site_network -p 80:80 -p 443:443 -p 3306:3306 -p 8888:80

// port 80:80
podman run -d --name nginx --pod zf_site_network nginx  
// port 8888:80, need mariadb 
podman run -d --name nextcloud --pod zf_site_network nextcloud 
// port 3306:3306
podman run -d --name mariadb --pod zf_site_network mariadb
// port 9000:9000, need mariadb
podman run -d --name php --pod zf_site_network php 
```
Thanks!

**Comment by mheon** [comment]
1. Podman, when run without root, has no privileges the user running it does not have. Binding ports under 1024 on Linux is a privileged operation, requiring root (though there is a sysctl to change this - see [here](https://github.com/torvalds/linux/blob/master/Documentation/networking/ip-sysctl.txt#L947)). This is a disadvantage of rootless Podman, which needs to trade off some functionality like this for security benefits. if you want things to work exactly as Docker does, please use Podman as root.

2. Pods share a single network stack - everything within a pod will have the same IP address, same localhost, etc. This lets applications talk to each other over localhost, but also means that two applications cannot bind to the same port within a pod. If you have multiple webapps, you can try binding them to different ports on localhost in the pod, then running a single HTTP server that proxies them all that runs on the primary port.

**Comment by ZeronoFreya** [comment]
@mheon Thank you for your reply. In addition, if pod is not used, how can containers contact each other?
I see podman support for creating a network, but after I add a container (like Nginx) to the network, the browser can't access the container?
```
sudo podman network create zf_site_network
podman run -d --name nginx -p 80:80 --network zf_site_network nginx
```

**Comment by mheon** [comment]
Networks created as root can only be used by root Podman - we should probably improve documentation about this. I would also expect that `podman run` would error when you tried the command; does it?

**Comment by ZeronoFreya** [comment]
@mheon  Okay, I'm already running podman as root, but how do I communicate between containers? If I can't do that, I'll have to go back to docker. At least, it's easy. Finally, let me say thank you.

**Comment by xcffl** [comment]
Inter container communication is done via 127.0.0.1 if they are in a pod. Inter pod communication is done via 10.0.2.3 (rootless, in root mode should be found via `ip a`, conmon interface). 

You can also use host networking, especially suitable for ingress reverse proxy. That way, the reverse proxy can find other pods via 127.0.0.1.

Besides, you should stick with root or rootless mode rather than hybrid. To use 443 port in rootless mode you can refer to the documentation.

**Comment by mheon** [comment]
@ZeronoFreya Assuming the `dnsname` plugin for CNI is installed (it should be a dependency on most distributions) you can look up other containers via their names, as Docker does. From there, communications works exactly as it does between any two hosts; each container has an IP address, and you can connect between them without issue. You could also assign them static IPs to avoid name lookup.

**Comment by rhatdan** [comment]
@ZeronoFreya @mheon Is this a solved problem, and we can close the issue.

**Comment by mheon** [comment]
I'm going to close this due to a lack of activity; feel free to open a new issue if more questions arise.
