### ISSUE TITLE
podman running kata containers is not cleanup up correctly.

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#5628]
```
# podman ps
# podman run -ti --runtime=/usr/bin/kata-runtime --rm  fedora sh
# ^d
# 
# podman ps 
ERRO[0000] OCI Runtime kata is in use by a container, but is not available (not in configuration file or not installed) 
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
```

**Comment by TomSweeneyRedHat** [comment]
just curious, does `buildah containers` show anything or `podman ps -a`?

**Comment by mheon** [comment]
Why are you specifying full path to `--runtime`? Why not `--runtime=kata`? I think our default configuration file includes it now...

IMO, NOTABUG, `--runtime=FULL-PATH` is reserved for CI only.

**Comment by rhatdan** [comment]
podman run -ti --runtime=kata --rm  fedora echo hello
Error: error creating libpod runtime: default OCI runtime "kata" not found: invalid argument

**Comment by rhatdan** [comment]
Anyways this error went away, since I think something was screwed up.

**Comment by mheon** [comment]
The root `libpod.conf` we ship by default includes the runtimes:

```
# Kata Containers with the default configured VMM
kata-runtime = [
    "/usr/bin/kata-runtime",
]

# Kata Containers with the QEMU VMM
kata-qemu = [
    "/usr/bin/kata-qemu",
]

# Kata Containers with the Firecracker VMM
kata-fc = [
    "/usr/bin/kata-fc",
]
```

Containers.conf includes only one of these (`kata`) - https://github.com/containers/common/blob/master/pkg/config/containers.conf#L372-L379
