### ISSUE TITLE
update-grub /usr/sbin/grub-probe: error: failed to get canonical path of /dev/mapper/<Host LVM2 Volume>

### ISSUE THREAD

**Issue by bbros-dev** [containers/libpod#5633]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Grub update fails in podman container run from Host where Host `/` is a LVM2 volume group.

**Steps to reproduce the issue:**

1. Start the container:

```bash
podman run -i -t --rm yelgeb/kernel:0.0.8 busybox sh
```

2. Inside the container run `update-grub`

```bash

BusyBox v1.27.2 (Ubuntu 1:1.27.2-2ubuntu3.2) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/ # update-grub
/usr/sbin/grub-probe: error: failed to get canonical path of `/dev/mapper/ubuntu--vg-root'.

```
3. The `/dev/mapper/...` is a Host detail:

```bash
# findmnt
TARGET                                SOURCE                                     FSTYPE   OPTIONS
/                                     /dev/mapper/ubuntu--vg-root[/home/<redacted>/.local/share/containers/storage/vfs/dir/967b8de0ca89db0c089cd6bee3cb37290b33e910aa4e89c466350041fe84872b]
│                           
```

**Describe the results you received:**

`/usr/sbin/grub-probe: error: failed to get canonical path of `/dev/mapper/ubuntu--vg-root'.`

**Describe the results you expected:**

That `update-grub` succeeds.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue always happens across different containers.

**Output of `podman version`:**

```
$ podman version
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.11, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1303990272
  MemTotal: 16652021760
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 3558531072
  SwapTotal: 4156551168
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: desktop.local.lan
  kernel: 5.3.0-40-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 287h 37m 5.02s (Approximately 11.96 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/hedge/.config/containers/storage.conf
  ContainerStore:
    number: 115
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/hedge/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 214
  RunRoot: /run/user/1000
  VolumePath: /home/hedge/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 1.8.2~1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Host.
Podman container.

**Comment by rhatdan** [comment]
This is expected and the way containers work.  You can not modify the host OS from inside of the container without exposing much more of the host to the container.

podman run -v /dev:/dev --privileged -ti busybox sh

Would probably work.

**Comment by bbros-dev** [comment]
To clarify, we're not trying to modify the host from within the container.  The opposite.  We are trying to modify only the container image.  

Apologies for anything we wrote that caused that misunderstanding.

We'd just like `update-grub` to succeed much that same as `make vmlinux` does.

The `--privileged` does not change the observed behavior. The `--volume ...` is not our use case.

**Comment by rhatdan** [comment]
Grub would have no effect, since you are not booting a kernel when a container comes up.  Containers are not VM's they do not have their own kernels.

**Comment by bbros-dev** [comment]
Understood.  That would be the case if we were trying to use grub.  The command at issue here is `update-grub` which concerns installed kernels.

**Comment by rhatdan** [comment]
Sure, but I think the tool is being fooled when looking at the host kernel, and not matching up its configuration.

**Comment by LaszloGombos** [comment]
I think this bug report belongs to grub not podman (I would love this to be resolved in grub as well).
