### ISSUE TITLE
running podman rootless fails to allow port binding to multiple host IP addresses

### ISSUE THREAD

**Issue by wdouglascampbell** [containers/libpod#5646]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running podman rootless prevents binding port to multiple host IP addresses.

1.  Allow non-root access to privileged ports

```echo 0 | sudo tee /proc/sys/net/ipv4/ip_unprivileged_port_start```

2.  Run nginx container using podman

```podman run -d -p 172.16.2.203:80:80 -p 172.16.2.204:80:80 -p 172.16.2.203:443:443 -p 172.16.2.204:443:433 nginx```

**Describe the results you received:**

```Error: failed to expose ports via rootlessport: "conflict with ID 1\n"```

**Describe the results you expected:**

Container runs without errors and allows access via calls to specified host IP addresses to ports 80 and 443 but deny access to other host IP addresses.

**Additional information you deem important (e.g. issue happens only occasionally):**

1)  Running podman rootless allows this to run successfully.

2)  Also, the following works (which I wasn't expecting given that the original command didn't):

```podman run -d -p 172.16.2.203:80:80 -p 172.16.2.204:80:8000 -p 172.16.2.203:443:433 -p 172.16.2.204:443:8443 nginx```

Note how it is allowing this to work if the port mapped inside the container is different so mapping to 80 and 8000 as well as 443 and 8443.

**Output of `podman version`:**

```
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.1
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 2539413504
  MemTotal: 4121174016
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 96f6022b37cbe12b26c9ad33a24677bec72a9cc3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: localhost.localdomain
  kernel: 5.5.8-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 6h 17m 33.04s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/home/core/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/core/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 6
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/core/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.1-2.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Fedora CoreOS
```

**Comment by tylarb** [comment]
@wdouglascampbell  the error message is returned as part of rootlessport. 

Can you verify if this behavior exists when running under root?

The check is here: 

```
vendor/github.com/rootless-containers/rootlesskit/pkg/port/portutil/portutil.go

 40 // ValidatePortSpec validates *port.Spec.
 41 // existingPorts can be optionally passed for detecting conflicts.
 42 func ValidatePortSpec(spec port.Spec, existingPorts map[int]*port.Status) error {
 43 ⇥       if spec.Proto != "tcp" && spec.Proto != "udp" {
 44 ⇥       ⇥       return errors.Errorf("unknown proto: %q", spec.Proto)
 45 ⇥       }
 46 ⇥       if spec.ParentIP != "" {
 47 ⇥       ⇥       if net.ParseIP(spec.ParentIP) == nil {
 48 ⇥       ⇥       ⇥       return errors.Errorf("invalid ParentIP: %q", spec.ParentIP)
 49 ⇥       ⇥       }
 50 ⇥       }
 51 ⇥       if spec.ParentPort <= 0 || spec.ParentPort > 65535 {
 52 ⇥       ⇥       return errors.Errorf("invalid ParentPort: %q", spec.ParentPort)
 53 ⇥       }
 54 ⇥       if spec.ChildPort <= 0 || spec.ChildPort > 65535 {
 55 ⇥       ⇥       return errors.Errorf("invalid ChildPort: %q", spec.ChildPort)
 56 ⇥       }
 57 ⇥       for id, p := range existingPorts {
 58 ⇥       ⇥       sp := p.Spec
 59 ⇥       ⇥       sameProto := sp.Proto == spec.Proto
 60 ⇥       ⇥       sameParent := sp.ParentIP == spec.ParentIP && sp.ParentPort == spec.ParentPort
 61 ⇥       ⇥       sameChild := sp.ChildPort == spec.ChildPort
 62 ⇥       ⇥       if sameProto && (sameParent || sameChild) {
 63 ⇥       ⇥       ⇥       return errors.Errorf("conflict with ID %d", id)
 64 ⇥       ⇥       }
 65 ⇥       }
 66 ⇥       return nil
 67 }

```

So I think the check is actually that you're using the same child port - 80 is used twice as a child port, hence your second example - mapping 80 to 80 on one container and 80 to 8080 on another container/IP works.

I can probably test the working state of _not_ using the sameChild spec, but in any case this is a rootlessport problem. 

If you can verify what behavior root has that would help further.

**Comment by mheon** [comment]
We confirmed on IRC earlier that this does not affect Podman as root - CNI is able to handle the multiple IP addresses properly.

This seems like a bug/feature request for rootlessport - I'm not sufficiently familiar with the constraints there to know if it's possible. @AkihiroSuda thoughts?

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/rootlesskit/blob/85b44e75634bb9e33dc7042b3ee1bbb2e52af02e/pkg/port/portutil/portutil.go#L62

Probably we just need to change `if sameProto && (sameParent || sameChild) { return err }` to `if sameProto && sameParent { return err }`.

**Comment by tylarb** [comment]
I confirmed fix above works. I'll submit PR to rootlesskit.

**Comment by AkihiroSuda** [comment]
Thanks @tylarb , released RootlessKit v0.9.3
https://github.com/rootless-containers/rootlesskit/releases/tag/v0.9.3

I guess the bot in this repo will automatically open PR for vendoring v0.9.3.

**Comment by wdouglascampbell** [comment]
Thanks all for working on this.  Had no Internet for a few days just am able to respond.

**Comment by AkihiroSuda** [comment]
https://github.com/containers/libpod/pull/5674 should have fixed this
