### ISSUE TITLE
Empty environment in poststop hooks

### ISSUE THREAD

**Issue by AlbanBedel** [containers/libpod#5653]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The environment is empty when poststop hooks run. Not even PATH is set which prevent many tools from working properly.

**Steps to reproduce the issue:**

1. Create a hook that write its environment to a temp file:
```sh
#!/bin/sh

env > /tmp/podman-hook-env-$$
```

2. Register it as prestart and poststop hook:
```json
{
    "version": "1.0.0",
    "hook": {
	"path": "/usr/local/bin/test-hook.sh",
	"args": [ "test-hook.sh" ]
    },
    "when": {
	"always": true
    },
    "stages": ["prestart", "poststop"]
}
```
3. Run a container and compare the 2 /tmp/podman-hook-env-* files.

**Describe the results you received:**

For prestart I see the following environment:
```sh
_CONTAINERS_USERNS_CONFIGURED=
HOME=/root
_OCI_SYNCPIPE=3
_OCI_STARTPIPE=4
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
XDG_RUNTIME_DIR=
_CONTAINERS_ROOTLESS_UID=
PWD=/var/lib/containers/storage/overlay-containers/60210276522e35edee32a97f0d537e9b5f83e4eafc8857a00779ee9e6ad69c7c/userdata
```

but for poststop I see the following environment:
```sh
PWD=/home/alban/Dev/podman-hooks
```

**Describe the results you expected:**

I would expect the environment in poststop to set PATH to allow running common tools.

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.10
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.14, commit: '
  Distribution:
    distribution: ubuntu
    version: "19.10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 925327360
  MemTotal: 8205549568
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 614461440
  SwapTotal: 1023406080
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: tack
  kernel: 5.3.0-42-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 6h 48m 51.75s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/alban/.config/containers/storage.conf
  ContainerStore:
    number: 17
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/alban/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 70
  RunRoot: /run/user/1000/containers
  VolumePath: /home/alban/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 1.8.2~1 amd64 [installed]
podman/unknown 1.8.2~1 arm64
podman/unknown 1.8.2~1 armhf
```

**Comment by rhatdan** [comment]
@giuseppe Could you take a look at this?

**Comment by rhatdan** [comment]
@giuseppe Did you ever get to look at this?  Is this an issue with crun? runc?
@kolyshkin Do you know?

**Comment by giuseppe** [comment]
that is expected.  More details here: https://github.com/containers/libpod/pull/857#issue-191611537

If you'd like to have some environments variable set in the hooks, you need to explicitely add them to the hook configuration.

I've tried both runc and crun.  runc seems to leak the environment variables in the prestart hook, while crun behaves the same as the poststop hook.

I am going to close the issue since it works as expected, please add more comments or reopen the issue if there is anything more to address.

**Comment by AlbanBedel** [comment]
I understand that a minimal environment is desirable, but no PATH is a bit extreme as it break every shell script or program that use execlp or execvp.

**Comment by rhatdan** [comment]
@AlbanBedel If you add
                  "env": [
                    "PATH=/usr/local/bin:/bin:/usr/bin",
                  ]
Doesn't this solve your issue?

```
man oci-hooks
...
$ cat /etc/containers/oci/hooks.d/nvidia.json
              {
                "version": "1.0.0",
                "hook": {
                  "path": "/usr/sbin/nvidia-container-runtime-hook",
                  "args": ["nvidia-container-runtime-hook", "prestart"],
                  "env": [
                    "NVIDIA_REQUIRE_CUDA=cuda>=9.1",
                    "NVIDIA_VISIBLE_DEVICES=GPU-fef8089b"
                  ]
                },
                "when": {
                  "annotations": {
                    "^com\\.example\\.department$": ".*fluid-dynamics$"
                  }
                },
                "stages": ["prestart"]
              }
```

**Comment by AlbanBedel** [comment]
It does, my point is that having a completely empty environment is very unusual. As a casual user you write a script, test that it work, configure it as a hook and ... nothing works. Cue a frustrating debug session to then find out that the empty environment is causing everything to fall to pieces. That's just frustrating and I expect quiet some users just give up assuming OCI hooks are utterly broken.

As I wrote earlier I do understand why an empty environment is desirable from a security perspective, but it is a major usability failure, so it should be well documented. A few variables, such as PATH, could also have sensible defaults to better balance security and usability.

**Comment by rhatdan** [comment]
I tend to agree with you, but I guess we would need this added to the standard.  What do you think @giuseppe Just adding PATH=/bin:/usr/bin would solve this problem

**Comment by giuseppe** [comment]
I think we could default to the same env variables we use for containers.  What do you think?  From a security perspective it won't be any worse than what we already do for a less privileged process.

**Comment by rhatdan** [comment]
SGTM. This needs to be handled in crun and runc correct?
