### ISSUE TITLE
Allow fallthrough to non systemd cgroup if no systemd is found

### ISSUE THREAD

**Issue by darix** [containers/libpod#5658]
we run podman in our build environment to build containers. the build enviroment does not run systemd. since the upgrade to 1.8.2 the fallback to a non systemd cgroup manager is broken again.

This is the 2nd time that this regression happens. Could there be a test case added to make sure this gets noticed before a release?

```
systemd cgroup flag passed, but systemd support for managing cgroups is not available
```

The podman call is sadly not visible in our build log output but I am sure we do not force the systemd cgroup manager.

**Comment by giuseppe** [comment]
thanks for the report.

Can you please give more details about your environment?  Are you running as rootless?  Are you on cgroup v2?

**Comment by darix** [comment]
we are just calling "podman build" inside a VM.

https://github.com/openSUSE/obs-build/blob/master/build-recipe-docker#L161

(call-podman just does some setup stuff and then calls podman with those same arguments.)

FWIW: in my current failure case it is an openSUSE:Leap:15.1 kernel 4.12.14. The important bit is we **dont** have systemd running. we "boot" into our build script.

@vrothberg knows about the issue from the last time we ran into it. and asked me to open a bug so it wont happen again in the future.

**Comment by rhatdan** [comment]
@giuseppe Did you ever get a chance to look at this?

**Comment by giuseppe** [comment]
> @giuseppe Did you ever get a chance to look at this?

I've not looked at it yet.

@darix is it something that you can workaround setting explicitly the cgroup manager `--cgroup-manager=cgroupfs`?

**Comment by mlschroe** [comment]
Yes, that seems to work well for us. Thanks for the hint!
