### ISSUE TITLE
binding tests: please fix flakes

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5665]
"special_test_bindings" is frequently failing in CI: 
* [Podman system](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6224214306848768/html/integration_test.log.html) fails with "Expected 2 to be 3"
* containers_test fails with `panic: send on closed channel` [example 1](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5504924658171904/html/integration_test.log.html), [example 2](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5411324435890176/html/integration_test.log.html)

These are almost certainly race conditions, and I bet a Go expert could identify and fix in a minute or two. Could such expert please do so? I've spent far too long gazing at the code but my Go knowledge is not enough to fix this.

**Comment by vrothberg** [comment]
I can have a look with a fresh pair of eyes tomorrow; unless somebody picks up until then.

Thanks for providing logs, Ed!

**Comment by rhatdan** [comment]
@edsantiago Is this still a problem?

**Comment by edsantiago** [comment]
Since CI is currently disabled, I have no idea. Can we leave this open until CI is back?

**Comment by mheon** [comment]
@edsantiago Tests are reenabled, but I don't think I've seen these recently

**Comment by rhatdan** [comment]
Let's reopen if they return.
