### ISSUE TITLE
Regression: podman exec --preserve-fds: hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5666]
Similar to #4020 but opening as new issue because I have no idea where the root cause is. CI is failing with hangs in the --preserve-fds test. When I tried to reproduce, I got:

|  tool  | works | hangs |
| --- | --- | --- |
| podman | 1.7.0-3.fc30 | 1.8.0-4.fc30 |
| conmon | 2.0.2-1.fc30 | 2.0.13-1.fc30 |
| runc | 1.0.0-95.rc9.gitc1485a1.fc30 | 1.0.0-102.dev.gitdc9208a.fc30 |

Bizarrely, I dnf-upgraded the 'works' system to match all the versions in 'hangs' --- and everything still works. I know it's not just my systems because [this is causing CI failures](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6171437748715520/html/integration_test.log.html#t--podman-exec-preserve-fds-sanity-check--1)

Symptom:
```console
# podman run --name test1 -d docker.io/library/alpine:latest top
39c9fd570fe7634acfd66140de740472ff611f7d6be6f302927fe38bdfc816ca
# podman exec --preserve-fds 1 test1 date
Sat Mar 28 14:55:36 UTC 2020
[hangs]
```
If I try a `^C` - `!!` loop, sometimes it exits cleanly, sometimes it hangs with no output at all, but usually it just does the same thing: echo one line, hang.

_Originally posted by @edsantiago in https://github.com/containers/libpod/issues/4020#issuecomment-605459180_

**Comment by edsantiago** [comment]
Another flake: PR 5667, [ubuntu-18 remote](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5686374594510848/html/integration_test.log.html)

**Comment by giuseppe** [comment]
have you opened the fd 3 before passing it down to Podman and `podman exec --preserve-fds 1`?

Otherwise it will pass some random fd down to conmon, the runtime and in the container.  Depending on what random fd is passed down, it can end up in a hang.

Could you try with: `podman exec --preserve-fds 1 test1 date 3<> /dev/null` ?

**Comment by edsantiago** [comment]
[feeling embarrassed today]. I thought I had written all that in #4020, but nope, doesn't look like it.

Yes, I tried a huge number of variants of `3<>` and `3<` and `3>` (and/or 4, and/or 2, and/or 0). I no longer have them in my terminal history, but the gist is: nothing helps.

**Comment by giuseppe** [comment]
thanks.

The issue seems to be in conmon, the good news is that it is fixed in conmon upstream, probably as part of: https://github.com/containers/conmon/pull/139

**Comment by rhatdan** [comment]
Since this is fixed in master, I am going to close.
