### ISSUE TITLE
CI: can we get a new conmon?

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5668]
CI is still flaking with "timed out waiting for file" (#5339): [example from 2020-03-30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4841949664378880/html/system_test.log.html).

This is apparently fixed in [conmon PR 128](https://github.com/containers/conmon/pull/128) which, if I read logs correctly, made it into conmon 2.0.13; the failed log above is 2.0.12-1.fc31.

@cevich when convenient, could you do the necessary magic to get conmon updated in the CI systems? Koji shows a recent `2.0.14` build.

(And if it's not too much trouble, an updated `skopeo` also please?)

**Comment by cevich** [comment]
Yep.  And I see [the docs explaining this](https://github.com/containers/libpod/blob/master/contrib/cirrus/README.md#test_build_cache_images_task-task) need a minor update as well.
