### ISSUE TITLE
 /usr/bin/podman version returning Error: could not get runtime: eventer creation: No support for journald logging

### ISSUE THREAD

**Issue by raukadah** [containers/libpod#5679]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
On creating podman rpm from libpod master branch using make package-install command then running */usr/bin/podman version* command retruns this error.
Error: could not get runtime: eventer creation: No support for journald logging

**Steps to reproduce the issue:**

1. git clone https://github.com/containers/libpod

2. cd libpod, make package-install

**Describe the results you received:**
Installed:
  podman-remote-99:1.8.3-1585651169.git9c7410d3.fc31.x86_64                                                                                                                 

Complete!
/usr/bin/podman version
Error: could not get runtime: eventer creation: No support for journald logging
make: *** [Makefile:662: package-install] Error 125

**Describe the results you expected:**
It should return podman version

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[raukadah@ironman libpod]$ /usr/bin/podman version
Error: could not get runtime: eventer creation: No support for journald logging
```

**Output of `podman info --debug`:**

```
[raukadah@ironman libpod]$ /usr/bin/podman info --debug
Error: could not get runtime: eventer creation: No support for journald logging

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is currently failing on rdo software factory CI with the same error.

**Comment by baude** [comment]
u need to install systemd-devel

**Comment by vrothberg** [comment]
> u need to install systemd-devel

I wonder if something has changed. Didn't we default to a non-systemd backend for events before?

**Comment by raukadah** [comment]
@baude systemd-devel is installed on the system.
```
[raukadah@ironman libpod]$ rpm -qa | grep systemd-devel
systemd-devel-243.7-1.fc31.x86_64
```

**Comment by baude** [comment]
was it installed when you built it? also, the spec in the contrib might not have support for systemd-devel yet

**Comment by raukadah** [comment]
During build time, it was not getting installed. https://logserver.rdoproject.org/78/5678/f7dda3889cc05d05e387791252254a20c80b5a48/github-check/podman-package-centos-7/5acfea1/job-output.txt
```
 Podman is being compiled without the systemd build tag. Install libsystemd on 	Ubuntu or systemd-devel on rpm based distro for journald support. 
```
Message was coming. Right now after applying https://github.com/containers/libpod/pull/5683 this patch, it vanishes, I think we can close this issue.
