### ISSUE TITLE
ID namespace error when deploying almond-server via podman

### ISSUE THREAD

**Issue by minnixtx** [containers/libpod#5704]
/kind bug

**Description**

**Steps to reproduce the issue:**

<pre><code>podman run -p 3000:3000 --uidmap keep-id \
-v /dev/shm:/dev/shm \
-v $XDG_RUNTIME_DIR/pulse:/run/pulse \
-v ${XDG_CONFIG_HOME:-$HOME/.config}/almond-server:/var/lib/almond-server \
minnixtx/almond-server:arm64</code></pre>

**Describe the results you received:**
<pre><code>ERRO[0615] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument
Trying to pull quay.io/minnixtx/almond-server:arm64...
  unauthorized: access to the requested resource is not authorized
Error: unable to pull minnixtx/almond-server:arm64: 2 errors occurred:
	* Error committing the finished image: error adding layer with blob "sha256:dbad5a3d9e059ad673cb03431604f7d02d3d16a4f6bad97eab35b8db19259d0b": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument
	* Error initializing source docker://quay.io/minnixtx/almond-server:arm64: Error reading manifest arm64 in quay.io/minnixtx/almond-server: unauthorized: access to the requested resource is not authorized</code></pre>

**Describe the results you expected:**
 
I expected the Almond virtual assistant server to run and be accessible via port 3000

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.

**Output of `podman version`:**

<pre><code>Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/arm64</code></pre>

**Output of `podman info --debug`:**

<details>
<summary>debug info</summary>

<pre><code>$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.11.6
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.14, commit: '
  Distribution:
    distribution: debian
    version: "10"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  MemFree: 155422720
  MemTotal: 502472704
  OCIRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 187531264
  SwapTotal: 251232256
  arch: arm64
  cpus: 4
  eventlogger: file
  hostname: orangepizeroplus2-h5
  kernel: 5.4.28-sunxi64
  os: linux
  rootless: true
  uptime: 15h 10m 23.08s (Approximately 0.62 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/minnix/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/minnix/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/minnix/.local/share/containers/storage/volumes</code></pre>
</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

<pre><code>~$ apt list podman
Listing... Done
podman/unknown 1.8.2~140 amd64
podman/unknown,now 1.8.2~140 arm64 [installed]
podman/unknown 1.8.2~140 armhf
podman/unknown 1.8.2~140 ppc64el</code></pre>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

For context, I have been working on building an arm64 container for the Stanford OVAL virtual assistant: Github page is [here](https://github.com/stanford-oval/almond-server). After cloning their git repo, the image builds successfully using buildx and pushes to registry. My docker build command:

<pre><code>docker buildx build -t minnixtx/almond-server:arm64 --platform=linux/arm64 . --push</code></pre>

The podman command I used is the recommended one from the almond-server github page.

<details>
<summary>My Dockerfile</summary>

<pre><code>FROM docker.io/fedora:31

# Install all deps in the standard repos
RUN dnf -y module install nodejs:10 && \
    dnf -y install git curl pulseaudio-libs-devel unzip nodejs make gcc gcc-c++ libcanberra-devel atlas-devel blas-devel

# Install yarn
RUN curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN dnf -y install python yarn

RUN mkdir /opt/almond
COPY . /opt/almond
WORKDIR /opt/almond

# snowboy doesn't like building in docker, due to overlayfs bugs...
RUN rm -rf /opt/almond/node_modules && \
    yarn --network-timeout 1000000 && \
    cp -Tr /usr/local/share/.cache/yarn/v6/npm-snowboy-1.3.1-220f23f026096fe5290d7919a9f0da93ccd253f2-integrity/node_modules/snowboy/ node_modules/snowboy/ && \
    (cd node_modules/snowboy/ && yarn install --ignore-scripts --no-lockfile && yarn run install) && \
    rm -fr /usr/local/share/.cache

EXPOSE 3000
ENV THINGENGINE_HOME=/var/lib/almond-server
ENV PULSE_SOCKET=unix:/run/pulse/native

ENTRYPOINT [ "yarn", "start"]</code></pre>
</details>

My repo: https://hub.docker.com/r/minnixtx/almond-server/tags

If any more info is needed please let me know. The device is an [Orange Pi Zero Plus2 H5](http://www.orangepi.org/OrangePiZeroPlus2/) running armbian.

**Comment by mheon** [comment]
Looks like your user may not have a valid mapping in `/etc/subuid` and `/etc/subgid`. Can you provide both of those files, plus the output of `podman unshare cat /proc/self/uid_map`

**Comment by minnixtx** [comment]
/etc/subuid:

<code>minnix:100000:65536</code>

/etc/subgid:

<code>minnix:100000:65536</code>

<pre><code>$ podman unshare cat /proc/self/uid_map
         0       1000          1</code></pre>

**Comment by mheon** [comment]
Can you try a `podman system migrate` and then see if things start working?

**Comment by minnixtx** [comment]
Ok will try it and post back

**Comment by minnixtx** [comment]
I'm going to reformat and reinstall and report back. I think I've kind of screwed things up with too much fiddling around.

**Comment by minnixtx** [comment]
Still more errors:

<pre><code>$ podman system migrate
$ podman run -p 3000:3000 --uidmap keep-id -v /dev/shm:/dev/shm -v $XDG_RUNTIME_DIR/pulse:/run/pulse -v ${XDG_CONFIG_HOME:-$HOME/.config}/almond-server:/var/lib/almond-server minnixtx/almond-server:arm64
Trying to pull docker.io/minnixtx/almond-server:arm64...
Getting image source signatures
Copying blob f77d8914c709 done  
Copying blob 687c2f71b096 done  
Copying blob f42516629c75 done  
Copying blob dbad5a3d9e05 done  
Copying blob 6fec01a34141 done  
Copying blob bd1b6c7d8d9b done  
Copying blob 436bdb7986f9 done  
Copying blob 2046c413010f done  
Copying config dbc3810e02 done  
Writing manifest to image destination
Storing signatures
ERRO[0599] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument
Trying to pull quay.io/minnixtx/almond-server:arm64...
  unauthorized: access to the requested resource is not authorized
Error: unable to pull minnixtx/almond-server:arm64: 2 errors occurred:
	* Error committing the finished image: error adding layer with blob "sha256:dbad5a3d9e059ad673cb03431604f7d02d3d16a4f6bad97eab35b8db19259d0b": ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument
	* Error initializing source docker://quay.io/minnixtx/almond-server:arm64: Error reading manifest arm64 in quay.io/minnixtx/almond-server: unauthorized: access to the requested resource is not authorized</code></pre>

**Comment by rhatdan** [comment]
Could you try this as root.  This might be something to do with the user namespace?
ERRO[0599] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: invalid argument 

Also what is the output of 

$ podman unshare cat /proc/self/uid_map

**Comment by minnixtx** [comment]
Hello thanks for your help and sorry for the delay. I promise to get back to this ASAP. It is hectic here right now. Just want to say I am appreciative and haven't forgotten.

**Comment by rhatdan** [comment]
@minnixtx Any progress?

**Comment by rhatdan** [comment]
Since we have had 0 activity in a couple of months, I am going to close this. Reopen if we need to make progress.
