### ISSUE TITLE
Add support for IPv6 port binding

### ISSUE THREAD

**Issue by Perflyst** [containers/libpod#5715]
/kind feature

**Description**

Would be nice to be able to bind ports to IPv6 addresses like with IPv4. In Docker works both.

**Describe the results you expected:**

`podman pod create --name=test --share net -p 2000:0000:60:1244::2:80:80/tcp` should work without an error like

Error: unable to create pod: Invalid ip address 2000:0000:60:1244::2: address 2000:0000:60:1244::2:: too many colons in address

**Comment by rhatdan** [comment]
@mccv1r0 @mheon Would this work, if we were not parsing the address so strictly?

**Comment by mheon** [comment]
I think we'll need to make a separate copy of each port for v4 and v6 when we add ports.

**Comment by mheon** [comment]
Oh, hmmmm. This isn't by default, but only when a v6 address is specified.

Yeah, I think @rhatdan is right - this is too-aggressive parsing of the address to try and ensure it's an IPv4

**Comment by mheon** [comment]
Also - does that command you gave work in Docker? Because I'm 90% sure that specifying port numbers after an IPv6 address using an extra `:` is wrong...

**Comment by Perflyst** [comment]
Yup, I was confused in the beginning too but it does not work with [ ] (brackets) and you need to do it like this.

**Comment by aleks-mariusz** [comment]
to bump this and follow up, so specifying the ipv6 address not like the typical `[2001:db8::]`  is how it _does_ work with docker or with podman? 

just as a note, that is counter to how every other utility that supports ipv6 works (the brackets are required to delimit where the address ends and where the port is to be specified..

**Comment by mheon** [comment]
I think we're going to have to retain support for the strange and nonstandard Docker parsing, but we can at least add support for standard IPv6 parsing at the same time.

**Comment by rhatdan** [comment]
@mheon Any movement on this?  Issue for Interns?

**Comment by mheon** [comment]
Just finished up on it now

**Comment by mheon** [comment]
Fixed by #5715

**Comment by mheon** [comment]
Sorry, bu #6529
