### ISSUE TITLE
ERRO[0000] [graphdriver] - no support for overlay fs

### ISSUE THREAD

**Issue by MariusHllk** [containers/libpod#5721]
/kind bug

**Description**

On a Raspbian 10 (Butcher) with a Raspberry Pi 3 Model B Rev 1.2 I am trying to use podman for running containers/pods. It seems that the setup has a problem with the filesystem.

**Steps to reproduce the issue:**

1. podman run hello-world

**Describe the results you received:**

```
root@raspberrypi:~# podman run hello-world
ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/stor
Error: error creating libpod runtime: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing fi
```

**Describe the results you expected:**
The usual execution of a sample hello-world-container based on the sample hello-world-image from docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/arm
```

**Output of `podman info --debug`:**

```
ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver
Error: could not get runtime: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Auflistung... Fertig
podman/unbekannt,now 1.8.2~140 armhf  [installiert]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
-

**Comment by rhatdan** [comment]
Install fuse-overlayfs

**Comment by vrothberg** [comment]
@rhatdan, we're _root_ (`root@raspberrypi:~#`). I have seen this error two times in the past week but could not track it down.

**Comment by mheon** [comment]
@Django987 I think the error you pasted got cut off? Looks like we're missing some of it.

Can you check what filesystem is in use at `/var/lib/containers/storage`? Output of `mount` would help.

**Comment by rhatdan** [comment]
Since we never got feedback, I am going to close, if @MariusHllk  wants more help please reopen the PR.

**Comment by srd424** [comment]
FWIW, just seen this when the overlay module was unavailable in a VM. Installing it and modprobing it didn't help until I removed `/var/run/containers/storage/overlay/overlay-false` ..

**Comment by rhatdan** [comment]
I guess this would be nice to put in a debug message.
