### ISSUE TITLE
No config files created in ubuntu WSL2 when rootless

### ISSUE THREAD

**Issue by daltschu22** [containers/libpod#5722]
/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run `Podman info` not as root

2. Run `podman run container`  not as root

**Describe the results you received:**

No files created in the container folder

**Describe the results you expected:**

Config files created in container folder.

**Additional information you deem important (e.g. issue happens only occasionally):**
Running ubuntu 18.04 on WSL2. 

**Output of `podman version`:**
```
podman version 1.8.2
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.1
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.14, commit: '
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 6091116544
  MemTotal: 13340864512
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 4294967296
  SwapTotal: 4294967296
  arch: amd64
  cpus: 12
  eventlogger: file
  hostname: dave-pc
  kernel: 4.19.84-microsoft-standard
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.3
      commit: unknown
  uptime: 7h 8m 16.38s (Approximately 0.29 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/me/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/me/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 8
  RunRoot: /tmp/run-1000/containers
  VolumePath: /home/me/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.8.2~2 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by mheon** [comment]
We've changed rootless Podman to no longer generate configuration files in the user's home directory automatically, so this is expected behavior, I believe.

**Comment by rhatdan** [comment]
Yup this works as designed.

**Comment by daltschu22** [comment]
Thank you! I was basing my experience off this article 
https://www.redhat.com/sysadmin/podman-windows-wsl2

And couldnt find if that had changed since it was written when googling around. This is good to know. Much appreciated!

**Comment by NikolausDemmel** [comment]
Is there a way to still manually generate a default config file on demand?

**Comment by djohn156** [comment]
I just came across this issue after more than a year. Would it be possible to either provide an update to the linked article or add a statement to the installation instructions? Also it'd be really great to mention that the default value of WSL for some Linux machines (tested with Ubuntu 20.04) is 1 and still needs to be manually upgraded.

**Comment by rhatdan** [comment]
Interested in opening a PR to add those?

**Comment by djohn156** [comment]
Not sure where I should put that information, but happy to give it a try if you could point me to the right files

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
@djohn156 Most of the configuration descriptions is handled in man pages.

man podman;

**Comment by TomSweeneyRedHat** [comment]
> man podman;

or for the web page oriented
http://docs.podman.io/en/latest/markdown/podman.1.html

**Comment by djohn156** [comment]
Thanks for pointing this out. Since it's rather about the setup instructions and less about usage of podman, what about opening a respective issue in https://github.com/containers/podman.io and handling it there?

**Comment by rhatdan** [comment]
SGTM
