### ISSUE TITLE
podman build --cap-add/--cap-drop has no effect and value is not validated, contrary to buildah behavior

### ISSUE THREAD

**Issue by amarshall** [containers/libpod#5723]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Passing `--cap-add` or `--cap-drop` to `podman build` has no effect and its value is not validated. This is contrary to buildah, where it is validated and has an effect (see "additional information" below), so this does *not* appear to be a buildah bug.

For simplicity, only `--cap-add` is referred to here, but all applies also to `--cap-drop`.

**Steps to reproduce the issue:**

1. Create a Dockerfile like:
   ```
   FROM fedora:31
   RUN capsh --print && exit 1
   ```

2. Run `podman build --cap-add=cap_sys_admin .` (tested also: `--cap-add=sys_admin` and all caps variants of both).

**Describe the results you received:**

Note omission of cap_sys_admin.

> Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
>
> Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
>
> Ambient set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap

**Describe the results you expected:**

Note presence of cap_sys_admin.

> Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap+eip
>
> Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap
>
> Ambient set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap

**Additional information you deem important (e.g. issue happens only occasionally):**

- `podman build` seems to do no validation of the value of `--cap-add`, e.g. `--cap-add=nonsense` continues without error.
- `podman run` performs validation of its `--cap-add` and, unlike buildah, permits omitting the `cap_` prefix.
- `buildah` does not have this problem, so this does not appear, on the surface, to be a buildah bug. E.g. running `buildah run --cap-add=cap_sys_admin $(buildah from fedora:31) capsh --print` includes cap_sys_admin. Further, passing `--cap-add=cap_nonsense` to buildah gives an error.
- Since the buildah version bundled with my podman is a bit older, I also tested against buildah 1.14.0-dev (the only other version currently in my Fedora repos) and `--cap-add` is functioning in that version.

**Output of `buildah version`:**

```
Version:         1.14.6
Go Version:      go1.14
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.3.1
Git Commit:      
Built:           Wed Dec 31 19:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version`:** 

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.14
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.14
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  Distribution:
    distribution: fedora
    version: "32"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 57172385792
  MemTotal: 67300593664
  OCIRuntime:
    name: crun
    package: crun-0.13-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8438935552
  SwapTotal: 8438935552
  arch: amd64
  cpus: 48
  eventlogger: journald
  hostname: <redacted>
  kernel: 5.6.2-300.fc32.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-6.0.dev.gita8414d1.fc32.x86_64
    Version: |-
      slirp4netns version 0.4.3+dev
      commit: a8414d1d1629f6f7a93b60b55e183a93d10d9a1c
  uptime: 5h 25m 38.29s (Approximately 0.21 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /home/<redacted>/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.8-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 0.7.8
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  GraphRoot: /home/<redacted>/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 49
  RunRoot: /run/user/1000/containers
  VolumePath: /home/<redacted>/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.8.2-2.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical.

**Comment by TomSweeneyRedHat** [comment]
@amarshall I ran a quick test against the latest from upstream and it's working for me.  Can you easily clone from GitHub and then run it?  I think this may have been recently fixed.

**Comment by amarshall** [comment]
I installed Podman from the COPR referenced from [install docs](https://podman.io/getting-started/installation#fedora) which appears to be from latest git (1593d4c0) and can confirm `--cap-add` and `--cap-drop` work as expected.

-----

However, unrelated to this issue, running that latest podman as root even for a simple run, e.g. `sudo podman run -it --rm fedora` fails with:

```
ERRO[0000] oci runtime "runc" does not support CGroups V2: use system migrate to mitigate 
Error: this version of runc doesn't work on cgroups v2: OCI runtime error
```

Not sure why that is or if it warrants another issue (or if there is one). Running under my own account works.

**Comment by rhatdan** [comment]
Switch to crun for an OCI runtime.  runc does not yet support cgroup V2.
What OS are you running on?

**Comment by amarshall** [comment]
@rhatdan I suspect it’s a packaging problem with the Podman from the aforementioned COPR repository, as it removes several dependencies (conmon, libvarlink-util, podman-plugins) compared with the Fedora packaged podman. I’m on Fedora 32.

**Comment by rhatdan** [comment]
Then please use the packages from the distro.

**Comment by amarshall** [comment]
That’s what I do normally, but for the purposes of testing if this bug had been resolved in an unreleased version I used the development COPR repository listed in the [Podman installation docs](https://podman.io/getting-started/installation#installing-development-versions-of-podman).

Anyway, testing on Podman 1.9.1 I can confirm this is resolved.
