### ISSUE TITLE
Build packages for aarch64 Ubuntu 18.04

### ISSUE THREAD

**Issue by c0d3st0rm** [containers/libpod#5729]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
[OBS](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable) builds packages for aarch64/Ubuntu 19.10, however not for 18.04. Could the package suite on OBS also be built for aarch64 Ubuntu 18.04, to support the Raspberry Pi/other ARM devices running Ubuntu Server 18.04 for ARM?

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
@lsm5 any input on this?

**Comment by lsm5** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
> 
> /kind feature
> 
> **Description**
> [OBS](https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable) builds packages for aarch64/Ubuntu 19.10, however not for 18.04. Could the package suite on OBS also be built for aarch64 Ubuntu 18.04, to support the Raspberry Pi/other ARM devices running Ubuntu Server 18.04 for ARM?

@c0d3st0rm last time I checked there were dependency issues on the 18.04 environment and those were low on OBS admins' priority list. However, 20.04 is now available for aarch64, so maybe that's a better option for you..

**Comment by c0d3st0rm** [comment]
20.04 sounds fine, thanks!
