### ISSUE TITLE
podman info: should include podman version

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5736]
The `podman info` command does not actually include podman's own version.

**Comment by afbjorklund** [comment]
I guess it is bug-compatible with docker that way ? (it only includes server version)

**Comment by afbjorklund** [comment]
Interestingly, `podman-remote info` _does_ include the podman version.  But only for the client!

The host part of the output is the same as `podman info`, in that it only mentions Buildah version.

**Comment by alitvak69** [comment]
podman info --debug includes podman version

**Comment by afbjorklund** [comment]
It has another block of info now, so I suppose this is fixed.

before: (without the actual date, for brevity)
```
host:
registries:
store:
```

after: (without the actual date, for brevity)
```
host:
registries:
store:
version:
```

Added in 62803f8d3bacaea9956e6ec3176b223b85d260a5

The main difference seems to be date format.


podman info (partial)
```
version:
  Built: 1589615354
  GitCommit: 343ab99b39771b5084a231a2db8d3dc969f395f9
  GoVersion: go1.13.8
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev
```

podman version
```
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.13.8
Git Commit:         343ab99b39771b5084a231a2db8d3dc969f395f9
Built:              Sat May 16 09:49:14 2020
OS/Arch:            linux/amd64
```

**Comment by rhatdan** [comment]
Yes I guess we should translate the date.

**Comment by dougsland** [comment]
@edsantiago looks like your requested is fixed. Could you please double check? 
If everything is working for you, please consider closing this ticket.

```
$ git clone git@github.com:containers/libpod.git && cd libpod
$ make && sudo make install

$ podman info
<snip>
version:
  APIVersion: 1
  Built: 1590582353
  BuiltTime: Wed May 27 08:25:53 2020
  GitCommit: 119e13d4bcc3e8da903da33b291f2795b0e76e71
  GoVersion: go1.14.2
  OsArch: linux/amd64
  Version: 2.0.0-dev
```

**Comment by edsantiago** [comment]
LGTM, thank you!

**Comment by rhatdan** [comment]
@afbjorklund Please open an issue on podman-remote info to get the other information.
