### ISSUE TITLE
race: 'podman stop' does not always remove all podman mounts

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#5747]
One of the e2e tests, `podman list running container` in [test/e2e/mount_test.go](https://github.com/containers/libpod/blob/master/test/e2e/mount_test.go#L185), occasionally [flakes in CI](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5127055163523072/html/integration_test.log.html#t--podman-list-running-container--1). Basically, `podman mount` is finding an active mountpoint even after the container is `podman stopped`. Rerunning `podman mount` a second later finds no mounts, so it's pretty likely a race: maybe there's some cleanup that isn't happening in time. 

If this race condition **is OK**, that is, if it doesn't matter whether `podman mount` shows a dead mountpoint from a stopped container, then the e2e test must be fixed.

If this race condition **is not OK**, that is, if `podman stop` should guarantee that there are no mount points when it exits, then podman stop must be fixed.

Reproducer:

```bash
#!/bin/bash

set -e

T0=$SECONDS

while :;do
    cid=$(podman run -dt docker.io/library/alpine:latest top)
    podman mount --notruncate | grep -q $cid
    podman stop $cid > /dev/null
    m2=$(podman mount --notruncate)
    if [[ "$m2" =~ $cid ]]; then
        echo "FOO! Still mounted!"
        echo "$m2"
        echo "time = $(( $SECONDS - $T0 )) seconds"
        sleep 1
        echo
        echo "after sleep 1:"
        podman mount
        exit 1
    fi
    podman rm $cid >/dev/null
done
```

Sample run:
```console
# /tmp/mtest
FOO! Still mounted!
2b473b127c369cd11da3c775780ea2e693e17511534c1e296980a35443d14a70 /var/lib/containers/storage/overlay/5798db64ca882ed888a403a5398d1bb5d020c8c0bab719ba67a71b13673b4773/merged
time = 96 seconds

after sleep 1:
```
CI failure is f30; I can reproduce with podman-1.8.0-4.fc30.

Problem still present in rawhide: podman-1.8.3-0.75.dev.gitf7dffed.fc33

**Comment by rhatdan** [comment]
Well if the container is running podman stop will stop the container, then conmon realizes that the container has stopped, and then execs `podman container cleanup` to cleanup the container.  This is where the race happens.  
We could make podman stop wait for the container to enter the stop state or disappear, but it could wait for a very long time,

**Comment by mheon** [comment]
Hmmmm. I think that, right now, `podman stop` does not provide a guarantee that a container has been cleaned up immediately after exit (we instead wait for the cleanup process to do it). I'm not sure if this is desirable, though. If we want to add such a guarantee, it would be trivial to make `podman stop` call `ctr.Cleanup()` immediately before exiting.

**Comment by rhatdan** [comment]
Wouldn't that give you a race as well, in that the container would still be running?  Or at least podman container cleanup would fail.

**Comment by mheon** [comment]
I think we guarantee that the container is stopped after the `Stop()` API call - it's just that we don't actually verify that the cleanup has completed when `podman stop` exits.

**Comment by mheon** [comment]
I'll self-assign this. It's fairly low priority, but hopefully I can get to it sometime in the next few weeks.
