### ISSUE TITLE
Implementation of compose-spec

### ISSUE THREAD

**Issue by rajveermalviya** [containers/libpod#5750]
/kind feature

`compose-spec` implementation

Reference implementation in go: [github.com/compose-spec/compose-ref](https://github.com/compose-spec/compose-ref)

References:
[compose-spec.io/](https://compose-spec.io/)
[github.com/compose-spec](https://github.com/compose-spec)

**Comment by mheon** [comment]
One of the goals of Podman's APIv2 is to allow `docker compose` to run against a Podman backend, which I think satisfies the spirit of this request. The Podman team is not presently looking at making a `podman play compose` that would directly run Compose files, but if someone else were to implement and contribute one, we'd be happy to take a look and merge it.

**Comment by rajveermalviya** [comment]
> Podman's APIv2 is to allow `docker compose` to run against a Podman backend

ok, that would be great!

**Comment by rhatdan** [comment]
This is not something the core team would work on, but if the community wants to build it, we would certainly consider merging it.

**Comment by rhatdan** [comment]
We now have docker.sock support so theoretically a lot of docker-compose should now work.  Closing and waiting for community to add new features.
