### ISSUE TITLE
as it has active exec sessions: container state improper

### ISSUE THREAD

**Issue by prozyworld** [containers/libpod#5757]
现在容器不能删掉 rm -f 也不行 报as it has active exec sessions: container state improper错误

container use (rm -f) cannot delete. output error as it has active exec sessions: container state improper

Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64

**Comment by rhatdan** [comment]
I don't believe this is a bug in the master branch.  Podman1.4.4 is a very old release.  On RHEL and Centos the current suported release is podman 1.6.4 please upgrade and see if the issue is fixed.
