### ISSUE TITLE
Configuring registry.mirror causes pulls to fail

### ISSUE THREAD

**Issue by mwhahaha** [containers/libpod#5764]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Adding a [[registry.mirror]] configuration to /etc/containers/registries.conf causes podman pull (and debug) operations to fail

[[registry.mirror]]
location = '192.168.0.127:5000'
insecure = true

2. Run a podman pull

3. Fail

I've tried different container references (docker.io/ and others) and all fail in the same way.

**Describe the results you received:**

[stack@standalone ~]$ sudo podman pull centos --log-level debug
DEBU[0000] Reading configuration file "/usr/share/containers/libpod.conf" 
DEBU[0000] Merged system config "/usr/share/containers/libpod.conf": &{{false false false false false true} 0 {   [] [] []}  docker://  runc map[crun:[/usr/bin/crun /usr/local/bin/crun] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] [crun runc] [crun] [] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] systemd   /var/run/libpod -1 false /etc/cni/net.d/ [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman []   k8s.gcr.io/pause:3.1 /pause false false  2048 shm    false} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
ERRO[0000] error pulling image "centos": unable to pull centos: error getting default registries to try: toml: cannot load TOML value of type map[string]interface {} into a Go slice 

**Describe the results you expected:**

[stack@standalone ~]$ sudo podman pull centos
Trying to pull registry.access.redhat.com/centos...
  name unknown: Repo not found
Trying to pull registry.fedoraproject.org/centos...
  manifest unknown: manifest unknown
Trying to pull registry.centos.org/centos...
Getting image source signatures
Copying blob e6a50b627bcb done
Copying config 0d53c857b2 done
Writing manifest to image destination
Storing signatures
0d53c857b2243421193c25be2bd91cfd0ef1ae68b3bb33615a665e3ac2b0b64c

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[stack@standalone ~]$ podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
[stack@standalone ~]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 7a4f0dd7b20a3d4bf9ef3e5cbfac05606b08eac0'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 13846048768
  MemTotal: 16647561216
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+272+3e64ee36.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: standalone.localdomain
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-2.git21fdece.module_el8.1.0+272+3e64ee36.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 1h 11m 18.6s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /home/stack/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-1.module_el8.1.0+272+3e64ee36.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/stack/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/stack/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-2.module_el8.1.0+272+3e64ee36.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dcdh** [comment]
Can you provide all the content of the file `registries.conf` ?

I've got the same issue (and message `cannot load TOML value of type map[string]interface {} into a Go slice`) because I was missing the registry part.

This will **not** work :
```
[[registry.mirror]]
location = "container-registry.ocp4-cluster-001.sandbox.okd/openshift"
insecure = true
```

This will work:
```
[[registry]]
prefix = "quay.io/openshift"
location = "quay.io/openshift"

[[registry.mirror]]
location = "container-registry.ocp4-cluster-001.sandbox.okd/openshift"
insecure = true
```

I fall into this trap, maybe the documentation should be updated.

**Comment by mwhahaha** [comment]
So yes I had only added the [[registry.mirror]] part and not a [[registry]] as well. This seems really counter intuative. It would be useful to a fully working example similar to what you've provided in the docs. What I was trying to do is configure docker-distribution as a mirror as documented https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache and then configure podman to leverage it. When I add the [[registry]] section for a namespace now I get an error about mixing sysregistry v1/v2.

```
cat /etc/containers/registries.conf 
# For more information on this configuration file, see containers-registries.conf(5).
#
# There are multiple versions of the configuration syntax available, where the
# second iteration is backwards compatible to the first one. Mixing up both
# formats will result in an runtime error.
#
# The initial configuration format looks like this:
#
# Registries to search for images that are not fully-qualified.
# i.e. foobar.com/my_image:latest vs my_image:latest
[registries.search]
registries = ['registry.access.redhat.com', 'registry.fedoraproject.org', 'registry.centos.org', 'docker.io']

# Registries that do not use TLS when pulling images or uses self-signed
# certificates.
[registries.insecure]
registries = ['192.168.24.1:8787', 'localhost:8787', 'standalone.ctlplane.localdomain:8787']

# Blocked Registries, blocks the `docker daemon` from pulling from the blocked registry.  If you specify
# "*", then the docker daemon will only be allowed to pull from registries listed above in the search
# registries.  Blocked Registries is deprecated because other container runtimes and tools will not use it.
# It is recommended that you use the trust policy file /etc/containers/policy.json to control which
# registries you want to allow users to pull and push from.  policy.json gives greater flexibility, and
# supports all container runtimes and tools including the docker daemon, cri-o, buildah ...
# The atomic CLI `atomic trust` can be used to easily configure the policy.json file.
[registries.block]
registries = []


[[registry]]
prefix = "docker.io/tripleomaster"
[[regsitry.mirror]]
location = "192.168.0.127:5000/tripleomaster"
insecure = true
```

This yields the following error now:
```
sudo podman pull docker.io/tripleomaster/centos-binary-swift-container:current-tripleo --log-level debug
DEBU[0000] Reading configuration file "/usr/share/containers/libpod.conf" 
DEBU[0000] Merged system config "/usr/share/containers/libpod.conf": &{{false false false false false true} 0 {   [] [] []}  docker://  runc map[crun:[/usr/bin/crun /usr/local/bin/crun] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] [crun runc] [crun] [] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] systemd   /var/run/libpod -1 false /etc/cni/net.d/ [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman []   k8s.gcr.io/pause:3.1 /pause false false  2048 shm    false} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error loading CNI config list file /etc/cni/net.d/87-podman-bridge.conflist: error parsing configuration list: unexpected end of JSON input 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/tripleomaster/centos-binary-swift-container:current-tripleo" 
Trying to pull docker.io/tripleomaster/centos-binary-swift-container:current-tripleo...
DEBU[0000] Error pulling image ref //tripleomaster/centos-binary-swift-container:current-tripleo: Error initializing source docker://tripleomaster/centos-binary-swift-container:current-tripleo: error loading registries configuration: mixing sysregistry v1/v2 is not supported 
  mixing sysregistry v1/v2 is not supported
ERRO[0000] error pulling image "docker.io/tripleomaster/centos-binary-swift-container:current-tripleo": unable to pull docker.io/tripleomaster/centos-binary-swift-container:current-tripleo: unable to pull image: Error initializing source docker://tripleomaster/centos-binary-swift-container:current-tripleo: error loading registries configuration: mixing sysregistry v1/v2 is not supported 
```

**Comment by vrothberg** [comment]
Hi @mwhahaha, thanks a lot for reaching out!

Did you checkout the `containers-registries.conf(5)` [man page](https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md)?

The `[registries.search]` notation is the (old) v1 format while only v2 supports mirroring among other things. If you want to enable mirroring, you need to use v2 only.

`[registries.search]` can transformed into the `unqualified-search-registries` list while insecure registries must be explicitly configured with `insecure=true`.

**Comment by mwhahaha** [comment]
Yes I did read the man page however it's not exactly clear on what is necessary to accomplish this.  So I guess I need to figure out the correct v1 to v2 format changes required to get it working. I think my issue is that the examples aren't exactly the best for folks who don't know how this all works. Perhaps some more complex or real world examples might be beneficial.

For UX, "sysregistry v1/v2" doesn't mean anything to me. Perhaps mentioning that this is the configuration format and not some other thing would be helpful.

**Comment by mwhahaha** [comment]
Ah ha. Figured it out. So for the default centos podman config looks something like...
```
[registries.search]
registries = ['registry.access.redhat.com', 'registry.fedoraproject.org', 'registry.centos.org', 'docker.io']

[registries.insecure]
registries = ['192.168.24.1:8787', 'localhost:8787', 'standalone.ctlplane.localdomain:8787']

[registries.block]
registries = []
```

A v2 conversion with a docker.io mirror looks like...
```
unqualified-search-registries = ['registry.access.redhat.com', 'registry.fedoraproject.org', 'registry.centos.org', 'docker.io']

[[registry]]
prefix = "docker.io"
insecure = true
location = "docker.io"
[[registry.mirror]]
location = "192.168.0.127:5000"
insecure = true

[[registry]]
prefix = '192.168.24.1:8787'
insecure = true
location = '192.168.24.1:8787'

[[registry]]
prefix = 'localhost:8787'
insecure = true
location = 'localhost:8787'

[[registry]]
prefix = 'standalone.ctlplane.localdomain:8787'
insecure = true
location = 'standalone.ctlplane.localdomain:8787'
```

It should be noted (and nothing caught it) that I originally had [[regsitry.mirror]] instead of [[registry.mirror]].

Also fun fact, if you have docker-distribution setup to proxy to registry-1.docker.io you can get away with:
```
[[registry]]
prefix = "docker.io"
insecure = true
location = "192.168.0.127:5000"
```

Anyway I'll close this, but I think having a more complex example v1 to v2 conversion would be nice.

**Comment by vrothberg** [comment]
Thanks for checking @mwhahaha!
