### ISSUE TITLE
podman login doesn't accept -u -p flags

### ISSUE THREAD

**Issue by hapnermw** [containers/libpod#5772]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.attempt to login with -u and -p flags returns "Error: too many arguments, login takes only 1 argument"

2.login without -u and -p results in podman prompting for user and password - this works

**Describe the results you received:**

I'm running the fedoracoreos AMI 

fedora-coreos-31.20200310.3.0-hvm (ami-0c0261fbc08b1b65a)

I've granted the core user access to the docker socket

sudo chmod 666 /var/run/docker.sock

I'm using podman to login to an AWS ECR container repository. This EC2 instance has an IAM role with a policy granting access to this repo. Since login works when podman is run in user/pw prompt mode there is nothing wrong with this config.

The only thing wrong is that podman doesn't support its -u and -p flags.

**Describe the results you expected:**

I expect login using -u and -p to work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.8.1
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.6
  podman version: 1.8.1
host:
  BuildahVersion: 1.14.2
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.10-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: 6b526d9888abb86b9e7de7dfdeec0da98ad32ee0'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 316825600
  MemTotal: 1019379712
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 96f6022b37cbe12b26c9ad33a24677bec72a9cc3
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: ip-10-0-6-155
  kernel: 5.5.8-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 1h 23m 25.13s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/home/core/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/home/core/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/core/.local/share/containers/storage/volumes
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
I failed to replicate the issue. can you provide more info on the podman command you are using?

```
podman login -u testname -p testpassword docker.io
WARNING! Using --password via the cli is insecure. Please consider using --password-stdin
Login Succeeded!
```

**Comment by hapnermw** [comment]
Here's an example that failed:

[core@ip-10-0-6-155 ~]$ podman login –u AWS –p
"eyJwYXlsb2FkIjoiM3grZmpMT2d4bUNwZlFVVVVOdHRzZkY5MC96M1ZUa21KbzZVYWdVZTZGY0hhTmZ0NExFNVMzNjRPdC9MSkwxSTBldHlGamtYVEU2amdEdWQweTlxcHRTZnU3WWZZczZycWtRVEQ5TXNTY2gzaEtXOUhvcE93YjhaSnlqOVBLWHFCSHhYSnpsQTdxeHNGaThZcFN5MHozWmpWZnh1dkFPWkhObEhBU3ZkaE5GY0ZGSXBzWW5XR0ZCM1RyZHlxYjUyYTluaWpSTkdYNUdXTCt1akhGeVE4YmRDV2VrVDU4dUNROCs0QnhzYnphNVpScDNybEFWOHJuYUdIMW1JdmpVOTdEdTM1c2owUzNqY3c4eDNJSXFjaWZMUzZUL1gyTWZvUHpqQ3g2QkJ3TzVNVEY0RWx5TG5oMHRuTEpGSG5TMkhtYXoyKzQ5MnNBaGExQ0hVVlZEUWZaNGg0Sm9OZXdwQzRlR1pMZG50V0loWGc3VmVyRklYb3pMUVVUV0tHYk5MVWxuZklwZkFYcmJKbTg1NGh0S0M4dGNjdVVZWm52c01YODRSOTZNY290L05RQjJVVUp2bWMyZjByeVdLWExtY3hKQzFWSVl3T1dPQUl2alR6Wi9ZcmdtZFJxT0tPV1AxUmdiZ1hZVEZBekYzZ2c0WlU5RENDdldKa29oczROVmVxVHJFNGdReHdoWEQrcE1Hb3hUQ0JrVjNScXNhRTNhaWpFWi92aWk1Um1hQ2hoMWJzREE3VG5BUmlKbmpsaXMzVENnUjh0MnRMeG9hVFBPSVZRVHdJVXJBanpFOGJnRS9RK3k4Vm1HMS9xb2lRUTVtQWFLUmdFUmRDb1NDdVgwcWh3b2taQnVid1lYZGRxY0NBV3o5TVhnbnB2czFyREdIaHRiaDZuWDVrMXg1Y0hFUTdOeVdGbmhWTEtqTHJFZGtiaVZ4bEpzWSs5QXdLTVlWMFc3aFh5TUxnbmMwVmVieEIyemF1SjBpSUZveUZtTzJWNU92QVlzekV3N21ndzB1d25IU3BXL3BpalNMMzNPZXBqTjdtcnhDdGVnZGU3QWlYS3h6Ny9qODU3VlBWU1l6d2x1VjlZVE5QYkI5amkvd2ZxMS9ZZUdGQ3VLWEI5Q29WdUtZOU0yN0cxcDNpUEFINGtub3hOelFWbFQ5OXY3VkErRmhhKzlVZE9RL0JyZDFJVE1hRGpzU1Q2aDZvNmU1RVdWVVhOMkZjeFkvUm1idmRDZWIvODZjUHU3OVJIdFNqODlyOFlCT1grNlZ0NFhybVNtRU92amk5KzBMRktjRzc5TUF4M1N5WHRrS0R3a1dQblJVNDgrY3VKUHRYOWZ4ME9wVHFRd3dnbS8yTDlScGozODFIcWg0d2dLaHQrOENWNnd5aVFQOEM0d1F2UjAxVFIzVm1tY0VGd2pmMHBYaUxTNU5xMTJFT2UvZTlJZStmdWVxUHJKb2VRZE03bE9zRFEreHp3YmJCMGU1Y0FMZEUra1RDd2pMMHJLN2g5M2N6L2ZCL29Dak9NYnlNVnB0V0xlS3R2bUxtNk9GSCt0VHlpcHZRcjdyajlBeU5vd3Fkdkh6THo1MEd3bGlabkk2dktZNzE1TzdCcG9TbjJQVzBEUHdXS3lDS0pPUm4yWUVIbzJIS05LYVRIdWNCR1VOelhWYlh5N05CZ2dYblZLeWlkRkt0RVR2NDhmL0RWZG5ZWm9PZ3ZUbXpBYlRGOUtSanRGUXJzSkE3YXlHSG1BdlhqK1BGZ3FUSVNGVFpYQi9qYnVIS0diaXhGeVFzY0pKN2Vmb3dqQk1CY2toS21qcHFESUtkUXpSYUhGYlhCcEtKWVZnMG42cXB2TDAwV2RZRlFmKzR0TmhzZTd2b3dQbjFCNTRlZzFHQ29YS1Q1T3ZtS0wyZ09MR2twRTZJMGlGam91cjhNL2dDOCtpaXBPdzVLUElpRURQanpNTlhNbWZlVHVEWStCRUkwVGg0U2E1MDJ6ci9tL1NXdWx2ZCt1a1BSUTdGV2U4RUYxSTlTNkRFZVRjeG85MDg1cjQ0c1RWZkV4RlRieDJudzdjRnZsbEZpVy91ckpzMmFydTd6UFVJVXBIVUh5TmE1aU0rdz09IiwiZGF0YWtleSI6IkFRRUJBSGh3bTBZYUlTSmVSdEptNW4xRzZ1cWVla1h1b1hYUGU1VUZjZTlScTgvMTR3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURJcVE4N2VNYm94NENwZGFVQUlCRUlBN1lDemRBeHJVdnVaN2VmVEg2RXcrdWp2L3hqLzk0ZHdsZ2NHQi80Y2YvRzZCdzhLSVpQM0poZlZWZ3hYVUZyT1pBZ05xYTBSYW1sZmFsaGM9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNTg2NDU5OTIyfQ=="
778349714046.dkr.ecr.us-east-1.amazonaws.com
Error: too many arguments, login takes only 1 argument


Here's an example that succeded where the user/pw were entered via login
prompts:

[core@ip-10-0-6-155 ~]$ podman login
778349714046.dkr.ecr.us-east-1.amazonaws.com
Username: AWS
Password:
Login Succeeded!

**Comment by rhatdan** [comment]
-p requires a PASSWORDSTRING and we require you to enter the registry.  We don't hard code docker.io.

**Comment by QiWang19** [comment]
@hapnermw  `–u AWS –p ...` your dash `–` looks not correct, should be `-`

**Comment by hapnermw** [comment]
I don't understand your note. Exactly what do you think is wrong with my
failed example?

**Comment by QiWang19** [comment]
@hapnermw it will work if you change the `–u –p` to `-u -p`


podman login -u AWS -p "eyJwYXlsb2FkIjoiM3grZmpMT2d4bUNwZlFVVVVOdHRzZkY5MC96M1ZUa21KbzZVYWdVZTZGY0hhTmZ0NExFNVMzNjRPdC9MSkwxSTBldHlGamtYVEU2amdEdWQweTlxcHRTZnU3WWZZczZycWtRVEQ5TXNTY2gzaEtXOUhvcE93YjhaSnlqOVBLWHFCSHhYSnpsQTdxeHNGaThZcFN5MHozWmpWZnh1dkFPWkhObEhBU3ZkaE5GY0ZGSXBzWW5XR0ZCM1RyZHlxYjUyYTluaWpSTkdYNUdXTCt1akhGeVE4YmRDV2VrVDU4dUNROCs0QnhzYnphNVpScDNybEFWOHJuYUdIMW1JdmpVOTdEdTM1c2owUzNqY3c4eDNJSXFjaWZMUzZUL1gyTWZvUHpqQ3g2QkJ3TzVNVEY0RWx5TG5oMHRuTEpGSG5TMkhtYXoyKzQ5MnNBaGExQ0hVVlZEUWZaNGg0Sm9OZXdwQzRlR1pMZG50V0loWGc3VmVyRklYb3pMUVVUV0tHYk5MVWxuZklwZkFYcmJKbTg1NGh0S0M4dGNjdVVZWm52c01YODRSOTZNY290L05RQjJVVUp2bWMyZjByeVdLWExtY3hKQzFWSVl3T1dPQUl2alR6Wi9ZcmdtZFJxT0tPV1AxUmdiZ1hZVEZBekYzZ2c0WlU5RENDdldKa29oczROVmVxVHJFNGdReHdoWEQrcE1Hb3hUQ0JrVjNScXNhRTNhaWpFWi92aWk1Um1hQ2hoMWJzREE3VG5BUmlKbmpsaXMzVENnUjh0MnRMeG9hVFBPSVZRVHdJVXJBanpFOGJnRS9RK3k4Vm1HMS9xb2lRUTVtQWFLUmdFUmRDb1NDdVgwcWh3b2taQnVid1lYZGRxY0NBV3o5TVhnbnB2czFyREdIaHRiaDZuWDVrMXg1Y0hFUTdOeVdGbmhWTEtqTHJFZGtiaVZ4bEpzWSs5QXdLTVlWMFc3aFh5TUxnbmMwVmVieEIyemF1SjBpSUZveUZtTzJWNU92QVlzekV3N21ndzB1d25IU3BXL3BpalNMMzNPZXBqTjdtcnhDdGVnZGU3QWlYS3h6Ny9qODU3VlBWU1l6d2x1VjlZVE5QYkI5amkvd2ZxMS9ZZUdGQ3VLWEI5Q29WdUtZOU0yN0cxcDNpUEFINGtub3hOelFWbFQ5OXY3VkErRmhhKzlVZE9RL0JyZDFJVE1hRGpzU1Q2aDZvNmU1RVdWVVhOMkZjeFkvUm1idmRDZWIvODZjUHU3OVJIdFNqODlyOFlCT1grNlZ0NFhybVNtRU92amk5KzBMRktjRzc5TUF4M1N5WHRrS0R3a1dQblJVNDgrY3VKUHRYOWZ4ME9wVHFRd3dnbS8yTDlScGozODFIcWg0d2dLaHQrOENWNnd5aVFQOEM0d1F2UjAxVFIzVm1tY0VGd2pmMHBYaUxTNU5xMTJFT2UvZTlJZStmdWVxUHJKb2VRZE03bE9zRFEreHp3YmJCMGU1Y0FMZEUra1RDd2pMMHJLN2g5M2N6L2ZCL29Dak9NYnlNVnB0V0xlS3R2bUxtNk9GSCt0VHlpcHZRcjdyajlBeU5vd3Fkdkh6THo1MEd3bGlabkk2dktZNzE1TzdCcG9TbjJQVzBEUHdXS3lDS0pPUm4yWUVIbzJIS05LYVRIdWNCR1VOelhWYlh5N05CZ2dYblZLeWlkRkt0RVR2NDhmL0RWZG5ZWm9PZ3ZUbXpBYlRGOUtSanRGUXJzSkE3YXlHSG1BdlhqK1BGZ3FUSVNGVFpYQi9qYnVIS0diaXhGeVFzY0pKN2Vmb3dqQk1CY2toS21qcHFESUtkUXpSYUhGYlhCcEtKWVZnMG42cXB2TDAwV2RZRlFmKzR0TmhzZTd2b3dQbjFCNTRlZzFHQ29YS1Q1T3ZtS0wyZ09MR2twRTZJMGlGam91cjhNL2dDOCtpaXBPdzVLUElpRURQanpNTlhNbWZlVHVEWStCRUkwVGg0U2E1MDJ6ci9tL1NXdWx2ZCt1a1BSUTdGV2U4RUYxSTlTNkRFZVRjeG85MDg1cjQ0c1RWZkV4RlRieDJudzdjRnZsbEZpVy91ckpzMmFydTd6UFVJVXBIVUh5TmE1aU0rdz09IiwiZGF0YWtleSI6IkFRRUJBSGh3bTBZYUlTSmVSdEptNW4xRzZ1cWVla1h1b1hYUGU1VUZjZTlScTgvMTR3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURJcVE4N2VNYm94NENwZGFVQUlCRUlBN1lDemRBeHJVdnVaN2VmVEg2RXcrdWp2L3hqLzk0ZHdsZ2NHQi80Y2YvRzZCdzhLSVpQM0poZlZWZ3hYVUZyT1pBZ05xYTBSYW1sZmFsaGM9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNTg2NDU5OTIyfQ==" 778349714046.dkr.ecr.us-east-1.amazonaws.com
WARNING! Using --password via the cli is insecure. Please consider using --password-stdin
Login Succeeded!

**Comment by hapnermw** [comment]
You are right. That is strange. I likely copied the original command from
an example that had the wrong dash character. I'll try to find it.

**Comment by QiWang19** [comment]
@hapnermw ok, thanks

**Comment by hapnermw** [comment]
Thanks for catching that. You can close the issue.

Sorry to have taken your time with such a stupid; but, hard to see problem.

Somewhere there is an example login with this issue ...

**Comment by QiWang19** [comment]
Sure. Feel free to open an issue if you have other questions.

**Comment by TomSweeneyRedHat** [comment]
@hapnermw If you do track down that bad example, please do let us know or better yet, open up a PR.
