### ISSUE TITLE
Ansible Role for Podman

### ISSUE THREAD

**Issue by hswong3i** [containers/libpod#5773]
I am now maintenance an Ansible Role for Podman installation (https://github.com/alvistack/ansible-role-podman), by building the source code manually and install for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. under https://github.com/containers/podman.io/blob/master/getting-started/installation.md#installing-development-versions-of-podman section?

**Comment by mheon** [comment]
I have no opposition. @TomSweeneyRedHat Thoughts?

PRs to podman.io are welcome - github.com/containers/podman.io

**Comment by TomSweeneyRedHat** [comment]
@hswong3i I'd very much welcome a PR for that.  Thanks!

**Comment by rhatdan** [comment]
@hswong3i Have you been able to work on this?

**Comment by hswong3i** [comment]
Sorry for my late update, PR now goes to https://github.com/containers/podman.io/pull/242, for installing nix-based static binary by using Ansible Role ;-)

**Comment by rhatdan** [comment]
Since this no longer applies to this repo, closing.
