### ISSUE TITLE
Rootful connection refused for Java app

### ISSUE THREAD

**Issue by Fodoj** [containers/libpod#5791]
```
Podman 1.8.2
Fedora 31 Workstation
```

Given this Containerfile:

```
FROM openjdk:15

RUN yum install unzip -y && \
    curl https://languagetool.org/download/LanguageTool-4.9.zip -o lt.zip

RUN unzip lt.zip && \
    mv LanguageTool-4.9 /opt/languagetool

ADD startup.sh /startup.sh

EXPOSE 8081

CMD /startup.sh
```

And this startup.sh:

```
#!/bin/sh

/usr/bin/java -cp /opt/languagetool/languagetool-server.jar org.languagetool.server.HTTPServer --allow-origin '*'
```

I then run `podman build . -t langtool:latest`, once for my regular user and once for root user.

Then when I run it as regular user with `podman run -p 8081:8081 localhost/langtool:latest` and try to access it `curl localhost:8081` I get, as expected:

```
Error: Missing arguments for LanguageTool API. Please see https://languagetool.org/http-api/swagger-ui/#/default
```

When I run the same command as root, all I get is:

```
curl: (7) Failed to connect to localhost port 8081: Connection refused
````

Same happens if I curl container IP etc. If I exec into container and try from the inside, it works fine.

Seems like while rootless slirp2netns works fine, regular rootfull CNI has some issues in this case.

It gets weirder when I try to run, for example, community nginx image:

```
podman run -P nginx
```

Then, when I compare two containers:

```
# podman ps
CONTAINER ID  IMAGE                           COMMAND               CREATED         STATUS             PORTS                    NAMES
2f1013925bdb  docker.io/library/nginx:latest  nginx -g daemon o...  30 seconds ago  Up 29 seconds ago  0.0.0.0:45181->80/tcp    interesting_dubinsky
aa709df10d30  localhost/langtool:latest       /bin/sh -c /start...  39 seconds ago  Up 39 seconds ago  0.0.0.0:36817->8081/tcp  elastic_lumiere
```

````
# curl localhost:45181
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

```
# curl localhost:36817
curl: (7) Failed to connect to localhost port 36817: Connection refused
````

Nothing suspicious in `ss -tupln`:

```                                             
tcp       LISTEN     0          4096                                         0.0.0.0:36817              0.0.0.0:*        users:(("conmon",pid=87819,fd=5),("podman",pid=87704,fd=17),("podman",pid=87704,fd=16))                                                       
tcp       LISTEN     0          4096                                         0.0.0.0:45181              0.0.0.0:*        users:(("conmon",pid=87976,fd=5),("podman",pid=87860,fd=17),("podman",pid=87860,fd=16))     
```

No clear difference in iptables rules:

```
# iptables-save|grep '45181'
-A CNI-DN-83908cab65618efe2e9f7 -s 10.88.0.27/32 -p tcp -m tcp --dport 45181 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-83908cab65618efe2e9f7 -s 127.0.0.1/32 -p tcp -m tcp --dport 45181 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-83908cab65618efe2e9f7 -p tcp -m tcp --dport 45181 -j DNAT --to-destination 10.88.0.27:80
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"podman\" id: \"2f1013925bdba80c5e4468024e012c398e1bd4b8ba75dcb366eb6a7d2b2d434e\"" -m multiport --dports 45181 -j CNI-DN-83908cab65618efe2e9f7
```

```
# iptables-save|grep '36817'
-A CNI-DN-6e9529d0cf961e8ec49e2 -s 10.88.0.26/32 -p tcp -m tcp --dport 36817 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-6e9529d0cf961e8ec49e2 -s 127.0.0.1/32 -p tcp -m tcp --dport 36817 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-6e9529d0cf961e8ec49e2 -p tcp -m tcp --dport 36817 -j DNAT --to-destination 10.88.0.26:8081
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"podman\" id: \"aa709df10d30b185ed89987c9cf26aaa851c96d304cc37ee502a68bf2e5f90d4\"" -m multiport --dports 36817 -j CNI-DN-6e9529d0cf961e8ec49e2
```

But in case of Java app, I get connection refused and in case of nginx it seems to just work.

And when I do the same rootless, Java app just works.

So I am a bit confused whats happening here, any advice?

**Comment by Fodoj** [comment]
Something to add - if I use `--network host` it works fine, of course.

**Comment by Fodoj** [comment]
Also could be of interest - if I run `firewall-cmd --reload` then it still does not work, but instead of `connection refused` it times out.

**Comment by Fodoj** [comment]
I figured out the problem - by default LangTool server runs only on localhost, so it does not listen on the interface that CNI gives to the container. Adding `--public` option solves the issue.

I was just confused it was working just fine in rootless mode, without `--public`. I guess it makes sense it works this way, but it was not obvious and confused the hell out of me.

In any case, excuse me for the spam. I hope this issue with detailed problem description will be helpful for someone who ends up with similar situation. Closing it now.

P.S.

Still, strange that `firewall-cmd --reload` breaks connections. And may be behaviour of `slirp4netns`/rootless should be aligned with rootful/CNI behaviour.

**Comment by mheon** [comment]
@Fodoj The firewall thing is known, and has a separate bug (can't find the link right now, sorry) - the brief version is that `firewall-cmd --reload` removes all non-permanent rules, which our container rules are counted as (making them permanent would let them survive reboot, which would be bad for different reasons). I'm looking to add a command that will re-initialize container networks to re-add the rules, which isn't exactly an optimal solution, but is better than our current one.
