### ISSUE TITLE
eBPF not supported: OCI runtime error

### ISSUE THREAD

**Issue by yellowhat** [containers/libpod#5795]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
Hi,
I would like to use the `--device` option, but I get the following error:
```
$  sudo podman run -it --rm --device=/dev/dri/card0:/dev/dri/card0 archlinux
Error: eBPF not supported: OCI runtime error
```
Instead if I do not use the `--device` option it works as expected.
Is there something wrong with my kernel configuration?

**Steps to reproduce the issue:**
1. `sudo podman run -it --rm --device=/dev/dri/card0:/dev/dri/card0 archlinux`
2.
3.

**Describe the results you received:**
`Error: eBPF not supported: OCI runtime error`

**Describe the results you expected:**
Container running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.14.1
Built:              Sun Apr 12 10:09:43 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.14.1
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v2
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.11, commit: ff9d97a08d7a4b58267ac03719786e4e7258cecf'
  Distribution:
    distribution: gentoo
    version: unknown
  MemFree: 9677873152
  MemTotal: 16494366720
  OCIRuntime:    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: janis
  kernel: 5.6.3
  os: linux
  rootless: false
  uptime: 1h 55m 52.78s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 0.7.8
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  GraphRoot: /home/vasco/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 8
  RunRoot: /run/user/1000
  VolumePath: /home/vasco/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
[ebuild   R    ] app-emulation/libpod-1.8.2::gentoo  USE="rootless -apparmor -btrfs (-selinux)" 0 KiB
```

**Comment by giuseppe** [comment]
the devices controller on cgroup v2 uses eBPF.

Secure Boot might be blocking eBPF (`man 7 kernel_lockdown`), could you please verify if that is the case by disabling it?

**Comment by yellowhat** [comment]
Yes secure boot is disabled.

Thanks

**Comment by giuseppe** [comment]
does eBPF generally work?  Are you able to use `execsnoop`?

**Comment by yellowhat** [comment]
Sorry, how can I test eBPF?
I have:
```
$ execsnoop
command not found: execsnoop
```

Thanks

**Comment by yellowhat** [comment]
I solved by enabling the flag bpf for app-emulation/crun.

Thanks

**Comment by giuseppe** [comment]
thanks for letting me know.  Is it something that should be fixed in the gentoo package?

**Comment by yellowhat** [comment]
Maybe enable by default the bpf flag for crun?

**Comment by giuseppe** [comment]
> Maybe enable by default the bpf flag for crun?

it is, but dependencies must be installed.
