### ISSUE TITLE
Is podman run -dt command option defined or deprecated? 

### ISSUE THREAD

**Issue by GrooveCS** [containers/libpod#5810]
/kind feature

**`podman run -dt` option not defined or labeled deprecated**
The current [podman-run.1.md](https://github.com/containers/automation_sandbox/blob/master/docs/source/markdown/podman-run.1.md) page does not list this option. It should be listed if valid or marked deprecated if it been replaced. 

Several reliable source tutorials and websites are using the option "`-dt`" yet the official documentation doesn't contain this option. 

**Examples**

1. Blog Article - _Podman: Managing pods and containers in a local container runtime_ in the section labeled [Add a container to a pod](https://developers.redhat.com/blog/2019/01/15/podman-managing-containers-pods/).

![Podman_ Managing pods and containers in a local container runtime - Red Hat Developer](https://user-images.githubusercontent.com/1635152/79242865-d84ba980-7e42-11ea-8966-e7ccf39769b8.jpg)

1. Enable Sysadmin Article - _Configuring container networking with Podman_ in the section labeled [Communicate between a root full container and the host](https://www.redhat.com/sysadmin/container-networking-podman).

![Configuring container networking with Podman _ Enable Sysadmin](https://user-images.githubusercontent.com/1635152/79242771-ba7e4480-7e42-11ea-9993-88c55f3b59a1.jpg)

**Comment by mheon** [comment]
`-dt` is not a single option, but a combination of `-d` and `-t` - run detached, with a terminal. Docker allows merging single-letter flags together like this (`-dit` is also valid, for example - `-d`, `-i`, `-t`), and Podman has inherited this support; I'm honestly not a fan because of issues of clarity, as seen here.

**Comment by rhatdan** [comment]
In most command line tools a single `-` indicates single letter options,  As @mheon Says they can be combined.
For example
`ls -latr`
Double `--` indicates long options  `--detach --tty` for example.

I don't believe this is an issue.
