### ISSUE TITLE
Arbitrary name for infra container

### ISSUE THREAD

**Issue by matthubb** [containers/libpod#5822]
/kind feature

**Description**

I would like to be able define _and_ manage the execution of a pod using a combination of the `podman-generate-systemd` and the [Shareable Services](https://www.redhat.com/sysadmin/podman-shareable-systemd-services) techniques, and be able to use these unit files as versioned, re-deployable configuration.

The sticking point seems to be the `.service` file for the infrastructure container (e.g. `pod-mytestpod.service`).

Pod creation / recreation could be handled in `ExecStartPre` / `ExecStopPost`, maybe. But I can't see a way of individually starting / stopping the infrastructure container without knowing its `b9bd69f9f12d-infra` style name in advance and I can't see a way of controlling the name given to the infrastructure container. So the unit file has to be customised to the instance of the pod? A predictably named infrastructure container might avoid this.

Any suggestions regarding how to extend _Shareable Services_ to pods would be appreciated.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @matthubb! We are tracking work for this in https://github.com/containers/libpod/issues/4875. I will find time to tackle that in May.
