### ISSUE TITLE
META: Podman Workflow Tombstone

### ISSUE THREAD

**Issue by bcstinch** [containers/libpod#5828]
This is a sort of meta issue where we wanted to enumerate how we were trying to use podman for some simple deployment cases and wondering if we're missing the mark and potentially chasing antipatterns. It's entirely possible that this is a RTFM moment for the community, if that's the case I hope this is a good sort of tombstone issue that people find. It originated as a discussion on IRC with @mheon @baude, but some of @baude suggestions invoked @vrothberg by name (hence tagging to get continuity). The echo-chamber that is responsible for this mess is @bcstinch and @storrgie.

All of this is being run on Fedora 31 server, fresh baremetal install.

```
podman --version
podman version 1.8.2
```
```
slirp4netns --version
slirp4netns version 0.4.0-beta.3+dev
commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
```

We're picking a simple application deployment where we have an application server dependent on a rdmbs server. In this case it's mattermost and postgres. Both of which we're consuming containers from the docker registry.

We're trying to work through a "lifecycle" of the application to ensure that we are prepared to manage this thing over its lifecycles for our users. For example here is the use case:

 - start with a mattermost instance at 5.16 and a postgres instance at 11
 - consume updates to mattermost, say 5.16->5.17 and 5.17->5.18
 - consume updates to postgres, say 11->12
 - consume more updates to mattermost, running all the way up to current day (e.g. 5.22 is about to release)

We're going to just go through changing mattermost instances as it's a bit easier to explain. We know that moving from postgres 11 to 12 requires some level of intervention, more than just pulling and starting a new container.

__Goals:__

 - operate the containers ephemerally, modifying nothing within them
 - minimal intervention within the containers (e.g. we know we'll have to shell in for pg_dumpall to migrate from 11 to 12, but thats not changing any configuration files)
 - volume binds for all persistent data, ensuring continuity as we lifecylce updates on the two dependent systems.
 - rootless instancing, running as a "system" user with subuid/subgid mapping, managed by systemd units (this may not be covered in our examples, but it's worth mentioning our intent)

to hit on that last point we have a little bit of work to do:

```
groupadd -g 800 mattermost
useradd -u 800 -g 800 -c "System Account for Mattermost" -d /opt/mattermost -s /sbin/nologin mattermost
usermod --add-subuids 200000-265535 --add-subgids 200000-265535 mattermost
sudo -u mattermost mkdir /opt/mattermost/socket
sudo -u mattermost mkdir /opt/mattermost/postgres
sudo -u mattermost mkdir /opt/mattermost/data
sudo -u mattermost mkdir /opt/mattermost/config
sudo -u mattermost mkdir /opt/mattermost/logs
sudo -u mattermost mkdir /opt/mattermost/plugins
sudo -u mattermost chmod 777 /opt/mattermost/socket
sudo -u mattermost chmod 777 /opt/mattermost/postgres
sudo -u mattermost chmod 777 /opt/mattermost/data
sudo -u mattermost chmod 777 /opt/mattermost/config
sudo -u mattermost chmod 777 /opt/mattermost/logs
sudo -u mattermost chmod 777 /opt/mattermost/plugins
```

This basically:

 - creates the group and user account
 - creates the subuid/subgid mapping
 - creates an area for us to persist data from these containers
 - sets the permissions wide open because the containers will be writing as "other" due to subuid/subgid mapping (maybe this is a very bad practice)
 
Forks in the road, all related to networking:

 - Fork 1: __use podman pods__
 - Fork 2: __use named sockets via volume binds__
 - Fork 3: __use host networking and conventional numerical socket binds__
 - Fork 4: __use cni while rootful with more complex networking__

We'll dig into each of these forks in the road:

__Fork 1:__

 - seems like the way that we should be "grouping" containers
 - allows for shared network namespace so containers can talk via localhost
 
this feels like the most __ideal__ way to handle this entire situation (putting containers in pods), however we run into a failure case quite quickly:

Initial Instance:
```
sudo -u mattermost podman pod create --name test-pod --publish 8065:8065

sudo -u mattermost podman run -dt --pod test-pod -e POSTGRES_PASSWORD=password -e POSTGRES_USER=mattermost -e POSTGRES_DB=mattermost --volume /opt/mattermost/postgres:/var/lib/postgresql/data:Z docker.io/postgres:12

sudo -u mattermost podman run -dt --pod test-pod --name mattermost-test -e MM_SQLSETTINGS_DRIVERNAME=postgres -e MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:password@localhost:5432/mattermost?sslmode=disable -e MM_SERVICESETTINGS_SITEURL=http://0.0.0.0 --volume /opt/mattermost/data:/mattermost/data:Z --volume /opt/mattermost/logs:/mattermost/logs:Z --volume /opt/mattermost/config:/mattermost/config:Z --volume /opt/mattermost/plugins:/mattermost/client/plugins:Z docker.io/mattermost/mattermost-team-edition:release-5.16


```

Update Mattermost:
```
sudo -u mattermost podman stop mattermost-test

sudo -u mattermost podman rm mattermost-test

sudo -u mattermost podman run -dt --pod test-pod --name mattermost-test -e MM_SQLSETTINGS_DRIVERNAME=postgres -e MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:password@localhost:5432/mattermost?sslmode=disable -e MM_SERVICESETTINGS_SITEURL=http://0.0.0.0 --volume /opt/mattermost/data:/mattermost/data:Z --volume /opt/mattermost/logs:/mattermost/logs:Z --volume /opt/mattermost/config:/mattermost/config:Z --volume /opt/mattermost/plugins:/mattermost/client/plugins:Z docker.io/mattermost/mattermost-team-edition:release-5.17
```

At this state we no longer can hit the application at 8065. We fail to see a response via a remote machine, or via running curl on the metal itself. This is __intermittent__, it happens about 50% of the time from what we can tell (doing it about 10 times).

In discussions on IRC we were informed that we'd likely need to "restart the pod". Or maybe we simply need to restart an underlying network service to free up that port again. However this leads into likely some RTFM style feedback we need to see (maybe the manuals are incomplete, maybe we're jackasses):

 - Should we be running our systemd units at the "pod" level?
    + we had been composing each one of our containers into their own units via cherrypicking from `podman generate systemd`
    + if instead we just managed the containers "participation" in the pod via directly invoking podman and kept the pod running with a systemd unit we could:
        * `systemctl stop mattermost` (which stops the pod)
        * `podman rm mattermost-test`
        * `podman <invoke everything to create new mattermost-test from new release tag>`
        * `systemctl start mattermost` (which starts the pod)
 - Why does the pod need to be restarted? Is this... intended behavior? Is something in the background failing silently which kills that forwarding to the port (is it even forwarding?)?

__Fork 2:__

 - seems like the easiest way to handle specifically mattermost, which explicitly supports socket interaction via volume binds
 - other applications will not necessarily support this, so while it's easy to get things working it's not necessarily a generalizable approach to say... hosting a jistsi instance

```
sudo mkdir -p /opt/mattermost/socket

sudo chmod -R 777 /opt/mattermost

sudo chown -R mattermost:mattermost /opt/mattermost

sudo -u mattermost podman run -dt -e POSTGRES_PASSWORD=password -e POSTGRES_USER=mattermost -e POSTGRES_DB=mattermost --volume /opt/mattermost/socket:/var/run/postgresql:Z --volume /opt/mattermost/postgres:/var/lib/postgresql/data:Z docker.io/postgres:12 

sudo -u mattermost podman run -dt -e MM_SQLSETTINGS_DRIVERNAME=postgres -e MM_SQLSETTINGS_DATASOURCE=postgres:///mattermost?host=/mattermost/socket -e MM_SERVICESETTINGS_SITEURL=http://0.0.0.0 --volume /opt/mattermost/socket:/mattermost/socket:Z --publish 8065:8065 --volume /opt/mattermost/data:/mattermost/data:Z --volume /opt/mattermost/logs:/mattermost/logs:Z --volume /opt/mattermost/config:/mattermost/config:Z --volume /opt/mattermost/plugins:/mattermost/client/plugins:Z docker.io/mattermost/mattermost-team-edition
```

We can then go throughout lifecycling and everything basically works fine.

__Fork 3:__

 - not using pods, but using host networking so we're able to ensure that containers can communicate with eachother
 - we think this is running rootless, however we're confused about how this is running rootless and using host networking (shared network namespaces here?)

```
sudo -u mattermost podman run -dt -e POSTGRES_PASSWORD=password -e POSTGRES_USER=mattermost -e POSTGRES_DB=mattermost --net=host --publish 127.0.0.1:5432:5432 --volume /opt/mattermost/postgres:/var/lib/postgresql/data:Z docker.io/postgres:12

sudo -u mattermost podman run -dt -e MM_SQLSETTINGS_DRIVERNAME=postgres -e MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:password@127.0.0.1:5432/mattermost?sslmode=disable -e MM_SERVICESETTINGS_SITEURL=http://0.0.0.0 --publish 8065:8065 --net=host --volume /opt/mattermost/data:/mattermost/data:Z --volume /opt/mattermost/logs:/mattermost/logs:Z --volume /opt/mattermost/config:/mattermost/config:Z --volume /opt/mattermost/plugins:/mattermost/client/plugins:Z docker.io/mattermost/mattermost-team-edition
```

We can then go throughout lifecycling and everything basically works fine.

__Fork 4:__

Instead of documenting this case, we're just sort of waving our hands at it. In our "pre-podman-lives" we'd used LXC directly and we'd created bind->vlan->bond interface stacks that we would use directly with the `veth`. We feel like we could do this but we didn't want to abandon the idea of podman rootless (which would be required if we wanted to use this type of networking).

__Conclusion__:

We're inclined to, at this stage, choose "fork 3" as our generalized approach to ensuring container-to-container networking. It's well understood (aside from our question of how this is working rootlessly) and allows us to continue in our adoption of podman. We're wanting really to use "fork 1" as our approach, but we're confused as to why we're loosing communications with the container itself.

The ideal is that we adopt whatever upstream considers to be golden path while balancing doing things explicitly/understandably enough.

**Comment by storrgie** [comment]
This is for sure related to the inquiry we asked issue #5740.

**Comment by rhatdan** [comment]
The 777 is incredibly dangerous,  If you want a bunch of different users able to write to the same files/directories, then

chmod 770 and chown root:mattermost ...

Than all of your user accounts need to be in the mattermost group.
>

**Comment by rhatdan** [comment]
I think using host networking would be fine for this as well.

**Comment by storrgie** [comment]
> The 777 is incredibly dangerous, If you want a bunch of different users able to write to the same files/directories, then
> 
> chmod 770 and chown root:mattermost ...
> 
> Than all of your user accounts need to be in the mattermost group.
>

How do you account for the container being run rootless and being uid/gid remapped? In this case the container would be writing files with the uid, example 200166.

**Comment by storrgie** [comment]
> I think using host networking would be fine for this as well.

Can you speculate on why fork 1 is unreliable? Is it intended that we always need to reboot the pod?

**Comment by rhatdan** [comment]
On 4/15/20 14:23, bcstinch wrote:
>
> This is a sort of meta issue where we wanted to enumerate how we were
> trying to use podman for some simple deployment cases and wondering if
> we're missing the mark and potentially chasing antipatterns. It's
> entirely possible that this is a RTFM moment for the community, if
> that's the case I hope this is a good sort of tombstone issue that
> people find. It originated as a discussion on IRC with @mheon
> <https://github.com/mheon> @baude <https://github.com/baude>, but some
> of @baude <https://github.com/baude> suggestions invoked @vrothberg
> <https://github.com/vrothberg> by name (hence tagging to get
> continuity). The echo-chamber that is responsible for this mess is
> @bcstinch <https://github.com/bcstinch> and @storrgie
> <https://github.com/storrgie>.
>
> All of this is being run on Fedora 31 server, fresh baremetal install.
>
> |podman --version podman version 1.8.2 |
> |slirp4netns --version slirp4netns version 0.4.0-beta.3+dev commit:
> bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e |
>
> We're picking a simple application deployment where we have an
> application server dependent on a rdmbs server. In this case it's
> mattermost and postgres. Both of which we're consuming containers from
> the docker registry.
>
> We're trying to work through a "lifecycle" of the application to
> ensure that we are prepared to manage this thing over its lifecycles
> for our users. For example here is the use case:
>
>   * start with a mattermost instance at 5.16 and a postgres instance at 11
>   * consume updates to mattermost, say 5.16->5.17 and 5.17->5.18
>   * consume updates to postgres, say 11->12
>   * consume more updates to mattermost, running all the way up to
>     current day (e.g. 5.22 is about to release)
>
> We're going to just go through changing mattermost instances as it's a
> bit easier to explain. We know that moving from postgres 11 to 12
> requires some level of intervention, more than just pulling and
> starting a new container.
>
> *Goals:*
>
>   * operate the containers ephemerally, modifying nothing within them
>   * minimal intervention within the containers (e.g. we know we'll
>     have to shell in for pg_dumpall to migrate from 11 to 12, but
>     thats not changing any configuration files)
>   * volume binds for all persistent data, ensuring continuity as we
>     lifecylce updates on the two dependent systems.
>   * rootless instancing, running as a "system" user with subuid/subgid
>     mapping, managed by systemd units (this may not be covered in our
>     examples, but it's worth mentioning our intent)
>
> to hit on that last point we have a little bit of work to do:
>
> |groupadd -g 800 mattermost useradd -u 800 -g 800 -c "System Account
> for Mattermost" -d /opt/mattermost -s /sbin/nologin mattermost usermod
> --add-subuids 200000-265535 --add-subgids 200000-265535 mattermost
> sudo -u mattermost mkdir /opt/mattermost/socket sudo -u mattermost
> mkdir /opt/mattermost/postgres sudo -u mattermost mkdir
> /opt/mattermost/data sudo -u mattermost mkdir /opt/mattermost/config
> sudo -u mattermost mkdir /opt/mattermost/logs sudo -u mattermost mkdir
> /opt/mattermost/plugins sudo -u mattermost chmod 777
> /opt/mattermost/socket sudo -u mattermost chmod 777
> /opt/mattermost/postgres sudo -u mattermost chmod 777
> /opt/mattermost/data sudo -u mattermost chmod 777
> /opt/mattermost/config sudo -u mattermost chmod 777
> /opt/mattermost/logs sudo -u mattermost chmod 777 /opt/mattermost/plugins|
||

**Comment by storrgie** [comment]
Sorry I'm not sure how to parse above, I think the only comment was `||` ?

**Comment by rhatdan** [comment]
That was unintentional.  I have no idea how that happened.

**Comment by rhatdan** [comment]
If the container is launched by a user in that group then we could leak the GroupID into the roootless container, and the processes would be allowed to write, by setting an annotation and using crun.

```
man podman run 
...
       Note:  if  the  user  only  has  access rights via a group, accessing the device from
       inside a rootless container will fail. The crun(1) runtime offers  a  workaround  for
       this by adding the option --annotation run.oci.keep_original_groups=1.
```
Anyways maybe @giuseppe @vrothberg @mheon Might have other ideas.

**Comment by storrgie** [comment]
> If the container is launched by a user in that group then we could leak the GroupID into the roootless container, and the processes would be allowed to write, by setting an annotation and using crun.
> 
> ```
> man podman run 
> ...
>        Note:  if  the  user  only  has  access rights via a group, accessing the device from
>        inside a rootless container will fail. The crun(1) runtime offers  a  workaround  for
>        this by adding the option --annotation run.oci.keep_original_groups=1.
> ```
> 
> Anyways maybe @giuseppe @vrothberg @mheon Might have other ideas.

We may be using this wrong, it doesn't appear to "buy" us anything in the sense that every folder would have to be created by the rootless container with the parent folder set to `o+rwx`. Once the container is only creating files it seems that we can drop the `o` permissions with this annotation in place.

Simple example case would be starting up a postgres rootless container with the annotation in place and having the `--volume /opt/mattermost/postgres:/var/lib/postgresql/data:Z` assignment.

**Comment by rhatdan** [comment]
If the parent container is writable by the shared group, then it should work.

**Comment by storrgie** [comment]
> If the parent container is writable by the shared group, then it should work.

yeah, currently using `chmod g+s` to setgid on the parent folder is the approach we're taking.

**Comment by storrgie** [comment]
In an effort to clean up. We're generally taking "fork 3" as enumerated above. We've been spending a good deal of time trying to get systemd units to play nice with lifecycling podman containers.... overall I'm incredibly thankful podman exists!

This can be closed, I just wanted others to find this when they started their journey to do deployments with cni/rootless/other ideas.

**Comment by storrgie** [comment]
Wanted to come back and provide another update since the intent was always a "tombstone" for others to find when encountering the same things. We'd optioned for fork 3 when beginning deployments, it worked quite fine for very simple things (e.g. postgres is quite a well maintained delightfully simple container that binds to a singular port). This `--net=host` option falls down quite hard for some more complex softwares (e.g. gitlab currently packages itself as an 'omnibus' that has tens of sub-systems doing inter-container networking).

What we ended up on was to utilize the `--network=container:<container>`... which sort of gives us a "pod-esq" experience of inter-linking containers through the same networking namespace. We're operating all containers as rootless, launched by systemd units, where we're handling the co-dependency through systemd unit features like `Requires` and `PartOf`. It's working, in a way that seems verbose/understandable. We'll probably come back to update this as we continue to progress with deployments that are more complex but still are on non-Kubernetes type systems.
