### ISSUE TITLE
Builds for podman 1.9.0  keep failing on SuSE build service

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#5833]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

May be it has to do with these messages:

`[  123s] GOPATH=/usr/src/packages/BUILD GO111MODULE=off /usr/bin/go generate ./cmd/podman/varlink/...
[  123s] warning: "./cmd/podman/varlink/..." matched no packages
[  123s] GOPATH=/usr/src/packages/BUILD GO111MODULE=off /usr/bin/go build -tags 'apparmor exclude_graphdriver_devicemapper seccomp systemd varlink' -ldflags '"-X main.buildInfo=1586967300"' -o bin/podman github.com/containers/libpod/cmd/podman
[  189s] # github.com/containers/libpod/cmd/podman/shared
[  189s] src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:70:42: undefined: iopodman.Create
[  189s] src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:71:7: undefined: iopodman.Create
[  189s] src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:317:34: undefined: iopodman.Create
[  190s] debian/rules:37: recipe for target 'override_dh_auto_build' failed
[  190s] make[1]: *** [override_dh_auto_build] Error 2
[  190s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[  190s] debian/rules:26: recipe for target 'build' failed
[  190s] make: *** [build] Error 2`

**Comment by rhatdan** [comment]
@alitvak69 Is this still a problem?

**Comment by alitvak69** [comment]
Not please close the issue.  Sorry for allowing it to go stale.
