### ISSUE TITLE
Non-root container user can't access mounted host directory

### ISSUE THREAD

**Issue by mlezajic** [containers/libpod#5838]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After upgrading from podman **v1.6.4** to a current dev version from git master (**2.0.0-dev**) i am no longer able to access files and/or directories on the host respectively on a mounted volume the way i used to be when i was still using **v1.6.4**. I would guess that this is most likely not a bug but some sort of configuration problem i need help with.

**Steps to reproduce the issue:**

I use podman in rootless mode, so i have created a dedicated technical user called <code>fwd</code> to operate podman.

1. As user <code>fwd</code> start a container with a mounted volume: 

   ```
   podman run --user $(id -u):$(id -g) -dit --volume /tmp/testdir:/tmp/testdir --name centos 
   registry.centos.org/centos:8
   ```
   where <code>id -u</code> is <code>1020</code> and <code>id -g</code> is <code>1020</code>.

   I have to specify <code>--user $(id -u):$(id -g)</code> since i don't want the 'active' user within 
   the container to be root. The reason is that the container (and thus the user <code>fwd</code>) is 
   going to invoke several scripts on the host (respectivley within the mounted volumes) that MUST  
   NOT be run as root. 

2. Access the container 

   <code>podman exec -it <container_id> /bin/bash</code>
   
   As expected the active user within the container is <code>fwd</code> respectively 
   <code>1020</code>: 
   
   ```
   bash-4.4$ whoami 
   1020 
   bash-4.4$ id -u 
   1020 
   bash-4.4$ id -g 
   1020 
   ```
 
3. Now i want to create a file within the the mounted volume respectively on the host which fails due to missing privileges:

   ```
   touch /tmp/testdir/test.txt 
   touch: cannot touch '/tmp/testdir/test.txt': Permission denied 
   ```

   On the host <code>testdir</code> belongs to user <code>fwd</code> (run <code>ls -la</code> 
   on the host):
   
   ```
   $ ls -la /tmp/testdir/
   total 8 
   drwxrwxr-x   2 fwd  fwd  4096 Apr 16 09:01 
   ```

   However, within the container <code>testdir</code> belongs to <code>root</code> (run <code>ls 
   -la</code> within the container):
   
   ```
   bash-4.4$ ls -la /tmp/testdir/
   total 8 
   drwxrwxr-x 2 root root 4096 Apr 16 08:01 .
   ```
 
4. Get it working by assigning the directory to <code>huser</code>
  
   What actually works is to assign the the directory to <code>huser</code>:
   
   ```   
   podman top <container_id> user huser
   USER   HUSER
   1020   297627
   ```
   
   ```  
   chown -R 297627:297627 /tmp/testdir
   ```  

   Now, within the container <code>testdir</code> belongs to <code>1020</code> (run <code>ls -la</code> within the container):
   
   ```  
   bash-4.4$ ls -la /tmp/testdir
   total 8
   drwxrwxr-x 2 1020 1020 4096 Apr 16 08:01 .
   ```  
   
   The file can now be created:
   
   ```    
   touch /tmp/testdir/test.txt <br>
   ```
  
**Describe the results you received:**

By assigning the <code>huser</code> to the mounted host volume i am able gain write access from within the container.

**Describe the results you expected:**

I am actually not quite sure what to expect. What is the recommended approach/best practice for such a scenario? Is assigning the <code>huser</code> to the needed host directories really what needs to be done or is there any other recommended way? Should <code>--uidmap</code> be utilized in any way ? 

When i was still using v1.6.4 the host directories belonged to <code>fwd</code> and could always be accessed from within the container. 

So what i am looking for is actually some advice or best practive for dealing with a scenario where the active container user can't be root and has to be able to access host volumes.

**Additional information you deem important (e.g. issue happens only occasionally):**

- podman is used/running in rootless mode
- I run podman based on a current build/pull from git master (using <code>make package-install</code>)

**Output of `podman version`:**

```
Version: 2.0.0-dev
RemoteAPI Version: 1
Go Version: go1.12.12
Git Commit: dd234f71d6c1b6f1dce0d0c7428b2d2a7783ee41-dirty
Built: Thu Apr 16 06:46:52 2020
OS/Arch: linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: dd234f71d6c1b6f1dce0d0c7428b2d2a7783ee41-dirty
  goVersion: go1.12.12
  podmanVersion: 2.0.0-dev
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: podman-2.0.0-1587016003.gitd6b3bc18.el8.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.7, commit: dd234f71d6c1b6f1dce0d0c7428b2d2a7783ee41-dirty'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: daisyt
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  memFree: 31875878912
  memTotal: 105331625984
  ociRuntime:
    name: runc
    package: runc-1.0.0-15.2.el8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: db2349efc4dc0001462089382d175ed38fdba742
      spec: 1.0.1-dev
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1048571904
  swapTotal: 1048571904
  uptime: 3h 50m 53.53s (Approximately 0.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-1587016003.gitd6b3bc18.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We run podman on a bare metal CentOS 8 server.
 
`cat /etc/os-release`:

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by mheon** [comment]
I think you may be misunderstanding how rootless Podman works. Rootless Podman is not, and will never be, root; it's not a setuid binary, and gains no privileges when it runs. Instead, we use a user namespace to shift the UIDs and GIDs of a block of users we are given access to on the host (via the `newuidmap` and `newgidmap` executables) and your own user within the containers we create. Root in the container is actually your user on the host, UID/GID 1 is the first UID/GID specified in your user's mapping in `/etc/subuid` and `/etc/subgid`, etc. If you mount a directory from the host into a rootless container and create a file in that directory as root in the container, you'll see it's actually owned by your user.

We do recognize that this doesn't really match how many people intend to use rootless Podman - they want their UID inside and outside the container to match. Thus, we provide the `--userns=keep-id` flag, which ensures that your user is mapped to its own UID and GID inside the container. It sounds like this will resolve your problem. However, given what I've said, I'm surprised that this worked at all in previous Podman versions; it doesn't sound like you running as the user you thought you were.

**Comment by mheon** [comment]
@giuseppe @rhatdan I have vague memories of this error, but a search doesn't find anything; any ideas?

**Comment by mlezajic** [comment]
> @giuseppe @rhatdan I have vague memories of this error, but a search doesn't find anything; any ideas?

Just tried with v1.9 and get the same error. Any ideas ?

**Comment by rhatdan** [comment]
I think this is an error in running in a pod with --keep-id.  I was able to get this to happen, by doing
podman pod create --name monitoring-pod.

If I run the container without the --keep-id, it works.

I think we have a bug in launching a pod with one of the containers wanting to retain their UID.

**Comment by mlezajic** [comment]
> I think this is an error in running in a pod with --keep-id. I was able to get this to happen, by doing
> podman pod create --name monitoring-pod.
> 
> If I run the container without the --keep-id, it works.
> 
> I think we have a bug in launching a pod with one of the containers wanting to retain their UID.

Is there any chance to get this fixed or somehow adressed ?

In general, what is the strategy with regard to any bugs that show up in v1.9? Are issues going to be fixed in v2.x only or might there for instance be something like v1.9.1 anytime soon?

**Comment by rhatdan** [comment]
We will look at them on a case by case basis, but we tend to force updates to the next release. In long term support worlds like RHEL we are willing to do some back ports, but it is very difficult to do and we don't have unlimited people working on this. 

In the case of this bug, having an upstream person fix it with a PR, would be best.  Most of the core engineers at this point are concentrating on the V2 effort.

**Comment by rhatdan** [comment]
@giuseppe @haircommander Any thoughts on this. Looks like we are starting the Pod in one user namespace and then the container in a different. One possible solution would be to add the --keep-id to the pod, so that the pod and then all of the containers would get launched into the correct user namespace.

**Comment by giuseppe** [comment]
> @giuseppe @haircommander Any thoughts on this. Looks like we are starting the Pod in one user namespace and then the container in a different. One possible solution would be to add the --keep-id to the pod, so that the pod and then all of the containers would get launched into the correct user namespace.

yes definitely, we need the keep-id at the pod level.

We shouldn't allow creating a separate user namespace when joining a pod.  It is possible but it is difficult to manage, we would need to first join the pod namespace and then create a new one.

**Comment by rhatdan** [comment]
@giuseppe @haircommander Any movement on this?

**Comment by giuseppe** [comment]
what if the pod is created like the following:
```
$ podman run --pod new:foo --userns=keep-id -ti ...
```

Would that create the pod with the correct mapping?

**Comment by mlezajic** [comment]
> what if the pod is created like the following:
> 
> ```
> $ podman run --pod new:foo --userns=keep-id -ti ...
> ```
> 
> Would that create the pod with the correct mapping?

After i have reported the issue a couple of weeks ago i went back to v1.6.4. Now, in order to test what you have suggested i wanted to install the latest v2 version from git master. When i run

```
make package-install
```
it fails with

```
# Only generate the varlink code on Linux (see issue #4814).
GO111MODULE=off go generate ./pkg/varlink/...
GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -asmflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=57a4c481b5298125f0d6d2fa28e2df4dbe770672 -X github.com/containers/libpod/libpod/define.buildInfo=1590479164 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc ' -tags "ABISupport varlink selinux seccomp systemd exclude_graphdriver_btrfs btrfs_noversion  exclude_graphdriver_devicemapper" -o bin/podman github.com/containers/libpod/cmd/podman
# k8s.io/apimachinery/pkg/util/errors
vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
# github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent
vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/parent.go:94:9: undefined: "github.com/pkg/errors".Is
# github.com/containers/libpod/pkg/bindings/containers
pkg/bindings/containers/containers.go:461:8: undefined: "github.com/pkg/errors".Is
pkg/bindings/containers/logs.go:59:7: undefined: "github.com/pkg/errors".Is
make[1]: *** [Makefile:186: bin/podman] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/libpod-1077d2d0'
error: Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)
make: *** [Makefile:691: package] Error 1


```

**Comment by giuseppe** [comment]
> ```
> 
> ```
> 
> 
> it fails with
> 
> ```
> # Only generate the varlink code on Linux (see issue #4814).
> GO111MODULE=off go generate ./pkg/varlink/...
> GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -asmflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=57a4c481b5298125f0d6d2fa28e2df4dbe770672 -X github.com/containers/libpod/libpod/define.buildInfo=1590479164 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc ' -tags "ABISupport varlink selinux seccomp systemd exclude_graphdriver_btrfs btrfs_noversion  exclude_graphdriver_devicemapper" -o bin/podman github.com/containers/libpod/cmd/podman
> # k8s.io/apimachinery/pkg/util/errors
> vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
> # github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent
> vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/parent.go:94:9: undefined: "github.com/pkg/errors".Is
> # github.com/containers/libpod/pkg/bindings/containers
> pkg/bindings/containers/containers.go:461:8: undefined: "github.com/pkg/errors".Is
> pkg/bindings/containers/logs.go:59:7: undefined: "github.com/pkg/errors".Is
> make[1]: *** [Makefile:186: bin/podman] Error 2
> make[1]: Leaving directory '/root/rpmbuild/BUILD/libpod-1077d2d0'
> error: Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)
> 
> 
> RPM build errors:
>     Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)
> make: *** [Makefile:691: package] Error 1
> ```

I think you need a newer go toolchain.  What version of go are you using?

**Comment by mlezajic** [comment]
> > ```
> > 
> > ```
> > 
> > 
> > it fails with
> > ```
> > # Only generate the varlink code on Linux (see issue #4814).
> > GO111MODULE=off go generate ./pkg/varlink/...
> > GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -asmflags 'all=-trimpath=/root/rpmbuild/BUILD/libpod-1077d2d0' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit=57a4c481b5298125f0d6d2fa28e2df4dbe770672 -X github.com/containers/libpod/libpod/define.buildInfo=1590479164 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc ' -tags "ABISupport varlink selinux seccomp systemd exclude_graphdriver_btrfs btrfs_noversion  exclude_graphdriver_devicemapper" -o bin/podman github.com/containers/libpod/cmd/podman
> > # k8s.io/apimachinery/pkg/util/errors
> > vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
> > # github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent
> > vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/parent.go:94:9: undefined: "github.com/pkg/errors".Is
> > # github.com/containers/libpod/pkg/bindings/containers
> > pkg/bindings/containers/containers.go:461:8: undefined: "github.com/pkg/errors".Is
> > pkg/bindings/containers/logs.go:59:7: undefined: "github.com/pkg/errors".Is
> > make[1]: *** [Makefile:186: bin/podman] Error 2
> > make[1]: Leaving directory '/root/rpmbuild/BUILD/libpod-1077d2d0'
> > error: Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)
> > 
> > 
> > RPM build errors:
> >     Bad exit status from /var/tmp/rpm-tmp.cgeiwV (%build)
> > make: *** [Makefile:691: package] Error 1
> > ```
> 
> I think you need a newer go toolchain. What version of go are you using?

```
$ go version
go version go1.12.12 linux/amd64
```

**Comment by rhatdan** [comment]
@giuseppe Any progress on this?

**Comment by giuseppe** [comment]
> @giuseppe Any progress on this?

It must be addressed in the OCI runtime.  I am currently trying to figure out a way to fix it in crun.

Let's close this bug as a dup of https://github.com/containers/libpod/issues/6153
