### ISSUE TITLE
Podman 1.9.0~1 ubuntu package does not contain podman binary

### ISSUE THREAD

**Issue by aidanhs** [containers/libpod#5846]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The podman package downloaded from the repository recommended on the 'install instructions' page does not actually contain the podman binary.

**Steps to reproduce the issue:**

1. Add repo from install instructions page

2. Install

3. Try and use podman

**Describe the results you received:**

```
/etc/apt/sources.list.d $ cat devel\:kubic\:libcontainers\:stable.list 
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /
/etc/apt/sources.list.d $ apt-cache show podman
Package: podman
Version: 1.9.0~1
Architecture: amd64
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Installed-Size: 15
Depends: libseccomp2, libdevmapper1.02.1, libgpgme11, catatonit, conmon (>= 1.0.0), containers-common (>= 0.1.40-9), containernetworking-plugins (>= 0.8.1), cri-o-runc, iptables, podman-plugins
Recommends: slirp4netns, uidmap, varlink
Conflicts: podman-rootless
Filename: ./amd64/podman_1.9.0~1_amd64.deb
Size: 8304
MD5sum: 9f356de3d886b1ad7cb336c63a8508a5
SHA1: d874840615c60b14297cf67274b7afae5095c912
SHA256: a3f0d4a58070972f34ba32f706114c4cb24f7033be726d0ff900e71a09c8d415
Section: devel
Priority: optional
Homepage: https://github.com/containers/libpod.git
Description: Manage pods, containers and container images.
Description-md5: 404953edf3c6603dbc4faa5ae9fb561b

/etc/apt/sources.list.d $ dpkg -c /var/cache/apt/archives/podman_1.9.0~1_amd64.deb 
drwxr-xr-x root/root         0 2020-04-15 17:07 ./
drwxr-xr-x root/root         0 2020-04-15 17:07 ./usr/
drwxr-xr-x root/root         0 2020-04-15 17:07 ./usr/share/
drwxr-xr-x root/root         0 2020-04-15 17:07 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-04-15 17:07 ./usr/share/doc/podman/
-rw-r--r-- root/root      6160 2020-04-15 17:07 ./usr/share/doc/podman/changelog.gz
-rw-r--r-- root/root      1687 2020-04-15 17:07 ./usr/share/doc/podman/copyright
```

**Describe the results you expected:**

It contains the binary

**Additional information you deem important (e.g. issue happens only occasionally):**

Maybe related to https://github.com/containers/libpod/issues/5833 ?

**Output of `podman version`:**

N/A

**Output of `podman info --debug`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 1.9.0~1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
Sorry about this. I'll try to add some elementary tests in my autobuilder to complain if no binary is found

**Comment by lsm5** [comment]
@aidanhs fixed in `1.9.0~2` building currently at https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman , and should be available in sometime. I'm gonna close this. Please re-open if it's not resolved with the new build.

**Comment by lsm5** [comment]
@pilebones ack, yup, the new fix will be pushed to all supported debians and ubuntus.

**Comment by pilebones** [comment]
Thanks a lot, could you mind notifying me when it's done?

**Comment by lsm5** [comment]
it usually gets done in less than an hour, but I'll keep an eye out and comment here.

**Comment by aidanhs** [comment]
Looks good now, thanks!

**Comment by lsm5** [comment]
@pilebones should be ready now for all x86_64.

**Comment by pilebones** [comment]
Perfect, it works fine now
