### ISSUE TITLE
podman run (...) --rm=False removes the container

### ISSUE THREAD

**Issue by EmilienM** [containers/libpod#5850]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman run (...) --rm=False removes the container.

**Steps to reproduce the issue:**

``podman run --rm=False --net host fedora echo helloworld``

**Describe the results you received:**

fedora container is created and then removed.

**Describe the results you expected:**

fedora container not being removed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
1.6.4
```

**Comment by rhatdan** [comment]
I checked in podmanV2 and this works correctly.  Currently we only want to fix major bugs in podman V1, and I don't see this as one.  So I am going to close as fixed in podman 2.0.0
If you believe this is critical then please open a bugzilla.
