### ISSUE TITLE
kernel: new mount options do not match the existing superblock, will be ignored

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#5857]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When I start container I find a kernel message in the logs.
`kernel: new mount options do not match the existing superblock, will be ignored`
This message was not present with podman 1.8.2

**Steps to reproduce the issue:**

Run a container using systemd service unit

**Describe the results you received:**
Message in the logs: 
`kernel: new mount options do not match the existing superblock, will be ignored`

**Describe the results you expected:**
No message in the logs

**Additional information you deem important (e.g. issue happens only occasionally):**
Systemd service unit.
```
[Unit]
Description=System Logging Service
Documentation=https://www.rsyslog.com/doc/
Requires=syslog.socket

[Service]
EnvironmentFile=-/etc/environment
Type=forking
ExecStartPre=-/usr/bin/podman rm rsyslogd
ExecStartPre=-/usr/bin/podman pull our-registry.ourdomain.com/utility/rsyslog-server:latest
ExecStart=/usr/bin/podman run -d --rm --name rsyslogd --log-driver=journald --log-opt=tag={{.Name}} --env CONTAINER_HOST=%H \
    -v /var/spool/postfix/dev:/var/spool/postfix/dev \
    -v /run/systemd/journal:/run/systemd/journal \
    -v /dev:/dev \
    -v /logs:/usr/local/registrator/logs \
    -v /logs:/logs \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/rsyslog.conf:/etc/rsyslog.conf:ro \
    -v /etc/rsyslog.d:/etc/rsyslog.d:ro \
    -v /var/spool/rsyslog:/var/spool/rsyslog \
    -v /var/log:/var/log \
    --net=host --cap-add=SYSLOG,SYS_NICE --pull=always --systemd=always \
    \
  our-registry.ourdomain.com/utility/rsyslog-server:latest
ExecStop=-/usr/bin/podman stop rsyslogd
ExecStopPost=-/usr/bin/podman rm --force rsyslogd
SyslogIdentifier=rsyslogd
LimitNOFILE=32768
LogLevelMax=6
Restart=always
RestartSec=10s
TimeoutStartSec=120
TimeoutStopSec=15

[Install]
WantedBy=multi-user.target
```

**Output of `podman version`:**

```
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.10.1
  podmanVersion: 1.9.0
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.15, commit: '
  cpus: 40
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: host.ourdomain.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.3.0-45-generic
  memFree: 40666742784
  memTotal: 67154833408
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 6446641152
  swapTotal: 6446641152
  uptime: 43h 8m 51.77s (Approximately 1.79 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.9.0~2 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
The message is in syslog/dmesg or is it in the joural log for your unit file?

**Comment by alitvak69** [comment]
Syslog / dmesg.  It is in /var/log/kern.log file.  It appears on every container restart.

```
2020-04-17T11:52:52.776474-07:00 logserver4n2-la kernel: [213097.320645] new mount options do not match the existing superblock, will be ignored
2020-04-17T11:52:52.776474-07:00 logserver4n2-la kernel: [213097.320645] new mount options do not match the existing superblock, will be ignored
2020-04-17T11:55:49.513851-07:00 logserver4n2-la kernel: [213273.966375] new mount options do not match the existing superblock, will be ignored
```

**Comment by rhatdan** [comment]
You are talking about these correct?
[488577.976711] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[488577.978565] new mount options do not match the existing superblock, will be ignored

They have been around for a very long time.  And we should probably remove them.  I think the container runtimes (crun, runc) are attempting to mount the mqueue with a label, and then when that fails, fall back to mounting the mqueue without the label.

@giuseppe PTAL, do you know if crun has this code?

**Comment by alitvak69** [comment]
I run ubuntu and don't have SELinux, so I had no mqueue messages, just similar to  the second one.  My dmesg  is not showing those errors before upgrade to 1.9.0

**Comment by rhatdan** [comment]
Are you using crun or runc?  And does this happen in rootless as well as rootful?

**Comment by alitvak69** [comment]
I use runc. 
`runc version spec: 1.0.1-dev`
Container run as root.

**Comment by giuseppe** [comment]
could you share the `config.json` file that podman generates for the container?

If there is no SELinux we shouldn't specify any mount label to the OCI runtime

**Comment by rhatdan** [comment]
I am not sure this is caused by SELinux.  But I am not sure.  I see this as a new kernel message in addition to the original mqueue one.

**Comment by alitvak69** [comment]
[config.zip](https://github.com/containers/libpod/files/4504723/config.zip)

**Comment by giuseppe** [comment]
the error is returned by the kernel when the cgroup v1 flags mismatch the flags specified for the controller if it is already mounted at another location.

I think it is safe to just ignore it

**Comment by rhatdan** [comment]
So this is because we are mounting cgroupfs on a container?

**Comment by giuseppe** [comment]
I think yes, it is caused by the mount of cgroup v1 inside of the container itself

**Comment by rhatdan** [comment]
Did you open a PR in the kernel to stop this?

**Comment by rhatdan** [comment]
@giuseppe Any movement on this?

**Comment by giuseppe** [comment]
I am not sure there is anything to do, AFAICS it is just a warning without any effect
