### ISSUE TITLE
Pod creation fails due to missing bridge mode networking

### ISSUE THREAD

**Issue by mlezajic** [containers/libpod#5858]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using a current dev version from git master (**2.0.0-dev**) pods can no longer be created. 

**Steps to reproduce the issue:**

We use podman in rootless mode, so we have created a dedicated technical user called <code>fwd</code> to operate podman.

1. As user <code>fwd</code> create a pod with one port mapping: 

   ```
   podman pod create -p 8080:8080 --name test
   ERRO[0000] PortMappings can only be used with Bridge mode networking 
   ```

**Describe the results you received:**

The pod creation immediately fails with <code>ERRO[0000] PortMappings can only be used with Bridge mode networking</code> using a current build from git master.

**Describe the results you expected:**

Pod creation succeeds. Actually the very same command worked prior to installing the latest build from git master. I have also tried using <code>--network bridge</code> but that didn't help either.

**Additional information you deem important (e.g. issue happens only occasionally):**

- podman is used/running in rootless mode
- I run podman pased on a build from git master (using <code>make package-install</code>)

**Output of `podman version`:**

```
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.12.12
Git Commit:         9c8f59905f675bcdfc753daffa0ff316c7d6c800-dirty
Built:              Fri Apr 17 06:35:26 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahversion: 1.14.8
  cgroupsversion: v1
  conmon:
    package: podman-2.0.0-1587101717.git0d2b5532.el8.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.7, commit: 9c8f59905f675bcdfc753daffa0ff316c7d6c800-dirty'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventlogger: journald
  hostname: daisyt
  idmappings:
    gidmap:
    - containerid: 0
      hostid: 1020
      size: 1
    - containerid: 1
      hostid: 296608
      size: 65536
    uidmap:
    - containerid: 0
      hostid: 1020
      size: 1
    - containerid: 1
      hostid: 296608
      size: 65536
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  memfree: 103735459840
  memtotal: 105331625984
  ociruntime:
    name: runc
    package: runc-1.0.0-15.2.el8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: db2349efc4dc0001462089382d175ed38fdba742
      spec: 1.0.1-dev
  os: linux
  rootless: true
  runtimeinfo: {}
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.3-23.2.el8.x86_64
    version: |-
      slirp4netns version 0.4.3-beta.1
      commit: b04291ba84ca35ccc60bd009372a28f9ea7ef841
  swapfree: 1048571904
  swaptotal: 1048571904
  uptime: 15h 47m 57.99s (Approximately 0.62 days)
store:
  configfile: /home/fwd/.config/containers/storage.conf
  containerstore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphdrivername: overlay
  graphoptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-1.module_el8.1.0+272+3e64ee36.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphroot: /home/fwd/.local/share/containers/storage
  graphstatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imagestore:
    number: 0
  runroot: /tmp/run-1020/containers
  volumepath: /home/fwd/.local/share/containers/storage/volumes
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
version:
  remoteapiversion: 1
  version: 2.0.0-dev
  goversion: go1.12.12
  gitcommit: 9c8f59905f675bcdfc753daffa0ff316c7d6c800-dirty
  built: 1587101726
  osarch: linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-1587101717.git0d2b5532.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We run podman on a bare metal CentOS 8 server.
 
`cat /etc/os-release`:

```
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by xcffl** [comment]
So basically it's due to the rootless network stack switching to CNI, whereas by default the `--network` parameter is set to `slirp4netns`. Set it manually to `--nework bridge` fixes this.

**Comment by mlezajic** [comment]
> So basically it's due to the rootless network stack switching to CNI, whereas by default the `--network` parameter is set to `slirp4netns`. ~Set it manually to `--nework bridge` fixes this.~ Manual setting takes no effect.
> 
> This change also has impact on `podman-compose`.

So what  needs to be done in that case?

**Comment by xcffl** [comment]
> > So basically it's due to the rootless network stack switching to CNI, whereas by default the `--network` parameter is set to `slirp4netns`. ~Set it manually to `--nework bridge` fixes this.~ Manual setting takes no effect.
> > This change also has impact on `podman-compose`.
> 
> So what needs to be done in that case?

I think they haven't migrate all features to v2 yet. Personally I downgrade to 1.x.

**Comment by mlezajic** [comment]
> > > So basically it's due to the rootless network stack switching to CNI, whereas by default the `--network` parameter is set to `slirp4netns`. ~Set it manually to `--nework bridge` fixes this.~ Manual setting takes no effect.
> > > This change also has impact on `podman-compose`.
> > 
> > 
> > So what needs to be done in that case?
> 
> I think they haven't migrate all features to v2 yet. Personally I downgrade to 1.x.

Thanks for getting back. I am going to downgrade to v1.6.4 as well as this is the only version i get from the current CentOs AppStream repository. What 1.x version are you going to use ?

**Comment by xcffl** [comment]
v1.8 which Fedora's staging repo provides. On centos you may use project kubic repo to have 1.8 as well

**Comment by mlezajic** [comment]
> v1.8 which Fedora's staging repo provides. On centos you may use project kubic repo to have 1.8 as well

Right, i have already tried kubic respectively v1.8.2, where i faced following issue:
https://github.com/containers/libpod/issues/5745

So i tried my luck moving forward and use latest and greatest, unfortunately this resulted in this issue. Do you know by chance if kubic is going to move v1.9 anytime soon ?

**Comment by xcffl** [comment]
Sorry I'm not familiar with their release agenda as I'm not affiliated with red hat or suse.

However, as the repo is built by CI, I think it will get updates soon.

**Comment by rhatdan** [comment]
Podman 1.9.* will be the last releases with the V1 protocol.  We have master branch working on 2.0 right now, and it is under heavy development,  There are lots of breakage and you will see lots of PRs this week to fix these.  We do not plan on releasing podman 2.* for a few months.  I would not attempt to use a podman 2.* for a while unless you are working on development.

**Comment by mlezajic** [comment]
> Podman 1.9.* will be the last releases with the V1 protocol. We have master branch working on 2.0 right now, and it is under heavy development, There are lots of breakage and you will see lots of PRs this week to fix these. We do not plan on releasing podman 2.* for a few months. I would not attempt to use a podman 2.* for a while unless you are working on development.

Thanks for the clarification. One more question in this regard:
Is there a chance to get issues fixed that might occur on some back level podman version? In our case we currently can 'only' use v1.6.4 (given that the Centos8 repo currently provides that). Or is it that one is required to always move to the latest stable version (v1.9 i suppose)? 

Our problem is that v1.6.4 appears to 'derail' every now and then. Containers are running stable for a couple of days and then all of a sudden crash (respectively end up in state 'Created') and can no longer be started. 'podman start <container_id>' would fail with some sort of a generic storage/overly related exception (unfortunately i can't recall the details of the exception as i have completely dropped the podman .config and .local directory and recreated everything from scratch to get it working again).

**Comment by mheon** [comment]
That sounds like a refresh happening - any chance this is as rootless? This sort of thing usually happens when the user rootless Podman is running as either logs out, or has their `/run/user/$UID` temporary directory re-created, or otherwise has Podman temporary files removed.

**Comment by mlezajic** [comment]
> That sounds like a refresh happening - any chance this is as rootless? 

We operate podman in rootless mode. The procedure is:
1. ssh into the machine as (non-root user) **userA**: 
   <code>ssh userA@host</code>

2. Become (non-root user) **userB**: 
   <code>sudo su - userB -s /bin/sh</code>

3. As **userB** operate podman (create pods, containers, etc.)

> This sort of thing usually happens when the user rootless Podman is running as either logs out

Not sure what 'logout' means in this context, certainly the containers remain running once i enter <code>exit</code> as **userB** and become **userA** again.

>, or has their `/run/user/$UID` temporary directory re-created, or otherwise has Podman temporary files removed.

Which files would be the 'Podman temporary files' ? If something like this happens its certainly not on purpose or explictly triggered by anything we are aware of. 

I guess i will have to wait until it happens again and then open another issue with the detailed error message/exception and appropriate version information in order to not 'mix' several problems in one issue..

**Comment by mheon** [comment]
Using `su` with rootless Podman is not recommended and probably not safe (at least on systems with Systemd init). We use a number of filesystems created by systemd (`/run/user/$UID` for example). Unfortunately, systemd is not really compatible with `su` and `sudo` - it doesn't treat these as real login sessions, so the filesystems we need may not be created. I imagine that this is somehow causing Podman to look in an incorrect place for its temporary state directory (though this should be protected by path safeguards in the database, which is rather confusing) and cause Podman to assume the system has rebooted, and reset all system state to account for this.

**Comment by mlezajic** [comment]
> Using `su` with rootless Podman is not recommended and probably not safe (at least on systems with Systemd init). We use a number of filesystems created by systemd (`/run/user/$UID` for example). Unfortunately, systemd is not really compatible with `su` and `sudo` - it doesn't treat these as real login sessions, so the filesystems we need may not be created. I imagine that this is somehow causing Podman to look in an incorrect place for its temporary state directory (though this should be protected by path safeguards in the database, which is rather confusing) and cause Podman to assume the system has rebooted, and reset all system state to account for this.

So one conclusion (best practice?) could be that only the user that initially logs into the machine should be the one that is running podman (<code>userA</code> in our case) as only this is going to create a valid login session ?

**Comment by mheon** [comment]
Yes (though you can likely use SSH to localhost as a sudo-substitute). We really ought to document this better on our part, as well.

**Comment by storrgie** [comment]
@mheon sorry to necrobump this. Wondering if use of `runuser` or another utility is more advisable? Or, is it best to always ssh in as the user?

With `runuser` you can have a "shell-less" user (e.g. `/sbin/nologin`) and specify the shell at invocation: `runuser -ls /bin/bash <user>`.

**Comment by mheon** [comment]
For reference, I did end up writing a blog about this: https://www.redhat.com/sysadmin/sudo-rootless-podman

SSH is probably the easiest but systemd also provides some tools that create a proper login session - `machinectl login` for example.
