### ISSUE TITLE
v1.9 podman images on quay.io actually contains v1.6.

### ISSUE THREAD

**Issue by GrahamDumpleton** [containers/libpod#5877]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Pull down and run podman stable images from quay.io tagged v1.9 and in it run podman to verify the version.

```
$ docker run --rm -it quay.io/podman/stable:v1.9 sh
sh-5.0# podman version
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64
```

**Describe the results you received:**

I would expect to see podman version 1.9.

**Describe the results you expected:**

I see podman version 1.6.

**Additional information you deem important (e.g. issue happens only occasionally):**

This means newer features and bug fixes are obviously not present. For example the ``podman system service`` command which was what was interested in.

```
# podman system --help
Manage podman

Usage:
  podman system [command]

Available Commands:
  df          Show podman disk usage
  info        Display podman system information
  migrate     Migrate containers
  prune       Remove unused data
  renumber    Migrate lock numbers
```

Expect instead:

```
[~] $ podman version
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.13.9
OS/Arch:            linux/amd64
[~] $ podman system --help
Manage podman

Usage:
  podman system [command]

Available Commands:
  df          Show podman disk usage
  info        Display podman system information
  migrate     Migrate containers
  prune       Remove unused data
  renumber    Migrate lock numbers
  reset       Reset podman storage
  service     Run API service
```

cc @jorgemoralespou

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
Building the libpod/contrib/podmanimage/stable/Dockerfile locally gets podman 1.9.0.  So this is something going wrong on quay.io.

**Comment by TomSweeneyRedHat** [comment]
The build trigger on quay.io fires whenever a new branch goes out and adds a tag with the branches' name.  However, when the branch is made, the rpm has yet to make it through testing so you get the latest stable version.  

I try to remember to remove those when they're created, but forgot to get to it quickly this time.  Also over the weekend, I think I figured out how to have quay.io not build those variants when a release comes out.  I'll clean that up too.
