### ISSUE TITLE
podman exec --detach

### ISSUE THREAD

**Issue by MarcoFalke** [containers/libpod#5884]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
What is the recommended way to run a command in the background in podman in a script? `docker exec` does it with `--detach`: https://docs.docker.com/engine/reference/commandline/exec/#options

It seems there is a manual detach option, but I presume that doesn't work in scripts?

```
$ podman exec --help | grep 'detach'
      --detach-keys string   Select the key sequence for detaching a container. Format is a single character [a-Z] or ctrl-<value> where <value> is one of: a-z, @, ^, [, , or _ (default "ctrl-p,ctrl-q")

**Comment by mheon** [comment]
Being worked on now as part of the APIv2 exec work.

**Comment by MarcoFalke** [comment]
Thanks. Is there a temporary workaround other than "install docker"?

**Comment by mheon** [comment]
Launching a shell in the container and backgrounding commands with `&` seems to work well enough - you can kill the shell and the commands will continue running.

**Comment by mheon** [comment]
#6270 has support for detached exec.
