### ISSUE TITLE
editing config.json

### ISSUE THREAD

**Issue by Swatigupta1997** [containers/libpod#5892]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I wish to attach a network to a container after it has already been created, i.e.
The functionality of "docker network connect"
Since there is no similar API in podman, I tried to do this by editing the container's config.json manually. But the config does not stay when the container is started. How to overcome this?

**Steps to reproduce the issue:**

1. Create and start a container:
podman run -it --name "container" --network=mgmtnet img_v1 /bin/bash

2. stop container:
 podman stop container

3. Edit config.json at:
/var/lib/containers/storage/overlay-containers/60dfc044f28b0b60f0490f351f44b3647531c245d1348084944feaea783a6ad5/userdata/config.json

I add an extra netns path in the namespaces section in config.json. 
```
"namespaces": [
            {
                "type": "pid"
            },
            {
                "type": "network",
>>              "path": "/var/run/netns/cni-8231c733-6932-ed54-4dee-92477014da6e",
>>[+]           "path": "/var/run/netns/test_net"
            },
            {
                "type": "ipc"
            },
            {
                "type": "uts"
            },
            {
                "type": "mount"
            }
        ],
```
4. Start the container:
podman start container

**Describe the results you received:**
I expected a new interface inside the container corresponding to the namespace I supplied in config.json.
The changes in config.json should persist.

**Describe the results you expected:**
New interface not found in container. On container start (step-4), config.json reverts back to original and my changes are wiped out.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
```
**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.4.2-stable2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 268267728896
  MemTotal: 270097387520
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 5368705024
  SwapTotal: 5368705024
  arch: amd64
  cpus: 16
  hostname: bng-ix-svr1.englab.juniper.net
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: false
  uptime: 2h 27m 43.71s (Approximately 0.08 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
#rpm -q podman
podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"

**Comment by mheon** [comment]
This is not supported via manual editing. We regenerate the configuration for each run of the container and immediately pass it into the OCI runtime as part of the container creation process.

Podman theoretically supports "pre-create" stage OCI hooks that receive the OCI spec before the container is created and have the option to process it, but I don't believe this has been tested in a number of releases (the original intended user did not require it in the end).

**Comment by mheon** [comment]
Also, adding *extra* network namespace paths is not supported. The spec allows at most one.

You need to edit the container's existing network namespace.

**Comment by mheon** [comment]
Also, may I ask what you're trying to do with `network connect`?

**Comment by Swatigupta1997** [comment]
Hi Matthew

Q "Also, may I ask what you're trying to do with network connect?"
 I wish to create macvtap interface connectivity between host and container.
Macvtaps require a physical interface on host for creation, but this info is not known at the time of first container start, so I must somehow allow the user to configure them at a later stage.

Right now, the network namespace (mentioned in  in conf.json) gets automatically created based on the .conflist specs in /etc/cni/net.d/ folder, right? The interfaces created inside the container depend on the network names provided in 'podman run --network cli' for which these specs exist.
Ex: 
```
podman run -it --log-level=debug --name "container" --network=jmgmtnet,cbnet img_v1 /bin/bash
```
will create two interfaces inside the container (corresponding to what is specified in the conflist files for jmgmtnet and cbnet):
```
root@d0ff7fb58a5c:/# ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.216.105.113  netmask 255.255.248.0  broadcast 10.216.111.255
        inet6 fe80::6451:21ff:fea3:4264  prefixlen 64  scopeid 0x20<link>
        ether 66:51:21:a3:42:64  txqueuelen 0  (Ethernet)
        RX packets 10  bytes 618 (618.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7  bytes 558 (558.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.110.226  netmask 255.255.255.0  broadcast 192.168.110.255
        ether ea:34:8d:da:a7:d5  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
on the host, i can see the network namespace (only one, as you pointed out. I was mistaken that there would be more):
```
# ip netns exec cni-fbf321e2-5ff9-7e13-1b05-c204dd8fcc6f ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 66:51:21:a3:42:64 brd ff:ff:ff:ff:ff:ff link-netnsid 0
3: eth1@if5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether ea:34:8d:da:a7:d5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
```
But I have noticed that, on every container restart, the namespace name is dynamically generated and is different from the earlier name.
Ex: On container stop and restart, the new namespace is now named:
/var/run/netns/cni-15a94433-5108-0246-1026-3e3267316bca

In this case, how do I supply a new interface to an already created container?
1) I cannot manually create an interface on host and move it to the namespace, as the namespace will change on reboots.
2) I cannot supply a new network name (based on conflist spec) to a running container ( as is done via network connect functionality) as there is no such support in podman start/network cli.
3) You mention that manual editing is not supported via config.json as it gets regenerated everytime. There must be somewhere this raw config is getting stored, from where you regenerate the config.json?
4) You mention OCI hooks, is it possible to supply a conflist-spec/network to the container through them?

PS: Thanks for taking the time and helping me out with this!

**Comment by Swatigupta1997** [comment]
Hi

Any updates?

**Comment by mheon** [comment]
The path to the namespace is in `podman inspect` as `SandboxKey` - that should provide the path to it in a deterministic manner. From there, you can modify the namespace itself to add interfaces. If you want to do this before the container starts, `podman init` should create the namespace but not start the container.

**Comment by rhatdan** [comment]
@Swatigupta1997 @mheon Can we close this issue?

**Comment by rhatdan** [comment]
Reopen if I was mistaken.
