### ISSUE TITLE
After upgrade to podman 1.9.0, ~/.local/share/containers being symlink causes problem

### ISSUE THREAD

**Issue by adelton** [containers/libpod#5932]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A bit of history:

For my rootless podman usage, I wanted to have the space consumption under control. After I saw the content of `~/.local/share/containers/storage` grow, I created separate partition, moved `~/.local/share/containers` to `/mnt/containers-storage/user` and created symlink `~/.local/share/containers` pointing to this new directory.

Then at one point I ditched then whole `~/.local/share/containers` to start afresh ... and the `~/.local/share/containers` was created again, consuming space under my home. So I moved it again to `/mnt/containers-storage/user`, created the symlink again, and edited `~/.config/containers/storage.conf` value `graphroot` to point to `/mnt/containers-storage/user`, so that should I purge my rootless containre storage in the future, it does not creep back under my home.

That was with podman-1.8.2-2.fc31.x86_64 and things were working fine.

Today I upgrade to podman-1.9.0-1.fc31.x86_64 and when I tried to run `podman run ...`, I got error message

```
Error: could not get runtime: database libpod root directory (staticdir) "/home/user/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/mnt/containers-storage/user/storage/libpod": database configuration mismatch
```

**Steps to reproduce the issue:**

1. Move `~/.local/share/containers` to different directory and edit `~/.config/containers/storage.conf` to point to this directory.

**Describe the results you received:**

Error
```
Error: could not get runtime: database libpod root directory (staticdir) "/home/user/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/mnt/containers-storage/user/storage/libpod": database configuration mismatch
```

**Describe the results you expected:**

If I have symlink in place so both paths resolve to the same location, podman should not complain at all, like it did in 1.8.2.

If podman needs to have these extra checks, the error message should provide some help about where that "database libpod root directory" can be configured. Or it should provide information how changing locations should be handled. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I am able to workaround the issue by editing my `~/.config/containers/storage.conf` and setting `graphroot` to point back to `/home/user/.local/share/containers/storage`. But I'd rather do the proper rename and if it needs to be done in multiple places (`~/.config/containers/storage.conf` and somewhere else), podman should be a bit more helpful with that.

Googling aroung I found similar reports about run and tmp but no real information about updating the "database libpod root directory".

**Output of `podman version`:**

```
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.13.9
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
Error: could not get runtime: database libpod root directory (staticdir) "/home/user/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/mnt/containers-storage/user/storage/libpod": database configuration mismatch
```

Note how this check effectively prevents proper debugging of the problem.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.0-1.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by mheon** [comment]
@rhatdan I think we might be missing a symlink resolve somewhere after the containers.conf work, maybe?

**Comment by rhatdan** [comment]
@adelton Is this fixed now?  I think it is, reopen if I am mistaken.
