### ISSUE TITLE
Cannot access the container port in the virtual machine from the host

### ISSUE THREAD

**Issue by Poorunga** [containers/libpod#5943]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
&emsp;&emsp;I used VMware Fusion to create an `ubuntu 16.04` virtual machine and installed `Podman` in this VM. The IP address assigned to the VM by NAT is `172.16.227.145`.
&emsp;&emsp;I created a nginx container using Podman: `podman run -p 8080:80 -d nginx`. Then, I can use the VM's browser to access the nginx default page, such as these urls: `http://127.0.0.1:8080` or `http://172.16.227.145:8080`
&emsp;&emsp;I can successfully ping VM's IP on the host. But, I cannot access nginx on the host browser, by typing in url: `http://172.16.227.145:8080`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "16.04"
  MemFree: 356323328
  MemTotal: 2065989632
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 486010880
  SwapTotal: 1022357504
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: ubuntu
  kernel: 4.15.0-91-generic
  os: linux
  rootless: false
  uptime: 5h 8m 12.88s (Approximately 0.21 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/xenial,now 1.6.2-1~ubuntu16.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Podman, unlike Docker, does not modify firewall rules to allow traffic on ports by default, so if you have a firewall blocking access to the ports on the host running Podman, you'll need to explicitly add firewall rules to allow traffic on 8080.

**Comment by rhatdan** [comment]
We consider this a security issue, and want users to explicitly modify their external firewall.
