### ISSUE TITLE
[Kubic project] Add packages for Ubuntu 20.04 distributions

### ISSUE THREAD

**Issue by floating-cat** [containers/libpod#5969]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The Ubuntu 20.04 was released, but there is no podman package for it currently: https://build.opensuse.org/repositories/devel:kubic:libcontainers:stable

**Describe the results you expected:**
Packages for Ubuntu 20.04

@lsm5 I saw you added the support for the Ubuntu 19.10. So I am pinging you here. Thanks.

**Comment by lsm5** [comment]
@floating-cat yes we'd like to see that as well but that's blocked on the OBS infra admins setting up 20.04 repos.

**Comment by alitvak69** [comment]
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04 returns 404

**Comment by lsm5** [comment]
> https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04 returns 404

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable

@alitvak69 OBS people have setup the 20.04 envs, but it doesn't look like it's been done correctly yet, as I see `find: command not found` errors. I'll ping them tomorrow.

**Comment by lsm5** [comment]
20.04 is ready now for x86_64 with other arches except ppc64le being built. Checking with admins about ppc64le setup.

**Comment by lsm5** [comment]
Please re-open if you notice any issues...
