### ISSUE TITLE
Unlimited hard ulimit with soft limit not supported 

### ISSUE THREAD

**Issue by coldbloodx** [containers/libpod#6005]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

[aaa@r8cn01 ~]$ docker run --rm -it --ulimit nofile="2000:-1"  centos  /bin/sh
Error: ulimit option "nofile=2000:-1" requires name=SOFT:HARD, failed to be parsed: ulimit soft limit must be less than or equal to hard limit: 2000 > -1

**Describe the results you received:**
Here is error message I got:
Error: ulimit option "nofile=2000:-1" requires name=SOFT:HARD, failed to be parsed: ulimit soft limit must be less than or equal to hard limit: 2000 > -1

**Describe the results you expected:**
The  command should be executed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
[aaa@r8cn01 ~]$ podman version
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
```
(paste your output here)
```

**Output of `podman info --debug`:**
[aaa@r8cn01 ~]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.4.2-stable2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 5214932992
  MemTotal: 6246227968
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: r8cn01
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: true
  uptime: 129h 31m 26.65s (Approximately 5.38 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/xianwu/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /podmanfs
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /tmp/run-33857
  VolumePath: /podmanfs/storage/volumes

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
[aaa@r8cn01 ~]$ rpm -q podman
podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
[aaa@r8cn01 ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 8.1.1911 (Core)
Release:	8.1.1911
Codename:	Core
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware environment.

**Comment by mheon** [comment]
Does the `-1` specifier work in Docker?

**Comment by rhatdan** [comment]
Were using the same parser as Docker, so I doubt it.

**Comment by coldbloodx** [comment]
@mheon @raukadah 
-1 works in docker.

in docker 19.03 on ubuntu 18.04:

root@ucn01:~# docker run --rm -it --ulimit fsize="2000:-1" ubuntu hostname
7ab7510d8c17


root@ucn01:~# docker info
Client:
 Debug Mode: false

Server:
 Containers: 20
  Running: 0
  Paused: 0
  Stopped: 20
 Images: 3
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.821GiB
 Name: ucn01
 ID: EB5M:GKHG:BWRR:K3E3:443W:CZMF:AC4O:LNA7:KEF7:7NSW:H4QD:BOYF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://9.21.54.109:80
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@ucn01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic


root@ucn01:~# dpkg -l docker
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                  Version                 Architecture            Description
+++-=====================================-=======================-=======================-================================================================================
un  docker                                <none>                  <none>                  (no description available)


 podman 1.4.2 on rhel 8.1
root mode:

[root@r8cn01 ~]#  docker run --rm -it --ulimit fsize="2000:-1" ubuntu hostname
Error: ulimit option "fsize=2000:-1" requires name=SOFT:HARD, failed to be parsed: ulimit soft limit must be less than or equal to hard limit: 2000 > -1
[root@r8cn01 ~]# docker info
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 5192196096
  MemTotal: 6246227968
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: r8cn01
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: false
  uptime: 138h 20m 38.53s (Approximately 5.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

[root@r8cn01 ~]# rpm -qa |grep podman
podman-docker-1.4.2-5.module_el8.1.0+237+63e26edc.noarch
podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
podman-manpages-1.4.2-5.module_el8.1.0+237+63e26edc.noarch


rootless mode:
[aaa@r8cn01 ~]$ docker info
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 5119832064
  MemTotal: 6246227968
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  hostname: r8cn01
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: true
  uptime: 138h 28m 35.46s (Approximately 5.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/xianwu/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /podmanfs
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /tmp/run-33857
  VolumePath: /podmanfs/storage/volumes

[aaa@r8cn01 ~]$ rpm -qa |grep docker
podman-docker-1.4.2-5.module_el8.1.0+237+63e26edc.noarch
[aaa@r8cn01 ~]$ rpm -qa |grep podman
podman-docker-1.4.2-5.module_el8.1.0+237+63e26edc.noarch
podman-1.4.2-5.module_el8.1.0+237+63e26edc.x86_64
podman-manpages-1.4.2-5.module_el8.1.0+237+63e26edc.noarch

**Comment by coldbloodx** [comment]
rootless mode:
[aaa@r8cn01 ~]$ docker run --rm -it --ulimit fsize="2000:-1" ubuntu hostname
Error: ulimit option "fsize=2000:-1" requires name=SOFT:HARD, failed to be parsed: ulimit soft limit must be less than or equal to hard limit: 2000 > -1

**Comment by rhatdan** [comment]
Does it work or doesn't it?

**Comment by coldbloodx** [comment]
@rhatdan 
it does NOT work.
test environment: rhel8.1, podman 1.4.2

**Comment by coldbloodx** [comment]
just tried on rhel 8.2,
it does NOT work either:
[root@lsf1x95 ~]# docker ps
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
[root@lsf1x95 ~]# docker run --rm -it --ulimit nofile=“2000:-1” centos /bin/sh
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull docker.io/library/centos...
Getting image source signatures
Copying blob 8a29a15cefae done
Copying config 470671670c done
Writing manifest to image destination
Storing signatures
Error: ulimit option “nofile=“2000:-1"” requires name=SOFT:HARD, failed to be parsed: strconv.ParseInt: parsing “-1”“: invalid syntax
[root@lsf1x95 ~]# rpm -qa|grep podman
podman-docker-1.6.4-1.module+el8.2.0+5182+3136e5d4.noarch
podman-1.6.4-1.module+el8.2.0+5182+3136e5d4.x86_64
podman-manpages-1.6.4-1.module+el8.2.0+5182+3136e5d4.noarch
cockpit-podman-11-1.module+el8.2.0+4966+a27241e9.noarch

**Comment by coldbloodx** [comment]
@rhatdan

a mistake, here, the encoding of the double quote(") is not correct, it works on rhel 8.2(podman 1.6.4). but it does NOT work on rhel 8.1(podman 1.4.2)

[root@lsf1x95 ~]# docker run --rm -it --ulimit fsize=“40992000:-1” centos /bin/sh
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
sh-4.4# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  5 06:15 pts/0    00:00:00 /bin/sh
root         8     1  0 06:15 pts/0    00:00:00 ps -ef
sh-4.4# cat /proc/1/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             40992000             unlimited            bytes

**Comment by rhatdan** [comment]
Ok so you are saying we have fixed this in the latest releases?
Closing issues, reopen if I am mistaken.

**Comment by coldbloodx** [comment]
yes, the cli works in podman 1.6.4.
