### ISSUE TITLE
Panic in varlinkapi.imagesToImageList

### ISSUE THREAD

**Issue by marusak** [containers/libpod#6021]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
In Cockpit tests we noticed that the connection to varlink drops and then we see go-panic in journal.
I don't actually have reproducer, but I hope that the logs are verbose enough.

**Describe the results you received:**
```
#0  0x00005611774e9251 runtime.raise (podman)                                   
#1  0x00005611774cf1fd runtime.sigfwdgo (podman)                                
#2  0x00005611774ce340 runtime.sigtrampgo (podman)                              
#3  0x00005611774e9543 runtime.sigtramp (podman)                                
#4  0x00007f6848affb20 __restore_rt (libpthread.so.0)                           
#5  0x00005611774e9251 runtime.raise (podman)                                   
#6  0x00005611774cee0a runtime.crash (podman)                                   
#7  0x00005611774b9496 runtime.fatalpanic (podman)                              
#8  0x00005611774b8e56 runtime.gopanic (podman)                                 
#9  0x00005611774ceb90 runtime.sigpanic (podman)                                
#10 0x0000561178769735 github.com/containers/libpod/pkg/varlinkapi.imagesToImageList (podman)
#11 0x0000561178769b33 github.com/containers/libpod/pkg/varlinkapi.(*VarlinkAPI).ListImages (podman)
#12 0x00005611785fa86e github.com/containers/libpod/pkg/varlink.(*VarlinkInterface).VarlinkDispatch (podman)
#13 0x00005611785eb707 github.com/containers/libpod/vendor/github.com/varlink/go/varlink.(*Service).HandleMessage (podman)
#14 0x00005611785ebb9e github.com/containers/libpod/vendor/github.com/varlink/go/varlink.(*Service).handleConnection (podman)
#15 0x00005611774e7841 runtime.goexit (podman)       
```
and the more verbose version: [bt1.txt](https://github.com/containers/libpod/files/4546028/bt1.txt)

It might be the same undrelying problem as with https://github.com/containers/libpod/issues/6018 as it is happening in the same test, the differenc is that we run it once as root and once as rootless (this one is the root one, #6018 is rootless). But the traceback looks completly different, so I opened it separatelly.

Our bots also saved the [core](https://logs.cockpit-project.org/logs/pull-370-20200428-120501-fb42efc7-fedora-32/TestApplication-testRunImageSystem-fedora-32-127.0.0.2-2201-FAIL.core/)

Possibly it happens when we execute `podman rmi -f $(podman images -q)` but this might be just red-harring.

**Comment by rhatdan** [comment]
@marusak Since we are moving away from Varlink and your team is moving to APIV2, we are not likely to fix or even look into this.  Al-right if I close this?

**Comment by marusak** [comment]
Sure, Today I tested the REST API on our tests and it seems to work rather nicely. And hopefully podman-2.0.0 is behind the corner, so we can close this.
