### ISSUE TITLE
[rootless] `podman ps`  doesnot show running container even though container processes are still running

### ISSUE THREAD

**Issue by grronline** [containers/libpod#6034]
[information.txt](https://github.com/containers/libpod/files/4550018/information.txt)

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
systemd based containers in rootless mode after some hours/days fails to get displayed with `podman ps`
1.

2.

3.

**Describe the results you received:**
`podman ps`  doesnot display the running containers 

**Describe the results you expected:**
it should display the running containers

**Additional information you deem important (e.g. issue happens only occasionally):**
unable to simulate further as podman start on the same container gives below error
Error: unable to start container "containerName": unable to find user postgres: no matching entries in passwd file

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 6ffbb2ec70dbe5ba56e4bfde946fb04f19dd8bbf'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 600000
      size: 1
    - container_id: 1
      host_id: 666666
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 600000
      size: 1
    - container_id: 1
      host_id: 666666
      size: 65536
  MemFree: 2170466304
  MemTotal: 8192004096
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2097147904
  SwapTotal: 2097147904
  arch: amd64
  cpus: 4
  eventlogger: file
  hostname: hostname
  kernel: 4.18.0-147.5.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-2.git21fdece.module+el8.1.1+5460+3ac089c3.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 308h 46m 53.3s (Approximately 12.83 days)
registries:
  blocked:
  - all
  insecure: null
  search:
  - path1
  - path2
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-1.module+el8.1.1+5259+bcdd613a.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 5
  RunRoot: /tmp/run-600000
  VolumePath: /home/podman/.local/share/containers/storage/volumes


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware based vm

**Comment by giuseppe** [comment]
are you running the container through a systemd service or is systemd running inside of the container?

Is lingering mode enabled for your user?

**Comment by grronline** [comment]
we are actually trying to run the container through a systemd service, lingering mode is not enabled for the user.
 ls -l /var/lib/systemd/linger
ls: cannot access '/var/lib/systemd/linger': No such file or directory

is it required only during rootless container being run as systemd or for any rootless container?
please share any document link for rootless container, which has the above information, so that i don't miss out on any other prerequisites.

**Comment by mheon** [comment]
Providing the systemd unit used to launch the container would help greatly.

Also, can you try a `podman ps --all --sync` when this happens and see if the container registers as running

**Comment by grronline** [comment]
actually i had tried podman ps --all --sync that didn't help, so had to kill the conmon process and rebooted the box, post which starting the container gives the below error
Error: unable to start container "containerName": unable to find user postgres: no matching entries in passwd file

more information is present in the attachment information.txt

**Comment by grronline** [comment]
any update

**Comment by giuseppe** [comment]
if you want to run rootless containers through systemd I suggest to manage their lifecycle through the systemd user session `systemctl --user` or at least make sure lingering mode is enabled.

Setting just `User=` in the systemd service file will not set up the session for the rootless user and will confuse Podman/OCI runtime.

Also the `MemoryMax=3G` and `CPUQuota=20%` limits you've specified do not apply to the container payload as it runs in a different cgroup.  You need to set these limits through Podman.

**Comment by balamuruganravi** [comment]
@giuseppe @mheon 
I am also facing this issue `podman ps` not listing the running container after 3-4 days. 
could you please help me to understand the issue. when I try to get inside the container `podman exec -it elasticsearch /bin/bash` throws 

> Error: cannot exec into container that is not running: container state improper.

### My config details
Podman Version: 1.4.4
AWS RHEL 7.7 & 8.1 
Instance Type: t3a.large 8GB RAM

### Podman run command:
`podman run -d \
-p {{port}}:{{port}} \
--name $CONTAINER_NAME \
-h $CONTAINER_NAME \
-v $CONTAINER_NAME:/usr/share/elasticsearch/data \
-e "ES_JAVA_OPTS=-Xms{{ jvm_heap_size_min }} -Xmx{{ jvm_heap_size_max }}" \
-e "node.master=true" \
-e "node.ingest=true" \
-e "node.data=true" \
$CONTAINER_IMAGE`


`podman@ip-xx-xxx-xxx-xxx[~] $ podman info
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 763367424
  MemTotal: 16507850752
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: ip-xx-xxx-xxx-xxx.cloud.net
  kernel: 3.10.0-1062.12.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 435h 3m 52.15s (Approximately 18.12 days)
registries:
  blocked:
  - all
  insecure: null
  search:
  - company.artifactory.com
  - company.artifactory.com
store:
  ConfigFile: /home/podman/.config/containers/storage.conf
  ContainerStore:
    number: 6
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/podman/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 7
  RunRoot: /tmp/run-600000
  VolumePath: /home/podman/.local/share/containers/storage/volumes`

**Comment by grronline** [comment]
@giuseppe ,

i have made note of your point regarding lingering mode,  podman related resource control parameters like memory,cpu in rootless mode give below error, cgroup v2 is still in technical evaluation stages in rhel 8.1 platform, how can we achieve resource control in rootless mode.

demopod@hostname[DEV][~] $ podman create --cpus=2 --name test localhost/postgres:12
Error: invalid configuration, cannot specify resource limits without cgroups v2 and --cgroup-manager=systemd
demopod@hostname[DEV][~] $ podman create --memory=2G --name test localhost/postgres:12
Error: invalid configuration, cannot specify resource limits without cgroups v2 and --cgroup-manager=systemd
demopod@hostname[DEV][~] $ podman create  --name test localhost/postgres:12
90302a4a9eaae56898cd2ea03a9476be20731a8fa21be971760a77e36aa903e2

regards.

**Comment by giuseppe** [comment]
unfortunately there is no way of achieving it without cgroup v2, cgroup delegation on cgroup v1 is not safe.

If you need resource control on cgroup v1, then you should use root containers

**Comment by rhatdan** [comment]
@giuseppe Will runc be able to support cgroupV2 by RHEL 8.3?

**Comment by giuseppe** [comment]
> @giuseppe Will runc be able to support cgroupV2 by RHEL 8.3?

I believe so

**Comment by balamuruganravi** [comment]
> @giuseppe @mheon
> I am also facing this issue `podman ps` not listing the running container after 3-4 days.
> could you please help me to understand the issue. when I try to get inside the container `podman exec -it elasticsearch /bin/bash` throws
> 
> > Error: cannot exec into container that is not running: container state improper.
> 
> ### My config details
> Podman Version: 1.4.4
> AWS RHEL 7.7 & 8.1
> Instance Type: t3a.large 8GB RAM
> 
> ### Podman run command:
> `podman run -d \ -p {{port}}:{{port}} \ --name $CONTAINER_NAME \ -h $CONTAINER_NAME \ -v $CONTAINER_NAME:/usr/share/elasticsearch/data \ -e "ES_JAVA_OPTS=-Xms{{ jvm_heap_size_min }} -Xmx{{ jvm_heap_size_max }}" \ -e "node.master=true" \ -e "node.ingest=true" \ -e "node.data=true" \ $CONTAINER_IMAGE`
> 
> `podman@ip-xx-xxx-xxx-xxx[~] $ podman info
> host:
> BuildahVersion: 1.9.0
> Conmon:
> package: podman-1.4.4-4.el7.x86_64
> path: /usr/libexec/podman/conmon
> version: 'conmon version 0.3.0, commit: unknown'
> Distribution:
> distribution: '"rhel"'
> version: "7.7"
> MemFree: 763367424
> MemTotal: 16507850752
> OCIRuntime:
> package: runc-1.0.0-65.rc8.el7.x86_64
> path: /usr/bin/runc
> version: 'runc version spec: 1.0.1-dev'
> SwapFree: 0
> SwapTotal: 0
> arch: amd64
> cpus: 4
> hostname: ip-xx-xxx-xxx-xxx.cloud.net
> kernel: 3.10.0-1062.12.1.el7.x86_64
> os: linux
> rootless: true
> uptime: 435h 3m 52.15s (Approximately 18.12 days)
> registries:
> blocked:
> 
> * all
>   insecure: null
>   search:
> * company.artifactory.com
> * company.artifactory.com
>   store:
>   ConfigFile: /home/podman/.config/containers/storage.conf
>   ContainerStore:
>   number: 6
>   GraphDriverName: vfs
>   GraphOptions: null
>   GraphRoot: /home/podman/.local/share/containers/storage
>   GraphStatus: {}
>   ImageStore:
>   number: 7
>   RunRoot: /tmp/run-600000
>   VolumePath: /home/podman/.local/share/containers/storage/volumes`

@giuseppe could you please provide your comments for this issue. also I have tried the `podman ps --all --sync` but it didn't help

**Comment by mheon** [comment]
@balamuruganravi Are you managing the container with systemd? Also, any chance you could try a more recent Podman version - 1.4.4 is getting very long in the tooth.

**Comment by balamuruganravi** [comment]
No I am not using systemd for managing the containers.  
I am facing this problem even on `podman version`
```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64 
```

**Comment by mheon** [comment]
Can you confirm that the container is still running? The container process should also have a `conmon` parent; can you check if `conmon` is dead if the container process is not?

**Comment by balamuruganravi** [comment]
Yes the container is running and I am able to access the application URL. can you please provide me the cmd/steps to check the `conmon ` process status

**Comment by mheon** [comment]
Try and find the PID of the process in the container (looks like a JVM from my initial glance). Then, see what the parent of that PID is - I usually use a tool like htop to do this. We expect every container to have a Conmon process as its parent.

Also, providing `podman inspect` for the container in question may help.

**Comment by balamuruganravi** [comment]
To find the PID of the process executed the `netstat -tulpn | grep LISTEN`  and got the belwo PID
`tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      20190/slirp4netns`

then executed the ` ps -ef | grep 20190` and got the PPID as 1
> podman   11989 20587  0 05:06 pts/1    00:00:00 grep --color=auto 20190
> podman   20190     1  0 Apr20 ?        00:05:59 /usr/bin/slirp4netns --api-socket /tmp/run-600000/libpod/tmp/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc.net --disable-host-loopback --mtu 65520 --enable-sandbox -c -e 3 -r 4 --netns-type=path /tmp/run-600000/netns/cni-9f29a76d-0791-a48c-8ec2-94244bff42dd tap0

```
podman@ip-xx-xx-xxx-xx[~] $ podman inspect elasticsearch
[
    {
        "Id": "dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc",
        "Created": "2020-04-20T04:28:17.102542074Z",
        "Path": "/usr/local/bin/docker-entrypoint.sh",
        "Args": [
            "eswrapper"
        ],
        "State": {
            "OciVersion": "1.0.1-dev",
            "Status": "configured",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-04-20T04:28:17.591506401Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "00b3863e02b053f496bd4cb792416e8cc8681d496cece7ae52b684f1fa1d7163",
        "ImageName": "artifactory.com/elasticsearch-7.6.1:v1",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "StaticDir": "/home/podman/.local/share/containers/storage/overlay-containers/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc/userdata",
        "OCIConfigPath": "/home/podman/.local/share/containers/storage/overlay-containers/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc/userdata/config.json",
        "OCIRuntime": "runc",
        "LogPath": "/home/podman/.local/share/containers/storage/overlay-containers/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc/userdata/ctr.log",
        "ConmonPidFile": "/tmp/run-600000/overlay-containers/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc/userdata/conmon.pid",
        "Name": "elasticsearch",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "system_u:object_r:container_file_t:s0:c174,c671",
        "ProcessLabel": "system_u:system_r:container_t:s0:c174,c671",
        "AppArmorProfile": "",
        "EffectiveCaps": null,
        "BoundingCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FSETID",
            "CAP_FOWNER",
            "CAP_MKNOD",
            "CAP_NET_RAW",
            "CAP_SETGID",
            "CAP_SETUID",
            "CAP_SETFCAP",
            "CAP_SETPCAP",
            "CAP_NET_BIND_SERVICE",
            "CAP_SYS_CHROOT",
            "CAP_KILL",
            "CAP_AUDIT_WRITE"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/home/podman/.local/share/containers/storage/overlay/6e79b8cbf0fa552af260c2943f7d49ebf961c15761279368834b05861c563aad/diff:/home/podman/.local/share/containers/storage/overlay/cc5cbd28c39535046f5c28b129dab3a5ea25a71ba2f9e4678e2418b1673390d6/diff:/home/podman/.local/share/containers/storage/overlay/a1959f33a7419876e2c551328b43ccfa9fec7d89858f00ce353341a8eca40d10/diff:/home/podman/.local/share/containers/storage/overlay/abb1462d95ce8944f4e27c00fa5cd6fc45d645ade503786a11512036681225a7/diff:/home/podman/.local/share/containers/storage/overlay/0342de846b7a2634ef4ec67b5a259a84c3bbd1897ff4f72433b7824af08ee316/diff:/home/podman/.local/share/containers/storage/overlay/2b167555db74dbae930dc172c112c7744198efc2ffb56b14067b5256f8729735/diff:/home/podman/.local/share/containers/storage/overlay/069b7fbf53a8680e5b5cf55fc5d8b960b674035f102130de9cc795c572d08d44/diff:/home/podman/.local/share/containers/storage/overlay/77b174a6a187b610e4699546bd973a8d1e77663796e3724318a2a4b24cb07ea0/diff",
                "MergedDir": "/home/podman/.local/share/containers/storage/overlay/b5df552e8d61fc96702a290cb36b309f5dd426267ee5c40bff587a3aed4a7eda/merged",
                "UpperDir": "/home/podman/.local/share/containers/storage/overlay/b5df552e8d61fc96702a290cb36b309f5dd426267ee5c40bff587a3aed4a7eda/diff",
                "WorkDir": "/home/podman/.local/share/containers/storage/overlay/b5df552e8d61fc96702a290cb36b309f5dd426267ee5c40bff587a3aed4a7eda/work"
            }
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "elasticsearch",
                "Source": "/home/podman/.local/share/containers/storage/volumes/elasticsearch/_data",
                "Destination": "/usr/share/elasticsearch/data",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "noexec",
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Dependencies": [],
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": [
                {
                    "hostPort": 9200,
                    "containerPort": 9200,
                    "protocol": "tcp",
                    "hostIP": ""
                },
                {
                    "hostPort": 9300,
                    "containerPort": 9300,
                    "protocol": "tcp",
                    "hostIP": ""
                }
            ],
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": ""
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/home/podman/.local/share/containers/storage",
            "--runroot",
            "/tmp/run-600000",
            "--log-level",
            "error",
            "--cgroup-manager",
            "cgroupfs",
            "--tmpdir",
            "/tmp/run-600000/libpod/tmp",
            "--runtime",
            "runc",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mount_program=/usr/bin/fuse-overlayfs",
            "--events-backend",
            "file",
            "container",
            "cleanup",
            "dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "elasticsearch",
            "Domainname": "",
            "User": "elasticsearch",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "http_proxy=http://10.xxx.xxx.xx:8080",
                "https_proxy=http://10.xx.xxx.xx:8080",
                "NO_PROXY=xx.x.xxx.xx",
                "HOSTNAME=elasticsearch",
                "container=podman",
                "http.host=0.0.0.0",
                "xpack.monitoring.collection.enabled=true",
                "bootstrap.memory_lock=true",
                "ELASTIC_CONTAINER=true",
                "ES_HOME=/usr/share/elasticsearch",
                "ES_JAVA_OPTS=-Xms2g -Xmx2g",
                "discovery.type=single-node",
                "cluster.name=es-singlenode-cluster",
                "path.data=/usr/share/elasticsearch/data",
                "HOME=/usr/share/elasticsearch"
            ],
            "Cmd": [
                "eswrapper"
            ],
            "Image": "artifactory.com/elasticsearch-7.6.1:v1",
            "Volumes": null,
            "WorkingDir": "/usr/share/elasticsearch",
            "Entrypoint": "/usr/local/bin/docker-entrypoint.sh",
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2020-02-29T00:15:25.529771Z",
                "org.label-schema.license": "Elastic-License",
                "org.label-schema.name": "Elasticsearch",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://www.elastic.co/products/elasticsearch",
                "org.label-schema.usage": "https://www.elastic.co/guide/en/elasticsearch/reference/index.html",
                "org.label-schema.vcs-ref": "aa751e09be0a5072e8570670309b1f12348f023b",
                "org.label-schema.vcs-url": "https://github.com/elastic/elasticsearch",
                "org.label-schema.vendor": "Elastic",
                "org.label-schema.version": "7.6.1",
                "org.opencontainers.image.created": "2020-02-29T00:15:25.529771Z",
                "org.opencontainers.image.documentation": "https://www.elastic.co/guide/en/elasticsearch/reference/index.html",
                "org.opencontainers.image.licenses": "Elastic-License",
                "org.opencontainers.image.revision": "aa751e09be0a5072e8570670309b1f12348f023b",
                "org.opencontainers.image.source": "https://github.com/elastic/elasticsearch",
                "org.opencontainers.image.title": "Elasticsearch",
                "org.opencontainers.image.url": "https://www.elastic.co/products/elasticsearch",
                "org.opencontainers.image.vendor": "Elastic",
                "org.opencontainers.image.version": "7.6.1"
            },
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.ContainerType": "sandbox",
                "io.kubernetes.cri-o.Created": "2020-04-20T04:28:17.102542074Z",
                "io.kubernetes.cri-o.TTY": "false",
                "io.podman.annotations.autoremove": "FALSE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "15"
            },
            "StopSignal": 15
        },
        "HostConfig": {
            "Binds": [
                "elasticsearch:/usr/share/elasticsearch/data:rw,rprivate,noexec,nosuid,nodev,rbind"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null
            },
            "NetworkMode": "default",
            "PortBindings": {
                "9200/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9200"
                    }
                ],
                "9300/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9300"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1024,
                    "Hard": 1024
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        }
    }
]
```

**Comment by giuseppe** [comment]
another possibility is that systemd automatically cleans up files under `/tmp` and we lose track of the 
containers.

https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles.html

Can you show the content of `/tmp/run-600000` when the container disappears?

**Comment by balamuruganravi** [comment]
`ls /tmp/run-600000`

> libpod  netns  overlay  overlay-containers  overlay-layers  overlay-locks  runc

**Comment by giuseppe** [comment]
can you please show the output for `find /tmp/run-600000/libpod /tmp/run-600000/runc` ?

**Comment by balamuruganravi** [comment]
podman@ip-xx.xx.xxx[~] $ `find /tmp/run-600000/libpod /tmp/run-600000/runc`

/tmp/run-600000/libpod
/tmp/run-600000/libpod/pause.pid
/tmp/run-600000/libpod/tmp
/tmp/run-600000/libpod/tmp/events
/tmp/run-600000/libpod/tmp/events/events.log
/tmp/run-600000/libpod/tmp/events/events.log.lock
/tmp/run-600000/libpod/tmp/socket
/tmp/run-600000/libpod/tmp/socket/3ee91c0e041f8e127e328f184b13e4d5eaf0261ade9a221543cc8963c5097b66
/tmp/run-600000/libpod/tmp/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc.net
/tmp/run-600000/libpod/tmp/5b178e410148a54df8e35935284c45bff765f343fd4db1b143a048404554b5ed.net
/tmp/run-600000/libpod/tmp/f95be159a55c1dec7cacd78260e2e8d24637d8eb6af2c00ae425a5531e216862.net
/tmp/run-600000/libpod/tmp/3722b259376bb8760141c2f8c5bc9b06c1579f295adcb0412133dec2d4f4b87f.net
/tmp/run-600000/libpod/tmp/1131ca6c7adec4b3d07e2b7199aa28ffc42029895f5ec87a3ecb7661476647ea.net
/tmp/run-600000/libpod/tmp/alive.lck
/tmp/run-600000/libpod/tmp/alive
/tmp/run-600000/libpod/tmp/exits
/tmp/run-600000/runc
/tmp/run-600000/runc/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc
/tmp/run-600000/runc/dcdbb0ba6c901f47361febcf2e2c8d96f8900437935e7cd51bc2cce626863fcc/state.json
/tmp/run-600000/runc/5b178e410148a54df8e35935284c45bff765f343fd4db1b143a048404554b5ed
/tmp/run-600000/runc/5b178e410148a54df8e35935284c45bff765f343fd4db1b143a048404554b5ed/state.json
/tmp/run-600000/runc/8738bf71a767b62efe538bca4dba09b55de3eaa9244f69661c44bf9e1586ace4
/tmp/run-600000/runc/8738bf71a767b62efe538bca4dba09b55de3eaa9244f69661c44bf9e1586ace4/state.json
/tmp/run-600000/runc/f95be159a55c1dec7cacd78260e2e8d24637d8eb6af2c00ae425a5531e216862
/tmp/run-600000/runc/f95be159a55c1dec7cacd78260e2e8d24637d8eb6af2c00ae425a5531e216862/state.json
/tmp/run-600000/runc/3722b259376bb8760141c2f8c5bc9b06c1579f295adcb0412133dec2d4f4b87f
/tmp/run-600000/runc/3722b259376bb8760141c2f8c5bc9b06c1579f295adcb0412133dec2d4f4b87f/state.json
/tmp/run-600000/runc/1131ca6c7adec4b3d07e2b7199aa28ffc42029895f5ec87a3ecb7661476647ea
/tmp/run-600000/runc/1131ca6c7adec4b3d07e2b7199aa28ffc42029895f5ec87a3ecb7661476647ea/state.json

**Comment by mheon** [comment]
`/tmp/run-600000/libpod/tmp/alive` being suddenly removed (by systemd or otherwise) sounds like a very good candidate here. That would make Libpod assume the system restarted and perform a full state refresh.

**Comment by balamuruganravi** [comment]
Yes. I'm not sure on why it exists suddenly. Could it possibly be a bug depending on the OS version? Is it sure that performing a state refresh will cause login rejections to containers but allow it to run? Trying to understand on how that works..

**Comment by giuseppe** [comment]
by default files older than 10 days are periodically deleted from `/tmp` (as configured in `/usr/lib/tmpfiles.d/tmp.conf`).

`/tmp` should be really used only for short lived sessions

**Comment by balamuruganravi** [comment]
I could see the below entry in `/usr/lib/tmpfiles.d/tmp.conf` file. is it causing the problem
```
# Clear tmp directories separately, to make them easier to override
v /tmp 1777 root root 10d
v /var/tmp 1777 root root 30d
```

**Comment by giuseppe** [comment]
I would say yes.  Files in that directories can disappear after a certain time.

**Comment by rhatdan** [comment]
Yes move your storage to /var/tmp (if that is not cleaned up, or better yet, allocate a directory owner by the user to store storage

**Comment by balamuruganravi** [comment]
Could you please help
To move storage to /var/tmp what file and param/key I should make changes

**Comment by giuseppe** [comment]
`/var/tmp` has exactly the same issue.  You need to use a directory not cleaned up by systemd

**Comment by balamuruganravi** [comment]
When I change path in `/home/podman/.config/containers/storage.conf` to `runroot = "/var/local"` and run the `podman info`
but it still shows the `RunRoot: /tmp/run-600000`  did I miss anything.

**Comment by rhatdan** [comment]
No, I believe we still use either /run or /tmp for "temporary" files.  The permanent storage should be in /var/local.
