### ISSUE TITLE
Fedora 32 version is lower than F31

### ISSUE THREAD

**Issue by abitrolly** [containers/libpod#6048]
/kind bug

I've just updated to F32 and my podman downgraded from 1.9.0 to 1.8.2.

**Describe the results you received:**

```bash
$ podman version
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.14
OS/Arch:            linux/amd64
```

**Describe the results you expected:**

Expected to use latest `podman` 2.0 with #5883 merged in (1.9.1 doesn't have the fix).

**Comment by vrothberg** [comment]
1.9.1 should land soon in F32.

> Expected to use latest podman 2.0 ...

2.0 does not exist yet. Note that the API is still experimental, so I am not sure if #5883 will make it into any release before 2.0.

**Comment by abitrolly** [comment]
I checked that #5883 works and would like to see that released for F32.

**Comment by abitrolly** [comment]
F32 is now with `podman` 1.9.1. Backporting #5883 is another issue.
