### ISSUE TITLE
Support named volumes?

### ISSUE THREAD

**Issue by ibuildthecloud** [containers/libpod#605]
Is there any thought to supporting named volumes?  Specifically
`podman run -v foo:/tmp blah`
`podman volume ls/rm/create`

I wouldn't expect podman to support volume drivers or anything such as that (unless CSI is usable, but let's ignore that).  All I would expect is that a named volume is essentially an alias for a host path.  So `foo` is really just `/var/lib/container/volumes/foo`.  I know you can say that you don't need the syntactical sugar for bind mounts, but I think it's really quite nice.  Named volumes allow you too logically manage buckets of host storage.

**Comment by rhatdan** [comment]
We would not support using Daemons for these services. but I could see support for this short cut. I don't see this as a focus of the team at this point.  But I am sure we would accept patches.

**Comment by mheon** [comment]
My question would be how we would store the list of named volumes. It's not a libpod-level concept, so podman would have to find a temporary directory to dump it in. Maybe an artifacts API for libpod as a whole (similar to the per-container one) would help

**Comment by ibuildthecloud** [comment]
I think this would be difficult to contribute without some guidance.  The issue is that doing this suddenly creates shared assets that have to be refcounted or managed in some way.  So it wouldn't be straight forward.

**Comment by rhatdan** [comment]
I am going through old Issues, trying to figure out if they are still relevant.  On this one, @ibuildthecloud is this still something you are interested in?  Would this be just a directory on disk that would be handled sort of the way we handle builtin volumes in container images.

I am fine with adding this functionality and allowed to experiment.  Should there be support for quota on these volumes or just force admins to handle it.

**Comment by rhatdan** [comment]
@umohnani8 Is this something you would like to play with?

**Comment by rhatdan** [comment]
@cjeanner Thanks, @umohnani8 is working on this now.

**Comment by vrothberg** [comment]
Is there progress on this feature?

**Comment by mheon** [comment]
I believe Urvashi is getting close to finishing a patch to add this.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg ack @mehon's thought on @umohnani8 working on this now.  She and @rhatdan were talking about it in e-mail, she's finding new layers to the issue and is trying to get a patch together that covers a chunk of them, then follow up with another PR or two to wrap up.

**Comment by umohnani8** [comment]
Yup actively working on on this.

**Comment by rhatdan** [comment]
We now have the volume command so I believe this is fixed.  Reopen if I am mistaken.
