### ISSUE TITLE
rootless v2 podman pod create returns error

### ISSUE THREAD

**Issue by joequant** [containers/libpod#6119]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am packaging podman for mageia linux, and I've run into a problem I suspect is because I am packaging configuration files incorrectly.

When I run podman pod create with the git version of 20200417, I get

[joe@big-apple libpod-241326a9a8c20ad7f2bcf651416b836e7778e090 (master)]$ podman pod create 
ERRO[0000] CNINetworks can only be used with Bridge mode networking 

**Steps to reproduce the issue:**

1. build version git
2. Run podman pod create

**Describe the results you received:**

error message

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

I very s

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahversion: 1.14.8
  cgroupsversion: v2
  conmon:
    package: conmon-2.0.15-1.mga8
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: c97b7dde0977ca31c535f1bcd5d6f720bf3bf0c7'
  cpus: 4
  distribution:
    distribution: mageia
    version: "8"
  eventlogger: journald
  hostname: big-apple
  idmappings:
    gidmap:
    - containerid: 0
      hostid: 1000
      size: 1
    - containerid: 1
      hostid: 100000
      size: 65636
    uidmap:
    - containerid: 0
      hostid: 1000
      size: 1
    - containerid: 1
      hostid: 100000
      size: 65536
  kernel: 5.6.10-server-1.mga8
  memfree: 49775652864
  memtotal: 67335356416
  ociruntime:
    name: crun
    package: crun-0.13-1.mga8
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  runtimeinfo: {}
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.1-1.mga8
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapfree: 24847052800
  swaptotal: 24847052800
  uptime: 6h 5m 33.22s (Approximately 0.25 days)
store:
  configfile: /home/joe/.config/containers/storage.conf
  containerstore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphdrivername: vfs
  graphoptions: {}
  graphroot: /home/joe/.local/share/containers/storage
  graphstatus: {}
  imagestore:
    number: 0
  runroot: /run/user/1000/containers
  volumepath: /home/joe/.local/share/containers/storage/volumes
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
version:
  remoteapiversion: 1
  version: 2.0.0-dev
  goversion: go1.14.2
  gitcommit: b5458c11d2440e50e6225e24c1fb73a2219bc580
  built: 1588861917
  osarch: linux/amd64


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by joequant** [comment]
Here is the error for 20200507

'''
[joe@big-apple SPECS]$ podman pod create
ERRO[0001] Error freeing pod lock after failed creation: no such file or directory 
Error: error adding Infra Container: cannot join CNI networks if running rootless: invalid argument
'''

**Comment by mheon** [comment]
What Podman version?

**Comment by joequant** [comment]
It's version 2.0.0 prerelease.  Running from master.

When I dump out the c.config.Networks, I get the network slirp4net

**Comment by joequant** [comment]
It looks to me like the networking changed between v1 and v2, and without a configuration file, podman defaults to v1 options which breaks v2 networking.  Thoughts?

**Comment by mheon** [comment]
Podman v2 right now is not very stable, so it's entirely possible that this is a bug in master. I'll take a look.

If you're looking to package, I'd recommend trying the v1.9 stable branch for now - it's going to be receiving bugfixes and other backports for some time, and it's a lot more stable than master is now.

**Comment by joequant** [comment]
It' packaging for cauldron the bleeding edge part of Mageia.  Since we aren't releasing that soon, I prefer to work a little on the wild side.

Thanks for looking into it.  My suspicion is that without a config file that the defaults are being set to something odd.

**Comment by mheon** [comment]
I get slightly different error messages, but the same general theme - it looks like rootless `pod create` is setting the default network namespace configuration incorrectly. Should be a simple fix.

**Comment by joequant** [comment]
Cool.  If you need some help fixing it, just point me to the relevant code
and I can take a look.

One thing about podman v2 is that it seems faster.

在 2020年5月8日 週五 03:05，Matthew Heon <notifications@github.com> 寫道：

**Comment by mheon** [comment]
#6124 should fix, if you're willing to test
