### ISSUE TITLE
cp support

### ISSUE THREAD

**Issue by ibuildthecloud** [containers/libpod#613]
FEATURE REQUEST

mount/umount is more powerful than cp, but just as buildah is more powerful than a Dockerfile, you still support a Dockerfile.  cp is such a common task it would be nice if it was supported.

**Comment by mheon** [comment]
I can see making a `cp` command that mounts (if unmounted), copies, and then unmounts (if you initially did a mount) under the hood. We have the code to do all three, combining them shouldn't be that difficult.

**Comment by mheon** [comment]
If you were thinking of a more Docker-style copy via stdin, I'm not specifically opposed to that, but the simpler approach would be to reuse the existing mount-based code.

**Comment by rhatdan** [comment]
@ibuildthecloud Any comment on our suggestions?  Or should I close this?

**Comment by mheon** [comment]
@rhatdan I think this is still a good enhancement, we should leave it open

**Comment by vrothberg** [comment]
I can pick that up if you want to, and would follow @mheon's inital proposal to map cp to mount, cp, unmount. Are you okay with that?

**Comment by rhatdan** [comment]
Im fine with it.  My  only concern is handling multiple mounts/unmounts and making sure we handle this correctly.

**Comment by mheon** [comment]
I think mount/unmount session-based concurrency would need to happen first

**Comment by vrothberg** [comment]
> My only concern is handling multiple mounts/unmounts and making sure we handle this correctly.
> [...]
> I think mount/unmount session-based concurrency would need to happen first

@mheon, @rhatdan, I think we handle this now correctly, do we? I think the internal counter solves most of it. But I am not sure if multiple `unmounts` should break the `cp` or not?

**Comment by mheon** [comment]
I think the internal counter does solve this, as long as each mount only
unmounts once.

**Comment by rhatdan** [comment]
I agree.

**Comment by vrothberg** [comment]
Great, this seems ready to be implemented :+1:

**Comment by ktdreyer** [comment]
I was using podman today, and I was sad about the lack of "cp" parity with `docker`. Now I'm happy to find this issue.

**Comment by rhatdan** [comment]
Would be a simple bash script to generate the equivalent.  (I am not a big fan of docker cp).  But I guess we will have to implement it.
```
mnt=$(podman mount $ctr)
cp $mnt/var/lib/foobar /tmp
cp /etc/mydata.conf $mnt/etc
podman umount $ctr
```

**Comment by rhatdan** [comment]
@QiWang19 Could you look into adding this command.

**Comment by mheon** [comment]
I think this is definitely more urgent now that `podman mount` is broken for rootless
