### ISSUE TITLE
Trying to run mpi job in pod

### ISSUE THREAD

**Issue by firefly-serenity** [containers/libpod#6138]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

What I am trying to achieve is, having multiple mpi jobs on one host. What works so far is to start one job with the flags `--pid=host --net=host --ipc=host --userns=keep-id`

To seperate the two jobs it would be nice to have seperated namespaces between the jobs. So I thought this would be a great usecase for a pod. 

Since pods share the net and the ipc I created a pod like this:
`podman pod create --share=pid --name dyna-00`

And then tried to create containers in this pod using mpirun. 
But unfortunatly this fails with the following error:

crun:
```
Error: cannot setns `/proc/47477/ns/pid`: Operation not permitted
write to sync socket: Broken pipe: OCI runtime permission denied error
```

runc:
```
Error: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/chome/poduser/.local/share/containers/storage/overlay/3c2065ca89c1efa71279086b3e45c7ffffe4a9e1e332f4e6f54e8d097f5593fb/merged\\\" at \\\"/proc\\\" caused \\\"operation not permitted\\\"\"": OCI runtime permission denied error
MPI Application rank 3 exited before MPI_Init() with status 126
mpirun: Broken pipe
```

**Steps to reproduce the issue:**

1. `podman pod create --share=pid --name test`

2. `mpirun -hostfile hostfile podman run --runtime /usr/bin/crun --rm --env-host --userns=keep-id -d --pod test localhost/ls-dyna sleep 600`

**Describe the results you received:**

crun:
```
Error: cannot setns `/proc/47477/ns/pid`: Operation not permitted
write to sync socket: Broken pipe: OCI runtime permission denied error
```

runc:
```
Error: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/chome/poduser/.local/share/containers/storage/overlay/3c2065ca89c1efa71279086b3e45c7ffffe4a9e1e332f4e6f54e8d097f5593fb/merged\\\" at \\\"/proc\\\" caused \\\"operation not permitted\\\"\"": OCI runtime permission denied error
MPI Application rank 3 exited before MPI_Init() with status 126
mpirun: Broken pipe
```

**Describe the results you expected:**

Creation of 24 containers that sleep for 600 seconds

**Additional information you deem important (e.g. issue happens only occasionally):**

When looking at the pod after the error happens, there are ~5 containers associated to the pod. But they are in status created and are not running

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.1.1+5259+bcdd613a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 6ffbb2ec70dbe5ba56e4bfde946fb04f19dd8bbf'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 77095333888
  MemTotal: 134818603008
  OCIRuntime:
    name: runc
    package: runc-1.0.0-60.rc8.module_el8.1.0+237+63e26edc.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 4287610880
  SwapTotal: 4294963200
  arch: amd64
  cpus: 48
  eventlogger: journald
  hostname: smtcac1903
  kernel: 4.18.0-147.3.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /bin/slirp4netns
    Package: slirp4netns-0.4.2-2.git21fdece.module+el8.1.1+5460+3ac089c3.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 1493h 26m 33.17s (Approximately 62.21 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /chome/poduser/.config/containers/storage.conf
  ContainerStore:
    number: 81
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-0.4.1-1.module_el8.1.0+237+63e26edc.x86_64
      Version: |-
        fuse-overlayfs: version 0.4.1
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /chome/poduser/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /tmp/run-1002
  VolumePath: /chome/poduser/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by rhatdan** [comment]
Sorry @firefly-serenity This seems to have been lost i the noice.
@adrianreber @giuseppe PTAL

**Comment by giuseppe** [comment]
both crun and runc fail for the reason that we are trying to join a PID namespace and at the same time create a new user namespace.  The new user namespace doesn't own the PID namespace, so it cannot mount `/proc`.  We can't even workaround it from Podman as we cannot bind mount PID from the host.

We need to support `--userns keep-id` at the POD level so that it is not necessary to specify it for the container.

I will play with it and see if I can do anything from crun to handle this case.

**Comment by giuseppe** [comment]
I am still trying to figure out a way to address it in the OCI runtime.

I am going to close it as a dup of https://github.com/containers/libpod/issues/6153
