### ISSUE TITLE
generate systemd transportability

### ISSUE THREAD

**Issue by storrgie** [containers/libpod#6157]
This might be an unwelcome suggestion, so just close if so. When using `podman generate systemd` I encountered a couple issues:

 - Use of `%t` might cause users headaches
 - the `.cid` file doesn't get removed until you start the unit again, where systemd itself removes the `.pid` file.

podman has an opinionated scope of "user" when using it (pretty much all around). While working through the use case of "wanting to run rootless as a user but from the root system manager" I found that the use of `%t` with `podman generate systemd --new` would fail (permissions). Instead of using `%t`, could use `%T` for the actual `/tmp`, or `%h` for the uses home directory.

I ended up, for now, with a unit that looks like this:

```
[Unit]
Description=Podman container-mattermost-postgres.service
Wants=network.target
After=network-online.target

[Service]
WorkingDirectory=/opt/mattermost
User=mattermost
Group=mattermost
Environment=PODMAN_SYSTEMD_UNIT=%N
Restart=on-failure
ExecStart=/usr/bin/podman run --conmon-pidfile %T/%N.pid --cidfile %T/%N.cid --cgroups=no-conmon \
  --name=postgres12 \
  --env-file /opt/mattermost/postgres.env \
  --net=host --publish 127.0.0.1:5432:5432 \
  --volume /opt/mattermost/postgres:/var/lib/postgresql/data:Z \
  docker.io/postgres:12
ExecStop=/usr/bin/podman stop --ignore --cidfile %T/%N.cid -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f --cidfile %T/%N.cid
ExecStopPost=/usr/bin/rm -f %T/%N.cid
PIDFile=%T/%N.pid
KillMode=none
Type=simple

[Install]
WantedBy=multi-user.target default.target
```

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out and providing the details.

The `%t` issue is already tracked in https://github.com/containers/libpod/issues/5572. I am currently busy fighting other fires but will tackle it as soon as possible. I want to make sure that using another macro doesn't introduce other undesired side effects.

> the .cid file doesn't get removed until you start the unit again, where systemd itself removes the .pid file.

Is this causing a problem for your use case? Note that it's not systemd removing the pid file but conmon.

**Comment by storrgie** [comment]
Closed as duplicate of #5572.

**Comment by storrgie** [comment]
> Thanks for reaching out and providing the details.
> 
> The `%t` issue is already tracked in #5572. I am currently busy fighting other fires but will tackle it as soon as possible. I want to make sure that using another macro doesn't introduce other undesired side effects.
> 
> > the .cid file doesn't get removed until you start the unit again, where systemd itself removes the .pid file.
> 
> Is this causing a problem for your use case? Note that it's not systemd removing the pid file but conmon.

I'd love for there to be consistency then of removal of `.pid` and `.cid`. I think in almost every use case I saw the `.cid` stick around after the unit was stopped. It's not necessarily a problem for my use case as much as it's weird that conmon implicitly handles the `.pid` but doesn't handle the `.cid` (confusion of consistency).

**Comment by rhatdan** [comment]
%h could b e an issue on NFS homedirs systems, since they might require the user to login to be used.
