### ISSUE TITLE
debug log level should dump out system call for container exec

### ISSUE THREAD

**Issue by joequant** [containers/libpod#6158]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

This is a minor feature request to follow up with #6149.  One difficulty in debugging #6149 was the lack of diagnostic information.  When debug is turned on, podman should dump out the system call that was used to execute runc/crun and the parameters and data send to the container.  This will make it easier to debug problems

This should be similar to the data that is logged with conmon and the containerized networking.

**Steps to reproduce the issue:**

1.  Run with debug level = true

2. There is plenty of logging information to set up networking but no debug information on how the container was executed.

3.

**Describe the results you received:**

No logging for container execution

**Describe the results you expected:**

Container execution should be logged so that it is possible to manual run the container and see why the container failed and to produce better bug reports.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.0.0-dev
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.mga8
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: c97b7dde0977ca31c535f1bcd5d6f720bf3bf0c7'
  cpus: 4
  distribution:
    distribution: mageia
    version: "8"
  eventLogger: file
  hostname: big-apple
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65636
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-server-1.mga8
  memFree: 9061416960
  memTotal: 67335356416
  ociRuntime:
    name: crun
    package: crun-0.13-1.mga8
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
     spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.4-1.mga8
    version: |-
      slirp4netns version 0.4.4
      commit: d6d5ddec4d898c5592b273412c800bb384c9ac88
      libslirp: 4.2.0
  swapFree: 24845479936
  swapTotal: 24847052800
  uptime: 61h 46m 29.88s (Approximately 2.54 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/joe/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 3
    stopped: 2
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/joe/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 29
  runRoot: /run/user/1000/containers
  volumePath: /home/joe/.local/share/containers/storage/volumes
version:
  Built: 1588982710
  GitCommit: 3f967448eeda4956604995b08f34bcaa0adbf372
  GoVersion: go1.14.2
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
This seems like a request for the OCI runtime (runc/crun) - we don't directly run the process, instead we run Conmon, which then runs the OCI runtime, which performs the exec. We do print information on how Conmon was called.

**Comment by rhatdan** [comment]
I think @mheon answered this query, reopen if You believe we need to reveal more information.
