### ISSUE TITLE
Deprecated libpod.conf shipped on Ubuntu

### ISSUE THREAD

**Issue by vrandr** [containers/libpod#6162]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description:**

-  The current Ubuntu 18.04 package comes with an old configuration file `/usr/share/containers/libpod.conf`.
- The new `containers.conf` configuration file is not part of the package

**Steps to reproduce the issue:**

1. Install `podman_1.9.1~1_amd64.deb` on Ubuntu 18.04

2. Run `dpkg -L podman | grep libpod.conf`

3. Run `dpkg -L podman | grep containers.conf`

**Describe the results you received:**

- Package ships `/usr/share/containers/libpod.conf`

**Describe the results you expected:**

- Package should ship `/usr/share/containers/containers.conf`

**Output of `podman version`:**

```
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.10.1
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.15, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: hostname
  idMappings:
    gidmap:
    - container_id: 0
      host_id: uid
      size: 1
    - container_id: 1
      host_id: 820896
      size: 65536
    uidmap:
    - container_id: 0
      host_id: uid
      size: 1
    - container_id: 1
      host_id: 820896
      size: 65536
  kernel: 4.15.0-88-generic
  memFree: 206110720
  memTotal: 4135727104
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: unknown
  swapFree: 3107450880
  swapTotal: 4133482496
  uptime: 1507h 51m 10.19s (Approximately 62.79 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 16
  runRoot: /run/user/uid/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 1.9.1~1 amd64 [installed]
```

**Comment by mheon** [comment]
@rhatdan @baude @vrothberg Should we remove the example `libpod.conf` from the repo? I think that's where it's being sourced from.

**Comment by vrothberg** [comment]
SGTM
@lsm5 WDYT

**Comment by rhatdan** [comment]
Yes remove it and ship a containers.conf if we need customizations.  We are shipping a containers.conf in Fedora 32 now.

**Comment by lsm5** [comment]
@rhatdan Is it ok to use the containers.conf from the vendored containers/common the containers.conf inside libpod?

The containers.conf shipped in f32 skopeo/containers-common differs from the containers.conf vendored via containers/common inside libpod like so:

```
$ diff containers.conf ~/repositories/libpod/vendor/github.com/containers/common/pkg/config/containers.conf 
50,58d49
< # Control container cgroup configuration
< # Determines  whether  the  container will create CGroups.
< # Options are:
< # `enabled`   Enable cgroup support within container
< # `disabled`  Disable cgroup support, will inherit cgroups from parent
< # `no-conmon` Container engine runs run without conmon
< #
< # cgroups = "enabled"
< 
358,365d348
< 
< # List of the OCI runtimes that supports running containers without cgroups.
< #
< # runtime_supports_nocgroups = ["crun"]
< 
< # List of the OCI runtimes that supports running containers with KVM Separation.
< #
< # runtime_supports_kvm = ["kata"]
```

**Comment by lsm5** [comment]
btw, would the same registries.conf also be used by buildah? I guess it's best added to containers-common deb package then.

**Comment by rhatdan** [comment]
I think the containers.conf from Fedora would be fine.  Although it looks newer then what is in containers/common?  The registries.conf file in Ubuntu should probably drop the fedora registry.  Perhaps add an ubuntu registry if one exists.

**Comment by lsm5** [comment]
@vrandr please try `1.9.2~3` and lemme know. Should be available on OBS now.

**Comment by lsm5** [comment]
Closing. Please reopen if the issue persists..

**Comment by vrandr** [comment]
> @vrandr please try `1.9.2~3` and lemme know. Should be available on OBS now.

I can confirm that `/usr/share/containers/libpod.conf` is gone now.

Thank you!
