### ISSUE TITLE
please backport PR#6008 to 1.6.x (rhel-8 version)

### ISSUE THREAD

**Issue by cjeanner** [containers/libpod#6171]
/kind bug

Hello,

Would it be possible to backport the mentioned 4a5fd6ca60ed3b318b50aca7a2965d03ea2a8f67 commit in podman 1.6.x version?
We currently have 1.6.4 on rhel-8, it would be really, really helpful to get the patch available there.
This patch has already been backported to 1.9, but this version isn't in rhel-8 :(.

For more background about the issue, please check #5915

Thank you!

C.

**Comment by mheon** [comment]
Do you just want a scratch build, or do you want this to ship in RHEL? If the latter, can you open this as a Bugzilla, so we can start the formal backport process?

**Comment by EmilienM** [comment]
we'll need it in both CentOS8 and RHEL8. Cédric, can you open a BZ for RHEL8 please?

**Comment by cjeanner** [comment]
will do asap, thanks for the feedback!

**Comment by rhatdan** [comment]
Podman 1.9.1 will be in RHEL8.2.1 which is scheduled for July.

**Comment by cjeanner** [comment]
@rhatdan hmm, we can't wait for that one I think :(.
@mheon here's the BZ asking for the backport to rhel-8.1: https://bugzilla.redhat.com/show_bug.cgi?id=1834346

**Comment by mheon** [comment]
Handled upstream, going to close

**Comment by mheon** [comment]
Or downstream, rather
