### ISSUE TITLE
Podman fails with no relevant diagnostics

### ISSUE THREAD

**Issue by paoloantinori** [containers/libpod#6185]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman run` fails reporting only `Error: error executing hook `/usr/libexec/oci/hooks.d/oci-systemd-hook` (exit code: 1): OCI runtime error`

**Steps to reproduce the issue:**

1. `podman --log-level=debug  run  -it homeassistant/home-assistant:0.107.7`

2.

3.

**Describe the results you received:**
https://gist.github.com/paoloantinori/94ef7334005f8efd650180570cc1c490

**Describe the results you expected:**
Bring up the container

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens constantly

**Output of `podman version`:**
```
$ podman -v
podman version 1.9.1

$ cat /etc/redhat-release 
Fedora release 32 (Thirty Two)
```

```
Error: error executing hook `/usr/libexec/oci/hooks.d/oci-systemd-hook` (exit code: 1): OCI runtime error
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: trane
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-300.fc32.x86_64
  memFree: 19406098432
  memTotal: 33013309440
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 16609439744
  swapTotal: 16609439744
  uptime: 45m 10.39s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.redhat.io
  - registry.centos.org
store:
  configFile: /home/pantinor/.config/containers/storage.conf
  containerStore:
    number: 50
    paused: 0
    running: 0
    stopped: 50
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/pantinor/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/pantinor/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.1-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It seems that the breaking change happened between `homeassistant/home-assistant:0.107.0` and `homeassistant/home-assistant:0.106.0`, for the image that i'm trying to run.

Tailing `journalctl` I notice this error when I try running the container:

```
May 12 08:48:08 trane oci-systemd-hook[68720]: systemdhook <error>: 997bc100746f: Failed to get memory subsystem path for the process: File exists```

**Comment by vrothberg** [comment]
Thanks for opening the issue! In this case, there is nothing much Podman can do as the underlying container runtime executes the hook (i.e., crun). It's already being tracked over at crun: https://github.com/containers/crun/issues/353

**Comment by paoloantinori** [comment]
Thank you!

**Comment by paoloantinori** [comment]
@vrothberg I've built `crun` master but I still don't see anything.

Could you be able to confirm if you the 2 files created remain empty?:

```bash
podman run --runtime /usr/bin/crun --annotation io.containers.trace-syscall="of:/home/pantinor/prof.json" --annotation="run.oci.hooks.stderr=/tmp/out" --annotation="run.oci.hooks.stdout=/tmp/err" docker.io/homeassistant/amd64-homeassistant:0.107.0```

**Comment by vrothberg** [comment]
> ... --runtime /usr/bin/crun  ...
Isn't crun being install to `/usr/local/bin/crun` if you use the makefile?

To debug the seccomp hook, you can also use `sudo journalctl` and look for `oci-seccomp-bpf-hook`.

**Comment by paoloantinori** [comment]
you are right, thanks for spotting that!
```
 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/sh ./libtool   --mode=install /usr/bin/install -c crun '/usr/local/bin'
libtool: install: /usr/bin/install -c crun /usr/local/bin/crun
 /usr/bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 crun.1 '/usr/local/share/man/man1'
```

But I still cannot see anything in the output files or in `journalctl` logs.

Am I doing something clearly wrong or is there still a set of scenarios where no logs are presented?


https://gist.github.com/paoloantinori/fe325ca014e4f17d060c0236cb40d129

**Comment by vrothberg** [comment]
Can you try with a simple `alpine ls` container? Just to start with something known to work.

**Comment by jam01** [comment]
@paoloantinori did you figure this one out? I'm having the same issue with ghcr.io/hassio-addons/ubuntu-base/amd64:6.2.0

**Comment by rhatdan** [comment]
@jam01 Open a new issue or at least show us what is failing?  Usually we tell people to try as rootfull, if it is failing in rootless mode.
