### ISSUE TITLE
centos-8: build fails with missing btrfs/ioctl.h

### ISSUE THREAD

**Issue by ssbarnea** [containers/libpod#6213]
On CentOS-8, running `make` would fail to build libpod regardless which system dependencies you install because it needs `btrfs/ioctl.h` which is not provided by any  official distro repository.

**Describe the results you received:**
TBH

**Describe the results you expected:**

Detect missing dependency and attempt to install it, with failure if it fails to sudo.

**Comment by mheon** [comment]
I don't think this is a job for our makefile; we need to run on multiple distributions, and the names of packages are not really consistent between them (not to mention we might be building in a minimal container without a functioning package manager). Best we can do is probably to use `pkg-config` to detect whether things are installed, and warn if they're not (or set build tags, if there are tags available for the feature in question). I'm under the impression that we're presently doing that for btrfs; our build-tag generation should handle that case already.

**Comment by rhatdan** [comment]
Correct 

cat ./hack/btrfs_tag.sh 
#!/bin/bash
cc -E - > /dev/null 2> /dev/null << EOF
#include <btrfs/version.h>
EOF
if test $? -ne 0 ; then
	echo btrfs_noversion
fi

**Comment by rhatdan** [comment]
This seems to be an downstream issue, closing.
