### ISSUE TITLE
Specifying podman socket with podman cli.

### ISSUE THREAD

**Issue by smekkley** [containers/libpod#6219]
I noticed that now we have podman api socket.
Does/will it support something like this?
```
podman system service -t 0 tcp://0.0.0.0:5192
```
```
podman -H tcp://0.0.0.0:5192 ps
```

**Comment by mheon** [comment]
I'll defer to @rhatdan here, but I believe the answer is no - we're reluctant to add support for that as it will require us to provide authentication for the socket.

Instead, we're focusing on tunneling requests to the unix socket over SSH.

**Comment by rhatdan** [comment]
Yes, we will not listen on random ports.  The idea is to setup ssh connections to the host, that way we can rely on ssh to provide crypto/authentication/authorization and Podman does not need to do it.
That being said.   I am not sure if what you specified will not work.
@jwhonce @baude WDYT?

**Comment by smekkley** [comment]
I've already tried podman-remote through varlink with ssh. 
Then I found this that varlink is going to be deprecated, so i assumed no ssh client in podman which is not necessarily bad news to me. Because that means I have an option to use tcp directly or set up ssh tcp forwarding with openssh.

 https://github.com/containers/libpod/blob/master/docs/source/markdown/podman-system-service.1.md

**Comment by mheon** [comment]
We're definitely integrating SSH tunnelling into the remote Podman client, and I believe the Go bindings for the HTTP API as well (@jwhonce can confirm whether I'm right about that).

**Comment by baude** [comment]
yup

**Comment by rhatdan** [comment]
Also varklink is deprecated.  Not going away for a while.

**Comment by mheon** [comment]
I think this is adequately answered, so I'm going to close - if there are further questions, please open a fresh issue.
