### ISSUE TITLE
/usr/bin/podman version returns Error: default OCI runtime "crun" not found: invalid argument

### ISSUE THREAD

**Issue by raukadah** [containers/libpod#6226]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

*On Installing podman from master on fedora 31and creating the rpm using make package-install command 
and then run
podman version
It returns Error: default OCI runtime "crun" not found: invalid argument
**Steps to reproduce the issue:**

1.git clone https://github.com/containers/libpod

2. make package-install 

3. /usr/bin/podman version

**Describe the results you received:**

Error: default OCI runtime "crun" not found: invalid argument
make: *** [Makefile:698: package-install] Error 125

**Describe the results you expected:**
It should print the podman version.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
 /usr/bin/podman version
Error: default OCI runtime "crun" not found: invalid argument
make: *** [Makefile:698: package-install] Error 125
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-99:2.0.0-1589455624.git150679d7.fc31.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is failing on rdo ci. Here is the logs: https://logserver.rdoproject.org/27/27527/3/check/podman-package-fedora-31/7bb60b7/job-output.txt

**Comment by rhatdan** [comment]
Podman requires crun to run on cgroupV2 machines.

**Comment by vrothberg** [comment]
I believe there's a slight regression when running `podman version` which should not error out even if crun isn't installed. @giuseppe suspected in IRC that we might be loading the config for `podman version` but shouldn't.

**Comment by rhatdan** [comment]
Config is loaded by default for every podman command, and it must be complaining that the system has no container engine.  Must be in containers common that this is being checked. But removing the check will just cause systems to blow up with then attempt a podman run.

**Comment by rhatdan** [comment]
I don't see an easy fix for this.  The containers.conf would need to be modified.
