### ISSUE TITLE
Question: which combinations are possible: call podman from docker, docker from podman, etc.

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/libpod#6239]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
@PavelSosin-320 could you make your question clearer? At this point, the question is too wide to provide an accurate response.

**Comment by rhatdan** [comment]
Docker and Podman are two different container engines.  They work independently and neither requires the other.  Both work with the same container images and container registries and both launch containers using the same tools to configure the linux kernel to run containers (runc).

**Comment by dougsland** [comment]
@rhatdan good candidate for close?

**Comment by PavelSosin-320** [comment]
If Docker-In-Docker image exists and used as Dockerized Docker build environment is it possible to create Docker-in-Podman and Podman-in-Docker to use as dockerized build environment.? 
Technically it means is it possible to run Docker engine inside Podman container and vise-versa?

**Comment by rhatdan** [comment]
It should be possible to work this way yes.
