### ISSUE TITLE
Question: when do new podman releases, like 1.9.2, become available for Ubuntu?

### ISSUE THREAD

**Issue by jdockter** [containers/libpod#6240]
**Description**

Wondering how frequently new releases get pushed to repositories like kubic for platforms like Ubuntu
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/
?

**Comment by mheon** [comment]
They should be auto-built by OBS - @lsm5 can you elaborate here?

**Comment by afbjorklund** [comment]
Our problem is currently that they are _too_ new, and would prefer having e.g. 1.8.2 instead...

**Comment by jdockter** [comment]
@afbjorklund so is there a bug in podman-remote?  Is it possible to build another way?

**Comment by afbjorklund** [comment]
I suppose we can build from source

**Comment by afbjorklund** [comment]
There is some kind of limitation in the opensuse platform, so it can only keep one deb version.
And there are not multiple tracks like in cri-o, so the other releases are only available for RHEL.

#3924 #4937

Was looking for the older packaging, but seems most of it happened in a single commit.
So probably means having to build our own binaries, like we also do for podman-remote.

https://gitlab.com/lsm5/podman/-/tree/debian

**Comment by lsm5** [comment]
I have disabled autobuilds for podman atm. Working on getting crun included into OBS after which I'll build podman.

RE: older releases, I think I'll go the route of creating OBS subprojects for older releases, so in that case if you need an older release, it would be a matter of adding an additional apt repo and installing the release you like.

**Comment by lsm5** [comment]
Seems like podman entered debian unstable, so I guess we're gonna soon start recommending that as the go-to build for anyone that requires stability.

**Comment by jdockter** [comment]
@afbjorklund @lsm5 not sure I follow, so should I be seeing 1.9.2 at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ soon or should I get it from a different process/location?

**Comment by lsm5** [comment]
> @afbjorklund @lsm5 not sure I follow, so should I be seeing 1.9.2 at https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ soon or should I get it from a different process/location?

it's building now. Should be ready in sometime.

**Comment by RussianNeuroMancer** [comment]
Not installable currently:

```
~$ sudo aptitude install podman
The following NEW packages will be installed:
  catatonit{a} containers-common{a} containers-golang{a} containers-image{a} crun{a} libslirp0{a} 
  podman{b} podman-plugins{a} runc{a} slirp4netns{a} uidmap{a} varlink{a} 
0 packages upgraded, 12 newly installed, 0 to remove and 59 not upgraded.
Need to get 25.3 MB of archives. After unpacking 111 MB will be used.
The following packages have unmet dependencies:
 podman : Depends: conmon (>= 2.0.16) but 2.0.16~1 is installed
          Depends: containernetworking-plugins (>= 0.8.6) but 0.8.6~1 is installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     podman [Not Installed]                             



Accept this solution? [Y/n/q/?] 
```

Pay attention to the "~1" part of the conmon and containernetworking-plugins package version.

**Comment by lsm5** [comment]
hmm, let me push an update, thanks for that

**Comment by lsm5** [comment]
I pushed `1.9.2~2` just now to handle this. Should be ready in sometime.

**Comment by afbjorklund** [comment]
I will try to rebuild 1.8.2~2 from source. Sometimes I miss the .src.rpm.

```
podman (1.8.2~2) testing; urgency=medium

  * autobuilt v1.8.2

 -- RH Container Bot <rhcontainerbot@fedoraproject.org>  Thu, 19 Mar 2020 21:11:26 +0000

```

**Comment by afbjorklund** [comment]
@lsm5 : the package failed to build from source, something about varlink ?

```
make[1]: Entering directory '/build/podman-1.8.2~2'
GOPATH=/build/podman-1.8.2~2 GO111MODULE=off /usr/bin/go generate ./pkg/varlink/...
go: warning: "./pkg/varlink/..." matched no packages
GOPATH=/build/podman-1.8.2~2 GO111MODULE=off /usr/bin/go build -tags 'apparmor exclude_graphdriver_devicemapper seccomp systemd varlink' -ldflags '"-X main.buildInfo=1590321690"' -o bin/podman github.com/containers/libpod/cmd/podman
# github.com/containers/libpod/cmd/podman/shared
src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:70:42: undefined: iopodman.Create
src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:71:7: undefined: iopodman.Create
src/github.com/containers/libpod/cmd/podman/shared/intermediate_varlink.go:317:34: undefined: iopodman.Create
make[1]: *** [debian/rules:38: override_dh_auto_build] Error 2
```

```diff
--- a/debian/rules
+++ b/debian/rules
@@ -34,7 +34,7 @@ override_dh_auto_configure:
        ln -s $(BUILDDIR) $(BUILDDIR)/src/$(DH_GOPKG)
 
 override_dh_auto_build:
-       $(GO_GENERATE) ./pkg/varlink/...
+       $(GO_GENERATE) ./cmd/podman/varlink/...
        $(GO_BUILD) -tags '$(BUILDTAGS)' -ldflags '$(LDFLAGS_PODMAN)' -o bin/podman $(DH_GOPKG)/cmd/podman
        $(GO_BUILD) -tags '$(BUILDTAGS) remoteclient' -ldflags '$(LDFLAGS_PODMAN)' -o bin/podman-remote $(DH_GOPKG)/cmd/podman
        make docs

```


Also had to make the pbuilder BUILDHOME writable, for the go cache:

```
failed to initialize build cache at /nonexistent/.cache/go-build: mkdir /nonexistent: permission denied
```

```
#BUILD_HOME=/nonexistent
BUILD_HOME=$BUILDDIR
```

But then I was able to build the stable package for ubuntu focal:

```
/var/cache/pbuilder/result/podman_1.8.2~2_amd64.deb
/var/cache/pbuilder/result/podman-rootless_1.8.2~2_amd64.deb
```

`dpkg: warning: downgrading podman from 1.9.2~3 to 1.8.2~2
`

And now `podman-remote build` works again, unlike before. (#6237)

**Comment by afbjorklund** [comment]
Was able to find the original files for 1.8.2~2 now, with the working .dsc file. So ignore above

https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman?rev=137

**Comment by jdockter** [comment]
@lsm5 two questions for you:

1) From your [past comment](https://github.com/containers/libpod/issues/6240#issuecomment-629678116) do you still plan to support older versions of podman to be installed rather than just stable?

2) Also when install with `sudo apt-get -qq -y install --install-recommends podman` what additional packages are installed with that?

Thanks.
