### ISSUE TITLE
Error: error pulling "": unable to pull or load image on a root-less container

### ISSUE THREAD

**Issue by Chayatan** [containers/libpod#6250]
Problem: podman load -i rhel6-6.tar fails in non-root user environment

guest2@host:/home $podman load -i rhel6-6.tar
Getting image source signatures
Copying blob f65fa38dc372 done
Copying config 594a9a79ca done
Writing manifest to image destination
Storing signatures
ERRO[0006] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: invalid argument
ERRO[0006] Error pulling image ref rhel6-6.tar: Error committing the finished image: error adding layer with blob "sha256:f65fa38dc3729ba856434b2a8103c041cb5b06465b7884bb1eaa4c308378a3c4": ApplyLayer exit status 1 stdout:  stderr: invalid argument
Failed
ERRO[0006] Error pulling image ref rhel6-6.tar: Error determining manifest MIME type for dir:rhel6-6.tar: open rhel6-6.tar/manifest.json: not a directory
Failed
Error: error pulling "": unable to pull dir:rhel6-6.tar: unable to pull image: Error determining manifest MIME type for dir:rhel6-6.tar: open rhel6-6.tar/manifest.json: not a directory

Note: The same command works perfectly fine as root user.

root@host:home # podman load -i rhel6-6.tar
Getting image source signatures
Copying blob f65fa38dc372 done
Copying config 594a9a79ca done
Writing manifest to image destination
Storing signatures
Loaded image(s): rhel6:6.8-65

podman version 1.4.4
cat /etc/*id
guest2:165536:65536
guest2:165536:65536

**Comment by mheon** [comment]
Any chance this could be re-tried with a more recent Podman? RHEL/CentOS 7.8 and 8.2 should have a 1.6.x release of Podman available.

**Comment by rhatdan** [comment]
Where did rhel6-6.tar come from?
