### ISSUE TITLE
podman pod inspect: needs --format option

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#6283]
```console
$ podman pod inspect --format '{{.Containers.0.id}}' abc
Error: unknown flag: --format
```
Pretty low priority if noone has asked for this yet (I searched)

**Comment by boaz0** [comment]
if no body minds I would like to work on this.

**Comment by vrothberg** [comment]
Sure, thanks!

**Comment by zhangguanzhang** [comment]
https://github.com/containers/podman/blob/master/test/system/200-pod.bats#L99
this line should be removed?

**Comment by rhatdan** [comment]
@zhangguanzhang Please open a PR to remove it.

**Comment by edsantiago** [comment]
I've already got one, it's just pending a few other fixes so it's not a micro PR. I'll get it pushed out today.

**Comment by edsantiago** [comment]
See #7362
