### ISSUE TITLE
Download error 

### ISSUE THREAD

**Issue by sjbylo** [containers/libpod#6285]
Click on the "Latest remote client for MacOS" link shows this error. 

Download error: NoSuchKeyThe specified key does not exist.No such object: libpod-master-releases/podman-remote-latest-master-darwin-amd64.zip

**Comment by lsm5** [comment]
@cevich @jwhonce PTAL ^

**Comment by mheon** [comment]
#6277 will resolve this (though I still need to get an OS X build up for the latest release)

**Comment by mheon** [comment]
Fixed now
