### ISSUE TITLE
make error - undefined: varlinkapi.New

### ISSUE THREAD

**Issue by Edward5hen** [containers/libpod#6286]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I'm following [the installation doc](https://podman.io/getting-started/installation) to build podman from scratch for version [2.0.0-rc1](https://github.com/containers/libpod/releases/tag/v2.0.0-rc1) on fedora 32. An error happens while doing the make step: `undefined: varlinkapi.New`. I didn't see this when I `make` for previous versions.

**Steps to reproduce the issue:**

1. cd go/src/github.com/containers/
2. wget https://github.com/containers/libpod/archive/v2.0.0-rc1.tar.gz
3. tar -xzvf v2.0.0-rc1.tar.gz
4. cd libpod-2.0.0-rc1/
5. export GOPATH=~/go
6. make BUILDTAGS="selinux seccomp"

**Describe the results you received:**
```
[root@localhost libpod-2.0.0-rc1]# make BUILDTAGS="selinux seccomp"
make: Warning: File 'Makefile' has modification time 24498 s in the future
mkdir -p "/root/go/src/github.com/containers"
ln -sfn "/root/go/src/github.com/containers/libpod-2.0.0-rc1" "/root/go/src/github.com/containers/libpod"
ln -sfn "/root/go/src/github.com/containers/libpod-2.0.0-rc1/vendor/github.com/varlink" "/root/go/src/github.com/varlink"
touch .gopathok
# Only generate the varlink code on Linux (see issue #4814).
GO111MODULE=off go generate ./pkg/varlink/...
fatal: not a git repository (or any of the parent directories): .git
Podman is being compiled without the systemd build tag. Install libsystemd on 	Ubuntu or systemd-devel on rpm based distro for journald support.
GO111MODULE=on go build -mod=vendor  -gcflags 'all=-trimpath=/root/go/src/github.com/containers/libpod-2.0.0-rc1' -asmflags 'all=-trimpath=/root/go/src/github.com/containers/libpod-2.0.0-rc1' -ldflags '-X github.com/containers/libpod/libpod/define.gitCommit= -X github.com/containers/libpod/libpod/define.buildInfo=1589798152 -X github.com/containers/libpod/libpod/config._installPrefix=/usr/local -X github.com/containers/libpod/libpod/config._etcDir=/etc ' -tags "ABISupport selinux seccomp" -o bin/podman github.com/containers/libpod/cmd/podman
# github.com/containers/libpod/pkg/domain/infra/abi
pkg/domain/infra/abi/system.go:37:3: undefined: varlinkapi.New
make: *** [Makefile:184: bin/podman] Error 2
```

**Describe the results you expected:**
make successfully

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
# hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: d67f983da189a241a6bfe30d8774b0b2
           Boot ID: efcfae8632fa422dbdca04fc42bca9ef
    Virtualization: kvm
  Operating System: Fedora 32 (Server Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:32
            Kernel: Linux 5.6.6-300.fc32.x86_64
      Architecture: x86-64
```

**Comment by lsm5** [comment]
hmm, rawhide rpmbuilds work fine with BUILDTAGS  https://koji.fedoraproject.org/koji/packageinfo?packageID=26289 , but that's because they don't run `make` for building. Looking...

**Comment by lsm5** [comment]
@Edward5hen can you try `make BUILDTAGS="varlink selinux seccomp"`. The `varlink` tag needs to be specified. 

@baude @jwhonce @vrothberg do we expect this to succeed without the `varlink` tag?

**Comment by vrothberg** [comment]
> make BUILDTAGS="selinux seccomp"

I believe we need varlink. `make {binaries, podman, podman-remote}` set the build tags automatically. I recommend use these targets for building.

**Comment by vrothberg** [comment]
The `make BUILDTAGS="selinux seccomp"` in the installation docs refers to building runc. Maybe there was a confusion around that?

**Comment by mheon** [comment]
I would 100% expect Podman to build successfully without Varlink - that's a tag we added ourselves to gate whether Varlink support was added to the build.

**Comment by vrothberg** [comment]
> I would 100% expect Podman to build successfully without Varlink - that's a tag we added ourselves to gate whether Varlink support was added to the build.

`# github.com/containers/libpod/pkg/domain/infra/abi` ... I assume the varlink API isn't guarded by the build tag

**Comment by lsm5** [comment]
> > I would 100% expect Podman to build successfully without Varlink - that's a tag we added ourselves to gate whether Varlink support was added to the build.
> 
> `# github.com/containers/libpod/pkg/domain/infra/abi` ... I assume the varlink API isn't guarded by the build tag

thanks, I'll look into this..

**Comment by Edward5hen** [comment]
> @Edward5hen can you try `make BUILDTAGS="varlink selinux seccomp"`. The `varlink` tag needs to be specified.
> 
> @baude @jwhonce @vrothberg do we expect this to succeed without the `varlink` tag?

@lsm5 this issue is not seen if I add the tag varlink - `make BUILDTAGS="varlink selinux seccomp"`

**Comment by rhatdan** [comment]
Yes we need to be able to build without varlink.

**Comment by vrothberg** [comment]
FWIW, I cannot reproduce on latest master on F32.

**Comment by lsm5** [comment]
yes, I see that too. I'll update my PR to only get rid of the `go generate` step when building without varlink and not specify varlink tag by default.
