### ISSUE TITLE
podman stop command fails to properly stop container

### ISSUE THREAD

**Issue by alitvak69** [containers/libpod#6298]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.  Run container without detaching
```
podman run  --rm --net=host --no-hosts=true --name=httpd-echo --pull=always hashicorp/http-echo:latest -listen ':8080' -text 'Hello World'
```
2.  Stop container
```
podman stop httpd-echo
```
**Describe the results you received:**
On the stderr / stdout of attached terminal I get

`[ERR] Unknown signal terminated`

Eventually, after 10 seconds,  I see podman stop returning an id of stopped container
The same situation is with detached container but ERR is in the logs

**Describe the results you expected:**
No error, container is stopped quickly with command returning a stopped container id

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.10.1
  podmanVersion: 1.9.2
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.16, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: alex3.xcastlabs.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-62-generic
  memFree: 1206530048
  memTotal: 4136144896
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 2155h 55m 11.91s (Approximately 89.79 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 1.9.2~2 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

KVM virtual machine and physical hardware server

**Comment by mheon** [comment]
Are you sure that message is not coming from the app inside the container? That doesn't seem to match the format of the error logs Podman itself prints.

**Comment by baude** [comment]
I just verified it is indeed coming from inside the container.  The 10 seconds is a timeout.  It looks like the app in your program catches the first signal.  After a 10 second timeout, podman kills it.

**Comment by alitvak69** [comment]
Yes you are right, looks like they wait for interrupt to kill the server 
```
signalCh := make(chan os.Signal, 1)
	signal.Notify(signalCh, os.Interrupt)

	// Wait for interrupt
	<-signalCh
```
Tested with nginx an it all good, sorry for jumping to conclusions.

**Comment by alitvak69** [comment]
Now, I wonder though why podman ps is hanging when I issue podman stop against this container in different terminal.  It looks like podman is waiting for one container to die.

**Comment by baude** [comment]
because while podman is waiting for the timeout, it has the container locked.  you'd be better suited to do a `podman stop -t0 httpd-echo` in this case.

**Comment by alitvak69** [comment]
I think I understand.  Thank you all.
