### ISSUE TITLE
APIv2 Missing Network Endpoints

### ISSUE THREAD

**Issue by maxm123** [containers/libpod#6334]
/kind bug

In the list of APIv2 endpoints is an inconsistency concerning the use of the /libpod prefix. It's logical to use the '/libpod' prefix for services like pods, generate/play kube and the swagger (e.g. `VersionedPath("/libpod/pods/json")`).
But I don't understand this for volumes, networks and manifests (I'm not sure about container health checks). Are they intentionally prefixed?
I stumbled over this while trying so set up the Drone CI Docker Runner with Podman and the logging output told me: `Failed Request: (404:Not Found) for POST:'/v1.33/volumes/create'`. Aren't those three endpoints compatible to their Docker equivalents?

**Comment by mheon** [comment]
All our API endpoints are duplicated (containers, pods, volumes, images, exec sessions), and most offer the additional functionality we've added that Docker does not support (the list containers endpoint, for example - `/v1.0/libpod/containers/json` - supports displaying pod information - the compatibility endpoint, `/v1.40/containers/json`, does not).

Can I ask what Podman version you tried with? The remote API is presently marked alpha, and while I believe we have every endpoint we intend on implementing done on master (we have no plans to implement the swarm endpoints), earlier versions were definitely missing some. I don't recall if volumes were one of them, though. We're planning a v2.0.0 release in the near future that will include the latest work on the remote API and will promote it out of alpha status, so it may be wise to wait for that.

**Comment by baude** [comment]
We have not implemented compatibility endpoints for volumes as of yet.

**Comment by maxm123** [comment]
I use v1.9.2.
Yes, I see that the `r.HandleFunc(...)` calls without libpod are missing for volumes and networks which they do not for e.g. containers. I've spent ~an hour looking through the code and to me it seems as though the services work exactly like the docker spec requires them to do.

There are some parameters which aren't handled yet and the network/connect and network/disconnect endpoints are missing. Are they possible at all? I clicked through the container creation code and didn't find out how it would be possible. I thought I could try to implement those two endpoints but I probably lack the depth of knowledge of the container runtime interfaces and the libpod code.

Anyway, I am happily awaiting v2.0.0, thanks for this awesome software 👍  .

**Comment by mheon** [comment]
Network stuff is difficult because of our CNI network stack, but I think I have some ideas about it. The inspect endpoint should already be ready.

**Comment by mheon** [comment]
Given this is mostly a request about network endpoints now, I'm going to rename and change to kind/feature

**Comment by baude** [comment]
we have network endpoints for compat and libpod.
