### ISSUE TITLE
remove doc reference to upcoming RHEL 7.7 release

### ISSUE THREAD

**Issue by ktdreyer** [containers/libpod#6349]
/kind bug

**Description**

The troubleshooting documentation says "Note RHEL 7 and CentOS 7 will not have support for this until RHEL7.7 is released", and Red Hat [shipped RHEL 7.7](https://access.redhat.com/errata/RHBA-2019:2351) a while ago.

**Describe the results you expected:**

The documentation should describe the default behavior with the latest released RHEL 7 utilities.

**Comment by rhatdan** [comment]
Please open a PR to fix the issue.
