### ISSUE TITLE
Varlink API - GetEvents not working on Ubuntu

### ISSUE THREAD

**Issue by EricJeffrey** [containers/libpod#6370]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

call to GetEvents on Ubuntu only return a system events, instead of what `podman stats` output

**Steps to reproduce the issue:**

1. On Ubuntu 18.04, installed by kubic

2. varlink call unix:/run/podman/io.podman/io.podman.GetEvents "{}"

**Describe the results you received:**
`{
  "events": {
    "id": "",
    "image": "",
    "name": "",
    "status": "refresh",
    "time": "2020-05-19T11:21:02.485891823+08:00",
    "type": "system"
  }
}`

**Describe the results you expected:**
things like what `podman events` generate

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.11.6
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.11.6
  podmanVersion: 1.9.2
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.16, commit: '
  cpus: 40
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: T440B
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-99-generic
  memFree: 49546964992
  memTotal: 66975105024
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 65534947328
  swapTotal: 65534947328
  uptime: 145h 58m 23.8s (Approximately 6.04 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
正在列表... 完成
podman/未知 1.9.2~3 armhf
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by mheon** [comment]
@baude PTAL

**Comment by EricJeffrey** [comment]
well, guess I've figured it out, might because of the `events_logger` configuration. also is `libpod.conf` replaced by `containers.conf`?

**Comment by EricJeffrey** [comment]
turn out to be my unknown about varlink, need to use `more` parameter to get stream data.
