### ISSUE TITLE
Missing libglib2.0 dependency for Debian 10 packages

### ISSUE THREAD

**Issue by yurinnick** [containers/libpod#6371]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Debian 10 package has missing dependency `libglib2.0-0`

**Steps to reproduce the issue:**

1. Follow the Debian 10 installation instruction from the `podman.io` website

2. Verify installation:

```
$ podman
Error: could not get runtime: please update to v2.0.1 or later: outdated conmon version

$ /usr/libexec/podman/conmon
/usr/libexec/podman/conmon: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```

3. Install `libglib2.0-0`

```
$ sudo apt-get install libglib2.0-0
```

4. Verify fix:
```
$ /usr/libexec/podman/conmon --version
conmon version 2.0.16
commit:

$ podman --version
podman version 1.9.2
```

**Describe the results you received:** Podman installation assumes that Linux distro  has `libglib` installed, but not specifically specify it as a dependency, resulting issues on distros line DietPi

**Describe the results you expected:** Packages has all required dependencies

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.9.2
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.11.6
  podmanVersion: 1.9.2
host:
  arch: arm
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.16, commit: '
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: file
  hostname: DietPi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    uidmap:
      size: 1                                                                                                                                                                 
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
  kernel: 4.19.97-v7l+
  memFree: 3272843264
  memTotal: 4148224000
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 22h 44m 39.14s (Approximately 0.92 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/yurinnick/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/yurinnick/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /tmp/run-1001/containers
  volumePath: /home/yurinnick/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown 1.9.2~3 amd64
podman/unknown 1.9.2~3 arm64
podman/unknown,now 1.9.2~3 armhf [installed]
podman/unknown 1.9.2~3 ppc64el
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Linux ditro: DietPi 6.30.0
- Debian version: 10.4
- Arch: armv7l

**Comment by afbjorklund** [comment]
We have this in minikube as well, our workaround is to install it explicitly:

```
hack/images/kicbase.Dockerfile:    # libglib2.0-0 is required for conmon, which is required for podman
hack/images/kicbase.Dockerfile:    libglib2.0-0 \
```

Unfortunately it was never reported upstream, at the time. (cc @priyawadhwa)

https://github.com/kubernetes/minikube/commit/abf35cfbc15b52b1d5149f66d9224a6fa7d742a3

Thanks for doing it.

Same with Ubuntu.

**Comment by vrothberg** [comment]
Thanks for the report!

@lsm5 PTAL

**Comment by afbjorklund** [comment]
The rpm package doesn't have a dependency either, but is saved by the RPM autodeps:

`libglib-2.0.so.0()(64bit)`

But the specfile only lists the build (devel) requirements, and not the runtime requirements...

`#Requires: glib2`
`BuildRequires: glib2-devel`

**Comment by lsm5** [comment]
> The rpm package doesn't have a dependency either, but is saved by the RPM autodeps:
> 
> `libglib-2.0.so.0()(64bit)`
> 
> But the specfile only lists the build (devel) requirements, and not the runtime requirements...
> 
> `#Requires: glib2`
> `BuildRequires: glib2-devel`

ack, thanks. I'll take care of that too.

**Comment by lsm5** [comment]
just pushed podman 1.9.3 to centos and debian on OBS along with the dependency fix in conmon, should be available in a bit..

**Comment by lsm5** [comment]
Closing.. Please reopen if the issue persists after upgrading to podman 1.9.3 + conmon 2.0.16~2

**Comment by yurinnick** [comment]
Thanks for the fast response! You're awesome!
