### ISSUE TITLE
confusing debug message about lipod.conf

### ISSUE THREAD

**Issue by FlorianLudwig** [containers/libpod#6378]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

```
# podman  --log-level=debug 
DEBU[0000] Ignoring lipod.conf EventsLogger setting "journald". Use containers.conf if you want to change this setting and remove libpod.conf files. 
```

I cannot find any `lipod.conf` nor `libpod.conf` on my system. It is not obvious which configs podman is making use of.

**Describe the results you received:**

**Describe the results you expected:**

Show full path of all loaded configs when running with `--log-level=debug`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:            1.9.2
RemoteAPI Version:  1
Go Version:         go1.13.10
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
We'd be looking at:
- `/etc/containers/libpod.conf`
- `/usr/share/containers/libpod.conf`

Can you confirm neither of these exists? If so, this definitely sounds like a bug...

**Comment by FlorianLudwig** [comment]
@mheon `/usr/share/containers/libpod.conf` does exist. Sorry, I just checked in `~` and `/etc`.

While `lipod.conf` still does have a typo it would be great to not fix the typo bug instead having the absolute path in the log would be quite helpful.

**Comment by mheon** [comment]
I didn't even notice the typo when you originally posted - oops. I agree that printing full paths would be nice here, definitely.

**Comment by boaz0** [comment]
@mheon can you assign it to me please :pray: 
thanks

**Comment by rhatdan** [comment]
@boaz0 I already opened it in containers/common.

https://github.com/containers/common/pull/164

**Comment by mheon** [comment]
Closing as c/common PR landed
