### ISSUE TITLE
Unable to install podman because of broken dependency

### ISSUE THREAD

**Issue by cranebytes** [containers/libpod#6386]
It is currently not possible to install podman on CentOS 8 because of broken dependencies.

Of you try to install podman you will end up with

```
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides conmon >= 2:2.0.16-3 needed by podman-1.9.3-2.1.el8.x86_64
```

However in the repository itself is only `2:2.0.16-1.1.el8` of `conmon` available.

I did not check other CentOS versions for this problem. Might be also affacted.

**Comment by vrothberg** [comment]
@lsm5 PTAL. @cranebytes used the Kubic stable repo.

**Comment by lsm5** [comment]
This was caused due to `Release: <CI_CNT>.<B_CNT>` in the OBS project config. I'll check on how best to fix this..

**Comment by lsm5** [comment]
> This was caused due to `Release: <CI_CNT>.<B_CNT>` in the OBS project config. I'll check on how best to fix this..

Alright, so I changed ^ to `Release: <SPEC_REL>` as per OBS' advice, which will create rpms with the exact release tag as specified in the spec file. That should hopefully fix this issue.

@cranebytes please try installing in a few minutes, you should see `conmon-2.0.16-3` on the OBS repo.

**Comment by lsm5** [comment]
Closing. Please reopen if the issue persists.
