### ISSUE TITLE
DOC: RHEL7 SELinux denies creation of unix socket in rootless container to /tmp

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/libpod#6414]
Moved from https://github.com/containers/podman.io/issues/243 by @skorhone

Audit reports following selinux error, when java is trying to create unix socket to /tmp.

type=AVC msg=audit(1590489952.995:140737): avc:  denied  { create } for  pid=23087 comm=417474616368204C697374656E6572 name=".java_pid63.tmp" scontext=system_u:                                                                               system_r:container_t:s0:c522,c777 tcontext=system_u:object_r:fusefs_t:s0 tclass=sock_file permissive=

Podman has been configured to use fuse-overlayfs. User has custom runroot and graphroot, which have following selinux types:

graphroot: drwxr-xr-x. someuser someuser unconfined_u:object_r:data_home_t:s0 lib
runroot: drwxrwxrwt. someuser someuser unconfined_u:object_r:user_tmp_t:s0 run

podman: version 1.6.4
container-selinux: version 2.119.1
fusermount3 version: 3.6.1
fuse-overlayfs: version 0.7.2
FUSE library version 3.6.1
using FUSE kernel interface version 7.29

Python script for testing socket creation inside container:

import socket; socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).bind("/tmp/test.sock")

Binding a local filesystem to /tmp fixes issue. This solution however leaves us responsible for clearing contents of container specific temporary directory after container has been wiped out.

Also removing selinux label from process using --security-opt label=disable or running container using --privileged works as well.

I think that overall documentation on recommended SELinux attributes for various locations could be improved.

**Comment by rhatdan** [comment]
You should not be creating the stream socket on fuse-overlay.  Can you move this to a tmpfs?

**Comment by rhatdan** [comment]
This should be against container-selinux

**Comment by rhatdan** [comment]
Fixed in container-selinux v2.134.0

**Comment by skorhone** [comment]
Definition for runroot in config is a bit vague. Considering I wasn't sure what gets stored to given location, I felt safer by using device that is less likely to run out of space

**Comment by rhatdan** [comment]
Could you open a PR to clean up the documentation?
