### ISSUE TITLE
Invalid default tmp_dir for rootless podman

### ISSUE THREAD

**Issue by gdm85** [containers/libpod#6425]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On a fresh podman install (non-root user) the `tmp_dir` value in `libpod.conf` does not match the runroot prefix in `storage.conf`

**Steps to reproduce the issue:**

1. run `podman info`

**Describe the results you received:**

```
Error: could not get runtime: cannot mkdir /home/ubuntu/rundir/libpod: mkdir /home/ubuntu/rundir/libpod: no such file or directory
```

**Describe the results you expected:**

No failure.

**Additional information you deem important (e.g. issue happens only occasionally):**

Editing `.config/containers/libpod.conf` manually seems to work:
```
tmp_dir = "/tmp/run-1000/libpod/tmp"
```

The default there of `/home/ubuntu/rundir/libpod/tmp` I deem is incorrect.

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 122695424
  MemTotal: 4181792768
  OCIRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 7959199744
  SwapTotal: 7999582208
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: argo
  kernel: 4.15.0-101-generic
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: 'slirp4netns: /usr/bin/slirp4netns'
    Version: |-
      slirp4netns version 0.4.2
      commit: unknown
  uptime: 3h 24m 57.13s (Approximately 0.18 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/ubuntu/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/ubuntu/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 15
  RunRoot: /tmp/run-1000
  VolumePath: /home/ubuntu/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Package: podman                          
Version: 1.6.2-1~ubuntu18.04~ppa1
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: devel
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Architecture: amd64
Uncompressed Size: 37.5 M
Depends: libseccomp2, libdevmapper1.02.1, libgpgme11, libvarlink, conmon (>= 1.0.0), containers-common (>= 0.1.36), cri-o-runc
Recommends: slirp4netns, containernetworking-plugins (>= 0.8.1), uidmap
Conflicts: podman:i386
Description: Manage pods, containers and container images.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Nothing else, it's pretty much a fresh Ubuntu 18 install.

**Comment by mheon** [comment]
Podman 1.6.x is getting very long in the tooth - you may want to consider upgrading. It looks like you're still on the Ubuntu PPA - we've transitioned to publishing via OBS. Instructions for adding the repo can be found at https://podman.io/getting-started/installation (Ubuntu subsection)

**Comment by polongibro** [comment]
Cat /etc/passwd for the user that is running podman and find out the uid.

Compare that uid number against the /tmp/ file that will have files starting with "run -####.

   example: ls -lah /tmp/
  result: run-1000    run-1001   run-1000

Those four numbers should match the uid of the user running podman, if they do not that is the problem. 

You will also see the ownership of each of the run files in tmp. If your uid that matches the file isn't owned by the you, that needs to be changed.

I replicated this issue when you copy the lippod.conf file from another instance. Podman randomly generates the run-#### and if it generates the same number that you bring over from another instance, it bunks.

#PDCSS team

**Comment by gdm85** [comment]
@polongibro it's not that; I provided instructions to replicate this issue from scratch, the configuration files are generated by podman itself and with the manual change I wrote there the issue is then fixed. It has nothing to do with the UID.

@mheon thanks; with `v1.9.3` I notice that the auto-generated config files are gone and specifically this issue is also gone. I guess someone could ask them to remove this PPA? https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Comment by polongibro** [comment]
@gdm85 I see how you replicated the issue for your specific problem, however, when podman generates the libpod.conf file for each user and the "tmp_dir = "/tmp/run-1000/libpod/tmp" stanza is generated, those numbers (in this case the run-1000) in the libpod.conf stanza is based on the UID of the user. Each podman libpod.conf file will match each users UID.

You can confirm this by comparing the cat /etc/passwd UID's with the Libpod.conf file. Your UID will match the stanza. You can also confirm this by going to the /tmp/ folder and you will see that your  user will own the podman run-1000 folder, which coincidentally will be call the exact same UID and Libpod.conf stanza.

**Comment by gdm85** [comment]
@polongibro if you read carefully the issue I submitted you will see that the user already has an UID of 1000. The issue you are describing has nothing to do with the one I submitted.
