### ISSUE TITLE
in podman-docker, drop the -u option

### ISSUE THREAD

**Issue by themr0c** [containers/libpod#6431]
The `-u` option to set the user is not supported in `podman`.
As this option is mainly used with docker to workaround the non-rootless behaviour of docker, it would be nice to drop this option as irrelevant instead of failing. (Maybe issue a warning).

It would fix issues like: https://github.com/pre-commit/pre-commit/issues/1243

**Comment by mheon** [comment]
We can't drop `-u` - the specific workaround you mention may be broken, but it's a very important flag (setting user in the container has many uses) and other than the case you mention (which seems more of a difference in how we handle Rootless versus how Docker does) we provide complete support for the flag.

**Comment by rhatdan** [comment]
Right podman run -u testuser ...  Works fine.  If you find this does not work then reopen the issue.
Rootless & Rootful podman supports running with multiple users, both by default run with root of the user namespace they are launched in.  If you want to run with a different user within the container then you use -u to select the user.  

When running in rootless mode, the `root` of the container is more powerful then then non-root of the container, so it is still advisable to run as Non-Root in a rootless container.

**Comment by themr0c** [comment]
I am probably missing some configuration, then. I will invertigate further. When using -u I get this error:
```
podman run -u 105971 antora/antora -v
Error: cannot setuid: Invalid argument: OCI runtime error
``

**Comment by mheon** [comment]
That UID is likely too high, if you're running rootless. By default, new users are assigned a 65536-length block of UIDs and GIDs that we use for rootless containers (the mappings are contained in `/etc/subuid` and `/etc/subgid`). Unless you've explicitly adjusted that number up, rootless containers will be able to use UIDs and GIDs up to and including 65536 (65536 from subuid/subgid plus one, the user that originally launched the container).

**Comment by rhatdan** [comment]
We should add a check for this on rootless containers.  Seems like an easy check on the CLI.  Then you could say something like.  You user can only launch contianers with UIDs < XYZ.

**Comment by mheon** [comment]
I don't think we can do it at create time (we need to make & mount the container to translate the UID) but we can definitely do it when we go to start the container, which should be enough for `podman run`
