### ISSUE TITLE
Rootless mariadb with persistent storage via bindmount: permissioned denied

### ISSUE THREAD

**Issue by mjlbach** [containers/libpod#6433]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm having trouble getting a mariadb instance running with rootless podman.

When I run this, I get the following issue:

```
chown: cannot read directory '/var/lib/mysql/data': Permission denied
```

**Steps to reproduce the issue:**

1. Make a directory to hold the database 
```
mkdir $HOME/mysql-data
sudo chown -R mysql:mysql mysql-data
```
2. Start the database
```
podman run --security-opt label=disable --rm  -v $HOME/mysql-data:/var/lib/mysql/data:z -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 mariadb/server
```

**Describe the results you received:**
```
chown: cannot read directory '/var/lib/mysql/data': Permission denied
```

**Describe the results you expected:**

Mariadb container starts with correct permissions. Note
```
sudo chown 100998:100997 mysql-data
```
Fixes the issue

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.9.2
```

**Output of `podman info --debug`:**

```
❯ podman info --debug
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.2
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.16-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.16, commit: 1044176f7dd177c100779d1c63931d6022e419bd'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: desktop-fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.13-300.fc32.x86_64
  memFree: 864075776
  memTotal: 16585113600
  ociRuntime:
    name: runc
    package: containerd.io-1.2.13-3.1.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 8235511808
  swapTotal: 8380215296
  uptime: 140h 13m 49.62s (Approximately 5.83 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/michael/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/michael/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /tmp/1000
  volumePath: /home/michael/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.2-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by rhatdan** [comment]
podman run --security-opt label=disable --rm  -v $HOME/mysql-data:/var/lib/mysql/data:z -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -p 3306:3306 mariadb/server

No reason to disable SELinux here. And you figured out the solution.  Anything in your homedir is owned by "root" in your container.  So if you want the database to be owned by the mariadb user, then you need to chown it to match the correct user.

**Comment by mjlbach** [comment]
Ah, I think I was just confused about the mapping of the uid of the "root" container user to host, I expected it to match the mysql id outside of the container but I'm realizing that was a flawed assumption. I can close

**Comment by rhatdan** [comment]
You inspired me to write my third blog today.  If you want to preview it, please send email to dwalsh@redhat.com
I think I cover what you did to figure this out.  BTW Good detective work by you, other then disabling SELinux. :^)
