### ISSUE TITLE
how to set podman container cgroup parent directory?

### ISSUE THREAD

**Issue by coldbloodx** [containers/libpod#6434]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1.  create cgroup in "/sys/fs/cgroup/cpu/test111/ccc ":
[leo@centos8 ccc]$ pwd
/sys/fs/cgroup/cpu/test111/ccc
[leo@centos8 ccc]$ ll
total 0
-rw-r--r-- 1 leo leo 0 May 29 14:50 cgroup.clone_children
-rw-r--r-- 1 leo leo 0 May 29 14:50 cgroup.procs
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.stat
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_all
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu_sys
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu_user
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_sys
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_user
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.cfs_period_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.cfs_quota_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.rt_period_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.rt_runtime_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.shares
-r--r--r-- 1 leo leo 0 May 29 14:50 cpu.stat
-rw-r--r-- 1 leo leo 0 May 29 14:50 notify_on_release
-rw-r--r-- 1 leo leo 0 May 29 14:50 tasks

2. start a container with --cgroup-parent=<path/to/cgroupdir>:
[leo@centos8 ~]$ podman run  --cgroup-parent=/sys/fs/cgroup/cpu/test111/ccc -v /etc/group:/etc/group -v /etc/passwd:/etc/passwd --userns=keep-id -it -w `pwd` -v `pwd`:`pwd` -v /tmp:/tmp --rm centos /bin/bash
[leo@49cc2d558f95 ~]$ id
uid=1000(leo) gid=1000(leo) groups=1000(leo)
[leo@49cc2d558f95 ~]$ ls -l /sys/fs/cgroup/cpu/test111/ccc

3. check cgroup-parent:
[leo@centos8 ccc]$ pwd
/sys/fs/cgroup/cpu/test111/ccc
[leo@centos8 ccc]$ ll
total 0
-rw-r--r-- 1 leo leo 0 May 29 14:50 cgroup.clone_children
-rw-r--r-- 1 leo leo 0 May 29 14:50 cgroup.procs
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.stat
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_all
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu_sys
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_percpu_user
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_sys
-r--r--r-- 1 leo leo 0 May 29 14:50 cpuacct.usage_user
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.cfs_period_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.cfs_quota_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.rt_period_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.rt_runtime_us
-rw-r--r-- 1 leo leo 0 May 29 14:50 cpu.shares
-r--r--r-- 1 leo leo 0 May 29 14:50 cpu.stat
-rw-r--r-- 1 leo leo 0 May 29 14:50 notify_on_release
-rw-r--r-- 1 leo leo 0 May 29 14:50 tasks
[leo@centos8 ccc]$ cat cgroup.procs
[leo@centos8 ccc]$ docker ps
CONTAINER ID  IMAGE                            COMMAND    CREATED        STATUS            PORTS  NAMES
49cc2d558f95  docker.io/library/centos:latest  /bin/bash  4 minutes ago  Up 4 minutes ago         inspiring_hermann

nothing is created in the cgroup-parent directory.

In docker itself, a directory named <container_id> should be created in cgroup-parent directory.

seems podman --cgroup-parent does not work.

or I did not use the parameter correctly ?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
[leo@centos8 ~]$ rpm -qa |grep podman
podman-docker-1.6.4-4.module_el8.1.0+298+41f9343a.noarch
podman-manpages-1.6.4-4.module_el8.1.0+298+41f9343a.noarch
podman-1.6.4-4.module_el8.1.0+298+41f9343a.x86_64

[leo@centos8 ~]$ podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64

```
(paste your output here)
```

**Output of `podman info --debug`:**
[leo@centos8 ~]$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 2721f230f94894671f141762bd0d1af2fb263239'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 7173423104
  MemTotal: 8254902272
  OCIRuntime:
    name: runc
    package: runc-1.0.0-64.rc9.module_el8.1.0+298+41f9343a.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  eventlogger: file
  hostname: centos8.1
  kernel: 4.18.0-147.8.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-3.git21fdece.module_el8.1.0+298+41f9343a.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 1h 57m 58.12s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/leo/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module_el8.1.0+298+41f9343a.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/leo/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/leo/.local/share/containers/storage/volumes

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
First: this is not expected to work. Podman does not use cgroups on cgroups v1 systems in rootless mode (there are security issues with cgroups v1 that make them unsafe for use without root access - v2, as used in Fedora 31/32, resolve these issues). We will not create cgroups as rootless on a cgroups v1 system, as your `podman info` output indicates your host is. It might be a good idea for us to disable the `--cgroup-parent` flag in this case, but for now it is a no-op.

If you do decide to do this as root: don't specify the full directory - specify the portion after `/sys/fs/cgroup` (so `-cgroup-parent=/test111/ccc`). Also, make sure you are using the `cgroupfs` cgroup manager, not `systemd` - the `systemd` driver expects to be given a slice to run under.

Also, be aware that you only created a cgroup for a single subsystem there (CPU). Podman uses a lot more controllers than just that, so it will create that cgroup for all of the other controllers where it may be missing (e.g. memory)

**Comment by coldbloodx** [comment]
@mheon
Got it, thank you for your answer :)

**Comment by mheon** [comment]
I think this is answered, so closing, feel free to reopen if there are further questions
