### ISSUE TITLE
podman cli does not match docker cli when no sub command is provided

### ISSUE THREAD

**Issue by tradetechpeter** [containers/libpod#6436]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. On CentOS 7 run `sudo podman`

2. Install the latest docker cli from the docker repos https://docs.docker.com/engine/install/centos/

3. On the same CentOS 7 machine run `sudo docker`

**Describe the results you received:**
$ sudo podman
Error: missing command 'podman COMMAND'
Try 'podman --help' for more information.
$ echo $?
125

$ sudo docker
Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/root/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/root/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/root/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/root/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  engine      Manage the docker engine
  image       Manage images
...
$ echo $?
0

**Describe the results you expected:**
Both commands should have similar output and they should both return zero on the command line

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-2.el7.centos.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 1708429312
  MemTotal: 3936452608
  OCIRuntime:
    package: containerd.io-1.2.13-3.2.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  SwapFree: 4294963200
  SwapTotal: 4294963200
  arch: amd64
  cpus: 2
  hostname: gla1vm201
  kernel: 3.10.0-957.27.2.el7.x86_64
  os: linux
  rootless: false
  uptime: 3h 6m 22.88s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-2.el7.centos.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual Machine

**Comment by rhatdan** [comment]
I disagree.  I don't want podman --help to pop up on every execution of a command.  Most commands work like podman 
```
$ ls --foobar
ls: unrecognized option '--foobar'
Try 'ls --help' for more information.
$ cut
cut: you must specify a list of bytes, characters, or fields
Try 'cut --help' for more information.
$ echo $?
1
$ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
$ echo $?
2
```
We do not match Docker when it is a what we consider a bug.
If you type into the screen, 
```
$ docker --foobar 2>&1 | wc -l
84
``` 
Docker dumps 84 lines worth of text and the actual error message scrolls off of the terminal. Most of this useless information that you probably already know. Now you have to scroll up to attempt to figure out what the mistake was. If you don't know how to use the command line, then you would issue  a docker --help.  

As opposed to
```
$ podman --foobar
Error: unknown flag: --foobar
```
