### ISSUE TITLE
rawhide: podman build is completely broken

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#6451]
koji is completely [broken on all arches](https://koji.fedoraproject.org/koji/buildinfo?buildID=1518699) on rawhide:
```
# Only generate the varlink code on Linux (see issue #4814).
GO111MODULE=off go generate ./pkg/varlink/...
../../vendor/github.com/varlink/go/cmd/varlink-go-interface-generator/main.go:12:2: cannot find package "github.com/varlink/go/varlink/idl" in any of:
	/usr/lib/golang/src/github.com/varlink/go/varlink/idl (from $GOROOT)
	/builddir/build/BUILD/libpod-22713d62e2860052e21e5e985fba169834709fdc/_output/src/github.com/varlink/go/varlink/idl (from $GOPATH)
pkg/varlink/generate.go:3: running "go": exit status 1
make: *** [Makefile:675: pkg/varlink/iopodman.go] Error 1
```
I'm guessing it has to be #6353 but it'll take me too long to figure out the full root cause. I bet something needs to be tweaked in the fedpkg specfile (master).

**Comment by baude** [comment]
@edsantiago the GOPATH isnt being set.

**Comment by edsantiago** [comment]
I've [removed varlink from the rawhide specfile](https://src.fedoraproject.org/rpms/podman/c/5907c5c652e1af6920ab16c42d0b6109f92c38ad?branch=master). Keeping fingers crossed.

**Comment by edsantiago** [comment]
Took two tries — my mistake, I had forgotten how to run `fedpkg local` to test — but Koji builds [are now fixed](https://koji.fedoraproject.org/koji/buildinfo?buildID=1518999).
