### ISSUE TITLE
`images --no-trunc` misformated image ID

### ISSUE THREAD

**Issue by marusak** [containers/libpod#6459]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
The `image ID` when using `--no-trunc` is misformated.

**Steps to reproduce the issue:**
1. 
```
 $ podman images --no-trunc
REPOSITORY                 TAG     IMAGE ID                                                                        CREATED       SIZE
docker.io/cockpit/tasks    latest  sha256:sha256:33060c8546e0b764a19ab8bdc5a08433a5ffa2211fc505ae986f5e6838f4748d  2 weeks ago   2.16 GB
```

**Describe the results you expected:**
Feels like one `sha256:` would be enough :)

Using my own build of podman from current master (d6bf6b92c).

**Comment by vrothberg** [comment]
Thanks for the report! I opened https://github.com/containers/libpod/pull/6460 to fix it.
