### ISSUE TITLE
APIv2 documentation is not working

### ISSUE THREAD

**Issue by marusak** [containers/libpod#6466]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
https://podman.readthedocs.io/en/latest/_static/api.html does not work. I saw this week or two weeks ago for the first time so not sure if still down or again.

![wentwrong](https://user-images.githubusercontent.com/12330670/83513962-0492b680-a4d3-11ea-9dd2-e01f4a6fad79.png)

**Comment by TomSweeneyRedHat** [comment]
@marusak How did you get to the page?  i.e. did you use a bookmark or a link from another page?  We're having a CORS issue when coming in from https://podman.readthedocs.io/en/latest and we're trying to chase those links down.  Try instead https://docs.podman.io

**Comment by marusak** [comment]
I just type `redo` into my browser and I get this option as I visited it before.

Interestingly, when I go to `https://docs.podman.io`, click on `Reference` (in "Finally, for Developers looking at how to interact with the Podman API, please see our API documentation Reference.") I see the doc in the small embedded window. When I click 'API documentation' (as in "To see full screen version please visit: API documentation") I get again to the broken page.

**Comment by TomSweeneyRedHat** [comment]
@marusak TYVM for the pointers.  I'll see if I can clean up that 'API documentation' link.

**Comment by baude** [comment]
Also, adding for people who are searching for a solution and end up here.  You can serve yourself the documentation by install go-swagger (https://github.com/go-swagger/go-swagger) and then:

1. cd pkg/api
2. make
3. swagger serve swagger.yaml

**Comment by TomSweeneyRedHat** [comment]
I've poked at this a bit.  As @marusak noted, the "API Documentation" link on this [page](https://docs.podman.io/en/latest/Reference.html) is failing.  We do have an issue when using the older addresses, `podman.readthedocs.io`, but this one as it is using `docs.podman.io` should work.  I suspect there may be an underlying issue with swagger and I'll need to have @cevich take a look.  However I know he's tied up this week with other things, so he may not get to it until next week.

The API doc is visible on the above link at the moment, you just can't go to a full screen with it.
