### ISSUE TITLE
Kubevirt capability in Podman

### ISSUE THREAD

**Issue by havok4u** [containers/libpod#6479]
/kind feature

**Description**

Create the ability to launch traditional VM's (that are VNFs) the way kubevirt does.  We can call this podvirt if you want.  I know Kata is a way to do VM's in podman, but it leverages all the same methods and patterns that enable container work loads (things that terminate).  VNF's forward traffic /packets and are definitely used in any edge platform.  Kubevirt ability in Podman would allow  us to use the same API's to run VNF's as well.  This is not unrealistic, as it is done in openshift today.

**Comment by rhatdan** [comment]
We would need to see a PR to judge this.  Not something the Podman team has time to work on. But if the Kubevirt community wanted to contribute it is something we would consider.

**Comment by havok4u** [comment]
It can be closed, gonna use something else so I can accomplish this.
