### ISSUE TITLE
Podman login returns username after logout indicates no user logged in.

### ISSUE THREAD

**Issue by bbros-dev** [containers/libpod#6499]
/kind bug

**Description**

I'm trying to resolve [troubleshooting issue #13 - Anonymous image pull fails with invalid username password ](https://github.com/containers/libpod/blob/master/troubleshooting.md#13-anonymous-image-pull-fails-with-invalid-usernamepassword)

`podman logout docker.io` returns `Not logged into docker.io`.
Yet `podman login --get-login docker.io` returns a username

According to [latest help documentation](http://docs.podman.io/en/latest/markdown/podman-login.1.html) this data can only come from:

```bash
$ cat ${XDG_RUNTIME_DIR}/containers/auth.json 
{
        "auths": {}
}
```

**Steps to reproduce the issue:**

1. Run
    ```
    podman logout docker.io
    podman login --get-login docker.io
    ```

**Describe the results you received:**

A user name.

**Describe the results you expected:**

No logged in user name.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.10.1
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.10.1
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.16, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: desktop.local.lan
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.3.0-40-generic
  memFree: 318054400
  memTotal: 16652148736
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: unknown
  swapFree: 3700944896
  swapTotal: 4156551168
  uptime: 37h 3m 8.25s (Approximately 1.54 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/<redacted>/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/<redacted>/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/<redacted>/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 1.9.3~1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical. Ubuntu 18.04.

**Comment by QiWang19** [comment]
`podman login --get-login docker.io` may return username from .docker/config.json, should fix the logout error message as something like not logged in podman, please logout using docker.

**Comment by bbros-dev** [comment]
Also need to update the help documentation (linked to in OP) to cite the docker config location as a data source for Podman.
