### ISSUE TITLE
[apiv2] fails with 'schema: error converting value for \"follow\"'

### ISSUE THREAD

**Issue by jgallucci32** [containers/libpod#6525]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
Podman API returns an error when using the `follow=1` parameter (or another parameter) parameter before the `stderr` or `stdout` streams when retrieving logs on a running container.

**Steps to reproduce the issue:**
1. Run a container
```
podman run -d --name hello-world hello-world
```

2. Use cURL to retreiving logs with the `follow=1` parameter on the running container
```
curl --unix-socket /run/podman/podman.sock http://docker/v1.24/containers/hello-world/logs?follow=1%26stderr=1
```

**Describe the results you received:**
Results in the following error
```
{
  "cause": "schema: error converting value for \"follow\"",
  "message": "Failed to parse parameters for /v1.24/containers/hello-world/logs?follow=1%26stderr=1: schema: error converting value for \"follow\"",
  "response": 400
}
```

**Describe the results you expected:**
HTTP/200 OK

**Additional information you deem important (e.g. issue happens only occasionally):**
It appears to also break when both `stderr` and `stdout` are specified at same time. Perhaps it is having issues parsing multiple arguments.

**Output of `podman version`:**

```
Version:      2.0.0-dev
API Version:  1
Go Version:   go1.14.3
Git Commit:   d857275901e8c1ea7515360631e5894018e17f30
Built:        Fri Jun  5 17:00:00 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-0.6.dev.git50aeae4.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18-dev, commit: 51e91bbc42aaf0676bb4023fb86f00460bf7a0a2'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: gallucci-fedora.devlnk.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.0-1.fc33.x86_64
  linkmode: dynamic
  memFree: 15239405568
  memTotal: 16783962112
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 19h 56m 58.63s (Approximately 0.79 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 4
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1591401600
  BuiltTime: Fri Jun  5 17:00:00 2020
  GitCommit: d857275901e8c1ea7515360631e5894018e17f30
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-0.121.dev.git1fcb678.fc33.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 33 (Rawhide Prerelease)

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by jgallucci32** [comment]
@mheon @jwhonce I just confirmed the issue is not exactly how I described it. There is a problem, just different. What I realized is the API does not like the %26 encoding. Even the Docker API has the same issue. To get past the first error I had to use ampersands(&) with single quotes (') as follows
```
curl --unix-socket /run/podman/podman.sock 'http://docker/v1.24/containers/hello-world/logs?follow=1&stderr=1'
```
The REAL problem is this command never returns the expected `HTTP/1.1 200 OK` as it does with the Docker API. The Podman API seems to hang indefinitely.

Please let me know if you want me to file a new issue or modify this one to reflect the real issue.

**Comment by jgallucci32** [comment]
@mheon @baude This appears to be a regression of Issue https://github.com/containers/libpod/issues/435 and related pull request https://github.com/containers/libpod/pull/437 addressed 2 years ago. I'll file a new ticket.

**Comment by jgallucci32** [comment]
/Close

I am going to re-open this issue to better describe the issue. The true issue is following a log with the API hangs indefinitely just like it currently does with the CLI but fixed recently.
