### ISSUE TITLE
podman: maybe support a `RUN` label like atomic CLI

### ISSUE THREAD

**Issue by dustymabe** [containers/libpod#653]
With podman we have more flexibility over the interface our users have. I think we should be very careful when stepping away from the known interface users are familiar with today, but in some cases it could make sense to accept targeted enhancements. 

One possible example is the run label command execution like is done by the Atomic CLI today. An example is:

```
LABEL run podman run -d --network=container:wordpress -v ~/workspace/logs:/var/log/mariadb:z -v ~/workspace/mysql:/var/lib/mysql:z -v ~/workspace/run:/run/mariadb:z -e DBUSER=user -e DBPASS=mypassword -e DBNAME=mydb --name mariadb mariadb
```

so `podman runl containername` could run the run label from the image.. This is just an idea and it's probably not the most well thought out, but just thought I'd drop it here.

**Comment by rhatdan** [comment]
This would be sort of merging atomic functionality into podman,  Interesting.  
One thing we need to move forward on is integrating podman better into the atomic CLI, to make it a first class citizen.  @baude has begun playing with varlink to make it a PODMAN API.  This would allow us to better integrate into atomic.

I was also thinking of changing atomic to realize if a container came with a LABEL RUN command of
docker run ...

The tool would be smart enough to run `podman run` if the docker client was not available and podman was.

**Comment by giuseppe** [comment]
in addition to that: should we teach atomic and the container images to not hardcode `/usr/bin/docker` in the labels but have something like `\${RUNTIME}` and atomic will set the correct value?
For a few releases we could add a warning when we find an hardcoded `/usr/bin/docker` label so that container images have time to be updated.

**Comment by rhatdan** [comment]
@baude We talked about this the other day.

**Comment by rhatdan** [comment]
I was thinking one of the first things we should add is 
podman help image or
podman container help CID
podman image help Image

**Comment by baude** [comment]
Id like this one still.

**Comment by mrguitar** [comment]
I think we mostly use the run, install, and help labels. Those are the ones I'd be interested in seeing.

**Comment by rhatdan** [comment]
I would add uninstall as well.

Looking at the atomic man page, this is what we see.
```
       atomic-diff(1) show the differences between two images|containers' RPMs
podman diff
       atomic-host(1) execute commands to manage an Atomic host.
rpm-ostree Provides this.
       atomic-images(1) operations on container images
podman images
       atomic-install(1) execute commands on installed images
*****podman install Is needed ****
       atomic-mount(1) mount image or container to filesystem
podman mount
       atomic-pull(1) pull latest image from repository
podman pull
       atomic-push(1) push container image to a repository
podman push
       atomic-run(1) execute image run method (default)
*** podman runp **** or some other name
       atomic-scan(1) scan an image or container for CVEs
*** NO EQUIVALENT And not sure this is a podman thing. ***
       atomic-sign(1) sign an image
This might be an interesting thing to add
       atomic-stop(1) execute container image stop method
podman stop
       atomic-storage(1) manage the container storage on the system
*** NO EQUIVALENT And this is a podman thing. ***
       atomic-top(1) display a top-like list of container processes
podman top
       atomic-trust(1) manage system container trust policy
This might be an interesting thing to add
       atomic-uninstall(1) uninstall container from system
*****podman uninstall Is needed ****
       atomic-unmount(1) unmount previously mounted image or container
podman umount
       atomic-update(1) Downloads the latest container image.
This might be an interesting thing to add
```

**Comment by mrguitar** [comment]
Great catch I forgot about that one

**Comment by rhatdan** [comment]
@baude @umohnani8 Could you guys work to get cards created for each one of these features.

**Comment by baude** [comment]
Yeah I can do them ...

**Comment by baude** [comment]
this is already assigned to me

**Comment by dustymabe** [comment]
I don't know if `podman install` and `podman uninstall` really make sense. I feel like that starts to overlap with system containers a bit much and feature creep is not good from a "clarity" perspective. I honestly hesitated about `podman runl` itself.

maybe an option would be something completely generic:

- `podman runl --label=LABEL IMAGE` would run container based on `IMAGE` using the text defined in `LABEL` label
- `podman runl IMAGE` would run container based on `IMAGE` using the text defined in `RUN` label (this is the only "convenience" assumption we will make

For example `podman runl --label=install IMAGE` would  run the image with the directions defined in the `INSTALL` label within the image. `podman runl --label=foo IMAGE` would  run the image with the directions defined in the `FOO` label within the image.

If we add too much "magic" it will get confusing quick.

**Comment by giuseppe** [comment]
Do we want/need to support existing images that already have these labels defined?

If we are reinventing it, I'd like to weight in: I don't particularly like the `INSTALL/UNINSTALL` labels, each single image needs to reinvent its "package manager" for copying data to the host.

With system containers we had the "create rpm" feature, but that is over designed IMO, but on a middle ground we could have the `--system-package=no` equivalent, where the tool copies the files to the host and has some basic templating for configuring them.

I am working on a simpler implementation of the system containers in Go, so they look more like the rest of our tools.  If people agree, we could re-use the "copy to host" feature for Podman.

**Comment by rhatdan** [comment]
I am willing to redesign, as long as we come up with something fairly simple for users to understand and use.

**Comment by giuseppe** [comment]
I've pushed my WIP here: https://github.com/giuseppe/os-containers  It is not really polished code, I need to do more work on it (so expect some `git push -f`)

**Comment by rhatdan** [comment]
I would want those commands/features in podman.  I don't want a new tool for this.  We need to focus everyone on a single tool.  But that looks like a good start.

**Comment by giuseppe** [comment]
some of the features, like copying files to the host, make sense for a Podman container as well.  I think it is a cleaner `INSTALL/UNINSTALL` replacement, and refactor it out so both tools can use it.

But some other features, like OSTree storage, don't really fit in the Podman CLI.  The OSTree storage doesn't use `containers/storage` at all and it is a completely different set of containers.  The advantages of the OSTree storage for containers, beside data deduplication, are: 1) no need for overlayfs 2) Support a different SELinux labels per each file, not just `container_share_t`.  The second in particular is important for lower level containers.

Or is there a clean way to integrate the two use cases?

**Comment by baude** [comment]
This is implemented. Closing
