### ISSUE TITLE
Missing a comprehensive guide to the new API

### ISSUE THREAD

**Issue by TomasTomecek** [containers/libpod#6535]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I wanted to check out the new API and play with it a bit but I am actually missing a guide (or a blog post) how to even reach the API.

[This documentation](http://docs.podman.io/en/latest/_static/api.html) is fantastic, but it's missing the step 0 - where is the HTTP api being served and how to reach it.

**Comment by jgallucci32** [comment]
@TomasTomecek The new Podman API (APIv2) is based off the Docker API referenced here: https://docs.docker.com/engine/api/

In my own personal testing the API has its limitations, but it is actively under development and supports many of the same calls you would expect in Docker. As far as I can tell it only works with sockets, but I imagine HTTP will be implemented down the road.

The use of the experimental service is explained in the help command `podman system service --help`
```
Run API service

Description:
  Run an API service

Enable a listening service for API access to Podman commands.


Usage:
  podman system service [flags] [URI]

Examples:
  podman system service --time=0 unix:///tmp/podman.sock

Flags:
  -t, --time int   Time until the service session expires in seconds.  Use 0 to disable the timeout (default 5)
```

To start the service run something like this to keep it running for a long period of time
```
podman system service -t 5000 &
```
You can use cURL on the socket with the same request you would for the Docker API
```
curl --unix-socket /run/podman/podman.sock http://docker/v1.24/info
```

NOTE: If you install the package `podman-docker` it will create a symbolic link for `/var/run/docker.sock` which links to `/run/podman/podman.sock`

**Comment by TomasTomecek** [comment]
@jgallucci32 thank you, this is exactly the info I was expecting to read [here](http://docs.podman.io/en/latest/_static/api.html).
