### ISSUE TITLE
podman-remote: build --file SUBPATH: exit 0, but NOP

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#6577]
Usual setup for podman system server
```console
$ mkdir a
$ echo 'FROM docker.io/library/alpine:latest' >a/Containerfile
$ ./bin/podman-remote --url $MYSOCK build --layers=true -t test --file a/Containerfile a
```
This exits immediately, with exit status 0, having performed nothing. On server debug log:
```
DEBU[0449] APIHandler -- Method: POST URL: /v1.0.0/libpod/build?dockerfile=a%2FContainerfile&forcerm=1&platform=linux%2Famd64&rm=1&shmsize=67108864&t=test
INFO[0449] Request Failed(Internal Server Error): error reading info about "/dev/shm/libpod_builder405942463/build/a/Containerfile": stat /dev/shm/libpod_builder405942463/build/a/Containerfile: no such file or directory
```
Running without `--file etc` proceeds farther, but with its own weirdness which I will report after this.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago it could well be end of day brain for me, but I'm not able to get your command to run using the latest  upstream.  The `--url` isn't found?  I've not played with the remote side much, so could be a user error here.  Also, what did you set `$MYSOCK` to and what command did you run for the server?
```
# ./bin/podman-remote --url $MYSOCK build --layers=true -t test --file ~/Dockerfile.alpine .
Error: unknown flag: --url
```

**Comment by edsantiago** [comment]
@tomsweeney sorry, I left out important steps because I was filing so many issues that day. "Usual setup" means:
```console
$ export MYSOCK=unix:/tmp/mypodmansock
$ ./bin/podman system service --timeout=0 $MYSOCK
```
That hangs (serving), so you need to set MYSOCK on the other shell.

I'm not seeing the same failure any more though. I will investigate further tomorrow.

**Comment by edsantiago** [comment]
Duh. The key is that podman server can't be in the same pwd as podman client. Yep, problem still exists.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago I still can't get  podman-remote to find a `--url` option.  Is that bit correct?

**Comment by edsantiago** [comment]
@TomSweeneyRedHat my first and only guess is that somehow you've got the build tags wrong and are building varlink instead of v2? But I have no idea how to even test that. `--version` doesn't help. Or maybe you're typing `make podman` instead of `make`? Can you `ls -l bin/podman-remote`? 

What does plain simple `./bin/podman-remote --url` say? For me it says `Error: flag needs an argument: --url`.
