### ISSUE TITLE
installing oci-umount causes podman to fail

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#6629]
With `oci-umount-2:2.5-4.gitc3cda1f.fc32` installed, `podman run` fails:
```console
# podman run alpine date
Error: error setting up OCI Hooks: parsing hook "/usr/share/containers/oci/hooks.d/oci-umount.json": unrecognized hook version: ""
```
This is `podman-2:2.0.0-0.2.rc6.fc32`. It is a regression: `1.9.3-1.fc32` works fine.

**Comment by heatmiser** [comment]
Seeing the same error...
# sudo podman run -i -t -P --name devcntr-$(date +%Y-%m-%d.%H%M) --hostname devcntr-$(date +%Y-%m-%d.%H%M) -v /etc/localtime:/etc/localtime:ro -v ~/cntrutil01:/cntrutil01:Z localhost/fed-cloudcntr:latest /bin/bash
Error: error setting up OCI Hooks: parsing hook "/usr/share/containers/oci/hooks.d/oci-umount.json": unrecognized hook version: "": parsing hook "/usr/share/containers/oci/hooks.d/oci-systemd-hook.json": unrecognized hook version: ""
Fedora 31
# podman -v
podman version 2.0.0-dev
# rpm -q podman
podman-2.0.0-1592321502.git908bc3fb.fc31.x86_64
...from Copr repo for Upstream_CRIO_Family owned by baude
Recently executed package updates, not sure what previous version of podman was, but it worked
