### ISSUE TITLE
v2.0.0-rc6: unable to change to root gid in container

### ISSUE THREAD

**Issue by lsm5** [containers/libpod#6645]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. I enter a container with a non-root user

2. Try to run sudo inside container

**Describe the results you received:**
```
sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin
```

**Describe the results you expected:**
sudo should work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.0-rc6
API Version:  1
Go Version:   go1.14.3
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: nagato.nanadai.me
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.6.18-300.fc32.x86_64
  linkmode: dynamic
  memFree: 4040089600
  memTotal: 16416161792
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8296329216
  swapTotal: 8296329216
  uptime: 24h 53m 54.52s (Approximately 1.00 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 47
    paused: 0
    running: 1
    stopped: 46
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 48
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.0-rc6

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-0.2.rc6.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by lsm5** [comment]
This issue occurs only if I start a container as non-root user and then try to sudo inside the container. 

It won't occur if the container is first started as root, then inside the container I try to first su to a non-root user and then sudo back.

**Comment by lsm5** [comment]
fixed in v2.0.0. Closing ...

**Comment by polongibro** [comment]
Using podman 1.6.4 on Rhel 7.9 and running into this issue of not being able to "sudo su" inside of a container and getting the following results:

sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin


Is there a fix for this I can apply to a previous version? Current environment does not allow for  a version update currently. I've been up and down this container with little success.

**Comment by rhatdan** [comment]
If you run as a privileged container does it work?

**Comment by sifive-benjamin-morse** [comment]
While stuck on podman version `1.6.4` I was able to get this working:

```
sudo podman exec -u 0 -it mycontainer bash
# Then while inside
su centos
# then I can run sudo or normal non-sudo commands just fine
```

This works because I've created a centos user. When you exit the interactive session you end up typing exit twice. This example is a centos host, centos guest
