### ISSUE TITLE
Add container name to hosts entry when using syntax --network container:name 

### ISSUE THREAD

**Issue by skorhone** [containers/libpod#6678]
/kind feature

**Description**
When referencing another container with podman run --network container:name, podman creates a host entry that contains referenced containers ip and id.

This requires user to do an additional step of resolving container id when running ad-hoc commands

podman run -it --network container:sonar_mysql -v ./sonar-dump.gz:/sonar-dump.gz --rm mysql:5.7 mysql -h<would be awesome, if I could use sonar_mysql here>

**Describe the results you received:**
Hosts file has target container ip and id

**Describe the results you expected:**
Hosts file has target container ip, id and name

**Comment by rhatdan** [comment]
The traditional way to handle this is to set the hostname. in the first container.  Then  you can reference it in the second container.  I have a simple patch to do what you want, but I am worried about why this was not done before.  I will open the PR to get comment and see if someone knows why this was not done in the past.
