### ISSUE TITLE
Running rootless container via REST api fails

### ISSUE THREAD

**Issue by daryllstrauss** [containers/libpod#6681]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I create a container using a rootless REST api and then try and run it, it fails with errors trying to create /var/run/netns.

**Steps to reproduce the issue:**

1. podman system service -t 0

2. cat > def.json << __EOM__
{
    "command": ["ls"],
    "image": "fedora:latest",
    "name": "test"
}
__EOM__

3. curl -d @def.json -H "Content-Type: application/json" --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock http://localhost/v1.24/libpod/containers/create

[this seems to work and returns a container id]

4. curl -X POST --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock http://localhost/v1.24/libpod/containers/test/start

**Describe the results you received:**

{"cause":"mkdir /var/run/netns: permission denied","message":"cannot create /var/run/netns: mkdir /var/run/netns: permission denied","response":500}

**Describe the results you expected:**

Container to successfully start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.17-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: bb8e273f5925c1a51737644637ef65d094a67ab1'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: ghost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.15-300.fc32.x86_64
  memFree: 1373212672
  memTotal: 16520306688
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 1788424192
  swapTotal: 8346660864
  uptime: 390h 12m 29.79s (Approximately 16.25 days)
registries:
  172.30.0.0/16:
    Blocked: false
    Insecure: true
    Location: 172.30.0.0/16
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: 172.30.0.0/16
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/daryll/.config/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 16
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/daryll/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 37
  runRoot: /run/user/1000
  volumePath: /home/daryll/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
bare metal

**Comment by daryllstrauss** [comment]
I was missing
    "netns": {
        "nsmode": "host"
    }
From the create command.

**Comment by mheon** [comment]
I think that bit is no longer necessary on 2.0, FYI - if not explicitly set, we will choose a sane default

**Comment by daryllstrauss** [comment]
Thanks.

It took me a while to figure out particularly because it's --network on the
command line and netns in the json, and netns isn't documented in the
swagger at http://docs.podman.io/en/latest/_static/api.html
