### ISSUE TITLE
Source IP should be 127.0.0.1 in rootless Podman 1.4.4 - RHEL 7.7

### ISSUE THREAD

**Issue by flopma** [containers/libpod#6691]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

For a rootless container the source IP of incoming packets on a publish port is always `10.0.2.2`.

**Steps to reproduce the issue:**

1. Start a NGINX container:
`podman run -p 8888:80 docker.io/library/nginx:latest`

2. Make a request from another terminal:
`curl http://localhost:8888`

3. Look at the source ip of the request in NGINX stdout log:
`10.0.2.2 - - [19/Jun/2020:15:29:21 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.29.0" "-"`

**Describe the results you received:**

The logged source address is always 10.0.2.2

**Describe the results you expected:**

The logged source IP address to match the IP of the host the request was coming from. In this case, 127.0.0.1. This is especially important here as I am setting up PosgreSQL and its security with IP based ACL.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.3
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "7.7"
  MemFree: 8009859072
  MemTotal: 16656347136
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 8
  hostname: removed
  kernel: 3.10.0-1062.9.1.el7.x86_64
  os: linux
  rootless: true
  uptime: 646h 18m 3.92s (Approximately 26.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  ConfigFile: edited/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: edited/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 3
  RunRoot: /run/user/6661
  VolumePath: edited/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.el7.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"

Do you have a workaround possible within version 1.4.4 or at least if I need to recompile, to be doable on CentOS 7.7?

Thx a lot for your valuable work

**Comment by flopma** [comment]
I see slirp is ran with this command `/usr/bin/slirp4netns --api-socket /run/user/6661/libpod/tmp/fa9929cebaf1f0a21416d2b386375353576c81882dae79a55cc92d272eac1bd8.net 18920 --disable-host-loopback --mtu 65520 -c -e 3 -r 4 18920 tap0`

Not sure if this helps to understand the context here.

**Comment by mheon** [comment]
Hmmm. This is 1.4.4, so pre-Rootlesskit - and I was under the impression that slirp did preserve source IP?

@giuseppe @AkihiroSuda Any ideas here?

**Comment by AkihiroSuda** [comment]
Expected behavior in v1.4

**Comment by flopma** [comment]
It does keep the source IP if it is not localhost. But for localhost, it transforms it to 10.0.2.2. Is this because of the parameter `--disable-host-loopback` ? If yes, any ways to tell podman to not use the parameter ? If you have pointers to some blogs/docs ? Is only doc the source of slirp4netns ? Thx

**Comment by rhatdan** [comment]
Please update to a newer version of podman,  podman 1.6.4 should be the latest in RHEL7.
