### ISSUE TITLE
Podman needs go >1.13 for building

### ISSUE THREAD

**Issue by rhafer** [containers/libpod#6708]
/kind bug

**Description**

Recent versions of libpod fail to build when using go1.12

**Steps to reproduce the issue:**

1. Install go1.12

2. `make podman`

**Describe the results you received:**

```
# github.com/containers/libpod/pkg/bindings/system
pkg/bindings/system/system.go:69:7: undefined: "github.com/pkg/errors".Is
make: *** [Makefile:188: bin/podman] Error 2
```

**Describe the results you expected:**

Either a successful build. Or a more helpful error message.

**Comment by TomSweeneyRedHat** [comment]
I ran into this very issue this weekend.  @rhafer I'm not sure we can do anything about the error message.  Are there places that you think we should document this need?

**Comment by rhafer** [comment]
> Are there places that you think we should document this need?

Updating the go version in `go.mod` helps. You get a slightly more helpful error then. See #6709

**Comment by TomSweeneyRedHat** [comment]
Thanks @rhafer
