### ISSUE TITLE
container cannot be started because of a permission denied error.

### ISSUE THREAD

**Issue by coldbloodx** [containers/libpod#6740]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.
on rhel 8.1, the system is configured using cgroup v1.

2.
podman started by a python script and the python script is put in to a cgroup.
podman cli:

/usr/bin/docker --log-level debug run --cidfile /tmp/lsf.lsf1010.job.5095.1592973527.task.1.1592973531318033 -v /scratch/lsf_addon/lcui/lsf1010:/scratch/lsf_addon/lcui/lsf1010 -v /home/xianwu:/home/xianwu -w /home/xianwu/ -it -v /home/xianwu/.lsbatch:/home/xianwu/.lsbatch -v /tmp:/tmp --env-file=/tmp/.sbd.env.lsf1010.5095.task.1.1592973531318033 --rm --sig-proxy=false --net=host --ipc=host -v /scratch/lsf_addon/lcui/passwd.podman:/etc/passwd -v /scratch/lsf_addon/lcui/group:/etc/group --userns=keep-id   --name lsf1010.job.5095.task.1 localhost/centos:lc /bin/sh -c sleep 100000

**Describe the results you received:**
the container cannot be started successfully.

**Describe the results you expected:**
the container can be started successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
[root@lsf1x125 ~]# rpm -qa |grep podman
podman-1.6.4-11.module+el8.2.0+6368+cf16aa14.x86_64
cockpit-podman-12-1.module+el8.2.0+6368+cf16aa14.noarch
python-podman-api-1.2.0-0.2.gitd0a45fe.module+el8.2.0+6368+cf16aa14.noarch
podman-docker-1.6.4-11.module+el8.2.0+6368+cf16aa14.noarch
```
[root@lsf1x125 ~]# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64```

**Output of `podman info --debug`:**

```
[root@lsf1x125 ~]# podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
[root@lsf1x125 ~]# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 9adfe850ef954416ea5dd0438d428a60f2139473'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 5802659840
  MemTotal: 8189198336
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 4293836800
  SwapTotal: 4294963200
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: lsf1x125
  kernel: 4.18.0-193.el8.x86_64
  os: linux
  rootless: false
  uptime: 478h 13m 32.38s (Approximately 19.92 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```

podman --log-level debug run 

time="2020-06-23T23:08:53-04:00" level=debug msg="adding entry to /etc/passwd for non existent default user"
time="2020-06-23T23:08:53-04:00" level=debug msg="/etc/system-fips does not exist on host, not mounting FIPS mode secret"
time="2020-06-23T23:08:53-04:00" level=warning msg="User mount overriding libpod mount at \"/etc/passwd\""
time="2020-06-23T23:08:53-04:00" level=debug msg="set root propagation to \"rslave\""
time="2020-06-23T23:08:53-04:00" level=debug msg="Created OCI spec for container f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 at /podman/xianwu/.local/share/containers/storage/overlay-containers/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/userdata/config.json"
time="2020-06-23T23:08:53-04:00" level=debug msg="/usr/bin/conmon messages will be logged to syslog"
time="2020-06-23T23:08:53-04:00" level=debug msg="running conmon: /usr/bin/conmon" args="[--api-version 1 -c f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 -u f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 -r /usr/bin/runc -b /podman/xianwu/.local/share/containers/storage/overlay-containers/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/userdata -p /tmp/run-33857/overlay-containers/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/userdata/pidfile -l k8s-file:/podman/xianwu/.local/share/containers/storage/overlay-containers/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/userdata/ctr.log --exit-dir /tmp/run-33857/libpod/tmp/exits --socket-dir-path /tmp/run-33857/libpod/tmp/socket --log-level debug --syslog -t --conmon-pidfile /tmp/run-33857/overlay-containers/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /podman/xianwu/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /tmp/run-33857 --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /tmp/run-33857/libpod/tmp --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mount_program=/usr/bin/fuse-overlayfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09]"
time="2020-06-23T23:08:53-04:00" level=debug msg="Received: -1"
time="2020-06-23T23:08:53-04:00" level=debug msg="Cleaning up container f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09"
time="2020-06-23T23:08:53-04:00" level=debug msg="Network is already cleaned up, skipping..."
time="2020-06-23T23:08:53-04:00" level=debug msg="unmounted container \"f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09\""
time="2020-06-23T23:08:53-04:00" level=debug msg="Cleaning up container f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09"
time="2020-06-23T23:08:53-04:00" level=debug msg="Network is already cleaned up, skipping..."
time="2020-06-23T23:08:53-04:00" level=debug msg="Container f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 storage is already unmounted, skipping..."
time="2020-06-23T23:08:53-04:00" level=debug msg="Container f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 storage is already unmounted, skipping..."
time="2020-06-23T23:08:53-04:00" level=debug msg="ExitCode msg: \"time=\\\"2020-06-23t23:08:53-04:00\\\" level=error msg=\\\"container_linux.go:349: starting container process caused \\\\\\\"process_linux.go:333: applying cgroup configuration for process caused \\\\\\\\\\\\\\\"failed to write 3135182 to cgroup.procs: write /sys/fs/cgroup/memory/lsf/lsf1010/job.5093.3134788.1592968124/tsk.5093.3134998/child.3134999/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/cgroup.procs: permission denied\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\ncontainer_linux.go:349: starting container process caused \\\"process_linux.go:333: applying cgroup configuration for process caused \\\\\\\"failed to write 3135182 to cgroup.procs: write /sys/fs/cgroup/memory/lsf/lsf1010/job.5093.3134788.1592968124/tsk.5093.3134998/child.3134999/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/cgroup.procs: permission denied\\\\\\\"\\\": oci runtime permission denied error\""
time="2020-06-23T23:08:53-04:00" level=error msg="time=\"2020-06-23T23:08:53-04:00\" level=error msg=\"container_linux.go:349: starting container process caused \\\"process_linux.go:333: applying cgroup configuration for process caused \\\\\\\"failed to write 3135182 to cgroup.procs: write /sys/fs/cgroup/memory/lsf/lsf1010/job.5093.3134788.1592968124/tsk.5093.3134998/child.3134999/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/cgroup.procs: permission denied\\\\\\\"\\\"\"\ncontainer_linux.go:349: starting container process caused \"process_linux.go:333: applying cgroup configuration for process caused \\\"failed to write 3135182 to cgroup.procs: write /sys/fs/cgroup/memory/lsf/lsf1010/job.5093.3134788.1592968124/tsk.5093.3134998/child.3134999/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/cgroup.procs: permission denied\\\"\": OCI runtime permission denied error"

syslog.
Jun 23 23:08:52 lsf1x125 podman[3135152]: 2020-06-23 23:08:52.974609889 -0400 EDT m=+0.176317594 container create f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 (image=localhost/centos:lc, name=lsf1010.job.5093.task.1)
Jun 23 23:08:53 lsf1x125 conmon[3135170]: conmon f16ac56c08ec0f9db83a <ndebug>: failed to write to /proc/self/oom_score_adj: Permission denied
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: addr{sun_family=AF_UNIX, sun_path=/tmp/conmon-term.GZDPM0}
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: attach sock path: /tmp/run-33857/libpod/tmp/socket/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/attach
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: addr{sun_family=AF_UNIX, sun_path=/tmp/run-33857/libpod/tmp/socket/f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09/attach}
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: terminal_ctrl_fd: 13
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: winsz read side: 15, winsz write side: 15
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: about to accept from console_socket_fd: 4
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: about to recvfd from connfd: 11
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ninfo>: console = {.name = '(null)'; .fd = 0}
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <nwarn>: Failed to get console terminal settings
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <ndebug>: couldn't find cb for pid 3135182
Jun 23 23:08:53 lsf1x125 conmon[3135171]: conmon f16ac56c08ec0f9db83a <error>: Failed to create container: exit status 1
Jun 23 23:08:53 lsf1x125 podman[3135152]: 2020-06-23 23:08:53.155550904 -0400 EDT m=+0.357258663 container remove f16ac56c08ec0f9db83afd6760b28e6ed80be0e46daa26033c5d66965ac95b09 (image=localhost/centos:lc, name=lsf1010.job.5093.task.1)
Jun 23 23:08:53 lsf1x125 conmon[3134965]: conmon 64bf077d96306030a28c <ninfo>: container 3134976 exited with status 126
Jun 23 23:08:53 lsf1x125 conmon[3134965]: conmon 64bf077d96306030a28c <nwarn>: stdio_input read failed Input/output error
Jun 23 23:08:53 lsf1x125 podman[3134946]: 2020-06-23 23:08:53.194747819 -0400 EDT m=+4.917201363 container died 64bf077d96306030a28cc311d13e830d3928b963b9f7e61dd521eb32df239fcf (image=localhost/centos:lc, name=lsf1010.job.5093)
Jun 23 23:08:53 lsf1x125 podman[3134946]: 2020-06-23 23:08:53.271733721 -0400 EDT m=+4.994187240 container remove 64bf077d96306030a28cc311d13e830d3928b963b9f7e61dd521eb32df239fcf (image=localhost/centos:lc, name=lsf1010.job.5093)
Jun 23 23:08:55 lsf1x125 systemd[1048]: Started podman-3135241.scope.
^C
```


**Additional environment details (AWS, VirtualBox, physical, etc.):**
rhel 8.1 with podman 1.6.4

**Comment by baude** [comment]
should this be filed as a rh bugzilla?

**Comment by mheon** [comment]
This does not appear to be a Podman bug; I strongly suspect that whatever if configuring the cgroup you place Podman in, is doing so incorrectly, such that the OCI runtime does not have permission to create and modify a child cgroup for the container.

**Comment by coldbloodx** [comment]
@rhatdan @mheon @baude 

Something weird is that when I removed the "--userns=keep-id" the container can be started successfully.

Any input?

**Comment by rhatdan** [comment]
Well --userns  keep-id would require any privilege ops to happen through sudo, without it the container starts as root in the user namespace.
