### ISSUE TITLE
`podman auto-update` doesn't work with containers that managed by the pod's systemd unit file

### ISSUE THREAD

**Issue by floating-cat** [containers/libpod#6770]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I have a pod, and there are several containes in this pod. I use `podman generate systemd --new --name pod_name` to creates systems unit files.
But I can't use `podman auto-update` to update the containers in this pod.

**Steps to reproduce the issue:**

1. I use simliar commands below to create pod, containers, and systems unit files:

```bash
podman pod create --name pod_a
podman create --name caddy --pod pod_a --label io.containers.autoupdate=image caddy:latest
# create some other containers, omit here for simplification
podman generate systemd --new --files --name pod_a
# remove pod and containers here then use systemctl to manage/create them
podman pod rm pod_a
sudo cp {pod-pod_a,container-caddy}.service /etc/systemd/system/
sudo systemctl enable --now pod-pod_a
```

2. Some container's images release new versions.

3. Use the `podman auto-update`.

**Describe the results you received:**
Podman shows the errors below:

```
...
Writing manifest to image destination
Storing signatures
Error: 3 errors occurred:
        * error auto-updating container "f151413c69619c902d8b599f159a6b83826bd6f55ce78a9afbfbe16bbcfb321b": restarting systemd unit "container-caddy.service" failed: Operation refused, unit container-caddy.service may be requested by dependency only (it is configured to refuse manual start/stop).
...
```

It seems the podman tries to restart these container services here. It doesn't work because these containers' systems unit files are created by `podman generate systemd --new --files --name pod_a`. These systems unit files contain `RefuseManualStart=yes` and `RefuseManualStop=yes`. So the podman failed to restart them here.

**Describe the results you expected:**
The podman should stop the pod (it would also stop its containers), update the images, then start the pod service.
Or some other ways that can update the containers without any problem.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.0
API Version:  1
Go Version:   go1.14.4
Git Commit:   eec482cae3289ecaad45c602629657da7062ce9c
Built:        Sat Jun 20 20:30:13 2020
OS/Arch:      linux/amd64
```

**Additional information:**
I tried to add `io.containers.autoupdate=image` label in this pod instead of this pod's containers.
Then use `podman auto-update` to update the containers. But it doesn't work, too.

edited:
After some thought, this issue might be a feature instead of a bug. So feel free to change the label of the issue to the feature.
Also, it might be a good idea/feature to add the `io.containers.autoupdate` label for pod instead of the containers here. Then podman check this pod's containers version and update them.

**Comment by vrothberg** [comment]
Thanks for the report, I opened https://github.com/containers/libpod/pull/6771 to fix it.
