### ISSUE TITLE
bind mounted volumes with different user but matching groups fail

### ISSUE THREAD

**Issue by avikivity** [containers/libpod#6774]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a /var/cache/ccache that is owned by root:ccache:

```
$ ls -ld /var/cache/ccache/
drwxrws---. 2 root ccache 6 Feb 19 06:44 /var/cache/ccache/
```

I am not root, but a proud member of the ccache group:

```
$ groups
ccache wheel mock stapusr stapsys stapdev wireshark avi docker
```

I have full access to /var/cache/ccache on the host, but on the guest, no access:

```
$ podman run -v /var/cache/ccache:/var/cache/ccache --rm docker.io/fedora:32 ls -ld /var/cache/ccache
drwxrws---. 2 nobody nobody 6 Feb 19 04:44 /var/cache/ccache
$ podman run -v /var/cache/ccache:/var/cache/ccache --rm docker.io/fedora:32 ls -l /var/cache/ccache
ls: cannot open directory '/var/cache/ccache': Permission denied
```

The directory is owned by nobody (expected) but also group-owned by nobody, although I do have access to it via the ccache group.

**Steps to reproduce the issue:**

1. dnf -y install ccache; sudo usermod $(id -un) -a -G ccache; newgrp ccache

2. podman run -v /var/cache/ccache:/var/cache/ccache --rm docker.io/fedora:32 ls -l /var/cache/ccache

**Describe the results you received:**

ls: cannot open directory '/var/cache/ccache': Permission denied

**Describe the results you expected:**

A big blinking green box flashing "Access Granted" in a large font.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.9.3
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.2
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 12
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: avi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-300.fc32.x86_64
  memFree: 2705891328
  memTotal: 33541308416
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 4713586688
  swapTotal: 16869486592
  uptime: 1079h 3m 18.17s (Approximately 44.96 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/avi/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.1-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/avi/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 64
  runRoot: /run/user/1000/containers
  volumePath: /home/avi/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Container runtimes will, by default, drop all supplemental groups on entering the container (for security reasons).

The `crun` runtime, default on F32, allows disabling this behavior using the following flag to `podman run`: `--annotation run.oci.keep_original_groups=1`

(Though this does have some limitations of its own - we can't map the group into the user namespace because of permissions issues, so inside the container, files will appear to be owned by nobody:nobody)

**Comment by avikivity** [comment]
Thanks, I confirm it works for me.

Why is dropping the groups helpful? I expect that if I have access to a file on the host, and I mount that file in a container, then I have access to the file in the container (regardless of _how_ I have access to the file in the host).

**Comment by mheon** [comment]
I believe the concern is that we'll leak a privileged group from the host (like `wheel`, or something similar) that will allow the container to, if it escapes, escalate permissions (or just access more of the system than it would otherwise). A lot of the security proposition of rootless containers is that, because they run only as your user and your group, they have a very limited ability to affect the system even if a vulnerability lets a process escape the container, and adding more groups does weaken that proposition.

**Comment by avikivity** [comment]
Ok, closing.

**Comment by rhatdan** [comment]
Excellent answer https://github.com/containers/libpod/issues/6774#issuecomment-649637610 Looks like the makings of a short blog.
