### ISSUE TITLE
Publish does not work after upgrade

### ISSUE THREAD

**Issue by afbjorklund** [containers/libpod#6806]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It seems like something changed in the --publish syntax ?

> **--publish**, **-p**=_ip_:_hostPort_:_containerPort_ | _ip_::_containerPort_ | _hostPort_:_containerPort_ | _containerPort_
>
> Publish a container's port, or range of ports, to the host.
>
> Both hostPort and containerPort can be specified as a range of ports.
>
> When specifying ranges for both, the number of container ports in the range must match the number of host ports in the range.

It no longer seems to accept the _ip_::_containerPort_ variant.

**Steps to reproduce the issue:**

1. Use "podman run" with `--publish` parameteres

2.

3.

**Describe the results you received:**

$ sudo podman2 run --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 ubuntu:20.04
Error: must provide a non-empty container host port to publish

**Describe the results you expected:**

$ sudo podman1 run --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 ubuntu:20.04

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

1.8.2

2.0.0

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by afbjorklund** [comment]
As far as I can tell, it is either 7ac3d906b (or maybe 4e2a0b5b9)

Can't seem to find any unit tests for cmd/podman/common/util.go

**Comment by mheon** [comment]
Is that actually legal? Huh. Didn't think it was.

Should be a quick fix, let me grab this.

**Comment by mheon** [comment]
#6808 to fix

**Comment by afbjorklund** [comment]
Thanks! The idea is to pick a random port, where we are tunneling in those services:

* 8443: minikube (custom variant, 6443 kubernetes)
* 22: ssh
* 2376: docker
* 5000: registry

This for compatibility with both virtualbox (host-only network) and docker desktop VM

Otherwise one might as well have used the "front entrance" and used the CNI IP...

**Comment by mheon** [comment]
Reworked to choose a random port, thanks for pointing that out.

**Comment by skorhone** [comment]
@mheon Documentation should be updated to reflect this change. There's currently nothing about randomizing port for this operation.

There's also no mention, if you can specify combination of single container port and range of host ports. In this case, host port should be randomized from given range (if you wan't to follow docker's implementation)

**Comment by mheon** [comment]
I'll do the second bit in a separate PR.
