### ISSUE TITLE
(no reproducer): podman ps: Failed to tear down network namespace

### ISSUE THREAD

**Issue by edsantiago** [containers/libpod#736]
With active podman tests running in one window, I ran ps in another and got:
```
# podman ps                            
ERRO[0001] `iptables -t filter -D FORWARD -s 10.88.47.7 ! -o 10.88.47.7 -j ACCEPT` failed: iptables: Bad rule (does a matching rule exist in that chain?).           
  (exit status 1)                
ERRO[0001] Error deleting network: failed to Statfs "/var/run/netns/cni-1feaa09a-142e-aa09-393e-1f0763f4b560": no such file or directory                             
ERRO[0001] Failed to tear down network namespace for container cca9c4df53715ee73d9d5b95e94955b583529904883b6960df5e077d6fd31682: failed to Statfs "/var/run/netns/cni-1feaa09a-142e-aa09-393e-1f0763f4b560": no such file or directory
```
This looks related to #348 but I'm surprised to see it in `podman ps` and I think it's worth tracking separately: even if #348 isn't fixed, it might be a good idea to suppress this output in `ps`. 

This was just once. I haven't been able to reproduce it.

podman-0.5.2-1525700809.gitfaa8c3e.fc27.x86_64

**Comment by edsantiago** [comment]
Forgot to capture exit code. Sorry.

**Comment by mheon** [comment]
`ps` does perform an `updateContainer()` on every container to sync with the database prior to displaying output. Inside `updateContainer()`, there is logic to handle cases where a container's network namespace changed (IE, the container was stopped and its network namespace cleaned up). In these cases, we can't tell for sure if the network namespace was completely removed on the other side, so we attempt to remove it again locally. This seems to be the result of that failing because the network namespace was successfully removed, so we print a log of angry logging messages saying that our attempt to delete it up again failed. The good news is that none of this should cause an abnormal exit code, just a lot of error-level logging.

The other good news is that this should only happen on a very narrow timing condition. A container has to stop and be cleaned up in the time between `ps` retrieving its initial list of containers, and `ps` retrieving information on the container in question. Otherwise, the network namespace won't change internally, so no attempt to remove the old one and no error logs when we fail.

**Comment by edsantiago** [comment]
That makes sense, and is consistent with the (not 100%, but close) reproducer I now have:
```
window 1# podman run -i --name foo fedora sleep 60        ! the -i seems to be important

window 2# podman kill foo;podman ps;podman wait foo;podman rm foo                                                    
5af3500ab3bbf5bdf0ac96d01b4146bfb373ca180fe34ae39409efed5f0e0040  
ERRO[0000] `iptables -t filter -D FORWARD -s 10.88.47.83 ! -o 10.88.47.83 -j ACCEPT` failed: iptables: Bad rule (does a matching rule exist in that chain?).
  (exit status 1)
ERRO[0000] Error deleting network: failed to Statfs "/var/run/netns/cni-8df8f08e-256d-6917-67ea-9656513f6c04": no such file or directory
ERRO[0000] Failed to tear down network namespace for container 5af3500ab3bbf5bdf0ac96d01b4146bfb373ca180fe34ae39409efed5f0e0040: failed to Statfs "/var/run/netns/cni-8df8f08e-256d-6917-67ea-9656513f6c04": no such file or directory
137
5af3500ab3bbf5bdf0ac96d01b4146bfb373ca180fe34ae39409efed5f0e0040
```
From a dumb user's perspective, I find it kind of alarming to see messages like this from what I expect to be a query-information-only command.

**Comment by edsantiago** [comment]
Oh - and exit code is indeed 0.

**Comment by mheon** [comment]
The problem with dropping the error logging down would be that we share the removal code with normal cleanup, and we probably want to actually log angry errors if cleanup fails in default case.
I suppose we could save the errors in `teardownNetNs()` instead of logging them, and return an error that we can log at various degrees of severity depending on how we called it.

**Comment by edsantiago** [comment]
I saw another message this morning in a different test run; I haven't been able to reproduce it but wonder if it's related?
```
# podman kill simple_l7j8
# podman wait simple_l7j8
unable to find container simple_l7j8: error joining network namespace for container cb267e5f18b7a39354bf9ab717c9f1694ae0b1ba1774f4e51be084f1e6180b95: error retrieving network namespace at /var/run/netns/cni-0fd25158-8374-8a3f-7939-a62c624b0426: unknown FS magic on "/var/run/netns/cni-0fd25158-8374-8a3f-7939-a62c624b0426": 1021994
```
This one was not a warning: it exited 125.

Reviewing logs of past runs I see it only once before, so it's not surprising that I can't reproduce it manually. Does this look like it could be related?

**Comment by mheon** [comment]
No, I think that's separate. Was that a test with user namespaces, by any chance?

**Comment by edsantiago** [comment]
No user namespaces involved.

**Comment by mheon** [comment]
We merged userns-related changes to network ns handling recently, so I was hoping that might be it. Ah well, no easy candidate for what's going on then.

**Comment by edsantiago** [comment]
Seen again in podman-0.6.4-1.gitd5beb2f.fc28. No userns. As before, no reproducer.
```
time podman ps -a
ERRO[0000] `iptables -t filter -D FORWARD -s 10.88.9.132 ! -o 10.88.9.132 -j ACCEPT` failed: iptables: Bad rule (does a matching rule exist in that chain?).
  (exit status 1) 
ERRO[0000] Error deleting network: failed to Statfs "/var/run/netns/cni-90d59231-a16d-5a38-9926-547fb5e92ff6": no such file or directory 
ERRO[0000] Failed to tear down network namespace for container 2c603c62175e2d98e6c5ecfd0ba99a63d84678e46b2a19e7a6b69c5e9dae1271: failed to Statfs "/var/run/netns/cni-90d59231-a16d-5a38-9926-547fb5e92ff6": no such file or directory 
CONTAINER ID   IMAGE                                          COMMAND                  CREATED          STATUS                              PORTS   NAMES
2c603c62175e   registry.access.redhat.com/rhel7/rhel:latest   bash -c for NUM in ...   14 seconds ago   Exited (0) Less than a second ago           run_sigproxy_ttyoff-test_6XTF
```

**Comment by mheon** [comment]
The current netns code in CNI that we're using has been deprecated. Our CNI maintainers recommended that we include (not vendor) their test code for creating network namespaces and modify it as we see fit. Unclear what the timeframe is on this change, but it ought to resolve our issues when it happens as we can rewrite the netns removal code to account for this.

**Comment by rhatdan** [comment]
@baude Could you take care of copying this code into ours and fixing this issue?

**Comment by mheon** [comment]
I think we can leave this be for now, given we just updated CNI and the deprecated code is still there. Unless we really want to fix the warnings, in which case we'd have to copy in the netns library?

**Comment by baude** [comment]
IMHO we have enough of our libs to tend after.  I'd prefer to not add another...

**Comment by edsantiago** [comment]
I'd like to encourage you to consider this from the perspective of end users. I've been seeing these warnings for months, and they *still* cost me time and energy to process every time I see them: Sometimes (often) it's a docker-autotest failure because the tests expect nothing on stderr; sometimes it's me running manual commands. *Every time* this happens I have to look at the error, confirm from memory that it's one of the Usual Ones Which I Can Ignore, but then also look closer to make sure there aren't any other errors being masked by this one. That's me, doing this for a living for months on end. How will this look to the potentially thousands of people being introduced to podman in the next few months? Every one of these thousands will have to spend time websearching for the error, finding this page, and realizing we don't care enough about their time. That adds up to a lot of lost productivity and possibly a lot of ill will.

**Comment by mheon** [comment]
@baude Want me to take this one, considering you'll be on vacation?

**Comment by rhatdan** [comment]
Yes we should take this in or build a new library on containers and vendor it in.  Main thing that I believe it needs is to have constants so we can start ignoring some errors.  Like network does not exist.

**Comment by baude** [comment]
@mheon sure, plus i dont really follow whats going on here.

**Comment by vrothberg** [comment]
@mheon what's the current state of this issue?

**Comment by mheon** [comment]
This one should be fixed, updating to a more recent
containernetworking/plugins to split the delete and close operations on
network namespaces resolved the issue.
