### ISSUE TITLE
Podman hangs after 'logout' in container with FUSE mount

### ISSUE THREAD

**Issue by mheon** [containers/libpod#794]
Reported via IRC:

Podman will hang after 'logout' is run in a container that has a mounted FUSE filesystem. Exec will fail with `exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"`. Podman attach will not retrieve any output, though you can still type into the container's console.

Reproduce with:
1. Launch podman with `pkexec podman run -it --priviledged=true --device=/dev/sdd1 --device=/dev/fuse debian su -` (will probably need to modify the device line - maybe a loopback with a FUSE fs on it?)
2. In the container, run `apt-get update; apt-get install exfat-fuse"; mount command: "cd /media; mkdir test; mount /dev/sdd1 test` (again, device will likely not be /dev/sdd1 if you want to reproduce)
3. In the container, run `logout`

I suspect that a FUSE mount isn't actually necessary to reproduce this, and any mount will be sufficient, but I haven't verified that yet.

**Comment by mheon** [comment]
Correction, just using ordinary mounts doesn't seem to trigger this - `logout` causes the container to exit, and you can exec into the container and remove it with `rm -f` without issue (even with the mount not being unmounted before exiting)

**Comment by mheon** [comment]
@rhatdan Potentially - the container is privileged, but this could be a more general selinux issue.

**Comment by rhatdan** [comment]
The mount should be cleaned up since the mount namespace went away.

**Comment by rhatdan** [comment]
@mheon Do we still have this issue?

**Comment by vrothberg** [comment]
Closing. Feel free to re-open if the issue is still present or reoccurs.
