### ISSUE TITLE
Podman ps and podman port with other container's network namespaces

### ISSUE THREAD

**Issue by mheon** [containers/libpod#846]
If a container is created with `--net=container`, when `podman ps` and `podman port` are run on the container, we won't see any ports (as the ports are bound in the network namespace of another container). We should account for this and display the ports of the other container here, as the container does have ports forwarded to it.

**Comment by vrothberg** [comment]
@baude, @mheon : I think we can fix this along with some other networking work (e.g., POD issues).

**Comment by mheon** [comment]
Agree - this is very important for pod work

**Comment by mheon** [comment]
I think Port may be partially fixed already

**Comment by rhatdan** [comment]
What is the latest on this issue?

**Comment by mheon** [comment]
Fairly certain this is still broken
