### ISSUE TITLE
podman inspect of image shows a lot less then buildah inspect of an image.

### ISSUE THREAD

**Issue by rhatdan** [containers/libpod#860]
[buildah_inspect.onbuild.txt](https://github.com/projectatomic/libpod/files/2059183/buildah_inspect.onbuild.txt)
[podman_inspect.onbuild.txt](https://github.com/projectatomic/libpod/files/2059184/podman_inspect.onbuild.txt)

**Comment by rhatdan** [comment]
@haircommander PTAL

**Comment by baude** [comment]
@rhatdan how about we add:

* history
* namespaceoptions
* configurenetwork
* idmappingoptions
* defaultcapbilities
* addcapabilities
* dropcapabilities

**Comment by mheon** [comment]
Images don't specify a lot of those, though - that seems specific to the buildah container?

**Comment by vrothberg** [comment]
Ping.  Is this still a desired change?

**Comment by TomSweeneyRedHat** [comment]
I think so, most likely waiting in stealth to attack @haircommander when he returns early next year.

**Comment by rhatdan** [comment]
@QiWang19 Could you take a look at this?

**Comment by QiWang19** [comment]
@rhatdan :ok_hand:
