### ISSUE TITLE
Split Linux-specific portions of Container struct into separate struct

### ISSUE THREAD

**Issue by mheon** [containers/libpod#892]
We are looking into potentially supporting multiple platforms. As a first step for this, we should investigate splitting the Container struct (and potentially Pod struct) to hold Linux-specific fields in a separate structure. We'd embed a pointer that that structure in Container, so when we develop support for extra platforms (OS X, Windows, etc), we could embed a pointer to that struct as well, and then have only one of those platform-specific structs in use per-container.

EX:
```
struct ContainerConfig {
    linuxConfig *LinuxConfig
    osxConfig *OSXConfig
    windowsConfig *WindowsConfig
}
```

**Comment by wking** [comment]
> As a first step for this, we should investigate splitting the Container struct (and potentially Pod struct) to hold Linux-specific fields in a separate structure.

At least at the config level, this feels a lot like [the existing OCI runtime-spec `Spec` structure][1].  Is there a reason we aren't just using that directly (with a separate field for our additional configurations like [`ConmonPidFile`][2]?  Defining our own (for example) [`CgroupParent`][3] only to translate into the OCI structure later seems like more trouble than its worth.  And with the OCI-specified settings handled by the already-cross-platform OCI structure, we would have fewer OS-specific, libpod-specified settings that would need to be shifted down into OS-specific sub-structures.

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/specs-go/config.go#L5-L28
[2]: https://github.com/projectatomic/libpod/blob/v0.6.1/pkg/spec/createconfig.go#L74
[3]: https://github.com/projectatomic/libpod/blob/v0.6.1/pkg/spec/createconfig.go#L75

**Comment by mheon** [comment]
@wking CgroupParent is mostly because we'll be creating our own CGroup hierarchy (make a parent for the container and `conmon` to share), so we can't directly use the container's CGroup. All the things in `ContainerConfig` should be similar cases - they're things either not found in the spec, or sufficiently different in meaning from what's in the spec to justify storing separately. If there is actual overlap, I'd love to remove it :smile: 

This is basically identical to the method used for separating platform-specific info in the OCI spec, though, and deliberately so.

**Comment by wking** [comment]
> All the things in `ContainerConfig` should be similar cases - they're things either not found in the spec, or sufficiently different in meaning from what's in the spec to justify storing separately.

Oops, I'd been confusing libpod's `CgroupParent` with [the OCI's `cgroupsPath`][1] (which is not a parent).  So yeah, you're probably already doing what I'd been trying to suggest, and sorry for the noise ;).

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config-linux.md#cgroups-path

**Comment by wking** [comment]
Won't we need something like what we did for `State` (#1033) here?

**Comment by mheon** [comment]
Yeah, we will at some point need to split `Config` similarly.
And probably further split `State` - there's a lot of Linux-specific things sitting in the common `State` now.

**Comment by baude** [comment]
CLosing for now ... please repoen as needed
