### ISSUE TITLE
no network traffic forwarded when using `podman run` on Atomic Host systems

### ISSUE THREAD

**Issue by miabbott** [containers/libpod#973]
/kind bug

**Description**

There is no network access from inside the containers when doing `podman run` on an Atomic Host system.

**Steps to reproduce the issue:**

1.  Boot F28AH or RHELAH
2.  podman run --rm docker.io/alpine ping -c 3 1.1.1.1

**Describe the results you received:**

```
# podman run --rm docker.io/alpine ping -c 3 1.1.1.1                                                                                                                          
PING 1.1.1.1 (1.1.1.1): 56 data bytes

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```

**Describe the results you expected:**

```
# podman run --rm --net=host docker.io/alpine ping -c 3 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=49 time=10.940 ms
64 bytes from 1.1.1.1: seq=1 ttl=49 time=10.927 ms
64 bytes from 1.1.1.1: seq=2 ttl=49 time=10.994 ms

--- 1.1.1.1 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Only appears to affect Atomic Host systems.

**Output of `podman version`:**

```
# podman version
Version:       0.5.3
Go Version:    go1.10.2
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
# podman info
host:
  MemFree: 707727360
  MemTotal: 2089435136
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 1
  hostname: micah-f28ah-vm0620a
  kernel: 4.16.11-300.fc28.x86_64
  os: linux
  uptime: 1h 50m 10.13s (Approximately 0.04 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 5
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 6
  RunRoot: /var/run/containers/storage

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Testing was done with VMs in OpenStack environment.

**Comment by miabbott** [comment]
See downstream bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1592932

https://bugzilla.redhat.com/show_bug.cgi?id=1593419


Additionally, this can be reproduced with git master on Atomic Hosts

**Comment by mheon** [comment]
We suspect this is tied to https://github.com/containernetworking/plugins/pull/75

**Comment by miabbott** [comment]
Ah of course...I've actually linked that in the downstream bugs  ¯\_(ツ)_/¯

**Comment by mheon** [comment]
@miabbott This has come up before, so I have the link very handy to provide for cases like this...

The good news is that the blockers upstream are hopefully close to done, so we should be seeing forward progress on it soon, hopefully.

**Comment by baude** [comment]
I believe this is fixed. re-open if not
